= 
cmcatee-MSFT

== Office 365 is now Microsoft 365

We’ve changed some of our Office 365 and Microsoft 365 subscription
names. You don’t need to do a thing. Your services, apps and features
are staying the same, along with the price of your subscription. Your
subscription name will automatically update in the Microsoft 365 admin
center and your billing statements will update on or after April 21,
2020.

* *Office 365 Business Essentials* is now *Microsoft 365 Business Basic*
* *Office 365 Business Premium* is now *Microsoft 365 Business Standard*
* *Microsoft 365 Business* is now *Microsoft 365 Business Premium*
* *Office 365 Business* is now *Microsoft 365 Apps for business*
* *Office 365 ProPlus* is now *Microsoft 365 Apps for enterprise*

https://go.microsoft.com/fwlink/?linkid=2120533[Learn more!]

=== Related content

link:../commerce/index.yml[Subscriptions and billing] (link page) +
link:../commerce/billing-and-payments/view-your-bill-or-invoice.md[View
your bill or invoice] (article) +
link:../commerce/billing-and-payments/pay-for-your-subscription.md[Paying
for your subscription] (article) +
link:../commerce/billing-and-payments/change-your-billing-addresses.md[Change
your billing addresses] (article)
