= Azure integration with Microsoft 365
:audience: Admin
:author: kelleyvice-msft
:description: Integrate Microsoft 365 with Azure AD if you want password sync or single sign-on with your on-premises environment.
:f1.keywords: ["CSH"]
:manager: scotv
:ms.assetid: a5efce5d-9c9c-4190-b61b-fd273c1d425f
:ms.author: kvice
:ms.collection: ["Ent_O365", "M365-identity-device-management"]
:ms.custom: ["Adm_O365", "seo-marvel-apr2020"]
:ms.localizationpriority: medium
:ms.service: microsoft-365-enterprise
:ms.topic: overview
:search.appverid: ["MET150", "MOE150", "MED150", "BCS160"]

== Azure integration with Microsoft 365

_This article applies to both Microsoft 365 Enterprise and Office 365 Enterprise._

Microsoft 365 uses Azure Active Directory (Azure AD) to manage user identities behind the scenes.
Your Microsoft 365 subscription includes a free Azure AD subscription so that you can integrate your on-premises Active Directory Domain Services (AD DS) to synchronize user accounts and passwords or set up single sign-on.
You can also purchase advanced features to better manage your accounts.

Azure AD also offers other functionality, like managing integrated apps, that you can use to extend and customize your Microsoft 365 subscriptions.

You can use the Azure AD deployment advisors for a guided setup and configuration experience in the Microsoft 365 admin center (you must be signed in to Microsoft 365):

* https://aka.ms/aadconnectpwsync[Azure AD Connect advisor]
* https://aka.ms/adfsguidance[AD FS deployment advisor]
* https://aka.ms/aadpguidance[Azure AD setup guide]

=== Azure AD editions and Microsoft 365 identity management

If you have a paid subscription to Microsoft 365, you also have a free Azure AD subscription.
You can use Azure AD to create and manage user and group accounts.
To activate this subscription, you have to complete a one-time registration.
Afterward, you can access Azure AD from your Microsoft 365 admin center.

For instructions to register your free Azure AD subscription, see xref:../compliance/use-your-free-azure-ad-subscription-in-office-365.adoc[use your free Azure AD subscription].
Don't go directly to azure.microsoft.com to sign up or you'll end up with a trial or paid subscription to Microsoft Azure that is separate from your free Azure AD subscription with Microsoft 365.

With the free subscription you can synchronize with on-premises directories, set up single sign-on, and synchronize with many software as service applications, such as Salesforce, DropBox, and many more.

If you want enhanced AD DS functionality, bi-directional synchronization, and other management capabilities, you can upgrade your free subscription to a paid premium subscription.
For the details, see https://azure.microsoft.com/pricing/details/active-directory/[Azure Active Directory editions].

For more information about Microsoft 365 and Azure AD, see xref:deploy-identity-solution-identity-model.adoc[Microsoft 365 identity models].

=== Extend the capabilities of your Microsoft 365 tenant

|===
| *Feature* | *Description*

| Integrated apps  +
| You can grant individual apps access to your Microsoft 365 data, such as mail, calendars, contacts, users, groups, files, and folders.
You can also authorize these apps at *Azure AD DC admin*, or *Global admin* level and make them available to your entire company by registering the apps in Azure AD.
For more information, see xref:integrated-apps-and-azure-ads.adoc[Integrated Apps and Azure AD for Microsoft 365 administrators].
+ For more information, see link:/microsoft-365/admin/add-users/about-admin-roles?[About admin roles].
+ Also see link:/azure/active-directory/manage-apps/what-is-single-sign-on[Single sign-on].
+

| Power Apps  +
| Power Apps are focused apps for mobile devices that can connect to your existing data sources like SharePoint lists and other data apps.
See https://support.office.com/article/9338b2d2-67ac-4b81-8e67-97da27e5e9ab[Create a Power App for a list in SharePoint Online] and the https://powerapps.microsoft.com/[Power Apps page] for details.
+
|===

=== See also

xref:microsoft-365-overview.adoc[Microsoft 365 Enterprise overview]
