= 
JoanneHendrickson

== Step 5: Identity mapping

This is Step 5 in a solution designed to complete a Cross-tenant
OneDrive migration. To learn more, see
link:cross-tenant-onedrive-migration.md[Cross-tenant OneDrive migration
overview].

* Step 1: link:cross-tenant-onedrive-migration-step1.md[Connect to the
source and the target tenants]
* Step 2: link:cross-tenant-onedrive-migration-step2.md[Establish trust
between the source and the target tenant]
* Step 3: link:cross-tenant-onedrive-migration-step3.md[Verify trust has
been established]
* Step 4: link:cross-tenant-onedrive-migration-step4.md[Pre-create users
and groups]
* *Step 5: link:cross-tenant-onedrive-migration-step5.md[Prepare
identity mapping]*
* Step 6: link:cross-tenant-onedrive-migration-step6.md[Start a
Cross-tenant OneDrive migration]
* Step 7: link:cross-tenant-onedrive-migration-step7.md[Post migration
steps]

=== Create the identity mapping file

In this step of the cross-tenant migration process, you’re going to
create a single CSV (comma separated values) file that contains the
mapping of the users and groups on the source tenant to their
corresponding users and groups on the target tenant.

We recommend that you take the time to verify your mappings, ensuring
they’re accurate before starting any migrations to the target tenant.

There’s a one-to-one relationship in the identity mapping file. You
can’t map the same user to multiple users in the target tenant. For
example, if you have instances where the admin is the owner of multiple
OneDrive accounts, the ownership must be changed to match the
corresponding user you wish to migrate from Source to Target. If you
don’t, those account files won’t migrate.

*Example:* In this example, the admin owns multiple OneDrive accounts.

[cols=",",options="header",]
|===
|Source Tenant Owner |Target Tenant User
|admin@source.com |new.userA@target.com
|admin@source.com |new.userB@target.com
|admin@source.com |new.userC@target.com
|===

Cross-tenant migration supports this scenario:

*Example*:

[cols=",",options="header",]
|===
|Source Tenant Owner |Target Tenant User
|userA@source.com |new.userA@target.com
|userB@source.com |new.userB@target.com
|userC@source.com |new.userC@target.com
|===

==== Create the CSV file

There are six columns needed in your CSV file. The first three are your
source values, each providing detail about where your data is currently
located. The remaining three columns are the corresponding info on the
target tenant. All six columns must be accounted for in the file. Create
your file in Excel and save it as a .csv file.

Users and groups are included in the same file. Depending on whether
it’s a user or group, what you enter in the column is different. In each
of the columns enter values as shown in the examples. *Do NOT include
column headings.*

[cols=",,",options="header",]
|===
|Column |User |Group
|1 |User |Group
|2 |SourceTenantCompanyID |SourceTenantCompanyID
|3 |SourceUserUpn |SourceGroupObjectID
|4 |TargetUserUpn |TargetGroupObjectID
|5 |TargetUserEmail |GroupName
|6 |UserType |GroupType
|===

____
[!IMPORTANT] *Do NOT include column headings in your CSV file.* In the
examples below we include them for illustrative purposes only.
____

*Users*. Enter your values as shown in this example for guests:

:::image type=``content''
source=``../media/cross-tenant-migration/t2t-onedrive-csv-mapping-users-columns.png''
alt-text=``format to use for mapping users'':::

:::image type=``content''
source=``../media/cross-tenant-migration/t2t-onedrive-csv-mapping-users-example.png''
alt-text=``example of csv for users'':::

*Groups*. Enter your values as shown in this example for guests:
:::image type=``content''
source=``../media/cross-tenant-migration/t2t-onedrive-csv-mapping-groups-columns.png''
alt-text=``format for csv file for groups'':::

_Example_:

:::image type=``content''
source=``../media/cross-tenant-migration/t2t-onedrive-csv-group-example.png''
alt-text=``example of adding groups to csv file'':::

*Guest users*. You can map guest accounts in the source tenant to member
accounts in the target tenant. You can also map a guest account in the
source to a guest account in the target if the guest has been previously
created. Enter your values as shown in this example for guests:

:::image type=``content''
source=``../media/cross-tenant-migration/t2t-onedrive-csv-mapping-users-guests.png''
alt-text=``csv example when mapping a guest to a member'':::

:::image type=``content''
source=``../media/cross-tenant-migration/t2t-onedrive-identity-mapping-example-guest-to-guest.png''
alt-text=``csv example when mapping a guest to a guest'':::

*Multiple users and groups in a CSV file:*

_Example:_

:::image type=``content''
source=``../media/cross-tenant-migration/t2t-onedrive-migration-csv-users-groups.png''
alt-text=``example of both users and groups in mapping file'':::

=== Obtain the source tenant company ID

To obtain Source Tenant Company ID:

[arabic]
. Sign in as Admin to your https://ms.portal.azure.com/[Azure portal]
. Select or Search for *Azure Active Directory*.
. Scroll down on the left-hand panel and select *Properties*.
. Locate the *Tenant ID Field*. The required Tenant ID will be in that
box.

:::image type=``content''
source=``../media/cross-tenant-migration/t2t-onedrive-azure-tenant-id.png''
alt-text=``getting the source tenant ID'':::

=== To obtain source group object ID:

[arabic]
. Sign in to source tenant as Admin to https://ms.portal.azure.com[Azure
Groups].
. Search for your required group(s).
. Select the required Group instance and then *Copy to clipboard*. Paste
this value in the sourceGroupObjectId column of your mapping CSV file.
. If you have multiple Groups to map, then repeat these steps for each
group.

:::image type=``content''
source=``../media/cross-tenant-migration/t2t-onedrive-source-group-objectid.png''
alt-text=``getting the source group object ID'':::

==== To obtain target group object ID:

[arabic]
. Sign in to Target tenant as Admin to https://ms.portal.azure.com[Azure
Groups]
. Search for your required group(s).
. Select the required group instance and then *Copy to clipboard*. Paste
this value in the targetGroupObjectId column of your mapping CSV file.
. If you have multiple groups to map, then repeat the above process to
obtain those specific targetGroupObjectId’s.
. For the GroupName, use the same ID as the _TargetGroupObjectId_ you
obtained.

:::image type=``content''
source=``../media/cross-tenant-migration/t2t-onedrive-target-group-objectid.png''
alt-text=``how to get the target object ID'':::

=== Upload the identity map

Once the identity mapping file has been prepared, the SharePoint
Administrator on the target tenant uploads the file to SharePoint. This
will allow identity mapping to occur automatically as part of the
cross-tenant migration.

____
[!IMPORTANT] Before you run the _Add-SPOTenantIdentityMap
-IdentityMapPath_ command, save and close the identitymap.csv file on
your Desktop/OneDrive/SharePoint. If the file remains open, you will
receive the following error.

_Add-SPOTenantIdentityMap: The process cannot access the file
`C:-Identity-Map.csv' because it is being used by another process._
____

[arabic]
. To upload the identity Map on the target tenant, run the following
command. For _-IdentityMapPath_, provide the full path and filename of
the identity mapping CSV file.

[source,powershell]
----
Add-SPOTenantIdentityMap -IdentityMapPath <identitymap.csv>
----

____
[!IMPORTANT] If you make or need to make any changes to your Identity
Map during the lifecycle of the migration you must run the
`Add-SPOTenantIdentityMap -IdentityMapPath <identitymap.csv>` command
*every time* a change is made to ensure those changes are applied to the
migration.
____

Uploading any new identity map will overwrite the current one. Make sure
that any revision or addition includes ALL users and groups for the full
migration. Your identity map should always include everyone you’re
wanting to migrate.

To look at the mapping entries in the identity mapping file for a
particular user, use the command _Get-SPOTenantIdentityMappingUser_ with
Field as _SourceUserKey_ and Value as the UPN of the user you are
moving.

*Example:*

[source,powershell]
----
get-spoTenantIdentityMappingUser -Field SourceUserKey -Value usera@Contoso.onmicrosoft.com
----

=== Verify cross-tenant compatibility status

Before starting any cross-tenant migrations, make sure that both
SharePoint database schemas are up to date and compatible between source
and target.

To perform this check, run the below cmdlet on your Source tenant.

[source,powershell]
----
Get-SPOCrossTenantCompatibilityStatus -PartnerCrossTenantHostURL [Target tenant hostname]

Get-SPOCrossTenantCompatibilityStatus -PartnerCrossTenantHostURL https://m365x12395529-my.sharepoint.com
----

* If the tenant status shows as *Compatible* or *Warning*, you can then
proceed with the next step of starting cross-tenant migrations.
* If the tenant status shows as *Incompatible*, your tenants will need
to be patched/updated to ensure compatibility.

[cols=",",options="header",]
|===
|Status |Can proceed with migration
|Compatible |Yes
|Warning |Yes
|Incompatible |No
|===

____
[!NOTE] We recommend waiting a period of 48 hours. If your tenants are
still reporting as _incompatible_, contact support.

We recommend performing the compatibility status check on a frequent
basis and prior to starting ANY instances of cross tenant migrations. If
the tenants are not compatible, this can result in cross-tenant
migrations failing.
____

=== Step 6: link:cross-tenant-onedrive-migration-step6.md[Start a OneDrive cross-tenant migration]
