= 
JoanneHendrickson

== Step 7: Post migration steps

This is Step 7 in a solution designed to complete a Cross-tenant
OneDrive migration. To learn more, see
link:cross-tenant-onedrive-migration.md[Cross-tenant OneDrive migration
overview].

* Step 1: link:cross-tenant-onedrive-migration-step1.md[Connect to the
source and the target tenants]
* Step 2: link:cross-tenant-onedrive-migration-step2.md[Establish trust
between the source and the target tenant]
* Step 3: link:cross-tenant-onedrive-migration-step3.md[Verify trust has
been established]
* Step 4: link:cross-tenant-onedrive-migration-step4.md[Pre-create users
and groups] +
* Step 5: link:cross-tenant-onedrive-migration-step5.md[Prepare identity
mapping]
* Step 6: link:cross-tenant-onedrive-migration-step6.md[Start a
Cross-tenant OneDrive migration]
* *Step 7: link:cross-tenant-onedrive-migration-step7.md[Post migration
steps]*

=== Removing trust relationship

____
[!IMPORTANT] Ensure you remove the Trust Relationship on both source and
target tenants before your source tenant licenses expire. Once the
licenses expire, the trust removal command will not work on source.
____

[arabic]
. On the source tenant, run this command to remove the trust
relationship between Source and Target tenant.
+
[source,powershell]
----
Remove-SPOCrossTenantRelationship -Scenario MnA -PartnerRole Target -PartnerCrossTenantHostUrl <TARGETCrossTenantHostUrl>
----
. On the target tenant, run this command to remove the trust
relationship between the target and source tenant.
+
[source,powershell]
----
Remove-SPOCrossTenantRelationship -Scenario MnA -PartnerRole Target -PartnerCrossTenantHostUrl <TARGETCrossTenantHostUrl>
----

==== Parameter definitions

[width="100%",cols="50%,50%",options="header",]
|===
|Parameter |Definition
|PartnerRole |Roles of the partner tenant you’re establishing trust
with. Use _source_ if partner tenant is the source of the OneDrive
migrations, and _target_ if the partner tenant is the destination.

|PartnerCrossTenantHostURL |The cross-tenant host URL of the partner
tenant. The partner tenant can determine this for you by running:
_Get-SPOCrossTenantHostURL_ on each of the tenants.
|===

=== Other post migration steps

Once the migration is complete, OneDrive users must sign in using their
new identity and resync their files to their devices on the target
tenant.

==== OneDrive for Business

With their new credentials, have users sign in to OneDrive using the
Microsoft 365 app launcher or a web browser.

==== Permissions on OneDrive content

Users with permission to access OneDrive content will continue to be
able to access it, provided they were included in the identity mapping
file

==== OneDrive Sync Client

The user must sign in to the *OneDrive Sync Client* and their new
OneDrive location using their new identity. Once you’ve completed that
step, the files and folders will begin resyncing to the device.

==== Sharing Links

The existing shared links for the migrated files will automatically
redirect to the new target location.
