= 
dstrome

== Exchange 2007 end of support roadmap

_This article applies to both Microsoft 365 Enterprise and Office 365
Enterprise._

Exchange Server 2007 reached end of support in April 2017. If you
haven’t started your migration from Exchange 2007 to Microsoft 365,
Office 365, or Exchange 2016, now’s the time to start planning.

=== What does _end of support_ mean?

Exchange Server, like almost all Microsoft products, has a support
lifecycle during which we provide new features, bug fixes, security
fixes, and so on. This lifecycle typically lasts for 10 years from the
product’s initial release. The end of this lifecycle is known as the
product’s end of support. Since Exchange 2007 reached its end of support
on April 11, 2017, Microsoft no longer provides:

* Technical support for problems that may occur.
* Bug fixes for issues that may impact the stability and usability of
the server.
* Security fixes for vulnerabilities that may make the server vulnerable
to security breaches.
* Time zone updates.

Your installation of Exchange 2007 will continue to run after the
end-of-support date. But because there are no new updates or support, we
strongly recommend that you migrate from Exchange 2007 as soon as
possible.

For more information about Office 2007 servers nearing the end of
support, see link:upgrade-from-office-2007-servers-and-products.md[Plan
your upgrade from Office 2007 servers and products].

=== What are my options?

You can:

* Migrate to Microsoft 365 by using cutover, staged, or hybrid
migration.
* Migrate your Exchange 2007 servers to a newer version of Exchange on
your on-premises servers.

The following sections explore each option in more detail.

==== Migrate to Microsoft 365

Migrating your email to Microsoft 365 is the best and simplest option to
help retire your Exchange 2007 deployment. With a migration to Microsoft
365, you can make a single hop from 10-year-old technology to
state-of-the-art features, including:

* Compliance capabilities such as Retention Policies, In-Place and
Litigation Hold, in-place eDiscovery, and more
* Microsoft 365 Groups
* Focused Inbox
* MyAnalytics
* REST APIs for programmatic access to email, calendars, contacts, and
so on

Microsoft 365 also gets new features and experiences first, so you and
your users can usually start using them right away. And you won’t have
to worry about:

* Purchasing and maintaining hardware.
* Paying to heat and cool your servers.
* Keeping up to date on security, product, and time-zone fixes.
* Maintaining storage and software to support compliance requirements.
* Upgrading to a new version of Exchange. With Microsoft 365, you’re
always on the latest version of Exchange.

===== How should I migrate to Microsoft 365?

You have a few migration options. You need to consider a few things,
including:

* The number of seats or mailboxes you need to move.
* How long you want the migration to last.
* Whether you need seamless integration between your on-premises
installation and Microsoft 365 during the migration.

This table shows your migration options and the most important factors
that determine which method to use:

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Migration option |Organization size |Duration
|Cutover migration |Fewer than 150 seats |A week or less

|Staged migration |More than 150 seats |A few weeks

|Full hybrid migration |Several hundred to thousands of seats |A few
months or more
|===

The following sections provide an overview of these methods. For more
detail, see
https://support.office.com/article/Decide-on-a-migration-path-0d4f2396-9cef-43b8-9bd6-306d01df1e27[Decide
on a migration path].

===== Cutover migration

In a cutover migration, you migrate all your mailboxes, distribution
groups, contacts, and so on, to Microsoft 365 at a preselected date and
time. After the migration is complete, you shut down your on-premises
Exchange servers and start using Microsoft 365 exclusively.

Cutover migration is great for small organizations that don’t have many
mailboxes, want to get to Microsoft 365 quickly, and don’t want to deal
with some of the complexities of the other methods. But it should be
completed in a week or less, and it requires users to reconfigure their
Outlook profiles. Cutover migration can handle up to 2,000 mailboxes,
but we strongly recommend you use it to migrate a maximum of 150
mailboxes. If you try to migrate more, you could run out of time to
transfer all the mailboxes before your deadline, and your IT support
staff may get overwhelmed with requests to help users reconfigure
Outlook.

If you’re thinking about doing a cutover migration, here are things to
consider:

* Microsoft 365 will need to connect to your Exchange 2007 servers using
Outlook Anywhere over TCP port 443.
* All on-premises mailboxes will be moved to Microsoft 365.
* You’ll need an on-premises administrator account that has read access
to your users’ mailboxes.
* The Exchange 2007 accepted domains that you want to use in Microsoft
365 need to be added as verified domains in the service.
* Between the time you start the migration and when you begin the
completion phase, Microsoft 365 will periodically synchronize the
Microsoft 365 and on-premises mailboxes. This lets you complete the
migration without worrying about email being left behind in your
on-premises mailboxes.
* Users will receive new temporary passwords for their Microsoft 365
accounts. They’ll need to change their password when they sign in to
their mailbox for the first time.
* You’ll need a Microsoft 365 license that includes Exchange Online for
each user mailbox you migrate.
* Users will need to set up a new Outlook profile on each of their
devices and download their email again. The amount of email that Outlook
will download can vary. For more information, see
https://support.office.com/article/Change-how-much-mail-to-keep-offline-f3a1251c-6dd5-4208-aef9-7c8c9522d633?ui=en-US&rs=en-US&ad=US&fromAR=1[Change
how much mail to keep offline].

For more information about cutover migration, see:

* https://support.office.com/article/What-you-need-to-know-about-a-cutover-email-migration-to-Office-365-961978ef-f434-472d-a811-1801733869da[What
you need to know about a cutover email migration]
* https://support.office.com/article/Perform-a-cutover-migration-of-email-to-Office-365-9496e93c-1e59-41a8-9bb3-6e8df0cd81b4[Perform
a cutover migration of email]

===== Staged migration

In a staged migration, you have a few hundred or a few thousand
mailboxes that you want to migrate to Microsoft 365, need to take a week
or more to complete the migration, and don’t need any of advanced hybrid
migration features like shared Free/Busy calendar information.

Staged migration is great for organizations that need to take more time
to migrate their mailboxes to Microsoft 365 but still plan to complete
the migration within a few weeks. You can migrate mailboxes in batches.
You control how many and which mailboxes are migrated at a given time.
You might batch mailboxes of users in the same department, for example,
to make sure they’re all moved at the same time. Or, you might leave
executive mailboxes until the last batch. As with cutover migrations,
your users will need to recreate their Outlook profiles.

If you’re thinking about doing a staged migration, here are things to
consider:

* Microsoft 365 will need to connect to your Exchange 2007 servers by
using Outlook Anywhere over TCP port 443.
* You’ll need an on-premises administrator account that has read access
to your users’ mailboxes.
* The Exchange 2007 accepted domains that you plan to use in Microsoft
365 need to be added as verified domains in the service.
* You’ll need to create a CSV file with the full name and email address
of each mailbox that you plan to migrate in a batch. You’ll also need to
include a new password for each mailbox that you’re migrating, and send
that password to each user. The user will be prompted to change the
password the first time that they sign in to their new Microsoft 365
mailbox.
* Between the time you start the migration batch and when you begin the
completion phase, Microsoft 365 will periodically synchronize the
Microsoft 365 and on-premises mailboxes included in the batch. This lets
you complete the migration without worrying about email being left
behind in your on-premises mailboxes.
* You’ll need a Microsoft 365 license that includes Exchange Online for
each user mailbox you migrate.
* Users will need to set up a new Outlook profile on each of their
devices and download their email again. The amount of email that Outlook
will download can vary. For more information, see
https://support.office.com/article/Change-how-much-mail-to-keep-offline-f3a1251c-6dd5-4208-aef9-7c8c9522d633?ui=en-US&rs=en-US&ad=US&fromAR=1[Change
how much mail to keep offline].

For more information about staged migration, see:

* https://support.office.com/article/What-you-need-to-know-about-a-staged-email-migration-to-Office-365-7e2c82be-5f3d-4e36-bc6b-e5b4d411e207[What
you need to know about a staged email migration]
* https://support.office.com/article/Perform-a-staged-migration-of-email-to-Office-365-83bc0b69-de47-4cc4-a57d-47e478e4894e[Perform
a staged migration of email]

===== Full hybrid

In a full hybrid migration, your organization has many hundreds, up to
tens of thousands, of mailboxes, and you want to move some or all of
them to Microsoft 365. Because these migrations are typically
longer-term, hybrid migrations make it possible to:

* Show on-premises users the free/busy calendar information for users in
Microsoft 365, and vice versa.
* See a unified global address list that contains recipients in both
on-premises and Microsoft 365.
* View full Outlook recipient properties for all users, regardless of
whether they’re on-premises or in Microsoft 365.
* Secure email communication between on-premises Exchange servers and
Microsoft 365 using TLS and certificates.
* Treat messages sent between on-premises Exchange servers and Microsoft
365 as internal, enabling them to:
** Be properly evaluated and processed by transport and compliance
agents targeting internal messages.
** Bypass anti-spam filters.

Full hybrid migration is best for organizations that expect to stay in a
hybrid configuration for many months or more. You’ll get the features
listed earlier in this section, plus directory synchronization, better
integrated compliance features, and the ability to move mailboxes to and
from Microsoft 365 by using online mailbox moves. Microsoft 365 becomes
an extension of your on-premises organization.

If you’re thinking about doing a full hybrid migration, here are things
to consider:

* Full hybrid migration isn’t suited to all types of organizations. Due
to the complexity of full hybrid migrations, organizations with less
than a few hundred mailboxes don’t typically see benefits that justify
the effort and cost needed to set one up. If this sounds like your
organization, we recommend that you consider a cutover or staged
migration instead.
* You’ll need to deploy at least one Exchange 2013 server in your
Exchange 2007 organization to act as a ``hybrid server.'' This server
will communicate with Microsoft 365 on behalf of your Exchange 2007
servers.
* Microsoft 365 will need to connect to the ``hybrid server'' using
Outlook Anywhere over TCP port 443.
* You’ll need to set up directory synchronization using Azure Active
Directory (Azure AD) Connect between your on-premises Active Directory
servers and Microsoft 365.
* Users will be able to sign in to their Microsoft 365 mailbox using the
same user name and password as when they sign in to the local network.
(This functionality requires Azure AD Connect with password
synchronization and/or Active Directory Federation Services.)
* You’ll need a Microsoft 365 license that includes Exchange Online for
each user mailbox you migrate.
* Users don’t need to set up a new Outlook profile on most of their
devices, although some older Android phones might need a new profile.
Users won’t have to redownload their email.

If full hybrid migration sounds right for you, see the following
resources to help with your migration:

* link:/exchange/exchange-deployment-assistant[Exchange Deployment
Assistant]
* link:/exchange/exchange-hybrid[Exchange Server Hybrid Deployments]
* link:/exchange/hybrid-configuration-wizard[Hybrid Configuration
wizard]
* link:/exchange/hybrid-configuration-wizard-faqs[Hybrid Configuration
wizard FAQs]
* link:/exchange/hybrid-deployment-prerequisites[Hybrid deployment
prerequisites]

==== Migrate to a newer version of Exchange Server

We strongly believe that you can achieve the best value and user
experience by migrating to Microsoft 365. But we also understand that
some organizations need to keep their email on-premises. This could be
because of regulatory requirements, to guarantee data isn’t stored in a
datacenter located in another country, or similar. If you choose to keep
your email on-premises, you can migrate your Exchange 2007 environment
to Exchange 2010, Exchange 2013, or Exchange 2016.

If you can’t migrate to Microsoft 365, we recommend that you migrate to
Exchange 2016. Exchange 2016 includes all the features of previous
releases of Exchange. It also most closely matches the experience
available with Microsoft 365, although some features are available only
in Microsoft 365. Check out just a few of the things you’ve been
missing:

[width="100%",cols="50%,50%",options="header",]
|===
|Exchange release |Features
|Exchange 2010 |Role-Based Access Control (permissions without ACLs)
Outlook Web App mailbox policies Ability to share free/busy and delegate
calendars between organizations

|Exchange 2013 |_Features from Exchange 2010 and …_ Simplified
architecture that reduced the number of server roles to three (Mailbox,
Client Access, Edge Transport) Data loss prevention policies (DLP) that
help keep sensitive information from leaking Improved Outlook Web App
experience

|Exchange 2016 |_Features from Exchange 2013 and …_ Further simplified
server roles to just Mailbox and Edge Transport Improved DLP along with
integration with SharePoint Improved database resilience Online document
collaboration
|===

===== Which version should I migrate to?

We recommend that you initially assume that you’ll migrate to Exchange
2016. Then, use the following information to confirm your assumption or
to rule out Exchange 2016. If you can’t migrate to Exchange 2016 for
some reason, do the same process with Exchange 2013, and so on.

[width="100%",cols="50%,50%",options="header",]
|===
|Consideration |More Info
|End of support dates |Like Exchange 2007, each version of Exchange has
its own end-of-support date: _Exchange 2010_ - January 2020 _Exchange
2013_ - April 2023 _Exchange 2016_ - October 2025 The earlier the end of
support, the sooner you’ll need to perform another migration.

|Migration path to Exchange 2010 and 2013. |Here are the general phases
for migrating to Exchange 2010 or Exchange 2013: - Install Exchange 2010
or 2013 into your existing Exchange 2007 organization. - Move services
and other infrastructure to Exchange 2010 or 2013.- Move mailboxes and
public folders to Exchange 2010 or 2013.- Decommission remaining
Exchange 2007 servers.

|Migration path to Exchange 2016 |Here are the general phases for
migrating to Exchange 2016: - Install Exchange 2013 into your existing
Exchange 2007 organization.- Move services and other infrastructure to
Exchange 2013.- Move mailboxes and public folders to Exchange 2013.-
Decommission remaining Exchange 2007 servers.- Install Exchange 2016
into your existing Exchange 2013 organization.- Move mailboxes, public
folders, services, and other infrastructure to Exchange 2016 (order
doesn’t matter). Decommission remaining Exchange 2013 servers. *Note:*
Migrating from Exchange 2013 to Exchange 2016 is simple. The two
versions have almost the same hardware requirements, and these versions
are very compatible. So you can rebuild a server you bought for Exchange
2013 and install Exchange 2016 on it. For online mailbox moves, most
users won’t even notice that their mailbox was moved off the server and
then back after you’ve rebuilt it with Exchange 2016.

|Version coexistence |When migrating to … *Exchange 2016:* Exchange 2016
can’t be installed in an organization that includes an Exchange 2007
server. You’ll first need to migrate to Exchange 2010 or 2013 (we
strongly recommend Exchange 2013), remove all Exchange 2007 servers, and
then migrate to Exchange 2016. *Exchange 2010 or Exchange 2013:* You can
install Exchange 2010 or Exchange 2013 into an existing Exchange 2007
organization. This enables you to install one or more Exchange 2010 or
2013 servers and perform your migration.

|Server hardware |Server hardware requirements have changed from
Exchange 2007. Make sure your hardware is compatible. For details, see:
link:/Exchange/plan-and-deploy/system-requirements[Exchange 2016 System
Requirements]
link:/exchange/exchange-2013-system-requirements-exchange-2013-help[Exchange
2013 System Requirements]
link:/previous-versions/office/exchange-server-2010/aa996719(v=exchg.141)[Exchange
2010 System Requirements] You’ll find that the significant improvements
in Exchange performance and the increased computing power and storage
capacity in newer servers mean you’ll likely need fewer servers to
support the same number of mailboxes.

|Operating system version |The minimum supported operating system
versions for each version are: *Exchange 2016* - Windows Server 2012
*Exchange 2013* - Windows Server 2008 R2 SP1 *Exchange 2010* - Windows
Server 2008 SP2 Find more information about operating system support at
link:/Exchange/plan-and-deploy/supportability-matrix[Exchange
Supportability Matrix].

|Active Directory forest functional level |The minimum supported Active
Directory forest functional levels for each version are: *Exchange 2016*
Windows Server 2008 R2 SP1 *Exchange 2013* Windows Server 2003 *Exchange
2010* Windows Server 2003 Find more information about forest functional
level support at
link:/Exchange/plan-and-deploy/supportability-matrix[Exchange
Supportability Matrix].

|Office client versions |The minimum supported Office client versions
for each version are: *Exchange 2016* - Office 2010 (with the latest
updates) *Exchange 2013* - Office 2007 SP3 *Exchange 2010* - Office 2003
Find more information about Office client support at
link:/Exchange/plan-and-deploy/supportability-matrix[Exchange
Supportability Matrix].
|===

===== How do I migrate?

If you decided to keep your email on-premises, use the following
resources to help with your migration:

* link:/exchange/exchange-deployment-assistant[Exchange Deployment
Assistant]
* Active Directory schema changes for Exchange
link:/Exchange/plan-and-deploy/active-directory/ad-schema-changes[2016],
link:/exchange/exchange-2013-active-directory-schema-changes-exchange-2013-help[2013],
https://www.microsoft.com/download/en/details.aspx?displaylang=en&id=5401[2010]
* System requirements for Exchange
link:/Exchange/plan-and-deploy/system-requirements[2016],
link:/exchange/exchange-2013-system-requirements-exchange-2013-help[2013],
link:/previous-versions/office/exchange-server-2010/aa996719(v=exchg.141)[2010]
* Prerequisites for Exchange
link:/Exchange/plan-and-deploy/prerequisites[2016],
link:/exchange/exchange-2013-prerequisites-exchange-2013-help[2013],
link:/previous-versions/office/exchange-server-2010/bb691354(v=exchg.141)[2010]

=== Get help

If you’re migrating to Microsoft 365, you might be eligible to use our
Microsoft FastTrack service. FastTrack provides best practices, tools,
and resources to make your migration to Microsoft 365 as seamless as
possible. Best of all, a support engineer will walk you through your
migration, from planning and design all the way to migrating your last
mailbox. For more about FastTrack, see
https://fasttrack.microsoft.com/[Microsoft FastTrack].

If you run into problems during your migration to Microsoft 365 and you
aren’t using FastTrack, or your migration to a newer version of Exchange
Server, we’re here to help. Here are some resources you can use:

* https://social.technet.microsoft.com/Forums/office/home?category=exchangeserver[Technical
community]
* https://support.microsoft.com/gp/support-options-for-business[Customer
support]

=== Related topics

link:upgrade-from-office-2007-servers-and-products.md[Resources to help
you upgrade your Office 2007 servers and clients]
