= 
kelleyvice-msft

== Fixing problems with directory synchronization for Microsoft 365

With directory synchronization, you can continue to manage users and
groups on-premises and synchronize additions, deletions, and changes to
the cloud. But setup is a little complicated and it can sometimes be
difficult to identify the source of problems. We have resources to help
you identify potential issues and fix them.

=== How do I know if something is wrong?

The first indication that something is wrong is when the DirSync Status
tile in the Microsoft 365 admin center indicates there is a problem.

You will also receive a mail (to the alternate email and to your admin
email) from Microsoft 365 that indicates your tenant has encountered
directory synchronization errors. For details see
link:identify-directory-synchronization-errors.md[Identify directory
synchronization errors in Microsoft 365].

=== How do I get Azure Active Directory Connect tool?

In the https://admin.microsoft.com[Microsoft 365 admin center], navigate
to *Users* > *Active users*. Click the *More* menu (three dots) and
select *Directory synchronization*.

Follow the link:set-up-directory-synchronization.md[instructions in the
wizard] to download Azure AD Connect.

If you are still using Azure Active Directory (Azure AD) Sync (DirSync),
take a look at
link:/troubleshoot/azure/active-directory/installation-configuration-wizard-errors[How
to troubleshoot Azure Active Directory Sync Tool installation and
Configuration Wizard error messages in Microsoft 365] for information
about the system requirements to install dirsync, the permissions you
need, and how to troubleshoot common errors.

To update from Azure AD Sync to Azure AD Connect, see
link:/azure/active-directory/hybrid/how-to-dirsync-upgrade-get-started[the
upgrade instructions].

=== Resolving common causes of problems with directory synchronization in Microsoft 365

==== Synchronized objects aren’t appearing or updating online, or I’m getting synchronization error reports from the Service.

* link:/azure/active-directory/hybrid/how-to-connect-syncservice-duplicate-attribute-resiliency[Identity
synchronization and duplicate attribute resiliency]

==== I have an alert in the admin center, or am receiving automated emails that there hasn’t been a recent synchronization event

* link:/azure/active-directory/hybrid/tshoot-connect-connectivity[Troubleshoot
connectivity issues with Azure AD Connect]
* link:/azure/active-directory/hybrid/reference-connect-accounts-permissions[Azure
AD Connect Accounts and permissions]
* link:/azure/active-directory/hybrid/how-to-connect-azureadaccount[Azure
AD Connect sync: How to manage the Azure AD service account]
* https://support.microsoft.com/help/2882421/directory-synchronization-to-azure-active-directory-stops-or-you-re-warned-that-sync-hasn-t-registered-in-more-than-a-day[Directory
synchronization to Azure Active Directory stops or you’re warned that
sync hasn’t registered in more than a day]

==== Password hashes aren’t synchronizing, or I’m seeing an alert in the admin center that there hasn’t been a recent password hash synchronization

* link:/azure/active-directory/hybrid/how-to-connect-password-hash-synchronization[Implementing
password hash synchronization with Azure AD Connect sync]

==== I’m seeing an alert that Object quota exceeded

* We have a built-in object quota to help protect the service. If you
have too many objects in your directory that need to sync to Microsoft
365, you’ll have to
https://support.office.com/article/32a17ca7-6fa0-4870-8a8d-e25ba4ccfd4b[Contact
support for business products] to increase your quota.

==== I need to know which attributes are synchronized

* You can find a list of all the attributes that are synced between
on-premises and the cloud
https://go.microsoft.com/fwlink/p/?LinkId=396719[right here].

==== I can’t manage or remove objects that were synchronized to the cloud

* Are you ready to manage objects in the cloud only? Or is there an
object that was deleted on-premises, but is stuck in the cloud? Take a
look at this
link:/azure/active-directory/hybrid/tshoot-connect-sync-errors[Troubleshooting
Errors during synchronization] and
link:/troubleshoot/azure/active-directory/cannot-manage-objects[support
article] for guidance on how to resolve these issues.

==== I got an error message that my company has exceeded the number of objects that can be synchronized

* You can read more about this issue
link:/troubleshoot/azure/active-directory/exceed-number-objects-synced[here].

=== Other resources

* link:/samples/browse/?redirectedfrom=TechNet-Gallery[Script to fix
duplicate user principal names]
* link:prepare-a-non-routable-domain-for-directory-synchronization.md[How
to prepare a non-routable domain (such as .local domain) for directory
synchronization]
* link:/samples/browse/?redirectedfrom=TechNet-Gallery[Script to count
total synchronized objects]
* https://go.microsoft.com/fwlink/p/?LinkId=396727[Troubleshoot AD FS
2.0]
* https://go.microsoft.com/fwlink/p/?LinkId=396728[Use PowerShell to fix
empty DisplayName attributes for mail-enabled groups]
* https://go.microsoft.com/fwlink/p/?LinkId=396730[Use PowerShell to fix
duplicate UPN]
* https://go.microsoft.com/fwlink/p/?LinkId=396731[Use PowerShell to fix
duplicate email addresses]
