= Plan for Microsoft 365 Enterprise
:audience: Admin
:author: kelleyvice-msft
:description: This article provides checklists and other resources to plan for your Microsoft 365 Enterprise deployment.
:f1.keywords: ["CSH"]
:manager: scotv
:ms.assetid: 712fced7-f9d0-4fde-8b79-286262a5d0bc
:ms.author: kvice
:ms.collection: ["Ent_O365", "M365-subscription-management"]
:ms.custom: ["Adm_O365", "seo-marvel-apr2020"]
:ms.date: 08/12/2019
:ms.localizationpriority: medium
:ms.service: microsoft-365-enterprise
:ms.topic: conceptual
:search.appverid: ["MET150", "MOE150", "BCS160"]

== Plan for Microsoft 365 Enterprise

When you move an enterprise organization to Microsoft 365, it's important to plan ahead and make the key design decisions that will streamline IT deployment and user adoption.

=== Planning with Microsoft 365 FastTrack

https://www.microsoft.com/fasttrack/microsoft-365[FastTrack for Microsoft 365] is the best method for getting help from Microsoft for planning your Microsoft 365 deployment.
FastTrack can help you through the most common design considerations and can answer questions along the way.

____
[!Note] You can also get help from a https://www.microsoft.com/solution-providers/home[Microsoft partner].
____

=== Do-it-yourself planning for Microsoft 365

To plan for Microsoft 365 on your own, step through the planning and design decisions for these areas:

* Your Microsoft 365 tenant
+
Includes planning for your network connections to the Internet, your Microsoft 365 identities, and integration with apps, on-premises, Azure, and other elements.
Go to xref:subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.adoc[Subscriptions, licenses, accounts, and tenants for Microsoft's cloud offerings] for more information.

* Support for your clients
+
Includes certificate-based authentication, mobile device management, authentication options, and inter-tenant collaboration.
Go to xref:microsoft-365-client-support-certificate-based-authentication.adoc[Certificate-based Authentication] for more information.

* Support for hybrid modern authentication
+
Includes planning for modern authentication when using hybrid configurations of key Microsoft 365 productivity apps.
Go to xref:hybrid-modern-auth-overview.adoc[Hybrid modern authentication overview and prerequisites] for more information.

* Older Office clients and servers
+
Includes migration information for Office 2007 and Office 2010 client and server products.
Go to xref:plan-upgrade-previous-versions-office.adoc[Plan your upgrade] for more information.

You can also sign in to your Microsoft 365 subscription and use the xref:setup-guides-for-microsoft-365.adoc[Setup guides for Microsoft 365 and Office 365 services].
