= 
kelleyvice-msft

== Get started with PowerShell for Microsoft 365

_This article applies to both Microsoft 365 Enterprise and Office 365
Enterprise._

You can use commands and scripts in PowerShell for Microsoft 365 to
manage Microsoft 365 and streamline your daily work. Use the following
information to learn why PowerShell for Microsoft 365 is crucial to
managing Microsoft 365, how to connect to your Microsoft 365
subscription and create reports, and where to get more information from
the Microsoft 365 community.

Select from these topics:

* link:why-you-need-to-use-microsoft-365-powershell.md[*Why you need to
use PowerShell for Microsoft 365*]
+
Start here if you’re new to PowerShell for Microsoft 365. Learn why you
should use PowerShell for Microsoft 365.
* link:connect-to-microsoft-365-powershell.md[*Connect to Microsoft 365
with PowerShell*]
+
Start here to connect to your Microsoft 365 subscription by using
PowerShell for Microsoft 365 and do administrative tasks from the
command line.
* link:connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window.md[*Connect
to all Microsoft 365 services in a single PowerShell window*]
+
You can manage Microsoft 365 in separate windows for Skype for Business
Online, SharePoint Online, Microsoft Exchange Online, and Microsoft 365
accounts and licenses. Or, you can manage them all from a single window.
This article explains how.
* link:use-windows-powershell-to-create-reports-in-microsoft-365.md[*Use
PowerShell to create reports in Microsoft 365*]
+
Start here if you’ve installed the PowerShell for Microsoft 365 modules
and want to learn about using automation commands to create reports
quickly.
* link:cmdlet-references-for-microsoft-365-services.md[*Cmdlet
references for Microsoft 365 services*]
+
Learn about the cmdlets for the PowerShell for Microsoft 365 modules.
* link:microsoft-365-powershell-community-resources.md[*Microsoft 365
community resources for PowerShell*]
+
Start here to connect to the PowerShell community and get more
information about using PowerShell for Microsoft 365.

=== Related topics

link:manage-microsoft-365-with-microsoft-365-powershell.md[Manage
Microsoft 365 with PowerShell]
