= 
kelleyvice-msft

== Hybrid solutions

With Microsoft Azure, you can deploy some Office Server workloads that
were typically deployed on-premises in Azure infrastructure services.

For Microsoft 365 identity infrastructure in Azure:

* link:/azure/active-directory/saas-apps/sharepoint-on-premises-tutorial[Using
Azure AD for SharePoint Server Authentication]
* link:deploy-microsoft-365-directory-synchronization-dirsync-in-microsoft-azure.md[Deploy
Microsoft 365 Directory Synchronization in Microsoft Azure]
* link:connect-an-on-premises-network-to-a-microsoft-azure-virtual-network.md[Connect
an on-premises network to a Microsoft Azure virtual network]
* link:deploy-high-availability-federated-authentication-for-microsoft-365-in-azure.md[Deploy
high availability federated authentication for Microsoft 365 in Azure]

For SharePoint Server 2013 workloads in Azure:

* link:microsoft-azure-architectures-for-sharepoint-2013.md[Microsoft
Azure Architectures for SharePoint 2013]
* link:sharepoint-server-2013-disaster-recovery-in-microsoft-azure.md[SharePoint
Server 2013 Disaster Recovery in Microsoft Azure]
* link:internet-sites-in-microsoft-azure-using-sharepoint-server-2013.md[Internet
Sites in Microsoft Azure using SharePoint Server 2013]

=== Related topics

link:../solutions/index.yml[Microsoft 365 solution and architecture
center]

link:../solutions/cloud-architecture-models.md[Microsoft cloud for
enterprise architects illustrations]

link:architectural-models-for-sharepoint-exchange-skype-for-business-and-lync.md[Architectural
models for SharePoint&#44; Exchange&#44; Skype for Business&#44; and Lync]
