= 
kelleyvice-msft

== Identity and device access for your Microsoft 365 test environment

_This Test Lab Guide can only be used for Microsoft 365 for enterprise
test environments._

link:../security/office-365-security/microsoft-365-policies-configurations.md[Identity
and device access configurations] are a set of recommended
configurations and conditional access policies to protect access to all
services that are integrated with Azure Active Directory (Azure AD).

To create a test environment that has the common identity and device
access configurations in place:

[arabic]
. Configure your test environment with the prerequisite identity and
security features based on your choice of identity model and
authentication method:

* link:cloud-only-prereqs-m365-test-environment.md[Cloud only]
* link:phs-prereqs-m365-test-environment.md[Password hash
synchronization (PHS)]
* link:pta-prereqs-m365-test-environment.md[Pass-through authentication
(PTA)]

[arabic, start=2]
. Use
link:../security/office-365-security/identity-access-policies.md[Common
identity and device access policies] to configure the policies that
build on the prerequisites configured for your test environment and
explore and verify protection for identities and devices.

=== See also

link:m365-enterprise-test-lab-guides.md#identity[Additional identity
Test Lab Guides]

link:deploy-identity-solution-overview.md[Deploy identity]

link:m365-enterprise-test-lab-guides.md[Microsoft 365 for enterprise
Test Lab Guides]

link:microsoft-365-overview.md[Microsoft 365 for enterprise overview]

link:/microsoft-365-enterprise/[Microsoft 365 for enterprise
documentation]
