= IPv6 support in Microsoft 365 services
:audience: ITPro
:author: kelleyvice-msft
:description: Summary: Describes IPv6 support in Microsoft 365 components and in Microsoft 365 government offerings.
:f1.keywords: ["CSH"]
:manager: scotv
:ms.assetid: c08786fb-298e-437c-8222-dab7625fc815
:ms.author: kvice
:ms.collection: Ent_O365
:ms.custom: Adm_O365
:ms.date: 06/02/2022
:ms.localizationpriority: medium
:ms.service: microsoft-365-enterprise
:ms.topic: conceptual
:search.appverid: ["MET150", "MOE150", "BCS160"]

== IPv6 support in Microsoft 365 services

With the growing adoption and support of IPv6 across enterprise networks, service providers and devices, many customers are wondering if their users can continue to access Microsoft 365 services from IPv6 clients and IPv6 networks.
Microsoft 365 services can be successfully used from both IPv6 dual stack and IPv6-only devices.
In fact, we have an increasing number of customers, from consumers to large enterprises, who are moving towards greater adoption of IPv6.
For most customers, IPv4 won't completely disappear from their digital landscape, so we aren't planning to require IPv6 or to de-prioritize IPv4 in any Microsoft 365 features or services.

One of our key priorities with Microsoft 365 is to ensure seamless customer and user experiences over the Internet from any location, from any device.
This includes access to Microsoft 365 from customer devices that are using IPv6 in the dual stack configuration as well as transitioning to IPv6-only client deployments.
In most cases, when you follow a standard Internet-based model of connecting to Microsoft 365 as described in xref:microsoft-365-network-connectivity-principles.adoc[Microsoft 365 network connectivity principles], xref:urls-and-ip-address-ranges.adoc[Microsoft 365 URLs and IP address ranges], and link:network-and-migration-planning.md#best-practices-for-network-planning-and-improving-migration-performance-for-office-365[Microsoft 365 network planning best practices], IPv6 transitions won't be disruptive to your user experience.

Many Microsoft 365 services already provide native IPv6 support today and can be accessed directly from IPv6 dual stack and IPv6-only clients.
Microsoft 365 also allows access through conventional IPv6 to IPv4 translation technologies (such as base 64 proxies or DNS64/NAT64) commonly used by customers and network solution providers to connect to IPv4 Internet resources.

As with any SaaS service and the Internet overall, the scope of natively IPv6 enabled Microsoft 365 interfaces, features and APIs expands continuously and without direct customer action or control.
If you're running IPv6 or IPv6-only services on your networks that need access to Microsoft 365 and the Internet, it is recommended that you include dynamic IPv6/IPv4 transitional mechanisms such as DNS64/NAT64 to ensure end-to-end IPv6 connectivity to Microsoft 365 without any further network reconfigurations.

Most of Microsoft 365 services have been or will be enabled with IPv6 capabilities completely transparently for end users and IT admins.
Some Microsoft 365 scenarios (such as anonymous inbound e-mail) do have special requirements and considerations for use in conjunction with IPv6.
For more details about scenario specific IPv6 requirements and considerations, please contact your Microsoft account team or Microsoft support.

Here's a short link you can use to come back: https://aka.ms/o365ip6

=== See also

xref:microsoft-365-networking-overview.adoc[Microsoft 365 Network Connectivity Overview]

xref:managing-office-365-endpoints.adoc[Managing Office 365 endpoints]

xref:urls-and-ip-address-ranges.adoc[Office 365 URLs and IP address ranges]

xref:microsoft-365-ip-web-service.adoc[Office 365 IP Address and URL Web service]

xref:assessing-network-connectivity.adoc[Assessing Microsoft 365 network connectivity]

xref:network-planning-and-performance.adoc[Network planning and performance tuning for Microsoft 365]

xref:performance-tuning-using-baselines-and-history.adoc[Office 365 performance tuning using baselines and performance history]

xref:performance-troubleshooting-plan.adoc[Performance troubleshooting plan for Office 365]

xref:content-delivery-networks.adoc[Content Delivery Networks]

https://aka.ms/netonboard[Microsoft 365 connectivity test]

https://azure.microsoft.com/blog/how-microsoft-builds-its-fast-and-reliable-global-network/[How Microsoft builds its fast and reliable global network]

https://techcommunity.microsoft.com/t5/Office-365-Networking/bd-p/Office365Networking[Office 365 Networking blog]
