= Manage passwords with PowerShell
:audience: Admin
:author: kelleyvice-msft
:description: Learn how to use PowerShell to manage passwords.
:f1.keywords: ["CSH"]
:manager: scotv
:ms.author: kvice
:ms.collection: Ent_O365
:ms.custom: ["PowerShell", "Ent_Office_Other", "O365ITProTrain"]
:ms.localizationpriority: medium
:ms.service: microsoft-365-enterprise
:ms.topic: article
:search.appverid: ["MET150"]

== Manage passwords with PowerShell

_This article applies to both Microsoft 365 Enterprise and Office 365 Enterprise._

You can use PowerShell for Microsoft 365 as an alternative to the Microsoft 365 admin center to manage passwords in Microsoft 365.

When a command block in this article requires that you specify variable values, use these steps.

. Copy the command block to the clipboard and paste it into Notepad or the PowerShell Integrated Script Environment (ISE).
. Fill in the variable values and remove the "<" and ">" characters.
. Run the commands in the PowerShell window or the PowerShell ISE.

=== Use the Azure Active Directory PowerShell for Graph module

First, link:connect-to-microsoft-365-powershell.md#connect-with-the-azure-active-directory-powershell-for-graph-module[connect to your Microsoft 365 tenant].

==== Set a password

Use these commands to specify a password for a user account.

[,powershell]
----
$userUPN="<user account sign in name, such as belindan@contoso.com>"
$newPassword="<new password>"
$secPassword = ConvertTo-SecureString $newPassword -AsPlainText -Force
Set-AzureADUserPassword -ObjectId  $userUPN -Password $secPassword
----

==== Force a user to change their password

Use these commands to set a password and force a user to change their new password.

[,powershell]
----
$userUPN="<user account sign in name, such as belindan@contoso.com>"
$newPassword="<new password>"
$secPassword = ConvertTo-SecureString $newPassword -AsPlainText -Force
Set-AzureADUserPassword -ObjectId  $userUPN -Password $secPassword -EnforceChangePasswordPolicy $true
----

Use these commands to set a password and force a user to change their new password the next time they sign in.

[,powershell]
----
$userUPN="<user account sign in name, such as belindan@contoso.com>"
$newPassword="<new password>"
$secPassword = ConvertTo-SecureString $newPassword -AsPlainText -Force
Set-AzureADUserPassword -ObjectId  $userUPN -Password $secPassword -ForceChangePasswordNextLogin $true
----

=== Use the Microsoft Azure Active Directory Module for Windows PowerShell

First, link:connect-to-microsoft-365-powershell.md#connect-with-the-microsoft-azure-active-directory-module-for-windows-powershell[connect to your Microsoft 365 tenant].

==== Set a password

Use these commands to specify a password for a user account.

[,powershell]
----
$userUPN="<user account sign in name>"
$newPassword="<new password>"
Set-MsolUserPassword -UserPrincipalName $userUPN -NewPassword $newPassword
----

==== Force a user to change their password

Use these commands to force a user to change their password.

[,powershell]
----
$userUPN="<user account sign in name>"
Set-MsolUserPassword -UserPrincipalName $userUPN -ForceChangePassword $true
----

=== See also

xref:manage-user-accounts-and-licenses-with-microsoft-365-powershell.adoc[Manage Microsoft 365 user accounts, licenses, and groups with PowerShell]

xref:manage-microsoft-365-with-microsoft-365-powershell.adoc[Manage Microsoft 365 with PowerShell]

xref:getting-started-with-microsoft-365-powershell.adoc[Getting started with PowerShell for Microsoft 365]
