= 
kelleyvice-msft

== Manage Microsoft 365 with PowerShell

_This article applies to both Microsoft 365 Enterprise and Office 365
Enterprise._

PowerShell for Microsoft 365 is a powerful management tool that
complements the Microsoft 365 admin center. For example, you can use
PowerShell automation to easily manage multiple user accounts and
licenses and to create reports.

Select from the following topics to learn how to use PowerShell to
manage Microsoft 365:

* link:getting-started-with-microsoft-365-powershell.md[*Get started*]
+
Start here if you’re not familiar with PowerShell for Microsoft 365, and
you want to install the Microsoft 365 modules and connect to your
subscription.
* link:manage-user-accounts-and-licenses-with-microsoft-365-powershell.md[*User
accounts&#44; licenses&#44; and groups*]
+
Start here if want to learn about using automation commands to manage
user accounts, licenses, and groups.
* link:manage-sharepoint-online-with-microsoft-365-powershell.md[*SharePoint*]
+
Start here if you want to use automation commands to manage SharePoint.
* link:/powershell/exchange/exchange-online-powershell[*Exchange
Online*]
+
Start here if you want to manage Exchange Online.
* link:use-powershell-for-email-migration-to-microsoft-365.md[*Email
migration*]
+
Start here if you want to migrate your email from pre-existing systems.
* link:/powershell/exchange/scc-powershell[*Security & Compliance
Center*]
+
Start here if you want to manage Security & Compliance Center features.
* link:manage-microsoft-365-with-windows-powershell-for-delegated-access-permissions-dap-p.md[*Delegated
Access Permissions (DAP) partners*]
+
Start here if you want to use Syndication and Cloud Solution Provider
(CSP) partners to manage your Microsoft 365 customer tenants.
* link:manage-skype-for-business-online-with-microsoft-365-powershell.md[*Skype
for Business Online*]
+
Start here to manage Skype for Business Online.
