= 
kelleyvice-msft

== Manage security groups with PowerShell

_This article applies to both Microsoft 365 Enterprise and Office 365
Enterprise._

You can use PowerShell for Microsoft 365 as an alternative to the
Microsoft 365 admin center to manage security groups.

This article describes listing, creating, changing settings, and
removing security groups.

When a command block in this article requires that you specify variable
values, use these steps.

[arabic]
. Copy the command block to the clipboard and paste it into Notepad or
the PowerShell Integrated Script Environment (ISE).
. Fill in the variable values and remove the ``<'' and ``>'' characters.
. Run the commands in the PowerShell window or the PowerShell ISE.

See
link:maintain-group-membership-with-microsoft-365-powershell.md[Maintain
security group membership] to manage group membership with PowerShell.

=== Use the Azure Active Directory PowerShell for Graph module

First,
link:connect-to-microsoft-365-powershell.md#connect-with-the-azure-active-directory-powershell-for-graph-module[connect
to your Microsoft 365 tenant].

==== List your groups

Use this command to list all of your groups.

[source,powershell]
----
Get-AzureADGroup
----

Use these commands to display the settings of a specific group by its
display name.

[source,powershell]
----
$groupName="<display name of the group>"
Get-AzureADGroup | Where { $_.DisplayName -eq $groupName }
----

==== Create a new group

Use this command to create a new security group.

[source,powershell]
----
New-AzureADGroup -Description "<group purpose>" -DisplayName "<name>" -MailEnabled $false -SecurityEnabled $true -MailNickName "<email name>"
----

==== Change the settings on a group

Display the settings of the group with these commands.

[source,powershell]
----
$groupName="<display name of the group>"
Get-AzureADGroup | Where { $_.DisplayName -eq $groupName } | Select *
----

Then, use the
link:/powershell/module/azuread/set-azureadgroup[Set-AzureADGroup]
article to determine how to change a setting.

==== Remove a security group

Use these commands to remove a security group.

[source,powershell]
----
$groupName="<display name of the group>"
Remove-AzureADGroup -ObjectId (Get-AzureADGroup | Where { $_.DisplayName -eq $groupName }).ObjectId
----

==== Manage the owners of a security group

Use these commands to display the current owners of a security group.

[source,powershell]
----
$groupName="<display name of the group>"
Get-AzureADGroupOwner -ObjectId (Get-AzureADGroup | Where { $_.DisplayName -eq $groupName }).ObjectId
----

Use these commands to add a user account by its *user principal name
(UPN)* to the current owners of a security group.

[source,powershell]
----
$userUPN="<UPN of the user account to add>"
$groupName="<display name of the group>"
Add-AzureADGroupOwner -ObjectId (Get-AzureADGroup | Where { $_.DisplayName -eq $groupName }).ObjectId -RefObjectId (Get-AzureADUser | Where { $_.UserPrincipalName -eq $userUPN }).ObjectId
----

Use these commands to add a user account by its *display name* to the
current owners of a security group.

[source,powershell]
----
$userName="<Display name of the user account to add>"
$groupName="<display name of the group>"
Add-AzureADGroupOwner -ObjectId (Get-AzureADGroup | Where { $_.DisplayName -eq $groupName }).ObjectId -RefObjectId (Get-AzureADUser | Where { $_.DisplayName -eq $userName }).ObjectId
----

Use these commands to remove a user account by its *UPN* to the current
owners of a security group.

[source,powershell]
----
$userUPN="<UPN of the user account to remove>"
$groupName="<display name of the group>"
Remove-AzureADGroupOwner -ObjectId (Get-AzureADGroup | Where { $_.DisplayName -eq $groupName }).ObjectId -OwnerId (Get-AzureADUser | Where { $_.UserPrincipalName -eq $userUPN }).ObjectId
----

Use these commands to remove a user account by its *display name* to the
current owners of a security group.

[source,powershell]
----
$userName="<Display name of the user account to remove>"
$groupName="<display name of the group>"
Remove-AzureADGroupOwner -ObjectId (Get-AzureADGroup | Where { $_.DisplayName -eq $groupName }).ObjectId -OwnerId (Get-AzureADUser | Where { $_.DisplayName -eq $userName }).ObjectId
----

=== Use the Microsoft Azure Active Directory Module for Windows PowerShell

First,
link:connect-to-microsoft-365-powershell.md#connect-with-the-microsoft-azure-active-directory-module-for-windows-powershell[connect
to your Microsoft 365 tenant].

==== List your groups

Use this command to list all of your groups.

[source,powershell]
----
Get-MsolGroup
----

Use these commands to display the settings of a specific group by its
display name.

[source,powershell]
----
$groupName="<display name of the group>"
Get-MsolGroup | Where { $_.DisplayName -eq $groupName }
----

==== Create a new group

Use this command to create a new security group.

[source,powershell]
----
New-MsolGroup -Description "<group purpose>" -DisplayName "<name>"
----

==== Change the settings on a group

Display the settings of the group with these commands.

[source,powershell]
----
$groupName="<display name of the group>"
Get-MsolGroup | Where { $_.DisplayName -eq $groupName } | Select *
----

Then, use the
link:/powershell/module/msonline/set-msolgroup[Set-MsolGroup] article to
determine how to change a setting.

==== Remove a security group

Use these commands to remove a security group.

[source,powershell]
----
$groupName="<display name of the group>"
Remove-MsolGroup -ObjectId (Get-AzureADGroup | Where { $_.DisplayName -eq $groupName }).ObjectId
----

=== See also

link:manage-user-accounts-and-licenses-with-microsoft-365-powershell.md[Manage
Microsoft 365 user accounts&#44; licenses&#44; and groups with PowerShell]

link:manage-microsoft-365-with-microsoft-365-powershell.md[Manage
Microsoft 365 with PowerShell]

link:getting-started-with-microsoft-365-powershell.md[Getting started
with PowerShell for Microsoft 365]
