= 
kelleyvice-msft

== Microsoft 365 endpoints

_This article applies to both Microsoft 365 Enterprise and Office 365
Enterprise._

Endpoints are the set of destination IP addresses, DNS domain names, and
URLs for Microsoft 365 traffic on the Internet.

To optimize performance to Microsoft 365 cloud-based services, these
endpoints need special handling by your client browsers and the devices
in your edge network. These devices include firewalls, SSL Break and
Inspect and packet inspection devices, and data loss prevention systems.

See link:managing-office-365-endpoints.md[Managing Microsoft 365
endpoints] for the details.

There are currently five different Microsoft 365 clouds. This table
takes you to the list of endpoints for each one.

[width="100%",cols="<58%,<42%",options="header",]
|===
|Cloud |Description
|link:urls-and-ip-address-ranges.md[Worldwide endpoints] |The endpoints
for worldwide Microsoft 365 subscriptions, which include the United
States Government Community Cloud (GCC).

|link:microsoft-365-u-s-government-dod-endpoints.md[U.S. Government DoD
endpoints] |The endpoints for United States Department of Defense (DoD)
subscriptions.

|link:microsoft-365-u-s-government-gcc-high-endpoints.md[U.S. Government
GCC High endpoints] |The endpoints for United States Government
Community Cloud High (GCC High) subscriptions.

|link:urls-and-ip-address-ranges-21vianet.md[Microsoft 365 operated by
21Vianet endpoints] |The endpoints for Microsoft 365 operated by
21Vianet, which is designed to meet the needs for Microsoft 365 in
China.

| |
|===

To automate getting the latest list of endpoints for your Microsoft 365
cloud, see the link:microsoft-365-ip-web-service.md[Office 365 IP
Address and URL Web service].

For additional endpoints, see these articles:

* link:additional-office365-ip-addresses-and-urls.md[Additional
endpoints not included in the Web service]
* link:network-requests-in-office-2016-for-mac.md[Network requests in
Office 2016 for Mac]

If you are a network equipment vendor, join the
link:microsoft-365-networking-partner-program.md[Office 365 Networking
Partner Program]. Enroll in the program to build Microsoft 365 network
connectivity principles into your products and solutions.
