= Microsoft 365 service health status
:audience: Admin
:author: kelleyvice-msft
:description: Microsoft 365 service health status
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.author: kvice
:ms.collection: ["Ent_O365", "Strat_O365_Enterprise"]
:ms.custom: admindeeplinkMAC
:ms.date: 04/19/2020
:ms.localizationpriority: high
:ms.service: microsoft-365-enterprise
:ms.topic: conceptual
:search.appverid: ["MET150"]

== Microsoft 365 network health status

Due to the increased demand for Microsoft's cloud services during the COVID-19 crisis, we are providing information about the health of Microsoft's global network and information about network quality issues that our customers might experience but that we don't control.

This information includes network issues that affect all of our software as service offerings, including Microsoft 365.

_There might be delays in the updates to this page.
We are updating it manually while we build a more automated solution._

When we detect significant issues within Microsoft's global network or with internet connectivity between our customers and Microsoft's network, we'll post that information here.
We recommend that customers continue to use the Microsoft 365 admin center https://go.microsoft.com/fwlink/p/?linkid=842900[Service Health dashboard] to understand the impact of any significant network issues on their tenant, as we provide much more detailed and targeted information there.

=== Current network issues

|===
| Location | Issue Type | Detail

| No current issues
|
|
|===

=== Recommendations to improve network experience

Use these resources to improve your network utilization for Microsoft services.

* xref:microsoft-365-vpn-split-tunnel.adoc[Optimize Microsoft 365 connectivity for remote users using VPN split tunneling]
* xref:./microsoft-365-network-connectivity-principles.adoc[Microsoft 365 principles of network connectivity]
* link:/azure/networking/working-remotely-support[Working remotely using Azure Networking services]
