= 
kelleyvice-msft

== Microsoft 365 inter-tenant collaboration

Suppose that two organizations, Fabrikam and Contoso, each have a
Microsoft 365 for business tenant and they want to work together on
several projects; some of which run for a limited time and some of which
are ongoing. How can Fabrikam and Contoso enable their people and teams
to collaborate more effectively across their different Microsoft 365
tenants in a secure manner? Microsoft 365, in conjunction with Azure
Active Directory (Azure AD) B2B collaboration, provides several options.
This article describes several key scenarios that Fabrikam and Contoso
can consider.

Microsoft 365 inter-tenant collaboration options include using a central
location for files and conversations, sharing calendars, using IM,
audio/video calls for communication, and securing access to resources
and applications. Use the following tables to select solutions and learn
more.

=== Exchange Online collaboration options

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Sharing goal |Administrative action |How-to information
|Share calendars with another Microsoft 365 organization |Administrators
can set up different levels of calendar access in Exchange Online to
allow businesses to collaborate with other businesses and to let users
share the schedules (free/busy information) with others. |

|Control how users share their calendars with people outside your
organization |Administrators apply sharing policies to users mailboxes
to control who it can be shared with and the level of access granted |

|Configure secure email channels and control mail flow with partner
organizations |Administrators create connectors to apply security to
mail exchanges with a partner organization or service provider. The
connectors enforce encryption via transport layer security (TLS) as well
as allowing restrictions on domain names or IP address ranges your
partners send email from. |
|===

=== SharePoint Online and OneDrive for Business collaboration options

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Sharing goals |Administrative action |How-to information
|Share sites and documents with external users |Administrators configure
sharing at the tenant, or site collection level for Microsoft account
authenticated, work or school account authenticated or guest accounts |

|Tracking and controlling external sharing for end users |OneDrive for
Business file owners and SharePoint Online end users configure site and
document sharing and establish notifications to track sharing |
|===

=== Skype for Business collaboration options

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Sharing goal |Administrative action |How-to information
|Skype for Business Online - IM, calls, and presence with other Skype
for Business users |Administrators can enable their Skype for Business
Online users to IM, make audio/video calls, and see presence with users
in another Microsoft 365 tenant.
|https://support.office.com/article/b414873a-0059-4cd5-aea1-e5d0857dbc94[Allow
users to contact external Skype for Business users]

|Skype for Business Online - IM, calls, and presence with Skype
(consumer) users |Administrators can enable their Skype for Business
Online users to IM, make calls, and see presence with Skype (consumer)
users.
|https://support.office.com/article/08666236-1894-42ae-8846-e49232bbc460[Let
Skype for Business users add Skype contacts]
|===

=== Azure AD B2B Collaboration options

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Sharing goal |Administrative action |How-to information
|Azure AD B2B collaboration - Content sharing by adding external users
to a group in an organization’s directory |A *Azure AD DC admin*,
*Security Admin*, *User Admin*, *Cloud Application Admin*, or *Global
admin* for one Microsoft 365 tenant can invite people in another
Microsoft 365 tenant to join their directory, add those external users
to a group, and grant access to content, such as SharePoint sites and
libraries for the group. |
|===

=== Microsoft 365 collaboration options

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Sharing goal |Administrative action |How-to information
|Microsoft 365 Groups - Email, calendar, OneNote, and shared files in a
central place |Groups are supported in Business Essentials, Business
Premium, Education, and the Enterprise E1, E3, and E5 plans. People in
one Microsoft 365 tenant can create a group and invite people in another
Microsoft 365 tenant as guest users. Applies to Dynamics CRM as well. |
|===

=== Yammer collaboration options

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Sharing goal |Administrative action |How-to information
|Yammer - Collaboration through an enterprise social medium |Unless the
ability to create external groups is disabled by a Yammer admin, users
can create external groups to collaborate in Yammer through
conversations, the ability to like and follow posts, share files, and
chat online.
|https://support.office.com/article/9ccd15ce-0efc-4dc1-81bc-4a424ab6f92a[Create
and manage external groups in Yammer]
|===

=== Teams collaboration options

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Sharing goal |Administrative action |How-to information
|Collaborate in Teams with users external to the organization |A *User
Admin*, or *Global admin* for the inviting Microsoft 365 tenant needs to
enable external collaboration in Teams. Global admins and team owners
will now be able to invite anyone with an email address to collaborate
in Teams. Admins can also manage and edit Guests already present in
their tenant. |

|Team owners can invite and manage how guests collaborate within their
teams. |Team owners have additional controls on what the guests can do
within their teams. |

|Guests from other tenants can view contents in Teams and collaborate
with other members |None. |link:/microsoftteams/guest-experience[The
guest access experience]
|===

=== Power BI collaboration options

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Sharing goal |Administrative action |How-to information
|Power BI enables external guest users to consume content shared to them
through links. This enables users in the organization to distribute
content in a secure way across organizations. |The Power BI Admin can
control whether users can invite external users to view content within
the organization. |link:/power-bi/service-admin-azure-ad-b2b[Distribute
Power BI content to external guest users with Azure AD B2B]
|===

=== Points to be aware of about Microsoft 365 inter-tenant collaboration

==== Sharing of user accounts, licenses, subscriptions, and storage

Each organization maintains its own user accounts, identities, security
groups, subscriptions, licenses, and storage. People use the
collaboration features in Microsoft 365 together with sharing policies
and security settings to provide access to needed information while
maintaining control of company assets.

* *User accounts:* Accounts cannot be shared or duplicated between the
tenants or partitions in the on-premises Active Directory Domain
Services.
* *Licenses & subscriptions:* In Microsoft 365, licenses from licensing
plans (also called SKUs or Microsoft 365 plans) give users access to the
Microsoft 365 services that are defined for those plans.
* *Storage:* In Microsoft 365 licensing plans, software boundaries and
limits for SharePoint Online are managed separately from mailbox storage
limits. Mailbox storage limits are set up and managed by using Exchange
Online. In both scenarios, storage can’t be shared across tenants.

==== Can we share domain namespaces across Microsoft 365 tenants?

No. Organization domain names, such as fabrikam.com or tailspintoys.com,
can only be associated and used with a single Microsoft 365 tenant. Each
tenant must have its own namespace. UPN, SMTP, and SIP namespaces cannot
be shared across tenants.

==== What about hybrid components and Microsoft 365 inter-tenant collaboration?

On-premises hybrid components, such as an Exchange organization and
Azure AD Connect, cannot be split across multiple tenants.
