= How modern authentication works for Office 2013 and Office 2016 client apps
:audience: Admin
:author: MSFTTracyP
:description: Learn how Microsoft 365 modern authentication features work differently for Office 2013 and 2016 client apps.
:f1.keywords: ["CSH"]
:manager: scotv
:ms.assetid: e4c45989-4b1a-462e-a81b-2a13191cf517
:ms.author: tracyp
:ms.collection: ["M365-security-compliance"]
:ms.custom: ["Adm_O365", "seo-marvel-apr2020"]
:ms.date: 8/1/2017
:ms.localizationpriority: medium
:ms.service: microsoft-365-enterprise
:ms.topic: conceptual
:search.appverid: ["MET150", "MOE150", "MED150", "GMA150", "GPA150", "GEA150", "BCS160"]

== How modern authentication works for Office 2013, Office 2016, and Office 2019 client apps

_This article applies to both Microsoft 365 Enterprise and Office 365 Enterprise._

Read this article to learn how Office 2013, Office 2016, and Office 2019 client apps use modern authentication features based on the authentication configuration on the Microsoft 365 tenant for Exchange Online, SharePoint Online, and Skype for Business Online.

____
[!NOTE] Legacy client apps, such as Office 2010 and Office for Mac 2011, do not support modern authentication and can only be used with basic authentication.
____

=== Availability of modern authentication for Microsoft 365 services

For the Microsoft 365 services, the default state of modern authentication is:

* Turned *on* for Exchange Online by default.
See https://support.office.com/article/58018196-f918-49cd-8238-56f57f38d662[Enable or disable modern authentication in Exchange Online] to turn it off or on.
* Turned *on* for SharePoint Online by default.
* Turned *on* for Skype for Business Online by default.
See https://social.technet.microsoft.com/wiki/contents/articles/34339.skype-for-business-online-enable-your-tenant-for-modern-authentication.aspx[Enable Skype for Business Online for modern authentication]to turn it off or on.

____
[!NOTE] For tenants created *before* August 1, 2017, modern authentication is turned *off* by default for Exchange Online and Skype for Business Online.
____

=== Sign-in behavior of Office client apps

Office 2013 client apps support legacy authentication by default.
Legacy means that they support either Microsoft Online Sign-in Assistant or basic authentication.
In order for these clients to use modern authentication features, the Windows client must have registry keys set.
For instructions, see https://support.office.com/article/7dc1c01a-090f-4971-9677-f1b192d6c910[Enable Modern Authentication for Office 2013 on Windows devices].

To enable modern authentication for any devices running Windows (for example on laptops and tablets), that have Microsoft Office 2013 installed, you need to set the following registry keys.
The keys have to be set on each device that you want to enable for modern authentication:

[cols="<,^,>"]
|===
| *Registry key* | *Type* | *Value*

| HKCU\SOFTWARE\Microsoft\Office\15.0\Common\Identity\EnableADAL
| REG_DWORD
| 1

| HKCU\SOFTWARE\Microsoft\Office\15.0\Common\Identity\Version
| REG_DWORD
| 1
|===

Read xref:./hybrid-modern-auth-overview.adoc[How to use Modern Authentication (ADAL) with Skype for Business] to learn about how it works with Skype for Business.

Office 2016 and Office 2019 clients support modern authentication by default, and no action is needed for the client to use these new flows.
However, explicit action is needed to use legacy authentication.

Click the links below to see how Office 2013, Office 2016, and Office 2019 client authentication works with the Microsoft 365 services depending on whether or not modern authentication is turned on.

* link:modern-auth-for-office-2013-and-2016.md#BK_EchangeOnline[Exchange Online]
* link:modern-auth-for-office-2013-and-2016.md#BK_SharePointOnline[SharePoint Online]
* link:modern-auth-for-office-2013-and-2016.md#BK_SFBO[Skype for Business Online]

+++<a name="BK_EchangeOnline">++++++</a>+++

==== Exchange Online

The following table describes the authentication behavior for Office 2013, Office 2016, and Office 2019 client apps when they connect to Exchange Online with or without modern authentication.

|===
| ***Office client app version*** | ***Registry key present?*** | ***Modern authentication on?*** | ***Authentication behavior with modern authentication turned on for the tenant (default)*** | ***Authentication behavior with modern authentication turned off for the tenant***

| Office 2019  +
| No, + AlwaysUseMSOAuthForAutoDiscover = 1 +
| Yes  +
| Forces modern authentication on Outlook 2013, 2016, or 2019.
+ https://support.microsoft.com/help/3126599/outlook-prompts-for-password-when-modern-authentication-is-enabled[More info]
| Forces modern authentication within the Outlook client.
+

| Office 2019  +
| No, or EnableADAL = 1  +
| Yes  +
| Modern authentication is attempted first.
If the server refuses a modern authentication connection, then basic authentication is used.
Server refuses modern authentication when the tenant is not enabled.
+
| Modern authentication is attempted first.
If the server refuses a modern authentication connection, then basic authentication is used.
Server refuses modern authentication when the tenant is not enabled.
+

| Office 2019  +
| Yes, EnableADAL = 1  +
| Yes  +
| Modern authentication is attempted first.
If the server refuses a modern authentication connection, then basic authentication is used.
Server refuses modern authentication when the tenant is not enabled.
+
| Modern authentication is attempted first.
If the server refuses a modern authentication connection, then basic authentication is used.
Server refuses modern authentication when the tenant is not enabled.
+

| Office 2019  +
| Yes, EnableADAL=0  +
| No  +
| Basic authentication  +
| Basic authentication  +

| Office 2016  +
| No, + AlwaysUseMSOAuthForAutoDiscover = 1 +
| Yes  +
| Forces modern authentication on 2013, 2016, or 2019.
+ https://support.microsoft.com/help/3126599/outlook-prompts-for-password-when-modern-authentication-is-enabled[More info]
| Forces modern authentication within the Outlook client.
+

| Office 2016  +
| No, or EnableADAL = 1  +
| Yes  +
| Modern authentication is attempted first.
If the server refuses a modern authentication connection, then basic authentication is used.
Server refuses modern authentication when the tenant is not enabled.
+
| Modern authentication is attempted first.
If the server refuses a modern authentication connection, then basic authentication is used.
Server refuses modern authentication when the tenant is not enabled.
+

| Office 2016  +
| Yes, EnableADAL = 1  +
| Yes  +
| Modern authentication is attempted first.
If the server refuses a modern authentication connection, then basic authentication is used.
Server refuses modern authentication when the tenant is not enabled.
+
| Modern authentication is attempted first.
If the server refuses a modern authentication connection, then basic authentication is used.
Server refuses modern authentication when the tenant is not enabled.
+

| Office 2016  +
| Yes, EnableADAL=0  +
| No  +
| Basic authentication  +
| Basic authentication  +

| Office 2013  +
| No  +
| No  +
| Basic authentication  +
| Basic authentication  +

| Office 2013  +
| Yes, EnableADAL = 1  +
| Yes  +
| Modern authentication is attempted first.
If the server refuses a modern authentication connection, then basic authentication is used.
Server refuses modern authentication when the tenant is not enabled.
+
| Modern authentication is attempted first.
If the server refuses a modern authentication connection, then basic authentication is used.
Server refuses modern authentication when the tenant is not enabled.
+
|===

+++<a name="BK_SharePointOnline">++++++</a>+++

==== SharePoint Online

The following table describes the authentication behavior for Office 2013, Office 2016, and Office 2019 client apps when they connect to SharePoint Online with or without modern authentication.

|===
| ***Office client app version*** | ***Registry key present?*** | ***Modern authentication on?*** | ***Authentication behavior with modern authentication turned on for the tenant (default)*** | ***Authentication behavior with modern authentication turned off for the tenant***

| Office 2019  +
| No, or EnableADAL = 1  +
| Yes  +
| Modern authentication only.
+
| Failure to connect.
+

| Office 2019  +
| Yes, EnableADAL = 1  +
| Yes  +
| Modern authentication only.
+
| Failure to connect.
+

| Office 2019  +
| Yes, EnableADAL = 0  +
| No  +
| Microsoft Online Sign-in Assistant only.
+
| Microsoft Online Sign-in Assistant only.
+

| Office 2016  +
| No, or EnableADAL = 1  +
| Yes  +
| Modern authentication only.
+
| Failure to connect.
+

| Office 2016  +
| Yes, EnableADAL = 1  +
| Yes  +
| Modern authentication only.
+
| Failure to connect.
+

| Office 2016  +
| Yes, EnableADAL = 0  +
| No  +
| Microsoft Online Sign-in Assistant only.
+
| Microsoft Online Sign-in Assistant only.
+

| Office 2013  +
| No  +
| No  +
| Microsoft Online Sign-in Assistant only.
+
| Microsoft Online Sign-in Assistant only.
+

| Office 2013  +
| Yes, EnableADAL = 1  +
| Yes  +
| Modern authentication only.
+
| Failure to connect.
+
|===

==== Skype for Business Online

+++<a name="BK_SFBO">++++++</a>+++

The following table describes the authentication behavior for Office 2013, Office 2016, and Office 2019 client apps when they connect to Skype for Business Online with or without modern authentication.

|===
| ***Office client app version*** | ***Registry key present?*** | ***Modern authentication on?*** | ***Authentication behavior with modern authentication turned on for the tenant*** | ***Authentication behavior with modern authentication turned off for the tenant (default)***

| Office 2019  +
| No, or EnableADAL = 1  +
| Yes  +
| Modern authentication is attempted first.
If the server refuses a modern authentication connection, then Microsoft Online Sign-in Assistant is used.
Server refuses modern authentication when Skype for Business Online tenants are not enabled.
+
| Modern authentication is attempted first.
If the server refuses a modern authentication connection, then Microsoft Online Sign-in Assistant is used.
Server refuses modern authentication when Skype for Business Online tenants are not enabled.
+

| Office 2019  +
| Yes, EnableADAL = 1  +
| Yes  +
| Modern authentication is attempted first.
If the server refuses a modern authentication connection, then Microsoft Online Sign-in Assistant is used.
Server refuses modern authentication when Skype for Business Online tenants are not enabled.
+
| Modern authentication is attempted first.
If the server refuses a modern authentication connection, then Microsoft Online Sign-in Assistant is used.
Server refuses modern authentication when Skype for Business Online tenants are not enabled.
+

| Office 2019  +
| Yes, EnableADAL = 0  +
| No  +
| Microsoft Online Sign-in Assistant only.
+
| Microsoft Online Sign-in Assistant only.
+

| Office 2016  +
| No, or EnableADAL = 1  +
| Yes  +
| Modern authentication is attempted first.
If the server refuses a modern authentication connection, then Microsoft Online Sign-in Assistant is used.
Server refuses modern authentication when Skype for Business Online tenants are not enabled.
+
| Modern authentication is attempted first.
If the server refuses a modern authentication connection, then Microsoft Online Sign-in Assistant is used.
Server refuses modern authentication when Skype for Business Online tenants are not enabled.
+

| Office 2016  +
| Yes, EnableADAL = 1  +
| Yes  +
| Modern authentication is attempted first.
If the server refuses a modern authentication connection, then Microsoft Online Sign-in Assistant is used.
Server refuses modern authentication when Skype for Business Online tenants are not enabled.
+
| Modern authentication is attempted first.
If the server refuses a modern authentication connection, then Microsoft Online Sign-in Assistant is used.
Server refuses modern authentication when Skype for Business Online tenants are not enabled.
+

| Office 2016  +
| Yes, EnableADAL = 0  +
| No  +
| Microsoft Online Sign-in Assistant only.
+
| Microsoft Online Sign-in Assistant only.
+

| Office 2013  +
| No  +
| No  +
| Microsoft Online Sign-in Assistant only.
+
| Microsoft Online Sign-in Assistant only.
+

| Office 2013  +
| Yes, EnableADAL = 1  +
| Yes  +
| Modern authentication is attempted first.
If the server refuses a modern authentication connection, then Microsoft Online Sign-in Assistant is used.
Server refuses modern authentication when Skype for Business Online tenants are not enabled.
+
| Microsoft Online Sign-in Assistant only.
+
|===

=== See also

xref:../admin/security-and-compliance/enable-modern-authentication.adoc[Enable Modern Authentication for Office 2013 on Windows devices]

xref:../admin/security-and-compliance/multi-factor-authentication-microsoft-365.adoc[Multi-factor authentication for Microsoft 365]

https://support.microsoft.com/office/sign-in-to-microsoft-365-with-multi-factor-authentication-2b856342-170a-438e-9a4f-3c092394d3cb[Sign in to Microsoft 365 with multi-factor authentication]

xref:microsoft-365-overview.adoc[Microsoft 365 Enterprise overview]
