= 
kelleyvice-msft

== Monitor Microsoft 365 connectivity

Once you’ve deployed Microsoft 365, you can maintain Microsoft 365
connectivity using some of the tools and techniques below. You’ll want
to understand the official
link:/office365/servicedescriptions/office-365-platform-service-description/service-health-and-continuity[Service
Health and Continuity] guidelines as well as our
https://support.office.com/article/fd16c8d2-4799-4c39-8fd7-045f06640166[Best
practices for using Microsoft 365 on a slow network]. You’ll also want
to grab the
https://blogs.office.com/2015/03/13/administer-on-the-go-with-the-updated-office-365-admin-app/[Microsoft
365 admin app] and bookmark our
https://support.office.com/article/17d3ff3f-3601-466e-b5a1-482b31cfb791[Microsoft
365 for business - Admin Help].

=== Monitoring Microsoft 365 Connectivity

[width="100%",cols="<50%,<50%",options="header",]
|===
|Type of monitoring |Description
|*Getting notified of new Microsoft 365 endpoints* |If you’re
https://support.office.com/article/99cab9d4-ef59-4207-9f2b-3728eb46bf9a[Managing
Microsoft 365 endpoints], you’ll want to receive notifications when we
publish new endpoints, you can subscribe to our RSS feed using your
favorite RSS reader. Here is how to
https://go.microsoft.com/fwlink/p/?LinkId=532416[subscribe via Outlook]
or you can https://go.microsoft.com/fwlink/p/?LinkId=532417[have the RSS
feed updates emailed to you].

|*Use System Center to Monitor Microsoft 365* |If you’re using Microsoft
System Center, you can download the
https://www.microsoft.com/download/details.aspx?id=103379[Microsoft
System Center Operations Manager Management Pack for Microsoft 365] to
begin monitoring Microsoft 365 today. For more detailed guidance, please
see the management pack operations guide.

|*Monitoring the health of Azure ExpressRoute* |If you are connecting to
Microsoft 365 using Azure ExpressRoute for Microsoft 365, you’ll want to
ensure that you’re using both the Microsoft 365 Service Health Dashboard
as well as the Azure
https://azure.microsoft.com/blog/reduce-troubleshooting-time-with-azure-resource-health/[Reducing
troubleshooting time with Azure Resource health]

|*Using Azure AD Connect Health with AD FS* |If you’re using AD FS for
Single Sign-On with Microsoft 365, you’ll want to begin
link:/azure/active-directory/hybrid/how-to-connect-health-adfs[using
Azure AD Connect Health to monitor your AD FS infrastructure].

|*Programmatically monitor Microsoft 365* |Refer to our guidance on the
link:/office/office-365-management-api/office-365-management-apis-overview[Microsoft
365 Management API].
|===

Here’s a short link you can use to come back:
link:[https://aka.ms/monitorconnectivity365]

=== Related topics

link:configure-services-and-applications.md[Configure Microsoft 365
Enterprise services and applications]

link:get-your-organization-ready-for-office-365.md[Get your organization
ready for Microsoft 365 Enterprise]

link:network-planning-and-performance.md[Network planning and
performance tuning for Microsoft 365]

link:microsoft-365-integration.md[Microsoft 365 integration with
on-premises environments]

link:managing-office-365-endpoints.md[Managing Microsoft 365 endpoints]
