= 
MikePlumleyMSFT

== Microsoft 365 Multi-Geo eDiscovery configuration

link:../compliance/overview-ediscovery-20.md[eDiscovery (Premium)
capabilities] allow a Multi-Geo eDiscovery administrator to search all
of the _Geographies_ without needing to utilize a ``Region'' security
filter. Data is exported to the Azure instance of the _Primary
Provisioned Geography_ location of the multi-geo _Tenant_.

Without eDiscovery (Premium) capabilities, an eDiscovery manager or
administrator of a Multi-Geo _Tenant_ will be able to conduct eDiscovery
only in the _Primary Provisioned Geography_ location of that _Tenant_.
To support the ability to conduct eDiscovery for _Satellite Geography_
locations, a new compliance security filter parameter named ``Region''
is available via PowerShell. This parameter can be used by _Tenants_
whose _Primary Provisioned Geography_ location is in North America,
Europe, or Asia Pacific. eDiscovery (Premium) is recommended for
_Tenants_ whose _Primary Provisioned Geography_ location is not in North
America, Europe, or Asia Pacific and who need to perform eDiscovery
across _Satellite Geography_ locations.

The Microsoft 365 global administrator must assign eDiscovery Manager
permissions to allow others to perform eDiscovery and assign a
``Region'' parameter in their applicable Compliance Security Filter to
specify the _Geography_ for conducting eDiscovery as _Satellite
Geography_ location, otherwise, no eDiscovery will be carried out for
the _Satellite Geography_ location. Only one ``Region'' security filter
per user is supported.

When the eDiscovery Manager or Administrator role is set for a
particular _Satellite Geography_ location, the eDiscovery Manager or
Administrator will only be able to perform eDiscovery search actions
against the SharePoint sites and OneDrive sites located in that
_Satellite Geography_ location. If an eDiscovery Manager or
Administrator attempts to search SharePoint or OneDrive sites outside
the specified _Satellite Geography_ location, no results will be
returned. Also, when the eDiscovery Manager or Administrator for a
_Satellite Geography_ location triggers an export, data is exported to
the Azure instance of that region. This helps organizations stay in
compliance by not allowing content to be exported across controlled
borders.

____
[!NOTE] If it’s necessary for an eDiscovery Manager to search across
multiple SharePoint _Satellite Geography_ locations, another user
account will need to be created for the eDiscovery Manager which
specifies the alternate _Satellite Geography_ location where the
OneDrive or SharePoint sites are located.
____

{empty}[!INCLUDE
link:../includes/microsoft-365-multi-geo-locations.md[Microsoft 365
Multi-Geo locations]]

To set the Compliance Security Filter for a Region:

[arabic]
. link:/powershell/exchange/connect-to-scc-powershell[Connect to
Microsoft 365 Security & Compliance PowerShell]
. Use the following syntax:
+
[source,powershell]
----
New-ComplianceSecurityFilter -Action All -FilterName <TheNameYouWantToAssign> -Region <RegionValue> -Users <UserPrincipalName>
----
+
For example:
+
[source,powershell]
----
New-ComplianceSecurityFilter -Action All -FilterName "NAM eDiscovery Managers" -Region NAM -Users adwood@contoso.onmicrosoft.com
----

See the
link:/powershell/module/exchange/new-compliancesecurityfilter[New-ComplianceSecurityFilter]
article for additional parameters and syntax.
