= Plan your upgrade from Office 2007 or 2010 servers and clients
:audience: ITPro
:author: kelleyvice-msft
:description: This article contains resources for users using Office 2007 or Office 2010 to help them plan their upgrade.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.assetid: b2acaeca-4986-40f4-92b7-a1bdd06e549d
:ms.author: kvice
:ms.collection: Ent_O365
:ms.custom: ["seo-marvel-apr2020"]
:ms.localizationpriority: medium
:ms.service: microsoft-365-enterprise
:ms.topic: overview
:search.appverid: ["MET150"]

== Plan your upgrade from Office 2007 or Office 2010 servers and clients

_This article applies to both Microsoft 365 for Enterprise and Office 365 for Enterprise._

If your organization uses old versions of Office products and servers, now is a great time to start planning your upgrade.
Office 2007 products and services have reached their xref:upgrade-from-office-2007-servers-and-products.adoc[end of support].
For Office 2010 products and services:

* Office 2010 and Exchange 2010 reached their end of support on _October 13, 2020_.
* SharePoint 2010 and Project Server 2010 will reach their end of support on _April 13, 2021_.

For more information, see xref:upgrade-from-office-2010-servers-and-products.adoc[Upgrade from Office 2010 servers and clients].

Use the resources in this article to get started on your upgrade.

=== What is Microsoft 365?

https://www.microsoft.com/microsoft-365[Microsoft 365] is a combination of innovative Office apps, intelligent cloud services, and world-class security that's designed to help you achieve more.

Microsoft 365 includes the licenses and capabilities to help ensure that your organization is working on the latest Windows operating system.
It also ensures that your Windows, iOS, and Android devices are enrolled with and secured by policies that require authentication and data protection.
Additionally, Windows 10 and your Microsoft 365 Apps for Enterprise (previously named Office 365 ProPlus) client software is continually updated to include the latest features and security updates.

Microsoft 365 is the way to digitally transform your business with constantly improving devices and productivity experiences that are enabled and secured by the Microsoft cloud.

|===
| Resource | Description

| https://www.microsoft.com/microsoft-365[Microsoft 365]
| Get information about the versions of Microsoft 365.

| link:../admin/index.yml[Microsoft 365 for Business documentation]
| Get detailed information about the version of Microsoft 365 for small and medium businesses.

| link:/microsoft-365/education/[Microsoft 365 for Education documentation]
| Get detailed information about the version of Microsoft 365 for educational organizations.

| link:./index.yml[Microsoft 365 for Enterprise documentation]
| Get detailed information about the version of Microsoft 365 for enterprise organizations.

|
|
|===

=== What happens if I don't upgrade?

You can choose not to upgrade at this time.
Your on-premises servers and applications will continue to run.
But when you no longer receive security updates or support options, your organization could be vulnerable to security breaches.
We strongly recommend that you plan your upgrade soon.
You can upgrade to Microsoft 365 or to newer versions of your on-premises servers and applications.

=== What upgrade options are available?

Organizations should consider several upgrade options:

* *Upgrade your on-premises servers and applications.* If you're using Office products and server applications on-premises, see the following planning content: +
+
|===
| Office 2007 products and services | Office 2010 products and services

| link:/DeployOffice/office-2007-end-support-roadmap[Office 2007] (Desktop)
| link:/DeployOffice/office-2010-end-support-roadmap[Office 2010] (Desktop)

| xref:exchange-2007-end-of-support.adoc[Exchange 2007]
| xref:exchange-2010-end-of-support.adoc[Exchange 2010]

| xref:sharepoint-2007-end-of-support.adoc[SharePoint 2007]
| xref:upgrade-from-sharepoint-2010.adoc[SharePoint 2010]

| link:/skypeforbusiness/plan-your-deployment/upgrade[Office Communications Server]
| link:/skypeforbusiness/plan-your-deployment/upgrade[Lync Server 2010]

| xref:project-server-2007-end-of-support.adoc[Project Server 2007]
| xref:project-server-2010-end-of-support.adoc[Project Server 2010]

| xref:pps-2007-end-of-support.adoc[PerformancePoint Server 2007]
|
|===

* *Implement a hybrid solution with Microsoft 365 or Office 365.* A hybrid solution uses your on-premises servers and applications and their cloud equivalents.
If you're moving to the cloud in phases or you must keep some server and applications on-premises, a hybrid solution might be right for your organization.
For more information, see xref:../solutions/cloud-architecture-models.adoc[Microsoft cloud architecture models].
* *Move to the cloud with Microsoft 365 or Office 365.* For many customers, moving to the cloud is an efficient and cost-effective solution.
A complete move to the cloud makes setup and ongoing management easier.
This option seamlessly provides all the latest features and security updates.
For more information, see the <<what-is-microsoft-365,What is Microsoft 365?>> section in this article.

=== Can I get help for my organization?

If you want help with planning your upgrade, consider one or more of the following options:

* Work with a partner or volume licensing specialist.
https://support.office.com/article/b6c18a9b-2aed-4c84-9d75-af709160258c.aspx[Find your Microsoft 365 partner or reseller].
* If your organization purchases a qualifying number of Microsoft 365 licenses, our FastTrack team can help you through the setup process.
For more information, see https://www.microsoft.com/fasttrack/microsoft-365[FastTrack for Microsoft 365].
* If you're part of a small organization, or if you prefer to handle your organization's Office upgrade yourself, see link:/office365/admin/setup/upgrade-users-to-latest-office-client[Upgrade your Microsoft 365 Business users to the latest Office client].

=== I'm a home user. What do I do?

If you're using Office 2007 or Office 2010 at home, consider the following upgrade options:

* *Use Office in a browser for free.* Create, view, and edit Office files in your browser.
Get access to those files from just about any device that has internet access.
+
https://products.office.com/office-online/documents-spreadsheets-presentations-office-online[Office on the web] includes https://go.microsoft.com/fwlink/p/?linkid=746664[Word for the web], https://go.microsoft.com/fwlink/p/?linkid=746665[Excel for the web], https://go.microsoft.com/fwlink/p/?linkid=746666[PowerPoint for the web], https://go.microsoft.com/fwlink/p/?linkid=746674[OneNote for the web], https://go.microsoft.com/fwlink/p/?linkid=746675[Sway], https://go.microsoft.com/fwlink/p/?linkid=746676[Email], https://go.microsoft.com/fwlink/p/?linkid=746678[Calendar], and https://go.microsoft.com/fwlink/p/?linkid=746679[OneDrive].
To get started, visit https://office.com[Office.com] and sign in by using your https://account.microsoft.com/account[Microsoft account].
If you don't have a Microsoft account, you can create one at https://office.com[Office.com].

* *Try Microsoft 365 Family.* Start a trial of https://www.microsoft.com/microsoft-365/p/microsoft-365-family/cfq7ttc0k5dm?rtc=2&activetab=pivot:overviewtab[Microsoft 365 Family] to see how it works for you.
With Microsoft 365 Family, you'll enjoy cloud storage with OneDrive.
+
Support for Windows 7 https://www.microsoft.com/microsoft-365/windows/end-of-windows-7-support[ended on January 14, 2020].
The versions of Word, Excel, PowerPoint, Outlook, Publisher, and Access that are provided with Office 365 Home or Office 365 Personal and that run on Windows 7 devices receive security updates but not feature updates.
To continue receiving feature updates for these applications, https://support.microsoft.com/help/12435/windows-10-upgrade-faq[upgrade your Windows 7 devices to Windows 10].

* *Purchase Office Home & Student.* If you choose this option, you make a one-time purchase and then install Office on your Windows PC or Mac.
This purchase isn't a subscription;
it's a one-time, perpetual-use license for one computer.
View the https://office.com/systemrequirements[requirements] and then choose a version.
 ** If your Windows PC is running Windows 10, consider getting https://www.microsoft.com/p/office-home-student-2019/cfq7ttc0k7c8[Office Home & Student 2019].
 ** If your Windows PC is running Windows 7, 8, or 8.1 and you're not upgrading to Windows 10 now, consider getting Office Home & Student 2016 or another edition of Microsoft Office.
You can get it from an authorized reseller.
+
Support for Windows 7 https://www.microsoft.com/microsoft-365/windows/end-of-windows-7-support[ended on January 14, 2020].
Microsoft no longer provides security updates for it.
Upgrade your Windows 7 devices to Windows 10 for continued security and feature updates and ongoing support.

If you choose not to upgrade now, your Office apps will continue to run according to the https://support.microsoft.com/lifecycle/search/13615[timelines].
However, to get security updates or new and improved features, you need to upgrade.

=== Next steps

* xref:upgrade-from-office-2007-servers-and-products.adoc[Upgrade from Office 2007 servers and clients]
* xref:upgrade-from-office-2010-servers-and-products.adoc[Upgrade from Office 2010 servers and clients]

=== Related topics

link:/lifecycle/[Microsoft Lifecycle Policy]
