= Project Server 2007 end of support roadmap
:audience: ITPro
:author: kelleyvice-msft
:description: On October 10, 2017, support ended for Project Server 2007, Project Portfolio Server, and Project 2007. Use this article to plan your upgrade now.
:f1.keywords: ["CSH"]
:manager: scotv
:ms.assetid: d379018f-72b7-4284-b40a-6c23c8ae38fe
:ms.author: kvice
:ms.collection: Ent_O365
:ms.custom: IT_ProjectAdmin
:ms.date: 1/31/2018
:ms.localizationpriority: medium
:ms.service: microsoft-365-enterprise
:ms.topic: conceptual
:search.appverid: ["MET150", "ZPJ120", "PJU120", "PJW120"]

== Project Server 2007 end of support roadmap

_This article applies to both Microsoft 365 Enterprise and Office 365 Enterprise._

Support ended for Office 2007 servers and applications in 2017, and you need to consider plans for migration.
If you're currently using Project Server 2007 and related products, note the following end-of-support dates:

|===
| *Product* | *End of support date*

| Project Server 2007  +
| October 10, 2017  +

| Project Portfolio Server 2007  +
| October 10, 2017  +

| Project 2007 Standard  +
| October 10, 2017  +

| Project 2007 Professional  +
| October 10, 2017  +
|===

For more information about Office 2007 servers reaching retirement, see xref:upgrade-from-office-2007-servers-and-products.adoc[Upgrade from Office 2007 servers and client products].

=== What does _end of support_ mean?

Most Microsoft products have a support lifecycle during which they get new features, bug fixes, security fixes, and so on.
This lifecycle typically lasts for 10 years from the product's initial release.
The end of this lifecycle is known as the product's end of support.
Because Project Server 2007 reached its end of support on October 10, 2017, Microsoft no longer provides:

* Technical support for problems that may occur.
* Bug fixes for issues that may impact the stability and usability of the server.
* Security fixes for vulnerabilities that may make the server vulnerable to security breaches.
* Time zone updates.

Your installation of Project Server 2007 will continue to run after this date.
But because of the changes listed previously, we strongly recommend that you migrate from Project Server 2007 as soon as practical.

=== What are my options?

If you're using Project Server 2007, you need to explore your migration options, which are:

* Migrate to Project Online
* Migrate to a newer on-premises version of Project Server (preferably Project Server 2016)

|===
| *Why would I prefer to migrate to Project Online* | *Why would I prefer to migrate to Project Server 2016*

| I have mobile users.
+  + Costs to migrate are a significant concern (hardware, software, hours, and effort to implement).
+  + After migration, costs to maintain my environment are a major concern (for example, automatic updates, guaranteed uptime, and so on).
+
| Business rules restrict me from operating my business in the cloud.
+  + I need control of updates to my environment.
|===

____
[!NOTE] For more information about options for moving from your Office 2007 servers, see xref:upgrade-from-office-2007-servers-and-products.adoc[Resources to help you upgrade from Office 2007 servers and clients].
Note that Project Server doesn't support a hybrid configuration, because Project Server and Project Online can't share the same resource pool.
____

=== Important considerations when you migrate from Project Server 2007

Consider the following when you plan to migrate from Project Server 2007:

* *Get help from a Microsoft Partner* - Upgrading from Project Server 2007 can be challenging and requires much preparation and planning.
It might be especially challenging if you weren't the person who set up Project Server 2007 originally.
Fortunately, there are Microsoft Partners who can help, whether you plan to migrate to Project Server 2016 or to Project Online.
Search for a Microsoft Partner to help with your migration on the https://go.microsoft.com/fwlink/p/?linkid=841249[Microsoft Partner Center].
Search on the term  _Gold Project and Portfolio Management_ to view a list of all Microsoft Partners who have expertise in Project.
* *Plan for your customizations* - Many of the customizations you made in your Project Server 2007 environment might not work when you migrate to Project Server 2016 or Project Online.
There are significant differences in Project Server architecture between versions.
The required operating systems, database servers, and client web browsers that are supported also differ.
Plan how to test or rebuild your customizations for the new environment.
Planning also provides a good opportunity to consider whether each customization is still needed.
For more information, see link:/SharePoint/upgrade-and-update/create-a-communication-plan-for-the-upgrade-to-sharepoint-2013[Create a plan for current customizations during upgrade to SharePoint 2013].
* *Time and patience* - Upgrade planning, execution, and testing will take time and effort, especially if you upgrade to Project Server 2016.
For example, if you migrate from Project Server 2007 to Project Server 2016, you first need to migrate to Project Server 2010, check your data, and then do the same thing when you migrate to each successive version.
You might want to check with a Microsoft Partner to get estimates of how long it will take and what it will cost.

=== Migrate to Project Online

If you choose to migrate from Project Server 2007 to Project Online, you can do the following to manually migrate your project plan data:

. Save your project plans from Project Server 2003 to .mpp format.
. In Project Professional 2013, Project Professional 2016, or the Project Online Desktop Client, open each .mpp file, and then save and publish it to Project Online.

You can manually create your Microsoft Project Web App (PWA) configuration in Project Online.
For example, recreate any needed custom fields or enterprise calendars.
Microsoft Partners can also help with this process.

Key resources:

|===
| *Resource* | *Description*

| https://support.office.com/article/e3e5f64f-ada5-4f9d-a578-130b2d4e5f11[Get started with Project Online] +
| How to set up and use Project Online +

| link:/office365/servicedescriptions/project-online-service-description/project-online-service-description[Project Online Service Descriptions] +
| Information about the different Project Online plans that are available to you +
|===

=== Migrate to a newer on-premises version of Project Server

We strongly believe that you get the best value and user experience by migrating to Project Online.
But we also understand that some organizations need to keep project data in an on-premises environment.
If you choose to keep your project data on-premises, you can migrate your Project Server 2007 environment to Project Server 2010, Project Server 2013, or Project Server 2016.

If you can't migrate to Project Online, we recommend that you migrate to Project Server 2016.
Project Server 2016 includes all the features of previous releases of Project Server.
It most closely matches the experience available with Project Online, although some features are available only in Project Online.

After each migration, you should check that your data migrated successfully.

____
[!NOTE]
____

==== How do I migrate to Project Server 2016?

Architectural differences between Project Server 2007 and Project Server 2016 prevent a direct migration path.
So you have to migrate your Project Server 2007 data to each successive version of Project Server until you reach Project Server 2016.

Follow these steps to Project Server 2016:

. Migrate from Project Server 2007 to Project Server 2010.
. Migrate from Project Serve 2010 to Project Server 2013.
. Migrate from Project Server 2013 to Project Server 2016.

After each migration, make sure that your data migrated successfully.

==== Step 1: Migrate from Project Server 2007 to Project Server 2010

For a comprehensive description of what you need to do to upgrade from Project Server 2007 to Project Server 2010, see link:/previous-versions/office/project-server-2010/gg502590(v=office.14)[Upgrade to Project Server 2010].

Key resources:

|===
| *Resource* | *Description*

| link:/previous-versions/office/project-server-2010/ee662496(v=office.14)[Project Server 2010 upgrade overview] +
| A high-level view of what you need to do to upgrade from Project Server 2007 to Project Server 2010 +

| link:/previous-versions/office/project-server-2010/ff603505(v=office.14)[Plan to Upgrade to Project Server 2010] +
| Planning considerations when you upgrade from Project Server 2007 to Project Server 2010, including System Requirements  +
|===

===== How do I upgrade?

For details, see link:/previous-versions/office/project-server-2010/gg502590(v=office.14)[Upgrade to Project Server 2010].
But it's important to understand that there are two distinct methods you can use to upgrade:

* *Database-attach upgrade:* This method only upgrades the content for your environment, not the configuration settings.
It's required if you're upgrading from Office Project Server 2007 deployed on hardware that only supports a 32-bit server operating system.
There are two types of database-attach upgrade methods:
 ** *Database-attach _full upgrade_* - Migrates the project data stored in the Office Project Server 2007 databases, plus the Microsoft Project Web App site data stored in a SharePoint content database.
 ** *Database-attach _core upgrade_* - Migrates only the project data stored in the Project Server databases.
* *In-place upgrade*: The configuration data for the farm and all content on the farm is upgraded on the existing hardware in a fixed order.
When you start the upgrade process, setup takes the entire farm offline.
The web sites and Microsoft Project Web App sites are unavailable until the upgrade is finished, and then setup restarts the server.
After you begin an in-place upgrade, you can't pause the upgrade or roll back to the previous version.
It's best to make a mirrored image of your production environment and do the in-place upgrade to this environment, not in your production environment.

Additional resources:

* link:/samples/browse/?redirectedfrom=TechNet-Gallery[SuperFlow for Microsoft Project Server 2010 Upgrade]
* link:/samples/browse/?redirectedfrom=TechNet-Gallery[Migration from Project Server 2007 to Project Server 2010]
* link:/previous-versions/office/project-server-2010/gg314581(v=office.14)[Upgrade considerations for Project Web App Web Parts]
* link:/previous-versions/office/developer/office-2010/ms481966(v=office.14)[Project Software Development Kit (SDK)]

==== Step 2: Migrate to Project Server 2013

After you verify that your data migrated successfully, the next step is to migrate to Project Server 2013.

For a comprehensive description of what you need to do to upgrade from Project Server 2010 to Project Server 2013, see link:/project/upgrade-to-project-server-2016[Upgrade to Project Server 2013].

Key resources:

|===
| *Resource* | *Description*

| link:/project/upgrade-to-project-server-2016[Overview of the Project Server 2013 upgrade process] +
| Overview of what you need to do to upgrade from Project Server 2010 to Project Server 2013  +

| link:/project/plan-for-upgrade-to-project-server-2016[Plan to upgrade to Project Server 2013] +
| Planning considerations when you upgrade from Project Server 2010 to Project Server 2013, including System Requirements +
|===

===== Things to know about upgrading to this version

link:/project/what-s-new-in-project-server-2013-upgrade[What's new in Project Server 2013 upgrade] describes important changes for upgrade for this version.
The most notable are:

* There's no in-place upgrade to Project Server 2013.
The database-attach method is the only supported method for upgrading from Project Server 2010 to Project Server 2013.
* The upgrade process will not only convert your Project Server 2010 data to Project Server 2013 format but will also consolidate the four Project Server 2010 databases into a single Project Web App database.
* In the 2013 versions, both SharePoint Server and Project Server changed to claims-based authentication.
If you're using classic authentication, you need to consider this factor for your upgrade.
For more information, see link:/sharepoint/security-for-sharepoint-server/security-for-sharepoint-server[Migrate from classic-mode to claims-based authentication in SharePoint 2013].

Additional resources:

* link:/project/overview-of-the-project-server-2016-upgrade-process[Overview of the upgrade process to Project Server 2013]
* link:/project/upgrading-to-project-server-2016[Upgrade your databases and Project Web App site collections (Project Server 2013)]
* https://go.microsoft.com/fwlink/p/?linkid=841270[Microsoft Project Server upgrade process diagram]
* https://go.microsoft.com/fwlink/p/?linkid=841271[The Great Database Consolidation, Project Server 2010 to 2013 Migration in 8 Easy Steps]

==== Step 3: Migrate to Project Server 2016

After you verify that your data migrated successfully, the next step is to migrate to Project Server 2016.

For a comprehensive description of what you need to do to upgrade from Project Server 2013 to Project Server 2016, see link:/project/upgrading-to-project-server-2016[Upgrade to Project Server 2016].

Key resources:

|===
| *Resource* | *Description*

| link:/previous-versions/office/project-server-2010/ee662104(v=office.14)[Overview of the Project Server 2016 upgrade process] +
| Overview of what you need to do to upgrade from Project Server 2013 to Project Server 2016 +

| link:/project/plan-for-upgrade-to-project-server-2016[Plan for upgrade to Project Server 2016] +
| Planning considerations you upgrade from Project Server 2013 to Project Server 2016 +
|===

===== Things to know about upgrading to this version

link:/project/plan-for-upgrade-to-project-server-2016[Things you need to know about Project Server 2016 upgrade] tells you some important changes for upgrade for this version, which include:

* When you create your Project Server 2016 environment to which you'll migrate your Project Server 2013 data, the Project Server 2016 installation files are included in SharePoint Server 2016.
For more information, see link:/project/deploy-project-server-2016[Deploy Project Server 2016].
* Resource plans are deprecated in Project Server 2016.
Your Project Server 2013 resource plans will be migrated to Resource Engagements in Project Server 2016 and in Project Online.
See https://support.office.com/article/73eefb5a-81fe-42bf-980e-9532b1bdc870[Overview: Resource engagements] for more information.

=== Migrate from Portfolio Server 2007

Project Portfolio Server 2007 was used with Project Server 2007 for portfolio strategy, prioritization, and optimization.
No additional versions of Project Portfolio Server were created after this version.
However, portfolio management features are available in Project Server 2016 and the Premium version of Project Online.
But data from Project Portfolio Server 2007 can't be migrated to either.
Data such as business drivers will have to be recreated.

Other resources:

* link:/office365/servicedescriptions/project-online-service-description/project-online-service-description[Project Online Service Descriptions:] See the portfolio management features that are included with Project Server 2016 and Project Online Premium.
* https://go.microsoft.com/fwlink/p/?linkid=841279[Microsoft Office Project Portfolio Server 2007 migration guide.]

=== Related topics

xref:sharepoint-2007-end-of-support.adoc[SharePoint Server 2007 end of support Roadmap]

xref:upgrade-from-office-2007-servers-and-products.adoc[Resources to help you upgrade from Office 2007 servers and clients]
