= 
kelleyvice-msft

== Remove Microsoft 365 licenses from user accounts with PowerShell

_This article applies to both Microsoft 365 Enterprise and Office 365
Enterprise._

____
[!Note] link:../admin/manage/remove-licenses-from-users.md[Learn how to
remove licenses from user accounts] with the Microsoft 365 admin center.
For a list of additional resources, see link:/admin[Manage users and
groups].
____

=== Use the Microsoft Graph PowerShell SDK

First, link:/graph/powershell/get-started#authentication[connect to your
Microsoft 365 tenant].

Assigning and removing licenses for a user requires the
User.ReadWrite.All permission scope or one of the other permissions
listed in the link:/graph/api/user-assignlicense[`Assign license' Graph
API reference page].

The Organization.Read.All permission scope is required to read the
licenses available in the tenant.

[source,powershell]
----
Connect-Graph -Scopes User.ReadWrite.All, Organization.Read.All
----

To view the licensing plan information in your organization, see the
following topics:

* link:view-licenses-and-services-with-microsoft-365-powershell.md[View
licenses and services with PowerShell]
* link:view-account-license-and-service-details-with-microsoft-365-powershell.md[View
account license and service details with PowerShell]

==== Removing licenses from user accounts

To remove licenses from an existing user account, use the following
syntax:

[source,powershell]
----
Set-MgUserLicense -UserId "<Account>" -RemoveLicenses @("<AccountSkuId1>") -AddLicenses @{}
----

This example removes the *SPE_E5* (Microsoft 365 E5) licensing plan from
the user *BelindaN@litwareinc.com*:

[source,powershell]
----
$e5Sku = Get-MgSubscribedSku -All | Where SkuPartNumber -eq 'SPE_E5'
Set-MgUserLicense -UserId "belindan@litwareinc.com" -RemoveLicenses @($e5Sku.SkuId) -AddLicenses @{}
----

To remove all licenses from a group of existing licensed users, use the
following syntax:

[source,powershell]
----
$licensedUsers = Get-MgUser -Filter 'assignedLicenses/$count ne 0' `
    -ConsistencyLevel eventual -CountVariable licensedUserCount -All `
    -Select UserPrincipalName,DisplayName,AssignedLicenses

foreach($user in $licensedUsers)
{
    $licencesToRemove = $user.AssignedLicenses | Select -ExpandProperty SkuId
    $user = Set-MgUserLicense -UserId $user.UserPrincipalName -RemoveLicenses $licencesToRemove -AddLicenses @{} 
}
----

Another way to free up a license is by deleting the user account. For
more information, see
link:delete-and-restore-user-accounts-with-microsoft-365-powershell.md[Delete
and restore user accounts with PowerShell].

=== Use the Azure Active Directory PowerShell for Graph module

____
The Set-AzureADUserLicense cmdlet is scheduled to be retired. Please
migrate your scripts to the Microsoft Graph SDK’s Set-MgUserLicense
cmdlet as described above. For more information, see
https://techcommunity.microsoft.com/t5/azure-active-directory-identity/migrate-your-apps-to-access-the-license-managements-apis-from/ba-p/2464366[Migrate
your apps to access the license managements APIs from Microsoft Graph].
____

First,
link:connect-to-microsoft-365-powershell.md#connect-with-the-azure-active-directory-powershell-for-graph-module[connect
to your Microsoft 365 tenant].

Next, list the license plans for your tenant with this command.

[source,powershell]
----
Get-AzureADSubscribedSku | Select SkuPartNumber
----

Next, get the sign-in name of the account for which you want to remove a
license, also known as the user principal name (UPN).

Finally, specify the user sign-in and license plan names, remove the
``<'' and ``>'' characters, and run these commands.

[source,powershell]
----
$userUPN="<user sign-in name (UPN)>"
$planName="<license plan name from the list of license plans>"
$license = New-Object -TypeName Microsoft.Open.AzureAD.Model.AssignedLicenses
$license.RemoveLicenses = (Get-AzureADSubscribedSku | Where-Object -Property SkuPartNumber -Value $planName -EQ).SkuID
Set-AzureADUserLicense -ObjectId $userUPN -AssignedLicenses $license
----

To remove all of the licenses for a specific user account, specify the
user sign-in name, remove the ``<'' and ``>'' characters, and run these
commands.

[source,powershell]
----
$userUPN="<user sign-in name (UPN)>"
$userList = Get-AzureADUser -ObjectID $userUPN
$Skus = $userList | Select -ExpandProperty AssignedLicenses | Select SkuID
if($userList.Count -ne 0) {
    if($Skus -is [array])
    {
        $licenses = New-Object -TypeName Microsoft.Open.AzureAD.Model.AssignedLicenses
        for ($i=0; $i -lt $Skus.Count; $i++) {
            $licenses.RemoveLicenses +=  (Get-AzureADSubscribedSku | Where-Object -Property SkuID -Value $Skus[$i].SkuId -EQ).SkuID   
        }
        Set-AzureADUserLicense -ObjectId $userUPN -AssignedLicenses $licenses
    } else {
        $licenses = New-Object -TypeName Microsoft.Open.AzureAD.Model.AssignedLicenses
        $licenses.RemoveLicenses =  (Get-AzureADSubscribedSku | Where-Object -Property SkuID -Value $Skus.SkuId -EQ).SkuID
        Set-AzureADUserLicense -ObjectId $userUPN -AssignedLicenses $licenses
    }
}
----

=== Use the Microsoft Azure Active Directory Module for Windows PowerShell

____
[!Note] The Set-MsolUserLicense and New-MsolUser (-LicenseAssignment)
cmdlets are scheduled to be retired. Please migrate your scripts to the
Microsoft Graph SDK’s Set-MgUserLicense cmdlet as described above. For
more information, see
https://techcommunity.microsoft.com/t5/azure-active-directory-identity/migrate-your-apps-to-access-the-license-managements-apis-from/ba-p/2464366[Migrate
your apps to access the license managements APIs from Microsoft Graph].
____

First,
link:connect-to-microsoft-365-powershell.md#connect-with-the-microsoft-azure-active-directory-module-for-windows-powershell[connect
to your Microsoft 365 tenant].

To view the licensing plan (*AccountSkuID*) information in your
organization, see the following topics:

* link:view-licenses-and-services-with-microsoft-365-powershell.md[View
licenses and services with PowerShell]
* link:view-account-license-and-service-details-with-microsoft-365-powershell.md[View
account license and service details with PowerShell]

If you use the *Get-MsolUser* cmdlet without using the _-All_ parameter,
only the first 500 accounts are returned.

==== Removing licenses from user accounts

To remove licenses from an existing user account, use the following
syntax:

[source,powershell]
----
Set-MsolUserLicense -UserPrincipalName <Account> -RemoveLicenses "<AccountSkuId1>", "<AccountSkuId2>"...
----

____
[!Note] PowerShell Core does not support the Microsoft Azure Active
Directory Module for Windows PowerShell module and cmdlets with *Msol*
in their name. To continue using these cmdlets, you must run them from
Windows PowerShell.
____

This example removes the *litwareinc:ENTERPRISEPACK* (Office 365
Enterprise E3) license from the user account BelindaN@litwareinc.com.

[source,powershell]
----
Set-MsolUserLicense -UserPrincipalName belindan@litwareinc.com -RemoveLicenses "litwareinc:ENTERPRISEPACK"
----

____
[!Note] You cannot use the `Set-MsolUserLicense` cmdlet to unassign
users from _canceled_ licenses. You must do this individually for each
user account in the Microsoft 365 admin center.
____

To remove all licenses from a group of existing licensed users, use
either of the following methods:

* *Filter the accounts based on an existing account attribute* To do
this, use the following syntax:

[source,powershell]
----
$userArray = Get-MsolUser -All <FilterableAttributes> | where {$_.isLicensed -eq $true}
for ($i=0; $i -lt $userArray.Count; $i++)
{
Set-MsolUserLicense -UserPrincipalName $userArray[$i].UserPrincipalName -RemoveLicenses $userArray[$i].licenses.accountskuid
}
----

This example removes all licenses from all user accounts in the Sales
department in the United States.

[source,powershell]
----
$userArray = Get-MsolUser -All -Department "Sales" -UsageLocation "US" | where {$_.isLicensed -eq $true}
for ($i=0; $i -lt $userArray.Count; $i++)
{
Set-MsolUserLicense -UserPrincipalName $userArray[$i].UserPrincipalName -RemoveLicenses $userArray[$i].licenses.accountskuid
}
----

* *Use a list of specific accounts for a specific license* To do this,
perform the following steps:

[arabic]
. Create and save a text file that contains one account on each line
like this:

[source,powershell]
----
akol@contoso.com
tjohnston@contoso.com
kakers@contoso.com
----

[arabic, start=2]
. Use the following syntax:

[source,powershell]
----
$x=Get-Content "<FileNameAndPath>"
for ($i=0; $i -lt $x.Count; $i++)
{
Set-MsolUserLicense -UserPrincipalName $x[$i] -RemoveLicenses "<AccountSkuId1>","<AccountSkuId2>"...
}
----

This example removes the *litwareinc:ENTERPRISEPACK* (Office 365
Enterprise E3) license from the user accounts defined in the text file
C:Documents.txt.

[source,powershell]
----
$x=Get-Content "C:\My Documents\Accounts.txt"
for ($i=0; $i -lt $x.Count; $i++)
{
Set-MsolUserLicense -UserPrincipalName $x[$i] -RemoveLicenses "litwareinc:ENTERPRISEPACK"
}
----

To remove all licenses from all existing user accounts, use the
following syntax:

[source,powershell]
----
$userArray = Get-MsolUser -All | where {$_.isLicensed -eq $true}
for ($i=0; $i -lt $userArray.Count; $i++)
{
Set-MsolUserLicense -UserPrincipalName $userArray[$i].UserPrincipalName -RemoveLicenses $userArray[$i].licenses.accountskuid
}
----

Another way to free up a license is by deleting the user account. For
more information, see
link:delete-and-restore-user-accounts-with-microsoft-365-powershell.md[Delete
and restore user accounts with PowerShell].

=== See also

link:manage-user-accounts-and-licenses-with-microsoft-365-powershell.md[Manage
Microsoft 365 user accounts&#44; licenses&#44; and groups with PowerShell]

link:manage-microsoft-365-with-microsoft-365-powershell.md[Manage
Microsoft 365 with PowerShell]

link:getting-started-with-microsoft-365-powershell.md[Getting started
with PowerShell for Microsoft 365]
