= Restrict SharePoint site content to a geo location
:audience: ITPro
:author: MikePlumleyMSFT
:description: In this article, learn how to restrict SharePoint sites to a specified geo location in a multi-geo environment.
:f1.keywords: ["NOCSH"]
:manager: pamgreen
:ms.author: mikeplum
:ms.collection: Strat_SP_gtc
:ms.custom: seo-marvel-apr2020
:ms.localizationpriority: medium
:ms.reviewer: adwood
:ms.service: microsoft-365-enterprise
:ms.topic: article

== Restrict SharePoint site content to a geo location

Under certain circumstances you might choose to enforce a site and its file content to remain in the geo location where the site was created, either by preventing the site from being moved or by preventing the caching of the site's file content in another geo location.

You can do this task by using the link:/powershell/module/sharepoint-online/set-sposite[Set-SPOSite] cmdlet with the *RestrictedToGeo* parameter.
This parameter has a default value of NULL, but you can change it to one of the following restrictions:

|===
| Restriction | Description

| NoRestriction
| The site can be moved to another geo location.

| BlockMoveOnly
| Site cannot be moved to another geo location, but site content can be cached in other geo locations.

| BlockFull
| Site cannot be moved to another geo location, and full file content is not cached in other geo locations.
Files' title (harvested from the content), file name, and other properties of the file can still be cached in other geo-locations.
+ Content stored in the site before it was configured to BlockFull, may continue to be cached in other geo locations.
|===

Use the following syntax:

`Set-SPOSite -Identity <siteURL> -RestrictedToGeo <restriction>`

For example:

`+Set-SPOSite -Identity https://contoso.sharepoint.com/sites/RegionRestrictedTeamSite -RestrictedToGeo BlockFull+`
