= Retrieve customer tenant reporting data with Windows PowerShell for DAP partners
:audience: Admin
:author: kelleyvice-msft
:description: Summary: Use remote Windows PowerShell for Microsoft Exchange Online to retrieve reports from individual customer tenants.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.assetid: 893e5275-30b3-433f-8ecd-644f78f513e2
:ms.author: kvice
:ms.collection: Ent_O365
:ms.custom: seo-marvel-apr2020
:ms.localizationpriority: medium
:ms.service: microsoft-365-enterprise
:ms.topic: article
:search.appverid: ["MET150"]

== Retrieve customer tenant reporting data with Windows PowerShell for Delegated Access Permissions (DAP) partners

_This article applies to both Microsoft 365 Enterprise and Office 365 Enterprise._

Use remote Windows PowerShell for Microsoft Exchange Online to retrieve reports from individual customer tenants.

Syndication and Cloud Solution Provider (CSP) partners can access the data that makes up customer tenant reports directly via remote Windows PowerShell for Exchange Online PowerShell.
This method lets partners collect and save the reporting data and then perform other operations on it.
After you open a remote connection, retrieving reporting data about a customer tenancy is identical to running any cmdlet against a customer tenancy.

This article describes how you can use remote Windows PowerShell for Exchange Online to connect to a single customer tenancy and retrieve a report.
By default, Windows PowerShell does not support aggregating reporting data from multiple customer tenancies.
The reports you retrieve with this procedure are only for the  _DelegatedOrg_ that you connect to.

=== Before you begin

* Connect to your Exchange Online tenant by using remote Windows PowerShell.
For instructions, see link:/powershell/exchange/connect-to-exchange-online-powershell[Connect to Exchange Online tenants with remote Windows PowerShell for Delegated Access Permissions (DAP) partners]

=== Run the Get-StaleMailboxReport sample

After you have opened a remote session to Exchange Online, run the following command to retrieve the *Get-StaleMailboxReport* for the date range 03/25/2015 through 03/31/2015.

[,powershell]
----
Get-StaleMailboxReport -StartDate 03/25/2015 -EndDate 03/31/2015
----

There are many other reporting cmdlets available for Exchange Online, Lync Online, SharePoint Online, and other services for message tracing that you can use.
To learn more about the available reporting cmdlets, see the articles listed in the following section.

=== See also

link:/previous-versions/office/developer/o365-enterprise-developers/jj984325(v=office.15)[Office 365 Reporting web service]

link:/powershell/module/exchange/get-csclientdevicedetailreport[Reporting cmdlets in Exchange Online]

https://go.microsoft.com/fwlink/p/?LinkID=533477[Help for partners]
