= 
kelleyvice-msft

== Set up your network for Microsoft 365

_This article applies to both Microsoft 365 Enterprise and Office 365
Enterprise._

An important part of your Microsoft 365 onboarding is to ensure that
your network and Internet connections are set up for optimized access.
Configuring your on-premises network to access a globally distributed
Software-as-a-Service (SaaS) cloud is different from a traditional
network that is optimized for traffic to on-premises datacenters and a
central Internet connection.

Use these articles to understand the key differences and to modify your
edge devices, client computers, and on-premises network to get the best
performance for your on-premises users.

=== How Microsoft 365 networking works

See these articles for an overview of connectivity for Microsoft 365:

* link:microsoft-365-networking-overview.md[Microsoft 365 networking
connectivity overview]
* link:microsoft-365-network-connectivity-principles.md[Microsoft 365
network connectivity principles]
* link:assessing-network-connectivity.md[Assessing Microsoft 365 network
connectivity]

For advice on enhancing performance, see
link:network-planning-and-performance.md[Network planning and
performance tuning for Microsoft 365].

=== Support Microsoft 365 networking as a network equipment vendor

If you are a network equipment vendor, join the
link:microsoft-365-networking-partner-program.md[Office 365 Networking
Partner Program]. Enroll in the program to build Office 365 network
connectivity principles into your products and solutions.

=== Office 365 endpoints

Endpoints are the set of destination IP addresses, DNS domain names, and
URLs for Office 365 traffic on the Internet.

To optimize performance to Office 365 cloud-based services, some
endpoints need special handling by your client browsers and the devices
in your edge network. These devices include firewalls, SSL Break and
Inspect and packet inspection devices, and data loss prevention systems.

See link:managing-office-365-endpoints.md[Managing Office 365 endpoints]
for the details.

There are currently five different Office 365 clouds. This table takes
you to the list of endpoints for each one.

[width="100%",cols="<58%,<42%",options="header",]
|===
|Endpoints |Description
|link:urls-and-ip-address-ranges.md[Worldwide endpoints] |The endpoints
for worldwide Office 365 subscriptions, which include the United States
Government Community Cloud (GCC).

|link:microsoft-365-u-s-government-dod-endpoints.md[U.S. Government DoD
endpoints] |The endpoints for United States Department of Defense (DoD)
subscriptions.

|link:microsoft-365-u-s-government-gcc-high-endpoints.md[U.S. Government
GCC High endpoints] |The endpoints for United States Government
Community Cloud High (GCC High) subscriptions.

|link:urls-and-ip-address-ranges-21vianet.md[Office 365 operated by
21Vianet endpoints] |The endpoints for Office 365 operated by 21Vianet,
which is designed to meet the needs for Office 365 in China.

| |
|===

To automate getting the latest list of endpoints for your Office 365
cloud, see the link:microsoft-365-ip-web-service.md[Office 365 IP
Address and URL Web service].

For additional endpoints, see these articles:

* link:additional-office365-ip-addresses-and-urls.md[Additional
endpoints not included in the Web service]
* link:network-requests-in-office-2016-for-mac.md[Network requests in
Office 2016 for Mac]

=== Additional topics for Microsoft 365 networking

See these articles for specialized topics in Microsoft 365 networking:

* link:content-delivery-networks.md[Content delivery networks]
* link:ipv6-support.md[IPv6 support in Office 365 services]
* link:nat-support-with-microsoft-365.md[NAT support with Office 365]

=== ExpressRoute for Microsoft 365

See these articles for information on the use of ExpressRoute for
Microsoft 365 traffic:

* link:azure-expressroute.md[Azure ExpressRoute for Microsoft 365]

____
[!NOTE] We *do not recommend* ExpressRoute for Microsoft 365 because it
does not provide the best connectivity model for the service in most
circumstances. As such, Microsoft authorization is required to use this
connectivity model. We review every customer request and authorize
ExpressRoute for Microsoft 365 only in the rare scenarios where it is
necessary. Please read the https://aka.ms/erguide[ExpressRoute for
Microsoft 365 guide] for more information and following a comprehensive
review of the document with your productivity, network, and security
teams, work with your Microsoft account team to submit an exception if
needed.
____
