= Set up your network for Microsoft 365
:audience: ITPro
:author: kelleyvice-msft
:description: Find links to articles with information to help you set up your network for Microsoft 365, including a network connectivity overview and list of endpoints.
:f1.keywords: ["CSH"]
:manager: scotv
:ms.assetid:
:ms.author: kvice
:ms.collection: ["M365-subscription-management", "Strat_O365_Enterprise"]
:ms.custom: ["Ent_TLGs", "seo-marvel-apr2020"]
:ms.date: 11/19/2019
:ms.localizationpriority: medium
:ms.service: microsoft-365-enterprise
:ms.topic: landing-page
:search.appverid: ["MET150"]

== Set up your network for Microsoft 365

_This article applies to both Microsoft 365 Enterprise and Office 365 Enterprise._

An important part of your Microsoft 365 onboarding is to ensure that your network and Internet connections are set up for optimized access.
Configuring your on-premises network to access a globally distributed Software-as-a-Service (SaaS) cloud is different from a traditional network that is optimized for traffic to on-premises datacenters and a central Internet connection.

Use these articles to understand the key differences and to modify your edge devices, client computers, and on-premises network to get the best performance for your on-premises users.

=== How Microsoft 365 networking works

See these articles for an overview of connectivity for Microsoft 365:

* xref:microsoft-365-networking-overview.adoc[Microsoft 365 networking connectivity overview]
* xref:microsoft-365-network-connectivity-principles.adoc[Microsoft 365 network connectivity principles]
* xref:assessing-network-connectivity.adoc[Assessing Microsoft 365 network connectivity]

For advice on enhancing performance, see xref:network-planning-and-performance.adoc[Network planning and performance tuning for Microsoft 365].

=== Support Microsoft 365 networking as a network equipment vendor

If you are a network equipment vendor, join the xref:microsoft-365-networking-partner-program.adoc[Office 365 Networking Partner Program].
Enroll in the program to build Office 365 network connectivity principles into your products and solutions.

=== Office 365 endpoints

Endpoints are the set of destination IP addresses, DNS domain names, and URLs for Office 365 traffic on the Internet.

To optimize performance to Office 365 cloud-based services, some endpoints need special handling by your client browsers and the devices in your edge network.
These devices include firewalls, SSL Break and Inspect and packet inspection devices, and data loss prevention systems.

See xref:managing-office-365-endpoints.adoc[Managing Office 365 endpoints] for the details.

There are currently five different Office 365 clouds.
This table takes you to the list of endpoints for each one.

|===
| Endpoints | Description

| xref:urls-and-ip-address-ranges.adoc[Worldwide endpoints]
| The endpoints for worldwide Office 365 subscriptions, which include the United States Government Community Cloud (GCC).

| xref:microsoft-365-u-s-government-dod-endpoints.adoc[U.S.
Government DoD endpoints]
| The endpoints for United States Department of Defense (DoD) subscriptions.

| xref:microsoft-365-u-s-government-gcc-high-endpoints.adoc[U.S.
Government GCC High endpoints]
| The endpoints for United States Government Community Cloud High (GCC High) subscriptions.

| xref:urls-and-ip-address-ranges-21vianet.adoc[Office 365 operated by 21Vianet endpoints]
| The endpoints for Office 365 operated by 21Vianet, which is designed to meet the needs for Office 365 in China.

|
|
|===

To automate getting the latest list of endpoints for your Office 365 cloud, see the xref:microsoft-365-ip-web-service.adoc[Office 365 IP Address and URL Web service].

For additional endpoints, see these articles:

* xref:additional-office365-ip-addresses-and-urls.adoc[Additional endpoints not included in the Web service]
* xref:network-requests-in-office-2016-for-mac.adoc[Network requests in Office 2016 for Mac]

=== Additional topics for Microsoft 365 networking

See these articles for specialized topics in Microsoft 365 networking:

* xref:content-delivery-networks.adoc[Content delivery networks]
* xref:ipv6-support.adoc[IPv6 support in Office 365 services]
* xref:nat-support-with-microsoft-365.adoc[NAT support with Office 365]

=== ExpressRoute for Microsoft 365

See these articles for information on the use of ExpressRoute for Office 365 traffic:

* xref:azure-expressroute.adoc[Azure ExpressRoute for Office 365]
* xref:implementing-expressroute.adoc[Implementing ExpressRoute for Office 365]
* xref:network-planning-with-expressroute.adoc[Network planning with ExpressRoute for Office 365]
* xref:routing-with-expressroute.adoc[Routing with ExpressRoute for Office 365]
