= 
kelleyvice-msft

== Deploy Microsoft 365 Enterprise for your organization

Are you ready to deploy Microsoft 365 Enterprise, integrate it with your
on-premises infrastructure, and enable your employees to take advantage
of cloud-based productivity and collaboration?

This article describes two deployment options, whether you want help or
are doing it on your own. In each case, Microsoft provides a guided path
for you to follow for deployment success.

=== Guided Microsoft 365 Enterprise setup process with FastTrack

*https://www.microsoft.com/fasttrack/microsoft-365[FastTrack for
Microsoft 365]* is the best method for deploying Microsoft 365.
FastTrack guides you through the most common deployment configurations
and can answer questions along the way.

To access a series of setup guides, sign in to your Microsoft 365
subscription, and then go to https://aka.ms/o365fasttrack[Setup
guidance].

____
[!NOTE] You can also get help from a
https://www.microsoft.com/solution-providers/home[Microsoft partner].
____

=== Do-it-yourself guided deployment of Microsoft 365 Enterprise

Deploying Microsoft 365 Enterprise on your own requires that you perform
detailed research to make the design decisions that streamline Microsoft
365 service configuration and user adoption. Start your planning
link:get-your-organization-ready-for-office-365.md[here].

To deploy Microsoft 365 Enterprise on your own after completing your
planning, these are the recommended steps.

[arabic]
. link:set-up-network-for-microsoft-365.md[Set up your network]
+
Includes adding your Internet domains and optimizing the network
performance for your on-premises users.
. link:protect-your-global-administrator-accounts.md[Set up your
identities]
+
Includes determining an identity model (cloud-only or hybrid), and for
hybrid identity, setting up directory synchronization between your
on-premises Active Directory Domain Services (AD DS) and your Microsoft
365 subscription.
. link:/microsoft-365/security/office-365-security/defender-for-office-36[Implement
security]
+
Includes configuring and rolling out basic and enhanced security,
threat, and information protections for your tenant and identities in
the first 30 days, 90 days, and beyond.
. link:/DeployOffice/deployment-guide-microsoft-365-apps[Deploy client
software]
+
Includes deploying Microsoft 365 Apps for enterprise (previously named
Office 365 ProPlus), the cloud-updated and always-current version of the
Office suite (Word, Excel, PowerPoint, and others) on your devices.
Every Microsoft 365 client license includes a license for Microsoft 365
Apps for enterprise.
. https://support.office.com/article/set-up-mobile-device-management-mdm-in-office-365-dd892318-bc44-4eb1-af00-9db5430be3cd[Set
up mobile device management]
+
Microsoft 365 Enterprise includes mobile device management capabilities
that help you secure and manage your users’ mobile devices.
. link:configure-services-and-applications.md[Configure services and
applications]
+
Includes information on migration of your data and links to articles
that get you started on key Microsoft 365 productivity apps such as
Exchange Online, SharePoint Online, and Teams.
. link:/office365/admin/admin-overview/get-started-with-office-365#training-resources-for-your-users[Train
your users]
+
Includes short videos that help your users get the most out of Microsoft
365 quickly.

____
[!NOTE] These steps are also for businesses and
https://go.microsoft.com/fwlink/?LinkId=627221[nonprofits] that want to
start with a custom deployment of Microsoft 365 Enterprise.
____
