= 
kelleyvice-msft

== Tenant roadmap for Microsoft 365

Your Microsoft 365 tenant is the set of services assigned to your
organization. Typically, this tenant is associated with one or more of
your public DNS domain names and acts as a central and isolated
container for different subscriptions and the licenses within them that
you assign to user accounts. For more information, see
link:subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md[Subscriptions&#44;
licenses&#44; accounts&#44; and tenants for Microsoft’s cloud offerings].

When you create a Microsoft 365 tenant, you assign it to a specific
geographical location. You can also have a tenant with multiple
geographical locations and move your tenant from one location to
another.

To get your tenant ready for user, groups, licenses, and cloud apps,
it’s critical to carefully plan and execute your tenant configuration.

=== Set up your Microsoft 365 tenant

After ensuring that your networking is optimized for access to Microsoft
365 for both on-premises and remote workers, your next big tasks are
planning for and then configuring your Microsoft 365 tenant for DNS
domain names, common services, and for that identity infrastructure that
supports secure user sign-in.

==== Plan

To plan for your tenant implementation:

* link:subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md[Understand
subscriptions&#44; licenses&#44; and Azure Active Directory (Azure AD) tenants]
* link:plan-for-third-party-ssl-certificates.md[Understand how to use
third-party SSL certificates]
* link:integrated-apps-and-azure-ads.md[Understand the ways a Microsoft
365 tenant is integrated with Azure AD services]
* link:microsoft-365-client-support-certificate-based-authentication.md[Plan
for client app support]
* link:hybrid-modern-auth-overview.md[Determine how to use hybrid modern
authentication]
* link:plan-upgrade-previous-versions-office.md[Plan for Office 2007 and
Office 2010 upgrades]
* link:/compliance/assurance/assurance-microsoft-365-isolation-controls#tenant-isolation[Understand
tenant isolation]

==== Deploy

To deploy your tenant:

* Add the link:../admin/setup/add-domain.md[DNS domains] for your
organization.
* Use the link:setup-guides-for-microsoft-365.md[setup guides in the
Microsoft 365 admin center].
* Build out your link:deploy-identity-solution-overview.md[identity
infrastructure].

==== Move a tenant’s geographic locations

Microsoft continues to open new datacenter geographic locations (geos)
for Microsoft 365 services. These new datacenter geos add capacity and
compute resources to support customer demand and usage growth.
Additionally, the new datacenter geos offer in-geo data residency for
core customer data.

For more information, see
link:moving-data-to-new-datacenter-geos.md[Moving core data to new
Microsoft 365 datacenter geos].

=== Deploy Microsoft 365 Multi-Geo

With Microsoft 365 Multi-Geo, your organization can expand its Microsoft
365 presence to multiple geographic regions and/or countries within your
existing tenant.

For more information, see link:microsoft-365-multi-geo.md[Microsoft 365
Multi-Geo].

=== Manage multiple Microsoft 365 tenants

Although having a single tenant for your organization is ideal, you may
be one of many organizations that have multiple tenants. Reasons can
include mergers and acquisitions, you want administrative isolation, or
you have a decentralized IT.

If you have multiple Microsoft 365 tenants, see these articles for more
information about:

* link:microsoft-365-inter-tenant-collaboration.md[Inter-tenant
collaboration]
* link:cross-tenant-mailbox-migration.md[Cross-tenant mailbox migration]
* link:microsoft-365-tenant-to-tenant-migrations.md[Tenant-to-tenant
migrations]

=== Next step

Start your tenant planning with
link:subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md[Subscriptions&#44;
licenses&#44; accounts&#44; and tenants].
