= Tenant roadmap for Microsoft 365
:audience: ITPro
:author: kelleyvice-msft
:description: The roadmap to set up your tenants for Microsoft 365.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.author: kvice
:ms.collection: ["M365-subscription-management", "m365initiative-coredeploy"]
:ms.custom: it-pro
:ms.localizationpriority: medium
:ms.service: microsoft-365-enterprise
:ms.topic: article

== Tenant roadmap for Microsoft 365

Your Microsoft 365 tenant is the set of services assigned to your organization.
Typically, this tenant is associated with one or more of your public DNS domain names and acts as a central and isolated container for different subscriptions and the licenses within them that you assign to user accounts.
For more information, see xref:subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.adoc[Subscriptions, licenses, accounts, and tenants for Microsoft's cloud offerings].

When you create a Microsoft 365 tenant, you assign it to a specific geographical location.
You can also have a tenant with multiple geographical locations and move your tenant from one location to another.

To get your tenant ready for user, groups, licenses, and cloud apps, it's critical to carefully plan and execute your tenant configuration.

=== Set up your Microsoft 365 tenant

After ensuring that your networking is optimized for access to Microsoft 365 for both on-premises and remote workers, your next big tasks are planning for and then configuring your Microsoft 365 tenant for DNS domain names, common services, and for that identity infrastructure that supports secure user sign-in.

==== Plan

To plan for your tenant implementation:

* xref:subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.adoc[Understand subscriptions, licenses, and Azure Active Directory (Azure AD) tenants]
* xref:plan-for-third-party-ssl-certificates.adoc[Understand how to use third-party SSL certificates]
* xref:integrated-apps-and-azure-ads.adoc[Understand the ways a Microsoft 365 tenant is integrated with Azure AD services]
* xref:microsoft-365-client-support-certificate-based-authentication.adoc[Plan for client app support]
* xref:hybrid-modern-auth-overview.adoc[Determine how to use hybrid modern authentication]
* xref:plan-upgrade-previous-versions-office.adoc[Plan for Office 2007 and Office 2010 upgrades]
* link:/compliance/assurance/assurance-microsoft-365-isolation-controls#tenant-isolation[Understand tenant isolation]

==== Deploy

To deploy your tenant:

* Add the xref:../admin/setup/add-domain.adoc[DNS domains] for your organization.
* Use the xref:setup-guides-for-microsoft-365.adoc[setup guides in the Microsoft 365 admin center].
* Build out your xref:deploy-identity-solution-overview.adoc[identity infrastructure].

==== Move a tenant's geographic locations

Microsoft continues to open new datacenter geographic locations (geos) for Microsoft 365 services.
These new datacenter geos add capacity and compute resources to support customer demand and usage growth.
Additionally, the new datacenter geos offer in-geo data residency for core customer data.

For more information, see xref:moving-data-to-new-datacenter-geos.adoc[Moving core data to new Microsoft 365 datacenter geos].

=== Deploy Microsoft 365 Multi-Geo

With Microsoft 365 Multi-Geo, your organization can expand its Microsoft 365 presence to multiple geographic regions and/or countries within your existing tenant.

For more information, see xref:microsoft-365-multi-geo.adoc[Microsoft 365 Multi-Geo].

=== Manage multiple Microsoft 365 tenants

Although having a single tenant for your organization is ideal, you may be one of many organizations that have multiple tenants.
Reasons can include mergers and acquisitions, you want administrative isolation, or you have a decentralized IT.

If you have multiple Microsoft 365 tenants, see these articles for more information about:

* xref:microsoft-365-inter-tenant-collaboration.adoc[Inter-tenant collaboration]
* xref:cross-tenant-mailbox-migration.adoc[Cross-tenant mailbox migration]
* xref:microsoft-365-tenant-to-tenant-migrations.adoc[Tenant-to-tenant migrations]

=== Next step

Start your tenant planning with xref:subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.adoc[Subscriptions, licenses, accounts, and tenants].
