= Turn off directory synchronization for Microsoft 365
:audience: Admin
:author: kelleyvice-msft
:description: In this article, find information about using PowerShell to turn off directory synchronization for Microsoft 365.
:f1.keywords: ["CSH"]
:manager: scotv
:ms.assetid: ee5f861e-bd48-4267-83d1-a4ead4b4a00d
:ms.author: kvice
:ms.collection: ["Ent_O365", "M365-identity-device-management"]
:ms.custom: ["Adm_O365", "seo-marvel-apr2020"]
:ms.localizationpriority: medium
:ms.service: microsoft-365-enterprise
:ms.topic: article
:search.appverid: ["MET150", "MOE150", "MED150"]

== Turn off directory synchronization for Microsoft 365

You can use PowerShell to turn off directory synchronization and convert your synchronized users to cloud-only.
However, it is not recommended that you turn off directory synchronization as a troubleshooting step.
If you need assistance with troubleshooting directory synchronization, see the xref:fix-problems-with-directory-synchronization.adoc[Fixing problems with directory synchronization for Microsoft 365] article.

https://support.office.com/article/32a17ca7-6fa0-4870-8a8d-e25ba4ccfd4b[Contact support] for business products if needed.

=== Turn off directory synchronization

To turn off Directory synchronization:

. First, install the required software and connect to your Microsoft 365 subscription.
For instructions, see link:connect-to-microsoft-365-powershell.md#connect-with-the-microsoft-azure-active-directory-module-for-windows-powershell[Connect with the Microsoft Azure Active Directory Module for Windows PowerShell].
. Use link:/previous-versions/azure/dn194097(v=azure.100)[Set-MsolDirSyncEnabled] to disable directory synchronization:

[,powershell]
----
  Set-MsolDirSyncEnabled -EnableDirSync $false
----

____
[!Note] If you use this command, you must wait 72 hours before you can turn directory synchronization back on.
____
