= 
dhb-msft

== Resources to help you upgrade from Office 2013 clients and servers

If you’re using Office 2013 clients and servers, be aware that *_support
ends on April 11, 2023_*. If you haven’t already begun to upgrade from
them to newer versions, we recommend you start now.

As you plan your upgrade, consider moving to Microsoft 365.

* Microsoft 365 has cloud-based services, such as Exchange Online,
SharePoint, and Teams.
* Microsoft 365 Apps for enterprise provides Office client apps that you
can install on local devices. The apps are updated regularly from the
Microsoft cloud with new productivity and security features.

=== Upgrade planning resources

The following table provides links to planning resources to help you
upgrade from these Office 2013 clients and servers.

[width="100%",cols="50%,50%",options="header",]
|===
|Product |Planning resource
|Office 2013 (desktop apps)Project 2013Visio 2013
|link:/deployoffice/endofsupport/plan-upgrade-older-versions-office[Plan
an upgrade from older versions of Office to Microsoft 365 Apps]

|Exchange Server 2013 |link:exchange-2013-end-of-support.md[Exchange
2013 end of support roadmap]

|SharePoint Server 2013 SharePoint Foundation 2013
|link:upgrade-from-sharepoint-2013.md[Upgrading from SharePoint 2013]

|Project Server 2013 |link:project-server-2013-end-of-support.md[Project
Server 2013 end of support roadmap]

|Lync Server 2013 |link:upgrade-from-lync-2013.md[Upgrading from Lync
Server 2013]
|===

We also recommend business and enterprise customers use the deployment
benefits provided by Microsoft and Microsoft Certified Partners,
including https://www.microsoft.com/fasttrack[Microsoft FastTrack] for
cloud migrations.

____
[!NOTE] If you use Office 2013 products and applications at home,
link:plan-upgrade-previous-versions-office.md#im-a-home-user-what-do-i-do[review
this information] for your upgrade choices.
____

=== Related articles

* link:/lifecycle/[Microsoft Lifecycle Policy]
* link:plan-upgrade-previous-versions-office.md[Plan your upgrade from
Office 2007 or Office 2010 servers and clients]
