= 
kelleyvice-msft

== Use the Centralized Deployment PowerShell cmdlets to manage add-ins

As a Microsoft 365 global admin, you can deploy Office Add-ins to users
via the Centralized Deployment feature (see
link:../admin/manage/manage-deployment-of-add-ins.md[Deploy Office
Add-ins in the admin center]. In addition to deploying Office Add-ins
via the Microsoft 365 admin center, you can also use Microsoft
PowerShell. Install the
https://www.powershellgallery.com/packages/O365CentralizedAddInDeployment[O365
Centralized Add-In Deployment Module for Windows PowerShell].

After you download the module, open a regular Windows PowerShell window
and run the following cmdlet:

[source,powershell]
----
 Import-Module -Name O365CentralizedAddInDeployment
----

=== Connect using your admin credentials

Before you can use the Centralized Deployment cmdlets, you need to sign
in.

[arabic]
. Start PowerShell.
. Connect to PowerShell by using your company admin credentials. Run the
following cmdlet.

[source,powershell]
----
Connect-OrganizationAddInService
----

[arabic, start=3]
. In the *Enter Credentials* page, enter your Microsoft 365 *User
Admin*, or *Global admin* credentials. Alternately, you can enter your
credentials directly into the cmdlet.
+
Run the following cmdlet specifying your company admin credentials as a
PSCredential object.

[source,powershell]
----
$secpasswd = ConvertTo-SecureString "MyPassword" -AsPlainText -Force
$mycredentials = New-Object System.Management.Automation.PSCredential ("serviceaccount@contoso.com", $secpasswd)
Connect-OrganizationAddInService -Credential $mycredentials
----

____
[!NOTE] For more information about using PowerShell, see
link:./connect-to-microsoft-365-powershell.md[Connect to Microsoft 365
with PowerShell].
____

=== Upload an add-in manifest

Run the *New-OrganizationAdd-In* cmdlet to upload an add-in manifest
from a path, which can be either a file location or URL. The following
example shows a file location for the value of the _ManifestPath_
parameter.

[source,powershell]
----
New-OrganizationAddIn -ManifestPath 'C:\Users\Me\Desktop\taskpane.xml' -Locale 'en-US'
----

You can also run the *New-OrganizationAdd-In* cmdlet to upload an add-in
and assign it to users or groups directly by using the _Members_
parameter, as shown in the following example. Separate the email
addresses of members with a comma.

[source,powershell]
----
New-OrganizationAddIn -ManifestPath 'C:\Users\Me\Desktop\taskpane.xml' -Locale 'en-US' -Members  'KathyBonner@contoso.com', 'MaxHargrave@contoso.com'
----

=== Upload an add-in from the Office Store

Run the *New-OrganizationAddIn* cmdlet to upload a manifest from the
Office Store.

In the following example, the *New-OrganizationAddIn* cmdlet specifies
the AssetId for an add-in for a United States location and content
market.

[source,powershell]
----
New-OrganizationAddIn -AssetId 'WA104099688' -Locale 'en-US' -ContentMarket 'en-US'
----

To determine the value for the _AssetId_ parameter, you can copy it from
the URL of the Office Store webpage for the add-in. AssetIds always
begin with ``WA'' followed by a number. For example, in the previous
example, the source for the AssetId value of WA104099688 is the Office
Store webpage URL for the add-in:
https://store.office.com/en-001/app.aspx?assetid=WA104099688.

The values for the _Locale_ parameter and the _ContentMarket_ parameter
are identical and indicate the country/region you’re trying to install
the add-in from. The format is en-US, fr-FR. and so forth.

____
[!NOTE] Add-ins uploaded from the Office Store will update automatically
within a few days of the latest update being available on the Office
Store.
____

=== Get details of an add-in

Run the *Get-OrganizationAddIn* cmdlet as shown below to get details of
all add-ins uploaded to the tenant, included an add-in’s product ID.

[source,powershell]
----
Get-OrganizationAddIn
----

Run the *Get-OrganizationAddIn* cmdlet with a value for the _ProductId_
parameter to specify which add-in you want to retrieve details for.

[source,powershell]
----
Get-OrganizationAddIn -ProductId 6a75788e-1c6b-4e9b-b5db-5975a2072122
----

To get full details of all the add-ins plus the assigned users and
groups, pipe the output of the *Get-OrganizationAddIn* cmdlet to the
Format-List cmdlet, as shown in the following example.

[source,powershell]
----
foreach($G in (Get-organizationAddIn)){Get-OrganizationAddIn -ProductId $G.ProductId | Format-List}
----

=== Turn on or turn off an add-in

To turn off an add-in so users and groups that are assigned to it will
no longer have access, run the *Set-OrganizationAddIn* cmdlet with the
_ProductId_ parameter and the _Enabled_ parameter set to `$false`, as
shown in the following example.

[source,powershell]
----
Set-OrganizationAddIn -ProductId 6a75788e-1c6b-4e9b-b5db-5975a2072122 -Enabled $false
----

To turn an add-in back on, run the same cmdlet with the _Enabled_
parameter set to `$true`.

[source,powershell]
----
Set-OrganizationAddIn -ProductId 6a75788e-1c6b-4e9b-b5db-5975a2072122 -Enabled $true
----

=== Add or remove users from an add-in

To add users and groups to a specific add-in, run the
*Set-OrganizationAddInAssignments* cmdlet with the _ProductId_, _Add_,
and _Members_ parameters. Separate the email addresses of members with a
comma.

[source,powershell]
----
Set-OrganizationAddInAssignments -ProductId 6a75788e-1c6b-4e9b-b5db-5975a2072122 -Add -Members 'KathyBonner@contoso.com','sales@contoso.com'
----

To remove users and groups, run the same cmdlet using the _Remove_
parameter.

[source,powershell]
----
Set-OrganizationAddInAssignments -ProductId 6a75788e-1c6b-4e9b-b5db-5975a2072122 -Remove -Members 'KathyBonner@contoso.com','sales@contoso.com'
----

To assign an add-in to all users on the tenant, run the same cmdlet
using the _AssignToEveryone_ parameter with the value set to `$true`.

[source,powershell]
----
Set-OrganizationAddInAssignments -ProductId 6a75788e-1c6b-4e9b-b5db-5975a2072122 -AssignToEveryone $true
----

To not assign an add-in to everyone and revert to the previously
assigned users and groups, you can run the same cmdlet and turn off the
_AssignToEveryone_ parameter by setting its value to `$false`.

[source,powershell]
----
Set-OrganizationAddInAssignments -ProductId 6a75788e-1c6b-4e9b-b5db-5975a2072122 -AssignToEveryone $false
----

=== Update an add-in

To update an add-in from a manifest, run the *Set-OrganizationAddIn*
cmdlet with the _ProductId_, _ManifestPath_, and _Locale_ parameters, as
shown in the following example.

[source,powershell]
----
Set-OrganizationAddIn -ProductId 6a75788e-1c6b-4e9b-b5db-5975a2072122 -ManifestPath 'C:\Users\Me\Desktop\taskpane.xml' -Locale 'en-US'
----

____
[!NOTE] Add-ins uploaded from the Office Store will update automatically
within a few days of the latest update being available on the Office
Store.
____

=== Delete an add-in

To delete an add-in, run the *Remove-OrganizationAddIn* cmdlet with the
_ProductId_ parameter, as shown in the following example.

[source,powershell]
----
Remove-OrganizationAddIn -ProductId 6a75788e-1c6b-4e9b-b5db-5975a2072122
----

=== Get detailed help for each cmdlet

You can look at detailed help for each cmdlet by using the Get-help
cmdlet. For example, the following cmdlet provides detailed information
about the Remove-OrganizationAddIn cmdlet.

[source,powershell]
----
Get-help Remove-OrganizationAddIn -Full
----
