= 
kelleyvice-msft

== Use lean popouts to reduce memory used when reading mail messages

This article contains information for improving message download
performance in Outlook on the web. This article is part of the
link:./network-planning-and-performance.md[Network planning and
performance tuning for Office 365] project.

As an Office 365 *Application Admin*, *Global admin*, or *User Admin*,
you can configure Outlook on the web to deliver _lean popouts_, a
smaller, less memory-intensive version of certain email messages in
Microsoft Edge or Internet Explorer. When lean popouts are configured
for Outlook on the web, server-side rendered components are loaded that
optimize performance.

____
[!NOTE] As of March 2018, lean popouts are not available for messages
that specify usage rights restrictions, such as Information Rights
Management (IRM).
____

These features will continue to work in the main window but are not
available in lean popouts:

* Outlook add-ins
* Skype for Business presence

=== To configure lean popouts for all users within your Office 365 organization

[arabic]
. link:/powershell/exchange/connect-to-exchange-online-powershell[Connect
to Exchange Online PowerShell].
. Run the
link:/powershell/module/exchange/set-organizationconfig[Set-OrganizationConfig]
cmdlet with the LeanPopoutEnabled parameter as follows:

[source,powershell]
----
Set-OrganizationConfig -LeanPopoutEnabled <$true |$false >
----

For example, to enable lean popouts for all users in your organization:

[source,powershell]
----
Set-OrganizationConfig -LeanPopoutEnabled $true
----

To disable lean popouts for all users in your organization:

[source,powershell]
----
Set-OrganizationConfig -LeanPopoutEnabled $false
----
