= Use lean popouts to reduce memory used when reading mail messages
:audience: ITPro
:author: kelleyvice-msft
:description: This article contains information for using lean popouts to improve message download performance in Outlook on the web.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.assetid: a6d6ba01-2562-4c3d-a8f1-78748dd506cf
:ms.author: kvice
:ms.custom: seo-marvel-apr2020
:ms.date: 12/3/2019
:ms.localizationpriority: medium
:ms.service: microsoft-365-enterprise
:ms.topic: article
:search.appverid: ["MET150"]

== Use lean popouts to reduce memory used when reading mail messages

This article contains information for improving message download performance in Outlook on the web.
This article is part of the xref:./network-planning-and-performance.adoc[Network planning and performance tuning for Office 365] project.

As an Office 365 *Application Admin*, *Global admin*, or *User Admin*, you can configure Outlook on the web to deliver _lean popouts_, a smaller, less memory-intensive version of certain email messages in Microsoft Edge or Internet Explorer.
When lean popouts are configured for Outlook on the web, server-side rendered components are loaded that optimize performance.

____
[!NOTE] As of March 2018, lean popouts are not available for messages that specify usage rights restrictions, such as Information Rights Management (IRM).
____

These features will continue to work in the main window but are not available in lean popouts:

* Outlook add-ins
* Skype for Business presence

=== To configure lean popouts for all users within your Office 365 organization

. link:/powershell/exchange/connect-to-exchange-online-powershell[Connect to Exchange Online PowerShell].
. Run the link:/powershell/module/exchange/set-organizationconfig[Set-OrganizationConfig] cmdlet with the LeanPopoutEnabled parameter as follows:

[,powershell]
----
  Set-OrganizationConfig -LeanPopoutEnabled <$true |$false >
----

For example, to enable lean popouts for all users in your organization:

[,powershell]
----
  Set-OrganizationConfig -LeanPopoutEnabled $true
----

To disable lean popouts for all users in your organization:

[,powershell]
----
  Set-OrganizationConfig -LeanPopoutEnabled $false
----
