= 
kelleyvice-msft

== Use PowerShell to create reports for Microsoft 365

_This article applies to both Microsoft 365 Enterprise and Office 365
Enterprise._

Many different reports are available in the Microsoft 365 admin center.
But these reports only provide so much information, and sometimes you
need more. That’s when you need PowerShell for Microsoft 365.

These articles describe how to use PowerShell for Microsoft 365 to get
information from your Microsoft 365 tenant:

* Get started with reporting using PowerShell for Microsoft 365:
** link:./why-you-need-to-use-microsoft-365-powershell.md[Why you need
to use PowerShell for Microsoft 365]
* Reports for user accounts and licenses:
** link:view-licenses-and-services-with-microsoft-365-powershell.md[View
Microsoft 365 licenses and services with PowerShell]
** link:view-licensed-and-unlicensed-users-with-microsoft-365-powershell.md[View
Microsoft 365 licensed and unlicensed users with PowerShell]
** link:view-account-license-and-service-details-with-microsoft-365-powershell.md[View
Microsoft 365 account license and service details with PowerShell]
** link:view-user-accounts-with-microsoft-365-powershell.md[View
Microsoft 365 user accounts with PowerShell]
* Reports for SharePoint Online:
** link:/powershell/sharepoint/sharepoint-online/connect-sharepoint-online[Get
started with SharePoint Online Management Shell]
** link:/powershell/module/sharepoint-online/get-spositegroup[Get-SPOSiteGroup
- Gets all the groups on a specified site collection]
* Reports for Exchange Online:
** link:/exchange/recipients-in-exchange-online/manage-user-mailboxes/use-powershell-to-display-mailbox-information[Use
Exchange Online PowerShell to display mailbox]

=== Related articles

link:manage-microsoft-365-with-microsoft-365-powershell.md[Manage
Microsoft 365 with PowerShell]

link:getting-started-with-microsoft-365-powershell.md[Get started with
PowerShell for Microsoft 365]

link:manage-sharepoint-online-with-microsoft-365-powershell.md[Manage
SharePoint with PowerShell]

link:manage-user-accounts-and-licenses-with-microsoft-365-powershell.md[Manage
Microsoft 365 user accounts&#44; licenses&#44; and groups with PowerShell]
