= View licensed and unlicensed Microsoft 365 users with PowerShell
:audience: Admin
:author: kelleyvice-msft
:description: This article explains how to use PowerShell to view licensed and unlicensed Microsoft 365 user accounts.
:f1.keywords: ["CSH"]
:manager: scotv
:ms.assetid: e4ee53ed-ed36-4993-89f4-5bec11031435
:ms.author: kvice
:ms.collection: Ent_O365
:ms.custom: ["O365ITProTrain", "Ent_Office_Other", "PowerShell", "seo-marvel-apr2020"]
:ms.date: 07/21/2020
:ms.localizationpriority: medium
:ms.service: microsoft-365-enterprise
:ms.topic: article
:search.appverid: ["MET150"]

== View licensed and unlicensed Microsoft 365 users with PowerShell

_This article applies to both Microsoft 365 Enterprise and Office 365 Enterprise._

User accounts in your Microsoft 365 organization may have some, all, or none of the available licenses assigned to them from the licensing plans that are available in your organization.
You can use PowerShell for Microsoft 365 to quickly find the licensed and unlicensed users in your organization.

=== Use the Microsoft Graph PowerShell SDK

First, link:/graph/powershell/get-started#authentication[connect to your Microsoft 365 tenant].

Reading user properties including license details requires the User.Read.All permission scope or one of the other permissions listed in the link:/graph/api/user-get['Get a user' Graph API reference page].

The Organization.Read.All permission scope is required to read the licenses available in the tenant.

[,powershell]
----
Connect-Graph -Scopes User.Read.All, Organization.Read.All
----

To view the license details of a specific user account, run the following command:

[,powershell]
----
Get-MgUserLicenseDetail -UserId "<user sign-in name (UPN)>"
----

For example:

[,powershell]
----
Get-MgUserLicenseDetail -UserId "belindan@litwareinc.com"
----

To view the list of all user accounts in your organization that have NOT been assigned any of your licensing plans (unlicensed users), run the following command:

[,powershell]
----
Get-MgUser -Filter 'assignedLicenses/$count eq 0' -ConsistencyLevel eventual -CountVariable unlicensedUserCount -All

Write-Host "Found $unlicensedUserCount unlicensed users."
----

To view the list of all member user accounts (excluding guests) in your organization that have NOT been assigned any of your licensing plans (unlicensed users), run the following command:

[,powershell]
----
Get-MgUser -Filter "assignedLicenses/`$count eq 0 and userType eq 'Member'" -ConsistencyLevel eventual -CountVariable unlicensedUserCount -All

Write-Host "Found $unlicensedUserCount unlicensed users (excluding guests)."
----

To view the list of all user accounts in your organization that have been assigned any of your licensing plans (licensed users), run the following command:

[,powershell]
----
Get-MgUser -Filter 'assignedLicenses/$count ne 0' -ConsistencyLevel eventual -CountVariable licensedUserCount -All -Select UserPrincipalName,DisplayName,AssignedLicenses | Format-Table -Property UserPrincipalName,DisplayName,AssignedLicenses

Write-Host "Found $licensedUserCount licensed users."
----

To view the list of all user accounts in your organization that have an E5 license assigned, run the following command:

[,powershell]
----
$e5Sku = Get-MgSubscribedSku -All | Where SkuPartNumber -eq 'SPE_E5'

Get-MgUser -Filter "assignedLicenses/any(x:x/skuId eq $($e5sku.SkuId) )" -ConsistencyLevel eventual -CountVariable e5licensedUserCount -All

Write-Host "Found $e5licensedUserCount E5 licensed users."
----

=== Use the Azure Active Directory PowerShell for Graph module

First, link:connect-to-microsoft-365-powershell.md#connect-with-the-azure-active-directory-powershell-for-graph-module[connect to your Microsoft 365 tenant].

To view the list of all user accounts in your organization that have NOT been assigned any of your licensing plans (unlicensed users), run the following command:

[,powershell]
----
Get-AzureAdUser | ForEach{ $licensed=$False ; For ($i=0; $i -le ($_.AssignedLicenses | Measure).Count ; $i++) { If( [string]::IsNullOrEmpty(  $_.AssignedLicenses[$i].SkuId ) -ne $True) { $licensed=$true } } ; If( $licensed -eq $false) { Write-Host $_.UserPrincipalName} }
----

To view the list of all user accounts in your organization that have been assigned any of your licensing plans (licensed users), run the following command:

[,powershell]
----
Get-AzureAdUser | ForEach { $licensed=$False ; For ($i=0; $i -le ($_.AssignedLicenses | Measure).Count ; $i++) { If( [string]::IsNullOrEmpty(  $_.AssignedLicenses[$i].SkuId ) -ne $True) { $licensed=$true } } ; If( $licensed -eq $true) { Write-Host $_.UserPrincipalName} }
----

____
[!Note] To list all of the users in your subscription, use the `Get-AzureAdUser -All $true` command.
____

=== Use the Microsoft Azure Active Directory Module for Windows PowerShell

First, link:connect-to-microsoft-365-powershell.md#connect-with-the-microsoft-azure-active-directory-module-for-windows-powershell[connect to your Microsoft 365 tenant].

To view the list of all user accounts and their licensing status in your organization, run the following command in PowerShell:

[,powershell]
----
Get-MsolUser -All
----

____
[!Note] PowerShell Core does not support the Microsoft Azure Active Directory Module for Windows PowerShell module and cmdlets with *Msol* in their name.
To continue using these cmdlets, you must run them from Windows PowerShell.
____

To view the list of all unlicensed user accounts in your organization, run the following command:

[,powershell]
----
Get-MsolUser -All -UnlicensedUsersOnly
----

To view the list of all licensed user accounts in your organization, run the following command:

[,powershell]
----
Get-MsolUser -All | where {$_.isLicensed -eq $true}
----

=== See also

xref:manage-user-accounts-and-licenses-with-microsoft-365-powershell.adoc[Manage Microsoft 365 user accounts, licenses, and groups with PowerShell]

xref:manage-microsoft-365-with-microsoft-365-powershell.adoc[Manage Microsoft 365 with PowerShell]

xref:getting-started-with-microsoft-365-powershell.adoc[Getting started with PowerShell for Microsoft 365]
