= 
efrene

== Difference between MDM and MAM

Microsoft 365 Business Premium offers a number of ways for you to
protect your business data. See
link:../../admin/admin-overview/what-is-microsoft-365.md[Overview of
Microsoft 365 Business Premium] for more about the various protections
that are automatically set up, and what you can set up yourself to
further protect your business. You can also onboard devices to Microsoft
Defender for Business to protect your Windows devices and the data in
your mobile devices. For more information, see
link:/microsoft-365/business-premium/m365bp-onboard-devices-mdb[Onboard
enrolled devices to Microsoft Defender for Business].

=== Mobile device management or MDM

Microsoft 365 Business Premium lets you set up policies that protect
data on your Windows 10 and 11 devices. When a device is under mobile
device management, you control the entire device, and can wipe data from
it, and also reset it to factory settings. For more information, see
link:/mem/intune/fundamentals/what-is-device-management#choose-the-device-management-solution-thats-right-for-you[Choose
the device management solution that’s right for you] and
link:/microsoft-365/business-premium/m365bp-protect-devices[Set up and
secure managed devices].

=== Mobile application management or MAM

Mobile application management lets you control your business data in
your users’ personal devices, such as iPhones and Androids, and their
personal Windows computers. You can use application management policies
to prevent your users from copying business data from Office apps to
their personal apps. You can also remove all data from the Office apps
on their personal devices. For more information, see
link:/mem/intune/fundamentals/what-is-device-management#choose-the-device-management-solution-thats-right-for-you[Choose
the device management solution that’s right for you] and
link:/microsoft-365/business-premium/m365bp-protect-devices[Set up and
secure managed devices].
