= What is the difference between device and app management
:audience: Admin
:author: efrene
:description: Learn the differences between mobile device management and mobile app management, or MDM and MAM.
:f1.keywords: ["NOCSH"]
:f1_keywords: ["O365E_understand_devices", "BCS365_understand_devices"]
:manager: scotv
:ms.author: efrene
:ms.collection: M365-subscription-management
:ms.custom: ["Core_O365Admin_Migration", "MiniMaven", "MSB365"]
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: conceptual
:search.appverid: ["BCS160", "MET150", "MOE150"]

== Difference between MDM and MAM

Microsoft 365 Business Premium offers a number of ways for you to protect your business data.
See xref:../../admin/admin-overview/what-is-microsoft-365.adoc[Overview of Microsoft 365 Business Premium] for more about the various protections that are automatically set up, and what you can set up yourself to further protect your business.
You can also set up policies that protect your Windows 10 devices and the data in your mobile devices.
xref:../../business-premium/m365bp-protection-settings-for-windows-10-devices.adoc[Set application protection settings for Windows 10 devices].

=== Mobile device management or MDM

Microsoft 365 Business Premium lets you set up policies that protect data on your Windows 10 devices.
When a device is under mobile device management, you control the entire device, and can wipe data from it, and also reset it to factory settings.
For more information, see xref:../../business-premium/m365bp-protection-settings-for-windows-10-devices.adoc[Set device protection settings for Windows 10 PCs].

=== Mobile application management or MAM

Mobile application management lets you control your business data in your users' personal devices, such as iPhones and Androids, and their personal Win 10 computers.
You can use application management policies to prevent your users from copying business data from Office apps to their personal apps.
You can also remove all data from the Office apps on their personal devices.
For more information, see xref:../../business-premium/m365bp-app-protection-settings-for-android-and-ios.adoc[Set app protection settings for Android or iOS devices] and xref:../../business-premium/m365bp-app-protection-settings-for-android-and-ios.adoc[Set application protection settings for Windows 10 devices].
