= 
dcurwin

== Configure Defender for Identity detection exclusions in Microsoft 365 Defender

*Applies to:*

* Microsoft 365 Defender
* Defender for Identity

This article explains how to configure
link:/defender-for-identity[Microsoft Defender for Identity] detection
exclusions in
link:/microsoft-365/security/defender/overview-security-center[Microsoft
365 Defender].

____
[!IMPORTANT] As part of the convergence with Microsoft 365 Defender,
some options and details have changed from their location in the
Defender for Identity portal. Please read the details below to discover
where to find both the familiar and new features.
____

[!INCLUDE link:includes/product-long.md[Product long]] enables the
exclusion of specific IP addresses, computers, domains, or users from a
number of detections.

For example, a *DNS Reconnaissance* alert could be triggered by a
security scanner that uses DNS as a scanning mechanism. Creating an
exclusion helps Defender for Identity ignore such scanners and reduce
false positives.

____
[!NOTE] Of the most common domains with
link:/defender-for-identity/exfiltration-alerts#suspicious-communication-over-dns-external-id-2031[Suspicious
communication over DNS] alerts opened on them, we observed the domains
that customers most excluded from the alert. These domains are added to
the exclusions list by default, but you have the option to easily remove
them.
____

=== How to add detection exclusions

[arabic]
. In https://security.microsoft.com/[Microsoft 365 Defender], go to
*Settings* and then *Identities*.
+
:::image type=``content''
source=``../../media/defender-identity/settings-identities.png''
alt-text=``The Identities option in the Name column''
lightbox=``../../media/defender-identity/settings-identities.png'':::
. You’ll then see *Excluded entities* in the left-hand menu.
+
:::image type=``content''
source=``../../media/defender-identity/excluded-entities.png''
alt-text=``The Excluded entities pane''
lightbox=``../../media/defender-identity/excluded-entities.png'':::

You can then set exclusions by two methods: *Exclusions by detection
rule* and *Global excluded entities*.

=== Exclusions by detection rule

[arabic]
. In the left-hand menu, select *Exclusions by detection rule*. You’ll
see a list of detection rules.
+
:::image type=``content''
source=``../../media/defender-identity/exclusions-by-detection-rule.png''
alt-text=``The Exclusions by detection rule option in the Excluded
entities item in the left pane''
lightbox=``../../media/defender-identity/exclusions-by-detection-rule.png'':::
. For each detection you want to configure, do the following steps:
[arabic]
.. Select the rule. You can search for detections using the search bar.
Once selected, a pane will open with the detection rule details.
+
:::image type=``content''
source=``../../media/defender-identity/detection-rule-details.png''
alt-text=``The details of a detection rule''
lightbox=``../../media/defender-identity/detection-rule-details.png'':::
.. To add an exclusion, select the *Excluded entities* button, and then
choose the exclusion type. Different excluded entities are available for
each rule. They include users, devices, domains and IP addresses. In
this example, the choices are *Exclude devices* and *Exclude IP
addresses*.
+
:::image type=``content''
source=``../../media/defender-identity/exclude-devices-or-ip-addresses.png''
alt-text=``The option to exclude devices or IP addresses''
lightbox=``../../media/defender-identity/exclude-devices-or-ip-addresses.png'':::
.. After choosing the exclusion type, you can add the exclusion. In the
pane that opens, select the *+* button to add the exclusion.
+
:::image type=``content''
source=``../../media/defender-identity/add-exclusion.png''
alt-text=``The option to add an exclusion''
lightbox=``../../media/defender-identity/add-exclusion.png'':::
.. Then add the entity to be excluded. Select *+ Add* to add the entity
to the list.
+
:::image type=``content''
source=``../../media/defender-identity/add-excluded-entity.png''
alt-text=``The option to add entity that is to be excluded''
lightbox=``../../media/defender-identity/add-excluded-entity.png'':::
.. Then select *Exclude IP addresses* (in this example) to complete the
exclusion.
+
:::image type=``content''
source=``../../media/defender-identity/exclude-ip-addresses.png''
alt-text=``The option to exclude IP addresses''
lightbox=``../../media/defender-identity/exclude-ip-addresses.png'':::
.. Once you’ve added exclusions, you can export the list or remove the
exclusions by returning to the *Excluded entities* button. In this
example, we’ve returned to *Exclude devices*. To export the list, select
the down arrow button.
+
:::image type=``content''
source=``../../media/defender-identity/return-to-exclude-devices.png''
alt-text=``The Return to Exclude devices option''
lightbox=``../../media/defender-identity/return-to-exclude-devices.png'':::
.. To delete an exclusion, select the exclusion and select the trash
icon.
+
:::image type=``content''
source=``../../media/defender-identity/delete-exclusion.png''
alt-text=``The Delete an exclusion option''
lightbox=``../../media/defender-identity/delete-exclusion.png'':::

=== Global excluded entities

You can now also configure exclusions by *Global excluded entities*.
Global exclusions allow you to define certain entities (IP addresses,
subnets, devices, or domains) to be excluded across all of the
detections Defender for Identity has. So for example, if you exclude a
device, it will only apply to those detections that have device
identification as part of the detection.

[arabic]
. In the left-hand menu, select *Global excluded entities*. You’ll see
the categories of entities that you can exclude.
+
:::image type=``content''
source=``../../media/defender-identity/global-excluded-entities.png''
alt-text=``The Global excluded entities submenu item''
lightbox=``../../media/defender-identity/global-excluded-entities.png'':::
. Choose an exclusion type. In this example, we selected *Exclude
domains*.
+
:::image type=``content''
source=``../../media/defender-identity/exclude-domains.png''
alt-text=``The Domains tab''
lightbox=``../../media/defender-identity/exclude-domains.png'':::
. A pane will open where you can add a domain to be excluded. Add the
domain you want to exclude.
+
:::image type=``content''
source=``../../media/defender-identity/add-excluded-domain.png''
alt-text=``The option to add a domain to be excluded''
lightbox=``../../media/defender-identity/add-excluded-domain.png'':::
. The domain will be added to the list. Select *Exclude domains* to
complete the exclusion.
+
:::image type=``content''
source=``../../media/defender-identity/select-exclude-domains.png''
alt-text=``The option to Select domains to be excluded''
lightbox=``../../media/defender-identity/select-exclude-domains.png'':::
. You’ll then see the domain in the list of entities to be excluded from
all detection rules. You can export the list, or remove the entities by
selecting them and clicking the *Remove* button.
+
:::image type=``content''
source=``../../media/defender-identity/global-excluded-entries-list.png''
alt-text=``The list of global excluded entries''
lightbox=``../../media/defender-identity/global-excluded-entries-list.png'':::

=== See also

* link:manage-security-alerts.md[Manage Defender for Identity security
alerts]
