= 
dcurwin

== Defender for Identity VPN integration in Microsoft 365 Defender

*Applies to:*

* Microsoft 365 Defender
* Defender for Identity

This article explains how to integrate a VPN with
link:/defender-for-identity[Microsoft Defender for Identity] in
link:/microsoft-365/security/defender/overview-security-center[Microsoft
365 Defender].

____
[!IMPORTANT] As part of the convergence with Microsoft 365 Defender,
some options and details have changed from their location in the
Defender for Identity portal. Please read the details below to discover
where to find both the familiar and new features.
____

[!INCLUDE link:includes/product-long.md[Product long]] can collect
accounting information from VPN solutions. When configured, the user’s
profile page includes information from the VPN connections, such as the
IP addresses and locations where connections originated. This
complements the investigation process by providing additional
information on user activity as well as a new detection for abnormal VPN
connections. The call to resolve an external IP address to a location is
anonymous. No personal identifier is sent in this call.

[!INCLUDE link:includes/product-short.md[Product short]] integrates with
your VPN solution by listening to RADIUS accounting events forwarded to
the [!INCLUDE link:includes/product-short.md[Product short]] sensors.
This mechanism is based on standard RADIUS Accounting
(https://tools.ietf.org/html/rfc2866[RFC 2866]), and the following VPN
vendors are supported:

* Microsoft
* F5
* Check Point
* Cisco ASA

=== Prerequisites

To enable VPN integration, make sure you set the following parameters:

* Open port UDP 1813 on your [!INCLUDE
link:includes/product-short.md[Product short]] sensors and/or [!INCLUDE
link:includes/product-short.md[Product short]] standalone sensors.

____
{empty}[!NOTE]

* By enabling *Radius Accounting*, the [!INCLUDE
link:includes/product-short.md[Product short]] sensor will enable a
pre-provisioned Windows firewall policy called *[!INCLUDE
link:includes/product-long.md[Product long]] Sensor* to allow incoming
RADIUS Accounting on port UDP 1813.
* VPN integration is not supported in environments adhering to Federal
Information Processing Standards (FIPS)
____

The example below uses Microsoft Routing and Remote Access Server (RRAS)
to describe the VPN configuration process.

If you’re using a third-party VPN solution, consult their documentation
for instructions on how to enable RADIUS Accounting.

=== Configure RADIUS Accounting on the VPN system

Perform the following steps on your RRAS server.

[arabic]
. Open the *Routing and Remote Access* console.
. Right-click the server name and select *Properties*.
. In the *Security* tab, under *Accounting provider*, select *RADIUS
Accounting* and select *Configure*.
+
:::image type=``content''
source=``../../media/defender-identity/radius-setup.png'' alt-text=``The
RADIUS setup''
lightbox=``../../media/defender-identity/radius-setup.png'':::
. In the *Add RADIUS Server* window, type the *Server name* of the
closest [!INCLUDE link:includes/product-short.md[Product short]] sensor
(which has network connectivity). For high availability, you can add
additional [!INCLUDE link:includes/product-short.md[Product short]]
sensors as RADIUS Servers. Under *Port*, make sure the default of 1813
is configured. Select *Change* and type a new shared secret string of
alphanumeric characters. Take note of the new shared secret string as
you’ll need to fill it out later during [!INCLUDE
link:includes/product-short.md[Product short]] Configuration. Check the
*Send RADIUS Account On and Accounting Off messages* box and select *OK*
on all open dialog boxes.
+
:::image type=``content''
source=``../../media/defender-identity/vpn-set-accounting.png''
alt-text=``The VPN setup''
lightbox=``../../media/defender-identity/vpn-set-accounting.png'':::

=== Configure VPN in Defender for Identity

[!INCLUDE link:includes/product-short.md[Product short]] collects VPN
data that helps profile the locations from which computers connect to
the network and to be able to detect suspicious VPN connections.

To configure VPN data in [!INCLUDE
link:includes/product-short.md[Product short]] in Microsoft 365
Defender:

[arabic]
. In Microsoft 365 Defender, go to *Settings* and then *Identities*.
+
:::image type=``content''
source=``../../media/defender-identity/settings-identities.png''
alt-text=``The Identities option under the settings menu item''
lightbox=``../../media/defender-identity/settings-identities.png'':::
. Select *VPN*.
. Select *Enable radius accounting*, and type the *Shared Secret* you
configured previously on your RRAS VPN Server. Then select *Save*.
+
:::image type=``content''
source=``../../media/defender-identity/vpn-integration.png''
alt-text=``The VPN integration''
lightbox=``../../media/defender-identity/vpn-integration.png'':::

After this is enabled, all Defender for Identity sensors will listen on
port 1813 for RADIUS accounting events, and your VPN setup is complete.

After the Defender for Identity sensor receives the VPN events and sends
them to the Defender for Identity cloud service for processing, the
entity profile will indicate distinct accessed VPN locations and
activities in the profile will indicate locations.

=== See also

* link:../defender/investigate-alerts.md[Investigate alerts in Microsoft
365 Defender]
