= Manage a group in the admin center
:audience: Admin
:author: MikePlumleyMSFT
:description: Learn to manage Microsoft 365 Groups, including adding remove group members, editing the email address, group name, or description, and customizing how the group works.
:f1.keywords: NOCSH
:manager: scotv
:ms.assetid: 74a1ef8b-3844-4d08-9980-9f8f7a36000f
:ms.author: mikeplum
:ms.collection: ["M365-subscription-management", "Adm_O365", "Adm_TOC"]
:ms.custom: admindeeplinkMAC
:ms.localizationpriority: medium
:ms.reviewer: arvaradh
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["BCS160", "MET150", "MOE150"]

== Manage a group in the Microsoft 365 admin center

After you have xref:create-groups.adoc[created a Microsoft 365 group] and added group members, you can configure your group.
You can edit the group name or description, manage owners or members, and specify whether external senders can email the group and whether to send copies of group conversations to members.

Go to the Microsoft 365 admin center at https://admin.microsoft.com.

=== Edit the group name or description

. In the admin center, expand *Groups*, and then click https://go.microsoft.com/fwlink/p/?linkid=2052855[*Groups*].
. Select the group that you want to edit, and then click *Edit name and description*.
. Update the name and description, and then select *Save*.

=== Manage group owners and members

. In the admin center, expand *Groups*, and then click https://go.microsoft.com/fwlink/p/?linkid=2052855[*Groups*].
. Click the name of the group you want to manage to open the settings pane.
. On the *Members* tab, choose if you want to manage owners or members.
. Choose *Add* to add someone or click *X* to remove someone.
. Click *Close*.

=== Send copies of conversations to group members' inboxes

When you use the admin center to create a group, by default users do not get copies of group emails sent to their inboxes though users get copies of group meeting invitations sent to their inboxes.
They'll need to go to the group to see conversations.
You can change this setting in the admin center.

When you turn this setting on, group members will get a copy of group emails and meeting invitations sent to their Outlook Inbox.
They can read and delete this copy of the email and not affect anyone else.
In the Group inbox, a copy of the email still exists.

Group members can opt out of receiving these emails by choosing to stop following the group in Outlook.

. In the admin center, expand *Groups*, and then click https://go.microsoft.com/fwlink/p/?linkid=2052855[*Groups*].
. Click the name of the group you want to manage to open the settings pane.
. On the *Settings* tab, select *Send copies of group conversations and events to group members* if you want members to receive copies of group messages and calendar items in their own inbox.
. Select *Save*.

=== Let people outside the organization email the group

This option is great if you want to have a company email address such as info@contoso.com.

. In the admin center, expand *Groups*, and then click https://go.microsoft.com/fwlink/p/?linkid=2052855[*Groups*].
. Click the name of the group you want to manage to open the settings pane.
. In the admin center groups list, select the name of the group you want to change, and then on the *Settings* tab, select *Allow external senders to email this group*.
. Select *Save*.

____
[!NOTE] It may take up to 30 minutes before users outside the organization can email the group.
____

=== Permanently delete a Microsoft 365 group

Sometimes you may want to permanently purge a group without waiting for the 30 day soft-deletion period to expire.
To do that, start PowerShell and run this command to get the object ID of the group:

[,powershell]
----
Get-AzureADMSDeletedGroup
----

Take note of the object ID of the group, or groups, that you want to permanently delete.

____
[!CAUTION] Purging the group removes the group and its data forever.
____

To purge the group run this command in PowerShell:

[,powershell]
----
Remove-AzureADMSDeletedDirectoryObject -Id <objectId>
----

To confirm that the group has been successfully purged, run the  _Get-AzureADMSDeletedGroup_  cmdlet again to confirm that the group no longer appears on the list of soft-deleted groups.
In some cases it may take as long as 24 hours for the group and all of its data to be permanently deleted.

=== Related articles

xref:create-groups.adoc[Create a Microsoft 365 group]

https://support.microsoft.com/office/bfc7a840-868f-4fd6-a390-f347bf51aff6[Manage guest access to Microsoft 365 Groups]

xref:../../solutions/choose-domain-to-create-groups.adoc[Choose the domain to use when creating Microsoft 365 Groups]

xref:../../solutions/allow-members-to-send-as-or-send-on-behalf-of-group.adoc[Allow members to send as or send on behalf of a Microsoft 365 group]

xref:../manage/upgrade-distribution-lists.adoc[Upgrade distribution lists to Microsoft 365 Groups]

xref:../../enterprise/manage-microsoft-365-groups-with-powershell.adoc[Manage Microsoft 365 Groups with PowerShell]
