= Buy a domain name
:audience: Admin
:author: efrene
:description: Learn how to buy a domain name in Microsoft 365.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.assetid: 1561140a-16a9-4a02-822d-a989250e479d
:ms.author: efrene
:ms.collection: ["highpri", "M365-subscription-management", "Adm_O365", "Adm_TOC", "Adm_O365_Setup"]
:ms.custom: ["VSBFY23", "AdminSurgePortfolio", "AdminTemplateSet"]
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["BCS160", "MET150", "MOE150", "GEA150"]

== Buy a domain name

____
[!NOTE] If your organization uses Office 365 operated by 21Vianet in China, see <<how-to-buy-a-domain-for-office-365-operated-by-21vianet,How to buy a domain for Office 365 operated by 21Vianet in China>>.
____

_To Add, modify or remove domains you *must* be a *Global Administrator* of a https://products.office.com/business/office[business or enterprise plan].
These changes affect the whole tenant, *Customized administrators_, or _regular users_ won't be able to make these changes.*

*link:../setup/domains-faq.yml[Check the Domains FAQ]* if you don't find what you're looking for.

=== Sign in and go to Settings > Domains > Buy a domain

. In the admin center, go to the *Settings* > https://go.microsoft.com/fwlink/p/?linkid=834818[Domains] page.
. On the *Domains* page, select *Buy domain*.

You can choose from the following top-level domains for your domain.

* .biz
* .com
* .info
* .me
* .mobi
* .net
* .org
* .tv
* .co.uk
* org.uk

____
[!NOTE] When you select *Buy domain*, you may be redirected to your Microsoft partner's website if the tenant is purchased/managed through a Microsoft partner.
____

=== Domain Privacy

We offer a free Domain Privacy Subscription with the purchase of a domain.
This keeps your contact information attached to the registration of your domain with ICANN private.
https://whois.icann.org/en/privacy-and-proxy-services[Learn more.]

=== Buy a domain from another domain registrar

If you want to buy a domain from a domain registrar other than https://www.godaddy.com[GoDaddy], we recommend you use one below that supports automatic setup (Domain Connect).

* https://www.1and1.com/[1&1 IONOS]
* https://www.wordpress.com[WordPress]

=== Transfer your domain to a different domain registrar

If your domain is managed by a provider that doesn't support all the necessary DNS records, you can transfer it to a different registrar.
When you transfer the domain, you change who you send payments to in order to renew and keep your domain name.

Request the transfer at the registrar that you want to move your domain to.
Look on their website for an option such as *Transfer DNS*.
After they make the changes, it can take a few days to update across the Internet.

::: moniker range="o365-21vianet"

=== How to buy a domain for Office 365 operated by 21Vianet

If you don't already have your own domain, you can easily buy one online at a domain name registrar, domain reseller, or even at your current Internet provider.
You get a domain name when you sign up for Office 365 operated by 21Vianet, for example, contoso.partner.onmschina.cn.
But you may want to use a custom domain name, like fourthcoffee.com.

To set up a domain in Microsoft 365, you must own a domain and change some of the DNS records for your domain.

____
[!CAUTION] Some domain registrars or DNS hosting providers do not allow creating all the DNS records required by Microsoft 365.
The following list of hosting providers supports all the needed records.
If you're thinking of using a different hosting provider, https://support.microsoft.com/office/dfbb03e3-08c1-4c4e-b2f0-891665b29b77[Service limitations when your hosting provider does not support SRV, CNAME, TXT, or redirection].
____

After you register your domain (at a domain registrar), you sign in to Microsoft 365 as an admin.
Then, set up your domain so you can use it with your email address and other services.

____
[!NOTE] The SharePoint Online Public Website information in this article only applies if your organization purchased Microsoft 365 prior to March 9, 2015.
____

==== Domain registrars that support all DNS records required for Microsoft 365

* https://oray.com/[Oray]
* https://www.hichina.com/[HiChina]
* http://www.east.net/[east.net]
* https://www.bizcn.com/[BIZCN]

::: moniker-end

=== Related content

xref:../setup/add-domain.adoc[Add a domain to Microsoft 365] (article) + link:../setup/domains-faq.yml[Domains FAQ] (article) + xref:../dns/update-dns-records-to-retain-current-hosting-provider.adoc[Update DNS records to keep your website with your current hosting provider] (article)
