= Find and fix issues after adding your domain or DNS records
:audience: Admin
:author: efrene
:description: Learn to track down any problems you run into while setting up a custom domain by making sure the DNS records are set up correctly.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.assetid: 40398b0b-bdd0-4afd-ab5e-b5ae6b7990bf
:ms.author: efrene
:ms.collection: ["highpri", "M365-subscription-management", "Adm_O365", "Adm_TOC", "Adm_O365_Setup"]
:ms.custom: ["VSBFY23", "AdminSurgePortfolio", "okr_smb", "AdminTemplateSet"]
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["BCS160", "MET150", "MOE150", "GEA150"]

== Find and fix issues after adding your domain or DNS records

*link:../setup/domains-faq.yml[Check the Domains FAQ]* if you don't find what you're looking for.

Getting your domain set up to work with Microsoft 365 can be challenging.
The DNS system is nitpicky to work with, and the DNS setup for your domain affects important business activities, like email!

____
[!NOTE] You can check for problems with your domain by checking its status.
Go to *Setup* > *Domains* and view the notifications in the *Status* column.
If you see an issue, select the three dots (more actions), and then choose *Check health*.
The pane that opens will describe any issues occurring with your domain.
____

=== What's going on?

* <<cant-verify-your-domain,Can't verify your domain?>>
* <<outlook-isnt-working,Outlook isn't working?>>
* <<everyones-email-got-switched-to-microsoft-365-and-you-only-wanted-your-email-to-switch,Everyone's email got switched to Microsoft 365 and you only wanted YOUR email to switch?>>
* <<cant-confirm-non-profit-or-school-account-status,Can't confirm non-profit or school account status?>>
* <<services-not-working-with-your-domain,Services not working with your domain?>>
* <<accessing-your-website-isnt-working,Accessing your website isn't working?>>

=== Can't verify your domain?

There are a couple of common reasons that domain verification doesn't work as it should:

. *The verification record value isn't quite correct.* Doublecheck that you've copied and pasted the exact value into the TXT verification record at your DNS host.
One common issue is not including the "MS=" part of the record.
We need that too!
. *The record hasn't been saved.* At some DNS hosts, you have to take an extra step to save the zone file (where the DNS record is stored) so that it will update across the Internet.
Make sure you've saved your changes so Microsoft 365 can see and verify the record.
. *The record hasn't updated across the Internet.* It typically only takes a few minutes for us to be able to see the new record, but occasionally it can take as long as a few hours.

=== Outlook isn't working?

If you've set up your MX record and other DNS records correctly for your domain, but mail doesn't work, let us help you link:/exchange/troubleshoot/outlook-connectivity/outlook-connection-issues[fix your Outlook problems].

=== Everyone's email got switched to Microsoft 365 and you only wanted YOUR email to switch?

+++<a name="BKMK_EmailSwitched">++++++</a>+++

When you add your domain to Microsoft 365, typically your domain's MX record is updated (by you or Microsoft 365) to point to Microsoft 365, and ALL email sent to that domain will start coming to Microsoft 365.
Make sure you've created mailboxes in Microsoft 365 for everyone who has email on your domain BEFORE you change the MX record.

What if you don't want to move email for everyone on your domain to Microsoft 365?
You can take steps to link:../setup/domains-faq.yml[pilot Microsoft 365 with just a few email addresses instead].

=== Can't confirm non-profit or school account status?

+++<a name="BKMK_validateAcct">++++++</a>+++

There are a couple of scenarios when you just need to verify your organization's domain and not set up any services.
For example, to prove to Microsoft 365 that your organization qualifies for a school subscription.

Check out the guidance in link:../setup/domains-faq.yml[Verify your Microsoft 365 domain to prove ownership, nonprofit or education status, or to activate Yammer] to make sure you've completed all the required steps.
It's a little different for each situation.

=== Services not working with your domain?

We can help you track down issues with your domain's DNS setup.
The domains troubleshooter in Microsoft 365 will show you any records that need fixing, and exactly what the records need to be set to.

____
[!TIP] Got your DNS set up correctly, but mail doesn't work in Outlook on your desktop?
Check out the link:/exchange/mail-flow-best-practices/mail-flow-best-practices[different mail flow scenarios you can have with Microsoft 365] to make sure you've got things set up correctly for your business.
Or get more troubleshooting help with email here: link:/exchange/troubleshoot/outlook-connectivity/outlook-connection-issues[Fix Outlook problems].
____

=== Accessing your website isn't working?

If you've fixed any DNS issues and you're still having trouble, try one of the following.

* People can't get to your website at _contoso.com_: xref:../setup/add-domain.adoc[Track down website issues]
* You can't update your A record or CNAME record to point to your website: xref:../setup/add-domain.adoc[Update custom DNS records in Microsoft 365]

=== Related content

link:/azure/active-directory/reports-monitoring/troubleshoot-audit-data-verified-domain[Troubleshoot: Audit data on verified domain change] (article) + link:../setup/domains-faq.yml[Domains FAQ] (article)
