= Invite users to a Microsoft 365 business subscription
:audience: Admin
:author: kwekua
:description: Invite users to join Microsoft 365 Business Standard organization
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.author: kwekua
:ms.collection: ["Adm_TOC"]
:ms.custom: ["AdminSurgePortfolio"]
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: article

== Invite users to a Microsoft 365 for business subscription (Admin)

____
[!IMPORTANT] These steps apply to Microsoft 365 Business Standard, Microsoft 365 Business Basic and Microsoft 365 Apps for business.
____

As the admin of a Microsoft 365 Business Standard subscription, you can invite your colleagues and coworkers to share and use your Microsoft 365 for business subscription.
When you invite your colleagues and coworkers to your subscription, you share all the following features and services:

* Get desktop versions of Office apps, including Outlook, Word, Excel, PowerPoint, and OneNote (plus Access and Publisher for PC only).
* Create a hub for teamwork to connect people using Microsoft Teams.
* Store and share files with 1 TB of OneDrive cloud storage per user.
* Use one license to cover fully installed Office apps on five mobile devices, five tablets, and five PCs or Macs per user.
* Get help anytime with around-the-clock phone and web support from Microsoft.

____
[!Note] The person who signs up for Microsoft 365 for business (usually the business owner) automatically becomes the technical administrator of the organization.
You can add other people as admins if you want help managing your Microsoft 365 services.
Check out xref:../add-users/assign-admin-roles.adoc[Assign admin roles] for more info.
____

=== Before you begin

Make sure you've already xref:signup-business-standard.adoc[signed up for Microsoft 365 Business Standard] or Microsoft 365 Apps for business.
And make sure you've already xref:../setup/setup-business-standard.adoc[set up your Business Standard organization] or xref:../setup/setup-apps-for-business.adoc[Set up Microsoft 365 Apps for business].
Once you've completed those steps, you can share an invite to your users.

=== Share an invitation to a Microsoft 365 for business subscription

. In the Microsoft 365 admin center, select *Invite people to Microsoft 365*.
. Add the usernames and email addresses for the people you want to invite and choose *Send*.
An invitation email will be sent to all the users you selected to add their user account information to Microsoft 365.

=== Next steps

Follow up with your users and make sure they got the email invite you sent about sharing your Microsoft 365 Business Standard subscription.

=== Frequently asked questions

==== I shared an email invite but the user didn't receive the email?

* Ask user to check their spam folder.
* Resend the invite email in the Microsoft 365 admin center.
From the admin center, hover over the user and select the action to resend email invite.
* Make sure the email address you entered for your user is correct.

==== How can I help an employee join my business and leave another business?

There are a couple of options in this case:

. They can contact the business owner or admin of the other business and ask to be removed from that business.
You can then add them to your organization.
. They can remove themselves by following the steps below:
 .. Go to https://myapps.microsoft.com/.
 .. Sign in to your account and select your profile initials.
 .. Select *View account* > *Manage organizations* > *Leave organization*
 .. Select *Leave* > *OK*.

==== How do I help someone install Microsoft Office?

Send them this article to help them install Office: https://support.microsoft.com/office/download-and-install-or-reinstall-microsoft-365-or-office-2019-on-a-pc-or-mac-4414eaaf-0478-48be-9c42-23adc4716658[Download and install Microsoft 365 Office or Office 2019 on a PC or a MAC].

==== How do I meet common GDPR (General Data Protection Regulation) obligations for my organization?

Under GDPR, an employee or customer may ask that you retrieve, or delete all information about them in your Microsoft cloud.
For more info, check out, link:/compliance/regulatory/gdpr-data-subject-requests[Data Subject Requests].

To search data that's been saved in the Microsoft cloud as part of your Microsoft 365 Business subscription, you and each user you've invited will need to visit https://account.microsoft.com/account/privacy to search data in locations such as OneDrive.
In addition, you (business or admin) may need to search for employee account data that's saved in the link:/compliance/regulatory/gdpr-dsr-office365[Azure Active Directory portal].

Depending on how you and other users save documents, you and every user you've invited may need to use built in search, and delete functionality to discover what is saved on your Windows PCs or Macs, on business apps on smartphones, and on non-Microsoft apps and sites.

____
[!NOTE] Once you attach a domain, and you and your users use business accounts to save data into the Microsoft cloud, you can conduct data subject requests on behalf of all users by following guidance in the link:/compliance/regulatory/gdpr-dsr-office365[Office 365 Data Subject Requests for the GDPR and CCPA] topic.
____

=== Related content

xref:../setup/setup-business-standard.adoc[Set up Microsoft 365 Business Standard]

xref:user-invite-business-standard.adoc[Accept invite to Microsoft 365 Business Standard (User)]
