= Quick help Deleted users checklist
:ROBOTS: NOINDEX
:audience: Admin
:author: kwekua
:description: Follow this checklist while deleting a user's Microsoft 365 account.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.assetid: 6016b50e-2b6e-4164-b565-2fde401fda3a
:ms.author: kwekua
:ms.collection: ["M365-subscription-management", "Adm_O365", "Adm_NonTOC"]
:ms.custom: AdminSurgePortfolio
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["BCS160", "MET150", "MOE150"]

== Quick help: Deleted users checklist

So, you've decided to delete a user from your organization.
For example, you can delete a user once that person leaves your organization.
There are a few things you should do before and after you delete that user.
This quick checklist helps you with the steps.

=== Remove the Microsoft 365 license from the user

You can remove a license from a user by searching for the user on the home page, or from the *Active users* page, and then selecting them.
On the *Licenses and Apps* tab, clear the check box for the license you want to remove from the user.
xref:../manage/remove-licenses-from-users.adoc[Read full article].

=== Block sign in

You can block the user so they can't sign in to your organization.
You can search for the user on the home page, or from the *Active users* page, and then select them.
At the top of the pane, under the user's name, select the *Block this user* icon, and then select the *Block this user from signing in* check box.
xref:../add-users/assign-admin-roles.adoc[Read full article].

=== Get their data

You can send this user's email to another employee or user in your organization by following these xref:../add-users/remove-former-employee.adoc[steps].
You can also back up and save any data from the former employee by following these xref:../add-users/get-access-to-and-back-up-a-former-user-s-data.adoc[steps].

=== Delete user

You can delete the user by searching for the user on the home page, or from the *Deleted users* page.
Select the user and select *Delete user*.
xref:../add-users/delete-a-user.adoc[Read full article].

=== What to do with the unassigned license

If you have a new employee or person that's joining your organization, you can assign them this license so they can use Microsoft 365.
You can search for the user on the home page, or from the *Active users* page, and then select them.
On the *Licenses and Apps* tab, select the check box for the license you want to add to the new user.
xref:../manage/assign-licenses-to-users.adoc[Read full article].

=== Remove license so you don't have to pay for it

You can also remove license from your subscription so you don't have to pay for it.
From the admin center home page, type *subscription* and select *View subscriptions*.
Select *Add/remove licenses*.
In the *Total licenses* box, enter the total number of licenses that you need for this subscription and then select *Submit change*.
For example, if you had 5 licenses and you need to remove 1 of them, you would enter *4*.
xref:../../commerce/licenses/buy-licenses.adoc[Read full article].
