= 
efrene

== Getting a mailbox not found error in Outlook on the web?

If you’re using Outlook on the web and you get a *Mailbox couldn’t be
found for* error, the account that you used to connect to Outlook on the
web doesn’t have an Exchange Online license and therefore, no mailbox is
associated with the account.

=== Assign a license to your account

Your admin can assign a license to your account by following these
steps:

[arabic]
. Open the
https://admin.microsoft.com/adminportal/home#/homepage[Microsoft 365
admin center] and go to *Active users* under the *Users* section, and
select the user who is seeing the error.
. In the user page that opens, go to the *Licenses and Apps* section,
select the appropriate *Location* value, and assign a license that
contains Exchange Online (expand the license to see its details).
. When you’re finished, click *Save changes*.

=== Related content

link:../email/add-another-email-alias-for-a-user.md[Add another email
alias for a user] (article) +
link:../email/configure-email-forwarding.md[Configure email forwarding
in Microsoft 365] (article) +
link:../email/create-a-shared-mailbox.md[Create a shared mailbox]
(article)
