= Get Microsoft Defender for Business
:audience: Admin
:author: denisebmsft
:description: Find out how to get Microsoft Defender for Business, endpoint protection for small and medium sized businesses.
:f1.keywords: NOCSH
:manager: dansimp
:ms.author: deniseb
:ms.collection: ["SMB", "m365-security-compliance"]
:ms.date: 08/11/2022
:ms.localizationpriority: medium
:ms.reviewer: shlomiakirav
:ms.service: microsoft-365-security
:ms.subservice: mdb
:ms.topic: overview
:search.appverid: MET150

== Get Microsoft Defender for Business

Defender for Business is a new endpoint security solution designed especially for small and medium-sized businesses (up to 300 employees).
This article describes how to get Defender for Business.

If you don't already have Microsoft Defender for Business, you can choose from several options:

* <<try-or-buy-microsoft-defender-for-business,Try or buy the standalone version of Defender for Business>>.
* <<get-microsoft-365-business-premium,Get Microsoft 365 Business Premium>>, which now includes Defender for Business.
* <<work-with-a-microsoft-partner,Work with a Microsoft partner>> who can help you get everything set up and configured.

If you have signed up for a trial, after you receive your acceptance email, you can <<how-to-activate-your-trial,activate your trial and assign user licenses>>, and then proceed to your <<next-steps,next steps>>.

=== Try or buy Microsoft Defender for Business

. Go to the https://www.microsoft.com/security/business/threat-protection/microsoft-defender-business[Microsoft Defender for Business] web page, and select the option to try or buy Defender for Business.
. When you receive your email with your account and subscription information, sign in using the link in your email.
. Proceed to xref:mdb-add-users.adoc[Add users and assign licenses].

____
[!TIP] See the xref:trial-playbook-defender-business.adoc[Trial playbook for Defender for Business].
____

=== Get Microsoft 365 Business Premium

_As of March 1, 2022, Defender for Business is included in Microsoft 365 Business Premium_.

. Visit the https://www.microsoft.com/microsoft-365/business/microsoft-365-business-premium?activetab=pivot%3aoverviewtab[Microsoft 365 Business Premium product page].
. Choose to try or buy your subscription.
See xref:../../commerce/try-or-buy-microsoft-365.adoc[Try or buy a Microsoft 365 for business subscription].
On the https://www.aka.ms/office365signup[Microsoft 365 Products site], choose *Microsoft 365 Business Premium*.
. After you have signed up for Microsoft 365 Business Premium, you'll receive an email with a link to sign in and get started.
Proceed to xref:../../business-premium/m365bp-setup.adoc[Set up Microsoft 365 Business Premium].

=== Work with a Microsoft partner

Microsoft has a list of solution providers who are authorized to sell offerings, including Microsoft 365 Business Premium and Microsoft Defender for Business.
To find a solution provider in your area, take the following steps:

. Go to the https://appsource.microsoft.com/marketplace/partner-dir[Browse Partners].
. In the *Filters* pane, specify search criteria, such as:
 ** Your location
 ** Your organization's size
 ** *Focus areas*, such as *Security* and/or *Threat Protection*
 ** *Services*, such as *Licensing* or *Managed Services (MSP)*

+
As soon as you select one or more criteria, the list of partners updates.
. Review the list of results.
Select a provider to learn more about their expertise and the services they provide.

=== How to activate your trial

When you receive your acceptance email, here's how to activate your trial subscription:

. In your acceptance email, select the link that includes your promo code.
. If you already have a Microsoft 365 subscription, sign in using your account.
If you don't already have a subscription, follow the prompts to create a new account.
. When you sign in for the first time, you'll go to the Microsoft 365 admin center (https://admin.microsoft.com/).
See xref:../../admin/admin-overview/admin-center-overview.adoc[Overview of the Microsoft 365 admin center].
. Use one of the following procedures, depending on your scenario: +
+
|===
| Scenario | Procedure

| You're setting up a Microsoft 365 subscription for the first time.
| Select *Go to guided setup* and complete the following steps:<ol><li>Either install your Office apps now, or choose *Continue* to skip this step.
(You can install your Office apps later.)</li><li>If your company has a domain, you can add it now (this option is recommended).
Alternately, you could choose to use your default `.onmicrosoft.com` domain for now.</li><li>Add users and assign licenses.
Each user you list will be assigned a license automatically.
See xref:mdb-add-users.adoc[Add users and assign licenses at the same time].</li></ol>

| You're adding a trial to an existing Microsoft 365 tenant.
| <ol><li>Go to the Microsoft 365 admin center (https://admin.microsoft.com/) and sign in.</li><li>In the navigation pane, choose *Users* > *Active users*.
Review the list of users.
</li><li>To assign licenses, follow the guidance in xref:../../admin/manage/assign-licenses-to-users.adoc[Assign licenses to users].</li></ol>
|===

=== Two portals for setup

When you're ready to get started, you'll work with two main portals: the Microsoft 365 admin center, and the Microsoft 365 Defender portal.

|===
| Portal | Description

| The Microsoft 365 admin center (https://admin.microsoft.com/)
| Use the Microsoft 365 admin center to activate your trial and sign in for the first time.<p> You'll also use the Microsoft 365 admin center to: <ul><li>Add or remove users.</li><li>Assign user licenses.</li><li>View your products and services.</li><li>Complete setup tasks for your Microsoft 365 subscription.</li></ul>To learn more, see xref:../../admin/admin-overview/admin-center-overview.adoc[Overview of the Microsoft 365 admin center].

| The Microsoft 365 Defender portal (https://security.microsoft.com)
| Use the Microsoft 365 Defender portal to set up and configure Defender for Business.<p>You'll use the Microsoft 365 Defender portal to: <ul><li>View your devices and device protection policies.</li><li>View detected threats and take action.</li><li>View security recommendations and manage your security settings.</li></ul>To learn more, see xref:mdb-get-started.adoc[Get started using the Microsoft 365 Defender portal].
|===

____
[!TIP] You can use the Microsoft Endpoint Manager admin center (https://endpoint.microsoft.com/) to onboard devices, and to configure security settings.
To learn more about Intune, see link:/mem/intune/fundamentals/what-is-intune[Microsoft Intune is an MDM and MAM provider for your devices].
____

=== Next steps

* xref:trial-playbook-defender-business.adoc[See the trial playbook: Microsoft Defender for Business].
* xref:mdb-use-wizard.adoc[Use the setup wizard in Microsoft Defender for Business].
* xref:mdb-setup-configuration.adoc[See the setup and configuration process for Defender for Business].
* xref:mdb-get-help.adoc[See how to get help and support for Defender for Business] (just in case you need help).
