= Microsoft Defender for Business preview features
:audience: Admin
:author: denisebmsft
:description: Learn how to access Microsoft Defender for Business preview features.
:keywords: preview, preview experience, Microsoft Defender for Business, features, updates
:manager: dansimp
:ms.author: deniseb
:ms.collection: ["m365-security-compliance"]
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mdb
:ms.topic: conceptual
:search.appverid: met150

== Microsoft Defender for Business preview features

*Applies to:*

* xref:mdb-overview.adoc[Microsoft Defender for Business]

Defender for Business is constantly being updated to include new feature enhancements and capabilities.

Learn about new features in Defender for Business preview releases, and be among the first to try upcoming features by turning on the preview experience.

=== What you need to know

When working with features in public preview, these features:

* Might have restricted or limited functionality.
For example, the feature might only apply to one platform.
* Typically go through feature changes before they're generally available (GA).
* Are fully supported by Microsoft.
* Might only be available in selected geographic regions or cloud environments.
For example, a preview feature might not exist in the government cloud.
* Individual features in preview might have more usage and support restrictions.
If so, this information is typically noted in the feature documentation.
* The preview versions are provided with a standard support level, and can be used for production environments.

=== Turn on preview features

If you turn on preview features, you'll have access to upcoming features, enabling you to provide feedback and help improve the overall experience before these features are generally available.

:::image type="content" source="media/mdb-previewfeatures.png" alt-text="Screenshot showing how to turn on preview features in advanced settings for endpoints.":::

Turn on the preview experience setting to be among the first to try upcoming features.

. In the navigation pane, select *Settings* > *Endpoints* > *Advanced features* > *Preview features*.
. Turn the setting to *On*, and then select *Save preferences*.

=== See also

xref:get-defender-business-servers.adoc[How to get Microsoft Defender for Business servers (preview)]
