= 
denisebmsft

== Microsoft 365 Lighthouse and Microsoft Defender for Business

=== Microsoft Defender for Business integrates with Microsoft 365 Lighthouse

If you’re a Microsoft Cloud Solution Provider (CSP) or Managed Service
Provider (MSP), you can use
link:../../lighthouse/m365-lighthouse-overview.md[Microsoft 365
Lighthouse] to manage security for your customers. Microsoft Defender
for Business and Defender for Endpoint integrate with Microsoft 365
Lighthouse, an admin portal that CSPs and MSPs can use to secure and
manage their customers’ data and devices.

:::image type=``content'' source=``media/lighthouse-incidents.png''
alt-text=``screenshot of incidents list in Microsoft 365 Lighthouse'':::

You can use the Microsoft 365 Lighthouse portal
(https://lighthouse.microsoft.com) to:

* Manage your customers’ security settings and capabilities.
* View and manage detected threats across your customers’ tenants.
* Initiate antivirus scans on customers’ devices to keep them up to date
and protected.

=== Learn more about Microsoft 365 Lighthouse

Microsoft 365 Lighthouse enables Microsoft CSPs and MSPs to secure and
manage devices, data, and users at scale.

To learn more, see:

* link:../../lighthouse/m365-lighthouse-overview.md[Overview of
Microsoft 365 Lighthouse]
* link:../../lighthouse/m365-lighthouse-requirements.md[Requirements for
Microsoft 365 Lighthouse]
* link:../../lighthouse/m365-lighthouse-sign-up.md[Sign up for Microsoft
365 Lighthouse]

=== See also

link:mdb-partners.md[Microsoft Defender for Business and managed service
provider resources] (provides information about RMM and PSA integration
for MSPs)
