= The simplified configuration process in Microsoft Defender for Business
:audience: Admin
:author: denisebmsft
:description: Defender for Business saves your business time with a simplified configuration process. See how it works and protects your business from day one.
:f1.keywords: NOCSH
:manager: dansimp
:ms.author: deniseb
:ms.collection: ["SMB", "M365-security-compliance", "m365-initiative-defender-business"]
:ms.date: 08/09/2022
:ms.localizationpriority: medium
:ms.reviewer: shlomiakirav
:ms.service: microsoft-365-security
:ms.subservice: mdb
:ms.topic: overview
:search.appverid: MET150

== The simplified configuration process in Microsoft Defender for Business

Microsoft Defender for Business features a simplified configuration process designed especially for small and medium-sized businesses.
A wizard-like experience takes the guesswork out of onboarding and managing devices.
*We recommend using the simplified configuration process, but you're not limited to this option*.

To onboard devices and configure security settings for your company's devices, you can choose from these experiences:

* The simplified configuration process in Microsoft Defender for Business;
or
* Use Microsoft Intune.

=== What to do

. <<review-your-setup-and-configuration-options,Review your setup and configuration options>>.
. <<next-steps,Proceed to your next steps>>.

=== Review your setup and configuration options

The following table describes each experience.

|===
| Portal experience | Description

| The simplified configuration experience in the Microsoft 365 Defender portal (https://security.microsoft.com)
| The simplified configuration experience includes a xref:mdb-use-wizard.adoc[wizard-like experience] to help you set up and configure Defender for Business.
Simplified configuration also includes default security settings and policies to help protect your company's devices as soon as they're onboarded to Defender for Business.
You can view and edit your default policies to suit your business needs.
To learn more, see xref:mdb-view-edit-policies.adoc[View or edit device policies in Microsoft Defender for Business].
+  + With the simplified experience, your security team uses the Microsoft 365 Defender portal as a one-stop shop to: <ul><li>Set up and configure Defender for Business</li><li>View and manage incidents</li><li>Respond to and mitigate threats</li><li>View reports</li><li>Review pending or completed actions

| The Microsoft Endpoint Manager admin center (https://endpoint.microsoft.com)
| Microsoft Intune is a cloud-based mobile device management (MDM) and mobile application management (MAM) provider for apps and devices.
If you're already using Intune, you can continue to use the Endpoint Manager admin center to manage devices such as mobile phones, tablets, and laptops.
See link:/mem/intune/fundamentals/what-is-device-management[Microsoft Intune: Device management].
|===

=== Next steps

* xref:mdb-setup-configuration.adoc[Set up and configure Microsoft Defender for Business].
* xref:mdb-get-started.adoc[Get started using Microsoft Defender for Business].
