= 
denisebmsft

== Respond to and mitigate threats in Microsoft Defender for Business

The Microsoft 365 Defender portal enables your security team to respond
to and mitigate detected threats. This article walks you through an
example of how you can use Defender for Business.

=== View detected threats

[arabic]
. Go to the Microsoft 365 Defender portal
(https://security.microsoft.com) and sign in.
. Notice cards on the Home page. Cards tell you at a glance how many
threats were detected, along with how many user accounts, endpoints
(devices), and other assets were affected. The following image is an
example of cards you might see:
+
:::image type=``content''
source=``../../media/defender-business/mdb-examplecards.png''
alt-text=``Screenshot of cards in the Microsoft 365 Defender portal'':::
. Select a button or link on the card to view more information and take
action. As an example, our *Devices at risk* card includes a *View
details* button. Selecting that button takes us to the *Devices* list,
as shown in the following image:
+
:::image type=``content''
source=``../../media/defender-business/mdb-deviceinventory.png''
alt-text=``Screenshot of device inventory'':::
+
The *Devices* page lists company devices, along with their risk level
and exposure level.
. Select an item, such as a device. A flyout pane opens and displays
more information about alerts and incidents generated for that item, as
shown in the following image:
+
:::image type=``content''
source=``../../media/defender-business/mdb-deviceinventory-selecteddeviceflyout.png''
alt-text=``Screenshot of the flyout pane for a selected device'':::
. On the flyout, view the information that is displayed. Select the
ellipsis (…) to open a menu that lists available actions, as shown in
the following image:
+
:::image type=``content''
source=``../../media/defender-business/mdb-deviceinventory-selecteddeviceflyout-menu.png''
alt-text=``Screenshot of available actions for a selected device'':::
. Select an available action. For example, you might choose *Run
antivirus scan*, which will cause Microsoft Defender Antivirus to start
a quick scan on the device. Or, you could select *Initiate Automated
Investigation* to trigger an automated investigation on the device.

=== Next steps

* link:mdb-review-remediation-actions.md[Review remediation actions in
the Action center]
* link:mdb-manage-devices.md[Manage devices in Defender for Business]
* link:mdb-view-manage-incidents.md[View and manage incidents in
Defender for Business]
