= 
denisebmsft

== View and edit security policies and settings in Microsoft Defender for Business

After you’ve onboarded your company’s devices to Defender for Business,
the next step is to review your security policies.

____
[!TIP] Defender for Business includes preconfigured security policies
with recommended settings. You can edit these settings to suit your
business needs.
____

Security policies to review and configure include:

* *link:#view-or-edit-your-next-generation-protection-policies[Next-generation
protection policies]*, which determine antivirus and antimalware
protection for your company’s devices
* *link:#view-or-edit-your-firewall-policies-and-custom-rules[Firewall
protection and rules]*, which determine what network traffic is allowed
to flow to and from your company’s devices
* *link:#set-up-web-content-filtering[Web content filtering]*, which
prevents people from visiting certain websites (URLs) based on
categories, such as adult content or legal liability
* *link:#review-settings-for-advanced-features[Advanced features]*, such
as automated investigation and response and endpoint detection and
response (EDR) in block mode

In Defender for Business, security policies are applied to devices
through
link:mdb-create-edit-device-groups.md#what-is-a-device-group[device
groups].

In addition to your security policies, you can
link:#view-and-edit-other-settings-in-the-microsoft-365-defender-portal[view
and edit settings], such as which time zone to use in the Microsoft 365
Defender portal (https://security.microsoft.com) and whether to receive
preview features as they become available.

Use this article as a guide to managing your security policies and
settings.

=== What to do

[arabic]
. link:#choose-where-to-manage-security-policies-and-devices[Choose
where to manage your security policies and devices].
. link:#view-or-edit-your-next-generation-protection-policies[Review
your next-generation protection policies].
. link:#view-or-edit-your-firewall-policies-and-custom-rules[Review your
firewall policies and custom rules].
. link:#set-up-web-content-filtering[Set up web content filtering].
. link:#review-settings-for-advanced-features[Review settings for
advanced features].
. link:#view-and-edit-other-settings-in-the-microsoft-365-defender-portal[View
other settings in the Microsoft 365 Defender portal].
. link:#next-steps[Proceed to your next steps].

=== Choose where to manage security policies and devices

Defender for Business features a
link:mdb-simplified-configuration.md[simplified configuration process]
that helps streamline the setup and configuration process. If you select
the simplified configuration process, you can view and manage your
security policies in the Microsoft 365 Defender portal
(https://security.microsoft.com/). However, you’re not limited to this
option. If you’ve been using Microsoft Intune, you can keep using the
Microsoft Endpoint Manager admin center.

The following table can help you choose where to manage your security
policies and devices.

[width="100%",cols="<50%,<50%",options="header",]
|===
|Option |Description
|*Use the Microsoft 365 Defender portal* (_recommended_) |The Microsoft
365 Defender portal (https://security.microsoft.com/) is a one-stop shop
for managing your company’s devices, security policies, and security
settings. You can access your security policies and settings, use the
link:mdb-view-tvm-dashboard.md[Microsoft Defender Vulnerability
Management dashboard], and link:mdb-view-manage-incidents.md[view and
manage incidents] all in one place.

|*Use the Microsoft Endpoint Manager admin center* |If your company is
already using Intune to manage security policies, you can continue using
the Endpoint Manager admin center to manage your devices and security
policies. To learn more, see
link:/mem/intune/protect/endpoint-security-policy[Manage device security
with endpoint security policies in Microsoft Intune].
|===

____
[!IMPORTANT] If you’re managing security policies in the Microsoft 365
Defender portal, you can _view_ those policies in the Endpoint Manager
admin center (https://endpoint.microsoft.com), where they’re listed as
*Antivirus* or *Firewall* policies. When you view your firewall policies
in the admin center, you’ll see two policies listed: one policy for
firewall protection and another for custom rules.
____

=== View or edit your next-generation protection policies

Depending on whether you’re using the Microsoft 365 Defender portal or
the Microsoft Endpoint Manager admin center to manage your
next-generation protection policies, use one of the following
procedures:

[width="100%",cols="<50%,<50%",options="header",]
|===
|Portal |Procedure
|Microsoft 365 Defender portal (https://security.microsoft.com) |

|Microsoft Endpoint Manager admin center
(https://endpoint.microsoft.com) |For help managing your security
settings in Intune, start with
link:/mem/intune/protect/endpoint-security[Manage endpoint security in
Microsoft Intune].
|===

=== View or edit your firewall policies and custom rules

Depending on whether you’re using the Microsoft 365 Defender portal or
the Microsoft Endpoint Manager admin center to manage your firewall
protection, use one of the following procedures.

[width="100%",cols="<50%,<50%",options="header",]
|===
|Portal |Procedure
|Microsoft 365 Defender portal (https://security.microsoft.com) |

|Microsoft Endpoint Manager admin center
(https://endpoint.microsoft.com) |For help managing your security
settings in Intune, start with
link:/mem/intune/protect/endpoint-security[Manage endpoint security in
Microsoft Intune].
|===

=== Set up web content filtering

Web content filtering enables your security team to track and regulate
access to websites based on content categories, such as:

* Adult content: Sites that are related to cults, gambling, nudity,
pornography, sexually explicit material, or violence
* High bandwidth: Download sites, image sharing sites, or peer-to-peer
hosts
* Legal liability: Sites that include child abuse images, promote
illegal activities, foster plagiarism or school cheating, or that
promote harmful activities
* Leisure: Sites that provide web-based chat rooms, online gaming,
web-based email, or social networking
* Uncategorized: Sites that have no content or that are newly registered

Not all websites in these categories are malicious, but they could be
problematic for your company because of compliance regulations,
bandwidth usage, or other concerns. You can create an audit-only policy
to get a better understanding of whether your security team should block
any website categories.

Web content filtering is available on the major web browsers, with
blocks performed by Windows Defender SmartScreen (Microsoft Edge) and
Network Protection (Chrome, Firefox, Brave, and Opera). For more
information, see
link:../defender-endpoint/web-content-filtering.md#prerequisites[Prerequisites
for web content filtering].

==== To set up web content filtering

[arabic]
. In the Microsoft 365 Defender portal (https://security.microsoft.com),
choose *Settings* > *Web content filtering* > *+ Add policy*.
. Specify a name and description for your policy.
. Select the categories to block. Use the expand icon to fully expand
each parent category, and then select specific web content categories.
To set up an audit-only policy that doesn’t block any websites, don’t
select any categories.
+
Don’t select *Uncategorized*.
. Specify the policy scope by selecting device groups to apply the
policy to. Only devices in the selected device groups will be prevented
from accessing websites in the selected categories.
. Review the summary and save the policy. The policy refresh might take
up to two hours to apply to your selected devices.

____
[!TIP] To learn more about web content filtering, see
link:../defender-endpoint/web-content-filtering.md[Web content
filtering].
____

=== Review settings for advanced features

In addition to next-generation protection, firewall, and web
content-filtering policies, Defender for Business includes advanced
security features. These features are preconfigured to recommended
settings. You can review and edit the settings to suit your business
needs.

To access settings for advanced features in the Microsoft 365 Defender
portal (https://security.microsoft.com), go to *Settings* > *Endpoints*
> *General* > *Advanced features*.

The following table describes advanced feature settings.

[width="100%",cols="<50%,<50%",options="header",]
|===
|Setting |Description
|*Automated Investigation* (turned on by default) |As alerts are
generated, automated investigations can occur. Each automated
investigation determines whether a detected threat requires action and
then takes or recommends remediation actions, such as sending a file to
quarantine, stopping a process, isolating a device, or blocking a URL.
While an investigation is running, any related alerts that arise are
added to the investigation until it’s completed. If an affected entity
is seen elsewhere, the automated investigation expands its scope to
include that entity, and the investigation process repeats.

|*Live Response* |Defender for Business includes the following types of
manual response actions:

|*Live Response for Servers* |(This setting is currently not available
in Defender for Business.)

|*Live Response unsigned script execution* |(This setting is currently
not available in Defender for Business.)

|*Enable EDR in block mode*(turned on by default) |Provides added
protection from malicious artifacts when Microsoft Defender Antivirus
isn’t the primary antivirus product and is running in passive mode on a
device. Endpoint detection and response (EDR) in block mode works behind
the scenes to remediate malicious artifacts detected by EDR
capabilities. Such artifacts might have been missed by the primary,
non-Microsoft antivirus product.

|*Allow or block a file* (turned on by default) |Enables you to allow or
block a file by using
link:../defender-endpoint/indicator-file.md[indicators]. This capability
requires Microsoft Defender Antivirus to be in active mode and
link:../defender-endpoint/cloud-protection-microsoft-defender-antivirus.md[cloud
protection] turned on.

|*Custom network indicators*(turned on by default) |Enables you to allow
or block an IP address, URL, or domain by using
link:../defender-endpoint/indicator-ip-domain.md[network indicators].
This capability requires Microsoft Defender Antivirus to be in active
mode and link:../defender-endpoint/enable-network-protection.md[network
protection] turned on.

|*Tamper protection*(we recommend you turn on this setting) |Tamper
protection prevents malicious apps from doing actions such as:

|*Show user details*(turned on by default) |Enables people in your
organization to see details, such as employees’ pictures, names, titles,
and departments. These details are stored in Azure Active Directory
(Azure AD).

|*Skype for Business integration*(turned on by default) |Skype for
Business was retired in July 2021. If you haven’t already moved to
Microsoft Teams, see link:/microsoftteams/deploy-small-business[Set up
Microsoft Teams in your small business].

|*Web content filtering*(turned on by default) |Blocks access to
websites that contain unwanted content and tracks web activity across
all domains. See link:#set-up-web-content-filtering[Set up web content
filtering].

|*Microsoft Intune connection*(we recommend you turn on this setting if
you have Intune) |If your organization’s subscription includes Microsoft
Intune (included in link:../../business/index.yml[Microsoft 365 Business
Premium]), this setting enables Defender for Business to share
information about devices with Intune.

|*Device discovery*(turned on by default) |Enables your security team to
find unmanaged devices that are connected to your company network.
Unknown and unmanaged devices introduce significant risks to your
network, whether it’s an unpatched printer, a network device with a weak
security configuration, or a server with no security controls.

|*Preview features* |Microsoft is continually updating services such as
Defender for Business to include new feature enhancements and
capabilities. If you opt in to receive preview features, you’ll be among
the first to try upcoming features in the preview experience.
|===

=== View and edit other settings in the Microsoft 365 Defender portal

In addition to security policies applied to devices, there are other
settings you can view and edit in Defender for Business. For example,
you specify the time zone to use, and you can onboard (or offboard)
devices.

____
[!NOTE] You might see more settings in your tenant than are listed in
this article. This article highlights the most important settings that
you should review in Defender for Business.
____

==== Settings to review for Defender for Business

The following table describes settings you can view and edit in Defender
for Business:

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Category |Setting |Description
|*Security center* |*Time zone* |Select the time zone to use for the
dates and times displayed in incidents, detected threats, and automated
investigation and remediation. You can either use UTC or your local time
zone (_recommended_).

|*Microsoft 365 Defender* |*Account* |View details such where your data
is stored, your tenant ID, and your organization (org) ID.

|*Microsoft 365 Defender* |*Preview features* |Turn on preview features
to try upcoming features and new capabilities. You can be among the
first to preview new features and provide feedback.

|*Endpoints* |*Email notifications* |Set up or edit your email
notification rules. When vulnerabilities are detected or an alert is
created, the recipients specified in your email notification rules will
receive an email. link:mdb-email-notifications.md[Learn more about email
notifications].

|*Endpoints* |*Device management* > *Onboarding* |Onboard devices to
Defender for Business by using a downloadable script. To learn more, see
link:mdb-onboard-devices.md[Onboard devices to Defender for Business].

|*Endpoints* |*Device management* > *Offboarding* |Offboard (remove)
devices from Defender for Business. When you offboard a device, it no
longer sends data to Defender for Business, but data received prior to
offboarding is retained. To learn more, see
link:mdb-offboard-devices.md[Offboarding a device].
|===

==== Access your settings in the Microsoft 365 Defender portal

[arabic]
. Go to the Microsoft 365 Defender portal
(https://security.microsoft.com/), and sign in.
. Select *Settings*, and then select a category (such as *Security
center*, *Microsoft 365 Defender*, or *Endpoints*).
. In the list of settings, select an item to view or edit.

=== Next steps

* link:mdb-get-started.md[Get started using Defender for Business]
* link:mdb-manage-devices.md[Manage devices in Defender for Business]
* link:mdb-view-manage-incidents.md[View and manage incidents in
Defender for Business]
* link:mdb-view-edit-policies.md[View or edit policies in Defender for
Business]
