= 
denisebmsft

== Resources for Microsoft partners using Microsoft Defender for Business and Microsoft 365 Business Premium

Small and medium-sized businesses recognize security as a key component
to their success, but often don’t have the capacity or expertise to have
a dedicated security operations team. Customers often need help with
managing the security of their endpoints and network, and addressing
alerts or detected threats. Microsoft partners can help!

If you’re a Microsoft partner, and you’re working with customers who
have or need link:mdb-overview.md[Defender for Business],
link:../../business-premium/index.md[Microsoft 365 Business Premium], or
link:../defender-endpoint/microsoft-defender-endpoint.md[Defender for
Endpoint], this article is for you.

* link:#integrate-microsoft-endpoint-security-with-your-rmm-tools-and-psa-software[Learn
how you can integrate Microsoft endpoint security with your RMM tools
and PSA software].
* link:#use-microsoft-365-lighthouse-to-secure-and-manage-your-customers-devices-and-data[See
how you can use Microsoft 365 Lighthouse to secure and manage your
customers’ devices and data].
* link:#learn-more-about-defender-for-business-and-microsoft-365-business-premium[Learn
more about Defender for Business and Microsoft 365 Business Premium].

=== Integrate Microsoft endpoint security with your RMM tools and PSA software

If you’re a Microsoft Managed Service Provider (MSP), you can integrate
Microsoft endpoint security with your remote monitoring and management
(RMM) tools and your professional service automation (PSA) software so
that you can:

* Get access to your customers’ Microsoft 365 Defender portal to
link:mdb-respond-mitigate-threats.md[address detected threats and
incidents].
* Get link:mdb-email-notifications.md[email notifications] about new
alerts or vulnerabilities across your customers’ tenants.
* Fetch and view link:mdb-view-manage-incidents.md[incidents and alerts]
with your security information and event management (SIEM) tools.
* Orchestrate link:mdb-review-remediation-actions.md[remediation
actions], such as approving actions following automated investigations,
or taking manual response actions on a device.

Integration can be done by using the
link:../defender-endpoint/management-apis.md[Defender for Endpoint
APIs]. Use the following resources to learn more:

[width="100%",cols="<50%,<50%",options="header",]
|===
|Resource |Description
|link:../defender-endpoint/management-apis.md[Overview of management and
APIs] |Defender for Business is built on Microsoft Defender for
Endpoint, and is an integration-ready platform. This article describes
how to automate workflows and innovate using the Defender for Endpoint
APIs.

|link:../defender-endpoint/configure-mssp-support.md[Configure managed
security service provider integration] |Provides an overview of steps to
take to successfully integrate a customer’s tenant with your MSP
solution.
|===

=== Use Microsoft 365 Lighthouse to secure and manage your customers’ devices and data

If you’re a Microsoft Cloud Solution Provider (CSP) or MSP, you can use
Microsoft 365 Lighthouse to help your customers manage their security
settings and capabilities, and protect their data and devices. You can
use Microsoft 365 Lighthouse to:

* Manage your customers’ security settings and capabilities.
* View and manage detected threats across your customers’ tenants.
* Initiate antivirus scans on customers’ devices to keep them up to date
and protected.

[width="100%",cols="<50%,<50%",options="header",]
|===
|Resource |Description
|link:../../lighthouse/m365-lighthouse-overview.md[Microsoft 365
Lighthouse] |Provides an overview of Microsoft 365 Lighthouse, an admin
portal that helps MSPs and CSPs secure and manage devices, data, and
users for small and medium-sized businesses.

|link:mdb-lighthouse-integration.md[Microsoft 365 Lighthouse and
Microsoft Defender for Business] |Describes how Defender for Business
integrates with Microsoft 365 Lighthouse and includes links to
additional information.
|===

=== Learn more about Defender for Business and Microsoft 365 Business Premium

[width="100%",cols="<50%,<50%",options="header",]
|===
|Resource |Description
|https://partner.microsoft.com[Microsoft Partner Network] |Visit the
Microsoft Partner Network to learn how to become a Microsoft partner and
join the Microsoft Partner Network.

|https://aka.ms/M365MDBseries[Microsoft 365 Business Premium and
Defender for Business partner webinar series] |This webinar series
provides:

|https://aka.ms/M365BPPartnerPlaybook[Microsoft 365 Business Premium
partner playbook and readiness series] |Practical guidance on building a
profitable managed services practice, with:

|https://aka.ms/MDBPartnerKit[Defender for Business partner kit] |The
Defender for Business partner kit provides you with practical guidance,
technical information, and customer-ready resources to market and sell
Defender for Business to small and medium-sized businesses.
|===
