= 
denisebmsft

== The simplified configuration process in Microsoft Defender for Business

Microsoft Defender for Business features a simplified configuration
process designed especially for small and medium-sized businesses. A
wizard-like experience takes the guesswork out of onboarding and
managing devices. *We recommend using the simplified configuration
process, but you’re not limited to this option*.

To onboard devices and configure security settings for your company’s
devices, you can choose from these experiences:

* The simplified configuration process in Microsoft Defender for
Business; or
* Use Microsoft Intune.

=== What to do

[arabic]
. link:#review-your-setup-and-configuration-options[Review your setup
and configuration options].
. link:#next-steps[Proceed to your next steps].

=== Review your setup and configuration options

The following table describes each experience.

[width="100%",cols="50%,50%",options="header",]
|===
|Portal experience |Description
|The simplified configuration experience in the Microsoft 365 Defender
portal (https://security.microsoft.com) |The simplified configuration
experience includes a link:mdb-use-wizard.md[wizard-like experience] to
help you set up and configure Defender for Business. Simplified
configuration also includes default security settings and policies to
help protect your company’s devices as soon as they’re onboarded to
Defender for Business. You can view and edit your default policies to
suit your business needs. To learn more, see
link:mdb-view-edit-policies.md[View or edit device policies in Microsoft
Defender for Business].With the simplified experience, your security
team uses the Microsoft 365 Defender portal as a one-stop shop to:

|The Microsoft Endpoint Manager admin center
(https://endpoint.microsoft.com) |Microsoft Intune is a cloud-based
mobile device management (MDM) and mobile application management (MAM)
provider for apps and devices. If you’re already using Intune, you can
continue to use the Endpoint Manager admin center to manage devices such
as mobile phones, tablets, and laptops. See
link:/mem/intune/fundamentals/what-is-device-management[Microsoft
Intune: Device management].
|===

=== Next steps

* If you’re ready to start your trial subscription, see
link:trial-playbook-defender-business.md[Trial user guide: Microsoft
Defender for Business].
* If you’re ready to use the simplified setup experience, see
link:mdb-use-wizard.md[Use the setup wizard in Microsoft Defender for
Business].
* If you want to see the overall setup process, see
link:mdb-setup-configuration.md[Set up and configure Microsoft Defender
for Business].
