= 
denisebmsft

== Trial user guide: Microsoft Defender for Business

*Welcome to the Defender for Business trial user guide!*

This guide will help you set up and use key features of your free trial.
Using recommendations in this article from the Microsoft Defender team,
learn how Defender for Business can help elevate your security from
traditional antivirus protection to next-generation protection, endpoint
detection and response, and vulnerability management.

=== What is Defender for Business?

Defender for Business is a new endpoint security solution designed
especially for small and medium-sized businesses with up to 300
employees. With this endpoint security solution, your organization’s
devices are well-protected from ransomware, malware, phishing, and other
threats.

:::image type=``content'' source=``media/mdb-offering-overview.png''
alt-text=``Defender for Business features and capabilities.'':::

*Let’s get started!*

=== Set up your trial

Here’s how to set up your trial subscription:

[arabic]
. link:#step-1-add-users-and-assign-licenses[Add users and assign
licenses].
. link:#step-2-visit-the-microsoft-365-defender-portal[Visit the
Microsoft 365 Defender portal].
. link:#step-3-use-the-setup-wizard-in-defender-for-business-recommended[Use
the setup wizard].
. link:#step-4-set-up-and-configure-defender-for-business[Set up and
configure Defender for Business].

==== Step 1: Add users and assign licenses

After you sign up for Defender for Business, the first step is to
*link:mdb-add-users.md[add users and assign licenses]*.

____
[!NOTE] You must be a global administrator to perform this task. The
person who signed your company up for Microsoft 365 or Defender for
Business is the global administrator by default.
link:mdb-roles-permissions.md[Learn more about roles and permissions].
____

==== Step 2: Visit the Microsoft 365 Defender portal

The Microsoft 365 Defender portal (https://security.microsoft.com) is
the one-stop shop where you use and manage Defender for Business. It
includes callouts to help you get started, cards that surface relevant
information, and a navigation bar that provides easy access to the
various features and capabilities.

* *link:mdb-get-started.md[Visit the Microsoft 365 Defender portal]*.
* *link:mdb-get-started.md#the-navigation-bar[Explore the navigation
bar]* on the left side of the screen to access your incidents, view
reports, and manage your security policies and settings.

==== Step 3: Use the setup wizard in Defender for Business (recommended)

Defender for Business was designed to save small and medium-sized
businesses time and effort. You can do initial setup and configuration
through a setup wizard. The setup wizard helps you grant access to your
security team, set up email notifications for your security team, and
onboard your company’s Windows devices. *link:mdb-use-wizard.md[Use the
setup wizard]*.

____
[!NOTE] You can only use the setup wizard once.
____

===== Setup wizard flow: what to expect

____
[!TIP] *Using the setup wizard is optional.* (See
link:mdb-use-wizard.md#what-happens-if-i-dont-use-the-wizard[What
happens if I don’t use the wizard?]). If you choose not to use the
wizard, or if the wizard is closed before your setup process is
complete, you can complete the setup and configuration process on your
own. See link:#step-4-set-up-and-configure-defender-for-business[Step 4:
Set up and configure Defender for Business].
____

[arabic]
. *link:mdb-roles-permissions.md#view-or-edit-role-assignments[Assign
user permissions]*. Grant your security team access to the Microsoft 365
Defender portal.
. *link:mdb-email-notifications.md#view-and-edit-email-notifications[Set
up email notifications]* for your security team.
. *link:mdb-onboard-devices.md[Onboard and configure Windows devices]*.
Onboarding devices right away helps protect those devices from day one.
+
____
[!NOTE] When you use the setup wizard, the system detects if you have
Windows devices that are already enrolled in Intune. You’ll be asked if
you want to use automatic onboarding for all or some of those devices.
You can onboard all Windows devices at once or select specific devices
at first and then add more devices later.
link:mdb-use-wizard.md#what-is-automatic-onboarding[Learn more about
automatic onboarding].
____
+
To onboard other devices, see
link:#step-4-set-up-and-configure-defender-for-business[Step 4: Set up
and configure Defender for Business].
. *link:mdb-configure-security-settings.md[View and edit your security
policies]*. Defender for Business includes default security policies for
next-generation protection and firewall protection that can be applied
to your company’s devices. These preconfigured security policies use
recommended settings, so you’re protected as soon as your devices are
onboarded to Defender for Business. And you can edit the policies or
create new ones.

==== Step 4: Set up and configure Defender for Business

If you choose not to use the setup wizard, see the following diagram
that depicts the
link:mdb-setup-configuration.md#the-setup-and-configuration-process[overall
setup and configuration process] for Defender for Business.

link:mdb-setup-configuration.md[:::image type=``content''
source=``media/mdb-setup-process-2.png'' alt-text=``Setup and
configuration process for Defender for Business.'':::]

If you used the setup wizard but you need to onboard more devices, such
as non-Windows devices, go directly to link:mdb-onboard-devices.md[step
4] in the following procedure:

[arabic]
. *link:mdb-requirements.md[Review the requirements]* to configure and
use Defender for Business.
. *link:mdb-roles-permissions.md[Assign roles and permissions]* in the
Microsoft 365 Defender portal.
* link:mdb-roles-permissions.md#roles-in-defender-for-business[Learn
about roles in Defender for Business].
* link:mdb-roles-permissions.md#view-or-edit-role-assignments[View or
edit role assignments for your security team].
. *link:mdb-email-notifications.md[Set up email notifications]* for your
security team.
* link:mdb-email-notifications.md#types-of-email-notifications[Learn
about types of email notifications].
* link:mdb-email-notifications.md#view-and-edit-email-notifications[View
and edit email notification settings].
. *link:mdb-onboard-devices.md[Onboard devices]*. To onboard Windows and
Mac clients, you can use a local script.
. *link:mdb-configure-security-settings.md[View and configure your
security policies]*. After you onboard your company’s devices to
Defender for Business, the next step is to view and edit your security
policies and settings.

Defender for Business includes pre-configured security policies that use
recommended settings. But you can edit the settings to suit your
business needs.

Security policies to review and configure include:

* link:mdb-configure-security-settings.md#view-or-edit-your-next-generation-protection-policies[Next-generation
protection policies] which determine antivirus and antimalware
protection for your company’s devices
* link:mdb-configure-security-settings.md#view-or-edit-your-firewall-policies-and-custom-rules[Firewall
protection and rules] which determine what network traffic is allowed to
flow to and from your company’s devices
* link:mdb-configure-security-settings.md#set-up-web-content-filtering[Web
content filtering]which prevents people from visiting certain websites
(URLs) based on categories, such as adult content or legal liability
* link:mdb-configure-security-settings.md#review-settings-for-advanced-features[Advanced
features] such as automated investigation and response and endpoint
detection and response (EDR) in block mode

=== Start using Defender for Business

For the next 30 days, here’s guidance from the product team on key
features to try:

[arabic]
. link:#1-use-the-defender-vulnerability-management-dashboard[Use your
Microsoft Defender Vulnerability Management dashboard].
. link:#2-view-and-respond-to-detected-threats[View and respond to
detected threats].
. link:#3-review-security-policies[Review security policies].
. link:#4-prepare-for-ongoing-security-management[Prepare for ongoing
security management].
. link:#5-try-the-document-drops-backdoor-tutorial[Try the Document
Drops Backdoor tutorial].

==== 1. Use the Defender Vulnerability Management dashboard

Defender for Business includes a Defender Vulnerability Management
dashboard that’s designed to save your security team time and effort.
Learn how to link:mdb-view-tvm-dashboard.md[use your Defender
Vulnerability Management dashboard].

* View your exposure score, which is associated with devices in your
organization.
* View your top security recommendations, such as address impaired
communications with devices, turn on firewall protection, or update
Microsoft Defender Antivirus definitions.
* View remediation activities, such as any files that were sent to
quarantine, or vulnerabilities found on devices.

==== 2. View and respond to detected threats

As threats are detected and alerts are triggered, incidents are created.
Your organization’s security team can view and manage incidents in the
Microsoft 365 Defender portal. Learn how to
link:mdb-view-manage-incidents.md[view and respond to detected threats].

* link:mdb-view-manage-incidents.md[View and manage incidents].
* link:mdb-respond-mitigate-threats.md[Respond to and mitigate threats].
* link:mdb-review-remediation-actions.md[Review mediation actions in the
Action Center].
* link:mdb-reports.md[View and use reports].

==== 3. Review security policies

In Defender for Business, security settings are configured through
policies that are applied to devices. Defender for Business includes
pre-configured policies to help protect your company’s devices as soon
as they are onboarded, safeguarding your organization against identity,
device, application, and document security threats.

Learn how to link:mdb-view-edit-create-policies.md[review security
policies].

==== 4. Prepare for ongoing security management

New security events, such as threat detection on a device, adding new
devices, and employees joining or leaving the organization, will require
you to manage security. In Defender for Business, there are many ways
for you to manage device security.

* link:mdb-manage-devices.md#view-the-list-of-onboarded-devices[View a
list of onboarded devices] to see their risk level, exposure level, and
health state.
* link:mdb-manage-devices.md#take-action-on-a-device-that-has-threat-detections[Take
action on a device] that has threat detections.
* link:mdb-manage-devices.md#onboard-a-device[Onboard a device to
Defender for Business].
* link:mdb-manage-devices.md#offboard-a-device[Offboard a device from
Defender for Business].

==== 5. Try the Document Drops Backdoor tutorial

Quickly see how Defender for Business works by trying a tutorial.

Simulate an attack that introduces file-based malware on a test device.
The tutorial describes how to use the simulation file and what to watch
for in the Microsoft 365 Defender portal.

____
[!NOTE] This tutorial requires Microsoft Word to be installed on your
test device.
____

To access the tutorial, do the following:

[arabic]
. Go to the https://security.microsoft.com[Microsoft 365 Defender
portal] and sign in.
. In the navigation pane, under *Endpoints*, choose *Tutorials*.
. Choose *Document Drops Backdoor*.

=== Additional resources

* link:mdb-overview.md[Overview of Defender for Business]
* link:mdb-tutorials.md[Tutorials and simulations in Defender for
Business]
* https://youtu.be/umhUNzMqZto[Video: Enterprise-Grade Protection for
Small & Medium Sized Businesses]
* link:get-defender-business.md[Get Defender for Business]
