= Enable Modern authentication for Office 2013 on Windows devices
:audience: Admin
:author: skjerland
:description: Learn to set registry keys to enable modern authentication for devices that have Microsoft Office 2013 installed.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.assetid: 7dc1c01a-090f-4971-9677-f1b192d6c910
:ms.author: sharik
:ms.collection: ["M365-subscription-management", "Adm_O365", "Adm_TOC"]
:ms.custom: ["AdminSurgePortfolio", "okr_smb", "AdminTemplateSet"]
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["BCS160", "MET150", "MOE150"]

== Enable Modern authentication for Office 2013 on Windows devices

Microsoft Office 2013 on Microsoft Windows computers supports Modern authentication.
But, to turn it on, you need to configure the following registry keys:

[cols="<,^,^"]
|===
| Registry key | Type | Value

| HKEY_CURRENT_USER\Software\Microsoft\Exchange\AlwaysUseMSOAuthForAutoDiscover
| REG_DWORD
| 1

| HKEY_CURRENT_USER\Software\Microsoft\Office\15.0\Common\Identity\EnableADAL
| REG_DWORD
| 1

| HKEY_CURRENT_USER\Software\Microsoft\Office\15.0\Common\Identity\Version
| REG_DWORD
| 1
|===

____
[!NOTE] Modern authentication is already enabled in Office 2016 or later.
You don't need to set these registry keys for later versions of Office.
____

=== Enable modern authentication for Office 2013 clients

. Close Outlook.
. Copy and paste the following text into Notepad:
+
[,text]
----
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Exchange]
"AlwaysUseMSOAuthForAutoDiscover"=dword:00000001

[HKEY_CURRENT_USER\Software\Microsoft\Office\15.0\Common]

[HKEY_CURRENT_USER\Software\Microsoft\Office\15.0\Common\Identity]
"EnableADAL"=dword:00000001
"Version"=dword:00000001
----

. Save the file with the file extension .reg instead of .txt in a location that's easy for you to find.
For example, `C:\Data\Office2013_Enable_ModernAuth.reg`.
. Open File Explorer (formerly known as Windows Explorer), browse to the location of the .reg file you just saved, and then double-click it.
. In the *User account control* dialog that appears, click *Yes* to allow the app to make changes to your device.
. In the *Registry Editor* warning dialog that appears, click *Yes* to accept the changes.

Once you've set the registry keys, you can set Office 2013 apps to use multifactor authentication (MFA) with Microsoft 365.
For more information, see xref:set-up-multi-factor-authentication.adoc[Set up multifactor authentication].

If you're currently signed in to any of Office client apps, you need to sign out and sign back in for the change to take effect.
Otherwise, the MRU and roaming settings will be unavailable until the identity is established.

=== Disable modern authentication on devices

The procedure to disable modern authentication on a device is very similar, but fewer registry keys are required, and you need to set their values to 0.

[cols=",^,^"]
|===
| Registry key | Type | Value

| HKEY_CURRENT_USER\Software\Microsoft\Exchange\AlwaysUseMSOAuthForAutoDiscover
| REG_DWORD
| 0

| HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\15.0\Common\Identity\EnableADAL
| REG_DWORD
| 0
|===

[,text]
----
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Exchange]
"AlwaysUseMSOAuthForAutoDiscover"=dword:00000000

[HKEY_CURRENT_USER\Software\Microsoft\Office\15.0\Common]

[HKEY_CURRENT_USER\Software\Microsoft\Office\15.0\Common\Identity]
"EnableADAL"=dword:00000000
----

=== Related content

https://support.microsoft.com/office/2b856342-170a-438e-9a4f-3c092394d3cb[Sign in to Office 2013 with a second verification method]

link:/outlook/troubleshoot/authentication/outlook-prompt-password-modern-authentication-enabled[Outlook prompts for password and doesn't use Modern Authentication to connect to Office 365]
