= 
cmcatee-MSFT

== Manage licenses for devices

If you have Microsoft 365 Apps for enterprise (device) or Microsoft 365
Apps for Education (device), you can assign licenses to devices by using
Azure AD groups. When a device has a license, anyone who uses that
device can use Microsoft 365 Apps for enterprise (previously named
Office 365 ProPlus). For example, let’s say you have 20 laptops and
tablets that are used by people in your organization. When you assign a
license to each device, each person who logs in to one of the devices
uses Microsoft 365 Apps for enterprise without the need for their own
license.

____
[!IMPORTANT] Device-based licensing for Microsoft 365 Apps for
enterprise is available only as an add-on license for some commercial
customers and some education customers. For commercial customers, the
license is _Microsoft 365 Apps for enterprise (device)_ and is available
only through Enterprise Agreement/Enterprise Agreement Subscription. For
education customers, the license is _Microsoft 365 Apps for Education
(device)_ and is available only through Enrollment for Education
Solutions (EES). For more information, read the blog post on
https://educationblog.microsoft.com/2019/08/attention-it-administrators-announcing-office-365-proplus-device-based-subscription-for-education[education
availability]. For commercial availability, contact your Microsoft
account representative.
____

To begin, you create a group in the Azure Active Directory admin center,
and then assign devices to the group. To learn more about device
licensing, including device requirements, what types of groups you can
use, and how to configure Microsoft 365 Apps for enterprise to use
device licensing, see
link:/deployoffice/device-based-licensing[Device-based licensing for
Microsoft 365 Apps for enterprise].

____
[!IMPORTANT] You must be a Global admin to complete the tasks in this
article.
____

=== Assign licenses to devices

When you assign licenses to a group, you assign licenses to all devices
within the group. You can only assign one subscription to any single
group.

[arabic]
. In the Microsoft 365 admin center, go to the *Billing* > Licenses
page.
. On the *Licenses* page, choose *Microsoft 365 Apps for Education
(device)* or *Microsoft 365 Apps for enterprise (device)*.
. On the next page, choose a subscription, then choose *Assign
licenses*.
. In the *Assign licenses to a group* pane, begin typing a group name,
and then choose it from the results to add it to the list.
. Choose *Assign*, then choose *Close*.

=== Unassign licenses from devices

When you unassign licenses from a group, you remove the licenses from
all devices within the group. All apps and their associated data are
then read-only.

[arabic]
. In the admin center, go to the *Billing* > Licenses page.
. On the *Licenses* page, choose *Microsoft 365 Apps for Education
(device)* or *Microsoft 365 Apps for enterprise (device)*.
. On the next page, choose a subscription, select the three dots (more
actions), and then choose *Unassign licenses*.
. In the *Unassign licenses* dialog box, choose *Unassign*.
