= 
cmcatee-MSFT

== Manage ISV app licenses in the Microsoft 365 admin center

An independent software vendor (ISV) app is an app that you buy from a
software vendor other than Microsoft.

=== Before you begin

You must be a Global, License, or User admin to assign licenses. For
more information, see
link:../../admin/add-users/about-admin-roles.md[About admin roles].

=== Assign ISV app licenses to users or groups

[arabic]
. In the Microsoft 365 admin center, go to the *Billing* > Licenses
page.
. Select the app that you want to assign licenses for.
. On the license details page, select *Assign licenses*.
. In the *Assign licenses* pane, begin typing the name of a user or
group, and then choose it from the results to add it to the list.
. When you’re finished, select *Assign*, then select *Close*.

=== Unassign ISV app licenses from users or groups

[arabic]
. In the admin center, *Billing* > Licenses page.
. Select the app that you want to unassign licenses for.
. On the license details page, select the users and groups to remove
licenses from, then select Unassign licenses.
. In the dialog box, confirm that you want to remove the licenses, then
select Unassign.

=== Add or remove ISV app licenses for your account

If you bought your app through Microsoft at
https://appsource.microsoft.com, you can link:buy-licenses.md[add or
remove licenses] in the Microsoft 365 admin center.

If you bought an ISV app through an app vendor, contact the vendor to
add or remove licenses from your account.

=== Next steps

Depending on the ISV app that you bought, your next step might be to
install the app into your organization’s environment. Installing the app
makes it available for your users. Use the following steps to install an
ISV app to your environment.

[arabic]
. In the admin center, *Billing* > Licenses page.
. Select the app that you want to install into your account.
. On the license details page, select *Install this product*. You are
redirected to a different platform site where you install the app into
your environment.

=== Related content

link:../../admin/manage/assign-licenses-to-users.md[Assign licenses to
users] (article) +
link:../../admin/manage/remove-licenses-from-users.md[Unassign licenses
from users] (article)
