= Manage ISV app licenses
:audience: Admin
:author: cmcatee-MSFT
:description: Learn how to manage licenses for independent software vendor (ISV) apps in the Microsoft 365 admin center.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.author: cmcatee
:ms.collection: ["M365-subscription-management", "Adm_O365"]
:ms.custom: ["commerce_licensing", "AdminSurgePortfolio"]
:ms.date: 06/08/2022
:ms.localizationpriority: medium
:ms.reviewer: argani, nicholak
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["MET150"]

== Manage ISV app licenses in the Microsoft 365 admin center

An independent software vendor (ISV) app is an app that you buy from a software vendor other than Microsoft.

=== Before you begin

You must be a Global, License, or User admin to assign licenses.
For more information, see xref:../../admin/add-users/about-admin-roles.adoc[About admin roles].

=== Assign ISV app licenses to users or groups

. In the Microsoft 365 admin center, go to the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=842264[Licenses] page.
. Select the app that you want to assign licenses for.
. On the license details page, select *Assign licenses*.
. In the *Assign licenses* pane, begin typing the name of a user or group, and then choose it from the results to add it to the list.
. When you're finished, select *Assign*, then select *Close*.

=== Unassign ISV app licenses from users or groups

. In the admin center, *Billing* > https://go.microsoft.com/fwlink/p/?linkid=842264[Licenses] page.
. Select the app that you want to unassign licenses for.
. On the license details page, select the users and groups to remove licenses from, then select Unassign licenses.
. In the dialog box, confirm that you want to remove the licenses, then select Unassign.

=== Add or remove ISV app licenses for your account

If you bought your app through Microsoft at https://appsource.microsoft.com, you can xref:buy-licenses.adoc[add or remove licenses] in the Microsoft 365 admin center.

If you bought an ISV app through an app vendor, contact the vendor to add or remove licenses from your account.

=== Next steps

Depending on the ISV app that you bought, your next step might be to install the app into your organization's environment.
Installing the app makes it available for your users.
Use the following steps to install an ISV app to your environment.

. In the admin center, *Billing* > https://go.microsoft.com/fwlink/p/?linkid=842264[Licenses] page.
. Select the app that you want to install into your account.
. On the license details page, select *Install this product*.
You are redirected to a different platform site where you install the app into your environment.

=== Related content

xref:../../admin/manage/assign-licenses-to-users.adoc[Assign licenses to users] (article) + xref:../../admin/manage/remove-licenses-from-users.adoc[Unassign licenses from users] (article)
