= 
MSFTTracyP

== How to run attack simulations for your team

Attack simulation training allows you to run realistic but benign cyber
attack scenarios in your organization. Simulated attacks can help you
identify and find vulnerable users, policies and practices before a real
attack impacts your organization, leveraging inbuilt or custom training
to reduce risk and better educate end users about threats.

=== What you’ll need

* Microsoft Defender for Office 365 Plan 2 (included as part of E5)
* Sufficient permissions (Security Administrator role)
* 5-10 minutes to perform the steps below.

=== Send a payload to target users

[arabic]
. Navigate to https://security.microsoft.com/attacksimulator[Attack
Simulation Training] in your subscription.
. Choose *Simulations* from the top navigation bar.
. Select *Launch a simulation*.
. Pick the technique you’d like to use from the flyout, and press
*Next*.
. Name the Simulation with something relevant / memorable and press
*Next*.
. Pick a relevant payload from the wizard, review the details and
customize if appropriate, when you are happy with the choice, press
*Next*.
. Choose who to target with the payload. If choosing the entire
organization highlight the radio button and press *Next*.
. Otherwise, select *Add Users* and then search or filter the users with
the wizard. Select Add User(s) and then *Next*.
. Under *Select training content preference*, leave the default
_Microsoft training experience (Recommended)_ or select _Redirect to a
custom URL_ if you want to use the custom URL. If you don’t want to
assign any training, then select _No training_.
* You can either let Microsoft assign training courses by selecting
_Assign training for me_ or you can choose specific modules with _Select
training courses and modules myself_
* Select a Due Date (30, 15, or 7 days) from the drop-down menu.
* Click *Next* to continue.
. Customize the landing page displayed when a user is phished if
appropriate, or otherwise leave the Microsoft Default.
[arabic]
.. Under *Payload indicators*, check the box to add payload indicators
to email. Adding payloads will help users to learn how to identify the
phishing email. Select _Open preview panel_ to view the message.
.. Click *Next* to continue.
. Choose if you’d like end user notifications, and if so, select the
delivery preferences and customize where needed.
[arabic]
.. Notice that you can also select _default language_ for the
notification under the *Select default language* drop-down menu.
. Select when to launch the simulation, and how long it should be valid
for. You can also enable _region aware time zone delivery_. This option
will deliver simulated attack messages to your employees during _their
working hours_ based on their region. Select *Next*.
. Send a test if you’re ready. Review the summary of choices. Click
*Submit*.

==== Further reading

To learn how Attack Simulation works see
link:../../office-365-security/attack-simulation-training-simulations.md[Simulate
a phishing attack with Attack simulation training - Office 365 |
Microsoft Docs]
