= 
MSFTTracyP

== How to handle Legitimate emails getting blocked (False Positive), using Microsoft Defender for Office 365

Microsoft Defender for Office 365 helps deal with important legitimate
business emails that are mistakenly blocked as threats (False
Positives). Defender for Office 365 can help admins understand _why_
legitimate emails are being blocked, how to resolve the situation
quickly, and prevent similar situations from happening in the future.

=== What you’ll need

* Microsoft Defender for Office 365 Plan 1 or 2 (included as part of
E5). Exchange Online customers can also leverage this feature.
* Sufficient permissions (Security Administrator role).
* 5-10 minutes to perform the steps below.

=== Handling legitimate emails in to Junk folder of end users

[arabic]
. Ask end users to report the email as *not junk* using Microsoft
Message Add-in or the Outlook buttons.
. End users can also add the sender to the
https://support.microsoft.com/office/safe-senders-in-outlook-com-470d4ee6-e3b6-402b-8cd9-a6f00eda7339[*safe
sender list*] in Outlook to prevent the email from these senders landing
in Junk folder.
. Admins can triage the user-reported messages from
link:/microsoft-365/security/office-365-security/admin-submission#view-user-reported-messages-to-microsoft[the
User reported tab on the Submission page].
. From those reported messages admins can submit to
link:/microsoft-365/security/office-365-security/admin-submission#notify-users-from-within-the-portal[*Microsoft
for analysis*] and understand why was that email blocked in the first
place.
. If needed, while submitting to Microsoft for analysis, admins can
judiciously create an
link:/microsoft-365/security/office-365-security/tenant-allow-block-list-email-spoof-configure[*allow*
for a sender] to mitigate the problem.
. Once the results from the admin submission are available, read it to
understand why emails were blocked and how your tenant setup could be
improved to _prevent_ similar situations from happening in the future.

=== Handling legitimate emails that are in quarantine folder of end users

[arabic]
. An end user receives an
link:../quarantine-quarantine-notifications.md[email digest] about
quarantined messages as per the settings enabled by security admins.
. End users can preview the messages in quarantine, block the sender,
release the messages, submit those messages to Microsoft for analysis,
and request release of those emails from admins.

=== Handling legitimate emails in quarantine folder of an admin

[arabic]
. Admins can view the quarantined emails (including the ones asking
permission to request release) from the
link:/microsoft-365/security/office-365-security/quarantine-admin-manage-messages-files[review
page].
. Admins can release the message from quarantine while submitting it to
Microsoft for analysis, and create an allow to mitigate the situation.
. Once the results for submissions are available, admins should read the
verdict to understand why emails were blocked, and how the tenant setup
could be improved to prevent similar situations from happening in the
future.
