= 
MSFTTracyP

== Steps to use manual email remediation in Threat Explorer

Email remediation is an already existing feature that helps admins act
on emails that are threats.

=== What you’ll need

* Microsoft Defender for Office 365 Plan 2 (Included in E5 plans)
* Sufficient permissions (be sure to grant the account
https://sip.security.microsoft.com/securitypermissions[Search and Purge]
role)

=== Create and track the remediation

[arabic]
. *Select a threat to remediate* in
https://security.microsoft.com/threatexplorer[Threat Explorer] and
select the *Message Actions* button, which will offer you options such
as _Soft Delete_ or _Hard Delete_.
. The side pane will open and ask for details like a name for the
remediation, severity, and description. Once the information is
reviewed, press *Submit*.
. As soon as the admin approves this action, they will see the Approval
ID and a link to the Microsoft 365 Defender Action Center
https://security.microsoft.com/action-center/history[here]. This page is
where *actions can be tracked*.
[arabic]
.. *Admin action alert* - A system alert shows up in the alert queue
with the name `Administrative action submitted by an Administrator'.
This indicates that an admin took the action of remediating an entity.
It gives details such as the name of the admin who took the action, and
the investigation link and time. This makes admins aware of each
important action, like remediation, taken on entities.
.. *Admin action investigation* - Since the analysis on entities was
already done by the admin and that’s what led to the action taken, no
additional analysis is done by the system. It shows details such as
related alert, entity selected for remediation, action taken,
remediation status, entity count, and approver of the action. This
allows admins to keep track of the investigation and actions carried out
_manually_–an admin action investigation.
. *Action logs in unified action center* - History and action logs for
email actions like soft delete and move to deleted items folder, are
_all available in a centralized view_ under the unified *Action Center*
> *History tab*.
. *Filters in unified action center* - There are multiple filters such
as remediation name, approval ID, Investigation ID, status, action
source, and action type. These are useful for finding and tracking email
actions in unified Action center.

____
[!IMPORTANT] Performance For better performance, remediation should be
done in batches of _50,000 or fewer_. Narrow down the search result by
using _latest delivery location_ and trigger email remediation if the
email is in remediable folder like Inbox, Junk, Deleted, for example.
____

=== Scenarios that call for email remediation

Here are scenarios of email remediation:

[arabic]
. As part of an investigation SecOps identifies a threat in an
end-user’s mailbox and wants to clear out the problem email(s).
. When suggested email actions in Automated Investigation and Response
(AIR) are approved by SecOps, remediation action triggers automatically
for the given email or email cluster.

Two manual email remediation scenarios:

[arabic]
. The main scenario:
[arabic]
.. Manual actions taken on emails (for example, using Threat Explorer or
Advanced Hunting) are only visible in the legacy Defender for Office 365
Action Center (Email and Collaboration > Review > Action Center in
Action center - Microsoft 365 security). +
. Two-step approval scenario:
[arabic]
.. Manual actions pending approval using the two-step approval process
(1. The email was added to remediation by one analyst, 2. The email was
reviewed and approved by another analyst).

Given the common scenarios, email remediation can be triggered in three
different ways.

[arabic]
. *Query based remediation*: By selecting all the search results with a
query (200,000 emails can be submitted at a maximum).
. *Handpicked remediation*: Selecting emails one-by-one by clicking on
the check box (100 emails can be submitted at one time).
. *Query based remediation with exclusions*: Selecting all emails, and
then manually removing a few messages (the query can hold a maximum of
1,000 emails and the maximum number of exclusions is 100).

=== Next Steps

[arabic]
. Go to the https://security.microsoft.com[Microsoft 365 Defender
portal] and sign in.
. In the navigation pane, select *Action center*.
. Go to the *History* tab, click on any waiting approval list. It opens
up a side pane. +
. Track the action status in the unified action center.

=== More information

link:../../office-365-security/air-review-approve-pending-completed-actions.md[Learn
more about email remediation]
