= 
MSFTBen

== Use Microsoft Defender for Office 365 with SharePoint Online

Microsoft SharePoint Online is a widely used user collaboration and file
storage tool. The following steps help reduce the attack surface area in
SharePoint Online and that help keep this collaboration tool in your
organization secure. However, it’s important to note there is a balance
to strike between security and productivity, and not all these steps may
be relevant for your organizational risk profile. Take a look, test, and
maintain that balance.

=== What you’ll need

* Microsoft Defender for Office 365 Plan 1
* Sufficient permissions (SharePoint administrator/security
administrator).
* Microsoft SharePoint Online (part of Microsoft 365).
* Five to ten minutes to perform these steps.

=== Turn on Microsoft Defender for Office 365 in SharePoint Online

If licensed for Microsoft Defender for Office 365 *(free 90-day
evaluation available at aka.ms/trymdo)* you can ensure seamless
protection from zero day malware and time of click protection within
Microsoft Teams.

To learn more, read
link:/microsoft-365/security/office-365-security/safe-attachments-for-spo-odfb-teams-configure#step-1-use-the-microsoft-365-defender-portal-to-turn-on-safe-attachments-for-sharepoint-onedrive-and-microsoft-teams[Step
1: Use the Microsoft 365 Defender portal to turn on Safe Attachments for
SharePoint&#44; OneDrive&#44; and Microsoft Teams].

[arabic]
. Sign in to the
https://security.microsoft.com/safeattachmentv2[security center’s safe
attachments configuration page].
. Select *Global settings*.
. Ensure that *Turn on Defender for Office 365 for SharePoint, OneDrive,
and Microsoft Teams* is set to *on*.
. Select *Save*.

=== Stop infected file downloads from SharePoint Online

By default, users can’t open, move, copy, or share malicious files that
are detected by Safe Attachments for SharePoint, OneDrive, and Microsoft
Teams. However, the _Download_ option is still available and should be
_disabled_.

To learn more, read
link:/microsoft-365/security/office-365-security/safe-attachments-for-spo-odfb-teams-configure#step-2-recommended-use-sharepoint-online-powershell-to-prevent-users-from-downloading-malicious-files[Step
2: (_Recommended_) Use SharePoint Online PowerShell to prevent users
from downloading malicious files].

[arabic]
. Open and connect to
link:/powershell/sharepoint/sharepoint-online/connect-sharepoint-online[SharePoint
Online PowerShell].
. Run the following command: *Set-SPOTenant
-DisallowInfectedFileDownload $true*.

==== Further reading

link:/microsoft-365/security/office-365-security/sharepoint-file-access-policies[Policy
recommendations for securing SharePoint sites and files]
