= Enable shared channels with all external organizations
:audience: ITPro
:author: MikePlumleyMSFT
:description: Learn how to enable shared channels with all other Microsoft 365 and Azure Active Directory organizations.
:f1.keywords: NOCSH
:manager: serdars
:ms.author: mikeplum
:ms.collection: ["highpri", "SPO_Content", "M365-collaboration", "m365solution-securecollab", "m365solution-scenario", "m365initiative-externalcollab"]
:ms.localizationpriority: medium
:ms.service: o365-solutions
:ms.topic: article
:recommendations: false

== Enable shared channels with all external organizations

While sharing shared channels externally is enabled by default in Teams, Azure Active Directory cross-tenant access settings for link:/azure/active-directory/external-identities/b2b-direct-connect-overview[B2B direct connect] must also be configured to share a channel externally.
By default, these settings are set to block all organizations.

You can change the B2B direct connect default settings to allow all organizations.
This allows users to collaborate in shared channels without your organization having to create a separate configuration for each organization that you want to collaborate with.
(Note that the organizations you collaborate with will also have to configure their B2B direct connect settings.)

If your organization doesn't have a requirement to restrict collaboration with other organizations, enabling all organizations by default can save you time and complexity in managing each organization separately.

____
[!NOTE] Changes to cross-tenant access settings may take two hours to take effect.
____

____
[!NOTE] link:/microsoft-365/admin/create-groups/manage-guest-access-in-groups[Guest settings for Microsoft 365 Groups] must be enabled to use shared channels with external participants.
____

=== Allow users to invite people in other organizations to participate in shared channels

You can allow your users to invite people from other organizations to use shared resources - such as shared channels in Teams - by default.

To allow users to invite B2B direct connect participants by default

. Sign in to https://aad.portal.azure.com[Azure Active Directory] using a Global administrator or Security administrator account.
. Select *External Identities*, and then select *Cross-tenant access settings (preview)*.
. On the *Default settings* tab, under *Inbound access settings*, select *Edit inbound defaults*.
. Select the *B2B direct connect* tab.
. On the *Users and groups* tab, under *Access status*, choose *Allow access*.
. On the *External applications* tab, under *Access status*, choose *Allow access*.
. Select *Save*.
. Select the *Trust settings* tab.
. Choose if you want to trust multi-factor authentication, compliant devices, or hybrid Azure AD joined devices from other organizations.
. Select *Save*.
. Close the *Default settings* blade.

=== Allow users to participate in shared channels in other organizations

You can allow your users to access resources that are hosted by an external organization - such as shared channels in Teams - by default.

To allow users to access resource from other organizations by default

. In https://aad.portal.azure.com[Azure Active Directory], select *External Identities*, and then select *Cross-tenant access settings (preview)*.
. On the *Default settings* tab, under *Outbound access settings*, select *Edit outbound defaults*.
. Select the *B2B direct connect* tab.
. On the *Users and groups* tab, under *Access status*, choose *Allow access*.
. On the *External applications* tab, under *Access status*, choose *Allow access*.
. Select *Save*.
. Close the *Default settings* blade.

=== Related topics

link:/azure/active-directory/external-identities/b2b-direct-connect-overview[B2B direct connect overview]

link:/azure/active-directory/external-identities/cross-tenant-access-settings-b2b-direct-connect[Configure cross-tenant access settings for B2B direct connect]
