= Collaborating with people outside your organization
:audience: ITPro
:author: MikePlumleyMSFT
:description: Learn how to configure Microsoft 365 apps like Teams, OneDrive, and SharePoint for collaboration with people outside your organization.
:f1.keywords: NOCSH
:manager: serdars
:ms.author: mikeplum
:ms.collection: ["highpri", "SPO_Content", "M365-collaboration", "m365solution-securecollab", "m365solution-scenario", "m365initiative-externalcollab"]
:ms.custom: ["seo-marvel-apr2020", "seo-marvel-jun2020"]
:ms.localizationpriority: medium
:ms.service: o365-solutions
:ms.topic: article
:recommendations: false

== Collaborating with people outside your organization

The external sharing capabilities in Microsoft 365 provide an opportunity for people in your organization to collaborate with partners, vendors, customers, and others who don't have an account in your directory.
You can share entire teams, channels, or sites with people outside your organization, or just individual files.

Collaborating with people outside your organization consists of these major components:

* *Enable sharing* - Configure the sharing controls across Azure Active Directory, Teams, Microsoft 365 Groups, and SharePoint to allow the level of sharing that you want for your organization.
* *Configure organizational relationships* - If you are using shared channels, you must configure cross-tenant access settings in Azure Active Directory to allow B2B direct connect access for each organization you want to collaborate with.
(These organizations must also configure organizational relationships with your tenant.)
* *Enable additional security* - While the basic sharing features can be configured to require people outside your organization to authenticate, Microsoft 365 provides many additional security and compliance features to help you protect your data and maintain your governance policies while sharing externally.

Read link:/microsoft-365/solutions/setup-secure-collaboration-with-teams[Set up secure collaboration with Microsoft 365 and Microsoft Teams] to learn how external sharing ties in with the overall Microsoft 365 collaboration guidance.

=== Enable sharing

By default, sharing with people outside your organization using guest access or anonymous access is enabled, but shared channels must be enabled by configuring organizational relationships in Azure AD.
Most guest sharing scenarios work without further configuration.
To confirm the settings for a scenario that you're using, or enable a new one, choose from the following options:

* xref:collaborate-on-documents.adoc[Collaborate on documents] - Learn how to configure Microsoft 365 to allow sharing and collaboration with people outside your organization (both guests and unauthenticated users) on files and folders.
* xref:collaborate-in-site.adoc[Collaborate in a site] - Learn how to configure Microsoft 365 to enable sharing SharePoint sites with guests.
* xref:collaborate-as-team.adoc[Collaborate as a team] - Learn how to configure Microsoft 365 to enable guest collaboration in Teams.
* link:/microsoft-365/solutions/collaborate-teams-direct-connect[Collaborate with external participants in a channel] for collaborating with people outside the organization in a shared channel.

For a comprehensive look at the guest sharing settings available across Microsoft 365, see xref:microsoft-365-guest-settings.adoc[Microsoft 365 guest sharing settings reference].

=== Enable additional security

Once you've enabled the scenario that you want to use for sharing with people outside your organization, consider additional safeguards to help protect your content from accidental or intentional inappropriate sharing.

* xref:best-practices-anonymous-sharing.adoc[Best practices for sharing files and folders with unauthenticated users] - Learn about best practices for sharing with unauthenticated users.
* xref:share-limit-accidental-exposure.adoc[Limit accidental exposure] - Learn how to reduce the chances of accidentally sharing sensitive content with people outside your organization.
* xref:create-secure-guest-sharing-environment.adoc[Create a secure guest sharing environment] - Learn about the tools provided in Microsoft 365 to help ensure that sharing with people outside your organization is done in a safe and secure manner and meets your governance requirements.

=== Collaborate with partner companies

When you're working on a large project that involves guests from another organization, consider shared channels.
Because shared channels do not use guest accounts, the users in the other organization can access the shared channel directly without having to log into your organization separately.

If you have an ongoing vendor relationship in which guests are often changing, you can use entitlement management in Azure Active Directory to simplify guest management and allow the partner company to share in that responsibility.
See xref:b2b-extranet.adoc[Create a B2B extranet with managed guests] for details.

=== Limit sharing

If some of the sharing features in Microsoft 365 conflict with your governance policies, see xref:microsoft-365-limit-sharing.adoc[Limit sharing in Microsoft 365] to learn about options for limiting sharing.

=== Related topics

link:/sharepoint/intro-to-file-collaboration[Intro to file collaboration in Microsoft 365]

link:/sharepoint/deploy-file-collaboration[Plan file collaboration in SharePoint with Microsoft 365]
