= Governing access in Microsoft 365 groups, Teams, and SharePoint
:audience: Admin
:author: MikePlumleyMSFT
:description: Learn about governing access in Microsoft 365 groups, Teams, and SharePoint.
:f1.keywords: NOCSH
:manager: serdars
:ms.author: mikeplum
:ms.collection: ["highpri", "M365-collaboration", "m365solution-collabgovernance"]
:ms.custom: ["M365solutions"]
:ms.localizationpriority: medium
:ms.reviewer:
:ms.service: o365-solutions
:ms.topic: article
:recommendations: false

== Governing access in Microsoft 365 groups, Teams, and SharePoint

There are many controls that enable you to govern how people access resources in groups, teams, and SharePoint.
Review these options and consider how they map to your business needs, the sensitivity of your data, and the scope of people that your users need to collaborate with.

The following table provides a quick reference for the access controls available in Microsoft 365.
Further information is provided in the following sections.

|===
| Category | Description | Reference

| Membership
|
|

|
| Discovery of private teams
| link:/microsoftteams/manage-discovery-of-private-teams[Manage discovery of private teams in Microsoft Teams]

|
| Dynamic group membership based on rules
| link:/azure/active-directory/users-groups-roles/groups-create-rule[Create or update a dynamic group in Azure Active Directory]

|
| Control who can share files, folders, and sites.
| https://support.microsoft.com/office/94b26e0b-2822-49d4-929a-8455698654b3[Set up and manage access requests]

| Conditional access
|
|

|
| Multi-factor Authentication
| link:/azure/active-directory/authentication/concept-mfa-howitworks[Azure AD multi-factor Authentication]

|
| Control device access based on group, team, or site sensitivity.
| xref:../compliance/sensitivity-labels-teams-groups-sites.adoc[Use sensitivity labels to protect content in Microsoft Teams, Microsoft 365 groups, and SharePoint sites]

|
| Limit site access for unmanaged devices.
| link:/sharepoint/control-access-from-unmanaged-devices[Control SharePoint access from unmanaged devices]

|
| Control site access based on location
| link:/sharepoint/control-access-based-on-network-location[Control access to SharePoint and OneDrive data based on network location]

| Guest access
|
|

|
| Allow or block SharePoint sharing from specified domains.
| link:/sharepoint/restricted-domains-sharing[Restrict sharing of SharePoint and OneDrive content by domain]

|
| Allow or block team or group membership from specified domains.
| link:/azure/active-directory/b2b/allow-deny-list[Allow or block invitations to B2B users from specific organizations]

|
| Prevent anonymous sharing.
| link:./share-limit-accidental-exposure.md#turn-off-anyone-links[Turn off Anyone links]

|
| Control the permissions for anonymous access links.
| link:./best-practices-anonymous-sharing.md#set-link-permissions[Set link permissions for Anyone links]

|
| Control the expiration of anonymous sharing links.
| link:./best-practices-anonymous-sharing.md#set-an-expiration-date-for-anyone-links[Set an expiration date for Anyone links]

|
| Control the type of sharing link shown to users by default.
| link:/sharepoint/change-default-sharing-link[Change the default link type for a site]

|
| Limit external sharing to specific people.
| link:./share-limit-accidental-exposure.md#limit-sharing-of-files-folders-and-sites-with-people-outside-your-organization-to-specified-security-groups[Limit external sharing to specified security groups]

|
| Control guest access to a group, team, or site based on information sensitivity.
| xref:../compliance/sensitivity-labels-teams-groups-sites.adoc[Use sensitivity labels to protect content in Microsoft Teams, Microsoft 365 groups, and SharePoint sites]

|
| Turn off sharing options.
| xref:./microsoft-365-limit-sharing.adoc[Limit sharing in Microsoft 365]

| User management
|
|

|
| Review team and group membership on a regular basis.
| link:/azure/active-directory/governance/access-reviews-overview[What are Azure AD access reviews?]

|
| Automate access management to groups and teams.
| link:/azure/active-directory/governance/entitlement-management-overview[What is Azure AD entitlement management?]
|===

=== Membership

Membership of teams and groups is controlled by owners.
Members can invite others, but the invitations are sent to owners for approval.
While public teams and groups are discoverable by anyone in the organization, you can control whether private teams and groups are discoverable:

* link:/microsoftteams/manage-discovery-of-private-teams[Manage discovery of private teams in Microsoft Teams]

You can manage membership of a group or team dynamically based on some criteria, such as department.
In this case, members and owners cannot invite people to the team.
Dynamic groups uses metadata that you define in Azure Active Directory to control who is a member of the group.
Be sure the metadata that you're using is complete and up to date as incorrect metadata can lead to users being left out of groups or incorrect users being added.

* link:/azure/active-directory/users-groups-roles/groups-create-rule[Create or update a dynamic group in Azure Active Directory]

SharePoint sites provide the ability to add owners, members, and visitors apart from group or team membership.
Depending on your requirements, you may want to restrict who can invite people to the site.
Also, depending on the sensitivity of the information in a given site, you may want to restrict who can share files and folder.
These restrictions are configured by the team, group, or site owner:

* https://support.microsoft.com/office/94b26e0b-2822-49d4-929a-8455698654b3[Set up and manage access requests]

=== Conditional access

With Microsoft 365, you can require multi-factor authentication for both people inside and outside your organization.
There are many options for the circumstances when people are prompted for a second factor of authentication.
We highly recommend that you deploy multi-factor authentication for your organization:

* link:/azure/active-directory/authentication/concept-mfa-howitworks[Azure AD multi-factor authentication]

If you have sensitive information in some of your groups and teams, you can enforce device management policies based on a group or team's sensitivity label.
You can block access entirely from unmanaged devices, or allow limited, web only access:

* xref:../compliance/sensitivity-labels-teams-groups-sites.adoc[Use sensitivity labels to protect content in Microsoft Teams, Microsoft 365 groups, and SharePoint sites]

In SharePoint, you can restrict access to sites from specified network locations.

* link:/sharepoint/control-access-based-on-network-location[Control access to SharePoint and OneDrive data based on network location]

Additional resources:

* link:/azure/active-directory/conditional-access/plan-conditional-access[Plan a Conditional Access deployment]
* link:/mem/intune/fundamentals/what-is-intune[Microsoft Intune overview]
* link:/sharepoint/control-access-from-unmanaged-devices[Control SharePoint access from unmanaged devices]

=== Guest access

You can restrict guests based on the domain of their email address.
SharePoint offers organization-wide and site-specific domain restriction settings.
Groups and Teams use the domain allowlists or blocklists in Azure AD.
Be sure to configure both settings to avoid unwanted sharing and ensure a consistent user experience:

* link:/sharepoint/restricted-domains-sharing[Restrict sharing of SharePoint and OneDrive content by domain]
* link:/azure/active-directory/b2b/allow-deny-list[Allow or block invitations to B2B users from specific organizations]

Microsoft 365 allows anonymous sharing of files and folders by using _Anyone_ sharing links.
_Anyone_ links can be forwarded and anyone with the link can access the shared item.
Depending on the sensitivity of your data, consider governing how _Anyone_ links are used - including turning them off entirely, restricting link permissions to read-only, or setting an expiration time for them:

* link:./share-limit-accidental-exposure.md#turn-off-anyone-links[Turn off Anyone links]
* link:./best-practices-anonymous-sharing.md#set-link-permissions[Set link permissions for Anyone links]
* link:./best-practices-anonymous-sharing.md#set-an-expiration-date-for-anyone-links[Set an expiration date for Anyone links]

When sharing files or folders, users have several link types to choose from.
To reduce the risk of accidental inappropriate sharing, you can change the default link type presented to users when they share.
For example, changing the default from _Anyone_ links - which allow anonymous access - to _People in your organization_ links can reduce the risk of unwanted external sharing of sensitive information:

* link:/sharepoint/change-default-sharing-link[Change the default link type for a site]

If your organization has sensitive data that you need to share with guests, but you're concerned about inappropriate sharing, you can limit external sharing of files and folders to the members of specified security groups.
In this way, you can restrict sharing externally to a specific group of people, or require your users to take training around appropriate external sharing before adding them to the security group:

* link:./share-limit-accidental-exposure.md#limit-sharing-of-files-folders-and-sites-with-people-outside-your-organization-to-specified-security-groups[Limit external sharing to specified security groups]

Groups and Teams have organization-level settings that allow or deny guest access.
While you can xref:per-group-guest-access.adoc[restrict guest access to specific teams or groups by using Microsoft PowerShell], we recommend doing this by means of a sensitivity label.
With sensitivity labels you can automatically allow or deny guest access based on the label applied:

* xref:../compliance/sensitivity-labels-teams-groups-sites.adoc[Use sensitivity labels to protect content in Microsoft Teams, Microsoft 365 groups, and SharePoint sites]

In an environment where you frequently invite guests to groups and teams, consider setting up regularly scheduled guest access reviews.
Owners can be prompted to review guests in their groups and teams and approve or deny access.

* link:/microsoft-365/solutions/create-secure-guest-sharing-environment#set-up-guest-access-reviews[Set up guest access reviews]

Microsoft 365 offers many different methods of sharing information.
If you have sensitive information and you want to restrict how it's shared, review the options for limiting sharing:

* xref:./microsoft-365-limit-sharing.adoc[Limit sharing in Microsoft 365]

Additional resources:

* xref:./setup-secure-collaboration-with-teams.adoc[Set up secure collaboration with Microsoft 365]
* xref:./best-practices-anonymous-sharing.adoc[Best practices for sharing files and folders with unauthenticated users]
* xref:./share-limit-accidental-exposure.adoc[Limit accidental exposure to files when sharing with people outside your organization]
* xref:./create-secure-guest-sharing-environment.adoc[Create a secure guest sharing environment]
* link:/azure/active-directory/b2b/delegate-invitations[Enable B2B external collaboration and manage who can invite guests]

=== User management

As groups and teams evolve in your organization, a good practice is to review team and group membership on a regular basis.
This may be particularly useful for teams and groups with a changing membership, those that contain sensitive information, or those that include guests.
Consider setting up access reviews for these teams and groups:

* link:/azure/active-directory/governance/access-reviews-overview[What are Azure AD access reviews?]

Many organizations have business partnerships with other organizations or key vendors with whom they collaborate in depth.
User management and access to resources can be challenging to manage in these scenarios.
Consider automating some of the user management tasks and even transitioning some of them to your partner organization:

* link:/azure/active-directory/governance/entitlement-management-overview[What is Azure AD entitlement management?]

Private channels in Teams allow for scoped conversations and file sharing between a subset of team members.
Depending on your specific business needs, you may want to allow or block this capability.

* link:/MicrosoftTeams/private-channels[Private channels in Microsoft Teams]

Shared channels allow you to invite people who are outside the team or outside the organization.
Depending on your specific business needs and external sharing policies, you may want to allow or block this capability.

* link:/MicrosoftTeams/shared-channels[Shared channels]

Additional resources:

* link:/azure/active-directory/governance[Azure Active Directory Identity Governance]

=== Related topics

link:collaboration-governance-overview.md#collaboration-governance-planning-recommendations[Collaboration governance planning recommendations]

xref:collaboration-governance-first.adoc[Create your collaboration governance plan]

link:/microsoftteams/security-compliance-overview[Security and compliance in Microsoft Teams]

link:/sharepoint/turn-external-sharing-on-or-off[Manage sharing settings in SharePoint]

link:/yammer/work-with-external-users/create-and-manage-an-external-network[Create and manage an external network in Yammer]

xref:./configure-teams-three-tiers-protection.adoc[Configure Teams with three tiers of protection]
