= Get access to Microsoft Bookings
:audience: Admin
:author: kwekuako
:description: Learn how to get access to the Bookings feature in Microsoft 365.
:manager: scotv
:ms.assetid: 5382dc07-aaa5-45c9-8767-502333b214ce
:ms.author: kwekua
:ms.localizationpriority: medium
:ms.service: bookings
:ms.topic: article

== Get access to Microsoft Bookings

This topic describes how to get access to Bookings for the first time.
It also tells you how to turn on or off Bookings in your organization.
It also explains how you can assign licenses to your users so they can access and use Bookings.

=== Access Bookings for the first time

If your IT administrator has granted you link:/microsoft-365/bookings/turn-bookings-on-or-off[access to Bookings], you can access the app via Office online.

The first time you use https://outlook.office.com/bookings/onboarding[Bookings] you'll create a calendar and set up your business.

. Select *Get started*, enter your business name and business type, and then select *Create calendar*.
. If this isn't your first time on this page, you can select another booking calendar or do a search for another booking calendar.
. Enter your business name and business type and select *Continue*.

You're now ready to set up Bookings for your organization.
You can get to the Bookings page with this https://outlook.office.com/bookings/onboarding[link], from the app launcher or from office.com.
Use the following topics to continue setting up your Bookings features.

* xref:enter-business-information.adoc[Enter your business information]
* xref:add-staff.adoc[Add staff to Bookings]
* xref:define-service-offerings.adoc[Define your service offerings]
* xref:schedule-closures-time-off-vacation.adoc[Schedule business closures, time off, and vacation time]
* xref:set-scheduling-policies.adoc[Set your scheduling policies]
* xref:employee-hours.adoc[Set employee working hours]
* xref:customize-booking-page.adoc[Customize and publish your booking page]
* xref:create-a-manual-booking.adoc[Create a manual booking]
