= 
kwekuako

== Manage group attendees in Bookings

Owners and staff members of a Bookings calendar can now manage and
update attendees for group services. For more information on service
offerings in Bookings, see link:define-service-offerings.md[Define your
service offerings in Bookings].

Make sure that you set the *Maximum number of attendees* to more than 1
on the Bookings service.

=== Update attendee list

____
[!NOTE] You must have Administrator or Team member permission before you
can update these settings.
____

[arabic]
. In Microsoft 365, select the app launcher, and then select *Bookings*.
. Choose your calendar, select the group meeting and choose *Edit*.

:::image type=``content'' source=``../media/group-booking-calendar.png''
alt-text=``Screenshot: Owner view of group booking calendar'':::

[arabic, start=3]
. To add attendees to the group booking, select *Add customer*.

:::image type=``content''
source=``../media/group-booking-add-customer.png''
alt-text=``Screenshot: Group booking service details page - add a
customer'':::

[arabic, start=4]
. To remove attendees, select the user you want to remove from the group
booking and select *Remove customer*. Once you remove the attendee,
they’ll get an email letting them know that they’ve been removed from
this booking.

=== Common issues

* Editing of a group booking service from the Teams app or from the
mobile app resets attendees to 1. Use the Bookings web app to edit the
group booking service.
* Group bookings doesn’t support resource bookings at this time.
