= Get Microsoft 365 for Campaigns
:audience: Admin
:author: denisebmsft
:description: Get Microsoft 365 for Campaigns so you can protect your campaign from cybersecurity threats to email, data, and communications.
:f1.keywords: ["NOCSH"]
:manager: dansimp
:ms.assetid: 5abfef7b-5957-484a-b06b-a7c55e013e44
:ms.author: deniseb
:ms.collection: ["Adm_O365", "M365-subscription-management", "M365-Campaigns", "m365solution-smb", "highpri"]
:ms.custom: ["Adm_O365", "Core_O365Admin_Migration", "MiniMaven", "MSB365"]
:ms.date: 09/15/2022
:ms.localizationpriority: high
:ms.service: microsoft-365-security
:ms.subservice: other
:ms.topic: how-to
:search.appverid: ["BCS160", "MET150"]

== How to get Microsoft 365 for Campaigns

Campaigns and political parties in the USA are eligible for special pricing for Microsoft 365 Business Premium.
Currently this special pricing is available to:

* National-level political parties in the United States, Canada, and New Zealand
* National or federal political campaigns in the United States and New Zealand
* State-level political parties in the United States
* U.S.
State-wide political campaigns (eg: campaigns seeking office for governor, state legislature, or attorney general)
+
____
[!IMPORTANT] Due to local regulations, we are unable to offer Microsoft 365 for Campaigns in the following states at this time: CO, DE, IL, OK, WI & WY.
We encourage campaigns in those states to explore additional offerings at https://www.office.com/business[Microsoft 365 for business].
____

If your campaign or political party qualifies, Microsoft 365 for Campaigns is the least expensive plan available through Microsoft.
See xref:m365-campaigns-sign-up.adoc[Sign up for Microsoft 365 for Campaigns].

____
[!TIP] If you're not eligible for special pricing, Microsoft 365 Business Premium is still the most cost-effective way obtain comprehensive security for a collaboration environment.
See xref:get-microsoft-365-business-premium.adoc[How to get Microsoft 365 Business Premium].
____

=== What does Microsoft 365 for Campaigns include?

Microsoft 365 for Campaigns includes simple controls that help you and your staff work together securely:

* *Protect user identity*: Make sure that users are who they say they are when they sign in to send email or to access files (multifactor authentication).
* *Protect sensitive information*: Protect sensitive information to monitor information that gets shared outside your organization (data loss prevention).
* *Protect mobile devices*: Protect data on mobile devices (mobile app protection policy).
* *Guard against malicious content*: Prevent access to malicious content by scanning email attachments (Defender for Office 365).
* *Protect passwords*: Set passwords to never expire which is more secure and helps prevent work stoppages (password policy).
* *AccountGuard Program Access*: Microsoft AccountGuard is a security service offered at no additional cost to customers in the political space.
The service is designed to inform and help these highly targeted customers protect themselves from cybersecurity threats across their organizational and personal Microsoft email accounts.
View more information at https://www.microsoftaccountguard.com/[Microsoft AccountGuard].

=== What does it cost, who needs it, and what is the commitment?

If your campaign qualifies for special pricing, Microsoft 365 for Campaigns costs $5 per user per month.

To protect your campaign, we recommend a license for the candidate, the campaign manager, all senior staff who are part of the campaign or party, and usually all full-time staff.
Certain volunteer employees might also need a license.
In general, assign a license to anyone in your campaign who needs protected email and devices.

There's no minimum time commitment when you sign up for Microsoft 365 for Campaigns.
You can pay monthly for the licenses you need and stop using the service anytime.

=== How do I qualify for special pricing?

. Go to https://aka.ms/m365forcampaigns/[aka.ms/m365forcampaigns] and provide a few details about your organization.
The details you provide help us to verify that you represent a national-level political campaign or party in the United States.
There's no commitment when you complete this form.
. After you've completed the form, it takes us a few days to review your information.
. After we've verified that you represent a national-level political campaign or party, you'll receive an email invitation from Microsoft.
Your invite includes a sign-up link specific to your organization.

=== Next steps

When you receive your invitation, xref:m365-campaigns-setup.adoc[Set up Microsoft 365 for Campaigns].
