= Microsoft 365 Business Premium overview
:author: denisebmsft
:description: Learn how to implement cybersecurity for small or medium sized businesses with Microsoft 365 Business Premium. The cybersecurity capabilities and features are optimized to prevent cyberattacks and security breaches, and help safeguard data, devices and information with high-grade cyber defenses.
:f1.keywords: ["NOCSH"]
:manager: dansimp
:ms.audience: Admin
:ms.author: deniseb
:ms.collection: ["M365-Campaigns", "m365solution-overview", "m365solution-smb", "highpri"]
:ms.custom: ["MiniMaven", "intro-overview"]
:ms.date: 09/15/2022
:ms.localizationpriority: high
:ms.service: microsoft-365-security
:ms.subservice: other
:ms.topic: overview
:search.appverid: ["BCS160", "MET150"]

== Microsoft 365 Business Premium -- productivity and cybersecurity for small business

Microsoft 365 Business Premium with its world class productivity tools is a wise choice for small and medium-sized businesses.
Designed with cybersecurity in mind, Microsoft 365 Business Premium safeguards your data, devices and information.
You are your organization's first and best defense against hackers and cyberattackers, including random individuals, organized crime, or highly sophisticated nation states.

The task before you is this: let Microsoft 365 Business Premium help secure your organization's future!
Approach this task by taking on the following six missions:

:::image type="content" source="media/sixmissions.png" alt-text="Diagram listing six missions.":::

|===
| What to do | How to do it

| *Fortify your environment* + (Tasks your admin completes.)
| xref:m365bp-setup-overview.adoc[*1.
Sign in and set up your environment*].
Complete the basic setup process for Microsoft 365 for your business or campaign.
Add users, assign licenses, and configure your domain to work with Microsoft 365.
+  + xref:m365bp-security-overview.adoc[*2.
Bump up security protection*].
Set up critical front-line security measures to prevent cyberattacks.
Set up multi-factor authentication (MFA), protect your admin accounts, and protect against malware and other threats.

| *Train your team*.
+ (Tasks everyone does.)
| xref:m365bp-protect-pcs-macs.adoc[*3.
Set up unmanaged (BYOD) devices*].
Set up all the unmanaged ("bring your own device," also referred to as BYOD) devices so they're safely part of the ecosystem.
+  + xref:m365bp-protect-email-overview.adoc[*4.
Use email securely*].
Know what to watch for in your email, and take the necessary steps to protect yourself from attacks.
+  + xref:m365bp-collaborate-share-securely.adoc[*5.
Collaborate and share securely*].
Share files with others and collaborate more securely with Microsoft Teams, SharePoint, and OneDrive.

| *Safeguard managed devices*.
+ (Tasks your admin or security team does.)
| xref:m365bp-protect-devices.adoc[*6.
Set up and secure managed devices*].
Enroll and secure company devices so they monitored and protected from threats.
|===

Completing all six missions is the most effective way to thwart hackers, protect against ransomware, and help ensure your organization's future is safeguarded with the best cybersecurity defenses.
Let's get started!

____
[!TIP] If you're new to cybersecurity, or if a term is unclear, see the link:m365bp-glossary.yml[glossary of terms].
____

=== Cybersecurity playbook

The guidance in these missions is based upon the xref:../security/office-365-security/microsoft-365-policies-configurations.adoc[Zero Trust security model], and is summarized in a downloadable https://download.microsoft.com/download/9/c/1/9c167271-8209-492e-acc2-38a39d1834c2/m365bp-cybersecurity-playbook.pdf[Cybersecurity playbook]).

https://download.microsoft.com/download/9/c/1/9c167271-8209-492e-acc2-38a39d1834c2/m365bp-cybersecurity-playbook.pdf[:::image type="content" source="media/m365bp-cyber-security-playbook.png" alt-text="Cybersecurity playbook.
Download this guide.":::]

=== Next steps

Proceed to xref:m365bp-setup-overview.adoc[Fortify your environment].
