= Upgrade Windows devices to Windows 10 Pro
:audience: Admin
:author: denisebmsft
:description: Learn how to upgrade your Windows devices to Windows 10 Pro with Microsoft 365 Business Premium.
:f1.keywords: ["NOCSH"]
:localization_priority: Normal
:manager: dansimp
:ms.author: deniseb
:ms.date: 09/15/2022
:ms.service: microsoft-365-security
:ms.subservice: other
:ms.topic: article
:search.appverid: ["MET150", "MOE150"]

== Upgrade Windows devices to Windows 10 Pro

If you have Windows devices running Windows 7 Pro, Windows 8 Pro, or Windows 8.1 Pro, your Microsoft 365 Business Premium subscription entitles you to upgrade those devices to Windows 10 or 11 Pro.

You can choose from several methods to upgrade:

* <<use-windows-update,Use Windows Update>> (recommended for most users)
* <<upgrade-your-device-using-the-microsoft-software-download-site,Upgrade your device using the Microsoft Software Download site>>
* <<create-installation-media-from-the-microsoft-software-download-site,Create installation media from the Microsoft Software Download site>>
* <<purchase-windows-10-or-11-pro-to-upgrade-from-windows-10-home,Purchase Windows 10 or 11 Pro to upgrade from Windows 10 Home>>

=== Use Windows Update

_This option is recommended for most users, as it uses a digital license._

____
[!IMPORTANT] Make sure that users are assigned a Microsoft 365 Business Premium license before they follow this procedure.
____

. On a Windows device, sign in using your account for Microsoft 365 Business Premium.
. Go to Windows Update, and check for updates.
. If your device isn't running Windows 10 Pro, you'll be prompted to upgrade.
Follow the prompts to complete your upgrade.

=== Upgrade your device using the Microsoft Software Download site

_The Windows Update method is preferred.
However, you can select this option if the device that you're using right now is the same device that you want to update._

. Go to the https://go.microsoft.com/fwlink/?LinkID=836951[Microsoft Software Download site].
. On the *Download Windows 10* site, select *Update now* to start upgrading the device to Windows 10 Pro.

=== Create installation media from the Microsoft Software Download site

_Select this option to create Windows 10 installation media (USB flash drive or ISO file) that you'll use to install Windows 10 on a different device than the one you're using right now._

. Go to the https://go.microsoft.com/fwlink/?LinkID=836960[Microsoft Software Download site].
. Follow the instructions on how to use the tool and create your installation media.

____
[!NOTE] If you have Windows devices running Windows 7 Pro, Windows 8 Pro, or Windows 8.1 Pro, your Microsoft 365 Business Premium subscription entitles you upgrade those devices to Windows Pro 10.
____

=== Purchase Windows 10 or 11 Pro to upgrade from Windows 10 Home

_Select this option for devices that are running Windows 10 Home._

. On a Windows device, open the Microsoft Store app.
. In the Microsoft Store app, search for `Windows 10 Pro`.
. Select the option to upgrade to Windows 10/11 Pro.
. Choose either *Learn more* or *Install*, and then follow the prompts.
Note that you might need to purchase Windows 10 Pro.

=== See also

https://support.microsoft.com/windows/activate-windows-c39005d4-95ee-b91e-b399-2820fda32227#WindowsVersion=Windows_10[Activate Windows]

https://go.microsoft.com/fwlink/?linkid=2197659[Microsoft 365 for business training videos]
