= Increase security in Microsoft 365 Business Premium
:audience: Admin
:author: denisebmsft
:description: Security overview for Microsoft 365 Business Premium which provides cybersecurity tools such as multi-factor authentication that you can use to prevent cyberattacks.
:f1.keywords: ["NOCSH"]
:manager: dansimp
:ms.author: deniseb
:ms.collection: ["M365-Campaigns", "m365solution-smb", "highpri"]
:ms.custom: ["MiniMaven"]
:ms.date: 09/15/2022
:ms.localizationpriority: high
:ms.service: microsoft-365-security
:ms.subservice: other
:ms.topic: overview
:search.appverid: ["BCS160", "MET150"]

== Bump up security

:::image type="content" source="media/mission2.png" alt-text="Boost your security protection with Microsoft 365 Business Premium.":::

In this mission, you boost your security defenses.
You begin by enforcing multifactor authentication (MFA) requirements by using either security defaults or Conditional Access.
You'll set up the different admin roles and specific levels of security for them.
Admin account access is a high-value target for the enemy hackers, and protecting those accounts is critical because the access and control they provide can impact the entire system.
And, you'll protect your email content and devices.

Stay vigilant - the safety and reliability of the system relies upon you.

Your objectives are to:

* xref:m365bp-conditional-access.adoc[Turn on security defaults (MFA)].
* xref:m365bp-protect-admin-accounts.adoc[Protect your admin accounts].
* xref:m365bp-increase-protection.adoc[Protect against malware and other threats].

Once you've achieved these objectives, proceed to xref:m365bp-devices-overview.adoc[Set up unmanaged (BYOD) devices].
