= Set up multi-factor authentication for Microsoft 365 Business Premium
:audience: Admin
:author: denisebmsft
:description: Set up multi-factor authentication for phones in Microsoft Business Premium. Increase your security by using Microsoft Business Premium's MFA features for your phone.
:f1.keywords: ["NOCSH"]
:manager: dansimp
:ms.author: deniseb
:ms.collection: ["M365-Campaigns", "m365solution-smb", "highpri"]
:ms.custom: ["MiniMaven"]
:ms.date: 09/15/2022
:ms.localizationpriority: high
:ms.service: microsoft-365-security
:ms.subservice: other
:ms.topic: conceptual
:search.appverid: ["BCS160", "MET150", "MOE150"]

== Set up MFA

Multi-factor authentication (MFA) provides increased security because instead of only using a password, or a code through text, a separate app on your phone is used to verify access.
This makes it difficult to hack.
When MFA is required, members of the organization can use the Microsoft Authenticator app to securely sign in on their devices.
+  +

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/RE2MmQR]
____

See more at https://support.office.com/article/a32541df-079c-420d-9395-9d59354f7225[Set up multi-factor authentication in Microsoft 365 Business Premium]

=== Use the Outlook app on your devices

When MFA is enforced, the authenticator app serves as a second form of authentication.
We also recommend that everyone install and use the Outlook app to access their Microsoft 365 email on their devices.
See https://www.microsoft.com/microsoft-365/outlook-mobile-for-android-and-ios[Download Microsoft Outlook for iOS and Android].

=== Next objective

Proceed to xref:m365bp-install-office-apps.adoc[install Office applications].
