= Microsoft 365 Business Premium - Productivity and security
:audience: Admin
:author: denisebmsft
:description: Learn how Microsoft 365 Business Premium helps you run your business more securely with productivity and security.
:f1.keywords: ["NOCSH"]
:manager: dansimp
:ms.author: deniseb
:ms.collection: ["M365-Campaigns", "m365solution-smb", "highpri"]
:ms.custom: ["MiniMaven"]
:ms.date: 09/15/2022
:ms.localizationpriority: high
:ms.service: microsoft-365-security
:ms.subservice: other
:ms.topic: conceptual
:search.appverid: ["BCS160", "MET150", "MOE150"]

== Productivity and security for small and medium-sized businesses

Microsoft 365 Business Premium is a comprehensive cloud productivity and security solution that was designed and built for small and medium-sized businesses (1-300 employees).
With Microsoft 365 Business Premium, you can:

* *Enable your employees to be connected and productive*, whether they're working on site or remotely, with best-in-class collaboration tools like xref:create-teams-for-collaboration.adoc[Microsoft Teams].
* *Provide your employees with secure access to their business data and apps*, and help ensure that only authorized personnel can access confidential work data.
* *Defend against sophisticated cyberthreats and safeguard your business data* with advanced protection against phishing, ransomware, and data loss.
* *Manage and secure devices* (Windows, Mac, iOS, and Android) that connect to your data, and help keep those devices up to date.

Microsoft 365 Business Premium offers you one comprehensive solution for productivity and security.
As an admin or IT Pro, you have everything you need in one place for administration, billing, and 24x7 support, while reducing cost and complexity for your business.

=== Video: Top 5 benefits of Microsoft 365 Business Premium

Watch the following video to see how Microsoft 365 Business Premium helps your business be more productive and secure: <p>

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/RE4Pq0G]
____

____
[!TIP] For more detailed information about what's included in Microsoft 365 Business Premium, see the https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWR6bM[Microsoft 365 User Subscription Suites for Small and Medium-sized Businesses].
____

=== Resources to train your users

The security recommendations provided in xref:index.adoc[this guidance] make it much harder for cyberattackers to gain access to your environment.
However, an important part of your security strategy includes training everyone in your organization&mdash;the people in your company who use your systems regularly.
Users can be your first line of defense.
Everyone needs to know how to work productively while maintaining a more secure environment.

Resources are available to help everyone in your organization to:

* xref:m365bp-devices-overview.adoc[Protect devices]
* xref:m365bp-protect-email-overview.adoc[Use email more securely]
* xref:m365bp-collaborate-share-securely.adoc[Collaborate and share information more securely]

Use the recommendations in this library to help your users be productive and more secure in their work.

=== Download the digital threats guide

Our digital threats guide describes different kinds of threats and what you and your staff can do to protect against these threats.
Download this visual guide for you and your team:

https://download.microsoft.com/download/9/1/f/91fa8f24-9953-4f33-9d87-a95624db5e0b/M365BPWhatCanUsersDoToSecure.pdf[:::image type="content" source="media/m365bp-whatuserscandotosecure.png" alt-text="Thumbnail of downloadable guide.":::]

[cols=2*]
|===
| https://download.microsoft.com/download/9/1/f/91fa8f24-9953-4f33-9d87-a95624db5e0b/M365BPWhatCanUsersDoToSecure.pdf[PDF]
| https://download.microsoft.com/download/9/1/f/91fa8f24-9953-4f33-9d87-a95624db5e0b/M365BPWhatCanUsersDoToSecure.pptx[PowerPoint]
|===

=== Next steps

. Get either xref:get-microsoft-365-business-premium.adoc[Microsoft 365 Business Premium] or xref:get-microsoft-365-campaigns.adoc[Microsoft 365 for Campaigns].
. xref:m365bp-setup-overview.adoc[Start the setup process].
. xref:m365bp-security-overview.adoc[Set up your security capabilities].
