= Protect unmanaged Windows PCs and Macs in Microsoft 365 Business Premium
:audience: Admin
:author: denisebmsft
:description: Protect unmanaged or bring-your-own devices (BYOD) from cyberattacks with Microsoft 365 Business Premium. How to set up cybersecurity for Windows PCs and Macs.
:f1.keywords: ["NOCSH"]
:manager: dansimp
:ms.author: deniseb
:ms.collection: ["M365-Campaigns", "m365solution-smb", "highpri"]
:ms.custom: ["MiniMaven"]
:ms.date: 09/15/2022
:ms.localizationpriority: high
:ms.service: microsoft-365-security
:ms.subservice: other
:ms.topic: how-to
:search.appverid: ["BCS160", "MET150", "MOE150"]

== Protect unmanaged Windows PCs and Macs in Microsoft 365 Business Premium

This objective is focused on creating protection for any unmanaged Windows 10 PCs and Macs not enrolled in Microsoft Intune.
It is very likely your small business or campaign may have staff who bring their own devices (BYOD), and these devices are not managed.
BYOD include personally-owned phones, tablets, and PCs.

____
[!NOTE] BYOD users must each install and run the Company Portal app to enroll these devices and receive access to company resources.
____

It's critical that you ensure your frontline users follow these guidelines so that minimum security capabilities are configured on all the BYOD devices.

=== <<tab/Windows10-11,Windows 10 or 11>>

=== Windows 10 or 11

==== Turn on device encryption

Device encryption is available on a wide range of Windows devices and helps protect your data by encrypting it.
If you turn on device encryption, only authorized individuals will be able to access your device and data.
See https://support.microsoft.com/help/4028713/windows-10-turn-on-device-encryption[turn on device encryption] for instructions.

If device encryption isn't available on your device, you can turn on standard https://support.microsoft.com/help/4028713/windows-10-turn-on-device-encryption[BitLocker encryption] instead.
(BitLocker isn't available on Windows 10 Home edition.)

==== Protect your device with Windows Security

If you have Windows 10 or 11, you'll get the latest antivirus protection with Windows Security.
When you start up Windows 10 for the first time, Windows Security is on and actively helping to protect your PC by scanning for malware (malicious software), viruses, and security threats.
Windows Security uses real-time protection to scan everything you download or run on your PC.

Windows Update downloads updates for Windows Security automatically to help keep your PC safe and protect it from threats.

If you have an earlier version of Windows and are using Microsoft Security Essentials, it's a good idea to move to Windows Security.
For more information, see https://support.microsoft.com/help/17464/windows-10-help-protect-my-device-with-windows-security[help protect my device with Windows Security].

==== Turn on Windows Defender Firewall

You should always run Windows Defender Firewall even if you have another firewall turned on.
Turning off Windows Defender Firewall might make your device (and your network, if you have one) more vulnerable to unauthorized access.
See https://support.microsoft.com/help/4028544/windows-10-turn-windows-defender-firewall-on-or-off[Turn Windows Firewall on or off] for instructions.

=== Next mission

Okay, mission complete!
Now, let's work on xref:m365bp-protect-email-overview.adoc[securing the email system] against phishing and other attacks.

=== <<tab/Mac,Mac>>

=== Mac

==== Use FileVault to encrypt your Mac disk

Disk encryption protects data when devices are lost or stolen.
FileVault full-disk encryption helps prevent unauthorized access to the information on your startup disk.
See https://support.apple.com/HT204837[use FileVault to encrypt the startup disk on your Mac] for instructions.

==== Protect your Mac from malware

Microsoft recommends that you install and use reliable antivirus software on your Mac.
See the following article for a list of choices: https://www.macworld.co.uk/feature/mac-software/mac-antivirus-3672182/[Best Mac antivirus 2019].

You can also reduce the risk of malware by using software only from reliable sources.
The settings in Security & Privacy preferences allow you to specify the sources of software installed on your Mac.
For more information, see https://support.apple.com/kb/PH25087[protect your Mac from malware].

==== Turn on firewall protection

Use firewall settings to protect your Mac from unwanted contact initiated by other computers when you're connected to the Internet or a network.
Without this protection, your Mac might be more vulnerable to unauthorized access.
See https://support.apple.com/HT201642[about the application firewall] for instructions.

=== Next mission

Okay, mission complete!
Now, let's work on xref:m365bp-protect-email-overview.adoc[securing email usage] against phishing and other attacks.
