= Add a new user to your network and systems
:audience: Admin
:author: denisebmsft
:description: How to add a new employee or user to your organization's network and internal systems. When a new employee joins your company, you must securely add them to the network.
:f1.keywords: ["NOCSH"]
:manager: dansimp
:ms.author: deniseb
:ms.collection:
:ms.custom: ["MiniMaven", "OKR_SMB_M365"]
:ms.date: 09/15/2022
:ms.localizationpriority: high
:ms.service: microsoft-365-security
:ms.subservice: other
:ms.topic: how-to
:search.appverid: ["BCS160", "MET150"]

== Add a new employee in Microsoft 365 Business Premium

The following information tells you how to use Microsoft 365 Business Premium to add a new employee to the organization.

*Not an admin?* https://support.microsoft.com/office/396b8d9e-e118-42d0-8a0d-87d1f2f055fb[Learn your way around Microsoft 365] helps business and home users with set up.

*No Office apps in your plan?* Follow the steps below, but skip the sections for installing apps.
Use the https://support.microsoft.com/office/91a4ec74-67fe-4a84-a268-f6bdf3da1804[Online versions of Office] instead.

=== How to add a new user

. Go to admin.microsoft.com
. Click *Add a user*.
. Enter the basic information and the _personal_ email address of the new employee.
+
When you set up your new employee in the Admin center, make sure to enter and send log-in details to the employee's personal account.
This way, they'll receive an email from the Microsoft Online Service Team that tells them how to log in to Microsoft 365 Business Premium.
If you don't send it to their personal email address, instead, print out the employee's sign in name and password, and give it to them in person.
Or, tell them the information over the phone.

. Have the new user sign in to use Microsoft 365 Business Premium.
Give them the following sign in information:
 ** Sign in at https://www.office.com.
 ** Select *Sign in*, then type the user ID and password.

And here's a quick reference to help them get started:

|===
| *Task* | *Find the details*

| Sign in to Office  +
| Go to https://www.office.com, select *Sign in*, and then enter your user ID and password.
+

| Install Office apps onto your computer.
+  +
| When you sign in, the home page has a link to download and install apps like Word and Outlook.
Select *Install Office*.
For instructions, see https://support.microsoft.com/office/4414eaaf-0478-48be-9c42-23adc4716658[How to install Office].
+

| Set up your email in Outlook 2016 .  +
| Once Office apps are installed on your computer, set up your email.
For instructions, see https://support.microsoft.com/office/6e27792a-9267-4aa4-8bb6-c84ef146101b[How to set up Outlook].
+

| Set up Skype for Business so you can connect with co-workers or business partners in your company or around the world.
You can start conversations with IM, voice, or video calls.
+
| https://support.microsoft.com/office/8a0d4da8-9d58-44f9-9759-5c8f340cb3fb[Install Skype for Business on your computer].
+  + To learn how to use Skype for Business, https://support.microsoft.com/office/3a21eca4-434d-41f1-ab06-3d4a268573b7[watch a video.] +  + Have you set up Skype for Business so your employees can contact people external to your business who are using the free Skype app?
If not, tell your new employee so they know what to expect when using Skype for Business.
+

| Install apps on your mobile device if you want to get email or use Skype for Business on your phone.
+
| If you want to set up the Outlook mobile app so you can get email via your phone.
For instructions, see https://support.microsoft.com/office/b2de2161-cc1d-49ef-9ef9-81acd1c8e234[iOS], https://support.microsoft.com/office/886db551-8dfa-4fd5-b835-f8e532091872[Android], https://support.microsoft.com/office/181a112a-be92-49ca-ade5-399264b3d417[Windows Phone] +  + If you want to use Skype for Business on your mobile device, download and install the mobile app.
For instructions, see https://support.microsoft.com/office/3239c8a3-cf55-4ff0-a967-5de51911c049#OS_Type=iOS[iOS], https://support.microsoft.com/office/4d1b7dfa-5b0b-4868-bae5-25947fb99e6e#OS_Type=Android[Android], https://support.microsoft.com/office/4d1b7dfa-5b0b-4868-bae5-25947fb99e6e#OS_Type=Windows_Phone[Windows Phone] +

| Complete the OneDrive for Business training to help you learn how to store and organize your documents, presentations, and spreadsheets in the cloud.
+
| Keep your business-related documents in the cloud by using OneDrive for Business.
You can always get to your content, even if you're signed in to Microsoft 365 on a different computer.
https://support.microsoft.com/office/b30da4eb-ddd2-44b6-943b-e6fbfc6b8dde[Watch a video to learn how to use your OneDrive for Business] +  + *Training:* https://support.microsoft.com/office/1f608184-b7e6-43ca-8753-2ff679203132[OneDrive for Business training] (Select OneDrive for Business).
+

| Complete the SharePoint Online training to help you collaborate with coworkers and share content.
+
| The best place to keep documents that your coworkers will also access is in SharePoint Online.
+  + *Training:* https://support.microsoft.com/office/c17b6824-cc22-478f-8757-497cc6b57121[Video: Collaborate with team content using SharePoint Online] +  + *Find out:* How is your organization using SharePoint Online, and what type of documents get stored there.
Also, which documents are stored in OneDrive for Business.
+
|===

=== See also

xref:../admin/security-and-compliance/secure-your-business-data.adoc[Best practices for securing Microsoft 365 for business plans]
