= Change your email address to use your custom domain
:audience: Admin
:author: efrene
:description: Change your email address to a friendly email address like tom@fourthcoffee.com by buying a domain name and adding it to Microsoft 365.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.assetid: f4d8cae9-6d06-4c4b-b4e5-6581fd05ea82
:ms.author: efrene
:ms.collection: ["M365-subscription-management", "Adm_O365", "Adm_TOC", "Adm_O365_Setup"]
:ms.custom: ["MSStore_Link", "AdminSurgePortfolio", "AdminTemplateSet", "adminvideo"]
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["BCS160", "MET150", "MOE150", "BEA160", "GEA150"]

== Change your Microsoft 365 email address to use your custom domain

Check out https://go.microsoft.com/fwlink/?linkid=2197659[Microsoft 365 small business help] on YouTube.

*link:../setup/domains-faq.yml[Check the Domains FAQ]* if you don't find what you're looking for.

::: moniker range="o365-worldwide"

Your initial email address in Microsoft 365 includes .onmicrosoft.com, like tom@fourthcoffee.onmicrosoft.com.
You can change it to a friendlier address like tom@fourthcoffee.com.
You'll need your own domain name, like fourthcoffee.com first.
If you already have one, great!
If not, you can learn how to xref:../get-help-with-domains/buy-a-domain-name.adoc[buy one from a domain registrar].

::: moniker-end

::: moniker range="o365-21vianet"

Your initial email address in Office 365 operated by 21Vianet includes partner.onmschina.cn, like tom@fourthcoffee.partner.onmschina.cn.
You can change it to a friendlier address like tom@fourthcoffee.cn.
You'll need your own domain name, like fourthcoffee.cn first.
If you already have one, great!
If not, you can learn how to xref:../get-help-with-domains/buy-a-domain-name.adoc[buy one from a domain registrar].

::: moniker-end

When you change your domain's email to come to Microsoft 365, by updating your domain's MX record during setup, ALL email sent to that domain will start coming to Microsoft 365.
Make sure you've added users and created mailboxes in Microsoft 365 for everyone who has email on your domain BEFORE you change the MX record.
Don't want to move email for everyone on your domain to Microsoft 365?
You can take steps to xref:../misc/pilot-microsoft-365-from-my-custom-domain.adoc[pilot Microsoft 365 with just a few email addresses instead].

=== Set up business email with a new domain

Check out this video and others on our https://go.microsoft.com/fwlink/?linkid=2198215[YouTube channel].

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/RWyVVA?autoplay=false]
____

Buy a new domain name for your email address and set up the email addresses with Microsoft 365.

. Buy a new domain name for your email address by providing your contact information for the new domain name, choosing your payment method, and then placing your order.
. Change the first part of the address (before the @ sign) or leave it as is.
. Sign out of Microsoft 365, and then sign back in with your new email address.
Your employee email addresses are updated with the new domain.

=== Set up business email with an existing domain

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/RWxApu?autoplay=false]
____

Use a domain name you already own whether you're using it for a website address or an email address at another provider.

. Sign into the website that hosts your domain.
Click a button to verify automatically or update the domain manually.
. Customize the email address or leave it as is.
. Sign out of Microsoft 365, and then sign back in with your new email address.
Your employee email addresses are updated with the new domain.

=== Change your email address to use your custom domain using the Microsoft 365 admin center

You must be a global admin to perform these steps.

::: moniker range="o365-worldwide"

. Go to the admin center at https://go.microsoft.com/fwlink/p/?linkid=2024339[https://admin.microsoft.com].

::: moniker-end

::: moniker range="o365-21vianet"

. Go to the admin center at https://go.microsoft.com/fwlink/p/?linkid=850627[https://portal.partner.microsoftonline.cn].

::: moniker-end

. Go to the *Setup* > *Domains* page.
. On the *Domains* page, select *Add domain*.
. Follow the steps to confirm that you own your domain.
You'll be guided to get everything set up correctly with your domain in Microsoft 365.
. Go to *Users* > *Active users*.
. Select a user to edit their username and change it to the domain you just added.

____
[!NOTE] If you are not using an Exchange license, you cannot use the domain to send or receive emails from the Microsoft 365 tenant.
____

=== Related content

xref:../get-help-with-domains/buy-a-domain-name.adoc[Buy a custom domain using Microsoft 365] (article) + link:/admin[Manage domains] (link page) + link:../setup/domains-faq.yml[Domains FAQ] (article)
