= Configure Clutter for your organization
:audience: Admin
:author: kwekua
:description: Learn to enable or disable the Clutter feature for all or specific users in your organization, using Exchange PowerShell.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.assetid: 832276bd-d024-47b6-a80a-a6b884907a5b
:ms.author: kwekua
:ms.collection: ["M365-subscription-management", "Adm_O365", "Adm_TOC"]
:ms.custom: ["AdminSurgePortfolio", "AdminTemplateSet"]
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["BCS160", "MET150", "MOE150"]

== Configure Microsoft 365 Clutter for your organization

____
[!TIP] xref:../setup/configure-focused-inbox.adoc[Focused Inbox] is going to replace Clutter.
Learn more: https://techcommunity.microsoft.com/t5/Outlook-Blog/Update-on-Focused-Inbox-and-our-plans-for-Clutter/ba-p/136448[Update on Focused Inbox and our plans for Clutter]
____

As an admin, you may have to manage the Clutter feature in Microsoft 365.
To turn the Clutter feature on/off for users in your organization, you must use Exchange PowerShell.
(Individuals can turn it on/off using these instructions: https://support.microsoft.com/office/a9c72a77-1bc4-40e6-ba6d-103c1d1aba4c[Turn off/on Clutter in Outlook].

Check out link:/powershell/exchange/exchange-online-powershell[Using PowerShell with Exchange Online] and link:/powershell/exchange/connect-to-exchange-online-powershell[Connect to Exchange Online PowerShell] for details on using Exchange PowerShell.
You need to have an account that has at least the Exchange Service administrator role and the ability to connect to Exchange Online with PowerShell.

=== Turn Clutter on using Exchange PowerShell

You can enable Clutter manually for a mailbox by running the link:/powershell/module/exchange/set-clutter[Set-Clutter] cmdlet.
You can also view Clutter settings for mailboxes in your organization by running the link:/powershell/module/exchange/get-clutter[Get-Clutter] cmdlet.

Turn on Clutter for a single user named Allie Bellew

`Set-Clutter -Identity "Allie Bellew" -Enable $true`

=== Turn Clutter off using Exchange PowerShell

You can disable Clutter manually for a mailbox by running the link:/powershell/module/exchange/set-clutter[Set-Clutter] cmdlet.
You can also view *Clutter* settings for mailboxes in your organization by running the link:/powershell/module/exchange/get-clutter[Get-Clutter] cmdlet.

Turn off Clutter for a single user named Allie Bellew:

`Set-Clutter -Identity "Allie Bellew" -Enable $false`

If you use PowerShell to bulk create your users, then you'll need to run link:/powershell/module/exchange/set-clutter[Set-Clutter] against each user's mailbox to manage Clutter.

=== When does the Clutter on/off switch appear to users in Outlook on the web?

+++<a name="bkmk_onoff">++++++</a>+++

As an admin, you can re-enable Clutter using Exchange PowerShell.
Once this is done, Focused Inbox will be turned off and Clutter will be active again.

*If you're using Outlook on the web with a Microsoft 365 Business Premium subscription:*

* If user currently has Clutter enabled:
 ** Clutter settings appear
* If user currently has Focused Inbox enabled:
 ** Clutter settings will not appear
* If neither Clutter or Focused Inbox is enabled:
 ** Both Clutter and Focused Inbox appear as options in the user's Mail Settings

*If you're using Outlook.com:*

* If user currently has Clutter enabled:
 ** Clutter settings appear
* If user currently has Focused Inbox enabled:
 ** Clutter settings will not appear
* If neither Clutter or Focused Inbox is enabled:
 ** Both Clutter and Focused Inbox appear as options in the user's Mail Settings
* If user enabled Focused Inbox at some point in the past:
 ** Clutter settings will never appear
+
Otherwise,

 ** Clutter settings will appear

=== Related content

https://support.microsoft.com/office/7b50c5db-7704-4e55-8a1b-dfc7bf1eafa0[Use Clutter to sort low priority messages in Outlook] (article) + https://support.microsoft.com/office/fe4d64ca-bf73-48f1-91b4-9a659e008bce[Use Clutter to sort low priority messages in OWA] (article) + https://support.microsoft.com/office/a9c72a77-1bc4-40e6-ba6d-103c1d1aba4c[Turn off Clutter in Outlook] (article)
