= Configure email forwarding
:audience: Admin
:author: kwekua
:description: Email forwarding lets you forward email messages sent to a Microsoft 365 user mailbox to another mailbox inside or outside of your organization.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.assetid: ab5eb117-0f22-4fa7-a662-3a6bdb0add74
:ms.author: kwekua
:ms.collection: ["M365-subscription-management", "Adm_O365", "Adm_TOC"]
:ms.custom: ["MSStore_Link", "AdminSurgePortfolio", "okr_smb", "AdminTemplateSet", "business_assist"]
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["BCS160", "MET150", "MOE150"]

== Configure email forwarding in Microsoft 365

As the admin of an organization, you might have company requirements to set up email forwarding for a user's mailbox.
Email forwarding lets you forward email messages sent to a user's mailbox to another user's mailbox inside or outside of your organization.

____
[!IMPORTANT] You can use outbound spam filter policies to control automatic forwarding to external recipients.
For more information, see link:/microsoft-365/security/office-365-security/external-email-forwarding#how-the-outbound-spam-filter-policy-settings-work-with-other-automatic-email-forwarding-controls[Control automatic external email forwarding in Microsoft 365].
____

____
[!TIP] If you need help with the steps in this topic, consider https://go.microsoft.com/fwlink/?linkid=2186871[working with a Microsoft small business specialist].
With Business Assist, you and your employees get around-the-clock access to small business specialists as you grow your business, from onboarding to everyday use.
____

=== Configure email forwarding

Before you set up email forwarding, note the following:

* Allow automatically forwarded messages to be sent to people on the remote domain.
See link:/exchange/mail-flow-best-practices/remote-domains/manage-remote-domains[Manage remote domains] for details.
* Once you set up email forwarding, only *new* emails sent to the  _from_  mailbox will be forwarded.
* Email forwarding requires that the  _from_  account has a license.
If you're setting up email forwarding because the user has left your organization, another option is to xref:convert-user-mailbox-to-shared-mailbox.adoc[convert their mailbox to a shared mailbox].
This way several people can access it.
However, a shared mailbox cannot exceed 50GB.

You must be an Exchange administrator or Global administrator in Microsoft 365 to do these steps.
For more information, see the topic xref:../add-users/about-admin-roles.adoc[About admin roles].

::: moniker range="o365-worldwide"

. In the admin center, go to the *Users* > *https://go.microsoft.com/fwlink/p/?linkid=834822[Active users]* page.
. Select the name of the user whose email you want to forward, then open the properties page.
. On the *Mail* tab, select *Manage email forwarding*.
. On the email forwarding page, select *Forward all emails sent to this mailbox*, enter the forwarding address, and choose whether you want to keep a copy of forwarded emails.
If you don't see this option, make sure a license is assigned to the user account.
Select *Save changes*.
+
*To forward to multiple email addresses*, you can ask the user to set up a rule in Outlook to forward to the addresses.

 .. Open *outlook* > *Home* >  *Rules* > Select *Manage Rules & Alerts*
 .. Select *New Rule* > *Select Apply rule on message I receive* located near bottom of list, then click *Next*.
 .. Click *Yes* when asked This rule will be applied to every message you receive.
 .. On the next list select the actions *redirect it to people or public group* and *stop processing more rules*
 .. Click the underlined phrase *people or public group* in the bottom part of window.
 .. Type the *email address* to forward mail to in the To field, then click *OK*.
 .. Select *Finish*

+
Or, in the admin center, xref:../setup/create-distribution-lists.adoc[create a distribution group], xref:add-user-or-contact-to-distribution-list.adoc[add the addresses to it], and then set up forwarding to point to the DL using the instructions in this article.

. Don't delete the account of the user who's email you're forwarding or remove their license!
If you do, email forwarding will stop.

::: moniker-end

::: moniker range="o365-21vianet"

. In the admin center, go to the *Users* > *https://go.microsoft.com/fwlink/p/?linkid=850628[Active users]* page.
. Select the name of the user whose email you want to forward to open the properties page.
. Expand *Mail settings*, and then in the *Email forwarding* section, select *Edit*.
. On the email forwarding page, set the toggle to *On*, enter the forwarding address, and choose whether you want to keep a copy of forwarded emails.
If you don't see this option, make sure a license is assigned to the user account.
Select *Save*.
+
*To forward to multiple email addresses*, you can ask the user to set up a rule in Outlook to forward to the addresses.
To learn more, see https://support.microsoft.com/office/45aa9664-4911-4f96-9663-ece42816d746[Use rules to automatically forward messages].
+
Or, in the admin center, xref:../setup/create-distribution-lists.adoc[create a distribution group], xref:add-user-or-contact-to-distribution-list.adoc[add the addresses to it], and then set up forwarding to point to the DL using the instructions in this article.

. Don't delete the account of the user who's email you're forwarding or remove their license!
If you do, email forwarding will stop.

::: moniker-end

=== Related content

xref:../email/create-a-shared-mailbox.adoc[Create a shared mailbox] (article) + https://support.microsoft.com/office/ccba89cb-141c-4a36-8c56-6d16a8556d2e[Send email from a different address] (article) + xref:../add-users/change-a-user-name-and-email-address.adoc[Change a user name and email address] (article) + link:/microsoft-365/security/office-365-security/external-email-forwarding[Control automatic external email forwarding in Microsoft 365] (article)
