= Convert a user mailbox to a shared mailbox
:audience: Admin
:author: SKjerland
:description: Learn to convert a private mailbox to a shared mailbox that can be accessed by several people instead of by just one person.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.assetid: 2e122487-e1f5-4f26-ba41-5689249d93ba
:ms.author: sharik
:ms.collection: ["M365-subscription-management", "Adm_O365", "Adm_TOC"]
:ms.custom: ["AdminSurgePortfolio", "AdminTemplateSet", "admindeeplinkEXCHANGE", "business_assist"]
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["BCS160", "MET150", "MOE150"]

== Convert a user mailbox to a shared mailbox

When you convert a user's mailbox to a shared mailbox, all of the existing email and calendar is retained.
Only now it's in a shared mailbox where several people will be able to access it instead of one person.
At a later date, you can convert a shared mailbox back to a user (private) mailbox.

____
[!TIP] If you need help with the steps in this topic, consider https://go.microsoft.com/fwlink/?linkid=2186871[working with a Microsoft small business specialist].
With Business Assist, you and your employees get around-the-clock access to small business specialists as you grow your business, from onboarding to everyday use.
____

=== Before you begin

*Here are some really important things that you need to know*:

* The user mailbox needs a license assigned to it before you convert it to a shared mailbox.
Otherwise, you won't see the option to convert the mailbox.
If you've removed the license, add it back so you can convert the mailbox.
After converting the user mailbox to a shared mailbox, you can remove the license from the user's account.
* Without a license, shared mailboxes are limited to 50 GB.
You might need to delete a bunch of large messages (say, messages with attachments) from the shared mailbox to shrink it down so you can remove the license.
+
To increase the size limit to 100 GB, assign an Exchange Online Plan 2 license to the shared mailbox.
+
If you assign an Exchange Online Plan 1 license and an Exchange Online Archiving add-on license to the shared mailbox, you can enable auto-expanding archiving for additional archive storage capacity.

* Don't delete the old user's account, because the account is required to anchor the shared mailbox.
If you've already deleted the user account, see <<convert-the-mailbox-of-a-deleted-user,Convert the mailbox of a deleted user>>.
* You don't need to reset the account password of the user mailbox.
However, if you don't reset the password, *the original username and password will continue to work on the shared mailbox* after the conversion is finished.
* Inbox rules are preserved after the user mailbox is converted to a shared mailbox.
* To put an In-Place Hold or a Litigation Hold on a shared mailbox, you must assign an Exchange Online Plan 2 license _or_ an Exchange Online Plan 1 license and an Exchange Online Archiving add-on license to the shared mailbox.

=== Use the Classic Exchange admin center to convert a mailbox

. Go to the https://go.microsoft.com/fwlink/p/?linkid=2059104[Classic Exchange admin center].
. Select *Recipients* > *Mailboxes*.
. Select the user mailbox.
Under *Convert to Shared Mailbox*, select *Convert*.
. If the mailbox is smaller than 50 GB, you can remove the xref:../manage/remove-licenses-from-users.adoc[license from the user], and stop paying for it.
Don't delete the user's account.
The shared mailbox needs it there as an anchor.
If you're converting the mailbox of an employee that's leaving your organization, you should take additional steps to make sure that they can no longer log in.
For more information, see xref:../add-users/remove-former-employee.adoc[Remove a former employee from Microsoft 365].

For everything else you need to know about shared mailboxes, see xref:about-shared-mailboxes.adoc[About shared mailboxes] and xref:create-a-shared-mailbox.adoc[Create a shared mailbox].

=== Use the New Exchange admin center to convert a mailbox

. Go to the https://admin.exchange.microsoft.com/#/homepage[Exchange admin center].
. Select *Recipients* > *Mailboxes*.
. Select the user mailbox.
In the *Others* tab, select *Convert to shared mailbox*.
. If the mailbox is smaller than 50 GB, you can remove the xref:../manage/remove-licenses-from-users.adoc[license from the user], and stop paying for it.
Don't delete the user's account.
The shared mailbox needs it there as an anchor.
If you are converting the mailbox of an employee that is leaving your organization, you should take additional steps to make sure that they cannot log in anymore.
Please see xref:../add-users/remove-former-employee.adoc[Remove a former employee from Microsoft 365].

For everything else you need to know about shared mailboxes, see xref:about-shared-mailboxes.adoc[About shared mailboxes] and xref:create-a-shared-mailbox.adoc[Create a shared mailbox].

=== Convert the mailbox of a deleted user

After deleting a user account, follow these steps to convert their old mailbox to a share mailbox:

. xref:../add-users/restore-user.adoc[Restore the user's account].
. Make sure a Microsoft 365 license is assigned to it.
. Reset the user's password.
. Wait 20-30 minutes for their mailbox to be re-created.
. Once the mailbox is re-created, remove the license from the user's mailbox.
Don't delete the user's old mailbox.
The shared mailbox needs it there as an anchor.
. Add members to the shared mailbox.

=== Convert a shared mailbox back to a user's (private) mailbox

. Go to the https://go.microsoft.com/fwlink/p/?linkid=2059104[Exchange admin center].
. Select *Recipients* > *Shared*.
. Select the shared mailbox.
Under *Convert to Regular Mailbox*, select *Convert*.
. Go back to the admin center.
Under *Users*, choose the user account associated with the old shared mailbox.
Assign a license to the account, and then reset the password.
+
It will take a few minutes for the mailbox to get set up, but after that, the person who's going to use that account is ready to go.
When they sign in, they'll see the email and calendar items that used to be in the shared mailbox.

=== Convert a user's mailbox in a hybrid environment

For more info about converting a user mailbox to a shared mailbox in an Exchange Hybrid environment, see:

* https://support.microsoft.com/office/cmdlets-to-create-or-modify-a-remote-shared-mailbox-in-an-on-premises-exchange-environment-9e83fb59-c001-729c-a4c0-b2964c154b49[Cmdlets to create or modify a remote shared mailbox in an on-premises Exchange environment]
* link:/exchange/troubleshoot/user-and-shared-mailboxes/shared-mailboxes-unexpectedly-converted-to-user-mailboxes[Shared mailboxes are unexpectedly converted to user mailboxes after directory synchronization runs in an Exchange hybrid deployment]

____
[!NOTE] If you're a member of the Organization Management or Recipient Management role group, you can use the Exchange Management Shell to change a user mailbox to a shared mailbox on-premises.
For example, `Set-Mailbox -Identity mailbox1@contoso.com -Type Shared`.
____

=== Related content

xref:about-shared-mailboxes.adoc[About shared mailboxes] (article) + xref:create-a-shared-mailbox.adoc[Create a shared mailbox] (article) + xref:configure-a-shared-mailbox.adoc[Configure a shared mailbox] (article) + xref:remove-license-from-shared-mailbox.adoc[Remove a license from a shared mailbox] (article) + xref:resolve-issues-with-shared-mailboxes.adoc[Resolve issues with shared mailboxes] (article)
