= 
mjcaparas
:keywords: managed security service provider, mssp, configure,
integration

== Access the Microsoft 365 Defender MSSP customer portal

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365
Defender]

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-mssp-support-abovefoldlink[Sign
up for a free trial.]
____

____
[!NOTE] These set of steps are directed towards the MSSP.
____

By default, MSSP customers access their Microsoft 365 Defender tenant
through the following URL: `https://security.microsoft.com/`.

MSSPs however, will need to use a tenant-specific URL in the following
format: `https://security.microsoft.com?tid=customer_tenant_id` to
access the MSSP customer portal.

In general, MSSPs will need to be added to each of the MSSP customer’s
Azure AD that they intend to manage.

Use the following steps to obtain the MSSP customer tenant ID and then
use the ID to access the tenant-specific URL:

[arabic]
. As an MSSP, log in to Azure AD with your credentials.
. Switch directory to the MSSP customer’s tenant.
. Select *Azure Active Directory > Properties*. You’ll find the tenant
ID in the Tenant ID field.
. Access the MSSP customer portal by replacing the `customer_tenant_id`
value in the following URL:
`https://security.microsoft.com/?tid=customer_tenant_id`.

=== Related topics

* link:grant-mssp-access.md[Grant MSSP access to the portal]
* link:configure-mssp-notifications.md[Configure alert notifications]
* link:fetch-alerts-mssp.md[Fetch alerts from customer tenant]
