= 
siosulli
:keywords: apis, graph api, supported apis, scans, network scans,
authenticated scan

== Add, update or delete a scan definition

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 2]
* link:../defender-vulnerability-management/index.yml[Microsoft Defender
Vulnerability Management]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365
Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

____
Want to experience Microsoft Defender Vulnerability Management? Learn
more about how you can sign up to the
link:../defender-vulnerability-management/get-defender-vulnerability-management.md[Microsoft
Defender Vulnerability Management public preview trial].
____

{empty}[!Includelink:../../includes/prerelease.md[Prerelease
information]]

{empty}[!Includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!Includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

API to add, update or delete an authenticated scan.

=== Limitations

Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.

You can post on machines last seen according to your configured
retention period.

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Defender for Endpoint APIs].

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Machine.ReadWrite.All |Read and write all scan
information.

|Delegated (work or school account) |Machine.Read.Write |Read and write
all scan information.
|===

____
[!NOTE] When obtaining a token using user credentials:

* To view data the user needs to have at least the following role
permission: `ViewData' or `TvmViewData' (See link:user-roles.md[Create
and manage roles] for more information)
* To edit data the user needs to have at least the following role
permission: `ManageSecurity' (See link:user-roles.md[Create and manage
roles] for more information)
____

=== HTTP request

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/DeviceAuthenticatedScanDefinitions
----

=== Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|Content-Type |string |application/json. *Required*.
|===

=== Request body

In the request body, supply a JSON object with the following parameters:

[cols="<,<,<",options="header",]
|===
|Parameter |Type |Description
|ScanDefinitionIds |String |The scan Id. *Required*.
|===

=== Response

If successful, this method returns 200 - Ok response code and the
updated Machine in the response body.

=== Example request to add a new scan

Here is an example of a request that adds a new scan.

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/DeviceAuthenticatedScanDefinitions
----

[source,json]
----
 {
"scanType": "Windows", 
"scanName": "Test Windows scan", 
"isActive": true, 
"target": "127.0.0.1", 
"intervalInHours": 1, 
"targetType": "Ip",
"scannerAgent": {
    "machineId": "eb663a27ae9d032f61bc268a79eedf14c4b90f77",
    "machineName": "DESKTOP-TEST",
"scanAuthenticationParams": { 
    "@odata.type": "#microsoft.windowsDefenderATP.api.WindowsAuthParams", 
    "type": "Kerberos", 
    "username": "username", 
    "domain": "password",
    "isGmsaUser": true
        },
    },
 },
 {
"scanType": "Network", 
"scanName": "Test Network scan", 
"isActive": true, 
"target": "127.0.0.1", 
"intervalInHours": 1, 
"targetType": "Ip",
"scannerAgent": {
    "machineId": "eb663a27678ik2f61bc268a79eeasdf450f77",
    "machineName": "DESKTOP-TEST",
"scanAuthenticationParams": {
    "@odata.type": "#microsoft.windowsDefenderATP.api.SnmpAuthParams", 
        "type": "AuthPriv", 
        "username": "username", 
        "authProtocol": "authProtocol", 
        "authPassword": "authPassword", 
        "privProtocol": "privProtocol", 
        "privPassword": "privPassword", 
        "communityString": "community-string" 
        },
    },
 }
----

=== Example request to delete scans

Here is an example of a request that deletes scans.

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/DeviceAuthenticatedScanDefinitions/BatchDelete
----

[source,json]
----
{
  "ScanDefinitionIds": ["td32f17af-5cc2-4e4e-964a-4c4ef7d216e2", "ab32g20af-5dd2-4a5e-954a-4c4ef7d216e2"],
}
----

=== Example request to update a scan

Here is an example of a request that updates a scan.

[source,http]
----
PATCH https://api.securitycenter.microsoft.com/api/DeviceAuthenticatedScanDefinitions/a07c400a-f8e1-4329-ae66-7d3be65df0ec
----

[source,json]
----
{
"scanName": "Test Network scan", 
"intervalInHours": 8,
"isActive": "True",
"targetType": "Ip",
"target": "10.5.0.8",
"scanAuthenticationParams": { 
 "@odata.type": "#microsoft.windowsDefenderATP.api.SnmpAuthParams", 
    "type": "Kerberos", 
    "username": "username", 
    "domain": "password",
    "isGmsaUser": true
    }
}
----
