= 
mjcaparas
:keywords: apis, graph api, supported apis, tags, machine tags

== Add or remove machine tags API

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 2]

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Adds or removes tag to a specific link:machine.md[Machine].

=== Limitations

[arabic]
. You can post on machines last seen according to your configured
retention period.
. Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Defender for Endpoint APIs].

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Machine.ReadWrite.All |`Read and write all machine
information'

|Delegated (work or school account) |Machine.ReadWrite |`Read and write
machine information'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to have at least the following role permission: `Manage
security setting'. For more (See link:user-roles.md[Create and manage
roles] for more information).
* The user needs to have access to the machine, based on machine group
settings (See link:machine-groups.md[Create and manage machine groups]
for more information).
____

=== HTTP request

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/machines/{id}/tags
----

=== Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|Content-Type |string |application/json. *Required*.
|===

=== Request body

In the request body, supply a JSON object with the following parameters:

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Parameter |Type |Description
|Value |String |The tag name. *Required*.

|Action |Enum |Add or Remove. Allowed values are: `Add' or `Remove'.
*Required*.
|===

=== Response

If successful, this method returns 200 - Ok response code and the
updated Machine in the response body.

=== Example Request

Here is an example of a request that adds machine tag.

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/machines/1e5bc9d7e413ddd7902c2932e418702b84d0cc07/tags
----

[source,json]
----
{
  "Value" : "test Tag 2",
  "Action": "Add"
}
----

To remove machine tag, set the Action to `Remove' instead of `Add' in
the request body.
