= 
schmurky
:keywords: advanced hunting, threat hunting, cyber threat hunting,
mdatp, microsoft defender atp, microsoft defender for endpoint, wdatp,
search, query, telemetry, custom detections, schema, kusto, time zone,
UTC

== Proactively hunt for threats with advanced hunting

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-advancedhunting-abovefoldlink[Sign
up for a free trial.]
____

Advanced hunting is a query-based threat-hunting tool that lets you
explore up to 30 days of raw data. You can proactively inspect events in
your network to locate threat indicators and entities. The flexible
access to data enables unconstrained hunting for both known and
potential threats.

Watch this video for a quick overview of advanced hunting and a short
tutorial that will get you started fast.

____
{empty}[!VIDEO https://www.microsoft.com/videoplayer/embed/RE4bGqo]
____

You can use the same threat-hunting queries to build custom detection
rules. These rules run automatically to check for and then respond to
suspected breach activity, misconfigured machines, and other findings.

____
[!TIP] Use
link:/microsoft-365/security/defender/advanced-hunting-overview[advanced
hunting in Microsoft 365 Defender] to hunt for threats using data from
Defender for Endpoint, Microsoft Defender for Office 365, Microsoft
Defender for Cloud Apps, and Microsoft Defender for Identity.
link:/microsoft-365/security/defender/m365d-enable[Turn on Microsoft 365
Defender].
____

Learn more about how to move your advanced hunting workflows from
Microsoft Defender for Endpoint to Microsoft 365 Defender in
link:/microsoft-365/security/defender/advanced-hunting-migrate-from-mde[Migrate
advanced hunting queries from Microsoft Defender for Endpoint].

=== Get started with advanced hunting

Go through the following steps to ramp up your advanced hunting
knowledge.

We recommend going through several steps to quickly get up and running
with advanced hunting.

'''''

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Learning goal |Description |Resource
|*Learn the language* |Advanced hunting is based on
link:/azure/kusto/query/[Kusto query language], supporting the same
syntax and operators. Start learning the query language by running your
first query. |link:advanced-hunting-query-language.md[Query language
overview]

|*Learn how to use the query results* |Learn about charts and various
ways you can view or export your results. Explore how you can quickly
tweak queries and drill down to get richer information.
|link:advanced-hunting-query-results.md[Work with query results]

|*Understand the schema* |Get a good, high-level understanding of the
tables in the schema and their columns. Learn where to look for data
when constructing your queries.
|link:advanced-hunting-schema-reference.md[Schema reference]

|*Use predefined queries* |Explore collections of predefined queries
covering different threat hunting scenarios.
|link:advanced-hunting-shared-queries.md[Shared queries]

|*Optimize queries and handle errors* |Understand how to create
efficient and error-free queries.
|link:advanced-hunting-best-practices.md[Query best practices]

|*Get the most complete coverage* |Use audit settings to provide better
data coverage for your organization.
|link:advanced-hunting-extend-data.md[Extend advanced hunting coverage]

|*Run a quick investigation* |Quickly run an advanced hunting query to
investigate suspicious activity.
|link:advanced-hunting-go-hunt.md[Quickly hunt for entity or event
information with _go hunt_]

|*Contain threats and address compromises* |Respond to attacks by
quarantining files, restricting app execution, and other actions
|link:advanced-hunting-take-action.md[Take action on advanced hunting
query results]

|*Create custom detection rules* |Understand how you can use advanced
hunting queries to trigger alerts and take response actions
automatically. |link:overview-custom-detections.md[Custom detections
overview]

| | |
|===

=== Data freshness and update frequency

Advanced hunting data can be categorized into two distinct types, each
consolidated differently.

* *Event or activity data*: Populates tables about alerts, security
events, system events, and routine assessments. Advanced hunting
receives this data almost immediately after the sensors that collect
them successfully transmit them to Defender for Endpoint.
* *Entity data*: Populates tables with consolidated information about
users and devices. This data comes from both relatively static data
sources and dynamic sources, such as Active Directory entries and event
logs. To provide fresh data, tables are updated with any new information
every 15 minutes, adding rows that might not be fully populated. Every
24 hours, data is consolidated to insert a record that contains the
latest, most comprehensive data set about each entity.

=== Time zone

Time information in advanced hunting is currently in the UTC time zone.

=== Related topics

* link:advanced-hunting-query-language.md[Learn the query language]
* link:advanced-hunting-query-results.md[Work with query results]
* link:advanced-hunting-shared-queries.md[Use shared queries]
* link:advanced-hunting-schema-reference.md[Understand the schema]
* link:advanced-hunting-best-practices.md[Apply query best practices]
* link:overview-custom-detections.md[Custom detections overview]
* link:/azure/storage/common/storage-account-overview[Storage account
overview]
* link:/azure/event-hubs/event-hubs-about[Azure Event Hubs — A big data
streaming platform and event ingestion service]
