= 
mjcaparas

== Alerts queue in Microsoft 365 Defender

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

Learn how you can view and manage the queue so that you can effectively
investigate threats seen on entities such as devices, files, or user
accounts.

=== In this section

[width="100%",cols="<50%,<50%",options="header",]
|===
|Topic |Description
|link:alerts-queue.md[View and organize the Alerts queue] |Shows a list
of alerts that were flagged in your network.

|link:manage-alerts.md[Manage alerts] |Learn about how you can manage
alerts such as change its status, assign it to a security operations
member, and see the history of an alert.

|link:investigate-alerts.md[Investigate alerts] |Investigate alerts that
are affecting your network, understand what they mean, and how to
resolve them.

|link:investigate-files.md[Investigate files] |Investigate the details
of a file associated with a specific alert, behavior, or event.

|link:investigate-machines.md[Investigate devices] |Investigate the
details of a device associated with a specific alert, behavior, or
event.

|link:investigate-ip.md[Investigate an IP address] |Examine possible
communication between devices in your network and external internet
protocol (IP) addresses.

|link:investigate-domain.md[Investigate a domain] |Investigate a domain
to see if devices and servers in your network have been communicating
with a known malicious domain.

|link:investigate-user.md[Investigate a user account] |Identify user
accounts with the most active alerts and investigate cases of potential
compromised credentials.
|===
