= 
mjcaparas
:keywords: apis, graph api, supported apis, get, alerts, recent

== Alert resource type

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]

____
[!NOTE] For the full available Alerts API experience across all
Microsoft Defenders’ products, visit:
link:/graph/api/resources/security-api-overview[Use the Microsoft Graph
security API - Microsoft Graph beta | Microsoft Learn].
____

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== Methods

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Method |Return Type |Description
|link:get-alert-info-by-id.md[Get alert] |link:alerts.md[Alert] |Get a
single link:alerts.md[alert] object.

|link:get-alerts.md[List alerts] |link:alerts.md[Alert] collection |List
link:alerts.md[alert] collection.

|link:update-alert.md[Update alert] |link:alerts.md[Alert] |Update
specific link:alerts.md[alert].

|link:batch-update-alerts.md[Batch update alerts] | |Update a batch of
link:alerts.md[alerts].

|link:create-alert-by-reference.md[Create alert] |link:alerts.md[Alert]
|Create an alert based on event data obtained from
link:run-advanced-query-api.md[Advanced Hunting].

|link:get-alert-related-domain-info.md[List related domains] |Domain
collection |List URLs associated with the alert.

|link:get-alert-related-files-info.md[List related files]
|link:files.md[File] collection |List the link:files.md[file] entities
that are associated with the link:alerts.md[alert].

|link:get-alert-related-ip-info.md[List related IPs] |IP collection
|List IPs that are associated with the alert.

|link:get-alert-related-machine-info.md[Get related machines]
|link:machine.md[Machine] |The link:machine.md[machine] that is
associated with the link:alerts.md[alert].

|link:get-alert-related-user-info.md[Get related users]
|link:user.md[User] |The link:user.md[user] that is associated with the
link:alerts.md[alert].
|===

=== Properties

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Property |Type |Description
|id |String |Alert ID.

|title |String |Alert title.

|description |String |Alert description.

|alertCreationTime |Nullable DateTimeOffset |The date and time (in UTC)
the alert was created.

|lastEventTime |Nullable DateTimeOffset |The last occurrence of the
event that triggered the alert on the same device.

|firstEventTime |Nullable DateTimeOffset |The first occurrence of the
event that triggered the alert on that device.

|lastUpdateTime |Nullable DateTimeOffset |The date and time (in UTC) the
alert was last updated.

|resolvedTime |Nullable DateTimeOffset |The date and time in which the
status of the alert was changed to `Resolved'.

|incidentId |Nullable Long |The link:view-incidents-queue.md[Incident]
ID of the Alert.

|investigationId |Nullable Long |The
link:automated-investigations.md[Investigation] ID related to the Alert.

|investigationState |Nullable Enum |The current state of the
link:automated-investigations.md[Investigation]. Possible values are:
`Unknown', `Terminated', `SuccessfullyRemediated', `Benign', `Failed',
`PartiallyRemediated', `Running', `PendingApproval', `PendingResource',
`PartiallyInvestigated', `TerminatedByUser', `TerminatedBySystem',
`Queued', `InnerFailure', `PreexistingAlert', `UnsupportedOs',
`UnsupportedAlertType', `SuppressedAlert'.

|assignedTo |String |Owner of the alert.

|rbacGroupName |String |RBAC device group name.

|mitreTechniques |String |Mitre Enterprise technique ID.

|relatedUser |String |Details of user related to a specific alert.

|severity |Enum |Severity of the alert. Possible values are:
`UnSpecified', `Informational', `Low', `Medium' and `High'.

|status |Enum |Specifies the current status of the alert. Possible
values are: `Unknown', `New', `InProgress' and `Resolved'.

|classification |Nullable Enum |Specification of the alert. Possible
values are: `TruePositive`, `Informational, expected activity`, and
`FalsePositive`.

|determination |Nullable Enum |Specifies the determination of the alert.

|category |String |Category of the alert.

|detectionSource |String |Detection source.

|threatFamilyName |String |Threat family.

|threatName |String |Threat name.

|machineId |String |ID of a link:machine.md[machine] entity that is
associated with the alert.

|computerDnsName |String |link:machine.md[machine] fully qualified name.

|aadTenantId |String |The Azure Active Directory ID.

|detectorId |String |The ID of the detector that triggered the alert.

|comments |List of Alert comments |Alert Comment object contains:
comment string, createdBy string, and createTime date time.

|Evidence |List of Alert evidence |Evidence related to the alert. See
example below.
|===

____
[!NOTE] Around August 29, 2022, previously supported alert determination
values (`Apt' and `SecurityPersonnel') will be deprecated and no longer
available via the API.
____

==== Response example for getting single alert:

[source,http]
----
GET https://api.securitycenter.microsoft.com/api/alerts/da637472900382838869_1364969609
----

[source,json]
----
{
    "id": "da637472900382838869_1364969609",
    "incidentId": 1126093,
    "investigationId": null,
    "assignedTo": null,
    "severity": "Low",
    "status": "New",
    "classification": null,
    "determination": null,
    "investigationState": "Queued",
    "detectionSource": "WindowsDefenderAtp",
    "detectorId": "17e10bbc-3a68-474a-8aad-faef14d43952",
    "category": "Execution",
    "threatFamilyName": null,
    "title": "Low-reputation arbitrary code executed by signed executable",
    "description": "Binaries signed by Microsoft can be used to run low-reputation arbitrary code. This technique hides the execution of malicious code within a trusted process. As a result, the trusted process might exhibit suspicious behaviors, such as opening a listening port or connecting to a command-and-control (C&C) server.",
    "alertCreationTime": "2021-01-26T20:33:57.7220239Z",
    "firstEventTime": "2021-01-26T20:31:32.9562661Z",
    "lastEventTime": "2021-01-26T20:31:33.0577322Z",
    "lastUpdateTime": "2021-01-26T20:33:59.2Z",
    "resolvedTime": null,
    "machineId": "111e6dd8c833c8a052ea231ec1b19adaf497b625",
    "computerDnsName": "temp123.middleeast.corp.microsoft.com",
    "rbacGroupName": "A",
    "aadTenantId": "a839b112-1253-6432-9bf6-94542403f21c",
    "threatName": null,
    "mitreTechniques": [
        "T1064",
        "T1085",
        "T1220"
    ],
    "relatedUser": {
        "userName": "temp123",
        "domainName": "DOMAIN"
    },
    "comments": [
        {
            "comment": "test comment for docs",
            "createdBy": "secop123@contoso.com",
            "createdTime": "2021-01-26T01:00:37.8404534Z"
        }
    ],
    "evidence": [
        {
            "entityType": "User",
            "evidenceCreationTime": "2021-01-26T20:33:58.42Z",
            "sha1": null,
            "sha256": null,
            "fileName": null,
            "filePath": null,
            "processId": null,
            "processCommandLine": null,
            "processCreationTime": null,
            "parentProcessId": null,
            "parentProcessCreationTime": null,
            "parentProcessFileName": null,
            "parentProcessFilePath": null,
            "ipAddress": null,
            "url": null,
            "registryKey": null,
            "registryHive": null,
            "registryValueType": null,
            "registryValue": null,
            "accountName": "name",
            "domainName": "DOMAIN",
            "userSid": "S-1-5-21-11111607-1111760036-109187956-75141",
            "aadUserId": "11118379-2a59-1111-ac3c-a51eb4a3c627",
            "userPrincipalName": "temp123@microsoft.com",
            "detectionStatus": null
        },
        {
            "entityType": "Process",
            "evidenceCreationTime": "2021-01-26T20:33:58.6133333Z",
            "sha1": "ff836cfb1af40252bd2a2ea843032e99a5b262ed",
            "sha256": "a4752c71d81afd3d5865d24ddb11a6b0c615062fcc448d24050c2172d2cbccd6",
            "fileName": "rundll32.exe",
            "filePath": "C:\\Windows\\SysWOW64",
            "processId": 3276,
            "processCommandLine": "rundll32.exe  c:\\temp\\suspicious.dll,RepeatAfterMe",
            "processCreationTime": "2021-01-26T20:31:32.9581596Z",
            "parentProcessId": 8420,
            "parentProcessCreationTime": "2021-01-26T20:31:32.9004163Z",
            "parentProcessFileName": "rundll32.exe",
            "parentProcessFilePath": "C:\\Windows\\System32",
            "ipAddress": null,
            "url": null,
            "registryKey": null,
            "registryHive": null,
            "registryValueType": null,
            "registryValue": null,
            "accountName": null,
            "domainName": null,
            "userSid": null,
            "aadUserId": null,
            "userPrincipalName": null,
            "detectionStatus": "Detected"
        },
        {
            "entityType": "File",
            "evidenceCreationTime": "2021-01-26T20:33:58.42Z",
            "sha1": "8563f95b2f8a284fc99da44500cd51a77c1ff36c",
            "sha256": "dc0ade0c95d6db98882bc8fa6707e64353cd6f7767ff48d6a81a6c2aef21c608",
            "fileName": "suspicious.dll",
            "filePath": "c:\\temp",
            "processId": null,
            "processCommandLine": null,
            "processCreationTime": null,
            "parentProcessId": null,
            "parentProcessCreationTime": null,
            "parentProcessFileName": null,
            "parentProcessFilePath": null,
            "ipAddress": null,
            "url": null,
            "registryKey": null,
            "registryHive": null,
            "registryValueType": null,
            "registryValue": null,
            "accountName": null,
            "domainName": null,
            "userSid": null,
            "aadUserId": null,
            "userPrincipalName": null,
            "detectionStatus": "Detected"
        }
    ]
}
----

=== Related articles

link:/graph/api/resources/security-api-overview[Use the Microsoft Graph
security API - Microsoft Graph beta | Microsoft Learn]
