= Access the Microsoft Defender for Endpoint APIs
:audience: ITPro
:author: mjcaparas
:description: Learn how you can use APIs to automate workflows and innovate based on Microsoft Defender for Endpoint capabilities
:keywords: apis, api, wdatp, open api, microsoft defender for endpoint api, microsoft defender atp, public api, supported apis, alerts, device, user, domain, ip, file, advanced hunting, query
:manager: dansimp
:ms.author: macapara
:ms.collection: M365-security-compliance
:ms.custom: api
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.reviewer:
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: conceptual
:search.appverid: met150

== Access the Microsoft Defender for Endpoint APIs

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]
* link:../defender-business/index.yml[Microsoft Defender for Business]

____
[!IMPORTANT] Advanced hunting capabilities are not included in Defender for Business.
See link:../defender-business/compare-mdb-m365-plans.md#compare-microsoft-defender-for-business-to-microsoft-defender-for-endpoint-plans-1-and-2[Compare Microsoft Defender for Business to Microsoft Defender for Endpoint Plans 1 and 2].
____

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign up for a free trial.]
____

Defender for Endpoint exposes much of its data and actions through a set of programmatic APIs.
Those APIs will enable you to automate workflows and innovate based on Defender for Endpoint capabilities.
The API access requires OAuth2.0 authentication.
For more information, see link:/azure/active-directory/develop/active-directory-v2-protocols-oauth-code[OAuth 2.0 Authorization Code Flow].

Watch this video for a quick overview of Defender for Endpoint's APIs.

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/RE4d73M]
____

In general, you'll need to take the following steps to use the APIs:

* Create an link:/microsoft-365/security/defender-endpoint/exposed-apis-create-app-nativeapp[AAD application]
* Get an access token using this application
* Use the token to access Defender for Endpoint API

You can access Defender for Endpoint API with *Application Context* or *User Context*.

* *Application Context: (Recommended)*
+
Used by apps that run without a signed-in user present.
for example, apps that run as background services or daemons.
+
Steps that need to be taken to access Defender for Endpoint API with application context:

 .. Create an AAD Web-Application.
 .. Assign the desired permission to the application, for example, 'Read Alerts', 'Isolate Machines'.
 .. Create a key for this Application.
 .. Get token using the application with its key.
 .. Use the token to access the Microsoft Defender for Endpoint API
+
For more information, see xref:exposed-apis-create-app-webapp.adoc[Get access with application context].

* *User Context:*
+
Used to perform actions in the API on behalf of a user.
+
Steps to take to access Defender for Endpoint API with user context:

 .. Create AAD Native-Application.
 .. Assign the desired permission to the application, e.g 'Read Alerts', 'Isolate Machines' etc.
 .. Get token using the application with user credentials.
 .. Use the token to access the Microsoft Defender for Endpoint API
+
For more information, see xref:exposed-apis-create-app-nativeapp.adoc[Get access with user context].

=== Related topics

* xref:exposed-apis-list.adoc[Microsoft Defender for Endpoint APIs]
* xref:exposed-apis-create-app-webapp.adoc[Access Microsoft Defender for Endpoint with application context]
* xref:exposed-apis-create-app-nativeapp.adoc[Access Microsoft Defender for Endpoint with user context]
