= Use attack surface reduction rules to prevent malware infection
:audience: ITPro
:author: jweston-1
:description: Attack surface reduction rules can help prevent exploits from using apps and scripts to infect devices with malware.
:keywords: Attack surface reduction rules, asr, hips, host intrusion prevention system, protection rules, anti-exploit, antiexploit, exploit, infection prevention, Microsoft Defender for Endpoint
:manager: dansimp
:ms.author: v-jweston
:ms.collection: ["m365initiative-m365-defender", "M365-security-compliance"]
:ms.custom: ["asr", "admindeeplinkDEFENDER"]
:ms.localizationpriority: medium
:ms.mktglfcycl: manage
:ms.pagetype: security
:ms.reviewer: oogunrinde, sugamar
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Attack surface reduction rules overview

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]
* Microsoft Defender Antivirus

*Platforms*

* Windows

=== Why attack surface reduction rules are important

Your organization's attack surface includes all the places where an attacker could compromise your organization's devices or networks.
Reducing your attack surface means protecting your organization's devices and network, which leaves attackers with fewer ways to perform attacks.
Configuring attack surface reduction rules in Microsoft Defender for Endpoint can help!

Attack surface reduction rules target certain software behaviors, such as:

* Launching executable files and scripts that attempt to download or run files
* Running obfuscated or otherwise suspicious scripts
* Performing behaviors that apps don't usually initiate during normal day-to-day work

Such software behaviors are sometimes seen in legitimate applications.
However, these behaviors are often considered risky because they are commonly abused by attackers through malware.
Attack surface reduction rules can constrain software-based risky behaviors and help keep your organization safe.

For a sequential, end-to-end process of how to manage ASR rules, see:

* xref:attack-surface-reduction-rules-deployment.adoc[Attack surface reduction (ASR) rules deployment overview]
* xref:attack-surface-reduction-rules-deployment-plan.adoc[Plan attack surface reduction (ASR) rules deployment]
* xref:attack-surface-reduction-rules-deployment-test.adoc[Test attack surface reduction (ASR) rules]
* xref:attack-surface-reduction-rules-deployment-implement.adoc[Enable attack surface reduction (ASR) rules]
* xref:attack-surface-reduction-rules-deployment-operationalize.adoc[Operationalize attack surface reduction (ASR) rules]

=== Assess rule impact before deployment

You can assess how an attack surface reduction rule might affect your network by opening the security recommendation for that rule in link:/windows/security/threat-protection/[Microsoft Defender Vulnerability Management].

:::image type="content" source="images/asrrecommendation.png" alt-text="The ASR recommendation" lightbox="images/asrrecommendation.png":::

In the recommendation details pane, check for user impact to determine what percentage of your devices can accept a new policy enabling the rule in blocking mode without adversely affecting productivity.

See link:enable-attack-surface-reduction.md#requirements[Requirements] in the "Enable attack surface reduction rules" article for information about supported operating systems and additional requirement information.

=== Audit mode for evaluation

Use xref:audit-windows-defender.adoc[audit mode] to evaluate how attack surface reduction rules would affect your organization if enabled.
Run all rules in audit mode first so you can understand how they affect your line-of-business applications.
Many line-of-business applications are written with limited security concerns, and they might perform tasks in ways that seem similar to malware.
By monitoring audit data and link:enable-attack-surface-reduction.md#exclude-files-and-folders-from-asr-rules[adding exclusions] for necessary applications, you can deploy attack surface reduction rules without reducing productivity.

=== Warn mode for users

(*NEW*!) Prior to warn mode capabilities, attack surface reduction rules that are enabled could be set to either audit mode or block mode.
With the new warn mode, whenever content is blocked by an attack surface reduction rule, users see a dialog box that indicates the content is blocked.
The dialog box also offers the user an option to unblock the content.
The user can then retry their action, and the operation completes.
When a user unblocks content, the content remains unblocked for 24 hours, and then blocking resumes.

Warn mode helps your organization have attack surface reduction rules in place without preventing users from accessing the content they need to perform their tasks.

==== Requirements for warn mode to work

Warn mode is supported on devices running the following versions of Windows:

* link:/windows/whats-new/whats-new-windows-10-version-1809[Windows 10, version 1809] or later
* Windows 11
* link:/windows-server/get-started/whats-new-in-windows-server-1809[Windows Server, version 1809] or later

Microsoft Defender Antivirus must be running with real-time protection in link:/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility#functionality-and-features-available-in-each-state[Active mode].

Also, make sure link:/windows/security/threat-protection/microsoft-defender-antivirus/manage-updates-baselines-microsoft-defender-antivirus#monthly-platform-and-engine-versions[Microsoft Defender Antivirus and antimalware updates] are installed.

* Minimum platform release requirement: `4.18.2008.9`
* Minimum engine release requirement: `1.1.17400.5`

For more information and to get your updates, see https://support.microsoft.com/help/4052623/update-for-microsoft-defender-antimalware-platform[Update for Microsoft Defender antimalware platform].

==== Cases where warn mode is not supported

Warn mode isn't supported for three attack surface reduction rules when you configure them in Microsoft Endpoint Manager.
(If you use Group Policy to configure your attack surface reduction rules, warn mode is supported.) The three rules that do not support warn mode when you configure them in Microsoft Endpoint Manager are as follows:

* link:attack-surface-reduction-rules-reference.md#block-javascript-or-vbscript-from-launching-downloaded-executable-content[Block JavaScript or VBScript from launching downloaded executable content] (GUID `d3e037e1-3eb8-44c8-a917-57927947596d`)
* link:attack-surface-reduction-rules-reference.md#block-persistence-through-wmi-event-subscription[Block persistence through WMI event subscription] (GUID `e6db77e5-3df2-4cf1-b95a-636979351e5b`)
* link:attack-surface-reduction-rules-reference.md#use-advanced-protection-against-ransomware[Use advanced protection against ransomware] (GUID `c1db55ab-c21a-4637-bb3f-a12568109d35`)

Also, warn mode isn't supported on devices running older versions of Windows.
In those cases, attack surface reduction rules that are configured to run in warn mode will run in block mode.

=== Notifications and alerts

Whenever an attack surface reduction rule is triggered, a notification is displayed on the device.
You can link:attack-surface-reduction-rules-deployment-implement.md#customize-attack-surface-reduction-rules[customize the notification] with your company details and contact information.

Also, when certain attack surface reduction rules are triggered, alerts are generated.

Notifications and any alerts that are generated can be viewed in the https://go.microsoft.com/fwlink/p/?linkid=2077139[Microsoft 365 Defender portal].

For specific details about notification and alert functionality, see: link:attack-surface-reduction-rules-reference.md#per-asr-rule-alert-and-notification-details[Per rule alert and notification details], in the article *Attack surface reduction rules reference*.

=== Advanced hunting and attack surface reduction events

You can use advanced hunting to view attack surface reduction events.
To streamline the volume of incoming data, only unique processes for each hour are viewable with advanced hunting.
The time of an attack surface reduction event is the first time that event is seen within the hour.

For example, suppose that an attack surface reduction event occurs on 10 devices during the 2:00 PM hour.
Suppose that the first event occurred at 2:15, and the last at 2:45.
With advanced hunting, you'll see one instance of that event (even though it actually occurred on 10 devices), and its timestamp will be 2:15 PM.

For more information about advanced hunting, see xref:advanced-hunting-overview.adoc[Proactively hunt for threats with advanced hunting].

=== Attack surface reduction features across Windows versions

You can set attack surface reduction rules for devices that are running any of the following editions and versions of Windows:

* Windows 10 Pro, link:/windows/whats-new/whats-new-windows-10-version-1709[version 1709] or later
* Windows 10 Enterprise, link:/windows/whats-new/whats-new-windows-10-version-1709[version 1709] or later
* Windows Server, link:/windows-server/get-started/whats-new-in-windows-server-1803[version 1803 (Semi-Annual Channel)] or later
* link:/windows-server/get-started-19/whats-new-19[Windows Server 2019]
* link:/windows-server/get-started/whats-new-in-windows-server-2016[Windows Server 2016]
* link:/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/hh801901(v=ws.11)[Windows Server 2012 R2]
+
____
[!NOTE] Windows Server 2016 and Windows Server 2012 R2 will need to be onboarded using the instructions in link:configure-server-endpoints.md#windows-server-2012-r2-and-windows-server-2016[Onboard Windows servers] for this feature to work.
____

Although attack surface reduction rules don't require a link:/windows/deployment/deploy-enterprise-licenses[Windows E5 license], if you have Windows E5, you get advanced management capabilities.
The advanced capabilities - available only in Windows E5 - include:

* The monitoring, analytics, and workflows available in xref:microsoft-defender-endpoint.adoc[Defender for Endpoint]
* The reporting and configuration capabilities in link:/microsoft-365/security/defender/overview-security-center[Microsoft 365 Defender].

These advanced capabilities aren't available with a Windows Professional or Windows E3 license.
However, if you do have those licenses, you can use Event Viewer and Microsoft Defender Antivirus logs to review your attack surface reduction rule events.

=== Review attack surface reduction events in the Microsoft 365 Defender portal

Defender for Endpoint provides detailed reporting for events and blocks as part of alert investigation scenarios.

You can query Defender for Endpoint data in xref:microsoft-defender-endpoint.adoc[Microsoft 365 Defender] by using link:/microsoft-365/security/defender/advanced-hunting-query-language[advanced hunting].

Here is an example query:

[,kusto]
----
DeviceEvents
| where ActionType startswith 'Asr'
----

=== Review attack surface reduction events in Windows Event Viewer

You can review the Windows event log to view events generated by attack surface reduction rules:

. Download the https://aka.ms/mp7z2w[Evaluation Package] and extract the file _cfa-events.xml_ to an easily accessible location on the device.
. Enter the words, _Event Viewer_, into the Start menu to open the Windows Event Viewer.
. Under *Actions*, select *Import custom view...*.
. Select the file _cfa-events.xml_ from where it was extracted.
Alternatively, xref:event-views.adoc[copy the XML directly].
. Select *OK*.

You can create a custom view that filters events to only show the following events, all of which are related to controlled folder access:

|===
| Event ID | Description

| 5007
| Event when settings are changed

| 1121
| Event when rule fires in Block-mode

| 1122
| Event when rule fires in Audit-mode
|===

The "engine version" listed for attack surface reduction events in the event log, is generated by Defender for Endpoint, not by the operating system.
Defender for Endpoint is integrated with Windows 10 and Windows 11, so this feature works on all devices with Windows 10 or Windows 11 installed.

=== See also

* xref:attack-surface-reduction-rules-deployment.adoc[Attack surface reduction (ASR) rules deployment overview]
* xref:attack-surface-reduction-rules-deployment-plan.adoc[Plan attack surface reduction (ASR) rules deployment]
* xref:attack-surface-reduction-rules-deployment-test.adoc[Test attack surface reduction (ASR) rules]
* xref:attack-surface-reduction-rules-deployment-implement.adoc[Enable attack surface reduction (ASR) rules]
* xref:attack-surface-reduction-rules-deployment-operationalize.adoc[Operationalize attack surface reduction (ASR) rules]
* xref:attack-surface-reduction-rules-report.adoc[Attack surface reduction (ASR) rules report]

____
[!TIP] If you're looking for Antivirus related information for other platforms, see:

* xref:mac-preferences.adoc[Set preferences for Microsoft Defender for Endpoint on macOS]
* xref:microsoft-defender-endpoint-mac.adoc[Microsoft Defender for Endpoint on Mac]
* link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS Antivirus policy settings for Microsoft Defender Antivirus for Intune]
* xref:linux-preferences.adoc[Set preferences for Microsoft Defender for Endpoint on Linux]
* xref:microsoft-defender-endpoint-linux.adoc[Microsoft Defender for Endpoint on Linux]
* xref:android-configure.adoc[Configure Defender for Endpoint on Android features]
* xref:ios-configure-features.adoc[Configure Microsoft Defender for Endpoint on iOS features]
____
