= 
dansimp
:keywords: action, center, autoir, automated, investigation, response,
remediation

== Visit the Action center to see remediation actions

During and after an automated investigation, remediation actions for
threat detections are identified. Depending on the particular threat and
how link:configure-automated-investigations-remediation.md[automated
investigation and remediation capabilities are configured] for your
organization, some remediation actions are taken automatically, and
others require approval. If you’re part of your organization’s security
operations team, you can view pending and completed
link:manage-auto-investigation.md#remediation-actions[remediation
actions] in the *Action center*.

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]
- https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 2] -
link:../defender-business/mdb-overview.md[Microsoft Defender for
Business]

=== The unified Action center

Recently, the Action center was updated. You now have a unified Action
center experience. To access your Action center, go to
https://security.microsoft.com/action-center and sign in.

:::image type=``content''
source=``images/mde-action-center-unified.png'' alt-text=``The Action
center page in the Microsoft 365 Defender portal''
lightbox=``images/mde-action-center-unified.png'':::

==== What’s changed?

The following table compares the new, unified Action center to the
previous Action center.

[width="100%",cols="50%,50%",options="header",]
|===
|The new, unified Action center |The previous Action center
|Lists pending and completed actions for devices and email in one
location (link:microsoft-defender-endpoint.md[Microsoft Defender for
Endpoint] plus
link:/microsoft-365/security/office-365-security/defender-for-office-365[Microsoft
Defender for Office 365]) |Lists pending and completed actions for
devices (link:microsoft-defender-endpoint.md[Microsoft Defender for
Endpoint] only)

|Is located at:https://security.microsoft.com/action-center |Is located
at:https://securitycenter.windows.com/action-center

|In the Microsoft 365 Defender portal, choose *Action center*. |In the
Microsoft 365 Defender portal, choose *Automated investigations* >
*Action center*.
|===

The unified Action center brings together remediation actions across
Defender for Endpoint and Defender for Office 365. It defines a common
language for all remediation actions, and provides a unified
investigation experience.

You can use the unified Action center if you have appropriate
permissions and one or more of the following subscriptions:

* link:/microsoft-365/security/mtp/microsoft-threat-protection[Microsoft
365 Defender]
* link:microsoft-defender-endpoint.md[Defender for Endpoint]
* link:/microsoft-365/security/office-365-security/defender-for-office-365[Defender
for Office 365]
* link:../defender-business/mdb-overview.md[Defender for Business]

=== Using the Action center

To get to the unified Action center in the improved Microsoft 365
Defender portal:

[arabic]
. Go to the Microsoft 365 Defender portal and sign in.
. In the navigation pane, select *Action center*.
. Use the *Pending actions* and *History* tabs. The following table
summarizes what you’ll see on each tab:
+
[width="100%",cols="50%,50%",options="header",]
|===
|Tab |Description
|*Pending* |Displays a list of actions that require attention. You can
approve or reject actions one at a time, or select multiple actions if
they have the same type of action (such as *Quarantine file*).

|*History* |Serves as an audit log for actions that were taken, such as:
|===
. To customize, sort, filter, and export data in the Action center, take
one or more of the following steps:
+
:::image type=``content''
source=``images/new-action-center-columnsfilters.png'' alt-text=``The
Action center with Columns and filters''
lightbox=``images/new-action-center-columnsfilters.png'':::
* Select a column heading to sort items in ascending or descending
order.
* Use the time period filter to view data for the past day, week, 30
days, or 6 months.
* Choose the columns that you want to view.
* Specify how many items to include on each page of data.
* Use filters to view just the items you want to see.
* Select *Export* to export results to a .csv file.

=== Next steps

* link:manage-auto-investigation.md[View and approve remediation
actions]
* https://aka.ms/MDATP-IR-Interactive-Guide[See the interactive guide:
Investigate and remediate threats with Microsoft Defender for Endpoint]

=== See also

* link:defender-endpoint-false-positives-negatives.md[Address false
positives/negatives in Microsoft Defender for Endpoint]
* link:../defender-business/compare-mdb-m365-plans.md[Compare security
features in Microsoft 365 plans for small and medium-sized businesses]
