= Use automated investigations to investigate and remediate threats
:audience: ITPro
:author: dansimp
:description: Understand the automated investigation flow in Microsoft Defender for Endpoint.
:keywords: automated, investigation, detection, Microsoft Defender for Endpoint
:manager: dansimp
:ms.author: dansimp
:ms.collection: ["m365-security-compliance", "m365initiative-defender-endpoint"]
:ms.custom: AIR
:ms.date: 08/31/2022
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.reviewer: ramarom, evaldm, isco, mabraitm, chriggs
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: how-to
:search.appverid: met150

== Overview of automated investigations

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* xref:../defender-business/mdb-overview.adoc[Microsoft Defender for Business]

*Platforms*

* Windows

Want to see how it works?
Watch the following video:

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/RE4bOeh]
____

The technology in automated investigation uses various inspection algorithms and is based on processes that are used by security analysts.
AIR capabilities are designed to examine alerts and take immediate action to resolve breaches.
AIR capabilities significantly reduce alert volume, allowing security operations to focus on more sophisticated threats and other high-value initiatives.
All remediation actions, whether pending or completed, are tracked in the xref:auto-investigation-action-center.adoc[Action center].
In the Action center, pending actions are approved (or rejected), and completed actions can be undone if needed.

This article provides an overview of AIR and includes links to next steps and additional resources.

____
[!TIP] Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-automated-investigations-abovefoldlink[Sign up for a free trial.]
____

=== How the automated investigation starts

An automated investigation can start when an alert is triggered or when a security operator initiates the investigation.

|===
| Situation | What happens

| An alert is triggered
| In general, an automated investigation starts when an xref:review-alerts.adoc[alert] is triggered, and an xref:view-incidents-queue.adoc[incident] is created.
For example, suppose a malicious file resides on a device.
When that file is detected, an alert is triggered, and incident is created.
An automated investigation process begins on the device.
As other alerts are generated because of the same file on other devices, they are added to the associated incident and to the automated investigation.

| An investigation is started manually
| An automated investigation can be started manually by your security operations team.
For example, suppose a security operator is reviewing a list of devices and notices that a device has a high risk level.
The security operator can select the device in the list to open its flyout, and then select *Initiate Automated Investigation*.
|===

=== How an automated investigation expands its scope

While an investigation is running, any other alerts generated from the device are added to an ongoing automated investigation until that investigation is completed.
In addition, if the same threat is seen on other devices, those devices are added to the investigation.

If an incriminated entity is seen in another device, the automated investigation process expands its scope to include that device, and a general security playbook starts on that device.
If 10 or more devices are found during this expansion process from the same entity, then that expansion action requires an approval, and is visible on the *Pending actions* tab.

=== How threats are remediated

As alerts are triggered, and an automated investigation runs, a verdict is generated for each piece of evidence investigated.
Verdicts can be:

* _Malicious_;
* _Suspicious_;
or
* _No threats found_.

As verdicts are reached, automated investigations can result in one or more remediation actions.
Examples of remediation actions include sending a file to quarantine, stopping a service, removing a scheduled task, and more.
To learn more, see link:manage-auto-investigation.md#remediation-actions[Remediation actions].

Depending on the xref:automation-levels.adoc[level of automation] set for your organization, as well as other security settings, remediation actions can occur automatically or only upon approval by your security operations team.
Additional security settings that can affect automatic remediation include link:/windows/security/threat-protection/microsoft-defender-antivirus/detect-block-potentially-unwanted-apps-microsoft-defender-antivirus[protection from potentially unwanted applications] (PUA).

All remediation actions, whether pending or completed, are tracked in the xref:auto-investigation-action-center.adoc[Action center].
If necessary, your security operations team can undo a remediation action.
To learn more, see link:/microsoft-365/security/defender-endpoint/manage-auto-investigation[Review and approve remediation actions following an automated investigation].

____
[!TIP] Check out the new, unified investigation page in the Microsoft 365 Defender portal.
To learn more, see link:/microsoft-365/security/defender/m365d-autoir-results#new-unified-investigation-page[Unified investigation page].
____

=== Requirements for AIR

Your subscription must include xref:microsoft-defender-endpoint.adoc[Defender for Endpoint] or xref:../defender-business/mdb-overview.adoc[Defender for Business].

____
[!NOTE] Automated investigation and response requires Microsoft Defender Antivirus for running in passive mode or active mode.
If Microsoft Defender Antivirus is disabled or uninstalled, Automated Investigation and Response will not function correctly.
____

Currently, AIR only supports the following OS versions:

* Windows Server 2012 R2 (Preview)
* Windows Server 2016 (Preview)
* Windows Server 2019
* Windows Server 2022
* Windows 10, version 1709 (OS Build 16299.1085 with https://support.microsoft.com/help/4493441/windows-10-update-kb4493441[KB4493441]) or later
* Windows 10, version 1803 (OS Build 17134.704 with https://support.microsoft.com/help/4493464/windows-10-update-kb4493464[KB4493464]) or later
* Windows 10, version link:/windows/release-information/status-windows-10-1809-and-windows-server-2019[1803] or later
* Windows 11

____
[!NOTE] Automated investigation and response on Windows Server 2012 R2 and Windows Server 2016 requires the link:/microsoft-365/security/defender-endpoint/configure-server-endpoints#new-windows-server-2012-r2-and-2016-functionality-in-the-modern-unified-solution[Unified Agent] to be installed.
____

=== Next steps

* xref:automation-levels.adoc[Learn more about automation levels]
* https://aka.ms/MDATP-IR-Interactive-Guide[See the interactive guide: Investigate and remediate threats with Microsoft Defender for Endpoint]
* xref:configure-automated-investigations-remediation.adoc[Configure automated investigation and remediation capabilities in Microsoft Defender for Endpoint]

=== See also

* link:/windows/security/threat-protection/microsoft-defender-antivirus/detect-block-potentially-unwanted-apps-microsoft-defender-antivirus[PUA protection]
* link:/microsoft-365/security/office-365-security/office-365-air[Automated investigation and response in Microsoft Defender for Office 365]
* link:/microsoft-365/security/defender/m365d-autoir[Automated investigation and response in Microsoft 365 Defender]
