= Use basic permissions to access Microsoft Defender Security Center
:audience: ITPro
:author: mjcaparas
:description: Learn how to use basic permissions to access the Microsoft Defender for Endpoint portal.
:keywords: assign user roles, assign read and write access, assign read only access, user, user roles, roles
:manager: dansimp
:ms.author: macapara
:ms.collection: M365-security-compliance
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Use basic permissions to access the portal

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* Azure Active Directory
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-basicaccess-abovefoldlink[Sign up for a free trial.]
____

Refer to the instructions below to use basic permissions management.

You can use either of the following solutions:

* Azure PowerShell
* Azure portal

For granular control over permissions, xref:rbac.adoc[switch to role-based access control].

=== Assign user access using Azure PowerShell

You can assign users with one of the following levels of permissions:

* Full access (Read and Write)
* Read-only access

==== Before you begin

* Install Azure PowerShell.
For more information, see, https://azure.microsoft.com/documentation/articles/powershell-install-configure/[How to install and configure Azure PowerShell].
+
____
[!NOTE] You need to run the PowerShell cmdlets in an elevated command-line.
____

* Connect to your Azure Active Directory.
For more information, see link:/powershell/module/msonline/connect-msolservice[Connect-MsolService].
 ** *Full access*: Users with full access can log in, view all system information and resolve alerts, submit files for deep analysis, and download the onboarding package.
Assigning full access rights requires adding the users to the "Security Administrator" or "Global Administrator" AAD built-in roles.
 ** *Read-only access*: Users with read-only access can log in, view all alerts, and related information.
+
They will not be able to change alert states, submit files for deep analysis or perform any state changing operations.
+
Assigning read-only access rights requires adding the users to the "Security Reader" Azure AD built-in role.

Use the following steps to assign security roles:

* For *read and write* access, assign users to the security administrator role by using the following command:
+
[,powershell]
----
Add-MsolRoleMember -RoleName "Security Administrator" -RoleMemberEmailAddress "secadmin@Contoso.onmicrosoft.com"
----

* For *read-only* access, assign users to the security reader role by using the following command:
+
[,powershell]
----
Add-MsolRoleMember -RoleName "Security Reader" -RoleMemberEmailAddress "reader@Contoso.onmicrosoft.com"
----

For more information, see link:/azure/active-directory/fundamentals/active-directory-groups-members-azure-portal[Add or remove group members using Azure Active Directory].

=== Assign user access using the Azure portal

For more information, see link:/azure/active-directory/fundamentals/active-directory-users-assign-role-azure-portal[Assign administrator and non-administrator roles to users with Azure Active Directory].

=== Related topic

* xref:rbac.adoc[Manage portal access using RBAC]
