= 
mjcaparas
:keywords: apis, graph api, supported apis, get, alert, information, id

== Batch update alerts

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Updates properties of a batch of existing link:alerts.md[Alerts].

Submission of *comment* is available with or without updating
properties.

Updatable properties are: `status`, `determination`, `classification`
and `assignedTo`.

=== Limitations

[arabic]
. You can update alerts that are available in the API. See
link:get-alerts.md[List Alerts] for more information.
. Rate limitations for this API are 10 calls per minute and 500 calls
per hour.

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Microsoft Defender for Endpoint APIs]

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Alert.ReadWrite.All |`Read and write all alerts'

|Delegated (work or school account) |Alert.ReadWrite |`Read and write
alerts'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to have at least the following role permission: `Alerts
investigation' (See link:user-roles.md[Create and manage roles] for more
information)
* The user needs to have access to the device associated with the alert,
based on device group settings (See link:machine-groups.md[Create and
manage device groups] for more information)

Device group creation is supported in Defender for Endpoint Plan 1 and
Plan 2.
____

=== HTTP request

[source,http]
----
POST /api/alerts/batchUpdate
----

=== Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|Content-Type |String |application/json. *Required*.
|===

=== Request body

In the request body, supply the IDs of the alerts to be updated and the
values of the relevant fields that you wish to update for these alerts.

Existing properties that are not included in the request body will
maintain their previous values or be recalculated based on changes to
other property values.

For best performance you shouldn’t include existing values that haven’t
changed.

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Property |Type |Description
|alertIds |List<String> |A list of the IDs of the alerts to be updated.
*Required*

|status |String |Specifies the updated status of the specified alerts.
The property values are: `New', `InProgress' and `Resolved'.

|assignedTo |String |Owner of the specified alerts

|classification |String |Specifies the specification of the specified
alerts. The property values are: `TruePositive`,
`Informational, expected activity`, and `FalsePositive`.

|determination |String |Specifies the determination of the specified
alerts.

|comment |String |Comment to be added to the specified alerts.
|===

____
[!NOTE] Around August 29, 2022, previously supported alert determination
values (`Apt' and `SecurityPersonnel') will be deprecated and no longer
available via the API.
____

=== Response

If successful, this method returns 200 OK, with an empty response body.

=== Example

==== Request

Here is an example of the request.

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/alerts/batchUpdate
----

[source,json]
----
{
    "alertIds": ["da637399794050273582_760707377", "da637399989469816469_51697947354"],
    "status": "Resolved",
    "assignedTo": "secop2@contoso.com",
    "classification": "FalsePositive",
    "determination": "Malware",
    "comment": "Resolve my alert and assign to secop2"
}
----
