= 
mjcaparas
:keywords: apis, graph api,

== Cancel machine action API

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
link:/microsoft-365/security/defender-endpoint/defender-endpoint[Microsoft
Defender for Endpoint] -
link:/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1[Microsoft
Defender for Endpoint Plan 1]

{empty}[!includelink:../../includes/prerelease.md[Prerelease
information]]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Cancel an already launched machine action that is not yet in final state
(completed, canceled, failed).

=== Limitations

[arabic]
. Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Get
started].

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Machine.CollectForensics Machine.Isolate
Machine.RestrictExecution Machine.Scan Machine.Offboard
Machine.StopAndQuarantine Machine.LiveResponse |Collect forensics
Isolate machineRestrict code execution Scan machine Offboard machine
Stop And Quarantine Run live response on a specific machine

|Delegated (work or school account) |Machine.CollectForensics
Machine.Isolate Machine.RestrictExecution Machine.Scan Machine.Offboard
Machine.StopAndQuarantineMachine.LiveResponse |Collect forensics Isolate
machine Restrict code execution Scan machineOffboard machine Stop And
Quarantine Run live response on a specific machine
|===

=== HTTP request

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/machineactions/<machineactionid>/cancel
----

=== Request headers

[cols=",,",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. Required.
|Content-Type |string |application/json. Required.
|===

=== Request body

[cols=",,",options="header",]
|===
|Parameter |Type |Description
|Comment |String |Comment to associate with the cancellation action.
|===

=== Response

If successful, this method returns 200, OK response code with a Machine
Action entity. If machine action entity with the specified id was not
found - 404 Not Found.

=== Example

==== Request

Here is an example of the request.

[source,http]
----
POST
https://api.securitycenter.microsoft.com/api/machineactions/988cc94e-7a8f-4b28-ab65-54970c5d5018/cancel
----

[source,json]
----
{
    "Comment": "Machine action was canceled by automation"
}
----

=== Related topic

* link:get-machineaction-object.md[Get machine action API]
