= 
denisebmsft
:keywords: behavioral blocking, rapid protection, client behavior,
Microsoft Defender for Endpoint

== Client behavioral blocking

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]
- Microsoft Defender Antivirus

*Platform* - Windows

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-assignaccess-abovefoldlink[Sign
up for a free trial.]
____

=== Overview

Client behavioral blocking is a component of
link:behavioral-blocking-containment.md[behavioral blocking and
containment capabilities] in Defender for Endpoint. As suspicious
behaviors are detected on devices (also referred to as clients or
endpoints), artifacts (such as files or applications) are blocked,
checked, and remediated automatically.

:::image type=``content''
source=``images/pre-execution-and-post-execution-detection-engines.png''
alt-text=``Cloud and client protection''
lightbox=``images/pre-execution-and-post-execution-detection-engines.png'':::

Antivirus protection works best when paired with cloud protection.

=== How client behavioral blocking works

link:microsoft-defender-antivirus-in-windows-10.md[Microsoft Defender
Antivirus] can detect suspicious behavior, malicious code, fileless and
in-memory attacks, and more on a device. When suspicious behaviors are
detected, Microsoft Defender Antivirus monitors and sends those
suspicious behaviors and their process trees to the cloud protection
service. Machine learning differentiates between malicious applications
and good behaviors within milliseconds, and classifies each artifact. In
almost real time, as soon as an artifact is found to be malicious, it’s
blocked on the device.

Whenever a suspicious behavior is detected, an
link:alerts-queue.md[alert] is generated and is visible while the attack
was detected and stopped; alerts, such as an ``initial access alert,''
are triggered and appear in the
link:/microsoft-365/security/defender/microsoft-365-defender[Microsoft
365 Defender portal] (formerly Microsoft 365 Defender).

Client behavioral blocking is effective because it not only helps
prevent an attack from starting, it can help stop an attack that has
begun executing. And, with link:feedback-loop-blocking.md[feedback-loop
blocking] (another capability of behavioral blocking and containment),
attacks are prevented on other devices in your organization.

=== Behavior-based detections

Behavior-based detections are named according to the
https://attack.mitre.org/matrices/enterprise[MITRE ATT&CK Matrix for
Enterprise]. The naming convention helps identify the attack stage where
the malicious behavior was observed:

[cols=",",options="header",]
|===
|Tactic |Detection threat name
|Initial Access |`Behavior:Win32/InitialAccess.*!ml`
|Execution |`Behavior:Win32/Execution.*!ml`
|Persistence |`Behavior:Win32/Persistence.*!ml`
|Privilege Escalation |`Behavior:Win32/PrivilegeEscalation.*!ml`
|Defense Evasion |`Behavior:Win32/DefenseEvasion.*!ml`
|Credential Access |`Behavior:Win32/CredentialAccess.*!ml`
|Discovery |`Behavior:Win32/Discovery.*!ml`
|Lateral Movement |`Behavior:Win32/LateralMovement.*!ml`
|Collection |`Behavior:Win32/Collection.*!ml`
|Command and Control |`Behavior:Win32/CommandAndControl.*!ml`
|Exfiltration |`Behavior:Win32/Exfiltration.*!ml`
|Impact |`Behavior:Win32/Impact.*!ml`
|Uncategorized |`Behavior:Win32/Generic.*!ml`
|===

____
[!TIP] To learn more about specific threats, see
*https://www.microsoft.com/wdsi/threats[recent global threat activity]*.
____

=== Configuring client behavioral blocking

If your organization is using Defender for Endpoint, client behavioral
blocking is enabled by default. However, to benefit from all Defender
for Endpoint capabilities, including
link:behavioral-blocking-containment.md[behavioral blocking and
containment], make sure the following features and capabilities of
Defender for Endpoint are enabled and configured:

* link:configure-machines-security-baseline.md[Defender for Endpoint
baselines]
* link:onboard-configure.md[Devices onboarded to Defender for Endpoint]
* link:edr-in-block-mode.md[EDR in block mode]
* link:attack-surface-reduction.md[Attack surface reduction]
* link:configure-microsoft-defender-antivirus-features.md[Next-generation
protection] (antivirus, antimalware, and other threat protection
capabilities)

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____
