= 
mjcaparas
:keywords: apis, graph api, supported apis, collect investigation
package

== Collect investigation package API

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Collect investigation package from a device.

=== Limitations

[arabic]
. Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.

____
{empty}[!IMPORTANT]

* These response actions are only available for devices on Windows 10,
version 1703 or later, and on Windows 11.
____

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Defender for Endpoint APIs]

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Machine.CollectForensics |`Collect forensics'

|Delegated (work or school account) |Machine.CollectForensics |`Collect
forensics'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to have at least the following role permission: `Alerts
Investigation' (See link:user-roles.md[Create and manage roles] for more
information)
* The user needs to have access to the device, based on device group
settings (See link:machine-groups.md[Create and manage device groups]
for more information)

Device group creation is supported in Defender for Endpoint Plan 1 and
Plan 2.
____

=== HTTP request

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/machines/{id}/collectInvestigationPackage
----

=== Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|Content-Type |string |application/json. *Required*.
|===

=== Request body

In the request body, supply a JSON object with the following parameters:

[cols="<,<,<",options="header",]
|===
|Parameter |Type |Description
|Comment |String |Comment to associate with the action. *Required*.
|===

=== Response

If successful, this method returns 201 - Created response code and
link:machineaction.md[Machine Action] in the response body. If a
collection is already running, this returns 400 Bad Request.

=== Example

==== Request

Here is an example of the request.

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/machines/fb9ab6be3965095a09c057be7c90f0a2/collectInvestigationPackage
----

[source,json]
----
{
  "Comment": "Collect forensics due to alert 1234"
}
----
