= 
denisebmsft
:keywords: troubleshoot, error, fix, update compliance, oms, monitor,
report, Microsoft Defender av, group policy object, setting, diagnostic
data, Microsoft Defender Antivirus

== Collect Microsoft Defender Antivirus diagnostic data

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 2]

This article describes how to collect diagnostic data that can be used
by Microsoft support and engineering teams to help troubleshoot issues
you might encounter when using the Microsoft Defender Antivirus.

____
[!NOTE] As part of the investigation or response process, you can
collect an investigation package from a device. Here’s how:
link:/windows/security/threat-protection/microsoft-defender-atp/respond-machine-alerts#collect-investigation-package-from-devices[Collect
investigation package from devices].

For performance-specific issues related to Microsoft Defender Antivirus,
see: link:tune-performance-defender-antivirus.md[Performance analyzer
for Microsoft Defender Antivirus].
____

On at least two devices that are experiencing the same issue, obtain the
.cab diagnostic file by taking the following steps:

[arabic]
. Open an administrator-level version of the command prompt as follows:
[loweralpha]
.. Open the *Start* menu.
.. Type *cmd*. Right-click on *Command Prompt* and then select *Run as
administrator*.
.. Specify administrator credentials or approve the prompt.
. Navigate to the directory for Microsoft Defender Antivirus. By
default, this is `C:\Program Files\Windows Defender`.
+
____
[!NOTE] If you’re running an
https://support.microsoft.com/help/4052623/update-for-microsoft-defender-antimalware-platform[updated
Microsoft Defender antimalware platform version], please run `MpCmdRun`
from the following location:
`C:\ProgramData\Microsoft\Windows Defender\Platform\<version>`.
____
. Type the following command, and then press *Enter*
+
[source,dos]
----
mpcmdrun.exe -GetFiles
----
. A .cab file will be generated that contains various diagnostic logs.
The location of the file will be specified in the output in the command
prompt. By default, the location is
`C:\ProgramData\Microsoft\Microsoft Defender\Support\MpSupportFiles.cab`.
+
____
[!NOTE] To redirect the cab file to a different path or UNC share, use
the following command:

`mpcmdrun.exe -GetFiles -SupportLogLocation <path>`

For more information, see
link:#redirect-diagnostic-data-to-a-unc-share[Redirect diagnostic data
to a UNC share].
____
. Copy these .cab files to a location that can be accessed by Microsoft
support. An example could be a password-protected OneDrive folder that
you can share with us.

____
[!NOTE] If you have a problem with Update compliance, send an email
using the Update Compliance support email template, and fill out the
template with the following information:

I am encountering the following issue when using Microsoft Defender
Antivirus in Update Compliance:

I have provided at least 2 support .cab files at the following location:

<accessible share, including access details such as password>

My OMS workspace ID is:

Please contact me at:
____

=== Redirect diagnostic data to a UNC share

To collect diagnostic data on a central repository, you can specify the
SupportLogLocation parameter.

[source,dos]
----
mpcmdrun.exe -GetFiles -SupportLogLocation <path>
----

Copies the diagnostic data to the specified path. If the path is not
specified, the diagnostic data will be copied to the location specified
in the Support Log Location Configuration.

When the SupportLogLocation parameter is used, a folder structure like
as follows will be created in the destination path:

[source,dos]
----
<path>\<MMDD>\MpSupport-<hostname>-<HHMM>.cab
----

'''''

[width="100%",cols="50%,50%",options="header",]
|===
|field |Description
|path |The path as specified on the command line or retrieved from
configuration

|MMDD |Month and day when the diagnostic data was collected (for
example, 0530)

|hostname |The hostname of the device on which the diagnostic data was
collected

|HHMM |Hours and minutes when the diagnostic data was collected (for
example, 1422)

| |
|===

____
[!NOTE] When using a file share please make sure that account used to
collect the diagnostic package has write access to the share.
____

=== Specify location where diagnostic data is created

You can also specify where the diagnostic .cab file will be created
using a Group Policy Object (GPO).

[arabic]
. Open the Local Group Policy Editor and find the SupportLogLocation GPO
at:
`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\SupportLogLocation`.
. Select *Define the directory path to copy support log files*.
+
:::image type=``content''
source=``images/GPO1-SupportLogLocationDefender.png'' alt-text=``The
local group policy editor''
lightbox=``images/GPO1-SupportLogLocationDefender.png'':::
+
:::image type=``content''
source=``images/GPO2-SupportLogLocationGPPage.png'' alt-text=``The
define path for log files setting''
lightbox=``images/GPO2-SupportLogLocationGPPage.png'':::
+
:::image type=``content''
source=``images/GPO1-SupportLogLocationDefender.png'' alt-text=``The
local group policy editor''
lightbox=``images/GPO1-SupportLogLocationDefender.png'':::
+
:::image type=``content''
source=``images/GPO2-SupportLogLocationGPPage.png'' alt-text=``The
define path for configuring the log files setting''
lightbox=``images/GPO2-SupportLogLocationGPPage.png'':::
. Inside the policy editor, select *Enabled*.
. Specify the directory path where you want to copy the support log
files in the *Options* field. :::image type=``content''
source=``images/GPO3-SupportLogLocationGPPageEnabledExample.png''
alt-text=``The Enabled directory path custom setting''
lightbox=``images/GPO3-SupportLogLocationGPPageEnabledExample.png'':::
. Select *OK* or *Apply*.

____
[!TIP] *Performance tip* Due to a variety of factors (examples listed
below) Microsoft Defender Antivirus, like other antivirus software, can
cause performance issues on endpoint devices. In some cases, you might
need to tune the performance of Microsoft Defender Antivirus to
alleviate those performance issues. Microsoft’s *Performance analyzer*
is a PowerShell command-line tool that helps determine which files, file
paths, processes, and file extensions might be causing performance
issues; some examples are:

* Top paths that impact scan time
* Top files that impact scan time
* Top processes that impact scan time
* Top file extensions that impact scan time
* Combinations – for example:
** top files per extension
** top paths per extension
** top processes per path
** top scans per file
** top scans per file per process

You can use the information gathered using Performance analyzer to
better assess performance issues and apply remediation actions. See:
link:tune-performance-defender-antivirus.md[Performance analyzer for
Microsoft Defender Antivirus].
____

=== See also

* link:troubleshoot-reporting.md[Troubleshoot Microsoft Defender
Antivirus reporting]
* link:tune-performance-defender-antivirus.md[Performance analyzer for
Microsoft Defender Antivirus]
