= 
mjcaparas
:keywords: community, community center, tech community, conversation,
announcements

== Access the Microsoft Defender for Endpoint Community Center

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365
Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-assignaccess-abovefoldlink[Sign
up for a free trial.]
____

The Defender for Endpoint Community Center is a place where community
members can learn, collaborate, and share experiences about the product.

There are several spaces you can explore to learn about specific
information:

* Announcements
* What’s new
* Threat Intelligence

There are several ways you can access the Community Center:

* In the Microsoft 365 Defender portal navigation pane, select
*Community center*. A new browser tab opens and takes you to the
Defender for Endpoint Tech Community page.
* Access the community through the
https://techcommunity.microsoft.com/t5/Windows-Defender-Advanced-Threat/ct-p/WindowsDefenderAdvanced[Microsoft
Defender for Endpoint Tech Community] page

You can instantly view and read conversations that have been posted in
the community.

To get the full experience within the community such as being able to
comment on posts, you’ll need to join the community. For more
information on how to get started in the Microsoft Tech Community, see
https://techcommunity.microsoft.com/t5/Getting-Started/Microsoft-Tech-Community-Getting-Started-Guide/m-p/77888#M15[Microsoft
Tech Community: Getting Started].
