= 
denisebmsft
:keywords: heuristic, machine learning, behavior monitor, real-time
protection, always-on, Microsoft Defender Antivirus, antimalware,
security, defender

== Configure behavioral, heuristic, and real-time protection

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 2]
* Microsoft Defender Antivirus

*Platforms* - Windows

Microsoft Defender Antivirus uses several methods to provide threat
protection:

* Cloud protection for near-instant detection and blocking of new and
emerging threats
* Always-on scanning, using file and process behavior monitoring and
other heuristics (also known as ``real-time protection'')
* Dedicated protection updates based on machine learning, human and
automated big-data analysis, and in-depth threat resistance research

You can configure how Microsoft Defender Antivirus uses these methods
with Group Policy, System Center Configuration Manage, PowerShell
cmdlets, and Windows Management Instrumentation (WMI).

This section covers configuration for always-on scanning, including how
to detect and block apps that are deemed unsafe, but may not be detected
as malware.

See link:cloud-protection-microsoft-defender-antivirus.md[Use next-gen
Microsoft Defender Antivirus technologies through cloud protection] for
how to enable and configure Microsoft Defender Antivirus cloud
protection.

=== In this section

[width="100%",cols="50%,50%",options="header",]
|===
|Topic |Description
|link:detect-block-potentially-unwanted-apps-microsoft-defender-antivirus.md[Detect
and block potentially unwanted applications] |Detect and block apps that
may be unwanted in your network, such as adware, browser modifiers and
toolbars, and rogue or fake antivirus apps

|link:configure-real-time-protection-microsoft-defender-antivirus.md[Enable
and configure Microsoft Defender Antivirus protection capabilities]
|Enable and configure real-time protection, heuristics, and other
always-on Microsoft Defender Antivirus monitoring features
|===

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____

=== See also

* link:defender-endpoint-antivirus-exclusions.md[Exclusions for
Microsoft Defender for Endpoint and Microsoft Defender Antivirus]
