= 
mjcaparas
:keywords: update tools, gpo, intune, mdm, microsoft endpoint manager,
policy, powershell

== Create a custom gradual rollout process for Microsoft Defender updates

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 2]
* Microsoft Defender Antivirus

*Platforms* - Windows

____
[!NOTE] This functionality requires Microsoft Defender Antivirus version
4.18.2106.X or newer.
____

To create your own custom gradual rollout process for Defender updates,
you can use Group Policy, Microsoft Endpoint Manager, and PowerShell.

The following table lists the available group policy settings for
configuring update channels:

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Setting title |Description |Location
|Select gradual Microsoft Defender monthly platform update rollout
channel |Enable this policy to specify when devices receive Microsoft
Defender platform updates during the monthly gradual rollout. |Windows
ComponentsDefender Antivirus

|Select gradual Microsoft Defender monthly engine update rollout channel
|Enable this policy to specify when devices receive Microsoft Defender
engine updates during the monthly gradual rollout. |Windows
ComponentsDefender Antivirus

|Select gradual Microsoft Defender daily security intelligence updates
rollout channel |Enable this policy to specify when devices receive
Microsoft Defender security intelligence updates during the daily
gradual rollout. |Windows ComponentsDefender Antivirus

|Disable gradual rollout of Microsoft Defender updates |Enable this
policy to disable gradual rollout of Defender updates. |Windows
ComponentsDefender Antivirus

| | |
|===

=== Group Policy

____
[!NOTE] An updated Defender ADMX template will be published together
with the 21H2 release of Windows 10. A non-localized version is
available for download at
https://github.com/microsoft/defender-updatecontrols.
____

You can use
link:/windows/win32/srvnodes/group-policy?redirectedfrom=MSDN[Group
Policy] to configure and manage Microsoft Defender Antivirus on your
endpoints.

In general, you can use the following procedure to configure or change
Microsoft Defender Antivirus group policy settings:

[arabic]
. On your Group Policy management machine, open the *Group Policy
Management Console*, right-click the *Group Policy Object* (GPO) you
want to configure and click *Edit*.
. Using the Group Policy Management Editor go to *Computer
configuration*.
. Click *Administrative templates*.
. Expand the tree to *Windows components > Microsoft Defender
Antivirus*.
. Expand the section (referred to as *Location* in the table in this
topic) that contains the setting you want to configure, double-click the
setting to open it, and make configuration changes.
. https://msdn.microsoft.com/library/ee663280(v=vs.85).aspx[Deploy the
updated GPO as you normally do].

=== Intune

Follow the instructions in below link to create a custom policy in
Intune:

link:/mem/intune/configuration/custom-settings-windows-10[Add custom
settings for Windows 10 devices in Microsoft Intune - Azure |Microsoft
Docs]

For more information on the Defender CSP used for the gradual rollout
process, see link:/windows/client-management/mdm/defender-csp[Defender
CSP].

=== PowerShell

Use the `Set-MpPreference` cmdlet to configure roll out of the gradual
updates.

Use the following parameters:

[source,powershell]
----
Set-MpPreference
-PlatformUpdatesChannel Beta|Preview|Staged|Broad|Delayed|NotConfigured
-EngineUpdatesChannel Beta|Preview|Staged|Broad|Delayed|NotConfigured
-DisableGradualRelease 1|0
-SignaturesUpdatesChannel Staged|Broad|NotConfigured
----

Example:

Use `Set-MpPreference -PlatformUpdatesChannel Beta` to configure
platform updates to arrive from the Beta Channel.

For more information on the parameters and how to configure them, see
link:/powershell/module/defender/set-mppreference[Set-MpPreference]
(Microsoft Defender Antivirus).

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____
