= 
mjcaparas
:keywords: managed security service provider, mssp, configure,
integration

== Configure alert notifications that are sent to MSSPs

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-mssp-support-abovefoldlink[Sign
up for a free trial.]
____

____
[!NOTE] This step can be done by either the MSSP customer or MSSP. MSSPs
must be granted the appropriate permissions to configure this on behalf
of the MSSP customer.
____

After access the portal is granted, alert notification rules can be
created so that emails are sent to MSSPs when alerts associated with the
tenant are created and set conditions are met.

For more information, see
link:configure-email-notifications.md#create-rules-for-alert-notifications[Create
rules for alert notifications].

These check boxes must be checked:

* *Include organization name* - The customer name will be added to email
notifications
* *Include tenant-specific portal link* - Alert link URL will have
tenant specific parameter (tid=target_tenant_id) that allows direct
access to target tenant portal

=== Related topics

* link:grant-mssp-access.md[Grant MSSP access to the portal]
* link:access-mssp-portal.md[Access the MSSP customer portal]
* link:fetch-alerts-mssp.md[Fetch alerts from customer tenant]
