= 
denisebmsft
:keywords: Microsoft Defender Antivirus, process, exclusion, files,
scans

== Configure exclusions for files opened by processes

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 2]
* Microsoft Defender Antivirus

*Platforms* - Windows

You can exclude files that have been opened by specific processes from
Microsoft Defender Antivirus scans. See
link:configure-exclusions-microsoft-defender-antivirus.md#recommendations-for-defining-exclusions[Recommendations
for defining exclusions] before defining your exclusion lists.

This article describes how to configure exclusion lists.

=== Examples of exclusions

[width="100%",cols="50%,50%",options="header",]
|===
|Exclusion |Example
|Any file on the machine that is opened by any process with a specific
file name |Specifying `test.exe` would exclude files opened by:

|Any file on the machine that is opened by any process under a specific
folder |Specifying `c:\test\sample\*` would exclude files opened by:

|Any file on the machine that is opened by a specific process in a
specific folder |Specifying `c:\test\process.exe` would exclude files
only opened by `c:\test\process.exe`
|===

When you add a process to the process exclusion list, Microsoft Defender
Antivirus won’t scan files opened by that process, no matter where the
files are located. The process itself, however, will be scanned unless
it has also been added to the
link:configure-extension-file-exclusions-microsoft-defender-antivirus.md[file
exclusion list].

The exclusions only apply to
link:configure-real-time-protection-microsoft-defender-antivirus.md[always-on
real-time protection and monitoring]. They don’t apply to scheduled or
on-demand scans.

Changes made with Group Policy to the exclusion lists *will show* in the
lists in the
link:microsoft-defender-security-center-antivirus.md[Windows Security
app]. However, changes made in the Windows Security app *will not show*
in the Group Policy lists.

You can add, remove, and review the lists for exclusions in Group
Policy, Microsoft Endpoint Configuration Manager, Microsoft Intune, and
with the Windows Security app, and you can use wildcards to further
customize the lists.

You can also use PowerShell cmdlets and WMI to configure the exclusion
lists, including reviewing your lists.

By default, local changes made to the lists (by users with administrator
privileges; changes made with PowerShell and WMI) will be merged with
the lists as defined (and deployed) by Group Policy, Configuration
Manager, or Intune. The Group Policy lists will take precedence in the
case of conflicts.

You can
link:configure-local-policy-overrides-microsoft-defender-antivirus.md#merge-lists[configure
how locally and globally defined exclusions lists are merged] to allow
local changes to override managed deployment settings.

=== Configure the list of exclusions for files opened by specified processes

==== Use Microsoft Intune to exclude files that have been opened by specified processes from scans

See link:/intune/device-restrictions-configure[Configure device
restriction settings in Microsoft Intune] and
link:/intune/device-restrictions-windows-10#microsoft-defender-antivirus[Microsoft
Defender Antivirus device restriction settings for Windows 10 in Intune]
for more details.

==== Use Microsoft Endpoint Manager to exclude files that have been opened by specified processes from scans

See
link:/configmgr/protect/deploy-use/endpoint-antimalware-policies#exclusion-settings[How
to create and deploy antimalware policies: Exclusion settings] for
details on configuring Microsoft Endpoint Manager (current branch).

==== Use Group Policy to exclude files that have been opened by specified processes from scans

[arabic]
. On your Group Policy management computer, open the
link:/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc731212(v=ws.11)[Group
Policy Management Console], right-click the Group Policy Object you want
to configure and click *Edit*.
. In the *Group Policy Management Editor* go to *Computer configuration*
and click *Administrative templates*.
. Expand the tree to *Windows components > Microsoft Defender Antivirus
> Exclusions*.
. Double-click *Process Exclusions* and add the exclusions:
[arabic]
.. Set the option to *Enabled*.
.. Under the *Options* section, click *Show…*.
.. Enter each process on its own line under the *Value name* column. See
the example table for the different types of process exclusions. Enter
*0* in the *Value* column for all processes.
. Click *OK*.

==== Use PowerShell cmdlets to exclude files that have been opened by specified processes from scans

Using PowerShell to add or remove exclusions for files that have been
opened by processes requires using a combination of three cmdlets with
the `-ExclusionProcess` parameter. The cmdlets are all in the
link:/powershell/module/defender/[Defender module].

The format for the cmdlets is:

[source,powershell]
----
<cmdlet> -ExclusionProcess "<item>"
----

The following are allowed as the <cmdlet>:

[cols=",",options="header",]
|===
|Configuration action |PowerShell cmdlet
|Create or overwrite the list |`Set-MpPreference`
|Add to the list |`Add-MpPreference`
|Remove items from the list |`Remove-MpPreference`
|===

____
[!IMPORTANT] If you have created a list, either with `Set-MpPreference`
or `Add-MpPreference`, using the `Set-MpPreference` cmdlet again will
overwrite the existing list.
____

For example, the following code snippet would cause Microsoft Defender
Antivirus scans to exclude any file that is opened by the specified
process:

[source,powershell]
----
Add-MpPreference -ExclusionProcess "c:\internal\test.exe"
----

For more information on how to use PowerShell with Microsoft Defender
Antivirus, see Manage antivirus with PowerShell cmdlets and
link:/powershell/module/defender[Microsoft Defender Antivirus cmdlets].

==== Use Windows Management Instruction (WMI) to exclude files that have been opened by specified processes from scans

Use the
link:/previous-versions/windows/desktop/legacy/dn455323(v=vs.85)[*Set*&#44;
*Add*&#44; and *Remove* methods of the *MSFT_MpPreference*] class for the
following properties:

[source,wmi]
----
ExclusionProcess
----

The use of *Set*, *Add*, and *Remove* is analogous to their counterparts
in PowerShell: `Set-MpPreference`, `Add-MpPreference`, and
`Remove-MpPreference`.

For more information and allowed parameters, see
link:/previous-versions/windows/desktop/defender/windows-defender-wmiv2-apis-portal[Windows
Defender WMIv2 APIs].

==== Use the Windows Security app to exclude files that have been opened by specified processes from scans

See link:microsoft-defender-security-center-antivirus.md[Add exclusions
in the Windows Security app] for instructions.

=== Use wildcards in the process exclusion list

The use of wildcards in the process exclusion list is different from
their use in other exclusion lists.

In particular, you cannot use the question mark (`?`) wildcard, and the
asterisk (`*`) wildcard can only be used at the end of a complete path.
You can still use environment variables (such as `%ALLUSERSPROFILE%`) as
wildcards when defining items in the process exclusion list.

The following table describes how the wildcards can be used in the
process exclusion list:

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Wildcard |Example use |Example matches
|`*` (asterisk) |`C:\MyData\*` |Any file opened by `C:\MyData\file.exe`

|Environment variables |`%ALLUSERSPROFILE%\CustomLogFiles\file.exe` |Any
file opened by `C:\ProgramData\CustomLogFiles\file.exe`
|===

=== Review the list of exclusions

You can retrieve the items in the exclusion list with MpCmdRun,
PowerShell,
link:/configmgr/protect/deploy-use/endpoint-antimalware-policies#exclusion-settings[Microsoft
Endpoint Configuration Manager],
link:/intune/device-restrictions-configure[Intune], or the
link:microsoft-defender-security-center-antivirus.md[Windows Security
app].

If you use PowerShell, you can retrieve the list in two ways:

* Retrieve the status of all Microsoft Defender Antivirus preferences.
Each of the lists will be displayed on separate lines, but the items
within each list will be combined into the same line.
* Write the status of all preferences to a variable, and use that
variable to only call the specific list you are interested in. Each use
of `Add-MpPreference` is written to a new line.

==== Validate the exclusion list by using MpCmdRun

To check exclusions with the dedicated
link:./command-line-arguments-microsoft-defender-antivirus.md?branch=v-anbic-wdav-new-mpcmdrun-options[command-line
tool mpcmdrun.exe], use the following command:

[source,dos]
----
MpCmdRun.exe -CheckExclusion -path <path>
----

____
[!NOTE] Checking exclusions with MpCmdRun requires Microsoft Defender
Antivirus CAMP version 4.18.1812.3 (released in December 2018) or later.
____

==== Review the list of exclusions alongside all other Microsoft Defender Antivirus preferences by using PowerShell

Use the following cmdlet:

[source,powershell]
----
Get-MpPreference
----

See link:use-powershell-cmdlets-microsoft-defender-antivirus.md[Use
PowerShell cmdlets to configure and run Microsoft Defender Antivirus]
and link:/powershell/module/defender[Microsoft Defender Antivirus
cmdlets] for more information on how to use PowerShell with Microsoft
Defender Antivirus.

==== Retrieve a specific exclusions list by using PowerShell

Use the following code snippet (enter each line as a separate command);
replace *WDAVprefs* with whatever label you want to name the variable:

[source,powershell]
----
$WDAVprefs = Get-MpPreference
$WDAVprefs.ExclusionProcess
----

See link:use-powershell-cmdlets-microsoft-defender-antivirus.md[Use
PowerShell cmdlets to configure and run Microsoft Defender Antivirus]
and link:/powershell/module/defender[Microsoft Defender Antivirus
cmdlets] for more information on how to use PowerShell with Microsoft
Defender Antivirus.

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____

=== Related articles

* link:configure-exclusions-microsoft-defender-antivirus.md[Configure
and validate exclusions in Microsoft Defender Antivirus scans]
* link:configure-extension-file-exclusions-microsoft-defender-antivirus.md[Configure
and validate exclusions based on file name&#44; extension&#44; and folder
location]
* link:configure-server-exclusions-microsoft-defender-antivirus.md[Configure
Microsoft Defender Antivirus exclusions on Windows Server]
* link:common-exclusion-mistakes-microsoft-defender-antivirus.md[Common
mistakes to avoid when defining exclusions]
* link:customize-run-review-remediate-scans-microsoft-defender-antivirus.md[Customize&#44;
initiate&#44; and review the results of Microsoft Defender Antivirus scans
and remediation]
* link:microsoft-defender-antivirus-in-windows-10.md[Microsoft Defender
Antivirus in Windows 10]
