= 
denisebmsft
:keywords: Microsoft Defender Antivirus, antimalware, security,
defender, cloud, timeout, block, period, seconds

== Configure the cloud block timeout period

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] - Microsoft Defender Antivirus

*Platforms* - Windows

When Microsoft Defender Antivirus finds a suspicious file, it can
prevent the file from running while it queries the
link:cloud-protection-microsoft-defender-antivirus.md[Microsoft Defender
Antivirus cloud service].

The default period that the file is
link:configure-block-at-first-sight-microsoft-defender-antivirus.md[blocked]
is 10 seconds. If you’re a security administrator, you can specify more
time to wait before the file is allowed to run. Extending the cloud
block timeout period can help ensure there is enough time to receive a
proper determination from the Microsoft Defender Antivirus cloud
service.

=== Prerequisites to use the extended cloud block timeout

link:configure-block-at-first-sight-microsoft-defender-antivirus.md[Block
at first sight] and its prerequisites must be enabled before you can
specify an extended timeout period.

=== Specify the extended timeout period using Microsoft Endpoint Manager

You can specify the cloud block timeout period with an
link:/mem/intune/protect/endpoint-security-policy[endpoint security
policy in Microsoft Endpoint Manager].

[arabic]
. Go to the Endpoint Manager admin center
(https://endpoint.microsoft.com/) and sign in.
. Select *Endpoint security*, and then under *Manage*, choose
*Antivirus*.
. Select (or create) an antivirus policy.
. In the *Configuration settings* section, expand *Cloud protection*.
Then, in the *Microsoft Defender Antivirus Extended Timeout In Seconds*
box, specify the more time, in seconds, from 1 second to 50 seconds.
Whatever you specify is added to the default 10 seconds.
. (This step is optional) Make any other changes to your antivirus
policy. (Need help? See
link:/mem/intune/protect/antivirus-microsoft-defender-settings-windows[Settings
for Microsoft Defender Antivirus policy in Microsoft Intune].)
. Choose *Next*, and finish configuring your policy.

=== Specify the extended timeout period using Group Policy

You can use Group Policy to specify an extended timeout for cloud
checks.

[arabic]
. On your Group Policy management computer, open the
link:/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc731212(v=ws.11)[Group
Policy Management Console]
. Right-click the Group Policy Object you want to configure and then
select *Edit*.
. In the *Group Policy Management Editor*, go to *Computer
configuration*, and then select *Administrative templates*.
. Expand the tree to *Windows components* > *Microsoft Defender
Antivirus* > *MpEngine*.
. Double-click *Configure extended cloud check* and ensure the option is
enabled.
+
Specify the extra amount of time to prevent the file from running while
waiting for a cloud determination. Specify the extra time, in seconds,
from 1 second to 50 seconds. Whatever you specify is added to the
default 10 seconds.
. Select *OK*.

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____
