= 
mjcaparas
:keywords: configure, proxy, internet, internet connectivity, settings,
proxy settings, netsh, winhttp, proxy server

== Configure device proxy and Internet connectivity settings

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://www.microsoft.com/WindowsForBusiness/windows-atp?ocid=docs-wdatp-configureendpointsscript-abovefoldlink[Sign
up for a free trial.]
____

The Defender for Endpoint sensor requires Microsoft Windows HTTP
(WinHTTP) to report sensor data and communicate with the Defender for
Endpoint service. The embedded Defender for Endpoint sensor runs in
system context using the LocalSystem account.

____
[!TIP] For organizations that use forward proxies as a gateway to the
Internet, you can use network protection to
link:investigate-behind-proxy.md[investigate connection events that
occur behind forward proxies].
____

The WinHTTP configuration setting is independent of the Windows Internet
(WinINet) browsing proxy settings (see,
link:/windows/win32/wininet/wininet-vs-winhttp[WinINet vs. WinHTTP]). It
can only discover a proxy server by using the following discovery
methods:

* Autodiscovery methods:
** Transparent proxy
** Web Proxy Auto-discovery Protocol (WPAD)
+
____
{empty}[!NOTE] If you’re using Transparent proxy or WPAD in your network
topology, you don’t need special configuration settings. For more
information on Defender for Endpoint URL exclusions in the proxy, see
link:#enable-access-to-microsoft-defender-for-endpoint-service-urls-in-the-proxy-server[Enable
access to Defender for Endpoint service URLs in the proxy server]
____
* Manual static proxy configuration:
** Registry-based configuration
** WinHTTP configured using netsh command: Suitable only for desktops in
a stable topology (for example: a desktop in a corporate network behind
the same proxy)

____
[!NOTE] Defender antivirus and EDR proxies can be set independently. In
the sections that follow, be aware of those distinctions.
____

=== Configure the proxy server manually using a registry-based static proxy

Configure a registry-based static proxy for Defender for Endpoint
detection and response (EDR) sensor to report diagnostic data and
communicate with Defender for Endpoint services if a computer isn’t
permitted to connect to the Internet.

____
[!NOTE] When using this option on Windows 10, or Windows 11, or Windows
Server 2019, or Windows Server 2022, it is recommended to have the
following (or later) build and cumulative update rollup:

* Windows 11
* Windows 10, version 1809 or Windows Server 2019, or Windows Server
2022 - https://support.microsoft.com/kb/5001384
* Windows 10, version 1909 - https://support.microsoft.com/kb/4601380
* Windows 10, version 2004 - https://support.microsoft.com/kb/4601382
* Windows 10, version 20H2 - https://support.microsoft.com/kb/4601382

These updates improve the connectivity and reliability of the CnC
(Command and Control) channel.
____

The static proxy is configurable through group policy (GP), both the
settings under group policy values should be configured to the proxy
server for using EDR. The group policy is available in Administrative
Templates.

* *Administrative Templates > Windows Components > Data Collection and
Preview Builds > Configure Authenticated Proxy usage for the Connected
User Experience and Telemetry Service*.
+
Set it to *Enabled* and select *Disable Authenticated Proxy usage*.
+
:::image type=``content'' source=``images/atp-gpo-proxy1.png''
alt-text=``The Group Policy setting1 status pane''
lightbox=``images/atp-gpo-proxy1.png'':::
* *Administrative Templates > Windows Components > Data Collection and
Preview Builds > Configure connected user experiences and telemetry*:
+
Configure the proxy.
+
:::image type=``content'' source=``images/atp-gpo-proxy2.png''
alt-text=``The Group Policy setting2 status pane''
lightbox=``images/atp-gpo-proxy2.png'':::

[width="100%",cols="<25%,<25%,<25%,<25%",options="header",]
|===
|Group Policy |Registry key |Registry entry |Value
|Configure authenticated proxy usage for the connected user experience
and the telemetry service
|`HKLM\Software\Policies\Microsoft\Windows\DataCollection`
|`DisableEnterpriseAuthProxy` |1 (REG_DWORD)

|Configure connected user experiences and telemetry
|`HKLM\Software\Policies\Microsoft\Windows\DataCollection`
|`TelemetryProxyServer` |`servername:port or ip:port` For example:
`10.0.0.6:8080` (REG_SZ)
|===

____
[!NOTE] If you are using `TelemetryProxyServer' setting on devices that
are otherwise *completely offline*, meaning the operating system is
unable to connect for the online certificate revocation list or Windows
Update, then it is recommended to add the additional registry setting
`PreferStaticProxyForHttpRequest` with a value of `1`. Parent registry
path location for ``PreferStaticProxyForHttpRequest'' is
``HKEY_LOCAL_MACHINEAdvanced Threat Protection'' The following command
can be used to insert the registry value in the correct location:
`reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows Advanced Threat Protection" /v PreferStaticProxyForHttpRequest /t REG_DWORD /d 1 /f`
The above registry value is applicable only starting with MsSense.exe
version 10.8210.* and later, or version 10.8049.* and later.
____

=== Configure a static proxy for Microsoft Defender Antivirus

Microsoft Defender Antivirus
link:cloud-protection-microsoft-defender-antivirus.md[cloud-delivered
protection] provides near-instant, automated protection against new and
emerging threats. Note, the connectivity is required for
link:manage-indicators.md[custom indicators] when Defender Antivirus is
your active anti-malware solution. For link:edr-in-block-mode.md[EDR in
block mode] has primary anti-malware solution when using a non-Microsoft
solution.

Configure the static proxy using the Group Policy available in
Administrative Templates:

[arabic]
. *Administrative Templates > Windows Components > Microsoft Defender
Antivirus > Define proxy server for connecting to the network*.
. Set it to *Enabled* and define the proxy server. Note, the URL must
have either http:// or https://. For supported versions for https://,
see link:manage-updates-baselines-microsoft-defender-antivirus.md[Manage
Microsoft Defender Antivirus updates].
+
:::image type=``content'' source=``images/proxy-server-mdav.png''
alt-text=``The proxy server for Microsoft Defender Antivirus''
lightbox=``images/proxy-server-mdav.png'':::
. Under the registry key
`HKLM\Software\Policies\Microsoft\Windows Defender`, the policy sets the
registry value `ProxyServer` as REG_SZ.
+
The registry value `ProxyServer` takes the following string format:
+
[source,text]
----
<server name or ip>:<port>

For example: http://10.0.0.6:8080
----

____
{empty}[!NOTE]

For resiliency purposes and the real-time nature of cloud-delivered
protection, Microsoft Defender Antivirus will cache the last known
working proxy. Ensure your proxy solution does not perform SSL
inspection. This will break the secure cloud connection.

Microsoft Defender Antivirus will not use the static proxy to connect to
Windows Update or Microsoft Update for downloading updates. Instead, it
will use a system-wide proxy if configured to use Windows Update, or the
configured internal update source according to the
link:manage-protection-updates-microsoft-defender-antivirus.md[configured
fallback order].

If required, you can use *Administrative Templates > Windows Components
> Microsoft Defender Antivirus > Define proxy auto-config (.pac)* for
connecting to the network. If you need to set up advanced configurations
with multiple proxies, use *Administrative Templates > Windows
Components > Microsoft Defender Antivirus > Define addresses* to bypass
proxy server and prevent Microsoft Defender Antivirus from using a proxy
server for those destinations.

You can use PowerShell with the `Set-MpPreference` cmdlet to configure
these options:

* ProxyBypass
* ProxyPacUrl
* ProxyServer
____

____
[!NOTE] To use the proxy correctly, configure these three different
proxy settings: - Microsoft Defender for Endpoint (MDE) - AV (Antivirus)
- Endpoint Detection and Response (EDR)
____

=== Configure the proxy server manually using netsh command

Use netsh to configure a system-wide static proxy.

____
{empty}[!NOTE]

* This will affect all applications including Windows services which use
WinHTTP with default proxy.
____

[arabic]
. Open an elevated command line:
[arabic]
.. Go to *Start* and type *cmd*.
.. Right-click *Command prompt* and select *Run as administrator*.
. Enter the following command and press *Enter*:
+
`command prompt netsh winhttp set proxy <proxy>:<port>`
+
For example: `netsh winhttp set proxy 10.0.0.6:8080`

To reset the winhttp proxy, enter the following command and press
*Enter*:

`command prompt netsh winhttp reset proxy`

See
link:/windows-server/networking/technologies/netsh/netsh-contexts[Netsh
Command Syntax&#44; Contexts&#44; and Formatting] to learn more.

=== Enable access to Microsoft Defender for Endpoint service URLs in the proxy server

By default, if a proxy or firewall is blocking all traffic by default
and allowing only specific domains, then add the domains listed in the
downloadable sheet to the allowed domains list.

The following downloadable spreadsheet lists the services and their
associated URLs that your network must be able to connect. Ensure there
are no firewall or network filtering rules to deny access for these
URLs. Optional, you may need to create an _allow_ rule specifically for
them.

[width="100%",cols="50%,50%",options="header",]
|===
|Spreadsheet of domains list |Description
|Microsoft Defender for Endpoint URL list for commercial customers
|Spreadsheet of specific DNS records for service locations, geographic
locations, and OS for commercial customers.

|Microsoft Defender for Endpoint URL list for Gov/GCC/DoD |Spreadsheet
of specific DNS records for service locations, geographic locations, and
OS for Gov/GCC/DoD customers.
|===

If a proxy or firewall has HTTPS scanning (SSL inspection) enabled,
exclude the domains listed in the above table from HTTPS scanning. In
your firewall, open all the URLs where the geography column is WW. For
rows where the geography column isn’t WW, open the URLs to your specific
data location. To verify your data location setting, see
link:/microsoft-365/security/defender-endpoint/data-retention-settings[Verify
data storage location and update data retention settings for Microsoft
Defender for Endpoint]. Don’t exclude the URL `*.blob.core.windows.net`
from any kind of network inspection.

____
[!NOTE] Windows devices running with version 1803 or earlier needs
`settings-win.data.microsoft.com`.

URLs that include v20 in them are only needed if you have Windows
devices running version 1803 or later. For example,
`us-v20.events.data.microsoft.com` is needed for a Windows device
running version 1803 or later and onboarded to US Data Storage region.
____

If a proxy or firewall is blocking anonymous traffic as Defender for
Endpoint sensor, and it’s connecting from system context to make sure
anonymous traffic is permitted in the previously listed URLs.

____
[!NOTE] Microsoft does not provide a proxy server. These URLs are
accessible via the proxy server that you configure.
____

==== Microsoft Monitoring Agent (MMA) - proxy and firewall requirements for older versions of Windows client or Windows Server

The information in the list of proxy and firewall configuration
information is required to communicate with Log Analytics agent (often
referred to as Microsoft Monitoring Agent) for previous versions of
Windows, such as Windows 7 SP1, Windows 8.1, and Windows Server 2008
R2*.

'''''

[cols=",,,",options="header",]
|===
|Agent Resource |Ports |Direction |Bypass HTTPS inspection
|*.ods.opinsights.azure.com |Port 443 |Outbound |Yes
|*.oms.opinsights.azure.com |Port 443 |Outbound |Yes
|*.blob.core.windows.net |Port 443 |Outbound |Yes
|*.azure-automation.net |Port 443 |Outbound |Yes
|===

____
[!NOTE] *These connectivity requirements apply to the previous Microsoft
Defender for Endpoint of Windows Server 2016, and Windows Server 2012 R2
that requires MMA. Instructions to onboard these operating systems with
the new unified solution are at
link:configure-server-endpoints.md[Onboard Windows servers], or migrate
to the new unified solution at
link:/microsoft-365/security/defender-endpoint/server-migration[Server
migration scenarios in Microsoft Defender for Endpoint].
____

____
[!NOTE] As a cloud-based solution, the IP range can change. It’s
recommended, you move to DNS resolving setting.
____

=== Confirm Microsoft Monitoring Agent (MMA) Service URL Requirements

See the following guidance to eliminate the wildcard (*) requirement for
your specific environment when using the Microsoft Monitoring Agent
(MMA) for previous versions of Windows.

[arabic]
. Onboard a previous operating system with the Microsoft Monitoring
Agent (MMA) into Defender for Endpoint (for more information, see
https://go.microsoft.com/fwlink/p/?linkid=2010326[Onboard previous
versions of Windows on Defender for Endpoint] and
link:configure-server-endpoints.md[Onboard Windows servers]).
. Ensure the machine is successfully reporting into the Microsoft 365
Defender portal.
. Run the TestCloudConnection.exe tool from ``C:FilesMonitoring Agent''
to validate the connectivity, and to get the required URLs for your
specific workspace.
. Check the Microsoft Defender for Endpoint URLs list for the complete
list of requirements for your region (refer to the Service URLs
https://download.microsoft.com/download/6/b/f/6bfff670-47c3-4e45-b01b-64a2610eaefa/mde-urls-commercial.xlsx[Spreadsheet]).
+
:::image type=``content'' source=``images/admin-powershell.png''
alt-text=``The administrator in Windows PowerShell''
lightbox=``images/admin-powershell.png'':::

The wildcards (*) used in *.ods.opinsights.azure.com,
*.oms.opinsights.azure.com, and *.agentsvc.azure-automation.net URL
endpoints can be replaced with your specific Workspace ID. The Workspace
ID is specific to your environment and workspace. It can be found in the
Onboarding section of your tenant within the Microsoft 365 Defender
portal.

The *.blob.core.windows.net URL endpoint can be replaced with the URLs
shown in the ``Firewall Rule: *.blob.core.windows.net'' section of the
test results.

____
[!NOTE] In the case of onboarding via Microsoft Defender for Cloud,
multiple workspaces can be used. You will need to perform the
TestCloudConnection.exe procedure on the onboarded machine from each
workspace (to determine, if there are any changes to the
*.blob.core.windows.net URLs between the workspaces).
____

=== Verify client connectivity to Microsoft Defender for Endpoint service URLs

Verify, the proxy configuration is completed successfully. The WinHTTP
can then discover and communicate through the proxy server in your
environment, and then the proxy server will allow traffic to the
Defender for Endpoint service URLs.

[arabic]
. Download the https://aka.ms/mdeanalyzer[Microsoft Defender for
Endpoint Client Analyzer tool] to the PC, where Defender for Endpoint
sensor is running on. For downlevel servers, use the latest preview
edition is available for download
https://aka.ms/BetaMDEAnalyzer[Microsoft Defender for Endpoint Client
Analyzer tool Beta].
. Extract the contents of MDEClientAnalyzer.zip on the device.
. Open an elevated command line:
[arabic]
.. Go to *Start* and type *cmd*.
.. Right-click *Command prompt* and select *Run as administrator*.
. Enter the following command and press *Enter*:
+
`command prompt  HardDrivePath\MDEClientAnalyzer.cmd`
+
Replace _HardDrivePath_ with the path, where the MDEClientAnalyzer tool
was downloaded. For example:
+
`command prompt  C:\Work\tools\MDEClientAnalyzer\MDEClientAnalyzer.cmd`
. The tool creates and extracts the _MDEClientAnalyzerResult.zip_ file
in the folder to use in the _HardDrivePath_.
. Open _MDEClientAnalyzerResult.txt_ and verify that you’ve performed
the proxy configuration steps to enable server discovery and access to
the service URLs.
+
The tool checks the connectivity of Defender for Endpoint service URLs.
Ensure the Defender for Endpoint client is configured to interact. The
tool will print the results in the _MDEClientAnalyzerResult.txt_ file
for each URL that can potentially be used to communicate with the
Defender for Endpoint services. For example:
+
[source,text]
----
Testing URL : https://xxx.microsoft.com/xxx
1 - Default proxy: Succeeded (200)
2 - Proxy auto discovery (WPAD): Succeeded (200)
3 - Proxy disabled: Succeeded (200)
4 - Named proxy: Doesn't exist
5 - Command line proxy: Doesn't exist
----

If any one of the connectivity options returns a (200) status, then the
Defender for Endpoint client can communicate with the tested URL
properly using this connectivity method.

However, if the connectivity check results indicate a failure, an HTTP
error is displayed (see HTTP Status Codes). You can then use the URLs in
the table shown in
link:#enable-access-to-microsoft-defender-for-endpoint-service-urls-in-the-proxy-server[Enable
access to Defender for Endpoint service URLs in the proxy server]. The
URLs available for use will depend on the region selected during the
onboarding procedure.

____
[!NOTE] The Connectivity Analyzer tool’s cloud connectivity checks are
not compatible with Attack Surface Reduction rule
link:attack-surface-reduction-rules-reference.md#block-process-creations-originating-from-psexec-and-wmi-commands[Block
process creations originating from PSExec and WMI commands]. You will
need to temporarily disable this rule, to run the connectivity tool.
Alternatively, you can temporarily add
link:attack-surface-reduction-rules-deployment-implement.md#customize-attack-surface-reduction-rules[ASR
exclusions] when running the analyzer.

When the TelemetryProxyServer is set in Registry or via Group Policy,
Defender for Endpoint will fall back, it fails to access the defined
proxy.
____

=== Related articles

* link:use-group-policy-microsoft-defender-antivirus.md[Use Group Policy
settings to configure and manage Microsoft Defender Antivirus]
* link:configure-endpoints.md[Onboard Windows devices]
* link:troubleshoot-onboarding.md[Troubleshoot Microsoft Defender for
Endpoint onboarding issues]
