= 
dansimp
:keywords: onboard, Intune management, Microsoft Defender for Endpoint,
Microsoft Defender, Windows Defender, attack surface reduction, ASR,
security baseline

== Optimize ASR rule deployment and detections

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://www.microsoft.com/WindowsForBusiness/windows-atp?ocid=docs-wdatp-onboardconfigure-abovefoldlink[Sign
up for a free trial.]
____

link:./attack-surface-reduction.md[Attack surface reduction (ASR) rules]
identify and prevent typical malware exploits. They control when and how
potentially malicious code can run. For example, they can prevent
JavaScript or VBScript from launching a downloaded executable, block
Win32 API calls from Office macros, and block processes that run from
USB drives.

:::image type=``content'' source=``../../media/attack-surface-mgmt.png''
alt-text=``Attack surface management card''
lightbox=``../../media/attack-surface-mgmt.png'':::

____
_Attack surface management card_
____

The _Attack surface management card_ is an entry point to tools in
Microsoft 365 Defender portal that you can use to:

* Understand how ASR rules are currently deployed in your organization.
* Review ASR detections and identify possible incorrect detections.
* Analyze the impact of exclusions and generate the list of file paths
to exclude.

Select *Go to attack surface management* > *Reports* > *Attack surface
reduction rules* > *Add exclusions*. From there, you can navigate to
other sections of Microsoft 365 Defender portal.

:::image type=``content''
source=``images/secconmgmt_asr_m365exlusions.png'' alt-text=``Add
exclusions tab in the Attack surface reduction rules page in the
Microsoft 365 Defender portal''
lightbox=``images/secconmgmt_asr_m365exlusions.png'':::

____
_The *Add exclusions* tab in the Attack surface reduction rules page in
Microsoft 365 Defender portal_
____

____
[!NOTE] To access Microsoft 365 Defender portal, you need a Microsoft
365 E3 or E5 license and an account that has certain roles on Azure
Active Directory.
link:/microsoft-365/security/defender/prerequisites[Read about required
licenses and permissions].
____

For more information about ASR rule deployment in Microsoft 365 Defender
portal, see link:configure-machines-asr.md[Optimize ASR rule deployment
and detections].

=== Related topics

* link:configure-machines.md[Ensure your devices are configured
properly]
* link:configure-machines-onboarding.md[Get devices onboarded to
Microsoft Defender for Endpoint]
* link:configure-machines-security-baseline.md[Monitor compliance to the
Microsoft Defender for Endpoint security baseline]
