= Onboard non-Windows devices to the Microsoft Defender for Endpoint service
:audience: ITPro
:author: mjcaparas
:description: Configure non-Windows devices so that they can send sensor data to the Microsoft Defender for Endpoint service.
:keywords: onboard non-Windows devices, macos, linux, device management, configure Microsoft Defender for Endpoint devices
:manager: dansimp
:ms.author: macapara
:ms.collection: ["M365-security-compliance", "m365-initiative-defender-endpoint"]
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150
:search.product: eADQiWindows 10XVcnh

== Onboard non-Windows devices

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

*Platforms*

* macOS
* Linux

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-nonwindows-abovefoldlink[Sign up for a free trial.]
____

Defender for Endpoint provides a centralized security operations experience for Windows and non-Windows platforms.
You'll be able to see alerts from various supported operating systems (OS) in Microsoft 365 Defender and better protect your organization's network.

You'll need to know the exact Linux distros and macOS versions that are compatible with Defender for Endpoint for the integration to work.
For more information, see:

* link:microsoft-defender-endpoint-linux.md#system-requirements[Microsoft Defender for Endpoint on Linux system requirements]
* link:microsoft-defender-endpoint-mac.md#system-requirements[Microsoft Defender for Endpoint on macOS system requirements].

=== Onboarding non-Windows devices

You'll need to take the following steps to onboard non-Windows devices:

. Select your preferred method of onboarding:
 ** For macOS devices, you can choose to onboard through Microsoft Defender for Endpoint or through a third-party solution.
For more information, see link:/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-mac[Microsoft Defender for Endpoint on Mac].
 ** For other non-Windows devices choose *Onboard non-Windows devices through third-party integration*.
  ... In the navigation pane, select *Partners and APIs* > *Partner Applications* . Make sure the third-party solution is listed.
  ... In the *Partner Applications* page, select the partner that supports your non-Windows devices.
  ... Click *View* to open the partner's page.
Follow the instructions provided on the page.
  ... After creating an account or subscribing to the partner solution, you should get to a stage where a tenant Global Admin in your organization is asked to accept a permission request from the partner application.
Read the permission request carefully to make sure that it's aligned with the service that you require.
. Run a detection test by following the instructions of the third-party solution.

=== Offboard non-Windows devices

For macOS and Linux devices, you can choose to offboard through Microsoft Defender for Endpoint.
In the navigation pane, select *Settings* > *Offboard* > *Select Operating System to start the offboarding Process*.

You can also offboard non-Windows devices by disabling the third-party integration.
Enable coverage for devices running non-Windows platforms by https://security.microsoft.com/interoperability/partners[integrating third-party solutions].

=== Related topics

* xref:configure-endpoints.adoc[Onboard Windows devices]
* xref:configure-server-endpoints.adoc[Onboard servers]
* xref:configure-proxy-internet.adoc[Configure proxy and Internet connectivity settings]
* xref:troubleshoot-onboarding.adoc[Troubleshooting Microsoft Defender for Endpoint onboarding issues]
