= Integrate your SIEM tools with Microsoft Defender for Endpoint
:audience: ITPro
:author: mjcaparas
:description: Learn how to ingest incidents and alerts, and integrate SIEM tools.
:keywords: configure siem, security information and events management tools, splunk, arcsight, custom indicators, rest api, alert definitions, indicators of compromise
:manager: dansimp
:ms.author: macapara
:ms.collection: M365-security-compliance
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Integrate your SIEM tools with Microsoft Defender for Endpoint

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

=== Ingest alerts using security information and events management (SIEM) tools

____
[!NOTE]

xref:alerts.adoc[Microsoft Defender for Endpoint Alert] is composed from one or more suspicious or malicious events that occurred on the device and their related details.
The Microsoft Defender for Endpoint Alert API is the latest API for alert consumption and contain a detailed list of related evidence for each alert.
For more information, see xref:alerts.adoc[Alert methods and properties] and xref:get-alerts.adoc[List alerts].
____

Microsoft Defender for Endpoint supports security information and event management (SIEM) tools ingesting information from your enterprise tenant in Azure Active Directory (AAD) using the OAuth 2.0 authentication protocol for a registered AAD application representing the specific SIEM solution or connector installed in your environment.

For more information, see:

* xref:api-terms-of-use.adoc[Microsoft Defender for Endpoint APIs license and terms of use]
* xref:apis-intro.adoc[Access the Microsoft Defender for Endpoint APIs]
* xref:api-hello-world.adoc[Hello World example (describes how to register an application in Azure Active Directory)]
* xref:exposed-apis-create-app-webapp.adoc[Get access with application context]

Microsoft Defender for Endpoint currently supports the following SIEM solution integrations:

* <<ingesting-incidents-and-alerts-from-the-microsoft-365-defender-and-microsoft-defender-for-endpoint-incidents-and-alerts-rest-apis,Ingesting incidents and alerts from the Microsoft 365 Defender and Microsoft Defender for Endpoint incidents and alerts REST APIs>>
* <<ingesting-microsoft-defender-for-endpoint-events-from-the-microsoft-365-defender-event-streaming-api,Ingesting Microsoft Defender for Endpoint events from the Microsoft 365 Defender event streaming API>>

=== Ingesting incidents and alerts from the Microsoft 365 Defender and Microsoft Defender for Endpoint incidents and alerts REST APIs

==== Ingesting incidents from the Microsoft 365 Defender incidents REST API

For more information on the Microsoft 365 Defender incidents API, see xref:../defender/api-incident.adoc[incidents methods and properties].

==== Ingesting alerts from the Microsoft Defender for Endpoint alerts REST API

For more information on the Microsoft Defender for Endpoint alerts API, see xref:alerts.adoc[alerts methods and properties].

=== SIEM tool integration with Microsoft Defender for Endpoint

==== Splunk

Using the Microsoft 365 Defender Add-on for Splunk that supports:

* Ingesting Microsoft Defender for Endpoint alerts
* Updating alerts in Microsoft Defender for Endpoint from within Splunk

For more information on the Microsoft 365 Defender Add-on for Splunk, see https://splunkbase.splunk.com/app/4959/[splunkbase].

==== Datadog

Microsoft 365 Defender for Endpoint integration with Datadog supports:

* Ingesting Microsoft Defender for Endpoint alerts and incidents
* Dashboards that enable monitoring metrics across endpoints, threats and vulnerabilities, and software

For more information on the integration, see https://app.datadoghq.com/marketplace/app/crest-data-systems-microsoft-defender/support[Datadog Marketplace].

==== Micro Focus ArcSight

The new SmartConnector for Microsoft 365 Defender ingests incidents that contain alerts from all Microsoft 365 Defender products - including from Microsoft Defender for Endpoint - into ArcSight and maps these onto its Common Event Framework (CEF).

For more information on the new ArcSight SmartConnector for Microsoft 365 Defender, see https://www.microfocus.com/documentation/arcsight/arcsight-smartconnectors/microsoft-365-defender/index.html[ArcSight Product documentation].

The SmartConnector replaces the previous FlexConnector for Microsoft 365 Defender.

==== IBM QRadar

____
[!NOTE] IBM QRadar integration with Microsoft 365 Defender, which include Microsoft Defender for Endpoint is now supported by the new Microsoft 365 Defender Device Support Module (DSM) that calls the xref:../defender/streaming-api.adoc[Microsoft 365 Defender Streaming API] that allows ingesting streaming event data from Microsoft 365 Defender products, including Microsoft Defender for Endpoint.
For more information on the new QRadar Microsoft 365 Defender DSM, see https://www.ibm.com/docs/en/dsm?topic=microsoft-365-defender[IBM QRadar Product Documentation], and for more information on Streaming API supported event types, see xref:../defender/supported-event-types.adoc[Supported event types].
____

New customers are no longer being onboarded using the previous QRadar Microsoft Defender ATP Device Support Module (DSM), and existing customers are encouraged to adopt the new Microsoft 365 Defender DSM as their single point of integration with all Microsoft 365 Defender products.

=== Ingesting Microsoft Defender for Endpoint events from the Microsoft 365 Defender event streaming API

Microsoft 365 Defender streaming event data includes alerts and other events from Microsoft Defender for Endpoint and other Microsoft Defender products.
These events may be streamed to an Azure Storage Account or to Azure Event Hubs.
The integration model via event hubs is currently supported by Splunk and IBM QRadar.

For more information, see xref:../defender/configure-siem-defender.adoc[Microsoft 365 Defender SIEM integration].
