= Configure alert notifications that are sent to MSSPs
:audience: ITPro
:author: mjcaparas
:description: Configure alert notifications that are sent to MSSPs
:keywords: managed security service provider, mssp, configure, integration
:manager: dansimp
:ms.author: macapara
:ms.collection: M365-security-compliance
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Configure alert notifications that are sent to MSSPs

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-mssp-support-abovefoldlink[Sign up for a free trial.]
____

____
[!NOTE] This step can be done by either the MSSP customer or MSSP.
MSSPs must be granted the appropriate permissions to configure this on behalf of the MSSP customer.
____

After access the portal is granted, alert notification rules can to be created so that emails are sent to MSSPs when alerts associated with the tenant are created and set conditions are met.

For more information, see link:configure-email-notifications.md#create-rules-for-alert-notifications[Create rules for alert notifications].

These check boxes must be checked:

* *Include organization name* - The customer name will be added to email notifications
* *Include tenant-specific portal link* - Alert link URL will have tenant specific parameter (tid=target_tenant_id) that allows direct access to target tenant portal

=== Related topics

* xref:grant-mssp-access.adoc[Grant MSSP access to the portal]
* xref:access-mssp-portal.adoc[Access the MSSP customer portal]
* xref:fetch-alerts-mssp.adoc[Fetch alerts from customer tenant]
