= Onboard Windows devices to Defender for Endpoint using Intune
:audience: ITPro
:author: mjcaparas
:description: Use Microsoft Intune to deploy the configuration package on devices so that they are onboarded to the Defender for Endpoint service.
:keywords: onboard devices using mdm, device management, onboard Microsoft Defender for Endpoint devices, mdm
:manager: dansimp
:ms.author: macapara
:ms.collection: M365-security-compliance
:ms.custom: admindeeplinkDEFENDER
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Onboard Windows devices to Defender for Endpoint using Intune

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-configureendpointsmdm-abovefoldlink[Sign up for a free trial.]
____

You can use mobile device management (MDM) solutions to configure Windows 10 devices.
Defender for Endpoint supports MDMs by providing OMA-URIs to create policies to manage devices.

For more information on using Defender for Endpoint CSP see, https://msdn.microsoft.com/library/windows/hardware/mt723296(v=vs.85).aspx[WindowsAdvancedThreatProtection CSP] and https://msdn.microsoft.com/library/windows/hardware/mt723297(v=vs.85).aspx[WindowsAdvancedThreatProtection DDF file].

=== Before you begin

Devices must be enrolled with Intune as your Mobile Device Management (MDM) solution.

For more information on enabling MDM with Microsoft Intune, see link:/mem/intune/enrollment/device-enrollment[Device enrollment (Microsoft Intune)].

=== Onboard devices using Microsoft Intune

Check out the https://download.microsoft.com/download/5/6/0/5609001f-b8ae-412f-89eb-643976f6b79c/mde-deployment-strategy.pdf[PDF] or https://download.microsoft.com/download/5/6/0/5609001f-b8ae-412f-89eb-643976f6b79c/mde-deployment-strategy.vsdx[Visio] to see the various paths in deploying Defender for Endpoint.

Follow the instructions from link:/mem/intune/protect/advanced-threat-protection-configure#enable-microsoft-defender-for-endpoint-in-intune[Intune].

For more information on using Defender for Endpoint CSP see, https://msdn.microsoft.com/library/windows/hardware/mt723296(v=vs.85).aspx[WindowsAdvancedThreatProtection CSP] and https://msdn.microsoft.com/library/windows/hardware/mt723297(v=vs.85).aspx[WindowsAdvancedThreatProtection DDF file].

____
[!NOTE]

* The *Health Status for onboarded devices* policy uses read-only properties and can't be remediated.
* Configuration of diagnostic data reporting frequency is only available for devices on Windows 10, version 1703.
* Onboarding to Defender for Endpoint will onboard the device to xref:../../compliance/endpoint-dlp-learn-about.adoc[Data Loss Prevention (DLP)], which is also a part of Microsoft 365 compliance.
____

=== Run a detection test to verify onboarding

After onboarding the device, you can choose to run a detection test to verify that a device is properly onboarded to the service.
For more information, see xref:run-detection-test.adoc[Run a detection test on a newly onboarded Microsoft Defender for Endpoint device].

=== Offboard devices using Mobile Device Management tools

For security reasons, the package used to Offboard devices will expire 30 days after the date it was downloaded.
Expired offboarding packages sent to a device will be rejected.
When downloading an offboarding package you'll be notified of the packages expiry date and it will also be included in the package name.

____
[!NOTE] Onboarding and offboarding policies must not be deployed on the same device at the same time, otherwise this will cause unpredictable collisions.
____

. Get the offboarding package from https://go.microsoft.com/fwlink/p/?linkid=2077139[Microsoft 365 Defender portal]:
 .. In the navigation pane, select *Settings* > *Endpoints* > *Device management* > *Offboarding*.
 .. Select Windows 10 or Windows 11 as the operating system.
 .. In the *Deployment method* field, select *Mobile Device Management / Microsoft Intune*.
 .. Click *Download package*, and save the .zip file.
. Extract the contents of the .zip file to a shared, read-only location that can be accessed by the network administrators who will deploy the package.
You should have a file named _WindowsDefenderATP_valid_until_YYYY-MM-DD.offboarding_.
. Use the Microsoft Intune custom configuration policy to deploy the following supported OMA-URI settings.
 ** OMA-URI: ./Device/Vendor/MSFT/WindowsAdvancedThreatProtection/Offboarding
 ** Date type: String
 ** Value: [Copy and paste the value from the content of the WindowsDefenderATP_valid_until_YYYY-MM-DD.offboarding file]

For more information on Microsoft Intune policy settings, see link:/mem/intune/configuration/custom-settings-windows-10[Windows 10 policy settings in Microsoft Intune].

____
[!NOTE] The *Health Status for offboarded devices* policy uses read-only properties and can't be remediated.
____

____
[!IMPORTANT] Offboarding causes the device to stop sending sensor data to the portal but data from the device, including reference to any alerts it has had will be retained for up to 6 months.
____

=== Related topics

* xref:configure-endpoints-gp.adoc[Onboard Windows devices using Group Policy]
* xref:configure-endpoints-sccm.adoc[Onboard Windows devices using Microsoft Endpoint Configuration Manager]
* xref:configure-endpoints-script.adoc[Onboard Windows devices using a local script]
* xref:configure-endpoints-vdi.adoc[Onboard non-persistent virtual desktop infrastructure (VDI) devices]
* xref:run-detection-test.adoc[Run a detection test on a newly onboarded Microsoft Defender for Endpoint device]
* xref:troubleshoot-onboarding.adoc[Troubleshoot Microsoft Defender for Endpoint onboarding issues]
