= 
denisebmsft

== Configure and validate exclusions for Microsoft Defender Antivirus scans

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] - Microsoft Defender Antivirus

*Platforms* - Windows

You can exclude certain files, folders, processes, and process-opened
files from Microsoft Defender Antivirus scans. Such exclusions apply to
link:scheduled-catch-up-scans-microsoft-defender-antivirus.md[scheduled
scans], link:run-scan-microsoft-defender-antivirus.md[on-demand scans],
and
link:configure-real-time-protection-microsoft-defender-antivirus.md[always-on
real-time protection and monitoring]. Exclusions for process-opened
files only apply to real-time protection.

____
[!TIP] For a detailed overview of suppressions, submissions, and
exclusions across Microsoft Defender Antivirus and Defender for
Endpoint, see link:defender-endpoint-antivirus-exclusions.md[Exclusions
for Microsoft Defender for Endpoint and Microsoft Defender Antivirus].
____

=== Configure and validate exclusions

To configure and validate exclusions, see the following:

* link:configure-extension-file-exclusions-microsoft-defender-antivirus.md[Configure
and validate exclusions based on file name&#44; extension&#44; and folder
location]. You can exclude files from Microsoft Defender Antivirus scans
based on their file extension, file name, or location.
* link:configure-process-opened-file-exclusions-microsoft-defender-antivirus.md[Configure
and validate exclusions for files opened by processes]. You can exclude
files from scans that have been opened by a specific process.

=== Recommendations for defining exclusions

____
[!IMPORTANT] Microsoft Defender Antivirus includes many automatic
exclusions based on known operating system behaviors and typical
management files, such as those used in enterprise management, database
management, and other enterprise scenarios and situations. For more
information, see
link:configure-server-exclusions-microsoft-defender-antivirus.md[automatic
exclusions].

Defining exclusions lowers the protection offered by Microsoft Defender
Antivirus. You should always evaluate the risks that are associated with
implementing exclusions, and you should only exclude files that you are
confident are not malicious.
____

Keep the following points in mind when you are defining exclusions:

* Exclusions are technically a protection gap. Consider all your options
when defining exclusions. Other options can be as simple as making sure
the excluded location has the appropriate access-control lists (ACLs) or
setting policies to audit mode at first.
* Review the exclusions periodically. Recheck and re-enforce mitigations
as part of your review process.
* Ideally, avoid defining exclusions in an effort to be proactive. For
example, don’t exclude something just because you think it might be a
problem in the future. Use exclusions only for specific issues, such as
those pertaining to performance or application compatibility that
exclusions could mitigate.
* Review and audit changes to your list of exclusions. Your security
team should preserve context around why a certain exclusion was added to
avoid confusion later on. Your security team should be able to provide
specific answers to questions about why exclusions exist.

=== Audit Antivirus Exclusions

Exchange has supported integration with the Antimalware Scan Interface
(AMSI) since the June 2021 Quarterly Updates for Exchange. It is highly
recommended to ensure these updates are installed and AMSI is working
using the guidance provided by the Exchange Team as this integration
will allow the best ability for Defender Antivirus to detect and block
exploitation of Exchange.

Many organizations exclude the Exchange directories from antivirus scans
for performance reasons. Microsoft recommends to audit AV exclusions on
Exchange systems and assess if they can be removed without impacting
performance in your environment to ensure the highest level of
protection. Exclusions can be managed by using Group Policy, PowerShell,
or systems management tools like Microsoft Endpoint Configuration
Manager.

To audit AV exclusions on an Exchange Server running Defender Antivirus,
run the *Get-MpPreference* command from an elevated PowerShell prompt.

If exclusions cannot be removed for the Exchange processes and folders,
running a Quick Scan in Defender Antivirus will scan the Exchange
directories and files, regardless of exclusions.

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____

=== See also

* link:configure-server-exclusions-microsoft-defender-antivirus.md[Microsoft
Defender Antivirus exclusions on Windows Server 2016]
* link:common-exclusion-mistakes-microsoft-defender-antivirus.md[Common
mistakes to avoid when defining exclusions]
* link:defender-endpoint-antivirus-exclusions.md[Exclusions for
Microsoft Defender for Endpoint and Microsoft Defender Antivirus]
