= Onboard non-persistent virtual desktop infrastructure (VDI) devices
:audience: ITPro
:author: mjcaparas
:description: Deploy the configuration package on virtual desktop infrastructure (VDI) device so that they are onboarded to Microsoft Defender for Endpoint service.
:keywords: configure virtual desktop infrastructure (VDI) device, vdi, device management, configure Microsoft Defender for Endpoint, endpoints
:manager: dansimp
:ms.author: macapara
:ms.collection: M365-security-compliance
:ms.custom: admindeeplinkDEFENDER
:ms.date: 04/15/2022
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150
:search.product: eADQiWindows 10XVcnh

== Onboard non-persistent virtual desktop infrastructure (VDI) devices in Microsoft 365 Defender

Virtual desktop infrastructure (VDI) is an IT infrastructure concept that lets end users access enterprise virtual desktops instances from almost any device (such as your personal computer, smartphone, or tablet), eliminating the need for organization to provide users with physical machines.
Using VDI devices reduce cost as IT departments are no longer responsible for managing, repairing, and replacing physical endpoints.
Authorized users can access the same company servers, files, apps, and services from any approved device through a secure desktop client or browser.

Like any other system in an IT environment, these too should have an Endpoint Detection and Response (EDR) and Antivirus solution to protect against advanced threats and attacks.

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]
* Virtual desktop infrastructure (VDI) devices
* Windows 10, Windows 11, Windows Server 2019, Windows Server 2022, Windows Server 2008R2/2012R2/2016

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-configvdi-abovefoldlink[Sign up for a free trial.]
____

____
[!NOTE] *Persistent VDI's* - Onboarding a persistent VDI machine into Microsoft Defender for Endpoint is handled the same way you would onboard a physical machine, such as a desktop or laptop.
Group policy, Microsoft Endpoint Manager, and other methods can be used to onboard a persistent machine.
In the Microsoft 365 Defender portal, (https://security.microsoft.com) under onboarding, select your preferred onboarding method, and follow the instructions for that type.
For more information see xref:onboard-windows-client.adoc[Onboarding Windows client].
____

=== Onboarding non-persistent virtual desktop infrastructure (VDI) devices

Defender for Endpoint supports non-persistent VDI session onboarding.

There might be associated challenges when onboarding VDI instances.
The following are typical challenges for this scenario:

* Instant early onboarding of a short-lived session, which must be onboarded to Defender for Endpoint prior to the actual provisioning.
* The device name is typically reused for new sessions.

In a VDI environment, VDI instances can have short lifespans.
VDI devices can appear in Defender for Endpoint portal as either:

* Single portal entry for each VDI instance.
If the VDI instance was already onboarded to Microsoft Defender for Endpoint and at some point deleted then  recreated with the same host name, a new object representing this VDI instance will NOT be created in the portal.
+
____
[!NOTE] In this case, the _same_ device name must be configured when the session is created, for example using an unattended answer file.
____

* Multiple entries for each device - one for each VDI instance.

The following steps will guide you through onboarding VDI devices and will highlight steps for single and multiple entries.

____
[!WARNING] For environments where there are low resource configurations, the VDI boot procedure might slow the Defender for Endpoint sensor onboarding.
____

==== Onboarding steps

____
[!NOTE] Windows Server 2016 and Windows Server 2012 R2 will need to be prepared by applying the installation package first using the instructions in link:/microsoft-365/security/defender-endpoint/configure-server-endpoints#windows-server-2012-r2-and-windows-server-2016[Onboard Windows servers] for this feature to work.
____

. Open the VDI configuration package .zip file (_WindowsDefenderATPOnboardingPackage.zip_) that you downloaded from the service onboarding wizard.
You can also get the package from the https://go.microsoft.com/fwlink/p/?linkid=2077139[Microsoft 365 Defender portal]:
 .. In the navigation pane, select *Settings* > *Endpoints* > *Device management* > *Onboarding*.
 .. Select the operating system.
 .. In the *Deployment method* field, select *VDI onboarding scripts for non-persistent endpoints*.
 .. Click *Download package* and save the .zip file.
. Copy the files from the WindowsDefenderATPOnboardingPackage folder extracted from the .zip file into the golden/master image under the path `C:\WINDOWS\System32\GroupPolicy\Machine\Scripts\Startup`.
 .. If you are implementing multiple entries for each device - one for each session, copy WindowsDefenderATPOnboardingScript.cmd.
 .. If you're implementing a single entry for each device, copy both Onboard-NonPersistentMachine.ps1 and WindowsDefenderATPOnboardingScript.cmd.

+
____
[!NOTE] If you don't see the `C:\WINDOWS\System32\GroupPolicy\Machine\Scripts\Startup` folder, it might be hidden.
You'll need to choose the *Show hidden files and folders* option from File Explorer.
____
. Open a Local Group Policy Editor window and navigate to *Computer Configuration* > *Windows Settings* > *Scripts* > *Startup*.
+
____
[!NOTE] Domain Group Policy may also be used for onboarding non-persistent VDI devices.
____

. Depending on the method you'd like to implement, follow the appropriate steps:
 ** For single entry for each device:
+
Select the *PowerShell Scripts* tab, then click *Add* (Windows Explorer will open directly in the path where you copied the onboarding script earlier).
Navigate to onboarding PowerShell script `Onboard-NonPersistentMachine.ps1`.
There's no need to specify the other file, as it will be triggered automatically.

 ** For multiple entries for each device:
+
Select the *Scripts* tab, then click *Add* (Windows Explorer will open directly in the path where you copied the onboarding script earlier).
Navigate to the onboarding bash script `WindowsDefenderATPOnboardingScript.cmd`.
. Test your solution:
 .. Create a pool with one device.
 .. Log on to device.
 .. Log off from device.
 .. Log on to device with another user.
 .. Depending on the method you'd like to implement, follow the appropriate steps:
  *** For single entry for each device: Check only one entry in Microsoft 365 Defender portal.
  *** For multiple entries for each device: Check multiple entries in Microsoft 365 Defender portal.
. Click *Devices list* on the Navigation pane.
. Use the search function by entering the device name and select *Device* as search type.

=== For downlevel SKUs (Windows Server 2008 R2)

____
[!NOTE] These instructions for other Windows server versions also apply if you are running the previous Microsoft Defender for Endpoint for Windows Server 2016 and Windows Server 2012 R2 that requires the MMA.
Instructions to migrate to the new unified solution are at link:/microsoft-365/security/defender-endpoint/server-migration[Server migration scenarios in Microsoft Defender for Endpoint].
____

____
[!NOTE] The following registry is relevant only when the aim is to achieve a 'Single entry for each device'.
____

. Set registry value to:
+
[,console]
----
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Advanced Threat Protection\DeviceTagging]
 "VDI"="NonPersistent"
----
+
or using command line:
+
[,console]
----
 reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Advanced Threat Protection\DeviceTagging" /v VDI /t REG_SZ /d "NonPersistent" /f
----

. Follow the xref:configure-server-endpoints.adoc[server onboarding process].

=== Updating virtual desktop infrastructure (VDI) images (persistent or non-persistent)

With the ability to easily deploy updates to VMs running in VDIs, we've shortened this guide to focus on how you can get updates on your machines quickly and easily.
You no longer need to create and seal golden images on a periodic basis, as updates are expanded into their component bits on the host server and then downloaded directly to the VM when it's turned on.

For more information, follow the guidance in link:/microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus[Deployment guide for Microsoft Defender Antivirus in a Virtual Desktop Infrastructure (VDI) environment].

____
[!NOTE] If you have onboarded the master image of your VDI environment (SENSE service is running), then you must offboard and clear some data before putting the image back into production.

. Ensure the sensor is stopped by running the command below in a CMD window:
+
[,console]
----
 sc query sense
----

. Run the below commands using PsExec.exe (which can be downloaded from https://download.sysinternals.com/files/PSTools.zip)

[,console]
----
 PsExec.exe -s cmd.exe
 cd "C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\Cyber"
 del *.* /f /s /q
 REG DELETE "HKLM\SOFTWARE\Microsoft\Windows Advanced Threat Protection" /v senseGuid /f
 exit
----
____

=== Other recommended configuration settings

After onboarding devices to the service, it's important to take advantage of the included threat protection capabilities by enabling them with the following recommended configuration settings.

==== Next generation protection configuration

The following configuration settings are recommended:

===== Cloud Protection Service

* Turn on cloud-delivered protection: Yes
* Cloud-delivered protection level: Not configured
* Defender Cloud Extended Timeout In Seconds: 20

===== Exclusions

* Disable local admin merge: Not configured
* Defender processes to exclude:
 ** `%Programfiles%\FSLogix\Apps\frxccd.exe`
 ** `%Programfiles%\FSLogix\Apps\frxccds.exe`
 ** `%Programfiles%\FSLogix\Apps\frxsvc.exe`
* File extensions to exclude from scans and real-time protection:
 ** `%Programfiles%\FSLogix\Apps\frxccd.sys`
 ** `%Programfiles%\FSLogix\Apps\frxdrv.sys`
 ** `%Programfiles%\FSLogix\Apps\frxdrvvt.sys`
 ** `%TEMP%*.VHD`
 ** `%TEMP%*.VHDX`
 ** `%Windir%\TEMP*.VHD`
 ** `%Windir%\TEMP*.VHDX`
 ** `+\\storageaccount.file.core.windows.net\share**.VHD+`
 ** `+\\storageaccount.file.core.windows.net\share**.VHDX+`

===== Real-time Protection

* Turn on all settings and set to monitor all files

===== Remediation

* Number of days to keep quarantined malware: 30
* Submit samples consent: Send all samples automatically
* Action to take on potentially unwanted apps: Enable
* Actions for detected threats:
 ** Low threat: Clean
 ** Moderate threat, High threat, Severe threat: Quarantine

===== Scan

* Scan archived files: Yes
* Use low CPU priority for scheduled scans: Not configured
* Disable catch-up full scan: Not configured
* Disable catchup quick scan: Not configured
* CPU usage limit per scan: 50
* Scan mapped netoword drives during full scan: Not configured
* Run daily quick scan at: 12 PM
* Scan type: Not configured
* Day of week to run scheduled scan: Not configured
* Time of day to run a scheduled scan: Not configured
* Check for signature updates before running scan: Yes

===== Updates

* Enter how often to check for security intelligence updates: 8
* Leave other settings in default state

===== User experience

* Allow user access to Microsoft Defender app: Not configured

===== Enable Tamper protection

* Enable tamper protection to prevent Microsoft Defender being disabled: Enable

===== Attack surface reduction

* Enable network protection: Audit mode
* Require SmartScreen for Microsoft Edge: Yes
* Block malicious site access: Yes
* Block unverified file download: Yes

===== Attack surface reduction rules

* Configure all available rules to Audit.

____
[!NOTE] Blocking these activities may interrupt legitimate business processes.
The best approach is setting everything to audit, identifying which ones are safe to turn on, and then enabling those settings on endpoints which do not have false positive detections.
____

=== Related topics

* xref:configure-endpoints-gp.adoc[Onboard Windows devices using Group Policy]
* xref:configure-endpoints-sccm.adoc[Onboard Windows devices using Microsoft Endpoint Configuration Manager]
* xref:configure-endpoints-mdm.adoc[Onboard Windows devices using Mobile Device Management tools]
* xref:configure-endpoints-script.adoc[Onboard Windows devices using a local script]
* xref:troubleshoot-onboarding.adoc[Troubleshoot Microsoft Defender for Endpoint onboarding issues]
