= 
denisebmsft
:keywords: Microsoft Defender Antivirus, antimalware, security,
defender, configure, configuration, Config Manager, Microsoft Endpoint
Configuration Manager, SCCM, Intune, MDM, mobile device management, GP,
group policy, PowerShell

== Configure Microsoft Defender Antivirus features

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365
Defender]
* Microsoft Defender Antivirus

*Platforms* - Windows

You can configure Microsoft Defender Antivirus with a number of tools,
such as:

* Microsoft Endpoint Manager (which includes Microsoft Intune and
Microsoft Endpoint Configuration Manager)
* Group Policy
* PowerShell cmdlets
* Windows Management Instrumentation (WMI)
* link:/mem/configmgr/tenant-attach/[Tenant attach]

The following broad categories of features can be configured:

* Cloud-delivered protection. See
link:cloud-protection-microsoft-defender-antivirus.md[Cloud-delivered
protection and Microsoft Defender Antivirus]
* Always-on real-time protection, including behavioral, heuristic, and
machine learning-based protection. See
link:configure-protection-features-microsoft-defender-antivirus.md[Configure
behavioral&#44; heuristic&#44; and real-time protection].
* How end users interact with the client on individual endpoints. See
the following resources:
** link:prevent-end-user-interaction-microsoft-defender-antivirus.md[Prevent
users from seeing or interacting with the Microsoft Defender Antivirus
user interface]
** link:configure-local-policy-overrides-microsoft-defender-antivirus.md[Prevent
or allow users to locally modify Microsoft Defender Antivirus policy
settings]

____
{empty}[!TIP] Review
link:configuration-management-reference-microsoft-defender-antivirus.md[Reference
topics for management and configuration tools]. If you’re looking for
Antivirus related information for other platforms, see: -
link:mac-preferences.md[Set preferences for Microsoft Defender for
Endpoint on macOS] - link:microsoft-defender-endpoint-mac.md[Microsoft
Defender for Endpoint on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____

____
[!TIP] *Performance tip* Due to a variety of factors (examples listed
below) Microsoft Defender Antivirus, like other antivirus software, can
cause performance issues on endpoint devices. In some cases, you might
need to tune the performance of Microsoft Defender Antivirus to
alleviate those performance issues. Microsoft’s *Performance analyzer*
is a PowerShell command-line tool that helps determine which files, file
paths, processes, and file extensions might be causing performance
issues; some examples are:

* Top paths that impact scan time
* Top files that impact scan time
* Top processes that impact scan time
* Top file extensions that impact scan time
* Combinations – for example:
** top files per extension
** top paths per extension
** top processes per path
** top scans per file
** top scans per file per process

You can use the information gathered using Performance analyzer to
better assess performance issues and apply remediation actions. See:
link:tune-performance-defender-antivirus.md[Performance analyzer for
Microsoft Defender Antivirus].
____
