= 
denisebmsft
:keywords: group policy, gpo, config manager, sccm, scep, powershell,
wmi, intune, defender, antivirus, antimalware, security, protection

== Manage Microsoft Defender Antivirus in your business

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365
Defender]
* Microsoft Defender Antivirus

*Platforms* - Windows

You can manage and configure Microsoft Defender Antivirus with the
following tools:

* link:tune-performance-defender-antivirus.md[Performance analyzer for
Microsoft Defender Antivirus]
* link:/mem/intune/protect/endpoint-security-antivirus-policy[Microsoft
Intune] (now part of Microsoft Endpoint Manager)
* link:/mem/configmgr/protect/deploy-use/endpoint-protection-configure[Microsoft
Endpoint Configuration Manager] (now part of Microsoft Endpoint Manager)
* link:./use-group-policy-microsoft-defender-antivirus.md[Group Policy]
* link:./use-powershell-cmdlets-microsoft-defender-antivirus.md[PowerShell
cmdlets]
* link:./use-wmi-microsoft-defender-antivirus.md[Windows Management
Instrumentation (WMI)]
* The
link:./command-line-arguments-microsoft-defender-antivirus.md[Microsoft
Malware Protection Command Line Utility] (referred to as the
_mpcmdrun.exe_ utility

The following articles provide further information, links, and resources
for using these tools to manage and configure Microsoft Defender
Antivirus.

[width="100%",cols="<50%,<50%",options="header",]
|===
|Article |Description
|link:use-intune-config-manager-microsoft-defender-antivirus.md[Manage
Microsoft Defender Antivirus with Microsoft Intune and Microsoft
Endpoint Configuration Manager] |Information about using Intune and
Configuration Manager to deploy, manage, report, and configure Microsoft
Defender Antivirus

|link:use-group-policy-microsoft-defender-antivirus.md[Manage Microsoft
Defender Antivirus with Group Policy settings] |List of all Group Policy
settings located in ADMX templates

|link:use-powershell-cmdlets-microsoft-defender-antivirus.md[Manage
Microsoft Defender Antivirus with PowerShell cmdlets] |Instructions for
using PowerShell cmdlets to manage Microsoft Defender Antivirus, plus
links to documentation for all cmdlets and allowed parameters

|link:use-wmi-microsoft-defender-antivirus.md[Manage Microsoft Defender
Antivirus with Windows Management Instrumentation (WMI)] |Instructions
for using WMI to manage Microsoft Defender Antivirus, plus links to
documentation for the WMIv2 APIs (including all classes, methods, and
properties)

|link:command-line-arguments-microsoft-defender-antivirus.md[Manage
Microsoft Defender Antivirus with the MpCmdRun.exe command-line tool]
|Instructions on using the dedicated command-line tool to manage and use
Microsoft Defender Antivirus
|===

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____
