= 
mjcaparas
:keywords: support, contact, premier support, solutions, problems, case

== Contact Microsoft Defender for Endpoint support

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-assignaccess-abovefoldlink[Sign
up for a free trial.]
____

Defender for Endpoint has recently upgraded the support process to offer
a more modern and advanced support experience.

The new widget allows customers to:

* Find solutions to common problems
* Submit a support case to the Microsoft support team

=== Prerequisites

It’s important to know the specific roles that have permission to open
support cases.

At a minimum, you must have a Service Support Administrator *OR*
Helpdesk Administrator role.

For more information on which roles have permission, see,
link:/azure/active-directory/roles/permissions-reference#security-administrator[Security
Administrator permissions]. Roles that include the action
`microsoft.office365.supportTickets/allEntities/allTasks` can submit a
case.

For general information on admin roles, see
link:/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide&preserve-view=true[About
admin roles].

=== Access the widget

Accessing the new support widget can be done in one of two ways:

[arabic]
. Clicking on the question mark on the top right of the portal and then
clicking on ``Microsoft support'':
+
:::image type=``content'' source=``../../media/contactsupport.png''
alt-text=``The Microsoft support icon in the Microsoft 365 Defender
portal'' lightbox=``../../media/contactsupport.png'':::
. Clicking on the *Need help?* button in the bottom right of the
Microsoft 365 Defender portal:
+
:::image type=``content'' source=``images/need-help-option.png''
alt-text=``The Need help button''
lightbox=``images/need-help-option.png'':::

In the widget you’ll be offered two options:

* Find solutions to common problems
* Open a service request

=== Find solutions to common problems

This option includes articles that might be related to the question you
may ask. Just start typing the question in the search box and articles
related to your search will be surfaced.

:::image type=``content'' source=``../../media/contactsupport1.png''
alt-text=``How can we help?''
lightbox=``../../media/contactsupport1.png'':::

In case the suggested articles aren’t sufficient, you can open a service
request.

=== Open a service request

Learn how to open support tickets by contacting Defender for Endpoint
support.

____
[!NOTE] If you have a premier support contract with Microsoft, you’ll
see the premier tag on the widget. If not, contact your Microsoft
account manager.
____

==== Contact support

:::image type=``content'' source=``../../media/contactsupport2.png''
alt-text=``The contact support 2''
lightbox=``../../media/contactsupport2.png'':::

[arabic]
. Fill in a title and description for the issue you are facing, the
phone number and email address where we may reach you.
. (Optional) Include up to five attachments that are relevant to the
issue to provide additional context for the support case.
. Select your time zone and an alternative language, if applicable. The
request will be sent to Microsoft Support Team. The team will respond to
your service request shortly.

=== Related topics

* link:troubleshoot-mdatp.md[Troubleshoot service issues]
* link:/microsoft-365/enterprise/view-service-health[Check service
health]
