= 
siosulli
:keywords: enable siem connector, siem, connector, security information
and events

== Enable Corelight as data source in Microsoft Defender for Endpoint

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365
Defender]

{empty}[!includelink:../../includes/prerelease.md[Prerelease
information]]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-enablesiem-abovefoldlink[Sign
up for a free trial.]
____

Microsoft has partnered with
https://corelight.com/integrations/iot-security[Corelight], provider of
the industry’s leading open network detection and response (NDR)
platform, to help you discover IoT/OT devices across your organization.
Using data, sent from Corelight network appliances, Microsoft 365
Defender gains increased visibility into the network activities of
unmanaged devices, including communication with other unmanaged devices
or external networks.

With this data source enabled, all events from Corelight network
appliances are sent to Microsoft 365 Defender. You can view these
activities in the unmanaged devices timeline, available in the Microsoft
Defender for Endpoint device inventory. For more information, see
link:device-discovery.md[Device discovery].

=== Prerequisites

[arabic]
. To setup the Corelight data integration, the user must have the
following roles:
* Tenant Global Administrator in Azure Active Directory
* Security Administrator for the Azure subscription that will be used
for the Microsoft Defender for IoT integration
. An onboarded Defender for IoT plan. For more information, see
link:/azure/defender-for-iot/organizations/eiot-defender-for-endpoint/[Enable
Enterprise IoT security with Defender for Endpoint].

=== Enabling the Corelight integration

To enable the Corelight integration, you’ll need to take the following
steps:

link:#step-1-turn-on-corelight-as-a-data-source[Step 1: Turn on
Corelight as a data source]
link:#step-2-provide-permission-for-corelight-to-send-events-to-microsoft-365-defender[Step
2: Provide permission for Corelight to send events to Microsoft 365
Defender]
link:#step-3-configure-your-corelight-appliance-to-send-data-to-microsoft-365-defender[Step
3: Configure your Corelight appliance to send data to Microsoft 365
Defender]

==== Step 1: Turn on Corelight as a data source

[arabic]
. In the navigation pane of the
https://security.microsoft.com/[https://security.microsoft.com] portal,
select *Settings* > *Device discovery* > *Data sources*.
+
:::image type=``content''
source=``../../media/defender-endpoint/enable-corelight.png''
alt-text=``The data sources page in the Microsoft 365 Defender portal''
lightbox=``../../media/defender-endpoint/enable-corelight.png'':::
. Select *Send Corelight data to M365D* and select *Save*.

==== Step 2: Provide permission for Corelight to send events to Microsoft 365 Defender

____
[!NOTE] You must be a global admin to grant Corelight permission to
access resources in your organization.
____

[arabic]
. As a Tenant Global Administrator, go to this
https://login.microsoftonline.com/common/oauth2/authorize?prompt=consent&client_id=d8be544e-9d1a-4825-a5cb-fb447457f692&response_type=code&sso_reload=true[link]
to grant permission.
. Go to https://security.microsoft.com/[https://security.microsoft.com]
portal, select *Settings* > *Microsoft 365 Defender*, and take note of
the *Tenant ID*. You’ll need this information when configuring your
Corelight appliance.

==== Step 3: Configure your Corelight appliance to send data to Microsoft 365 Defender

____
[!NOTE] The integration is available in Corelight Sensor software v25
and later.

You will need internet connectivity for your sensor to reach both the
Defender and Corelight cloud services for the solution to work.
____

===== Enable the integration in the Corelight web interface

[arabic]
. In the Corelight web interface, navigate to *Sensor* > *Export*.
+
:::image type=``content'' source=``images/exporttodefender.png''
alt-text=``The kafka export''
lightbox=``images/exporttodefender.png'':::
. Enable *Export To Microsoft Defender*.
. Enter your Microsoft 356 Defender Tenant ID.
. Optionally, you can:
* set the *Zeek Logs to Exclude*. The minimal set of logs you must
include are: dns, conn, files, http, ssl, ssh, x509, snmp, smtp, ftp,
sip, dhcp, and notice.
* choose to create a *Microsoft Defender Log Filter*.
. Select *Apply Changes*.

===== Enable the integration in the corelight-client

[arabic]
. Enable *Export To Microsoft Defender* using the following command in
the corelight-client:
+
[source,command]
----
corelight-client configuration update \
--bro.export.defender.enable True
----
. Set your tenant ID
. Optionally, you can use the following command to exclude certain logs
or to create a Microsoft Defender log filter. The minimal set of logs
you must include are: dns, conn, files, http, ssl, ssh, x509, snmp,
smtp, ftp, sip, dhcp, and notice.
+
[source,command]
----
  corelight-client configuration update \
 --bro.export.defender.exclude=<logs_to_exclude> \
 --bro.export.defender.filter=<logs_to_filter>
----

=== See also

* link:device-discovery-faq.md[Device discovery FAQ]
