= 
mjcaparas
:keywords: apis, graph api, supported apis, get, alert, information, id

== Create alert API

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Creates new link:alerts.md[Alert] on top of *Event*.

* *Microsoft Defender for Endpoint Event* is required for the alert
creation.
* You need to supply three parameters from the Event in the request:
*Event Time*, *Machine ID*, and *Report ID*. See example below.
* You can use an event found in Advanced Hunting API or Portal.
* If there existing an open alert on the same Device with the same
Title, the new created alert will be merged with it.
* An automatic investigation starts automatically on alerts created via
the API.

=== Limitations

[arabic]
. Rate limitations for this API are 15 calls per minute.

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Microsoft Defender for Endpoint APIs]

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Alert.ReadWrite.All |`Read and write all alerts'

|Delegated (work or school account) |Alert.ReadWrite |`Read and write
alerts'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to have at least the following role permission: `Alerts
investigation' (For more information see link:user-roles.md[Create and
manage roles])
* The user needs to have access to the device associated with the alert,
based on device group settings (For more information, see
link:machine-groups.md[Create and manage device groups]

Device Group creation is supported in both Defender for Endpoint Plan 1
and Plan 2
____

=== HTTP request

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/alerts/CreateAlertByReference
----

=== Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|Content-Type |String |application/json. *Required*.
|===

=== Request body

In the request body, supply the following values (all are required):

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Property |Type |Description
|eventTime |DateTime(UTC) |The precise time of the event as string, as
obtained from advanced hunting. e.g., `2018-08-03T16:45:21.7115183Z`
*Required*.

|reportId |String |The reportId of the event, as obtained from advanced
hunting. *Required*.

|machineId |String |Id of the device on which the event was identified.
*Required*.

|severity |String |Severity of the alert. The property values are:
`Low', `Medium' and `High'. *Required*.

|description |String |Description of the alert. *Required*.

|recommendedAction |String |Security officer needs to take this action
when analyzing the alert. *Required*.

|category |String |Category of the alert. The property values are:
``General'', ``CommandAndControl'', ``Collection'',
``CredentialAccess'', ``DefenseEvasion'', ``Discovery'',
``Exfiltration'', ``Exploit'', ``Execution'', ``InitialAccess'',
``LateralMovement'', ``Malware'', ``Persistence'',
``PrivilegeEscalation'', ``Ransomware'', ``SuspiciousActivity''
*Required*.
|===

=== Response

If successful, this method returns 200 OK, and a new
link:alerts.md[alert] object in the response body. If event with the
specified properties (_reportId_, _eventTime_ and _machineId_) was not
found - 404 Not Found.

=== Example

==== Request

Here’s an example of the request.

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/alerts/CreateAlertByReference
----

[source,json]
----
{
    "machineId": "1e5bc9d7e413ddd7902c2932e418702b84d0cc07",
    "severity": "Low",
    "title": "example",
    "description": "example alert",
    "recommendedAction": "nothing",
    "eventTime": "2018-08-03T16:45:21.7115183Z",
    "reportId": "20776",
    "category": "Exploit"
}
----
