= Create alert from event API
:audience: ITPro
:author: mjcaparas
:description: Learn how to use the Create alert API to create a new Alert on top of Event in Microsoft Defender for Endpoint.
:keywords: apis, graph api, supported apis, get, alert, information, id
:manager: dansimp
:ms.author: macapara
:ms.collection: M365-security-compliance
:ms.custom: api
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Create alert API

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign up for a free trial.]
____

[!includexref:../../includes/microsoft-defender-api-usgov.adoc[Microsoft Defender for Endpoint API URIs for US Government]]

[!includexref:../../includes/improve-request-performance.adoc[Improve request performance]]

=== API description

Creates new xref:alerts.adoc[Alert] on top of *Event*.

* *Microsoft Defender for Endpoint Event* is required for the alert creation.
* You need to supply three parameters from the Event in the request: *Event Time*, *Machine ID*, and *Report ID*.
See example below.
* You can use an event found in Advanced Hunting API or Portal.
* If there existing an open alert on the same Device with the same Title, the new created alert will be merged with it.
* An automatic investigation starts automatically on alerts created via the API.

=== Limitations

. Rate limitations for this API are 15 calls per minute.

=== Permissions

One of the following permissions is required to call this API.
To learn more, including how to choose permissions, see xref:apis-intro.adoc[Use Microsoft Defender for Endpoint APIs]

|===
| Permission type | Permission | Permission display name

| Application
| Alert.ReadWrite.All
| 'Read and write all alerts'

| Delegated (work or school account)
| Alert.ReadWrite
| 'Read and write alerts'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to have at least the following role permission: 'Alerts investigation' (For more information see xref:user-roles.adoc[Create and manage roles] )
* The user needs to have access to the device associated with the alert, based on device group settings (For more information, see xref:machine-groups.adoc[Create and manage device groups]

Device Group creation is supported in both Defender for Endpoint Plan 1 and Plan 2
____

=== HTTP request

[,http]
----
POST https://api.securitycenter.microsoft.com/api/alerts/CreateAlertByReference
----

=== Request headers

|===
| Name | Type | Description

| Authorization
| String
| Bearer \{token}.
*Required*.

| Content-Type
| String
| application/json.
*Required*.
|===

=== Request body

In the request body, supply the following values (all are required):

|===
| Property | Type | Description

| eventTime
| DateTime(UTC)
| The precise time of the event as string, as obtained from advanced hunting.
e.g.,  `2018-08-03T16:45:21.7115183Z` *Required*.

| reportId
| String
| The reportId of the event, as obtained from advanced hunting.
*Required*.

| machineId
| String
| Id of the device on which the event was identified.
*Required*.

| severity
| String
| Severity of the alert.
The property values are: 'Low', 'Medium' and 'High'.
*Required*.

| title
| String
| Title for the alert.
*Required*.

| description
| String
| Description of the alert.
*Required*.

| recommendedAction
| String
| Security officer needs to take this action when analyzing the alert.
*Required*.

| category
| String
| Category of the alert.
The property values are: "General", "CommandAndControl", "Collection", "CredentialAccess", "DefenseEvasion", "Discovery", "Exfiltration", "Exploit", "Execution", "InitialAccess", "LateralMovement", "Malware", "Persistence", "PrivilegeEscalation", "Ransomware", "SuspiciousActivity" *Required*.
|===

=== Response

If successful, this method returns 200 OK, and a new xref:alerts.adoc[alert] object in the response body.
If event with the specified properties (_reportId_, _eventTime_ and _machineId_) was not found - 404 Not Found.

=== Example

==== Request

Here's an example of the request.

[,http]
----
POST https://api.securitycenter.microsoft.com/api/alerts/CreateAlertByReference
----

[,json]
----
{
    "machineId": "1e5bc9d7e413ddd7902c2932e418702b84d0cc07",
    "severity": "Low",
    "title": "example",
    "description": "example alert",
    "recommendedAction": "nothing",
    "eventTime": "2018-08-03T16:45:21.7115183Z",
    "reportId": "20776",
    "category": "Exploit"
}
----
