= 
mjcaparas
:keywords: data, storage, settings, retention, update

== Verify data storage location and update data retention settings for Microsoft Defender for Endpoint

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-gensettings-abovefoldlink[Sign
up for a free trial.]
____

During the onboarding process, a wizard takes you through the data
storage and retention settings of Defender for Endpoint.

After completing the onboarding, you can verify your selection in the
data retention settings page.

=== Verify data storage location

During the link:production-deployment.md[Set up phase], you would have
selected the location to store your data.

You can verify the data location by navigating to *Settings* >
*Endpoints* > *Data retention* (under *General*).

=== Update data retention settings

You can update the data retention settings. By default, the retention
period is 180 days.

[arabic]
. In the navigation pane, select *Settings* > *Endpoints* > *Data
retention* (under *General*).
. Select the data retention duration from the drop-down list.
+
____
[!NOTE] Other settings are not editable.
____
. Click *Save preferences*.

=== Related topics

* link:data-retention-settings.md[Update data retention settings]
* link:configure-email-notifications.md[Configure alert notifications in
Defender for Endpoint]
* link:advanced-features.md[Configure advanced features]
