= 
dansimp
:keywords: Microsoft Defender for Endpoint, protected folder access
blocked, detect suspicious files, detect suspicious apps,

== Controlled folder access (CFA) demonstration test tool (block script)

Controlled Folder Access helps you protect valuable data from malicious
apps and threats, such as ransomware. All apps (any executable file,
including .exe, .scr, .dll files and others) are assessed by Microsoft
Defender Antivirus, which then determines if the app is malicious or
safe. If the app is determined to be malicious or suspicious, then it
will not be allowed to make changes to any files in any protected
folder.

=== Scenario requirements and setup

* Windows 10 1709 build 16273
* Microsoft Defender Antivirus (active mode)

=== PowerShell commands

[source,powershell]
----
Set-MpPreference -EnableControlledFolderAccess <State>
----

=== Rule states

[cols="<,<,<",options="header",]
|===
|State |Mode |Numeric value
|Disabled |= Off |0
|Enabled |= Block mode |1
|Audit |= Audit mode |2
|===

==== Verify configuration

[source,powershell]
----
Get-MpPreference
----

=== Scenario

==== Setup

Download and run this
https://demo.wd.microsoft.com/Content/CFA_SetupScript.zip[setup script].
Before running the script set execution policy to Unrestricted using
this PowerShell command:

[source,powershell]
----
Set-ExecutionPolicy Unrestricted
----

You can perform these manual steps instead:

[arabic]
. Turn on CFA using powershell command:

[source,powershell]
----
Set-MpPreference -EnableControlledFolderAccess Enabled
----

[arabic, start=2]
. Download the CFA
https://demo.wd.microsoft.com/Content/CFAtool.exe[test tool]
. Execute the PowerShell commands above

=== Scenario: Use the CFA test tool to simulate an untrusted process writing to a protected folder

[arabic]
. Launch CFA test tool
. Select the desired folder and create file

* You can find more information
link:/microsoft-365/security/defender-endpoint/evaluate-controlled-folder-access[here].

=== Clean-up

Download and run this
https://demo.wd.microsoft.com/Content/ASR_CFA_CleanupScript.zip[cleanup
script]. You can perform these manual steps instead:

[source,powershell]
----
Set-MpPreference -EnableControlledFolderAccess Disabled
----

=== See also

link:/windows/threat-protection/windows-defender-exploit-guard/controlled-folders-exploit-guard[Controlled
folder access]
