= 
dansimp
:keywords: Microsoft Defender for Endpoint, Microsoft Defender ATP,
virus protection, virus detection, virus deletion,

== Cloud-delivered protection demonstration

Cloud-delivered protection for Microsoft Defender Antivirus, also
referred to as Microsoft Advanced Protection Service (MAPS), provides
you with strong, fast protection in addition to our standard real-time
protection.

=== Scenario requirements and setup

* Windows 7, Windows 8.1, Windows 10, Windows 11
* Microsoft Defender Real-time protection is enabled
* Cloud-delivered protection is enabled by default, however you may need
to re-enable it if it has been disabled as part of previous
organizational policies. For more information, see
link:/windows/threat-protection/windows-defender-antivirus/enable-cloud-protection-windows-defender-antivirus?ocid=wd-av-demo-cloud-middle[Enable
cloud-delivered protection in Microsoft Defender Antivirus].
* You can also download and use the
https://www.powershellgallery.com/packages/WindowsDefender_InternalEvaluationSettings/[PowerShell
script] to enable this setting and others on Windows 10 and Windows 11.

==== Scenario

[arabic]
. Download the https://aka.ms/ioavtest[test file]. Important: The test
file isn’t malicious, it’s just a harmless file simulating a virus.
. If you see file blocked by Microsoft Defender SmartScreen, select on
``View downloads'' button.
+
:::image type=``content''
source=``images/cloud-delivered-protection-smartscreen-block.png''
alt-text=``SmartScreen blocks an unsafe download, and provides a button
to select to view the *Downloads* list details.'':::
. In Downloads menu right select on the blocked file and select on
*Download unsafe file*.
+
:::image type=``content''
source=``images/cloud-delivered-protection-smartscreen-block-view-downloads.png''
alt-text=``Lists the download as unsafe, but provides an option to
proceed with the download'':::
. You should see that ``Microsoft Defender Antivirus'' found a virus and
deleted it.
+
____
{empty}[!NOTE]

In some cases, you might also see *Threat Found* notification from
Microsoft Defender Security Center.
____
+
:::image type=``content''
source=``images/cloud-delivered-protection-smartscreen-threat-found-notification.png''
alt-text=``Microsoft Defender Antivirus Threats found notification
provides options to get details'':::
. If the file executes, or if you see that it was blocked by Microsoft
Defender SmartScreen, cloud-delivered protection isn’t working. For more
information, see
link:/windows/threat-protection/windows-defender-antivirus/configure-network-connections-windows-defender-antivirus?ocid=wd-av-demo-cloud-middle[Configure
and validate network connections for Microsoft Defender Antivirus].

=== See also

link:/windows/threat-protection/windows-defender-antivirus/utilize-microsoft-cloud-protection-windows-defender-antivirus?ocid=wd-av-demo-cloud-bottom[Utilize
Microsoft cloud-delivered protection in Microsoft Defender Antivirus]

link:defender-endpoint-demonstrations.md[Microsoft Defender for Endpoint
- demonstration scenarios]
