= 
dansimp
:keywords: Microsoft Defender for Endpoint, Controlled folder access
protection, Controlled folder access demonstration

== Controlled folder access (CFA) demonstrations (block ransomware)

Controlled Folder Access helps you protect valuable data from malicious
apps and threats, such as ransomware. All apps (any executable file,
including .exe, .scr, .dll files and others) are assessed by Microsoft
Defender Antivirus, which then determines if the app is malicious or
safe. If the app is determined to be malicious or suspicious, then it
will not be allowed to make changes to any files in any protected
folder.

=== Scenario requirements and setup

* Windows 10 1709 build 16273
* Microsoft Defender Antivirus (active mode)

=== PowerShell commands

[source,powershell]
----
Set-MpPreference -EnableControlledFolderAccess (State)
----

[source,powershell]
----
Set-MpPreference -ControlledFolderAccessProtectedFolders C:\demo\
----

=== Rule states

[cols="<,<,<",options="header",]
|===
|State |Mode |Numeric value
|Disabled |= Off |0
|Enabled |= Block mode |1
|Audit |= Audit mode |2
|===

=== Verify configuration

[source,powershell]
----
Get-MpPreference
----

=== Test file

https://demo.wd.microsoft.com/Content/ransomware_testfile_unsigned.exe[CFA
ransomware test file]

=== Scenarios

==== Setup

Download and run this
https://demo.wd.microsoft.com/Content/CFA_SetupScript.zip[setup script].
Before running the script set execution policy to Unrestricted using
this PowerShell command:

[source,powershell]
----
Set-ExecutionPolicy Unrestricted
----

You can perform these manual steps instead:

[arabic]
. Create a folder under c: named demo, ``c:''
. Save this
https://demo.wd.microsoft.com/Content/testfile_safe.txt[clean file] into
c:(we need something to encrypt)
. Execute PowerShell commands above

==== Scenario 1: CFA blocks ransomware test file

[arabic]
. Turn on CFA using PowerShell command:

[source,powershell]
----
Set-MpPreference -EnableControlledFolderAccess Enabled
----

[arabic, start=2]
. Add the demo folder to protected folders list using PowerShell
command:

[source,powershell]
----
Set-MpPreference -ControlledFolderAccessProtectedFolders C:\demo\
----

[arabic, start=3]
. Download the ransomware
https://demo.wd.microsoft.com/Content/ransomware_testfile_unsigned.exe[test
file]
. Execute the ransomware test file *this isn’t ransomware, it simple
tries to encrypt c:

===== Scenario 1 expected results

5 seconds after executing the ransomware test file you should see a
notification CFA blocked the encryption attempt.

==== Scenario 2: What would happen without CFA

[arabic]
. Turn off CFA using this PowerShell command:

[source,powershell]
----
Set-MpPreference -EnableControlledFolderAccess Disabled
----

[arabic, start=2]
. Execute the ransomware
https://demo.wd.microsoft.com/Content/ransomware_testfile_unsigned.exe[test
file]

===== Scenario 2 expected results

* The files in c:will be encrypted and you should get a warning message
* Execute the ransomware test file again to decrypt the files

=== Clean-up

Download and run this
https://demo.wd.microsoft.com/Content/ASR_CFA_CleanupScript.zip[cleanup
script]. You can perform these manual steps instead:

[source,powershell]
----
Set-MpPreference -EnableControlledFolderAccess Disabled
----

Cleanup c:encryption run the
https://demo.wd.microsoft.com/Content/ransomware_cleanup_encrypt_decrypt.exe[encrypt/decrypt
file]

=== See also

link:/windows/threat-protection/windows-defender-exploit-guard/controlled-folders-exploit-guard?ocid=wd-av-demo-cfa-bottom[Controlled
folder access]
