= 
dansimp
:keywords: Microsoft Defender for Endpoint, phishing website, malware
website, app reputation,

== SmartScreen app reputation demonstration

Test how Microsoft Defender for Endpoint SmartScreen helps you identify
phishing and malware websites based on App reputation.

=== Scenario requirements and setup

* Windows 10
* Internet Explorer or Microsoft Edge browser required
* To turn ON/OFF, go to *Settings* > *Update & Security* > *Windows
Security* > *Open Windows Security* > *App & browser control* > *Check
apps and files*

=== Scenario Demos

==== Known good program

This program has a good reputation; the download should run
uninterrupted:

* https://demo.smartscreen.msft.net/download/known/freevideo.exe[Known
good program download]
+
Launching this link should render a message similar to the following:
+
:::image type=``content''
source=``images/smartscreen-app-reputation-known-good.png''
alt-text=``Based on the target file’s reputation, SmartScreen allows the
download without interference.'':::

==== Unknown program

Because the program download doesn’t have sufficient reputation to
ensure that it’s trustworthy, SmartScreen will show a warning before
running the program download.

* https://demo.smartscreen.msft.net/download/unknown/freevideo.exe[Unknown
program]
+
Launching this link should render a message similar to the following:
+
:::image type=``content''
source=``images/smartscreen-app-reputation-unknown.png''
alt-text=``SmartScreen doesn’t have sufficient reputation information
about the download file, and warns the user to stop or proceed with
caution.'':::

==== Known malware

This download is known malware; SmartScreen should block this program
from running.

* https://demo.smartscreen.msft.net/download/known/knownmalicious.exe[Known
malware]
+
Launching this link should render a message similar to the following:
+
:::image type=``content''
source=``images/smartscreen-app-reputation-known-malware.png''
alt-text=``Screenshot showing how SmartScreen detects a file download
with an unsafe reputation.; the download is blocked.'':::

=== Learn more

link:/windows/security/threat-protection/windows-defender-smartscreen/windows-defender-smartscreen-overview.md[Microsoft
Defender SmartScreen Documentation]

=== See also

link:defender-endpoint-demonstrations.md[Microsoft Defender for Endpoint
- demonstration scenarios]
