= 
mjcaparas
:keywords: windows defender compatibility, defender, Microsoft Defender
for Endpoint, defender for endpoint, antivirus, mde

== Antivirus solution compatibility with Microsoft Defender for Endpoint

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-defendercompat-abovefoldlink[Sign
up for a free trial.]
____

The Microsoft Defender for Endpoint agent depends on Microsoft Defender
Antivirus for some capabilities such as file scanning.

____
[!IMPORTANT] Defender for Endpoint does not adhere to the Microsoft
Defender Antivirus Exclusions settings.
____

You must configure Security intelligence updates on the Defender for
Endpoint devices whether Microsoft Defender Antivirus is the active
anti-malware or not. For more information, see
link:manage-updates-baselines-microsoft-defender-antivirus.md[Manage
Microsoft Defender Antivirus updates and apply baselines].

If an onboarded device is protected by a third-party anti-malware
client, Microsoft Defender Antivirus on that endpoint will enter into
passive mode.

Microsoft Defender Antivirus will continue to receive updates, and the
_mspeng.exe_ process will be listed as a running a service. But, it
won’t perform scans and doesn’t replace the running third-party
anti-malware client.

The Microsoft Defender Antivirus interface will be disabled. Users on
the device won’t be able to use Microsoft Defender Antivirus to perform
on-demand scans or configure most options.

For more information, see the
link:microsoft-defender-antivirus-compatibility.md[Microsoft Defender
Antivirus and Defender for Endpoint compatibility topic].
