= 
mjcaparas
:keywords: deploy, rings, evaluate, pilot, insider fast, insider slow,
setup, onboard, phase, deployment, deploying, adoption, configuring

== Deploy Microsoft Defender for Endpoint in rings

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-assignaccess-abovefoldlink[Sign
up for a free trial.]
____

Deploying Microsoft Defender for Endpoint can be done using a ring-based
deployment approach.

The deployment rings can be applied in the following scenarios:

* link:#new-deployments[New deployments]
* link:#existing-deployments[Existing deployments]

=== New deployments

:::image type=``content'' source=``images/deployment-rings.png''
alt-text=``The deployment rings.''
lightbox=``images/deployment-rings.png'':::

A ring-based approach is a method of identifying a set of endpoints to
onboard and verifying that certain criteria is met before proceeding to
deploy the service to a larger set of devices. You can define the exit
criteria for each ring and ensure that they are satisfied before moving
on to the next ring.

Adopting a ring-based deployment helps reduce potential issues that
could arise while rolling out the service. By piloting a certain number
of devices first, you can identify potential issues and mitigate
potential risks that might arise.

Table 1 provides an example of the deployment rings you might use.

*Table 1*:

[width="100%",cols="50%,50%",options="header",]
|===
|Deployment ring |Description
|Evaluate |Ring 1: Identify 50 systems for pilot testing

|Pilot |Ring 2: Identify the next 50-100 endpoints in production
environment

|Full deployment |Ring 3: Roll out service to the rest of environment in
larger increments
|===

==== Exit criteria

An example set of exit criteria for these rings can include:

* Devices show up in the device inventory list
* Alerts appear in dashboard
* link:run-detection-test.md[Run a detection test]
* link:attack-simulations.md[Run a simulated attack on a device]

==== Evaluate

Identify a small number of test machines in your environment to onboard
to the service. Ideally, these machines would be fewer than 50
endpoints.

==== Pilot

Microsoft Defender for Endpoint supports a variety of endpoints that you
can onboard to the service. In this ring, identify several devices to
onboard and based on the exit criteria you define, decide to proceed to
the next deployment ring.

The following table shows the supported endpoints and the corresponding
tool you can use to onboard devices to the service.

[width="100%",cols="50%,50%",options="header",]
|===
|Endpoint |Deployment tool
|*Windows* |link:configure-endpoints-script.md[Local script (up to 10
devices)] NOTE: If you want to deploy more than 10 devices in a
production environment, use the Group Policy method instead or the other
supported tools listed below. link:configure-endpoints-gp.md[Group
Policy] link:configure-endpoints-mdm.md[Microsoft Endpoint Manager/
Mobile Device Manager] link:configure-endpoints-sccm.md[Microsoft
Endpoint Configuration Manager] link:configure-endpoints-vdi.md[VDI
scripts]

|*macOS* |link:mac-install-manually.md[Local script]
link:mac-install-with-intune.md[Microsoft Endpoint Manager]
link:mac-install-with-jamf.md[JAMF Pro]
link:mac-install-with-other-mdm.md[Mobile Device Management]

|*Linux Server* |link:linux-install-manually.md[Local script]
link:linux-install-with-puppet.md[Puppet]
link:linux-install-with-ansible.md[Ansible]

|*iOS* |link:ios-install.md[Microsoft Endpoint Manager]

|*Android* |link:android-intune.md[Microsoft Endpoint Manager]
|===

==== Full deployment

At this stage, you can use the link:deployment-strategy.md[Plan
deployment] material to help you plan your deployment.

Use the following material to select the appropriate Microsoft Defender
for Endpoint architecture that best suites your organization.

[width="100%",cols="50%,50%",options="header",]
|===
|Item |Description
|https://github.com/MicrosoftDocs/microsoft-365-docs/raw/public/microsoft-365/security/defender-endpoint/downloads/mdatp-deployment-strategy.pdf[:::image
type=``content'' source=``images/mde-deployment-strategy.png''
alt-text=``The strategy for Microsoft Defender for Endpoint
deployment.'' lightbox=``images/mde-deployment-strategy.png'':::]
https://download.microsoft.com/download/5/6/0/5609001f-b8ae-412f-89eb-643976f6b79c/mde-deployment-strategy.pdf[PDF]
|
https://download.microsoft.com/download/5/6/0/5609001f-b8ae-412f-89eb-643976f6b79c/mde-deployment-strategy.vsdx[Visio]
|The architectural material helps you plan your deployment for the
following architectures:
|===

=== Existing deployments

==== Windows endpoints

For Windows and/or Windows Servers, you select several machines to test
ahead of time (before patch Tuesday) by using the *Security Update
Validation program (SUVP)*.

For more information, see:

* https://techcommunity.microsoft.com/t5/windows-it-pro-blog/what-is-the-security-update-validation-program/ba-p/275767[What
is the Security Update Validation Program]
* https://www.microsoft.com/security/blog/2012/03/28/software-update-validation-program-and-microsoft-malware-protection-center-establishment-twc-interactive-timeline-part-4/[Software
Update Validation Program and Microsoft Malware Protection Center
Establishment - TwC Interactive Timeline Part 4]

==== Non-Windows endpoints

With macOS and Linux, you could take a couple of systems and run in the
Beta channel.

____
[!NOTE] Ideally at least one security admin and one developer so that
you are able to find compatibility, performance and reliability issues
before the build makes it into the Current channel.
____

The choice of the channel determines the type and frequency of updates
that are offered to your device. Devices in Beta are the first ones to
receive updates and new features, followed later by Preview and lastly
by Current.

:::image type=``content'' source=``images/insider-rings.png''
alt-text=``The insider rings.'' lightbox=``images/insider-rings.png'':::

In order to preview new features and provide early feedback, it is
recommended that you configure some devices in your enterprise to use
either Beta or Preview.

____
[!WARNING] Switching the channel after the initial installation requires
the product to be reinstalled. To switch the product channel: uninstall
the existing package, re-configure your device to use the new channel,
and follow the steps in this document to install the package from the
new location.
____
