= 
denisebmsft
:keywords: deploy, manage, update, protection, Microsoft Defender
Antivirus

== Deploy, manage, and report on Microsoft Defender Antivirus

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 2]
* Microsoft Defender Antivirus

*Platforms*

* Windows

You can deploy, manage, and report on Microsoft Defender Antivirus in
many ways.

Because the Microsoft Defender Antivirus client is installed as a core
part of Windows 10 and Windows 11, traditional deployment of a client to
your endpoints doesn’t apply.

However, in most cases you’ll still need to enable the protection
service on your endpoints with Microsoft Intune, Microsoft Endpoint
Configuration Manager, Microsoft Defender for Cloud, or Group Policy
Objects, which is described in the following table.

You’ll also see other links for:

* Managing Microsoft Defender Antivirus protection, including managing
product and protection updates
* Reporting on Microsoft Defender Antivirus protection

____
[!IMPORTANT] In most cases, Windows 10 or Windows 11 will disable
Microsoft Defender Antivirus if it finds another antivirus product that
is running and up-to-date. You must disable or uninstall third-party
antivirus products before Microsoft Defender Antivirus will function. If
you re-enable or install third-party antivirus products, then Windows 10
or Windows 11 automatically disables Microsoft Defender Antivirus.
____

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Tool |Deployment options (2) |Management options (network-wide
configuration and policy or baseline deployment) (link:#fn3[3])
|Reporting options
|Microsoft Intune |link:/intune/endpoint-protection-configure[Add
endpoint protection settings in Intune]
|link:/intune/device-restrictions-configure[Configure device restriction
settings in Intune] |link:/intune/device-management[Use the Intune
console to manage devices]

|Microsoft Endpoint Manager (link:#fn1[1]) |Use the
link:/mem/configmgr/protect/deploy-use/endpoint-protection-site-role[Endpoint
Protection point site system role] and
link:/mem/configmgr/protect/deploy-use/endpoint-protection-configure-client[enable
Endpoint Protection with custom client settings]. |With
link:/microsoft-365/security/office-365-security/anti-malware-policies-configure[default
and customized antimalware policies] and client management. |With the
default
link:/mem/configmgr/apps/deploy-use/monitor-applications-from-the-console[Configuration
Manager Monitoring workspace] and email alerts.

|Group Policy and Active Directory (domain-joined) |Use a Group Policy
Object to deploy configuration changes and ensure Microsoft Defender
Antivirus is enabled. |Use Group Policy Objects (GPOs) to
link:/microsoft-365/security/defender-endpoint/manage-protection-update-schedule-microsoft-defender-antivirus[configure
update options for Microsoft Defender Antivirus] and
link:/microsoft-365/security/defender-endpoint/configure-microsoft-defender-antivirus-features[configure
Windows Defender features]. |Endpoint reporting isn’t available with
Group Policy. You can generate a list of Group Policies to determine if
any settings or policies aren’t applied.

|PowerShell |Deploy with Group Policy, Microsoft Endpoint Configuration
Manager, or manually on individual endpoints. |Use the
link:/powershell/module/defender/set-mppreference[Set-MpPreference] and
link:/powershell/module/defender/update-mpsignature[Update-MpSignature]
cmdlets available in the Defender module. |Use the appropriate
link:/powershell/module/defender[Get- cmdlets available in the Defender
module].

|Windows Management Instrumentation |Deploy with Group Policy, Microsoft
Endpoint Configuration Manager, or manually on individual endpoints.
|Use the
link:/previous-versions/windows/desktop/defender/set-msft-mppreference[Set
method of the MSFT_MpPreference class] and the
link:/previous-versions/windows/desktop/defender/update-msft-mpsignature[Update
method of the MSFT_MpSignature class]. |Use the
link:/previous-versions/windows/desktop/defender/msft-mpcomputerstatus[MSFT_MpComputerStatus]
class and the get method of associated classes in the
link:/windows/win32/wmisdk/wmi-providers[Windows Defender WMIv2
Provider].

|Microsoft Azure |Deploy Microsoft Antimalware for Azure in the
link:/azure/security/azure-security-antimalware#antimalware-deployment-scenarios[Azure
portal&#44; by using Visual Studio virtual machine configuration&#44; or using
Azure PowerShell cmdlets]. You can also
link:/azure/defender-for-cloud/endpoint-protection-recommendations-technical[Install
Endpoint protection in Microsoft Defender for Cloud]. |Configure
link:/azure/security/azure-security-antimalware#enable-and-configure-antimalware-using-powershell-cmdlets[Microsoft
Antimalware for Virtual Machines and Cloud Services with Azure
PowerShell cmdlets] or
https://gallery.technet.microsoft.com/Antimalware-For-Azure-5ce70efe[use
code samples]. |Use
link:/azure/security/azure-security-antimalware#enable-and-configure-antimalware-using-powershell-cmdlets[Microsoft
Antimalware for Virtual Machines and Cloud Services with Azure
PowerShell cmdlets] to enable monitoring. You can also review usage
reports in Azure Active Directory to determine suspicious activity,
including the Possibly infected devices report, and configure an SIEM
tool to report on
link:troubleshoot-microsoft-defender-antivirus.md[event logs and error
codes in Microsoft Defender Antivirus] and add that tool as an app in
Azure AD.
|===

[arabic]
. The availability of some functions and features, especially related to
cloud-delivered protection, differ between Microsoft Endpoint Manager
(Current Branch) and System Center 2012 Configuration Manager. In this
library, we’ve focused on Windows 10, Windows 11, Windows Server 2016,
and Microsoft Endpoint Manager (Current Branch). See
link:cloud-protection-microsoft-defender-antivirus.md[Use Microsoft
cloud-provided protection in Microsoft Defender Antivirus] for a table
that describes the major differences. link:#ref2[(Return to table)]
. In Windows 10 and Windows 11, Microsoft Defender Antivirus is a
component available without installation or deployment of another client
or service. It will automatically be enabled when third-party antivirus
products are either uninstalled or out of date (except on Windows Server
2016). Traditional deployment, therefore, isn’t required. Deployment
here refers to ensuring the Microsoft Defender Antivirus component is
available and enabled on endpoints or servers. link:#ref2[(Return to
table)]
. Configuration of features and protection, including configuring
product and protection updates, are further described in the
link:configure-notifications-microsoft-defender-antivirus.md[Configure
Microsoft Defender Antivirus features] section in this library.
link:#ref2[(Return to table)]

=== In this section

[width="100%",cols="50%,50%",options="header",]
|===
|Article |Description
|link:deploy-microsoft-defender-antivirus.md[Deploy and enable Microsoft
Defender Antivirus protection] |While the client is installed as a core
part of Windows 10 or Windows 11, and traditional deployment doesn’t
apply, you’ll still need to enable the client on your endpoints with
Microsoft Endpoint Configuration Manager, Microsoft Intune, or Group
Policy Objects.

|link:manage-updates-baselines-microsoft-defender-antivirus.md[Manage
Microsoft Defender Antivirus updates and apply baselines] |There are two
parts to updating Microsoft Defender Antivirus: updating the client on
endpoints (product updates), and updating Security intelligence
(protection updates). You can update Security intelligence in many ways,
using Microsoft Endpoint Configuration Manager, Group Policy,
PowerShell, and WMI.

|link:report-monitor-microsoft-defender-antivirus.md[Monitor and report
on Microsoft Defender Antivirus protection] |You can use Microsoft
Intune, Microsoft Endpoint Configuration Manager, the Update Compliance
add-in for Microsoft Operations Management Suite, or a third-party SIEM
product (by consuming Windows event logs) to monitor protection status
and create reports about endpoint protection.
|===

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____

____
[!TIP] *Performance tip* Due to a variety of factors (examples listed
below) Microsoft Defender Antivirus, like other antivirus software, can
cause performance issues on endpoint devices. In some cases, you might
need to tune the performance of Microsoft Defender Antivirus to
alleviate those performance issues. Microsoft’s *Performance analyzer*
is a PowerShell command-line tool that helps determine which files, file
paths, processes, and file extensions might be causing performance
issues; some examples are:

* Top paths that impact scan time
* Top files that impact scan time
* Top processes that impact scan time
* Top file extensions that impact scan time
* Combinations – for example:
** top files per extension
** top paths per extension
** top processes per path
** top scans per file
** top scans per file per process

You can use the information gathered using Performance analyzer to
better assess performance issues and apply remediation actions. See:
link:tune-performance-defender-antivirus.md[Performance analyzer for
Microsoft Defender Antivirus].
____
