= 
mjcaparas
:keywords: deploy, plan, deployment strategy, cloud native, management,
on prem, evaluation, onboarding, local, group policy, gp, endpoint
manager, mem

== Plan your Microsoft Defender for Endpoint deployment

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-secopsdashboard-abovefoldlink[Sign
up for a free trial.]
____

Plan your Microsoft Defender for Endpoint deployment so that you can
maximize the security capabilities within the suite and better protect
your enterprise from cyber threats.

This solution provides guidance on how to identify your environment
architecture, select the type of deployment tool that best fits your
needs, and guidance on how to configure capabilities.

:::image type=``content'' source=``images/deployment-guide-plan.png''
alt-text=``The deployment flow''
lightbox=``images/deployment-guide-plan.png'':::

=== Step 1: Identify architecture

We understand that every enterprise environment is unique, so we’ve
provided several options to give you the flexibility in choosing how to
deploy the service.

Depending on your environment, some tools are better suited for certain
architectures.

Use the following material to select the appropriate Defender for
Endpoint architecture that best suites your organization.

[width="100%",cols="<50%,<50%",options="header",]
|===
|Item |Description
|https://download.microsoft.com/download/5/6/0/5609001f-b8ae-412f-89eb-643976f6b79c/mde-deployment-strategy.pdf[:::image
type=``content'' source=``images/mde-deployment-strategy.png''
alt-text=``The strategy for deployment of Defender for Endpoint''
lightbox=``images/mde-deployment-strategy.png'':::]
https://download.microsoft.com/download/5/6/0/5609001f-b8ae-412f-89eb-643976f6b79c/mde-deployment-strategy.pdf[PDF
document]
https://download.microsoft.com/download/5/6/0/5609001f-b8ae-412f-89eb-643976f6b79c/mde-deployment-strategy.vsdx[Visio
drawing] |The architectural material helps you plan your deployment for
the following architectures:
|===

=== Step 2: Select deployment method

The following table lists the supported endpoints and the corresponding
deployment tool that you can use so that you can plan the deployment
appropriately.

[width="100%",cols="50%,50%",options="header",]
|===
|Endpoint |Deployment tool
|*Windows* |link:configure-endpoints-script.md[Local script (up to 10
devices)] link:configure-endpoints-gp.md[Group Policy]
link:configure-endpoints-mdm.md[Microsoft Endpoint Manager/ Mobile
Device Manager] link:configure-endpoints-sccm.md[Microsoft Endpoint
Configuration Manager] link:configure-endpoints-vdi.md[VDI scripts]

|*macOS* |link:mac-install-manually.md[Local script]
link:mac-install-with-intune.md[Microsoft Endpoint Manager]
link:mac-install-with-jamf.md[JAMF Pro]
link:mac-install-with-other-mdm.md[Mobile Device Management]

|*Linux Server* |link:linux-install-manually.md[Local script]
link:linux-install-with-puppet.md[Puppet]
link:linux-install-with-ansible.md[Ansible]

|*iOS* |link:ios-install.md[App-based]

|*Android* |link:android-intune.md[Microsoft Endpoint Manager]
|===

=== Step 3: Configure capabilities

After onboarding endpoints, configure the security capabilities in
Defender for Endpoint so that you can maximize the robust security
protection available in the suite. Capabilities include:

* Endpoint detection and response
* Next-generation protection
* Attack surface reduction

=== Related topics

* link:deployment-phases.md[Deployment phases]
