= 
denisebmsft
:keywords: deploy, enable, Microsoft Defender Antivirus

== Deploy and enable Microsoft Defender Antivirus

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 2]
* Microsoft Defender Antivirus

*Platforms* - Windows

Depending on the management tool you are using, you may need to
specifically enable or configure Microsoft Defender Antivirus
protection.

See the table in
link:deploy-manage-report-microsoft-defender-antivirus.md#ref2[Deploy&#44;
manage&#44; and report on Microsoft Defender Antivirus] for instructions on
how to enable protection with Microsoft Intune, Microsoft Endpoint
Configuration Manager, Group Policy, Active Directory, Microsoft Azure,
PowerShell cmdlets, and Windows Management Instruction (WMI).

Some scenarios require more guidance on how to successfully deploy or
configure Microsoft Defender Antivirus protection, such as Virtual
Desktop Infrastructure (VDI) environments.

The remaining article in this section provides end-to-end advice and
best practices for
link:deployment-vdi-microsoft-defender-antivirus.md[setting up Microsoft
Defender Antivirus on virtual machines (VMs) in a VDI or Remote Desktop
Services (RDS) environment].

=== Related articles

* link:microsoft-defender-antivirus-in-windows-10.md[Microsoft Defender
Antivirus in Windows 10]
* link:deploy-manage-report-microsoft-defender-antivirus.md[Deploy&#44;
manage updates&#44; and report on Microsoft Defender Antivirus]
* link:deployment-vdi-microsoft-defender-antivirus.md[Deployment guide
for Microsoft Defender Antivirus in a virtual desktop infrastructure
(VDI) environment]

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____
