= 
dansimp

== Microsoft Defender for Endpoint Device Control Removable Storage Access Control

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]

____
[!NOTE] The Group Policy management and Intune OMA-URI/Custom Policy
management of this product are now generally available (4.18.2106): See
https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/protect-your-removable-storage-and-printers-with-microsoft/ba-p/2324806[Tech
Community blog: Protect your removable storage and printer with
Microsoft Defender for Endpoint].
____

=== Overview

Microsoft Defender for Endpoint Device Control Removable Storage Access
Control feature enables you to audit, allow, or prevent the read, write,
or execute access to removable storage with or without exclusions.

[cols=",",options="header",]
|===
|Privilege |Permission
|Access |Read, Write, Execute
|Action Mode |Audit, Allow, Prevent
|CSP Support |Yes
|GPO Support |Yes
|User-based Support |Yes
|Machine-based Support |Yes
|===

==== Prepare your endpoints

Deploy Removable Storage Access Control on Windows 10 and Windows 11
devices that have the anti-malware client version *4.18.2103.3 or
later*.

* *4.18.2104 or later*: Add `SerialNumberId`, `VID_PID`, filepath-based
GPO support, and `ComputerSid`
* *4.18.2105 or later*: Add Wildcard support for
`HardwareId/DeviceId/InstancePathId/FriendlyNameId/SerialNumberId`, the
combination of specific user on specific machine, removable SSD (a
SanDisk Extreme SSD)/USB Attached SCSI (UAS) support
* *4.18.2107 or later*: Add Windows Portable Device (WPD) support (for
mobile devices, such as tablets); add `AccountName` into
link:device-control-removable-storage-access-control.md#view-data-in-microsoft-defender-for-endpoint[advanced
hunting]
* *4.18.2205 or later*: Expand the default enforcement to *Printer*. If
you set it to *Deny*, it will block Printer as well, so if you only want
to manage storage, make sure to create a custom policy to allow Printer
* *4.18.2207 or later*: Add *File* support, the common use case can be:
block people from Read/Write/Execute access specific file on removable
storage; add *Network* and *VPN Connection* support, the common use case
can be: block people from access removable storage when the machine
isn’t connecting corporate network.

:::image type=``content'' source=``images/powershell.png''
alt-text=``Screenshot of the PowerShell interface''
lightbox=``images/powershell.png'':::

____
[!NOTE] None of Windows Security components need to be active as you can
run Removable Storage Access Control independent of Windows Security
status.
____

=== Device Control Removable Storage Access Control properties

The Removable Storage Access Control includes Removable storage group
creation and access policy rule creation:

* Removable storage group allows you to create group. For example,
authorized USB group or encrypted USB group.
* Access policy rule allows you to create policy to restrict each
removable storage group. For example, only allow authorized user to
Write access-authorized USB group.
* To block a specific removable storage class but allow specific media,
you can use `IncludedIdList` a group through `PrimaryId` and
`ExcludedIDList` a group through `DeviceId/HardwareId/etc.` For more
information, see
link:deploy-manage-removable-storage-intune.md#deploy-removable-storage-access-control-by-using-intune-oma-uri[Deploy
Removable Storage Access Control by using Intune OMA-URI].

Here are the properties you can use when you create the group and policy
XML files.

==== Group

Group includes following types:

* Device: if there’s an explicit type setting, this setting is the
default, including removable storage and Printer.
* Network
* VPN Connection

The following table lists the properties you can use in *Group*:

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Property Name |Description |Options
|*GroupId* |GUID, a unique ID, represents the group and will be used in
the policy. |You can generate ID through
[PowerShell[(/powershell/module/microsoft.powershell.utility/new-guid)

|*Type* |The type of the group. |*File*

|*DescriptorIdList* |List the device properties you want to use to cover
in the group. All properties are case sensitive. |*PrimaryId*: The
Primary ID includes `RemovableMediaDevices`, `CdRomDevices`,
`WpdDevices`, `PrinterDevices`.

|*MatchType* |When there are multiple device properties being used in
the `DescriptorIDList`, MatchType defines the relationship. |*MatchAll*:
Any attributes under the `DescriptorIdList` will be *And* relationship;
for example, if administrator puts `DeviceID` and `InstancePathID`, for
every connected USB, system will check to see whether the USB meets both
values.
|===

==== Access policy rule

Every access policy rule called *PolicyRule* can be used to define
access restriction for each group through multiple *Entry*.

The following table lists the properties you can use in *PolicyRule*:

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Property Name |Description |Options
|*PolicyRule Id* |GUID, a unique ID, represents the policy and will be
used in the reporting and troubleshooting. |You can generate ID through
link:/powershell/module/microsoft.powershell.utility/new-guid[PowerShell]

|*Name* |String, the name of the policy and will display on the toast
based on the policy setting. |

|*IncludedIdList* |The group(s) that the policy will be applied to. If
multiple groups are added, the policy will be applied to any media in
all those groups. |The Group ID/GUID must be used at this instance.

|*ExcludedIDList* |The group(s) that the policy won’t be applied to.
|The Group ID/GUID must be used at this instance.

|*Entry* |One PolicyRule can have multiple entries; each entry with a
unique GUID tells Device Control one restriction. |See Entry properties
table below to get details.
|===

The following table lists the properties you can use in *Entry*:

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Property Name |Description |Options
|*Entry Id* |GUID, a unique ID, represents the entry and will be used in
the reporting and troubleshooting. |You can generate ID through
link:/powershell/module/microsoft.powershell.utility/new-guid[PowerShell]

|*Type* |Defines the action for the removable storage groups in
IncludedIDList. |Allow

|*Sid* |Local user Sid or user Sid group or the Sid of the AD object or
the Object ID of the Azure AD object, defines whether to apply this
policy over a specific user or user group. One entry can have a maximum
of one SID and an entry without any SID means to apply the policy over
the machine. |

|*ComputerSid* |Local computer Sid or computer Sid group or the Sid of
the AD object or the Object Id of the AAD object, defines whether to
apply this policy over a specific machine or machine group. One entry
can have a maximum of one ComputerSID and an entry without any
ComputerSID means to apply the policy over the machine. If you want to
apply an Entry to a specific user and specific machine, add both SID and
ComputerSID into the same Entry. |

|*Options* |Defines whether to display notification or not |*When Type
Allow is selected*:

|AccessMask |Defines the access. |*Disk level access*:

|Parameters |Condition for this Entry, for example Network condition.
|Can add groups (non Devices type) or even put Parameters into
Parameters. See Parameters properties table below to get details.
|===

The following table lists the properties you can use in *Parameters*:

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Property Name |Description |Options
|*MatchType* |When there are multiple device properties being used in
the `DescriptorIDList`, MatchType defines the relationship. |*MatchAll*:
Any attributes under the `DescriptorIdList` will be *And* relationship;
for example, if administrator puts `DeviceID` and `InstancePathID`, for
every connected USB, system will check to see whether the USB meets both
values.

|*File* |You can use one or multiple File or Network or VPN Connection
group(s) as parameter for this Entry, and then define MatchType for the
relationship between those groups. |

|*Parameters* |You can embed Parameters inside Parameters with
MatchType. |
|===

For specific guidance, see:

[width="100%",cols="50%,50%",options="header",]
|===
|Article |Description
|link:deploy-manage-removable-storage-group-policy.md[Deploying
Removable Storage Access Control by using Group Policy] |Use Group
Policy to deploy the policy.

|link:deploy-manage-removable-storage-intune.md[Deploying Removable
Storage Access Control by using Intune OMA-URI] |Use Intune to deploy
the policy.
|===

=== View data in Microsoft Defender for Endpoint

The https://security.microsoft.com/advanced-hunting[Microsoft 365
Defender portal] shows events triggered by the Device Control Removable
Storage Access Control. To access the Microsoft 365 security, you must
have the following subscription:

* Microsoft 365 for E5 reporting

If `AuditAllowed` or `AuditDenied` is configured in your policy and
*Send event* is selected in *Options*, an event will be sent to Advanced
hunting or the Device control report for every covered access
(`AccessMask` in the entry), regardless of whether it was initiated by
the system or by the user who signed in.

[source,kusto]
----
//RemovableStoragePolicyTriggered: event triggered by Disk level enforcement
DeviceEvents
| where ActionType == "RemovableStoragePolicyTriggered"
| extend parsed=parse_json(AdditionalFields)
| extend RemovableStorageAccess = tostring(parsed.RemovableStorageAccess)
| extend RemovableStoragePolicyVerdict = tostring(parsed.RemovableStoragePolicyVerdict)
| extend MediaBusType = tostring(parsed.BusType)
| extend MediaClassGuid = tostring(parsed.ClassGuid)
| extend MediaClassName = tostring(parsed.ClassName)
| extend MediaDeviceId = tostring(parsed.DeviceId)
| extend MediaInstanceId = tostring(parsed.DeviceInstanceId)
| extend MediaName = tostring(parsed.MediaName)
| extend RemovableStoragePolicy = tostring(parsed.RemovableStoragePolicy)
| extend MediaProductId = tostring(parsed.ProductId)
| extend MediaVendorId = tostring(parsed.VendorId)
| extend MediaSerialNumber = tostring(parsed.SerialNumber)
|project Timestamp, DeviceId, DeviceName, InitiatingProcessAccountName, ActionType, RemovableStorageAccess, RemovableStoragePolicyVerdict, MediaBusType, MediaClassGuid, MediaClassName, MediaDeviceId, MediaInstanceId, MediaName, RemovableStoragePolicy, MediaProductId, MediaVendorId, MediaSerialNumber, FolderPath, FileSize
| order by Timestamp desc
----

[source,kusto]
----
//information of file written to removable storage
DeviceEvents
| where ActionType contains "RemovableStorageFileEvent"
| extend parsed=parse_json(AdditionalFields)
| extend Policy = tostring(parsed.Policy)
| extend PolicyRuleId = tostring(parsed.PolicyRuleId)
| extend MediaClassName = tostring(parsed.ClassName)
| extend MediaInstanceId = tostring(parsed.InstanceId)
| extend MediaName = tostring(parsed.MediaName)
| extend MediaProductId = tostring(parsed.ProductId)
| extend MediaVendorId = tostring(parsed.VendorId)
| extend MediaSerialNumber = tostring(parsed.SerialNumber)
| extend FileInformationOperation = tostring(parsed.DuplicatedOperation)
| extend FileEvidenceLocation = tostring(parsed.TargetFileLocation)
| project Timestamp, DeviceId, DeviceName, InitiatingProcessAccountName, ActionType, Policy, PolicyRuleId, FileInformationOperation, MediaClassName, MediaInstanceId, MediaName, MediaProductId, MediaVendorId, MediaSerialNumber, FileName, FolderPath, FileSize, FileEvidenceLocation, AdditionalFields
| order by Timestamp desc
----
