= Microsoft Defender for Endpoint device timeline event flags
:audience: ITPro
:author: dansimp
:description: Use Microsoft Defender for Endpoint device timeline event flags to
:keywords: Defender for Endpoint device timeline, event flags
:manager: dansimp
:ms.author: dansimp
:ms.collection: M365-security-compliance
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Microsoft Defender for Endpoint device timeline event flags

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-assignaccess-abovefoldlink[Sign up for a free trial.]
____

Event flags in the Defender for Endpoint device timeline help you filter and organize specific events when you're  investigate potential attacks.

The Defender for Endpoint device timeline provides a chronological view of the events and associated alerts observed on a device.
This list of events provides full visibility into any events, files, and IP addresses observed on the device.
The list can sometimes be lengthy.
Device timeline event flags help you track events that could be related.

After you've gone through a device timeline, you can sort, filter, and export the specific events that you flagged.

While navigating the device timeline, you can search and filter for specific events.
You can set event flags by:

* Highlighting the most important events
* Marking events that requires deep dive
* Building a clean breach timeline

=== Flag an event

. Find the event that you want to flag
. Click the flag icon in the Flag column.

:::image type="content" source="images/device-flags.png" alt-text="The device timeline flag" lightbox="images/device-flags.png":::

=== View flagged events

. In the timeline *Filters* section, enable *Flagged events*.
. Click *Apply*.
Only flagged events are displayed.

You can apply additional filters by clicking on the time bar.
This will only show events prior to the flagged event.

:::image type="content" source="images/device-flag-filter.png" alt-text="The device timeline flag with the filter switched on" lightbox="images/device-flag-filter.png":::
