= Turn on network protection
:author: denisebmsft
:description: Enable network protection with Group Policy, PowerShell, or Mobile Device Management and Configuration Manager.
:keywords: Network protection, exploits, malicious website, ip, domain, domains, enable, turn on
:manager: dansimp
:ms.author: deniseb
:ms.collection: m365-security-compliance
:ms.localizationpriority: medium
:ms.mktglfcycl: manage
:ms.pagetype: security
:ms.reviewer: mkaminska
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: conceptual
:search.appverid: met150

== Turn on network protection

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]
* Microsoft Defender Antivirus

*Platforms*

* Windows
* Linux (See xref:network-protection-linux.adoc[Network protection for Linux])
* macOS (See xref:network-protection-macos.adoc[Network protection for macOS])

____
[!TIP] Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-assignaccess-abovefoldlink[Sign up for a free trial.]
____

xref:network-protection.adoc[Network protection] helps to prevent employees from using any application to access dangerous domains that may host phishing scams, exploits, and other malicious content on the internet.
You can xref:evaluate-network-protection.adoc[audit network protection] in a test environment to view which apps would be blocked before enabling network protection.

link:/mem/intune/protect/endpoint-protection-windows-10#network-filtering[Learn more about network filtering configuration options.]

=== Check if network protection is enabled

Check if network protection has been enabled on a local device by using Registry editor.

. Select the *Start* button in the task bar and type *regedit* to open Registry editor.
. Choose *HKEY_LOCAL_MACHINE* from the side menu.
. Navigate through the nested menus to *SOFTWARE* > *Policies* > *Microsoft* > *Windows Defender* > *Windows Defender Exploit Guard* > *Network Protection*.

If the Key is missing,  Navigate to *SOFTWARE* > *Microsoft* > *Windows Defender* > *Windows Defender Exploit Guard* > *Network Protection*.

. Select *EnableNetworkProtection* to see the current state of network protection on the device:
 ** 0, or *Off*
 ** 1, or *On*
 ** 2, or *Audit* mode

+
:::image type="content" source="../../media/95341270-b738b280-08d3-11eb-84a0-16abb140c9fd.png" alt-text="Network Protection registry key" lightbox="../../media/95341270-b738b280-08d3-11eb-84a0-16abb140c9fd.png":::

=== Enable network protection

Enable network protection by using any of these methods:

* <<powershell,PowerShell>>
* <<mobile-device-management-mdm,Mobile Device Management (MDM)>>
* <<microsoft-endpoint-manager,Microsoft Endpoint Manager>>
* <<group-policy,Group Policy>>
* <<microsoft-endpoint-configuration-manager,Microsoft Endpoint Configuration Manager>>

==== PowerShell

. Type *powershell* in the Start menu, right-click *Windows PowerShell* and select *Run as administrator*.
. Enter the following cmdlet:
+
[,powershell]
----
 Set-MpPreference -EnableNetworkProtection Enabled
----

. Optional: Enable the feature in audit mode using the following cmdlet:
+
[,powershell]
----
 Set-MpPreference -EnableNetworkProtection AuditMode
----
+
Use `Disabled` instead of `AuditMode` or `Enabled` to turn off the feature.

==== Mobile device management (MDM)

Use the link:/windows/client-management/mdm/policy-csp-defender[./Vendor/MSFT/Policy/Config/Defender/EnableNetworkProtection] configuration service provider (CSP) to enable or disable network protection or enable audit mode.

https://support.microsoft.com/topic/update-for-microsoft-defender-antimalware-platform-92e21611-8cf1-8e0e-56d6-561a07d144cc[Update Microsoft Defender antimalware platform to the latest version] before you enable or disable network protection or enable audit mode.

==== Microsoft Endpoint Manager

===== Microsoft Defender for Endpoint Baseline method

. Sign into the Microsoft Endpoint Manager admin center (https://endpoint.microsoft.com).
. Go to *Endpoint security* > *Security baselines* > *Microsoft Defender for Endpoint Baseline*.
. Select *Create a profile*, then provide a name for your profile, and then select *Next*.
. In the *Configuration settings* section, go to *Attack Surface Reduction Rules* > set *Block*, *Enable* or *Audit* for *Enable network protection*.
Select *Next*.
. Select the appropriate *Scope tags* and *Assignments* as required by your organization.
. Review all the information, and then select *Create*.

===== Antivirus policy method

. Sign into the Microsoft Endpoint Manager admin center (https://endpoint.microsoft.com).
. Go to *Endpoint security* > *Antivirus*
. Select *Create a policy*
. In the *Create a policy* flyout, choose *Windows 10, Windows 11, and Windows Server* from the *Platform* list.
. Choose *Microsoft Defender Antivirus* from the *Profile* list then choose *Create*
. Provide a name for your profile, and then select *Next*.
. In the *Configuration settings* section, select *Disabled*, *Enabled (block mode)* or *Enabled (audit mode)* for *Enable Network Protection*, then select *Next*.
. Select the appropriate *Assignments* and *Scope tags* as required by your organization.
. Review all the information, and then select *Create*.

===== Configuration profile method

. Sign into the Microsoft Endpoint Manager admin center (https://endpoint.microsoft.com).
. Go to *Devices* > *Configuration profiles* > *Create profile*.
. In the *Create a profile* flyout, select *Platform* and choose the *Profile Type* as *Templates*.
. In the *Template name*, Choose *Endpoint protection* from the list of templates, and then select *Create*.
. Go to *Endpoint protection* > *Basics*, provide a name for your profile, and then select *Next*.
. In the *Configuration settings* section, go to *Microsoft Defender Exploit Guard* > *Network filtering* > *Network protection* > *Enable* or *Audit*.
Select *Next*.
. Select the appropriate *Scope tags*, *Assignments*, and *Applicability rules* as required by your organization.
Admins can set more requirements.
. Review all the information, and then select *Create*.

==== Group Policy

Use the following procedure to enable network protection on domain-joined computers or on a standalone computer.

. On a standalone computer, go to *Start* and then type and select *Edit group policy*.
+
_-Or-_
+
On a domain-joined Group Policy management computer, open the https://technet.microsoft.com/library/cc731212.aspx[Group Policy Management Console], right-click the Group Policy Object you want to configure and select *Edit*.

. In the *Group Policy Management Editor*, go to *Computer configuration* and select *Administrative templates*.
. Expand the tree to *Windows components* > *Microsoft Defender Antivirus* > *Windows Defender Exploit Guard* > *Network protection*.
+
____
[!NOTE] On older versions of Windows, the group policy path may say "Windows Defender Antivirus" instead of "Microsoft Defender Antivirus."
____

. Double-click the *Prevent users and apps from accessing dangerous websites* setting and set the option to *Enabled*.
In the options section, you must specify one of the following options:
 ** *Block* - Users can't access malicious IP addresses and domains.
 ** *Disable (Default)* - The Network protection feature won't work.
Users won't be blocked from accessing malicious domains.
 ** *Audit Mode* - If a user visits a malicious IP address or domain, an event will be recorded in the Windows event log.
However, the user won't be blocked from visiting the address.

+
____
[!IMPORTANT] To fully enable network protection, you must set the Group Policy option to *Enabled* and also select *Block* in the options drop-down menu.
____
+
____
[!NOTE] Optional: Follow the steps in <<check-if-network-protection-is-enabled,Check if network protection is enabled>> to verify that your Group Policy settings are correct.
____

==== Microsoft Endpoint Configuration Manager

. Open the Configuration Manager console.
. Go to *Assets and Compliance* > *Endpoint Protection* > *Windows Defender Exploit Guard*.
. Select *Create Exploit Guard Policy* from the ribbon to create a new policy.
 ** To edit an existing policy, select the policy, then select *Properties* from either the ribbon or the right-click menu.
Edit the *Configure network protection* option from the *Network Protection* tab.
. On the *General* page, specify a name for the new policy and verify the *Network protection* option is enabled.
. On the *Network protection* page, select one of the following settings for the *Configure network protection* option:
 ** *Block*
 ** *Audit*
 ** *Disabled*
. Complete the rest of the steps, and save the policy.
. From the ribbon, select *Deploy* to deploy the policy to a collection.

____
[!IMPORTANT] Once you deploy an Exploit Guard policy from Configuration Manager, the Exploit Guard settings will not be removed from the clients if you remove the deployment.
`Delete not supported` is recorded in the Configuration Manager client's ExploitGuardHandler.log if you remove the client's Exploit Guard deployment.
// CMADO8538577
The following PowerShell script can be run under SYSTEM context to remove these settings:
// CMADO9907132

[,powershell]
----
$defenderObject = Get-WmiObject -Namespace "root/cimv2/mdm/dmmap" -Class "MDM_Policy_Config01_Defender02" -Filter "InstanceID='Defender' and ParentID='./Vendor/MSFT/Policy/Config'"
$defenderObject.AttackSurfaceReductionRules = $null
$defenderObject.AttackSurfaceReductionOnlyExclusions = $null
$defenderObject.EnableControlledFolderAccess = $null
$defenderObject.ControlledFolderAccessAllowedApplications = $null
$defenderObject.ControlledFolderAccessProtectedFolders = $null
$defenderObject.EnableNetworkProtection = $null
$defenderObject.Put()

$exploitGuardObject = Get-WmiObject -Namespace "root/cimv2/mdm/dmmap" -Class "MDM_Policy_Config01_ExploitGuard02" -Filter "InstanceID='ExploitGuard' and ParentID='./Vendor/MSFT/Policy/Config'"
$exploitGuardObject.ExploitProtectionSettings = $null
$exploitGuardObject.Put()
----
____

=== See also

* xref:network-protection.adoc[Network protection]
* xref:network-protection-linux.adoc[Network protection for Linux]
* xref:network-protection-macos.adoc[Network protection for macOS]
* link:network-protection.md#network-protection-and-the-tcp-three-way-handshake[Network protection and the TCP three-way handshake]
* xref:evaluate-network-protection.adoc[Evaluate network protection]
* xref:troubleshoot-np.adoc[Troubleshoot network protection]
