= Enable and update Microsoft Defender Antivirus on Windows Server
:audience: ITPro
:author: v-smandalika
:description: Learn how to enable and update Microsoft Defender Antivirus on Windows Server
:keywords: Windows Server, Defender Antivirus
:manager: dansimp
:ms.author: v-smandalika
:ms.collection: ["M365-security-compliance", "m365-initiative-defender-endpoint"]
:ms.custom: intro-overview
:ms.date: 08/10/2022
:ms.localizationpriority: high
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: conceptual
:search.appverid: met150

== Enable and update Defender Antivirus to the latest version on Windows Server

If you wish to use Microsoft Defender Antivirus on your Windows Server, and it had been previously disabled or uninstalled, you may need to take further steps to re-enable it and ensure it's fully updated.

To enable and update Microsoft Defender Antivirus on Windows Server, perform the following steps:

. Install the latest Servicing Stack Update (SSU).
. Install the latest cumulative update (LCU).
. Reinstall Microsoft Defender Antivirus or re-enable it.
For more information on how to reinstall or re-enable Microsoft Defender Antivirus on Windows Server, see <<re-enable-microsoft-defender-antivirus-on-windows-server-if-it-was-disabled,Re-enable Microsoft Defender Antivirus on Windows Server if it was disabled>> and <<re-enable-microsoft-defender-antivirus-on-windows-server-if-it-was-uninstalled,Re-enable Microsoft Defender Antivirus on Windows Server if it was uninstalled>>.
. Reboot the system.
. Install the latest version of the platform update.
+
____
[!NOTE] Re-enabling Microsoft Defender Antivirus doesn't automatically install the platform update.
You can download and install the latest platform version using Windows update.
Alternatively, you can download the update package from the https://www.catalog.update.microsoft.com/Search.aspx?q=KB4052623[Microsoft Update Catalog] or from the https://go.microsoft.com/fwlink/?linkid=870379&arch=x64[Antimalware and cyber security portal].

If you're preparing to install the modern, unified solution on Windows Server 2016, you can leverage the https://github.com/microsoft/mdefordownlevelserver/blob/main/Install.ps1[Installer help script] to automate the platform update and the subsequent installation and onboarding.
This script can also assist in re-enabling Microsoft Defender Antivirus.
____

=== Re-enable Microsoft Defender Antivirus on Windows Server if it was disabled

First, ensure that Microsoft Defender Antivirus is not disabled either through Group Policy or registry.
For more information, see link:/microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus-when-migrating[Troubleshoot Microsoft Defender Antivirus while migrating from a third-party solution].

On Windows Server 2016, in some cases, you may need to use the xref:command-line-arguments-microsoft-defender-antivirus.adoc[Malware Protection Command-Line Utility] to re-enable Microsoft Defender Antivirus.

As a local administrator on the server, perform the following steps:

. Open Command Prompt.
. Run the following command: `MpCmdRun.exe -wdenable`.
. Restart the device.

=== Re-enable Microsoft Defender Antivirus on Windows Server if it was uninstalled

In case the Defender feature was uninstalled/removed, you can add it back.

As a local administrator on the server, perform the following steps:

. Open Windows PowerShell.
. Run the following commands:
+
[,powershell]
----
# For Windows Server 2016
Dism /Online /Enable-Feature /FeatureName:Windows-Defender-Features
Dism /Online /Enable-Feature /FeatureName:Windows-Defender
Dism /Online /Enable-Feature /FeatureName:Windows-Defender-Gui

# For Windows Server 1803 and later, including Windows Server 2019 and 2022
Dism /Online /Enable-Feature /FeatureName:Windows-Defender
----
+
When the DISM command is being used within a task sequence running PowerShell, the following path to cmd.exe is required.
+
[,powershell]
----
C:\Windows\System32\cmd.exe /c Dism /Online /Enable-Feature /FeatureName:Windows-Defender-Features
C:\Windows\System32\cmd.exe /c Dism /Online /Enable-Feature /FeatureName:Windows-Defender
----
+
____
[!NOTE] You can also use Server Manager or PowerShell cmdlets to install the Microsoft Defender Antivirus feature.
____

. Reboot the system.
