= 
mjcaparas
:keywords: attack surface reduction, evaluate, next, generation,
protection

== Evaluate Microsoft Defender for Endpoint

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-enablesiem-abovefoldlink[Sign
up for a free trial.]
____

https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint] is a unified platform for preventative protection, post-breach
detection, automated investigation, and response.

You can evaluate Microsoft Defender for Endpoint in your organization by
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial[starting
your free trial].

You can also evaluate the different security capabilities in Microsoft
Defender for Endpoint by using the following instructions.

=== Evaluate attack surface reduction

These capabilities help prevent attacks and exploitations from infecting
your organization.

* link:./evaluate-exploit-protection.md[Evaluate exploit protection]
* link:./evaluate-exploit-protection.md[Evaluate network protection]
* link:./evaluate-controlled-folder-access.md[Evaluate controlled folder
access]
* link:/windows/security/threat-protection/microsoft-defender-application-guard/test-scenarios-md-app-guard[Evaluate
application guard]
* link:/windows/security/threat-protection/windows-firewall/evaluating-windows-firewall-with-advanced-security-design-examples[Evaluate
network firewall]

=== Evaluate next-generation protection

Next gen protections help detect and block the latest threats.

* link:/windows/security/threat-protection/microsoft-defender-antivirus/evaluate-microsoft-defender-antivirus[Evaluate
antivirus]

=== See Also

link:microsoft-defender-endpoint.md[Microsoft Defender for Endpoint
overview]
