= 
dansimp
:keywords: Exploit protection, windows 10, windows 11, windows defender,
ransomware, protect, evaluate, test, demo, try

== Evaluate controlled folder access

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]
- Microsoft Defender Antivirus

*Platforms* - Windows

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-enablesiem-abovefoldlink[Sign
up for a free trial.]
____

link:controlled-folders.md[Controlled folder access] is a feature that
helps protect your documents and files from modification by suspicious
or malicious apps. Controlled folder access is supported on Windows
Server 2019, Windows Server 2022, Windows 10, and Windows 11 clients.

It is especially useful in helping protect against
https://www.microsoft.com/wdsi/threats/ransomware[ransomware] that
attempts to encrypt your files and hold them hostage.

This article helps you evaluate controlled folder access. It explains
how to enable audit mode so you can test the feature directly in your
organization.

=== Use audit mode to measure impact

Enable the controlled folder access in audit mode to see a record of
what _would_ have happened if it was fully enabled. Test how the feature
will work in your organization to ensure it doesn’t affect your
line-of-business apps. You can also get an idea of how many suspicious
file modification attempts generally occur over a certain period of
time.

To enable audit mode, use the following PowerShell cmdlet:

[source,powershell]
----
Set-MpPreference -EnableControlledFolderAccess AuditMode
----

____
[!TIP] If you want to fully audit how controlled folder access will work
in your organization, you’ll need to use a management tool to deploy
this setting to devices in your network(s). You can also use Group
Policy, Intune, mobile device management (MDM), or Microsoft Endpoint
Manager to configure and deploy the setting, as described in the main
link:controlled-folders.md[controlled folder access topic].
____

=== Review controlled folder access events in Windows Event Viewer

The following controlled folder access events appear in Windows Event
Viewer under Microsoft/Windows/Windows Defender/Operational folder.

[cols=",",options="header",]
|===
|Event ID |Description
|5007 |Event when settings are changed
|1124 |Audited controlled folder access event
|1123 |Blocked controlled folder access event
|===

____
[!TIP] You can configure a
link:/windows/win32/wec/setting-up-a-source-initiated-subscription[Windows
Event Forwarding subscription] to collect the logs centrally.
____

=== Customize protected folders and apps

During your evaluation, you may wish to add to the list of protected
folders, or allow certain apps to modify files.

See link:controlled-folders.md[Protect important folders with controlled
folder access] for configuring the feature with management tools,
including Group Policy, PowerShell, and MDM configuration service
providers (CSPs).

=== See also

* link:controlled-folders.md[Protect important folders with controlled
folder access]
* link:evaluate-mde.md[Evaluate Microsoft Defender for Endpoint]
* link:audit-windows-defender.md[Use audit mode]
