= 
denisebmsft
:keywords: Microsoft Defender Antivirus, cloud protection, cloud,
antimalware, security, defender, evaluate, test, protection, compare,
real-time protection

== Evaluate Microsoft Defender Antivirus

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:*

* Microsoft Defender Antivirus
* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1]
* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]

*Platforms* - Windows

Use this guide to determine how well Microsoft Defender Antivirus
protects you from viruses, malware, and potentially unwanted
applications. It explains the important next-generation protection
features of Microsoft Defender Antivirus available for both small and
large enterprises, and how they increase malware detection and
protection across your network.

You can choose to configure and evaluate each setting independently, or
all at once. We have grouped similar settings based upon typical
evaluation scenarios, and include instructions for using PowerShell to
enable the settings.

The guide is available in PDF format for offline viewing:

* https://www.microsoft.com/download/details.aspx?id=54795[Download the
guide in PDF format]

You can also download a PowerShell that will enable all the settings
described in the guide automatically. You can obtain the script
alongside the PDF download above, or individually from PowerShell
Gallery:

* https://www.powershellgallery.com/packages/WindowsDefender_InternalEvaluationSettings[Download
the PowerShell script to automatically configure the settings]

____
[!IMPORTANT] The guide is currently intended for single-machine
evaluation of Microsoft Defender Antivirus. Enabling all of the settings
in this guide may not be suitable for real-world deployment.

For the latest recommendations for real-world deployment and monitoring
of Microsoft Defender Antivirus across a network, see
link:deploy-manage-report-microsoft-defender-antivirus.md[Deploy
Microsoft Defender Antivirus].
____

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____

=== Related topics

* link:microsoft-defender-antivirus-in-windows-10.md[Microsoft Defender
Antivirus in Windows 10]
* link:deploy-manage-report-microsoft-defender-antivirus.md[Deploy
Microsoft Defender Antivirus]
