= Create an app to access Microsoft Defender for Endpoint without a user
:audience: ITPro
:author: mjcaparas
:description: Learn how to design a web app to get programmatic access to Microsoft Defender for Endpoint without a user.
:keywords: apis, graph api, supported apis, actor, alerts, device, user, domain, ip, file, advanced hunting, query
:manager: dansimp
:ms.author: macapara
:ms.collection: M365-security-compliance
:ms.custom: api
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.reviewer:
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Create an app to access Microsoft Defender for Endpoint without a user

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* link:../defender-business/index.yml[Microsoft Defender for Business]

____
[!IMPORTANT] Advanced hunting capabilities are not included in Defender for Business.
See link:../defender-business/compare-mdb-m365-plans.md#compare-microsoft-defender-for-business-to-microsoft-defender-for-endpoint-plans-1-and-2[Compare Microsoft Defender for Business to Microsoft Defender for Endpoint Plans 1 and 2].
____

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign up for a free trial.]
____

[!includexref:../../includes/microsoft-defender-api-usgov.adoc[Microsoft Defender for Endpoint API URIs for US Government]]

[!includexref:../../includes/improve-request-performance.adoc[Improve request performance]]

This page describes how to create an application to get programmatic access to Defender for Endpoint without a user.
If you need programmatic access to Defender for Endpoint on behalf of a user, see xref:exposed-apis-create-app-nativeapp.adoc[Get access with user context].
If you are not sure which access you need, see xref:apis-intro.adoc[Get started].

Microsoft Defender for Endpoint exposes much of its data and actions through a set of programmatic APIs.
Those APIs will help you automate work flows and innovate based on Defender for Endpoint capabilities.
The API access requires OAuth2.0 authentication.
For more information, see link:/azure/active-directory/develop/active-directory-v2-protocols-oauth-code[OAuth 2.0 Authorization Code Flow].

In general, you'll need to take the following steps to use the APIs:

* Create an Azure Active Directory (Azure AD) application.
* Get an access token using this application.
* Use the token to access Defender for Endpoint API.

This article explains how to create an Azure AD application, get an access token to Microsoft Defender for Endpoint, and validate the token.

=== Create an app

. Log on to https://portal.azure.com[Azure] with a user that has the *Global Administrator* role.
. Navigate to *Azure Active Directory* > *App registrations* > *New registration*.
+
:::image type="content" source="images/atp-azure-new-app2.png" alt-text="The application registration pane" lightbox="images/atp-azure-new-app2.png":::

. In the registration form, choose a name for your application, and then select *Register*.
. To enable your app to access Defender for Endpoint and assign it *'Read all alerts'* permission, on your application page, select *API Permissions* > *Add permission* > *APIs my organization uses* >, type *WindowsDefenderATP*, and then select *WindowsDefenderATP*.
+
____
[!NOTE] _WindowsDefenderATP_ does not appear in the original list.
Start writing its name in the text box to see it appear.
____
+
:::image type="content" source="images/add-permission.png" alt-text="The API permissions pane" lightbox="images/add-permission.png":::
+
Select *Application permissions* > *Alert.Read.All*, and then select *Add permissions*.
+
:::image type="content" source="images/application-permissions.png" alt-text="The application permission information pane" lightbox="images/application-permissions.png":::
+
You need to select the relevant permissions.
'Read All Alerts' is only an example.
For example:

 ** To xref:run-advanced-query-api.adoc[run advanced queries], select the 'Run advanced queries' permission.
 ** To xref:isolate-machine.adoc[isolate a device], select the 'Isolate machine' permission.
 ** To determine which permission you need, look at the *Permissions* section in the API you are interested to call.

. Select *Grant consent*.
+
____
[!NOTE] Every time you add a permission, you must select *Grant consent* for the new permission to take effect.
____
+
:::image type="content" source="images/grant-consent.png" alt-text="The grant permissions page" lightbox="images/grant-consent.png":::

. To add a secret to the application, select *Certificates & secrets*, add a description to the secret, and then select *Add*.
+
____
[!NOTE] After you select *Add*, select *copy the generated secret value*.
You won't be able to retrieve this value after you leave.
____
+
:::image type="content" source="images/webapp-create-key2.png" alt-text="The create application option" lightbox="images/webapp-create-key2.png":::

. Write down your application ID and your tenant ID.
On your application page, go to *Overview* and copy the following.
+
:::image type="content" source="images/app-and-tenant-ids.png" alt-text="The created app and tenant IDs" lightbox="images/app-and-tenant-ids.png":::

. *For Microsoft Defender for Endpoint Partners only*.
Set your app to be multi-tenanted (available in all tenants after consent).
This is *required* for third-party apps (for example, if you create an app that is intended to run in multiple customers' tenant).
This is *not required* if you create a service that you want to run in your tenant only (for example, if you create an application for your own usage that will only interact with your own data).
To set your app to be multi-tenanted:
 ** Go to *Authentication*, and add `+https://portal.azure.com+` as the *Redirect URI*.
 ** On the bottom of the page, under *Supported account types*, select the *Accounts in any organizational directory* application consent for your multi-tenant app.

+
You need your application to be approved in each tenant where you intend to use it.
This is because your application interacts Defender for Endpoint on behalf of your customer.
+
You (or your customer if you are writing a third-party app) need to select the consent link and approve your app.
The consent should be done with a user who has administrative privileges in Active Directory.
+
The consent link is formed as follows:
+
[,https]
----
 https://login.microsoftonline.com/common/oauth2/authorize?prompt=consent&client_id=00000000-0000-0000-0000-000000000000&response_type=code&sso_reload=true
----
+
Where 00000000-0000-0000-0000-000000000000 is replaced with your application ID.

*Done!* You have successfully registered an application!
See examples below for token acquisition and validation.

=== Get an access token

For more information on Azure AD tokens, see the link:/azure/active-directory/develop/active-directory-v2-protocols-oauth-client-creds[Azure AD tutorial].

==== Use PowerShell

[,powershell]
----
# This script acquires the App Context Token and stores it in the variable $token for later use in the script.
# Paste your Tenant ID, App ID, and App Secret (App key) into the indicated quotes below.

$tenantId = '' ### Paste your tenant ID here
$appId = '' ### Paste your Application ID here
$appSecret = '' ### Paste your Application key here

$resourceAppIdUri = 'https://api.securitycenter.microsoft.com'
$oAuthUri = "https://login.microsoftonline.com/$TenantId/oauth2/token"
$authBody = [Ordered] @{
    resource = "$resourceAppIdUri"
    client_id = "$appId"
    client_secret = "$appSecret"
    grant_type = 'client_credentials'
}
$authResponse = Invoke-RestMethod -Method Post -Uri $oAuthUri -Body $authBody -ErrorAction Stop
$token = $authResponse.access_token
$token
----

==== Use C#:

The following code was tested with NuGet Microsoft.Identity.Client 3.19.8.

____
[!IMPORTANT] The https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory[Microsoft.IdentityModel.Clients.ActiveDirectory] NuGet package and Azure AD Authentication Library (ADAL) have been deprecated.
No new features have been added since June 30, 2020.
We strongly encourage you to upgrade, see the link:/azure/active-directory/develop/msal-migration[migration guide] for more details.
____

. Create a new console application.
. Install NuGet https://www.nuget.org/packages/Microsoft.Identity.Client/[Microsoft.Identity.Client].
. Add the following:
+
[,csharp]
----
 using Microsoft.Identity.Client;
----

. Copy and paste the following code in your app (don't forget to update the three variables: `tenantId, appId, appSecret`):
+
[,csharp]
----
 string tenantId = "00000000-0000-0000-0000-000000000000"; // Paste your own tenant ID here
 string appId = "11111111-1111-1111-1111-111111111111"; // Paste your own app ID here
 string appSecret = "22222222-2222-2222-2222-222222222222"; // Paste your own app secret here for a test, and then store it in a safe place!
 const string authority = https://login.microsoftonline.com;
 const string audience = https://api.securitycenter.microsoft.com;

 IConfidentialClientApplication myApp = ConfidentialClientApplicationBuilder.Create(appId).WithClientSecret(appSecret).WithAuthority($"{authority}/{tenantId}").Build();

 List<string> scopes = new List<string>() { $"{audience}/.default" };

 AuthenticationResult authResult = myApp.AcquireTokenForClient(scopes).ExecuteAsync().GetAwaiter().GetResult();

 string token = authResult.AccessToken;
----
+
==== Use Python

See link:run-advanced-query-sample-python.md#get-token[Get token using Python].

==== Use Curl

____
[!NOTE] The following procedure assumes that Curl for Windows is already installed on your computer.
____

. Open a command prompt, and set CLIENT_ID to your Azure application ID.
. Set CLIENT_SECRET to your Azure application secret.
. Set TENANT_ID to the Azure tenant ID of the customer that wants to use your app to access Defender for Endpoint.
. Run the following command:
+
[,console]
----
 curl -i -X POST -H "Content-Type:application/x-www-form-urlencoded" -d "grant_type=client_credentials" -d "client_id=%CLIENT_ID%" -d "scope=https://securitycenter.onmicrosoft.com/windowsatpservice/.default" -d "client_secret=%CLIENT_SECRET%" "https://login.microsoftonline.com/%TENANT_ID%/oauth2/v2.0/token" -k
----
+
You will get an answer in the following form:
+
[,console]
----
 {"token_type":"Bearer","expires_in":3599,"ext_expires_in":0,"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIn <truncated> aWReH7P0s0tjTBX8wGWqJUdDA"}
----

=== Validate the token

Ensure that you got the correct token:

. Copy and paste the token you got in the previous step into https://jwt.ms[JWT] in order to decode it.
. Validate that you get a 'roles' claim with the desired permissions.
+
In the following image, you can see a decoded token acquired from an app with permissions to all of  Microsoft Defender for Endpoint's roles:
+
:::image type="content" source="images/webapp-decoded-token.png" alt-text="The token details portion" lightbox="images/webapp-decoded-token.png":::

=== Use the token to access Microsoft Defender for Endpoint API

. Choose the API you want to use.
For more information, see xref:exposed-apis-list.adoc[Supported Defender for Endpoint APIs].
. Set the authorization header in the http request you send to "Bearer \{token}" (Bearer is the authorization scheme).
. The expiration time of the token is one hour.
You can send more than one request with the same token.

The following is an example of sending a request to get a list of alerts *using C#*:

[,csharp]
----
var httpClient = new HttpClient();

var request = new HttpRequestMessage(HttpMethod.Get, "https://api.securitycenter.microsoft.com/api/alerts");

request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);

var response = httpClient.SendAsync(request).GetAwaiter().GetResult();

// Do something useful with the response
----

=== See also

* xref:exposed-apis-list.adoc[Supported Microsoft Defender for Endpoint APIs]
* xref:exposed-apis-create-app-nativeapp.adoc[Access Microsoft Defender for Endpoint on behalf of a user]
