= 
mjcaparas
:keywords: apis, graph api, supported apis, get, device, IP, find, find
device, by ip, ip

== Find devices by internal IP API

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!Includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!Includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Find link:machine.md[Machines] seen with the requested internal IP in
the time range of 15 minutes prior and after a given timestamp.

=== Limitations

[arabic]
. The given timestamp must be in the past 30 days.
. Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Microsoft Defender for Endpoint APIs]

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Machine.Read.All |`Read all machine profiles'

|Application |Machine.ReadWrite.All |`Read and write all machine
information'

|Delegated (work or school account) |Machine.Read |`Read machine
information'

|Delegated (work or school account) |Machine.ReadWrite |`Read and write
machine information'
|===

____
[!NOTE] When obtaining a token using user credentials:

* Response will include only devices that the user have access to based
on device group settings (See link:machine-groups.md[Create and manage
device groups] for more information)
* The user needs to have at least the following role permission: `View
Data' (See link:user-roles.md[Create and manage roles] for more
information)
* Response will include only devices that the user have access to based
on device group settings (See link:machine-groups.md[Create and manage
device groups] for more information)

Device group creation is supported in Defender for Endpoint Plan 1 and
Plan 2.
____

=== HTTP request

[source,http]
----
GET /api/machines/findbyip(ip='{IP}',timestamp={TimeStamp})
----

=== Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|===

=== Request body

Empty

=== Response

If successful - 200 OK with list of the machines in the response body.
If the timestamp is not in the past 30 days - 400 Bad Request.

=== Example

==== Request

Here’s an example of the request.

[source,http]
----
GET https://api.securitycenter.microsoft.com/api/machines/findbyip(ip='10.248.240.38',timestamp=2019-09-22T08:44:05Z)
----
