= 
mjcaparas
:keywords: apis, graph api, supported apis, get, device, log on, users

== Get machine logon users API

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Retrieves a collection of logged on users on a specific device.

=== Limitations

[arabic]
. You can query on alerts last updated according to your configured
retention period.
. Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Microsoft Defender for Endpoint APIs]

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |User.Read.All |`Read user profiles'
|Delegated (work or school account) |User.Read.All |`Read user profiles'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to have at least the following role permission: `View
Data'. For more information, see link:user-roles.md[Create and manage
roles].
* Response will include users only if the device is visible to the user,
based on device group settings. For more information, see
link:machine-groups.md[Create and manage device groups].

Device group creation is supported in Defender for Endpoint Plan 1 and
Plan 2.
____

=== HTTP request

[source,http]
----
GET /api/machines/{id}/logonusers
----

=== Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|===

=== Request body

Empty

=== Response

If successful and device exists - 200 OK with list of link:user.md[user]
entities in the body. If device was not found - 404 Not Found.

=== Example

==== Request

Here is an example of the request.

[source,http]
----
GET https://api.securitycenter.microsoft.com/api/machines/1e5bc9d7e413ddd7902c2932e418702b84d0cc07/logonusers
----

==== Response

Here is an example of the response.

[source,http]
----
HTTP/1.1 200 OK
Content-type: application/json
{
    "@odata.context": "https://api.securitycenter.microsoft.com/api/$metadata#Users",
    "value": [
        {
            "id": "contoso\\user1",
            "accountName": "user1",
            "accountDomain": "contoso",
            "firstSeen": "2019-12-18T08:02:54Z",
            "lastSeen": "2020-01-06T08:01:48Z",
            "logonTypes": "Interactive",
            "isDomainAdmin": true,
            "isOnlyNetworkUser": false
        },
        ...
    ]
}
----
