= 
siosulli
:keywords: apis, graph api, supported apis, scan history, definition

== Get scan history by definition

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 2]
* link:../defender-vulnerability-management/index.yml[Microsoft Defender
Vulnerability Management]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365
Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

____
Want to experience Microsoft Defender Vulnerability Management? Learn
more about how you can sign up to the
link:../defender-vulnerability-management/get-defender-vulnerability-management.md[Microsoft
Defender Vulnerability Management public preview trial].
____

{empty}[!Includelink:../../includes/prerelease.md[Prerelease
information]]

{empty}[!Includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!Includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Retrieves a list of the scan history by definitions.

=== Limitations

[arabic]
. Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Microsoft Defender for Endpoint APIs].

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Machine.Read.All |Read all scan information.

|Delegated (work or school account) |Machine.Read.All |Read all scan
information.
|===

____
[!NOTE] When obtaining a token using user credentials:

* To view data the user needs to have at least the following role
permission: `ViewData' or `TvmViewData' (See link:user-roles.md[Create
and manage roles] for more information)
____

=== HTTP request

[source,http]
----
POST api/DeviceAuthenticatedScanDefinitions/GetScanHistoryByScanDefinitionId
----

=== Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|Content-Type |string |application/json. *Required*.
|===

=== Request body

In the request body, supply a JSON object with the following parameters:

[cols="<,<,<",options="header",]
|===
|Parameter |Type |Description
|ScanDefinitionIds |String |The scan Id. *Required*.
|===

=== Response

If successful, this method returns 200 - OK response code with a list of
the scan history by definition.

=== Example request

Here is an example of the request.

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/DeviceAuthenticatedScanDefinitions/GetScanHistoryByScanDefinitionId
----

[source,json]
----
{
    "ScanDefinitionIds": ["4ad8d463-6b3a-4894-b42a-a2de9ea0a8ae", "60c4aa57-c573-4488-8d18-230914792a92", "c6220f67-2cad-4ba3-a2fa-7ded6384da56"]
}
----

=== Response example

[source,json]
----
{
"@odata.context": "https://api.securitycenter.microsoft.com/api/DeviceAuthenticatedScanDefinitions/GetScanHistoryByScanDefinitionId",
    "value": [
    {
    "ScanDefinitionIds": "4ad8d463-6b3a-4894-b42a-a2de9ea0a8ae",
    "LastScanned": "2022-12-20T11:14:24.5561791Z",
    "ScanStatus": "Partial Success",
    "ScannerId": "625431694b7d2ca9d07e77ca1b029ef216bebb6d"
    },
    {
    "ScanDefinitionIds": "60c4aa57-c573-4488-8d18-230914792a92",
    "LastScanned": "2022-11-17T15:13:24.5561791Z",
    "ScanStatus": "Partial Success",
    "ScannerId": "625431694b7d2ca9d07e77ca1b029ef216bebb6d"
    },
    {
    "ScanDefinitionIds": "c6220f67-2cad-4ba3-a2fa-7ded6384da56",
    "LastScanned": "2022-11-10T18:15:24.5561791Z",
    "ScanStatus": "Partial Success",
    "ScannerId": "625431694b7d2ca9d07e77ca1b029ef216bebb6d"
    },
   ]
}
----
