= Get alert related machine information
:audience: ITPro
:author: mjcaparas
:description: Retrieve all devices related to a specific alert using Microsoft Defender for Endpoint.
:keywords: apis, graph api, supported apis, get alert information, alert information, related device
:manager: dansimp
:ms.author: macapara
:ms.collection: M365-security-compliance
:ms.custom: api
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Get alert related machine information API

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign up for a free trial.]
____

[!includexref:../../includes/microsoft-defender-api-usgov.adoc[Microsoft Defender for Endpoint API URIs for US Government]]

[!includexref:../../includes/improve-request-performance.adoc[Improve request performance]]

=== API description

Retrieves xref:machine.adoc[Device] related to a specific alert.

=== Limitations

. You can query on alerts last updated according to your configured retention period.
. Rate limitations for this API are 100 calls per minute and 1500 calls per hour.

=== Permissions

One of the following permissions is required to call this API.
To learn more, including how to choose permissions, see xref:apis-intro.adoc[Use Microsoft Defender for Endpoint APIs]

|===
| Permission type | Permission | Permission display name

| Application
| Machine.Read.All
| 'Read all machine information'

| Application
| Machine.ReadWrite.All
| 'Read and write all machine information'

| Delegated (work or school account)
| Machine.Read
| 'Read machine information'

| Delegated (work or school account)
| Machine.ReadWrite
| 'Read and write machine information'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to have at least the following role permission: 'View Data' (See xref:user-roles.adoc[Create and manage roles] for more information)
* The user needs to have access to the device associated with the alert, based on device group settings (See xref:machine-groups.adoc[Create and manage device groups] for more information)

Device group creation is supported in Defender for Endpoint Plan 1 and Plan 2.
____

=== HTTP request

[,http]
----
GET /api/alerts/{id}/machine
----

=== Request headers

|===
| Name | Type | Description

| Authorization
| String
| Bearer \{token}.
*Required*.
|===

=== Request body

Empty

=== Response

If successful and alert and device exist - 200 OK.
If alert not found or device not found - 404 Not Found.

=== Example

==== Request example

Here is an example of the request.

[,http]
----
GET https://api.securitycenter.microsoft.com/api/alerts/636688558380765161_2136280442/machine
----

==== Response example

Here is an example of the response.

[,json]
----
{
    "id": "1e5bc9d7e413ddd7902c2932e418702b84d0cc07",
    "computerDnsName": "mymachine1.contoso.com",
    "firstSeen": "2018-08-02T14:55:03.7791856Z",
    "lastSeen": "2021-01-25T07:27:36.052313Z",
    "osPlatform": "Windows10" "Windows11",
    "osProcessor": "x64",
    "version": "1901",
    "lastIpAddress": "10.166.113.46",
    "lastExternalIpAddress": "167.220.203.175",
    "osBuild": 19042,
    "healthStatus": "Active",
    "deviceValue": "Normal",
    "rbacGroupName": "The-A-Team",
    "riskScore": "Low",
    "exposureLevel": "Low",
    "aadDeviceId": "fd2e4d29-7072-4195-aaa5-1af139b78028",
    "machineTags": [
        "Tag1",
        "Tag2"
    ],
    "ipAddresses": [
        {
            "ipAddress": "10.166.113.47",
            "macAddress": "8CEC4B897E73",
            "operationalStatus": "Up"
        },
        {
            "ipAddress": "2a01:110:68:4:59e4:3916:3b3e:4f96",
            "macAddress": "8CEC4B897E73",
            "operationalStatus": "Up"
        }
    ]
}
----
