= List Investigations API
:audience: ITPro
:author: mjcaparas
:description: Use this API to create calls related to get Investigations collection
:keywords: apis, graph api, supported apis, Investigations collection
:manager: dansimp
:ms.author: macapara
:ms.collection: M365-security-compliance
:ms.custom: api
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== List Investigations API

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign up for a free trial.]
____

[!includexref:../../includes/microsoft-defender-api-usgov.adoc[Microsoft Defender for Endpoint API URIs for US Government]]

[!includexref:../../includes/improve-request-performance.adoc[Improve request performance]]

=== API description

Retrieves a collection of xref:investigation.adoc[Investigations].

Supports https://www.odata.org/documentation/[OData V4 queries].

The OData's `$filter` query is supported on: `startTime`, `id`, `state`, `machineId` and `triggeringAlertId` properties.
+ `$stop` with max value of 10,000   + `$skip`

See examples at xref:exposed-apis-odata-samples.adoc[OData queries with Microsoft Defender for Endpoint]

=== Limitations

. Maximum page size is 10,000.
. Rate limitations for this API are 100 calls per minute and 1500 calls per hour.

=== Permissions

One of the following permissions is required to call this API.
To learn more, including how to choose permissions, see xref:apis-intro.adoc[Use Microsoft Defender for Endpoint APIs]

|===
| Permission type | Permission | Permission display name

| Application
| Alert.Read.All
| 'Read all alerts'

| Application
| Alert.ReadWrite.All
| 'Read and write all alerts'

| Delegated (work or school account)
| Alert.Read
| 'Read alerts'

| Delegated (work or school account)
| Alert.ReadWrite
| 'Read and write alerts'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to have at least the following role permission: 'View Data' (See xref:user-roles.adoc[Create and manage roles] for more information)
____

=== HTTP request

[,http]
----
GET https://api.securitycenter.microsoft.com/api/investigations
----

=== Request headers

|===
| Name | Type | Description

| Authorization
| String
| Bearer \{token}.
*Required*.
|===

=== Request body

Empty

=== Response

If successful, this method returns 200, Ok response code with a collection of xref:investigation.adoc[Investigations] entities.

=== Example

==== Request example

Here is an example of a request to get all investigations:

[,http]
----
GET https://api.securitycenter.microsoft.com/api/investigations
----

==== Response example

Here is an example of the response:

[,json]
----
{
    "@odata.context": "https://api.securitycenter.microsoft.com/api/$metadata#Investigations",
    "value": [
        {
            "id": "63017",
            "startTime": "2020-01-06T14:11:34Z",
            "endTime": null,
            "state": "Running",
            "cancelledBy": null,
            "statusDetails": null,
            "machineId": "a69a22debe5f274d8765ea3c368d00762e057b30",
            "computerDnsName": "desktop-gtrcon0",
            "triggeringAlertId": "da637139166940871892_-598649278"
        }
        ...
    ]
}
----
