= 
mjcaparas
:keywords: apis, graph api, supported apis, get, domain, domain related
devices

== Get domain statistics API

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Retrieves the statistics on the given domain.

=== Limitations

[arabic]
. Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.
. The maximum value for `lookbackhours` is 720 hours (30 days).

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Microsoft Defender for Endpoint APIs]

[cols="<,<,<",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |URL.Read.All |`Read URLs'
|Delegated (work or school account) |URL.Read.All |`Read URLs'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to have at least the following role permission: `View
Data' (See link:user-roles.md[Create and manage roles] for more
information)
____

=== HTTP request

[source,http]
----
GET /api/domains/{domain}/stats
----

=== Request headers

[cols="<,<",options="header",]
|===
|Header |Value
|Authorization |Bearer \{token}. *Required*.
|===

=== Request URI parameters

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Name |Type |Description
|lookBackHours |Int32 |Defines the hours we search back to get the
statistics. Defaults to 30 days. *Optional*.
|===

=== Request body

Empty

=== Response

If successful and domain exists - 200 OK, with statistics object in the
response body. If domain does not exist - 200 OK with an prevalence set
to 0.

=== Example

==== Request example

Here is an example of the request.

[source,http]
----
GET https://api.securitycenter.microsoft.com/api/domains/example.com/stats?lookBackHours=48
----

==== Response example

Here is an example of the response.

[source,json]
----
{
    "@odata.context": "https://api.securitycenter.microsoft.com/api/$metadata#microsoft.windowsDefenderATP.api.InOrgDomainStats",
    "host": "example.com",
    "organizationPrevalence": 4070,
    "orgFirstSeen": "2017-07-30T13:23:48Z",
    "orgLastSeen": "2017-08-29T13:09:05Z"
}
----
