= 
siosulli
:keywords: api, apis, export assessment, per device assessment, per
machine assessment, vulnerability assessment report, device
vulnerability assessment, device vulnerability report, secure
configuration assessment, secure configuration report, software
vulnerabilities assessment, software vulnerability report, vulnerability
report by machine,

== List all security baselines assessment profiles

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]
* link:../defender-vulnerability-management/index.yml[Microsoft Defender
Vulnerability Management]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365
Defender]

____
Want to experience Microsoft Defender Vulnerability Management? Learn
more about how you can sign up to the
link:../defender-vulnerability-management/get-defender-vulnerability-management.md[Microsoft
Defender Vulnerability Management public preview trial].
____

=== 1. Get security baselines assessment profiles

This API retrieves a list of all security baselines assessment profiles
created by the organization.

==== 1.1 Parameters

* Supports OData V4 queries.
* OData supported operators:
** $filter on : id,name, operatingSystem, operatingSystemVersion,
status, settingsNumber, passedDevices, totalDevices
** $top with max value of 10,000.
** $skip.

==== 1.2 HTTP request

[source,http]
----
GET:/api/baselineProfiles
----

==== 1.3 Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|===

==== 1.4 Properties

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Property |Type |Description
|Id |String |Unique identifier for the specific baseline profile.

|name |String |The profile name.

|description |String |The profile description.

|benchmark |String |The profile benchmark.

|version |String |The profile version.

|operatingSystem |String |The profile applicable operating system.

|operatingSystemVersion |String |The profile applicable operating system
version.

|status |Boolean |Indicates whether the profile is active or not

|complianceLevel |String |The compliance level chosen for the profile.

|settingsNumber |Int |Number of selected configurations in the profile.

|createdBy |String |The user that created this profile.

|lastUpdatedBy |DateTime |The last user to modify this profile.

|createdOnTimeOffset |DateTime |The date and time the profile was
created.

|lastUpdateTimeOffset |DateTime |The date and time the profile was last
updated.

|passedDevices |Int |The number of devices applicable to this profile
that are compliant with all of the profile configurations.

|totalDevices |Int |Number of devices applicable to this profile.
|===

=== 1.5 Example

==== 1.5.1 Request example

[source,http]
----
GET https://api.securitycenter.microsoft.com/api/baselineProfiles
----

==== 1.6.2 Response example

[source,json]
----
{
    "@odata.context": "https:// api.securitycenter.microsoft.com/api/$metadata#Collection(microsoft.windowsDefenderATP.api.PublicBaselineProfileDto)",
    "value":
    [
        {
            "id": "02bcbb9d-d197-479e-811e-1cd5a6f9f8fa",
            "name": "Windows 10 build 1909 CIS profile",
            "description": "important",
            "benchmark": "CIS",
            "version": "1.0.0",
            "operatingSystem": "Windows 10",
            "operatingSystemVersion": "1909",
            "status": true,
            "complianceLevel": "Level 1 (L1) - Corporate/Enterprise Environment (general use)",
            "settingsNumber": 51,
            "createdBy": "user@org.net",
            "lastUpdatedBy": null,
            "createdOnTimestampUTC": "0001-01-01T00:00:00Z",
            "lastUpdateTimestampUTC": "0001-01-01T00:00:00Z",
            "passedDevices": 0,
            "totalDevices": 10
        }
     ]
}
----

=== See also

* link:export-security-baseline-assessment.md[Export security baselines
assessment]
* link:get-security-baselines-assessment-configurations.md[Get security
baselines assessment configurations]
