= 
siosulli
:keywords: apis, graph api, supported apis, get, browser extension
information, Microsoft Defender for Endpoint, Microsoft Defender
Vulnerability Management

== Get browser extensions permission information

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]
* link:../defender-vulnerability-management/index.yml[Microsoft Defender
Vulnerability Management]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365
Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.].
____

____
Want to experience Microsoft Defender Vulnerability Management? Learn
more about how you can sign up to the
link:../defender-vulnerability-management/get-defender-vulnerability-management.md[Microsoft
Defender Vulnerability Management public preview trial].
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

{empty}[!includelink:../../includes/prerelease.md[Prerelease
information]]

=== API description

Retrieves a list of all the permissions requested by a specific browser
extension. This is a static data description and would mainly be used to
enhance the data returned by the
link:get-assessment-browser-extensions.md[Export browser extensions
assessment API].

By combining these APIs you’ll be able to see a description of the
permissions requested by the browser extensions that come up in the
link:get-assessment-browser-extensions.md[Export browser extensions
assessment] results.

Supports https://www.odata.org/documentation/[OData V4 queries]. OData
supported operators: `$filter` on: `id`, `name`, `description`,
`cvssV3`, `publishedOn`, `severity`, and `updatedOn` properties. `$top`
with max value of 10,000. `$skip`. See examples at
link:exposed-apis-odata-samples.md[OData queries with Microsoft Defender
for Endpoint].

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Microsoft Defender for Endpoint APIs] for details.

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Software.Read.All |`Read Threat and Vulnerability
Management software information'

|Delegated (work or school account) |Software.Read |`Read Threat and
Vulnerability Management software information'
|===

=== HTTP request

[source,http]
----
GET api/browserextensions/permissionsinfo
----

=== Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|===

=== Request body

Empty

=== Response

If successful, this method returns 200 OK with the list of all
permissions requested by a browser extension in the body.

=== Example

==== Request example

Here is an example of the request.

[source,http]
----
GET https://api.securitycenter.microsoft.com/api/browserextensions/permissionsinfo
----

==== Response example

Here is an example of the response.

[source,json]
----
{
    "@odata.context": "https://api.securitycenter.microsoft.com/api/$metadata#BrowserExtension",
    "value": [
{
  "value": [
    {
      "key": "audioCapture",
      "permissionName": "Capture audio from attached mic or webcam",
      "description": "Capture audio from attached mic or webcam. Could be used to listen in on use."
    },
    {
      "key": "app.window.fullscreen.overrideEsc",
      "permissionName": "Prevent escape button from exiting fullscreen",
      "description": "Can prevent escape button from exiting fullscreen."
    },
    {
      "key": "browsingData",
      "permissionName": "Clear browsing data",
      "description": "Clears browsing data which could result in a forensics/logging issues."
    },
    {
      "key": "content_security_policy",
      "permissionName": "Can manipulate default Content Security Policy (CSP)",
      "description": "CSP works as a block/allow listing mechanism for resources loaded or executed by your extensions. Can manipulate default CSP."
    }

            ]
}
    ]
----

=== See also

* link:get-assessment-browser-extensions.md[Get browser extensions
permission info]
* link:../defender-vulnerability-management/tvm-browser-extensions.md[Browser
extensions assessment]

=== Other related

* link:../defender-vulnerability-management/defender-vulnerability-management.md[Vulnerability
management]
* link:../defender-vulnerability-management/tvm-weaknesses.md[Vulnerabilities
in your organization]
