= List devices by software
:audience: ITPro
:author: DulceMontemayor
:description: Retrieve a list of devices that has this software installed.
:keywords: apis, graph api, supported apis, get, list devices, devices list, list devices by software, Microsoft Defender for Endpoint tvm api
:manager: dansimp
:ms.author: dolmont
:ms.collection: M365-security-compliance
:ms.custom: api
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== List devices by software

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign up for a free trial.]
____

[!includexref:../../includes/microsoft-defender-api-usgov.adoc[Microsoft Defender for Endpoint API URIs for US Government]]

[!includexref:../../includes/improve-request-performance.adoc[Improve request performance]]

[!includexref:../../includes/prerelease.adoc[Prerelease information]]

Retrieve a list of device references that has this software installed.

=== Permissions

One of the following permissions is required to call this API.
To learn more, including how to choose permissions, see xref:apis-intro.adoc[Use Microsoft Defender for Endpoint APIs] for details.

|===
| Permission type | Permission | Permission display name

| Application
| Software.Read.All
| 'Read Threat and Vulnerability Management Software information'

| Delegated (work or school account)
| Software.Read
| 'Read Threat and Vulnerability Management Software information'
|===

=== HTTP request

[,http]
----
GET /api/Software/{Id}/machineReferences
----

=== Request headers

|===
| Name | Type | Description

| Authorization
| String
| Bearer \{token}.*Required*.
|===

=== Request body

Empty

=== Response

If successful, this method returns 200 OK and a list of devices with the software installed in the body.

=== Example

==== Request example

Here is an example of the request.

[,http]
----
GET https://api.securitycenter.microsoft.com/api/Software/microsoft-_-edge/machineReferences
----

==== Response example

Here is an example of the response.

[,json]
----

{
    "@odata.context": "https://api.securitycenter.microsoft.com/api/$metadata#MachineReferences",
    "value": [
        {
            "id": "7c7e1896fa39efb0a32a2cf421d837af1b9bf762",
            "computerDnsName": "dave_desktop",
            "osPlatform": "Windows10" "Windows11",
            "rbacGroupName": "GroupTwo"
        },
        {
            "id": "7d5cc2e7c305e4a0a290392abf6707f9888fda0d",
            "computerDnsName": "jane_PC",
            "osPlatform": "Windows10" "Windows11",
            "rbacGroupName": "GroupTwo"
        }
        ...
    ]
}
----

=== Related topics

* link:/microsoft-365/security/defender-endpoint/next-gen-threat-and-vuln-mgt[Microsoft Defender Vulnerability Management]
* link:/microsoft-365/security/defender-endpoint/tvm-software-inventory[Defender Vulnerability Management software inventory]
