= 
jweston-1
:keywords: apis, remediation, remediation api, get, remediation tasks,
remediation exposed devices

== List exposed devices of one remediation activity

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365
Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/prerelease.md[Prerelease
information]]

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API Description

Returns information about exposed devices for the specified remediation
task.

link:tvm-remediation.md[Learn more about remediation activities].

=== List exposed devices associated with a remediation task (id)

*URL:* GET: /api/remediationTasks/\{id}/machineReferences

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Microsoft Defender for Endpoint APIs for details.]

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |RemediationTasks.Read.All |'Read Threat and Vulnerability
Management vulnerability information'

|Delegated (work or school account) |RemediationTask.Read.Read |'Read
Threat and Vulnerability Management vulnerability information'
|===

=== Properties details

[width="100%",cols="<25%,<25%,<25%,<25%",options="header",]
|===
|Property (id) |Data type |Description |Example
|id |String |Device ID |w2957837fwda8w9ae7f023dba081059dw8d94503

|computerDnsName |String |Device name
|PC-SRV2012R2Foo.UserNameVldNet.local

|osPlatform |String |Device operating system |WindowsServer2012R2

|rbacGroupName |String |Name of the device group this device is
associated with |Servers
|===

=== Example

==== Request example

[source,http]
----
GET https://api.securitycenter.windows.com/api/remediationtasks/03942ef5-aecb-4c6e-b555-d6a97013844c/machinereferences
----

==== Response example

[source,json]
----
{
    "@odata.context": "https://api.securitycenter.windows.com/api/$metadata#MachineReferences",
    "value": [
        {
            "id": "3cb5df6bb3640a2d37ad09fcd357b182d684fafc",
            "computerDnsName": "ComputerPII_2ea21b2d97c9df23c143ad9e3e454cb674232529.DomainPII_21eed80b086e79bdfa178eabfa25e8be9acfa346.corp.contoso.com",
            "osPlatform": "WindowsServer2016",
            "rbacGroupName": "UnassignedGroup",

        },
        {
            "id": "3d9b1ca53e8f077199c7dcbfc9dbfa78f9bf1918",
            "computerDnsName": "ComputerPII_001d606fc149567c192747f48fae304b43c0ddba.DomainxPII_21eed80b086e79bdfa178eabfa25e8be9acfa346.corp.contoso.com",
            "osPlatform": "WindowsServer2012R2",
            "rbacGroupName": "UnassignedGroup",

        },
        {
            "id": "3db8b27e6172951d7ea2e2d75945abec56feaf82",
            "computerDnsName": "ComputerPII_ce60cfbjj4b82a091deb5eae560332bba99a9bd7.DomainPII_0bc1aee0fa396d175e514bd61a9e7a5b2b07ee8e.corp.contoso.com",
            "osPlatform": "WindowsServer2016",
            "rbacGroupName": "UnassignedGroup",

        },
        {
            "id": "3bad326dcda5b53fab47408cd4a7080f3f3cc8ab",
            "computerDnsName": "ComputerPII_b6b35960dd6539d1d1cef5ada02e235e7b357408.DomainPII_21eed80b089e76bdfa178eadfa25e8de9acfa346.corp.contoso.com",
            "osPlatform": "WindowsServer2012R2",
            "rbacGroupName": "UnassignedGroup",

        }
]
}
----

=== See also

* link:get-remediation-methods-properties.md[Remediation methods and
properties]
* link:get-remediation-one-activity.md[Get one remediation activity by
Id]
* link:get-remediation-all-activities.md[List all remediation
activities]
* link:next-gen-threat-and-vuln-mgt.md[Microsoft Defender Vulnerability
Management]
* link:tvm-weaknesses.md[Vulnerabilities in your organization]
