= List all recommendations
:audience: ITPro
:author: DulceMontemayor
:description: Retrieves a list of all security recommendations affecting the organization.
:keywords: apis, graph api, supported apis, get, security recommendations, Microsoft Defender for Endpoint tvm api, threat and vulnerability management, threat and vulnerability management api, mdvm
:manager: dansimp
:ms.author: dolmont
:ms.collection: M365-security-compliance
:ms.custom: api
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== List all recommendations

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign up for a free trial.]
____

[!includexref:../../includes/microsoft-defender-api-usgov.adoc[Microsoft Defender for Endpoint API URIs for US Government]]

[!includexref:../../includes/improve-request-performance.adoc[Improve request performance]]

[!includexref:../../includes/prerelease.adoc[Prerelease information]]

Retrieves a list of all security recommendations affecting the organization.

=== API description

Returns information about all security recommendations affecting the organization.

_URL:_ GET:/api/recommendations  + Supports https://www.odata.org/documentation/[OData V4 queries].
+ OData supported operators:  + `$filter` on:  `id`, `productName`, `vendor`, `recommendedVersion`, `recommendationCategory`, `subCategory`, `severityScore`, `remediationType`, `recommendedProgram`, `recommendedVendor`, and `status` properties.
+ `$top` with max value of 10,000.
+ `$skip`.
+ See examples at xref:exposed-apis-odata-samples.adoc[OData queries with Microsoft Defender for Endpoint].

=== Permissions

One of the following permissions is required to call this API.
To learn more, including how to choose permissions, see xref:apis-intro.adoc[Use Microsoft Defender for Endpoint APIs] for details.

|===
| Permission type | Permission | Permission display name

| Application
| SecurityRecommendation.Read.All
| 'Read Threat and Vulnerability Management security recommendation information'

| Delegated (work or school account)
| SecurityRecommendation.Read
| 'Read Threat and Vulnerability Management security recommendation information'
|===

=== HTTP request

[,http]
----
GET /api/recommendations
----

=== Request headers

|===
| Name | Type | Description

| Authorization
| String
| Bearer \{token}.
*Required*.
|===

=== Request body

Empty

=== Response

If successful, this method returns 200 OK with the list of security recommendations in the body.

=== Example

==== Request

Here is an example of the request.

[,http]
----
GET https://api.securitycenter.microsoft.com/api/recommendations
----

==== Response

Here is an example of the response.

[,json]
----
{
    "@odata.context": "https://api.securitycenter.microsoft.com/api/$metadata#Recommendations",
    "value": [
        {
            "id": "va-_-microsoft-_-windows_10" "va-_-microsoft-_-windows_11",
            "productName": "windows_10" "Windows_11",
            "recommendationName": "Update Windows 10" "Update Windows 11",
            "weaknesses": 397,
            "vendor": "microsoft",
            "recommendedVersion": "",
            "recommendationCategory": "Application",
            "subCategory": "",
            "severityScore": 0,
            "publicExploit": true,
            "activeAlert": false,
            "associatedThreats": [
                "3098b8ef-23b1-46b3-aed4-499e1928f9ed",
                "40c189d5-0330-4654-a816-e48c2b7f9c4b",
                "4b0c9702-9b6c-4ca2-9d02-1556869f56f8",
                "e8fc2121-3cf3-4dd2-9ea0-87d7e1d2b29d",
                "94b6e94b-0c1d-4817-ac06-c3b8639be3ab"
            ],
            "remediationType": "Update",
            "status": "Active",
            "configScoreImpact": 0,
            "exposureImpact": 7.674418604651163,
            "totalMachineCount": 37,
            "exposedMachinesCount": 7,
            "nonProductivityImpactedAssets": 0,
            "relatedComponent": "Windows 10" "Windows 11"
        }
        ...
     ]
}
----

=== See also

* link:/microsoft-365/security/defender-endpoint/next-gen-threat-and-vuln-mgt[Microsoft Defender Vulnerability Management]
* link:/microsoft-365/security/defender-endpoint/tvm-security-recommendation[Vulnerability management security recommendations]
