= 
mjcaparas
:keywords: apis, graph api, supported apis, upload to library

== Get live response results

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]

{empty}[!includelink:../../includes/prerelease.md[Prerelease
information]]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Retrieves a specific live response command result by its index.

=== Limitations

[arabic]
. Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.

=== Minimum requirements

Before you can initiate a session on a device, make sure you fulfill the
following requirements:

* *Verify that you’re running a supported version of Windows*.
+
Devices must be running one of the following versions of Windows
** *Windows 11*
** *Windows 10*
*** link:/windows/whats-new/whats-new-windows-10-version-1909[Version
1909] or later
*** link:/windows/whats-new/whats-new-windows-10-version-1903[Version
1903] with
https://support.microsoft.com/help/4515384/windows-10-update-kb4515384[KB4515384]
*** link:/windows/whats-new/whats-new-windows-10-version-1809[Version
1809 (RS 5)] with
https://support.microsoft.com/help/4537818/windows-10-update-kb4537818[with
KB4537818]
*** link:/windows/whats-new/whats-new-windows-10-version-1803[Version
1803 (RS 4)] with
https://support.microsoft.com/help/4537795/windows-10-update-kb4537795[KB4537795]
*** link:/windows/whats-new/whats-new-windows-10-version-1709[Version
1709 (RS 3)] with
https://support.microsoft.com/help/4537816/windows-10-update-kb4537816[KB4537816]
** *Windows Server 2019 - Only applicable for Public preview*
*** Version 1903 or (with
https://support.microsoft.com/help/4515384/windows-10-update-kb4515384[KB4515384])
later
*** Version 1809 (with
https://support.microsoft.com/help/4537818/windows-10-update-kb4537818[KB4537818])
** *Windows Server 2022*

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Get
started].

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Machine.Read.All |`’Read all machine profiles'’

|Application |“Machine.ReadWrite.All |`Read and write all machine
information'

|Delegated (work or school account) |Machine.LiveResponse |Run live
response on a specific machine
|===

=== HTTP request

[source,http]
----
GET https://api.securitycenter.microsoft.com/api/machineactions/{machine action
id}/GetLiveResponseResultDownloadLink(index={command-index})
----

=== Request headers

[cols=",,",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. Required.
|===

=== Request body

Empty

=== Response

If successful, this method returns 200, Ok response code with object
that holds the link to the command result in the _value_ property. This
link is valid for 30 minutes and should be used immediately for
downloading the package to a local storage. An expired link can be
re-created by another call, and there is no need to run live response
again.

_Runscript transcript properties:_

[cols=",",options="header",]
|===
|Property |Description
|script_name |Executed script name
|exit_code |Executed script exit code
|script_output |Executed script standard output
|script_errors |Executed script standard error output
|===

=== Example

==== Request example

Here is an example of the request.

[source,http]
----
GET https://api.securitycenter.microsoft.com/api/machineactions/988cc94e-7a8f-4b28-ab65-54970c5d5018/GetLiveResponseResultDownloadLink(index=0)
----

==== Response example

Here is an example of the response.

HTTP/1.1 200 Ok

Content-type: application/json

[source,json]
----
{
    "@odata.context": "https://api.securitycenter.microsoft.com/api/$metadata#Edm.String",
    "value": "https://core.windows.net/investigation-actions-data/ID/CustomPlaybookCommandOutput/4ed5e7807ad1fe59b00b664fe06a0f07?se=2021-02-04T16%3A13%3A50Z&sp=r&sv=2019-07-07&sr=b&sig=1dYGe9rPvUlXBPvYSmr6/OLXPY98m8qWqfIQCBbyZTY%3D"
}
----

_File content:_

[source,json]
----
{
    "script_name": "minidump.ps1",
    "exit_code": 0,
    "script_output": "Transcript started, output file is C:\\ProgramData\\Microsoft\\Windows Defender Advanced Threat Protection\\Temp\\PSScriptOutputs\\PSScript_Transcript_{TRANSCRIPT_ID}.txt
C:\\windows\\TEMP\\OfficeClickToRun.dmp.zip\n51 MB\n\u0000\u0000\u0000",
    "script_errors":""
}
----

=== Related topics

* link:get-machineaction-object.md[Get machine action API]
* link:cancel-machine-action.md[Cancel machine action]
* link:run-live-response.md[Run live response]
