= 
mjcaparas
:keywords: apis, graph api, supported apis, Investigations collection

== List Investigations API

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Retrieves a collection of link:investigation.md[Investigations].

Supports https://www.odata.org/documentation/[OData V4 queries].

The OData’s `$filter` query is supported on: `startTime`, `id`, `state`,
`machineId` and `triggeringAlertId` properties. `$stop` with max value
of 10,000 `$skip`

See examples at link:exposed-apis-odata-samples.md[OData queries with
Microsoft Defender for Endpoint]

=== Limitations

[arabic]
. Maximum page size is 10,000.
. Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Microsoft Defender for Endpoint APIs]

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Alert.Read.All |`Read all alerts'

|Application |Alert.ReadWrite.All |`Read and write all alerts'

|Delegated (work or school account) |Alert.Read |`Read alerts'

|Delegated (work or school account) |Alert.ReadWrite |`Read and write
alerts'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to have at least the following role permission: `View
Data' (See link:user-roles.md[Create and manage roles] for more
information)
____

=== HTTP request

[source,http]
----
GET https://api.securitycenter.microsoft.com/api/investigations
----

=== Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|===

=== Request body

Empty

=== Response

If successful, this method returns 200, Ok response code with a
collection of link:investigation.md[Investigations] entities.

=== Example

==== Request example

Here is an example of a request to get all investigations:

[source,http]
----
GET https://api.securitycenter.microsoft.com/api/investigations
----

==== Response example

Here is an example of the response:

[source,json]
----
{
    "@odata.context": "https://api.securitycenter.microsoft.com/api/$metadata#Investigations",
    "value": [
        {
            "id": "63017",
            "startTime": "2020-01-06T14:11:34Z",
            "endTime": null,
            "state": "Running",
            "cancelledBy": null,
            "statusDetails": null,
            "machineId": "a69a22debe5f274d8765ea3c368d00762e057b30",
            "computerDnsName": "desktop-gtrcon0",
            "triggeringAlertId": "da637139166940871892_-598649278"
        }
        ...
    ]
}
----
