= 
mjcaparas
:keywords: apis, graph api, supported apis, get, alert, information, id

== Get alert information by ID API

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Retrieves specific link:alerts.md[Alert] by its ID.

=== Limitations

* You can get alerts last updated according to your configured retention
period.
* Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Microsoft Defender for Endpoint APIs].

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Alert.Read.All |`Read all alerts'

|Application |Alert.ReadWrite.All |`Read and write all alerts'

|Delegated (work or school account) |Alert.Read |`Read alerts'

|Delegated (work or school account) |Alert.ReadWrite |`Read and write
alerts'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to have at least the following role permission: `View
Data' (See link:user-roles.md[Create and manage roles] for more
information)
* The user needs to have access to the device associated with the alert,
based on device group settings (See link:machine-groups.md[Create and
manage device groups] for more information)

Device group creation is supported in Defender for Endpoint Plan 1 and
Plan 2.
____

=== HTTP request

[source,http]
----
GET /api/alerts/{id}
----

=== Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|===

=== Request body

Empty

=== Response

If successful, this method returns 200 OK, and the link:alerts.md[alert]
entity in the response body. If alert with the specified ID was not
found - 404 Not Found.
