= Get browser extensions permission info
:audience: ITPro
:author: siosulli
:description: Retrieves a list of all permissions required for a browser extension
:keywords: apis, graph api, supported apis, get, browser extension information, Microsoft Defender for Endpoint, Microsoft Defender Vulnerability Management
:manager: dansimp
:ms.author: siosulli
:ms.collection: M365-security-compliance
:ms.custom: api
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Get browser extensions permission information

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* link:../defender-vulnerability-management/index.yml[Microsoft Defender Vulnerability Management]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign up for a free trial.].
____

____
Want to experience Microsoft Defender Vulnerability Management?
Learn more about how you can sign up to the xref:../defender-vulnerability-management/get-defender-vulnerability-management.adoc[Microsoft Defender Vulnerability Management public preview trial].
____

[!includexref:../../includes/microsoft-defender-api-usgov.adoc[Microsoft Defender for Endpoint API URIs for US Government]]

[!includexref:../../includes/improve-request-performance.adoc[Improve request performance]]

[!includexref:../../includes/prerelease.adoc[Prerelease information]]

=== API description

Retrieves a list of all the permissions requested by a specific browser extension.
This is a static data description and would mainly be used to enhance the data returned by the xref:get-assessment-browser-extensions.adoc[Export browser extensions assessment API].

By combining these APIs you'll be able to see a description of the permissions requested by the browser extensions that come up in the xref:get-assessment-browser-extensions.adoc[Export browser extensions assessment] results.

{blank} + Supports https://www.odata.org/documentation/[OData V4 queries].
+ OData supported operators:  + `$filter` on:  `id`, `name`, `description`, `cvssV3`, `publishedOn`, `severity`, and `updatedOn` properties.
+ `$top` with max value of 10,000.
+ `$skip`.
+ See examples at xref:exposed-apis-odata-samples.adoc[OData queries with Microsoft Defender for Endpoint].

=== Permissions

One of the following permissions is required to call this API.
To learn more, including how to choose permissions, see xref:apis-intro.adoc[Use Microsoft Defender for Endpoint APIs] for details.

|===
| Permission type | Permission | Permission display name

| Application
| Software.Read.All
| 'Read Threat and Vulnerability Management software information'

| Delegated (work or school account)
| Software.Read
| 'Read Threat and Vulnerability Management software information'
|===

=== HTTP request

[,http]
----
GET api/browserextensions/permissionsinfo
----

=== Request headers

|===
| Name | Type | Description

| Authorization
| String
| Bearer \{token}.
*Required*.
|===

=== Request body

Empty

=== Response

If successful, this method returns 200 OK with the list of all permissions requested by a browser extension in the body.

=== Example

==== Request example

Here is an example of the request.

[,http]
----
GET https://api.securitycenter.microsoft.com/api/browserextensions/permissionsinfo
----

==== Response example

Here is an example of the response.

[,json]
----
{
    "@odata.context": "https://api.securitycenter.microsoft.com/api/$metadata#BrowserExtension",
    "value": [
{
  "value": [
    {
      "key": "audioCapture",
      "permissionName": "Capture audio from attached mic or webcam",
      "description": "Capture audio from attached mic or webcam. Could be used to listen in on use."
    },
    {
      "key": "app.window.fullscreen.overrideEsc",
      "permissionName": "Prevent escape button from exiting fullscreen",
      "description": "Can prevent escape button from exiting fullscreen."
    },
    {
      "key": "browsingData",
      "permissionName": "Clear browsing data",
      "description": "Clears browsing data which could result in a forensics/logging issues."
    },
    {
      "key": "content_security_policy",
      "permissionName": "Can manipulate default Content Security Policy (CSP)",
      "description": "CSP works as a block/allow listing mechanism for resources loaded or executed by your extensions. Can manipulate default CSP."
    }

            ]
}
    ]
----

=== See also

* xref:get-assessment-browser-extensions.adoc[Get browser extensions permission info]
* xref:../defender-vulnerability-management/tvm-browser-extensions.adoc[Browser extensions assessment]

=== Other related

* xref:../defender-vulnerability-management/defender-vulnerability-management.adoc[Vulnerability management]
* xref:../defender-vulnerability-management/tvm-weaknesses.adoc[Vulnerabilities in your organization]
