= Get missing KBs by device ID
:audience: ITPro
:author: dansimp
:description: Retrieves missing security updates by device ID
:keywords: apis, graph api, supported apis, get, list, file, information, device id, threat & vulnerability management api, Microsoft Defender for Endpoint tvm api
:manager: dansimp
:ms.author: dansimp
:ms.collection: M365-security-compliance
:ms.custom: api
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Get missing KBs by device ID

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* link:../defender-vulnerability-management/index.yml[Microsoft Defender Vulnerability Management]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign up for a free trial.]
____

____
Want to experience Microsoft Defender Vulnerability Management?
Learn more about how you can sign up to the xref:../defender-vulnerability-management/get-defender-vulnerability-management.adoc[Microsoft Defender Vulnerability Management public preview trial].
____

[!includexref:../../includes/microsoft-defender-api-usgov.adoc[Microsoft Defender for Endpoint API URIs for US Government]]

[!includexref:../../includes/improve-request-performance.adoc[Improve request performance]]

Retrieves missing KBs (security updates) by device ID

=== HTTP request

[,http]
----
GET /api/machines/{machineId}/getmissingkbs
----

=== Permissions

The following permission is required to call this API.
To learn more, including how to choose permissions, see xref:apis-intro.adoc[Use Microsoft Defender for Endpoint APIs].

|===
| Permission type | Permission | Permission display name

| Application
| Software.Read.All
| 'Read Threat and Vulnerability Management Software information'
|===

=== Request header

|===
| Name | Type | Description

| Authorization
| String
| Bearer \{token}.
*Required*.
|===

=== Request body

Empty

=== Response

If successful, this method returns 200 OK, with the specified device missing kb data in the body.

=== Example

==== Request

Here is an example of the request.

[,http]
----
GET https://api.securitycenter.microsoft.com/api/machines/2339ad14a01bd0299afb93dfa2550136057bff96/getmissingkbs
----

==== Response

Here is an example of the response.

[,json]
----
{
    "@odata.context": "https://api.securitycenter.microsoft.com/api/$metadata#Collection(microsoft.windowsDefenderATP.api.PublicProductFixDto)",
    "value": [
        {
            "id": "4540673",
            "name": "March 2020 Security Updates",
            "productsNames": [
                "windows_10",
                "edge",
                "internet_explorer"
            ],
            "url": "https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4540673",
            "machineMissedOn": 1,
            "cveAddressed": 97
        }
        ]
}
----

=== Related topics

* link:/microsoft-365/security/defender-endpoint/next-gen-threat-and-vuln-mgt[Microsoft Defender Vulnerability Management]
* link:/microsoft-365/security/defender-endpoint/tvm-software-inventory[Defender Vulnerability Management software inventory]
