= 
DulceMontemayor
:keywords: apis, graph api, supported apis, get, vulnerability
information, Microsoft Defender for Endpoint tvm api

== List vulnerabilities by machine and software

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

Retrieves a list of all the vulnerabilities affecting the organization
per link:machine.md[machine] and link:software.md[software].

* If the vulnerability has a fixing KB, it will appear in the response.
* Supports https://www.odata.org/documentation/[OData V4 queries].
* The OData’s `$filter` query is supported on: `id`, `cveId`,
`machineId`, `fixingKbId`, `productName`, `productVersion`, `severity`,
and `productVendor` properties. `$stop` with max value of 10,000 `$skip`

____
[!TIP] This is great API for link:api-power-bi.md[Power BI integration].
____

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Microsoft Defender for Endpoint APIs] for details.

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Vulnerability.Read.All |`Read Threat and Vulnerability
Management vulnerability information'

|Delegated (work or school account) |Vulnerability.Read |`Read Threat
and Vulnerability Management vulnerability information'
|===

=== HTTP request

[source,http]
----
GET /api/vulnerabilities/machinesVulnerabilities
----

=== Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|===

=== Request body

Empty

=== Response

If successful, this method returns 200 OK with the list of
vulnerabilities in the body.

=== Example

==== Request example

Here is an example of the request.

[source,http]
----
GET https://api.securitycenter.microsoft.com/api/vulnerabilities/machinesVulnerabilities
----

==== Response example

Here is an example of the response.

[source,json]
----
{
    "@odata.context": "https://api.securitycenter.microsoft.com/api/$metadata#Collection(microsoft.windowsDefenderATP.api.PublicAssetVulnerabilityDto)",
    "value": [
        {
            "id": "5afa3afc92a7c63d4b70129e0a6f33f63a427e21-_-CVE-2020-6494-_-microsoft-_-edge_chromium-based-_-81.0.416.77-_-",
            "cveId": "CVE-2020-6494",
            "machineId": "5afa3afc92a7c63d4b70129e0a6f33f63a427e21",
            "fixingKbId": null,
            "productName": "edge_chromium-based",
            "productVendor": "microsoft",
            "productVersion": "81.0.416.77",
            "severity": "Low"
        },
        {
            "id": "7a704e17d1c2977c0e7b665fb18ae6e1fe7f3283-_-CVE-2016-3348-_-microsoft-_-windows_server_2012_r2-_-6.3.9600.19728-_-3185911",
            "cveId": "CVE-2016-3348",
            "machineId": "7a704e17d1c2977c0e7b665fb18ae6e1fe7f3283",
            "fixingKbId": "3185911",
            "productName": "windows_server_2012_r2",
            "productVendor": "microsoft",
            "productVersion": "6.3.9600.19728",
            "severity": "Low"
        },
        ...
    ]

}
----

=== See also

* link:/microsoft-365/security/defender-endpoint/next-gen-threat-and-vuln-mgt[Microsoft
Defender Vulnerability Management]
* link:/microsoft-365/security/defender-endpoint/tvm-weaknesses[Vulnerabilities
in your organization]
