= 
dansimp
:keywords: apis, graph api, supported apis, get, alerts, recent

== Get device secure score

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

Retrieves your link:tvm-microsoft-secure-score-devices.md[Microsoft
Secure Score for Devices]. A higher Microsoft Secure Score for Devices
means your endpoints are more resilient from cybersecurity threat
attacks.

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Microsoft Defender for Endpoint APIs] for details.

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Score.Read.All |`Read Threat and Vulnerability Management
score'

|Delegated (work or school account) |Score.Read |`Read Threat and
Vulnerability Management score'
|===

=== HTTP request

[source,http]
----
GET /api/configurationScore
----

=== Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|===

=== Request body

Empty

=== Response

If successful, this method returns 200 OK, with the device secure score
data in the response body.

=== Example

==== Request example

Here is an example of the request.

[source,http]
----
GET https://api.securitycenter.microsoft.com/api/configurationScore
----

==== Response example

Here is an example of the response.

____
[!NOTE] The response list shown here may be truncated for brevity.
____

[source,json]
----
{
    "@odata.context": "https://api.securitycenter.microsoft.com/api/$metadata#ConfigurationScore/$entity",
    "time": "2019-12-03T09:15:58.1665846Z",
    "score": 340
}
----

=== See also

* link:exposed-apis-odata-samples.md[OData queries with Microsoft
Defender for Endpoint]
