= 
dansimp
:keywords: apis, graph api, supported apis, get, list, file,
information, software id, threat & vulnerability management api,
Microsoft Defender for Endpoint tvm api, mdvm, Microsoft Defender
Vulnerability Management

== Get missing KBs by software ID

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

Retrieves missing KBs (security updates) by software ID

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Microsoft Defender for Endpoint APIs] for details.

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Software.Read.All |`Read Threat and Vulnerability
Management Software information'

|Delegated (work or school account) |Software.Read |`Read Threat and
Vulnerability Management Software information'
|===

=== HTTP request

[source,http]
----
GET /api/Software/{Id}/getmissingkbs
----

=== Request header

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|===

=== Request body

Empty

=== Response

If successful, this method returns 200 OK, with the specified software
missing kb data in the body.

=== Example

==== Request

Here is an example of the request.

[source,http]
----
GET https://api.securitycenter.microsoft.com/api/Software/microsoft-_-edge/getmissingkbs
----

==== Response

Here is an example of the response.

[source,json]
----
{
    "@odata.context": "https://api.securitycenter.microsoft.com/api/$metadata#Collection(microsoft.windowsDefenderATP.api.PublicProductFixDto)",
    "value": [
         {
            "id": "4540673",
            "name": "March 2020 Security Updates",
            "productsNames": [
                "edge"
            ],
            "url": "https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4540673",
            "machineMissedOn": 240,
            "cveAddressed": 14
         },
         ...
        ]
}
----

=== Related topics

* link:/microsoft-365/security/defender-endpoint/next-gen-threat-and-vuln-mgt[Microsoft
Defender Vulnerability Management]
* link:/microsoft-365/security/defender-endpoint/tvm-software-inventory[Defender
Vulnerability Management software inventory]
