= 
mjcaparas
:keywords: apis, graph api, supported apis, get, domain, related, alerts

== Get domain-related alerts API

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Retrieves a collection of link:alerts.md[Alerts] related to a given
domain address.

=== Limitations

* You can query on alerts last updated according to your configured
retention period.
* Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Microsoft Defender for Endpoint APIs]

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Alert.Read.All |`Read all alerts'

|Application |Alert.ReadWrite.All |`Read and write all alerts'

|Delegated (work or school account) |Alert.Read |`Read alerts'

|Delegated (work or school account) |Alert.ReadWrite |`Read and write
alerts'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to have at least the following role permission: `View
Data' (See link:user-roles.md[Create and manage roles] for more
information)
* Response will include only alerts, associated with devices, that the
user have access to, based on device group settings (See
link:machine-groups.md[Create and manage device groups] for more
information)

Device group creation is supported in Defender for Endpoint Plan 1 and
Plan 2.
____

=== HTTP request

[source,http]
----
GET /api/domains/{domain}/alerts
----

=== Request headers

[cols=",",options="header",]
|===
|Header |Value
|Authorization |String
|===

=== Request body

Empty

=== Response

If successful and domain exists - 200 OK with list of
link:alerts.md[alert] entities. If domain does not exist - 200 OK with
an empty set.

=== Example

==== Request

Here’s an example of the request.

[source,http]
----
GET https://api.securitycenter.microsoft.com/api/domains/client.wns.windows.com/alerts
----
