= 
mjcaparas
:keywords: apis, graph api, supported apis, machineaction object

== Get machineAction API

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Retrieves specific link:machineaction.md[Machine Action] by its ID.

=== Limitations

* Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Defender for Endpoint APIs].

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Machine.Read.All |`Read all machine profiles'

|Application |Machine.ReadWrite.All |`Read and write all machine
information'

|Delegated (work or school account) |Machine.Read |`Read machine
information'

|Delegated (work or school account) |Machine.ReadWrite |`Read and write
machine information'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to have at least the following role permission: `View
Data' (See link:user-roles.md[Create and manage roles] for more
information)
____

=== HTTP request

[source,http]
----
GET https://api.securitycenter.microsoft.com/api/machineactions/{id}
----

=== Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|===

=== Request body

Empty

=== Response

If successful, this method returns 200, Ok response code with a
link:machineaction.md[Machine Action] entity. If machine action entity
with the specified ID was not found - 404 Not Found.

=== Example

==== Example request

Here is an example of the request.

[source,http]
----
GET https://api.securitycenter.microsoft.com/api/machineactions/2e9da30d-27f6-4208-81f2-9cd3d67893ba
----

==== Response example

Here’s an example of the response.

[source,json]
----
HTTP/1.1 200 Ok
Content-type: application/json
{
    "@odata.context": "https://api.securitycenter.microsoft.com/api/$metadata#MachineActions/$entity",
    "id": "5382f7ea-7557-4ab7-9782-d50480024a4e",
    "type": "Isolate",
    "scope": "Selective",
    "requestor": "Analyst@TestPrd.onmicrosoft.com",
    "requestorComment": "test for docs",
    "status": "Succeeded",
    "machineId": "7b1f4967d9728e5aa3c06a9e617a22a4a5a17378",
    "computerDnsName": "desktop-test",
    "creationDateTimeUtc": "2019-01-02T14:39:38.2262283Z",
    "lastUpdateDateTimeUtc": "2019-01-02T14:40:44.6596267Z",
    "relatedFileInfo": null
}
----
