= 
mjcaparas
:keywords: apis, graph api, supported apis, get, devices, related,
alerts

== Get machine related alerts API

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Retrieves all link:alerts.md[Alerts] related to a specific device.

=== Limitations

[arabic]
. You can query on devices last updated according to your configured
retention period.
. Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Alert.Read.All |`Read all alerts'

|Application |Alert.ReadWrite.All |`Read and write all alerts'

|Delegated (work or school account) |Alert.Read |`Read alerts'

|Delegated (work or school account) |Alert.ReadWrite |`Read and write
alerts'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to have at least the following role permission: `View
Data'. For more information about permissions, see
link:user-roles.md[Create and manage roles].
* The user needs to have access to the device, based on device group
settings. For more information about device group settings, see
link:machine-groups.md[Create and manage device groups].

Device group creation is supported in Defender for Endpoint Plan 1 and
Plan 2. ## HTTP request
____

[source,http]
----
GET /api/machines/{id}/alerts
----

=== Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|===

=== Request body

Empty

=== Response

If successful and device exists: 200 OK with list of
link:alerts.md[alert] entities in the body. If device was not found: 404
Not Found.
