= Grant access to managed security service provider (MSSP)
:audience: ITPro
:author: mjcaparas
:description: Take the necessary steps to configure MSSP integration with the Microsoft Defender for Endpoint
:experimental:
:keywords: managed security service provider, mssp, configure, integration
:manager: dansimp
:ms.author: macapara
:ms.collection: M365-security-compliance
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Grant managed security service provider (MSSP) access (preview)

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-mssp-support-abovefoldlink[Sign up for a free trial.]
____

____
[!IMPORTANT] Some information relates to prereleased product which may be substantially modified before it's commercially released.
Microsoft makes no warranties, express or implied, with respect to the information provided here.
____

To implement a multi-tenant delegated access solution, take the following steps:

. Enable xref:rbac.adoc[role-based access control] in Defender for Endpoint and connect with Active Directory (AD) groups.
. Configure link:/azure/active-directory/governance/identity-governance-overview[Governance Access Packages] for access request and provisioning.
. Manage access requests and audits in link:/azure/active-directory/governance/entitlement-management-request-approve[Microsoft Myaccess].

=== Enable role-based access controls in Microsoft Defender for Endpoint

. *Create access groups for MSSP resources in Customer AAD: Groups*
+
These groups will be linked to the Roles you create in Defender for Endpoint.
To do so, in the customer AD tenant, create three groups.
In our example approach, we create the following groups:

 ** Tier 1 Analyst
 ** Tier 2 Analyst
 ** MSSP Analyst Approvers

. Create Defender for Endpoint roles for appropriate access levels in Customer Defender for Endpoint.
+
To enable RBAC in the customer Microsoft 365 Defender portal, access menu:Settings[Permissions > Roles] and "Turn on roles", from a user account with Global Administrator or Security Administrator rights.
+
:::image type="content" source="images/mssp-access.png" alt-text="MSSP access" lightbox="images/mssp-access.png":::
+
Then, create RBAC roles to meet MSSP SOC Tier needs.
Link these roles to the created user groups via "Assigned user groups".
+
Two possible roles:

 ** *Tier 1 Analysts*
+
Perform all actions except for live response and manage security settings.

 ** *Tier 2 Analysts*
+
Tier 1 capabilities with the addition to xref:live-response.adoc[live response]

+
For more information, see xref:rbac.adoc[Use role-based access control].

=== Configure Governance Access Packages

. *Add MSSP as Connected Organization in Customer AAD: Identity Governance*
+
Adding the MSSP as a connected organization will allow the MSSP to request and have accesses provisioned.
+
To do so, in the customer AD tenant, access Identity Governance: Connected organization.
Add a new organization and search for your MSSP Analyst tenant via Tenant ID or Domain.
We suggest creating a separate AD tenant for your MSSP Analysts.

. *Create a resource catalog in Customer AAD: Identity Governance*
+
Resource catalogs are a logical collection of access packages, created in the customer AD tenant.
+
To do so, in the customer AD tenant,  access Identity Governance: Catalogs, and add *New Catalog*.
In our example, we will call it *MSSP Accesses*.
+
:::image type="content" source="images/goverance-catalog.png" alt-text="The new catalog page" lightbox="images/goverance-catalog.png":::
+
Further more information, see link:/azure/active-directory/governance/entitlement-management-catalog-create[Create a catalog of resources].

. *Create access packages for MSSP resources Customer AAD: Identity Governance*
+
Access packages are the collection of rights and accesses that a requestor will be granted upon approval.
+
To do so, in the customer AD tenant, access Identity Governance: Access Packages, and add *New Access Package*.
Create an access package for the MSSP approvers and each analyst tier.
For example, the following Tier 1 Analyst configuration creates an access package that:

 ** Requires a member of the AD group *MSSP Analyst Approvers* to authorize new requests
 ** Has annual access reviews, where the SOC analysts can request an access extension
 ** Can only be requested by users in the MSSP SOC Tenant
 ** Access auto expires after 365 days

+
____
[!div class="mx-imgBorder"] :::image type="content" source="images/new-access-package.png" alt-text="The New access package page" lightbox="images/new-access-package.png":::
____
+
For more information, see link:/azure/active-directory/governance/entitlement-management-access-package-create[Create a new access package].

. *Provide access request link to MSSP resources from Customer AAD: Identity Governance*
+
The My Access portal link is used by MSSP SOC analysts to request access via the access packages created.
The link is durable, meaning the same link may be used over time for new analysts.
The analyst request goes into a queue for approval by the *MSSP Analyst Approvers*.
+
____
[!div class="mx-imgBorder"] :::image type="content" source="images/access-properties.png" alt-text="The Properties page" lightbox="images/access-properties.png":::
____
+
The link is located on the overview page of each access package.

=== Manage access

. Review and authorize access requests in Customer and/or MSSP myaccess.
+
Access requests are managed in the customer My Access, by members of the MSSP Analyst Approvers group.
+
To do so, access the customer's myaccess using: `+https://myaccess.microsoft.com/@<Customer Domain>+`.
+
Example: `+https://myaccess.microsoft.com/@M365x440XXX.onmicrosoft.com#/+`

. Approve or deny requests in the *Approvals* section of the UI.
+
At this point, analyst access has been provisioned, and each analyst should be able to access the customer's Microsoft 365 Defender portal: `+https://security.microsoft.com/?tid=<CustomerTenantId>+`

=== Related topics

* xref:access-mssp-portal.adoc[Access the MSSP customer portal]
* xref:configure-mssp-notifications.adoc[Configure alert notifications]
* xref:fetch-alerts-mssp.adoc[Fetch alerts from customer tenant]
