= 
mjcaparas
:keywords: apis, supported apis, submit, ti, indicator, update

== Import Indicators API

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Submits or Updates batch of link:ti-indicator.md[Indicator] entities.

CIDR notation for IPs is not supported.

=== Limitations

[arabic]
. Rate limitations for this API are 30 calls per minute.
. There is a limit of 15,000 active link:ti-indicator.md[Indicators] per
tenant.
. Maximum batch size for one API call is 500.

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Get
started]

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Ti.ReadWrite |`Read and write Indicators'

|Application |Ti.ReadWrite.All |`Read and write All Indicators'

|Delegated (work or school account) |Ti.ReadWrite |`Read and write
Indicators'
|===

=== HTTP request

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/indicators/import
----

=== Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|Content-Type |string |application/json. *Required*.
|===

=== Request body

In the request body, supply a JSON object with the following parameters:

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Parameter |Type |Description
|Indicators |List<link:ti-indicator.md[Indicator]> |List of
link:ti-indicator.md[Indicators]. *Required*
|===

=== Response

* If successful, this method returns 200 - OK response code with a list
of import results per indicator, see example below.
* If not successful: this method return 400 - Bad Request. Bad request
usually indicates incorrect body.

=== Example

==== Request example

Here is an example of the request.

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/indicators/import
----

[source,json]
----
{
    "Indicators":
    [
        {
            "indicatorValue": "220e7d15b011d7fac48f2bd61114db1022197f7f",
            "indicatorType": "FileSha1",
            "title": "demo",
            "application": "demo-test",
            "expirationTime": "2021-12-12T00:00:00Z",
            "action": "Alert",
            "severity": "Informational",
            "description": "demo2",
            "recommendedActions": "nothing",
            "rbacGroupNames": ["group1", "group2"]
        },
        {
            "indicatorValue": "2233223322332233223322332233223322332233223322332233223322332222",
            "indicatorType": "FileSha256",
            "title": "demo2",
            "application": "demo-test2",
            "expirationTime": "2021-12-12T00:00:00Z",
            "action": "Alert",
            "severity": "Medium",
            "description": "demo2",
            "recommendedActions": "nothing",
            "rbacGroupNames": []
        }
    ]
}
----

==== Response example

Here is an example of the response.

[source,json]
----
{
    "value": [
        {
            "id": "2841",
            "indicator": "220e7d15b011d7fac48f2bd61114db1022197f7f",
            "isFailed": false,
            "failureReason": null
        },
        {
            "id": "2842",
            "indicator": "2233223322332233223322332233223322332233223322332233223322332222",
            "isFailed": false,
            "failureReason": null
        }
    ]
}
----

=== Related topic

* link:manage-indicators.md[Manage indicators]
