= 
mjcaparas

== Microsoft Defender for Endpoint sensitivity labels protect and prioritize incident response

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

A typical advanced persistent threat lifecycle (or APT) involves some
data exfiltration – the point at which data is _taken_ from the
organization. In those situations, sensitivity labels can tell security
operations where to start by spelling out what data is highest priority
to protect.

Defender for Endpoint helps to make prioritization of security incidents
simpler with the use of sensitivity labels too. For example, sensitivity
labels quickly identify incidents that may involve devices with
sensitive information on them (such as confidential information).

Here’s how to use sensitivity labels in Defender for Endpoint.

=== Investigate incidents that involve sensitive data on devices with Defender for Endpoint

Learn how to use data sensitivity labels to prioritize incident
investigation.

____
[!NOTE] Labels are detected for Windows 10, version 1809 or later, and
Windows 11.
____

[arabic]
. In Microsoft 365 Defender portal, select *Incidents & alerts* >
*Incidents*.
. Scroll to the right to see the *Data sensitivity* column. This column
reflects sensitivity labels that have been observed on devices related
to the incidents providing an indication of whether sensitive files may
be impacted by the incident.
+
:::image type=``content'' source=``images/data-sensitivity-column.png''
alt-text=``The Highly confidential option in the data sensitivity
column'' lightbox=``images/data-sensitivity-column.png'':::
+
You can also filter based on *Data sensitivity*
+
:::image type=``content'' source=``images/data-sensitivity-filter.png''
alt-text=``The data sensitivity filter''
lightbox=``images/data-sensitivity-filter.png'':::
. Open the incident page to further investigate.
+
:::image type=``content'' source=``images/incident-page.png''
alt-text=``The incident page details''
lightbox=``images/incident-page.png'':::
. Select the *Devices* tab to identify devices storing files with
sensitivity labels.
+
:::image type=``content'' source=``images/investigate-devices-tab.png''
alt-text=``The Device tab''
lightbox=``images/investigate-devices-tab.png'':::
. Select the devices that store sensitive data and search through the
timeline to identify which files may be impacted then take appropriate
action to ensure that data is protected.
+
You can narrow down the events shown on the device timeline by searching
for data sensitivity labels. Doing this will show only events associated
with files that have said label name.
+
:::image type=``content'' source=``images/machine-timeline-labels.png''
alt-text=``The device timeline with narrowed down search results based
on label'' lightbox=``images/machine-timeline-labels.png'':::

____
[!TIP] These data points are also exposed through the `DeviceFileEvents'
in advanced hunting, allowing advanced queries and schedule detection to
take into account sensitivity labels and file protection status.
____

=== Related information about sensitivity labels

* link:../../compliance/sensitivity-labels.md[Learn about sensitivity
labels in Office 365]
* https://support.microsoft.com/office/apply-sensitivity-labels-to-your-files-and-email-in-office-2f96e7cd-d5a4-403b-8bd7-4cc636bae0f9[Learn
to apply sensitivity label inside of email or Office]
* link:../../compliance/dlp-sensitivity-label-as-condition.md[Learn how
to use sensitivity labels as a condition when applying Data Loss
Prevention]
