= Investigate an IP address associated with an alert
:audience: ITPro
:author: mjcaparas
:description: Use the investigation options to examine possible communication between devices and external IP addresses.
:keywords: investigate, investigation, IP address, alert, Microsoft Defender for Endpoint, external IP
:manager: dansimp
:ms.author: macapara
:ms.collection: m365-security-compliance
:ms.date: 04/24/2018
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Investigate an IP address associated with a Microsoft Defender for Endpoint alert

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-investigateip-abovefoldlink[Sign up for a free trial.]
____

Examine possible communication between your devices and external internet protocol (IP) addresses.

Identifying all devices in the organization that communicated with a suspected or known malicious IP address, such as Command and Control (C2) servers, helps determine the potential scope of breach, associated files, and infected devices.

You can find information from the following sections in the IP address view:

* IP worldwide
* Reverse DNS names
* Alerts related to this IP
* IP in organization
* Prevalence

=== IP Worldwide and Reverse DNS names

The IP address details section shows attributes of the IP address such as its ASN and its Reverse DNS names.

=== Alerts related to this IP

The *Alerts related to this IP* section provides a list of alerts that are associated with the IP.

=== IP in organization

The *IP in organization* section provides details on the prevalence of the IP address in the organization.

=== Prevalence

The *Prevalence* section displays how many devices have connected to this IP address, and when the IP was first and last seen.
You can filter the results of this section by time period;
the default period is 30 days.

=== Most recent observed devices with IP

The *Most recent observed devices* with IP section provides a chronological view on the events and associated alerts that were observed on the IP address.

*Investigate an external IP:*

. Select *IP* from the *Search bar* drop-down menu.
. Enter the IP address in the *Search* field.
. Click the search icon or press *Enter*.

Details about the IP address are displayed, including: registration details (if available), reverse IPs (for example, domains), prevalence of devices in the organization that communicated with this IP Address (during selectable time period), and the devices in the organization that were observed communicating with this IP address.

____
[!NOTE] Search results will only be returned for IP addresses observed in communication with devices in the organization.
____

Use the search filters to define the search criteria.
You can also use the timeline search box to filter the displayed results of all devices in the organization observed communicating with the IP address, the file associated with the communication and the last date observed.

Clicking any of the device names will take you to that device's view, where you can continue to investigate reported alerts, behaviors, and events.

=== Related topics

* xref:alerts-queue.adoc[View and organize the Microsoft Defender for Endpoint Alerts queue]
* xref:manage-alerts.adoc[Manage Microsoft Defender for Endpoint alerts]
* xref:investigate-alerts.adoc[Investigate Microsoft Defender for Endpoint alerts]
* xref:investigate-files.adoc[Investigate a file associated with a Microsoft Defender for Endpoint alert]
* xref:investigate-machines.adoc[Investigate devices in the Microsoft Defender for Endpoint Devices list]
* xref:investigate-domain.adoc[Investigate a domain associated with a Microsoft Defender for Endpoint alert]
* xref:investigate-user.adoc[Investigate a user account in Microsoft Defender for Endpoint]
