= 
mjcaparas
:keywords: apis, graph api, supported apis, isolate device

== Isolate machine API

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Isolates a device from accessing external network.

=== Limitations

[arabic]
. Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.

{empty}[!includelink:../../includes/machineactionsnote.md[Device actions
note]]

____
{empty}[!IMPORTANT]

* Full isolation is available for devices on Windows 10, version 1703,
and on Windows 11.
* Selective isolation is available for devices on Windows 10, version
1709 or later, and on Windows 11.
* When isolating a device, only certain processes and destinations are
allowed. Therefore, devices that are behind a full VPN tunnel won’t be
able to reach the Microsoft Defender for Endpoint cloud service after
the device is isolated. We recommend using a split-tunneling VPN for
Microsoft Defender for Endpoint and Microsoft Defender Antivirus
cloud-based protection-related traffic.
____

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Microsoft Defender for Endpoint APIs]

[cols="<,<,<",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Machine.Isolate |`Isolate machine'
|Delegated (work or school account) |Machine.Isolate |`Isolate machine'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to have at least the following role permission: `Active
remediation actions' (See link:user-roles.md[Create and manage roles]
for more information)
* The user needs to have access to the device, based on device group
settings (See link:machine-groups.md[Create and manage device groups]
for more information)

Device group creation is supported in Defender for Endpoint Plan 1 and
Plan 2.
____

=== HTTP request

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/machines/{id}/isolate
----

=== Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|Content-Type |string |application/json. *Required*.
|===

=== Request body

In the request body, supply a JSON object with the following parameters:

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Parameter |Type |Description
|Comment |String |Comment to associate with the action. *Required*.

|IsolationType |String |Type of the isolation. Allowed values are:
`Full' or `Selective'.
|===

*IsolationType* controls the type of isolation to perform and can be one
of the following:

* Full: Full isolation
* Selective: Restrict only limited set of applications from accessing
the network (see
link:respond-machine-alerts.md#isolate-devices-from-the-network[Isolate
devices from the network] for more details)

=== Response

If successful, this method returns 201 - Created response code and
link:machineaction.md[Machine Action] in the response body.

=== Example

==== Request

Here is an example of the request.

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/machines/1e5bc9d7e413ddd7902c2932e418702b84d0cc07/isolate
----

[source,json]
----
{
  "Comment": "Isolate machine due to alert 1234",
  "IsolationType": "Full" 
}
----

* To release a device from isolation, see
link:unisolate-machine.md[Release device from isolation].
