= 
dansimp
:keywords: microsoft, defender, Microsoft Defender for Endpoint, linux,
updates, deploy

== Deploy updates for Microsoft Defender for Endpoint on Linux

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-investigateip-abovefoldlink[Sign
up for a free trial.]
____

Microsoft regularly publishes software updates to improve performance,
security, and to deliver new features.

____
[!WARNING] Each version of Defender for Endpoint on Linux has an
expiration date, after which it will no longer continue to protect your
device. You must update the product prior to this date. To check the
expiration date, run the following command:

[source,bash]
----
mdatp health --field product_expiration
----
____

Generally available Microsoft Defender for Endpoint capabilities are
equivalent regardless update channel used for a deployment (Beta
(Insider), Preview (External), Current (Production)).

To update Defender for Endpoint on Linux manually, execute one of the
following commands:

=== RHEL and variants (CentOS and Oracle Linux)

[source,bash]
----
sudo yum update mdatp
----

=== SLES and variants

[source,bash]
----
sudo zypper update mdatp
----

=== Ubuntu and Debian systems

[source,bash]
----
sudo apt-get install --only-upgrade mdatp
----

____
[!IMPORTANT] When integrating Microsoft Defender for Endpoint and
Defender for Cloud, the mdatp agent will automatically receive updates
by default.
____
