= 
dansimp
:keywords: microsoft, defender, Microsoft Defender for Endpoint, linux,
whatsnew, release

== What’s new in Microsoft Defender for Endpoint on Linux

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]

This article is updated frequently to let you know what’s new in the
latest releases of Microsoft Defender for Endpoint on Linux.

* link:mac-whatsnew.md[What’s new in Defender for Endpoint on macOS]
* link:ios-whatsnew.md[What’s new in Defender for Endpoint on iOS]

Nov-2022 (Build: 101.85.27 | Release version: 30.122092.18527.0)

 Released: *November 02, 2022*  Published: *November 02, 2022*  Build:
*101.85.27*  Release version: *30.122092.18527.0*  Engine version:
*1.1.19500.2*  Signature version: *1.371.1369.0*

*What’s new*

* There are multiple fixes and new changes in this release
** V2 engine is default with this release and V1 engine bits are
completely removed for enhanced security.
** V2 engine support configuration path for AV definitions. (mdatp
definition set path)
** Removed external packages dependencies from MDE package. Removed
dependencies are libatomic1, libselinux, libseccomp, libfuse, and
libuuid
** In case crash collection is disabled by configuration, crash
monitoring process will not be launched.
** Performance fixes to optimally use system events for AV capabilities.
** Stability improvement in case of mdatp restart and loading of epsext
issues.
** Other fixes

*Known issues*

* While upgrading from mdatp version 101.75.43 or 101.78.13, you may
encounter a kernel hang. Run the following commands before attempting to
upgrade to version 101.85.21. More information about the underlying
issue can be found at https://access.redhat.com/solutions/2838901[System
hang due to blocked tasks in fanotify code]

There are two ways to mitigate the problem in upgrading.

Use your package manager to uninstall the 101.75.43 or 101.78.13 mdatp
version. Example:

[source,bash]
----
sudo apt purge mdatp
sudo apt-get install mdatp
----

As an alternative to the above, you can follow the instructions to
link:/microsoft-365/security/defender-endpoint/linux-resources#uninstall[uninstall],
then
link:/microsoft-365/security/defender-endpoint/linux-install-manually#application-installation[install]
the latest version of the package.

In case you don’t want to uninstall mdatp you can disable rtp and mdatp
in sequence before upgrade. Caution: Some customers(<1%) are
experiencing issues with this method.

[source,bash]
----
sudo mdatp config real-time-protection --value=disabled
sudo systemctl disable mdatp
----

Sep-2022 (Build: 101.80.97 | Release version: 30.122072.18097.0)

 Released: *September 14, 2022*  Published: *September 14, 2022*  Build:
*101.80.97*  Release version: *30.122072.18097.0*  Engine version:
*1.1.19300.3*  Signature version: *1.369.395.0*

*What’s new*

* Fixes a kernel hang observed on select customer workloads running
mdatp version 101.75.43. After RCA this was attributed to a race
condition while releasing the ownership of a sensor file descriptor. The
race condition was exposed due to a recent product change in the
shutdown path. Customers on newer Kernel versions (5.1+) are not
impacted by this issue. More information about the underlying issue can
be found at https://access.redhat.com/solutions/2838901[System hang due
to blocked tasks in fanotify code].

*Known issues*

* When upgrading from mdatp version 101.75.43 or 101.78.13, you might
encounter a kernel hang. Run the following commands before attempting to
upgrade to version 101.80.97. This should prevent the issue from
occurring.

....
sudo mdatp config real-time-protection --value=disabled
sudo systemctl disable mdatp
....

After executing the above, use your package manager to perform the
upgrade.

As an alternative to the above, you can follow the instructions to
link:/microsoft-365/security/defender-endpoint/linux-resources#uninstall[uninstall],
then
link:/microsoft-365/security/defender-endpoint/linux-install-manually#application-installation[install]
the latest version of the package.

Aug-2022 (Build: 101.78.13, | Release version: 30.122072.17813.0)

 Released: *August 24, 2022*  Published: *August 24, 2022*  Build:
*101.78.13*  Release version: *30.122072.17813.0*  Engine version:
*1.1.19300.3*  Signature version: *1.369.395.0*

*What’s new*

* Rolled back due to reliability issues

Aug-2022 (Build: 101.75.43 | Release version: 30.122071.17543.0)

 Released: *August 2, 2022*  Published: *August 2, 2022*  Build:
*101.75.43*  Release version: *30.122071.17543.0*  Engine version:
*1.1.19300.3*  Signature version: *1.369.395.0*

*What’s new*

* Added support for Red Hat Enterprise Linux version 9.0
* Added a new field in the output of `mdatp health` that can be used to
query the enforcement level of the network protection feature. The new
field is called `network_protection_enforcement_level` and can take one
of the following values: `audit`, `block`, or `disabled`.
* Addressed a product bug where multiple detections of the same content
could lead to duplicate entries in the threat history
* Addressed an issue where one of the processes spawned by the product
(`mdatp_audisp_plugin`) was sometimes not properly terminated when the
service was stopped
* Other bug fixes

Jul-2022 (Build: 101.73.77 | Release version: 30.122062.17377.0)

 Released: *July 21, 2022*  Published: *July 21, 2022*  Build:
*101.73.77*  Release version: *30.122062.17377.0*  Engine version:
*1.1.19200.3*  Signature version: *1.367.1011.0*

*What’s new*

* Added an option to
link:linux-preferences.md#configure-file-hash-computation-feature[configure
file hash computation]
* From this build onwards, the product will have the new anti-malware
engine by default
* Performance improvements for file copy operations
* Bug fixes

Jun-2022 (Build: 101.71.18 | Release version: 30.122052.17118.0)

 Released: *June 24, 2022*  Published: *June 24, 2022*  Build:
*101.71.18*  Release version: *30.122052.17118.0*

*What’s new*

* Fix to support definitions storage in non-standard locations (outside
of /var) for v2 definition updates
* Fixed an issue in the product sensor used on RHEL 6 that could lead to
an OS hang
* `mdatp connectivity test` was extended with an extra URL that the
product requires to function correctly. The new URL is
https://go.microsoft.com/fwlink/?linkid=2144709.
* Up until now, the product log level wasn’t persisted between product
restarts. Starting from this version, there’s a new command-line tool
switch that persists the log level. The new command is
`mdatp log level persist --level <level>`.
* Removed the dependency on `python` from the product installation
package
* Performance improvements for file copy operations and processing of
network events originating from `auditd`
* Bug fixes

May-2022 (Build: 101.68.80 | Release version: 30.122042.16880.0)

 Released: *May 23, 2022*  Published: *May 23, 2022*  Build: *101.68.80*
 Release version: *30.122042.16880.0*

*What’s new*

* Added support for kernel version `2.6.32-754.47.1.el6.x86_64` when
running on RHEL 6
* On RHEL 6, product can now be installed on devices running Unbreakable
Enterprise Kernel (UEK)
* Fixed an issue where the process name was sometimes incorrectly
displayed as `unknown` when running
`mdatp diagnostic real-time-protection-statistics`
* Fixed a bug where the product sometimes was incorrectly detecting
files inside the quarantine folder
* Fixed an issue where the `mdatp` command-line tool was not working
when `/opt` was mounted as a soft-link
* Performance improvements & bug fixes

May-2022 (Build: 101.65.77 | Release version: 30.122032.16577.0)

 Released: *May 2, 2022*  Published: *May 2, 2022*  Build: *101.65.77*
 Release version: *30.122032.16577.0*

*What’s new*

* Improved the `conflicting_applications` field in `mdatp health` to
show only the most recent 10 processes and also to include the process
names. This makes it easier to identify which processes are potentially
conflicting with Microsoft Defender for Endpoint for Linux.
* Bug fixes

Mar-2022 (Build: 101.62.74 | Release version: 30.122022.16274.0)

 Released: *Mar 24, 2022*  Published: *Mar 24, 2022*  Build: *101.62.74*
 Release version: *30.122022.16274.0*

*What’s new*

* Addressed an issue where the product would incorrectly block access to
files greater than 2GB in size when running on older kernel versions
* Bug fixes

Mar-2022 (Build: 101.60.93 | Release version: 30.122012.16093.0)

 Released: *Mar 9, 2022*  Published: *Mar 9, 2022*  Build: *101.60.93*
 Release version: *30.122012.16093.0*

*What’s new*

* This version contains a security update for
https://msrc-blog.microsoft.com/2022/03/08/guidance-for-cve-2022-23278-spoofing-in-microsoft-defender-for-endpoint/[CVE-2022-23278]

Mar-2022 (Build: 101.60.05 | Release version: 30.122012.16005.0)

 Released: *Mar 3, 2022*  Published: *Mar 3, 2022*  Build: *101.60.05*
 Release version: *30.122012.16005.0*

*What’s new*

* Added support for kernel version 2.6.32-754.43.1.el6.x86_64 for RHEL
6.10
* Bug fixes

Feb-2022 (Build: 101.58.80 | Release version: 30.122012.15880.0)

 Released: *Feb 20, 2022*  Published: *Feb 20, 2022*  Build: *101.58.80*
 Release version: *30.122012.15880.0*

*What’s new*

* The command-line tool now supports restoring quarantined files to a
location other than the one where the file was originally detected. This
can be done through
`mdatp threat quarantine restore --id [threat-id] --path [destination-folder]`.
* Starting with this version, network protection for Linux can be
evaluated on demand
* Bug fixes

Jan-2022 (Build: 101.56.62 | Release version: 30.121122.15662.0)

 Released: *Jan 26, 2022*  Published: *Jan 26, 2022*  Build: *101.56.62*
 Release version: *30.121122.15662.0*

*What’s new*

* Fixed a product crash introduced in 101.53.02 and that has impacted
multiple customers

Jan-2022 (Build: 101.53.02 | Release version: (30.121112.15302.0)

 Released: *Jan 8, 2022*  Published: *Jan 8, 2022*  Build: *101.53.02*
 Release version: *30.121112.15302.0*

*What’s new*

* Performance improvements & bug fixes

2021 releases

(Build: 101.52.57 | Release version: 30.121092.15257.0)

Build: 101.52.57 Release version: 30.121092.15257.0

What’s new

* Added a capability to detect vulnerable log4j jars in use by Java
applications. The machine is periodically inspected for running Java
processes with loaded log4j jars. The information is reported to the
Microsoft Defender for Endpoint backend and is exposed in the
Vulnerability Management area of the portal.

(Build: 101.47.76 | Release version: 30.121092.14776.0)

Build: 101.47.76 Release version: 30.121092.14776.0

What’s new

* Added a new switch to the command-line tool to control whether
archives are scanned during on-demand scans. This can be configured
through mdatp config scan-archives –value [enabled/disabled]. By
default, this is set to enabled.
* Bug fixes

(Build: 101.45.13 | Release version: 30.121082.14513.0)

Build: 101.45.13 Release version: 30.121082.14513.0

What’s new

* Starting with this version, we are bringing Microsoft Defender for
Endpoint support to the following distros:
** RHEL6.7-6.10 and CentOS6.7-6.10 versions.
** Amazon Linux 2
** Fedora 33 or higher
* Bug fixes

(Build: 101.45.00 | Release version: 30.121072.14500.0)

Build: 101.45.00 Release version: 30.121072.14500.0

What’s new

* Added new switches to the command-line tool:
** Control degree of parallelism for on-demand scans. This can be
configured through
`mdatp config maximum-on-demand-scan-threads --value [number-between-1-and-64]`.
By default, a degree of parallelism of `2` is used.
** Control whether scans after security intelligence updates are enabled
or disabled. This can be configured through
`mdatp config scan-after-definition-update --value [enabled/disabled]`.
By default, this is set to `enabled`.
* Changing the product log level now requires elevation
* Bug fixes

(Build: 101.39.98 | Release version: 30.121062.13998.0)

Build: 101.39.98 Release version: 30.121062.13998.0

What’s new

* Performance improvements & bug fixes

(Build: 101.34.27 | Release version: 30.121052.13427.0)

Build: 101.34.27 Release version: 30.121052.13427.0

What’s new

* Performance improvements & bug fixes

(Build: 101.29.64 | Release version: 30.121042.12964.0)

Build: 101.29.64 Release version: 30.121042.12964.0

What’s new

* Starting with this version, threats detected during on-demand
antivirus scans triggered through the command-line client are
automatically remediated. Threats detected during scans triggered
through the user interface still require manual action.
* `mdatp diagnostic real-time-protection-statistics` now supports two
additional switches:
** `--sort`: sorts the output descending by total number of files
scanned
** `--top N`: displays the top N results (only works if `--sort` is also
specified)
* Performance improvements & bug fixes

(Build: 101.25.72 | Release version: 30.121022.12563.0)

Build: 101.25.72 Release version: 30.121022.12563.0

What’s new

* Microsoft Defender for Endpoint on Linux is now available in preview
for US Government customers. For more information, see
link:gov.md[Microsoft Defender for Endpoint for US Government
customers].
* Fixed an issue where usage of Microsoft Defender for Endpoint on Linux
on systems with FUSE filesystems was leading to OS hang
* Performance improvements & other bug fixes

(Build: 101.25.63 | Release version: 30.121022.12563.0)

Build: 101.25.63 Release version: 30.121022.12563.0

What’s new

* Performance improvements & bug fixes

(Build: 101.23.64 | Release version: 30.121021.12364.0)

Build: 101.23.64 Release version: 30.121021.12364.0

What’s new

* Performance improvement for the situation where an entire mount point
is added to the antivirus exclusion list. Prior to this version, file
activity originating from the mount point was still processed by the
product. Starting with this version, file activity for excluded mount
points is suppressed, leading to better product performance
* Added a new option to the command-line tool to view information about
the last on-demand scan. To view information about the last on-demand
scan, run `mdatp health --details antivirus`
* Other performance improvements & bug fixes

(Build: 101.18.53)

....
<p> 
Build:<b> 101.18.53 </b><br>
    
<p>What's new</b></p>
....

* EDR for Linux is now
https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/edr-for-linux-is-now-is-generally-available/ba-p/2048539[generally
available]
* Added a new command-line switch (`--ignore-exclusions`) to ignore AV
exclusions during custom scans (`mdatp scan custom`)
* Extended `mdatp diagnostic create` with a new parameter
(`--path [directory]`) that allows the diagnostic logs to be saved to a
different directory - Performance improvements & bug fixes
