= 
dansimp
:keywords: microsoft, defender, Microsoft Defender for Endpoint, linux,
installation, deploy, uninstallation, puppet, ansible, linux, redhat,
ubuntu, debian, sles, suse, centos, fedora, amazon linux 2

== Deploy Microsoft Defender for Endpoint on Linux manually

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-investigateip-abovefoldlink[Sign
up for a free trial.]
____

____
[!TIP] Looking for advanced guidance on deploying Microsoft Defender for
Endpoint on Linux? See
link:comprehensive-guidance-on-linux-deployment.md[Advanced deployment
guide on Defender for Endpoint on Linux].
____

This article describes how to deploy Microsoft Defender for Endpoint on
Linux manually. A successful deployment requires the completion of all
of the following tasks:

* link:#prerequisites-and-system-requirements[Prerequisites and system
requirements]
* link:#configure-the-linux-software-repository[Configure the Linux
software repository]
** link:#rhel-and-variants-centos-fedora-oracle-linux-and-amazon-linux-2[RHEL
and variants (CentOS&#44; Fedora&#44; Oracle Linux and Amazon Linux 2)]
** link:#sles-and-variants[SLES and variants]
** link:#ubuntu-and-debian-systems[Ubuntu and Debian systems]
* link:#application-installation[Application installation]
* link:#download-the-onboarding-package[Download the onboarding package]
* link:#client-configuration[Client configuration]

=== Prerequisites and system requirements

Before you get started, see
link:microsoft-defender-endpoint-linux.md[Microsoft Defender for
Endpoint on Linux] for a description of prerequisites and system
requirements for the current software version.

____
[!WARNING] Upgrading your operating system to a new major version after
the product installation requires the product to be reinstalled. You
need to
link:linux-resources.md#uninstall-defender-for-endpoint-on-linux[Uninstall]
the existing Defender for Endpoint on Linux, upgrade the operating
system, and then reconfigure Defender for Endpoint on Linux following
the below steps.
____

=== Configure the Linux software repository

Defender for Endpoint on Linux can be deployed from one of the following
channels (denoted below as _[channel]_): _insiders-fast_,
_insiders-slow_, or _prod_. Each of these channels corresponds to a
Linux software repository. Instructions for configuring your device to
use one of these repositories are provided below.

The choice of the channel determines the type and frequency of updates
that are offered to your device. Devices in _insiders-fast_ are the
first ones to receive updates and new features, followed later by
_insiders-slow_ and lastly by _prod_.

In order to preview new features and provide early feedback, it is
recommended that you configure some devices in your enterprise to use
either _insiders-fast_ or _insiders-slow_.

____
[!WARNING] Switching the channel after the initial installation requires
the product to be reinstalled. To switch the product channel: uninstall
the existing package, re-configure your device to use the new channel,
and follow the steps in this document to install the package from the
new location.
____

==== RHEL and variants (CentOS, Fedora, Oracle Linux and Amazon Linux 2)

* Install `yum-utils` if it isn’t installed yet:
+
[source,bash]
----
sudo yum install yum-utils
----
+
____
[!NOTE] Your distribution and version, and identify the closest entry
(by major, then minor) for it under
`https://packages.microsoft.com/config/rhel/`.
____
+
Use the following table to help guide you in locating the package:
+
[width="100%",cols="50%,50%",options="header",]
|===
|Distro & version |Package
|For RHEL/Centos/Oracle 8.0-8.5
|https://packages.microsoft.com/config/rhel/8/prod.repo

|For RHEL/Centos/Oracle 7.2-7.9 & Amazon Linux 2
|https://packages.microsoft.com/config/rhel/7.2/prod.repo

|For Fedora 33
|https://packages.microsoft.com/config/fedora/33/prod.repo

|For Fedora 34
|https://packages.microsoft.com/config/fedora/34/prod.repo
|===
+
+
In the following commands, replace _[version]_ and _[channel]_ with the
information you’ve identified:
+
[source,bash]
----
sudo yum-config-manager --add-repo=https://packages.microsoft.com/config/rhel/[version]/[channel].repo
----
+
____
[!TIP] Use hostnamectl command to identify system related information
including release _[version]_.
____
+
For example, if you are running CentOS 7 and want to deploy Defender for
Endpoint on Linux from the _prod_ channel:
+
[source,bash]
----
sudo yum-config-manager --add-repo=https://packages.microsoft.com/config/rhel/7/prod.repo
----
+
Or if you wish to explore new features on selected devices, you might
want to deploy Microsoft Defender for Endpoint on Linux to
_insiders-fast_ channel:
+
[source,bash]
----
sudo yum-config-manager --add-repo=https://packages.microsoft.com/config/rhel/7/insiders-fast.repo
----
* Install the Microsoft GPG public key:
+
[source,bash]
----
sudo rpm --import http://packages.microsoft.com/keys/microsoft.asc
----

==== SLES and variants

____
[!NOTE] Your distribution and version, and identify the closest entry
(by major, then minor) for it under
`https://packages.microsoft.com/config/sles/`.
____

In the following commands, replace _[distro]_ and _[version]_ with the
information you’ve identified:

[source,bash]
----
sudo zypper addrepo -c -f -n microsoft-[channel] https://packages.microsoft.com/config/[distro]/[version]/[channel].repo
----

____
[!TIP] Use SPident command to identify system related information
including release _[version]_.
____

For example, if you are running SLES 12 and wish to deploy Microsoft
Defender for Endpoint on Linux from the _prod_ channel:

[source,bash]
----
sudo zypper addrepo -c -f -n microsoft-prod https://packages.microsoft.com/config/sles/12/prod.repo
----

* Install the Microsoft GPG public key:
+
[source,bash]
----
sudo rpm --import http://packages.microsoft.com/keys/microsoft.asc
----

==== Ubuntu and Debian systems

* Install `curl` if it isn’t installed yet:
+
[source,bash]
----
sudo apt-get install curl
----
* Install `libplist-utils` if it isn’t installed yet:
+
[source,bash]
----
sudo apt-get install libplist-utils
----
+
____
[!NOTE] Your distribution and version, and identify the closest entry
(by major, then minor) for it under
`https://packages.microsoft.com/config/[distro]/`.
____
+
In the following command, replace _[distro]_ and _[version]_ with the
information you’ve identified:
+
[source,bash]
----
 curl -o microsoft.list https://packages.microsoft.com/config/[distro]/[version]/[channel].list
----
+
____
[!TIP] Use hostnamectl command to identify system related information
including release _[version]_.
____
+
For example, if you are running Ubuntu 18.04 and wish to deploy
Microsoft Defender for Endpoint on Linux from the _prod_ channel:
+
[source,bash]
----
curl -o microsoft.list https://packages.microsoft.com/config/ubuntu/18.04/prod.list
----
* Install the repository configuration:
+
[source,bash]
----
sudo mv ./microsoft.list /etc/apt/sources.list.d/microsoft-[channel].list
----
+
For example, if you chose _prod_ channel:
+
[source,bash]
----
sudo mv ./microsoft.list /etc/apt/sources.list.d/microsoft-prod.list
----
* Install the `gpg` package if not already installed:
+
[source,bash]
----
sudo apt-get install gpg
----
+
If `gpg` is not available, then install `gnupg`.
+
[source,bash]
----
sudo apt-get install gnupg
----
* Install the Microsoft GPG public key:
+
[source,bash]
----
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
----
* Install the HTTPS driver if not already installed:
+
[source,bash]
----
sudo apt-get install apt-transport-https
----
* Update the repository metadata:
+
[source,bash]
----
sudo apt-get update
----

=== Application installation

* RHEL and variants (CentOS and Oracle Linux):
+
[source,bash]
----
sudo yum install mdatp
----
+
____
[!NOTE] If you have multiple Microsoft repositories configured on your
device, you can be specific about which repository to install the
package from. The following example shows how to install the package
from the `production` channel if you also have the `insiders-fast`
repository channel configured on this device. This situation can happen
if you are using multiple Microsoft products on your device. Depending
on the distribution and the version of your server, the repository alias
might be different than the one in the following example.
____
+
[source,bash]
----
# list all repositories
yum repolist
----
+
[source,output]
----
...
packages-microsoft-com-prod               packages-microsoft-com-prod        316
packages-microsoft-com-prod-insiders-fast packages-microsoft-com-prod-ins      2
...
----
+
[source,bash]
----
# install the package from the production repository
sudo yum --enablerepo=packages-microsoft-com-prod install mdatp
----
* SLES and variants:
+
[source,bash]
----
sudo zypper install mdatp
----
+
____
[!NOTE] If you have multiple Microsoft repositories configured on your
device, you can be specific about which repository to install the
package from. The following example shows how to install the package
from the `production` channel if you also have the `insiders-fast`
repository channel configured on this device. This situation can happen
if you are using multiple Microsoft products on your device.
____
+
[source,bash]
----
zypper repos
----
+
[source,output]
----
...
#  | Alias | Name | ...
XX | packages-microsoft-com-insiders-fast | microsoft-insiders-fast | ...
XX | packages-microsoft-com-prod | microsoft-prod | ...
...
----
+
[source,bash]
----
sudo zypper install packages-microsoft-com-prod:mdatp
----
* Ubuntu and Debian system:
+
[source,bash]
----
sudo apt-get install mdatp
----
+
____
[!NOTE] If you have multiple Microsoft repositories configured on your
device, you can be specific about which repository to install the
package from. The following example shows how to install the package
from the `production` channel if you also have the `insiders-fast`
repository channel configured on this device. This situation can happen
if you are using multiple Microsoft products on your device.
____
+
[source,bash]
----
cat /etc/apt/sources.list.d/*
----
+
[source,output]
----
deb [arch=arm64,armhf,amd64] https://packages.microsoft.com/config/ubuntu/18.04/prod insiders-fast main
deb [arch=amd64] https://packages.microsoft.com/config/ubuntu/18.04/prod bionic main
----
+
[source,bash]
----
sudo apt -t bionic install mdatp
----

____
[!NOTE] Reboots are NOT required after installing or updating Microsoft
Defender for Endpoint on Linux except when you’re running auditD in
immutable mode.
____

=== Download the onboarding package

Download the onboarding package from Microsoft 365 Defender portal.

____
[!IMPORTANT] If you miss this step, any command executed will show a
warning message indicating that the product is unlicensed. Also the
`mdatp health` command returns a value of `false`.
____

[arabic]
. In the Microsoft 365 Defender portal, go to *Settings > Endpoints >
Device management > Onboarding*.
. In the first drop-down menu, select *Linux Server* as the operating
system. In the second drop-down menu, select *Local Script* as the
deployment method.
. Select *Download onboarding package*. Save the file as
WindowsDefenderATPOnboardingPackage.zip.
+
:::image type=``content'' source=``images/portal-onboarding-linux.png''
alt-text=``Downloading an onboarding package in the Microsoft 365
Defender portal'' lightbox=``images/portal-onboarding-linux.png'':::
. From a command prompt, verify that you have the file, and extract the
contents of the archive:
+
[source,bash]
----
ls -l
----
+
[source,output]
----
total 8
-rw-r--r-- 1 test  staff  5752 Feb 18 11:22 WindowsDefenderATPOnboardingPackage.zip
----
+
[source,bash]
----
unzip WindowsDefenderATPOnboardingPackage.zip
----
+
[source,output]
----
Archive:  WindowsDefenderATPOnboardingPackage.zip
inflating: MicrosoftDefenderATPOnboardingLinuxServer.py
----

=== Client configuration

[arabic]
. Copy MicrosoftDefenderATPOnboardingLinuxServer.py to the target
device.
+
____
[!NOTE] Initially the client device is not associated with an
organization and the _orgId_ attribute is blank.
____
+
[source,bash]
----
mdatp health --field org_id
----
. Run MicrosoftDefenderATPOnboardingLinuxServer.py.
+
____
[!NOTE] To run this command, you must have `python` or `python3`
installed on the device depending on the distro and version. If needed,
see
https://opensource.com/article/20/4/install-python-linux[Step-by-step
Instructions for Installing Python on Linux].
____
+
If you’re running RHEL 8.x or Ubuntu 20.04 or higher, you will need to
use `python3`.
+
[source,bash]
----
sudo python3 MicrosoftDefenderATPOnboardingLinuxServer.py
----
+
For the rest of distros and versions, you will need to use `python`.
+
[source,bash]
----
sudo python MicrosoftDefenderATPOnboardingLinuxServer.py
----
. Verify that the device is now associated with your organization and
reports a valid organization identifier:
+
[source,bash]
----
mdatp health --field org_id
----
. Check the health status of the product by running the following
command. A return value of `1` denotes that the product is functioning
as expected:
+
[source,bash]
----
mdatp health --field healthy
----
+
____
[!IMPORTANT] When the product starts for the first time, it downloads
the latest antimalware definitions. This may take up to a few minutes
depending on the network connectivity. During this time the above
command returns a value of `false`. You can check the status of the
definition update using the following command:

[source,bash]
----
mdatp health --field definitions_status
----

Please note that you may also need to configure a proxy after completing
the initial installation. See
link:linux-static-proxy-configuration.md#post-installation-configuration[Configure
Defender for Endpoint on Linux for static proxy discovery:
Post-installation configuration].
____
. Run an AV detection test to verify that the device is properly
onboarded and reporting to the service. Perform the following steps on
the newly onboarded device:
* Ensure that real-time protection is enabled (denoted by a result of
`1` from running the following command):
+
[source,bash]
----
mdatp health --field real_time_protection_enabled
----
+
If it is not enabled, execute the following command:
+
[source,bash]
----
 mdatp config real-time-protection --value enabled
----
* Open a Terminal window and execute the following command:
+
[source,bash]
----
curl -o /tmp/eicar.com.txt https://www.eicar.org/download/eicar.com.txt
----
* The file should have been quarantined by Defender for Endpoint on
Linux. Use the following command to list all the detected threats:
+
[source,bash]
----
mdatp threat list
----
. Run an EDR detection test and simulate a detection to verify that the
device is properly onboarded and reporting to the service. Perform the
following steps on the newly onboarded device:
* Verify that the onboarded Linux server appears in Microsoft 365
Defender. If this is the first onboarding of the machine, it can take up
to 20 minutes until it appears.
* Download and extract the https://aka.ms/LinuxDIY[script file] to an
onboarded Linux server and run the following command:
`./mde_linux_edr_diy.sh`
* After a few minutes, a detection should be raised in Microsoft 365
Defender.
* Look at the alert details, machine timeline, and perform your typical
investigation steps.

=== Installer script

Alternatively, you can use an automated
https://github.com/microsoft/mdatp-xplat/blob/master/linux/installation/mde_installer.sh[installer
bash script] provided in our
https://github.com/microsoft/mdatp-xplat/[public GitHub repository]. The
script identifies the distribution and version, simplifies the selection
of the right repository, sets up the device to pull the latest package,
and combines the product installation and onboarding steps.

[source,bash]
----
> ./mde_installer.sh --help
usage: basename ./mde_installer.sh [OPTIONS]
Options:
-c|--channel      specify the channel from which you want to install. Default: insiders-fast
-i|--install      install the product
-r|--remove       remove the product
-u|--upgrade      upgrade the existing product
-o|--onboard      onboard/offboard the product with <onboarding_script>
-p|--passive-mode set EPP to passive mode
-t|--tag          set a tag by declaring <name> and <value>. ex: -t GROUP Coders
-m|--min_req      enforce minimum requirements
-w|--clean        remove repo from package manager for a specific channel
-v|--version      print out script version
-h|--help         display help
----

Read more
https://github.com/microsoft/mdatp-xplat/tree/master/linux/installation[here].

=== Log installation issues

See link:linux-resources.md#log-installation-issues[Log installation
issues] for more information on how to find the automatically generated
log that is created by the installer when an error occurs.

=== How to migrate from Insiders-Fast to Production channel

[arabic]
. Uninstall the ``Insiders-Fast channel'' version of Defender for
Endpoint on Linux.
+
[source,bash]
----
sudo yum remove mdatp
----
. Disable the Defender for Endpoint on Linux Insiders-Fast repo
+
[source,bash]
----
sudo yum repolist
----
+
____
[!NOTE] The output should show ``packages-microsoft-com-fast-prod''.
____
+
[source,bash]
----
sudo yum-config-manager --disable packages-microsoft-com-fast-prod
----
. Redeploy Microsoft Defender for Endpoint on Linux using the
``Production channel''.

=== Uninstallation

See
link:linux-resources.md#uninstall-defender-for-endpoint-on-linux[Uninstall]
for details on how to remove Defender for Endpoint on Linux from client
devices.

=== See also

* link:health-status.md[Investigate agent health issues]
