= 
dansimp
:keywords: microsoft, defender, Microsoft Defender for Endpoint, linux,
performance

== Troubleshoot performance issues for Microsoft Defender for Endpoint on Linux

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint] - https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft
Defender for Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-investigateip-abovefoldlink[Sign
up for a free trial.]
____

This document provides instructions on how to narrow down performance
issues related to Defender for Endpoint on Linux using the available
diagnostic tools to be able to understand and mitigate the existing
resource shortages and the processes that are making the system into
such situations. Performance problems are mainly caused by bottlenecks
in one or more hardware subsystems, depending on the profile of resource
utilization on the system. Sometimes applications are sensitive to disk
I/O resources and may need more CPU capacity, and sometimes some
configurations are not sustainable, and may trigger too many new
processes, and open too many file descriptors.

Depending on the applications that you are running and your device
characteristics, you may experience suboptimal performance when running
Defender for Endpoint on Linux. In particular, applications or system
processes that access many resources such as CPU, Disk, and Memory over
a short timespan can lead to performance issues in Defender for Endpoint
on Linux.

____
[!WARNING] Before starting, *please make sure that other security
products are not currently running on the device*. Multiple security
products may conflict and impact the host performance.
____

=== Troubleshoot performance issues using Real-time Protection Statistics

*Applies to:* - Only performance issues related to AV

Real-time protection (RTP) is a feature of Defender for Endpoint on
Linux that continuously monitors and protects your device against
threats. It consists of file and process monitoring and other
heuristics.

The following steps can be used to troubleshoot and mitigate these
issues:

[arabic]
. Disable real-time protection using one of the following methods and
observe whether the performance improves. This approach helps narrow
down whether Defender for Endpoint on Linux is contributing to the
performance issues.
+
If your device is not managed by your organization, real-time protection
can be disabled from the command line:
+
[source,bash]
----
mdatp config real-time-protection --value disabled
----
+
[source,output]
----
Configuration property updated
----
+
If your device is managed by your organization, real-time protection can
be disabled by your administrator using the instructions in
link:linux-preferences.md[Set preferences for Defender for Endpoint on
Linux].
+
____
[!NOTE] If the performance problem persists while real-time protection
is off, the origin of the problem could be the endpoint detection and
response (EDR) component. In this case please follow the steps from the
*Troubleshoot performance issues using Microsoft Defender for Endpoint
Client Analyzer* section of this article.
____
. To find the applications that are triggering the most scans, you can
use real-time statistics gathered by Defender for Endpoint on Linux.
+
____
[!NOTE] This feature is available in version 100.90.70 or newer.
____
+
This feature is enabled by default on the `Dogfood` and `InsiderFast`
channels. If you’re using a different update channel, this feature can
be enabled from the command line:
+
[source,bash]
----
mdatp config real-time-protection-statistics --value enabled
----
+
This feature requires real-time protection to be enabled. To check the
status of real-time protection, run the following command:
+
[source,bash]
----
mdatp health --field real_time_protection_enabled
----
+
Verify that the `real_time_protection_enabled` entry is `true`.
Otherwise, run the following command to enable it:
+
[source,bash]
----
mdatp config real-time-protection --value enabled
----
+
[source,output]
----
Configuration property updated
----
+
To collect current statistics, run:
+
[source,bash]
----
mdatp diagnostic real-time-protection-statistics --output json > real_time_protection.json
----
+
____
[!NOTE] Using `--output json` (note the double dash) ensures that the
output format is ready for parsing.
____
+
The output of this command will show all processes and their associated
scan activity.
. On your Linux system, download the sample Python parser
*high_cpu_parser.py* using the command:
+
[source,bash]
----
wget -c https://raw.githubusercontent.com/microsoft/mdatp-xplat/master/linux/diagnostic/high_cpu_parser.py
----
+
The output of this command should be similar to the following:
+
[source,output]
----
--2020-11-14 11:27:27-- https://raw.githubusercontent.com/microsoft.mdatp-xplat/master/linus/diagnostic/high_cpu_parser.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.xxx.xxx
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)| 151.101.xxx.xxx| :443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1020 [text/plain]
Saving to: 'high_cpu_parser.py'
100%[===========================================>] 1,020    --.-K/s   in 0s
----
. Next, type the following commands:
+
[source,bash]
----
chmod +x high_cpu_parser.py
----
+
[source,bash]
----
cat real_time_protection.json | python high_cpu_parser.py  > real_time_protection.log
----
+
The output of the above is a list of the top contributors to performance
issues. The first column is the process identifier (PID), the second
column is the process name, and the last column is the number of scanned
files, sorted by impact. For example, the output of the command will be
something like the below:
+
[source,output]
----
... > python ~/repo/mdatp-xplat/linux/diagnostic/high_cpu_parser.py <~Downloads/output.json | head -n 10
27432 None 76703
73467 actool    1249
73914 xcodebuild 1081
73873 bash 1050
27475 None 836
1    launchd     407
73468 ibtool     344
549  telemetryd_v1   325
4764 None 228
125  CrashPlanService 164
----
+
To improve the performance of Defender for Endpoint on Linux, locate the
one with the highest number under the `Total files scanned` row and add
an exclusion for it. For more information, see
link:linux-exclusions.md[Configure and validate exclusions for Defender
for Endpoint on Linux].
+
____
[!NOTE] The application stores statistics in memory and only keeps track
of file activity since it was started and real-time protection was
enabled. Processes that were launched before or during periods when real
time protection was off are not counted. Additionally, only events which
triggered scans are counted.
____
. Configure Microsoft Defender for Endpoint on Linux with exclusions for
the processes or disk locations that contribute to the performance
issues and re-enable real-time protection.
+
For more information, see link:linux-exclusions.md[Configure and
validate exclusions for Microsoft Defender for Endpoint on Linux].

=== Troubleshoot performance issues using Microsoft Defender for Endpoint Client Analyzer

*Applies to:* - Performance issues of all available Defender for
Endpoint components such as AV and EDR

The Microsoft Defender for Endpoint Client Analyzer (MDECA) can collect
traces, logs, and diagnostic information in order to troubleshoot
performance issues on
link:/microsoft-365/security/defender-endpoint/onboard-configure[onboarded
devices] on macOS.

____
{empty}[!NOTE]

* The Microsoft Defender for Endpoint Client Analyzer tool is regularly
used by Microsoft Customer Support Services (CSS) to collect information
such as (but not limited to) IP addresses, PC names that will help
troubleshoot issues you may be experiencing with Microsoft Defender for
Endpoint. For more information about our privacy statement, see
https://privacy.microsoft.com/privacystatement[Microsoft Privacy
Statement].
* As a general best practice, it is recommended to update the
link:mac-whatsnew.md[Microsoft Defender for Endpoint agent to latest
available version] and confirming that the issue still persists before
investigating further.
____

To run the client analyzer for troubleshooting performance issues, see
link:run-analyzer-macos-linux.md[Run the client analyzer on macOS and
Linux].

____
[!NOTE] In case after following the above steps, the performance problem
persists, please contact customer support for further instructions and
mitigation.
____

=== See also

* link:health-status.md[Investigate agent health issues]
