= 
dansimp
:keywords: microsoft, defender, Microsoft Defender for Endpoint, linux,
exclusions, scans, antivirus

== Configure and validate exclusions for Microsoft Defender for Endpoint on Linux

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365
Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-investigateip-abovefoldlink[Sign
up for a free trial.]
____

This article provides information on how to define exclusions that apply
to on-demand scans, and real-time protection and monitoring.

____
[!IMPORTANT] The exclusions described in this article don’t apply to
other Defender for Endpoint on Linux capabilities, including endpoint
detection and response (EDR). Files that you exclude using the methods
described in this article can still trigger EDR alerts and other
detections.
____

You can exclude certain files, folders, processes, and process-opened
files from Defender for Endpoint on Linux scans.

Exclusions can be useful to avoid incorrect detections on files or
software that are unique or customized to your organization. They can
also be useful for mitigating performance issues caused by Defender for
Endpoint on Linux.

____
[!WARNING] Defining exclusions lowers the protection offered by Defender
for Endpoint on Linux. You should always evaluate the risks that are
associated with implementing exclusions, and you should only exclude
files that you are confident are not malicious.
____

=== Supported exclusion types

The follow table shows the exclusion types supported by Defender for
Endpoint on Linux.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Exclusion |Definition |Examples
|File extension |All files with the extension, anywhere on the device
|`.test`

|File |A specific file identified by the full path
|`/var/log/test.log``/var/log/*.log``/var/log/install.?.log`

|Folder |All files under the specified folder (recursively)
|`/var/log/``/var/*/`

|Process |A specific process (specified either by the full path or file
name) and all files opened by it |`/bin/cat``cat``c?t`
|===

____
[!IMPORTANT] The paths above must be hard links, not symbolic links, in
order to be successfully excluded. You can check if a path is a symbolic
link by running `file <path-name>`.
____

File, folder, and process exclusions support the following wildcards:

[width="100%",cols="20%,20%,20%,20%,20%",options="header",]
|===
|Wildcard |Description |Example |Matches |Does not match
|* |Matches any number of any characters including none (note that when
this wildcard is used inside a path it will substitute only one folder)
|`/var/\*/\*.log` |`/var/log/system.log` |`/var/log/nested/system.log`

|? |Matches any single character |`file?.log` |`file1.log``file2.log`
|`file123.log`
|===

=== How to configure the list of exclusions

==== From the management console

For more information on how to configure exclusions from Puppet,
Ansible, or another management console, see
link:linux-preferences.md[Set preferences for Defender for Endpoint on
Linux].

==== From the command line

Run the following command to see the available switches for managing
exclusions:

[source,bash]
----
mdatp exclusion
----

____
[!TIP] When configuring exclusions with wildcards, enclose the parameter
in double-quotes to prevent globbing.
____

Examples:

* Add an exclusion for a file extension:
+
[source,bash]
----
mdatp exclusion extension add --name .txt
----
+
[source,output]
----
Extension exclusion configured successfully
----
* Add an exclusion for a file:
+
[source,bash]
----
mdatp exclusion file add --path /var/log/dummy.log
----
+
[source,output]
----
File exclusion configured successfully
----
* Add an exclusion for a folder:
+
[source,bash]
----
mdatp exclusion folder add --path /var/log/
----
+
[source,output]
----
Folder exclusion configured successfully
----
* Add an exclusion for a second folder:
+
[source,bash]
----
mdatp exclusion folder add --path /var/log/
mdatp exclusion folder add --path /other/folder
----
+
[source,output]
----
Folder exclusion configured successfully
----
* Add an exclusion for a folder with a wildcard in it:
+
[source,bash]
----
mdatp exclusion folder add --path "/var/*/"
----
+
____
[!NOTE] This will only exclude paths one level below _/var/_, but not
folders which are more deeply nested; for example,
_/var/this-subfolder/but-not-this-subfolder_.
____
+
[source,bash]
----
mdatp exclusion folder add --path "/var/"
----
+
____
[!NOTE] This will exclude all paths whose parent is _/var/_; for
example, _/var/this-subfolder/and-this-subfolder-as-well_.
____
+
[source,output]
----
Folder exclusion configured successfully
----
* Add an exclusion for a process:
+
[source,bash]
----
mdatp exclusion process add --name cat
----
+
[source,output]
----
Process exclusion configured successfully
----
* Add an exclusion for a second process:
+
[source,bash]
----
mdatp exclusion process add --name cat
mdatp exclusion process add --name dog
----
+
[source,output]
----
Process exclusion configured successfully
----

=== Validate exclusions lists with the EICAR test file

You can validate that your exclusion lists are working by using `curl`
to download a test file.

In the following Bash snippet, replace `test.txt` with a file that
conforms to your exclusion rules. For example, if you have excluded the
`.testing` extension, replace `test.txt` with `test.testing`. If you are
testing a path, ensure that you run the command within that path.

[source,bash]
----
curl -o test.txt https://www.eicar.org/download/eicar.com.txt
----

If Defender for Endpoint on Linux reports malware, then the rule is not
working. If there is no report of malware, and the downloaded file
exists, then the exclusion is working. You can open the file to confirm
that the contents are the same as what is described on the
http://2016.eicar.org/86-0-Intended-use.html[EICAR test file website].

If you do not have Internet access, you can create your own EICAR test
file. Write the EICAR string to a new text file with the following Bash
command:

[source,bash]
----
echo 'X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*' > test.txt
----

You can also copy the string into a blank text file and attempt to save
it with the file name or in the folder you are attempting to exclude.

=== Allow threats

In addition to excluding certain content from being scanned, you can
also configure the product not to detect some classes of threats
(identified by the threat name). You should exercise caution when using
this functionality, as it can leave your device unprotected.

To add a threat name to the allowed list, execute the following command:

[source,bash]
----
mdatp threat allowed add --name [threat-name]
----

The threat name associated with a detection on your device can be
obtained using the following command:

[source,bash]
----
mdatp threat list
----

For example, to add `EICAR-Test-File (not a virus)` (the threat name
associated with the EICAR detection) to the allowed list, execute the
following command:

[source,bash]
----
mdatp threat allowed add --name "EICAR-Test-File (not a virus)"
----
