= 
mjcaparas
:keywords: apis, graph api, supported apis, get, devices

== List library files

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft
Defender for Endpoint]

{empty}[!includelink:../../includes/prerelease.md[Prerelease
information]]

* Want to experience Microsoft Defender for Endpoint?
https://www.microsoft.com/microsoft-365/windows/microsoft-defender-atp?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

List live response library files.

=== Limitations

[arabic]
. Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Get
started].

[width="100%",cols="34%,15%,51%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Library.Manage |Manage live response library

|Delegated (work or school account) |Library.Manage |Manage live
response library
|===

=== HTTP request

[source,http]
----
GET https://api.securitycenter.microsoft.com/api/libraryfiles
----

=== Request headers

[cols=",,",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. Required.
|===

=== Request body

Empty

=== Response

If successful, this method returns 200 - OK response code with a
collection of live response library file entities.

=== Example

*Request*

Here is an example of a request that gets all live response library
files

[source,http]
----
GET https://api.securitycenter.microsoft.com/api/libraryfiles
----

=== Response example

Here is an example of the response.

[source,json]
----
HTTP/1.1 200 Ok
Content-type: application/json
{
"\@odata.context": "https://api.securitycenter.microsoft.com
/api/\$metadata\#LibraryFiles",
"value": [
    {
    "fileName": "script1.ps1",
    "sha256": "6e212a0db618507c44e4ec8ee7499dfef7e5767e5f8d31144df3b96fd1145caf",
    "description": null,
    "creationTime": "2019-10-24T10:54:23.2009016Z",
    "lastUpdatedTime": "2019-10-24T10:54:23.2009016Z",
    "createdBy": "admin",
    "hasParameters": true,
    "parametersDescription": "test"
    },
    {
    "fileName": "script.sh",
    "sha256": "d0f3e3b0641dbf88ee39c822516e81a909d1d06d22341dd9b1f12aa5e5c027a2",
    "description": null,
    "creationTime": "2018-10-24T11:15:35.3688259Z",
    "lastUpdatedTime": "2018-10-24T11:15:35.3688259Z",
    "createdBy": "username",
    "hasParameters": false
    },
    {
    "fileName": "memdump.exe",
    "sha256": "fa70b87730290c0d30fe255d1dfb65de82f96286ebfeeb1d88ed3cc831329825",
    "description": "Process memory dump",
    "creationTime": "2018-10-24T10:54:23.2009016Z",
    "lastUpdatedTime": "2018-10-24T10:54:23.2009016Z",
    "createdBy": "admin",
    "hasParameters": false
    }
]
}
----

=== Related topic

* link:run-live-response.md[Run live response]
