= 
mjcaparas
:keywords: example, command, cli, remote, shell, connection, live,
response, real-time, command, script, remediate, hunt, export, log,
drop, download, file

== Live response command examples

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-investigateip-abovefoldlink[Sign
up for a free trial.]
____

Learn about common commands used in live response and see examples on
how they’re typically used.

Depending on the role you have, you can run basic or advanced live
response commands. For more information on basic and advanced commands,
see link:live-response.md[Investigate entities on devices using live
response].

=== `analyze`

[source,console]
----
# Analyze the file malware.txt
analyze file c:\Users\user\Desktop\malware.txt
----

[source,console]
----
# Analyze the process by PID
analyze process 1234
----

=== `connections`

[source,console]
----
# List active connections in json format using parameter name
connections -output json
----

[source,console]
----
# List active connections in json format without parameter name
connections json
----

=== `dir`

[source,console]
----
# List files and sub-folders in the current folder (by default it will show relative paths [-relative_path])
dir
----

[source,console]
----
# List files and sub-folders in the current folder, with their full path
dir -full_path
----

[source,console]
----
# List files and sub-folders in a specific folder
dir C:\Users\user\Desktop\
----

[source,console]
----
# List files and subfolders in the current folder in json format
dir -output json
----

=== `fileinfo`

[source,console]
----
# Display information about a file
fileinfo C:\Windows\notepad.exe
----

=== `findfile`

[source,console]
----
# Find file by name
findfile test.txt
----

=== `getfile`

[source,console]
----
# Download a file from a machine
getfile c:\Users\user\Desktop\work.txt
----

[source,console]
----
# Download a file from a machine, automatically run prerequisite commands
getfile c:\Users\user\Desktop\work.txt -auto
----

____
{empty}[!NOTE]

The following file types _cannot_ be downloaded using this command from
within Live Response:

* link:/windows-hardware/drivers/ifs/reparse-points[Reparse point files]
* link:/windows-server/administration/windows-commands/fsutil-sparse[Sparse
files]
* Empty files
* Virtual files, or files that are not fully present locally

These file types _are_ supported by
link:/powershell/scripting/overview[PowerShell].

Use PowerShell as an alternative, if you have problems using this
command from within Live Response.
____

=== `library`

[source,console]
----
# List files in the library
library
----

[source,console]
----
# Delete a file from the library
library delete script.ps1
----

=== `processes`

[source,console]
----
# Show all processes
processes
----

[source,console]
----
# Get process by pid
processes 123
----

[source,console]
----
# Get process by pid with argument name
processes -pid 123
----

[source,console]
----
# Get process by name
processes -name notepad.exe
----

=== `putfile`

[source,console]
----
# Upload file from library
putfile get-process-by-name.ps1
----

[source,console]
----
# Upload file from library, overwrite file if it exists
putfile get-process-by-name.ps1 -overwrite
----

[source,console]
----
# Upload file from library, keep it on the machine after a restart
putfile get-process-by-name.ps1 -keep
----

=== `registry`

[source,console]
----
# Show information about the values in a registry key
registry HKEY_CURRENT_USER\Console
----

[source,console]
----
# Show information about a specific registry value (the double backslash \\ indicates a registry value versus key)
registry HKEY_CURRENT_USER\Console\\ScreenBufferSize
----

=== `remediate`

[source,console]
----
# Remediate file in specific path
remediate file c:\Users\user\Desktop\malware.exe
----

[source,console]
----
# Remediate process with specific PID
remediate process 7960
----

[source,console]
----
# Remediate a registry value (the double backslash \\ indicates a registry value versus key)
remediate registry HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run\\SPStartup
----

[source,console]
----
# See list of all remediated entities
remediate list
----

=== `run`

[source,console]
----
# Run PowerShell script from the library without arguments
run script.ps1
----

[source,console]
----
# Run PowerShell script from the library with arguments
run get-process-by-name.ps1 -parameters "-processName Registry"
----

____
{empty}[!NOTE]

For long running commands such as `**run**' or `**getfile**', you may
want to use the `**&**' symbol at the end of the command to perform that
action in the background. This will allow you to continue investigating
the machine and return to the background command when done using
`**fg**' link:live-response.md#basic-commands[basic command].
____

____
{empty}[!NOTE]

When passing parameters to a live response script, do not include the
following forbidden characters: *`;'*, *`&'*, *`|'*, *`!'*, and *`$'*.
____

=== `scheduledtask`

[source,console]
----
# Get all scheduled tasks
scheduledtasks
----

[source,console]
----
# Get specific scheduled task by location and name
scheduledtasks Microsoft\Windows\Subscription\LicenseAcquisition
----

[source,console]
----
# Get specific scheduled task by location and name with spacing
scheduledtasks "Microsoft\Configuration Manager\Configuration Manager Health Evaluation"
----

=== `undo`

[source,console]
----
# Restore remediated registry
undo registry HKEY_CURRENT_USER\Console\ScreenBufferSize
----

[source,console]
----
# Restore remediated scheduledtask
undo scheduledtask Microsoft\Windows\Subscription\LicenseAcquisition
----

[source,console]
----
# Restore remediated file
undo file c:\Users\user\Desktop\malware.exe
----
