= How to schedule scans with Microsoft Defender for Endpoint on macOS
:audience: ITPro
:author: dansimp
:description: Learn how to schedule an automatic scanning time for Microsoft Defender for Endpoint in macOS to better protect your organization's assets.
:keywords: microsoft, defender, Microsoft Defender for Endpoint, mac, scans, antivirus
:manager: dansimp
:ms.author: dansimp
:ms.collection: ["m365-security-compliance"]
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: conceptual
:search.appverid: met150

== Schedule scans with Microsoft Defender for Endpoint on macOS

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign up for a free trial.]
____

While you can start a threat scan at any time with Microsoft Defender for Endpoint, your enterprise might benefit from scheduled or timed scans.
For example, you can schedule a scan to run at the beginning of every workday or week.

=== Schedule a scan with _launchd_

You can create a scanning schedule using the _launchd_ daemon on a macOS device.

For more information on the _.plist_ file format used here, see https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html[About Information Property List Files] at the official Apple developer website.

==== Schedule a quick scan

The following code shows the schema you need to use to schedule a quick scan.

. Open a text editor and use this example as a guide for your own scheduled scan file.
+
[,xml]
----
 <?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
 <plist version="1.0">
 <dict>
     <key>Label</key>
     <string>com.microsoft.wdav.schedquickscan</string>
     <key>ProgramArguments</key>
     <array>
         <string>sh</string>
         <string>-c</string>
         <string>/usr/local/bin/mdatp scan quick</string>
     </array>
     <key>RunAtLoad</key>
     <true/>
     <key>StartCalendarInterval</key>
     <dict>
         <key>Day</key>
         <integer>3</integer>
         <key>Hour</key>
         <integer>2</integer>
         <key>Minute</key>
         <integer>0</integer>
         <key>Weekday</key>
         <integer>5</integer>
     </dict>
     <key>WorkingDirectory</key>
     <string>/usr/local/bin/</string>
 </dict>
 </plist>
----

. Save the file as _com.microsoft.wdav.schedquickscan.plist_.

==== Schedule a full scan

. Open a text editor and use this example for a full scan.
+
[,xml]
----
 <?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
 <plist version="1.0">
 <dict>
     <key>Label</key>
     <string>com.microsoft.wdav.schedfullscan</string>
     <key>ProgramArguments</key>
     <array>
         <string>sh</string>
         <string>-c</string>
         <string>/usr/local/bin/mdatp scan full</string>
     </array>
     <key>RunAtLoad</key>
     <true/>
     <key>StartCalendarInterval</key>
     <dict>
         <key>Day</key>
         <integer>3</integer>
         <key>Hour</key>
         <integer>2</integer>
         <key>Minute</key>
         <integer>50</integer>
         <key>Weekday</key>
         <integer>5</integer>
     </dict>
     <key>WorkingDirectory</key>
     <string>/usr/local/bin/</string>
 </dict>
 </plist>
----

. Save the file as _com.microsoft.wdav.schedfullscan.plist_.

==== Load your file

. Open *Terminal*.
. Enter the following commands to load your file:
+
[,bash]
----
 launchctl load /Library/LaunchDaemons/<your file name.plist>
 launchctl start <your file name>
----

. Your scheduled scan will run at the date, time, and frequency you defined in your p-list.
In the previous examples, the scan runs at 2:50 AM every Friday.
 ** The `Weekday` value of `StartCalendarInterval` uses an integer to indicate the fifth day of the week, or Friday.
The range is between 0 and 7 with 7 representing Sunday.
 ** The `Day` value of `StartCalendarInterval` uses an integer to indicate the third day of the month.
The range is between 1 and 31.
 ** The `Hour` value of `StartCalendarInterval` uses an integer to indicate the second hour of the day.
The range is between 0 and 24.
The `Minute` value of `StartCalendarInterval` uses an integer to indicate fifty minutes of the hour.
The range is between 0 and 59.

____
[!IMPORTANT] Agents executed with _launchd_ will not run at the scheduled time while the device is asleep.
They will instead run once the device resumes from sleep mode.

If the device is turned off, the scan will run at the next scheduled scan time.
____

=== Schedule a scan with Intune

You can also schedule scans with Microsoft Intune.
The https://github.com/microsoft/shell-intune-samples/tree/master/Misc/MDATP#runmdatpquickscansh[runMDATPQuickScan.sh] shell script available at https://github.com/microsoft/shell-intune-samples/tree/master/Misc/MDATP[Scripts for Microsoft Defender for Endpoint] will persist when the device resumes from sleep mode.

See link:/mem/intune/apps/macos-shell-scripts[Use shell scripts on macOS devices in Intune] for more detailed instructions on how to use this script in your enterprise.
