= Deployment with a different Mobile Device Management (MDM) system for Microsoft Defender for Endpoint on Mac
:audience: ITPro
:author: maximvelichko
:description: Install Microsoft Defender for Endpoint on Mac on other management solutions.
:keywords: microsoft, defender, Microsoft Defender for Endpoint, mac, installation, deploy, macos, catalina, mojave, high sierra
:manager: dansimp
:ms.author: mavel
:ms.collection: ["m365-security-compliance"]
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: conceptual
:search.appverid: met150

== Deployment with a different Mobile Device Management (MDM) system for Microsoft Defender for Endpoint on macOS

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-investigateip-abovefoldlink[Sign up for a free trial.]
____

=== Prerequisites and system requirements

Before you get started, see xref:microsoft-defender-endpoint-mac.adoc[the main Microsoft Defender for Endpoint on macOS page] for a description of prerequisites and system requirements for the current software version.

=== Approach

____
[!CAUTION]
____

____
Currently, Microsoft officially supports only Intune and JAMF for the deployment and management of Microsoft Defender for Endpoint on macOS.
Microsoft makes no warranties, express or implied, with respect to the information provided below.
____

If your organization uses a Mobile Device Management (MDM) solution that is not officially supported, this does not mean you are unable to deploy or run Microsoft Defender for Endpoint on macOS.

Microsoft Defender for Endpoint on macOS does not depend on any vendor-specific features.
It can be used with any MDM solution that supports the following features:

* Deploy a macOS .pkg to managed devices.
* Deploy macOS system configuration profiles to managed devices.
* Run an arbitrary admin-configured tool/script on managed devices.

Most modern MDM solutions include these features, however, they may call them differently.

You can deploy Defender for Endpoint without the last requirement from the preceding list, however:

* You will not be able to collect status in a centralized way.
* If you decide to uninstall Defender for Endpoint, you will need to log on to the client device locally as an administrator.

=== Deployment

Most MDM solutions use the same model for managing macOS devices, with similar terminology.
Use xref:mac-install-with-jamf.adoc[JAMF-based deployment] as a template.

==== Package

Configure deployment of a xref:mac-install-with-jamf.adoc[required application package],  with the installation package (wdav.pkg) downloaded from xref:mac-install-with-jamf.adoc[Microsoft 365 Defender portal].

In order to deploy the package to your enterprise, use the instructions associated with your MDM solution.

==== License settings

Set up xref:mac-install-with-jamf.adoc[a system configuration profile].

Your MDM solution may call it something like "Custom Settings Profile", as Microsoft Defender for Endpoint on macOS is not part of macOS.

Use the property list, jamf/WindowsDefenderATPOnboarding.plist, which can be extracted from an onboarding package downloaded from xref:mac-install-with-jamf.adoc[Microsoft 365 Defender portal].
Your system may support an arbitrary property list in XML format.
You can upload the jamf/WindowsDefenderATPOnboarding.plist file as-is in that case.
Alternatively, it may require you to convert the property list to a different format first.

Typically, your custom profile has an ID, name, or domain attribute.
You must use exactly "com.microsoft.wdav.atp" for this value.
MDM uses it to deploy the settings file to */Library/Managed Preferences/com.microsoft.wdav.atp.plist* on a client device, and Defender for Endpoint uses this file for loading the onboarding information.

==== Kernel extension policy

Set up a KEXT or kernel extension policy.
Use team identifier *UBF8T346G9* to allow kernel extensions provided by Microsoft.

____
[!CAUTION] If your environment consists of Apple Silicon (M1) devices, these machines should not receive configuration profiles with KEXT policies.
Apple does not support KEXT on these machines, deployment of such profile would fail on M1 machines.
____

==== System extension policy

Set up a system extension policy.
Use team identifier *UBF8T346G9* and approve the following bundle identifiers:

* com.microsoft.wdav.epsext
* com.microsoft.wdav.netext

==== Full disk access policy

Grant Full Disk Access to the following components:

* Microsoft Defender for Endpoint
 ** Identifier: `com.microsoft.wdav`
 ** Identifier Type: Bundle ID
 ** Code Requirement: `identifier "com.microsoft.wdav" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = UBF8T346G9`
* Microsoft Defender for Endpoint Security Extension
 ** Identifier: `com.microsoft.wdav.epsext`
 ** Identifier Type: Bundle ID
 ** Code Requirement: `identifier "com.microsoft.wdav.epsext" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = UBF8T346G9`

==== Network extension policy

As part of the Endpoint Detection and Response capabilities, Microsoft Defender for Endpoint on macOS inspects socket traffic and reports this information to the Microsoft 365 Defender portal.
The following policy allows the network extension to perform this functionality.

* Filter type: Plugin
* Plugin bundle identifier: `com.microsoft.wdav`
* Filter data provider bundle identifier: `com.microsoft.wdav.netext`
* Filter data provider designated requirement: `identifier "com.microsoft.wdav.netext" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = UBF8T346G9`
* Filter sockets: `true`

=== Check installation status

Run xref:mac-install-with-jamf.adoc[Microsoft Defender for Endpoint] on a client device to check the onboarding status.
