= 
dansimp
:keywords: microsoft, defender, Microsoft Defender for Endpoint, mac,
installation, macos, whatsnew, catalina, big sur, monterey, ventura, mde
for mac

== What’s new in Microsoft Defender for Endpoint on Mac

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

For more information on Microsoft Defender for Endpoint on other
operating systems:

* link:linux-whatsnew.md[What’s new in Microsoft Defender for Endpoint
on Linux]
* link:ios-whatsnew.md[What’s new in Microsoft Defender for Endpoint on
iOS]

*Known issues*

Apple has identified an issue on macOS
https://developer.apple.com/documentation/macos-release-notes/macos-13_1-release-notes[Ventura
upgrade], and expected to be fixed in the next release. The issue
impacts Microsoft Defender for endpoint security extensions, and might
result in losing Full Disk Access Authorization, impacting its ability
to function properly.

____
To mitigate the risk with this issue, make sure that
link:mac-install-manually.md[Microsoft Defender for Endpoint has Full
Disk Access Authorization].
____

Dec-2022 (Build: 101.90.97 | Release version: 20.122102.19097.0)

 Build: *101.90.97*  Release version: *20.122102.19097.0*  Engine
version: *1.1.19900.2*  Signature version: *1.381.202.0*

*What’s new*

* Scanning optimization for move file operations
* Adding exclusions from command line now requires admin privileges
* Decrease sysextd noise from Tamper Protection in Advanced Hunting
* Bug and performance fixes

Nov-2022 (Build: 101.87.30 | Release version: 20.122082.18681.0)

 Released: *Nov 5, 2022*  Published: *Nov 5, 2022*  Build: *101.87.30*
 Release version: *20.122082.18681.0*  Engine version: *1.1.19700.3*
 Signature version: *1.379.17.0*

*What’s new*

* Fix for some users experiencing performance issues and temporary
system hangs
* Bug and performance fixes

Oct-2022 (Build: 101.86.81 | Release version: 20.122082.18681.0)

 Released: *Oct 25, 2022*  Published: *Oct 25, 2022*  Build: *101.86.81*
 Release version: *20.122082.18681.0*  Engine version: *1.1.19700.3*
 Signature version: *1.377.636.0*

*What’s new*

* Bug fix: Upgrade fails if _mdatp user a member of _lpadmin group

____
[!IMPORTANT] This is a minimal recommended MDE version for macOS
Ventura.
____

Oct-2022 (Build: 101.82.21 | Release version: 20.122082.18221.0)

 Build: *101.82.21*  Release version: *20.122082.18221.0*  Engine
version: *1.1.19400.3*  Signature version: *1.369.962.0*

*What’s new*

* Bug fix - Mac TP in Block mode causing device hang on shutdown/crashes
on reboot
* Add a mdatp command-line switch to view the on-demand scan history
* Improve Performance of Device Owner on MacOs
* Ready for macOS Ventura (13.0)
* Bug and performance fixes

Aug-2022 (Build: 101.78.13 | Release version: 20.122072.17813.0)

 Build: *101.78.13*  Release version: *20.122072.17813.0*  Engine
version: *1.1.19500.2*  Signature version: *1.373.556.0*

*What’s new*

* Fix for uninstaller to properly delete Application Support folder
* Fix for Network Protection not filtering Safari when Firewall or
iCloud Private Relay is on
* Fix for osqueryui zombie processes
* Fix for UI crash on Ventura
* Fix for definitions not getting downloaded right after install
* Other bug fixes

Aug-2022 (Build: 101.75.90 | Release version: 20.122071.17590.0)

 Released: *Aug 3, 2022*  Published: *Aug 3, 2022*  Build: *101.75.90*
 Release version: *20.122071.17590.0*  Engine version: *1.1.19300.3*
 Signature version: *1.369.395.0*

*What’s new*

* Added a new field in the output of `mdatp health` that can be used to
query the enforcement level of the network protection feature. The new
field is called `network_protection_enforcement_level` and can take one
of the following values: `audit`, `block`, or `disabled`.
* Addressed a product bug where multiple detections of the same content
could lead to duplicate entries in the threat history.
* Other bug fixes.

Jul-2022 (Build: 101.73.77 | Release version: 20.122062.17377.0)

 Released: *Jul 21, 2022*  Published: *Jul 21, 2022*  Build: *101.73.77*
 Release version: *20.122062.17377.0*  Engine version: *1.1.19200.3*
 Signature version: *1.367.1011.0*

*What’s new*

* Addressed an issue where printing could not be completed successfully
due to the network extension
* Added an option to
link:mac-preferences.md#configure-file-hash-computation-feature[configure
file hash computation]
* From this build onwards, the product will have the new anti-malware
engine by default
* Performance improvements for file copy operations
* Bug fixes

Jul-2022 (Build: 101.71.18 | Release version: 20.122052.17118.0)

 Released: *Jul 7, 2022*  Published: *Jul 7, 2022*  Build: *101.71.18*
 Release version: *20.122052.17118.0*

*What’s new*

* `mdatp connectivity test` was extended with an extra URL that the
product requires to function correctly. The new URL is
https://go.microsoft.com/fwlink/?linkid=2144709.
* Up until now, the product log level wasn’t persisted between product
restarts. Starting from this version, there’s a new command-line tool
switch that persists the log level. The new command is
`mdatp log level persist --level <level>`.
* Fixed a bug in the product installation package that in rare cases
could lead a loss of product state during updates
* Performance improvements for file copy operations and built-in macOS
applications
* Bug fixes

Jun-2022 (Build: 101.70.19 | Release version: 20.122051.17019.0)

 Released: *Jun 14, 2022*  Published: *Jun 14, 2022*  Build: *101.70.19*
 Release version: *20.122051.17019.0*

*What’s new*

* Fixed a bug where threat-related notifications were not always
presented to the end user.
* Performance improvements & other bug fixes

Jun-2022 (Build: 101.70.18 | Release version: 20.122042.17018.0)

 Released: *Jun 2, 2022*  Published: *Jun 2, 2022*  Build: *101.70.18*
 Release version: *20.122042.17018.0*

*What’s new*

* Fixed a bug where the installation package was sometimes hanging
indefinitely during product updates
* Fixed a bug where the product sometimes was incorrectly detecting
files inside the quarantine folder
* Performance improvements & other bug fixes

May-2022 (Build: 101.66.54 | Release version: 20.122041.16654.0)

 Released: *May 11, 2022*  Published: *May 11, 2022*  Build: *101.66.54*
 Release version: *20.122041.16654.0*

*What’s new*

* Addressed an issue where
`mdatp diagnostic real-time-protection-statistics` was not printing the
correct process path in some cases.
* Bug fixes

Apr-2022 (Build: 101.64.15 | Release version: 20.122032.16415.0)

 Released: *Apr 26, 2022*  Published: *Apr 26, 2022*  Build: *101.64.15*
 Release version: *20.122032.16415.0*

*What’s new*

* Fixed a regression introduced in version 101.61.69 where the status
menu icon was sometimes showing an error icon, even though no action was
required from the end user
* Improved the `conflicting_applications` field in `mdatp health` to
show only the most recent 10 processes and also to include the process
names. This makes it easier to identify which processes are potentially
conflicting with Microsoft Defender for Endpoint for Mac.
* Fixed a bug in `mdatp device-control removable-media policy list`
where vendor ID and product ID were displayed as decimal instead of
hexadecimal
* Performance improvements & other bug fixes

Mar-2022 (Build: 101.61.69 | Release version: 20.122022.16169.0)

 Released: *Mar 25, 2022*  Published: *Mar 25, 2022*  Build: *101.61.69*
 Release version: *20.122022.16169.0*

*What’s new*

* Bug fixes

Mar-2022 (Build: 101.60.91 | Release version: 20.122021.16091.0)

 Released: *Mar 8, 2022*  Published: *Mar 8, 2022*  Build: *101.60.91*
 Release version: *20.122021.16091.0*

*What’s new*

* This version contains a security update for
https://msrc-blog.microsoft.com/2022/03/08/guidance-for-cve-2022-23278-spoofing-in-microsoft-defender-for-endpoint/[CVE-2022-23278]

Feb-2022 (Build: 101.59.50 | Release version: 20.122021.15950.0)

 Released: *Feb 28, 2022*  Published: *Feb 28, 2022*  Build: *101.59.50*
 Release version: *20.122021.15950.0*

*What’s new*

* This version adds support for macOS 12.3. Starting with macOS 12.3,
https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes[Apple
is removing Python 2.7]. There will be no Python version preinstalled on
macOS by default. *ACTION NEEDED*:
** Users must update Microsoft Defender for Endpoint for Mac to version
101.59.50 (or newer) prior to updating their devices to macOS Monterey
12.3 (or newer). This minimal version 101.59.50 is a prerequisite to
eliminating Python-related issues with Microsoft Defender for Endpoint
for Mac on macOS Monterey.
** For remote deployments, existing MDM setups must be updated to
Microsoft Defender for Endpoint for Mac version 101.59.50 (or newer).
Pushing via MDM an older Microsoft Defender for Endpoint for Mac version
to macOS Monterey 12.3 (or newer) will result in an installation
failure. **

Feb-2022 (Build: 101.59.10 | Release version: 20.122012.15910.0)

 Released: *Feb 22, 2022*  Published: *Feb 22, 2022*  Build: *101.59.10*
 Release version: *20.122012.15910.0*

*What’s new*

* The command-line tool now supports restoring quarantined files to a
location other than the one where the file was originally detected. This
can be done through
`mdatp threat quarantine restore --id [threat-id] --path [destination-folder]`.
* Extended device control to handle devices connected over Thunderbolt 3
* Improved the handling of device control policies containing invalid
vendor IDs and product IDs. Prior to this version, if the policy
contained one or more invalid IDs, the entire policy was ignored.
Starting from this version, only the invalid portions of the policy are
ignored. Issues with the policy are surfaced through
`mdatp device-control removable-media policy list`.
* Bug fixes

Feb-2022 (Build: 101.56.62 | Release version: 20.121122.15662.0)

 Released: *Feb 7, 2022*  Published: *Feb 7, 2022*  Build: *101.56.62*
 Release version: *20.121122.15662.0*

*What’s new*

* Bug fixes

Jan-2022 (Build: 101.56.35 | Release version: 20.121121.15635.0)

 Released: *Jan 30, 2022*  Published: *Jan 30, 2022*  Build: *101.56.35*
 Release version: *20.121121.15635.0*

*What’s new*

* The application has been renamed from ``Microsoft Defender ATP'' to
``Microsoft Defender''. End users will observe the following changes:
* The application installation path has been changed from
`/Application/Microsoft Defender ATP.app` to
`/Applications/Microsoft Defender.app`.
* Within the user experience, occurrences of ``Microsoft Defender ATP''
have been replaced with ``Microsoft Defender''
* Resolved an issue where some VPN applications could not connect due to
the network content filter that is distributed with Microsoft Defender
for Endpoint for Mac
* Addressed an issue discovered in macOS 12.2 beta 2 where the
installation package could not be opened due to a change in the
operating system (OS) that prevents installation of packages with
certain characteristics. While it appears that this OS change is not
included in the final release of macOS 12.2, it is likely that it will
be reintroduced in a future macOS version. As such, we encourage all
enterprise administrators to refresh the Microsoft Defender for Endpoint
package in their management console to this product version (or a newer
version).
* Addressed an issue seen on some M1 devices where the product was stuck
with invalid antimalware definitions and could not successfully update
to a working set of definitions.
* `mdatp health` output has been extended with an additional attribute
called `full_disk_access_enabled` that can be used to determine whether
Full Disk Access has been granted to all components of Microsoft
Defender for Endpoint for Mac.
* Performance improvements & bug fixes

Jan-2022 (Build: 101.54.16 | Release version: 20.121111.15416.0)

 Released: *Jan 12, 2022*  Published: *Jan 12, 2022*  Build: *101.54.16*
 Release version: *20.121111.15416.0*

*What’s new*

* macOS 10.14 (Mojave) is no longer supported
* After a product setting stops being managed by the administrator
through MDM, it now reverts to the value it had before it was managed
(the value configured locally by the end user or, if no such local value
was explicitly provided, the default value used by the product). Prior
to this change, after a setting stopped being managed, its managed value
persisted and was still used by the product.
* Performance improvements & bug fixes

2021 releases

(Build: 101.49.25 | Release version: 20.121092.14925.0)

 Build: *101.49.25*  Release version: *20.121092.14925.0*

*What’s new*

* Added a new switch to the command-line tool to control whether
archives are scanned during on-demand scans. This can be configured
through `mdatp config scan-archives --value [enabled/disabled]`. By
default, this is set to enabled.
* Bug fixes

(Build: 101.47.27 | Release version: 20.121082.14727.0)

 Build: *101.47.27*  Release version: *20.121082.14727.0*

*What’s new*

* Fix for a system freeze occurring on shutdown on macOS Mojave and
macOS Catalina.

(Build: 101.43.84 | Release version: 20.121082.14384.0)

 Build: *101.43.84*  Release version: *20.121082.14384.0*

*What’s new*

* Candidate build for macOS 12 (Monterey)
* Bug fixes

(Build: 101.41.10 | Release version: 20.121072.14110.0)

 Build: *101.41.10*  Release version: *20.121072.14110.0*

*What’s new*

* Added new switches to the command-line tool:
** Control degree of parallelism for on-demand scans. This can be
configured through
`mdatp config maximum-on-demand-scan-threads --value [number-between-1-and-64]`.
By default, a degree of parallelism of 2 is used.
** Control whether scans after security intelligence updates are enabled
or disabled. This can be configured through
`mdatp config scan-after-definition-update --value [enabled/disabled]`.
By default, this is set to enabled.
* Changing the product log level now requires elevation.
* Performance improvements & bug fixes

(Build: 101.40.84 | Release version: 20.121071.14084.0)

 Build: *101.40.84*  Release version: *20.121071.14084.0*

*What’s new*

* M1 chip native support
* Performance improvements & bug fixes

(Build: 101.37.97 | Release version: 20.121062.13797.0)

 Build: *101.37.97*  Release version: *20.121062.13797.0*

*What’s new*

* Performance improvements & bug fixes

(Build: 101.34.28 | Release version: 20.121061.13428.0)

 Build: *101.34.28*  Release version: *20.121061.13428.0*

*What’s new*

* Bug fixes

(Build: 101.34.27 | Release version: 20.121052.13427.0)

 Build: *101.34.27*  Release version: *20.121052.13427.0*

*What’s new*

* Bug fixes

(Build: 101.34.20 | Release version: 20.121051.13420.0)

 Build: *101.34.20*  Release version: *20.121051.13420.0*

*What’s new*

* link:mac-device-control-overview.md[Device control for macOS] is now
in general availability.
* Addressed an issue where a quick scan could not be started from the
status menu on macOS 11 (Big Sur).
* Other bug fixes

(Build: 101.32.69 | Release version: 20.121042.13269.0)

 Build: *101.32.69*  Release version: *20.121042.13269.0*

*What’s new*

* Addressed an issue where concurrent access to the keychain from
Microsoft Defender for Endpoint and other applications can lead to
keychain corruption.

(Build: 101.29.64 | Release version: 20.121042.12964.0)

 Build: *101.29.64*  Release version: *20.121042.12964.0*

*What’s new*

* Starting with this version, threats detected during on-demand
antivirus scans triggered through the command-line client are
automatically remediated. Threats detected during scans triggered
through the user interface still require manual action.
* `mdatp diagnostic real-time-protection-statistics` now supports two
additional switches:
** `--sort`: sorts the output descending by total number of files
scanned
** `--top N`: displays the top N results (only works if `--sort` is also
specified)
* Performance improvements (specifically for when `YARN` is used) & bug
fixes

(Build: 101.27.50 | Release version: 20.121022.12750.0)

 Build: *101.27.50*  Release version: *20.121022.12750.0*

*What’s new*

* Fix to accommodate for Apple certificate expiration for macOS Catalina
and earlier. This fix restores Microsoft Defender Vulnerability
Management (MDVM) functionality.

(Build: 101.25.69 | Release version: 20.121022.12569.0)

 Build: *101.25.69*  Release version: *20.121022.12569.0*

*What’s new*

* Microsoft Defender for Endpoint on macOS is now available in preview
for US Government customers. For more information, see
link:gov.md[Microsoft Defender for Endpoint for US Government
customers].
* Performance improvements (specifically for the situation when the
XCode Simulator app is used) & bug fixes.

(Build: 101.23.64 | Release version: 20.121021.12364.0)

 Build: *101.23.64*  Release version: *20.121021.12364.0*

*What’s new*

* Added a new option to the command-line tool to view information about
the last on-demand scan. To view information about the last on-demand
scan, run `mdatp health --details antivirus`.
* Performance improvements & bug fixes

Prior releases

(Build: 101.22.79 | Release version: 20.121012.12279.0)

 Build: *101.22.79*  Release version: *20.121012.12279.0*

*What’s new*

* Performance improvements & bug fixes

(Build: 101.19.88 | Release version: 20.121011.11988.0)

 Build:*101.19.88*  Release version: *20.121011.11988.0*

*What’s new*

* Performance improvements & bug fixes

(Build: 101.19.48 | Release version: 20.120121.11948.0)

 Build: *101.19.48*  Release version: *20.120121.11948.0*

*What’s new*

____
[!NOTE] The old command-line tool syntax has been deprecated with this
release. For information on the new syntax, see
link:mac-resources.md#configuring-from-the-command-line[Resources]. -
Added a new command-line switch to disable the network extension:
`mdatp system-extension network-filter disable`. This command can be
useful to troubleshoot networking issues that could be related to
Microsoft Defender for Endpoint on Mac. - Performance improvements & bug
fixes
____

(Build: 101.19.21 | Release version: 20.120101.11921.0)

 Build: *101.19.21*  Release version: *20.120101.11921.0*

*What’s new*

* Bug fixes

(Build: 101.15.26 | Release version: 20.120102.11526.0)

 Build: *101.15.26*  Release version: *20.120102.11526.0*

*What’s new*

* Improved the reliability of the agent when running on macOS 11 Big
Sur.
* Added a new command-line switch (`--ignore-exclusions`) to ignore AV
exclusions during custom scans (`mdatp scan custom`).
* Performance improvements & bug fixes

(Build: 101.13.75 | Release version: 20.120101.11375.0)

 Build: *101.13.75*  Release version: *20.120101.11375.0*

*What’s new*

* Removed conditions when Microsoft Defender for Endpoint was triggering
a macOS 11 (Big Sur) bug that manifests into a kernel panic.
* Fixed a memory leak in the Endpoint Security system extension when
running on mac 11 (Big Sur).
* Bug fixes

(Build: 101.10.72)

 Build: *101.10.72*

*What’s new*

* Bug fixes

(Build: 101.09.61)

 Build: *101.09.61*

*What’s new*

* Added a new managed preference for
link:++mac-preferences.md#show--hide-option-to-send-feedback++[disabling
the option to send feedback].
* Status menu icon now shows a healthy state when the product settings
are managed. Previously, the status menu icon was displaying a warning
or error state, even though the product settings were managed by the
administrator.
* Performance improvements & bug fixes

(Build: 101.09.50)

 Build: *101.09.50*

*What’s new*

* This product version has been validated on macOS Big Sur 11 beta 9.
* The new syntax for the mdatp command-line tool is now the default one.
For more information on the new syntax, see
link:mac-resources.md#configuring-from-the-command-line[Resources for
Microsoft Defender for Endpoint on macOS]. > [!NOTE] > The old
command-line tool syntax will be removed from the product on *January
1st, 2021*.
* Extended `mdatp diagnostic create` with a new parameter
(`--path [directory]`) that allows the diagnostic logs to be saved to a
different directory.
* Performance improvements & bug fixes

(Build: 101.09.49)

 Build: *101.09.49*

*What’s new*

* User interface improvements to differentiate exclusions that are
managed by the IT administrator versus exclusions defined by the local
user.
* Improved CPU utilization during on-demand scans.
* Performance improvements & bug fixes

(Build: 101.07.23)

 Build: *101.07.23*

*What’s new*

* Added new fields to the output of `mdatp --health` for checking the
status of passive mode and the EDR group ID. > [!NOTE] >
`mdatp --health` will be replaced with `mdatp health` in a future
product update.
* Fixed a bug where automatic sample submission was not marked as
managed in the user interface.
* Added new settings for controlling the retention of items in the
antivirus scan history. You can now
link:mac-preferences.md#antivirus-scan-history-retention-in-days[specify
the number of days to retain items in the scan history] and
link:mac-preferences.md#maximum-number-of-items-in-the-antivirus-scan-history[specify
the maximum number of items in the scan history].
* Bug fixes

(Build: 101.06.63)

 Build: *101.06.63*

*What’s new*

* Addressed a performance regression introduced in version `101.05.17`.
The regression was introduced with the fix to eliminate the kernel
panics some customers have observed when accessing SMB shares. We have
reverted this code change and are investigating alternative ways to
eliminate the kernel panics.

(Build: 101.05.17)

 Build: *101.05.17*

*What’s new*

____
[!IMPORTANT] We are working on a new and enhanced syntax for the `mdatp`
command-line tool. The new syntax is currently the default in the
Insider Fast and Insider Slow update channels. We encourage you to
famliliarize yourself with this new syntax. We will continue supporting
the old syntax in parallel with the new syntax and will provide more
communication around the deprecation plan for the old syntax in the
upcoming months. - Addressed a kernel panic that occurred sometimes when
accessing SMB file shares. - Performance improvements & bug fixes
____

(Build: 101.05.16)

 Build: *101.05.16*

*What’s new*

* Improvements to quick scan logic to significantly reduce the number of
scanned files.
* Added
link:mac-resources.md#how-to-enable-autocompletion[autocompletion
support] for the command-line tool.
* Bug fixes

(Build: 101.03.12)

 Build: *101.03.12*

*What’s new*

* Performance improvements & bug fixes

(Build: 101.01.54)

 Build: *101.01.54*

*What’s new*

* Improvements around compatibility with Time Machine
* Accessibility improvements
* Performance improvements & bug fixes

(Build: 101.00.31)

 Build: *101.00.31*

*What’s new*

* Improved
link:/mem/intune/apps/apps-advanced-threat-protection-macos[product
onboarding experience for Intune users]
* Antivirus link:mac-exclusions.md#supported-exclusion-types[exclusions
now support wildcards]
* Added the ability to trigger antivirus scans from the macOS contextual
menu. You can now right-click a file or a folder in Finder and select
*Scan with Microsoft Defender for Endpoint*.
* In-place product downgrades are now explicitly disallowed by the
installer. If you need to downgrade, first uninstall the existing
version and reconfigure your device.
* Other performance improvements & bug fixes

(Build: 100.90.27)

 Build: *100.90.27*

*What’s new*

* You can now link:mac-updates.md#set-the-channel-name[set an update
channel] for Microsoft Defender for Endpoint on macOS that is different
from the system-wide update channel.
* New product icon
* Other user experience improvements
* Bug fixes

(Build: 100.86.92)

 Build: *100.86.92*

*What’s new*

* Improvements around compatibility with Time Machine
* Addressed an issue where the product was sometimes not cleaning all
files under `/Library/Application Support/Microsoft/Defender` during
uninstallation.
* Reduced the CPU utilization of the product when Microsoft products are
updated through Microsoft AutoUpdate.
* Other performance improvements & bug fixes

(Build: 100.86.91)

 Build: *100.86.91*

*What’s new*

____
[!CAUTION] To ensure the most complete protection for your macOS devices
and in alignment with Apple stopping delivery of macOS native security
updates to OS versions older than [current - 2], MDATP for Mac
deployment and updates will no longer be supported on macOS Sierra
[10.12]. MDATP for Mac updates and enhancements will be delivered to
devices running versions Catalina [10.15], Mojave [10.14], and High
Sierra [10.13].

If you already have MDATP for Mac deployed to your Sierra [10.12]
devices, please upgrade to the latest macOS version to eliminate risks
of losing protection.
____

* Performance improvements & bug fixes

(Build: 100.83.73)

 Build: *100.83.73*

*What’s new*

* Added more controls for IT administrators around
link:mac-preferences.md#exclusion-merge-policy[management of
exclusions],
link:mac-preferences.md#threat-type-settings-merge-policy[management of
threat type settings], and
link:mac-preferences.md#disallowed-threat-actions[disallowed threat
actions].
* When Full Disk Access is not enabled on the device, a warning is now
displayed in the status menu.
* Performance improvements & bug fixes

(Build: 100.82.60)

 Build: *100.82.60*

*What’s new*

* Addressed an issue where the product fails to start following a
definition update.

(Build: 100.80.42)

 Build: *100.80.42*

*What’s new*

* Bug fixes

(Build: 100.79.42)

 Build: *100.79.42*

*What’s new*

* Fixed an issue where Microsoft Defender for Endpoint on Mac was
sometimes interfering with Time Machine.
* Added a new switch to the command-line utility for testing the
connectivity with the backend service
+
[source,bash]
----
mdatp connectivity test
----
* Added ability to view the full threat history in the user interface
(can be accessed from the *Protection history* view).
* Performance improvements & bug fixes

(Build: 100.72.15)

 Build: *100.72.15*

*What’s new*

* Bug fixes

(Build: 100.70.99)

 Build: *100.70.99*

*What’s new*

* Addressed an issue that impacts the ability of some users to upgrade
to macOS Catalina when real-time protection is enabled. This sporadic
issue was caused by Microsoft Defender for Endpoint locking files within
Catalina upgrade package while scanning them for threats, which led to
failures in the upgrade sequence.

(Build: 100.68.99)

 Build: *100.68.99*

*What’s new*

* Added the ability to configure the antivirus functionality to run in
link:mac-preferences.md#enforcement-level-for-antivirus-engine[passive
mode].
* Performance improvements & bug fixes

(Build: 100.65.28)

 Build: *100.65.28*

*What’s new*

* Added support for macOS Catalina.

____
[!CAUTION] macOS 10.15 (Catalina) contains new security and privacy
enhancements. Beginning with this version, by default, applications are
not able to access certain locations on disk (such as Documents,
Downloads, Desktop, etc.) without explicit consent. In the absence of
this consent, Microsoft Defender for Endpoint is not able to fully
protect your device.

The mechanism for granting this consent depends on how you deployed
Microsoft Defender for Endpoint:

* For manual deployments, see the updated instructions in the
link:mac-install-manually.md#how-to-allow-full-disk-access[Manual
deployment topic].
* For managed deployments, see the updated instructions in the
link:mac-install-with-jamf.md[JAMF-based deployment] and
link:mac-install-with-intune.md#create-system-configuration-profiles[Microsoft
Intune-based deployment] topics.
____

* Performance improvements & bug fixes
