= Manage tamper protection for your organization using Microsoft 365 Defender
:audience: ITPro
:author: denisebmsft
:description: Turn tamper protection on or off for your tenant using the Microsoft 365 Defender portal.
:keywords: malware, defender, antivirus, tamper protection, Microsoft 365 Defender
:manager: dansimp
:ms.author: deniseb
:ms.collection: ["M365-security-compliance", "m365initiative-defender-endpoint"]
:ms.custom: ["nextgen", "admindeeplinkDEFENDER"]
:ms.localizationpriority: medium
:ms.mktglfcycl: manage
:ms.pagetype: security
:ms.reviewer: mattcall, pahuijbr, hayhov, oogunrinde
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Manage tamper protection for your organization using Microsoft 365 Defender portal

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* Microsoft Defender Antivirus

*Platforms*

* Windows

Tamper protection can be turned on or off for your tenant using the Microsoft 365 Defender portal (https://security.microsoft.com).
Here are a few points to keep in mind:

* Currently, the option to manage 'tamper protection' in the Microsoft 365 Defender portal is on by default for new deployments.
For existing deployments, 'tamper protection' is available on an opt-in basis.
To opt in, in the https://go.microsoft.com/fwlink/p/?linkid=2077139[Microsoft 365 Defender portal], choose *Settings* > *Endpoints* > *Advanced features* > *Tamper protection*.
* When you use the Microsoft 365 Defender portal to manage 'tamper protection', you do not have to use Intune or the tenant attach method.
* When you manage 'tamper protection' in the Microsoft 365 Defender portal, the setting is applied tenant wide, affecting all of your devices that are running Windows 10, Windows 10 Enterprise multi-session, Windows 11, Windows 11 Enterprise multi-session, Windows Server 2012 R2, Windows Server 2016, Windows Server 2019 or Windows Server 2022.
To fine-tune 'tamper protection' (such as having tamper protection on for some devices but off for others), use either xref:manage-tamper-protection-microsoft-endpoint-manager.adoc[Manage tamper protection for your organization using Microsoft Endpoint Manager] or xref:manage-tamper-protection-configuration-manager.adoc[Manage tamper protection using tenant attach with Configuration Manager, version 2006].
* If you have a hybrid environment, tamper protection settings configured in Intune take precedence over settings configured in the Microsoft 365 Defender portal.

=== Requirements for managing tamper protection in the Microsoft 365 Defender portal

* You must have appropriate link:/microsoft-365/security/defender-endpoint/assign-portal-access[permissions] assigned, such as global admin, security admin, or security operations.
* Your Windows devices must be running one of the following versions of Windows:
 ** Windows 11
 ** Windows 11 Enterprise multi-session
 ** Windows 10
 ** Windows 10 Enterprise multi-session
 ** Windows Server 2022
 ** Windows Server 2019
 ** Windows Server, version 1803 or later
 ** Windows Server 2016
 ** Windows Server 2012 R2

For more information about releases, see link:/windows/release-health/release-information[Windows 10 release information].

* Your devices must be link:/microsoft-365/security/defender-endpoint/onboarding[onboarded to Microsoft Defender for Endpoint].
* Your devices must be using anti-malware platform version `4.18.2010.7` (or above) and anti-malware engine version `1.1.17600.5` (or above).
(xref:manage-updates-baselines-microsoft-defender-antivirus.adoc[Manage Microsoft Defender Antivirus updates and apply baselines].)
* xref:enable-cloud-protection-microsoft-defender-antivirus.adoc[Cloud-delivered protection] must be turned on.

____
[!NOTE] When tamper protection is enabled via the Microsoft 365 Defender portal, cloud-delivered protection is required, so that the enabled state of tamper protection can be controlled.
+ Starting with the November 2021 update (platform version `4.18.2111.5`), if cloud-delivered protection is not turned on for a device and tamper protection is turned on in the Microsoft 365 Defender portal, then cloud-delivered protection will be automatically turned on for that device along with tamper protection.
____

=== Turn tamper protection on (or off) in the Microsoft 365 Defender portal

:::image type="content" source="../../media/mde-turn-tamperprotectionon.png" alt-text="Turn tamper protection turned on in the Microsoft 365 Defender portal" lightbox="../../media/mde-turn-tamperprotectionon.png":::

. Go to the Microsoft 365 Defender portal (https://security.microsoft.com) and sign in.
. Choose *Settings* > *Endpoints*.
. Go to *General* > *Advanced features*, and then turn tamper protection on.

____
[!TIP] If you're looking for Antivirus related information for other platforms, see:

* xref:mac-preferences.adoc[Set preferences for Microsoft Defender for Endpoint on macOS]
* xref:microsoft-defender-endpoint-mac.adoc[Microsoft Defender for Endpoint on Mac]
* link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS Antivirus policy settings for Microsoft Defender Antivirus for Intune]
* xref:linux-preferences.adoc[Set preferences for Microsoft Defender for Endpoint on Linux]
* xref:microsoft-defender-endpoint-linux.adoc[Microsoft Defender for Endpoint on Linux]
* xref:android-configure.adoc[Configure Defender for Endpoint on Android features]
* xref:ios-configure-features.adoc[Configure Microsoft Defender for Endpoint on iOS features]
____
