= 
denisebmsft
:keywords: malware, defender, antivirus, tamper protection, Microsoft
365 Defender

== Manage tamper protection for your organization using Microsoft 365 Defender portal

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 2]
* Microsoft Defender Antivirus

*Platforms* - Windows

Tamper protection can be turned on or off for your tenant using the
Microsoft 365 Defender portal (https://security.microsoft.com). Here are
a few points to keep in mind:

* Currently, the option to manage tamper protection in the Microsoft 365
Defender portal is on by default for new deployments. For existing
deployments, tamper protection is available on an opt-in basis. To opt
in, in the Microsoft 365 Defender portal, choose *Settings* >
*Endpoints* > *Advanced features* > *Tamper protection*.
* When you use the Microsoft 365 Defender portal to manage tamper
protection, you don’t have to use Intune or the tenant attach method.
* When you manage tamper protection in the Microsoft 365 Defender
portal, the setting is applied tenant wide, affecting all of your
devices that are running Windows 10, Windows 10 Enterprise
multi-session, Windows 11, Windows 11 Enterprise multi-session, Windows
Server 2012 R2, Windows Server 2016, Windows Server 2019 or Windows
Server 2022. To fine-tune tamper protection (such as having tamper
protection on for some devices but off for others), use either
link:manage-tamper-protection-microsoft-endpoint-manager.md[Manage
tamper protection for your organization using Microsoft Endpoint
Manager] or
link:manage-tamper-protection-configuration-manager.md[Manage tamper
protection using tenant attach with Configuration Manager&#44; version
2006].
* If you have a hybrid environment, tamper protection settings
configured in Intune take precedence over settings configured in the
Microsoft 365 Defender portal.
* Tamper protection is part of anti-tampering capabilities that include
link:attack-surface-reduction-rules-reference.md[standard protection
attack surface reduction rules].

=== Requirements for managing tamper protection in the Microsoft 365 Defender portal

* You must have appropriate
link:/microsoft-365/security/defender-endpoint/assign-portal-access[permissions]
assigned, such as global admin, security admin, or security operations.
* Your Windows devices must be running one of the following versions of
Windows:
** Windows 11
** Windows 11 Enterprise multi-session
** Windows 10
** Windows 10 Enterprise multi-session
** Windows Server 2022
** Windows Server 2019
** Windows Server, version 1803 or later
** Windows Server 2016
** Windows Server 2012 R2

For more information about releases, see
link:/windows/release-health/release-information[Windows 10 release
information].

* Your devices must be
link:/microsoft-365/security/defender-endpoint/onboarding[onboarded to
Microsoft Defender for Endpoint].
* Your devices must be using anti-malware platform version `4.18.2010.7`
(or above) and anti-malware engine version `1.1.17600.5` (or above).
(link:manage-updates-baselines-microsoft-defender-antivirus.md[Manage
Microsoft Defender Antivirus updates and apply baselines].)
* link:enable-cloud-protection-microsoft-defender-antivirus.md[Cloud-delivered
protection] must be turned on.

____
[!NOTE] When tamper protection is enabled via the Microsoft 365 Defender
portal, cloud-delivered protection is required, so that the enabled
state of tamper protection can be controlled. +
Starting with the November 2021 update (platform version `4.18.2111.5`),
if cloud-delivered protection is not turned on for a device and tamper
protection is turned on in the Microsoft 365 Defender portal, then
cloud-delivered protection will be automatically turned on for that
device along with tamper protection.
____

=== Turn tamper protection on (or off) in the Microsoft 365 Defender portal

:::image type=``content''
source=``../../media/mde-turn-tamperprotectionon.png'' alt-text=``Turn
tamper protection turned on in the Microsoft 365 Defender portal''
lightbox=``../../media/mde-turn-tamperprotectionon.png'':::

[arabic]
. Go to the Microsoft 365 Defender portal
(https://security.microsoft.com) and sign in.
. Choose *Settings* > *Endpoints*.
. Go to *General* > *Advanced features*, and then turn tamper protection
on.

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____
