= 
mjcaparas
:keywords: manage suppression, rules, rule name, scope, action, alerts,
turn on, turn off

== Manage suppression rules

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

There might be scenarios where you need to suppress alerts from
appearing in the portal. You can create suppression rules for specific
alerts that are known to be innocuous such as known tools or processes
in your organization. For more information on how to suppress alerts,
see link:manage-alerts.md[Suppress alerts].

You can view a list of all the suppression rules and manage them in one
place. You can also turn an alert suppression rule on or off.

[arabic]
. Log in to https://go.microsoft.com/fwlink/p/?linkid=2077139[Microsoft
365 Defender] using an account with the Security administrator or Global
administrator role assigned.
. In the navigation pane, select *Settings* > *Endpoints* > *Rules* >
*Alert suppression*. The list of suppression rules that users in your
organization have created is displayed.
. Select a rule by clicking on the check-box beside the rule name.
. Click *Turn rule on*, *Edit rule*, or *Delete rule*. When making
changes to a rule, you can choose to release alerts that it has already
suppressed, regardless whether or not these alerts match the new
criteria.

=== View details of a suppression rule

[arabic]
. In the navigation pane, select *Settings* > *Endpoints* > *Rules* >
*Alert suppression*. The list of suppression rules that users in your
organization have created is displayed.
. Click on a rule name. Details of the rule is displayed. You’ll see the
rule details such as status, scope, action, number of matching alerts,
created by, and date when the rule was created. You can also view
associated alerts and the rule conditions.

=== Related topics

* link:manage-alerts.md[Manage alerts]
