= 
denisebmsft
:keywords: updates, security baselines, schedule updates

== Manage the schedule for when protection updates should be downloaded and applied

____
[!IMPORTANT] Customers who applied the March 2022 Microsoft Defender
engine update (*1.1.19100.5*) might have encountered high resource
utilization (CPU and/or memory). Microsoft has released an update
(*1.1.19200.5*) that resolves the bugs introduced in the earlier
version. Customers are recommended to update to this new engine build of
Antivirus Engine (*1.1.19200.5*). To ensure any performance issues are
fully fixed, it is recommended to reboot machines after applying update.
For more information, see
link:manage-updates-baselines-microsoft-defender-antivirus.md#monthly-platform-and-engine-versions[Monthly
platform and engine versions].
____

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] - Microsoft Defender Antivirus

*Platforms* - Windows

Microsoft Defender Antivirus lets you determine when it should look for
and download updates.

You can schedule updates for your endpoints by:

* Specifying the day of the week to check for protection updates
* Specifying the interval to check for protection updates
* Specifying the time to check for protection updates

You can also randomize the times when each endpoint checks and downloads
protection updates. See the
link:scheduled-catch-up-scans-microsoft-defender-antivirus.md[Schedule
scans] topic for more information.

=== Use Configuration Manager to schedule protection updates

[arabic]
. On your Microsoft Endpoint Manager console, open the antimalware
policy you want to change (click *Assets and Compliance* in the
navigation pane on the left, then expand the tree to *Overview* >
*Endpoint Protection* > *Antimalware Policies*)
. Go to the *Security intelligence updates* section.
. To check and download updates at a certain time:
[arabic]
.. Set *Check for Endpoint Protection security intelligence updates at a
specific interval…* to *0*.
.. Set *Check for Endpoint Protection security intelligence updates
daily at…* to the time when updates should be checked. 3
. To check and download updates on a continual interval, Set *Check for
Endpoint Protection security intelligence updates at a specific
interval…* to the number of hours that should occur between updates.
. link:/sccm/protect/deploy-use/endpoint-antimalware-policies#deploy-an-antimalware-policy-to-client-computers[Deploy
the updated policy as usual].

=== Use Group Policy to schedule protection updates

____
[!IMPORTANT] By default, ``SignatureScheduleDay'' is set as ``8'' and
``SignatureUpdateInterval'' is set as ``0'' so Microsoft Defender
Antivirus will not schedule protection updates. Enabling these settings
will override that default.
____

[arabic]
. On your Group Policy management machine, open the
link:/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc731212(v=ws.11)[Group
Policy Management Console], right-click the Group Policy Object you want
to configure and click *Edit*.
. In the *Group Policy Management Editor* go to *Computer
configuration*.
. Click *Policies* then *Administrative templates*.
. Expand the tree to *Windows components* > *Microsoft Defender
Antivirus* > *Security Intelligence Updates* and configure the following
settings:
[arabic]
.. Double-click the *Specify the day of the week to check for security
intelligence updates* setting and set the option to *Enabled*. Enter the
day of the week to check for updates. Click *OK*.
.. Double-click the *Specify the interval to check for security
intelligence updates* setting and set the option to *Enabled*. Enter the
number of hours between updates. Click *OK*.
.. Double-click the *Specify the time to check for security intelligence
updates* setting and set the option to *Enabled*. Enter the time when
updates should be checked. The time is based on the local time of the
endpoint. Click *OK*.

=== Use PowerShell cmdlets to schedule protection updates

Use the following cmdlets:

[source,powershell]
----
Set-MpPreference -SignatureScheduleDay
Set-MpPreference -SignatureScheduleTime
Set-MpPreference -SignatureUpdateInterval
----

See link:use-powershell-cmdlets-microsoft-defender-antivirus.md[Use
PowerShell cmdlets to configure and run Microsoft Defender Antivirus]
and link:/powershell/module/defender/[Defender Antivirus cmdlets] for
more information on how to use PowerShell with Microsoft Defender
Antivirus.

=== Use Windows Management Instruction (WMI) to schedule protection updates

Use the
link:/previous-versions/windows/desktop/legacy/dn455323(v=vs.85)[*Set*
method of the *MSFT_MpPreference*] class for the following properties:

[source,wmi]
----
SignatureScheduleDay
SignatureScheduleTime
SignatureUpdateInterval
----

See the following for more information and allowed parameters:

* link:/previous-versions/windows/desktop/defender/windows-defender-wmiv2-apis-portal[Windows
Defender WMIv2 APIs]

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features] - link:android-configure.md[Configure Defender for
Endpoint on Android features] - link:linux-preferences.md[Set
preferences for Microsoft Defender for Endpoint on Linux] -
link:microsoft-defender-endpoint-linux.md[Microsoft Defender for
Endpoint on Linux]
____

=== Related articles

* link:deploy-manage-report-microsoft-defender-antivirus.md[Deploy
Microsoft Defender Antivirus]
* link:manage-updates-baselines-microsoft-defender-antivirus.md[Manage
Microsoft Defender Antivirus updates and apply baselines]
* link:manage-outdated-endpoints-microsoft-defender-antivirus.md[Manage
updates for endpoints that are out of date]
* link:manage-event-based-updates-microsoft-defender-antivirus.md[Manage
event-based forced updates]
* link:manage-updates-mobile-devices-vms-microsoft-defender-antivirus.md[Manage
updates for mobile devices and virtual machines (VMs)]
* link:microsoft-defender-antivirus-in-windows-10.md[Microsoft Defender
Antivirus in Windows 10 and 11]
