= 
denisebmsft
:keywords: malware, defender, antivirus, tamper protection

== Manage tamper protection on an individual device

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 2]
* Microsoft Defender Antivirus

*Platforms* - Windows

____
[!NOTE] Tamper protection blocks attempts to modify Microsoft Defender
Antivirus settings through the registry. To help ensure that tamper
protection doesn’t interfere with non-Microsoft security products or
enterprise installation scripts that modify these settings, go to
*Windows Security* and update *Security intelligence* to version
1.287.60.0 or later. (See
https://www.microsoft.com/wdsi/definitions[Security intelligence
updates].) After you’ve made this update, tamper protection continues to
protect your registry settings, and logs attempts to modify them without
returning errors.
____

If you’re a home user, or you aren’t subject to settings managed by a
security team, you can use the Windows Security app to manage tamper
protection. You must have appropriate admin permissions on your device
to do change security settings, such as tamper protection.

Here’s what you see in the Windows Security app:

:::image type=``content'' source=``images/tamperprotectionturnedon.png''
alt-text=``Turn tamper protection turned on in Windows 10 Home''
lightbox=``images/tamperprotectionturnedon.png'':::

[arabic]
. Select *Start*, and start typing _Security_. In the search results,
select *Windows Security*.
. Select *Virus & threat protection* > *Virus & threat protection
settings*.
. Set *Tamper Protection* to *On* or *Off*.

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____
