= 
denisebmsft
:keywords: post-migration, manage, operations, maintenance, utilization,
intune, Microsoft Defender for Endpoint, edr

== Manage Microsoft Defender for Endpoint with Intune

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

We recommend using link:/mem[Microsoft Endpoint Manager], which includes
Microsoft Intune (Intune) to manage your organization’s threat
protection features for devices (also referred to as endpoints).
link:/mem/endpoint-manager-overview[Learn more about Endpoint Manager].

This article describes how to find your Microsoft Defender for Endpoint
settings in Intune, and lists various tasks you can perform.

=== Find your Microsoft Defender for Endpoint settings in Intune

____
[!IMPORTANT] You must have either the global administrator or service
administrator role assigned in Intune to configure the settings
described in this article. To learn more, see
*link:/mem/intune/fundamentals/users-add#types-of-administrators[Types
of administrators (Intune)]*.
____

[arabic]
. Go to the Azure portal (https://portal.azure.com) and sign in.
. Under *Azure Services*, choose *Intune*.
. In the navigation pane on the left, choose *Device configuration*, and
then, under *Manage*, choose *Profiles*.
. Select an existing profile, or create a new one.

____
[!TIP] Need help? See
*link:/mem/intune/protect/advanced-threat-protection#example-of-using-microsoft-defender-atp-with-intune[Using
Microsoft Defender for Endpoint with Intune]*.
____

=== Configure Microsoft Defender for Endpoint with Intune

The following table lists various tasks you can perform to configure
Microsoft Defender for Endpoint with Intune. You don’t have to configure
everything all at once; choose a task, read the corresponding resources,
and then proceed.

[width="100%",cols="50%,50%",options="header",]
|===
|Task |Resources to learn more
|*Manage your organization’s devices using Intune* to protect those
devices and data stored on them
|link:/mem/intune/protect/device-protect[Protect devices with Microsoft
Intune]

|*Integrate Microsoft Defender for Endpoint with Intune* as a Mobile
Threat Defense solution _(for Android devices and devices running
Windows 10 or Windows 11)_
|link:/mem/intune/protect/advanced-threat-protection[Enforce compliance
for Microsoft Defender for Endpoint with Conditional Access in Intune]

|*Use Conditional Access* to control the devices and apps that can
connect to your email and company resources
|link:/microsoft-365/security/defender-endpoint/configure-conditional-access[Configure
Conditional Access in Microsoft Defender for Endpoint]

|*Configure Microsoft Defender Antivirus settings* using the Policy
configuration service provider
(link:/windows/client-management/mdm/policy-configuration-service-provider[Policy
CSP])
|link:/mem/intune/configuration/device-restrictions-windows-10#microsoft-defender-antivirus[Device
restrictions: Microsoft Defender Antivirus]
link:/windows/client-management/mdm/policy-csp-defender[Policy CSP -
Microsoft Defender for Endpoint]

|*If necessary, specify exclusions for Microsoft Defender Antivirus*
_Generally, you shouldn’t need to apply exclusions. Microsoft Defender
Antivirus includes a number of automatic exclusions based on known
operating system behaviors and typical management files, such as those
used in enterprise management, database management, and other enterprise
scenarios._
|https://support.microsoft.com/help/822158/virus-scanning-recommendations-for-enterprise-computers[Virus
scanning recommendations for Enterprise computers that are running
currently supported versions of Windows]
link:/mem/intune/configuration/device-restrictions-windows-10#microsoft-defender-antivirus-exclusions[Device
restrictions: Microsoft Defender Antivirus Exclusions for Windows 10 and
Windows 11 devices]
link:/windows/security/threat-protection/microsoft-defender-antivirus/configure-server-exclusions-microsoft-defender-antivirus[Configure
Microsoft Defender Antivirus exclusions on Windows Server 2016 or 2019
or 2022]

|*Configure your attack surface reduction rules* to target software
behaviors that are often abused by attackers _Configure your attack
surface reduction rules in
link:/microsoft-365/security/defender-endpoint/audit-windows-defender[audit
mode] at first (for at least one week and up to two months). You can
monitor status using Power BI
(https://github.com/microsoft/MDATP-PowerBI-Templates/tree/master/Attack%20Surface%20Reduction%20rules[get
our template]), and then set those rules to active mode when you’re
ready._
|link:/microsoft-365/security/defender-endpoint/audit-windows-defender[Audit
mode in Microsoft Defender for Endpoint]
link:/mem/intune/protect/endpoint-protection-windows-10?toc=/intune/configuration/toc.json&bc=/intune/configuration/breadcrumb/toc.json#attack-surface-reduction[Endpoint
protection: Attack Surface Reduction]
link:/microsoft-365/security/defender-endpoint/attack-surface-reduction[Learn
more about attack surface reduction rules]
https://techcommunity.microsoft.com/t5/microsoft-defender-atp/demystifying-attack-surface-reduction-rules-part-1/ba-p/1306420[Tech
Community blog post: Demystifying attack surface reduction rules - Part
1]

|*Configure your network filtering* to block outbound connections from
any app to IP addresses or domains with low reputations _Network
filtering is also referred to as
link:/microsoft-365/security/defender-endpoint/network-protection[network
protection]._ _Make sure that Windows 10 and Windows 11 devices have the
latest
https://support.microsoft.com/help/4052623/update-for-microsoft-defender-antimalware-platform[antimalware
platform updates] installed._
|link:/mem/intune/protect/endpoint-protection-windows-10#network-filtering[Endpoint
protection: Network filtering]
link:/microsoft-365/security/defender-endpoint/evaluate-network-protection#review-network-protection-events-in-windows-event-viewer[Review
network protection events in Windows Event Viewer]

|*Configure controlled folder access* to protect against ransomware
_link:/microsoft-365/security/defender-endpoint/controlled-folders[Controlled
folder access] is also referred to as antiransomware protection._
|link:/mem/intune/protect/endpoint-protection-windows-10#controlled-folder-access[Endpoint
protection: Controlled folder access]
link:/microsoft-365/security/defender-endpoint/enable-controlled-folders#intune[Enable
controlled folder access in Intune]

|*Configure exploit protection* to protect your organization’s devices
from malware that uses exploits to spread and infect other devices
_link:/microsoft-365/security/defender-endpoint/exploit-protection[Exploit
protection] is also referred to as Exploit Guard._
|link:/mem/intune/protect/endpoint-protection-windows-10#microsoft-defender-exploit-guard[Endpoint
protection: Microsoft Defender Exploit Guard]
link:/microsoft-365/security/defender-endpoint/enable-exploit-protection#intune[Enable
exploit protection in Intune]

|*Configure Microsoft Defender SmartScreen* to protect against malicious
sites and files on the internet. _Microsoft Edge should be installed on
your organization’s devices. For protection on Google Chrome and FireFox
browsers, configure exploit protection._
|link:/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview[Microsoft
Defender SmartScreen]
link:/mem/intune/configuration/device-restrictions-windows-10#microsoft-defender-smartscreen[Device
restrictions: Microsoft Defender SmartScreen]
link:/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-available-settings#mdm-settings[Policy
settings for managing SmartScreen in Intune]

|*Configure Microsoft Defender Firewall* to block unauthorized network
traffic flowing into or out of your organization’s devices
|link:/mem/intune/protect/endpoint-protection-windows-10#microsoft-defender-firewall[Endpoint
protection: Microsoft Defender Firewall]
link:/windows/security/threat-protection/windows-firewall/windows-firewall-with-advanced-security[Microsoft
Defender Firewall with Advanced Security]

|*Configure encryption and BitLocker* to protect information on your
organization’s devices running Windows
|link:/mem/intune/protect/endpoint-protection-windows-10#windows-encryption[Endpoint
protection: Windows Encryption]
link:/windows/security/information-protection/bitlocker/bitlocker-overview[BitLocker
for Windows 10 and Windows 11 devices]

|*Configure Microsoft Defender Credential Guard* to protect against
credential theft attacks |For Windows 10, Windows 11, Windows Server
2016, and Windows Server 2019, and Windows Server 2022, see
link:/mem/intune/protect/endpoint-protection-windows-10#microsoft-defender-credential-guard[Endpoint
protection: Microsoft Defender Credential Guard] For Windows 7 SP1,
Windows Server 2008 R2 SP1, Windows 8.1, and Windows Server 2012 R2, see
https://www.microsoft.com/download/details.aspx?id=36036[Mitigating
Pass-the-Hash (PtH) Attacks and Other Credential Theft&#44; Versions 1 and
2]

|*Configure Microsoft Defender Application Control* to choose whether to
audit or trust apps on your organization’s devices _Microsoft Defender
Application Control is also referred to as
link:/windows/security/threat-protection/windows-defender-application-control/applocker/applocker-overview[AppLocker]._
|link:/windows/security/threat-protection/windows-defender-application-control/deploy-windows-defender-application-control-policies-using-intune[Deploy
Microsoft Defender Application Control policies by using Microsoft
Intune]
link:/mem/intune/protect/endpoint-protection-windows-10#microsoft-defender-application-control[Endpoint
protection: Microsoft Defender Application Control]
link:/windows/client-management/mdm/applocker-csp[AppLocker CSP]

|*Configure device control and USB peripherals access* to help prevent
threats in unauthorized peripherals from compromising your devices
|link:/windows/security/threat-protection/device-control/control-usb-devices-using-intune[Control
USB devices and other removable media using Microsoft Defender for
Endpoint and Intune]
|===

=== Configure your Microsoft 365 Defender portal

If you haven’t already done so, configure your Microsoft 365 Defender
portal to view alerts, configure threat protection features, and view
detailed information about your organization’s overall security posture.
See
link:/microsoft-365/security/defender/microsoft-365-defender[Microsoft
365 Defender]. You can also configure whether and what features end
users can see in the Microsoft 365 Defender portal.

* link:/microsoft-365/security/defender-endpoint/use[Overview of
Microsoft 365 Defender]
* link:/mem/intune/protect/endpoint-protection-windows-10#microsoft-defender-security-center[Endpoint
protection: Microsoft 365 Defender]

=== Next steps

* link:/microsoft-365/security/defender-endpoint/next-gen-threat-and-vuln-mgt[Get
an overview of Defender Vulnerability Management]
