'''

title: Manage Microsoft Defender for Endpoint after initial setup or migration description: Now that you've made the switch to Microsoft Defender for Endpoint, your next step is to manage your threat protection features keywords: post-migration, manage, operations, maintenance, utilization, Microsoft Defender for Endpoint, edr ms.service: microsoft-365-security ms.subservice: mde ms.mktglfcycl: deploy ms.sitesec: library ms.pagetype: security ms.author: deniseb author: denisebmsft ms.localizationpriority: medium manager: dansimp audience: ITPro ms.collection:

* M365-security-compliance

ms.topic: conceptual ms.date: 07/01/2022 ms.reviewer: chventou search.appverid: met150 --

== Manage Microsoft Defender for Endpoint after initial setup or migration

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign up for a free trial.]
____

After you have set up and configured Microsoft Defender for Endpoint, your next step is to manage your features and capabilities.
We recommend using link:/mem/endpoint-manager-overview[Microsoft Endpoint Manager], which includes link:/mem/intune/fundamentals/what-is-intune[Microsoft Intune] and link:/mem/configmgr/core/understand/introduction[Microsoft Endpoint Configuration Manager], to manage your organization's devices and security settings.
However, you can use other tools/methods, such as link:/azure/active-directory-domain-services/manage-group-policy[Group Policy Objects in Azure Active Directory Domain Services].

The following table lists various tools/methods you can use, with links to learn more.

|===
| Tool/Method | Description

| *link:/windows/security/threat-protection/microsoft-defender-atp/tvm-dashboard-insights[Microsoft Defender Vulnerability Management dashboard insights]* in the https://security.microsoft.com/[Microsoft 365 Defender] portal
| The Defender Vulnerability Management dashboard provides actionable information that your security operations team can use to reduce exposure and improve your organization's security posture.
+  + See link:/microsoft-365/security/defender-endpoint/next-gen-threat-and-vuln-mgt[Defender Vulnerability Management] and link:/microsoft-365/security/defender-endpoint/use[Overview of Microsoft 365 Defender].

| *link:/mem/intune/fundamentals/what-is-intune[Microsoft Intune]*  (recommended)
| Microsoft Intune (Intune), a component of link:/mem/endpoint-manager-overview[Microsoft Endpoint Manager], focuses on mobile device management (MDM) and mobile application management (MAM).
With Intune, you control how your organization's devices are used, including mobile phones, tablets, and laptops.
You can also configure specific policies to control applications.
+  + See xref:manage-mde-post-migration-intune.adoc[Manage Microsoft Defender for Endpoint using Intune].

| *link:/mem/configmgr/core/understand/introduction[Microsoft Endpoint Configuration Manager]*
| Microsoft Endpoint Manager (Configuration Manager), formerly known as System Center Configuration Manager, is a component of link:/mem/endpoint-manager-overview[Microsoft Endpoint Manager].
Configuration Manager is a powerful tool to manage your users, devices, and software.
+  + See xref:manage-mde-post-migration-configuration-manager.adoc[Manage Microsoft Defender for Endpoint with Configuration Manager].

| *link:/azure/active-directory-domain-services/manage-group-policy[Group Policy Objects in Azure Active Directory Domain Services]*
| link:/azure/active-directory-domain-services/overview[Azure Active Directory Domain Services] includes built-in Group Policy Objects for users and devices.
You can customize the built-in Group Policy Objects as needed for your environment, as well as create custom Group Policy Objects and organizational units (OUs).
+  + See xref:manage-mde-post-migration-group-policy-objects.adoc[Manage Microsoft Defender for Endpoint with Group Policy Objects].

| *xref:manage-mde-post-migration-other-tools.adoc[PowerShell, WMI, and MPCmdRun.exe]*
| _We recommend using Microsoft Endpoint Manager (which includes Intune and Configuration Manager) to manage threat protection features on your organization's devices.
However, you can configure some settings, such as Microsoft Defender Antivirus settings on individual devices (endpoints) with PowerShell, WMI, or the MPCmdRun.exe tool._ +  + You can use PowerShell to manage Microsoft Defender Antivirus, exploit protection, and your attack surface reduction rules.
See link:manage-mde-post-migration-other-tools.md#configure-microsoft-defender-for-endpoint-with-powershell[Configure Microsoft Defender for Endpoint with PowerShell].
+  + You can use Windows Management Instrumentation (WMI) to manage Microsoft Defender Antivirus and exclusions.
See link:manage-mde-post-migration-other-tools.md#configure-microsoft-defender-for-endpoint-with-windows-management-instrumentation-wmi[Configure Microsoft Defender for Endpoint with WMI].
+  + You can use the Microsoft Malware Protection Command-Line Utility (MPCmdRun.exe) to manage Microsoft Defender Antivirus and exclusions, as well as validate connections between your network and the cloud.
See link:manage-mde-post-migration-other-tools.md#configure-microsoft-defender-for-endpoint-with-microsoft-malware-protection-command-line-utility-mpcmdrunexe[Configure Microsoft Defender for Endpoint with MPCmdRun.exe].
|===

=== See also

* xref:defender-endpoint-false-positives-negatives.adoc[Address false positives/negatives in Microsoft Defender for Endpoint]
