= Manage automation file uploads
:audience: ITPro
:author: mjcaparas
:description: Enable content analysis and configure the file extension and email attachment extensions that will be submitted for analysis
:keywords: automation, file, uploads, content, analysis, file, extension, email, attachment
:manager: dansimp
:ms.author: macapara
:ms.collection: M365-security-compliance
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Manage automation file uploads

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-automationefileuploads-abovefoldlink[Sign up for a free trial.]
____

Enable the content analysis capability so that certain files and email attachments can automatically be uploaded to the cloud for additional inspection in Automated investigation.

Identify the files and email attachments by specifying the file extension names and email attachment extension names.

For example, if you add _exe_ and _bat_ as file or attachment extension names, then all files or attachments with those extensions will automatically be sent to the cloud for additional inspection during Automated investigation.

=== Add file extension names and attachment extension names.

. In the navigation pane, select *Settings* > *Endpoints* > *Rules* > *Automation uploads*.
. Toggle the content analysis setting between *On* and *Off*.
. Configure the following extension names and separate extension names with a comma:
 ** *File extension names* - Suspicious files except email attachments will be submitted for additional inspection

=== Related topics

* xref:manage-automation-folder-exclusions.adoc[Manage automation folder exclusions]
