= Schedule Microsoft Defender Antivirus protection updates
:author: denisebmsft
:description: Schedule the day, time, and interval for when protection updates should be downloaded
:keywords: updates, security baselines, schedule updates
:manager: dansimp
:ms.author: deniseb
:ms.collection: m365-security-compliance
:ms.custom: nextgen
:ms.localizationpriority: medium
:ms.mktglfcycl: manage
:ms.pagetype: security
:ms.reviewer: pahuijbr
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Manage the schedule for when protection updates should be downloaded and applied

____
[!IMPORTANT] Customers who applied the March 2022 Microsoft Defender engine update (*1.1.19100.5*) might have encountered high resource utilization (CPU and/or memory).
Microsoft has released an update (*1.1.19200.5*) that resolves the bugs introduced in the earlier version.
Customers are recommended to update to this new engine build of Antivirus Engine (*1.1.19200.5*).
To ensure any performance issues are fully fixed, it is recommended to reboot machines after applying update.
For more information, see link:manage-updates-baselines-microsoft-defender-antivirus.md#monthly-platform-and-engine-versions[Monthly platform and engine versions].
____

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* Microsoft Defender Antivirus

*Platforms*

* Windows

Microsoft Defender Antivirus lets you determine when it should look for and download updates.

You can schedule updates for your endpoints by:

* Specifying the day of the week to check for protection updates
* Specifying the interval to check for protection updates
* Specifying the time to check for protection updates

You can also randomize the times when each endpoint checks and downloads protection updates.
See the xref:scheduled-catch-up-scans-microsoft-defender-antivirus.adoc[Schedule scans] topic for more information.

=== Use Configuration Manager to schedule protection updates

. On your Microsoft Endpoint Manager console, open the antimalware policy you want to change (click *Assets and Compliance* in the navigation pane on the left, then expand the tree to *Overview* > *Endpoint Protection* > *Antimalware Policies*)
. Go to the *Security intelligence updates* section.
. To check and download updates at a certain time:
 .. Set *Check for Endpoint Protection security intelligence updates at a specific interval...* to *0*.
 .. Set *Check for Endpoint Protection security intelligence updates daily at...* to the time when updates should be checked.
3
. To check and download updates on a continual interval, Set *Check for Endpoint Protection security intelligence updates at a specific interval...* to the number of hours that should occur between updates.
. link:/sccm/protect/deploy-use/endpoint-antimalware-policies#deploy-an-antimalware-policy-to-client-computers[Deploy the updated policy as usual].

=== Use Group Policy to schedule protection updates

____
[!IMPORTANT] By default, "SignatureScheduleDay" is set as "8" and "SignatureUpdateInterval" is set as "0" so Microsoft Defender Antivirus will not schedule protection updates.
Enabling these settings will override that default.
____

. On your Group Policy management machine, open the link:/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc731212(v=ws.11)[Group Policy Management Console], right-click the Group Policy Object you want to configure and click *Edit*.
. In the *Group Policy Management Editor* go to *Computer configuration*.
. Click *Policies* then *Administrative templates*.
. Expand the tree to *Windows components* > *Microsoft Defender Antivirus* > *Signature Updates* and configure the following settings:
 .. Double-click the *Specify the day of the week to check for security intelligence updates* setting and set the option to *Enabled*.
Enter the day of the week to check for updates.
Click *OK*.
 .. Double-click the *Specify the interval to check for definition updates* setting and set the option to *Enabled*.
Enter the number of hours between updates.
Click *OK*.
 .. Double-click the *Specify the time to check for definition updates* setting and set the option to *Enabled*.
Enter the time when updates should be checked.
The time is based on the local time of the endpoint.
Click *OK*.

=== Use PowerShell cmdlets to schedule protection updates

Use the following cmdlets:

[,powershell]
----
Set-MpPreference -SignatureScheduleDay
Set-MpPreference -SignatureScheduleTime
Set-MpPreference -SignatureUpdateInterval
----

See xref:use-powershell-cmdlets-microsoft-defender-antivirus.adoc[Use PowerShell cmdlets to configure and run Microsoft Defender Antivirus]  and link:/powershell/module/defender/[Defender Antivirus cmdlets] for more information on how to use PowerShell with Microsoft Defender Antivirus.

=== Use Windows Management Instruction (WMI) to schedule protection updates

Use the link:/previous-versions/windows/desktop/legacy/dn455323(v=vs.85)[*Set* method of the *MSFT_MpPreference*] class for the following properties:

[,wmi]
----
SignatureScheduleDay
SignatureScheduleTime
SignatureUpdateInterval
----

See the following for more information and allowed parameters:

* link:/previous-versions/windows/desktop/defender/windows-defender-wmiv2-apis-portal[Windows Defender WMIv2 APIs]

____
[!TIP] If you're looking for Antivirus related information for other platforms, see:

* xref:mac-preferences.adoc[Set preferences for Microsoft Defender for Endpoint on macOS]
* xref:microsoft-defender-endpoint-mac.adoc[Microsoft Defender for Endpoint on Mac]
* link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS Antivirus policy settings for Microsoft Defender Antivirus for Intune]
* xref:ios-configure-features.adoc[Configure Microsoft Defender for Endpoint on iOS features]
* xref:android-configure.adoc[Configure Defender for Endpoint on Android features]
* xref:linux-preferences.adoc[Set preferences for Microsoft Defender for Endpoint on Linux]
* xref:microsoft-defender-endpoint-linux.adoc[Microsoft Defender for Endpoint on Linux]
____

=== Related articles

* xref:deploy-manage-report-microsoft-defender-antivirus.adoc[Deploy Microsoft Defender Antivirus]
* xref:manage-updates-baselines-microsoft-defender-antivirus.adoc[Manage Microsoft Defender Antivirus updates and apply baselines]
* xref:manage-outdated-endpoints-microsoft-defender-antivirus.adoc[Manage updates for endpoints that are out of date]
* xref:manage-event-based-updates-microsoft-defender-antivirus.adoc[Manage event-based forced updates]
* xref:manage-updates-mobile-devices-vms-microsoft-defender-antivirus.adoc[Manage updates for mobile devices and virtual machines (VMs)]
* xref:microsoft-defender-antivirus-in-windows-10.adoc[Microsoft Defender Antivirus in Windows 10 and 11]
