= 
dansimp
:keywords: microsoft, defender, Microsoft Defender for Endpoint, linux,
installation, deploy, uninstallation, puppet, ansible, linux, redhat,
ubuntu, debian, sles, suse, centos

== Microsoft Defender for Endpoint on Linux

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

This topic describes how to install, configure, update, and use
Microsoft Defender for Endpoint on Linux.

____
[!CAUTION] Running other third-party endpoint protection products
alongside Microsoft Defender for Endpoint on Linux is likely to lead to
performance problems and unpredictable side effects. If non-Microsoft
endpoint protection is an absolute requirement in your environment, you
can still safely take advantage of Defender for Endpoint on Linux EDR
functionality after configuring the antivirus functionality to run in
link:linux-preferences.md#enforcement-level-for-antivirus-engine[Passive
mode].
____

=== How to install Microsoft Defender for Endpoint on Linux

Microsoft Defender for Endpoint for Linux includes antimalware and
endpoint detection and response (EDR) capabilities.

==== Prerequisites

* Access to the Microsoft 365 Defender portal
* Linux distribution using the https://systemd.io/[systemd] system
manager
+
____
[!NOTE] Linux distribution using system manager, except for RHEL/CentOS
6.x support both SystemV and Upstart.
____
* Beginner-level experience in Linux and BASH scripting
* Administrative privileges on the device (in case of manual deployment)

____
[!NOTE] Microsoft Defender for Endpoint on Linux agent is independent
from
link:/azure/azure-monitor/agents/agents-overview#log-analytics-agent[OMS
agent]. Microsoft Defender for Endpoint relies on its own independent
telemetry pipeline.
____

==== Installation instructions

There are several methods and deployment tools that you can use to
install and configure Microsoft Defender for Endpoint on Linux.

In general you need to take the following steps:

* Ensure that you have a Microsoft Defender for Endpoint subscription.
* Deploy Microsoft Defender for Endpoint on Linux using one of the
following deployment methods:
** The command-line tool:
*** link:linux-install-manually.md[Manual deployment]
** Third-party management tools:
*** link:linux-install-with-puppet.md[Deploy using Puppet configuration
management tool]
*** link:linux-install-with-ansible.md[Deploy using Ansible
configuration management tool]
*** link:linux-deploy-defender-for-endpoint-with-chef.md[Deploy using
Chef configuration management tool]

If you experience any installation failures, refer to
link:linux-support-install.md[Troubleshooting installation failures in
Microsoft Defender for Endpoint on Linux].

____
[!NOTE] It is not supported to install Microsoft Defender for Endpoint
in any other location other than the default install path.
____

____
[!NOTE] Microsoft Defender for Endpoint on Linux creates an ``mdatp''
user with random UID and GID. If you want to control the UID and GID,
create an ``mdatp'' user prior to installation using the
``/usr/sbin/nologin'' shell option. For example:
`mdatp:x:UID:GID::/home/mdatp:/usr/sbin/nologin`.
____

==== System requirements

____
[!NOTE] Support of Red Hat Enterprise Linux and CentOS 6.7+ to 6.10+ are
in preview.
____

* Supported Linux server distributions and x64 (AMD64/EM64T) and x86_64
versions:
** Red Hat Enterprise Linux 6.7 or higher (Preview)
** Red Hat Enterprise Linux 7.2 or higher
** Red Hat Enterprise Linux 8.x
** Red Hat Enterprise Linux 9.x
** CentOS 6.7 or higher (Preview)
** CentOS 7.2 or higher
** Ubuntu 16.04 LTS or higher LTS
** Debian 9 or higher
** SUSE Linux Enterprise Server 12 or higher
** Oracle Linux 7.2 or higher
** Oracle Linux 8.x
** Amazon Linux 2
** Fedora 33 or higher
+
____
[!NOTE] Distributions and version that are not explicitly listed are
unsupported (even if they are derived from the officially supported
distributions).
____
* List of supported kernel versions > [!NOTE] > Microsoft Defender for
Endpoint on Red Hat Enterprise Linux and CentOS - 6.7 to 6.10 is a
Kernel based solution. You must verify that the kernel version is
supported before updating to a newer kernel version. See the list below
for the list of supported kernels. > Microsoft Defender for Endpoint for
all other supported distributions and versions is
kernel-version-agnostic. With a minimal requirement for the kernel
version to be at or above 3.10.0-327.
** The `fanotify` kernel option must be enabled
** Red Hat Enterprise Linux 6 and CentOS 6:
*** For 6.7: 2.6.32-573.*
*** For 6.8: 2.6.32-642.*
*** For 6.9: 2.6.32-696.* (except 2.6.32-696.el6.x86_64)
*** For 6.10: 2.6.32.754.2.1.el6.x86_64 to 2.6.32-754.48.1:
**** 2.6.32-754.10.1.el6.x86_64
**** 2.6.32-754.11.1.el6.x86_64
**** 2.6.32-754.12.1.el6.x86_64
**** 2.6.32-754.14.2.el6.x86_64
**** 2.6.32-754.15.3.el6.x86_64
**** 2.6.32-754.17.1.el6.x86_64
**** 2.6.32-754.18.2.el6.x86_64
**** 2.6.32-754.2.1.el6.x86_64
**** 2.6.32-754.22.1.el6.x86_64
**** 2.6.32-754.23.1.el6.x86_64
**** 2.6.32-754.24.2.el6.x86_64
**** 2.6.32-754.24.3.el6.x86_64
**** 2.6.32-754.25.1.el6.x86_64
**** 2.6.32-754.27.1.el6.x86_64
**** 2.6.32-754.28.1.el6.x86_64
**** 2.6.32-754.29.1.el6.x86_64
**** 2.6.32-754.29.2.el6.x86_64
**** 2.6.32-754.3.5.el6.x86_64
**** 2.6.32-754.30.2.el6.x86_64
**** 2.6.32-754.33.1.el6.x86_64
**** 2.6.32-754.35.1.el6.x86_64
**** 2.6.32-754.39.1.el6.x86_64
**** 2.6.32-754.41.2.el6.x86_64
**** 2.6.32-754.43.1.el6.x86_64
**** 2.6.32-754.47.1.el6.x86_64
**** 2.6.32-754.48.1.el6.x86_64
**** 2.6.32-754.6.3.el6.x86_64
**** 2.6.32-754.9.1.el6.x86_64

____
[!NOTE] After a new package version is released, support for the
previous two versions is reduced to technical support only. Versions
older than that which are listed in this section are provided for
technical upgrade support only.
____

____
[!CAUTION] Running Defender for Endpoint on Linux side by side with
other `fanotify`-based security solutions is not supported. It can lead
to unpredictable results, including hanging the operating system.
____

* Disk space: 2 GB
+
____
[!NOTE] An additional 2 GB disk space might be needed if cloud
diagnostics are enabled for crash collections.
____
* /opt/microsoft/mdatp/sbin/wdavdaemon requires executable permission.
For more information, see ``Ensure that the daemon has executable
permission'' in
link:/microsoft-365/security/defender-endpoint/linux-support-install[Troubleshoot
installation issues for Microsoft Defender for Endpoint on Linux].
* Cores: 2 minimum, 4 preferred
* Memory: 1 GB minimum, 4 preferred
+
____
[!NOTE] Please make sure that you have free disk space in /var.
____
* The solution currently provides real-time protection for the following
file system types:
** `btrfs`
** `ecryptfs`
** `ext2`
** `ext3`
** `ext4`
** `fuse`
** `fuseblk`
** `jfs`
** `nfs`
** `overlay`
** `ramfs`
** `reiserfs`
** `tmpfs`
** `udf`
** `vfat`
** `xfs`

After you’ve enabled the service, you may need to configure your network
or firewall to allow outbound connections between it and your endpoints.

* Audit framework (`auditd`) must be enabled.
+
____
[!NOTE] System events captured by rules added to `/etc/audit/rules.d/`
will add to `audit.log`(s) and might affect host auditing and upstream
collection. Events added by Microsoft Defender for Endpoint on Linux
will be tagged with `mdatp` key.
____

==== Configuring Exclusions

When adding exclusions to Microsoft Defender Antivirus, you should be
mindful of
link:/microsoft-365/security/defender-endpoint/common-exclusion-mistakes-microsoft-defender-antivirus[Common
Exclusion Mistakes for Microsoft Defender Antivirus]

==== Network connections

The following downloadable spreadsheet lists the services and their
associated URLs that your network must be able to connect to. You should
ensure that there are no firewall or network filtering rules that would
deny access to these URLs. If there are, you may need to create an
_allow_ rule specifically for them.

'''''

[width="100%",cols="50%,50%",options="header",]
|===
|Spreadsheet of domains list |Description
|Microsoft Defender for Endpoint URL list for commercial customers
|Spreadsheet of specific DNS records for service locations, geographic
locations, and OS for commercial customers.

|Microsoft Defender for Endpoint URL list for Gov/GCC/DoD |Spreadsheet
of specific DNS records for service locations, geographic locations, and
OS for Gov/GCC/DoD customers.
|===

____
[!NOTE] For a more specific URL list, see
link:/microsoft-365/security/defender-endpoint/configure-proxy-internet#enable-access-to-microsoft-defender-atp-service-urls-in-the-proxy-server[Configure
proxy and internet connectivity settings].
____

Defender for Endpoint can discover a proxy server by using the following
discovery methods:

* Transparent proxy
* Manual static proxy configuration

If a proxy or firewall is blocking anonymous traffic, make sure that
anonymous traffic is permitted in the previously listed URLs. For
transparent proxies, no additional configuration is needed for Defender
for Endpoint. For static proxy, follow the steps in
link:linux-static-proxy-configuration.md[Manual Static Proxy
Configuration].

____
[!WARNING] PAC, WPAD, and authenticated proxies are not supported.
Ensure that only a static proxy or transparent proxy is being used.

SSL inspection and intercepting proxies are also not supported for
security reasons. Configure an exception for SSL inspection and your
proxy server to directly pass through data from Defender for Endpoint on
Linux to the relevant URLs without interception. Adding your
interception certificate to the global store will not allow for
interception.
____

For troubleshooting steps, see
link:linux-support-connectivity.md[Troubleshoot cloud connectivity
issues for Microsoft Defender for Endpoint on Linux].

=== How to update Microsoft Defender for Endpoint on Linux

Microsoft regularly publishes software updates to improve performance,
security, and to deliver new features. To update Microsoft Defender for
Endpoint on Linux, refer to link:linux-updates.md[Deploy updates for
Microsoft Defender for Endpoint on Linux].

=== How to configure Microsoft Defender for Endpoint on Linux

Guidance for how to configure the product in enterprise environments is
available in link:linux-preferences.md[Set preferences for Microsoft
Defender for Endpoint on Linux].

=== Common Applications to Microsoft Defender for Endpoint can impact

High I/O workloads from certain applications can experience performance
issues when Microsoft Defender for Endpoint is installed. These include
applications for developer scenarios like Jenkins and Jira, and database
workloads like OracleDB and Postgres. If experiencing performance
degradation, consider setting exclusions for trusted applications,
keeping
link:/microsoft-365/security/defender-endpoint/common-exclusion-mistakes-microsoft-defender-antivirus[Common
Exclusion Mistakes for Microsoft Defender Antivirus] in mind. For
additional guidance, consider consulting documentation regarding
antivirus exclusions from third party applications.

=== Resources

* For more information about logging, uninstalling, or other topics, see
link:linux-resources.md[Resources].

=== Related articles

* link:/azure/defender-for-cloud/integration-defender-for-endpoint[Protect
your endpoints with Defender for Cloud’s integrated EDR solution:
Microsoft Defender for Endpoint]
* link:/azure/defender-for-cloud/quickstart-onboard-machines[Connect
your non-Azure machines to Microsoft Defender for Cloud]
* link:network-protection-linux.md[Turn on network protection for Linux]
