= 
mjcaparas
:keywords: minimum requirements, licensing, comparison table

== Minimum requirements for Microsoft Defender for Endpoint

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-minreqs-abovefoldlink[Sign
up for a free trial.]
____

There are some minimum requirements for onboarding devices to the
service. Learn about the licensing, hardware and software requirements,
and other configuration settings to onboard devices to the service.

____
{empty}[!TIP]

* This article describes the minimum requirements for Microsoft Defender
for Endpoint Plan 2. If you are looking for information about Defender
for Endpoint Plan 1, see
link:mde-p1-setup-configuration.md#review-the-requirements[Requirements
for Defender for Endpoint Plan 1].
* Learn about the latest enhancements in Defender for Endpoint:
https://techcommunity.microsoft.com/t5/Windows-Defender-Advanced-Threat/ct-p/WindowsDefenderAdvanced[Defender
for Endpoint Tech Community].
* Defender for Endpoint demonstrated industry-leading optics and
detection capabilities in the recent MITRE evaluation. Read:
https://cloudblogs.microsoft.com/microsoftsecure/2018/12/03/insights-from-the-mitre-attack-based-evaluation-of-windows-defender-atp/[Insights
from the MITRE ATT&CK-based evaluation].
____

=== Licensing requirements

The standalone versions of link:defender-endpoint-plan-1-2.md[Defender
for Endpoint Plan 1 and Plan 2], even when they are included as part of
other Microsoft 365 plans, do not include server licenses. To onboard
servers to those plans, you’ll need Defender for Servers Plan 1 or Plan
2 as part of the
link:/azure/defender-for-cloud/defender-for-cloud-introduction[Defender
for Cloud] offering. To learn more, see the overview of
link:/azure/defender-for-cloud/defender-for-servers-introduction[Microsoft
Defender for Servers].

For information licensing requirements for Microsoft Defender for
Endpoint, see
link:/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-defender-for-endpoint[Microsoft
Defender for Endpoint licensing information].

For detailed licensing information, see the
https://www.microsoft.com/licensing/terms/[Product Terms site] and work
with your account team to learn more about the terms and conditions.

For more information on the array of features in Windows editions, see
https://www.microsoft.com/windowsforbusiness/compare[Compare Windows
editions]. ## Browser requirements

Access to Defender for Endpoint is done through a browser, supporting
the following browsers:

* Microsoft Edge
* Google Chrome

____
[!NOTE] While other browsers might work, the mentioned browsers are the
ones supported.
____

=== Hardware and software requirements

==== Supported Windows versions

* Windows 11 Enterprise
* Windows 11 Education
* Windows 11 Pro
* Windows 11 Pro Education
* Windows 10 Enterprise
* link:/windows/whats-new/ltsc/[Windows 10 Enterprise LTSC 2016 (or
later)]
* Windows 10 Enterprise IoT
+
____
[!NOTE] While Windows 10 IoT Enterprise is a supported OS in Microsoft
Defender for Endpoint and enables OEMs/ODMs to distribute it as part of
their product or solution, customers should follow the OEM/ODM’s
guidance around host-based installed software and supportability.
____
* Windows 10 Education
* Windows 10 Pro
* Windows 10 Pro Education
* Windows 8.1 Enterprise
* Windows 8.1 Pro
* Windows 7 SP1 Enterprise
(link:/troubleshoot/windows-client/windows-7-eos-faq/windows-7-extended-security-updates-faq[Requires
ESU for support].)
* Windows 7 SP1 Pro
(link:/troubleshoot/windows-client/windows-7-eos-faq/windows-7-extended-security-updates-faq[Requires
ESU for support].)
* Windows server
** Windows Server 2008 R2 SP1
(link:/windows-server/get-started/extended-security-updates-deploy[Requires
ESU for support])
** Windows Server 2012 R2
** Windows Server 2016
** Windows Server, version 1803 or later
** Windows Server 2019 and later
** Windows Server 2019 core edition
** Windows Server 2022
* Windows Virtual Desktop
* Windows 365

Devices on your network must be running one of these editions.

The hardware requirements for Defender for Endpoint on devices are the
same for the supported editions.

____
Cores: 2 minimum, 4 preferred Memory: 1 GB minimum, 4 preferred
____

For more information on supported versions of Windows 10, see
link:/windows/release-health/release-information[Windows 10 release
information].

____
[!NOTE] - Endpoints running mobile versions of Windows (such as Windows
CE and Windows 10 Mobile) aren’t supported.

* Virtual Machines running Windows 10 Enterprise 2016 LTSB may encounter
performance issues if run on non-Microsoft virtualization platforms.
* For virtual environments, we recommend using Windows 10 Enterprise
LTSC 2019 or later.
* The standalone versions of link:defender-endpoint-plan-1-2.md[Defender
for Endpoint Plan 1 and Plan 2] do not include server licenses. To
onboard servers to those plans, you’ll need Defender for Servers Plan 1
or Plan 2 as part of the
link:/azure/defender-for-cloud/defender-for-cloud-introduction[Defender
for Cloud] offering. To learn more. see
link:/azure/defender-for-cloud/defender-for-servers-introduction[Overview
of Microsoft Defender for Servers].
____

When components are up-to-date on Microsoft Windows operating systems,
Microsoft Defender for Endpoint support will follow the respective
operating system’s lifecycle. For more information, see
link:/lifecycle/faq/general-lifecycle[Lifecycle FAQ]. New features or
capabilities are typically provided only on operating systems that have
not yet reached the end of their lifecycle. Security intelligence
updates (definition and engine updates) and detection logic will
continue to be provided until at least:

* The link:/lifecycle/products/[end of support date] (for operating
systems that do not have an Extended Security Updates (ESU) program).
* The link:/lifecycle/faq/extended-security-updates[end of ESU date]
(for operating systems that have an ESU program).

==== Other supported operating systems

* link:microsoft-defender-endpoint-android.md[Android]
* link:microsoft-defender-endpoint-ios.md[iOS]
* link:microsoft-defender-endpoint-linux.md[Linux]
* link:microsoft-defender-endpoint-mac.md[macOS]

____
[!NOTE] You’ll need to confirm the Linux distributions and versions of
Android, iOS, and macOS are compatible with Defender for Endpoint for
the integration to work.
____

==== Network and data storage and configuration requirements

When you run the onboarding wizard for the first time, you must choose
where your Microsoft Defender for Endpoint-related information is
stored: in the European Union, the United Kingdom, or the United States
datacenter.

____
{empty}[!NOTE]

* You cannot change your data storage location after the first-time
setup.
* Review the link:data-storage-privacy.md[Microsoft Defender for
Endpoint data storage and privacy] for more information on where and how
Microsoft stores your data.
____

===== Internet connectivity

Internet connectivity on devices is required either directly or through
proxy.

For more information on additional proxy configuration settings, see
link:configure-proxy-internet.md[Configure device proxy and Internet
connectivity settings].

=== Microsoft Defender Antivirus configuration requirement

The Defender for Endpoint agent depends on the ability of Microsoft
Defender Antivirus to scan files and provide information about them.

Configure Security intelligence updates on the Defender for Endpoint
devices whether Microsoft Defender Antivirus is the active antimalware
or not. For more information, see
link:/windows/security/threat-protection/microsoft-defender-antivirus/manage-updates-baselines-microsoft-defender-antivirus[Manage
Microsoft Defender Antivirus updates and apply baselines].

When Microsoft Defender Antivirus isn’t the active antimalware in your
organization and you use the Defender for Endpoint service, Microsoft
Defender Antivirus goes on passive mode.

If your organization has turned off Microsoft Defender Antivirus through
group policy or other methods, devices that are onboarded must be
excluded from this group policy.

If you’re onboarding servers and Microsoft Defender Antivirus isn’t the
active antimalware on your servers, Microsoft Defender Antivirus will
either need to be configured to go on passive mode or uninstalled. The
configuration is dependent on the server version. For more information,
see link:microsoft-defender-antivirus-compatibility.md[Microsoft
Defender Antivirus compatibility].

____
[!NOTE] Your regular group policy doesn’t apply to Tamper Protection,
and changes to Microsoft Defender Antivirus settings will be ignored
when Tamper Protection is on.
____

=== Microsoft Defender Antivirus Early Launch Antimalware (ELAM) driver is enabled

If you’re running Microsoft Defender Antivirus as the primary
antimalware product on your devices, the Defender for Endpoint agent
will successfully onboard.

If you’re running a third-party antimalware client and use Mobile Device
Management solutions or Microsoft Endpoint Manager (current branch),
you’ll need to ensure the Microsoft Defender Antivirus ELAM driver is
enabled. For more information, see
link:troubleshoot-onboarding.md#ensure-that-microsoft-defender-antivirus-is-not-disabled-by-a-policy[Ensure
that Microsoft Defender Antivirus is not disabled by policy].

=== Related topics

* link:production-deployment.md[Set up Microsoft Defender for Endpoint
deployment]
* link:onboard-configure.md[Onboard devices]
