= 
mjcaparas
:keywords: mssp, integration, managed, security, service, provider

== Managed security service provider partnership opportunities

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-mssp-support-abovefoldlink[Sign
up for a free trial.]
____

Security is recognized as a key component in running an enterprise,
however some organizations might not have the capacity or expertise to
have a dedicated security operations team to manage the security of
their endpoints and network, others may want to have a second set of
eyes to review alerts in their network.

To address this demand, managed security service providers (MSSP) offer
to deliver managed detection and response (MDR) services on top of
Defender for Endpoint.

Defender for Endpoint adds partnership opportunities for this scenario
and allows MSSPs to take the following actions:

* Get access to MSSP customer’s Microsoft 365 Defender portal
* Get email notifications, and
* Fetch alerts through security information and event management (SIEM)
tools

=== Related topic

* link:configure-mssp-support.md[Configure managed security service
provider integration]
