= 
denisebmsft
:keywords: Microsoft Defender Antivirus, windows defender, antimalware,
virus, malware, threat, detection, protection, security

== Next-generation protection overview

*Applies to*

* Microsoft Defender Antivirus
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 2]
* link:../defender-business/index.yml[Microsoft Defender for Business]

*Platforms* - Windows

Microsoft Defender for Endpoint includes next-generation protection to
reinforce the security perimeter of your network. Next-generation
protection was designed to catch all types of emerging threats. In
addition to Microsoft Defender Antivirus, your next-generation
protection services include the following capabilities:

* link:configure-protection-features-microsoft-defender-antivirus.md[Behavior-based&#44;
heuristic&#44; and real-time antivirus protection], which includes always-on
scanning using file and process behavior monitoring and other heuristics
(also known as _real-time protection_). It also includes detecting and
blocking apps that are deemed unsafe, but might not be detected as
malware.
* link:cloud-protection-microsoft-defender-antivirus.md[Cloud-delivered
protection], which includes near-instant detection and blocking of new
and emerging threats.
* link:manage-updates-baselines-microsoft-defender-antivirus.md[Dedicated
protection and product updates], which includes updates related to
keeping Microsoft Defender Antivirus up to date.

____
[!TIP] Next-generation protection is included in both Microsoft Defender
for Endpoint Plan 1 and Plan 2. link:defender-endpoint-plan-1-2.md[Learn
more about Defender for Endpoint Plan 1 and Plan 2] Next-generation
protection is also included in Microsoft Defender for Business and
Microsoft 365 Business Premium.
link:../defender-business/compare-mdb-m365-plans.md[Compare security
features in Microsoft 365 plans for small and medium-sized businesses].
____

=== Configure next-generation protection services

For information on how to configure next-generation protection services,
see link:configure-microsoft-defender-antivirus-features.md[Configure
Microsoft Defender Antivirus features].

____
[!NOTE] Configuration and management is largely the same in Windows
Server as in Windows clients. However, there are some differences.
____

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____

____
[!TIP] *Performance tip* Due to a variety of factors (examples listed
below) Microsoft Defender Antivirus, like other antivirus software, can
cause performance issues on endpoint devices. In some cases, you might
need to tune the performance of Microsoft Defender Antivirus to
alleviate those performance issues. Microsoft’s *Performance analyzer*
is a PowerShell command-line tool that helps determine which files, file
paths, processes, and file extensions might be causing performance
issues; some examples are:

* Top paths that impact scan time
* Top files that impact scan time
* Top processes that impact scan time
* Top file extensions that impact scan time
* Combinations – for example:
** top files per extension
** top paths per extension
** top processes per path
** top scans per file
** top scans per file per process

You can use the information gathered using Performance analyzer to
better assess performance issues and apply remediation actions. See:
link:tune-performance-defender-antivirus.md[Performance analyzer for
Microsoft Defender Antivirus].
____
