= 
siosulli
:keywords: offboarding, Microsoft Defender for Endpoint offboarding,
offboarding

== Offboard devices from the Microsoft Defender for Endpoint service

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

*Platforms* - macOS - Linux - Windows Server 2012 R2 - Windows Server
2016

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-offboarddevices-abovefoldlink[Sign
up for a free trial.]
____

Follow the corresponding instructions depending on your preferred
deployment method.

____
[!NOTE] The status of a device will be switched to
link:fix-unhealthy-sensors.md#inactive-devices[Inactive] 7 days after
offboarding.

Offboarded devices’ data (such as Timeline, Alerts, Vulnerabilities,
etc.) will remain in the portal until the configured
link:data-storage-privacy.md#how-long-will-microsoft-store-my-data-what-is-microsofts-data-retention-policy[retention
period] expires.

The device’s profile (without data) will remain in the
link:machines-view-overview.md[Devices List] for no longer than 180
days.

In addition, devices that are not active in the last 30 days are not
factored in on the data that reflects your organization’s Defender
Vulnerability Management link:tvm-exposure-score.md[exposure score] and
Microsoft Secure Score for Devices.

To view only active devices, you can filter by
link:machines-view-overview.md#use-filters-to-customize-the-device-inventory-views[sensor
health state], link:machine-tags.md[device tags] or
link:machine-groups.md[machine groups].
____

=== Offboard Windows devices

* link:configure-endpoints-script.md#offboard-devices-using-a-local-script[Offboard
devices using a local script]
* link:configure-endpoints-gp.md#offboard-devices-using-group-policy[Offboard
devices using Group Policy]
* link:configure-endpoints-mdm.md#offboard-devices-using-mobile-device-management-tools[Offboard
devices using Mobile Device Management tools]

=== Offboard Servers

* link:configure-server-endpoints.md#offboard-windows-servers[Offboard
servers]

=== Offboard non-Windows devices

* link:configure-endpoints-non-windows.md#offboard-non-windows-devices[Offboard
non-Windows devices]
