= 
mjcaparas
:keywords: apis, graph api, supported apis, collect investigation
package

== Offboard machine API

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Offboard device from Defender for Endpoint.

=== Limitations

* Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.
+
{empty}[!includelink:../../includes/machineactionsnote.md[Machine
actions note]]

____
[!NOTE] This API is supported on Windows 11, Windows 10, version 1703
and later; on Windows Server 2019 and later; and on Windows Server 2012
R2 and Windows Server 2016 when using the
link:update-agent-mma-windows.md#upgrade-to-the-new-unified-agent-for-defender-for-endpoint[new&#44;
unified agent for Defender for Endpoint]. This API is not supported on
macOS or Linux devices.
____

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Defender for Endpoint APIs]

[cols=",,",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Machine.Offboard |`Offboard machine'

|Delegated (work or school account) |Machine.Offboard |`Offboard
machine'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to `Global Admin' AD role
* The user needs to have access to the device, based on device group
settings (See link:machine-groups.md[Create and manage device groups]
for more information)

Device group creation is supported in Defender for Endpoint Plan 1 and
Plan 2.
____

=== HTTP request

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/machines/{id}/offboard
----

The machine ID can be found in the URL when you select the device.
Generally, it is a 40 digit alphanumeric number that can be found in the
URL.

=== Request headers

[cols=",,",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|Content-Type |string |application/json. *Required*.
|===

=== Request body

In the request body, supply a JSON object with the following parameters:

[cols=",,",options="header",]
|===
|Parameter |Type |Description
|Comment |String |Comment to associate with the action. *Required*.
|===

=== Response

If successful, this method returns 200 - Created response code and
link:machineaction.md[Machine Action] in the response body.

=== Example

==== Request

Here is an example of the request. If there is no JSON comment added, it
will error out with code *400*.

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/machines/1e5bc9d7e413ddd7902c2932e418702b84d0cc07/offboard
----

[source,json]
----
{
  "Comment": "Offboard machine by automation"
}
----
