= 
denisebmsft
:keywords: windows defender, antivirus, office 365, onedrive, restore,
ransomware

== Better together: Microsoft Defender Antivirus and Office 365

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] - Microsoft Defender Antivirus - Microsoft 365

*Platforms* - Windows

You might already know that:

* *Microsoft Defender Antivirus protects your Windows device from
software threats, such as viruses, malware, and spyware*. Microsoft
Defender Antivirus is your complete, ongoing protection, built into
Windows 10 and Windows 11, and ready to go.
link:./microsoft-defender-antivirus-in-windows-10.md[Microsoft Defender
Antivirus is your next-generation protection].
* *Office 365 includes antiphishing, antispam, and antimalware
protection*. With your Office 365 subscription, you get premium email
and calendars, Office apps, 1 TB of cloud storage (via OneDrive), and
advanced security across all your devices. This is true for home and
business users. And if you’re a business user, and your organization is
using Office 365 E5, you get even more protection through Microsoft
Defender for Office 365
link:/microsoft-365/security/office-365-security/protect-against-threats[Protect
against threats with Office 365].
* *OneDrive, included in Office 365, enables you to store your files and
folders online, and share them as you see fit*. You can work together
with people (for work or fun), and coauthor files that are stored in
OneDrive. You can also access your files across all your devices (your
PC, phone, and tablet). link:/OneDrive/manage-sharing[Manage sharing in
OneDrive].

*But did you know there are good security reasons to use Microsoft
Defender Antivirus together with Office 365*? Here are two:

[arabic]
. link:#ransomware-protection-and-recovery[You get ransomware protection
and recovery].
. link:#integration-means-better-protection[Integration means better
protection].

Read the following sections to learn more.

=== Ransomware protection and recovery

When you save your files to link:/onedrive[OneDrive], and
link:./microsoft-defender-antivirus-in-windows-10.md[Microsoft Defender
Antivirus] detects a ransomware threat on your device, the following
things occur:

[arabic]
. *You are told about the threat*. (If your organization is using
link:microsoft-defender-endpoint.md[Microsoft Defender for Endpoint],
your security operations team is notified, too.)
. *Microsoft Defender Antivirus helps you (and your organization’s
security team) remove the ransomware* from your device(s). (If your
organization is using Microsoft Defender for Endpoint, your security
operations team can determine whether other devices are infected and
take appropriate action, too.)
. *You get the option to recover your files in OneDrive*. With the
OneDrive Files Restore feature, you can recover your files in OneDrive
to the state they were in before the ransomware attack occurred. See
https://support.office.com/article/0d90ec50-6bfd-40f4-acc7-b8c12c73637f[Ransomware
detection and recovering your files].

Think of the time and hassle this can save.

=== Integration means better protection

Microsoft Defender for Office 365 integrated with Microsoft Defender for
Endpoint means better protection for your organization. Here’s how:

* link:/microsoft-365/security/office-365-security/defender-for-office-365[Microsoft
Defender for Office 365] safeguards your organization against malicious
threats posed in email messages, email attachments, and links (URLs) in
Office documents.
+
AND
* link:microsoft-defender-endpoint.md[Microsoft Defender for Endpoint]
protects your devices from cyber threats, detects advanced attacks and
data breaches, automates security incidents, and improves your security
posture.
+
SO
* Once integration is enabled, your security operations team can see a
list of devices that are used by the recipients of any detected URLs or
email messages, along with recent alerts for those devices, in the
Microsoft 365 Defender portal.

If you haven’t already done so,
link:/microsoft-365/security/office-365-security/integrate-office-365-ti-with-mde[integrate
Microsoft Defender for Office 365 with Microsoft Defender for Endpoint].

=== More good reasons to use OneDrive

Protection from ransomware is one great reason to put your files in
OneDrive. And there are several more good reasons, summarized in this
video:

____
{empty}[!VIDEO
https://www.microsoft.com/videoplayer/embed/70b4d256-46fb-481f-ad9b-921ef5fd7bed]
____

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____

=== Want to learn more? See these resources:

* link:/onedrive[OneDrive]
* link:/microsoft-365/security/office-365-security/defender-for-office-365[Microsoft
Defender for Office 365]
* link:microsoft-defender-endpoint.md[Microsoft Defender for Endpoint]
