= 
siosulli
:keywords: onboard, servers, vm, on-premises, oms gateway, log
analytics, azure log analytics, mma

== Onboard devices without Internet access to Microsoft Defender for Endpoint

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

For devices with no direct internet connection, the use of a proxy
solution is the recommended approach. For older Windows devices
onboarded using the previous, MMA-based solution the use of the OMS
gateway solution provides an alternative approach. For more information
about onboarding methods, see the following articles: -
link:/microsoft-365/security/defender-endpoint/onboard-downlevel[Onboard
previous versions of Windows] -
link:++/microsoft-365/security/defender-endpoint/configure-server-endpoints#windows-server-2008-r2-sp1--windows-server-2012-r2-and-windows-server-2016++[Onboard
servers to the Microsoft Defender for Endpoint service]

____
[!IMPORTANT] - Windows or Windows Server in disconnected environments
must be able to update Certificate Trust Lists offline via an internal
file or web server. - For more information about updating CTLs offline,
see
link:/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn265983(v=ws.11)#configure-a-file-or-web-server-to-download-the-ctl-files[Configure
a file or web server to download the CTL files].
____

=== Devices running Windows 10 or later, Windows Server 2012 R2 or later, Linux and macOS

Depending on the operating system, the proxy to be used for Microsoft
Defender for Endpoint can be configured automatically, typically through
the use of autodiscovery or an autoconfig file, or statically specific
to Defender for Endpoint services running on the device.

* For Windows devices, please reference
link:/microsoft-365/security/defender-endpoint/configure-proxy-internet[Configure
device proxy and Internet connectivity settings]
* For Linux devices, please reference
link:/microsoft-365/security/defender-endpoint/linux-static-proxy-configuration[Configure
Microsoft Defender for Endpoint on Linux for static proxy discovery]
* For macOS devices, please reference
link:/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-mac#network-connections[Microsoft
Defender for Endpoint on Mac]

=== Windows devices running the previous MMA-based solution

____
[!NOTE] - An OMS gateway server cannot be used as proxy for disconnected
Windows or Windows Server devices when configured via
`TelemetryProxyServer' registry or GPO. - For Windows or Windows Server
- while you may use TelemetryProxyServer, it must point to a standard
proxy device or appliance.
____

* Set up Azure Log Analytics (formerly known as OMS Gateway) to act as
proxy or hub:
** link:/azure/azure-monitor/platform/gateway#download-the-log-analytics-gateway[Azure
Log Analytics Agent]
** link:onboard-downlevel.md#install-and-configure-microsoft-monitoring-agent-mma[Install
and configure Microsoft Monitoring Agent (MMA)] point to Defender for
Endpoint Workspace key & ID

link:onboard-downlevel.md[Onboard previous versions of Windows]

==== Azure virtual machines

* For devices running the previous, MMA-based solution, set up Azure Log
Analytics Gateway (formerly known as OMS Gateway) to act as proxy or
hub:
** link:/azure/azure-monitor/platform/gateway#download-the-log-analytics-gateway[Azure
Log Analytics Gateway]
** link:onboard-downlevel.md#install-and-configure-microsoft-monitoring-agent-mma[Install
and configure Microsoft Monitoring Agent (MMA)] point to Defender for
Endpoint Workspace key & ID
* Offline Azure VMs in the same network of OMS Gateway
** Configure Azure Log Analytics IP as a proxy
** Azure Log Analytics Workspace Key & ID
* Microsoft Defender for Cloud
** link:/azure/security-center/security-center-wdatp#enable-windows-defender-atp-integration[Security
Policy > Log Analytics Workspace]
** link:/azure/security-center/security-center-wdatp#enable-windows-defender-atp-integration[Threat
Detection > Allow Defender for Endpoint to access my data]
+
For more information, see
link:/azure/security-center/tutorial-security-policy[Working with
security policies].

____
[!NOTE] Any client that has no access to the internet cannot be
onboarded to Microsoft Defender Endpoint. A client must either have
access to the required URLs directly, or it must have access via a
proxy.
____
