= 
siosulli
:keywords: onboarding, Microsoft Defender for Endpoint onboarding, sccm,
group policy, mdm, local script, detection test

== Defender for Endpoint onboarding Windows Client

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]
- link:/microsoft-365/compliance/endpoint-dlp-learn-about[Endpoint data
loss prevention (DLP)] -
link:/microsoft-365/compliance/insider-risk-management[Insider risk
management]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https:%2F%2Faka.ms%2FMDEp2OpenTrial[Sign
up for a free trial.]
____

You’ll need to go through the onboarding section of the Defender for
Endpoint portal to onboard any of the supported devices. Depending on
the device, you’ll be guided with appropriate steps and provided
management and deployment tool options suitable for the device.

Devices in your organization must be configured so that the Defender for
Endpoint service can get sensor data from them. There are various
methods and deployment tools that you can use to configure the devices
in your organization.

In general, you’ll identify the client you’re onboarding, then follow
the corresponding tool appropriate to the device or your environment.

:::image type=``content'' source=``images/onboarddevices.png''
alt-text=``Onboard devices'' lightbox=``images/onboarddevices.png'':::

=== Related topics

* link:configure-endpoints-mdm.md[Onboard Windows devices using
Microsoft Intune]
* link:configure-endpoints-gp.md[Onboard Windows devices using Group
Policy]
* link:configure-endpoints-script.md[Onboard Windows devices using a
local script]
* link:configure-endpoints-vdi.md[Onboard non-persistent virtual desktop
infrastructure (VDI) devices]
