= 
mjcaparas
:keywords: microsoft defender for endpoint, onboard, deploy

== Onboard to the Microsoft Defender for Endpoint service

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

Learn about the various phases of deploying Microsoft Defender for
Endpoint and how to configure the capabilities within the solution.

These are the steps you need to take to deploy Defender for Endpoint:

* Step 1: Onboard endpoints to the service
* Step 2: Configure capabilities

:::image type=``content'' source=``images/deployment-steps.png''
alt-text=``The deployment steps''
lightbox=``images/deployment-steps.png'':::

=== Step 1: Onboard endpoints using any of the supported management tools

The link:deployment-strategy.md[Plan deployment] topic outlines the
general steps you need to take to deploy Defender for Endpoint.

Watch this video for a quick overview of the onboarding process and
learn about the available tools and methods.

____
{empty}[!VIDEO https://www.microsoft.com/videoplayer/embed/RE4bGqr]
____

After identifying your architecture, you’ll need to decide which
deployment method to use. The deployment tool you choose influences how
you onboard endpoints to the service.

==== Onboarding tool options

The following table lists the available tools based on the endpoint that
you need to onboard.

[width="100%",cols="25%,75%",options="header",]
|===
|Endpoint |Tool options
|*Windows* |link:configure-endpoints-script.md[Local script (up to 10
devices)] link:configure-endpoints-gp.md[Group Policy]
link:configure-endpoints-mdm.md[Microsoft Endpoint Manager/ Mobile
Device Manager] link:configure-endpoints-sccm.md[Microsoft Endpoint
Configuration Manager] link:configure-endpoints-vdi.md[VDI scripts]
link:azure-server-integration.md[Integration with Microsoft Defender for
Cloud]

|*macOS* |link:mac-install-manually.md[Local scripts]
link:mac-install-with-intune.md[Microsoft Endpoint Manager]
link:mac-install-with-jamf.md[JAMF Pro]
link:mac-install-with-other-mdm.md[Mobile Device Management]

|*Linux Server* |link:linux-install-manually.md[Local script]
link:linux-install-with-puppet.md[Puppet]
link:linux-install-with-ansible.md[Ansible]

|*iOS* |link:ios-install.md[Microsoft Endpoint Manager]

|*Android* |link:android-intune.md[Microsoft Endpoint Manager]
|===

=== Step 2: Configure capabilities

After onboarding the endpoints, you’ll then configure the capabilities.
The following table lists the components that you can configure. Choose
the components that you’d like to use and remove the ones that don’t
apply.

[width="100%",cols="50%,50%",options="header",]
|===
|Capability |Description
|link:overview-endpoint-detection-response.md[Endpoint Detection &
Response (EDR)] |Defender for Endpoint endpoint detection and response
capabilities provide advanced attack detections that are near real-time
and actionable. Security analysts can prioritize alerts effectively,
gain visibility into the full scope of a breach, and take response
actions to remediate threats.

|link:next-gen-threat-and-vuln-mgt.md[Microsoft Defender Vulnerability
Management (MDVM)] |Defender Vulnerability Management is a component of
Microsoft Defender for Endpoint, and provides both security
administrators and security operations teams with unique value,
including: - Real-time endpoint detection and response (EDR) insights
correlated with endpoint vulnerabilities - Invaluable device
vulnerability context during incident investigations - Built-in
remediation processes through Microsoft Intune and Microsoft System
Center Configuration Manager.

|link:microsoft-defender-antivirus-windows.md[Next-generation protection
(NGP)] |Microsoft Defender Antivirus is a built-in antimalware solution
that provides next-generation protection for desktops, portable
computers, and servers. Microsoft Defender Antivirus includes:
-Cloud-delivered protection for near-instant detection and blocking of
new and emerging threats. Along with machine learning and the
Intelligent Security Graph, cloud-delivered protection is part of the
next-gen technologies that power Microsoft Defender Antivirus. -
Always-on scanning using advanced file and process behavior monitoring
and other heuristics (also known as ``real-time protection''). -
Dedicated protection updates based on machine learning, human and
automated big-data analysis, and in-depth threat resistance research.

|link:overview-attack-surface-reduction.md[Attack Surface Reduction
(ASR)] |Attack surface reduction capabilities in Microsoft Defender for
Endpoint help protect the devices and applications in the organization
from new and emerging threats.

|link:automated-investigations.md[Auto Investigation & Remediation
(AIR)] |Microsoft Defender for Endpoint uses Automated investigations to
significantly reduce the volume of alerts that need to be investigated
individually. The Automated investigation feature leverages various
inspection algorithms, and processes used by analysts (such as
playbooks) to examine alerts and take immediate remediation action to
resolve breaches. This significantly reduces alert volume, allowing
security operations experts to focus on more sophisticated threats and
other high value initiatives.

|link:microsoft-threat-experts.md[Microsoft Defender Experts] |Microsoft
Defender Experts is a managed hunting service that provides Security
Operation Centers (SOCs) with expert level monitoring and analysis to
help them ensure that critical threats in their unique environments
don’t get missed.
|===

After onboarding the endpoints, you’ll then configure the various
capabilities such as endpoint detection and response, next-generation
protection, and attack surface reduction.

=== Example deployments

In this deployment guide, we’ll guide you through using two deployment
tools to onboard endpoints and how to configure capabilities.

The tools in the example deployments are:

* link:onboarding-endpoint-configuration-manager.md[Onboarding using
Microsoft Endpoint Configuration Manager]
* link:onboarding-endpoint-manager.md[Onboarding using Microsoft
Endpoint Manager]

Using the mentioned deployment tools above, you’ll then be guided in
configuring the following Defender for Endpoint capabilities:

* Endpoint detection and response configuration
* Next-generation protection configuration
* Attack surface reduction configuration

=== Related topics

* link:onboarding-endpoint-configuration-manager.md[Onboarding using
Microsoft Endpoint Configuration Manager]
* link:onboarding-endpoint-manager.md[Onboarding using Microsoft
Endpoint Manager]
* link:../office-365-security/safe-documents-in-e5-plus-security-about.md[Safe
Documents in Microsoft 365 E5]
