= Troubleshoot sensor health using Microsoft Defender for Endpoint Client Analyzer
:audience: ITPro
:author: mjcaparas
:description: Troubleshoot sensor health on devices to identify potential configuration, environment, connectivity, or telemetry issue affecting sensor data or capability.
:f1.keywords: ["NOCSH"]
:keywords: sensor, sensor health, misconfigured, inactive, no sensor data, sensor data, impaired communications, communication
:manager: dansimp
:ms.author: macapara
:ms.collection: m365-security-compliance
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: conceptual
:search.appverid: met150

== Troubleshoot sensor health using Microsoft Defender for Endpoint Client Analyzer

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]

The Microsoft Defender for Endpoint Client Analyzer (MDECA) can be useful when diagnosing sensor health or reliability issues on link:/microsoft-365/security/defender-endpoint/onboard-configure[onboarded devices] running either Windows, Linux, or macOS.
For example, you may want to run the analyzer on a machine that appears to be unhealthy according to the displayed link:/microsoft-365/security/defender-endpoint/fix-unhealthy-sensors[sensor health status] (Inactive, No Sensor Data or Impaired Communications) in the security portal.

Besides obvious sensor health issues, MDECA can collect other traces, logs, and diagnostic information for troubleshooting complex scenarios such as:

* Application compatibility (AppCompat), performance, network connectivity, or
* Unexpected behavior related to link:/microsoft-365/compliance/endpoint-dlp-learn-about[Endpoint Data Loss Prevention].

=== Privacy notice

* The Microsoft Defender for Endpoint Client Analyzer tool is regularly used by Microsoft Customer Support Services (CSS) to collect information that will help troubleshoot issues you may be experiencing with Microsoft Defender for Endpoint.
* The collected data may contain Personally Identifiable Information (PII) and/or sensitive data, such as (but not limited to) IP addresses, PC names, and usernames.
* Once data collection is complete, the tool saves the data locally on the machine within a subfolder and compressed zip file.
* No data is automatically sent to Microsoft.
If you are using the tool during collaboration on a support issue, you may be asked to send the compressed data to Microsoft CSS using Secure File Exchange to facilitate the investigation of the issue.

For more information about Secure File Exchange, see link:/troubleshoot/azure/general/secure-file-exchange-transfer-files[How to use Secure File Exchange to exchange files with Microsoft Support]

For more information about our privacy statement, see https://privacy.microsoft.com/privacystatement[Microsoft Privacy Statement].

=== Requirements

* Before running the analyzer, we recommend ensuring your proxy or firewall configuration allows access to link:configure-proxy-internet.md#enable-access-to-microsoft-defender-for-endpoint-service-urls-in-the-proxy-server[Microsoft Defender for Endpoint service URLs].
* The analyzer can run on supported editions of link:minimum-requirements.md#supported-windows-versions[Windows], link:microsoft-defender-endpoint-linux.md#system-requirements[Linux], or link:microsoft-defender-endpoint-mac.md#system-requirements[macOS] either before of after onboarding to Microsoft Defender for Endpoint.
* For Windows devices, if you are running the analyzer directly on specific machines and not remotely via link:/microsoft-365/security/defender-endpoint/troubleshoot-collect-support-log[Live Response], then SysInternals link:/sysinternals/downloads/psexec[PsExec.exe] should be allowed (at least temporarily) to run.
The analyzer calls into PsExec.exe tool to run cloud connectivity checks as Local System and emulate the behavior of the SENSE service.
+
____
[!NOTE] On Windows devices, if you use Attack Surface Reduction (ASR) rule link:attack-surface-reduction-rules-reference.md#block-process-creations-originating-from-psexec-and-wmi-commands[Block process creations originating from PSExec and WMI commands], then may want to temporarily disable the rule or link:enable-attack-surface-reduction.md#exclude-files-and-folders-from-asr-rules[configure an exclusion to the ASR rule] to allow the analyzer to run connectivity checks to cloud as expected.
____
