= 
mjcaparas
:keywords: settings, general settings, permissions, apis, rules

== Configure general Defender for Endpoint settings

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-prefsettings-abovefoldlink[Sign
up for a free trial.]
____

Use the *Settings > Endpoints* menu to modify general settings, advanced
features, enable the preview experience, email notifications, and the
custom threat intelligence feature.

=== In this section

[width="100%",cols="<50%,<50%",options="header",]
|===
|Topic |Description
|General settings |Modify your general settings that were previously
defined as part of the onboarding process.

|Permissions |Manage portal access using RBAC as well as device groups.

|APIs |Enable the threat intel and SIEM integration.

|Rules |Configure suppressions rules and automation settings.

|Device management |Onboard and offboard devices.

|Network assessments |Choose devices to be scanned regularly and added
to the device inventory.
|===
