= 
mjcaparas
:keywords: preview, preview experience, Microsoft Defender for Endpoint,
features, updates

== Microsoft Defender for Endpoint preview features

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

The Defender for Endpoint service is constantly being updated to include
new feature enhancements and capabilities.

Learn about new features in the Defender for Endpoint preview release
and be among the first to try upcoming features by turning on the
preview experience.

____
[!TIP] Get notified when this page is updated by copying and pasting the
following URL into your feed reader:
`https://learn.microsoft.com/api/search/rss?search=%22In+the+navigation+pane%2C+select+Settings+%3E+Advanced+features+%3E+Preview+features.%22&locale=en-us&facet=`
____

For more information on new capabilities that are generally available,
see link:whats-new-in-microsoft-defender-endpoint.md[What’s new in
Defender for Endpoint].

=== What you need to know

When working with features in public preview, these features:

* May have restricted or limited functionality. For example, the feature
may only apply to one platform.
* Typically go through feature changes before they’re generally
available (GA).
* Are fully supported by Microsoft.
* May only be available in selected geographic regions or cloud
environments. For example, the feature may not exist in the government
cloud.
* Individual features in preview may have more usage and support
restrictions. If so, this information is typically noted in the feature
documentation.
* The preview versions are provided with a standard support level, and
can be used for production environments.

=== Turn on preview features

You’ll have access to upcoming features that you can provide feedback on
to help improve the overall experience before features are generally
available.

Turn on the preview experience setting to be among the first to try
upcoming features.

[arabic]
. In the navigation pane, select *Settings* > *Endpoints* > *Advanced
features* > *Preview features*.
. Toggle the setting between *On* and *Off* and select *Save
preferences*.

____
{empty}[!TIP] Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-preview-belowfoldlink[Sign
up for a free trial.]
____
