= 
mjcaparas
:keywords: raw data export, streaming API, API, Event hubs, Azure
storage, storage account, Advanced Hunting, raw data sharing

== Raw Data Streaming API

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]

____
[!NOTE] For the full data streaming experience available, please visit
link:/microsoft-365/security/defender/streaming-api[Stream Microsoft 365
Defender events | Microsoft Learn].
____

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-configuresiem-abovefoldlink[Sign
up for a free trial.]
____

=== Stream Advanced Hunting events to Event Hubs and/or Azure storage account

Microsoft Defender for Endpoint supports streaming events available
through link:../defender/advanced-hunting-overview.md[Advanced Hunting]
to an link:/azure/event-hubs/[Event Hubs] and/or
link:/azure/storage/common/storage-account-overview[Azure storage
account].

____
{empty}[!VIDEO https://www.microsoft.com/videoplayer/embed/RE4r4ga]
____

=== In this section

[width="100%",cols="<50%,<50%",options="header",]
|===
|Topic |Description
|link:raw-data-export-event-hub.md[Stream Microsoft Defender for
Endpoint events to Azure Event Hubs] |Learn about enabling the streaming
API in your tenant and configure Defender for Endpoint to stream
link:advanced-hunting-overview.md[Advanced Hunting] to Event Hubs.

|link:raw-data-export-storage.md[Stream Defender for Endpoint events to
your Azure storage account] |Learn about enabling the streaming API in
your tenant and configure Defender for Endpoint to stream
link:advanced-hunting-overview.md[Advanced Hunting] to your Azure
storage account.
|===

=== Related topics

* link:/microsoft-365/security/defender/streaming-api[Stream Microsoft
365 Defender events | Microsoft Learn]
* link:advanced-hunting-overview.md[Overview of Advanced Hunting]
* link:/azure/event-hubs/[Azure Event Hubs documentation]
* link:/azure/storage/common/storage-account-overview[Azure Storage
Account documentation]
