= 
mjcaparas
:keywords: raw data export, streaming API, API, Azure Event Hubs, Azure
storage, storage account, Advanced Hunting, raw data sharing

== Configure Microsoft Defender for Endpoint to stream Advanced Hunting events to your Azure Event Hubs

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender
for Endpoint Plan 2]

____
[!NOTE] For the full data streaming experience available, please visit
link:/microsoft-365/security/defender/streaming-api[Stream Microsoft 365
Defender events | Microsoft Learn].
____

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-configuresiem-abovefoldlink[Sign
up for a free trial.]
____

=== Before you begin

[arabic]
. Create an link:/azure/event-hubs/[event hub] in your tenant.
. Log in to your https://ms.portal.azure.com/[Azure tenant], go to
*Subscriptions > Your subscription > Resource Providers > Register to
Microsoft.insights*.

=== Enable raw data streaming

[arabic]
. Log in to the https://security.microsoft.com[Microsoft 365 Defender]
as a *_Global Administrator_* or *_Security Administrator_*.
. Go to the
https://security.microsoft.com/interoperability/dataexport[Data export
settings page] in the Microsoft Defender portal.
. Click on *Add data export settings*.
. Choose a name for your new settings.
. Choose *Forward events to Azure Event Hubs*.
. Type your *Event Hubs name* and your *Event Hubs resource ID*.
+
In order to get your *Event Hubs resource ID*, go to your Azure Event
Hubs namespace page on https://ms.portal.azure.com/[Azure] > properties
tab > copy the text under *Resource ID*:
+
:::image type=``content'' source=``images/event-hub-resource-id.png''
alt-text=``The Event Hubs resource Id-1''
lightbox=``images/event-hub-resource-id.png'':::
. Choose the events you want to stream and click *Save*.

=== The schema of the events in Azure Event Hubs

[source,json]
----
{
    "records": [
                    {
                        "time": "<The time WDATP received the event>"
                        "tenantId": "<The Id of the tenant that the event belongs to>"
                        "category": "<The Advanced Hunting table name with 'AdvancedHunting-' prefix>"
                        "properties": { <WDATP Advanced Hunting event as Json> }
                    }
                    ...
                ]
}
----

* Each event hub message in Azure Event Hubs contains list of records.
* Each record contains the event name, the time Microsoft Defender for
Endpoint received the event, the tenant it belongs (you will only get
events from your tenant), and the event in JSON format in a property
called ``**properties**''.
* For more information about the schema of Microsoft Defender for
Endpoint events, see link:advanced-hunting-overview.md[Advanced Hunting
overview].
* In Advanced Hunting, the *DeviceInfo* table has a column named
*MachineGroup* which contains the group of the device. Here every event
will be decorated with this column as well. See
link:machine-groups.md[Device Groups] for more information. > [!NOTE] >
Device group creation is supported in Defender for Endpoint Plan 1 and
Plan 2.

=== Data types mapping

To get the data types for event properties do the following:

[arabic]
. Log in to https://security.microsoft.com[Microsoft 365 Defender] and
go to https://security.microsoft.com/hunting-package[Advanced Hunting
page].
. Run the following query to get the data types mapping for each event:
+
[source,kusto]
----
{EventType}
| getschema
| project ColumnName, ColumnType 
----

* Here is an example for Device Info event:
+
:::image type=``content''
source=``images/machine-info-datatype-example.png'' alt-text=``The Event
Hubs resource Id-2''
lightbox=``images/machine-info-datatype-example.png'':::

=== Related topics

* link:/microsoft-365/security/defender/streaming-api[Stream Microsoft
365 Defender events | Microsoft Learn]
* link:advanced-hunting-overview.md[Overview of Advanced Hunting]
* link:raw-data-export.md[Microsoft Defender for Endpoint streaming API]
* link:raw-data-export-storage.md[Stream Microsoft Defender for Endpoint
events to your Azure storage account]
* link:/azure/event-hubs/[Azure Event Hubs documentation]
* link:/azure/event-hubs/troubleshooting-guide[Troubleshoot connectivity
issues - Azure Event Hubs]
