= 
denisebmsft
:keywords: siem, monitor, report, Microsoft Defender AV, Microsoft
Defender Antivirus

== Report on Microsoft Defender Antivirus

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] - Microsoft Defender Antivirus

*Platforms* - Windows

Microsoft Defender Antivirus is built into Windows 10, Windows 11,
Windows Server 2019, Windows Server 2022, and Windows Server 2016.
Microsoft Defender Antivirus is of your next-generation protection in
Microsoft Defender for Endpoint. Next-generation protection helps
protect your devices from software threats like viruses, malware, and
spyware across email, apps, the cloud, and the web.

With Microsoft Defender Antivirus, you have several options for
reviewing protection status and alerts. You can use Microsoft Endpoint
Manager to
link:/configmgr/protect/deploy-use/monitor-endpoint-protection[monitor
Microsoft Defender Antivirus] or
link:/configmgr/protect/deploy-use/endpoint-configure-alerts[create
email alerts]. Or, you can monitor protection using
link:/intune/introduction-intune[Microsoft Intune].

If you have a third-party security information and event management
(SIEM) server, you can also consume
link:/windows/win32/events/windows-events[Windows Defender client
events].

Windows events comprise several security event sources, including
Security Account Manager (SAM) events
(link:/windows/whats-new/whats-new-windows-10-version-1507-and-1511[enhanced
for Windows 10], also see the
link:/windows/security/threat-protection/auditing/security-auditing-overview[Security
auditing] topic) and
link:troubleshoot-microsoft-defender-antivirus.md[Windows Defender
events].

These events can be centrally aggregated using the
link:/windows/win32/wec/windows-event-collector[Windows event
collector]. Often, SIEM servers have connectors for Windows events,
allowing you to correlate all security events in your SIEM server.

You can also
link:/security/benchmark/azure/security-control-logging-monitoring[monitor
malware events using the Malware Assessment solution in Log Analytics].

For monitoring or determining status with PowerShell, WMI, or Microsoft
Azure, see the
link:deploy-manage-report-microsoft-defender-antivirus.md#ref2[(Deployment&#44;
management&#44; and reporting options table)].

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____

____
[!TIP] *Performance tip* Due to a variety of factors (examples listed
below) Microsoft Defender Antivirus, like other antivirus software, can
cause performance issues on endpoint devices. In some cases, you might
need to tune the performance of Microsoft Defender Antivirus to
alleviate those performance issues. Microsoft’s *Performance analyzer*
is a PowerShell command-line tool that helps determine which files, file
paths, processes, and file extensions might be causing performance
issues; some examples are:

* Top paths that impact scan time
* Top files that impact scan time
* Top processes that impact scan time
* Top file extensions that impact scan time
* Combinations – for example:
** top files per extension
** top paths per extension
** top processes per path
** top scans per file
** top scans per file per process

You can use the information gathered using Performance analyzer to
better assess performance issues and apply remediation actions. See:
link:tune-performance-defender-antivirus.md[Performance analyzer for
Microsoft Defender Antivirus].
____

=== See also

* link:microsoft-defender-antivirus-in-windows-10.md[Microsoft Defender
Antivirus in Windows 10]
* link:deploy-manage-report-microsoft-defender-antivirus.md[Deploy
Microsoft Defender Antivirus]
