= Monitor and report on Microsoft Defender Antivirus protection
:author: denisebmsft
:description: Use Configuration Manager or security information and event management (SIEM) tools to consume reports, and monitor Microsoft Defender Antivirus with PowerShell and WMI.
:keywords: siem, monitor, report, Microsoft Defender AV, Microsoft Defender Antivirus
:manager: dansimp
:ms.author: deniseb
:ms.collection: M365-security-compliance
:ms.custom: nextgen
:ms.localizationpriority: medium
:ms.mktglfcycl: manage
:ms.pagetype: security
:ms.reviewer:
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Report on Microsoft Defender Antivirus

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* Microsoft Defender Antivirus

*Platforms*

* Windows

Microsoft Defender Antivirus is built into Windows 10, Windows 11, Windows Server 2019, Windows Server 2022, and Windows Server 2016.
Microsoft Defender Antivirus is of your next-generation protection in Microsoft Defender for Endpoint.
Next-generation protection helps protect your devices from software threats like viruses, malware, and spyware across email, apps, the cloud, and the web.

With Microsoft Defender Antivirus, you have several options for reviewing protection status and alerts.
You can use Microsoft Endpoint Manager to link:/configmgr/protect/deploy-use/monitor-endpoint-protection[monitor Microsoft Defender Antivirus] or link:/configmgr/protect/deploy-use/endpoint-configure-alerts[create email alerts].
Or, you can monitor protection using link:/intune/introduction-intune[Microsoft Intune].

If you have a third-party security information and event management (SIEM) server, you can also consume link:/windows/win32/events/windows-events[Windows Defender client events].

Windows events comprise several security event sources, including Security Account Manager (SAM) events (link:/windows/whats-new/whats-new-windows-10-version-1507-and-1511[enhanced for Windows 10], also see the link:/windows/security/threat-protection/auditing/security-auditing-overview[Security auditing] topic) and  xref:troubleshoot-microsoft-defender-antivirus.adoc[Windows Defender events].

These events can be centrally aggregated using the link:/windows/win32/wec/windows-event-collector[Windows event collector].
Often, SIEM servers have connectors for Windows events, allowing you to correlate all security events in your SIEM server.

You can also link:/security/benchmark/azure/security-control-logging-monitoring[monitor malware events using the Malware Assessment solution in Log Analytics].

For monitoring or determining status with PowerShell, WMI, or Microsoft Azure, see the link:deploy-manage-report-microsoft-defender-antivirus.md#ref2[(Deployment, management, and reporting options table)].

____
[!TIP] If you're looking for Antivirus related information for other platforms, see:

* xref:mac-preferences.adoc[Set preferences for Microsoft Defender for Endpoint on macOS]
* xref:microsoft-defender-endpoint-mac.adoc[Microsoft Defender for Endpoint on Mac]
* link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS Antivirus policy settings for Microsoft Defender Antivirus for Intune]
* xref:linux-preferences.adoc[Set preferences for Microsoft Defender for Endpoint on Linux]
* xref:microsoft-defender-endpoint-linux.adoc[Microsoft Defender for Endpoint on Linux]
* xref:android-configure.adoc[Configure Defender for Endpoint on Android features]
* xref:ios-configure-features.adoc[Configure Microsoft Defender for Endpoint on iOS features]
____

=== See also

* xref:microsoft-defender-antivirus-in-windows-10.adoc[Microsoft Defender Antivirus in Windows 10]
* xref:deploy-manage-report-microsoft-defender-antivirus.adoc[Deploy Microsoft Defender Antivirus]
