= 
denisebmsft

== Restore quarantined files in Microsoft Defender Antivirus

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] - Microsoft Defender Antivirus

*Platforms* - Windows

If Microsoft Defender Antivirus is configured to detect and remediate
threats on your device, Microsoft Defender Antivirus quarantines
suspicious files. If you are certain a quarantined file is not a threat,
you can restore it.

[arabic]
. Open *Windows Security*.
. Select *Virus & threat protection* and then click *Protection
history*.
. In the list of all recent items, filter on *Quarantined Items*.
. Select an item you want to keep, and take an action, such as restore.

____
[!TIP] Restoring a file from quarantine can also be done using Command
Prompt. See
link:/windows/security/threat-protection/microsoft-defender-atp/respond-file-alerts#restore-file-from-quarantine[Restore
a file from quarantine].
____

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____

=== Related articles

* link:configure-remediation-microsoft-defender-antivirus.md[Configure
remediation for scans]
* link:review-scan-results-microsoft-defender-antivirus.md[Review scan
results]
* link:configure-extension-file-exclusions-microsoft-defender-antivirus.md[Configure
and validate exclusions based on file name&#44; extension&#44; and folder
location]
* link:configure-process-opened-file-exclusions-microsoft-defender-antivirus.md[Configure
and validate exclusions for files opened by processes]
* link:configure-server-exclusions-microsoft-defender-antivirus.md[Configure
Microsoft Defender Antivirus exclusions on Windows Server]
