= 
mjcaparas
:keywords: apis, graph api, supported apis, collect investigation
package

== Restrict app execution API

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Restrict execution of all applications on the device except a predefined
set.

=== Limitations

[arabic]
. Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.

{empty}[!includelink:../../includes/machineactionsnote.md[Device actions
note]]

____
{empty}[!IMPORTANT]

* This action is available for devices on Windows 10, version 1709 or
later, and on Windows 11.
* This feature is available if your organization uses Microsoft Defender
Antivirus.
* This action needs to meet the Windows Defender Application Control
code integrity policy formats and signing requirements. For more
information, see
link:/windows/device-security/device-guard/requirements-and-deployment-planning-guidelines-for-device-guard#code-integrity-policy-formats-and-signing[Code
integrity policy formats and signing].
____

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Microsoft Defender for Endpoint APIs]

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Machine.RestrictExecution |`Restrict code execution'

|Delegated (work or school account) |Machine.RestrictExecution
|`Restrict code execution'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to have at least the following role permission: `Active
remediation actions' (See link:user-roles.md[Create and manage roles]
for more information)
* The user needs to have access to the device, based on device group
settings (See link:machine-groups.md[Create and manage device groups]
for more information)

Device group creation is supported in Defender for Endpoint Plan 1 and
Plan 2.
____

=== HTTP request

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/machines/{id}/restrictCodeExecution
----

=== Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|Content-Type |string |application/json. *Required*.
|===

=== Request body

In the request body, supply a JSON object with the following parameters:

[cols="<,<,<",options="header",]
|===
|Parameter |Type |Description
|Comment |String |Comment to associate with the action. *Required*.
|===

=== Response

If successful, this method returns 201 - Created response code and
link:machineaction.md[Machine Action] in the response body.

If you send multiple API calls to restrict app execution for the same
device, it returns ``pending machine action'' or HTTP 400 with the
message ``Action is already in progress''.

=== Example

==== Request

Here is an example of the request.

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/machines/1e5bc9d7e413ddd7902c2932e418702b84d0cc07/restrictCodeExecution 
----

[source,json]
----
{
  "Comment": "Restrict code execution due to alert 1234"
}
----

* To remove code execution restriction from a device, see
link:unrestrict-code-execution.md[Remove app restriction].
