= 
denisebmsft
:keywords: scan results, remediation, full scan, quick scan

== Review Microsoft Defender Antivirus scan results

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] - Microsoft Defender Antivirus

*Platforms* - Windows

After a Microsoft Defender Antivirus scan completes, whether it is an
link:run-scan-microsoft-defender-antivirus.md[on-demand] or
link:scheduled-catch-up-scans-microsoft-defender-antivirus.md[scheduled
scan], the results are recorded and you can view the results.

=== Use Configuration Manager to review scan results

See link:/configmgr/protect/deploy-use/monitor-endpoint-protection[How
to monitor Endpoint Protection status].

=== Use PowerShell cmdlets to review scan results

The following cmdlet will return each detection on the endpoint. If
there are multiple detections of the same threat, each detection will be
listed separately, based on the time of each detection:

[source,powershell]
----
Get-MpThreatDetection
----

:::image type=``content''
source=``../../media/wdav-get-mpthreatdetection.png'' alt-text=``The
PowerShell cmdlets and outputs''
lightbox=``../../media/wdav-get-mpthreatdetection.png'':::

You can specify `-ThreatID` to limit the output to only show the
detections for a specific threat.

If you want to list threat detections, but combine detections of the
same threat into a single item, you can use the following cmdlet:

[source,powershell]
----
Get-MpThreat
----

:::image type=``content'' source=``../../media/wdav-get-mpthreat.png''
alt-text=``The PowerShell code''
lightbox=``../../media/wdav-get-mpthreat.png'':::

See link:use-powershell-cmdlets-microsoft-defender-antivirus.md[Use
PowerShell cmdlets to configure and run Microsoft Defender Antivirus]
and link:/powershell/module/defender/[Defender Antivirus cmdlets] for
more information on how to use PowerShell with Microsoft Defender
Antivirus.

=== Use Windows Management Instruction (WMI) to review scan results

Use the
link:/previous-versions/windows/desktop/defender/windows-defender-wmiv2-apis-portal[*Get*
method of the *MSFT_MpThreat* and *MSFT_MpThreatDetection*] classes.

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____

=== Related articles

* link:customize-run-review-remediate-scans-microsoft-defender-antivirus.md[Customize&#44;
initiate&#44; and review the results of Microsoft Defender Antivirus scans
and remediation]
* link:microsoft-defender-antivirus-in-windows-10.md[Microsoft Defender
Antivirus in Windows 10]
