= 
mjcaparas
:keywords: apis, supported apis, advanced hunting, query

== Advanced Hunting using Python

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

Run advanced queries using Python, see
link:run-advanced-query-api.md[Advanced Hunting API].

In this section, we share Python samples to retrieve a token and use it
to run a query.

____
*Prerequisite*: You first need to link:apis-intro.md[create an app].
____

=== Get token

* Run the following commands:

[source,python]
----
import json
import urllib.request
import urllib.parse

tenantId = '00000000-0000-0000-0000-000000000000' # Paste your own tenant ID here
appId = '11111111-1111-1111-1111-111111111111' # Paste your own app ID here
appSecret = '22222222-2222-2222-2222-222222222222' # Paste your own app secret here

url = "https://login.microsoftonline.com/%s/oauth2/token" % (tenantId)

resourceAppIdUri = 'https://api.securitycenter.microsoft.com'

body = {
    'resource' : resourceAppIdUri,
    'client_id' : appId,
    'client_secret' : appSecret,
    'grant_type' : 'client_credentials'
}

data = urllib.parse.urlencode(body).encode("utf-8")

req = urllib.request.Request(url, data)
response = urllib.request.urlopen(req)
jsonResponse = json.loads(response.read())
aadToken = jsonResponse["access_token"]
----

where

* tenantId: ID of the tenant on behalf of which you want to run the
query (that is, the query will be run on the data of this tenant)
* appId: ID of your Azure AD app (the app must have `Run advanced
queries' permission to Microsoft Defender for Endpoint)
* appSecret: Secret of your Azure AD app

=== Run query

Run the following query:

[source,python]
----
query = 'DeviceRegistryEvents | limit 10' # Paste your own query here

url = "https://api.securitycenter.microsoft.com/api/advancedqueries/run"
headers = { 
    'Content-Type' : 'application/json',
    'Accept' : 'application/json',
    'Authorization' : "Bearer " + aadToken
}

data = json.dumps({ 'Query' : query }).encode("utf-8")

req = urllib.request.Request(url, data, headers)
response = urllib.request.urlopen(req)
jsonResponse = json.loads(response.read())
schema = jsonResponse["Schema"]
results = jsonResponse["Results"]
----

* schema contains the schema of the results of your query
* results contain the results of your query

==== Complex queries

If you want to run complex queries (or multiline queries), save your
query in a file and, instead of the first line in the above sample, run
the below command:

[source,python]
----
queryFile = open("D:\\Temp\\myQuery.txt", 'r') # Replace with the path to your file
query = queryFile.read()
queryFile.close()
----

=== Work with query results

You can now use the query results.

To iterate over the results do the below:

[source,python]
----
for result in results:
    print(result) # Prints the whole result
    print(result["EventTime"]) # Prints only the property 'EventTime' from the result
----

To output the results of the query in CSV format in file file1.csv do
the below:

[source,python]
----
import csv

outputFile = open("D:\\Temp\\file1.csv", 'w')
output = csv.writer(outputFile)
output.writerow(results[0].keys())
for result in results:
    output.writerow(result.values())

outputFile.close()
----

To output the results of the query in JSON format in file file1.json do
the below:

[source,python]
----
outputFile = open("D:\\Temp\\file1.json", 'w')
json.dump(results, outputFile)
outputFile.close()
----

=== Related topic

* link:apis-intro.md[Microsoft Defender for Endpoint APIs]
* link:run-advanced-query-api.md[Advanced Hunting API]
* link:run-advanced-query-sample-powershell.md[Advanced Hunting using
PowerShell]
