= Run live response commands on a device
:audience: ITPro
:author: mjcaparas
:description: Learn how to run a sequence of live response commands on a device.
:f1.keywords: ["NOCSH"]
:keywords: apis, graph api, supported apis, upload to library
:manager: dansimp
:ms.author: macapara
:ms.collection: m365-security-compliance
:ms.custom: api
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Run live response commands on a device

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]

[!includexref:../../includes/prerelease.adoc[Prerelease information]]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign up for a free trial.]
____

[!includexref:../../includes/microsoft-defender-api-usgov.adoc[Microsoft Defender for Endpoint API URIs for US Government]]

[!includexref:../../includes/improve-request-performance.adoc[Improve request performance]]

=== API description

Runs a sequence of live response commands on a device

=== Limitations

. Rate limitations for this API are 10 calls per minute (additional requests are responded with HTTP 429).
. 25 concurrently running sessions (requests exceeding the throttling limit will receive a "429 - Too many requests" response).
. If the machine is not available, the session will be queued for up to 3 days.
. RunScript command timeouts after 10 minutes.
. Live response commands cannot be queued up and can only be executed one at a time.
. If the machine that you are trying to run this API call is in an RBAC device group that does not have an automated remediation level assigned to it, you'll need to at least enable the minimum Remediation Level for a given Device Group.
+
____
[!NOTE] Device group creation is supported in Defender for Endpoint Plan 1 and Plan 2.
____

. Multiple live response commands can be run on a single API call.
However, when a live response command fails all the subsequent actions will not be executed.

=== Minimum Requirements

Before you can initiate a session on a device, make sure you fulfill the following requirements:

* *Verify that you're running a supported version of Windows*.
+
Devices must be running one of the following versions of Windows

 ** *Windows 11*
 ** *Windows 10*
  *** link:/windows/whats-new/whats-new-windows-10-version-1909[Version 1909] or later
  *** link:/windows/whats-new/whats-new-windows-10-version-1903[Version 1903] with https://support.microsoft.com/help/4515384/windows-10-update-kb4515384[KB4515384]
  *** link:/windows/whats-new/whats-new-windows-10-version-1809[Version 1809 (RS 5)] with https://support.microsoft.com/help/4537818/windows-10-update-kb4537818[with KB4537818]
  *** link:/windows/whats-new/whats-new-windows-10-version-1803[Version 1803 (RS 4)] with https://support.microsoft.com/help/4537795/windows-10-update-kb4537795[KB4537795]
  *** link:/windows/whats-new/whats-new-windows-10-version-1709[Version 1709 (RS 3)] with https://support.microsoft.com/help/4537816/windows-10-update-kb4537816[KB4537816]
 ** *Windows Server 2019 - Only applicable for Public preview*
  *** Version 1903 or (with https://support.microsoft.com/help/4515384/windows-10-update-kb4515384[KB4515384]) later
  *** Version 1809 (with https://support.microsoft.com/help/4537818/windows-10-update-kb4537818[KB4537818])
 ** *Windows Server 2022*

=== Permissions

One of the following permissions is required to call this API.
To learn more, including how to choose permissions, see xref:apis-intro.adoc[Get started].

|===
| Permission type | Permission | Permission display name

| Application
| Machine.LiveResponse
| Run live response on a specific machine

| Delegated (work or school account)
| Machine.LiveResponse
| Run live response on a specific machine
|===

=== HTTP request

[,http]
----
POST https://api.securitycenter.microsoft.com/API/machines/{machine_id}/runliveresponse
----

=== Request headers

|===
| Name | Type | Description

| Authorization
| String
| Bearer<token>.
Required.

| Content-Type
| string
| application/json.
Required.
|===

=== Request body

|===
| Parameter | Type | Description

| Comment
| String
| Comment to associate with the action.

| Commands
| Array
| Commands to run.
Allowed values are PutFile, RunScript, GetFile.
|===

=== Commands

|===
| Command Type | Parameters | Description

| PutFile
| Key: FileName <p> Value: <file name>
| Puts a file from the library to the device.
Files are saved in a working folder and are deleted when the device restarts by default.

| RunScript
| Key: ScriptName + Value: <Script from library> <p> Key: Args + Value: <Script arguments>
| Runs a script from the library on a device.
<p>  The Args parameter is passed to your script.
<p> Timeouts after 10 minutes.

| GetFile
| Key: Path + Value: <File path>
| Collect file from a device.
NOTE: Backslashes in path must be escaped.
|===

=== Response

* If successful, this method returns 201 Created.
+
Action entity.
If machine with the specified ID was not found - 404 Not Found.

=== Example

==== Request example

Here is an example of the request.

[,http]
----
POST https://api.securitycenter.microsoft.com/api/machines/1e5bc9d7e413ddd7902c2932e418702b84d0cc07/runliveresponse

```JSON
{
   "Commands":[
      {
         "type":"RunScript",
         "params":[
            {
               "key":"ScriptName",
               "value":"minidump.ps1"
            },
            {
               "key":"Args",
               "value":"OfficeClickToRun"
            }

         ]
      },
      {
         "type":"GetFile",
         "params":[
            {
               "key":"Path",
               "value":"C:\\windows\\TEMP\\OfficeClickToRun.dmp.zip"
            }
         ]
      }
   ],
   "Comment":"Testing Live Response API"
}
----

==== Response example

Here is an example of the response.

[,http]
----
HTTP/1.1 200 Ok
----

Content-type: application/json

[,json]
----
{
    "@odata.context": "https://api.securitycenter.microsoft.com/api/$metadata#MachineActions/$entity",
    "id": "{machine_action_id}",
    "type": "LiveResponse",
    "requestor": "analyst@microsoft.com",
    "requestorComment": "Testing Live Response API",
    "status": "Pending",
    "machineId": "{machine_id}",
    "computerDnsName": "hostname",
    "creationDateTimeUtc": "2021-02-04T15:36:52.7788848Z",
    "lastUpdateDateTimeUtc": "2021-02-04T15:36:52.7788848Z",
    "errorHResult": 0,
    "commands": [
        {
            "index": 0,
            "startTime": null,
            "endTime": null,
            "commandStatus": "Created",
            "errors": [],
            "command": {
                "type": "RunScript",
                "params": [
                    {
                        "key": "ScriptName",
                        "value": "minidump.ps1"
                    },{
                        "key": "Args",
                        "value": "OfficeClickToRun"
                    }
                ]
            }
        }, {
            "index": 1,
            "startTime": null,
            "endTime": null,
            "commandStatus": "Created",
            "errors": [],
            "command": {
                "type": "GetFile",
                "params": [{
                        "key": "Path", "value": "C:\\windows\\TEMP\\OfficeClickToRun.dmp.zip"
                    }
                ]
            }
        }
    ]
}
----

=== Related topics

* xref:get-machineaction-object.adoc[Get machine action API]
* xref:get-live-response-result.adoc[Get live response result]
* xref:cancel-machine-action.adoc[Cancel machine action]
