= Schedule antivirus scans using Windows Management Instrumentation
:author: denisebmsft
:description: Schedule antivirus scans using WMI
:keywords: quick scan, full scan, WMI, schedule, antivirus
:manager: dansimp
:ms.author: deniseb
:ms.collection: M365-security-compliance
:ms.custom: nextgen
:ms.date: 10/18/2021
:ms.localizationpriority: medium
:ms.mktglfcycl: manage
:ms.pagetype: security
:ms.reviewer: pauhijbr, ksarens
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: how-to
:search.appverid: met150

== Schedule antivirus scans using Windows Management Instrumentation (WMI)

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* Microsoft Defender Antivirus

*Platforms*

* Windows

This article describes how to configure scheduled scans using WMI.
To learn more about scheduling scans and about scan types, see xref:schedule-antivirus-scans.adoc[Configure scheduled quick or full Microsoft Defender Antivirus scans].

=== Use Windows Management Instruction (WMI) to schedule scans

Use the link:/previous-versions/windows/desktop/legacy/dn455323(v=vs.85)[*Set* method of the *MSFT_MpPreference*] class for the following properties:

[,wmi]
----
ScanParameters
ScanScheduleDay
ScanScheduleTime
RandomizeScheduleTaskTimes
----

For more information and allowed parameters, see link:/previous-versions/windows/desktop/defender/windows-defender-wmiv2-apis-portal[Windows Defender WMIv2 APIs]

=== WMI for scheduling scans when an endpoint is not in use

Use the link:/previous-versions/windows/desktop/legacy/dn455323(v=vs.85)[Set method of the MSFT_MpPreference class] for the following properties:

[,wmi]
----
ScanOnlyIfIdleEnabled
----

For more information about APIs and allowed parameters, see link:/previous-versions/windows/desktop/defender/windows-defender-wmiv2-apis-portal[Windows Defender WMIv2 APIs].

____
[!NOTE] When you schedule scans for times when endpoints are not in use, scans do not honor the CPU throttling configuration and will take full advantage of the resources available to complete the scan as fast as possible.
____

=== WMI for scheduling scans to complete remediation

Use the link:/previous-versions/windows/desktop/legacy/dn455323(v=vs.85)[*Set* method of the *MSFT_MpPreference*] class for the following properties:

[,wmi]
----
RemediationScheduleDay
RemediationScheduleTime
----

For more information and allowed parameters, see link:/previous-versions/windows/desktop/defender/windows-defender-wmiv2-apis-portal[Windows Defender WMIv2 APIs].

=== WMI for scheduling daily scans

Use the link:/previous-versions/windows/desktop/legacy/dn455323(v=vs.85)[*Set* method of the *MSFT_MpPreference*] class for the following properties:

[,wmi]
----
ScanScheduleQuickScanTime
----

For more information and allowed parameters, see link:/previous-versions/windows/desktop/defender/windows-defender-wmiv2-apis-portal[Windows Defender WMIv2 APIs].

____
[!TIP] If you're looking for Antivirus related information for other platforms, see:

* xref:mac-preferences.adoc[Set preferences for Microsoft Defender for Endpoint on macOS]
* xref:microsoft-defender-endpoint-mac.adoc[Microsoft Defender for Endpoint on Mac]
* link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS Antivirus policy settings for Microsoft Defender Antivirus for Intune]
* xref:linux-preferences.adoc[Set preferences for Microsoft Defender for Endpoint on Linux]
* xref:microsoft-defender-endpoint-linux.adoc[Microsoft Defender for Endpoint on Linux]
* xref:android-configure.adoc[Configure Defender for Endpoint on Android features]
* xref:ios-configure-features.adoc[Configure Microsoft Defender for Endpoint on iOS features]
____
