= 
denisebmsft
:keywords: quick scan, full scan, WMI, schedule, antivirus

== Schedule antivirus scans using Windows Management Instrumentation (WMI)

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] - Microsoft Defender Antivirus

*Platforms* - Windows

This article describes how to configure scheduled scans using WMI. To
learn more about scheduling scans and about scan types, see
link:schedule-antivirus-scans.md[Configure scheduled quick or full
Microsoft Defender Antivirus scans].

=== Use Windows Management Instruction (WMI) to schedule scans

Use the
link:/previous-versions/windows/desktop/legacy/dn455323(v=vs.85)[*Set*
method of the *MSFT_MpPreference*] class for the following properties:

[source,wmi]
----
ScanParameters
ScanScheduleDay
ScanScheduleTime
RandomizeScheduleTaskTimes
----

For more information and allowed parameters, see
link:/previous-versions/windows/desktop/defender/windows-defender-wmiv2-apis-portal[Windows
Defender WMIv2 APIs]

=== WMI for scheduling scans when an endpoint is not in use

Use the
link:/previous-versions/windows/desktop/legacy/dn455323(v=vs.85)[Set
method of the MSFT_MpPreference class] for the following properties:

[source,wmi]
----
ScanOnlyIfIdleEnabled
----

For more information about APIs and allowed parameters, see
link:/previous-versions/windows/desktop/defender/windows-defender-wmiv2-apis-portal[Windows
Defender WMIv2 APIs].

____
[!NOTE] When you schedule scans for times when endpoints are not in use,
scans do not honor the CPU throttling configuration and will take full
advantage of the resources available to complete the scan as fast as
possible.
____

=== WMI for scheduling scans to complete remediation

Use the
link:/previous-versions/windows/desktop/legacy/dn455323(v=vs.85)[*Set*
method of the *MSFT_MpPreference*] class for the following properties:

[source,wmi]
----
RemediationScheduleDay
RemediationScheduleTime
----

For more information and allowed parameters, see
link:/previous-versions/windows/desktop/defender/windows-defender-wmiv2-apis-portal[Windows
Defender WMIv2 APIs].

=== WMI for scheduling daily scans

Use the
link:/previous-versions/windows/desktop/legacy/dn455323(v=vs.85)[*Set*
method of the *MSFT_MpPreference*] class for the following properties:

[source,wmi]
----
ScanScheduleQuickScanTime
----

For more information and allowed parameters, see
link:/previous-versions/windows/desktop/defender/windows-defender-wmiv2-apis-portal[Windows
Defender WMIv2 APIs].

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____
