= 
siosulli
:keywords: apis, graph api, supported apis, score, exposure score,
device secure score, exposure score by device group

== Score resource type

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

{empty}[!includelink:../../includes/prerelease.md[Prerelease
information]]

=== Methods

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Method |Return Type |Description
|link:get-exposure-score.md[Get exposure score] |link:score.md[Score]
|Get the organizational exposure score.

|link:get-device-secure-score.md[Get device secure score]
|link:score.md[Score] |Get the organizational device secure score.

|link:get-machine-group-exposure-score.md[List exposure score by device
group] |link:score.md[Score] |List scores by device group.
|===

____
[!NOTE] Device group creation is supported in Defender for Endpoint Plan
1 and Plan 2.
____

=== Properties

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Property |Type |Description
|Score |Double |The current score.

|Time |DateTime |The date and time in which the call for this API was
made.

|RbacGroupName |String |The device group name.

|RbacGroupId |String |The device group ID.
|===
