= Server migration scenarios for the new version of Microsoft Defender for Endpoint
:audience: ITPro
:author: mjcaparas
:description: Read this article to get an overview of how to migrate your servers from the previous, MMA-based solution to the current Defender for Endpoint unified solution package.
:keywords: migrate server, server, 2012r2, 2016, server migration, device management, configure Microsoft Defender for Endpoint servers, onboard Microsoft Defender for Endpoint servers
:manager: dansimp
:ms.author: macapara
:ms.collection: M365-security-compliance
:ms.date: 09/19/2022
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150
:search.product: eADQiWindows 10XVcnh

== Server migration scenarios from the previous, MMA-based Microsoft Defender for Endpoint solution

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* Windows Server 2012 R2
* Windows Server 2016
* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]

____
[!NOTE] Always ensure the operating system, and Microsoft Defender Antivirus on Windows Server 2016, are fully updated before proceeding with installation or upgrade.
To receive regular product improvements and fixes for the EDR Sensor component, ensure Windows Update https://go.microsoft.com/fwlink/?linkid=2168277[KB5005292] gets applied or approved after installation.
In addition, to keep protection components updated, please reference link:/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus#monthly-platform-and-engine-versions[Manage Microsoft Defender Antivirus updates and apply baselines].
____

These instructions apply to the new unified solution and installer (MSI) package of Microsoft Defender for Endpoint for Windows Server 2012 R2 and Windows Server 2016.
This article contains high-level instructions for various possible migration scenarios from the previous to the current solution.
These high-level steps are intended as guidelines to be adjusted to the deployment and configuration tools available in your environment.

*If you are using Microsoft Defender for Cloud to perform deployment, you can automate installation and upgrade.
See https://techcommunity.microsoft.com/t5/microsoft-defender-for-cloud/defender-for-servers-plan-2-now-integrates-with-mde-unified/ba-p/3527534[Defender for Servers Plan 2 now integrates with MDE unified solution]*

____
[!NOTE] Operating system upgrades with Microsoft Defender for Endpoint installed are not supported.
Please offboard and uninstall, upgrade the operating system, then proceed with installation.
____

____
[!NOTE] Full Microsoft Endpoint Configuration Manager automation and integration to perform an automated upgrade will be available in a later release of MECM.
From the 2107 release with the latest hotfix rollup, you CAN use the Endpoint Protection node for configuration as well as Group Policy, PowerShell, Microsoft Endpoint Manager tenant attach or local configuration.
In addition, you can leverage existing functionality in Microsoft Endpoint Configuration Manager to automate manual upgrade steps;
methods for which are described below.
____

=== Installer script

____
[!NOTE] Make sure the machines you run the script on is not blocking the execution of the script.
The recommended execution policy setting for PowerShell is Allsigned.
This requires importing the script's signing certificate into the Local Computer Trusted Publishers store if the script is running as SYSTEM on the endpoint.
____

To facilitate upgrades when Microsoft Endpoint Configuration Manager is not yet available or updated to perform the automated upgrade, you can use this https://github.com/microsoft/mdefordownlevelserver[upgrade script].
Download it by selection the "Code" button and downloading the .zip file, then extracting install.ps1.
It can help automate the following required steps:

. Remove the OMS workspace for Microsoft Defender for Endpoint (OPTIONAL).
. Remove System Center Endpoint Protection (SCEP) client if installed.
. Download and install (Windows Server 2012 R2) link:configure-server-endpoints.md#prerequisites[prerequisites] if required.
. Install Microsoft Defender for Endpoint.
. Apply the onboarding script *for use with Group Policy* downloaded from https://security.microsoft.com[Microsoft 365 Defender].

To use the script, download it to an installation directory where you have also placed the installation and onboarding packages (see xref:configure-server-endpoints.adoc[Configure server endpoints]).

EXAMPLE: .\install.ps1 -RemoveMMA +++<YOUR_WORKSPACE_ID>+++-OnboardingScript ".\WindowsDefenderATPOnboardingScript.cmd"+++</YOUR_WORKSPACE_ID>+++

For more information on how to use the script, use the PowerShell command "get-help .\install.ps1".

=== Microsoft Endpoint Configuration Manager migration scenarios

____
[!NOTE] You'll need Microsoft Endpoint Configuration Manager, version 2107 or later to perfom Endpoint Protection policy configuration.
____

For instructions on how to migrate using Microsoft Endpoint Configuration Manager older than version 2207 please see link:/microsoft-365/security/defender-endpoint/application-deployment-via-mecm[Migrating servers from Microsoft Monitoring Agent to the unified solution.]

=== If you are running a non-Microsoft antivirus solution

. Fully update the machine including Microsoft Defender Antivirus (Windows Server 2016) ensuring link:configure-server-endpoints.md#prerequisites[prerequisites] have been met.
For more information on the prerequisites that have to be met, see link:configure-server-endpoints.md#prerequisites-for-windows-server-2016[Prerequisites for Windows Server 2016].
. Ensure third-party antivirus management no longer pushes antivirus agents to these machines.*
. Author your policies for the protection capabilities in Microsoft Defender for Endpoint and target those to the machine in the tool of your choice.*
. Install the Microsoft Defender for Endpoint for Windows Server 2012 R2 and 2016 package and *enable passive mode*.
See link:configure-server-endpoints.md#install-microsoft-defender-for-endpoint-using-the-command-line[Install Microsoft Defender Antivirus using command line].
a.
Apply the onboarding script *for use with Group Policy* downloaded from https://security.microsoft.com[Microsoft 365 Defender].
. Apply updates.
. Remove your non-Microsoft antivirus software by either using the non-Microsoft antivirus console or by using Microsoft Endpoint Configuration Manager as appropriate.
Make sure to remove passive mode configuration.*

____
[!TIP] You can use the link:server-migration.md#installer script[installer-script] as part of your application to automate the above steps.
To enable passive mode, apply the -Passive flag.
For example, .\install.ps1 -RemoveMMA +++<YOUR_WORKSPACE_ID>+++-OnboardingScript ".\WindowsDefenderATPOnboardingScript.cmd" -Passive+++</YOUR_WORKSPACE_ID>+++
____

*These steps only apply if you intend to replace your non-Microsoft antivirus solution.
See xref:why-use-microsoft-defender-antivirus.adoc[Better together: Microsoft Defender Antivirus and Microsoft Defender for Endpoint].

To move a machine out of passive mode, set the following key to 0:

Path: HKLM\SOFTWARE\Policies\Microsoft\Windows Advanced Threat Protection  Name: ForceDefenderPassiveMode Type: REG_DWORD Value: 0

=== If you are running System Center Endpoint Protection but are not managing the machine using Microsoft Endpoint Configuration Manager (MECM/ConfigMgr)

. Fully update the machine including Microsoft Defender Antivirus (Windows Server 2016) ensuring link:configure-server-endpoints.md#prerequisites[prerequisites] have been met.
. Create and apply policies using Group Policy, PowerShell, or a 3rd party management solution.
. Uninstall System Center Endpoint Protection (Windows Server 2012 R2).
. Install Microsoft Defender for Endpoint (see xref:configure-server-endpoints.adoc[Configure server endpoints].)
. Apply the onboarding script *for use with Group Policy* downloaded from https://security.microsoft.com[Microsoft 365 Defender].
. Apply updates.

____
[!TIP] You can use the installer script to automate the above steps.
____

=== Microsoft Defender for Cloud scenarios

==== You're using Microsoft Defender for Cloud. The Microsoft Monitoring Agent (MMA) and/or Microsoft Antimalware for Azure (SCEP) are installed and you want to upgrade.

If you're using Microsoft Defender for Cloud, you can leverage the automated upgrade process.
See link:/azure/security-center/security-center-wdatp#enable-the-microsoft-defender-for-endpoint-integration[Protect your endpoints with Defender for Cloud's integrated EDR solution: Microsoft Defender for Endpoint].

=== Group Policy configuration

For configuration using Group Policy, ensure you're using the latest ADMX files in your central store to access the correct Defender for Endpoint policy options.
Please reference link:/troubleshoot/windows-client/group-policy/create-and-manage-central-store[How to create and manage the Central Store for Group Policy Administrative Templates in Windows] and download the latest files *for use with Windows 10*.
