= 
dansimp
:keywords: apis, graph api, supported apis, tags, machine tags

== Set device value API

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Set the device value of a specific link:machine.md[Machine]. See
link:tvm-assign-device-value.md[assign device values] for more
information.

=== Limitations

[arabic]
. You can post on devices last seen according to your configured
retention period.
. Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Microsoft Defender for Endpoint APIs]

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Machine.ReadWrite.All |`Read and write all machine
information'

|Delegated (work or school account) |Machine.ReadWrite |`Read and write
machine information'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to have at least the following role permission: `Manage
security setting'. For more (See link:user-roles.md[Create and manage
roles] for more information)
* The user needs to have access to the machine, based on machine group
settings (See link:machine-groups.md[Create and manage machine groups]
for more information)
____

=== HTTP request

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/machines/{machineId}/setDeviceValue
----

=== Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|Content-Type |string |application/json. *Required*.
|===

=== Request body

In the request body, supply a JSON object with the following parameters:

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Parameter |Type |Description
|DeviceValue |Enum |Device value. Allowed values are: `Normal', `Low'
and `High'. *Required*.
|===

=== Response

If successful, this method returns 200 - Ok response code and the
updated Machine in the response body.

=== Example

==== Request

Here is an example of a request that adds machine tag.

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/machines/1e5bc9d7e413ddd7902c2932e418702b84d0cc07/setDeviceValue
----

[source,json]
----
{
  "DeviceValue" : "High"
}
----
