= 
mjcaparas
:keywords: apis, graph api, supported apis, stop and quarantine file

== Stop and quarantine file API

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Stop execution of a file on a device and delete it.

=== Limitations

[arabic]
. Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.

{empty}[!includelink:../../includes/machineactionsnote.md[Device actions
note]]

____
[!IMPORTANT] You can only take this action if:

* The device you’re taking the action on is running Windows 10, version
1703 or later, or Windows 11
* The file does not belong to trusted third-party publishers or is not
signed by Microsoft
* Microsoft Defender Antivirus must at least be running on Passive mode.
For more information, see
link:/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility[Microsoft
Defender Antivirus compatibility].
____

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Use
Microsoft Defender for Endpoint APIs]

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Machine.StopAndQuarantine |`Stop And Quarantine'

|Application |Machine.Read.All |`Read all machine profiles'

|Application |Machine.ReadWrite.All |`Read and write all machine
information'

|Delegated (work or school account) |Machine.StopAndQuarantine |`Stop
And Quarantine'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to have at least the following role permission: `Active
remediation actions' (See link:user-roles.md[Create and manage roles]
for more information)
* The user needs to have access to the device, based on device group
settings (See link:machine-groups.md[Create and manage device groups]
for more information)

Device group creation is supported in Defender for Endpoint Plan 1 and
Plan 2.
____

=== HTTP request

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/machines/{id}/StopAndQuarantineFile
----

=== Request headers

[cols="<,<,<",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer \{token}. *Required*.
|Content-Type |string |application/json. *Required*.
|===

=== Request body

In the request body, supply a JSON object with the following parameters:

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Parameter |Type |Description
|Comment |String |Comment to associate with the action. *Required*.

|Sha1 |String |Sha1 of the file to stop and quarantine on the device.
*Required*.
|===

=== Response

If successful, this method returns 201 - Created response code and
link:machineaction.md[Machine Action] in the response body.

=== Example

==== Request

Here is an example of the request.

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/machines/1e5bc9d7e413ddd7902c2932e418702b84d0cc07/StopAndQuarantineFile 
----

[source,json]
----
{
  "Comment": "Stop and quarantine file on machine due to alert 441688558380765161_2136280442",
  "Sha1": "87662bc3d60e4200ceaf7aae249d1c343f4b83c9"
}
----
