= Troubleshoot problems with Network protection
:audience: ITPro
:author: dansimp
:description: Resources and sample code to troubleshoot issues with Network protection in Microsoft Defender for Endpoint.
:keywords: troubleshoot, error, fix, windows defender eg, asr, rules, hips, troubleshoot, audit, exclusion, false positive, broken, blocking, Microsoft Defender for Endpoint
:manager: dansimp
:ms.author: dansimp
:ms.collection: M365-security-compliance
:ms.localizationpriority: medium
:ms.mktglfcycl: manage
:ms.pagetype: security
:ms.reviewer: oogunrinde
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: how-to
:search.appverid: met150

== Troubleshoot network protection

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
[!TIP] Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-pullalerts-abovefoldlink[Sign up for a free trial.]
____

This article provides troubleshooting information for xref:network-protection.adoc[network protection], in cases, such as:

* Network protection blocks a website that is safe (false positive)
* Network protection fails to block a suspicious or known malicious website (false negative)

There are four steps to troubleshooting these problems:

. Confirm prerequisites
. Use audit mode to test the rule
. Add exclusions for the specified rule (for false positives)
. Submit support logs

=== Confirm prerequisites

Network protection will only work on devices with the following conditions:

____
[!div class="checklist"]

* Endpoints are running Windows 10 Pro or Enterprise edition, version 1709 or higher.
* Endpoints are using Microsoft Defender Antivirus as the sole antivirus protection app.
link:/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility[See what happens when you're using a non-Microsoft antivirus solution].
* link:/windows/security/threat-protection/microsoft-defender-antivirus/configure-real-time-protection-microsoft-defender-antivirus[Real-time protection] is enabled.
* link:/windows/security/threat-protection/microsoft-defender-antivirus/enable-cloud-protection-microsoft-defender-antivirus[Cloud-delivered protection] is enabled.
* Audit mode isn't enabled.
Use link:enable-network-protection.md#group-policy[Group Policy] to set the rule to *Disabled* (value: *0*).
____

=== Use audit mode

You can enable network protection in audit mode and then visit a website that we've created to demo the feature.
All website connections will be allowed by network protection but an event will be logged to indicate any connection that would have been blocked if network protection was enabled.

. Set network protection to *Audit mode*.
+
[,powershell]
----
Set-MpPreference -EnableNetworkProtection AuditMode
----

. Perform the connection activity that is causing an issue (for example, attempt to visit the site, or connect to the IP address you do or don't want to block).
. link:network-protection.md#review-network-protection-events-in-windows-event-viewer[Review the network protection event logs] to see if the feature would have blocked the connection if it had been set to *Enabled*.
+
If network protection isn't blocking a connection that you're expecting it should block, enable the feature.
+
[,powershell]
----
Set-MpPreference -EnableNetworkProtection Enabled
----

=== Report a false positive or false negative

If you've tested the feature with the demo site and with audit mode, and network protection is working on pre-configured scenarios, but isn't working as expected for a specific connection, use the https://www.microsoft.com/wdsi/filesubmission[Windows Defender Security Intelligence web-based submission form] to report a false negative or false positive for network protection.
With an E5 subscription, you can also xref:alerts-queue.adoc[provide a link to any associated alert].

See xref:defender-endpoint-false-positives-negatives.adoc[Address false positives/negatives in Microsoft Defender for Endpoint].

=== Add exclusions

The current exclusion options are:

. Setting up a custom allow indicator.
. Using IP exclusions: `Add-MpPreference -ExclusionIpAddress 192.168.1.1`
. Excluding an entire process.
For more information, see xref:configure-exclusions-microsoft-defender-antivirus.adoc[Microsoft Defender Antivirus exclusions].

=== Collect diagnostic data for file submissions

When you report a problem with network protection, you're asked to collect and submit diagnostic data that can be used by Microsoft support and engineering teams to help troubleshoot issues.

. Open an elevated command prompt and change to the Windows Defender directory:
+
[,console]
----
cd c:\program files\windows defender
----

. Run this command to generate the diagnostic logs:
+
[,console]
----
mpcmdrun -getfiles
----

. Attach the file to the submission form.
By default, diagnostic logs are saved at `C:\ProgramData\Microsoft\Windows Defender\Support\MpSupportFiles.cab`.

=== Resolve connectivity issues with network protection (for E5 customers)

Due to the environment where network protection runs, Microsoft is unable to see your operating system proxy settings.
In some cases, network protection clients are unable to reach the cloud service.
To resolve connectivity issues with network protection, configure one of the following registry keys so that network protection becomes aware of the proxy configuration:

[,powershell]
----
Set-MpPreference -ProxyServer <proxy IP address: Port>
----

--OR--

[,powershell]
----
Set-MpPreference -ProxyPacUrl <Proxy PAC url>
----

You can configure the registry key by using PowerShell, Microsoft Endpoint Manager, or Group Policy.
Here are some resources to help:

* link:/powershell/scripting/samples/working-with-registry-keys[Working with Registry Keys]
* link:/mem/configmgr/protect/deploy-use/endpoint-protection-configure-client[Configure custom client settings for Endpoint Protection]
* link:/mem/configmgr/protect/deploy-use/endpoint-protection-group-policies[Use Group Policy settings to manage Endpoint Protection]

=== See also

* xref:network-protection.adoc[Network protection]
* link:network-protection.md#network-protection-and-the-tcp-three-way-handshake[Network protection and the TCP three-way handshake]
* xref:evaluate-network-protection.adoc[Evaluate network protection]
* xref:enable-network-protection.adoc[Enable network protection]
* xref:defender-endpoint-false-positives-negatives.adoc[Address false positives/negatives in Defender for Endpoint]
