= 
jweston-1
:keywords: troubleshoot, error, fix, windows defender eg, asr, rules,
hips, troubleshoot, audit, exclusion, false positive, broken, blocking,
Microsoft Defender for Endpoint

== Troubleshoot attack surface reduction rules

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-pullalerts-abovefoldlink[Sign
up for a free trial.]
____

When you use link:attack-surface-reduction.md[attack surface reduction
rules] you may run into issues, such as:

* A rule blocks a file, process, or performs some other action that it
shouldn’t (false positive)
* A rule doesn’t work as described, or doesn’t block a file or process
that it should (false negative)

There are four steps to troubleshooting these problems:

[arabic]
. link:#confirm-prerequisites[Confirm prerequisites]
. link:#use-audit-mode-to-test-the-rule[Use audit mode to test the rule]
. link:#add-exclusions-for-a-false-positive[Add exclusions for the
specified rule] (for false positives)
. link:#collect-diagnostic-data-for-file-submissions[Submit support
logs]

=== Confirm prerequisites

Attack surface reduction rules will only work on devices with the
following conditions:

* Endpoints are running Windows 10 Enterprise, version 1709 (also known
as the Fall Creators Update).
* Endpoints are using Microsoft Defender Antivirus as the sole antivirus
protection app.
link:/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility[Using
any other antivirus app will cause Microsoft Defender Antivirus to
disable itself].
* link:/windows/security/threat-protection/microsoft-defender-antivirus/configure-real-time-protection-microsoft-defender-antivirus[Real-time
protection] is enabled.
* Audit mode isn’t enabled. Use Group Policy to set the rule to
*Disabled* (value: *0*) as described in
link:enable-attack-surface-reduction.md[Enable attack surface reduction
rules].

If these prerequisites have all been met, proceed to the next step to
test the rule in audit mode.

=== Use audit mode to test the rule

Follow these instructions in
link:evaluate-attack-surface-reduction.md[Use the demo tool to see how
attack surface reduction rules work] to test the specific rule you’re
encountering problems with.

[arabic]
. Enable audit mode for the specific rule you want to test. Use Group
Policy to set the rule to *Audit mode* (value: *2*) as described in
link:enable-attack-surface-reduction.md[Enable attack surface reduction
rules]. Audit mode allows the rule to report the file or process, but
will still allow it to run.
. Perform the activity that is causing an issue (for example, open or
execute the file or process that should be blocked but is being
allowed).
. link:attack-surface-reduction.md[Review the attack surface reduction
rule event logs] to see if the rule would have blocked the file or
process if the rule had been set to *Enabled*.

If a rule isn’t blocking a file or process that you’re expecting it
should block, first check if audit mode is enabled.

Audit mode may have been enabled for testing another feature, or by an
automated PowerShell script, and may not have been disabled after the
tests were completed.

If you’ve tested the rule with the demo tool and with audit mode, and
attack surface reduction rules are working on pre-configured scenarios,
but the rule isn’t working as expected, proceed to either of the
following sections based on your situation:

[arabic]
. If the attack surface reduction rule is blocking something that it
shouldn’t block (also known as a false positive), you can
link:#add-exclusions-for-a-false-positive[first add an attack surface
reduction rule exclusion].
. If the attack surface reduction rule isn’t blocking something that it
should block (also known as a false negative), you can proceed
immediately to the last step,
link:#collect-diagnostic-data-for-file-submissions[collecting diagnostic
data and submitting the issue to us].

=== Add exclusions for a false positive

If the attack surface reduction rule is blocking something that it
shouldn’t block (also known as a false positive), you can add exclusions
to prevent attack surface reduction rules from evaluating the excluded
files or folders.

To add an exclusion, see
link:attack-surface-reduction-rules-deployment-implement.md#customize-attack-surface-reduction-rules[Customize
Attack surface reduction].

____
[!IMPORTANT] You can specify individual files and folders to be
excluded, but you cannot specify individual rules. This means any files
or folders that are excluded will be excluded from all ASR rules.
____

=== Report a false positive or false negative

Use the
https://www.microsoft.com/wdsi/support/report-exploit-guard[Windows
Defender Security Intelligence web-based submission form] to report a
false negative or false positive for network protection. With a Windows
E5 subscription, you can also link:alerts-queue.md[provide a link to any
associated alert].

=== Collect diagnostic data for file submissions

When you report a problem with attack surface reduction rules, you’re
asked to collect and submit diagnostic data that can be used by
Microsoft support and engineering teams to help troubleshoot issues.

[arabic]
. Open an elevated command prompt and change to the Windows Defender
directory:
+
[source,console]
----
cd "c:\program files\windows defender"
----
. Run this command to generate the diagnostic logs:
+
[source,console]
----
mpcmdrun -getfiles
----
. By default, they’re saved to
`C:\ProgramData\Microsoft\Windows Defender\Support\MpSupportFiles.cab`.
Attach the file to the submission form.

=== Related articles

* link:attack-surface-reduction.md[Attack surface reduction rules]
* link:enable-attack-surface-reduction.md[Enable attack surface
reduction rules]
* link:evaluate-attack-surface-reduction.md[Evaluate attack surface
reduction rules]
