= Troubleshoot Microsoft Defender Antivirus while migrating from a third-party solution
:author: martyav
:description: Troubleshoot common errors when migrating to Microsoft Defender Antivirus
:keywords: event, error code, logging, troubleshooting, microsoft defender antivirus, windows defender antivirus, migration, microsoft defender antivirus
:manager: dansimp
:ms.author: deniseb
:ms.collection: M365-security-compliance
:ms.custom: nextgen
:ms.localizationpriority: medium
:ms.mktglfcycl: manage
:ms.reviewer:
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Troubleshoot Microsoft Defender Antivirus while migrating from a third-party solution

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://www.microsoft.com/windows/comprehensive-security[Microsoft Defender Antivirus]

*Platforms*

* Windows

You can find help here if you encounter issues while migrating from a third-party security solution to Microsoft Defender Antivirus.

=== Review event logs

. Open the Event viewer app by selecting the *Search* icon in the taskbar, and searching for _event viewer_.
+
Information about Microsoft Defender Antivirus can be found under  *Applications and Services Logs* > *Microsoft* > *Windows* > *Windows Defender*.

. From there, select *Open* underneath *Operational*.
+
Selecting an event from the details pane will show you more information about an event in the lower pane, under the *General* and *Details* tabs.

=== Microsoft Defender Antivirus won't start

This issue can manifest in the form of  several different event IDs, all of which have the same underlying cause.

==== Associated event IDs

|===
| Event ID | Log name | Description | Source

| 15
| Application
| Updated Windows Defender status successfully to SECURITY_PRODUCT_STATE_OFF.
| Security Center

| 5007
| Microsoft-Windows-Windows Defender/Operational
| Microsoft Defender Antivirus Configuration has changed.
If this is an unexpected event you should review the settings as this may be the result of malware.
<p> *Old value:* Default\IsServiceRunning = 0x0 <p> *New value:* HKLM\SOFTWARE\Microsoft\Windows Defender\IsServiceRunning = 0x1
| Windows Defender

| 5010
| Microsoft-Windows-Windows Defender/Operational
| Microsoft Defender Antivirus scanning for spyware and other potentially unwanted software is disabled.
| Windows Defender
|===

==== How to tell if Microsoft Defender Antivirus won't start because a third-party antivirus is installed

On a Windows 10 or Windows 11 device, if you are not using Microsoft Defender for Endpoint, and you have a third-party antivirus installed, then Microsoft Defender Antivirus will be automatically turned off.
If you are using Microsoft Defender for Endpoint with a third-party antivirus installed, Microsoft Defender Antivirus will start in passive mode, with reduced functionality.

____
[!TIP] The scenario just described applies only to Windows 10 and Windows 11.
Other versions of Windows have xref:microsoft-defender-antivirus-compatibility.adoc[different responses] to Microsoft Defender Antivirus being run alongside third-party security software.
____

===== Use Services app to check if Microsoft Defender Antivirus is turned off

To open the Services app, select the *Search* icon from the taskbar and search for _services_.
You can also open the app from the command-line by typing _services.msc_.

Information about Microsoft Defender Antivirus will be listed within the Services app under *Windows Defender* > *Operational*.
The antivirus service name is _Microsoft Defender Antivirus Service_.

While checking the app, you may see that _Microsoft Defender Antivirus Service_ is set to manual, but when you try to start this service manually, you get a warning stating, _The Microsoft Defender Antivirus Service service on Local Computer started and then stopped.
Some services stop automatically if they are not in use by other services or programs._

This indicates that Microsoft Defender Antivirus has been automatically turned off to preserve compatibility with a third-party antivirus.

===== Generate a detailed report

You can generate a detailed report about currently active group policies by opening a command prompt in *Run as admin* mode, then entering the following command:

[,console]
----
GPresult.exe /h gpresult.html
----

This will generate a report located at _./gpresult.html_.
Open this file and you might see the following results, depending on how Microsoft Defender Antivirus was turned off.

====== Group policy results

====== If security settings are implemented via group policy (GPO) at the domain or local level, or though System center configuration manager (SCCM)

Within the GPResults report, under the heading, _Windows Components/Microsoft Defender Antivirus_, you may see something like the following entry, indicating that Microsoft Defender Antivirus is turned off.

|===
| Policy | Setting | Winning GPO

| Turn off Microsoft Defender Antivirus
| Enabled
| Win10-Workstations
|===

======= If security settings are implemented via Group policy preference (GPP)

Under the heading, _Registry item (Key path: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender, Value name: DisableAntiSpyware)_, you may see something like the following entry, indicating that Microsoft Defender Antivirus is turned off.

|===
| DisableAntiSpyware | -

| Winning GPO
| Win10-Workstations

| Result: Success
|

| *General*
|

| Action
| Update

| *Properties*
|

| Hive
| HKEY_LOCAL_MACHINE

| Key path
| SOFTWARE\Policies\Microsoft\Windows Defender

| Value name
| DisableAntiSpyware

| Value type
| REG_DWORD

| Value data
| 0x1 (1)
|===

======= If security settings are implemented via registry key

The report may contain the following text, indicating that Microsoft Defender Antivirus is turned off:

____
Registry (regedit.exe)

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender DisableAntiSpyware (dword) 1 (hex)
____

======= If security settings are set in Windows or your Windows Server image

Your imagining admin might have set the security policy, *link:/windows-hardware/customize/desktop/unattend/security-malware-windows-defender-disableantispyware[DisableAntiSpyware]*, locally via _GPEdit.exe_, _LGPO.exe_, or by modifying the registry in their task sequence.
You can link:/windows-hardware/manufacture/desktop/configure-a-trusted-image-identifier-for-windows-defender[configure a Trusted Image Identifier] for Microsoft Defender Antivirus.

==== Turn Microsoft Defender Antivirus back on

Microsoft Defender Antivirus will automatically turn on if no other antivirus is currently active.
You'll need to turn the third-party antivirus completely off to ensure Microsoft Defender Antivirus can run with full functionality.

____
[!WARNING] Solutions suggesting that you edit the _Windows Defender_ start values for _wdboot_, _wdfilter_, _wdnisdrv_, _wdnissvc_, and _windefend_ in  HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services are unsupported, and may force you to re-image your system.
____

Passive mode is available if you start using Microsoft Defender for Endpoint and a third-party antivirus together with Microsoft Defender Antivirus.
Passive mode allows Microsoft Defender Antivirus to scan files and update itself, but it will not remediate threats.
In addition, behavior monitoring via xref:configure-real-time-protection-microsoft-defender-antivirus.adoc[Real Time Protection] is not available under passive mode, unless link:/microsoft-365/security/defender-endpoint/information-protection-in-windows-overview[Endpoint data loss prevention (DLP)] is deployed.

Another feature, known as xref:limited-periodic-scanning-microsoft-defender-antivirus.adoc[limited periodic scanning], is available to end-users when Microsoft Defender Antivirus is set to automatically turn off.
This feature allows Microsoft Defender Antivirus to scan files periodically alongside a third-party antivirus, using a limited number of detections.

____
[!IMPORTANT] Limited periodic scanning is not recommended in enterprise environments.
The detection, management and reporting capabilities available when running Microsoft Defender Antivirus in this mode are reduced as compared to active mode.
____

____
[!TIP] If you're looking for Antivirus related information for other platforms, see:

* xref:mac-preferences.adoc[Set preferences for Microsoft Defender for Endpoint on macOS]
* xref:microsoft-defender-endpoint-mac.adoc[Microsoft Defender for Endpoint on Mac]
* link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS Antivirus policy settings for Microsoft Defender Antivirus for Intune]
* xref:linux-preferences.adoc[Set preferences for Microsoft Defender for Endpoint on Linux]
* xref:microsoft-defender-endpoint-linux.adoc[Microsoft Defender for Endpoint on Linux]
* xref:android-configure.adoc[Configure Defender for Endpoint on Android features]
* xref:ios-configure-features.adoc[Configure Microsoft Defender for Endpoint on iOS features]
____

==== See also

* xref:microsoft-defender-antivirus-compatibility.adoc[Microsoft Defender Antivirus compatibility]
* xref:microsoft-defender-security-center-antivirus.adoc[Microsoft Defender Antivirus in the Windows Security app]
