= Troubleshooting mode scenarios in Microsoft Defender for Endpoint
:audience: ITPro
:author: dansimp
:description: Use the Microsoft Defender for Endpoint troubleshooting mode to address various antivirus issues.
:keywords: antivirus, troubleshoot, troubleshooting mode, tamper protection, compatibility
:manager: dansimp
:ms.author: dansimp
:ms.collection: ["m365-security-compliance"]
:ms.localizationpriority: medium
:ms.mktglfcycl: manage
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150
:search.product: eADQiWindows 10XVcnh

== Troubleshooting mode scenarios in Microsoft Defender for Endpoint

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint]

____
Want to experience Defender for Endpoint?
https://www.microsoft.com/WindowsForBusiness/windows-atp?ocid=docs-wdatp-configureendpointsscript-abovefoldlink[Sign up for a free trial.]
____

Microsoft Defender for Endpoint troubleshooting mode allows you to troubleshoot various Microsoft Defender Antivirus features by enabling them from the device and testing different scenarios, even if they're controlled by the organization policy.
The troubleshooting mode is disabled by default and requires you to turn it on for a device (and/or group of devices) for a limited time.
Note that this is exclusively an enterprise-only feature, and requires Microsoft 365 Defender access.

=== Scenario 1: Unable to install application

If you want to install an application but receive an error message that Microsoft Defender Antivirus and tamper protection is on, follow the steps below to troubleshoot the issue.

. Request the security admin to turn on troubleshooting mode.
You'll get a Windows Security notification once the troubleshooting mode starts.
. Connect to the device (using Terminal Services for example) with local admin permissions.
. Start Process Monitor (ProcMon).
See the steps described in xref:troubleshoot-performance-issues.adoc[Troubleshoot performance issues related to real-time protection].
. Go to *Windows security* > *Threat & virus protection* > *Manage settings* > *Tamper protection* > *Off*.
. Launch an elevated PowerShell command prompt, and toggle off RTP.
 ** Run `Get-MpComputerStatus` to check the RealTimeProtection status.
 ** Run `Set-mppreference -DisableRealtimeMonitoring $true` to turn off RTP.
 ** Run `Get-MpComputerStatus` again to verify to RealTimeProtection status.
. Try installing the application.

=== Scenario 2: High CPU usage due to Windows Defender (MsMpEng.exe)

Sometimes during a scheduled scan, MsMpEng.exe can consume high CPU.

. Go to *Task Manager* > *Details* tab to confirm that MsMpEng.exe is the reason behind the high CPU usage.
Also check to see if a scheduled scan is currently underway.
. Run ProcMon during the CPU spike for around 5 minutes, and then review the ProcMon log for clues.
. Once root cause is determined, turn on troubleshooting mode.
. Log in to the machine and launch an elevated PowerShell command prompt.
. Add process/file/folder/extension exclusions based on ProcMon findings using one of the following commands (the path, extension, and process exclusions mentioned below are examples only):
 ** `Set-mppreference -ExclusionPath` (for example, C:\DB\DataFiles)
 ** `Set-mppreference –ExclusionExtension` (for example, .dbx)
 ** `Set-mppreference –ExclusionProcess` (for example, C:\DB\Bin\Convertdb.exe)
. After adding the exclusion, check to see if the CPU usage has dropped.

For more information on Set-MpPreference cmdlet configuration preferences for Windows Defender scans and updates, see link:/powershell/module/defender/set-mppreference[Set-MpPreference].

=== Scenario 3: Application taking longer to perform an action

When Microsoft Defender Antivirus real-time protection is turned on, application takes a long time to perform basic tasks.
To turn off real-time protection and troubleshoot the issue, follow the steps below.

. Request security admin to turn on troubleshooting mode on the device.
. To disable RTP for this scenario, first turn off tamper protection.
For more information, see xref:prevent-changes-to-security-settings-with-tamper-protection.adoc[Protect security settings with tamper protection].
. Once tamper protection is disabled, log in to the device.
. Launch an elevated PowerShell command prompt.
 ** `Set-mppreference -DisableRealtimeMonitoring $true`
. After disabling RTP, check to see if the application is slow.

=== Scenario 4: Microsoft Office plugin blocked by Attack Surface Reduction

Attack Surface Reduction (ASR) is not allowing Microsoft Office plugin to work properly because *Block all Office applications from creating child processes* is set to block mode.

. Turn on troubleshooting mode, and log in to the device.
. Launch an elevated PowerShell command prompt.
 ** `Set-MpPreference -AttackSurfaceReductionRules_Ids D4F940AB-401B-4EFC-AADC-AD5F3C50688A -AttackSurfaceReductionRules_Actions Disabled`
. After disabling the ASR Rule, confirm that the Microsoft Office plugin now works.

For more information, see xref:overview-attack-surface-reduction.adoc[Overview of attack surface reduction].

=== Scenario 5: Domain blocked by Network Protection

Network Protection is blocking Microsoft domain, preventing users from accessing it.

. Turn on troubleshooting mode, and log in to the device.
. Launch an elevated PowerShell command prompt.
 ** `Set-MpPreference -EnableNetworkProtection Disabled`
. After disabling Network Protection, check to see if the domain is now allowed.

For more information, see xref:network-protection.adoc[Use network protection to help prevent connections to bad sites].

=== Related topics

* xref:enable-troubleshooting-mode.adoc[Enable troubleshooting mode]
* xref:prevent-changes-to-security-settings-with-tamper-protection.adoc[Protect security settings with tamper protection]
* link:/powershell/module/defender/set-mppreference[Set-MpPreference]
* xref:network-protection.adoc[Protect your network]
* xref:overview-attack-surface-reduction.adoc[Overview of attack surface reduction]
* xref:detect-block-potentially-unwanted-apps-microsoft-defender-antivirus.adoc[Detect and block potentially unwanted applications]
* link:/microsoft-365/security/defender-endpoint/[Get an overview of Microsoft Defender for Endpoint]
* xref:why-use-microsoft-defender-antivirus.adoc[Better together: Microsoft Defender Antivirus and Microsoft Defender for Endpoint]
