= Troubleshoot SIEM tool integration issues in Microsoft Defender for Endpoint
:audience: ITPro
:author: mjcaparas
:description: Troubleshoot issues that might arise when using SIEM tools with Microsoft Defender for Endpoint.
:keywords: troubleshoot, siem, client secret, secret
:manager: dansimp
:ms.author: macapara
:ms.collection: M365-security-compliance
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: troubleshooting
:search.appverid: met150

== Troubleshoot SIEM tool integration issues

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-pullalerts-abovefoldlink[Sign up for a free trial.]
____

You might need to troubleshoot issues while pulling detections in your SIEM tools.

This page provides detailed steps to troubleshoot issues you might encounter.

=== Learn how to get a new client secret

If your client secret expires or if you've misplaced the copy provided when you were enabling the SIEM tool application,  you'll need to get a new secret.

. Login to the https://portal.azure.com[Azure management portal].
. Select *Azure Active Directory*.
. Select your tenant.
. Click *App registrations*.
Then in the applications list, select the application.
. Select *Certificates & Secrets* section, Click on New Client Secret, then provide a description and specify the validity duration.
. Click *Save*.
The key value is displayed.
. Copy the value and save it in a safe place.

=== Error when getting a refresh access token

If you encounter an error when trying to get a refresh token when using the threat intelligence API or SIEM tools, you'll need to add reply URL for relevant application in Azure Active Directory.

. Login to the https://ms.portal.azure.com[Azure management portal].
. Select *Azure Active Directory*.
. Select your tenant.
. Click *App Registrations*.
Then in the applications list, select the application.
. Add the following URL:
 ** For the European Union: `+https://winatpmanagement-eu.securitycenter.windows.com/UserAuthenticationCallback+`
 ** For the United Kingdom: `+https://winatpmanagement-uk.securitycenter.windows.com/UserAuthenticationCallback+`
 ** For the United States:  `+https://winatpmanagement-us.securitycenter.windows.com/UserAuthenticationCallback+`.
. Click *Save*.

=== Error while enabling the SIEM connector application

If you encounter an error when trying to enable the SIEM connector application, check the pop-up blocker settings of your browser.
It might be blocking the new window being opened when you enable the capability.

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-troubleshootsiem-belowfoldlink[Sign up for a free trial.]
____

=== Related topics

* xref:configure-siem.adoc[Pull detections to your SIEM tools]
