= 
denisebmsft
:keywords: MMA, agent, azure log

== Updating MMA on Windows devices for Microsoft Defender for Endpoint

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

If you’re using the Microsoft Monitoring Agent (MMA) on Windows devices,
it’s important to keep this agent updated. For Windows Server 2012 R2
and Windows Server 2016, Microsoft recommends upgrading to the new,
unified agent for Defender for Endpoint. This article describes how to:

* *link:#update-mma-on-your-devices[Update the MMA on your devices]*
(for devices running Windows 7 SP1 Enterprise, Windows 7 SP1 Pro,
Windows 8.1 Pro, Windows 8.1 Enterprise, and Windows Server 2008 R2
SP1).
* *link:#upgrade-to-the-new-unified-agent-for-defender-for-endpoint[Upgrade
to the new&#44; unified agent for Defender for Endpoint]* (for devices
running Windows Server 2012 R2 and Windows Server 2016).

=== Update MMA on your devices

_This option applies to devices running Windows 7 SP1 Enterprise,
Windows 7 SP1 Pro, Windows 8.1 Pro, Windows 8.1 Enterprise, and Windows
Server 2008 R2 SP1._

* See
link:/azure/azure-monitor/agents/agent-manage?tabs=PowerShellLinux[Manage
and maintain the Log Analytics agent for Windows and Linux] for
instructions on how to upgrade the agent using Azure Automation or a
command line approach for use with various deployment tools and methods
at your disposal.
* Update MMA by using
link:/windows/deployment/update/how-windows-update-works[Microsoft
Update], through
link:/windows/deployment/update/waas-manage-updates-wsus[Windows Server
Update Services] or
link:/mem/configmgr/osd/deploy-use/manage-windows-as-a-service[Configuration
Manager]. Use the method that was configured when MMA was first
installed on the device.
* Download the MMA setup file:
** *Windows 64-bit agent*:
https://go.microsoft.com/fwlink/?LinkId=828603
** *Windows 32-bit agent*:
https://go.microsoft.com/fwlink/?LinkId=828604

=== Upgrade to the new, unified agent for Defender for Endpoint

_This option applies to servers running Windows Server 2012 R2 and
Windows Server 2016._

A new agent was released in April 2022 for Windows Server 2012 R2 and
Windows Server 2016. The new agent doesn’t depend on MMA. There are
significant benefits to moving to this new agent, such as a vastly
extended feature set. To learn more, see
https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/defending-windows-server-2012-r2-and-2016/ba-p/2783292[Tech
Community Blog: Defending Windows Server 2012 R2 and 2016].

* Microsoft Defender Vulnerability Management provides an assessment
(SCID-2030) titled ``Update Microsoft Defender for Endpoint core
components'' that will allow you to track which Windows Server 2012 R2
and 2016 machines haven’t yet been upgraded.
* See link:server-migration.md[Server migration scenarios from the
previous&#44; MMA-based Microsoft Defender for Endpoint solution] to
understand your options for upgrading to the new agent.
* If you’re using Microsoft Endpoint Configuration Manager
(SCCM/ConfigMgr) 2107 or later to manage your servers running Windows
Server 2012 R2 or Windows Server 2016, see
link:application-deployment-via-mecm.md[Migrating servers from Microsoft
Monitoring Agent to the unified solution] to perform an *orchestrated*
upgrade.
* If you’re using Microsoft Endpoint Configuration Manager
(SCCM/ConfigMgr) 2207 or later to manage your servers running Windows
Server 2012 R2 or Windows Server 2016, see
link:/mem/configmgr/protect/deploy-use/defender-advanced-threat-protection[Onboarding
to Microsoft Defender for Endpoint with Configuration Manager 2207 and
later versions] to perform an *automated* upgrade.
* If you’re using Microsoft Defender for Cloud with servers running
Windows Server 2012 R2 or Windows Server 2016, you can automate the
upgrade by selecting *Enable unified solution*. See
link:/azure/defender-for-cloud/integration-defender-for-endpoint?tabs=windows[Users
with Defender for Servers enabled and Microsoft Defender for Endpoint
deployed].

=== Important information about MMA

* If you’ve determined that you aren’t using the MMA for Defender for
Endpoint, or you’ve already updated your agent, no other steps are
needed.
* If you are, however, still using MMA for other purposes (such as Log
Analytics), MMA is currently set to retire in August 2024. See
https://azure.microsoft.com/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/[We’re
retiring the Log Analytics agent in Azure Monitor on 31 August 2024].
Depending your particular scenario, this could be a good time to upgrade
to link:/azure/azure-monitor/agents/azure-monitor-agent-migration[Azure
Monitoring Agent&#44; the successor of MMA].

____
[!IMPORTANT] Devices running Windows 7 SP1, Windows 8.1, Windows Server
2008 R2, Windows Server 2012 R2, or Windows Server 2016 that haven’t
been upgraded to the link:application-deployment-via-mecm.md[new&#44;
unified solution] will remain dependent on MMA. In such cases,
link:/azure/azure-monitor/agents/agents-overview[AMA] cannot be used as
a substitute for Defender for Endpoint.
____

=== See also

* link:switch-to-mde-overview.md[Make the switch from non-Microsoft
endpoint protection to Microsoft Defender for Endpoint]
* link:deployment-phases.md[Microsoft Defender for Endpoint deployment
overview]
* link:onboarding.md[Onboard to the Microsoft Defender for Endpoint
service]
