= Update alert entity API
:audience: ITPro
:author: mjcaparas
:description: Learn how to update a Microsoft Defender for Endpoint alert by using this API. You can update the status, determination, classification, and assignedTo properties.
:keywords: apis, graph api, supported apis, get, alert, information, id
:manager: dansimp
:ms.author: macapara
:ms.collection: M365-security-compliance
:ms.custom: api
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Update alert

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign up for a free trial.]
____

[!Includexref:../../includes/microsoft-defender-api-usgov.adoc[Microsoft Defender for Endpoint API URIs for US Government]]

[!Includexref:../../includes/improve-request-performance.adoc[Improve request performance]]

=== API description

Updates properties of existing xref:alerts.adoc[Alert].

Submission of *comment* is available with or without updating properties.

Updatable properties are: `status`, `determination`, `classification`, and `assignedTo`.

=== Limitations

. You can update alerts that available in the API.
For more information, see xref:get-alerts.adoc[List Alerts].
. Rate limitations for this API are 100 calls per minute and 1500 calls per hour.

=== Permissions

One of the following permissions is required to call this API.
To learn more, including how to choose permissions, see xref:apis-intro.adoc[Use Microsoft Defender for Endpoint APIs]

|===
| Permission type | Permission | Permission display name

| Application
| Alerts.ReadWrite.All
| 'Read and write all alerts'

| Delegated (work or school account)
| Alert.ReadWrite
| 'Read and write alerts'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to have at least the following role permission: 'Alerts investigation' (For more information, see xref:user-roles.adoc[Create and manage roles] )
* The user needs to have access to the device associated with the alert, based on device group settings (For more information, see xref:machine-groups.adoc[Create and manage device groups]

Device group creation is supported in Defender for Endpoint Plan 1 and Plan 2.
____

=== HTTP request

[,http]
----
PATCH /api/alerts/{id}
----

=== Request headers

|===
| Name | Type | Description

| Authorization
| String
| Bearer \{token}.
*Required*.

| Content-Type
| String
| application/json.
*Required*.
|===

=== Request body

In the request body, supply the values for the relevant fields that should be updated.

Existing properties that aren't included in the request body will maintain their previous values or be recalculated based on changes to other property values.

For best performance, you shouldn't include existing values that haven't change.

|===
| Property | Type | Description

| Status
| String
| Specifies the current status of the alert.
The property values are: 'New', 'InProgress' and 'Resolved'.

| assignedTo
| String
| Owner of the alert

| Classification
| String
| Specifies the specification of the alert.
The property values are: `TruePositive`, `Informational, expected activity`, and `FalsePositive`.

| Determination
| String
| Specifies the determination of the alert.
<p>Possible determination values for each classification are: + <li> *True positive*: `Multistage attack` (MultiStagedAttack), `Malicious user activity` (MaliciousUserActivity), `Compromised account` (CompromisedUser) -- consider changing the enum name in public api accordingly, `Malware` (Malware), `Phishing` (Phishing), `Unwanted software` (UnwantedSoftware), and `Other` (Other).
<li> *Informational, expected activity:* `Security test` (SecurityTesting), `Line-of-business application` (LineOfBusinessApplication), `Confirmed activity` (ConfirmedUserActivity) - consider changing the enum name in public api accordingly, and `Other` (Other).
<li>  *False positive:* `Not malicious` (Clean) - consider changing the enum name in public api accordingly, `Not enough data to validate` (InsufficientData), and `Other` (Other).

| Comment
| String
| Comment to be added to the alert.
|===

____
[!NOTE] Around August 29, 2022, previously supported alert determination values ('Apt' and 'SecurityPersonnel') will be deprecated and no longer available via the API.
____

=== Response

If successful, this method returns 200 OK, and the xref:alerts.adoc[alert] entity in the response body with the updated properties.
If alert with the specified ID wasn't found - 404 Not Found.

=== Example

==== Request

Here's an example of the request.

[,http]
----
PATCH https://api.securitycenter.microsoft.com/api/alerts/121688558380765161_2136280442
----

[,json]
----
{
    "status": "Resolved",
    "assignedTo": "secop2@contoso.com",
    "classification": "FalsePositive",
    "determination": "Malware",
    "comment": "Resolve my alert and assign to secop2"
}
----
