= Update machine entity API
:audience: ITPro
:author: mjcaparas
:description: Learn how to update machine tags by using this API. You can update the tags and devicevalue properties.
:keywords: apis, graph api, supported apis, get, alert, information, id
:manager: dansimp
:ms.author: macapara
:ms.collection: M365-security-compliance
:ms.custom: api
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Update machine

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign up for a free trial.]
____

[!includexref:../../includes/microsoft-defender-api-usgov.adoc[Microsoft Defender for Endpoint API URIs for US Government]]

[!includexref:../../includes/improve-request-performance.adoc[Improve request performance]]

=== API description

Updates properties of existing xref:machine.adoc[Machine].

Updatable properties are: `machineTags` and `deviceValue`.

=== Limitations

. You can update machines that are available in the API.
. Update machine only appends tags to the tag collection.
If tags exist, they must be included in the tags collection in the body.
. Rate limitations for this API are 100 calls per minute and 1500 calls per hour.

=== Permissions

One of the following permissions is required to call this API.
To learn more, including how to choose permissions, see xref:apis-intro.adoc[Use Microsoft Defender for Endpoint APIs]

|===
| Permission type | Permission | Permission display name

| Application
| Machine.ReadWrite.All
| 'Read and write machine information for all machines'

| Delegated (work or school account)
| Machine.ReadWrite
| 'Read and write machine information'
|===

____
[!NOTE] When obtaining a token using user credentials:

* The user needs to have at least the following role permission: 'Alerts investigation'.
For more information, see xref:user-roles.adoc[Create and manage roles].
* The user needs to have access to the device associated with the alert, based on device group settings.
For more information, see xref:machine-groups.adoc[Create and manage device groups].

Device group creation is supported in Defender for Endpoint Plan 1 and Plan 2.
____

=== HTTP request

[,http]
----
PATCH /api/machines/{machineId}
----

=== Request headers

|===
| Name | Type | Description

| Authorization
| String
| Bearer \{token}.
*Required*.

| Content-Type
| String
| application/json.
*Required*.
|===

=== Request body

In the request body, supply the values for the relevant fields that should be updated.

Existing properties that are not included in the request body will maintain their previous values or be recalculated based on changes to other property values.

For best performance, you shouldn't include existing values that haven't change.

|===
| Property | Type | Description

| machineTags
| String collection
| Set of xref:machine.adoc[machine] tags.

| deviceValue
| Nullable Enum
| The xref:tvm-assign-device-value.adoc[value of the device].
Possible values are: 'Normal', 'Low' and 'High'.
|===

=== Response

If successful, this method returns 200 OK, and the xref:machine.adoc[machine] entity in the response body with the updated properties.

If machine tags collection in body doesn't contain existing machine tags - replaces all tags with the tags provided in the request body.

If machine with the specified ID was not found - 404 Not Found.

=== Example

==== Request

Here's an example of the request.

[,http]
----
PATCH https://api.securitycenter.microsoft.com/api/machines/{machineId}
----

[,json]
----
{
    "deviceValue": "Normal",
    "machineTags": [
                     "Demo Device",
                     "Generic User Machine - Attack Source",
                     "Windows 10" "Windows11",
                     "Windows Insider - Fast"
    ]
}
----
