= 
mjcaparas
:keywords: apis, graph api, supported apis, upload to library

== Upload files to the live response library

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
link:/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint[Microsoft
Defender for Endpoint]

{empty}[!includelink:../../includes/prerelease.md[Prerelease
information]]

____
Want to experience Microsoft Defender for Endpoint?
https://www.microsoft.com/microsoft-365/windows/microsoft-defender-atp?ocid=docs-wdatp-exposedapis-abovefoldlink[Sign
up for a free trial.]
____

{empty}[!includelink:../../includes/microsoft-defender-api-usgov.md[Microsoft
Defender for Endpoint API URIs for US Government]]

{empty}[!includelink:../../includes/improve-request-performance.md[Improve
request performance]]

=== API description

Upload file to live response library.

=== Limitations

[arabic]
. File max size limitation is 20MB.
. Rate limitations for this API are 100 calls per minute and 1500 calls
per hour.

=== Permissions

One of the following permissions is required to call this API. To learn
more, including how to choose permissions, see link:apis-intro.md[Get
started].

[width="100%",cols="43%,19%,38%",options="header",]
|===
|Permission type |Permission |Permission display name
|Application |Library.Manage |Manage live response library

|Delegated (work or school account) |Library.Manage |Manage live
response library
|===

=== HTTP request

Upload

[source,http]
----
POST https://api.securitycenter.microsoft.com/api/libraryfiles
----

=== Request headers

[cols=",,",options="header",]
|===
|Name |Type |Description
|Authorization |String |Bearer<token>. Required.
|Content-Type |string |multipart/form-data. Required.
|===

=== Request body

In the request body, supply a form-data object with the following
parameters:

[width="100%",cols="25%,14%,61%",options="header",]
|===
|Parameter |Type |Description
|File |File content |The file to be uploaded to live response
library.Required

|Description |String |Description of the file.

|ParametersDescription |String |(Optional) Parameters required for the
script to run. Default value is an empty string.

|OverrideIfExists |Boolean |(Optional) Whether to override the file if
it already exists. Default value is an empty string.
|===

=== Response

* If successful, this method returns 200 - OK response code and the
uploaded live response library entity in the response body.
* If not successful: this method returns 400 - Bad Request. +
Bad request usually indicates incorrect body.

=== Example

Request

Here is an example of the request using curl.

[source,curl]
----
curl -X POST https://api.securitycenter.microsoft.com/api/libraryfiles -H
"Authorization: Bearer \$token" -F "file=\@mdatp1.png" -F
"ParametersDescription=test"  
-F "HasParameters=true" -F "OverrideIfExists=true" -F "Description=test
description"
----

=== Related topic

* link:run-live-response.md[Run live response]
