= 
denisebmsft
:keywords: wmi, scripts, windows management instrumentation,
configuration

== Use Windows Management Instrumentation (WMI) to configure and manage Microsoft Defender Antivirus

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1] -
https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2] - Microsoft Defender Antivirus

*Platforms* - Windows

Windows Management Instrumentation (WMI) is a scripting interface that
allows you to retrieve, modify, and update settings.

Read more about WMI at the
link:/windows/win32/wmisdk/wmi-start-page[Microsoft Developer Network
System Administration library].

Microsoft Defender Antivirus has a number of specific WMI classes that
can be used to perform most of the same functions as Group Policy and
other management tools. Many of the classes are analogous to
link:use-powershell-cmdlets-microsoft-defender-antivirus.md[Defender for
Cloud PowerShell cmdlets].

The
link:/previous-versions/windows/desktop/defender/windows-defender-wmiv2-apis-portal[MSDN
Windows Defender WMIv2 Provider reference library] lists the available
WMI classes for Microsoft Defender Antivirus, and includes example
scripts.

Changes made with WMI will affect local settings on the endpoint where
the changes are deployed or made. This means that deployments of policy
with Group Policy, Microsoft Endpoint Configuration Manager, or
Microsoft Intune can overwrite changes made with WMI.

You can
link:configure-local-policy-overrides-microsoft-defender-antivirus.md[configure
which settings can be overridden locally with local policy overrides].

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____

____
[!TIP] *Performance tip* Due to a variety of factors (examples listed
below) Microsoft Defender Antivirus, like other antivirus software, can
cause performance issues on endpoint devices. In some cases, you might
need to tune the performance of Microsoft Defender Antivirus to
alleviate those performance issues. Microsoft’s *Performance analyzer*
is a PowerShell command-line tool that helps determine which files, file
paths, processes, and file extensions might be causing performance
issues; some examples are:

* Top paths that impact scan time
* Top files that impact scan time
* Top processes that impact scan time
* Top file extensions that impact scan time
* Combinations – for example:
** top files per extension
** top paths per extension
** top processes per path
** top scans per file
** top scans per file per process

You can use the information gathered using Performance analyzer to
better assess performance issues and apply remediation actions. See:
link:tune-performance-defender-antivirus.md[Performance analyzer for
Microsoft Defender Antivirus].
____

=== Related topics

* link:tune-performance-defender-antivirus.md[Performance analyzer for
Microsoft Defender Antivirus]
* link:configuration-management-reference-microsoft-defender-antivirus.md[Reference
topics for management and configuration tools]
* link:microsoft-defender-antivirus-in-windows-10.md[Microsoft Defender
Antivirus in Windows 10]
