= 
denisebmsft
:keywords: scep, intune, endpoint protection, configuration

== Use Microsoft Endpoint Manager to configure and manage Microsoft Defender Antivirus

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 1]
* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]
* Microsoft Defender Antivirus

*Platforms* - Windows

You can use link:/mem/endpoint-manager-overview[Microsoft Endpoint
Manager] to configure Microsoft Defender Antivirus scans.
link:/mem/intune/fundamentals/what-is-intune[Microsoft Intune] and
link:/mem/configmgr/core/understand/introduction[Configuration Manager]
are now part of Endpoint Manager.

=== Configure Microsoft Defender Antivirus scans in Endpoint Manager

[arabic]
. Go to the Microsoft Endpoint Manager admin center
(https://endpoint.microsoft.com), and sign in.
. Navigate to *Endpoint Security*.
. Under *Manage*, choose *Antivirus*.
. Select your Microsoft Defender Antivirus policy.
. Under *Manage*, choose *Properties*.
. Next to *Configuration settings*, choose *Edit*.
+
____
[!IMPORTANT] AllowOnAccessProtection and AllowIntrusionPreventionSystem
antivirus settings are officially being deprecated and as such cannot be
configured.
____
. Expand the *Scan* section, and review or edit your scanning settings.
. Choose *Review + save*.

____
[!TIP] Need help? See link:/mem/intune/protect/endpoint-security[Manage
endpoint security in Microsoft Intune].
____

____
{empty}[!TIP] If you’re looking for Antivirus related information for
other platforms, see: - link:mac-preferences.md[Set preferences for
Microsoft Defender for Endpoint on macOS] -
link:microsoft-defender-endpoint-mac.md[Microsoft Defender for Endpoint
on Mac] -
link:/mem/intune/protect/antivirus-microsoft-defender-settings-macos[macOS
Antivirus policy settings for Microsoft Defender Antivirus for Intune] -
link:linux-preferences.md[Set preferences for Microsoft Defender for
Endpoint on Linux] - link:microsoft-defender-endpoint-linux.md[Microsoft
Defender for Endpoint on Linux] - link:android-configure.md[Configure
Defender for Endpoint on Android features] -
link:ios-configure-features.md[Configure Microsoft Defender for Endpoint
on iOS features]
____

=== Related articles

* link:tune-performance-defender-antivirus.md[Performance analyzer for
Microsoft Defender Antivirus]
* link:configuration-management-reference-microsoft-defender-antivirus.md[Reference
articles for management and configuration tools]
* link:microsoft-defender-antivirus-in-windows-10.md[Microsoft Defender
Antivirus in Windows 10]

____
[!TIP] *Performance tip* Due to a variety of factors (examples listed
below) Microsoft Defender Antivirus, like other antivirus software, can
cause performance issues on endpoint devices. In some cases, you might
need to tune the performance of Microsoft Defender Antivirus to
alleviate those performance issues. Microsoft’s *Performance analyzer*
is a PowerShell command-line tool that helps determine which files, file
paths, processes, and file extensions might be causing performance
issues; some examples are:

* Top paths that impact scan time
* Top files that impact scan time
* Top processes that impact scan time
* Top file extensions that impact scan time
* Combinations – for example:
** top files per extension
** top paths per extension
** top processes per path
** top scans per file
** top scans per file per process

You can use the information gathered using Performance analyzer to
better assess performance issues and apply remediation actions. See:
link:tune-performance-defender-antivirus.md[Performance analyzer for
Microsoft Defender Antivirus].
____
