= Protect your organization against web threats
:audience: ITPro
:author: dansimp
:description: Learn about web protection in Microsoft Defender for Endpoint and how it can protect your organization.
:keywords: web protection, web threat protection, web browsing, security, phishing, malware, exploit, websites, network protection, Edge, Internet Explorer, Chrome, Firefox, web browser
:manager: dansimp
:ms.author: dansimp
:ms.collection: M365-security-compliance
:ms.date: 08/22/2022
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mde
:ms.topic: article
:search.appverid: met150

== Protect your organization against web threats

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 1]
* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
Want to experience Microsoft Defender for Endpoint?
https://signup.microsoft.com/create-account/signup?products=7f379fee-c4f9-4278-b0a1-e4c8c2fcdf7e&ru=https://aka.ms/MDEp2OpenTrial?ocid=docs-wdatp-main-abovefoldlink&rtc=1[Sign up for a free trial.]
____

Web threat protection is part of xref:web-protection-overview.adoc[Web protection] in Defender for Endpoint.
It uses xref:network-protection.adoc[network protection] to secure your devices against web threats.
By integrating with Microsoft Edge and popular third-party browsers like Chrome and Firefox, web threat protection stops web threats without a web proxy and can protect devices while they are away or on premises.
Web threat protection stops access to phishing sites, malware vectors, exploit sites, untrusted or low-reputation sites, as well as sites that you have blocked in your xref:manage-indicators.adoc[custom indicator list].

____
[!NOTE] It might take up to two hours for devices to receive new custom indicators.
____

=== Prerequisites

Web protection uses network protection to provide web browsing security on Microsoft Edge and third-party web browsers.

To turn on network protection on your devices:

* Edit the Defender for Endpoint security baseline under *Web & Network Protection* to enable network protection before deploying or redeploying it.
link:configure-machines-security-baseline.md#review-and-assign-the-microsoft-defender-for-endpoint-security-baseline[Learn about reviewing and assigning the Defender for Endpoint security baseline]
* Turn network protection on using Intune device configuration, SCCM, Group Policy, or your MDM solution.
xref:enable-network-protection.adoc[Read more about enabling network protection]

____
[!NOTE] If you set network protection to *Audit only*, blocking will be unavailable.
Also, you will be able to detect and log attempts to access malicious and unwanted websites on Microsoft Edge only.
____

=== Configure web threat protection

The following procedure describes how to configure web threat protection using the Microsoft Endpoint Manager admin center.

. Go to the Microsoft Endpoint Manager admin center (https://endpoint.microsoft.com), and sign in.
. Choose *Endpoint security* > *Attack surface reduction*, and then choose *+ Create policy*.
. Select a platform, such as *Windows 10 and later*, select the *Web protection* profile, and then choose *Create*.
. On the *Basics* tab, specify a name and description, and then choose *Next*.
. On the *Configuration settings* tab, expand *Web Protection*, specify your settings, and then choose *Next*.
 ** Set *Enable network protection* to *Enabled* so web protection is turned on.
Alternately, you can set network protection to *Audit mode* to see how it will work in your environment.
In audit mode, network protection does not prevent users from visiting sites or domains, but it does track detections as events.
 ** To protect users from potential phishing scams and malicious software, turn *Require SmartScreen for Microsoft Edge Legacy* to *Yes*.
 ** To prevent users from bypassing warnings about potentially malicious sites, set *Block malicious site access* to *Yes*.
 ** To prevent users from bypassing the warnings and downloading unverified files, set *Block unverified file download* to *Yes*.
. On the *Scope tags* tab, if your organization is using scope tags, choose *+ Select scope tags*, and then choose *Next*.
(If you are not using scope tags, choose *Next*.) To learn more about scope tags, see link:/mem/intune/fundamentals/scope-tags[Use role-based access control (RBAC) and scope tags for distributed IT].
. On the *Assignments* tab, specify the users and devices to receive the web protection policy, and then choose *Next*.
. On the *Review + create* tab, review your policy settings, and then choose *Create*.

=== Related topics

* xref:web-protection-overview.adoc[Web protection overview]
* xref:web-threat-protection.adoc[Web threat protection]
* xref:web-protection-monitoring.adoc[Monitor web security]
* xref:web-protection-response.adoc[Respond to web threats]
* xref:network-protection.adoc[Network protection]
