= Overview of Microsoft 365 Lighthouse
:audience: Admin
:author: SKjerland
:description: For Managed Service Providers (MSPs), learn how Microsoft 365 Lighthouse can help you secure and manage customer tenants in one location.
:f1.keywords: CSH
:manager: scotv
:ms-reviewer: crimora
:ms.author: sharik
:ms.collection: ["M365-subscription-management", "Adm_O365"]
:ms.custom: ["AdminSurgePortfolio", "M365-Lighthouse", "intro-overview"]
:ms.localizationpriority: medium
:ms.service: microsoft-365-lighthouse
:ms.topic: article
:search.appverid: MET150

== Overview of Microsoft 365 Lighthouse

Microsoft 365 Lighthouse is an admin portal that helps Managed Service Providers (MSPs) secure and manage devices, data, and users at scale for small- and medium-sized business (SMB) customers.

Lighthouse simplifies onboarding of customer tenants by recommending security configuration baselines tailored to SMB customers and providing multi-tenant views across all customer environments.
With Lighthouse, MSPs can scale the management of their customers, focus on what's most important, quickly find and investigate risks, and take action to get their customers to a healthy and secure state.

No additional costs are associated with using Lighthouse to manage Microsoft 365 services and connected devices.
Lighthouse is available to MSPs enrolled in the Cloud Solution Provider (CSP) program that service SMB customers.
This includes CSP partners transacting directly with Microsoft and those transacting through an indirect provider (distributor).

____
[!IMPORTANT]  To use Lighthouse, MSPs and their customer tenants must meet the requirements listed in xref:m365-lighthouse-requirements.adoc[Microsoft 365 Lighthouse requirements].
____

For more information about the CSP program, see the link:/partner-center/csp-overview[Cloud Solution Provider program overview].

____
[!NOTE] + A similar offering, Azure Lighthouse, helps service providers deliver managed services for Azure services by using comprehensive and robust management tooling built into the Azure platform.
To learn more, see link:/azure/lighthouse/overview[What is Azure Lighthouse?]
____

=== Watch: What is Microsoft 365 Lighthouse?

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/RE4QVMP]
____

=== Microsoft 365 Lighthouse benefits

Lighthouse helps MSPs secure and manage Microsoft 365 services and connected endpoints at scale by:

* Providing tenant deployment journeys so technicians can follow a consistent set of steps to secure and configure customer tenants.
* Using a default SMB security baseline that prescribes best practices targeted to small- and medium-sized business tenants.
* Providing multi-tenant insights on device compliance for a clear view of how devices are being evaluated across all organizations, tools to compare policies, and the top settings that aren't being met.
* Simplifying common tasks like resetting a password.
* Configuring multifactor authentication and self-service password reset, including tools to help drive adoption by users.
* Understanding and protecting against risky sign-ins.
* Managing threats on Windows 10 devices by providing details on threats detected by Microsoft 365 Defender and actions to take to resolve issues and keep devices up to date.
* Providing insights into Microsoft 365 service incidents and advisories that impact the customer tenants they manage.

____
[!NOTE]  For more information on how to sign up, see xref:m365-lighthouse-sign-up.adoc[Sign up for Microsoft 365 Lighthouse].
____

=== Related content

xref:m365-lighthouse-sign-up.adoc[Sign up for Microsoft 365 Lighthouse] (article) + xref:m365-lighthouse-tenants-page-overview.adoc[Overview of the Tenants page in Microsoft 365 Lighthouse] (article) + xref:m365-lighthouse-device-compliance-page-overview.adoc[Overview of the Device compliance page in Microsoft 365 Lighthouse] (article) + link:m365-lighthouse-faq.yml[Microsoft 365 Lighthouse FAQ] (article) + link:../security/defender-business/index.yml[Microsoft Defender for Business] (link page)
