= Compare device compliance policy settings in Microsoft 365 Lighthouse
:audience: Admin
:author: SKjerland
:description: For Managed Service Providers (MSPs) using Microsoft 365 Lighthouse, learn how to compare device compliance policy settings.
:f1.keywords: NOCSH
:manager: scotv
:ms-reviewer: ragovind
:ms.author: sharik
:ms.collection: ["M365-subscription-management", "Adm_O365"]
:ms.custom: ["AdminSurgePortfolio", "M365-Lighthouse"]
:ms.localizationpriority: medium
:ms.service: microsoft-365-lighthouse
:ms.topic: article
:search.appverid: MET150

== Compare device compliance policy settings in Microsoft 365 Lighthouse

Microsoft 365 Lighthouse lets you view compliance policies across your tenants in a single view.
You can drive security and standardization across your tenants by comparing policies.
You can filter views to see settings that have been configured (versus settings that were left not configured), settings that differ in their configurations, or settings that match.
You can also search for specific settings to see how they compare across policies.

=== Before you begin

Make sure devices have a Microsoft Intune license and are enrolled in Microsoft Endpoint Manager (MEM).

=== Compare policy settings

. In the left navigation pane in Lighthouse, select *Devices* > *Device compliance*.
. Select the *Policies* tab.
. From the *Filters* dropdown list, select an operating system or platform.
+
____
[!NOTE] You can only compare policies with the same operating system or platform.
____

. From the filtered list, select up to three policies that you want to compare.
. Select *Compare*.

You can filter the results to see *Settings that differ*, *Settings that match*, or *Configured settings*.

=== Configure a policy setting

. In the left navigation pane in Lighthouse, select *Devices* > *Device compliance*.
. Select the *Policies* tab.
. From the list of policies, select the policy that you want to view.
. In the policy details pane, select *View this policy in Microsoft Endpoint Manager*.
. In MEM, edit the policy settings as needed.

=== Next steps

As you make policy adjustments, make sure you assess your changes against your current baseline settings.
For more information, see xref:m365-lighthouse-deploy-standard-tenant-configurations-overview.adoc[Overview of using baselines to deploy standard tenant configurations].

=== Related content

link:/mem/intune/enrollment/device-enrollment[What is device enrollment in Intune?] (article) + link:/mem/intune/protect/device-compliance-get-started[Use compliance policies to set rules for devices you manage with Intune] (article) + xref:m365-lighthouse-deploy-standard-tenant-configurations-overview.adoc[Overview of using Microsoft 365 Lighthouse baselines to deploy standard tenant configurations] (article)
