= Get help and support for Microsoft 365 Lighthouse
:audience: Admin
:author: SKjerland
:description: For Managed Service Providers (MSPs) using Microsoft 365 Lighthouse, learn how to get help and support.
:f1.keywords: CSH
:manager: scotv
:ms-reviewer: crimora
:ms.author: sharik
:ms.collection: ["M365-subscription-management", "Adm_O365"]
:ms.custom: ["AdminSurgePortfolio", "M365-Lighthouse"]
:ms.localizationpriority: medium
:ms.service: microsoft-365-lighthouse
:ms.topic: article
:search.appverid: MET150

== Get help and support for Microsoft 365 Lighthouse

Several options are available if you need help.
First, check to see if there are any known issues:

* Review the current health of customer tenant services:
 .. In the left navigation pane of Lighthouse, select *Service health*.
 .. View detailed information about current and past issues.
* Review the current health of the Lighthouse tenant services:
 .. Go to the Microsoft 365 admin center at https://go.microsoft.com/fwlink/p/?linkid=2024339[https://admin.microsoft.com].
 .. In the left navigation pane, select *Health* > *Service health*.
 .. In the list of services, find *Microsoft 365 suite*, and then expand it to show all the services in the suite.
 .. Find *Microsoft 365 Lighthouse* and check the health.
* See if the issue is listed in link:/microsoft-365/lighthouse/m365-lighthouse-known-issues[Known issues with Microsoft 365 Lighthouse].

If you're experiencing an issue that isn't listed in any of these resources, then follow the instructions in this article to view self-help options or to create a service request.

=== Before you begin

* To create and manage service requests, you must have at least one Azure Active Directory (Azure AD) role assigned to you with the following property set: *microsoft.office365.supportTickets/allEntities/allTasks*.
For a list of Azure AD roles, see link:/azure/active-directory/roles/permissions-reference[Azure AD built-in roles].
For information on how to assign roles, see link:/azure/active-directory/roles/manage-roles-portal[Assign Azure AD roles to users].
* If you need to create a service request, gather as many details as possible about your issue, such as diagnostic logs, tenant ID, and user IDs (if specific users are affected).

=== Access help and support

. In Lighthouse, select the *?* icon at the top of the portal to open the *Help* pane, and then do one of the following:
 ** If you're on the page of the portal where the issue occurred, select *Show diagnostics*.
+
This will create a JSON file with information to help Support agents troubleshoot your issue.
Save the file so you can attach it to your service request.
+
____
[!NOTE] The JSON file will contain personally identifiable information.
____

 ** If your issue isn't isolated to the current page of the portal, go to the next step.
. In the *Help* pane, select the *Help + support* button.
This opens the *How can we help?* pane.
+
____
[!NOTE] If the *How can we help?* pane doesn't open, you'll need to reach out to someone in your partner tenant who has Global Administrator permissions and ask them to help.
____

. In the *How can we help?* pane, enter a description of your issue, and then press *Enter*.
We recommend including the full product name _Microsoft 365 Lighthouse_ in your description to ensure the search results include relevant help articles.
. Check out the list of recommended articles to see if any of them help resolve your issue.
+
If you enter a description of your issue and it doesn't return a list of help articles, rephrase your description and try another search.

. If the recommended articles don't help, select *Contact Support*.
. Fill out the information in the form, attach any screenshots and the JSON file that you saved in step&nbsp;1 if applicable, and then select *Contact me*.
The expected wait time is indicated in the pane.

=== Related content

xref:m365-lighthouse-known-issues.adoc[Known issues with Microsoft 365 Lighthouse] (article) + link:m365-lighthouse-faq.yml[Microsoft 365 Lighthouse FAQ] (article) + xref:m365-lighthouse-troubleshoot.adoc[Troubleshooot and resolve problems and error messages in Microsoft 365 Lighthouse] (article)
