= Manage self-service password reset in Microsoft 365 Lighthouse
:audience: Admin
:author: SKjerland
:description: For Managed Service Providers (MSPs) using Microsoft 365 Lighthouse, learn how to manage self-service password reset.
:f1.keywords: NOCSH
:manager: scotv
:ms-reviewer: ragovind
:ms.author: sharik
:ms.collection: ["M365-subscription-management", "Adm_O365"]
:ms.custom: ["AdminSurgePortfolio", "M365-Lighthouse"]
:ms.localizationpriority: medium
:ms.service: microsoft-365-lighthouse
:ms.topic: article
:search.appverid: MET150

== Manage self-service password reset in Microsoft 365 Lighthouse

Microsoft 365 Lighthouse lets partners manage Azure Active Directory (Azure AD) self-service password reset (SSPR).
SSPR gives users the ability to change or reset their password with no administrator or help desk involvement.
If a user's account is locked or they forget their password, they can follow prompts to unblock themselves and get back to work.
This ability reduces help desk calls and loss of productivity when a user can't sign in to their device or an application.

=== Before you begin

The following conditions must be met before a tenant will appear in the list:

* The customer tenant must have an Azure AD Premium license for each user.
For more information on which licenses support SSPR, see link:/azure/active-directory/authentication/concept-sspr-licensing[Licensing requirements for Azure Active Directory self-service password reset].
* The customer tenant must be active within Lighthouse.
To learn how to determine if a tenant is active, see xref:m365-lighthouse-tenants-page-overview.adoc[Overview of the Windows 365 (Cloud PCs) page in Microsoft 365 Lighthouse].

=== View SSPR tenant status

* In the left navigation pane in Lighthouse, select *Users* > *Password reset*.

The Password reset page provides an overview of the tenants that have enabled SSPR through the recommended settings, the number of users who haven't registered for SSPR, and a detailed breakdown by tenant of the SSPR deployment progress across the organizations that you manage.

=== Enable SSPR for a tenant

. In the left navigation pane in Lighthouse, select *Users* > *Password reset*.
. On the *Password reset* page, select a tenant from the list to open the details pane.
. Select *Edit SSPR settings in Azure Active Directory* to go to Azure Active Directory (Azure AD).
. In Azure AD, enable SSPR for all or selected users.
To learn more, see link:/azure/active-directory/authentication/tutorial-enable-sspr[Tutorial: Enable users to unlock their account or reset passwords using Azure Active Directory self-service password reset].

=== Notify users to register for SSPR

. In the left navigation pane in Lighthouse, select *Users* > *Password reset*.
. On the *Password reset* page, select a tenant from the list to open the details pane.
. Select the users that you want to notify.
. Select *Create email*.

Lighthouse opens your default email client and prepopulates the email message with instructions to register for SSPR.
All the selected users will be included on the BCC line.
If you prefer to individually email users, you can select the email icon next to the username.

If you want to use a different email account, you can export the list of users to a file.
You can also download sample email templates that you can customize with your company branding.

=== Related content

link:/azure/active-directory/authentication/howto-sspr-deployment[Plan an Azure Active Directory self-service password reset deployment] (article) + link:/azure/active-directory/authentication/tutorial-enable-sspr[Tutorial: Enable users to unlock their account or reset passwords using Azure Active Directory self-service password reset] (article) + https://www.youtube.com/watch?v=rA8TvhNcCvQ[How to enable and configure SSPR in Azure AD] (video) + xref:m365-lighthouse-manage-mfa.adoc[Manage multifactor authentication in Microsoft 365 Lighthouse] (article)
