= Add more SharePoint storage to your subscription
:audience: Admin
:author: cmcatee-MSFT
:description: Add file storage in your Microsoft 365 subscription. With extra file storage, you can store more content in SharePoint.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.author: cmcatee
:ms.collection: ["M365-subscription-management", "Adm_O365", "SPO_Content"]
:ms.custom: ["commerce_purchase", "MAX_CampaignID", "okr_SMB", "AdminSurgePortfolio", "business_assist", "AdminTemplateSet", "admindeeplinkSPO"]
:ms.date: 05/24/2022
:ms.localizationpriority: medium
:ms.reviewer: jkinma, jmueller
:ms.service: o365-administration
:ms.topic: article
:search.appverid: MET150

== Add more SharePoint storage to your subscription

If you start to run out of storage for your SharePoint sites, you can add storage to your subscription if your plan is eligible.
If you don't see the *Office 365 Extra File Storage* in the list of available add-ons, it means your plan is not eligible.
For more information, see <<is-my-plan-eligible-for-office-365-extra-file-storage,Is my plan eligible?>>

____
[!NOTE] If you bought your subscription through Volume Licensing or a CSP, you can't buy *Office 365 Extra File Storage* for your organization directly from Microsoft.
Contact your representative or partner for help.
For information about OneDrive storage, see link:/onedrive/set-default-storage-space[Set the default storage space for OneDrive users].
____

____
[!TIP] If you need help with the steps in this topic, consider https://go.microsoft.com/fwlink/?linkid=2186871[working with a Microsoft small business specialist].
With Business Assist, you and your employees get around-the-clock access to small business specialists as you grow your business, from onboarding to everyday use.
____

=== Before you begin

You must be a Global or SharePoint admin to do the tasks in this article.
For more information, see xref:../admin/add-users/about-admin-roles.adoc[About admin roles].

=== View available storage

. In the SharePoint admin center, go to https://go.microsoft.com/fwlink/?linkid=2185220[*Active sites*], and sign in with an account that has link:/sharepoint/sharepoint-admin-role[admin permissions] for your organization.
. In the upper right of the page, see the amount of storage used across all sites, and the total storage for your subscription.
If your organization has configured Multi-Geo in Office 365, the bar also shows the amount of storage used across all geo locations.
+
____
[!NOTE] The storage used doesn't include changes made within the last 24-48 hours.
____

After you determine how much storage you're using, you can add or remove storage space for your subscription.
To find out how much it will cost to add storage space, follow the steps in this article, and review the pricing information before you buy more.

For information about setting site collection storage limits, see link:/sharepoint/manage-site-collection-storage-limits[Manage site collection storage limits].

=== Buy the extra storage add-on

If you haven't yet bought extra storage for your subscription, you can do that.

. In the admin center, go to the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=868433[Purchase services] page.
. At the bottom of the *Purchase services* page, in the *Add-ons* section, find *Office 365 Extra File Storage*, and select *Details*.
. On the product details page, select *Next*.
. If needed, choose the base subscription, then enter the number of gigabytes of storage you want to add.
. Select *Check out now*.
. On the *How does this look?* page, verify the number of gigabytes of storage you selected, review the pricing information, and then select *Next*.
. On the *Complete order* page, verify the total.
If you need to make any changes, select *Edit order*.
If the order requires a credit check, select the check box.
When you're finished, select *Place order* > *Go to Admin Home*.

=== Increase or decrease your extra storage

If you've already bought extra file storage via the *Office 365 Extra File Storage* add-on, you can use these steps to increase or decrease the extra storage space for your subscription.
You can reduce the storage to as low as 1 gigabyte.
To remove all of the extra storage space, xref:../admin/get-help-support.adoc[contact support].

. In the admin center, go to the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=842054[Your products] page.
. On the *Products* tab, select the subscription that contains the *Office 365 Extra File Storage* add-on.
. On the product details page, in the *Add-ons* section, select *Manage add-ons*.
. In the *Manage add-ons* pane, from the *Add-on* list, choose *Office 365 Extra File Storage*.
. In the *Quantity* text box, enter the number of GBs of storage space that you want for the subscription.
. Select *Save*.

=== Is my plan eligible for Office 365 Extra File Storage?

Office 365 Extra File Storage is available for the following subscriptions:

* Office 365 Enterprise E1
* Office 365 Enterprise E2
* Office 365 Enterprise E3
// Office 365 Enterprise E4
* Office 365 Enterprise E5
* Office 365 A3 (faculty)
* Office 365 A5 (faculty)
* Office for the web with SharePoint Plan 1
* Office for the web with SharePoint Plan 2
* SharePoint Online Plan 1
* SharePoint Online Plan 2
* Microsoft 365 Business Basic
* Microsoft 365 Business Standard
* Microsoft 365 Business Premium
* Microsoft 365 E3
* Microsoft 365 E5
* Microsoft 365 F1
* Microsoft 365 F3

____
[!NOTE] Office 365 Extra File Storage is also available for GCC, GCC High, and DOD plans.
____

=== Related content

link:/sharepoint/manage-site-collection-storage-limits[Manage site storage limits] (article)
