= 
cmcatee-MSFT

== Buy or manage add-ons for Microsoft 365 business plans

Many Microsoft 365 for business plans have add-ons that you can buy for
your subscriptions. Add-ons provide more features to enhance your
subscription experience.

There are two types of add-ons:

[arabic]
. *Traditional add-ons* are linked to a specific subscription. If you
cancel the subscription, the associated add-on is also canceled.
. *Standalone add-on subscriptions* appear as a separate subscription on
the *Your products* page and have their own expiration date. Unlike
traditional add-ons, standalone add-on subscriptions aren’t linked to a
specific subscription. You manage a standalone add-on subscription the
same way that you manage any other subscription.

=== Before you begin

You must be a Global or Billing admin to do the steps described in this
article. For more information, see
link:../admin/add-users/about-admin-roles.md[About admin roles].

=== Buy an add-on

Use the following steps to find and buy add-ons. The list only includes
add-ons that are available to you. This list is based on your currently
active subscriptions, and any other existing add-ons you already have.
If an add-on isn’t on the list, it’s not available to buy.

For information about Skype for Business add-ons, see
link:/SkypeForBusiness/skype-for-business-and-microsoft-teams-add-on-licensing/skype-for-business-and-microsoft-teams-add-on-licensing[Skype
for Business and Microsoft Teams add-on licensing].

[arabic]
. In the admin center, go to the *Billing* > Purchase services page.
. At the bottom of the *Purchase services* page, in the *Add-ons*
section, find the add-on that you want to buy, and select *Details*.
. On the product details page, select *Next*.
. If needed, complete any other order information. This information
might include selecting the subscription the add-on is for. When you’re
finished, select *Check out now*.
. If needed, review the order and pricing information, then select
*Next*.
. Choose a payment method, or add a new one, then select *Place order* >
*Go to Admin Home*.

=== Manage an add-on

You manage a standalone add-on subscription the same way that you manage
any other subscription – on the *Your products* page. For example, you
can link:licenses/buy-licenses.md[buy or remove licenses],
link:subscriptions/renew-your-subscription.md[manage recurring billing],
and link:billing-and-payments/manage-payment-methods.md[edit or replace
payment methods] for standalone add-on subscriptions.

You manage a traditional add-on by going to the subscription that
contains it and making changes there. Use the following steps to manage
a traditional add-on.

[arabic]
. In the admin center, go to the *Billing* > Your products page.
. On the *Products* tab, select the subscription that contains the
add-on that you want to update.
. On the subscription details page, the *Add-ons* section lists the
add-ons that you bought. Select *Manage add-ons*.
. In the *Manage add-ons* pane, from the *Add-on* drop-down list, select
the add-on that you want to change.
. Enter a quantity change for the add-on, then select *Save*.

=== Remove an add-on

To remove a standalone add-on subscription, you
link:subscriptions/cancel-your-subscription.md[cancel the subscription],
just like any other subscription. Or you can
link:subscriptions/renew-your-subscription.md[turn off Recurring
billing].

You can’t remove a traditional add-on. If you want to remove a
traditional add-on, contact support for help
(link:../admin/get-help-support.md[Get support].

=== Related content

link:add-storage-space.md[Add storage space for your subscription]
(article) +
link:licenses/buy-licenses.md[Buy or remove subscription licenses]
(article) +
link:subscriptions/renew-your-subscription.md#turn-recurring-billing-off-or-on[Turn
Recurring billing off or on] (article) +
link:billing-and-payments/manage-payment-methods.md[Manage payment
methods] (article)
