= 
cmcatee-MSFT

== Review Microsoft-certified cloud solution provider partner administrative privileges

If you have a Microsoft-certified cloud solution provider (reseller
partner), we recommend you conduct a quarterly review of the delegated
administrative privileges (DAP) assigned to them. Make sure your
organization wants this partner to have access to your organization’s
data and make purchases on your behalf.

____
[!IMPORTANT] Giving DAP, which include Global admin permissions, to any
partner might present a security risk. Having too many Global admins is
also a security risk.
https://www.microsoft.com/security/blog/2021/10/25/nobelium-targeting-delegated-administrative-privileges-to-facilitate-broader-attacks/[Learn
more about recent activity targeting delegated privileges].
____

After you accept a DAP agreement from a reseller partner, they can
assign the Global admin role for your organization to their employees.
The Global admin role gives the partner’s employees access to your
employees’ personal data and other sensitive information. It also gives
them permission to take tenant-wide actions, such as the following
actions:

* Changing user passwords
* Adding users with email accounts
* Adding and managing web domains associated with your organization

When DAP is enabled, you have no control over the number of Global
admins your partner can add. You can only grant or deny the partner DAP
(Global admin) access to your account.

=== Review and remove roles from partners

[arabic]
. In the Microsoft 365 admin center, go to the *Settings* > Partner
relationships page. Partners with DAP have *Global Administrator* listed
in the *Roles* column.
. To remove the Global admin role from a partner, find the name of the
partner that you want to remove.
. Select the row that has *Reseller* as the *Relationship Type*.
. On the partner details page, select *Remove roles*, then select *Yes*.

____
{empty}[!NOTE]

* If you remove DAP (Global admin role) from a partner, we recommend
that you contact them to discuss future service delivery. For example,
you can create a user account with lower privileges and share that
account information with your partner. Learn more about
link:../admin/add-users/add-users.md[adding users] and
link:../admin/add-users/assign-admin-roles.md[assigning admin roles].
* Even with the Global admin role removed, the partner can still make
purchases on your behalf. We recommend that you contact the partner to
ask them to remove that ability in the Partner Center.
____

=== Related content

link:manage-partners.md[Manage partner relationships] (article) +
link:../admin/add-users/about-admin-roles.md[About admin roles]
(article) +
link:/partner-center/customers-revoke-admin-privileges#delegated-admin-privileges-in-azure-ad[Delegated
admin privileges in Azure AD] (article)
