= Use your promo code to reduce price
:audience: Admin
:author: cmcatee-MSFT
:description: Learn how to apply a promotional code to your Microsoft 365 subscription to reduce price, and how to troubleshoot promo code in case of an error.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.author: cmcatee
:ms.collection: ["M365-subscription-management", "Adm_O365"]
:ms.custom: ["commerce_purchase", "AdminSurgePortfolio", "okr_SMB"]
:ms.date: 03/17/2021
:ms.localizationpriority: medium
:ms.reviewer: drjones, jmueller
:ms.service: o365-administration
:ms.topic: article
:search.appverid: MET150

== Use your Microsoft 365 for business promo code to reduce the price

When you purchase a subscription, you can use a promotional code to reduce the price.
Read this article to learn how to apply a promo code to your subscription, to learn about the <<promo-code-terms,Promo code terms>>, and to <<troubleshooting-promo-codes,Troubleshoot promo codes>>.

=== Apply a promo code to your subscription

. Begin your purchase by either purchasing a new subscription, or by adding services to an existing subscription.
. When you check out, choose *Have a promo or discount code?*, and then enter your code in the box.
. Select *Apply promo code*.
You should see confirmation that it was successfully applied.
If you see a different message, refer to <<troubleshooting-promo-codes,Troubleshooting promo codes>> to figure out why.
. Continue checking out.
On the order confirmation page, you'll see your discount code included with the amount.

At any time after you complete your purchase, you can see the discount created by your promo code on your bill.
To learn more, see xref:billing-and-payments/view-your-bill-or-invoice.adoc[View your].

=== Promo code terms

The following guidelines apply to promo codes for Microsoft 365 for business subscriptions.

* *Number of promo codes per subscription* You can use a promo code for multiple subscriptions in the same order, but you cannot use multiple promo codes for the same subscription.
* *Length of discount* Once applied to your order, the promo code discount lasts for the length of your subscription's term.
If your subscription's term is month-to-month, the promo code discount lasts until the end of the billing month you entered it in.
If your subscription's term is yearly (even if it's paid monthly), the promo code discount lasts until the end of the billing year you entered it in.
* *Promo code license limits* Some promo codes have a maximum level.
Only licenses up to that maximum are discounted.
You can confirm whether your promo code has these limitations by looking at its Terms and Conditions.
* *Promo code end dates* The promo end date is the last day a promo code for that campaign can be redeemed.
Once your purchase is completed, the discounted price for your subscription applies for the whole term of the order.

=== Troubleshooting promo codes

If you receive an error message after you enter your promo code, there may be a number of reasons.
The following list describes the most common causes of error messages.

* *You made a typo when you entered the code.* Pay close attention to any dashes, capital or lowercase letters or special symbols in the promo code.
Promo codes should be entered exactly.
* *You are trying to apply the promo code to a subscription that is not new.* Promo codes are intended for new subscriptions.
If you are trying to use one in an already active subscription, you will not see the option to apply your promo code.
There is no way to apply a promo code after the purchase is complete.
* *The promo code has expired.* Campaigns are set up for a limited time.
Promo codes have an expiration date.
If the promo code you are trying to use exceeds the expiration date, it's no longer usable.
There is no way to accept or replace expired promotion codes, but you can still purchase a subscription without one.
* *The promo code you are using is for the wrong geographical region.* Some promo codes are only valid for a particular country or region.
Promo codes don't work in a country or region other than the one for which they were created.

=== Related content

xref:./try-or-buy-microsoft-365.adoc[Buy a subscription from your free trial] (article)\ + xref:./try-or-buy-microsoft-365.adoc[Buy another subscription] (article)\ + xref:buy-or-edit-an-add-on.adoc[Buy or edit an add-on] (article)
