= 
cmcatee-MSFT

== Understand billing profiles

A billing profile contains a payment method, Bill-to information, and
other invoice settings, such as purchase order number and email invoice
preference. You use a billing profile to pay for the products that you
buy from Microsoft. Billing profiles are automatically created, and each
are invoiced separately.

____
{empty}[!NOTE]

Not all accounts have a billing profile. If you’re not sure if you have
a one, you can
link:manage-billing-profiles.md#view-my-billing-profiles[view a list of
your billing profiles].
____

=== What are billing profile roles?

Roles on billing profiles have permissions to control purchases, and
view and manage invoices. Assign these roles to users who track,
organize, and pay invoices. For example, members of the procurement team
in your organization.

[width="100%",cols="27%,73%",options="header",]
|===
|Role |Description
|Billing profile owner |Manage everything for a billing profile

|Billing profile contributor |Manage everything except permissions in a
billing profile

|Billing profile reader |Read-only view of everything in a billing
profile

|Invoice manager |View and pay bills, and has a read-only view of
everything in a billing profile
|===

=== View my billing profiles

____
{empty}[!NOTE]

If you follow these steps and the billing profiles list is empty, it
means that you don’t have a billing profile, and can’t use this feature.
____

[arabic]
. In the admin center, go to the *Billing* > Bills & payments page.
. Select the *Billing profile* tab, then select a billing profile from
the list.

Each billing profile includes the following information:

* *Billing profile name and status* – The unique name of the billing
profile, and whether the billing profile is active or disabled for
purchasing.
* *Invoice settings* – Currency based on the country of the billing
account, information about invoice frequency and date, the option to
receive invoices as email attachments, and an optional PO number field
* *Payment methods* – Shows the primary and backup payment method, if
any, for the profile
* *Billing account* – Name of the billing account the profile is related
to. For more information about billing accounts, see
link:../manage-billing-accounts.md[Understand billing accounts].
* *Contact information* – Billing address and contact name and email
address
* *Billing profile roles* – A list of people who are assigned one of the
billing profile roles to do things for that profile. For example, pay
bills, add a PO number, or replace the payment method that is used to
make purchases.

____
{empty}[!NOTE]

You can only assign billing profile roles to users in your organization.
____

=== Need help? Contact support

If you have questions or need help with your Azure charges, create a
support request with Azure support.

If you have questions or need help with your billing profile in
Microsoft 365 admin center, link:../../admin/get-help-support.md[contact
support].

=== Related content

link:pay-for-subscription-billing-profile.md[How to pay for your
subscription with a billing profile] (article) +
link:../manage-billing-accounts.md[Understand billing accounts]
(article) +
link:manage-payment-methods.md[Manage payment methods] (article)
