= 
cmcatee-MSFT

== Billing information for Microsoft 365 for business in Mexico

=== 1. Where can I get an invoice for my Microsoft 365 for business purchase?

Your invoice is sent to the registered billing notification email
address 24 hours after your purchase is confirmed. To download your
invoice in the Microsoft 365 admin center, go to the *Billing* > Bills &
payments page.

____
[!IMPORTANT] If you want the invoice to include your RFC, you must add
it before the purchase confirmation.
____

=== 2. How can I add my RFC (Registro Federal de Contribuyentes) to the invoice I get for the purchase of Microsoft 365 for business?

==== During the purchase process (Checkout)

During the checkout purchase process, when you get to step *4. Payment
and billing*, select the box to enter an RFC. This step is necessary so
that you can see it reflected in your purchase invoice.

==== For your future purchases

You can add or modify your RFC so that the information is reflected in
future Microsoft 365 for business purchases. To add or modify your RFC,
go to the *Billing* > Billing accounts page.

____
[!NOTE] If you’re in a recurrent billing subscription, the addition or
modification of the RFC is reflected on the invoice of your next charge.
____

=== 3. Can I add or modify my RFC to an invoice that was already generated?

It’s important that you add or modify your RFC before you make your
purchase. After we have generated your Microsoft 365 for business
invoice, you can’t add or modify the RFC information.

=== 4. Why don’t I get a CFDI (Comprobante Fiscal Digital por Internet)?

Microsoft Corporation, as tax resident in the United States of America,
is only able to issue invoices under the laws of jurisdiction and is not
obligated to provide a CFDI electronic invoice.

=== 5. Is the invoice I receive valid for my accounting operations in Mexico?

An invoice generated by foreign entities (in this case Microsoft
Corporation) that includes the respective RFC is valid for tax purposes
in Mexico. (We recommend consulting your accountant for more
information).

=== Related content

link:view-your-bill-or-invoice.md[View your bill or invoice] (article) +
link:understand-your-invoice2.md[Understand your bill or invoice for
Microsoft 365 for business] (article)
