= 
cmcatee-MSFT

== Payment options for your Microsoft business subscription

____
[!IMPORTANT] As of January 26, 2021, new bank accounts are no longer
supported for customers in Belgium, France, Italy, Luxembourg, Portugal,
Spain, and the United States. If you’re an existing customer in one of
those countries, you can continue paying for your subscription with an
existing bank account that is in good standing. However, you can’t add
new subscriptions to the bank account.
____

You can use a credit or debit card, or bank account to pay for your
Microsoft business subscription. For qualifying customers, you can pay
by invoice, using check or electronic funds transfer (EFT). If you have
a billing profile, your options are slightly different. For more
information, see link:pay-for-subscription-billing-profile.md[How to pay
for your subscription with a billing profile]. If you’re not sure if
your account has a billing profile, see
link:manage-billing-profiles.md[Understand billing profiles].

*Just want to find out where to send your invoice payment?* If you
currently pay your invoice by check or EFT, see
link:#where-do-i-send-my-check-or-eft-payment[Where do I send my check
or EFT payment?]

____
[!TIP] If you need help with the steps in this topic, consider
https://go.microsoft.com/fwlink/?linkid=2186871[working with a Microsoft
small business specialist]. With Business Assist, you and your employees
get around-the-clock access to small business specialists as you grow
your business, from onboarding to everyday use.
____

=== Before you begin

* You must be a Global or Billing admin to do the steps described in
this article. For more information, see
link:../../admin/add-users/about-admin-roles.md[About admin roles].
* The payment method that you choose during checkout is the payment
method that we use for all future billing periods. You can change it at
any time.

=== Directives from the Reserve Bank of India

Currently, some credit card transactions, especially transactions
exceeding 5,000 INR, are blocked due to a directive by the Reserve Bank
of India. This might affect automatic payments, which means that you
might have to make payments manually in the Microsoft 365 admin center.
This directive doesn’t affect usage charges.

https://www.rbi.org.in/Scripts/NotificationUser.aspx?Id=11668&Mode=0[Learn
more about the Reserve Bank of India directive for recurring payments].

As of September 30, 2022, Microsoft and other online merchants no longer
store credit card information. Microsoft has removed all stored card
details from the admin center. To avoid service interruption, you must
add and verify a payment method for all subscriptions.

https://www.rbi.org.in/Scripts/NotificationUser.aspx?Id=12211[Learn
about the Reserve Bank of India directive for card storage].

____
[!IMPORTANT] Because of the removal of credit card information, when you
view your list of payment methods, the *Expiration Date* and *Status*
columns only say ``Unknown.''
____

==== UPI and NetBanking payment options

The admin center supports two alternate payment options for customers in
India:

* UPI (Unified Payments Interface) payment is a real-time payment
method.
* NetBanking (Internet Banking) provides customers with access to
banking services on an online platform.

____
[!IMPORTANT] UPI and NetBanking are only supported for one-time
transactions for existing customers only.
____

===== How do I make a payment with UPI or NetBanking?

[arabic]
. If you’re a returning customer, when you make a payment, select *UPI /
NetBanking* from the *Payment method* drop-down list, then select *Make
payment*.
. You’re redirected to the payment partner, BillDesk, where you choose
UPI or NetBanking for your payment method.
. Follow the instructions in BillDesk to complete the transaction.

After you submit the payment, allow time for the payment to appear in
the admin center.

===== How am I refunded if I made a payment with UPI or NetBanking?

Refunds are treated as a regular charge and are refunded to your bank
account.

=== Paying by credit or debit card, or bank account

____
[!IMPORTANT] Paying by bank account is not available in some countries
or regions.
____

You can pay for your subscription with a credit or debit card, or a bank
account. When you pay with one of these payment methods, we continue to
charge that payment method until the subscription expires, or is
canceled. You can link:manage-payment-methods.md[manage payment methods]
whenever you need to. You can also choose to
link:manage-billing-notifications.md#receive-your-organizations-invoices-as-email-attachments[receive
your organization’s invoices as email attachments].

=== Paying by invoice

If you’re a new customer, paying by invoice isn’t available as a payment
method. However, you can buy subscriptions with a credit or debit card
or through a partner or reseller.

If you’re an existing customer, and you meet the eligibility
requirements described below, you can contact support to help you change
a current subscription to be paid by invoice. If you want to buy a new
subscription, and you meet the eligibility requirements, you might be
approved to change your payment method to pay by invoice. Contact
support to find out if you can pay by invoice, and to help you buy a new
subscription using the pay by invoice option.

*Eligibility requirements.* To be eligible to pay by invoice, you must:

* Be an established customer for at least six months and have no
outstanding balances
* Have a subscription cost that exceeds a certain amount (this amount
varies by service location)
* Pass a credit check

____
[!NOTE] Customers who live in Brazil can pay for a subscription with a
Boleto Bancario. If you have selected this option, the billet for
payment is sent to the email provided during subscription purchase
within 10 working days after the order date. The due date is 30 days
after the order date. If you don’t receive your Boleto by email, check
your spam folder or contact support.

If you prefer, you can pay by electronic transfer between accounts. The
Agency and account number are at the bottom of your invoice. You must
enter your invoice number in the Transfer identification field.
____

If you pay by invoice for your subscription, you get an email when your
billing statement is ready to view. This email doesn’t contain a copy of
your billing statement. However, you can choose to
link:manage-billing-notifications.md#receive-your-organizations-invoices-as-email-attachments[receive
your organization’s invoices as email attachments]. Your billing
statement includes details about your options for making a payment, and
where to send it. If you enter a purchase order (PO) number when you buy
a subscription, the number appears on your billing statement. For
information about accessing billing statements, see
link:view-your-bill-or-invoice.md[View your bill or invoice].

=== What if I have an outstanding balance?

If we’re unable to charge the payment method on file, we send an email
that lets you know there’s a problem. The email briefly states what the
problem is and includes a link where you can check the outstanding
balance. We continue to retry the transaction every few days for 30
days, during which time the subscription is in a grace period. Every
time a transaction fails, you receive an email alert about the failure.

If you personally added the payment method that has a past due amount,
you can use *Settle balance* to make a payment. The payment method that
you use to pay the overdue amount becomes the new payment method for all
subscriptions that used the declined payment method.

[arabic]
. In the admin center, go to the *Billing* > *Bills & payments* page,
then select the Payment methods tab.
. A warning message says which payment method was declined. Select
*Settle balance*.
. In the right pane, choose a different payment method, or select *Add a
new payment method*.
. After you’ve updated the payment method information, select *Save*.

If you didn’t add the payment method used to pay for the subscription,
you must replace the payment method with one you previously added, or
with a new one.

=== Where do I send my check or EFT payment?

link:view-your-bill-or-invoice.md[Check your invoice] for payment
instructions for your country or region. If you’re not sure how much you
owe, you can check your bill and billing history online on the
*Invoices* tab of the Bills & payments page.

____
{empty}[!NOTE]

* Paying by check is only available in a few countries.
* If you must pay the membership fee for the Microsoft Partner Network
(MPN) program (Action Pack subscription, Silver or Gold competencies),
see
link:/partner-center/mpn-pay-fee-silver-gold-competency?tabs=workspaces-view[Pay
competency fees] for information about how to make an MPN payment.
____

=== Check or wire transfer payment processing time

Payments made by check are posted three to five business days after the
check clears your bank. You can contact your bank to confirm the check
status.

Payments made by wire transfer have processing times that vary,
depending on the type of transfer:

* ACH domestic transfers - Five business days. Two to three days to
arrive, plus two days to post.
* Wire transfers (domestic) - Four business days. Two days to arrive,
plus two days to post.
* Wire transfers (international) - Seven business days. Five days to
arrive, plus two days to post.

If your account is approved for payment by check or wire transfer, the
instructions for payment are on the invoice.

=== Can I pay my invoice online?

You can’t pay your invoice online. You must remit payment via either
check or EFT.

=== Can I change from my current payment method to paying by invoice?

You can only change to paying by invoice if you meet the eligibility
requirements described in the link:#paying-by-invoice[Paying by invoice]
section above. You must first pay any outstanding balance on the credit
or debit card or bank account before you can change to paying by
invoice. Contact support to see if you can change to paying by invoice.

=== Can I change from paying by invoice to using a different payment method?

You can’t automatically change from paying by invoice to paying with a
different payment method. Instead, you must
link:../try-or-buy-microsoft-365.md#buy-a-different-subscription[buy a
different subscription] paid for with a credit or debit card or bank
account, link:../subscriptions/move-users-different-subscription.md[move
all users to the new subscription], and then
link:../subscriptions/cancel-your-subscription.md[cancel the old
subscription].

=== Related content

link:manage-payment-methods.md[Manage payment methods] (article) +
link:view-your-bill-or-invoice.md[View your bill or invoice] (article) +
link:understand-your-invoice2.md[Understand your bill or invoice]
(article)
