= Understand your bill or invoice
:audience: Admin
:author: cmcatee-MSFT
:description: Learn how to read and understand your bill or invoice for Microsoft business products.
:f1.keywords: ["MACBillingBillsPaymentsInvoices"]
:manager: scotv
:ms.author: cmcatee
:ms.collection: ["highpri", "M365-subscription-management", "Adm_O365"]
:ms.custom: ["commerce_billing", "VSBFY23", "AdminSurgePortfolio", "AdminTemplateSet"]
:ms.date: 08/08/2022
:ms.localizationpriority: medium
:ms.reviewer: amberb, vikdesai
:ms.service: o365-administration
:ms.topic: article
:search.appverid: MET150

== Understand your bill or invoice

The invoice provides a summary of your charges and instructions for payment.
You can <<view-your-online-invoice,view your online invoice>> in the Microsoft 365 admin center.
You can also download it in the Portable Document Format (.pdf) to send via email.

To view and print your invoice:

. On the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=2102895[Bills & payments] page, select an invoice date range.
. To print or save a PDF copy of the bill, select *Download invoice PDF*, and then print the PDF.

To learn more, see xref:view-your-bill-or-invoice.adoc[View your bill or invoice].

If you only have a Microsoft 365 subscription, see xref:understand-your-invoice2.adoc[Understand your bill or invoice for Microsoft 365 for business].

=== How often and when am I billed?

Depending on the billing frequency you chose when you bought your subscription, you receive an invoice monthly, every 3 months, every 6 months, or annually.
The amount of time since the last invoice date is called the Billing Period and is shown on page one of the invoice, above the Billing Summary section.
This time represents the date range during which charges accrue for the current invoice.
If you made a change to your subscription outside of this date range, like adding or removing licenses, the associated charges appear on the invoice for the next billing period.

Starting on page two of the invoice, you see the charges grouped by product order.
For Azure customers, the charges might be organized by invoice section.

At the end of each billing period, you receive an email that says your new invoice is ready to view or download in the Microsoft 365 admin center.
If you have more than one billing profile, you receive an invoice for each billing profile.
Learn how to xref:view-your-bill-or-invoice.adoc[find and view your bill or invoice].

=== Understand the invoice header

The top of the first page identifies who is accountable for payment, where the bill is sent to, and a summary of charges.

|===
| Term | Description

| Sold to
| The billing account that identifies the name and address of the legal entity responsible for payment.
This information can be managed on the https://go.microsoft.com/fwlink/p/?linkid=2084771[Billing accounts] page, where you can find the account agreement and manage roles and permissions.

| Bill to
| Identifies who receives the invoice.
This information can be managed on the https://go.microsoft.com/fwlink/p/?linkid=2103629[Billing profiles] page.
The billing profile is also shown on the online invoice page, in the *Invoice summary* section.
To learn more about billing profiles and how you can use them to build more flexible billing options for your organization, see xref:manage-billing-profiles.adoc[Manage billing profiles].

| Billing Profile
| The name of the billing profile used to define invoice properties like *Bill to*, *PO number*, and payment terms.
This information can be managed on the https://go.microsoft.com/fwlink/p/?linkid=2103629[Billing profiles] page.
For more information about billing profiles and how you can use them to build more flexible billing options for your organization, see xref:manage-billing-profiles.adoc[Manage billing profiles].

| Invoice number
| A unique, Microsoft-generated invoice number used for tracking purposes.

| Invoice date
| Date that the invoice is generated, typically five to 12 days after the end of the billing cycle.
You can check your invoice date on the billing profile details page.
Charges that occur between the end of the billing period and the invoice date are included in the invoice for the next month, since they are in the next billing period.
The billing period start and end dates for each invoice are listed in the invoice PDF above *Billing Summary*.

| Payment terms
| How you pay for your Microsoft bill.
_Net 30 days_ means that you pay by following instructions on your invoice, within 30 days of the invoice date.
|===

=== Understand the billing summary

The *Billing Summary* shows the summary of charges since the previous billing period, any credits that were applied, tax, and the total amount due.

|===
| Term | Description

| Charges
| Total number of products purchased for this billing period, and their related charges and taxes.
Purchases are aggregated to provide a concise view of your bill.

| Credits
| Credits you received from returns

| Azure credits applied
| Your Azure credits that are automatically applied to Azure charges each billing period.
If you don't have any Azure credits, this field is hidden.
For more information about Azure credits, see link:/azure/billing/billing-mca-check-azure-credits-balance[Track Microsoft Customer Agreement Azure credit balance].

| Subtotal
| The pre-tax amount due

| Tax
| The type and amount of tax that you pay, depending on the country of your billing profile.
If you don't have to pay tax, no tax is shown on your invoice.
|===

==== Understand your charges

The charges pages show the cost broken down by product.
For Azure customers, the charges might be organized by invoice section.
For more information about how invoice sections are used with Azure products, see link:/azure/billing/billing-mca-overview#invoice-sections[Invoice sections] in link:/azure/billing/billing-mca-overview[Get started with your Microsoft Customer Agreement billing account].
Within each product order, cost is broken down by service family.

|===
| Term | Description

| Unit price
| The effective unit price of the service (in pricing currency) that is used to calculate the charge.
This price is unique for a product, service family, meter, and offer.

| Qty
| Quantity purchased or consumed during the billing period

| Charges/Credits
| Net amount of charges after credits/refunds are applied

| Azure Credit
| The amount of Azure credits applied to the Charges/Credits

| Tax rate
| Tax rate, depending on the country

| Tax amount
| Amount of tax applied to the purchase based on tax rate

| Total
| The total amount due for the purchase
|===

Line items details vary depending on the type of product you're charged for.
For example, for Azure products, the amount of Azure credits applied is shown.
Seat-based products show a unit price and quantity.
The invoice details show the products purchased, discount or credits that were applied, tax rate and amount, and the line item totals.

____
Total = Charges - Azure Credit + Tax
____

The total amount due for each service family is calculated by subtracting Azure credits from credits/charges, and adding tax:

____
Total = Charges/Credits - Azure Credit + Tax
____

If there are Azure charges on your invoice that you would like more details on, see link:/azure/cost-management-billing/understand/review-customer-agreement-bill[Review your Microsoft Customer Agreement invoice].

=== Understand the last invoice page

==== Payment instructions

At the bottom of the invoice are instructions on how to pay your bill.
You can pay by wire, check, or online.

==== Publisher information

If you have third-party services in your bill, the name and address of each publisher is listed at the bottom of your invoice.

=== View your online invoice

Invoices are available online.
A link to your online invoice is available from your PDF invoice, and from an email notification.
The online invoice is expandable so you can view the charges on your invoice and see more details for each item.
The online invoice includes:

* *Pricing details*&mdash;Additional information including details about discounts and product pricing.
* *Online payment*&mdash;You can choose to make a payment online from the invoice.
* *Azure cost management*&mdash;For Azure customers, online invoices include a link to Azure cost management.

==== To view your online invoice

. In the admin center, go to the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=2102895[Bills & payments] page.
. To download the .pdf version of your invoice, choose *Download invoice PDF* in the row for the invoice you want to see.
. To view your online invoice, choose an invoice from the list.
You can also download the .pdf from the invoice details page.

=== Invoice FAQ

==== When is my Invoice available?

Some invoices are generated within 24 hours of the purchase.
Other invoices are generated at the end of the billing period and include all items from that period.

==== How do I pay the amount due on my Invoice?

Payment instructions depend on your payment method and are provided at the bottom of the invoice PDF.
If your payment method is a credit card, it's automatically charged within 10 days of the invoice date.
If your payment method is by check or wire transfer, see the information under *Payment Instructions* in the PDF.

==== What's the difference between "Sold to" and "Bill to" addresses?

* *Sold to:* The legal entity responsible for payment and identified on the invoice.
The address provided here is used to determine your tax rate unless you opt to provide an alternative shipping address during your purchase.
For more information, see xref:tax-information.adoc[Tax information].
* *Bill to:* The address where the physical invoice is sent, if applicable.
There can be multiple *Bill to* addresses per legal entity, but only one *Bill to* address per billing profile.

==== What are "Billed amount" and "Amount due?"

* *Billed amount:* The total amount for the purchase that you made.
* *Amount due:* The remaining balance for what you owe.

==== What is the difference between "'Service period" and "Billing period?"

* *Service period:* The time period during which you're charged to use the service.
* *Billing period:* The time period since the last invoice date.

==== Why don't I see Azure prepayment as a payment method?

Azure prepayment is available as a payment method only for eligible Azure product and services

=== Need help? Contact support

If you have questions or need help with your Azure credits, https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/newsupportrequest[create a support request with Azure support].

If you have questions or need help with your invoice in Microsoft 365 admin center, xref:../../admin/get-help-support.adoc[contact support for business products].

=== Related content

xref:understand-your-invoice2.adoc[Understand your bill or invoice for Microsoft 365 for business] (article) + link:/azure/billing/billing-mca-check-azure-credits-balance[Track Microsoft Customer Agreement Azure credit balance] (article) + link:/azure/cost-management-billing/understand/review-customer-agreement-bill[Review your Microsoft Customer Agreement invoice] (article) + link:/azure/billing/billing-mca-overview[Get started with your Microsoft Customer Agreement billing account] (article)
