= 
cmcatee-MSFT

== View your Microsoft 365 for business subscription bill or invoice

Check out https://go.microsoft.com/fwlink/?linkid=2197659[Microsoft 365
small business help] on YouTube.

This article is for people who have a Microsoft 365 for business
subscription.

If you need help with interpreting the charges you see on your bill, see
link:understand-your-invoice2.md[Understand your bill or invoice] for a
detailed walkthrough.

*Have a problem with your bill?*
link:../../admin/get-help-support.md[Contact support for business
products].

=== Before you begin

You must be a Global or Billing admin to do the steps described in this
article.

=== Watch: View, download, or print your bill

Check out this video and others on our
https://go.microsoft.com/fwlink/?linkid=2209539[YouTube channel].

____
{empty}[!VIDEO
https://www.microsoft.com/videoplayer/embed/RE1FGmo?autoplay=false]
____

[arabic]
. In the Microsoft 365 admin center, select *Billing* in the left
navigation pane, and then select the *Invoices* tab.
. Select an invoice to view it. If you don’t see an invoice, select
*Filter by: Last 6 months* from the drop-down list.
. To view the invoice details, select *Download PDF* in the top-right
corner of the invoice.

=== View a bill or invoice

::: moniker range=``o365-worldwide''

[arabic]
. In the admin center, go to the *Billing* > Bills & payments page.

::: moniker-end

::: moniker range=``o365-21vianet''

[arabic]
. In the admin center, go to the *Billing* > Bills & payments page.

::: moniker-end

[arabic, start=2]
. On the *Invoices* tab, choose the invoice that you want to view. If
you don’t see an invoice, use the date filter and select *Past 3
months*, *Past 6 months*, or *Specify date range*.
. On the *Invoice summary* page, you see invoice details including the
list of items, the price for each item, and the total cost for all items
in the invoice.
. To print or save a PDF copy of the invoice, select *Download PDF*.

If you want to receive a copy of your billing statement in email, see
link:manage-billing-notifications.md[Manage billing notifications and
invoice attachments].

::: moniker range=``o365-21vianet''

=== Request a Fapiao

You can submit your Fapiao request to our
https://go.microsoft.com/fwlink/p/?linkid=837465[Fapiao management
system] about three (3) days after you have paid.

[arabic]
. In the admin center, go to the *Billing* > *Bills & payments* page.
. Find the invoice that you want, and then select *Get Fapiaos*.

____
{empty}[!NOTE]

You need a registered account to access the
https://go.microsoft.com/fwlink/p/?linkid=837465[Fapiao management
system]. If you haven’t already set up an account, see
link:../../admin/services-in-china/apply-for-a-fapiao.md[Apply for a
Fapiao for Office 365 operated by 21Vianet].
____

::: moniker-end

____
{empty}[!NOTE]

Microsoft 365 services do not provide payment receipts. For credit card
payments, please use the invoice and credit card billing statement to
match your payment.
____

=== Run the Unknown Charge Diagnostic

As a Microsoft 365 Global admin, you can use a diagnostic tool that runs
within the Microsoft 365 admin center to research unexpected charges
from Microsoft that appear on your bank or credit card statement.

____
[!NOTE] The Unknown Charge Diagnostic is only available for customers
who bought their products and services from Microsoft.com, including
Microsoft 365 Enterprise, Education, and Non-profit.
____

Select the *Run Tests* link below to open the diagnostic tool in the
Microsoft 365 admin center.

____
{empty}[!div class=``nextstepaction'']
https://aka.ms/PillarUnknownCharge[Run Tests: Unknown Charge]
____

=== Next steps

If you have a balance and would like to pay it, you can do that online.
To learn how, see link:pay-for-your-subscription.md[Pay for your
subscription].

=== Related content

link:pay-for-your-subscription.md[Pay by invoice&#44; credit card&#44; or bank
account] (article) +
link:manage-payment-methods.md[Manage payment methods] (article) +
link:mexico-billing-info.md[Billing information for Microsoft 365 for
business in Mexico] (article) +
link:/education/windows/school-get-minecraft[Minecraft: Education
Edition payment options] (article)
