= Guest users in the Microsoft 365 admin center
:audience: Admin
:author: kwekua
:description: Learn how to populate the Guest users list in the Microsoft 365 admin center so guests can attend meetings, view documents and chat in Teams they're invited to.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.author: kwekua
:ms.collection: ["M365-subscription-management", "Adm_O365", "Adm_TOC"]
:ms.custom: ["AdminSurgePortfolio", "AdminTemplateSet", "admindeeplinkMAC"]
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: overview
:search.appverid: ["BCS160", "MET150", "MOE150"]

== Guest users in Microsoft 365 admin center

By default, guest access for Microsoft 365 groups is turned on for your organization.
Admins can control whether to allow guest access to groups for their whole organization or for individual groups.

Any guests you add to your Microsoft Teams, SharePoint, or Azure Active Directory are also added to the *Guest users* list in the https://go.microsoft.com/fwlink/p/?linkid=2074830[Microsoft 365 admin center].
Guests can attend meetings, view documents and chat in Teams they're invited to.
Once a user shows up in the *Guest users* list, you can remove their access there.

To view guest users, in the https://go.microsoft.com/fwlink/p/?linkid=2074830[Microsoft 365 admin center], in the left nav, expand *Users*, and then choose *Guest users*.

=== Before you begin

You must be a global administrator to perform this task.

=== Watch: Add guests to Teams

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/RE1FQMp]
____

=== Watch: Join a team as a guest

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/RE4tyys]
____

=== Understanding guest accounts in Microsoft 365

Being able to easily share files and documents with the right people while preventing oversharing requires planning.
The following resources provide more background to help you create a secure guest sharing environment in Microsoft 365.

* xref:../../solutions/plan-external-collaboration.adoc[Plan external collaboration]
* xref:../../solutions/create-secure-guest-sharing-environment.adoc[Create a secure guest sharing environment]
* xref:../../solutions/setup-secure-collaboration-with-teams.adoc[Set up secure file and document sharing and collaboration with Teams in Microsoft 365]
* link:/microsoftteams/guest-access[Guest access in Microsoft Teams]

In addition to Microsoft Teams and SharePoint, Microsoft 365 also supports guest access in other applications.
The following Microsoft 365 products support guest access.

* Power Apps (Canvas apps) - link:/power-apps/maker/canvas-apps/share-app-guests[Share a canvas app with guest users].
* Lists - https://support.microsoft.com/office/external-or-guest-sharing-in-onedrive-sharepoint-and-lists-7aa070b8-d094-4921-9dd9-86392f2a79e7[External or guest sharing in OneDrive, SharePoint, and Lists].
* OneDrive - https://support.microsoft.com/office/external-or-guest-sharing-in-onedrive-sharepoint-and-lists-7aa070b8-d094-4921-9dd9-86392f2a79e7[External or guest sharing in OneDrive, SharePoint, and Lists].
* Planner -- Applies to Web and mobile platforms.
https://support.microsoft.com/office/guest-access-in-microsoft-planner-cc5d7f96-dced-4da4-ab62-08c72d9759c6[Guest access in Microsoft Planner].
* Microsoft 365 groups - xref:../create-groups/manage-guest-access-in-groups.adoc[Manage guest access in Microsoft 365 groups].
* Yammer - link:/yammer/work-with-external-users/create-and-manage-external-groups[Work with external groups in Yammer networks not aligned to native mode].

For Microsoft Office applications like Microsoft Word and Excel, guest access is controlled by the location of the output file, for example, Microsoft SharePoint, Teams, and OneDrive.

=== Next steps: Add guests in Azure Active Directory

To add guests in the Azure Active Directory, see link:/azure/active-directory/b2b/b2b-quickstart-add-guest-users-portal[add guest users].

After you add a user you can also assign them to a group, or give them access to an app in your organization.
Once you've added a user in the Azure AD portal, that user will also be listed on the *Guest users* page in the https://go.microsoft.com/fwlink/p/?linkid=2074830[Microsoft 365 admin center].

See link:/azure/active-directory/b2b/tutorial-bulk-invite[add guests in bulk] to invite multiple guests to collaborate with your organization.

=== Related content

xref:../create-groups/manage-guest-access-in-groups.adoc[Manage guest access in Microsoft 365 groups] (article) + xref:../../solutions/per-group-guest-access.adoc[Prevent guests from being added to a specific Microsoft 365 group or Microsoft Teams] (article) + https://techcommunity.microsoft.com/t5/microsoft-365-blog/new-organization-switcher-in-the-microsoft-365-admin-center/ba-p/1165543[Organization switcher in the Microsoft 365 admin center]  (article)
