'''

title: "About the Exchange Administrator role" f1.keywords:

* NOCSH ms.author: efrene author: efrene manager: scotv audience: Admin ms.topic: overview ms.service: o365-administration ms.localizationpriority: medium ms.collection:
* M365-subscription-management
* Adm_O365

ms.custom:

* AdminSurgePortfolio
* admindeeplinkEXCHANGE search.appverid:
* BCS160
* MET150
* MOE150
* GEA150 ms.assetid: 097ae285-c4af-4319-9770-e2559d66e4c8 description: "Exchange administrators manage your organization's email and mailboxes and, for example, recover deleted items in a user's mailbox." --

== About the Exchange Administrator role

To help you administer Microsoft 365, you can xref:assign-admin-roles.adoc[assign] users permissions to manage your organization's email and mailboxes from the https://go.microsoft.com/fwlink/p/?linkid=2059104[Exchange admin center].
You do this by assigning them to the Exchange Administrator role.

____
[!TIP] When you assign someone to the Exchange Administrator role, we recommend assigning them to the Service Support Administrator role.
This way they can see important information in the Microsoft 365 admin center, such as the health of the Exchange Online service, and change and release notifications.
____

Here are some of the key tasks users can do when they are assigned to the Exchange Administrator role:

* link:/Exchange/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages[Recover deleted items in a user mailbox - Admin Help]
* xref:../../compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.adoc[Set up an archive and deletion policy for mailboxes in your organization].
* Set up mailbox features such as the mailbox sharing policy: how users can share calendar and contacts information with others outside of your organization.
* Set up "link:give-mailbox-permissions-to-another-user.md#send-email-from-another-users-mailbox[Send as]" and "link:give-mailbox-permissions-to-another-user.md#send-email-on-behalf-of-another-user[Send on behalf]" delegates for someone's mailbox.
For example, an executive may want their assistant to have the ability to send mail on their behalf.
* xref:../email/create-a-shared-mailbox.adoc[Create a shared mailbox] so a group of people can monitor and send email from a common email address.
* xref:../../security/office-365-security/anti-spam-protection.adoc[Email anti-spam protection] and malware filters for the organization.
* Manage Microsoft 365 groups

=== Exchange Online role groups

If you have a large organization, the Exchange admin might want to assign users to Exchange role groups.
When an admin adds a user to a role group, the user gets permissions to perform certain business functions only members of that group can do.

For example, the Exchange admin might assign someone to the Discovery Management role group so they can perform searches of mailboxes for data that meets certain criteria.
To learn more, see link:/exchange/permissions-exo/permissions-exo[Permissions in Exchange Online] and link:/exchange/manage-role-groups-exchange-2013-help[Manage Role Groups].

=== Learn about other admin roles

* xref:about-admin-roles.adoc[About Microsoft 365 admin roles]
* link:/sharepoint/sharepoint-admin-role[About the SharePoint Online admin role]
* link:/skypeforbusiness/skype-for-business-online[About the Skype for Business admin role]
* link:/MicrosoftTeams/using-admin-roles[Use Microsoft Teams admin role]
