= Step 4 - Forward a former employee's email to another employee or convert to a shared mailbox
:audience: Admin
:author: kwekua
:description: Forward a former employee's email to another employee or convert it to a shared mailbox where several people will be able to access it instead of one person.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.author: kwekua
:ms.collection: ["M365-subscription-management", "Adm_O365", "Adm_TOC", "SPO_Content"]
:ms.custom: ["MSStore_Link", "TRN_M365B", "OKR_SMB_Videos", "AdminSurgePortfolio", "m365solution-removeemployee"]
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["BCS160", "MET150", "MOE150"]

== Step 4 - Forward a former employee's email to another employee or convert to a shared mailbox

In this step, you assign the former employee's email address to another employee, or convert the user's mailbox to a shared mailbox.

=== Convert former employee's mailbox to a shared mailbox

When you convert a user's mailbox to a shared mailbox, all of the existing email and calendar are retained.
Only now it's in a shared mailbox where several people will be able to access it instead of one person.
You can convert a shared mailbox back to a user (private) mailbox at a later date if you want.

* Creating a shared mailbox is the less expensive way to go because you won't have to pay for a license *as long as the mailbox is smaller than 50 GB*.
If it is over 50 GB, you'll need to assign a license to it.
* If you convert the mailbox to a shared mailbox, all the old email will be available, too.
This can take up a lot of space.
* If you set up email forwarding, only _new_ emails sent to the former employee will be sent to the current employee.

Follow these steps to xref:../email/convert-user-mailbox-to-shared-mailbox.adoc[convert the user's mailbox to a shared mailbox].

=== Forward a former employee's email to another employee

____
[!IMPORTANT] If you're setting up email forwarding or a shared mailbox, in the end, don't delete the former employee's account.
The account needs to be there to anchor the email forwarding or shared mailbox.
____

. In the admin center, go to the *Users* > https://go.microsoft.com/fwlink/p/?linkid=834822[Active users] page.
. Select the name of the employee that you want to block, and then select the *Mail* tab.
. Under *Email Forwarding*, select *Manage email forwarding*.
. Turn on *Forward all email sent to this mailbox*.
In the *Forwarding address* box, type the email address of the current employee who's going to get the email.
. Select *Save*.
. Remember, don't delete the former employee's account.

==== Cancel Outlook meetings

Make sure to cancel all meetings that the former user had on their calendar.
This lets people remove the meetings created by the former user.

If the person had meetings that booked equipment or rooms, they won't be available to be booked until those meetings are canceled.
Read https://support.microsoft.com/office/delete-an-appointment-or-a-meeting-2703bfdb-9a07-4396-be3b-a9f79438455b[Delete an appointment or a meeting] for the steps.

=== Related content

https://support.microsoft.com/office/open-and-use-a-shared-mailbox-in-outlook-d94a8e9e-21f1-4240-808b-de9c9c088afd[Open and use a shared mailbox in Outlook]

https://support.microsoft.com/office/access-another-person-s-mailbox-a909ad30-e413-40b5-a487-0ea70b763081[Access another person's mailbox]

link:/exchange/exchange-admin-center[Exchange admin center in Exchange Online]

https://support.microsoft.com/office/manage-another-person-s-mail-and-calendar-items-afb79d6b-2967-43b9-a944-a6b953190af5[Manager another person's mail and calendar items]
