= Step 6 - Remove and delete the Microsoft 365 license from a former employee
:audience: Admin
:author: kwekua
:description: You can remove a former employee's Microsoft 365 license, and then delete it from your subscription or assign the license to another user.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.author: kwekua
:ms.collection: ["M365-subscription-management", "Adm_O365", "Adm_TOC", "SPO_Content"]
:ms.custom: ["MSStore_Link", "TRN_M365B", "OKR_SMB_Videos", "AdminSurgePortfolio", "m365solution-removeemployee"]
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["BCS160", "MET150", "MOE150"]

== Step 6 - Remove and delete the Microsoft 365 license from a former employee

If you don't want to pay for a license after someone leaves your organization, you need to remove their Microsoft 365 license and then delete it from your subscription.
You can assign a license to another user if you don't delete it.

If the mailbox needs to be accessed by authorized people who have been granted eDiscovery permissions for compliance or legal reasons, it must be assigned an Exchange Online Plan 2 license (or an Exchange Online Plan 1 license with an Exchange Online Archiving add-on license) so that a hold can be applied to the mailbox before it's deleted.
After the user account is deleted, any Exchange Online license associated with the user account will be available to assign to a new user.

When you remove the license, all that user's data is held for 30 days.
You can xref:get-access-to-and-back-up-a-former-user-s-data.adoc[access] the data, or xref:restore-user.adoc[restore] the account if the user comes back.
After 30 days, all the user's data (except for documents stored on SharePoint Online) is permanently deleted from Microsoft 365 and can't be recovered.

. In the admin center, go to the *Users* > https://go.microsoft.com/fwlink/p/?linkid=834822[Active users] page.
. Select the name of the employee that you want to block, and then select the *Licenses and Apps* tab.
. Clear the check boxes for the license(s) you want to remove, and then select *Save changes*.

*To reduce the number of licenses you're paying for* until you hire another person, do the following steps:

. In the admin center, go to the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=842054[Your products] page, and select the *Products* tab.
. Select the subscription from which you want to remove licenses.
. On the details page, select *Remove licenses*.
. In the *Remove licenses* pane, under New quantity, in the *Total licenses* box, enter the total number of licenses that you want for this subscription.
For example, if you have 25 licenses and you want to remove one of them, enter 24.
. Select *Save*.

When you xref:add-users.adoc[add another person] to your business, you'll be prompted to buy a license at the same time, with just one step!

For more information about managing user licenses for Microsoft 365 for business, see xref:../manage/assign-licenses-to-users.adoc[Assign licenses to users in Microsoft 365 for business], and xref:../manage/remove-licenses-from-users.adoc[Unassign licenses from users in Microsoft 365 for business].

=== How the deleted employee account affects Skype for Business

When you remove a user's license from Office 365, the PSTN calling number associated with the user will be released.
You can assign it to another user.

If the user belongs to a queue group, they will no longer be a viable target of the call queue agents.
So, we recommend also removing the user from the groups associated with the call queue.

=== Set up call forwarding to people in your organization

If you need to set up call forwarding for the terminated employee's phone number, the call forwarding setting under calling policies can set up forwarding where incoming calls can be forwarded to other users or can ring another person at the same time.
For more information, see link:/microsoftteams/teams-calling-policy[Calling policies in Microsoft Teams].
