= Reset passwords
:audience: Admin
:author: kwekua
:description: Sign in with your Microsoft 365 admin account to reset passwords for users when you have a Microsoft 365 for business subscription.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.assetid: 7a5d073b-7fae-4aa5-8f96-9ecd041aba9c
:ms.author: kwekua
:ms.collection: ["highpri", "M365-subscription-management", "Adm_O365", "Adm_TOC"]
:ms.custom: ["VSBFY23", "TopSMBIssues", "MSStore_Link", "TRN_M365B", "OKR_SMB_Videos", "AdminSurgePortfolio", "AdminTemplateSet", "business_assist", "adminvideo"]
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["BCS160", "MET150", "MOE150", "BEA160", "GEA150"]

== Reset passwords in Microsoft 365 for business

Check out https://go.microsoft.com/fwlink/?linkid=2197659[Microsoft 365 small business help] on YouTube.

This article explains how to reset passwords for yourself and for your users when you have a Microsoft 365 for business subscription.

____
[!NOTE] You can also set up self-service password reset for your users so they can reset their own passwords.
To learn more, see xref:let-users-reset-passwords.adoc[Let users reset their own passwords].
____

____
[!TIP] If you need help with the steps in this topic, consider https://go.microsoft.com/fwlink/?linkid=2186871[working with a Microsoft small business specialist].
With Business Assist, you and your employees get around-the-clock access to small business specialists as you grow your business, from onboarding to everyday use.
____

=== Before you begin

This article is for people who set password expiration policy for a business, school, or nonprofit.
To complete these steps, you need to sign in with your Microsoft 365 admin account.
xref:../admin-overview/admin-center-overview.adoc[Overview in the Microsoft 365 admin center].

You must be an xref:about-admin-roles.adoc[global admin or password administrator] to perform these steps.

=== Watch: Reset a business password for a user

Check out this video and others on our https://go.microsoft.com/fwlink/?linkid=2198204[YouTube channel].

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/RE1FVVP]
____

. When a user requests a new password, you'll receive a password reset request in email.
To reset the password, open the app launcher and select *Admin*.
. In the Microsoft 365 admin center, select *Users*,  https://go.microsoft.com/fwlink/p/?linkid=834822[*Active users*], and then select the key icon next to the user who requested the reset.
. Select *Auto-generate password* to have a random password automatically created.
. Select *Reset*.

If you found this video helpful, check out the link:../../business-video/index.yml[complete training series for small businesses and those new to Microsoft 365].

=== Steps: Reset a business password for a user

. In the admin center, go to the *Users* > https://go.microsoft.com/fwlink/p/?linkid=834822[Active users] page.
. On the *Active users* page, select the user and then select *Reset password*.
. Follow the instructions on the *Reset password* page to auto-generate a new password for the user or create one for them, and then select *Reset*.
. Enter an email address the user can get to so they receive the new password, and follow up with them to make sure they got it.

=== Let users reset their own passwords

We strongly recommend that you set up self-service password reset.
This way you don't have to manually reset passwords for your users.
Less work for you!
To learn how, see xref:let-users-reset-passwords.adoc[Let users reset their own passwords in Office 365].

=== Resend user password

. In the admin center, go to the *Users* > https://go.microsoft.com/fwlink/p/?linkid=834822[Active users] page.
. On the *Active users* page, select the user and then select *Reset password*.
. Follow the instructions on the *Reset password* page to auto-generate a new password for the user or create one for them, and then select *Reset*.
. Enter an email address the user can get to, so they receive the new password, and follow up with them to make sure they got it.

=== Reset my admin password

Use these steps if you forgot your password but you're able to sign in to Microsoft 365 because, for example, your password is saved in your browser:

. Select your name (icon) in upper right corner > *My Account* > *Personal Info*.
. Under *Contact details*, double-check that your *Alternate email* is accurate and that you've provided a mobile phone number.
If not, change them now.
. Sign out: select your name in the upper right corner > *Sign out*.
. Now sign in again: type your user name > *Next* > and then select *Forgot password*.
. Follow the steps in the wizard to reset your password.
It uses your alternate contact info to verify you're the right person to reset your password.

If you forgot your password and can't sign in:

* Ask another global admin in your business to reset your password for you.
* Make sure you've provided alternate contact information, including a mobile phone number.
* Or, xref:../../business-video/get-help-support.adoc[call Microsoft Support].

=== Reset all business passwords for everyone in your organization at the same time

These steps work for a business with tens of users.
If you have hundreds or thousands of users, see the next section on resetting passwords in bulk (maximum 40 users at a time).

. In the admin center, go to the *Users* > https://go.microsoft.com/fwlink/p/?linkid=834822[Active users] page.
. Select the option next to *Display name* to select everyone in your business.
Then unselect yourself.
You can't reset your own password at the same time you reset everyone else's password.
. Select *Reset password*.
. Follow the instructions on the *Reset password* page, and select *Reset*.
If you opted for auto-generating the passwords, the new temporary passwords will be displayed.
. Enter an email address where you can receive the temporary passwords.
You'll need to notify your users what their temporary passwords are.

=== Reset business passwords in bulk

Use PowerShell!
Check out this post by Eyal Doron: https://go.microsoft.com/fwlink/?linkid=853696[Managing passwords with PowerShell].

// Here's a related article: [Set the passwords for multiple user accounts](/office365/enterprise/powershell/manage-office-365-with-office-365-powershell).

For overview information, see xref:../../enterprise/manage-microsoft-365-with-microsoft-365-powershell.adoc[Manage Microsoft 365 with PowerShell].

=== Force a password change for all users in your business

Check out this great blog post by Vasil Michev, Microsoft MVP: https://go.microsoft.com/fwlink/?linkid=853693[Force password change for all users in Office 365].

=== Set strong passwords

. link:/office365/enterprise/powershell/connect-to-office-365-powershell#connect-with-the-microsoft-azure-active-directory-module-for-windows-powershell[Connect to Microsoft 365 with PowerShell].
. Using PowerShell, you can turn off strong password requirements for all users with the following command:
+
```powershell  Get-MsolUser | Set-MsolUser -StrongPasswordRequired $false

. You can turn *OFF* strong password requirements for specific users with this command:
+
[,powershell]
----
 Set-MsolUser –UserPrincipalName –StrongPasswordRequired  $false
----

____
[!NOTE] The userPrincipalName must be in the Internet-style sign-in format where the user name is followed by the at sign (@) and a domain name.
For example: user@contoso.com.
____

=== I don't have a Microsoft 365 for business subscription

Try this article: https://support.microsoft.com/office/eba0b4a2-c0ae-472c-99f6-bc63ee2425a8?wt.mc_id=SCL_reset-passwords_AdmHlp[I forgot the username or password for the account I use with Office.]

=== Related content

xref:../add-users/let-users-reset-passwords.adoc[Let users reset their own passwords] (article) + xref:../add-users/reset-passwords.adoc[Reset passwords] (article) + xref:set-password-to-never-expire.adoc[Set an individual user's password to never expire] (article) + xref:../manage/set-password-expiration-policy.adoc[Set the password expiration policy for your organization] (article) + link:../../business-video/index.yml[Microsoft 365 for business training videos] (link page)
