= Microsoft Teams EHR connector Virtual Appointments report
:appliesto: ["Microsoft Teams", "Microsoft 365 for frontline workers"]
:audience: ITPro
:author: LanaChin
:description: Learn how to use the Teams EHR connector Virtual Appointments report in the Microsoft Teams admin center to get an overview of EHR-integrated virtual appointment usage in your organization.
:f1.keywords: ["NOCSH"]
:manager: samanro
:ms.author: v-lanachin
:ms.collection: ["M365-collaboration", "Teams_ITAdmin_Healthcare", "microsoftcloud-healthcare", "m365solution-healthcare", "m365solution-scenario", "m365-frontline"]
:ms.localizationpriority: high
:ms.reviewer:
:ms.service: microsoft-365-frontline
:ms.topic: conceptual
:search.appverid: MET150
:searchScope: ["Microsoft Teams", "Microsoft Cloud for Healthcare"]

== Microsoft Teams EHR connector Virtual Appointments report

The Microsoft Teams Electronic Health Record (EHR) connector Virtual Appointments report in the Microsoft Teams admin center gives you a quick and easy way to view Teams EHR-integrated virtual appointment usage in your organization.

To view the report, you must be a global admin, Teams admin, Global reader, or Report reader.

=== View the report

There are two ways to access and view the report in the Teams admin center.

* Through the <<the-ehr-connector-usage-card,EHR connector usage card>> in the dashboard
* Directly by choosing <<the-teams-ehr-connector-virtual-appointments-report,*EHR connector Virtual Appointments*>> in *Analytics & reports* > *Usage reports*

==== The EHR connector usage card

In the left navigation of the Microsoft Teams admin center, choose *Dashboard*, and then go to the *EHR connector Virtual Appointments* card.

Here, you get an at-a-glance view of Teams EHR-integrated virtual appointment activity by month, including completed appointments, remaining allocation, and whether you've exceeded the monthly limit (depending on the license you have).

:::image type="content" source="media/ehr-connector-report-card.png" alt-text="Screenshot of the EHR connector usage card in the Teams admin center dashboard." lightbox="media/ehr-connector-report-card.png":::

Choose *View details* to see report details.
To purchase more licenses, choose *Buy more*.

==== The Teams EHR connector Virtual Appointments report

. In the left navigation of the Teams admin center, go to *Analytics & reports* > *Usage reports*.
. On the *View reports* tab, choose *EHR connector Virtual Appointments* and a date range.
Then, select *Run report*.
+
:::image type="content" source="media/ehr-connector-report.png" alt-text="Screenshot of the Teams EHR connector Virtual Appointments report in the Teams admin center." lightbox="media/ehr-connector-report.png":::

===== Interpret the report

|===
| Callout | Description

| *1*
| Each report shows the date for when the report was generated and the date range you chose.

| *2*
| The table gives you detailed information about each appointment that took place during the selected date range.
Keep in mind that you won't see entries for appointments in which either a staff member or patient didn't join.
<ul><li>**Start time (UTC)** is the date and time when both a staff member and participant are in the appointment.
</li> <li>**Duration** is the time difference between the start time and when the last person leaves the appointment.</li> <li>**Primary** is the name of the meeting organizer.
<li>**Primary's email** is the email address of the meeting organizer.</li> <li> *Department* is the department information for the appointment.
If the information isn't displayed correctly, contact your EHR support team.
For integration with Epic, make sure `+&departmentId=%PERFDEPID;;;
; ;;NONE;%+` is part of the provider integration record.
</li></li> <li>**Attendants** is the total number of staff members and participants in the appointment.</li> <li>**Within limit** indicates whether the appointment is within the allocation limit.
</li> </ul>

| *3*
| You can export the report to a CSV file for offline analysis.
Select *Export to Excel* to download the report.

| *4*
| Select *Filter* to filter the report details view.

| *5*
| Select *Full screen* to view the report in full screen mode.

| *6*
| Select *Edit columns* to add or remove columns in the table
|===

____
[!NOTE] For more analytics on Teams EHR-integrated virtual appointments, see xref:virtual-visits-usage-report.adoc[Virtual Visits usage report].
With the Virtual Visits usage report, you can view key metrics such as total appointments, lobby wait time, appointment duration, and no shows.
Use this information to gain insight into usage trends to help you optimize virtual appointments to deliver better business outcomes.
____

=== Related articles

* xref:ehr-admin-cerner.adoc[Virtual appointments with Teams - Integration into Cerner EHR]
* xref:ehr-admin-epic.adoc[Virtual appointments with Teams - Integration into Epic EHR]
