= 
daisyfell

== Learn where to start with a frontline deployment

Thanks for choosing Microsoft 365 for frontline workers. Whether you’re
an independent business or a large multi-national enterprise, Microsoft
365 and Teams for frontline workers can help bring your organization
together with tools for communication, collaboration, and productivity.
And no matter whether you’re just getting into collaboration tools for
the first time, or you’ve already been using Microsoft 365 and Teams for
your non-frontline workers, we can help you get up and running.

[width="100%",cols="50%,50%",options="header",]
|===
|Article |Description
|link:get-up-and-running.md[Trial setup for frontline managers] |If
you’re a manager of a frontline worker team, you can set up a trial for
your frontline workforce from within Microsoft Teams. Admins can learn
more about the manager-led setup at: link:flw-trial.md[Manage the
Frontline Trial in Teams].

|link:flw-pilot.md[Start with a pilot deployment of Microsoft 365 for
frontline workers] |Before you commit to a full rollout of Microsoft 365
for frontline workers across your organization, it’s a good idea to try
it out first with a small set of real people in your organization.

|link:flw-setup-microsoft-365.md[Set up Microsoft 365 for frontline
workers] |Follow this setup path if you’re an IT pro or responsible for
planning, or deploying Teams for Frontline Workers. It walks through
preparing your environment, setting up the core of Microsoft 365, and
then setting up the services you need for your scenarios.

|link:deploy-teams-at-scale.md[Deploy Microsoft Teams at scale] |Once
you’ve set up Microsoft 365 and assigned licenses to your users, you can
use PowerShell to create and manage Teams for your whole frontline
workforce.
|===

After you have set up Microsoft 365, Microsoft Teams, and any services
you need, you can configure Teams and the apps in Teams to support your
scenarios. Each of the paths above will walk you through the whole
process, from initial setup to a configured team with the apps your
users need to start working.
