= 
lanachin

== Use the Shifts connector wizard to connect Shifts to Blue Yonder Workforce Management

=== Overview

{empty}[!INCLUDE
link:includes/shifts-connector-wizard-intro.md[shifts-connector-wizard-intro]]

=== Integrate Shifts with Blue Yonder Workforce Management

The
link:shifts-connectors.md#microsoft-teams-shifts-connector-for-blue-yonder[Microsoft
Teams Shifts connector for Blue Yonder] enables you to integrate Shifts
with Blue Yonder Workforce Management (Blue Yonder WFM) to manage your
schedules and keep them up to date. In this article, we walk you through
how to run the wizard to set up a connection to Blue Yonder WFM through
the connector.

____
[!NOTE] You can also use PowerShell to integrate Shifts with Blue Yonder
WFM. To learn more, see
link:shifts-connector-blue-yonder-powershell-setup.md[Use PowerShell to
connect Shifts to Blue Yonder Workforce Management].
____

=== Before you begin

You must be a Microsoft 365 global admin to run the wizard.

==== Prerequisites

{empty} [!INCLUDE
link:includes/shifts-connector-prerequisites.md[shifts-connector-prerequisites]]

* The teams you want to map don’t have any schedules. If a team has an
existing schedule,
link:#remove-schedules-from-teams-you-want-to-map[remove the schedule
from the team] before you map a Blue Yonder WFM instance to it.
Otherwise, you’ll see duplicate shifts.

=== Remove schedules from teams you want to map

____
[!NOTE] Complete this step if you’re mapping Blue Yonder WFM instances
to existing teams that have schedules. If you’re mapping to teams that
don’t have any schedules or if you’re creating new teams to map to, you
can skip this step.
____

Use PowerShell to remove schedules from teams.

[arabic]
. First, you’ll need to install the PowerShell modules and get set up.
Follow the steps to
link:shifts-connector-powershell-manage.md#set-up-your-environment[set
up your environment]
. Run the following command:
+
[source,powershell]
----
Remove-CsTeamsShiftsScheduleRecord -TeamId <Teams team ID> -DateRangeStartDate <start time> -DateRangeEndDate <end time> -ClearSchedulingGroup:$false -EntityType <the scenario entities that you want to remove, the format is @(scenario1, scenario2, ...)> -DesignatedActorId <Teams team owner ID>
----
+
To get a list of scenarios for the `EntityType` parameter, run
link:/powershell/module/teams/get-csteamsshiftsconnectionconnector[Get-CsTeamsShiftsConnectionConnector].
Schedule data will be removed for the date and time range that you
specify.

To learn more, see
link:/powershell/module/teams/remove-csteamsshiftsschedulerecord[Remove-CsTeamsShiftsScheduleRecord].

=== Run the wizard

==== Get started

[arabic]
. In the left navigation of the https://admin.microsoft.com/[Microsoft
365 admin center], choose *Setup*, and then go to the *Apps and email*
section.
. Select *Connect your workforce management system*. Here, you can learn
more about Shifts connectors and the frontline worker and manager
experience when you connect Shifts to your WFM system. :::image
type=``content''
source=``media/shifts-connector-wizard-get-started.png''
alt-text=``Screenshot of the details page for the Shifts connector
wizard in the Microsoft 365 admin center.''
lightbox=``media/shifts-connector-wizard-get-started.png'':::
. When you’re ready, select *Get started*.
. On the Choose your connector page, choose *Blue Yonder Workforce
Management*, and then select *Next* to create a Blue Yonder WFM
connection.

==== Enter connection details

[arabic]
. On the Connection details page, give your connection a unique name. It
can’t be longer than 128 characters or have any special characters.
:::image type=``content''
source=``media/shifts-connector-wizard-connection-details.png''
alt-text=``Screenshot of the Connection details page of the wizard,
showing connection settings.''
lightbox=``media/shifts-connector-wizard-connection-details.png'':::
. Enter your Blue Yonder WFM service account name and password and
service URLs.
. When you’re done, select *Next* to test the connection with the
settings you entered.

==== Choose sync settings

On the Sync settings page, you choose the information to sync from Blue
Yonder WFM to Shifts, the sync frequency, and whether Shifts users can
make changes to the data.

[arabic]
. Enter your Microsoft 365 system account. :::image type=``content''
source=``media/shifts-connector-wizard-sync-settings.png''
alt-text=``Screenshot of the Sync settings page of the wizard, showing
sync settings.''
lightbox=``media/shifts-connector-wizard-sync-settings.png'':::
. Under *Email notification recipients*, choose who receives email
notifications about this connection. You can add individual users and
groups. The email notifications contain information about connection
setup status and any issues or errors that may occur after the
connection is set up.
. Choose your sync settings:
[arabic]
.. Under *Schedule and shifts*, choose the Blue Yonder WFM data that
Shifts users can see or change, and then set the sync frequency.
.. Under *Time card*, choose what action Shifts users can do with time
entries.
.. Under *Requests*, choose the types of requests that Shifts users can
see and create.
+
____
[!IMPORTANT] If you chose any of the following options to disable open
shifts, open shift requests, swap requests, or time off requests,
there’s another step you need to do to hide the capability in Shifts.

* Open shifts: *Shifts users will not see Blue Yonder WFM data*
* Swap requests: *Feature is disabled for all users*
* Time off requests: *Feature is disabled for all users*

After you run the wizard, make sure you follow the steps in the
link:#disable-open-shifts-open-shifts-requests-swap-requests-and-time-off-requests[Disable
open shifts&#44; open shifts requests&#44; swap requests&#44; and time off requests]
section later in this article.
____
. When you’re done choosing your settings, select *Create connection*.

==== Map Blue Yonder Workforce Management instances to teams

Choose the Blue Yonder WFM instances that you want to connect to Shifts,
and then map each instance to a team in Teams. You can map up to 100
instances. There’s two ways that you can do this:

* link:#manually-map-instances-to-teams[Manually map instances to teams]
* link:#use-a-csv-file-to-map-instances-to-teams[Prepare and upload a
CSV file that defines your mappings]

===== Manually map instances to teams

Select the instances that you want to map.

:::image type=``content''
source=``media/shifts-connector-wizard-sites.png'' alt-text=``Screenshot
of wizard, showing the list of Blue Yonder WFM instances.''
lightbox=``media/shifts-connector-wizard-sites.png''::: Then, map each
instance to a team in Teams. You can map an instance to an existing team
or you can create a new team. :::image type=``content''
source=``media/shifts-connector-wizard-search-team.png''
alt-text=``Screenshot of the pane showing the search team option and
create a new team option.''
lightbox=``media/shifts-connector-wizard-search-team.png'':::

{empty}[!INCLUDE
link:includes/shifts-connector-manually-map-instances.md[shifts-connector-manually-map-instances]]

===== Use a CSV file to map instances to teams

[arabic]
. Select *switch to bulk mode*.
. Select *download a template file* to download a mapping template that
you can use to define your mappings.
+
:::image type=``content''
source=``media/shifts-connector-wizard-mapping-file.png''
alt-text=``Screenshot of the Upload mapping file page of the wizard.''
lightbox=``media/shifts-connector-wizard-mapping-file.png'':::
. Use the template to create your mapping file. It contains these
columns, in the following order, starting with the first column. An
asterisk (*) indicates a required column.
+
[width="100%",cols="50%,50%",options="header",]
|===
|Column name |Description
|*Blue Yonder Instance ID** |The Blue Yonder WFM instance ID.

|*Blue Yonder Instance Name* |The Blue Yonder WFM instance name.

|*Team ID** |The team ID.

|*Team Name* |The team name.

|*Time zone** |The time zone in tz database format. For example,
Europe/London.
|===
+
____
[!NOTE] You only need to fill out the required columns (Blue Yonder
Instance ID, Team ID, Time zone) to map instances to teams.
____
+
Here’s an example of what a mapping file looks like.
+
[width="100%",cols="20%,20%,20%,20%,20%",options="header",]
|===
|Blue Yonder Instance ID |Blue Yonder Instance Name |Team ID |Team Name
|Time zone
|2111 |Contoso US Team |3a4d78a-2261 |US Team |America/Los_Angeles

|3212 |Contoso UK Team |2d1f6c2e-5272 |UK Team |Europe/London

|4865 | |bfa6o89e-1328 | |America/Toronto
|===
. When you’ve created your mapping file, select *Browse* to upload it.
The wizard validates your file. If it finds errors, you’ll see a list of
the errors, and a message requesting that you correct them. Otherwise,
you’ll see a message to continue to the next step. +
. Select *Next*.

==== Review and finish

Review your settings. If you need to make changes to any team mappings,
choose *Edit* to do so. When you’re ready, select *Finish*.

:::image type=``content''
source=``media/shifts-connector-wizard-review.png''
alt-text=``Screenshot of the Review page of the wizard, showing
mappings.'' lightbox=``media/shifts-connector-wizard-review.png'':::

You’ll see a message to confirm that we received your request along with
an operation ID. Make a note of the operation ID. You’ll need it to
check the setup status of your connection.

:::image type=``content''
source=``media/shifts-connector-wizard-operation-id.png''
alt-text=``Screenshot of the wizard page, showing confirmation message
and operation ID.''
lightbox=``media/shifts-connector-wizard-operation-id.png'':::

The wizard starts the process to set up the connection and map the
instances to the teams you selected. This process may take some time to
complete. The recipients you chose will receive email notifications
about setup status.

Select *Done* to exit the wizard.

You’re on your way but you’re not done yet! Be sure to check your email.
You’ll receive a confirmation that we received your request along with a
link:shifts-connector-powershell-manage.md#check-connection-setup-status[link]
to how you can check setup status.

____
[!NOTE] If an issue or error occurs in a connection after it’s set up,
you’ll get notified in email. Follow the instructions in the email to
troubleshoot the issue.
____

=== Disable open shifts, open shifts requests, swap requests, and time off requests

____
[!IMPORTANT] Follow these steps only if you chose any of the following
options to disable open shifts, open shift requests, swap requests, or
time off requests in the wizard. Completing this step hides the
capability in Shifts.

* Open shifts: *Shifts users will not see Blue Yonder WFM data*
* Swap requests: *Feature is disabled for all users*
* Time off requests: *Feature is disabled for all users*

Without this second step, users will still see the capability in Shifts,
and will get an ``unsupported operation'' error message if they try to
use it.
____

To hide open shifts, swap requests, and time off requests in Shifts, use
the Graph API link:/graph/api/resources/schedule[schedule resource type]
to set the following parameters to `false` for each team that you mapped
to a Blue Yonder WFM instance:

* Open shifts: `openShiftsEnabled`
* Swap requests: `swapShiftsRequestsEnabled`
* Time off requests: `timeOffRequestsEnabled`

To hide open shifts requests in Shifts, go to *Settings* in Shifts, and
then turn off the *Open shifts* setting.

=== Manage your connection

After a connection is set up, you can manage and make changes to it in
the Microsoft 365 admin center or by using PowerShell.

==== Use the Microsoft 365 admin center

The Connector Management page lists each connection that you’ve set up,
along with information such as health status and sync interval details.
You can also access the wizard to make changes to any of your
connections. For example, you can update sync settings and team
mappings.

To learn more, see
link:shifts-connector-blue-yonder-admin-center-manage.md[Use the
Microsoft 365 admin center to manage your Shifts connection to Blue
Yonder Workforce Management].

==== Use PowerShell

You can use PowerShell to view an error report, change connection
settings, disable sync, and more. For step-by-step guidance, see
link:shifts-connector-powershell-manage.md[Use PowerShell to manage your
Shifts connection to Blue Yonder Workforce Management].

=== Related articles

* link:shifts-connectors.md[Shifts connectors]
* link:/microsoftteams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams?bc=/microsoft-365/frontline/breadcrumb/toc.json&toc=/microsoft-365/frontline/toc.json[Manage
the Shifts app in Teams]
