= Use PowerShell to manage your Shifts connection to Blue Yonder Workforce Management
:appliesto: ["Microsoft Teams", "Microsoft 365 for frontline workers"]
:audience: admin
:author: LanaChin
:description: Learn how to use PowerShell to manage your Shifts connection to Blue Yonder Workforce Management.
:manager: samanro
:ms.author: v-lanachin
:ms.collection: ["M365-collaboration", "m365-frontline"]
:ms.localizationpriority: high
:ms.reviewer:
:ms.service: microsoft-365-frontline
:ms.topic: article
:search.appverid: MET150

== Use PowerShell to manage your Shifts connection to Blue Yonder Workforce Management

=== Overview

The link:shifts-connectors.md#microsoft-teams-shifts-connector-for-blue-yonder[Microsoft Teams Shifts connector for Blue Yonder] enables you to integrate the Shifts app in Microsoft Teams with Blue Yonder Workforce Management (Blue Yonder WFM).
After you set up a connection, your frontline workers can seamlessly view and manage their schedules in Blue Yonder WFM from within Shifts.

You can use the xref:shifts-connector-wizard.adoc[Shifts connector wizard] in the Microsoft 365 admin center or xref:shifts-connector-blue-yonder-powershell-setup.adoc[PowerShell] to set up a connection.
After a connection is set up, you manage it by using <<shifts-connector-cmdlets,Shifts connector PowerShell cmdlets>>.

This article describes how to use PowerShell to do the following:

* <<check-connection-setup-status,Check connection setup status>>
* <<view-an-error-report-for-a-connection,View an error report for a connection>>
* <<resolve-connection-errors,Resolve connection errors>>
* <<change-connection-settings,Change connection settings>>
* <<unmap-a-team-from-one-connection-and-map-it-to-another-connection,Unmap a team from one connection and map it to another connection>>
* <<disable-sync-for-a-connection,Disable sync for a connection>>

____
[!NOTE] This article assumes that you've already set up a connection to Blue Yonder WFM, either by using the wizard or PowerShell.
____

=== Before you begin

[!INCLUDE xref:includes/shifts-connector-admin-role.adoc[shifts-connector-admin-role]]

=== Set up your environment

____
[!NOTE] Make sure you follow these steps to set up your environment before running any of the commands or scripts in this article.
____

[!INCLUDE xref:includes/shifts-connector-set-up-environment.adoc[shifts-connector-set-up-environment]]

. Connect to Teams.
+
[,powershell]
----
 Connect-MicrosoftTeams
----
+
When you're prompted, sign in using your admin credentials.
You're now set up to run the scripts in this article and Shifts connector cmdlets.

=== Check connection setup status

+++<a name="setup_status">++++++</a>+++

To check the status of the connection you set up using the operation ID that you received in email:

. <<set-up-your-environment,Set up your environment>> (if you haven't already).
. Run the following command.
This command gives you the overall status of the team mappings for the connection.
+
[,powershell]
----
 Get-CsTeamsShiftsConnectionOperation -OperationId <YourOperationId>
----

To learn more, see link:/powershell/module/teams/get-csteamsshiftsconnectionoperation[Get-CsTeamsShiftsConnectionOperation].

=== View an error report for a connection

+++<a name="error_report">++++++</a>+++

You can run a report that shows error details for a connection.
The report lists team and user mappings that succeeded and failed.
It also provides information about any issues related to the accounts associated with the connection.

. <<set-up-your-environment,Set up your environment>> (if you haven't already).
. Get a list of error reports for a connection.
+
[,powershell]
----
 Get-CsTeamsShiftsConnectionErrorReport -ConnectorInstanceId <ConnectorInstanceId>
----

. To view a specific error report, run the following command:
+
[,powershell]
----
 Get-CsTeamsShiftsConnectionErrorReport -ErrorReportId <ErrorReportId>
----

To learn more, see link:/powershell/module/teams/get-csteamsshiftsconnectionerrorreport[Get-CsTeamsShiftsConnectionErrorReport].

=== Resolve connection errors

==== User mapping errors

User mapping errors may occur if one or more users in a Blue Yonder WFM instance isn't a member of the mapped team in Teams.
To resolve this issue, make sure that the users in the mapped team match the users in the Blue Yonder WFM instance.

To view details of unmapped users, <<set-up-your-environment,set up your environment>> (if you haven't already), and then run the following script.

[,powershell]
----
#View sync errors script
Write-Host "View sync errors"
Start-Sleep 1

#Ensure Teams module is of version x
Write-Host "Checking Teams module version"
try {
    Get-InstalledModule -Name "MicrosoftTeams" -MinimumVersion 4.1.0
} catch {
    throw
}

#List connection instances available
Write-Host "Listing connection instances"
$InstanceList = Get-CsTeamsShiftsConnectionInstance
write $InstanceList

#Get an instance
if ($InstanceList.Count -gt 0){
    $InstanceId = Read-Host -Prompt 'Input the instance ID that you want to retrieve user sync results from'
}
else {
    throw "Instance list is empty"
}

#Get a list of the mappings
Write-Host "Listing team mappings"
$mappings = Get-CsTeamsShiftsConnectionTeamMap -ConnectorInstanceId $InstanceId
write $mappings

#For each mapping, retrieve the failed mappings
ForEach ($mapping in $mappings){
    $teamsTeamId = $mapping.TeamId
    $wfmTeamId = $mapping.WfmTeamId
    Write-Host "Failed mapped users in the mapping of ${teamsTeamId} and ${wfmTeamId}:"
    $userSyncResult = Get-CsTeamsShiftsConnectionSyncResult -ConnectorInstanceId $InstanceId -TeamId $teamsTeamId
    Write-Host "Failed AAD users:"
    write $userSyncResult.FailedAadUser
    Write-Host "Failed WFM users:"
    write $userSyncResult.FailedWfmUser
}
----

==== Account authorization errors

Account authorization errors may occur if the Blue Yonder WFM service account or Microsoft 365 system account credentials are incorrect or don't have the required permissions.

To change your Blue Yonder WFM service account or Microsoft 365 system account credentials for the connection, you can run the link:/powershell/module/teams/set-csteamsshiftsconnectioninstance[Set-CsTeamsShiftsConnectionInstance] cmdlet or use the PowerShell script in the <<change-connection-settings,Change connection settings>> section of this article.

=== Change connection settings

+++<a name="change_settings">++++++</a>+++

Use this script to change connection settings.
Settings that you can change include your Blue Yonder WFM service account and password, Microsoft 365 system account, team mappings, and sync settings.

Sync settings include the sync frequency (in minutes) and the schedule data that's synced between Blue Yonder WFM and Shifts.
Schedule data is defined in the following parameters, which you can view by running link:/powershell/module/teams/get-csteamsshiftsconnectionconnector[Get-CsTeamsShiftsConnectionConnector].

* The *enabledConnectorScenarios* parameter defines data that's synced from Blue Yonder WFM to Shifts.
Options are `Shift`, `SwapRequest`, `UserShiftPreferences`, `OpenShift`, `OpenShiftRequest`, `TimeOff`, `TimeOffRequest`.
* The *enabledWfiScenarios* parameter defines data that's synced from Shifts to Blue Yonder WFM.
Options are `SwapRequest`, `OpenShiftRequest`, `TimeOffRequest`, `UserShiftPreferences`.
+
____
[!NOTE] If you choose not to sync open shifts, open shift requests, swap requests, or time off requests between Shifts and Blue Yonder WFM, there's another step you need to do to hide the capability in Shifts.
After you run this script, make sure you follow the steps in the <<disable-open-shifts-open-shifts-requests-swap-requests-and-time-off-requests,Disable open shifts, open shifts requests, swap requests, and time off requests>> section later in this article.
____

____
[!IMPORTANT] For settings that you don't want to change, you'll need to re-enter the original settings when you're prompted by the script.
____

<<set-up-your-environment,Set up your environment>> (if you haven't already), and then run the following script.

[,powershell]
----
#Update connector instance and mapping script
Write-Host "Update connector instance and mapping"
Start-Sleep 1

#Ensure Teams module is at least version x
Write-Host "Checking Teams module version"
try {
    Get-InstalledModule -Name "MicrosoftTeams" -MinimumVersion 4.1.0
} catch {
    throw
}

#Connect to MS Graph
Connect-MgGraph -Scopes "User.Read.All","Group.ReadWrite.All"

#List connector types available (comment out if not implemented for preview)
Write-Host "Listing connector types available"
$BlueYonderId = "6A51B888-FF44-4FEA-82E1-839401E9CD74"
$connectors = Get-CsTeamsShiftsConnectionConnector
write $connectors
$blueYonder = $connectors | where {$_.Id -match $BlueYonderId}

#List connection instances available
Write-Host "Listing connection instances available"
$InstanceList = Get-CsTeamsShiftsConnectionInstance
write $InstanceList

#Prompt for the WFM username and password
$WfmUserName = Read-Host -Prompt 'Input your WFM user name'
$WfmPwd = Read-Host -Prompt 'Input your WFM password' -AsSecureString
$plainPwd =[Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($WfmPwd))

#Get the instance ID
$BlueYonderId = "6A51B888-FF44-4FEA-82E1-839401E9CD74"
$InstanceId = Read-Host -Prompt 'Input the instance ID that you want to update'
$Instance = Get-CsTeamsShiftsConnectionInstance -ConnectorInstanceId $InstanceId
$Etag = $Instance.etag

#Change sync setting
$designatorName = Read-Host -Prompt "Input designated actor's user name"
$designator = Get-MgUser -UserId $designatorName
$teamsUserId = $designator.Id
$UpdatedInstanceName = Read-Host -Prompt 'Input new connection instance name'
$updatedConnectorScenarioString = Read-Host -Prompt 'Input new enabled connector scenarios'
$updatedWfiScenarioString = Read-Host -Prompt 'Input new enabled WFI scenarios'
$Delimiters = ",", ".", ":", ";", " ", "`t"
$updatedConnectorScenario = $updatedConnectorScenarioString -Split {$Delimiters -contains $_}
$updatedConnectorScenario = $updatedConnectorScenario.Trim()
$updatedConnectorScenario = $updatedConnectorScenario.Split('',[System.StringSplitOptions]::RemoveEmptyEntries)
$updatedWfiScenario = $updatedWfiScenarioString -Split {$Delimiters -contains $_}
$updatedWfiScenario = $updatedWfiScenario.Trim()
$updatedWfiScenario = $updatedWfiScenario.Split('', [System.StringSplitOptions]::RemoveEmptyEntries)
$adminApiUrl = $Instance.ConnectorSpecificSettingAdminApiUrl
$cookieAuthUrl = $Instance.ConnectorSpecificSettingCookieAuthUrl
$essApiUrl = $Instance.ConnectorSpecificSettingEssApiUrl
$federatedAuthUrl = $Instance.ConnectorSpecificSettingFederatedAuthUrl
$retailWebApiUrl = $Instance.ConnectorSpecificSettingRetailWebApiUrl
$siteManagerUrl = $Instance.ConnectorSpecificSettingSiteManagerUrl
$syncFreq = Read-Host -Prompt 'Input new sync frequency'

#Read admin email list
[psobject[]]$AdminEmailList = @()
while ($true){
$AdminEmail = Read-Host -Prompt "Enter admin's email to receive error report"
$AdminEmailList += $AdminEmail
$title    = 'Adding another email'
$question = 'Would you like to add another admin email?'
$choices  = '&Yes', '&No'
$decision = $Host.UI.PromptForChoice($title, $question, $choices, 1)
if ($decision -eq 1) {
    break
}
}
$UpdatedInstance = Set-CsTeamsShiftsConnectionInstance -ConnectorId $BlueYonderId -ConnectorInstanceId $InstanceId -ConnectorSpecificSettingAdminApiUrl $adminApiUrl -ConnectorSpecificSettingCookieAuthUrl $cookieAuthUrl -ConnectorSpecificSettingEssApiUrl $essApiUrl -ConnectorSpecificSettingFederatedAuthUrl $federatedAuthUrl -ConnectorSpecificSettingLoginPwd $plainPwd -ConnectorSpecificSettingLoginUserName $WfmUserName -ConnectorSpecificSettingRetailWebApiUrl $retailWebApiUrl -ConnectorSpecificSettingSiteManagerUrl $siteManagerUrl -DesignatedActorId $teamsUserId -EnabledConnectorScenario $updatedConnectorScenario -EnabledWfiScenario $updatedWfiScenario -Name $UpdatedInstanceName -SyncFrequencyInMin $syncFreq -IfMatch $Etag -ConnectorAdminEmail $AdminEmailList

#Get a list of the mappings
Write-Host "Listing mappings"
$TeamMaps = Get-CsTeamsShiftsConnectionTeamMap -ConnectorInstanceId $InstanceId
write $TeamMaps

#Modify a mapping
#Remove a mapping
Write-Host "Removing a mapping"
$TeamsTeamId = Read-Host -Prompt 'Input the Teams team ID that you want to unlink'
$WfmTeamId = Read-Host -Prompt 'Input the WFM team ID that you want to unlink'
Remove-CsTeamsShiftsConnectionTeamMap -ConnectorInstanceId $InstanceId -TeamId $TeamsTeamId
Write-Host "Success"

#Add a mapping
Write-Host "Adding a mapping"
$TeamsTeamId = Read-Host -Prompt 'Input the Teams team ID that you want to link'
$WfmTeamId = Read-Host -Prompt 'Input the WFM team ID that you want to link'
New-CsTeamsShiftsConnectionTeamMap -ConnectorInstanceId $InstanceId -TeamId $TeamsTeamId -TimeZone "America/Los_Angeles" -WfmTeamId $WfmTeamId
Write-Host "Success"
----

=== Disable open shifts, open shifts requests, swap requests, and time off requests

____
[!IMPORTANT] Follow these steps only if you chose to disable open shifts, open shift requests, swap requests, or time off requests using the script in the <<change-connection-settings,Change connection settings>> section earlier in this article or by using the link:/powershell/module/teams/set-csteamsshiftsconnectioninstance[Set-CsTeamsShiftsConnectionInstance] cmdlet.
Completing this step hides the capability in Shifts.
Without this second step, users will still see the capability in Shifts, and will get an "unsupported operation" error message if they try to use it.
____

To hide open shifts, swap requests, and time off requests in Shifts, use the Graph API link:/graph/api/resources/schedule[schedule resource type] to set the following parameters to `false` for each team that you mapped to a Blue Yonder WFM instance:

* Open shifts: `openShiftsEnabled`
* Swap requests:  `swapShiftsRequestsEnabled`
* Time off requests: `timeOffRequestsEnabled`

To hide open shifts requests in Shifts, go to *Settings* in Shifts, and then turn off the *Open shifts* setting.

=== Unmap a team from one connection and map it to another connection

____
[!NOTE] The Microsoft 365 system account must be the same for both connections.
If it isn't, you'll get a "This designated actor profile doesn't have team ownership privileges" error message.
____

If you want to unmap a team from one connection and map it to another connection:

. <<set-up-your-environment,Set up your environment>> (if you haven't already).
. View a list of all team mappings for a connection.
+
[,powershell]
----
 Get-CsTeamsShiftsConnectionTeamMap -ConnectorInstanceId <ConnectorInstanceId>
----

. Remove a team mapping from the connection.
+
[,powershell]
----
 Remove-CsTeamsShiftsConnectionTeamMap -ConnectorInstanceId <ConnectorInstanceId> -TeamId <TeamId>
----

. Map the team to another connection.
+
[,powershell]
----
 New-CsTeamsShiftsConnectionTeamMap -ConnectorInstanceId <ConnectorInstanceId> -TeamId <TeamId> -WfmTeamId <SiteId> -TimeZone <TimeZone>
----

To learn more, see link:/powershell/module/teams/get-csteamsshiftsconnectionteammap[Get-CsTeamsShiftsConnectionTeamMap], link:/powershell/module/teams/remove-csteamsshiftsconnectionteammap[Remove-CsTeamsShiftsConnectionTeamMap], and link:/powershell/module/teams/new-csteamsshiftsconnectionteammap[New-CsTeamsShiftsConnectionTeamMap].

=== Disable sync for a connection

Use this script to disable sync for a connection.
Keep in mind this script doesn't remove or delete a connection.
It turns off sync so that no data is synced between Shifts and Blue Yonder WFM for the connection that you specify.

<<set-up-your-environment,Set up your environment>> (if you haven't already), and then run the following script.

[,powershell]
----
#Disable sync script
Write-Host "Disable sync"
#Ensure Teams module is at least version x
Write-Host "Checking Teams module version"
try {
    Get-InstalledModule -Name "MicrosoftTeams" -MinimumVersion 4.1.0
} catch {
    throw
}

#List connection instances available
Write-Host "Listing connection instances"
$InstanceList = Get-CsTeamsShiftsConnectionInstance
write $InstanceList

#Get an instance
if ($InstanceList.Count -gt 0){
    $InstanceId = Read-Host -Prompt 'Input the instance ID that you want to disable sync'
    $Instance = Get-CsTeamsShiftsConnectionInstance -ConnectorInstanceId $InstanceId
    $Etag = $Instance.etag
    $InstanceName = $Instance.Name
    $DesignatedActorId = $Instance.designatedActorId
    $adminApiUrl = $Instance.ConnectorSpecificSettingAdminApiUrl
    $cookieAuthUrl = $Instance.ConnectorSpecificSettingCookieAuthUrl
    $essApiUrl = $Instance.ConnectorSpecificSettingEssApiUrl
    $federatedAuthUrl = $Instance.ConnectorSpecificSettingFederatedAuthUrl
    $retailWebApiUrl = $Instance.ConnectorSpecificSettingRetailWebApiUrl
    $siteManagerUrl = $Instance.ConnectorSpecificSettingSiteManagerUrl
    $ConnectorAdminEmail = $Instance.ConnectorAdminEmail
}
else {
    throw "Instance list is empty"
}

#Remove scenarios in the mapping
Write-Host "Disabling scenarios in the team mapping"
$UpdatedInstanceName = $InstanceName + " - Disabled"
$BlueYonderId = "6A51B888-FF44-4FEA-82E1-839401E9CD74"
$WfmUserName = Read-Host -Prompt 'Input your WFM user name'
$WfmPwd = Read-Host -Prompt 'Input your WFM password' -AsSecureString
$plainPwd =[Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($WfmPwd))

$UpdatedInstance = Set-CsTeamsShiftsConnectionInstance -ConnectorId $BlueYonderId -ConnectorInstanceId $InstanceId -ConnectorSpecificSettingAdminApiUrl $adminApiUrl -ConnectorSpecificSettingCookieAuthUrl $cookieAuthUrl -ConnectorSpecificSettingEssApiUrl $essApiUrl -ConnectorSpecificSettingFederatedAuthUrl $federatedAuthUrl -ConnectorSpecificSettingLoginPwd $plainPwd -ConnectorSpecificSettingLoginUserName $WfmUserName -ConnectorSpecificSettingRetailWebApiUrl $retailWebApiUrl -ConnectorSpecificSettingSiteManagerUrl $siteManagerUrl -DesignatedActorId $DesignatedActorId -EnabledConnectorScenario @() -EnabledWfiScenario @() -Name $UpdatedInstanceName -SyncFrequencyInMin 60 -IfMatch $Etag -ConnectorAdminEmail $ConnectorAdminEmail

if ($UpdatedInstance.Id -ne $null) {
    Write-Host "Success"
}
else {
    throw "Update instance failed"
}
----

=== Shifts connector cmdlets

For help with Shifts connector cmdlets, search for *CsTeamsShiftsConnection* in the link:/powershell/teams/intro[Teams PowerShell cmdlet reference].
Here are links to some commonly used cmdlets.

* link:/powershell/module/teams/get-csteamsshiftsconnectionoperation[Get-CsTeamsShiftsConnectionOperation]
* link:/powershell/module/teams/new-csteamsshiftsconnectioninstance[New-CsTeamsShiftsConnectionInstance]
* link:/powershell/module/teams/get-csteamsshiftsconnectioninstance[Get-CsTeamsShiftsConnectionInstance]
* link:/powershell/module/teams/set-csteamsshiftsconnectioninstance[Set-CsTeamsShiftsConnectionInstance]
* link:/powershell/module/teams/remove-csteamsshiftsconnectioninstance[Remove-CsTeamsShiftsConnectionInstance]
* link:/powershell/module/teams/test-csteamsshiftsconnectionvalidate[Test-CsTeamsShiftsConnectionValidate]
* link:/powershell/module/teams/new-csteamsshiftsconnectionteammap[New-CsTeamsShiftsConnectionTeamMap]
* link:/powershell/module/teams/get-csteamsshiftsconnectionteammap[Get-CsTeamsShiftsConnectionTeamMap]
* link:/powershell/module/teams/remove-csteamsshiftsconnectionteammap[Remove-CsTeamsShiftsConnectionTeamMap]
* link:/powershell/module/teams/get-csteamsshiftsconnectionconnector[Get-CsTeamsShiftsConnectionConnector]
* link:/powershell/module/teams/get-csteamsshiftsconnectionsyncresult[Get-CsTeamsShiftsConnectionSyncResult]
* link:/powershell/module/teams/get-csteamsshiftsconnectionwfmuser[Get-CsTeamsShiftsConnectionWfmUser]
* link:/powershell/module/teams/get-csteamsshiftsconnectionwfmteam[Get-CsTeamsShiftsConnectionWfmTeam]
* link:/powershell/module/teams/get-csteamsshiftsconnectionerrorreport[Get-CsTeamsShiftsConnectionErrorReport]
* link:/powershell/module/teams/remove-csteamsshiftsschedulerecord[Remove-CsTeamsShiftsScheduleRecord]

=== Related articles

* xref:shifts-connectors.adoc[Shifts connectors]
* xref:shifts-connector-wizard.adoc[Use the Shifts connector wizard to connect Shifts to Blue Yonder Workforce Management]
* xref:shifts-connector-blue-yonder-powershell-setup.adoc[Use PowerShell to connect Shifts to Blue Yonder Workforce Management]
* link:/microsoftteams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams?bc=/microsoft-365/frontline/breadcrumb/toc.json&toc=/microsoft-365/frontline/toc.json[Manage the Shifts app]
* link:/microsoftteams/teams-powershell-overview[Teams PowerShell overview]
