= 
LanaChin

== Use PowerShell to manage your Shifts connection to UKG Dimensions

{empty}[!INCLUDE link:includes/preview-feature.md[preview-feature]]

=== Overview

The
link:shifts-connectors.md#microsoft-teams-shifts-connector-for-ukg-dimensions[Microsoft
Teams Shifts connector for UKG Dimensions] enables you to integrate the
Shifts app in Microsoft Teams with UKG Dimensions. After you set up a
connection, your frontline workers can seamlessly view and manage their
schedules in UKG Dimensions from within Shifts.

You can use the link:shifts-connector-wizard-ukg.md[Shifts connector
wizard] in the Microsoft 365 admin center or
link:shifts-connector-ukg-powershell-setup.md[PowerShell] to set up a
connection. After a connection is set up, you can manage it by using
link:#shifts-connector-cmdlets[Shifts connector PowerShell cmdlets].

This article describes how to use PowerShell to do the following:

* link:#check-connection-setup-status[Check connection setup status]
* link:#view-an-error-report-for-a-connection[View an error report for a
connection]
* link:#resolve-connection-errors[Resolve connection errors]
* link:#change-connection-settings[Change connection settings]
* link:#unmap-a-team-from-one-connection-and-map-it-to-another-connection[Unmap
a team from one connection and map it to another connection]
* link:#disable-sync-for-a-connection[Disable sync for a connection]

This article assumes that you’ve already set up a connection to UKG
Dimensions, either by using the wizard or PowerShell.

____
[!NOTE] You can also manage your connection in the Microsoft 365 admin
center. For example, you can check the health status and access the
wizard to change connection settings. To learn more, see
link:shifts-connector-ukg-admin-center-manage.md[Use the Microsoft 365
admin center to manage your Shifts connection to UKG Dimensions].
____

=== Before you begin

{empty}[!INCLUDE
link:includes/shifts-connector-admin-role.md[shifts-connector-admin-role]]

=== Set up your environment

____
[!NOTE] Make sure you follow these steps to set up your environment
before running any of the commands or scripts in this article.
____

{empty}[!INCLUDE
link:includes/shifts-connector-set-up-environment.md[shifts-connector-set-up-environment]]

[arabic, start=7]
. Connect to Teams.
+
[source,powershell]
----
Connect-MicrosoftTeams
----
+
When you’re prompted, sign in using your admin credentials. You’re now
set up to run the scripts in this article and Shifts connector cmdlets.

=== Check connection setup status

{empty}[!INCLUDE
link:includes/shifts-connector-check-setup-status.md[shifts-connector-check-setup-status]]

=== View an error report for a connection

{empty}[!INCLUDE
link:includes/shifts-connector-view-error-report.md[shifts-connector-view-error-report]]

____
[!NOTE] For a complete list of error messages, see
link:#list-of-error-messages[List of error messages] later in this
article.
____

=== Resolve connection errors

==== User mapping errors

User mapping errors may occur if one or more users in a WFM instance
isn’t a member of the mapped team in Teams. To resolve this issue, make
sure that the users in the mapped team match the users in the WFM
instance.

To view details of unmapped users, link:#set-up-your-environment[set up
your environment] (if you haven’t already), and then run the following
script.

[source,powershell]
----
#View sync errors script
Write-Host "View sync errors"
Start-Sleep 1

#Ensure Teams module is of version x
Write-Host "Checking Teams module version"
try {
    Get-InstalledModule -Name "MicrosoftTeams" -MinimumVersion 4.7.0
} catch {
    throw
}

#List connection instances available
Write-Host "Listing connection instances"
$InstanceList = Get-CsTeamsShiftsConnectionInstance
write $InstanceList

#Get an instance
if ($InstanceList.Count -gt 0){
    $InstanceId = Read-Host -Prompt 'Input the instance ID that you want to retrieve user sync results from'
}
else {
    throw "Instance list is empty"
}

#Get a list of the mappings
Write-Host "Listing team mappings"
$mappings = Get-CsTeamsShiftsConnectionTeamMap -ConnectorInstanceId $InstanceId
write $mappings

#For each mapping, retrieve the failed mappings
ForEach ($mapping in $mappings){
    $teamsTeamId = $mapping.TeamId
    $wfmTeamId = $mapping.WfmTeamId
    Write-Host "Failed mapped users in the mapping of ${teamsTeamId} and ${wfmTeamId}:"
    $userSyncResult = Get-CsTeamsShiftsConnectionSyncResult -ConnectorInstanceId $InstanceId -TeamId $teamsTeamId
    Write-Host "Failed AAD users:"
    write $userSyncResult.FailedAadUser
    Write-Host "Failed WFM users:"
    write $userSyncResult.FailedWfmUser
}
----

==== Account authorization errors

{empty}[!INCLUDE
link:includes/shifts-connector-account-authorization-errors.md[shifts-connector-account-authorization-errors]]

=== Change connection settings

{empty}[!INCLUDE
link:includes/shifts-connector-change-connection-settings.md[shifts-connector-change-connection-settings]]

link:#set-up-your-environment[Set up your environment] (if you haven’t
already), and then run the following script.

[source,powershell]
----
#Update connector instance and mapping script
Write-Host "Update Connector instance and mapping"
Start-Sleep 1

#Ensure Teams module is at least version x
Write-Host "Checking Teams module version"
try {
    Get-InstalledModule -Name "MicrosoftTeams" -MinimumVersion 4.7.0
} catch {
    throw
}

#Connect to MS Graph
Connect-MgGraph -Scopes "User.Read.All","Group.ReadWrite.All"

#List connector types available (comment out if not implemented for preview)
Write-Host "Listing connector types available"
$UkgId = "95BF2848-2DDA-4425-B0EE-D62AEED4C0A0"
$connectors = Get-CsTeamsShiftsConnectionConnector
write $connectors
$Ukg = $connectors | where {$_.Id -match $UkgId}

#List connection instances available
Write-Host "Listing connection instances available"
$InstanceList = Get-CsTeamsShiftsConnectionInstance | where {$_.ConnectorId -match $UkgId}
write $InstanceList

#Prompt for the WFM username and password
$WfmUserName = Read-Host -Prompt 'Input your WFM user name'
$WfmPwd = Read-Host -Prompt 'Input your WFM password' -AsSecureString
$plainPwd =[Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($WfmPwd))

#Get the instance ID
$InstanceId = Read-Host -Prompt 'Input the instance ID that you want to update'
$Instance = Get-CsTeamsShiftsConnectionInstance -ConnectorInstanceId $InstanceId
$Etag = $Instance.etag

#Change sync setting
$designatorName = Read-Host -Prompt "Input designated actor's user name"
$designator = Get-MgUser -UserId $designatorName
$teamsUserId = $designator.Id
$UpdatedInstanceName = Read-Host -Prompt 'Input new connection instance name'
$updatedConnectorScenarioString = Read-Host -Prompt 'Input new enabled connector scenarios'
$updatedWfiScenarioString = Read-Host -Prompt 'Input new enabled WFI scenarios'
$Delimiters = ",", ".", ":", ";", " ", "`t"
$updatedConnectorScenario = $updatedConnectorScenarioString -Split {$Delimiters -contains $_}
$updatedConnectorScenario = $updatedConnectorScenario.Trim()
$updatedConnectorScenario = $updatedConnectorScenario.Split('',[System.StringSplitOptions]::RemoveEmptyEntries)
$updatedWfiScenario = $updatedWfiScenarioString -Split {$Delimiters -contains $_}
$updatedWfiScenario = $updatedWfiScenario.Trim()
$updatedWfiScenario = $updatedWfiScenario.Split('', [System.StringSplitOptions]::RemoveEmptyEntries)
$apiUrl = $Instance.ConnectorSpecificSettingApiUrl
$ssoUrl = $Instance.ConnectorSpecificSettingSsoUrl
$clientId = $Instance.ConnectorSpecificSettingClientId
$syncFreq = Read-Host -Prompt 'Input new sync frequency'
$AppKey = Read-Host -Prompt 'Input your app key' -AsSecureString
$plainKey =[Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($AppKey))
$ClientSecret = Read-Host -Prompt 'Input your client secret' -AsSecureString
$plainSecret =[Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($ClientSecret))

#Read admin email list
[psobject[]]$AdminEmailList = @()
while ($true){
$AdminEmail = Read-Host -Prompt "Enter admin's email to receive error report"
$AdminEmailList += $AdminEmail
$title    = 'Adding another email'
$question = 'Would you like to add another admin email?'
$choices  = '&Yes', '&No'
$decision = $Host.UI.PromptForChoice($title, $question, $choices, 1)
if ($decision -eq 1) {
    break
}
}
$UpdatedInstance = Set-CsTeamsShiftsConnectionInstance `
    -ConnectorInstanceId $InstanceId `
    -ConnectorId $UkgId `
    -ConnectorAdminEmail $AdminEmailList `
    -DesignatedActorId $teamsUserId `
    -EnabledConnectorScenario $updatedConnectorScenario `
    -EnabledWfiScenario $updatedWfiScenario `
    -Name $UpdatedInstanceName `
    -SyncFrequencyInMin $syncFreq `
    -ConnectorSpecificSettings (New-Object Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.ConnectorSpecificUkgDimensionsSettingsRequest `
        -Property @{
            apiUrl = $apiUrl
            ssoUrl = $ssoUrl
            appKey = $plainKey
            clientId = $clientId
            clientSecret = $plainSecret
            LoginUserName = $WfmUserName
            LoginPwd = $plainPwd
        }) `
    -IfMatch $Etag
if ($UpdatedInstance.Id -ne $null) {
    Write-Host "Success"
}
else {
    throw "Update instance failed"
}
#Get a list of the mappings
Write-Host "Listing mappings"
$TeamMaps = Get-CsTeamsShiftsConnectionTeamMap -ConnectorInstanceId $InstanceId
write $TeamMaps

#Modify a mapping
#Remove a mapping
Write-Host "Removing a mapping"
$TeamsTeamId = Read-Host -Prompt 'Input the Teams team ID that you want to unlink'
$WfmTeamId = Read-Host -Prompt 'Input the WFM team ID that you want to unlink'
Remove-CsTeamsShiftsConnectionTeamMap -ConnectorInstanceId $InstanceId -TeamId $TeamsTeamId
Write-Host "Success"

#Add a mapping
Write-Host "Adding a mapping"
$TeamsTeamId = Read-Host -Prompt 'Input the Teams team ID that you want to link'
$WfmTeamId = Read-Host -Prompt 'Input the WFM team ID that you want to link'
New-CsTeamsShiftsConnectionTeamMap -ConnectorInstanceId $InstanceId -TeamId $TeamsTeamId -TimeZone "America/Los_Angeles" -WfmTeamId $WfmTeamId
Write-Host "Success"
----

=== Disable open shifts, open shifts requests, swap requests, and time off requests

{empty}[!INCLUDE
link:includes/shifts-connector-disable-shifts-requests.md[shifts-connector-disable-shifts-requests]]

=== Unmap a team from one connection and map it to another connection

{empty}[!INCLUDE
link:includes/shifts-connector-unmap-a-team.md[shifts-connector-unmap-a-team]]

=== Disable sync for a connection

Use this script to disable sync for a connection. Keep in mind this
script doesn’t remove or delete a connection. It turns off sync so that
no data is synced between Shifts and your WFM system for the connection
that you specify.

link:#set-up-your-environment[Set up your environment] (if you haven’t
already), and then run the following script.

[source,powershell]
----
#Disable sync script
Write-Host "Disable sync"
Start-Sleep 1

#Ensure Teams module is at least version x
Write-Host "Checking Teams module version"
try {
    Get-InstalledModule -Name "MicrosoftTeams" -MinimumVersion 4.7.0
} catch {
    throw
}

#List connection instances available
$UkgId = "95BF2848-2DDA-4425-B0EE-D62AEED4C0A0"
Write-Host "Listing connection instances"
$InstanceList = Get-CsTeamsShiftsConnectionInstance | where {$_.ConnectorId -match $UkgId}
write $InstanceList

#Get an instance
if ($InstanceList.Count -gt 0){
    $InstanceId = Read-Host -Prompt 'Input the instance ID that you want to disable sync'
    $Instance = Get-CsTeamsShiftsConnectionInstance -ConnectorInstanceId $InstanceId
    $Etag = $Instance.etag
    $InstanceName = $Instance.Name
    $DesignatedActorId = $Instance.designatedActorId
    $apiUrl = $Instance.ConnectorSpecificSettingApiUrl
    $ssoUrl = $Instance.ConnectorSpecificSettingSsoUrl
    $clientId = $Instance.ConnectorSpecificSettingClientId
    $ConnectorAdminEmail = $Instance.ConnectorAdminEmail
}
else {
    throw "Instance list is empty"
}

#Remove scenarios in the mapping
Write-Host "Disabling scenarios in the team mapping"
$UpdatedInstanceName = $InstanceName + " - Disabled"
$UkgId = "95BF2848-2DDA-4425-B0EE-D62AEED4C0A0"
$WfmUserName = Read-Host -Prompt 'Input your WFM user name'
$WfmPwd = Read-Host -Prompt 'Input your WFM password' -AsSecureString
$plainPwd =[Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($WfmPwd))
$AppKey = Read-Host -Prompt 'Input your app key' -AsSecureString
$plainKey =[Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($AppKey))
$ClientSecret = Read-Host -Prompt 'Input your client secret' -AsSecureString
$plainSecret =[Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($ClientSecret))

$UpdatedInstance = Set-CsTeamsShiftsConnectionInstance `
    -ConnectorInstanceId $InstanceId `
    -ConnectorId $UkgId `
    -ConnectorAdminEmail $ConnectorAdminEmail `
    -DesignatedActorId $DesignatedActorId `
    -EnabledConnectorScenario @() `
    -EnabledWfiScenario @() `
    -Name $UpdatedInstanceName `
    -SyncFrequencyInMin 10 `
    -ConnectorSpecificSettings (New-Object Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.ConnectorSpecificUkgDimensionsSettingsRequest `
        -Property @{
            apiUrl = $apiUrl
            ssoUrl = $ssoUrl
            appKey = $plainKey
            clientId = $clientId
            clientSecret = $plainSecret
            LoginUserName = $WfmUserName
            LoginPwd = $plainPwd
        }) `
    -IfMatch $Etag

if ($UpdatedInstance.Id -ne $null) {
    Write-Host "Success"
}
else {
    throw "Update instance failed"
}
----

=== List of error messages

Here’s the list of error messages that you may encounter and information
to help you resolve them.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Error type |Error details |Resolution
|Unable to authenticate workforce management system. |The workforce
management system account credentials you’ve provided are invalid or
this account doesn’t have the required permissions. |Update your WFM
service account credentials in the connection settings. To do this, do
one of the following:

|Unable to authenticate Graph. |Authentication failed. Ensure that
you’ve entered valid credentials for the designated actor and have the
required permissions. |Make sure that your Microsoft 365 system account
(also known as designated actor) is added as a team owner. Or, update
your Microsoft 365 system account credentials in the connection
settings.

|Some users have failed to map correctly |Mapping failed for some users:
<X> succeeded, <X> failed AAD user(s) and <X> failed workforce
management system user(s). |Use the
link:/powershell/module/teams/get-csteamsshiftsconnectionsyncresult[Get-CsTeamsShiftsConnectionSyncResult]
cmdlet or link:#user-mapping-errors[this PowerShell script] to identify
the users for whom the mapping failed. Make sure that the users in the
mapped team match the users in the WFM instance.

|Unable to map a team or teams in this batch. |This designated actor
profile doesn’t have team ownership privileges. |Make sure your
Microsoft 365 system account (also known as designated actor) is added
as a team owner.If you’ve changed your Microsoft 365 system account, add
that account as a team owner, and update the connection settings to use
that account.

| |This team is already mapped to an existing connector instance. |Unmap
the team from the existing connection by using the
link:/powershell/module/teams/remove-csteamsshiftsconnectionteammap[Remove-CsTeamsShiftsConnectionTeamMap]
cmdlet. Or, create a new connection to remap the team.

| |This timezone is invalid. The timezone passed in is not using tz
database format. |Make sure that the time zone is correct, and then
remap the team.

| |We can’t find this connector instance. |Map the team to an existing
connection.

| |This AAD team couldn’t be found. |Make sure that the team exists or
create a new team.
|===

=== Shifts connector cmdlets

For help with Shifts connector cmdlets, search for
*CsTeamsShiftsConnection* in the link:/powershell/teams/intro[Teams
PowerShell cmdlet reference]. Here are links to some commonly used
cmdlets.

* link:/powershell/module/teams/get-csteamsshiftsconnectionoperation[Get-CsTeamsShiftsConnectionOperation]
* link:/powershell/module/teams/new-csteamsshiftsconnectioninstance[New-CsTeamsShiftsConnectionInstance]
* link:/powershell/module/teams/get-csteamsshiftsconnectioninstance[Get-CsTeamsShiftsConnectionInstance]
* link:/powershell/module/teams/set-csteamsshiftsconnectioninstance[Set-CsTeamsShiftsConnectionInstance]
* link:/powershell/module/teams/update-csteamsshiftsconnectioninstance[Update-CsTeamsShiftsConnectionInstance]
* link:/powershell/module/teams/remove-csteamsshiftsconnectioninstance[Remove-CsTeamsShiftsConnectionInstance]
* link:/powershell/module/teams/test-csteamsshiftsconnectionvalidate[Test-CsTeamsShiftsConnectionValidate]
* link:/powershell/module/teams/new-csteamsshiftsconnectionteammap[New-CsTeamsShiftsConnectionTeamMap]
* link:/powershell/module/teams/get-csteamsshiftsconnectionteammap[Get-CsTeamsShiftsConnectionTeamMap]
* link:/powershell/module/teams/remove-csteamsshiftsconnectionteammap[Remove-CsTeamsShiftsConnectionTeamMap]
* link:/powershell/module/teams/get-csteamsshiftsconnectionconnector[Get-CsTeamsShiftsConnectionConnector]
* link:/powershell/module/teams/get-csteamsshiftsconnectionsyncresult[Get-CsTeamsShiftsConnectionSyncResult]
* link:/powershell/module/teams/get-csteamsshiftsconnectionwfmuser[Get-CsTeamsShiftsConnectionWfmUser]
* link:/powershell/module/teams/get-csteamsshiftsconnectionwfmteam[Get-CsTeamsShiftsConnectionWfmTeam]
* link:/powershell/module/teams/get-csteamsshiftsconnectionerrorreport[Get-CsTeamsShiftsConnectionErrorReport]
* link:/powershell/module/teams/remove-csteamsshiftsschedulerecord[Remove-CsTeamsShiftsScheduleRecord]

=== Related articles

* link:shifts-connectors.md[Shifts connectors]
* link:shifts-connector-wizard-ukg.md[Use the Shifts connector wizard to
connect Shifts to UKG Dimensions]
* link:shifts-connector-ukg-powershell-setup.md[Use PowerShell to
connect Shifts to UKG Dimensions]
* link:shifts-connector-ukg-admin-center-manage.md[Use the Microsoft 365
admin center to manage your Shifts connection to UKG Dimensions]
* link:/microsoftteams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams?bc=/microsoft-365/frontline/breadcrumb/toc.json&toc=/microsoft-365/frontline/toc.json[Manage
the Shifts app]
* link:/microsoftteams/teams-powershell-overview[Teams PowerShell
overview]
