= 
LanaChin

== Use PowerShell to connect Shifts to Blue Yonder Workforce Management

=== Overview

Use the
link:shifts-connectors.md#microsoft-teams-shifts-connector-for-blue-yonder[Microsoft
Teams Shifts connector for Blue Yonder] to integrate the Shifts app in
Microsoft Teams with Blue Yonder Workforce Management (Blue Yonder WFM).
After a connection is set up, your frontline workers can seamlessly view
and manage their schedules in Blue Yonder WFM from within Shifts.

In this article, we walk you through how to use PowerShell to set up and
configure the connector to integrate Shifts with Blue Yonder WFM.

To set up the connection, you run a PowerShell script. The script
configures the connector, applies sync settings, creates the connection,
and maps Blue Yonder WFM instances to teams. Sync settings determine the
features enabled in Shifts and the schedule information that’s synced
between Blue Yonder WFM and Shifts. Mappings define the sync
relationship between your Blue Yonder WFM instances and teams in Teams.
You can map to existing teams and new teams.

We provide two scripts. You can use either script, depending on whether
you want to map to existing teams or create new teams to map to.

You can set up multiple connections, each with different sync settings.
For example, if your organization has multiple locations with different
schedule requirements, create a connection with unique sync settings for
each location. Keep in mind that a Blue Yonder WFM instance can only be
mapped to one team at any given time. If an instance is already mapped
to a team, it can’t be mapped to another team.

With Blue Yonder WFM as the system of record, your frontline workers can
efficiently manage their schedules and availability in Shifts on their
devices. Frontline managers can continue to use Blue Yonder WFM to set
up schedules.

____
[!NOTE] You can also use the link:shifts-connector-wizard.md[Shifts
connector wizard] in the Microsoft 365 admin center to connect Shifts to
Blue Yonder WFM.
____

=== Before you begin

==== Prerequisites

{empty}[!INCLUDE
link:includes/shifts-connector-prerequisites.md[shifts-connector-prerequisites]]

==== Admin role to manage the connector using PowerShell

{empty}[!INCLUDE
link:includes/shifts-connector-admin-role.md[shifts-connector-admin-role]]

=== Set up your environment

{empty}[!INCLUDE
link:includes/shifts-connector-set-up-environment.md[shifts-connector-set-up-environment]]

=== Connect to Teams

Run the following to connect to Teams.

[source,powershell]
----
Connect-MicrosoftTeams
----

When you’re prompted, sign in using your admin credentials. You’re now
set up to run the scripts in this article and Shifts connector cmdlets.

=== Identify the teams you want to map

____
[!NOTE] Complete this step if you’re mapping Blue Yonder WFM instances
to existing teams. If you’re creating new teams to map to, you can skip
this step.
____

In the Azure portal, go to the
https://ms.portal.azure.com/#blade/Microsoft_AAD_IAM/GroupsManagementMenuBlade/AllGroups[All
groups] page to get a list of the TeamIds of teams in your organization.

Take note of the TeamIds of the teams you want to map. The script will
prompt you to enter this information.

____
[!NOTE] If one or more teams have an existing schedule, the script will
remove the schedules from those teams. Otherwise, you’ll see duplicate
shifts.
____

=== Run the script

Run the script:

* To set up a connection and create new teams to map,
link:#set-up-a-connection-and-create-new-teams-to-map[run this script].
* To set up a connection and map to existing teams,
link:#set-up-a-connection-and-map-to-existing-teams[run this script].

The script does the following actions. You’ll be prompted to enter setup
and configuration details.

[arabic]
. Tests and verifies the connection to Blue Yonder WFM using the Blue
Yonder WFM service account credentials and service URLs that you enter.
. Configures the Shifts connector.
. Applies sync settings. These settings include the sync frequency (in
minutes) and the schedule data that’s synced between Blue Yonder WFM and
Shifts. Schedule data is defined in the following parameters:
* The *enabledConnectorScenarios* parameter defines data that’s synced
from Blue Yonder WFM to Shifts. Options are `Shift`, `SwapRequest`,
`UserShiftPreferences`, `OpenShift`, `OpenShiftRequest`, `TimeOff`,
`TimeOffRequest`.
* The *enabledWfiScenarios* parameter defines data that’s synced from
Shifts to Blue Yonder WFM. Options are `SwapRequest`,
`OpenShiftRequest`, `TimeOffRequest`, `UserShiftPreferences`.
+
To learn more, see
link:/powershell/module/teams/new-csteamsshiftsconnectioninstance[New-CsTeamsShiftsConnectionInstance].
To see the list of supported sync options for each parameter, run
link:/powershell/module/teams/get-csteamsshiftsconnectionconnector[Get-CsTeamsShiftsConnectionConnector].
+
____
[!IMPORTANT] The script enables sync for all these options. If you want
to change sync settings, you can do so after the connection is set up.
To learn more, see link:shifts-connector-powershell-manage.md[Use
PowerShell to manage your Shifts connection to Blue Yonder Workforce
Management].
____
. Creates the connection.
. Maps Blue Yonder WFM instances to teams. Mappings are based on the
Blue Yonder WFM instance IDs and TeamIds that you enter or new teams you
create, depending on the script that you run. If a team has an existing
schedule, the script removes schedule data for the date and time range
that you specify.

A Success message on the screen indicates that your connection is
successfully set up.

=== Manage your connection

After a connection is set up, you can manage and make changes to it in
the Microsoft 365 admin center or by using PowerShell.

==== Use the Microsoft 365 admin center

The Connector Management page lists each connection that you’ve set up,
along with information such as health status and sync interval details.
You can also access the wizard to make changes to any of your
connections. For example, you can update sync settings and team
mappings.

To learn more, see
link:shifts-connector-blue-yonder-admin-center-manage.md[Use the
Microsoft 365 admin center to manage your Shifts connection to Blue
Yonder Workforce Management].

==== Use PowerShell

You can use PowerShell to view an error report, change connection
settings, disable sync, and more. For step-by-step guidance, see
link:shifts-connector-powershell-manage.md[Use PowerShell to manage your
Shifts connection to Blue Yonder Workforce Management].

=== Scripts

==== Set up a connection and create new teams to map

[source,powershell]
----
#Map WFM instances to teams script
Write-Host "Map WFM sites to teams"
Start-Sleep 1

#Ensure Teams module is at least version x
Write-Host "Checking Teams module version"
try {
    Get-InstalledModule -Name "MicrosoftTeams" -MinimumVersion 4.7.0
} catch {
    throw
}

#Connect to MS Graph
Connect-MgGraph -Scopes "User.Read.All","Group.ReadWrite.All"

#List connector types available (comment out if not implemented for preview)
Write-Host "Listing connector types available"
$BlueYonderId = "6A51B888-FF44-4FEA-82E1-839401E9CD74"
$connectors = Get-CsTeamsShiftsConnectionConnector
write $connectors
$blueYonder = $connectors | where {$_.Id -match $BlueYonderId}
$enabledConnectorScenario = $blueYonder.SupportedScenario
$wfiSupportedScenario = $blueYonder.wfiSupportedScenario

#Prompt for entering of WFM username and password
$WfmUserName = Read-Host -Prompt 'Input your WFM user name'
$WfmPwd = Read-Host -Prompt 'Input your WFM password' -AsSecureString
$plainPwd =[Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($WfmPwd))

#Test connection settings
Write-Host "Testing connection settings"
$InstanceName = Read-Host -Prompt 'Input connection instance name'
$adminApiUrl = Read-Host -Prompt 'Input admin api url'
$cookieAuthUrl = Read-Host -Prompt 'Input cookie authorization url'
$essApiUrl = Read-Host -Prompt 'Input ess api url'
$federatedAuthUrl = Read-Host -Prompt 'Input federated authorization url'
$retailWebApiUrl = Read-Host -Prompt 'Input retail web api url'
$siteManagerUrl = Read-Host -Prompt 'Input site manager url'
$testResult = Test-CsTeamsShiftsConnectionValidate `
    -Name $InstanceName `
    -ConnectorId $BlueYonderId `
    -ConnectorSpecificSettings (New-Object Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.ConnectorSpecificBlueYonderSettingsRequest `
        -Property @{
            AdminApiUrl = $adminApiUrl
            SiteManagerUrl = $siteManagerUrl
            EssApiUrl = $essApiUrl
            RetailWebApiUrl = $retailWebApiUrl
            CookieAuthUrl = $cookieAuthUrl
            FederatedAuthUrl = $federatedAuthUrl
            LoginUserName = $WfmUserName
            LoginPwd = $plainPwd
        })
if ($testResult.Code -ne $NULL) {
    write $testResult
    throw "Validation failed, conflict found"
}
Write-Host "Test complete, no conflicts found"

#Create a connection instance (includes WFM site team ids)
Write-Host "Creating a connection instance"
$designatorName = Read-Host -Prompt "Input designated actor's user name"
$domain = $designatorName.Split("@")[1]
$designator = Get-MgUser -UserId $designatorName
$teamsUserId = $designator.Id
$syncFreq = Read-Host -Prompt "Input sync frequency"

#Read admin email list
[psobject[]]$AdminEmailList = @()
while ($true){
$AdminEmail = Read-Host -Prompt "Enter admin's email to receive error report"
$AdminEmailList += $AdminEmail
$title    = 'Adding another email'
$question = 'Would you like to add another admin email?'
$choices  = '&Yes', '&No'
$decision = $Host.UI.PromptForChoice($title, $question, $choices, 1)
if ($decision -eq 1) {
    break
}
}
$InstanceResponse = New-CsTeamsShiftsConnectionInstance `
    -ConnectorId $BlueYonderId `
    -ConnectorAdminEmail $AdminEmailList `
    -DesignatedActorId $teamsUserId `
    -EnabledConnectorScenario $enabledConnectorScenario `
    -EnabledWfiScenario $wfiSupportedScenario `
    -Name $InstanceName `
    -SyncFrequencyInMin $syncFreq `
    -ConnectorSpecificSettings (New-Object Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.ConnectorSpecificBlueYonderSettingsRequest `
        -Property @{
            AdminApiUrl = $adminApiUrl
            SiteManagerUrl = $siteManagerUrl
            EssApiUrl = $essApiUrl
            RetailWebApiUrl = $retailWebApiUrl
            CookieAuthUrl = $cookieAuthUrl
            FederatedAuthUrl = $federatedAuthUrl
            LoginUserName = $WfmUserName
            LoginPwd = $plainPwd
        })
$InstanceId = $InstanceResponse.id
$Etag = $InstanceResponse.etag
if ($InstanceId -ne $null){
    Write-Host "Success"
} else {
    throw "Connector instance creation failed"
}

#Retrieve the list of instances
Write-Host "Listing the WFM team sites"
$WfmTeamIds = Get-CsTeamsShiftsConnectionWfmTeam -ConnectorInstanceId $InstanceId
write $WfmTeamIds
if (($WfmTeamIds -ne $NULL) -and ($WfmTeamIds.Count -gt 0)){
    [System.String]$WfmTeamId = Read-Host -Prompt "Input the ID of WFM team you want to map"
}
else {
    throw "The WfmTeamId list is null or empty"
}

#Retrieve the list of WFM users and their roles
Write-Host "Listing WFM users and roles"
$WFMUsers = Get-CsTeamsShiftsConnectionWfmUser -ConnectorInstanceId $InstanceId -WfmTeamId $WfmTeamId
write $WFMUsers

#Keep mapping teams until user stops it
while ($true)
{

#Create a new Teams team with owner set to system account and name set to the site name
Write-Host "Creating a Teams team"
$teamsTeamName = Read-Host -Prompt "Input the Teams team name"
$Team = New-Team -DisplayName $teamsTeamName -Visibility "Public" -Owner $teamsUserId
Write-Host "Success"
$TeamsTeamId=$Team.GroupId

#Add users to the Team for Shifts
Write-Host "Adding users to Teams team"
$currentUser = Read-Host -Prompt "Input the current user's user name or ID"
Add-TeamUser -GroupId $TeamsTeamId -User $currentUser -Role Owner
$failedWfmUsers=@()
foreach ($user in $WFMUsers) {
    try {
    $userEmail = $user.Name + "@" +$domain
    Add-TeamUser -GroupId $TeamsTeamId -User $userEmail
    } catch {
        $failedWfmUsers+=$user
    }
}
if($failedWfmUsers.Count -gt 0){
    Write-Host "There are WFM users not existed in Teams tenant:"
    write $failedWfmUsers
}

#Enable scheduling in the group
$RequestBody = @{
    Enabled = $true
    TimeZone = "America/Los_Angeles"
}
$teamUpdateUrl="https://graph.microsoft.com/v1.0/teams/"+$TeamsTeamId+"/schedule"
$Schedule = Invoke-MgGraphRequest -Uri $teamUpdateUrl -Method PUT -Body $RequestBody

#Create a mapping of the new team to the instance
Write-Host "Create a mapping of the new team to the site"
$TimeZone = Read-Host -Prompt "Input the time zone of team mapping"
$teamMappingResult = New-CsTeamsShiftsConnectionTeamMap -ConnectorInstanceId $InstanceId -TeamId $TeamsTeamId -TimeZone $TimeZone -WfmTeamId $WfmTeamId
Write-Host "Success"

$title    = 'Connecting another team'
$question = 'Would you like to connect another team?'
$choices  = '&Yes', '&No'

$decision = $Host.UI.PromptForChoice($title, $question, $choices, 1)
if ($decision -eq 1) {
    break
}
}
Remove-TeamUser -GroupId $TeamsTeamId -User $currentUser -Role Owner
Disconnect-MgGraph
----

==== Set up a connection and map to existing teams

[source,powershell]
----
#Map WFM sites to existing teams script
Write-Host "Map WFM sites to existing teams"
Start-Sleep 1

#Ensure Teams module is at least version x
Write-Host "Checking Teams module version"
try {
    Get-InstalledModule -Name "MicrosoftTeams" -MinimumVersion 4.7.0
} catch {
    throw
}

#Connect to MS Graph
Connect-MgGraph -Scopes "User.Read.All","Group.ReadWrite.All"

#List connector types available (comment out if not implemented for preview)
Write-Host "Listing connector types available"
$BlueYonderId = "6A51B888-FF44-4FEA-82E1-839401E9CD74"
$connectors = Get-CsTeamsShiftsConnectionConnector
write $connectors
$blueYonder = $connectors | where {$_.Id -match $BlueYonderId}
$enabledConnectorScenario = $blueYonder.SupportedScenario
$wfiSupportedScenario = $blueYonder.wfiSupportedScenario

#Prompt for entering of WFM username and password
$WfmUserName = Read-Host -Prompt 'Input your WFM user name'
$WfmPwd = Read-Host -Prompt 'Input your WFM password' -AsSecureString
$plainPwd =[Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($WfmPwd))

#Test connection settings
Write-Host "Testing connection settings"
$InstanceName = Read-Host -Prompt 'Input connection instance name'
$adminApiUrl = Read-Host -Prompt 'Input admin api url'
$cookieAuthUrl = Read-Host -Prompt 'Input cookie authorization url'
$essApiUrl = Read-Host -Prompt 'Input ess api url'
$federatedAuthUrl = Read-Host -Prompt 'Input federated authorization url'
$retailWebApiUrl = Read-Host -Prompt 'Input retail web api url'
$siteManagerUrl = Read-Host -Prompt 'Input site manager url'
$testResult = Test-CsTeamsShiftsConnectionValidate `
    -Name $InstanceName `
    -ConnectorId $BlueYonderId `
    -ConnectorSpecificSettings (New-Object Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.ConnectorSpecificBlueYonderSettingsRequest `
        -Property @{
            AdminApiUrl = $adminApiUrl
            SiteManagerUrl = $siteManagerUrl
            EssApiUrl = $essApiUrl
            RetailWebApiUrl = $retailWebApiUrl
            CookieAuthUrl = $cookieAuthUrl
            FederatedAuthUrl = $federatedAuthUrl
            LoginUserName = $WfmUserName
            LoginPwd = $plainPwd
        })
if ($testResult.Code -ne $NULL) {
    write $testResult
    throw "Validation failed, conflict found"
}
Write-Host "Test complete, no conflicts found"

#Create an instance (includes WFM site team ids)
Write-Host "Creating a connection instance"
$designatorName = Read-Host -Prompt "Input designated actor's user name"
$domain = $designatorName.Split("@")[1]
$designator = Get-MgUser -UserId $designatorName
$teamsUserId = $designator.Id
$syncFreq = Read-Host -Prompt "Input sync frequency. Value should be equal to or more than 10."

#Read admin email list
[psobject[]]$AdminEmailList = @()
while ($true){
$AdminEmail = Read-Host -Prompt "Enter admin's email to receive error report"
$AdminEmailList += $AdminEmail
$title    = 'Adding another email'
$question = 'Would you like to add another admin email?'
$choices  = '&Yes', '&No'
$decision = $Host.UI.PromptForChoice($title, $question, $choices, 1)
if ($decision -eq 1) {
    break
}
}

$InstanceResponse = New-CsTeamsShiftsConnectionInstance `
    -ConnectorId $BlueYonderId `
    -ConnectorAdminEmail $AdminEmailList `
    -DesignatedActorId $teamsUserId `
    -EnabledConnectorScenario $enabledConnectorScenario `
    -EnabledWfiScenario $wfiSupportedScenario `
    -Name $InstanceName `
    -SyncFrequencyInMin $syncFreq `
    -ConnectorSpecificSettings (New-Object Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.ConnectorSpecificBlueYonderSettingsRequest `
        -Property @{
            AdminApiUrl = $adminApiUrl
            SiteManagerUrl = $siteManagerUrl
            EssApiUrl = $essApiUrl
            RetailWebApiUrl = $retailWebApiUrl
            CookieAuthUrl = $cookieAuthUrl
            FederatedAuthUrl = $federatedAuthUrl
            LoginUserName = $WfmUserName
            LoginPwd = $plainPwd
    })
$InstanceId = $InstanceResponse.id
$Etag = $InstanceResponse.etag
if ($InstanceId -ne $null){
    Write-Host "Success"
} else {
    throw "Connector instance creation failed"
}

#Retrieve the list of instances
Write-Host "Listing the WFM team sites"
$WfmTeamIds = Get-CsTeamsShiftsConnectionWfmTeam -ConnectorInstanceId $InstanceId
write $WfmTeamIds
if (($WfmTeamIds -ne $NULL) -and ($WfmTeamIds.Count -gt 0)){
    [System.String]$WfmTeamId = Read-Host -Prompt "Input the ID of WFM team you want to map"
}
else {
    throw "The WfmTeamId list is null or empty"
}

#Retrieve the list of WFM users and their roles
Write-Host "Listing WFM users and roles"
$WFMUsers = Get-CsTeamsShiftsConnectionWfmUser -ConnectorInstanceId $InstanceId -WfmTeamId $WfmTeamId
write $WFMUsers

#Keep mapping teams until user stops it
while ($true)
{

$TeamsTeamId = Read-Host -Prompt "Input the ID of the Teams team to be mapped"
#Clear schedule of the Teams team
Write-Host "Clear schedule of the existing team"
$startTime = Read-Host -Prompt "Input the start time of clear schedule"
$endTime = Read-Host -Prompt "Input the end time of clear schedule"

$entityTypeString = Read-Host -Prompt 'Input the entity types of clear schedule'
$Delimiters = ",", ".", ":", ";", " ", "`t"
$entityType = $entityTypeString -Split {$Delimiters -contains $_}
$entityType = $entityType.Trim()
$entityType = $entityType.Split('',[System.StringSplitOptions]::RemoveEmptyEntries)
Remove-CsTeamsShiftsScheduleRecord -TeamId $TeamsTeamId -DateRangeStartDate $startTime -DateRangeEndDate $endTime -ClearSchedulingGroup:$True -EntityType $entityType -DesignatedActorId $teamsUserId

#Create a mapping of the existing team to the instance
Write-Host "Create a mapping of the existing team to the site"
$teamMappingResult = New-CsTeamsShiftsConnectionTeamMap -ConnectorInstanceId $InstanceId -TeamId $TeamsTeamId -TimeZone "America/Los_Angeles" -WfmTeamId $WfmTeamId
Write-Host "Success"


$title    = 'Connecting another team'
$question = 'Would you like to connect another team?'
$choices  = '&Yes', '&No'

$decision = $Host.UI.PromptForChoice($title, $question, $choices, 1)
if ($decision -eq 1) {
    break
}
}
Disconnect-MgGraph
----

=== Shifts connector cmdlets

For help with Shifts connector cmdlets, including the cmdlets used in
the scripts, search for *CsTeamsShiftsConnection* in the
link:/powershell/teams/intro[Teams PowerShell cmdlet reference]. Here
are links to some commonly used cmdlets.

* link:/powershell/module/teams/get-csteamsshiftsconnectionoperation[Get-CsTeamsShiftsConnectionOperation]
* link:/powershell/module/teams/new-csteamsshiftsconnectioninstance[New-CsTeamsShiftsConnectionInstance]
* link:/powershell/module/teams/get-csteamsshiftsconnectioninstance[Get-CsTeamsShiftsConnectionInstance]
* link:/powershell/module/teams/set-csteamsshiftsconnectioninstance[Set-CsTeamsShiftsConnectionInstance]
* link:/powershell/module/teams/update-csteamsshiftsconnectioninstance[Update-CsTeamsShiftsConnectionInstance]
* link:/powershell/module/teams/remove-csteamsshiftsconnectioninstance[Remove-CsTeamsShiftsConnectionInstance]
* link:/powershell/module/teams/test-csteamsshiftsconnectionvalidate[Test-CsTeamsShiftsConnectionValidate]
* link:/powershell/module/teams/new-csteamsshiftsconnectionteammap[New-CsTeamsShiftsConnectionTeamMap]
* link:/powershell/module/teams/get-csteamsshiftsconnectionteammap[Get-CsTeamsShiftsConnectionTeamMap]
* link:/powershell/module/teams/remove-csteamsshiftsconnectionteammap[Remove-CsTeamsShiftsConnectionTeamMap]
* link:/powershell/module/teams/get-csteamsshiftsconnectionconnector[Get-CsTeamsShiftsConnectionConnector]
* link:/powershell/module/teams/get-csteamsshiftsconnectionsyncresult[Get-CsTeamsShiftsConnectionSyncResult]
* link:/powershell/module/teams/get-csteamsshiftsconnectionwfmuser[Get-CsTeamsShiftsConnectionWfmUser]
* link:/powershell/module/teams/get-csteamsshiftsconnectionwfmteam[Get-CsTeamsShiftsConnectionWfmTeam]
* link:/powershell/module/teams/get-csteamsshiftsconnectionerrorreport[Get-CsTeamsShiftsConnectionErrorReport]
* link:/powershell/module/teams/remove-csteamsshiftsschedulerecord[Remove-CsTeamsShiftsScheduleRecord]

=== Related articles

* link:shifts-connectors.md[Shifts connectors]
* link:shifts-connector-powershell-manage.md[Use PowerShell to manage
your Shifts connection to Blue Yonder Workforce Management]
* link:shifts-connector-blue-yonder-admin-center-manage.md[Use the
Microsoft 365 admin center to manage your Shifts connection to Blue
Yonder Workforce Management]
* link:/microsoftteams/expand-teams-across-your-org/shifts/manage-the-shifts-app-for-your-organization-in-teams?bc=/microsoft-365/frontline/breadcrumb/toc.json&toc=/microsoft-365/frontline/toc.json[Manage
the Shifts app]
* link:/microsoftteams/teams-powershell-overview[Teams PowerShell
overview]
* link:/powershell/teams/intro[Teams PowerShell cmdlet reference]
