= Help your frontline workers track time and attendance
:appliesto: ["Microsoft Teams", "Microsoft 365 for frontline workers"]
:audience: ITPro
:author: daisyfell
:description: Resources to help train your frontline team in using Shifts to access and manage their schedules.
:f1.keywords: ["NOCSH"]
:manager: pamgreen
:ms.author: daisyfeller
:ms.collection: ["microsoftcloud-healthcare", "m365solution-healthcare", "m365solution-scenario", "m365-frontline"]
:ms.localizationpriority: high
:ms.reviewer:
:ms.service: microsoft-365-frontline
:ms.topic: article
:search.appverid:
:searchScope: ["Microsoft Teams", "Microsoft Cloud for Healthcare"]

== Help your frontline workers track time and attendance

Now that your organization has begun using Shifts to manage schedules, you'll need to make sure that your frontline workers understand how to track their time and attendance.

Use your xref:flw-corp-comms.adoc[corporate communications strategy] to share Shifts training content with your team and make sure they have access to the resources they need:

. Share the https://support.microsoft.com/office/what-is-shifts-f8efe6e4-ddb3-4d23-b81b-bb812296b821[Shifts video training] with your team to help them understand the basics.
. Share <<shifts-videos-for-managers,Videos for frontline managers>> with your managers to help them set up and manage schedules for their teams.
. Share <<shifts-videos-for-users,Videos for users>> with all of your frontline staff to help them perform regular tasks such as clocking in and swapping shifts.

=== Shifts videos for managers

Create a schedule with Shifts + https://go.microsoft.com/fwlink/?linkid=2202612[View Create a schedule with Shifts on YouTube]

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/RE546xr]
____

Copy a schedule with Shifts + https://go.microsoft.com/fwlink/?linkid=2202298[View Copy a schedule with Shifts on YouTube]

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/RE54jxu]
____

Reuse a weekly schedule from Excel with Shifts + https://go.microsoft.com/fwlink/?linkid=2202611[View Reuse a weekly schedule from Excel with Shifts on YouTube]

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/RE546xQ]
____

=== Shifts videos for users

Clocking in with Shifts + https://go.microsoft.com/fwlink/?linkid=2202613[View Clocking in with Shifts on YouTube]

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/RE54uyx]
____

Swap Shifts + https://go.microsoft.com/fwlink/?linkid=2202711[View Swap Shifts on YouTube]

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/RE54jBv]
____

Tags with Shifts + https://go.microsoft.com/fwlink/?linkid=2202712[View Tags with Shifts on YouTube]

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/RE5443n]
____
