= 
LanaChin

== Microsoft Teams Virtual Visits usage report

The Virtual Visits usage report in the Microsoft Teams admin center
gives you an overview of Teams virtual appointment activity in your
organization. You can view detailed activity for virtual appointments
scheduled through the link:bookings-virtual-visits.md[Bookings app] and
the
link:teams-in-hc.md#virtual-appointments-and-electronic-healthcare-record-ehr-integration[Microsoft
Teams Electronic Health Record (EHR) connector].

To view the report, you must be a global admin or Teams admin.

The report contains the following tabs. The information you’ll see in
the report depends on whether you have a license for the Bookings app,
the Teams EHR connector, or both.

[width="100%",cols="50%,50%",options="header",]
|===
|Tab |Description
|*link:#virtual-visits[Virtual Visits]* |Shows the total number of
virtual appointments, with a breakdown of the number of appointments
scheduled using the Bookings app and Teams EHR-integrated meetings
conducted from your EHR system.

|*link:#duration[Duration]* |Shows the average duration of appointments
and average lobby wait time of participants.

|*link:#bookings[Bookings]* |Shows the number of appointments scheduled
through the Bookings app.

|*link:#ehr[EHR]* |Shows the number of Teams EHR-integrated appointments
conducted from your EHR system.
|===

Use this report to gain insight into virtual appointment activity and
trends in your organization. The information can help you optimize
virtual appointments to deliver better business outcomes.

=== View the Virtual Visits usage report

[arabic]
. In the left navigation of the Microsoft Teams admin center, choose
*Analytics & reports* > *Usage reports*. On the *View reports* tab,
under *Report*, select *Virtual Visits usage*.
. Under *Date range*, select a date range of 7 days, 30 days, or 90
days. Then, choose *Run report*.

____
[!NOTE] By default, Virtual Visits analytics is on and the report is
available. By using this report, you give Microsoft permission to
collect data about virtual appointments in your organization. For
information about our data retention policies, see
link:/compliance/assurance/assurance-data-retention-deletion-and-destruction-overview[Data
retention&#44; deletion&#44; and destruction in Microsoft 365].

If you want to turn off the report for your organization, you can do so
in *Settings* in the upper-right corner of the page. This setting may
take between 0 (zero) to 2 hours to take effect after you change it.
____

=== Interpret the report

==== Virtual Visits

The graphs you’ll see here depend on whether you have a license for the
Bookings app, the Teams EHR connector, or both. To learn more, see
link:/microsoftteams/bookings-app-admin?bc=/microsoft-365/frontline/breadcrumb/toc.json&toc=/microsoft-365/frontline/toc.json[Manage
the Bookings app], and link:ehr-admin-cerner.md[Integration into Cerner
EHR] or link:ehr-admin-epic.md[Integration into Epic EHR].

:::image type=``content''
source=``media/virtual-visits-usage-report-virtual-visits.png''
alt-text=``Screenshot of the Virtual Visits tab of the Virtual Visits
usage report showing numbered callouts.''
lightbox=``media/virtual-visits-usage-report-virtual-visits.png'':::

[width="100%",cols="39%,61%",options="header",]
|===
|Callout |Description
|*1* |Each report has a date for when the report was generated. The
reports usually reflect a 24 to 48-hour latency from time of activity.

|*2* |The X axis is the selected date range for the report. The Y axis
is the number of appointments.Hover over the dot on a given date to see
the number of appointments on that date.

|*3* |You can filter what you see on the chart by selecting an item in
the legend. For example, select *Total Bookings Virtual Visits* or
*Total EHR Virtual Visits* to see only the info related to each one.
Changing this selection doesn’t change the information in the table.

|*4* |The table gives you detailed information about each appointment
that took place during the selected date range.

|*5* |Select *Settings* to open the *Virtual Visits analytics* pane.
From here, you can turn off or turn on Virtual Visits reporting for your
organization and add or remove columns in the table. To see the
information that you want in the table, make sure to add the columns to
the table.

|*6* |You can export the report to a CSV file for offline analysis.
Select *Export to Excel*, and then on the *Downloads* tab, choose
*Download* to download the report when it’s ready.
|===

==== Duration

:::image type=``content''
source=``media/virtual-visits-usage-report-duration.png''
alt-text=``Screenshot of the Duration tab of the Virtual Visits usage
report showing numbered callouts.''
lightbox=``media/virtual-visits-usage-report-duration.png'':::

[width="100%",cols="39%,61%",options="header",]
|===
|Callout |Description
|*1* |Each report has a date for when the report was generated. The
reports usually reflect a 24 to 48-hour latency from time of activity.

|*2* |The X axis is the selected date range for the report. The Y axis
is the number of minutes.Hover over the dot on a given date to see the
average appointment duration or average lobby wait time for a given
date.

|*3* |You can filter what you see on the chart by selecting an item in
the legend. For example, select *Average Virtual Visit duration* or
*Average lobby wait time* to see only the info related to each one.
Changing this selection doesn’t change the information in the table.

|*4* |The table gives you detailed information about each appointment
that took place during the selected date range.

|*5* |Select *Settings* to open the *Virtual Visits analytics* pane.
From here, you can turn off or turn on Virtual Visits reporting for your
organization and add or remove columns in the table. To see the
information that you want in the table, make sure to add the columns to
the table.

|*6* |You can export the report to a CSV file for offline analysis.
Select *Export to Excel*, and then on the *Downloads* tab, choose
*Download* to download the report when it’s ready.
|===

==== Bookings

You’ll see this tab if you have a license that includes the Bookings
app. To learn more, see
link:/microsoftteams/bookings-app-admin?bc=/microsoft-365/frontline/breadcrumb/toc.json&toc=/microsoft-365/frontline/toc.json[Manage
the Bookings app].

:::image type=``content''
source=``media/virtual-visits-usage-report-bookings.png''
alt-text=``Screenshot of the Bookings tab of the Virtual Visits usage
report showing numbered callouts.''
lightbox=``media/virtual-visits-usage-report-bookings.png'':::

[width="100%",cols="39%,61%",options="header",]
|===
|Callout |Description
|*1* |Each report has a date for when the report was generated. The
reports usually reflect a 24 to 48-hour latency from time of activity.

|*2* |The X axis is the selected date range for the report. The Y axis
is the number of Bookings appointments.Hover over the dot on a given
date to see the number of Bookings appointments that occurred on that
date.

|*3* |The table gives you detailed information about each appointment
that took place during the selected date range.

|*4* |Select *Settings* to open the *Virtual Visits analytics* pane.
From here, you can turn off or turn on Virtual Visits reporting for your
organization and add or remove columns in the table. To see the
information that you want in the table, make sure to add the columns to
the table.

|*5* |You can export the report to a CSV file for offline analysis.
Select *Export to Excel*, and then on the *Downloads* tab, choose
*Download* to download the report when it’s ready.
|===

==== EHR

You’ll see this tab if you have a license that includes the Teams EHR
connector. To learn more, see link:ehr-admin-cerner.md[Integration into
Cerner EHR] or link:ehr-admin-epic.md[Integration into Epic EHR].

:::image type=``content''
source=``media/virtual-visits-usage-report-ehr.png''
alt-text=``Screenshot of the EHR tab of the Virtual Visits usage report
showing numbered callouts.''
lightbox=``media/virtual-visits-usage-report-ehr.png'':::

[width="100%",cols="39%,61%",options="header",]
|===
|Callout |Description
|*1* |Each report has a date for when the report was generated. The
reports usually reflect a 24 to 48-hour latency from time of activity.

|*2* |The X axis is the selected date range for the report. The Y axis
is the number of EHR appointments.Hover over the dot on a given date to
see the number of EHR appointments on that date.

|*3* |The table gives you detailed information about each appointment
that took place during the selected date range.

|*4* |Select *Settings* to open the *Virtual Visits analytics* pane.
From here, you can turn off or turn on Virtual Visits reporting for your
organization and add or remove columns in the table. To see the
information that you want in the table, make sure to add the columns to
the table.

|*5* |You can export the report to a CSV file for offline analysis.
Select *Export to Excel*, and then on the *Downloads* tab, choose
*Download* to download the report when it’s ready.
|===

____
[!NOTE] If your organization would like to participate in private
preview for non-admin users such as business decision makers to have
access to and view this report,
mailto:tapmwtanalytics@microsoft.com[reach out us].
____

=== Related articles

* link:bookings-virtual-visits.md[Virtual appointments with Teams and
the Bookings app]
* link:ehr-admin-epic.md[Virtual appointments with Teams - Integration
into Epic EHR]
* link:ehr-admin-cerner.md[Virtual appointments with Teams - Integration
into Cerner EHR]
