= 
LanaChin

== Virtual Appointments with Microsoft Teams

With Virtual Appointments in Microsoft Teams, you have a complete
meeting platform to schedule, manage, and conduct business-to-customer
engagements. For example:

* Financial advisors, claims adjusters, and other financial
professionals can meet with clients remotely.
* Sales associates, product experts, and design consultants can conduct
virtual fittings and consultations.
* Clinicians can meet with patients or other healthcare providers to
discuss medical care.
* Human resources departments can conduct virtual interviews with job
candidates.

This article gives you an overview of the capabilities available in
Teams for scheduling and managing virtual appointments.

* link:#the-virtual-appointments-app[The Virtual Appointments app], for
every organization
* link:#the-bookings-app[The Bookings app], for every organization
* link:#teams-electronic-health-record-ehr-connector[The Teams
Electronic Health Record (EHR) connector], for healthcare organizations
who use an EHR system
* link:#virtual-appointment-meeting-template[Virtual appointment meeting
template], for every organization
* link:#virtual-appointment-graph-api[Virtual Appointment Graph API],
for developers in your organization

=== The Virtual Appointments app

{empty}[!INCLUDE link:includes/preview-feature.md[preview-feature]]

The Virtual Appointments app provides a central hub for all your virtual
appointment needs. The app enables a seamless end-to-end experience for
business-to-customer engagements, integrating schedules from the
Bookings app, analytics, and management options, all in one place.

You can schedule, view, and manage virtual appointments, get real-time
status updates in a queue view, send appointment reminders, view
analytics and reports to gain insight into virtual appointments
activity, and configure calendar, staff, and booking page settings.

With any Microsoft 365 license, you can use basic Virtual Appointments
capabilities that make it easy to schedule and join business-to-customer
meetings. For example, you can schedule appointments in the Bookings
calendar and external attendees can link:browser-join.md[join through a
browser] without having to download Teams.
link:/microsoftteams/teams-add-on-licensing/licensing-enhance-teams[Teams
Premium] (Preview) unlocks advanced Virtual Appointments capabilities
that your organization can use to manage and personalize the experience.
These include a queue view of scheduled and on-demand appointments, SMS
text notifications, custom waiting rooms, and analytics.

To learn more, see:

* link:/microsoftteams/manage-virtual-appointments-app?bc=/microsoft-365/frontline/breadcrumb/toc.json&toc=/microsoft-365/frontline/toc.json[Manage
the Virtual Appointments app]
* https://guidedtour.microsoft.com/guidedtour/industry-longform/virtual-appointments/1/1[Virtual
Appointments guided tour]

=== The Bookings app

The
https://support.microsoft.com/office/what-is-bookings-42d4e852-8e99-4d8f-9b70-d7fc93973cb5[Bookings
app] in Teams offers a simple way to schedule and manage virtual
appointments. Use it to schedule virtual appointments such as financial
consultations, healthcare visits, interviews, customer support, virtual
fittings and consultations, and education office hours.

Schedulers can manage multiple department and staff calendars, as well
as communications with internal and external attendees.

Each scheduled virtual appointment contains a Teams meeting link that’s
sent to attendees in email where they can easily join from a browser or
in Teams on any device.

With any Microsoft 365 license, you can use basic Virtual Appointments
capabilities that make it easy to schedule and join business-to-customer
meetings. For example, attendees can wait in a pre-appointment waiting
room and link:browser-join.md[join through a browser] without having to
download Teams. With
link:/microsoftteams/teams-add-on-licensing/licensing-enhance-teams[Teams
Premium] (Preview), your organization gets advanced Virtual Appointments
capabilities on top of Bookings to manage and personalize the
experience. These include a queue view of scheduled and on-demand
appointments, SMS text notifications, custom waiting rooms, and
analytics.

To learn more, see:

* link:/microsoftteams/bookings-app-admin?bc=/microsoft-365/frontline/breadcrumb/toc.json&toc=/microsoft-365/frontline/toc.json[Manage
the Bookings app]
* link:bookings-virtual-appointments.md[Virtual Appointments with Teams
and the Bookings app]
* link:virtual-appointments-toolkit.md[Help your clients and customers
use virtual appointments]

=== Teams Electronic Health Record (EHR) connector

If your healthcare organization uses an EHR system, you can use the
Teams EHR connector to integrate Teams for a more seamless virtual care
experience. The Teams EHR connector requires an active subscription to
Microsoft Cloud for Healthcare or a subscription to Microsoft Teams EHR
connector standalone offer.

After you set up the Teams EHR connector, clinicians can launch visits
with patients and consultations with other providers in Teams directly
from the EHR system.

Currently, the Teams EHR connector supports integration with the Cerner
EHR system and Epic EHR system. To learn more, see:

* link:ehr-admin-cerner.md[Virtual appointments with Teams - Integration
into Cerner EHR]
* link:ehr-admin-epic.md[Virtual appointments with Teams - Integration
into Epic EHR]

=== Virtual appointment meeting template

The Virtual appointment template is a default meeting template in Teams
that your users can use to schedule virtual appointments with customers,
clients and other people outside your organization. The template allows
you to specify values for meeting settings that meeting organizers
typically control. Use it to apply default settings and enforce
settings.

With this template, you can enable a consistent experience across your
organization for virtual appointments scheduled directly within Teams
and help enforce compliance requirements.

To learn more, see
link:/microsoftteams/virtual-appointment-meeting-template[Virtual
appointment meeting template in Teams].

=== Virtual Appointment Graph API

Developers can programmatically create and manage Virtual Appointments
using Microsoft Graph. With the Virtual Appointment Graph API, virtual
appointment join links can be embedded in any app, with features that
include a waiting room and browser join experience for external
attendees.

To learn more, see
link:/graph/api/resources/virtualappointment?view=graph-rest-beta[virtualAppointment
resource type].

=== Related articles

* link:browser-join.md[Manage the join experience for Teams Virtual
Appointments on browsers]
