= 
Tinacyt

== Monitoring Test Status

Test run status in the Test Base portal keeps you informed of where your
package is in the testing process. You can see status in the *Test
summary* page in addition to the *Details* pane.

This status provides details about test execution. If failures were
detected during test execution, you’ll find additional status and
guidance information on the *Test Analysis* tab.

Current possible execution status values are described in the table that
follows:

=== Table 2. Test Execution status

[width="100%",cols="50%,50%",options="header",]
|===
|Status |Meaning
|*Completed* |Test run and data processing are completed. Results are
available.

|*Processing* |Test execution is complete. Data is processing and
results will be available soon.

|*Test Execution in Progress* |Test execution is in progress.

|*Test Failure* |Test run and data processing are complete. Your full
test result details are available to view and there’s a failure that
requires your attention.

|*Infrastructure Failure* |There’s a failure in our infrastructure. The
issue will be investigated and require no further action from you.
|===
