= Overview
:audience: Software-Vendor
:author: Tinacyt
:description: Understanding Test Base
:f1.keywords: NOCSH
:manager: rshastri
:ms.author: tinachen
:ms.collection: TestBase-M365
:ms.custom:
:ms.date: 07/06/2021
:ms.localizationpriority: medium
:ms.reviewer: tinachen
:ms.service: test-base
:ms.topic: how-to
:search.appverid: MET150

== What is Test Base for Microsoft 365?

Test Base is an Azure service that enables data-driven application testing while providing user access to intelligent testing from anywhere in the world.

The following entities are encouraged to onboard their applications, binaries, and test scripts onto the Test Base for Microsoft 365 service: Independent Software Vendors (ISVs), System Integrators (SIs) to validate their applications and IT Professionals who want to validate their line-of-business (LOB) applications through integration with Microsoft Intune.

=== Why test your application with Test Base?

The Test Base for Microsoft 365 service can accommodate the expansion of your testing matrix as necessary so you will have confidence in the integrity, compatibility, and usability of your applications.

Test Base enables your application to continue working as expected even as platform dependencies vary, and new updates are applied by the Windows update service.
With Test Base, you can avoid the aggravation, protracted time commitments, and the expense of setting up and maintaining a complex lab environment for testing your applications.

In addition, you can automatically test compatibility against security and feature updates for Windows by using secure virtual machines (VMs) while also obtaining access to world-class intelligence for testing your applications.
You can also get your apps tested for compatibility against pre-release windows security updates by submitting a request to get the access.

=== How does Test Base work?

To sign up for the Test Base service, see xref:createAccount.adoc[Create a new Test Base account].

After a customer has enrolled in the Test Base service, it is a simple matter to begin uploading application packages for testing.

Following a successful upload, packages are tested against Windows pre-release updates.

After initial tests are successfully completed, the customer can do a deep dive with insights on performance and regression analysis to detect whether pre-release content updates have degraded application performance in any way.

However, if the package failed any test, then the customer can also leverage Insights from memory or CPU regressions to remediate the failure and then update the package as necessary.

With Test Base, the customer can use a single location to manage all packages being tested, which can also facilitate uploading and updating packages to generate new application versions as needed.

____
[!NOTE] *So that customers can take advantage of pre-release update content, they must specifically request access to it.
Once your request for access to pre-release updates is approved, your uploaded packages will automatically get scheduled to be tested against the pre-release Windows updates for the OS versions selected during onboarding*.
____

Then, as new Windows pre-release updates become available, application packages are automatically tested with new pre-release content.
Thereafter, an additional round of insights may be required.
If customers do not specifically request access, then application packages will be tested against only the current released version of Windows.

After packages are successfully tested, customers can deliver them to their software customers and end users with confidence and the assurance that Test Base did its job.

=== Next steps

Follow the link to get started

____
[!div class="nextstepaction"] xref:createaccount.adoc[Create a new Test Base account | Microsoft Docs]
____
