= Integrate Microsoft OneDrive LTI with Desire2Learn Brightspace
:audience: admin
:author: DaniEASmith
:description: Create and grade assignments, build and curate course content, and collaborate on files in real time with the new Microsoft OneDrive Learning Tools Interoperability for Desire2Learn Brightspace.
:manager: serdars
:ms.author: danismith
:ms.collection: m365initiative-edu
:ms.localizationpriority: medium
:ms.reviewer: amitman
:ms.service: o365-administration
:ms.topic: article

== Integrate Microsoft OneDrive LTI with Desire2Learn Brightspace

This guide provides IT admins steps for registering the OneDrive LTI app for the Desire2Learn (D2L) Brightspace LMS.

For an overview of Microsoft LTI, see xref:index.adoc[Integrating Microsoft products with your Learning Management System (LMS)].

The steps to add the OneDrive LTI app are:

. <<step-1-add-the-new-microsoft-onedrive-lti-app,Step 1: Add the new Microsoft OneDrive LTI app>>.
. <<step-2-deploy-the-lti-app-in-users-brightspace-experience,Step 2: Deploy the LTI app in users' Brightspace experience>>.
. <<step-3-turn-off-the-older-onedrive-app,Step 3: Turn off the older OneDrive app>>.
. <<step-4-turn-on-the-new-onedrive-lti-app-on-the-quicklinks-activity-bar-optional,Step 4: Turn on the new OneDrive LTI app on the Quicklinks activity bar>> (optional).

____
[!IMPORTANT] The person who performs this integration should be an administrator of Brightspace and an administrator of the Microsoft 365 tenant.

The source documentation for LTI 1.3 settings is located in the https://community.brightspace.com/s/article/LTI-Advantage-Administrator-Guide[LTI Advantage - Administrator Guide].
____

=== Step 1: Add the new Microsoft OneDrive LTI app

==== Register a new Microsoft OneDrive LTI app

. Sign into the https://onedrivelti.microsoft.com/admin[Microsoft OneDrive LTI Registration Portal].
. Select the *Admin Consent* button and accept the permissions.
 .. If this step isn't performed, the following step will give you an error, and you won't be able to take this step for an hour once you've gotten the error.
. Select the *Create new LTI Tenant* button.
. In the *LTI Consumer Platform* list, select *D2L Brightspace*.
. In the *D2L Brightspace Base URL* field, enter your Brightspace base URL, like `+https://testschool.brightspace.com+`.
. Select the *Next* button.
The *Register LTI 1.3 App* page will load.
 .. Keep this page open in its own tab when completing the next set of steps.

==== Add Microsoft LTI registration details to Brightspace

. In a new tab, open your Brightspace admin site to register the new Microsoft LTI app.
. Navigate to *Admin* > *Manage Extensibility* and select *LTI Advantage*.
. Select *Register App*.
. Register your app as *standard*.
. Enter a name for the app, like `OneDrive LTI`.
. Enter the domain of the URL where you registered the LTI app, like `+https://onedrivelti.microsoft.com+`.
. Using the details given in the Microsoft LTI Registration Portal, copy and paste the *Redirect URL*, *OpenID Connect Login URL*, and *Keyset URL* into Brightspace.
 .. Paste Microsoft's *Redirect URL* into Brightspace's *ToolOIDCLaunchRedirectUri* field.
 .. Paste Microsoft's *OpenID Connect Login URL* into Brightspace's *OIDCLoginInitiationUri* field.
 .. Paste Microsoft's *Keyset URL* in Brightspace's *ToolPublicJwksUri* field.
. Select the *Deep Linking* extension.
. Select *Register*.
. You'll be shown Brightspace registration details.
 .. Keep this page open in its own tab when completing the next set of steps.

==== Add Brightspace LTI registration details to the Microsoft LTI Registration Portal

After the app is registered in Brightspace, copy values from Brightspace's registration portal into Microsoft's LTI registration portal.

. Navigate back your open tab of Microsoft's *Register LTI 1.3 App* page.
. Copy Brightspace registration details and paste them into Microsoft's LTI Registration Portal.
 .. Paste Brightspace's *Issuer* into Microsoft's *LTI Issuer* field.
 .. Paste Brightspace's *OpenID Connect Authentication Endpoint* into Microsoft's *LTI Authorize URL* field.
 .. Paste Brightspace's *Brightspace Keyset URL* into Microsoft's *LTI Public Jwks URL* field.
 .. Paste Brightspace's *Brightspace OAuth2 Access Token URL* into Microsoft's *LTI Access Token URL* field.
 .. Paste Brightspace's *Client ID* into Microsoft's *LTI Client ID* field.
. Select the *Next* button.
. Select the *Save* button.
. A message saying _LTI consumer was created successfully._ will appear.
. Review your registration details by selecting the *View LTI Tenants* button on the home page.

=== Step 2: Deploy the LTI app in users' Brightspace experience

After Microsoft OneDrive LTI and Brightspace are connected, you need to deploy the OneDrive LTI app in users' Brightspace experience.

. Sign into your Brightspace admin site.
. Select the LTI app that you created.
. Enter in a deployment a name.
. Select all security settings except *Classlist* and *Anonymous*.
. Don't set configuration settings.
. Select *Create Deployment*.
. Choose the org units you want to use the new LTI app.
You can select the root org to include everyone or select individual org units.

==== Create links to the OneDrive LTI app in users' Brightspace experience

. Sign into your Brightspace admin site.
. Select the Brightspace OneDrive LTI app you created.
Deployment details will appear.
. Select *View Links*.
. Select *Create a link*.
. Enter in a name for the link.
. Paste the *Redirect URL* into the *URL* field.
. Set the *Type* to *Deep Linking Quicklink*.
. Select the *Save and Close* button.

The OneDrive LTI app will now show up in *Add Existing Content* and *QuickLinks* in Brightspace.
The link will show a generic _link_ icon rather than a OneDrive _cloud_ icon.
Also, the title will reflect the name provided in the app's LTI link settings.

=== Step 3: Turn off the older OneDrive app

The OneDrive LTI app is now available to users, but the older OneDrive app must now be turned off.

. Sign in to your Brightspace admin portal.
. Navigate to *Admin* > *Config Variable Browser*
. Locate the variable titled *d2l.3rdParty.OneDrive.EnableOneDrivePicker* and set the value to *off*.

=== Step 4: Turn on the new OneDrive LTI app on the Quicklinks activity bar (optional)

To add the OneDrive LTI app to Brightspace's activity bar, set an org unit *Config Variable* to the *link ID* of the LTI app.

You'll need to repeat these steps for every org ID (or parent org ID) where you want the OneDrive LTI app to appear in the activity bar.

==== Collect the Link IDs

. Sign in to your Brightspace admin portal.
. Navigate to *Admin* > *External Learning Tools* > *LTI Advantage Deployments* > *View Links* at the bottom of the page.
. Navigate to the correct link, and then move your mouse to the URL at the top of the browser.
 .. For example, `+https://example.desire2learn.com/d2l/le/ltiadvantage/deployments/3bfcc0b7-2fb6-4ffe-b353-95b520d4bae6/links/details/25988+`.
. Copy the digits after the final `/` in the URL.
 .. For example, using the URL above, copy `25988`.

==== Update the Config Variables

. In the Brightspace admin portal, navigate to *Admin* > *Config Variable Browser*.
. Locate the variable titled *3rdparty.microsoft.onedriveLTI.linkId*, and paste the copied URL to the *link ID* field for the org units where OneDrive LTI should appear.
 .. This value is a number.

=== Common questions concerning the OneDrive LTI app

==== Does the new OneDrive LTI FilePicker support personal accounts?

Yes, personal accounts are allowed to open OneDrive to upload the files.
There's a checkbox in the app in the OneDrive LTI registration portal to allow multiple accounts or not.
If checked, personal accounts are allowed.

==== Does the FilePicker support multiple languages?

The OneDrive LTI FilePicker looks at the LTI language setting parameter passed from the LMS, and (as backup) the browser setting (since the former is an optional claim) to determine the language to use.
