= Integrate Microsoft Teams classes and meetings with Moodle
:audience: admin
:author: DaniEASmith
:description: Create and manage Teams classes and meetings with Microsoft OneDrive Learning Tools Interoperability for Moodle.
:f1.keywords: ["CSH"]
:manager: serdars
:ms.author: danismith
:ms.collection: M365-modern-desktop
:ms.localizationpriority: medium
:ms.reviewer: amitman
:ms.service: o365-administration
:ms.topic: article

== Integrate Microsoft Teams classes and meetings within Moodle

This guide provides the IT admin steps for registering both Teams Classes and Teams Meetings LTI apps on Moodle.

For details on managing all LTI apps for any LMS, see xref:manage-microsoft-one-lti.adoc[Manage Microsoft LMS Gateway for any LMS].

=== Prerequisites before set up

For the integration between Moodle and Teams to function correctly, Moodle and Teams must be set up to communicate with one another.

Follow the xref:moodle-plugin-configuration.adoc[instructions for installing and configuring the Moodle plugin].

=== Register Microsoft Teams LTI for use in Moodle

The person who performs this integration should be a Moodle administrator and a Microsoft 365 tenant administrator.

. Visit https://lti.microsoft.com/[Microsoft LMS Gateway] and select the *Go to registration portal* button.
. Sign in with a Microsoft 365 administrator account.
. After signing in, select *Add new registration*.
. Select either *Teams Meetings LTI* or *Teams Classes LTI* to register and then select *Next*.
. Enter in an easily identifiable *Registration* name and select *Moodle* as the LMS platform.
Select *Next*.
. You'll be given a list of keys that need to be added to your Moodle site.
. Open Moodle in another tab.
Don't close the Microsoft LMS Gateway tab.
. In Moodle, go to *Site administration* > *Plugins* > *Activity modules* > *External tools* > *Manage tools*.
. On the *Manage tools* page, select *configure a tool manually*.
. Under *Tool settings*, enter in a *Tool name* like *Microsoft Teams Classes*.
For *LTI version*, select *LTI 1.3*.
For *Public key type*, select *Keyset URL*.
. Next, copy the keys from *Microsoft LTI keys* to the corresponding tools inputs.
 .. Microsoft's *Target link URL* key goes into Moodle's *Tool URL* field.
 .. Microsoft's *Open ID connection URL* key goes into Moodle's *Initiate login URL* field.
 .. Microsoft's *Redirect URL* key goes into Moodle's *Redirection URI(s)* field.
. Select *Save changes*.
. The new tool should now appear in the *Tools* section of Moodle's *Manage tools* page.
Select the list icon to view *Tool configuration details*.
. Go back to the Microsoft LMS Gateway tab.
Select *Next* to go to the *LMS provided registration keys* step.
. Copy and paste the values from Moodle's *Tool configuration details* to Microsoft's *LMS provided registration keys* step.
+
Paste the values as follows:
+
|===
| On Moodle | On Microsoft LTI registration portal

| Platform ID
| Issuer ID URL

| Client ID
| Client ID

| Deployment ID
| Deployment ID

| Public keyset URL
| Keyset URL

| Access token URL
| Access token URL

| Authentication request URL
| Platform authentication URL
|===
+
____
[!NOTE] Make sure that the public keyset URL isn't restricted by your network settings for requests originating from the Microsoft LMS Gateway.
____
+
Select *Next*.

. Review the *Review and add* page.
If there are no errors, select *Save and exit*.
You should see a message indicating successful registration.

You've completed registration of either the Teams Classes or Teams Meetings LTI app.

If you would like to add the other app too, repeat the steps above, selecting the other Teams LTI app in step 4.

==== Add Teams LTI apps to educators' Moodle courses

After registering Teams LTI apps, educators can add the Teams Classes app and the Teams Meetings app to their Moodle courses.

* https://support.microsoft.com/topic/use-microsoft-teams-classes-in-your-lms-ac6a1e34-32f7-45e6-b83e-094185a1e78a[Educator instructions on adding the Teams Classes app].
* https://support.microsoft.com/topic/use-microsoft-teams-meetings-in-your-lms-11b6095d-f90b-42b9-ab77-4dcff2bb3b76[Educator instructions on adding the Teams Meetings app].

=== Technical requirements to launch Teams LTI apps

To launch the Teams LTI apps within Moodle, there are a few technical requirements that need to be met.

____
[!NOTE] IT admins and educators can register LTI apps on the LTI apps registration portal.
____

==== IT admin technical requirements

* Use Moodle version 3.10 or above.
* Download the latest Microsoft O365 plugin for Moodle version 3.10 or above.
* Access the LTI apps registration portal to register the LTI apps.
 ** Registration must be on completed on a desktop device.
* Download the latest version of Microsoft Edge, Google Chrome, Safari, or Mozilla Firefox.

==== Educator technical requirements

* Access the LTI apps registration portal to register the LTI apps, if the IT admin hasn't registered the apps.
 ** Registration must be on completed on a desktop device.
* Download the latest version of Microsoft Edge, Google Chrome, Safari, or Mozilla Firefox.
* <<add-teams-lti-apps-to-educators-moodle-courses,Teams LTI apps for Classes and Meetings in Moodle>>.

==== Student technical requirements

* Teams LTI apps for Classes and Meetings in Moodle.
 ** Students don't need to take any actions to add the Teams Classes or Meetings LTI apps.
