= 
cmcatee-MSFT

== Cancel your Microsoft business subscription

This article only applies to canceling *Dynamics 365*, *Intune*, *Power
Platform*, *Windows 365*, and *Microsoft 365 for business*
subscriptions. If you have Microsoft 365 Family or Personal, see
https://support.microsoft.com/office/cancel-a-microsoft-365-subscription-46e2634c-c64b-4c65-94b9-2cc9c960e91b?OCID=M365_DocsCancel_Link[Cancel
a Microsoft 365 subscription].

____
[!WARNING] Before you cancel a subscription, make sure your users
link:#save-your-data[save their data].
____

*In this article:*

link:#before-you-begin[Before you begin] +
link:#whats-the-easiest-way-to-cancel[What’s the easiest way to
cancel?] +
link:#how-do-i-cancel-my-free-trial[How do I cancel my free trial?] +
link:#what-if-i-bought-my-subscription-through-a-partner[What if I
bought my subscription through a partner?] +
link:#determine-your-cancellation-options[Determine your cancellation
options] +
link:#steps-to-cancel-your-subscription[Steps to cancel your
subscription] +
link:#save-your-data[Save your data] +
link:#next-steps[Next steps] +
link:#related-content[Related content]

=== Before you begin

* You must be a Global or Billing admin to do the tasks in this article.
For more information, see
link:../../admin/add-users/about-admin-roles.md[About admin roles].
* If you added your own domain name to use with your subscription, you
must link:../../admin/get-help-with-domains/remove-a-domain.md[remove
the domain] before you cancel your subscription.
* If you have a domain subscription, to prevent any other charges for
that subscription, link:renew-your-subscription.md[turn off recurring
billing].

=== What’s the easiest way to cancel?

The easiest way to cancel your subscription is to
link:renew-your-subscription.md#turn-recurring-billing-off-or-on[turn
off recurring billing]. When you turn off recurring billing, you can
continue to use your subscription until it expires at the end of the
subscription term. If you want to cancel immediately, use the
information and steps in this article to do that.

=== How do I cancel my free trial?

You can cancel your free trial at any time to stop future charges. To
cancel a free trial,
link:renew-your-subscription.md#turn-recurring-billing-off-or-on[turn
off recurring billing]. If you don’t turn off recurring billing, after
your one month free trial ends, you’re charged the applicable
subscription fee. If your trial subscription doesn’t have a payment
method associated with it, you can just let it expire at the end of the
trial period, and you won’t be charged.

=== What if I bought my subscription through a partner?

If you bought your subscription through a Microsoft representative or a
reseller partner, you have seven days to cancel for a pro-rated refund.
Contact your seller or partner to help you cancel your subscription.
link:../manage-partners.md#what-can-a-partner-do-for-my-organization-or-school[Learn
more about partners].

If your organization is in Chile, and you bought your subscription
through a partner in Chile, you have 10 days to cancel for a prorated
refund.

=== Determine your cancellation options

____
[!IMPORTANT] Before you continue,
link:../billing-and-payments/manage-billing-profiles.md#view-my-billing-profiles[determine
if you have a billing profile].
____

==== If you have a billing profile

You can only cancel and receive a prorated credit or refund if you
cancel within seven days after the start or renewal of your
subscription. If you cancel during this limited time window, the
prorated amount is either credited towards your next invoice or returned
to you in the next billing cycle.

If you need to cancel within seven days after the start or renewal of
your subscription, go to link:#steps-to-cancel-your-subscription[Steps
to cancel your subscription] later in this article.

If more than seven days have passed,
link:renew-your-subscription.md[turn off recurring billing]. Turning off
recurring billing prevents your subscription from renewing at the end of
its term. You keep access to your products and services for the
remainder of your subscription. If you have an annual subscription and
are paying monthly, you’re charged each month for the remainder of your
subscription term.

==== If you don’t have a billing profile

If you cancel after you start or renew your subscription, you receive a
prorated credit or refund. The amount is either credited towards your
next invoice or returned to you in the next billing cycle.

The steps to cancel your trial or paid subscription depend on the number
of licenses in your subscription. The following table explains what
steps you can take, based on the number of licenses in your
subscription.

[width="100%",cols="50%,50%",options="header",]
|===
|If your subscription has |You can
|25 or fewer licenses |link:#steps-to-cancel-your-subscription[Use the
steps below to cancel] your trial or paid subscription online in the
Microsoft 365 admin center.

|More than 25 licenses |Reduce the number of licenses to 25 or fewer and
then link:#steps-to-cancel-your-subscription[use the steps below to
cancel].
|===

If you can’t reduce the number of licenses,
link:renew-your-subscription.md[turn off recurring billing]. Turning off
recurring billing prevents you from being charged again for your
subscription, and lets you keep your access to your products and
services for the remainder of your subscription.

If you’re unable to cancel your subscription,
link:../../admin/get-help-support.md[contact support] for help.

=== Steps to cancel your subscription

____
[!NOTE] If you have multiple subscriptions to the same product, such as
Microsoft 365 Business Premium, canceling one subscription won’t impact
the licenses or services that you bought inside inside the other
subscriptions.
____

::: moniker range=``o365-worldwide''

[arabic]
. In the Microsoft 365 admin center, go to the *Billing* > Your products
page.

::: moniker-end

::: moniker range=``o365-21vianet''

[arabic]
. In the admin center, go to the *Billing* > Your products page.

::: moniker-end

[arabic, start=2]
. Find the subscription that you want to cancel. Select the three dots
(more actions), then select *Cancel subscription*.
. In the *Cancel subscription* pane, choose a reason why you’re
canceling. Optionally, provide any feedback.
. Select *Save*.

Your subscription now appears in a *Disabled* state, and has reduced
functionality until it’s deleted. For information about what you can
expect when you cancel a paid Microsoft 365 for business subscription,
see link:what-if-my-subscription-expires.md[What happens to my data and
access when my Microsoft 365 for business subscription ends?]

____
[!WARNING] If you explicitly delete a subscription, it skips the
*Expired* and *Disabled* states and the SharePoint Online data and
content, including OneDrive content, is deleted immediately.
____

=== Save your data

When the cancellation becomes effective, your users lose access to their
data. Before you cancel the subscription, have them save their OneDrive
for Business or SharePoint Online files to another location. Any
customer data that you leave behind might be deleted after 30 days, and
is deleted no later than 180 days after cancellation.

* To move email, contacts, tasks, and calendar information to another
account, see
https://support.microsoft.com/office/14252b52-3075-4e9b-be4e-ff9ef1068f91[Export
or backup email&#44; contacts&#44; and calendar to an Outlook .pst file].
* To save a document library or list content (such as contacts) from a
SharePoint Online environment (OneDrive for Business or team sites) to
file shares or to a local computer, see
link:/sharepoint/troubleshoot/migration-tool/content-manual-migration[Information
about manual migration of SharePoint Online content].

=== Next steps

==== Uninstall Office (optional)

If you canceled your subscription, and didn’t
link:move-users-different-subscription.md[move users to a different
subscription] that includes Microsoft 365, Microsoft 365 runs in reduced
functionality mode. When this happens, users can only read and print
documents, and Microsoft 365 applications display
https://support.microsoft.com/office/0d23d3c0-c19c-4b2f-9845-5344fedc4380[Unlicensed
Product notifications]. To avoid any confusion, have your users
https://support.microsoft.com/office/9dd49b83-264a-477a-8fcc-2fdf5dbf61d8[uninstall
Office] from their machines.

==== Close your account (optional)

If you want to completely close your account with Microsoft, see
link:../close-your-account.md[Close your account].

=== Related content

link:renew-your-subscription.md[Renew your subscription] (article) +
link:reactivate-your-subscription.md[Reactivate your subscription]
(article) +
link:move-users-different-subscription.md[Move users to a different
subscription] (article)
