= Cancel your business subscription
:audience: Admin
:author: cmcatee-MSFT
:description: Learn how to cancel your Dynamics 365, Intune, Power Platform, and Microsoft 365 for business trial or paid subscriptions in the Microsoft 365 admin center.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.author: cmcatee
:ms.collection: ["highpri", "M365-subscription-management", "Adm_O365"]
:ms.custom: ["commerce_subscriptions", "VSBFY23", "AdminSurgePortfolio", "AdminTemplateSet", "admindeeplinkMAC"]
:ms.date: 07/07/2022
:ms.localizationpriority: high
:ms.reviewer: jkinma, jmueller
:ms.service: o365-administration
:ms.topic: article
:search.appverid: MET150

== Cancel your Microsoft subscription

If you want to cancel your subscription, the easiest way to do that is to xref:renew-your-subscription.adoc[turn off recurring billing].
When you turn off recurring billing, you can continue to use your subscription until it expires at the end of the subscription term.
If you want to cancel immediately, use the information and steps in this article to do that.

You can cancel your free trial at any time to stop future charges.
After your 1-month free trial ends, you will be charged the applicable subscription fee.

____
[!IMPORTANT]

* This article only applies to Dynamics 365, Intune, Power Platform, Windows 365, and Microsoft 365 for business subscriptions.
If you have Microsoft 365 Family or Personal, see https://support.microsoft.com/office/cancel-a-microsoft-365-subscription-46e2634c-c64b-4c65-94b9-2cc9c960e91b?OCID=M365_DocsCancel_Link[Cancel a Microsoft 365 subscription].
* If you bought your subscription through a Microsoft representative or a reseller partner, you have seven days to cancel for a pro-rated refund.
Contact your seller or partner to help you cancel your subscription.
link:../manage-partners.md#what-can-a-partner-do-for-my-organization-or-school[Learn more about partners].
* If your organization is located in Chile, and you bought your subscription through a partner in Chile, you have 10 days to cancel for a pro-rated refund.
____

=== Before you begin

* You must be a Global or Billing admin to do the tasks in this article.
For more information, see xref:../../admin/add-users/about-admin-roles.adoc[About admin roles].
* Before you cancel a subscription, make sure your users <<save-your-data,save their data>>.
* If you added your own domain name to use with your subscription, you must xref:../../admin/get-help-with-domains/remove-a-domain.adoc[remove the domain] before you cancel your subscription.
* If you have a domain subscription, to prevent any other charges for that subscription, xref:renew-your-subscription.adoc[turn off recurring billing].

=== Determine your cancellation options

____
[!IMPORTANT] Before you continue, link:../billing-and-payments/manage-billing-profiles.md#view-my-billing-profiles[determine if you have a billing profile].
____

==== If you have a billing profile

You can only cancel and receive a prorated credit or refund if you cancel within seven days after the start or renewal of your subscription.
If you cancel during this limited time window, the prorated amount is either credited towards your next invoice or returned to you in the next billing cycle.

If you need to cancel within seven days after the start or renewal of your subscription, go to <<steps-to-cancel-your-subscription,Steps to cancel your subscription>> later in this article.

If more than seven days have passed, xref:renew-your-subscription.adoc[turn off recurring billing].
This prevents your subscription from renewing at the end of its term.
You keep access to your products and services for the remainder of your subscription.
If you have an annual subscription and are paying monthly, you are charged each month for the remainder of your subscription term.

==== If you don't have a billing profile

If you cancel after you start or renew your subscription, you receive a prorated credit or refund.
The amount is either credited towards your next invoice or returned to you in the next billing cycle.

The steps to cancel your trial or paid subscription depend on the number of licenses in your subscription.
The following table explains what steps you can take, based on your number of licenses.

|===
| If your subscription has | You can

| 25 or fewer licenses
| <<steps-to-cancel-your-subscription,Use the steps below to cancel>> your trial or paid subscription online in the https://go.microsoft.com/fwlink/p/?linkid=2024339[Microsoft 365 admin center].

| More than 25 licenses
| Reduce the number of licenses to 25 or fewer and then <<steps-to-cancel-your-subscription,use the steps below to cancel>>.
|===

If you can't reduce the number of licenses, xref:renew-your-subscription.adoc[turn off recurring billing].
This prevents you from being charged again for your subscription, and lets you keep your access to your products and services for the remainder of your subscription.

If you're unable to cancel your subscription, xref:../../admin/get-help-support.adoc[contact support] for help.

=== Steps to cancel your subscription

____
[!NOTE] If you have multiple subscriptions to the same product, such as Microsoft 365 Business Premium, canceling one subscription won't impact the purchased licenses or services inside the others.
____

::: moniker range="o365-worldwide"

. In the Microsoft 365 admin center, go to the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=842054[Your products] page.

::: moniker-end

::: moniker range="o365-21vianet"

. In the admin center, go to the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=850626[Your products] page.

::: moniker-end

. Find the subscription that you want to cancel.
Select the three dots (more actions), then select *Cancel subscription*.
. In the *Cancel subscription* pane, choose a reason why you're canceling.
Optionally, provide any feedback.
. Select *Save*.

Your subscription now appears in a *Disabled* state, and has reduced functionality until it's deleted.
For more information about what you can expect when a paid Microsoft 365 for business subscription is canceled, see xref:what-if-my-subscription-expires.adoc[What happens to my data and access when my Microsoft 365 for business subscription ends?]

____
[!IMPORTANT] If you explicitly delete a subscription, then it skips the *Expired* and *Disabled* states and the SharePoint Online data and content, including OneDrive, is deleted immediately.
____

=== Save your data

When the cancellation becomes effective, your users lose access to their data.
Before you cancel the subscription, have them save their OneDrive for Business or SharePoint Online files to another location.
Any customer data that you leave behind might be deleted after 30 days, and is deleted no later than 180 days after cancellation.

* To move email, contacts, tasks, and calendar information to another account, see https://support.microsoft.com/office/14252b52-3075-4e9b-be4e-ff9ef1068f91[Export or backup email, contacts, and calendar to an Outlook .pst file].
* To save a document library or list content (such as contacts) from a SharePoint Online environment (OneDrive for Business or team sites) to file shares or to a local computer, see link:/sharepoint/troubleshoot/migration-tool/content-manual-migration[Information about manual migration of SharePoint Online content].

=== Next steps

==== Uninstall Office (optional)

If you canceled your subscription, and didn't xref:move-users-different-subscription.adoc[move users to a different subscription] that includes Microsoft 365, Microsoft 365 runs in reduced functionality mode.
When this happens, users can only read and print documents, and Microsoft 365 applications display https://support.microsoft.com/office/0d23d3c0-c19c-4b2f-9845-5344fedc4380[Unlicensed Product notifications].
To avoid any confusion, have your users https://support.microsoft.com/office/9dd49b83-264a-477a-8fcc-2fdf5dbf61d8[uninstall Office] from their machines.

==== Close your account (optional)

If you want to completely close your account with Microsoft, see xref:../close-your-account.adoc[Close your account].

=== Related content

xref:renew-your-subscription.adoc[Renew your subscription] (article) + xref:reactivate-your-subscription.adoc[Reactivate your subscription] (article) + xref:move-users-different-subscription.adoc[Move users to a different subscription] (article)
