= Manage self-service purchases (Admins)
:audience: Admin
:author: cmcatee-MSFT
:description: Admins can learn how to manage self-service purchases made by users in their organization.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.author: cmcatee
:ms.collection: ["M365-subscription-management", "Adm_O365"]
:ms.custom: ["commerce_ssp", "AdminSurgePortfolio", "okr_smb"]
:ms.date: 05/24/2022
:ms.localizationpriority: medium
:ms.reviewer: prlachhw, pablom
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["MET150"]

== Manage self-service purchases (Admin)

As an admin, you can see self-service purchases made by people in your organization.
You see the product name, purchaser name, subscriptions purchased, expiration date, purchase price, and assigned users for each self-service purchase.
If required by your organization, you can turn off self-service purchasing on a per product basis via PowerShell.
You have the same data management and access policies over products bought through self-service purchase or centrally.

You can also control whether users in your organization can make self-service purchases.
For more information, see xref:allowselfservicepurchase-powershell.adoc[Use AllowSelfServicePurchase for the MSCommerce PowerShell module].

=== View self-service subscriptions

::: moniker range="o365-worldwide"

. In the admin center, go to the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=842054[Your products] page.

::: moniker-end

::: moniker range="o365-21vianet"

. In the admin center, go to the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=850626[Your products] page.
::: moniker-end
. On the *Products* tab, select the filter icon, then select *Self-service*.
. To view more details about a subscription, choose one from the list.

=== View who has licenses for a self-service purchase subscription

____
[!NOTE] As an admin, you can't assign or unassign licenses for a self-service purchase subscription bought by a user in your organization.
You can <<take-over-a-self-service-purchase-subscription,take over a self-service purchase subscription>>, and then assign or unassign licenses.
____

::: moniker range="o365-worldwide"

. In the admin center, go to the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=842264[Licenses] page.

::: moniker-end

::: moniker range="o365-21vianet"

. In the admin center, go to the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=850625[Licenses] page.

::: moniker-end

. Select the filter icon, then choose *Self-service*.
. Select a product to see licenses assigned to people.
+
____
[!NOTE] If there are multiple purchases for a product, that product is only listed once, and the *Available quantity* column shows the total of all subscriptions bought for that product.
____

. The *Users* list is grouped by the names of people who made self-service purchases.
. To export a list of users with licenses for these subscriptions, choose the subscriptions that you want to export, then choose *Export users*.

=== Disable or enable self-service purchases

You can disable or enable self-service purchases for users in your organization.
The *MSCommerce* PowerShell module includes a *PolicyID* parameter value for *AllowSelfServicePurchase* that lets you control whether users in your organization can make self-service purchases, and for which products.

You can use the *MSCommerce* PowerShell module to:

* View the default state of the *AllowSelfServicePurchase* parameter value--whether it's enabled or disabled by product
* View a list of applicable products and whether self-service purchase is enabled or disabled
* View or modify the current setting for a specific product to either enable or disable it

____
[!IMPORTANT] When you use the *AllowSelfServicePurchase* policy, it enables or disables both self-service purchases and self-service trials.
For a list of the products available for self-service purchase, see link:allowselfservicepurchase-powershell.md#view-a-list-of-self-service-purchase-products-and-their-status[View a list of self-service purchase products and their status].
Only Project and Visio are available for trial subscriptions.
____

For more information, see xref:allowselfservicepurchase-powershell.adoc[Use AllowSelfServicePurchase for the MSCommerce PowerShell module].

=== Centralize licenses under a single subscription

You can assign existing licenses or purchase additional subscriptions through existing agreements for users assigned to self-service purchases.
After you assign these centrally purchased licenses, you can request that purchasers cancel their existing subscriptions.

::: moniker range="o365-worldwide"

. In the admin center go to the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=868433[Purchase services] page.

::: moniker-end

::: moniker range="o365-21vianet"

. In the https://go.microsoft.com/fwlink/p/?linkid=850627[admin center], go to the *Billing* > *Purchase services* page.

::: moniker-end

. Find and choose the product that you want to buy, then choose *Buy*.
. Complete the remaining steps to complete your purchase.
. Follow the steps in <<view-who-has-licenses-for-a-self-service-purchase-subscription,View who has licenses for a self-service purchased subscription>> to export a list of users to reference in the next step.
. Assign licenses to everyone who has a license in the other subscription.
For full steps, see xref:../../admin/manage/assign-licenses-to-users.adoc[Assign licenses to users].
. Contact the person who bought the self-service purchase subscription and ask them to link:manage-self-service-purchases-users.md#cancel-a-subscription[cancel it].

=== Take over a self-service purchase subscription

You can take over a self-service purchase subscription made by a user in your organization.
When you take over a self-service purchase subscription, you have two options:

. Move the users to a different subscription and cancel the original subscription.
. Cancel the self-service purchase subscription and remove licenses from assigned users.

==== Move users to a different subscription

When you move users to a different subscription, the old subscription is automatically canceled.
The user who originally bought the self-service purchase subscription receives an email that says the subscription was canceled.

____
[!NOTE] You must have an available license for each user you're moving in the subscription that you're moving users to.
____

::: moniker range="o365-worldwide"

. In the admin center, go to the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=842054[Your products] page.

::: moniker-end

::: moniker range="o365-21vianet"

. In the https://go.microsoft.com/fwlink/p/?linkid=850627[admin center], go to the *Billing* > *Your products* page.

::: moniker-end

. On the *Products* tab, select the filter icon, then select *Self-service*.
. Select the subscription that you want to take over.
. On the subscription details page, in the *Subscriptions and settings* section, select *Take control of this subscription*.
. In the right pane, select *Move users*.
. Select the product that you want to move the users to, then select *Move users*.
. In the *Move users to* box, select *Move users*.
The move process might take several minutes.
Don't close your browser while the process runs.
. When the move process is finished, close the *Move completed pane*.
. On the subscription details page, the *Subscription status* for the self-service purchased subscription shows as *Deleted*.

==== Cancel a self-service purchase subscription

When you choose to cancel a self-service purchase subscription, users with licenses lose access to the product.
The user who originally bought the self-service purchase subscription receives an email that says the subscription was canceled.

::: moniker range="o365-worldwide"

. In the admin center, go to the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=842054[Your products] page.

::: moniker-end

::: moniker range="o365-21vianet"

. In the https://go.microsoft.com/fwlink/p/?linkid=850627[admin center], go to the *Billing* > *Your products* page.

::: moniker-end

. On the *Products* tab, select the filter icon, then select *Self-service*.
. Select the subscription that you want to cancel.
. On the subscription details page, in the *Subscriptions and settings* section, select *Take control of this subscription*.
. In the right pane, select *Cancel subscription*.
. Select a reason for your cancellation from the drop-down list, then select *Cancel subscription*.
. In the *Are you sure you want to cancel?* box, select *Cancel subscription*.
. Close the right pane.
. On the subscription details page, the *Subscription status* shows as *Deleted*.

=== Need help? Contact us.

For common questions about self-service purchases, see link:self-service-purchase-faq.yml[Self-service purchases FAQ].

If you have questions or need help with self-service purchases, xref:../../admin/get-help-support.adoc[contact support].
