= 
cmcatee-MSFT

== Verify academic eligibility for Microsoft 365 Education subscriptions

If you’re part of an academic institution, you can sign up for a free
trial of Microsoft 365 Education. After Microsoft verifies the academic
eligibility of your school, you can buy Microsoft 365 products at
academic prices. This includes products that are available for free,
like Office 365 A1 for faculty and Office 365 A1 for students. You have
until the end of the free trial to convert it to a paid subscription at
academic prices.

This article describes how to verify your school’s academic eligibility,
check the eligibility status, and buy subscriptions at academic prices
after your school is approved.

=== Before you begin

You must already have a Microsoft 365 Education trial subscription. If
you don’t have a trial subscription,
https://www.microsoft.com/microsoft-365/academic/compare-office-365-education-plans?activetab=tab%3aprimaryr1[visit
this webpage] and select *Get started for free*.

=== Verify that you have a trial subscription

If you’re not sure if you have a Microsoft 365 Education trial
subscription, use these steps to verify that you do.

[arabic]
. In the Microsoft 365 admin center, go to the *Billing* > Your products
page.
. Look for *Office 365 A1 for faculty Trial* and *Office 365 A1 for
students Trial*. If you don’t find these subscriptions,
https://www.microsoft.com/microsoft-365/academic/compare-office-365-education-plans?activetab=tab%3aprimaryr1[visit
this webpage] and select *Get started for free*.

=== Verify your school’s academic eligibility

In most cases, when you sign up for a free trial and complete the
eligibility verification wizard to provide your school’s domain, you
receive an immediate approval or denial of your school’s eligibility. In
some cases, we require more information to complete a manual eligibility
review and will reach out to you with a questionnaire to complete. This
review can take up to 10 business days. After we review your school’s
eligibility information, we send an email that notifies you of your
school’s status.

You can close the academic verification wizard before entering a domain
and start using the trial subscription right away. However, you aren’t
eligible for academic prices until you complete the verification
process. You must complete the process before the end of your free trial
to convert to a paid subscription and continue to use it. This also
applies when you convert to the free A1 subscription.

____
[!IMPORTANT] If you exited the verification wizard before entering a
domain, you can https://go.microsoft.com/fwlink/p/?linkid=2135255[resume
the academic verification wizard] at any time during your free trial.
____

If your academic eligibility is denied, see
link:#my-school-isnt-eligible-what-do-i-do-now[My school isn’t eligible.
What do I do now?]

=== Check the status of your school’s academic eligibility

After you have a Microsoft 365 Education trial, you can check the status
of your school’s academic eligibility at any time.

[arabic]
. Go to the Microsoft 365 admin center.
. On the home page, find the *Billing* card. +
The *Billing* card indicates the status of the verification process. The
card shows one of the following statuses: approved, pending, declined,
or add your domain.
+
____
[!NOTE] If you don’t see one of those statuses, it means that you don’t
have a Microsoft 365 Education trial subscription. To start a free
trial,
https://www.microsoft.com/microsoft-365/academic/compare-office-365-education-plans?activetab=tab%3aprimaryr1[visit
this webpage] and select *Get started for free*.
____

=== Buy subscriptions at academic prices

After your school’s eligibility is verified, you can buy subscriptions
at academic prices. You can also
link:../try-or-buy-microsoft-365.md[convert your free trial to a paid
subscription]. If you want to convert your trial subscription, you must
do so before the end of the trial period.

[arabic]
. In the Microsoft 365 admin center, go to the *Billing* > Purchase
services page.
. To view academic offers, select the *Education* tab.
+
____
[!NOTE] The *Education* tab isn’t displayed if your eligibility is
pending.
____
. When you find the offer you want to buy, select it, then select *Buy*.
. Complete the checkout process to buy the subscription.

=== When does my free trial end?

You can find the expiration date for your free trial subscription on the
*Your products* page. You can also extend the trial.

[arabic]
. In the Microsoft 365 admin center, go to the *Billing* > Your products
page.
. Find the trial subscription.
. In the *Billing* section, under *Free trial subscription*, the
expiration date is shown.
. If you want to extend the trial, select *Extend trial*. You can only
do this once per free trial subscription.

=== My school isn’t eligible. What do I do now?

If your school doesn’t qualify as a Microsoft Qualified Academic
Institution, you can still buy commercial offers in the admin center on
the *Billing* > Purchase services page. If your organization is a
nonprofit group, your group might be eligible for subscriptions for
non-profits. To learn more, see
https://www.microsoft.com/nonprofits/eligibility[Discounts and donations
for nonprofits].

If you have questions about your school’s academic eligibility decision,
link:../../admin/get-help-support.md[contact support].

=== Next steps

To learn how to deploy Microsoft 365 for your school, visit
link:/microsoft-365/education/deploy/[Microsoft 365 Education
documentation and resources]. Next, you can
link:../../admin/add-users/add-users.md[add users and assign licenses at
the same time]. If you need to, you can also
link:../licenses/buy-licenses.md[buy more licenses for your
subscription].

=== Related content

link:/education/itadmins[Microsoft 365 Education Documentation for IT
Admins] (article links) +
https://microsoft.com/education/products/teams/default.aspx[Microsoft
Teams for Education] (product page) +
link:../licenses/subscriptions-and-licenses.md[Understand subscriptions
and licenses in Microsoft 365 for business] (article) +
link:../../admin/manage/assign-licenses-to-users.md[Assign licenses to
users] (article) +
link:../licenses/buy-licenses.md[Buy or remove subscription licenses]
(article) +
link:move-users-different-subscription.md[Move users to a different
subscription] (article)
