= Assign licenses to users in the Microsoft 365 admin center
:audience: Admin
:author: cmcatee-MSFT
:description: Assign licenses depending on whether you want to assign product licenses to specific users or assign users licenses to a specific product.
:f1.keywords: ["CSH"]
:manager: scotv
:ms.author: cmcatee
:ms.collection: ["highpri", "M365-subscription-management", "Adm_O365", "Adm_TOC"]
:ms.custom: ["commerce_licensing", "VSBFY23", "AdminSurgePortfolio", "TopSMBIssues", "SaRA", "business_assist", "okr_SMB", "manage_licenses", "AdminTemplateSet"]
:ms.date: 07/12/2022
:ms.localizationpriority: high
:ms.reviewer: sinakassaw, nicholak
:ms.service: o365-administration
:ms.topic: article
:search.appverid: MET150

== Assign Microsoft 365 licenses to users

You can assign licenses to users on either the *Active users* page, or on the *Licenses* page.
The method you use depends on whether you want to assign product licenses to specific users or assign users licenses to a specific product.

____
[!NOTE]

* As an admin, you can't assign or unassign licenses for a self-service purchase subscription bought by a user in your organization.
You can link:../../commerce/subscriptions/manage-self-service-purchases-admins.md#take-over-a-self-service-purchase-subscription[take over a self-service purchase subscription], and then assign or unassign licenses.
* For some subscriptions, you can only cancel during a limited window of time after you buy or renew your subscription.
If the cancellation window has passed, turn off recurring billing to cancel the subscription at the end of its term.
____

xref:../add-users/add-users.adoc[Learn how to add a user and assign a license at the same time].

____
[!TIP] If you need help with the steps in this topic, consider https://go.microsoft.com/fwlink/?linkid=2186871[working with a Microsoft small business specialist].
With Business Assist, you and your employees get around-the-clock access to small business specialists as you grow your business, from onboarding to everyday use.
____

=== Before you begin

* You must be a Global, License, or User admin to assign licenses.
For more information, see xref:../add-users/about-admin-roles.adoc[About Microsoft 365 admin roles].
* You can xref:../../enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.adoc[assign Microsoft 365 licenses to user accounts with PowerShell].
* To use group-based licensing, see link:/azure/active-directory/users-groups-roles/licensing-groups-assign[Assign licenses to users by group membership in Azure Active Directory]
* Some services, like Sway, are automatically assigned to users, and don't need to be assigned individually.

=== Use the Licenses page to assign licenses to users

The *Licenses* page lets you assign or unassign licenses for up to 20 users at a time.
The page shows the products you own, the number of available licenses for each product, and the number of assigned licenses out of the total licenses available.

The *Licenses* page shows an aggregate total of licenses for all subscriptions for the same product name.
For example, you might have one subscription for Microsoft 365 Business Premium that has 5 licenses, and another subscription that has 8 licenses for the same product.
The *Licenses* page shows that you have a total of 13 licenses for Microsoft 365 Business Premium across all your subscriptions.
This is different from what you see on the *Your products* page, which displays a row for each subscription you own, even if they are for the same product.

::: moniker range="o365-worldwide"

. In the admin center, go to the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=842264[Licenses] page.

::: moniker-end

::: moniker range="o365-21vianet"

. In the admin center, go to the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=850625[Licenses] page.

::: moniker-end

. Select a product.
. On the product details page, select *Assign licenses*.
. In the *Assign licenses to users* pane, begin typing a name, and then choose it from the results to add it to the list.
You can add up to 20 users at a time.
. Select *Turn apps and services on or off* to assign or remove access to specific items.
. When you're finished, select *Assign*, then close the right pane.

If there's a conflict, you see a message that tells you what the problem is, and how to fix it.
For example, if you selected licenses that contain conflicting services, the error message says to review the services included with each license and try again.

=== Change the apps and services a user has access to

::: moniker range="o365-worldwide"

. In the admin center, go to the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=842264[Licenses] page.

::: moniker-end

::: moniker range="o365-21vianet"

. In the admin center, go to the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=850625[Licenses] page.

::: moniker-end

. On the *Licenses* page, select the row for a specific user.
. In the right pane, select or deselect the apps and services that you want to give access to or remove access from.
. When you're finished, select *Save*, then select *Close*.

=== Use the Active users page to assign licenses

When you use the *Active users* page to assign licenses, you assign users licenses to products.

==== Assign licenses to multiple users

::: moniker range="o365-worldwide"

. In the admin center, go to the *Users* > https://go.microsoft.com/fwlink/p/?linkid=834822[Active users] page.

::: moniker-end

::: moniker range="o365-21vianet"

. In the admin center, go to the *Users* > https://go.microsoft.com/fwlink/p/?linkid=850628[Active users] page.

::: moniker-end

. Select the circles next to the names of the users that you want to assign licenses to.
. At the top, select *Manage product licenses*.
. In the *Manage product licenses* pane, select *Assign more: Keep the existing licenses and assign more* > *Next*.
. Under *Licenses*, select the box for the license(s) that you want the selected users to have.
+  By default, all services associated with those licenses are automatically assigned to the users.
You can limit which services are available to the users.
Deselect the boxes for the services that you don't want the users to have.
. At the bottom of the pane, select *Save changes*.
+  You might have to buy additional licenses if you don't have enough licenses for everyone.

____
[!NOTE] If you want to assign licenses for a large number of users, use link:/azure/active-directory/enterprise-users/licensing-groups-assign[Assign licenses to users by group membership in Azure Active Directory]
____

==== Assign licenses to one user

::: moniker range="o365-worldwide"

. In the admin center, go to the *Users* > https://go.microsoft.com/fwlink/p/?linkid=834822[Active users] page.

::: moniker-end

::: moniker range="o365-21vianet"

. In the admin center, go to the *Users* > https://go.microsoft.com/fwlink/p/?linkid=850628[Active users] page.

::: moniker-end

. Select the row of the user that you want to assign a license to.
. In the right pane, select *Licenses and Apps*.
. Expand the *Licenses* section, select the boxes for the licenses that you want to assign, then select *Save changes*.

=== Assign a license to a guest user

You can invite guest users to collaborate with your organization in the Azure Active Directory admin center.
To learn about guest users, see link:/azure/active-directory/external-identities/what-is-b2b[What is guest user access in Azure Active Directory B2B?].
If you don't have any guest users, see link:/azure/active-directory/external-identities/b2b-quickstart-add-guest-users-portal[Quickstart: Add guest users to your directory in the Azure portal].

____
[!IMPORTANT] You must be a Global admin to do these steps.
____

. Go to the https://go.microsoft.com/fwlink/p/?linkid=2067268[Azure Active Directory admin center].
. In the navigation pane, select *Users*.
. {blank}
+
[cols=2*]
|===
| On the **Users
| All Users (Preview)** page, select *Add filters*.
|===

. In the *Pick a field* menu, choose *User type*, then select *Apply*.
. In the next menu, select *Guest*.
. In the list of results, select the user who needs a license.
. Under *Manage*, select *Licenses*.
. Select *Assignments*.
. On the *Update license assignments* page, select the product you want to assign a license for.
. On the right, clear the check boxes for any services you don't want the guest user to have access to.
. Select *Save*.

=== Next steps

If your users don't yet have the Office apps installed, you can share the xref:../setup/employee-quick-setup.adoc[Employee quick start guide] with your users to set up things, like https://support.microsoft.com/office/4414eaaf-0478-48be-9c42-23adc4716658[how to download and install Microsoft 365 or Office 2019 on a PC or Mac] and https://support.microsoft.com/office/7dabb6cb-0046-40b6-81fe-767e0b1f014f[how to set up Office apps and email on a mobile device].

=== Related content

xref:../../commerce/licenses/subscriptions-and-licenses.adoc[Understand subscriptions and licenses] (article) + xref:remove-licenses-from-users.adoc[Unassign licenses from users] (article) + xref:../../commerce/licenses/buy-licenses.adoc[Buy or remove licenses for your subscription] (article)
