= Change your organization's address, technical contact, and more
:audience: Admin
:author: cmcatee-MSFT
:description: Make changes to your organization profile, such as organization name, address, phone, technical contact, and email.
:f1.keywords: ["CSH"]
:manager: scotv
:ms.author: cmcatee
:ms.collection: ["M365-subscription-management", "Adm_O365", "Adm_TOC"]
:ms.custom: ["commerce_billing", "AdminSurgePortfolio", "AdminTemplateSet", "admindeeplinkMAC"]
:ms.date: 02/11/2022
:ms.localizationpriority: medium
:ms.reviewer: tugu, jmueller
:ms.service: o365-administration
:ms.topic: article
:search.appverid: MET150

== Change your organization's address, technical contact, and more

You can make changes to your organization profile, such as your organization name, address, phone, and technical contact.
*You must be a global admin to update this information.*

To change the address associated with your bill or subscription, see xref:../../commerce/billing-and-payments/change-your-billing-addresses.adoc[Change your billing addresses for Microsoft 365 for business].

=== Change organization settings for Cloud PCs

By default, new Cloud PCs are created with the Windows 11 operating system and the Standard User account type.
To change these default settings, use the following steps:

. Sign in to the Microsoft 365 admin center with a Global admin account.
. Go to the *Settings* > https://go.microsoft.com/fwlink/p/?linkid=2053743[*Org settings*] page.
. On the *Services* tab, select *Windows 365*.
. Select your preferred operating system and account type, then select *Save*.

Organization settings only apply to newly-created Cloud PCs.
When these settings are changed, they won't change the OS or account type of existing Cloud PCs.

=== Edit organization information

____
[!IMPORTANT] You can't change the country or region for your subscription.
That's because the country or region where your organization is headquartered determines which services are available to you, the taxes and billing currency, and the location of the data center.
To change your organization's country or region, sign up for a new account, choose the desired country or region, and purchase a new subscription.
____

To change other information on your company's profile page:

. In the admin center, go to the *Settings* > https://go.microsoft.com/fwlink/p/?linkid=2053743[*Org settings*] page.
. On the *Organization profile* tab, select *Organization information*.
. Update your organization's information, then select *Save changes*.
Be sure to fill in all required fields marked with an * to enable saving your changes.

An explanation of each field is provided below.

=== What do these fields mean?

|===
| *Field* | *Description*

| Name  +
| The name entered here is what users will see on the following pages:  + Sign-in page: If your users have set up other Microsoft accounts with their business or school email address, they may see the organization name on the sign-in page.
This helps them distinguish between their work or school account and their other accounts, so they can identify which one to use when they sign in.
+ Organization profile link and page: The link to your organization's profile displays the organization name.
+ Yammer navigation: In Yammer, the left navigation uses the organization name as the name of the home Yammer network.
+ OneDrive sync client: The organization name is shown in File Explorer on Windows and Finder on Mac, the file paths, the OneDrive activity center, the tooltip of the OneDrive cloud icon, and the OneDrive settings window.
Currently, updating the organization name does not update it for configured clients.
+ MS Teams: Organization Switcher in Teams displays the organization Name +

| Address, City, State/Province, Postal code  +
| The address entered here is what you will see on your bill, under Sold To: The Sold To address on your bill is the same as your organization address on your profile page (see xref:../../commerce/billing-and-payments/understand-your-invoice2.adoc[Understand your bill or invoice for Microsoft 365 for business].
+

| Country or region  +
| This is the country or region where the company is headquartered.
The selected country or region determines which services are available to you, the taxes and billing currency for your country or region, and the location of the data center closest to you (see https://office.microsoft.com/redir/FX103037529[Microsoft Office license restrictions]).
+ NOTE: Once selected, the country or region cannot be changed.
If you want to change the selection, you'll have to cancel your subscription and sign up again.
For help with this process, xref:../../business-video/get-help-support.adoc[contact support].

| Phone  +
| This is the primary number for your company.
It's usually the number of your company headquarters.
+

| Technical contact  +
| This is the email address for the primary technical person who administers your Microsoft 365 subscription.
This is the person who will receive communications about Microsoft 365 service status.
+

| Preferred language  +
| The preferred language determines the language for all communications that are sent from Microsoft to your organization.
When you sign up, this setting determines the language used by SharePoint Online, which your users see on your team site.
If you change the language preference setting after you sign up, all future communications are sent in the most recent language selected.
+ NOTE: The language used by SharePoint Online can't be changed.
|===

=== Change your alternate email address

As an admin, you can change your alternate email address for resetting passwords.

. Go to the https://go.microsoft.com/fwlink/p/?linkid=2024339[Microsoft 365 admin center].
. In the header, select your profile icon, then select *View account*.
. On the left, select *Security info*.
. In the Email section, select *Change*
. Edit the address in the *Alternate email* box, then select *Next*.
. Enter the code sent to the alternate email address and select *OK* to verify the change.
To learn about changing other profile information, see xref:change-contact-preferences.adoc[Change your contact preferences] or https://support.microsoft.com/office/6f238bff-5252-441e-b32b-655d5d85d15b[Change your display language].

==== Email signatures

You can change your email signature in Outlook Web App.
For more information, see https://support.microsoft.com/office/30c69a79-efc6-42d2-b740-4bf1c1f8a01c[Mail settings].

=== Related content

https://support.microsoft.com/office/ccba89cb-141c-4a36-8c56-6d16a8556d2e[Send email from a different address] (article) + xref:../add-users/change-a-user-name-and-email-address.adoc[Change a user name and email address] (article) + xref:../email/configure-email-forwarding.adoc[Configure email forwarding in Microsoft 365] (article)
