= Unassign licenses from users
:audience: Admin
:author: cmcatee-MSFT
:description: The method you use to unassign product licenses depends on whether you unassign licenses from specific users or from a specific product.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.author: cmcatee
:ms.collection: ["M365-subscription-management", "Adm_O365", "Adm_TOC"]
:ms.custom: ["commerce_licensing", "AdminSurgePortfolio", "okr_smb", "manage_licenses", "AdminTemplateSet"]
:ms.date: 07/12/2022
:ms.localizationpriority: medium
:ms.reviewer: sinakassaw, nicholak
:ms.service: o365-administration
:ms.topic: article
:search.appverid: MET150

== Unassign Microsoft 365 licenses from users

You can unassign licenses from users on either the *Active users* page, or on the *Licenses* page.
The method you use depends on whether you want to unassign product licenses from specific users or unassign users licenses from a specific product.

____
[!NOTE]

* As an admin, you can't assign or unassign licenses for a self-service purchase subscription bought by a user in your organization.
You can link:../../commerce/subscriptions/manage-self-service-purchases-admins.md#take-over-a-self-service-purchase-subscription[take over a self-service purchase subscription], and then assign or unassign licenses.
* For some subscriptions, you can only cancel during a limited window of time after you buy or renew your subscription.
If the cancellation window has passed, turn off recurring billing to cancel the subscription at the end of its term.
____

=== Before you begin

* You must be a Global, License, User admin to unassign licenses.
For more information, see xref:../add-users/about-admin-roles.adoc[About Microsoft 365 admin roles].
* You can xref:../../enterprise/remove-licenses-from-user-accounts-with-microsoft-365-powershell.adoc[remove licenses from user accounts with Office 365 PowerShell].
* You can also xref:../add-users/delete-a-user.adoc[delete user accounts] that were assigned a license to make their license available to other users.
When you delete a user account, their license is immediately available to assign to someone else.

=== Use the Licenses page to unassign licenses

The *Licenses* page lets you assign or unassign licenses for up to 20 users at a time.
The page shows the products you own, the number of available licenses for each product, and the number of assigned licenses out of the total licenses available.

The *Licenses* page shows an aggregate total of licenses for all subscriptions for the same product name.
For example, you might have one subscription for Microsoft 365 Business Premium that has 5 licenses, and another subscription that has 8 licenses for the same product.
The *Licenses* page shows that you have a total of 13 licenses for Microsoft 365 Business Premium across all your subscriptions.
This is different from what you see on the *Your products* page, which displays a row for each subscription you own, even if they are for the same product.

::: moniker range="o365-worldwide"

. In the admin center, go to the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=842264[Licenses] page.

::: moniker-end

::: moniker range="o365-21vianet"

. In the admin center, go to the *Billing* > https://go.microsoft.com/fwlink/p/?linkid=850625[Licenses] page.

::: moniker-end

. Select a product.
. Select the check boxes of the users for whom you want to unassign licenses.
. Select *Unassign licenses*.
. In the *Unassign licenses* box, select *Unassign*.

=== Use the Active users page to unassign licenses

When you use the *Active users* page to unassign licenses, you unassign product licenses from users.

==== Unassign licenses from one user

::: moniker range="o365-worldwide"

. In the admin center, go to the *Users* > https://go.microsoft.com/fwlink/p/?linkid=834822[Active users] page.

::: moniker-end

::: moniker range="o365-21vianet"

. In the admin center, go to the *Users* > https://go.microsoft.com/fwlink/p/?linkid=850628[Active users] page.

::: moniker-end

. Select the row of the user that you want to unassign a license for.
. In the right pane, select *Licenses and Apps*.
. Expand the *Licenses* section, clear the boxes for the licenses that you want to unassign, then select *Save changes*.

==== Unassign licenses from multiple users

::: moniker range="o365-worldwide"

. In the admin center, go to the *Users* > https://go.microsoft.com/fwlink/p/?linkid=834822[Active users] page.

::: moniker-end

::: moniker range="o365-21vianet"

. In the admin center, go to the *Users* > https://go.microsoft.com/fwlink/p/?linkid=850628[Active users] page.

::: moniker-end

. Select the circles next to the names of the users who you want to unassign licenses for.
. At the top, select *Manage product licenses*.
. In the *Manage product licenses* pane, select *Unassign all* > *Save changes*.
. At the bottom of the pane, select *Done*.

=== What happens to a user's data when you remove their license?

* When a license is removed from a user, Exchange Online data that is associated with that account is held for 30 days.
After the 30-day grace period, the data is deleted and can't be recovered.
However, it is linked to the retention policy, and the content that matches retention labels is retained for discovery.
* Files saved in OneDrive for Business aren't deleted unless the user is deleted from the Microsoft 365 admin center or is removed through Active Directory synchronization.
For more information, see link:/onedrive/retention-and-deletion[OneDrive retention and deletion].
* When the license is removed, the user's mailbox is no longer searchable by using an eDiscovery tool such as Content Search or eDiscovery (Premium).
For more information, see "Searching disconnected or de-licensed mailboxes" in xref:../../compliance/content-search.adoc[Content Search in Microsoft 365].
* If you have an Enterprise subscription, like Office 365 Enterprise E3, Exchange Online lets you preserve the mailbox data of a deleted user account by using xref:../../compliance/inactive-mailboxes-in-office-365.adoc[inactive mailboxes].
For more information, see xref:../../compliance/create-and-manage-inactive-mailboxes.adoc[Create and manage inactive mailboxes in Exchange Online].
* To learn how to block a user's access to Microsoft 365 data after their license is removed, and how to get access to the data afterwards, see xref:../add-users/remove-former-employee.adoc[Remove a former employee].
* If you remove a user's license and they still have Office apps installed, they see https://support.microsoft.com/office/0d23d3c0-c19c-4b2f-9845-5344fedc4380[Unlicensed Product and activation errors in Office] when they use Office apps.

=== Next steps

If you're not going to xref:assign-licenses-to-users.adoc[reassign the unused licenses to other users], consider xref:../../commerce/licenses/buy-licenses.adoc[removing the licenses from your subscription] so that you're not paying for more licenses than you need.

=== Related content

xref:../../commerce/licenses/buy-licenses.adoc[Remove licenses from your subscription] (article) + xref:assign-licenses-to-users.adoc[Assign licenses to users] (article) + xref:../../commerce/licenses/subscriptions-and-licenses.adoc[Understand subscriptions and licenses in Microsoft 365 for business] (article)
