= Stay on top of changes
:audience: Admin
:author: kwekua
:description: Learn how to stay on top of the Microsoft 365 updates using Message center, Targeted Release, Roadmap, and Blogs and Community.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.assetid: 719f4904-cbdd-4889-a0cf-fbd7837dfecd
:ms.author: kwekua
:ms.collection: ["M365-subscription-management", "Adm_O365", "Adm_TOC"]
:ms.custom: AdminSurgePortfolio
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["BCS160", "MET150", "MOE150"]

== Stay on top of Microsoft 365 product and feature changes

With Microsoft 365, you receive new product updates and features as they become available instead of scheduled updates that are months or years apart.
As a result, you and your users will routinely experience new and improved ways to do your job rather than a costly and time-consuming company-wide upgrade.
The challenge with such a model is keeping up with the changes and updates.
Here are a few ways that you can stay on top of the Microsoft 365 updates in your organization.

=== Stay on top of Microsoft 365 changes

|===
| Feature | Description | How to use

| *Message center* +
| Learn about official service announcements and feature changes.
You can read these messages in the Microsoft 365 admin center, the admin mobile app, or receive a weekly digest in email.
Share these messages with others in your organization when you see a message someone else should act on.
You can also use the Service Communications API to retrieve messages.
+
| Sign in to the xref:../admin-overview/admin-center-overview.adoc[admin center] or xref:../admin-overview/admin-mobile-app.adoc[admin mobile app].
Select *Health* > *Message center*.
Select a message to read or share.
+ Change the services you see messages about or opt-in to the weekly digest by choosing *Edit preferences* in the admin center.
This is also where you can opt-out of the weekly digest.
+ xref:message-center.adoc[Overview of the Microsoft 365 Message center] +

| *Targeted release* +
| Sign up for Targeted release for yourself and a select group of individuals at your organization.
Get the latest Microsoft 365 updates before everyone else and then inform or train your users on the new experience.
+
| Sign in to the xref:../admin-overview/admin-center-overview.adoc[admin center] or xref:../admin-overview/admin-mobile-app.adoc[admin mobile app].
Selece *Settings* > *Organization profile* > *Release preferences*.
Learn more about xref:release-options-in-office-365.adoc[Targeted release].
+

| *Roadmap* +
| Visit the Microsoft 365 Roadmap to learn about features that have been launched, are rolling out, are in development, have been cancelled, or previously released.
The roadmap is the official site for Microsoft 365 updates and changes.
+
| Visit the https://www.microsoft.com/microsoft-365/roadmap[Microsoft 365 Roadmap] frequently and learn about planned updates and releases.
+

| *Blogs* and *Community* +
| Visit Office Blogs, Microsoft Community, and Microsoft Tech Community to learn more details about changes in Microsoft 365 and share experiences with other users.
+
| Visit https://www.microsoft.com/en-us/microsoft-365/blog/[Office Blogs].
Visit https://answers.microsoft.com[Microsoft Community].
Visit https://techcommunity.microsoft.com[Microsoft Tech Community].
+
|===

____
[!NOTE] You need to be a global administrator to make changes to release preferences.
____
