= Use a QR code to sign-in to the Outlook mobile apps
:audience: Admin
:author: kwekua
:description: Learn how to use a QR code to authenticate and download Outlook mobile.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.author: kwekua
:ms.collection: ["Adm_O365"]
:ms.custom: ["AdminSurgePortfolio", "AdminTemplateSet"]
:ms.localizationpriority: high
:ms.service: o365-administration
:ms.topic: article

== Use a QR code to sign-in to the Outlook mobile apps

As the Microsoft 365 administrator, you can enable your users to sign in to Outlook for Android or iOS app on their mobile devices without having to enter their username and password.
By scanning a QR code, users can securely authenticate and sign in to Outlook mobile.

In Outlook on the web or other desktop Outlook applications, users may see notifications informing them that they can use Outlook on their mobile device.
These notifications can be managed by the administrator using Exchange PowerShell.
If users choose to send themselves an SMS text message to download the app on their mobile device, a QR code will appear on their computer.
They will be able to scan the QR code to log into Outlook on their phone or tablet.
This QR code is a short lived token that can only be redeemed once.

The notification is only generated if the following conditions are met:

. The QR code experience is enabled for the tenant (this experience is enabled by default).
. The user is not already using Outlook for iOS and Android.
. The user has an empty state at reading pane (does not select the option of auto opening the first email).
. The user did not dismiss the notification.

____
[!NOTE] In some cases, your users must re-authenticate on their computer to generate the QR code.
____

=== Use Exchange PowerShell

This feature is on by default.
To disable this feature, follow the steps below.

. link:/powershell/exchange/connect-to-exchange-online-powershell[Connect to Exchange PowerShell].
. Using PowerShell, you can disable the notifications informing your users about the Outlook mobile apps.
This also prevents the QR code sign-in flow from being shown.

[,powershell]
----
Set-OrganizationConfig -MobileAppEducationEnabled <Boolean>
----

____
[!NOTE] When using the Exchange PowerShell command, changes may take up to 8 hours to propagate.
____

=== Related content

xref:release-options-in-office-365.adoc[Set up the Standard or Targeted release options] (article) + link:/powershell/module/exchange/set-organizationconfig[Set-OrganizationConfig] (article)
