= Industry collaboration programs
:audience: ITPro
:author: dansimp
:description: There are various collaborative programs regarding Microsoft industry-wide anti-malware - Virus Information Alliance (VIA), Microsoft Virus Initiative (MVI), and Coordinated Malware Eradication (CME)
:keywords: security, malware, antivirus industry, anti-malware Industry, collaboration programs, alliances, Virus Information Alliance, Microsoft Virus Initiative, Coordinated Malware Eradication, WDSI, MMPC, Microsoft Malware Protection Center, partnerships
:manager: dansimp
:ms.author: dansimp
:ms.collection: M365-security-compliance
:ms.localizationpriority: medium
:ms.mktglfcycl: secure
:ms.reviewer:
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.topic: conceptual
:search.appverid: met150

== Industry collaboration programs

There are various industry-wide collaboration programs with different objectives and requirements, provided by Microsoft.
Enrolling in the right program can help you protect your customers, gain more insight into the current threat landscape, or help disrupting the malware ecosystem.

=== Virus Information Alliance (VIA)

The VIA program gives members access to information that will help improve protection for Microsoft customers.
Malware telemetry and samples can be provided to security teams to help identify gaps in their protection, prioritize new threat coverage, or better respond to threats.

*You must be a member of VIA if you want to apply for membership to the other programs.*

Go to the xref:virus-information-alliance-criteria.adoc[VIA program page] for more information.

=== Microsoft Virus Initiative (MVI)

MVI is open to organizations who build and own a Real Time Protection (RTP) anti-malware product of their own design, or one developed using a third-party Antivirus SDK.

Members get access to the xref:../defender/api-overview.adoc[Microsoft 365 Defender APIs] for the Microsoft 365 Defender portal, IOfficeAntivirus (IOAV), AntiMalware Scan Interface (AMSI), and Cloud Files, along with health data and other telemetry to help customers stay protected.
Anti-malware products are submitted to Microsoft for performance testing regularly.

Go to the xref:virus-initiative-criteria.adoc[MVI program page] for more information.

=== Coordinated Malware Eradication (CME)

CME is open to organizations who are involved in cybersecurity and anti-malware or interested in fighting cybercrime.

The program aims to bring organizations in cybersecurity and other industries together to pool tools, information, and actions to drive coordinated campaigns against malware.
The ultimate goal is to create efficient and long-lasting results for better protection of our communities, customers, and businesses.

Go to the xref:coordinated-malware-eradication.adoc[CME program page] for more information.
