= 
dansimp
:keywords: security, malware, protection, unwanted, software, alter,
infect, unwanted software, software bundlers, browser modifiers,
privacy, security, computing experience, prevent infection, solution,
WDSI, MMPC, Microsoft Malware Protection Center, virus research threats,
research malware, pc protection, computer infection, virus infection,
descriptions, remediation, latest threats

== Unwanted software

Unwanted software are programs that alter the Windows experience without
your consent or control. This can take the form of modified browsing
experience, lack of control over downloads and installation, misleading
messages, or unauthorized changes to Windows settings.

=== How unwanted software works

Unwanted software can be introduced when a user searches for and
downloads applications from the internet. Some applications are software
bundlers, which means that they’re packed with other applications. As a
result, other programs can be inadvertently installed when the original
application is downloaded.

Here are some indications of unwanted software:

* There are programs that you didn’t install and that may be difficult
to uninstall
* Browser features or settings have changed, and you can’t view or
modify them
* There are excessive messages about your device’s health or about files
and programs
* There are ads that can’t be easily closed

Some indicators are harder to recognize because they’re less disruptive,
but are still unwanted. For example, unwanted software can modify web
pages to display specific ads, monitor browsing activities, or remove
control of the browser.

Microsoft uses an extensive link:criteria.md[evaluation criteria] to
identify unwanted software.

=== How to protect against unwanted software

To prevent unwanted software infection, download software only from
official websites, or from the Microsoft Store. Be wary of downloading
software from third-party sites.

Use link:/microsoft-edge/deploy/index[Microsoft Edge] when browsing the
internet. Microsoft Edge includes additional protections that
effectively block browser modifiers that can change your browser
settings. Microsoft Edge also blocks known websites hosting unwanted
software using link:/microsoft-edge/deploy/index[Windows Defender
SmartScreen] (also used by Internet Explorer).

Enable
link:/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-in-windows-10[Microsoft
Defender Antivirus] in Windows 10. It provides real-time protection
against threats and detects and removes known unwanted software.

Download
https://www.microsoft.com/download/details.aspx?id=5201[Microsoft
Security Essentials] for real-time protection in Windows 7 or Windows
Vista.

For more general tips, see link:prevent-malware-infection.md[prevent
malware infection].

==== What should I do if my device is infected?

If you suspect that you have unwanted software, you can
https://www.microsoft.com/wdsi/filesubmission[submit files for
analysis].

Some unwanted software adds uninstallation entries, which means that you
can *remove them using Settings*. 1. Select the Start button 2. Go to
*Settings > Apps > Apps & features*. 3. Select the app you want to
uninstall, then select *Uninstall*.

If you only recently noticed symptoms of unwanted software infection,
consider sorting the apps by install date, and then uninstall the most
recent apps that you didn’t install.

You may also need to *remove browser add-ons* in your browsers, such as
Internet Explorer, Firefox, or Chrome.

In case threat removal is unsuccessful, read about
https://support.microsoft.com/help/4466982/windows-10-troubleshoot-problems-with-detecting-and-removing-malware[troubleshooting
malware detection and removal problems].
