= How to report false positives or false negatives following automated investigation in Microsoft Defender for Office 365
:audience: ITPro
:author: dansimp
:description: Was something missed or wrongly detected by AIR in Microsoft Defender for Office 365? Learn how to submit false positives or false negatives to Microsoft for analysis.
:f1.keywords: ["NOCSH"]
:keywords: automated, investigation, alert, trigger, action, remediation, false positive, false negative
:manager: dansimp
:ms.author: dansimp
:ms.collection: ["M365-security-compliance", "m365initiative-defender-office365"]
:ms.custom: ["autoir"]
:ms.date: 01/29/2021
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: mdo
:ms.topic: how-to
:search.appverid: met150

== How to report false positives/negatives in automated investigation and response capabilities

[!INCLUDE xref:../includes/mdo-trial-banner.adoc[MDO Trial banner]]

*Applies to*

* xref:defender-for-office-365.adoc[Microsoft Defender for Office 365 plan 2]
* xref:../defender/microsoft-365-defender.adoc[Microsoft 365 Defender]

If xref:automated-investigation-response-office.adoc[automated investigation and response (AIR) capabilities in Office 365] missed or wrongly detected something, there are steps your security operations team can take to fix it.
Such actions include:

* <<report-a-false-positivenegative-to-microsoft-for-analysis,Reporting a false positive/negative to Microsoft>>;
* <<adjust-an-alert-to-prevent-false-positives-from-recurring,Adjusting alerts>> (if needed);
and
* <<undo-a-remediation-action,Undoing remediation actions that were taken>>.

Use this article as a guide.

=== Report a false positive/negative to Microsoft for analysis

If AIR in Microsoft Defender for Office 365 missed an email message, an email attachment, a URL in an email message, or a URL in an Office file, you can xref:admin-submission.adoc[submit suspected spam, phish, URLs, and files to Microsoft for Office 365 scanning].

You can also https://www.microsoft.com/wdsi/filesubmission[Submit a file to Microsoft for malware analysis].

=== Adjust an alert to prevent false positives from recurring

If an alert is triggered by legitimate use, or the alert is inaccurate, you can link:/cloud-app-security/managing-alerts[Manage alerts in the Defender for Cloud Apps portal].

If your organization is using link:/windows/security/threat-protection[Microsoft Defender for Endpoint] in addition to Office 365, and a file, IP address, URL, or domain is treated as malware on a device, even though it's safe, you can link:/windows/security/threat-protection/microsoft-defender-atp/manage-indicators[create a custom indicator with an "Allow" action for your device].

=== Undo a remediation action

In most cases, if a remediation action was taken on an email message, email attachment, or URL, and the item is actually not a threat, your security operations team can undo the remediation action and take steps to prevent the false positive from recurring.
You can either use <<undo-an-action-using-threat-explorer,Threat Explorer>> or the <<undo-an-action-in-the-action-center,Actions tab for an investigation>> to undo an action.

____
[!IMPORTANT] Make sure you have the necessary permissions before attempting to perform the following tasks.
____

==== Undo an action using Threat Explorer

With Threat Explorer, your security operations team can find an email affected by an action and potentially undo the action.

|===
| Scenario | Undo Options | Learn more

| An email message was routed to a user's Junk Email folder
| <ul><li>Move the message to the user's Deleted Items folder</li><li>Move the message to the user's Inbox</li><li>Delete the message</li></ul>
| xref:investigate-malicious-email-that-was-delivered.adoc[Find and investigate malicious email that was delivered in Office 365]

| An email message or a file was quarantined
| <ul><li>Release the email or file</li><li> Delete the email or file</li></ul>
| xref:manage-quarantined-messages-and-files.adoc[Manage quarantined messages as an admin]
|===

==== Undo an action in the Action center

In the Action center, you can see remediation actions that were taken and potentially undo the action.

. In the Microsoft 365 Defender portal at https://security.microsoft.com, go to the Action center by selecting *Action center*.
To go directly to the Action center, use https://security.microsoft.com/action-center/.
. In the Action center, select the *History* tab to view the list of completed actions.
. Select an item.
Its flyout pane opens.
. In the flyout pane, select *Undo*.
(Only actions that can be undone will have an *Undo* button.)

=== See also

* xref:defender-for-office-365.adoc[Microsoft Defender for Office 365]
* xref:office-365-air.adoc[Automated investigations in Microsoft Defender for Office 365]
