= 
chrisda

== Create blocked sender lists in EOP

{empty}[!INCLUDE link:../includes/mdo-trial-banner.md[MDO Trial banner]]

*Applies to* - link:eop-about.md[Exchange Online Protection] -
link:defender-for-office-365.md[Microsoft Defender for Office 365 plan 1
and plan 2] - link:../defender/microsoft-365-defender.md[Microsoft 365
Defender]

In Microsoft 365 organizations with mailboxes in Exchange Online or
standalone Exchange Online Protection (EOP) organizations without
Exchange Online mailboxes, EOP offers multiple ways of blocking email
from unwanted senders. Collectively, you can think of these options as
_blocked sender lists_.

The available blocked sender lists are described in the following list
in order from most recommended to least recommended:

[arabic]
. Block entries for domains and email addresses (including spoofed
senders) in the Tenant Allow/Block List.
. Outlook Blocked Senders (the Blocked Senders list that’s stored in
each mailbox).
. Blocked sender lists or blocked domain lists (anti-spam policies).
. Mail flow rules (also known as transport rules).
. The IP Block List (connection filtering).

The rest of this article contains specifics about each method.

____
[!NOTE] Always submit messages in your blocked sender lists to Microsoft
for analysis. For instructions, see
link:submissions-admin.md#report-questionable-email-to-microsoft[Report
questionable email to Microsoft]. If the messages or message sources are
determined to be harmful, Microsoft can automatically block the
messages, and you won’t need to manually maintain the entry in blocked
sender lists.

Instead of blocking email, you also have several options to allow email
from specific sources using _safe sender lists_. For more information,
see link:create-safe-sender-lists-in-office-365.md[Create safe sender
lists].
____

=== Email message basics

A standard SMTP email message consists of a _message envelope_ and
message content. The message envelope contains information that’s
required for transmitting and delivering the message between SMTP
servers. The message content contains message header fields
(collectively called the _message header_) and the message body. The
message envelope is described in RFC 5321, and the message header is
described in RFC 5322. Recipients never see the actual message envelope
because it’s generated by the message transmission process, and it isn’t
actually part of the message.

* The `5321.MailFrom` address (also known as the *MAIL FROM* address, P1
sender, or envelope sender) is the email address that’s used in the SMTP
transmission of the message. This email address is typically recorded in
the *Return-Path* header field in the message header (although it’s
possible for the sender to designate a different *Return-Path* email
address). If the message can’t be delivered, it’s the recipient for the
non-delivery report (also known as an NDR or bounce message).
* The `5322.From` (also known as the *From* address or P2 sender) is the
email address in the *From* header field, and is the sender’s email
address that’s displayed in email clients.

Frequently, the `5321.MailFrom` and `5322.From` addresses are the same
(person-to-person communication). However, when email is sent on behalf
of someone else, the addresses can be different.

Blocked sender lists and blocked domain lists in anti-spam policies in
EOP inspect only the `5322.From` addresses. This behavior is similar to
Outlook Blocked Senders that use the `5322.From` address.

=== Use block entries in the Tenant Allow/Block List

Our number one recommended option for blocking mail from specific
senders or domains is the Tenant Allow/Block List. For instructions, see
link:tenant-allow-block-list-email-spoof-configure.md[Allow or block
email using the Tenant Allow/Block List].

Email messages from these senders are marked as _high confidence spam_
(SCL = 9). What happens to the messages is determined by the
link:anti-spam-policies-configure.md[anti-spam policy] that detected the
message for the recipient. In the default anti-spam policy and new
custom policies, messages that are marked as high confidence spam are
delivered to the Junk Email folder by default. In Standard and Strict
link:preset-security-policies.md[preset security policies], high
confidence spam messages are quarantined.

As an added benefit, users in the organization can’t send email to these
blocked domains and addresses. They’ll receive the following
non-delivery report (also known as an NDR or bounce message):
`5.7.1  Your message can't be delivered because one or more recipients are blocked by your organization's tenant allow/block list policy.`
The entire message is blocked to all recipients if email is sent to any
of the entries in the list.

Only if you can’t use the Tenant Allow/Block List for some reason should
you consider using a different method to block senders.

=== Use Outlook Blocked Senders

When only a small number of users received unwanted email, users or
admins can add the sender email addresses to the Blocked Senders list in
the mailbox. For instructions, see
link:configure-junk-email-settings-on-exo-mailboxes.md[Configure junk
email settings on Exchange Online mailboxes].

When messages are successfully blocked due to a user’s Blocked Senders
list, the *X-Forefront-Antispam-Report* header field will contain the
value `SFV:BLK`.

____
[!NOTE] If the unwanted messages are newsletters from a reputable and
recognizable source, unsubscribing from the email is another option to
stop the user from receiving the messages.
____

=== Use blocked sender lists or blocked domain lists

When multiple users are affected, the scope is wider, so the next best
option is blocked sender lists or blocked domain lists in anti-spam
policies. Messages from senders on the lists are marked as *High
confidence spam*, and the action that you’ve configured for the *High
Confidence Spam* filter verdict is taken on the messages. For more
information, see link:anti-spam-policies-configure.md[Configure
anti-spam policies].

The maximum limit for these lists is approximately 1000 entries.

=== Use mail flow rules

Mail flow rules can also look for keywords or other properties in the
unwanted messages.

Regardless of the conditions or exceptions that you use to identify the
messages, you configure the action to set the spam confidence level
(SCL) of the message to 9, which marks the message as *High confidence
spam*. For more information, see
link:/exchange/security-and-compliance/mail-flow-rules/use-rules-to-set-scl[Use
mail flow rules to set the SCL in messages].

____
[!IMPORTANT] It’s easy to create rules that are _overly_ aggressive, so
it’s important that you identify only the messages you want to block
using very specific criteria. Also, be sure to
link:/exchange/security-and-compliance/mail-flow-rules/manage-mail-flow-rules#monitor-rule-usage[monitor
the usage of the rule] to ensure everything works as expected.
____

=== Use the IP Block List

When it’s not possible to use one of the other options to block a
sender, _only then_ should you use the IP Block List in the connection
filter policy. For more information, see
link:connection-filter-policies-configure.md[Configure the connection
filter policy]. It’s important to keep the number of blocked IPs to a
minimum, so blocking entire IP address ranges is _not_ recommended.

You should _especially_ avoid adding IP address ranges that belong to
consumer services (for example, outlook.com) or shared infrastructures,
and also ensure that you review the list of blocked IP addresses as part
of regular maintenance.
