= 
msfttracyp

== Microsoft Defender for Office 365

{empty}[!INCLUDE link:../includes/mdo-trial-banner.md[MDO Trial banner]]

*Applies to* - link:defender-for-office-365.md[Microsoft Defender for
Office 365 plan 1 and plan 2] -
link:../defender/microsoft-365-defender.md[Microsoft 365 Defender]

____
[!IMPORTANT] This article is for *business customers*.

But if you’re using Outlook.com, *_Microsoft 365 Family, or Microsoft
365 Personal_*, and you need info about *_Safe Links or Safe Attachments
in Outlook_* blocking emails, see
https://support.microsoft.com/office/advanced-outlook-com-security-for-microsoft-365-subscribers-882d2243-eab9-4545-a58a-b36fee4a46e2?storagetype=live[Advanced
Outlook.com security for Microsoft 365 subscribers].
____

Microsoft Defender for Office 365 safeguards your organization against
malicious threats posed by email messages, links (URLs), and
collaboration tools. Defender for Office 365 includes:

* *link:preset-security-policies.md[Installation by Preset can set up
everything for you]*: The easiest and the recommended setup automates
the roll-out of a secure environment (if automated policies are possible
in your organization). Abbreviated steps are available too:
link:step-by-step-guides/ensuring-you-always-have-the-optimal-security-controls-with-preset-security-policies.md[Just
the steps for preset policy setup&#44; please!]
* *link:#defender-for-office-365-policies[Threat protection policies]*:
Define threat-protection policies to set the appropriate level of
protection for your organization.
* *link:#how-to-view-microsoft-defender-for-office-365-reports[Reports]*:
View real-time reports to monitor Defender for Office 365 performance in
your organization.
* *link:#use-threat-investigation-and-response-capabilities[Threat
investigation and response capabilities]*: Use leading-edge tools to
investigate, understand, simulate, and prevent threats.
* *link:air-about.md[Automated investigation and response
capabilities]*: Save time and effort investigating and mitigating
threats.

=== Interactive guide to Microsoft Defender for Office 365

If you need more information, this interactive guide will show you and
example of how to safeguard your organization with Microsoft Defender
for Office 365.

You’ll also see how Defender for Office 365 can help you define
protection policies, analyze threats to your organization, and respond
to attacks.

https://aka.ms/MSDO-IG[Check out the interactive guide]

=== What’s the difference between Microsoft Defender for Office 365 Plan 1 and Plan 2?

For more on what’s included in Microsoft 365 Plans 1 & 2, browse over to
link:microsoft-defender-for-office-365-product-overview.md[this
document].

This article spells out what makes up the two products, and the
*_emphasis_* of each part of _Microsoft Defender for Office 365_ using a
familiar structure: _Protect_, _Detect_, _Investigate_, and _Respond_.

Graphics and short, scannable paragraphs answer questions like:

* What is _Plan 1_ optimized to do for you?
* What’s the biggest advantage to you and your company in _Plan 2_?
* Who has _Exchange Online Protection_ and what’s it optimized to do?

The goal of this article is clarity and quick readability. So, don’t
miss it!

=== Getting Started

There are two methods to set up Microsoft Defender for Office 365 for
your subscription.

==== Preset security policy configuration is recommended

It is *recommended* that – as much as your organization can, given its
specific needs – you configure via *preset security policies*. You can
learn more about presets here: link:preset-security-policies.md[Preset
setup information and steps]; or just
link:step-by-step-guides/ensuring-you-always-have-the-optimal-security-controls-with-preset-security-policies.md[the
steps for preset policy setup&#44; please].

==== Manual configuration for Microsoft Defender for Office 365

Though it’s no longer the recommended practice, here are the initial
logical configuration chunks for manual set up:

* Configure everything with `__anti__' in the name.
** anti-malware
** anti-phishing
** anti-spam
* Set up everything with `__safe__' in the name.
** Safe Links
** Safe Attachments
* Defend the workloads (ex. SharePoint Online, OneDrive, and Teams)
* Protect with zero-hour auto purge (ZAP).

To learn by doing things manually, link:protect-against-threats.md[click
this link].

____
[!NOTE] Microsoft Defender for Office 365 comes in two different Plan
types. You can tell if you have *Plan 1* if you have `Real-time
Detections', and *Plan 2*, if you have Threat Explorer. The Plan you
have influences the tools you will see, so be certain that you’re aware
of your Plan as you learn.
____

=== Manual steps to Configure Microsoft Defender for Office 365 policies

It’s recommended that you configure with preset security policies, but
some organizations must configure manually.

With Microsoft Defender for Office 365, your organization’s security
team can configure protection by defining policies in the Microsoft 365
Defender portal at https://security.microsoft.com at *Email &
collaboration* > *Policies & rules* > *Threat policies*. Or, you can go
directly to the *Threat policies* page by using
https://security.microsoft.com/threatpolicy.

____
[!TIP] For a quick list of policies to define, see
link:protect-against-threats.md[Protect against threats].
____

=== Defender for Office 365 Policies

The policies that are defined for your organization determine the
behavior and protection level for predefined threats.

Policy options are extremely flexible. For example, your organization’s
security team can set fine-grained threat protection at the user,
organization, recipient, and domain level. It is important to review
your policies regularly because new threats and challenges emerge daily.

* *link:safe-attachments-about.md[Safe Attachments]*: Provides zero-day
protection to safeguard your messaging system, by checking email
attachments for malicious content. It routes all messages and
attachments that do not have a virus/malware signature to a special
environment, and then uses machine learning and analysis techniques to
detect malicious intent. If no suspicious activity is found, the message
is forwarded to the mailbox. To learn more, see
link:safe-attachments-policies-configure.md[Set up Safe Attachments
policies].
* *link:safe-links-about.md[Safe Links]*: Provides time-of-click
verification of URLs, for example, in emails messages and Office files.
Protection is ongoing and applies across your messaging and Office
environment. Links are scanned for each click: safe links remain
accessible and malicious links are dynamically blocked. To learn more,
see link:safe-links-policies-configure.md[Set up Safe Links policies].
* *link:safe-attachments-for-spo-odfb-teams-about.md[Safe Attachments
for SharePoint&#44; OneDrive&#44; and Microsoft Teams]*: Protects your
organization when users collaborate and share files, by identifying and
blocking malicious files in team sites and document libraries. To learn
more, see link:safe-attachments-for-spo-odfb-teams-configure.md[Turn on
Defender for Office 365 for SharePoint&#44; OneDrive&#44; and Microsoft Teams].
* *link:anti-phishing-policies-about.md#exclusive-settings-in-anti-phishing-policies-in-microsoft-defender-for-office-365[Anti-phishing
protection in Defender for Office 365]*: Detects attempts to impersonate
your users and internal or custom domains. It applies machine learning
models and advanced impersonation-detection algorithms to avert phishing
attacks. To learn more, see
link:anti-phishing-policies-mdo-configure.md[Configure anti-phishing
policies in Microsoft Defender for Office 365].

=== How to view Microsoft Defender for Office 365 reports

Microsoft Defender for Office 365 includes
link:reports-defender-for-office-365.md[reports] to monitor Defender for
Office 365. You can access the reports in theMicrosoft 365 Defender
portal at https://security.microsoft.com at *Reports* > *Email &
collaboration* > *Email & collaboration reports*. You can also go
directly to the *Email and collaboration reports* page using
https://security.microsoft.com/securityreports.

Reports update in real-time, providing you with the latest insights.
These reports also provide recommendations and alert you to imminent
threats. Predefined reports include the following:

* link:threat-explorer-about.md[Threat Explorer (or real-time
detections)]
* link:reports-defender-for-office-365.md#threat-protection-status-report[Threat
protection status report]
* … and several more.

=== Use threat investigation and response capabilities

Microsoft Defender for Office 365 Plan 2 includes best-of-class
link:office-365-ti.md[threat investigation and response tools] that
enable your organization’s security team to anticipate, understand, and
prevent malicious attacks.

* *link:threat-trackers.md[Threat trackers]* provide the latest
intelligence on prevailing cybersecurity issues. For example, you can
view information about the latest malware, and take countermeasures
before it becomes an actual threat to your organization. Available
trackers include link:threat-trackers.md#noteworthy-trackers[Noteworthy
trackers], link:threat-trackers.md#trending-trackers[Trending trackers],
link:threat-trackers.md#tracked-queries[Tracked queries], and
link:threat-trackers.md#saved-queries[Saved queries].
* *link:threat-explorer-about.md[Threat Explorer in Plan 2 (or real-time
detections in Plan 1)]* (also referred to as Explorer) is a real-time
report that allows you to identify and analyze recent threats. You can
configure Explorer to show data for custom periods.
* *link:attack-simulation-training-simulations.md[Attack simulation
training]* allows you to run realistic attack scenarios in your
organization to identify vulnerabilities. Simulations of current types
of attacks are available, including spear phishing credential harvest
and attachment attacks, and password spray and brute force password
attacks.

=== Save time with automated investigation and response

When you are investigating a potential cyberattack, time is of the
essence. The sooner you can identify and mitigate threats, the better
off your organization will be.

link:air-about.md[Automated investigation and response] (AIR)
capabilities include a set of security playbooks that can be launched
automatically, such as when an alert is triggered, or manually, such as
from a view in Explorer.

AIR can save your security operations team time and effort in mitigating
threats effectively and efficiently. To learn more, see
link:air-about.md[AIR in Office 365].

=== Permissions required to use Microsoft Defender for Office 365 features

To access Microsoft Defender for Office 365 features, you _must_ be
assigned an appropriate role. The following table includes some
examples:

[width="100%",cols="50%,50%",options="header",]
|===
|Role or role group |Resources to learn more
|global administrator (or Organization Management) |You can assign this
role in Azure Active Directory or in the Microsoft 365 Defender portal.
For more information, see link:mdo-portal-permissions.md[Permissions in
the Microsoft 365 Defender portal].

|Security Administrator |You can assign this role in Azure Active
Directory or in the Microsoft 365 Defender portal. For more information,
see link:mdo-portal-permissions.md[Permissions in the Microsoft 365
Defender portal].

|Organization Management in Exchange Online
|link:/exchange/permissions-exo/permissions-exo[Permissions in Exchange
Online]

|Search and Purge |This role is available only in the Microsoft 365
Defender portal or the Microsoft Purview compliance portal. For more
information, see link:mdo-portal-permissions.md[Permissions in the
Microsoft 365 Defender portal] and
link:../../compliance/microsoft-365-compliance-center-permissions.md[Permissions
in the Microsoft Purview compliance portal].

| |
|===

=== Where to get Microsoft Defender for Office 365

Microsoft Defender for Office 365 is included in certain subscriptions,
such as Microsoft 365 E5, Office 365 E5, Office 365 A5, and Microsoft
365 Business Premium.

If your subscription doesn’t include Defender for Office 365, you can
get Defender for Office 365 Plan 1 or Plan 2 as an add-on to certain
subscriptions. To learn more, take a look at the following resources:

* link:/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#office-365-advanced-threat-protection-atp-availability[Microsoft
Defender for Office 365 availability] for a list of subscriptions that
include Defender for Office 365 plans.
* link:/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#feature-availability-across-advanced-threat-protection-atp-plans[Feature
availability across Microsoft Defender for Office 365 plans] for a list
of features included in Plan 1 and 2.
* https://products.office.com/exchange/advance-threat-protection#pmg-allup-content[Get
the right Microsoft Defender for Office 365] to compare plans and
purchase Defender for Office 365.
* https://go.microsoft.com/fwlink/p/?LinkID=698279[Start a free trial]

=== What new features are coming for Microsoft Defender for Office 365?

New features are added to Microsoft Defender for Office 365 continually.
To learn more, see the following resources:

* https://www.microsoft.com/microsoft-365/roadmap?filters=&searchterms=Microsoft%2CDefender%2Cfor%2COffice%2C365[Microsoft
365 Roadmap] provides a list of new features in development and rolling
out.
* link:/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#whats-new-in-office-365-advanced-threat-protection-atp[Microsoft
Defender for Office 365 Service Description] describes features and
availability across Defender for Office 365 plans.

=== See also

* link:../defender/microsoft-365-defender.md[Microsoft 365 Defender]
* link:../defender/m365d-autoir.md[Automated investigation and response
(AIR) in Microsoft 365 Defender]
