'''

title: Mail flow in EOP f1.keywords:

* NOCSH ms.author: chrisda author: chrisda manager: dansimp ms.date:  audience: ITPro ms.topic: overview

ms.localizationpriority: medium ms.assetid: e109077e-cc85-4c19-ae40-d218ac7d0548 ms.custom:

* seo-marvel-apr2020 description: Admin can learn about the options for configuring mail flow and routing in Exchange Online Protection (EOP).
ms.subservice: mdo ms.service: microsoft-365-security ms.collection: M365-security-compliance search.appverid: met150 --

== Mail flow in EOP

[!INCLUDE xref:../includes/mdo-trial-banner.adoc[MDO Trial banner]]

*Applies to*

* xref:exchange-online-protection-overview.adoc[Exchange Online Protection]
* xref:defender-for-office-365.adoc[Microsoft Defender for Office 365 plan 1 and plan 2]
* xref:../defender/microsoft-365-defender.adoc[Microsoft 365 Defender]

In Microsoft 365 organizations with Exchange Online mailboxes, or standalone Exchange Online Protection (EOP) organizations without Exchange Online mailboxes, all messages sent to your organization pass through EOP before users see them.
You have options about how to route messages that pass through EOP for processing before they are routed to user mailboxes.

=== Working with messages and message access options

EOP offers flexibility in how your messages are routed.
The following topics explain steps in the mail flow process.

link:/exchange/mail-flow-best-practices/use-directory-based-edge-blocking[Use Directory Based Edge Blocking to reject messages sent to invalid recipients] Describes the Directory Based Edge Blocking feature which lets you reject messages for invalid recipients at the service network perimeter.

link:/exchange/mail-flow-best-practices/manage-accepted-domains/manage-accepted-domains[View or edit accepted domains in EOP] describes how to manage domains that are associated with your EOP service.

If you add subdomains to your organization, your EOP service can help you manage these too.
Learn more about subdomains at link:/exchange/mail-flow-best-practices/manage-accepted-domains/enable-mail-flow-for-subdomains[Enable mail flow for subdomains in Exchange Online].

link:/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/use-connectors-to-configure-mail-flow[Configure mail flow using connectors] introduces connectors and shows how you can use them to customize mail routing.
Scenarios include ensuring secure communication with a partner organization and setting up a smart host.

link:/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/enhanced-filtering-for-connectors[Enhanced Filtering for Connectors] describes how to configure connectors if your mail is routed to a service or device before EOP.

In hybrid environments where EOP protects on-premises Exchange mailboxes, you need to configure mail flow rules (also known as transport rules) in on-premises Exchange.
These mail flow rules translate the EOP spam filtering verdict so the junk email rule in the mailbox can move the message to the Junk Email folder.
For details, see link:/exchange/standalone-eop/configure-eop-spam-protection-hybrid[Configure EOP to deliver spam to the Junk Email folder in hybrid environments].
If you don't  want to move messages to each user's Junk Email folder, you may choose another action by editing your anti-spam policies (also known as content filter policies).
For more information, see xref:configure-your-spam-filter-policies.adoc[Configure anti-spam policies].

=== Verify mail flow

To verify that your EOP setup, including your connector configuration, is working correctly, see the "How do you know this task worked?" section in link:/exchange/standalone-eop/set-up-your-eop-service[Set up your EOP service].

link:/exchange/mail-flow-best-practices/test-mail-flow[Test mail flow by validating your Microsoft 365 connectors] provides instructions for testing that your mail flow is set up correctly.
