= 
dansimp

== Non-delivery report in the Security & Compliance Center

{empty}[!INCLUDE link:../includes/mdo-trial-banner.md[MDO Trial banner]]

*Applies to* - link:exchange-online-protection-overview.md[Exchange
Online Protection] - link:defender-for-office-365.md[Microsoft Defender
for Office 365 plan 1 and plan 2] -
link:../defender/microsoft-365-defender.md[Microsoft 365 Defender]

The *Non-delivery report* in the link:mail-flow-insights-v2.md[Mail flow
dashboard] in the https://protection.office.com[Security & Compliance
Center] shows the most-encountered error codes in non-delivery reports
(also known as NDRs or bounce messages) for users in your organization.
This report shows the details of NDRs so you can troubleshoot email
delivery problems.

:::image type=``content''
source=``../../media/mfi-non-delivery-report-widget.png'' alt-text=``The
Non-delivery report widget in the Mail flow dashboard in the Security &
Compliance Center''
lightbox=``../../media/mfi-non-delivery-report-widget.png'':::

=== Report view for the Non-delivery report

Clicking on the *Non-delivery report* widget will take you to the
*Non-delivery report*.

By default, the activity for all error codes is shown. If you click
*Show data for*, you can select a specific error code from the dropdown.

If you hover over a specific color (error code) on a specific day in the
chart, you’ll see the total number of messages for the error.

:::image type=``content''
source=``../../media/mfi-non-delivery-report-overview-view.png''
alt-text=``The Report view in the Non-accepted domain report''
lightbox=``../../media/mfi-non-delivery-report-overview-view.png'':::

=== Details table view for the Non-delivery report

If you click *View details table* in a report view, the following
information is shown:

* *Date*
* *Non-delivery report code*
* *Count*
* *Sample messages*: The message IDs of a sample of affected messages.

If you click *Filters* in a details table view, you can specify a date
range with *Start date* and *End date*.

To email the report for a specific date range to one or more recipients,
click *Request download*.

When you select a row in the table, a flyout appears with the following
information:

* *Date*
* *Non-delivery report code*: You can click on the link to find for more
information about the causes and solutions for the specific error code.
* *Count*
* *Sample messages*: You can click *View sample messages* to see the
link:message-trace-scc.md[message trace] results for a sample of the
affected messages.

:::image type=``content''
source=``../../media/mfi-non-delivery-report-details-flyout.png''
alt-text=``The Details flyout after selecting a row in Details table
view in the Non-delivery report''
lightbox=``../../media/mfi-non-delivery-report-details-flyout.png'':::

=== Related topics

For information about other insights in the Mail flow dashboard, see
link:mail-flow-insights-v2.md[Mail flow insights in the Security &
Compliance Center].
