= 
msfttracyp

== Microsoft Defender for Office 365 security product overview

{empty}[!INCLUDE link:../includes/mdo-trial-banner.md[MDO Trial banner]]

*Applies to* - link:eop-about.md[Exchange Online Protection] -
link:defender-for-office-365.md[Microsoft Defender for Office 365 plan 1
and plan 2]

This article will introduce you to your new Microsoft Defender for
Office 365 security properties in the Cloud. Whether you’re part of a
Security Operations Center, you’re a Security Administrator new to the
space, or you want a refresher, let’s get started.

____
[!CAUTION] If you’re using *Outlook.com*, *Microsoft 365 Family*, or
*Microsoft 365 Personal*, and need _Safe Links_ or _Safe Attachments_
info, *_click this link_*:
https://support.microsoft.com/office/advanced-outlook-com-security-for-office-365-subscribers-882d2243-eab9-4545-a58a-b36fee4a46e2[Advanced
Outlook.com security for Microsoft 365 subscribers].
____

=== What is Defender for Office 365 security

Every Office 365 subscription comes with security capabilities. The
goals and actions that you can take depend on the focus of these
different subscriptions. In Office 365 security, there are three main
security services (or products) tied to your subscription type:

[arabic]
. Exchange Online Protection (EOP)
. Microsoft Defender for Office 365 Plan 1 (Defender for Office P1)
. Microsoft Defender for Office 365 Plan 2 (Defender for Office P2)

____
[!NOTE] If you bought your subscription and need to roll out security
features _right now_, skip to the steps in the
link:protect-against-threats.md[Protect Against Threats] article. If
you’re new to your subscription and would like to know your license
before you begin, browse Billing > Your Products in the
https://admin.microsoft.com/AdminPortal/#/homepage[Microsoft 365 admin
center].
____

Office 365 security builds on the core protections offered by EOP. EOP
is present in any subscription where Exchange Online mailboxes can be
found (remember, all the security products discussed here are
Cloud-based).

You may be accustomed to seeing these three components discussed in this
way:

[width="100%",cols="34%,33%,33%",options="header",]
|===
|EOP |Microsoft Defender for Office 365 P1 |Microsoft Defender for
Office 365 P2
|Prevents broad, volume-based, known attacks. |Protects email and
collaboration from zero-day malware, phish, and business email
compromise. |Adds post-breach investigation, hunting, and response, as
well as automation, and simulation (for training).
|===

But in terms of architecture, let’s start by thinking of each piece as
cumulative layers of security, each with a security emphasis. More like
this:

:::image type=``content''
source=``../../media/tp_GraphicEOPATPP1P2_2.png'' alt-text=``The EOP and
Microsoft Defender for Office 365 and their relationships to one another
with service emphasis, including a note for email authentication''
lightbox=``../../media/tp_GraphicEOPATPP1P2_2.png'':::

Though each of these services emphasizes a goal from among Protect,
Detect, Investigate, and Respond, *_all_* the services can carry out
*_any_* of the goals of protecting, detecting, investigating, and
responding.

The core of Office 365 security is EOP protection. Microsoft Defender
for Office 365 P1 contains EOP in it. Defender for Office 365 P2
contains P1 and EOP. The structure is cumulative. That’s why, when
configuring this product, you should start with EOP and work to Defender
for Office 365.

Though email authentication configuration takes place in public DNS,
it’s important to configure this feature to help defend against
spoofing. _If you have EOP,_ *_you should
link:email-authentication-about.md[configure email authentication]_*.

If you have an Office 365 E3, or below, you have EOP, but with the
option to buy standalone Defender for Office 365 P1 through upgrade. If
you have Office 365 E5, you already have Defender for Office 365 P2.

____
[!TIP] If your subscription is neither Office 365 E3 or E5, you can
still check to see if you have the option to upgrade to Microsoft
Defender for Office 365 P1. If you’re interested,
https://www.microsoft.com/microsoft-365/exchange/advance-threat-protection#coreui-contentrichblock-x07wids[this
webpage] lists subscriptions eligible for the Microsoft Defender for
Office 365 P1 upgrade (check the end of the page for the fine-print).
____

=== The Office 365 security ladder from EOP to Microsoft Defender for Office 365

____
[!IMPORTANT] Learn the details on these pages:
link:eop-about.md[Exchange Online Protection], and
link:defender-for-office-365.md[Defender for Office 365].
____

What makes adding Microsoft Defender for Office 365 plans an advantage
to pure EOP threat management can be difficult to tell at first glance.
To help sort out if an upgrade path is right for your organization,
let’s look at the capabilities of each product when it comes to:

* preventing and detecting threats
* investigating
* responding

starting with *Exchange Online Protection*:

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Prevent/Detect |Investigate |Respond
|Technologies include: | |
|===

If you want to dig in to EOP, *link:eop-about.md[jump to this article]*.

Because these products are cumulative, if you evaluate Microsoft
Defender for Office 365 P1 and decide to subscribe to it, you’ll add
these abilities.

Gains with *Defender for Office 365, Plan 1* (to date):

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Prevent/Detect |Investigate |Respond
|Technologies include everything in EOP plus: | |
|===

So, Microsoft Defender for Office 365 P1 expands on the *_prevention_*
side of the house, and adds extra forms of *_detection_*.

Microsoft Defender for Office 365 P1 also adds *Real-time detections*
for investigations. This threat hunting tool’s name is in bold because
having it is clear means of _knowing_ you have Defender for Office 365
P1. It doesn’t appear in Defender for Office 365 P2.

Gains with *Defender for Office 365, Plan 2* (to date):

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Prevent/Detect |Investigate |Respond
|Technologies include everything in EOP, and Microsoft Defender for
Office 365 P1 plus: | |
|===

So, Microsoft Defender for Office 365 P2 expands on the *_investigation
and response_* side of the house, and adds a new hunting strength.
Automation.

In Microsoft Defender for Office 365 P2, the primary hunting tool is
called *Threat Explorer* rather than Real-time detections. If you see
Threat Explorer when you navigate to the Microsoft 365 Defender portal,
you’re in Microsoft Defender for Office 365 P2.

To get into the details of Microsoft Defender for Office 365 P1 and P2,
*link:defender-for-office-365.md[jump to this article]*.

____
[!TIP] EOP and Microsoft Defender for Office 365 are also different when
it comes to end-users. In EOP and Defender for Office 365 P1, the focus
is _awareness_, and so those two services include the _Report message
Outlook add-in_ so users can report emails they find suspicious, for
further analysis.

In Defender for Office 365 P2 (which contains everything in EOP and P1),
the focus shifts to _further training_ for end-users, and so the
Security Operations Center has access to a powerful _Threat Simulator_
tool, and the end-user metrics it provides.
____

=== Microsoft Defender for Office 365 Plan 1 vs. Plan 2 cheat sheet

This quick-reference will help you understand what capabilities come
with each Microsoft Defender for Office 365 subscription. When combined
with your knowledge of EOP features, it can help business decision
makers determine what Microsoft Defender for Office 365 is best for
their needs.

[width="100%",cols="50%,50%",options="header",]
|===
|Defender for Office 365 Plan 1 |Defender for Office 365 Plan 2
|Configuration, protection, and detection capabilities: |Defender for
Office 365 Plan 1 capabilities
|===

* Microsoft Defender for Office 365 Plan 2 is included in Office 365 E5,
Office 365 A5, and Microsoft 365 E5.
* Microsoft Defender for Office 365 Plan 1 is included in Microsoft 365
Business Premium.
* Microsoft Defender for Office 365 Plan 1 and Defender for Office 365
Plan 2 are each available as an add-on for certain subscriptions. To
learn more, here’s another link
link:/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#feature-availability-across-advanced-threat-protection-atp-plans[Feature
availability across Microsoft Defender for Office 365 plans].
* The link:safe-documents-in-e5-plus-security-about.md[Safe Documents]
feature is only available to users with the Microsoft 365 A5 or
Microsoft 365 E5 Security licenses (not included in Microsoft Defender
for Office 365 plans).
* If your current subscription doesn’t include Microsoft Defender for
Office 365 and you want it,
https://info.microsoft.com/ww-landing-M365SMB-web-contact.html[contact
sales to start a trial], and find out how Microsoft Defender for Office
365 can work for in your organization.
* Microsoft Defender for Office 365 P2 customers have access to
*Microsoft 365 Defender integration* to efficiently detect, review, and
respond to incidents and alerts.

____
[!TIP] *_Insider tip_*. You can use the Microsoft Learn table of
contents to learn about EOP and Microsoft Defender for Office 365.
Navigate back to this page, link:index.yml[Office 365 Security
overview], and you’ll notice that table of contents organization in the
side-bar. It begins with Deployment (including migration) and then
continues into prevention, detection, investigation, and response.

This structure is divided so that *Security Administration* topics are
followed by *Security Operations* topics. If you’re a new member of
either job role, use the link in this tip, and your knowledge of the
table of contents, to help learn the space. Remember to use _feedback
links_ and _rate articles_ as you go. Feedback helps us improve what we
offer you.
____

=== Where to go next

If you’re a Security Admin, you may need to configure DKIM or DMARC for
your mail. You may want to roll out `Strict' security presets for your
priority users, or look for what’s new in the product. Or if you’re with
Security Ops, you may want to leverage Real-time detections or Threat
Explorer to investigate and respond, or train end-user detection with
Attack Simulator. Either way, here are some additional recommendations
for what to look at next.

link:email-authentication-about.md[Email Authentication&#44; including SPF&#44;
DKIM&#44; and DMARC (with links to setup of all three)]

link:recommended-settings-for-eop-and-office365.md[See the specific
recommended `golden' configs] and link:preset-security-policies.md[use
their recommended presets to configure security policies quickly]

Catch up on link:defender-for-office-365-whats-new.md[what’s new in
Microsoft Defender for Office 365 (including EOP developments)]

link:threat-explorer-about.md[Use Threat Explorer or Real-time
detections]

Use link:attack-simulation-training-simulations.md[Attack simulation
training]
