= Migrate from a third-party protection service to Microsoft Defender for Office 365
:audience: Admin
:author: chrisda
:description: Learn the right way to migrate from third-party protection services or devices like Google Postini, the Barracuda Spam and Virus Firewall, or Cisco IronPort to Microsoft Defender for Office 365 protection.
:f1.keywords: ["NOCSH"]
:manager: dansimp
:ms.author: chrisda
:ms.collection: ["M365-security-compliance", "m365solution-mdo-migration", "highpri"]
:ms.custom:
:ms.date:
:ms.localizationpriority: medium
:ms.service: microsoft-365-security
:ms.subservice: mdo
:ms.topic: conceptual
:search.appverid: ["MET150", "MOE150"]

== Migrate from a third-party protection service or device to Microsoft Defender for Office 365

*Applies to*

* xref:defender-for-office-365.adoc[Microsoft Defender for Office 365 plan 1 and plan 2]

If you already have an existing third-party protection service or device that sits in front of Microsoft 365, you can use this guide to migrate your protection to Microsoft Defender for Office 365 to get the benefits of a consolidated management experience, potentially reduced cost (using products that you already pay for), and a mature product with integrated security protection.
For more information, see https://www.microsoft.com/security/business/threat-protection/office-365-defender[Microsoft Defender for Office 365].

Watch this short video to learn more about migrating to Defender for Office 365.

____
[!VIDEO https://www.microsoft.com/en-us/videoplayer/embed/RWRwfH]
____

This guide provides specific and actionable steps for your migration, and assumes the following facts:

* You already have Microsoft 365 mailboxes, but you're currently using a third-party service or device for email protection.
Mail from the internet flows through the protection service before delivery into your Microsoft 365 organization, and Microsoft 365 protection is as low as possible (it's never completely off;
for example, malware protection is always enforced).
+
:::image type="content" source="../../media/mdo-migration-before.png" alt-text="The Mail flows from the internet through the third-party protection service or device before delivery into Microsoft 365" lightbox="../../media/mdo-migration-before.png":::

* You're beyond the investigation and consideration phase for protection by Defender for Office 365.
If you need to evaluate Defender for Office 365 to decide whether it's right for your organization, we recommend that you consider the options described in xref:try-microsoft-defender-for-office-365.adoc[Try Microsoft Defender for Office 365].
* You've already purchased Defender for Office 365 licenses.
* You need to retire your existing third-party protection service, which means you'll ultimately need to point the MX records for your email domains to Microsoft 365.
When you're done, mail from the internet will flow directly into Microsoft 365 and will be protected exclusively by Exchange Online Protection (EOP) and Defender for Office 365.
+
:::image type="content" source="../../media/mdo-migration-after.png" alt-text="The mail flows from the internet into Microsoft 365" lightbox="../../media/mdo-migration-after.png":::

Eliminating your existing protection service in favor of Defender for Office 365 is a big step that you shouldn't take lightly, nor should you rush to make the change.
The guidance in this migration guide will help you transition your protection in an orderly manner with minimal disruption to your users.

The very high-level migration steps are illustrated in the following diagram.
The actual steps are listed in the section named <<the-migration-process,The migration process>> later in this article.

:::image type="content" source="../../media/mdo-migration-overview.png" alt-text="The process of migration from a third-party protection solution or device to Defender for Office 365" lightbox="../../media/mdo-migration-overview.png":::

=== Why use the steps in this guide?

In the IT industry, surprises are generally bad.
Simply flipping your MX records to point to Microsoft 365 without prior and thoughtful testing will result in many surprises.
For example:

* You or your predecessors have likely spent a lot of time and effort customizing your existing protection service for optimal mail delivery (in other words, blocking what needs to be blocked, and allowing what needs to be allowed).
It's almost a guaranteed certainty that not every customization in your current protection service is required in Defender for Office 365.
It's also very possible that Defender for Office 365 will introduce new issues (allows or blocks) that didn't happen or weren't required in your current protection service.
* Your help desk and security personnel need to know what to do in Defender for Office 365.
For example, if a user complains about a missing message, does your help desk know where or how to look for it?
They're likely familiar with the tools in your existing protection service, but what about the tools in Defender for Office 365?

In contrast, if you follow the steps in this migration guide, you'll get the following tangible benefits for your migration:

* Minimal disruption to users.
* Objective data from Defender for Office 365 that you can use as you report on the progress and success of the migration to management.
* Early involvement and instruction for help desk and security personnel.

The more you familiarize yourself with how Defender for Office 365 will affect your organization, the better the transition will be for users, help desk personnel, security personnel, and management.

This migration guide gives you a plan for gradually "turning the dial" so you can monitor and test how Defender for Office 365 affects your users and their email so you can react quickly to any issues that you encounter.

=== The migration process

The process of migrating from a third-party protection service to Defender for Office 365 can be divided into three phases as described in the following table:

:::image type="content" source="../../media/phase-diagrams/migration-phases.png" alt-text="The process for migrating to Defender for Office 365" lightbox="../../media/phase-diagrams/migration-phases.png":::

|===
| Phase | Description

| xref:migrate-to-defender-for-office-365-prepare.adoc[Prepare for your migration]
| <ol><li>link:migrate-to-defender-for-office-365-prepare.md#inventory-the-settings-at-your-existing-protection-service[Inventory the settings at your existing protection service]</li><li>link:migrate-to-defender-for-office-365-prepare.md#check-your-existing-protection-configuration-in-microsoft-365[Check your existing protection configuration in Microsoft 365]</li><li>link:migrate-to-defender-for-office-365-prepare.md#check-your-mail-routing-configuration[Check your mail routing configuration]</li><li>link:migrate-to-defender-for-office-365-prepare.md#move-features-that-modify-messages-into-microsoft-365[Move features that modify messages into Microsoft 365]</li><li>link:migrate-to-defender-for-office-365-prepare.md#define-spam-and-bulk-user-experiences[Define spam and bulk user experiences]</li><li>link:migrate-to-defender-for-office-365-prepare.md#identify-and-designate-priority-accounts[Identify and designate priority accounts]</li></ol>

| xref:migrate-to-defender-for-office-365-setup.adoc[Set up Defender for Office 365]
| <ol><li>link:migrate-to-defender-for-office-365-setup.md#step-1-create-distribution-groups-for-pilot-users[Create distribution groups for pilot users]</li><li>link:migrate-to-defender-for-office-365-setup.md#step-2-configure-user-submission-for-user-message-reporting[Configure user submission for user message reporting]</li><li>link:migrate-to-defender-for-office-365-setup.md#step-3-maintain-or-create-the-scl-1-mail-flow-rule[Maintain or create the SCL=-1 mail flow rule]</li><li>link:migrate-to-defender-for-office-365-setup.md#step-4-configure-enhanced-filtering-for-connectors[Configure Enhanced Filtering for Connectors]</li><li>link:migrate-to-defender-for-office-365-setup.md#step-5-create-pilot-protection-policies[Create pilot protection policies]</li></ol>

| xref:migrate-to-defender-for-office-365-onboard.adoc[Onboard to Defender for Office 365]
| <ol><li>link:migrate-to-defender-for-office-365-onboard.md#step-1-begin-onboarding-security-teams[Begin onboarding Security Teams]</li><li>link:migrate-to-defender-for-office-365-onboard.md#step-2-optional-exempt-pilot-users-from-filtering-by-your-existing-protection-service[(Optional) Exempt pilot users from filtering by your existing protection service]</li><li>link:migrate-to-defender-for-office-365-onboard.md#step-3-tune-spoof-intelligence[Tune spoof intelligence]</li><li>link:migrate-to-defender-for-office-365-onboard.md#step-4-tune-impersonation-protection-and-mailbox-intelligence[Tune impersonation protection and mailbox intelligence]</li><li>link:migrate-to-defender-for-office-365-onboard.md#step-5-use-data-from-user-submissions-to-measure-and-adjust[Use data from user submissions to measure and adjust]</li><li>link:migrate-to-defender-for-office-365-onboard.md#step-6-optional-add-more-users-to-your-pilot-and-iterate[(Optional) Add more users to your pilot and iterate]</li><li>link:migrate-to-defender-for-office-365-onboard.md#step-7-extend-microsoft-365-protection-to-all-users-and-turn-off-the-scl-1-mail-flow-rule[Extend Microsoft 365 protection to all users and turn off the SCL=-1 mail flow rule]</li><li>link:migrate-to-defender-for-office-365-onboard.md#step-8-switch-your-mx-records[Switch your MX records]</li></ol>
|===

=== Next step

* Proceed to xref:migrate-to-defender-for-office-365-prepare.adoc[Phase 1: Prepare].
