= 
chrisda

== Permissions in the Security & Compliance Center

{empty}[!INCLUDE link:../includes/mdo-trial-banner.md[MDO Trial banner]]

*Applies to* - link:exchange-online-protection-overview.md[Exchange
Online Protection] - link:defender-for-office-365.md[Microsoft Defender
for Office 365 plan 1 and plan 2] -
link:../defender/microsoft-365-defender.md[Microsoft 365 Defender]

The Security & Compliance Center lets you grant permissions to people
who perform compliance tasks like device management, data loss
prevention, eDiscovery, retention, and so on. These people can perform
only the tasks that you explicitly grant them access to. To access the
Security & Compliance Center, users need to be a global administrator or
a member of one or more Security & Compliance Center role groups.

Permissions in the Security & Compliance Center are based on the
role-based access control (RBAC) permissions model. RBAC is the same
permissions model that’s used by Exchange, so if you’re familiar with
Exchange, granting permissions in the Security & Compliance Center will
be very similar. It’s important to remember, however, that Exchange role
groups and Security & Compliance Center role groups don’t share
membership or permissions. While both have an Organization Management
role group, they aren’t the same. The permissions they grant, and the
members of the role groups, are different. There’s a list of Security &
Compliance Center role groups below.

:::image type=``content''
source=``../../media/992c20ca-e82e-497c-9c8d-6fab212deb80.png''
alt-text=``The Permissions page in the Security & Compliance Center''
lightbox=``../../media/992c20ca-e82e-497c-9c8d-6fab212deb80.png'':::

=== Relationship of members, roles, and role groups

A *role* grants permissions to do a set of tasks; for example, the Case
Management role lets people work with eDiscovery cases.

A *role group* is a set of roles that lets people do their jobs across
the Security & Compliance Center. For example, the Compliance
Administrator role group includes (among other roles) the roles for Case
Management, Content Search, and Organization Configuration (plus others)
because someone who’s a compliance admin will need the permissions for
those tasks to do their job.

The Security & Compliance Center includes default role groups for the
most common tasks and functions that you’ll need to assign people to. We
recommend simply adding individual users as *members* to the default
role groups.

:::image type=``content''
source=``../../media/2a16d200-968c-4755-98ec-f1862d58cb8b.png''
alt-text=``The relationship of role groups to roles and members''
lightbox=``../../media/2a16d200-968c-4755-98ec-f1862d58cb8b.png'':::

=== Role groups in the Security & Compliance Center

The following table lists the default role groups that are available in
the Security & Compliance Center, and the roles that are assigned to the
role groups by default. To grant permissions to a user to perform a
compliance task, add them to the appropriate Security & Compliance
Center role group.

Managing permissions in the Security & Compliance Center only gives
users access to the compliance features that are available within the
Security & Compliance Center itself. If you want to grant permissions to
other compliance features that aren’t in the Security & Compliance
Center, such as Exchange mail flow rules (also known as transport
rules), you need to use the Exchange admin center (EAC). For more
information, see
link:/exchange/permissions-exo/permissions-exo[Permissions in Exchange
Online].

To see how to grant access to the Security & Compliance Center, check
out link:grant-access-to-the-security-and-compliance-center.md[Give
users access to Microsoft Purview admin center].

____
[!NOTE] To view the *Permissions* tab in the Security & Compliance
Center, you need to be an admin. Specifically, you need to be assigned
the *Role Management* role, and that role is assigned only to the
*Organization Management* role group in the Security & Compliance Center
by default. Furthermore, the *Role Management* role allows users to
view, create, and modify role groups.
____

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Role group |Description |Default roles assigned
|*Attack Simulation Administrators* |Don’t use this role group in the
Security & Compliance Center. Use the corresponding role in Azure AD.
|Attack Simulator Admin

|*Attack Simulator Payload Authors* |Don’t use this role group in the
Security & Compliance Center. Use the corresponding role in Azure AD.
|Attack Simulator Payload Author

|*Communication Compliance* |Provides permission to all the
communication compliance roles: administrator, analyst, investigator,
and viewer. |Case Management Communication Compliance Admin
Communication Compliance Analysis Communication Compliance Case
Management Communication Compliance Investigation Communication
Compliance Viewer Data Classification Feedback Provider Data Connector
Admin View-Only Case

|*Communication Compliance Administrators* |Administrators of
communication compliance that can create/edit policies and define global
settings. |Communication Compliance Admin Communication Compliance Case
Management Data Connector Admin

|*Communication Compliance Analysts* |Analysts of communication
compliance that can investigate policy matches, view message meta data,
and take remediation actions. |Communication Compliance Analysis
Communication Compliance Case Management

|*Communication Compliance Investigators* |Analysts of communication
compliance that can investigate policy matches, view message content,
and take remediation actions. |Case Management Communication Compliance
Analysis Communication Compliance Case Management Communication
Compliance Investigation Data Classification Feedback Provider View-Only
Case

|*Communication Compliance Viewers* |Viewer of communication compliance
that can access the available reports and widgets. |Communication
Compliance Case Management Communication Compliance Viewer

|*Compliance Administrator*1 |Members can manage settings for device
management, data loss prevention, reports, and preservation. |Case
Management Communication Compliance Admin Communication Compliance Case
Management Compliance Administrator Compliance Search Data
Classification Feedback Provider Data Classification Feedback Reviewer
Data Connector Admin Data Investigation Management Device Management
Disposition Management DLP Compliance Management Hold IB Compliance
Management Information Protection Admin Information Protection Analyst
Information Protection Investigator Information Protection Reader
Insider Risk Management Admin Manage Alerts Organization Configuration
RecordManagement Retention Management View-Only Audit Logs View-Only
Case View-Only Device Management View-Only DLP Compliance Management
View-Only IB Compliance Management View-Only Manage Alerts View-Only
Recipients View-Only Record Management View-Only Retention Management

|*Compliance Data Administrator* |Members can manage settings for device
management, data protection, data loss prevention, reports, and
preservation. |Compliance Administrator Compliance Search Data Connector
Admin Device Management Disposition Management DLP Compliance Management
IB Compliance Management Information Protection Admin Information
Protection Analyst Information Protection Investigator Information
Protection Reader Manage Alerts Organization Configuration
RecordManagement Retention Management Sensitivity Label Administrator
View-Only Audit Logs View-Only Device Management View-Only DLP
Compliance Management View-Only IB Compliance Management View-Only
Manage Alerts View-Only Recipients View-Only Record Management View-Only
Retention Management

|*Compliance Manager Administrators* |Manage template creation and
modification. |Compliance Manager Administration Compliance Manager
Assessment Compliance Manager Contribution Compliance Manager Reader
Data Connector Admin

|*Compliance Manager Assessors* |Create assessments, implement
improvement actions, and update test status for improvement actions.
|Compliance Manager Assessment Compliance Manager Contribution
Compliance Manager Reader Data Connector Admin

|*Compliance Manager Contributors* |Create assessments and perform work
to implement improvement actions. |Compliance Manager Contribution
Compliance Manager Reader Data Connector Admin

|*Compliance Manager Readers* |View all Compliance Manager content
except for administrator functions. |Compliance Manager Reader

|*Content Explorer Content Viewer* |View the contents files in Content
explorer. |Data Classification Content Viewer

|*Content Explorer List Viewer* |View all items in Content explorer in
list format only. |Data Classification List Viewer

|*Data Investigator* |Perform searches on mailboxes, SharePoint Online
sites, and OneDrive for Business locations. |Communication Compliance
Search Custodian Data Investigation Management Export Preview Review RMS
Decrypt Search And Purge

|*eDiscovery Manager* |Members can perform searches and place holds on
mailboxes, SharePoint Online sites, and OneDrive for Business locations.
Members can also create and manage eDiscovery cases, add and remove
members to a case, create and edit Content Searches associated with a
case, and access case data in eDiscovery (Premium). An eDiscovery
Administrator is a member of the eDiscovery Manager role group who has
been assigned additional permissions. In addition to the tasks that an
eDiscovery Manager can perform, an eDiscovery Administrator can: |Case
Management Communication Compliance Search Custodian Export Hold Preview
Review RMS Decrypt

|*Global Reader* |Members have read-only access to reports, alerts, and
can see all the configuration and settings. The primary difference
between Global Reader and Security Reader is that a Global Reader can
access *configuration and settings*. |Security Reader Sensitivity Label
Reader Service Assurance View View-Only Audit Logs View-Only Device
Management View-Only DLP Compliance Management View-Only IB Compliance
Management View-Only Manage Alerts View-Only Recipients View-Only Record
Management View-Only Retention Management

|*Information Protection* |Full control over all information protection
features, including sensitivity labels and their policies, DLP, all
classifier types, activity and content explorers, and all related
reports. |Data Classification Content Viewer Information Protection
Admin Information Protection Analyst Information Protection Investigator
Information Protection Reader

|*Information Protection Admins* |Create, edit, and delete DLP policies,
sensitivity labels and their policies, and all classifier types. Manage
endpoint DLP settings and simulation mode for auto-labeling policies.
|Information Protection Admin

|*Information Protection Analysts* |Access and manage DLP alerts and
activity explorer. View-only access to DLP policies, sensitivity labels
and their policies, and all classifier types. |Data Classification List
Viewer Information Protection Analyst

|*Information Protection Investigators* |Access and manage DLP alerts,
activity explorer, and content explorer. View-only access to DLP
policies, sensitivity labels and their policies, and all classifier
types. |Data Classification Content Viewer Information Protection
Analyst Information Protection Investigator

|*Information Protection Readers* |View-only access to reports for DLP
policies and sensitivity labels and their policies. |Information
Protection Reader

|*Insider Risk Management* |Use this role group to manage insider risk
management for your organization in a single group. By adding all user
accounts for designated administrators, analysts, and investigators, you
can configure insider risk management permissions in a single group.
This role group contains all the insider risk management permission
roles. This is the easiest way to quickly get started with insider risk
management and is a good fit for organizations that do not need separate
permissions defined for separate groups of users. |Case Management Data
Connector Admin Insider Risk Management Admin Insider Risk Management
Analysis Insider Risk Management Audit Insider Risk Management
Investigation View-Only Case

|*Insider Risk Management Admins* |Use this role group to initially
configure insider risk management and later to segregate insider risk
administrators into a defined group. Users in this role group can
create, read, update, and delete insider risk management policies,
global settings, and role group assignments. |Case Management Data
Connector Admin Insider Risk Management Admin View-Only Case

|*Insider Risk Management Analysts* |Use this group to assign
permissions to users that will act as insider risk case analysts. Users
in this role group can access all insider risk management alerts, cases,
and notices templates. They cannot access the insider risk Content
Explorer. |Case Management Insider Risk Management Analysis View-Only
Case

|*Insider Risk Management Auditors* |Use this group to assign
permissions to users that will audit insider risk management activities.
Users in this role group can access the insider risk audit log. |Insider
Risk Management Audit

|*Insider Risk Management Investigators* |Use this group to assign
permissions to users that will act as insider risk data investigators.
Users in this role group can access all insider risk management alerts,
cases, notices templates, and the Content Explorer for all cases. |Case
Management Insider Risk Management Investigation View-Only Case

|*IRM Contributors* |This role group is visible, but is used by
background services only. |Insider Risk Management Permanent
contribution Insider Risk Management Temporary contribution

|*Knowledge Administrators* |Configure knowledge, learning, assign
trainings and other intelligent features. |Knowledge Admin

|*MailFlow Administrator* |Members can monitor and view mail flow
insights and reports in the Security & Compliance Center. Global admins
can add ordinary users to this group, but, if the user isn’t a member of
the Exchange Admin group, the user will not have access to Exchange
admin-related tasks. |View-Only Recipients

|*Organization Management*1 |Members can control permissions for
accessing features in the Security & Compliance Center, and also manage
settings for device management, data loss prevention, reports, and
preservation. |Audit Logs

|*Privacy Management* |Manage access control for Priva in the Microsoft
Purview compliance portal. |Case Management

|*Privacy Management Administrators* |Administrators of privacy
management solution that can create/edit policies and define global
settings. |Case Management

|*Privacy Management Analysts* |Analysts of privacy management solution
that can investigate policy matches, view messages meta data, and take
remediation actions. |Case Management

|*Privacy Management Contributors* |Manage contributor access for
privacy management cases. |Privacy Management Permanent contribution

|*Privacy Management Investigators* |Investigators of privacy management
solution that can investigate policy matches, view message content, and
take remediation actions. |Case Management

|*Privacy Management Viewers* |Viewer of privacy management solution
that can access the available dashboards and widgets. |Data
Classification List Viewer

|*Quarantine Administrator* |Members can access all Quarantine actions.
For more information, see
link:manage-quarantined-messages-and-files.md[Manage quarantined
messages and files as an admin in EOP] |Quarantine

|*Records Management* |Members can configure all aspects of records
management, including retention labels and disposition reviews.
|Disposition Management

|*Reviewer* |Members can access review sets in
link:../../compliance/overview-ediscovery-20.md[eDiscovery (Premium)]
cases. Members of this role group can see and open the list of cases on
the *eDiscovery > Advanced* page in the Microsoft Purview compliance
portal that they’re members of. After the user accesses an eDiscovery
(Premium) case, they can select *Review sets* to access case data. This
role doesn’t allow the user to preview the results of a collection
search that’s associated with the case or do other search or case
management tasks. Members of this role group can only access the data in
a review set. |Review

|*Security Administrator* |Members have access to a number of security
features of Identity Protection Center, Privileged Identity Management,
Monitor Microsoft 365 Service Health, and Security & Compliance Center.
|Audit Logs

|*Security Operator* |Members can manage security alerts, and also view
reports and settings of security features. |Compliance Search

|*Security Reader* |Members have read-only access to a number of
security features of Identity Protection Center, Privileged Identity
Management, Monitor Microsoft 365 Service Health, and Security &
Compliance Center. |Security Reader

|*Service Assurance User* |Members can access the Service assurance
section in the Security & Compliance Center. Service assurance provides
reports and documents that describe Microsoft’s security practices for
customer data that’s stored in Microsoft 365. It also provides
independent third-party audit reports on Microsoft 365. For more
information, see link:../../compliance/service-assurance.md[Service
assurance in the Security & Compliance Center]. |Service Assurance View

|*Subject Rights Request Administrators* |Create subject rights
requests. |Case Management Subject Rights Request Admin View-Only Case

|*Supervisory Review* |Members can create and manage the policies that
define which communications are subject to review in an organization.
For more information, see
link:../../compliance/communication-compliance-configure.md[Configure
communication compliance policies for your organization]. |Supervisory
Review Administrator
|===

____
[!NOTE] 1 This role group doesn’t assign members the permissions
necessary to search the audit log or to use any reports that might
include Exchange data, such as the DLP or Defender for Office 365
reports. To search the audit log or to view all reports, a user has to
be assigned permissions in Exchange Online. This is because the
underlying cmdlet used to search the audit log is an Exchange Online
cmdlet. Global admins can search the audit log and view all reports
because they’re automatically added as members of the Organization
Management role group in Exchange Online. For more information, see
link:../../compliance/search-the-audit-log-in-security-and-compliance.md[Search
the audit log in the Security & Compliance Center].
____

=== Roles in the Security & Compliance Center

The following table lists the available roles and the role groups that
they’re assigned to by default.

Note that the following roles aren’t assigned to the Organization
Management role group by default:

* Attack Simulator Admin
* Attack Simulator Payload Author
* Communication
* Communication Compliance Analysis
* Communication Compliance Investigation
* Communication Compliance Viewer
* Compliance Manager Administration
* Compliance Manager Assessment
* Compliance Manager Contribution
* Compliance Manager Reader
* Custodian
* Data Classification Content Viewer
* Data Classification Feedback Provider
* Data Classification Feedback Reviewer
* Data Classification List Viewer
* Data Investigation Management
* Disposition Management
* Export
* Information Protection Admin
* Information Protection Analyst
* Information Protection Investigator
* Information Protection Reader
* Insider Risk Management Analysis
* Insider Risk Management Audit
* Insider Risk Management Investigation
* Insider Risk Management Permanent contribution
* Insider Risk Management Temporary contribution
* Knowledge Admin
* Preview
* Privacy Management Admin
* Privacy Management Analysis
* Privacy Management Investigation
* Privacy Management Permanent contribution
* Privacy Management Temporary contribution
* Privacy Management Viewer
* Review
* RMS Decrypt
* Subject Rights Request Admin
* Supervisory Review Administrator
* Tenant AllowBlockList Manager

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Role |Description |Default role group assignments
|*Attack Simulator Admin* |Don’t use this role in the Security &
Compliance Center. Use the corresponding role in Azure AD. |Attack
Simulator Administrators

|*Attack Simulator Payload Author* |Don’t use this role in the Security
& Compliance Center. Use the corresponding role in Azure AD. |Attack
Simulator Payload Authors

|*Audit Logs* |Turn on and configure auditing for the organization, view
the organization’s audit reports, and then export these reports to a
file. |Organization Management Security Administrator

|*Case Management* |Create, edit, delete, and control access to
eDiscovery cases. |Communication Compliance Communication Compliance
Investigators Compliance Administrator eDiscovery Manager Insider Risk
Management Insider Risk Management Admins Insider Risk Management
Analysts Insider Risk Management Investigators Organization Management
Privacy Management Privacy Management Administrators Privacy Management
Analysts Privacy Management Investigators Subject Rights Request
Administrators

|*Communication* |Manage all communications with the custodians
identified in an eDiscovery (Premium) case. Create hold notifications,
hold reminders, and escalations to management. Track custodian
acknowledgment of hold notifications and manage access to the custodian
portal that is used by each custodian in a case to track communications
for the cases where they were identified as a custodian. |Data
Investigator eDiscovery Manager

|*Communication Compliance Admin* |Used to manage policies in the
Communication Compliance feature. |Communication Compliance
Communication Compliance Administrators Compliance Administrator
Organization Management

|*Communication Compliance Analysis* |Used to perform investigation,
remediation of the message violations in the Communication Compliance
feature. Can only view message meta data. |Communication Compliance
Communication Compliance Analysts Communication Compliance Investigators

|*Communication Compliance Case Management* |Used to access
Communication Compliance cases. |Communication Compliance Communication
Compliance Administrators Communication Compliance Analysts
Communication Compliance Investigators Communication Compliance Viewers
Compliance Administrator Organization Management

|*Communication Compliance Investigation* |Used to perform
investigation, remediation, and review message violations in the
Communication Compliance feature. Can view message meta data and
message. |Communication Compliance Communication Compliance
Investigators

|*Communication Compliance Viewer* |Used to access reports and widgets
in the Communication Compliance feature. |Communication Compliance
Communication Compliance Viewers

|*Compliance Administrator* |View and edit settings and reports for
compliance features. |Compliance Administrator Compliance Data
Administrator Organization Management

|*Compliance Manager Administration* |Manage template creation and
modification. |Compliance Manager Administrators

|*Compliance Manager Assessment* |Create assessments, implement
improvement actions, and update test status for improvement actions.
|Compliance Manager Administrators Compliance Manager Assessors

|*Compliance Manager Contribution* |Create assessments and perform work
to implement improvement actions. |Compliance Manager Administrators
Compliance Manager Assessors Compliance Manager Contributors

|*Compliance Manager Reader* |View all Compliance Manager content except
for administrator functions. |Compliance Manager Administrators
Compliance Manager Assessors Compliance Manager Contributors Compliance
Manager Readers

|*Compliance Search* |Perform searches across mailboxes and get an
estimate of the results. |Compliance Administrator Compliance Data
Administrator Data Investigator eDiscovery Manager Organization
Management Security Operator

|*Custodian* |Identify and manage custodians for eDiscovery (Premium)
cases and use the information from Azure Active Directory and other
sources to find data sources associated with custodians. Associate other
data sources such as mailboxes, SharePoint sites, and Teams with
custodians in a case. Place a legal hold on the data sources associated
with custodians to preserve content in the context of a case. |Data
Investigator eDiscovery Manager

|*Data Classification Content Viewer* |View in-place rendering of files
in Content explorer. |Content Explorer Content Viewer Information
Protection Information Protection Investigators Privacy Management
Privacy Management Investigators

|*Data Classification Feedback Provider* |Allows providing feedback to
classifiers in content explorer. |Communication Compliance Communication
Compliance Investigators Compliance Administrator

|*Data Classification Feedback Reviewer* |Allows reviewing feedback from
classifiers in feedback explorer. |Compliance Administrator

|*Data Classification List Viewer* |View the list of files in content
explorer. |Content Explorer List Viewer Information Protection Analysts
Privacy Management Privacy Management Analysts Privacy Management
Investigators Privacy Management Viewers

|*Data Connector Admin* |Create and manage connectors to import and
archive non-Microsoft data in Microsoft 365. |Communication Compliance
Communication Compliance Administrators Compliance Administrator
Compliance Data Administrator Compliance Manager Administrators
Compliance Manager Assessors Compliance Manager Contributors Insider
Risk Management Insider Risk Management Admins Organization Management

|*Data Investigation Management* |Create, edit, delete, and control
access to data investigation. |Compliance Administrator Data
Investigator

|*Device Management* |View and edit settings and reports for device
management features. |Compliance Administrator Compliance Data
Administrator Organization Management Security Administrator

|*Disposition Management* |Control permissions for accessing Manual
Disposition in the Security & Compliance Center. |Compliance
Administrator Compliance Data Administrator Records Management

|*DLP Compliance Management* |View and edit settings and reports for
data loss prevention (DLP) policies. |Compliance Administrator
Compliance Data Administrator Organization Management Security
Administrator

|*Export* |Export mailbox and site content that’s returned from
searches. |Data Investigator eDiscovery Manager

|*Hold* |Place content in mailboxes, sites, and public folders on hold.
When on hold, a copy of the content is stored in a secure location.
Content owners will still be able to modify or delete the original
content. |Compliance Administrator eDiscovery Manager Organization
Management

|*IB Compliance Management* |View, create, remove, modify, and test
Information Barrier policies. |Compliance Administrator Compliance Data
Administrator Organization Management Security Administrator

|*Information Protection Admin* |Create, edit, and delete DLP policies,
sensitivity labels and their policies, and all classifier types. Manage
endpoint DLP settings and simulation mode for auto-labeling policies.
|Compliance Administrator Compliance Data Administrator Information
Protection Information Protection Admins

|*Information Protection Analyst* |Access and manage DLP alerts and
activity explorer. View-only access to DLP policies, sensitivity labels
and their policies, and all classifier types. |Compliance Administrator
Compliance Data Administrator Information Protection Information
Protection Analysts Information Protection Investigators

|*Information Protection Investigator* |Access and manage DLP alerts,
activity explorer, and content explorer. View-only access to DLP
policies, sensitivity labels and their policies, and all classifier
types. |Compliance Administrator Compliance Data Administrator
Information Protection Information Protection Investigators

|*Information Protection Reader* |View-only access to reports for DLP
policies and sensitivity labels and their policies. |Compliance
Administrator Compliance Data Administrator Information Protection
Information Protection Readers

|*Insider Risk Management Admin* |Create, edit, delete, and control
access to Insider Risk Management feature. |Compliance Administrator
Insider Risk Management Insider Risk Management Admins Organization
Management

|*Insider Risk Management Analysis* |Access all insider risk management
alerts, cases, and notices templates. |Insider Risk Management Insider
Risk Management Analysts

|*Insider Risk Management Audit* |Allow viewing Insider Risk audit
trails. |Insider Risk Management Insider Risk Management Auditors

|*Insider Risk Management Investigation* |Access all insider risk
management alerts, cases, notices templates, and the Content Explorer
for all cases. |Insider Risk Management Insider Risk Management
Investigators

|*Insider Risk Management Permanent contribution* |This role group is
visible, but is used by background services only. |IRM Contributors

|*Insider Risk Management Temporary contribution* |This role group is
visible, but is used by background services only. |IRM Contributors

|*Knowledge Admin* |Configure knowledge, learning, assign trainings and
other intelligent features. |Knowledge Administrators

|*Manage Alerts* |View and edit settings and reports for alerts.
|Compliance Administrator

|*Organization Configuration* |Run, view, and export audit reports and
manage compliance policies for DLP, devices, and preservation.
|Compliance Administrator

|*Preview* |View a list of items that are returned from content
searches, and open each item from the list to view its contents. |Data
Investigator

|*Privacy Management Admin* |Manage policies in Privacy Management and
has access to all functionality of the solution. |Privacy Management

|*Privacy Management Analysis* |Perform investigation and remediation of
the message violations in Privacy Management. Can only view messages
metadata. |Privacy Management

|*Privacy Management Investigation* |Perform investigation, remediation,
and review message violations in Privacy Management. Can view message
metadata and the full message. |Privacy Management

|*Privacy Management Permanent contribution* |Access Privacy Management
cases as a permanent contributor. |Privacy Management

|*Privacy Management Temporary contribution* |Access Privacy Management
cases as a temporary contributor. |Privacy Management

|*Privacy Management Viewer* |Access dashboards and widgets in Privacy
Management. |Privacy Management

|*Quarantine* |Allows viewing and releasing quarantined email.
|Quarantine Administrator

|*RecordManagement* |View and edit the configuration of the records
management feature. |Compliance Administrator

|*Retention Management* |Manage retention policies, retention labels,
and retention label policies. |Compliance Administrator

|*Review* |This role lets users access review sets in eDiscovery
(Premium) cases. Users who are assigned this role can see and open the
list of cases on the *eDiscovery > Advanced* page in the Microsoft
Purview compliance portal that they’re members of. After the user
accesses an eDiscovery (Premium) case, they can select *Review sets* to
access case data. This role doesn’t allow the user to preview the
results of a collection search that’s associated with the case or do
other search or case management tasks. Users with this role can only
access the data in a review set. |Data Investigator

|*RMS Decrypt* |Decrypt RMS-protected content when exporting search
results. |Data Investigator

|*Role Management* |Manage role group membership and create or delete
custom role groups. |Organization Management

|*Search And Purge* |Lets people bulk-remove data that matches the
criteria of a content search. |Data Investigator Organization Management

|*Security Administrator* |View and edit the configuration and reports
for Security features. |Organization Management Security Administrator

|*Security Reader* |View the configuration and reports for Security
features. |Global Reader Organization Management Security Operator
Security Reader

|*Sensitivity Label Administrator* |View, create, modify, and remove
sensitivity labels. |Compliance Data Administrator Organization
Management Security Administrator

|*Sensitivity Label Reader* |View the configuration and usage of
sensitivity labels. |Global Reader Organization Management Security
Reader

|*Service Assurance View* |Download the available documents from the
Service Assurance section. Content includes independent auditing,
compliance documentation, and trust-related guidance for using Microsoft
365 features to manage regulatory compliance and security risks. |Global
Reader Organization Management Service Assurance User

|*Supervisory Review Administrator* |Manage supervisory review policies,
including which communications to review and who should do the review.
|Supervisory Review

|*Tag Contributor* |View and update membership of existing user tags.
|Organization Management Security Administrator Security Operator

|*Tag Manager* |View, update, create, and delete user tags.
|Organization Management Security Administrator

|*Tag Reader* |Read-only access to existing user tags. |Security Reader

|*Tenant AllowBlockList Manager* |Manage tenant allow block list
settings. |Security Operator

|*View-Only Audit Logs* |View and export audit reports. Because these
reports might contain sensitive information, you should only assign this
role to people with an explicit need to view this information.
|Compliance Administrator Compliance Data Administrator Global Reader
Organization Management Security Administrator Security Operator

|*View-Only Case* | |Communication Compliance Communication Compliance
Investigators Compliance Administrator Insider Risk Management Insider
Risk Management Admins Insider Risk Management Analysts Insider
RiskManagement Investigators Organization Management Privacy Management
Privacy Management Administrators Privacy Management Analysts Privacy
Management Investigators Subject Rights Request Administrators

|*View-Only Device Management* |View the configuration and reports for
the Device Management feature. |Compliance Administrator Compliance Data
Administrator Global Reader Organization Management Security
Administrator Security Operator Security Reader

|*View-Only DLP Compliance Management* |View the settings and reports
for data loss prevention (DLP) policies. |Compliance Administrator
Compliance Data Administrator Global Reader Organization Management
Security Administrator Security Operator Security Reader

|*View-Only IB Compliance Management* |View the configuration and
reports for the Information Barriers feature. |Compliance Administrator
Compliance Data Administrator Global Reader Organization Management
Security Administrator Security Operator Security Reader

|*View-Only Manage Alerts* |View the configuration and reports for the
Manage Alerts feature. |Compliance Administrator Compliance Data
Administrator Global Reader Organization Management Security
Administrator Security Operator Security Reader

|*View-Only Recipients* |View information about users and groups.
|Compliance Administrator Compliance Data Administrator Global Reader
MailFlow Administrator Organization Management

|*View-Only Record Management* |View the configuration of the records
management feature. |Compliance Administrator Compliance Data
Administrator Global Reader Organization Management

|*View-Only Retention Management* |View the configuration of retention
policies, retention labels, and retention label policies. |Compliance
Administrator Compliance Data Administrator Global Administrator
Organization Management
|===
