'''

title: Recover from a ransomware attack ms.author: chrisda author: chrisda manager: dansimp ms.date:  audience: ITPro ms.topic: article

ms.localizationpriority: medium search.appverid:

* MET150 ms.collection:
* M365-security-compliance
* m365initiative-defender-office365
* m365solution-ransomware
* highpri description: Microsoft 365 admins can learn how to recover from a ransomware attack.
ms.subservice: mdo ms.service: microsoft-365-security --

== Recover from a ransomware attack in Microsoft 365

*Applies to*

* xref:exchange-online-protection-overview.adoc[Exchange Online Protection]
* xref:defender-for-office-365.adoc[Microsoft Defender for Office 365 plan 1 and plan 2]
* xref:../defender/microsoft-365-defender.adoc[Microsoft 365 Defender]

Even if you take every precaution to protect your organization, you can still fall victim to a link:/windows/security/threat-protection/intelligence/ransomware-malware[ransomware] attack.
Ransomware is big business, and in today's threat landscape Microsoft 365 is an ever-increasing https://i.blackhat.com/USA21/Wednesday-Handouts/us-21-Cloudy-With-A-Chance-Of-APT-Novel-Microsoft-365-Attacks-In-The-Wild.pdf[target for sophisticated attacks].

The steps in this article will give you the best chance to recover data and stop the internal spread of infection.
Before you get started, consider the following items:

* There's no guarantee that paying the ransom will return access to your files.
In fact, paying the ransom can make you a target for more ransomware.
+
If you already paid, but you recovered without using the attacker's solution, contact your bank to see if they can block the transaction.
+
We also recommend that you report the ransomware attack to law enforcement, scam reporting websites, and Microsoft as described later in this article.

* It's important for you respond quickly to the attack and its consequences.
The longer you wait, the less likely it is that you can recover the affected data.

=== Step 1: Verify your backups

If you have offline backups, you can probably restore the encrypted data *after* you've removed the ransomware payload (malware) from your environment and *after* you've verified that there's no unauthorized access in your Microsoft 365 environments.

If you don't have backups, or if your backups were also affected by the ransomware, you can skip this step.

=== Step 2: Disable Exchange ActiveSync and OneDrive sync

The key point here is to stop the spread of data encryption by the ransomware.

If you suspect email as a target of the ransomware encryption, temporarily disable user access to mailboxes.
Exchange ActiveSync synchronizes data between devices and Exchange Online mailboxes.

To disable Exchange ActiveSync for a mailbox, see https://support.microsoft.com/help/2795303[How to disable Exchange ActiveSync for users in Exchange Online].

To disable other types of access to a mailbox, see:

* link:/Exchange/recipients-in-exchange-online/manage-user-mailboxes/enable-or-disable-mapi[Enable or disable MAPI for a mailbox].
* link:/Exchange/clients-and-mobile-in-exchange-online/pop3-and-imap4/enable-or-disable-pop3-or-imap4-access[Enable or Disable POP3 or IMAP4 access for a user]

Pausing OneDrive sync will help protect your cloud data from being updated by potentially infected devices.
For more information, see https://support.microsoft.com/office/2152bfa4-a2a5-4d3a-ace8-92912fb4421e[How to Pause and Resume sync in OneDrive].

=== Step 3: Remove the malware from the affected devices

Run a full, current antivirus scan on all suspected computers and devices to detect and remove the payload that's associated with the ransomware.

Don't forget to scan devices that are synchronizing data, or the targets of mapped network drives.

You can use https://www.microsoft.com/windows/comprehensive-security[Windows Defender] or (for older clients) https://www.microsoft.com/download/details.aspx?id=5201[Microsoft Security Essentials].

An alternative that will also help you remove ransomware or malware is the https://www.microsoft.com/download/details.aspx?id=9905[Malicious Software Removal Tool (MSRT)].

If these options don't work, you can try https://support.microsoft.com/help/17466[Windows Defender Offline] or https://support.microsoft.com/help/4466982[Troubleshoot problems with detecting and removing malware].

=== Step 4: Recover files on a cleaned computer or device

After you've completed the previous step to remove the ransomware payload from your environment (which will prevent the ransomware from encrypting or removing your files), you can use https://support.microsoft.com/help/17128[File History] in Windows 11, Windows 10, Windows 8.1, and by using System Protection in Windows 7 to attempt to recover your local files and folders.

*Notes*:

* Some ransomware will also encrypt or delete the backup versions, so you can't use File History or System Protection to restore files.
If that happens, you need use backups on external drives or devices that were not affected by the ransomware or OneDrive as described in the next section.
* If a folder is synchronized to OneDrive and you aren't using the latest version of Windows, there might be some limitations using File History.

=== Step 5: Recover your files in your OneDrive for Business

Files Restore in OneDrive for Business allows you to restore your entire OneDrive to a previous point in time within the last 30 days.
For more information, see https://support.microsoft.com/office/fa231298-759d-41cf-bcd0-25ac53eb8a15[Restore your OneDrive].

=== Step 6: Recover deleted email

In the rare case that the ransomware deleted all your email, you can probably recover the deleted items.
For more information, see:

* link:/exchange/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages[Recover deleted messages in a user's mailbox]
* https://support.microsoft.com/office/49e81f3c-c8f4-4426-a0b9-c0fd751d48ce[Recover deleted items in Outlook for Windows]

=== Step 7: Re-enable Exchange ActiveSync and OneDrive sync

After you've cleaned your computers and devices and recovered your data, you can re-enable Exchange ActiveSync and OneDrive sync that you previously disabled in <<step-2-disable-exchange-activesync-and-onedrive-sync,Step 2>>.

=== Step 8 (Optional): Block OneDrive sync for specific file extensions

After you've recovered, you can prevent OneDrive for Business clients from synchronizing the file types that were affected by this ransomware.
For more information, see link:/powershell/module/sharepoint-online/set-spotenantsyncclientrestriction[Set-SPOTenantSyncClientRestriction]

=== Report the attack

==== Contact law enforcement

You should contact your local or federal law enforcement agencies.
For example, if you are in the United States you can contact the https://www.fbi.gov/contact-us/field[FBI local field office], http://www.ic3.gov/complaint/default.aspx[IC3] or http://www.secretservice.gov/[Secret Service].

==== Submit a report to your country's scam reporting website

Scam reporting websites provide information about how to prevent and avoid scams.
They also provide mechanisms to report if you were victim of scam.

* Australia: http://www.scamwatch.gov.au/[SCAMwatch]
* Canada: http://www.antifraudcentre-centreantifraude.ca/[Canadian Anti-Fraud Centre]
* France: http://www.ssi.gouv.fr/[Agence nationale de la sécurité des systèmes d'information]
* Germany: https://www.bsi.bund.de/DE/Home/home_node.html[Bundesamt für Sicherheit in der Informationstechnik]
* Ireland: http://www.garda.ie/[a Garda Síochána]
* New Zealand: http://www.consumeraffairs.govt.nz/scams[Consumer Affairs Scams]
* Switzerland https://www.ncsc.admin.ch/ncsc/de/home.html[Nationales Zentrum für Cybersicherheit NCSC]
* United Kingdom: http://www.actionfraud.police.uk/[Action Fraud]
* United States: http://www.onguardonline.gov/[On Guard Online]

If your country isn't listed, ask your local or federal law enforcement agencies.

==== Submit email messages to Microsoft

You can report phishing messages that contain ransomware by using one of several methods.
For more information, see xref:report-junk-email-messages-to-microsoft.adoc[Report messages and files to Microsoft].

=== Additional ransomware resources

Key information from Microsoft:

* https://blogs.microsoft.com/on-the-issues/2021/07/20/the-growing-threat-of-ransomware/[The growing threat of ransomware], Microsoft On the Issues blog post on July 20, 2021
* link:/security/compass/human-operated-ransomware[Human-operated ransomware]
* link:/security/compass/protect-against-ransomware[Rapidly protect against ransomware and extortion]
* https://www.microsoft.com/security/business/microsoft-digital-defense-report[2021 Microsoft Digital Defense Report] (see pages 10-19)
* https://security.microsoft.com/threatanalytics3/05658b6c-dc62-496d-ad3c-c6a795a33c27/overview[Ransomware: A pervasive and ongoing threat] threat analytics report in the Microsoft 365 Defender portal

Microsoft 365:

* link:/microsoft-365/solutions/ransomware-protection-microsoft-365[Deploy ransomware protection for your Microsoft 365 tenant]
* https://azure.microsoft.com/resources/maximize-ransomware-resiliency-with-azure-and-microsoft-365/[Maximize Ransomware Resiliency with Azure and Microsoft 365]
* link:/compliance/assurance/assurance-malware-and-ransomware-protection[Malware and ransomware protection]
* https://support.microsoft.com//windows/protect-your-pc-from-ransomware-08ed68a7-939f-726c-7e84-a72ba92c01c3[Protect your Windows PC from ransomware]
* link:/sharepoint/troubleshoot/security/handling-ransomware-in-sharepoint-online[Handling ransomware in SharePoint Online]
* https://security.microsoft.com/threatanalytics3?page_size=30&filters=tags%3DRansomware&ordering=-lastUpdatedOn&fields=displayName,alertsCount,impactedEntities,reportType,createdOn,lastUpdatedOn,tags,flag[Threat analytics reports for ransomware] in the Microsoft 365 Defender portal

Microsoft 365 Defender:

* link:/microsoft-365/security/defender/advanced-hunting-find-ransomware[Find ransomware with advanced hunting]

Microsoft Azure:

* https://azure.microsoft.com/resources/azure-defenses-for-ransomware-attack/[Azure Defenses for Ransomware Attack]
* https://azure.microsoft.com/resources/maximize-ransomware-resiliency-with-azure-and-microsoft-365/[Maximize Ransomware Resiliency with Azure and Microsoft 365]
* link:/security/compass/backup-plan-to-protect-against-ransomware[Backup and restore plan to protect against ransomware]
* https://www.youtube.com/watch?v=VhLOr2_1MCg[Help protect from ransomware with Microsoft Azure Backup] (26 minute video)
* link:/azure/security/fundamentals/recover-from-identity-compromise[Recovering from systemic identity compromise]
* link:/azure/sentinel/fusion#ransomware[Advanced multistage attack detection in Microsoft Sentinel]
* https://techcommunity.microsoft.com/t5/azure-sentinel/what-s-new-fusion-detection-for-ransomware/ba-p/2621373[Fusion Detection for Ransomware in Microsoft Sentinel]

Microsoft Defender for Cloud Apps:

* link:/cloud-app-security/anomaly-detection-policy[Create anomaly detection policies in Defender for Cloud Apps]

Microsoft Security team blog posts:

* https://www.microsoft.com/security/blog/2021/09/07/3-steps-to-prevent-and-recover-from-ransomware/[3 steps to prevent and recover from ransomware (September 2021)]
* https://www.microsoft.com/security/blog/2021/09/20/a-guide-to-combatting-human-operated-ransomware-part-1/[A guide to combatting human-operated ransomware: Part 1 (September 2021)]
+
Key steps on how Microsoft's Detection and Response Team (DART) conducts ransomware incident investigations.

* https://www.microsoft.com/security/blog/2021/09/27/a-guide-to-combatting-human-operated-ransomware-part-2/[A guide to combatting human-operated ransomware: Part 2 (September 2021)]
+
Recommendations and best practices.

* https://www.microsoft.com/security/blog/2021/05/26/becoming-resilient-by-understanding-cybersecurity-risks-part-4-navigating-current-threats/[Becoming resilient by understanding cybersecurity risks: Part 4--navigating current threats (May 2021)]
+
See the *Ransomware* section.

* https://www.microsoft.com/security/blog/2020/03/05/human-operated-ransomware-attacks-a-preventable-disaster/[Human-operated ransomware attacks: A preventable disaster (March 2020)]
+
Includes attack chain analyses of actual attacks.

* https://www.microsoft.com/security/blog/2019/12/16/ransomware-response-to-pay-or-not-to-pay/[Ransomware response--to pay or not to pay?
(December 2019)]
* https://www.microsoft.com/security/blog/2019/12/17/norsk-hydro-ransomware-attack-transparency/[Norsk Hydro responds to ransomware attack with transparency (December 2019)]
