= 
dansimp

== How do I report a suspicious email or file to Microsoft?

{empty}[!INCLUDE link:../includes/mdo-trial-banner.md[MDO Trial banner]]

*Applies to* - link:exchange-online-protection-overview.md[Exchange
Online Protection] - link:defender-for-office-365.md[Microsoft Defender
for Office 365 plan 1 and plan 2] -
link:../defender/microsoft-365-defender.md[Microsoft 365 Defender]

Wondering what to do with suspicious emails or files? In Microsoft 365
organizations with mailboxes in Exchange Online or standalone Exchange
Online Protection (EOP) organizations without Exchange Online mailboxes,
_users_ and _admins_ have different ways to report a suspicious email
message, URL, or email attachment to Microsoft.

In addition, Microsoft 365 organizations with Microsoft Defender for
Endpoint admins also have several methods for reporting files.

Watch this video that shows more information about the unified
submissions experience. > [!VIDEO
https://www.microsoft.com/en-us/videoplayer/embed/RE50HhM]

=== Report a suspicious email to Microsoft

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Method |Submission type |Description
|link:admin-submission.md[Use the Submissions portal to submit suspected
spam&#44; phish&#44; URLs&#44; and email attachments to Microsoft] |Admin |The
recommended reporting method for admins in organizations with Exchange
Online mailboxes (not available in standalone EOP).

|link:enable-the-report-message-add-in.md[Enable the Report Message or
the Report Phishing add-ins] |User |Works with Outlook and Outlook on
the web (formerly known as Outlook Web App). Depending on your
subscription, messages that users reported with the add-ins are
available in link:admin-submission.md[the Admin Submissions portal],
link:air-view-investigation-results.md[Automated investigation and
response (AIR) results], the
link:view-email-security-reports.md#user-reported-messages-report[User-reported
messages report], and
link:++threat-explorer-views.md#email--submissions++[Explorer]. You can
configure reported messages to be copied or redirected to a mailbox that
you specify. For more information, see link:user-submission.md[User
submissions policies].

|link:report-false-positives-and-false-negatives.md[Report false
positives and false negatives in Outlook] |User |Submit false positives
(good email that was blocked or sent to junk folder) and false negatives
(unwanted email or phish that was delivered to the inbox) to Exchange
Online Protection (EOP) using the Report Message feature.

|link:/exchange/security-and-compliance/mail-flow-rules/use-rules-to-see-what-users-are-reporting-to-microsoft[Use
mail flow rules to see what users are reporting to Microsoft] |Admin
|Learn how to create a mail flow rule (also known as a transport rule)
that notifies you when users report messages to Microsoft for analysis.

|link:../intelligence/submission-guide.md[Submit files for analysis]
|Admin |Submit email attachments and other suspected files to Microsoft
for analysis.
|===

____
[!NOTE] When you report an email entity to Microsoft, a copy is made of
everything associated with the email to include it in the reviews. This
copy includes the email content, the email headers, and related data
about the email routing. Attachments in the message are also included.

Microsoft treats your feedback as your organization’s permission to
analyze all of the information and to improve the suspected message
reporting and review process. Your message is stored securely until it
is deleted no later than 30 days after you provided it. Microsoft may
read your submitted message and attachments, however, your email is
still treated as confidential between you and Microsoft. Your submission
is not provided to any other party for the review process.
____
