= 
chrisda

== Safe Attachments for SharePoint, OneDrive, and Microsoft Teams

{empty}[!INCLUDE link:../includes/mdo-trial-banner.md[MDO Trial banner]]

*Applies to* - link:defender-for-office-365.md[Microsoft Defender for
Office 365 plan 1 and plan 2] -
link:../defender/microsoft-365-defender.md[Microsoft 365 Defender]

Safe Attachments for SharePoint, OneDrive, and Microsoft Teams in
link:defender-for-office-365-whats-new.md[Microsoft Defender for Office
365] provides an additional layer of protection for files that have
already been scanned asynchronously by the
link:anti-malware-protection-for-spo-odfb-teams-about.md[common virus
detection engine in Microsoft 365]. Safe Attachments for SharePoint,
OneDrive, and Microsoft Teams helps detect and block existing files that
are identified as malicious in team sites and document libraries.

Safe Attachments for SharePoint, OneDrive, and Microsoft Teams is not
enabled by default. To turn it on, see
link:safe-attachments-for-spo-odfb-teams-configure.md[Turn on Safe
Attachments for SharePoint&#44; OneDrive&#44; and Microsoft Teams].

=== How Safe Attachments for SharePoint, OneDrive, and Microsoft Teams works

When Safe Attachments for SharePoint, OneDrive, and Microsoft Teams is
enabled and identifies a file as malicious, the file is locked using
direct integration with the file stores. The following image shows an
example of a malicious file detected in a library.

:::image type=``content''
source=``../../media/2bba71cc-7ad1-4799-8b9d-d56f923db3a7.png''
alt-text=``The files in OneDrive for Business with one detected as
malicious''
lightbox=``../../media/2bba71cc-7ad1-4799-8b9d-d56f923db3a7.png'':::

Although the blocked file is still listed in the document library and in
web, mobile, or desktop applications, people can’t open, copy, move, or
share the file. But they can delete the blocked file.

Here’s an example of what a blocked file looks like on a mobile device:

:::image type=``content''
source=``../../media/cb1c1705-fd0a-45b8-9a26-c22503011d54.png''
alt-text=``The option to delete a blocked file from OneDrive for
Business from the OneDrive mobile app''
lightbox=``../../media/cb1c1705-fd0a-45b8-9a26-c22503011d54.png'':::

By default, people can download a blocked file. Here’s what downloading
a blocked file looks like on a mobile device:

:::image type=``content''
source=``../../media/be288a82-bdd8-4371-93d8-1783db3b61bc.png''
alt-text=``The option to download a blocked file in OneDrive for
Business''
lightbox=``../../media/be288a82-bdd8-4371-93d8-1783db3b61bc.png'':::

SharePoint Online admins can prevent people from downloading malicious
files. For instructions, see
link:safe-attachments-for-spo-odfb-teams-configure.md#step-2-recommended-use-sharepoint-online-powershell-to-prevent-users-from-downloading-malicious-files[Use
SharePoint Online PowerShell to prevent users from downloading malicious
files].

To learn more about the user experience when a file has been detected as
malicious, see
https://support.microsoft.com/office/01e902ad-a903-4e0f-b093-1e1ac0c37ad2[What
to do when a malicious file is found in SharePoint Online&#44; OneDrive&#44; or
Microsoft Teams].

=== View information about malicious files detected by Safe Attachments for SharePoint, OneDrive, and Microsoft Teams

Files that are identified as malicious by Safe Attachments for
SharePoint, OneDrive, and Microsoft Teams will show up in
link:reports-defender-for-office-365.md[reports for Microsoft Defender
for Office 365] and in link:threat-explorer-about.md[Explorer (and
real-time detections)].

When a file is identified as malicious by Safe Attachments for
SharePoint, OneDrive, and Microsoft Teams, the file is also available in
quarantine, but only to admins. For more information, see
link:quarantine-admin-manage-messages-files.md#use-the-microsoft-365-defender-portal-to-manage-quarantined-files-in-defender-for-office-365[Manage
quarantined files in Defender for Office 365].

=== Keep these points in mind

* Defender for Office 365 will not scan every single file in SharePoint
Online, OneDrive for Business, or Microsoft Teams. This is by design.
Files are scanned asynchronously. The process uses sharing and guest
activity events along with smart heuristics and threat signals to
identify malicious files.
* Make sure your SharePoint sites are configured to use the
link:/sharepoint/guide-to-sharepoint-modern-experience[Modern
experience]. Defender for Office 365 protection applies whether the
Modern experience or the Classic view is used; however, visual
indicators that a file is blocked are available only in the Modern
experience.
* Safe Attachments for SharePoint, OneDrive, and Microsoft Teams is part
of your organization’s overall threat protection strategy, which
includes anti-spam and anti-malware protection in Exchange Online
Protection (EOP), as well as Safe Links and Safe Attachments in
Microsoft Defender for Office 365. To learn more, see
link:protect-against-threats.md[Protect against threats in Office 365].
