= Secure by default in Office 365
:audience: ITPro
:author: dansimp
:description: Learn more about the secure by default setting in Exchange Online Protection (EOP)
:f1.keywords: ["NOCSH"]
:manager: dansimp
:ms.author: dansimp
:ms.collection: ["M365-security-compliance"]
:ms.date: 06/28/2021
:ms.localizationpriority: medium
:ms.service: microsoft-365-security
:ms.subservice: mdo
:ms.topic: conceptual
:search.appverid: ["MET150", "MOE150"]

== Secure by default in Office 365

[!INCLUDE xref:../includes/mdo-trial-banner.adoc[MDO Trial banner]]

*Applies to*

* xref:exchange-online-protection-overview.adoc[Exchange Online Protection]
* xref:defender-for-office-365.adoc[Microsoft Defender for Office 365 plan 1 and plan 2]
* xref:../defender/microsoft-365-defender.adoc[Microsoft 365 Defender]

"Secure by default" is a term used to define the default settings that are most secure as possible.

However, security needs to be balanced with productivity.
This can include balancing across:

* *Usability*: Settings should not get in the way of user productivity.
* *Risk*: Security might block important activities.
* *Legacy settings*: Some configurations for older products and features might need to be maintained for business reasons, even if new, modern settings are improved.

Microsoft 365 organizations with mailboxes in Exchange Online are protected by Exchange Online Protection (EOP).
This protection includes:

* Email with suspected malware will automatically be quarantined.
Whether recipients are notified about quarantined malware messages is controlled by the quarantine policy and the settings in the anti-malware policy.
For more information, see xref:configure-anti-malware-policies.adoc[Configure anti-malware policies in EOP].
* Email identified as high confidence phishing will be handled according to the anti-spam policy action.
See xref:configure-your-spam-filter-policies.adoc[Configure anti-spam policies in EOP].

For more information about EOP, see xref:exchange-online-protection-overview.adoc[Exchange Online Protection overview].

Because Microsoft wants to keep our customers secure by default, some tenants overrides are not applied for malware or high confidence phishing.
These overrides include:

* Allowed sender lists or allowed domain lists (anti-spam policies)
* Outlook Safe Senders
* IP Allow List (connection filtering)
* Exchange mail flow rules (also known as transport rules)

More information on these overrides can be found in xref:create-safe-sender-lists-in-office-365.adoc[Create safe sender lists].

____
[!NOTE] We have deprecated the *Move message to Junk Email folder* action for a *High confidence phishing email* verdict in EOP anti-spam policies.
Anti-spam policies that use this action for high confidence phishing messages will be converted to *Quarantine message*.
The *Redirect message to email address* action for high confidence phishing messages is unaffected.
____

Secure by default is not a setting that can be turned on or off, but is the way our filtering works out of the box to keep potentially dangerous or unwanted messages out of your mailboxes.
Malware and high confidence phishing messages should be quarantined.
By default, only admins can manage messages that are quarantined as malware or high confidence phishing, and they can also report false positives to Microsoft from there.
For more information, see xref:manage-quarantined-messages-and-files.adoc[Manage quarantined messages and files as an admin in EOP].

=== More on why we're doing this

The spirit of being secure by default is: we're taking the same action on the message that you would take if you knew the message malicious, even when a configured exception would otherwise allow the message to be delivered.
This is the same approach that we've always used on malware, and now we're extending this same behavior to high confidence phishing messages.

Our data indicates that a user is 30 times more likely to click a malicious link in messages in the Junk Email folder versus Quarantine.
Our data also indicates that the false positive rate (good messages marked as bad) for high confidence phishing messages is very low, and admins can resolve any false positives with admin submissions.

We also determined that the allowed sender and allowed domain lists in anti-spam policies and Safe Senders in Outlook were too broad and were causing more harm than good.

To put it another way: as a security service, we're acting on your behalf to prevent your users from being compromised.

=== Exceptions

You should only consider using overrides in the following scenarios:

* Phishing simulations: Simulated attacks can help you identify vulnerable users before a real attack impacts your organization.
To prevent phishing simulation messages from being filtered, see link:/microsoft-365/security/office-365-security/configure-advanced-delivery#use-the-microsoft-365-defender-portal-to-configure-third-party-phishing-simulations-in-the-advanced-delivery-policy[Configure third-party phishing simulations in the advanced delivery policy].
* Security/SecOps mailboxes: Dedicated mailboxes used by security teams to get unfiltered messages (both good and bad).
Teams can then review to see if they contain malicious content.
For more information, see link:/microsoft-365/security/office-365-security/configure-advanced-delivery#use-the-microsoft-365-defender-portal-to-configure-secops-mailboxes-in-the-advanced-delivery-policy[Configure SecOps mailboxes in the advanced delivery policy].
* Third-party filters: Secure by default only applies when the MX record for your domain is set to Exchange Online Protection (contoso.mail.protection.outlook.com).
If it's set to another service or device, it is possible to override Secure by default with a link:/exchange/security-and-compliance/mail-flow-rules/use-rules-to-set-scl[Transport Rule] to bypass all spam filtering.
When Microsoft detects messages as High Confidence Phish with this rule in place, they still deliver to the Inbox.
* False positives: You might want to temporarily allow certain messages that are still being analyzed by Microsoft xref:admin-submission.adoc[via Admin submissions].
As with all overrides, it is recommended that they are temporary.
