'''

title: Sending mail to Microsoft 365 f1.keywords:

* NOCSH ms.author: chrisda author: chrisda manager: dansimp ms.date:  audience: ITPro ms.topic: overview

ms.localizationpriority: medium search.appverid:

* MET150 ms.assetid: f9d4b5b6-8f4c-44df-9b06-2f9b3058ca20 ms.collection:
* M365-security-compliance ms.custom:
* seo-marvel-apr2020 description: Learn as a guest sender, how can you increase the ability to deliver email to users in Microsoft 365.
Also learn how to report junk email & phishing attempts as a guest.
ms.subservice: mdo ms.service: microsoft-365-security --

== Sending mail to Microsoft 365

These articles help external senders improve their reputation and increase their ability to deliver email to users at Microsoft 365.
They also provide some information about how you can report junk email and phishing attempts even if you aren't a Microsoft 365 user yourself.

If you're not a customer, but are trying to send mail to someone in who is, you're in the right place.
If you're an admin and you need help with fighting spam, this isn't the right section for you.
Instead, go to xref:anti-spam-protection.adoc[anti-spam] and xref:anti-malware-protection.adoc[anti-malware].

|===
| For information about... | See...

| Services provided to email system admins that are sending individual and bulk email to customers.
| xref:services-for-non-customers.adoc[Services for non-customers sending mail to Office 365]

| How to fix problems reaching customers at Microsoft 365 through email.
Best practices for sending bulk mail to Microsoft 365 recipients.
| xref:troubleshooting-mail-sent-to-office-365.adoc[Troubleshooting mail sent to Office 365]

| How Microsoft 365 prevents junk email, including phishing and spoofing email, from being sent to our customers.
| xref:anti-spam-protection.adoc[Anti-spam protection in Microsoft 365]

| How you, an admin sending email to Microsoft 365 customers, can avoid having email blocked by adhering to our anti-spam policies.
This is the legal stuff you need to know.
| xref:reference-policies-practices-and-guidelines.adoc[Reference: Policies, practices, and guidelines]
|===
