= 
chrisda

== Sending mail to Microsoft 365

These articles help external senders improve their reputation and
increase their ability to deliver email to users at Microsoft 365. They
also provide some information about how you can report junk email and
phishing attempts even if you aren’t a Microsoft 365 user yourself.

If you’re not a customer, but are trying to send mail to someone in who
is, you’re in the right place. If you’re an admin and you need help with
fighting spam, this isn’t the right section for you. Instead, go to
link:anti-spam-protection-about.md[anti-spam] and
link:anti-malware-protection-about.md[anti-malware].

[width="100%",cols="50%,50%",options="header",]
|===
|For information about… |See…
|Services provided to email system admins that are sending individual
and bulk email to customers.
|link:services-for-non-customers.md[Services for non-customers sending
mail to Office 365]

|How to fix problems reaching customers at Microsoft 365 through email.
Best practices for sending bulk mail to Microsoft 365 recipients.
|link:mail-flow-troubleshooting.md[Troubleshooting mail sent to Office
365]

|How Microsoft 365 prevents junk email, including phishing and spoofing
email, from being sent to our customers.
|link:anti-spam-protection-about.md[Anti-spam protection in Microsoft
365]

|How you, an admin sending email to Microsoft 365 customers, can avoid
having email blocked by adhering to our anti-spam policies. This is the
legal stuff you need to know.
|link:reference-policies-practices-and-guidelines.md[Reference:
Policies&#44; practices&#44; and guidelines]
|===
