= SIEM integration with Microsoft Defender for Office 365
:audience: ITPro
:author: denisebmsft
:description: Integrate your organization's SIEM server with Microsoft Defender for Office 365 and related threat events in the Office 365 Activity Management API.
:f1.keywords: ["NOCSH"]
:manager: dansimp
:ms.assetid: eb56b69b-3170-4086-82cf-ba40a530fa1b
:ms.author: deniseb
:ms.collection: ["M365-security-compliance"]
:ms.custom: seo-marvel-apr2020
:ms.date: 08/21/2020
:ms.localizationpriority:
:ms.service: microsoft-365-security
:ms.subservice: mdo
:ms.topic: article
:search.appverid: ["MET150", "MOE150"]

== SIEM integration with Microsoft Defender for Office 365

*Applies to*

* xref:exchange-online-protection-overview.adoc[Exchange Online Protection]
* xref:defender-for-office-365.adoc[Microsoft Defender for Office 365 plan 1 and plan 2]
* xref:../defender/microsoft-365-defender.adoc[Microsoft 365 Defender]

[!INCLUDE xref:../includes/mdo-trial-banner.adoc[MDO Trial banner]]

If your organization is using a security information and event management (SIEM) server, you can integrate Microsoft Defender for Office 365 with your SIEM server.
You can set up this integration by using the link:/office/office-365-management-api/office-365-management-activity-api-reference[Office 365 Activity Management API].

SIEM integration enables you to view information, such as malware or phish detected by Microsoft Defender for Office 365, in your SIEM server reports.

* To see an example of SIEM integration with Microsoft Defender for Office 365, see https://techcommunity.microsoft.com/t5/microsoft-security-and/improve-the-effectiveness-of-your-soc-with-office-365-atp-and/ba-p/1525185[Tech Community blog: Improve the Effectiveness of your SOC with Defender for Office 365 and the O365 Management API].
* To learn more about the Office 365 Management APIs, see link:/office/office-365-management-api/office-365-management-apis-overview[Office 365 Management APIs overview].

=== How SIEM integration works

The Office 365 Activity Management API retrieves information about user, admin, system, and policy actions and events from your organization's Microsoft 365 and Azure Active Directory activity logs.
If your organization has Microsoft Defender for Office 365 Plan 1 or 2, or Office 365 E5, you can use the link:/office/office-365-management-api/office-365-management-activity-api-schema#office-365-advanced-threat-protection-and-threat-investigation-and-response-schema[Microsoft Defender for Office 365 schema].

Recently, events from automated investigation and response capabilities in link:defender-for-office-365.md#microsoft-defender-for-office-365-plan-1-and-plan-2[Microsoft Defender for Office 365 Plan 2] were added to the Office 365 Management Activity API.
In addition to including data about core investigation details such as ID, name and status, the API also contains high-level information about investigation actions and entities.

The SIEM server or other similar system polls the *audit.general* workload to access detection events.
To learn more, see link:/office/office-365-management-api/get-started-with-office-365-management-apis[Get started with Office 365 Management APIs].

=== Enum: AuditLogRecordType - Type: Edm.Int32

==== AuditLogRecordType

The following table summarizes the values of *AuditLogRecordType* that are relevant for Microsoft Defender for Office 365 events: +  +

|===
| Value | Member name | Description

| 28
| ThreatIntelligence
| Phishing and malware events from Exchange Online Protection and Microsoft Defender for Office 365.

| 41
| ThreatIntelligenceUrl
| Safe Links time-of-block and block override events from Microsoft Defender for Office 365.

| 47
| ThreatIntelligenceAtpContent
| Phishing and malware events for files in SharePoint Online, OneDrive for Business, and Microsoft Teams, from Microsoft Defender for Office 365.

| 64
| AirInvestigation
| Automated investigation and response events, such as investigation details and relevant artifacts, from Microsoft Defender for Office 365 Plan 2.
|===

____
[!IMPORTANT] You must have either the global administrator or Security Administrator role assigned in the Microsoft 365 Defender portal to set up SIEM integration with Microsoft Defender for Office 365.
For more information, see xref:permissions-microsoft-365-security-center.adoc[Permissions in the Microsoft 365 Defender portal].

Audit logging must be turned on for your Microsoft 365 environment.
To get help with this, see xref:../../compliance/turn-audit-log-search-on-or-off.adoc[Turn audit log search on or off].
____

=== See also

xref:office-365-ti.adoc[Office 365 threat investigation and response]

xref:automated-investigation-response-office.adoc[Automated investigation and response (AIR) in Office 365]
