= 
denisebmsft

== Security Information and Event Management (SIEM) server integration with Microsoft 365 services and applications

*Applies to* - link:eop-about.md[Exchange Online Protection] -
link:defender-for-office-365.md[Microsoft Defender for Office 365 plan 1
and plan 2] - link:../defender/microsoft-365-defender.md[Microsoft 365
Defender]

{empty}[!INCLUDE link:../includes/mdo-trial-banner.md[MDO Trial banner]]

=== Summary

Is your organization using or planning to get a Security Information and
Event Management (SIEM) server? You might be wondering how it integrates
with Microsoft 365 or Office 365. This article provides a list of
resources you can use to integrate your SIEM server with Microsoft 365
services and applications.

____
[!TIP] If you don’t have a SIEM server yet and are exploring your
options, consider *link:/azure/sentinel/overview[Microsoft Sentinel]*.
____

=== Do I need a SIEM server?

Whether you need a SIEM server depends on many factors, such as your
organization’s security requirements and where your data resides.
Microsoft 365 includes a wide variety of security features that meet
many organizations’ security needs without additional servers, such as a
SIEM server. Some organizations have special circumstances that require
the use of a SIEM server. Here are some examples:

* _Fabrikam_ has some content and applications on premises, and some in
the cloud (they have a hybrid cloud deployment). To get security reports
across all their content and applications, Fabrikam has implemented a
SIEM server.
* _Contoso_ is a financial services organization that has particularly
stringent security requirements. They have added a SIEM server to their
environment to take advantage of the extra security protection they
require.

=== SIEM server integration with Microsoft 365

A SIEM server can receive data from a wide variety of Microsoft 365
services and applications. The following table lists several Microsoft
365 services and applications, along with SIEM server inputs and
resources to learn more.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Microsoft 365 Service or Application |SIEM server inputs/methods
|Resources to learn more
|link:defender-for-office-365.md[Microsoft Defender for Office 365]
|Audit logs |link:siem-integration-with-office-365-ti.md[SIEM
integration with Microsoft Defender for Office 365]

|link:/windows/security/threat-protection/[Microsoft Defender for
Endpoint] |HTTPS endpoint hosted in Azure
|link:../defender-endpoint/configure-siem.md[Pull alerts to your SIEM
tools]

|link:/cloud-app-security/what-is-cloud-app-security[Microsoft Defender
for Cloud Apps] |Log integration |link:/cloud-app-security/siem[SIEM
integration with Microsoft Defender for Cloud Apps]
|===

____
[!TIP] Take a look at link:/azure/sentinel/overview[Microsoft Sentinel].
Microsoft Sentinel comes with connectors for Microsoft solutions. These
connectors are available ``out of the box'' and provide for real-time
integration. You can use Microsoft Sentinel with your Microsoft 365
Defender solutions and Microsoft 365 services, including Office 365,
Azure AD, Microsoft Defender for Identity, Microsoft Defender for Cloud
Apps, and more.
____

==== Audit logging must be turned on

Make sure that audit logging is turned on before you configure SIEM
server integration.

* For SharePoint Online, OneDrive for Business, and Azure Active
Directory, see
link:../../compliance/turn-audit-log-search-on-or-off.md[Turn auditing
on or off].
* For Exchange Online, see
link:../../compliance/enable-mailbox-auditing.md[Manage mailbox
auditing].

=== Integration steps if your SIEM is Microsoft Sentinel

Be sure that your current plan allows for Microsoft Sentinel integration
(for example, you have Microsoft Defender for Office 365 Plan 2 or
higher), and that your account in Microsoft Defender for Office 365 or
Microsoft 365 Defender is a _Security Administrator_. Finally, be sure
that you have _Write permissions in Microsoft Sentinel_.

[arabic]
. Navigate to Microsoft Sentinel.
. On the navigation to the left of the screen *Configuration* > *Data
connectors*.
. *Search for* Microsoft 365 Defender and select the *Microsoft 365
Defender (preview) connector*.
. On the right of your screen select *Open Connector Page*.
. Under *Configuration* > select *Connect incidents & alerts*
[arabic]
.. Turn off all Microsoft incident creation rules for the products
currently selected.
. Scroll to *Microsoft Defender for Office 365* in the *Connect events*
section of the page.

Note that you can choose tables from _any other Microsoft Defender
product_ you find helpful and applicable while completing the final
step, (below).

[arabic, start=7]
. Select *EmailEvents*, *EmailUrlInfo*, *EmailAttachmentInfo*, and
*EmailPostDeliveryEvents* > and *Apply Changes*.

=== More resources

link:/azure/security-center/security-center-partner-integration#exporting-data-to-a-siem[Integrate
security solutions in Microsoft Defender for Cloud]

link:/graph/security-integration[Integrate Microsoft Graph Security API
alerts with a SIEM]
