= 
dansimp

== How do I report a suspicious email or file to Microsoft?

{empty}[!INCLUDE link:../includes/mdo-trial-banner.md[MDO Trial banner]]

*Applies to* - link:eop-about.md[Exchange Online Protection] -
link:defender-for-office-365.md[Microsoft Defender for Office 365 plan 1
and plan 2] - link:../defender/microsoft-365-defender.md[Microsoft 365
Defender]

Wondering what to do with suspicious emails or files? In Microsoft 365
organizations with mailboxes in Exchange Online or standalone Exchange
Online Protection (EOP) organizations without Exchange Online mailboxes,
_users_ and _admins_ have different ways to report a suspicious email
message, URL, or email attachment to Microsoft.

In addition, admins in Microsoft 365 organizations with Microsoft
Defender for Endpoint also have several methods for reporting files.

Watch this video that shows more information about the unified
submissions experience. > [!VIDEO
https://www.microsoft.com/en-us/videoplayer/embed/RE50HhM]

=== Report suspicious email messages to Microsoft

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Method |Submission type |Comments
|link:submissions-outlook-report-messages.md#use-the-built-in-report-button-in-outlook-on-the-web[The
built-in Report button] |User |Currently, this method is available only
in Outlook on the web (formerly known as Outlook Web App or OWA).

|link:submissions-outlook-report-messages.md#use-the-report-message-and-report-phishing-add-ins-in-outlook[The
Microsoft Report Message and Report Phishing add-ins] |User |These free
add-ins work in Outlook on all available platforms. For installation
instructions, see
link:submissions-users-report-message-add-in-configure.md[Enable the
Report Message or the Report Phishing add-ins].

|link:submissions-admin.md[The Submissions page in the Microsoft 365
Defender portal] |Admin |Admins use this method to submit good (false
positive) and bad (false negative) entities including user-reported
messages to Microsoft for further analysis. Tabs include *Email*, *Email
attachments*, *URLs*, and *Files*. The Submissions page is available to
organizations who have Exchange Online mailboxes as part of a Microsoft
365 subscription (not available in standalone EOP).
|===

link:submissions-user-reported-messages-files-custom-mailbox.md[User
reported message settings] allow admins to configure whether user
reported messages go to a specified reporting mailbox, to Microsoft, or
both. Depending on your subscription, user reported messages are
available in the following locations in the Microsoft 365 Defender
portal:

* link:submissions-admin.md[The Submissions page]
* link:air-view-investigation-results.md[Automated investigation and
response (AIR) results]
* link:reports-email-security.md#user-reported-messages-report[The
User-reported messages report]
* link:++threat-explorer-views.md#email--submissions++[Threat Explorer]

Admins can use mail flow rules (also known as transport rules) to notify
specified email address when users report messages to Microsoft for
analysis. For more information, see
link:/exchange/security-and-compliance/mail-flow-rules/use-rules-to-see-what-users-are-reporting-to-microsoft[Use
mail flow rules to see what users are reporting to Microsoft].

Admins can also submit email attachments and other suspected files to
Microsoft for analysis using the sample submission portal at
https://www.microsoft.com/wdsi/filesubmission. For more information, see
link:../intelligence/submission-guide.md[Submit files for analysis].

____
[!NOTE] When you report an email entity to Microsoft, we copy everything
associated with the email to include it in our continual algorithm
reviews. This copy includes the email content, email headers, and
related data about email routing. Any message attachments are also
included.

Microsoft treats your feedback as your organization’s permission for us
to analyze all of the previously described information to fine tune the
message hygiene algorithms. We hold your message in our secure audited
datacenters in the USA. The submission is deleted as soon as it’s no
longer required. Microsoft personnel might read your submitted messages
and attachments, which is normally not permitted for email in Microsoft
365. However, your email is still treated as confidential between you
and Microsoft, and we will not provide your email or attachments to any
other party as part of the review process.

Information is blocked from going outside the organization when data is
not supposed to leave the tenant boundary for compliance purposes (for
example, in U.S. Government organizations: Microsoft 365 GCC, GCC High,
and DoD). Reporting a message or file to Microsoft from one of these
organizations will have the following message in the result details:

*Further investigation needed*. Your tenant does not allow data to leave
the environment, so we could not find anything with an initial scan.
You’ll need to contact Microsoft support to have this item reviewed.
____
