= Azure Information Protection support for Office 365 operated by 21Vianet
:audience: Admin
:author: skjerland
:description: Learn more about Azure Information Protection (AIP) for Office 365 operated by 21Vianet and how to configure it for customers in China.
:f1.keywords: ["NOCSH"]
:manager: scotv
:monikerRange: o365-21vianet
:ms.author: sharik
:ms.collection: ["M365-subscription-management", "Adm_O365", "Adm_NonTOC"]
:ms.custom: AdminSurgePortfolio
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: overview
:search.appverid: ["MET150", "GEU150", "GEA150"]

== Azure Information Protection support for Office 365 operated by 21Vianet

This article covers the differences between Azure Information Protection (AIP) support for Office 365 operated by 21Vianet and commercial offerings, as well as specific instructions for configuring AIP for customers in China&mdash;including how to install the AIP on-premises scanner and manage content scan jobs.

=== Differences between AIP for Office 365 operated by 21Vianet and commercial offerings

While our goal is to deliver all commercial features and functionality to customers in China with our AIP for Office 365 operated by 21Vianet offer, there's some missing functionality that we'd like to highlight.

The following list includes the existing gaps between AIP for Office 365 operated by 21Vianet and our commercial offerings as of January 2021:

* Active Directory Rights Management Services (AD RMS) encryption is supported only in Microsoft 365 Apps for enterprise (build 11731.10000 or later).
Office Professional Plus doesn't support AD RMS.
* Migration from AD RMS to AIP is currently not available.
* Sharing of protected emails with users in the commercial cloud is supported.
* Sharing of documents and email attachments with users in the commercial cloud is currently not available.
This includes Office 365 operated by 21Vianet users in the commercial cloud, non-Office 365 operated by 21Vianet users in the commercial cloud, and users with an RMS for Individuals license.
* IRM with SharePoint (IRM-protected sites and libraries) is currently not available.
* The Mobile Device Extension for AD RMS is currently not available.
* The link:/azure/information-protection/rms-client/mobile-app-faq[Mobile Viewer] is not supported by Azure China 21Vianet.
* The AIP area of the Azure portal is unavailable to customers in China.
Use <<step-6-install-the-aip-on-premises-scanner-and-manage-content-scan-jobs,PowerShell commands>> instead of performing actions in the portal, such as managing and running your content scan jobs.
* AIP endpoints in Office 365 operated by 21Vianet are different than the endpoints required for other cloud services.
Network connectivity from clients to the following endpoints is required:
 ** Download label and label policies: `*.protection.partner.outlook.cn`
 ** Azure Rights Management service: `*.aadrm.cn`

=== Configure AIP for customers in China

To configure AIP for customers in China:

. <<step-1-enable-rights-management-for-the-tenant,Enable Rights Management for the tenant>>.
. <<step-2-add-the-microsoft-information-protection-sync-service-service-principal,Add the Microsoft Information Protection Sync Service service principal>>.
. <<step-3-configure-dns-encryption,Configure DNS encryption>>.
. <<step-4-install-and-configure-the-aip-unified-labeling-client,Install and configure the AIP unified labeling client>>.
. <<step-5-configure-aip-apps-on-windows,Configure AIP apps on Windows>>.
. <<step-6-install-the-aip-on-premises-scanner-and-manage-content-scan-jobs,Install the AIP on-premises scanner and manage content scan jobs>>.

==== Step 1: Enable Rights Management for the tenant

For the encryption to work correctly, RMS must be enabled for the tenant.

. Check if RMS is enabled:
 .. Launch PowerShell as an administrator.
 .. If the AIPService module isn't installed, run `Install-Module AipService`.
 .. Import the module using `Import-Module AipService`.
 .. Connect to the service using `Connect-AipService -environmentname azurechinacloud`.
 .. Run `(Get-AipServiceConfiguration).FunctionalState` and check if the state is `Enabled`.
. If the functional state is `Disabled`, run `Enable-AipService`.

==== Step 2: Add the Microsoft Information Protection Sync Service service principal

The *Microsoft Information Protection Sync Service*  service principal is not available in Azure China tenants by default, and is required for Azure Information Protection.
Create this service principal manually via the Azure Az PowerShell module.

. If you don't have the Azure Az module installed, install it or use a resource where the Azure Az module comes preinstalled, such as link:/azure/cloud-shell/overview[Azure Cloud Shell].
For more information, see link:/powershell/azure/install-az-ps[Install the Azure Az PowerShell module].
. Connect to the service using the link:/powershell/module/az.accounts/Connect-AzAccount[Connect-AzAccount] cmdlet and the `azurechinacloud` environment name:
+
[,powershell]
----
 Connect-azaccount -environmentname azurechinacloud
----

. Create the *Microsoft Information Protection Sync Service*  service principal manually using the link:/powershell/module/az.resources/new-azadserviceprincipal[New-AzADServicePrincipal] cmdlet and the `870c4f2e-85b6-4d43-bdda-6ed9a579b725` application ID for the Microsoft Purview Information Protection Sync Service:
+
[,powershell]
----
 New-AzADServicePrincipal -ApplicationId 870c4f2e-85b6-4d43-bdda-6ed9a579b725
----

. After adding the service principal, add the relevant permissions required to the service.

==== Step 3: Configure DNS encryption

For encryption to work correctly, Office client applications must connect to the China instance of the service and bootstrap from there.
To redirect client applications to the right service instance, the tenant admin must configure a DNS SRV record with information about the Azure RMS URL.
Without the DNS SRV record, the client application will attempt to connect to the public cloud instance by default and will fail.

Also, the assumption is that users will log in with a username based off the tenant-owned domain (for example, `joe@contoso.cn`), and not the `onmschina` username (for example, `joe@contoso.onmschina.cn`).
The domain name from the username is used for DNS redirection to the correct service instance.

===== Configure DNS encryption - Windows

. Get the RMS ID:
 .. Launch PowerShell as an administrator.
 .. If the AIPService module isn't installed, run `Install-Module AipService`.
 .. Connect to the service using `Connect-AipService -environmentname azurechinacloud`.
 .. Run `(Get-AipServiceConfiguration).RightsManagementServiceId` to get the RMS ID.
. Log in to your DNS provider, navigate to the DNS settings for the domain, and then add a new SRV record.
 ** Service = `_rmsredir`
 ** Protocol = `_http`
 ** Name = `_tcp`
 ** Target = `[GUID].rms.aadrm.cn` (where GUID is the RMS ID)
 ** Priority, Weight, Seconds, TTL = default values
. Associate the custom domain with the tenant in the https://portal.azure.cn/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/Domains[Azure portal].
This will add an entry in DNS, which might take several minutes to get verified after you add the value to the DNS settings.
. Log in to the Microsoft 365 admin center with the corresponding global admin credentials and add the domain (for example, `contoso.cn`) for user creation.
In the verification process, additional DNS changes might be required.
Once verification is done, users can be created.

===== Configure DNS encryption - Mac, iOS, Android

Log in to your DNS provider, navigate to the DNS settings for the domain, and then add a new SRV record.

* Service = `_rmsdisco`
* Protocol = `_http`
* Name = `_tcp`
* Target = `api.aadrm.cn`
* Port = `80`
* Priority, Weight, Seconds, TTL = default values

==== Step 4: Install and configure the AIP unified labeling client

Download and install the AIP unified labeling client from the https://www.microsoft.com/download/details.aspx?id=53018[Microsoft Download Center].

For more information, see:

* link:/azure/information-protection/[AIP documentation]
* link:/azure/information-protection/rms-client/unifiedlabelingclient-version-release-history[AIP version history and support policy]
* link:/azure/information-protection/requirements[AIP system requirements]
* link:/azure/information-protection/quickstart-deploy-client[AIP quickstart: Deploy the AIP client]
* link:/azure/information-protection/rms-client/clientv2-admin-guide[AIP administrator guide]
* link:/azure/information-protection/rms-client/clientv2-user-guide[AIP user guide]
* xref:../../compliance/sensitivity-labels.adoc[Learn about Microsoft 365 sensitivity labels]

==== Step 5: Configure AIP apps on Windows

AIP apps on Windows need the following registry key to point them to the correct sovereign cloud for Azure China:

* Registry node = `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\MSIP`
* Name = `CloudEnvType`
* Value = `6` (default = 0)
* Type = `REG_DWORD`

____
[!IMPORTANT] Make sure you don't delete the registry key after an uninstall.
If the key is empty, incorrect, or non-existent, the functionality will behave as the default value (default value = 0 for the commercial cloud).
If the key is empty or incorrect, a print error is also added to the log.
____

==== Step 6: Install the AIP on-premises scanner and manage content scan jobs

Install the AIP on-premises scanner to scan your network and content shares for sensitive data, and apply classification and protection labels as configured in your organization's policy.

When configuring and managing your content scan jobs, use the following procedure instead of the link:/azure/information-protection/deploy-aip-scanner-configure-install?tabs=azure-portal-only[Azure portal interface] that's used by the commercial offerings.

For more information, see link:/azure/information-protection/deploy-aip-scanner[What is the Azure Information Protection unified labeling scanner?] and link:/azure/information-protection/deploy-aip-scanner-prereqs#use-powershell-with-a-disconnected-computer[Manage your content scan jobs using PowerShell only].

*To install and configure your scanner*:

. Sign in to the Windows Server computer that will run the scanner.
Use an account that has local administrator rights and that has permissions to write to the SQL Server master database.
. Start with PowerShell closed.
If you've previously installed the AIP client and scanner, make sure that the *AIPScanner* service is stopped.
. Open a Windows PowerShell session with the *Run as an administrator* option.
. Run the link:/powershell/module/azureinformationprotection/Install-AIPScanner[Install-AIPScanner] cmdlet, specifying your SQL Server instance on which to create a database for the Azure Information Protection scanner, and a meaningful name for your scanner cluster.
+
[,powershell]
----
 Install-AIPScanner -SqlServerInstance <name> -Cluster <cluster name>
----
+
____
[!TIP] You can use the same cluster name in the link:/powershell/module/azureinformationprotection/install-aipscanner[Install-AIPScanner] command to associate multiple scanner nodes to the same cluster.
Using the same cluster for multiple scanner nodes enables multiple scanners to work together to perform your scans.
____

. Verify that the service is now installed by using *Administrative Tools* > *Services*.
+
The installed service is named *Azure Information Protection Scanner* and is configured to run by using the scanner service account that you created.

. Get an Azure token to use with your scanner.
An Azure AD token allows the scanner to authenticate to the Azure Information Protection service, enabling the scanner to run non-interactively.
 .. Open the Azure portal and create an Azure AD application to specify an access token for authentication.
For more information, see link:/azure/information-protection/rms-client/clientv2-admin-guide-powershell#how-to-label-files-non-interactively-for-azure-information-protection[How to label files non-interactively for Azure Information Protection].
+
____
[!TIP] When creating and configuring Azure AD applications for the link:/powershell/module/azureinformationprotection/set-aipauthentication[Set-AIPAuthentication] command, the *Request API permissions* pane shows the *APIs my organization uses* tab instead of the *Microsoft APIs* tab.
Select the *APIs my organization uses* to then select *Azure Rights Management Services*.
____

 .. From the Windows Server computer, if your scanner service account has been granted the *Log on locally* right for the installation, sign in with this account and start a PowerShell session.
+
If your scanner service account cannot be granted the *Log on locally* right for the installation, use the _OnBehalfOf_ parameter with link:/powershell/module/azureinformationprotection/set-aipauthentication[Set-AIPAuthentication], as described in link:/azure/information-protection/rms-client/clientv2-admin-guide-powershell#how-to-label-files-non-interactively-for-azure-information-protection[How to label files non-interactively for Azure Information Protection].

 .. Run link:/powershell/module/azureinformationprotection/set-aipauthentication[Set-AIPAuthentication], specifying values copied from your Azure AD application:

+
[,powershell]
----
   Set-AIPAuthentication -AppId <ID of the registered app> -AppSecret <client secret sting> -TenantId <your tenant ID> -DelegatedUser <Azure AD account>
----
+
For example:
+
[,powershell]
----
   $pscreds = Get-Credential CONTOSO\scanner
   Set-AIPAuthentication -AppId "77c3c1c3-abf9-404e-8b2b-4652836c8c66" -AppSecret "OAkk+rnuYc/u+]ah2kNxVbtrDGbS47L4" -DelegatedUser scanner@contoso.com -TenantId "9c11c87a-ac8b-46a3-8d5c-f4d0b72ee29a" -OnBehalfOf $pscreds
   Acquired application access token on behalf of CONTOSO\scanner.
----
+
The scanner now has a token to authenticate to Azure AD.
This token is valid for one year, two years, or never, according to your configuration of the *Web app /API* client secret in Azure AD.
When the token expires, you must repeat this procedure.
. Run the link:/powershell/module/azureinformationprotection/set-aipscannerconfiguration[Set-AIPScannerConfiguration] cmdlet to set the scanner to function in offline mode.
Run:
+
[,powershell]
----
 Set-AIPScannerConfiguration -OnlineConfiguration Off
----

. Run the link:/powershell/module/azureinformationprotection/set-aipscannercontentscanjob[Set-AIPScannerContentScanJob] cmdlet to create a default content scan job.
+
The only required parameter in the *Set-AIPScannerContentScanJob* cmdlet is *Enforce*.
However, you may want to define other settings for your content scan job at this time.
For example:
+
[,powershell]
----
 Set-AIPScannerContentScanJob -Schedule Manual -DiscoverInformationTypes PolicyOnly -Enforce Off -DefaultLabelType PolicyDefault -RelabelFiles Off -PreserveFileDetails On -IncludeFileTypes '' -ExcludeFileTypes '.msg,.tmp' -DefaultOwner <account running the scanner>
----
+
The syntax above configures the following settings while you continue the configuration:

 ** Keeps the scanner run scheduling to _manual_
 ** Sets the information types to be discovered based on the sensitivity labeling policy
 ** Does _not_ enforce a sensitivity labeling policy
 ** Automatically labels files based on content, using the default label defined for the sensitivity labeling policy
 ** Does _not_ allow for relabeling files
 ** Preserves file details while scanning and auto-labeling, including _date modified_, _last modified_, and _modified by_ values
 ** Sets the scanner to exclude .msg and .tmp files when running
 ** Sets the default owner to the account you want to use when running the scanner

. Use the link:/powershell/module/azureinformationprotection/add-aipscannerrepository[Add-AIPScannerRepository] cmdlet to define the repositories you want to scan in your content scan job.
For example, run:
+
[,powershell]
----
 Add-AIPScannerRepository -OverrideContentScanJob Off -Path 'c:\repoToScan'
----
+
Use one of the following syntaxes, depending on the type of repository you're adding:

 ** For a network share, use `\\Server\Folder`.
 ** For a SharePoint library, use `+http://sharepoint.contoso.com/Shared%20Documents/Folder+`.
 ** For a local path: `C:\Folder`
 ** For a UNC path: `\\Server\Folder`

+
____
[!NOTE] Wildcards are not supported and WebDav locations are not supported.

To modify the repository later on, use the link:/powershell/module/azureinformationprotection/set-aipscannerrepository[Set-AIPScannerRepository] cmdlet instead.
____

Continue with the following steps as needed:

* link:/azure/information-protection/deploy-aip-scanner-manage#run-a-discovery-cycle-and-view-reports-for-the-scanner[Run a discovery cycle and view reports for the scanner]
* link:/azure/information-protection/deploy-aip-scanner-configure-install?tabs=azure-portal-only#use-powershell-to-configure-the-scanner-to-apply-classification-and-protection[Use PowerShell to configure the scanner to apply classification and protection]
* link:/azure/information-protection/deploy-aip-scanner-configure-install?tabs=azure-portal-only#use-powershell-to-configure-a-dlp-policy-with-the-scanner[Use PowerShell to configure a DLP policy with the scanner]

The following table lists PowerShell cmdlets that are relevant for installing the scanner and managing your content scan jobs:

|===
| Cmdlet | Description

| link:/powershell/module/azureinformationprotection/add-aipscannerrepository[Add-AIPScannerRepository]
| Adds a new repository to your content scan job.

| link:/powershell/module/azureinformationprotection/get-aipscannerconfiguration[Get-AIPScannerConfiguration]
| Returns details about your cluster.

| link:/powershell/module/azureinformationprotection/get-aipscannercontentscanjob[Get-AIPScannerContentScanJob]
| Gets details about your content scan job.

| link:/powershell/module/azureinformationprotection/get-aipscannerrepository[Get-AIPScannerRepository]
| Gets details about repositories defined for your content scan job.

| link:/powershell/module/azureinformationprotection/remove-aipscannercontentscanjob[Remove-AIPScannerContentScanJob]
| Deletes your content scan job.

| link:/powershell/module/azureinformationprotection/remove-aipscannerrepository[Remove-AIPScannerRepository]
| Removes a repository from your content scan job.

| link:/powershell/module/azureinformationprotection/set-aipscannercontentscanjob[Set-AIPScannerContentScanJob]
| Defines settings for your content scan job.

| link:/powershell/module/azureinformationprotection/set-aipscannerrepository[Set-AIPScannerRepository]
| Defines settings for an existing repository in your content scan job.

|
|
|===

For more information, see:

* link:/azure/information-protection/deploy-aip-scanner[What is the Azure Information Protection unified labeling scanner?]
* link:/azure/information-protection/deploy-aip-scanner-configure-install?tabs=powershell-only[Configuring and installing the Azure Information Protection (AIP) unified labeling scanner]
* link:/azure/information-protection/deploy-aip-scanner-prereqs#use-powershell-with-a-disconnected-computer[Manage your content scan jobs using PowerShell only].
