= Create distribution groups
:audience: Admin
:author: kwekua
:description: Create distribution groups or lists in the Microsoft 365 admin center so you can send emails to a group without typing each recipient's name.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.assetid: b1ffe755-59e5-4369-826d-825f145a8400
:ms.author: kwekua
:ms.collection: ["highpri", "M365-subscription-management", "Adm_O365"]
:ms.custom: ["VSBFY23", "seo-marvel-may2020", "AdminSurgePortfolio", "okr_smb", "AdminTemplateSet"]
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["BCS160", "MET150", "MOE150"]

== Create distribution groups in the Microsoft 365 admin center

Used when you want to send email to group of people without having to type each individual recipient's name, distribution groups (distribution lists) are organized by a particular discussion subject (such as "Marketing") or by users who share common work that requires them to communicate frequently.
They also provide a way for you to automatically forward email to multiple email addresses.

Distribution groups are sometimes called distribution lists.

=== Create a distribution group (list)

::: moniker range="o365-worldwide"

Go to the admin center at https://go.microsoft.com/fwlink/p/?linkid=2024339[https://admin.microsoft.com].

::: moniker-end

::: moniker range="o365-21vianet"

Go to the admin center at https://go.microsoft.com/fwlink/p/?linkid=850627[https://portal.partner.microsoftonline.cn/adminportal].

::: moniker-end

. Select the app launcher icon and choose *Admin*.
+
Can't find the app you're looking for?
From the app launcher, select *All apps* to see an alphabetical list of the apps available to you.
From there, you can search for a specific app.

. Select *Groups* > *Groups* in the left navigation pane, and then select *Add a group*.
. On the *Choose a group type* field, choose *Distribution*, and then choose *Next*.
. Enter a name, description, and email alias for your new group, and choose whether you want people outside your organization to send email to the group.
. Press *Add* to create a group, and then review your group and choose *Close*.
. To add users to your distribution list, see xref:../email/add-user-or-contact-to-distribution-list.adoc[Add a user or contact to a distribution group].

Check out how to use group in Outlook 2016 and Outlook on the web in https://support.microsoft.com/office/1c97fcb2-0ed4-41e6-b401-58f9d7d40e39[Use contact groups (formerly distribution lists) in Outlook].

Check out link:/office365/troubleshoot/groups/distribution-list-issues[Distribution group issues] for help with distribution list issues.

=== Related content

xref:../email/office-365-user-email-settings.adoc[User email settings] (article) + xref:../email/create-edit-or-delete-a-security-group.adoc[Create, edit, or delete a security group in the Microsoft 365 admin center] (article) + xref:../email/create-a-shared-mailbox.adoc[Create a shared mailbox] (article)
