'''

title: Customize a SharePoint team site for file storage and sharing f1.keywords:

* NOCSH ms.author: sharik author: SKjerland manager: scotv audience: Admin ms.topic: article ms.service: o365-administration ms.localizationpriority: medium ms.collection:
* M365-subscription-management
* Adm_O365
* SPO_Content ms.custom:
* IT_Networking
* seo-marvel-apr2020
* seo-marvel-may2020
* AdminSurgePortfolio search.appverid:
* BCS160
* MET150
* MOE150 ms.assetid: 70a62f09-45ea-4968-8482-43cddfb8cc01 description: Learn how to customize, organize, and manage your SharePoint team site with document libraries, lists, and hubs.
--

== Customize your team site for file storage and sharing

If you have a small business with a few employees, one of the best ways to set up and facilitate file sharing and online collaboration is to use OneDrive and a SharePoint team site together.
We recommend creating a team site that's connected to a Microsoft 365 group.
If you want to use chat, you can create this site by creating a team in Microsoft Teams.
For more info about Teams, see https://support.microsoft.com/office/b98d533f-118e-4bae-bf44-3df2470c2b12[Video: What is Microsoft Teams?].
If you don't want to use Teams, you can create a team site from the SharePoint start page.

https://support.microsoft.com/office/75545757-36c3-46a7-beed-0aaa74f0401e[What is a SharePoint team site?]

https://support.microsoft.com/office/ef10c1e7-15f3-42a3-98aa-b5972711777d[Create a team site in SharePoint]

Here are some ideas and links to help you customize, organize, and manage your team site.

=== Customize your team site

To give more visibility to data on a team site, you can customize the SharePoint start page to help you and your employees get to the information you need quickly.
For example, you might have a links to employee OneDrive folders, and links to Documents, Contacts, Tasks, Calendars, and a OneNote notebook where you store meeting agendas and notes.

For info on customizing the look and feel of your start page, see https://support.microsoft.com/office/06bbadc3-6b04-4a60-9d14-894f6a170818[Change the look of your SharePoint site].

Improve navigation on your site with https://support.microsoft.com/office/3cd61ae7-a9ed-4e1e-bf6d-4655f0bf25ca[Customize the navigation on your SharePoint site].

To improve the discoverability of a site, add it as a featured link on the SharePoint start page.
For info, see link:/sharepoint/change-links-list-on-sharepoint-home-page[Add featured links to the SharePoint start page].

To add an image to a team site start page, see https://support.microsoft.com/office/4a9b0e98-c89a-4a41-8adb-b7750dccca16[Add a picture or image file to a SharePoint page].

To add pages to your site, see https://support.microsoft.com/office/b3d46deb-27a6-4b1e-87b8-df851e503dec[Add a page to a site].

To learn about team site settings, see https://support.microsoft.com/office/8376034D-D0C7-446E-9178-6AB51C58DF42[Manage your SharePoint team site settings].

=== Work with document libraries

A team site includes a document library that you can start using immediately for file storage and document management.

To begin uploading, see https://support.microsoft.com/office/eb18fcba-c953-4d45-8d90-8da66edeacdb[Upload a folder or files to a document library]

Learn how to edit, delete, check out files, and more.
For more info, see https://support.microsoft.com/office/a9d89171-1673-4892-9dd2-1ca52037dea2[Work with files in a document library].

For info on creating views of libraries to surface specific data, see https://support.microsoft.com/office/8f6b08e0-a9a0-4232-9b9b-b374a2ad3da7[Create a custom view of a document library].

=== Work with lists to organize data

SharePoint includes many templates for lists that you can add to your site, such as a list of links, a calendar, contacts, or tasks.

Learn how to https://support.microsoft.com/office/0D397414-D95F-41EB-ADDD-5E6EFF41B083#ID0EAAGAAA=Online[Create a list in SharePoint].

For info on expanding your lists with more columns, see https://support.microsoft.com/office/2b0361ae-1bd3-41a3-8329-269e5f81cfa2[Create a column in a SharePoint list or library].

If you're storing a lot of data in a list, see https://support.microsoft.com/office/B8588DAE-9387-48C2-9248-C24122F07C59[Manage large lists and libraries in SharePoint].

View a video on adding calendars to your site, see https://support.microsoft.com/office/61b96006-70e2-4535-a34f-ee4fc772f798[Create a shared calendar].

=== Organize sites into hubs

Your team site shares almost everything with all members of the group associated with the site.
If you want to have a separate site for specific customers, you can create additional team sites, and manage them using SharePoint hub sites.
Here's more information.

Hub sites let you add and associate sites.
For more info, see https://support.microsoft.com/office/fe26ae84-14b7-45b6-a6d1-948b3966427f[What is a SharePoint hub site?].

Ready to build a hub site, see link:/sharepoint/create-hub-site[Create a hub site in SharePoint Online].

To learn how to add sites to a hub site, see https://support.microsoft.com/office/ae0009fd-af04-4d3d-917d-88edb43efc05[Associate a SharePoint site with a hub site].

=== Sharing files with the team

While file storage and document management is a start, sharing with your team and external clients is also important.
The following articles will help you manage users and share your data:

* For file sharing with your team, see https://support.microsoft.com/office/1fe37332-0f9a-4719-970e-d2578da4941c[Share SharePoint files or folders in Microsoft 365].
* To understand sharing outside your team, see link:/sharepoint/external-sharing-overview[External sharing overview].

=== Managing users and groups

As you manage your team site, you may have to add or remove users.
Here's information to help you understand, add, and manage users on your team site.

View a video on groups with link:/training/m365/[Understand and manage groups].

To add users to a Microsoft 365 group, see xref:../add-users/add-users.adoc[Add users and assign licenses at the same time].

Learn how to handle access requests with https://support.microsoft.com/office/94B26E0B-2822-49D4-929A-8455698654B3[Set up and manage access requests].

=== Next steps

You must set up Office apps on your devices so you can edit files that are stored on your team site from your tablet or phone.
If you don't install the Office apps for your tablet or phone, you'll be able to view the files on your team site, but not edit them.

* https://support.microsoft.com/office/cafe9d6f-8b0c-4b03-b20a-12438a82a22d[Install and set up Office on an Android with Microsoft 365]
* https://support.microsoft.com/office/9df6d10c-7281-4671-8666-6ca8e339b628[Install and set up Office on an iPhone or iPad with Microsoft 365]
* https://support.microsoft.com/office/2b7c1b51-a717-45d6-90c9-ee1c1c5ee0b7[Set up Office on Windows Phone with Microsoft 365]
* https://go.microsoft.com/fwlink/?LinkID=511458[Learn more about using OneDrive].
