= Move your files to OneDrive
:audience: Admin
:author: efrene
:description: Learn how to move your files to OneDrive.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.author: efrene
:ms.collection: ["highpri", "M365-subscription-management", "Adm_O365"]
:ms.custom: ["VSBFY23", "AdminSurgePortfolio", "adminvideo"]
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["BCS160", "MET150", "MOE150"]

== Move files to OneDrive for Business

Check out https://go.microsoft.com/fwlink/?linkid=2197659[Microsoft 365 small business help] on YouTube.

=== Watch: Move your files to OneDrive for Business

Check out this video and others on our https://go.microsoft.com/fwlink/?linkid=2198202[YouTube channel].

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/d74b083c-1f44-43ea-8a14-2e1fc600b341?autoplay=false]
____

After you sign up for Microsoft 365 Business Premium, you&#39;ll want to copy your existing work files to OneDrive for Business.
OneDrive is a good place to store personal work files or sensitive business files that you want to control access to.

. From Windows, select the  *Start* button.
. Search for OneDrive, and select it.
. Enter your work email address.
. Select  *Sign in* , and then select  *Next*.
. Go through the short tutorial, and then select  *Open my OneDrive folder*.
If you also use the personal version of OneDrive, you&#39;ll see it here.
. In File Explorer, go to the files you want to copy.
. Select the files, and then drag and drop them into your OneDrive folder.
Blue circular arrows beside your files mean that they&#39;re syncing to the cloud.
When they&#39;re done syncing, green check marks are displayed.

In addition to working on your OneDrive files locally, you can access them from your web browser:

. In your web browser, sign in to office.com with your work email.
. Choose  *OneDrive*.
All of your files are listed, and you can work on them in the browser from any computer.
