= Set up Outlook for email
:audience: Admin
:author: kwekua
:description: Learn how to set up Outlook for your Microsoft 365 email.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.author: kwekua
:ms.collection: ["highpri", "M365-subscription-management", "Adm_O365"]
:ms.custom: ["VSBFY23", "AdminSurgePortfolio", "adminvideo"]
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["BCS160", "MET150", "MOE150"]

== Set up Outlook for Microsoft 365 for business email

Check out https://go.microsoft.com/fwlink/?linkid=2197659[Microsoft 365 small business help] on YouTube.

=== Watch: Set up Outlook for email

Check out this video and others on our https://go.microsoft.com/fwlink/?linkid=2198010[YouTube channel].

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/9fe86884-8a83-42cc-bca9-61a12e6dad31?autoplay=false]
____

After installing the Office apps, you&#39;ll want set up Outlook to start using email, calendar, and contacts.
Here&#39;s how.

. Open the Start menu.
Search for Outlook, and choose it.
. Enter your Microsoft 365 email address, and select  *Connect*.
. Enter any additional email addresses that you want to use, such as your previous or personal email address.
Select  *Next*.
. If prompted, enter a password, and then select  *Sign in*.
. After all of your accounts have been added, choose if you want to set up Outlook mobile or wait until later.
. Select  *Done*.
It may take several minutes for Outlook to download your email and other data.

Now you can view email for the accounts you added.
You can also view your calendar, contacts, and tasks.
