'''

title: Import a term set using a SKOS-based format description: "Learn how to Import a term set using a SKOS-based format" ms.author: mikeplum author: MikePlumleyMSFT manager: serdars audience: admin ms.service: microsoft-365-enterprise ms.topic: article ms.collection: enabler-strategic ms.custom: admindeeplinkSPO search.appverid:  ms.localizationpriority: high

'''

== Import a term set using a SKOS-based format

You can import a term set using a SKOS-based format.
For details about the format, see xref:skos-format-reference.adoc[SharePoint taxonomy SKOS format reference].
This feature requires a xref:index.adoc[SharePoint Syntex] license.

We recommend keeping your import files to less than 20,000 terms.
Larger files can increase the time taken for validation and import.

. In the SharePoint admin center, expand *Content services*, and then select https://go.microsoft.com/fwlink/?linkid=2185073[*Term store*].
. Select the term group where you want to import the term set.
. In the command bar, click *Import term set*.
. If you want to download a sample file to use as a template, click *sample-metadata.ttl* to get a sample file that uses the SKOS-based format.
. Create the import file that contains the term sets & terms you wish to import.
. Under *File format*, select *SKOS (*.ttl)*.
. Click *Browse* and navigate to and add your import file.
. Click *Import*.
Do not close the panel until the import completes.

On successful import of the file, a success message will be displayed, and the term store will refresh and you can navigate to the newly created term sets.

=== See also

link:/sharepoint/managed-metadata[Introduction to managed metadata]

xref:document-understanding-overview.adoc[Document understanding overview]

https://support.microsoft.com/office/168fbc86-7fce-4288-9a1f-b83fc3921c18[Import term sets (site level)]
