= 
jameseccles

== Manage Microsoft Syntex by using PowerShell

____
[!IMPORTANT] The Microsoft Syntex PowerShell cmdlets and all other PnP
components are open-source tools backed by an active community providing
support for them. There is no SLA for open-source tool support from
official Microsoft support channels.
____

For these scenarios, the Syntex cmdlets in the PnP PowerShell module can
be used to interact with models and explanations. To learn more about
how to install this module, see
link:/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets[PnP
PowerShell overview].

Select from the following scenarios to learn how to use PowerShell to
manage Syntex:

* link:powershell-syntex-import-export.md[*Export and import models*]
+
Start here if you want to learn how to export an unstructured document
processing model from a content center, and import to another content
center or tenant.
* link:powershell-syntex-publishing.md[*Publishing*]
+
Start here if want to learn how to use PowerShell to publish custom
models to document libraries.
* link:powershell-syntex-processing.md[*Processing*]
+
Start here if you want to learn how to use PowerShell to trigger
processing of custom models on a document library.
* link:powershell-syntex-explanations.md[*Explanations*]
+
Start here if want to learn how to create a custom explanation template
for an unstructured document processing model using PowerShell.
