= SKOS format reference for SharePoint taxonomy
:audience: admin
:author: MikePlumleyMSFT
:description: SKOS format reference for SharePoint taxonomy
:manager: serdars
:ms.author: mikeplum
:ms.collection: enabler-strategic
:ms.localizationpriority: high
:ms.service: microsoft-365-enterprise
:ms.topic: article
:search.appverid:

== SKOS format reference for SharePoint taxonomy

This article includes RDF vocabulary used to represent link:/dotnet/api/microsoft.sharepoint.taxonomy[SharePoint taxonomy] and is based on https://www.w3.org/TR/skos-primer/[SKOS].
For serialization of this RDF syntax, use RDF https://www.w3.org/TR/turtle/[TURTLE].

The following table shows the https://www.w3.org/TR/skos-primer/[SKOS] equivalents for the link:/dotnet/api/microsoft.sharepoint.taxonomy[SharePoint taxonomy] vocabulary.
SharePoint doesn't support https://www.w3.org/TR/skos-primer/[SKOS] values that have no SharePoint taxonomy equivalent.

|===
| SharePoint taxonomy | SKOS equivalent

| sharepoint-taxonomy: Term
| skos: Concept

| sharepoint-taxonomy: TermSet
| skos: ConceptScheme

| sharepoint-taxonomy: inTermSet
| skos: inScheme

| sharepoint-taxonomy: hasTopLevelTerm
| skos: hasTopConcept

| sharepoint-taxonomy: topLevelTermOf
| skos: topConceptOf

| sharepoint-taxonomy: defaultLabel
| skos: prefLabel

| sharepoint-taxonomy: termSetName
| skos: prefLabel

| sharepoint-taxonomy: propertyName
| skos: prefLabel

| sharepoint-taxonomy: otherLabel
| skos: altLabel

| sharepoint-taxonomy: description
| skos: definition

| sharepoint-taxonomy: parent
| skos: broader

| sharepoint-taxonomy: child
| skos: narrower
|===

The following table displays the entities of the SharePoint taxonomy vocabulary derived from https://www.w3.org/TR/owl2-primer/[OWL].

|===
| SharePoint taxonomy vocabulary | Derived from OWL

| sharepoint-taxonomy: isAvailableForTagging
| owl: datatypeproperty

| sharepoint-taxonomy: SharedCustomPropertyForTerm
| owl: ObjectProperty

| sharepoint-taxonomy: LocalCustomPropertyForTerm
| owl: ObjectProperty

| sharepoint-taxonomy: CustomPropertyForTermSet
| owl: ObjectProperty
|===

=== SharePoint taxonomy vocabulary

A taxonomy is a formal classification system.
A taxonomy groups the words, labels, and terms that describe something, and then arranges the groups into a hierarchy.

*sharepoint-taxonomy:Term*

Represents a Term or a Keyword in a managed metadata hierarchy.

A link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] is the atomic unit of a SharePoint link:/dotnet/api/microsoft.sharepoint.taxonomy.termstore[TermStore].
Each link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] belongs to a link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSet] that belongs to a link:/dotnet/api/microsoft.sharepoint.taxonomy.group[TermGroup].

The syntax to define a link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] is as follows:

[,skos]
----
ex:TermA    a    sharepoint-taxonomy:Term;
    sharepoint-taxonomy:inTermSet    ex:TermSetA;
    sharepoint-taxonomy:topLevelTermOf    ex:TermSetA;
    sharepoint-taxonomy:child    ex:TermA1;
    sharepoint-taxonomy:isAvailableForTagging    “true”^^xsd:Boolean;
    sharePoint-taxonomy:defaultLabel    “Term A”@en-us.
----

A link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] compulsorily exists within a link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSet].
DefaultLabel is the name of the link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] as it appears in the visual representation.
The required fields for defining a link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] include:

* sharepoint-taxonomy: defaultLabel
* sharepoint-taxonomy: inTermSet

A link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] can:

* Be hierarchically related to another link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] that is provided both the link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Terms] belong to the same link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSet].
* Have multiple child link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Terms], but only a single parent link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term].
* Not have a parent link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] defined, if it's a topLevelTermOf a link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSet].
* Have one defaultLabel, per link:/dotnet/api/microsoft.sharepoint.taxonomy.termstore[TermStore] working language.
* Not exist if it neither contains a parent link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term], nor is the topLevelTermOf a link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSet].
* Have only a unique defaultLabel in the same hierarchical level.

*sharepoint-taxonomy:TermSet*

Represents a hierarchical or flat set of Term objects known as a "TermSet".

As the name suggests, TermSet is a set of link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Terms].
A link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] in a link:/dotnet/api/microsoft.sharepoint.taxonomy.termstore[TermStore] must belong to a link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSet].
No link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] can exist independently.

The syntax to define a link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSet] is:

[,skos]
----
ex:TermSetA    a    sharepoint-taxonomy:TermSet;
    sharepoint-taxonomy:termSetName    “TermSet A";
    sharepoint-taxonomy:isAvailableForTagging    “true”^^xsd:Boolean;
    sharepoint-taxonomy:hasTopLevelTerm    Ex:Term A.
----

link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSets] are logically grouped together in link:/dotnet/api/microsoft.sharepoint.taxonomy.group[TermGroups].
The required field for defining a link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSet] is:

* sharepoint-taxonomy: termSetName

If the termSetName provided isn't unique within the link:/dotnet/api/microsoft.sharepoint.taxonomy.group[TermGroup], SharePoint appends a number at the end of the name to maintain the uniqueness of termSetName(s).

*sharepoint-taxonomy:hasTopLevelTerm*

SharePoint uses this property to map the top-most link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] in the link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSet], which is the entry point to the hierarchy of link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Terms] in a link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSet].
This is an inverse relation to sharepoint-taxonomy: topLevelTermOf.

The syntax to define this is:

[,skos]
----
ex:TermSetA    sharepoint-taxonomy:hasTopLevelTerm    ex:TermA.
----

____
[!NOTE] You cannot define the top level link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] of a parent link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term].
____

*sharepoint-taxonomy:topLevelTermOf*

Sharepoint-taxonomy: topLevelTermOf is the inverse of sharepoint-taxonomy: hasTopLevelTerm

The syntax to define this is:

[,skos]
----
ex:TermA    sharepoint-taxonomy:topLevelTermOf    ex:TermSetA.
----

*sharepoint-taxonomy:inTermSet*

Use this to map a link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] to a link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSet].
A link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] can only exist in a single link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSet].
SharePoint requires this property when <<sharepoint-taxonomy-vocabulary,defining a term>>.

=== Required labels

Your organization may want to do careful planning before you start to use managed metadata.
The amount of planning that you must do depends on how formal your taxonomy is.
It also depends on how much control that you want to impose on metadata.
At each level of the hierarchy, you need to configure required labels for a Term or TermSet.

A Term can have one or more labels in the default language, and zero or more labels in the non-default language.
If the term has labels in a language, one of the labels must be the default label.

*sharepoint-taxonomy:defaultLabel*

Use this default lexical label for a link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] that is a required parameter for a link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term].
Use to visually representing the link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term].

The syntax to define a defaultLabel is:

[,skos]
----
ex:TermA    sharepoint-taxonomy:defaultLabel    “Term A”@en-us.
----

The defaultLabel contains two parts to it -- the string and the language tag.
The language must be one of the link:/dotnet/api/microsoft.sharepoint.taxonomy.termstore[TermStore] working languages.
The defaultLabel must be unique for all link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Terms] in the same link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSet], at the same hierarchical level.

*sharepoint-taxonomy:termSetName*

Gets and sets the name for the current TermSet object.

This is the lexical label for a link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSet], in a link:/dotnet/api/microsoft.sharepoint.taxonomy.termstore[TermStore] working language.
This is a required parameter for a link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSet].
Use to visually representing a link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSet].

The syntax to define a termSetName is:

[,skos]
----
ex:TermA    sharepoint-taxonomy:TermSetName    “Term Set A”@en-us.
----

*sharepoint-taxonomy:propertyName*

Gets and sets the property name for the current TermSet object.

This is the lexical label for a sharepoint-taxonomy:SharedCustomPropertyForTerm, sharepoint-taxonomy:LocalCustomPropertyForTerm and sharepoint-taxonomy:CustomPropertyForTermSet in a link:/dotnet/api/microsoft.sharepoint.taxonomy.termstore[TermStore] working language.

The sharepoint-taxonomy: propertyName is treated as the key of the CustomProperty.

The syntax to define a propetyName is:

[,skos]
----
ex:SharedCustomProperty1    sharepoint-taxonomy:propertyName    “Shared Custom Property Key 1”@en-us.
----

=== Optional labels

You can also add optional labels to your taxonomy.

*sharepoint-taxonomy:otherLabel*

This is the alternate lexical label for a link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term].

The syntax to define an otherLabel is:

[,skos]
----
ex:TermA    sharepoint-taxonomy:otherLabel    “Term A”@en-us.
----

=== Semantic relationships

Taxonomies have hierarchical and sometimes a simple "`related term`" associative relationship, but some have "semantic relationships" or custom-created relationships.

*sharepoint-taxonomy:parent*

This hierarchically relates a link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] to another link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term].
A link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] could be a top level link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] of a link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSet], but in case it doesn't it must have a parent link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term].

The syntax to define a parent is:

[,skos]
----
ex:TermA1    sharepoint-taxonomy:parent    ex:TermA.
----

This means that TermA is the parent and  TermA is the child.

*sharepoint-taxonomy:child*

The object contains one or more child TermSet instances, and these can be accessed through the TermSets property.
This class also provides methods for creating new child TermSet objects.
Permissions for editing child Term and TermSet instances are specified on the group.

This hierarchically relates a link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] to another link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term].

The syntax to define a child is:

[,skos]
----
ex:TermA    sharepoint-taxonomy:child    ex:TermA1.
----

This means that TermA is the parent and  TermA is the child.

=== Documentation notes

This section discusses the taxonomy detailed in the Microsoft.SharePoint.Taxonomy Namespace.

*sharepoint-taxonomy:description*

This is a detailed explanation of any link:/dotnet/api/microsoft.sharepoint.taxonomy[SharePoint taxonomy] vocabulary entity.

The syntax to add a description is:

[,skos]
----
ex:TermA    sharepoint-taxonomy:description    “Term A is the top level term of TermSetA”@en-us.
----

=== Custom properties

Gets the collection of custom property objects for the current Term object from the read-only dictionary.

Custom Properties are key-values pairs that can be defined for a link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] or a link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSet], to further the description of the link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] or a link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSet].
SharePoint specifies the key of the custom property with the help of propertyName.

*sharepoint-taxonomy:CustomPropertyForTermSet*

The syntax to define this is:

[,skos]
----
ex:CustomProp1    rdf:type    sharepoint-taxonomy:CustomPropertyForTermSet;
    sharepoint-taxonomy:propertyName “Colour”.

ex:TermSetA    ex:CustomProp1    “Red”@en-us.
----

*sharepoint-taxonomy:SharedCustomPropertyForTerm*

If the custom property for a link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] needs to be carried along with the link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term], when you reuse the link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] somewhere else, then you need to be define it under SharedCustomPropertyForTerm.

The syntax to define this is:

[,skos]
----
ex:CustomProp2    rdf:type sharepoint-taxonomy:SharedCustomPropertyForTerm;
    sharepoint-taxonomy:propertyName “Length”.

ex:TermA    ex:CustomProp2    “5 cm”@en-us.
----

*sharepoint-taxonomy:LocalCustomPropertyForTerm*

If the custom property for a link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] doesn't need to be carried along with the link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term], when you reuse the link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] somewhere else, then you need to define it under LocalCustomPropertyForTerm.

The syntax to define this is:

[,skos]
----
ex:CustomProp3    rdf:type sharepoint-taxonomy:LocalCustomPropertyForTerm;
    sharepoint-taxonomy:propertyName “width”.

ex:TermA    ex:CustomProp3    “5 cm”@en-us.
----

=== Data properties

At each level of the hierarchy, you can configure specific data properties for a Term or TermSet.

*sharepoint-taxonomy:isAvailableForTagging*

Use this to specify if a link:/dotnet/api/microsoft.sharepoint.taxonomy.term[Term] or a link:/dotnet/api/microsoft.sharepoint.taxonomy.termset[TermSet] available in SharePoint Lists and Libraries.

The syntax for this is:

[,skos]
----
ex:TermA    sharepoint-taxonomy:isAvailableForTagging     "true"^^xsd:Boolean;
----

=== Domain and range

The table below describes the domain and range of SharePoint taxonomy vocabulary.

|===
| Predicates/verb | Meaning | Domain | Range

| inTermSet
| In term set
| Term
| Term Set

| inTermGroup
| In term group
| TermSet
| TermGroup

| topLevelTermOf
| Is Top Level Term Of
| Term
| TermSet

| hasTopLevelTerm
| Has top level term
| Term Set
| Term

| termSetName
| Term set has Name
| Term
| Plain literal

| defaultLabel
| Term has default label
| Term
| Plain literal

| otherLabel
| Term has other label
| Term
| Plain literal

| propertyName
| Has Property Label
| SharedCustomPropertyForTerm, LocalCustomPropertyForTerm, CustomPropertyForTermSet
| Boolean, String, Integer, Decimal, Double

| description
| Has Description
| All
| Plain literal

| parent
| Has parent
| Term
| Term

| child
| Has Child
| Term
| Term

| isAvailableForTagging
| Is available for tagging
| Term, Term Set
| Boolean

| SharedCustomPropertyForTerm
| Has shared custom property
| Term
| Boolean, string, Integer, Decimal, Double

| LocalCustomPropertyForTerm
| Has local custom property
| Term
| Boolean, String, Integer, Decimal, Double

| CustomPropertyForTermSet
| Has Custom Property
| TermSet
| Boolean, String, Integer, Decimal, Double
|===

https://www.w3.org/TR/skos-primer/[SKOS] valid scenarios that link:/dotnet/api/microsoft.sharepoint.taxonomy[SharePoint taxonomy] doesn't allow:

* Hierarchical redundancy - A https://www.w3.org/TR/skos-primer/[SKOS] concept can be attached to several broader concepts at the same time, but a sharepoint-taxonomy:Term can have only one sharepoint-taxonomy:parent, hence cyclic dependency, of Terms are also not allowed.
* Orphaned terms aren't allowed in SharePoint taxonomy.
Every sharepoint-taxonomy: Term should either have a sharepoint-taxonomy: parent or it should be the sharepoint-taxonomy: topLevelTermOf a TermSet.
* SharePoint taxonomy doesn't support associative relations.
* SharePoint taxonomy only allows two types of Hierarchical relations -- sharepoint-taxonomy: parent and sharepoint-Taxonomy: child.
* Unlike https://www.w3.org/TR/skos-primer/[SKOS] the hierarchical relationship in SharePoint taxonomy vocabulary, can only be established with Terms within the same TermSet.

=== See also

xref:import-term-set-skos.adoc[Import a term set using a SKOS-based format]
