= Run a trial of Microsoft SharePoint Syntex
:audience: admin
:author: chuckedmonson
:description: Learn how to plan, sign up, and run a trial pilot program for SharePoint Syntex in your organization.
:manager: pamgreen
:ms.author: chucked
:ms.collection: ["enabler-strategic", "m365initiative-syntex"]
:ms.custom: ["Adopt", "admindeeplinkMAC"]
:ms.date:
:ms.localizationpriority: medium
:ms.reviewer: lauris; jaeccles
:ms.service: microsoft-365-enterprise
:ms.topic: article
:search.appverid:

== Run a trial of Microsoft SharePoint Syntex

This article describes how to set up and run a trial pilot program to deploy SharePoint Syntex in your organization.
It also recommends best practices for the trial.

=== Sign up for a trial

The trial of SharePoint Syntex gives access to 300 users for 30 days.

____
[!NOTE] Up to 300 users are included in the trial to ensure the automatic addition of 1 million AI Builder credits.
You do not have to include 300 users for a trial to succeed.
____

You can get the trial version from one of the following sources:

* The https://www.microsoft.com/microsoft-365/enterprise/sharepoint-syntex?activetab=pivot:overviewtab[SharePoint Syntex product page]
* The https://admin.microsoft.com[Microsoft 365 admin center]
 .. Sign in to the https://admin.microsoft.com[Microsoft 365 admin center].
 .. Go to *Billing* > https://go.microsoft.com/fwlink/p/?linkid=868433[*Purchase Services*].
 .. Scroll down to the *Add-Ons* section.
 .. On the SharePoint Syntex tile, select *Details*.
 .. Select *Start free trial*.
 .. To confirm the trial, follow the remaining wizard steps.

You must be a Microsoft 365 global administrator or billing administrator to activate a trial.

==== Who should be involved in a trial

|===
| Role | Activity

| Microsoft 365 global admin or billing admin
| Activate the trial and assign licenses

| Microsoft 365 global admin or SharePoint admin
| Configure SharePoint Syntex and create content centers

| Business users
| Model building and testing
|===

==== Before you activate a trial

To successfully plan a SharePoint Syntex trial, consider the following factors:

* The most meaningful testing is completed on "`real world`" scenarios and data.
* You can only activate a SharePoint Syntex trial once per tenant.

A test or demo tenant can be used as a "`dry run`" to walk through the activation steps and administrative controls.
But it's probably best to evaluate model building on a production tenant.

To maximize the value of a trial on a production tenant, planning and business engagement are essential.
You should engage one or more business areas to identify three to six use cases that could potentially be addressed by SharePoint Syntex.
These use cases should:

* Include scenarios that could be solved by either the form processing or document understanding model.
* Have a clear understanding of the purpose for any extracted metadata;
for example, view formatting or automation by using Power Automate.
While SharePoint Syntex is focused on classifying documents and extracting metadata, the value to quantify is what this metadata enables.
* Be based on a defined set of data;
for example, specific SharePoint sites or libraries.
A common misconception of SharePoint Syntex is that general purpose models can be applied across all organization content.
A more accurate view is that models are built to help solve specific business problems in targeted locations.

All of these use cases might not be a good fit for SharePoint Syntex.
The goal of a quality trial isn't to prove that SharePoint Syntex will fit all the scenarios.
Instead, the trial should help you better understand the value of the product.

For each of the planned use cases, identify users who are subject matter experts in the related content or process.
The creation of SharePoint Syntex models is focused on domain experts in the content, rather than on IT professionals or developer resources.

=== Activate a trial

When you initiate a trial, you need to:

* Assign licenses to the relevant users.
* Perform xref:set-up-content-understanding.adoc[additional setup of SharePoint Syntex].
 ** You might want to xref:create-a-content-center.adoc[create more content centers].

After the trial is activated, you can create models and process files.
See xref:create-a-content-center.adoc[guidance for model creation].

=== During a trial

Trial periods are limited, so it's best to focus initially on whether SharePoint Syntex models can classify documents and extract metadata for the defined use cases.
After the trial period is over, you can evaluate how the metadata can be used.

=== After a trial

Based on the outcome of the trial, you can decide whether to proceed to production use of SharePoint Syntex.

==== Proceed to production use

To ensure continuity of service, you need to purchase the required number of xref:syntex-licensing.adoc[licenses] and assign those licenses to users.
Trial users who don't have a full license at the end of the trial period won't be able to fully use SharePoint Syntex.

You might have to estimate your projected use of form processing and plan for the expected number of AI Builder credits.
For help, see https://powerapps.microsoft.com/ai-builder-calculator/[Estimate the AI Builder capacity that's right for you].

==== Don't proceed to production use

If you don't purchase licenses following the trial:

* You won't be able to create new models.
* Libraries that were running models will no longer automatically classify files or extract models.
* Any previously classified files or extracted metadata won't be affected.
* Content centers and any document understanding models won't be automatically deleted.
These will remain available for use if you decide to purchase licenses in the future.
* Form processing models will be stored in the Dataverse (previously named Common Data Service (CDS)) instance of the default Power Platform environment.
These could be used with future licensing for SharePoint Syntex or with AI Builder capabilities in the Power Platform.

=== See also

xref:adoption-getstarted.adoc[Get started driving adoption of SharePoint Syntex]

xref:adoption-scenarios.adoc[Scenarios and use cases for SharePoint Syntex]
