= Connect your domain to Microsoft 365
:audience: Admin
:author: twernermsft
:description: Learn how to connect your domain to Microsoft 365.
:f1.keywords: ["NOCSH"]
:manager: scotv
:monikerRange: o365-worldwide
:ms.author: twerner
:ms.collection: ["highpri", "M365-subscription-management", "Adm_O365"]
:ms.custom: ["VSBFY23", "AdminSurgePortfolio", "adminvideo", "admindeeplinkMAC"]
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["BCS160", "MET150", "MOE150"]

== Connect your domain to Microsoft 365 for business

Check out https://go.microsoft.com/fwlink/?linkid=2197659[Microsoft 365 small business help] on YouTube.

=== Watch: Connect your domain to Microsoft 365

Check out this video and others on our https://go.microsoft.com/fwlink/?linkid=2198216[YouTube channel].

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/RE4LFpy?autoplay=false]
____

Once you've set up Microsoft 365 and moved your email data from Google Workspace, you can connect your domain to Microsoft 365.

First you will need to delete existing DNS records from Google, and then we can add new DNS records from Microsoft 365.

. Sign into your Google Workspace admin console at https://admin.google.com[admin.google.com].
. Select *Domains*, *Manage domains*, *View details*, *Manage domain*, then *DNS* in the left nav.
. Scroll down to *Synthetic records*, open *Google Workspace*, select *Delete*, then *Delete* again.
. Scroll down to *Custom resource records* and delete any existing DNS records that appear, including any you may have created previously for Microsoft 365.
. Go to the https://admin.microsoft.com[Microsoft 365 admin center].
. In the left nav, choose, *Show all* > *Settings* > https://go.microsoft.com/fwlink/p/?linkid=834818[*Domains*].
. Then choose your default domain.
. Select *Continue setup*, then, to connect your domain, choose  *Continue*.
. Scroll down to view the DNS records that need to be copied to Google.
. Open *MX Records*, and under *Points to address or value*, copy the record.
. Return to Google, and in the *Custom resource records* section, open the record type dropdown and select *MX*.
. In the *Data* field, paste the record you copied.
. Then select *Add*.
. Repeat the process for CNAME and TXT records and add the values in the Google DNS management page.
. Return to the Microsoft 365 admin center and select *Continue*.
+
Your domain setup is complete.
