= Migrate Google files to Microsoft 365 for business
:audience: Admin
:author: efrene
:description: Learn how to migrate Google files to Microsoft 365 for business by using the SharePoint Migration Manager.
:f1.keywords: ["NOCSH"]
:manager: scotv
:monikerRange: o365-worldwide
:ms.author: efrene
:ms.collection: ["highpri", "M365-subscription-management", "Adm_O365"]
:ms.custom: ["VSBFY23", "AdminSurgePortfolio", "adminvideo"]
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["BCS160", "MET150", "MOE150"]

== Migrate Google files to Microsoft 365 for business with Migration Manager

Check out https://go.microsoft.com/fwlink/?linkid=2197659[Microsoft 365 small business help] on YouTube.

=== Watch: Migrate Google files to Microsoft 365 for business

Check out this video and others on our https://go.microsoft.com/fwlink/?linkid=2198217[YouTube channel].

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/RWSx43?autoplay=false]
____

When you move to Microsoft 365 for business from Google Workspace, you'll want to migrate your files from Google Drive.
You can use the SharePoint Migration Manager to move files from personal and shared Drives.
This video and summary of the required steps gives you an overview of how to do this.
For more information, see link:/sharepointmigration/mm-google-overview[Migrate Google Workspace to Microsoft 365 with Migration Manager].

____
[!NOTE] Migration Manager will make a copy of the files and move the copies to Microsoft 365 for business.
The original files will stay in Google Drives also.
____

=== Before you start

All the users should have signed in to Microsoft 365 for business and set up their OneDrive for Business.
To do this, go to https://office.com[office.com], sign in with your Microsoft 365 for business credentials, and then choose OneDrive.

=== Install the Microsoft 365 Migration App

Use the following steps to install the Microsoft 365 Migration app in your Google Workspace environment.

. In the SharePoint Admin Center, select *Migration*.
. On the *Migration* page, in the *Google Workspace* section, select *Get Started*.
. On the *Migrate your Google Workspace content to Microsoft 365* page, select *Connect to Google Workspace*.
. Select *Install and authorize*.
. On the *Google Workspace Marketplace* page, select *Sign in* and enter your Google Workspace admin credentials.
. Select *Domain Install*.
. Select *Continue*.
. Select the checkbox, then select *Allow*.
. When the installation completes, select *Done*.
. Return to the *Install the migration app* page, and select *Next*.
. Select *Sign in to Google Workspace*, and then enter your Google Workspace admin credentials.
. Select *Finish*.

=== Select and scan your drives

After installing the Microsoft 365 Migration App in your Google environment, you can now select the drives you want to migrate and then scan them to make sure that they are safe to copy to Microsoft 365.

. On the *Scan* tab, select the Google drives you want to copy to Microsoft 365.
. Select *Scan*.
When the scan completes, the drives will show a scan status of *Ready to migrate*.
. Select *Copy to migration*.

=== Start the migration

After selecting and scanning the drives you want to migrate, use the following steps to migrate them.

. On the *Migration* tab, verify the destination paths of the drives you want to migrate.
Edit them if needed.
. Select the drives you want to migrate, then select *Migrate*.
. When migration successfully completes, each drive will show a *Migration status* of *Completed*.
