= Set up Microsoft 365 for Google Workspace migration
:audience: Admin
:author: twernermsft
:description: Learn how to Set up Microsoft 365 so it is ready for migration from Google Workspace.
:f1.keywords: ["NOCSH"]
:manager: scotv
:monikerRange: o365-worldwide
:ms.author: twerner
:ms.collection: ["M365-subscription-management", "Adm_O365"]
:ms.custom: ["AdminSurgePortfolio", "adminvideo"]
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["BCS160", "MET150", "MOE150"]

== Set up Microsoft 365 for Google Workspace migration

Check out https://go.microsoft.com/fwlink/?linkid=2197659[Microsoft 365 small business help] on YouTube.

=== Watch: Set up Microsoft 365 for Google Workspace migration

Check out this video and others on our https://go.microsoft.com/fwlink/?linkid=2198101[YouTube channel].

____
[!VIDEO https://www.microsoft.com/videoplayer/embed/RE4JD2Y?autoplay=false]
____

To migrate email, calendar, and contacts from Google Workspace, you need to set up Microsoft 365 Business Premium with a temporary domain until your business domain is ready to be used with your subscription.

. Sign in to https://office.com[office.com],  and choose *Admin*.
. In the Microsoft 365 admin center, choose *Go to guided setup*.
. Optionally, install Office apps, then select *Continue*.
. Since you are migrating from Google Workspace, choose the default domain, and select *Use this domain*.
. Enter your user's names, and desired usernames, verify your email address so you can receive your user's passwords,then select *Add users and assign licenses*.
. Enter the email addresses where your users will receive their new credentials, select *Send email and continue*.
. Then *Continue* again to connect your temporary domain.
. Optionally choose to inform users in your organization about Teams, then select *Continue*.
. Expand and review your *Android and iOS settings*, then select *Create mobile app management policy*.
. Provide feedback, if desired, and choose *Go to admin center*.

The next step in the process will be to set up protections for your organization.
