'''

title: Manage GDPR data subject requests in Microsoft Whiteboard ms.author: v-jdeweese author: johnddeweese manager: alexfaulkner ms.reviewer:  audience: admin ms.topic: article ms.custom:  ms.service: microsoft-365-enterprise search.appverid: MET150 ms.collection:  ms.localizationpriority: medium description: Learn how to export, transfer, or delete personal information from Microsoft Whiteboard.

'''

== Manage GDPR data subject requests in Microsoft Whiteboard

The General Data Protection Regulation (GDPR) gives rights to users to manage personal data collected by an organization.
These rights can be exercised through a data subject request (DSR).

This article provides information about how to export, transfer, or delete personal information from Microsoft Whiteboard.

In order to manage personal information, you must first ensure that Whiteboard is enabled for your organization.
For more information, see xref:manage-whiteboard-access-organizations.adoc[Manage access to Whiteboard].

=== Export a whiteboard

==== On Windows

On Windows, do the following steps:

. Select the *More* (*...*) button for the whiteboard that you want to export.
. Select *Export image (png)*.
. In the window that opens, select a location where to save the image.

==== On iOS or the web

On iOS or the web, do the following steps:

. Open the whiteboard you want to export.
. Select the *Settings* icon.
. Do one of the following steps:
 ** In Whiteboard for iOS, select *Export image (png)*.
 ** In Whiteboard for the web, select *Export image (SVG)*.
. In the window that opens, select a location where to save the image.

=== Transfer a whiteboard

To transfer a whiteboard, contact your IT administrator and have them change ownership of any whiteboards you want to transfer.

=== Delete a whiteboard

To delete a whiteboard, do the following steps:

. Select the *More* (*...*) button for the whiteboard you want to delete.
. Select *Delete*.

To delete a whiteboard file in OneDrive for Business, do the following steps:

. Navigate to the Whiteboards folder in OneDrive.
. Right-click the whiteboard file you want to delete.
. Select *Delete*.

____
[!WARNING] This will permanently delete the selected whiteboard.
____
