'''

title: Manage access to Microsoft Whiteboard for your organization ms.author: v-jdeweese author: johnddeweese manager: alexfaulkner ms.reviewer:  audience: admin ms.topic: article ms.custom:  ms.service: microsoft-365-enterprise search.appverid: MET150 ms.collection:  ms.localizationpriority: medium description: Learn how to set up Microsoft Whiteboard for your organization in the Microsoft 365 admin center.

'''

== Manage access to Microsoft Whiteboard for your organization

____
[!NOTE] This article applies to Enterprise or Education organizations who use Whiteboard.
For US Government GCC High environments, see xref:manage-whiteboard-access-gcc-high.adoc[Manage access to Microsoft Whiteboard for GCC High environments].
____

Microsoft Whiteboard is a visual collaboration canvas where people, content, and ideas come together.
Microsoft Whiteboard on OneDrive for Business is enabled by default for applicable Microsoft 365 tenants.
It can be enabled or disabled at a tenant-wide level.
You should also ensure that *Microsoft Whiteboard Services* is enabled in the *Azure Active Directory admin center* > *Enterprise applications*.

Whiteboard conforms to global standards including SOC 1, SOC 2, ISO 27001, HIPAA, and EU Model Clauses.

The following admin settings are required for Whiteboard:

* Whiteboard must be enabled globally in the Microsoft 365 admin center.
* The `Set-SPOTenant -IsWBFluidEnabled` cmdlet must be enabled using link:/powershell/sharepoint/sharepoint-online/connect-sharepoint-online[SharePoint Online PowerShell].

You can control access to Whiteboard in the following ways:

* Enable or disable Whiteboard for your entire tenant using the Microsoft 365 admin center.
* Show or hide Whiteboard for specific users in meetings using a Teams meeting policy.
It will still be visible via the web, native clients, and the Teams tab app.
* Require conditional access policies for accessing Whiteboard using the Azure Active Directory admin center.

____
[!NOTE] Teams meeting policies only hide Whiteboard entry points;
it doesn't prevent the users from using Whiteboard.
Conditional access policies prevent any access to Whiteboard, but doesn't hide the entry points.
____

=== Enable or disable Whiteboard

To enable or disable Whiteboard for your tenant, do the following steps:

. Go to the Microsoft 365 admin center.
. On the home page of the admin center, in the Search box on the top right, type _Whiteboard_.
. In the search results, select *Whiteboard settings*.
. On the Whiteboard panel, toggle *Turn Whiteboard on or off for your entire organization* to *On*.
. Select *Save*.
. Connect to link:/powershell/sharepoint/sharepoint-online/connect-sharepoint-online[SharePoint Online PowerShell].
. Enable Fluid using the following `Set-SPOTenant` cmdlet:

 Set-SPOTenant -IsWBFluidEnabled $true

=== Show or hide Whiteboard

To show or hide Whiteboard in meetings, see link:/microsoftteams/meeting-policies-content-sharing[Meeting policy settings].

=== Prevent access to Whiteboard

To prevent access to Whiteboard for specific users, see link:/azure/active-directory/conditional-access/concept-conditional-access-policies[Building a Conditional Access policy].

=== See also

xref:manage-data-organizations.adoc[Manage data for Whiteboard]

xref:manage-sharing-organizations.adoc[Manage sharing for Whiteboard]

xref:deploy-on-windows-organizations.adoc[Deploy Whiteboard on Windows]
