'''

title: Manage clients for Microsoft Whiteboard in GCC High environments ms.author: v-jdeweese author: johnddeweese manager: alexfaulkner ms.reviewer:  audience: admin ms.topic: article ms.custom:  ms.service: microsoft-365-enterprise search.appverid: MET150 ms.collection:  ms.localizationpriority: medium description: Learn which clients are currently supported for Whiteboard.

'''

== Manage clients for Microsoft Whiteboard in GCC High environments

____
[!NOTE] This guidance applies to US Government Community Cloud (GCC) High environments.
____

Whiteboard clients are currently being updated to support OneDrive for Business.

=== Clients supported

The following clients are currently supported in Whiteboard:

* Standalone Whiteboard web application at https://whiteboard.office365.us
* Microsoft Teams meetings, chats, and channels using Teams desktop and web
* Standalone Whiteboard application for mobile

=== Clients planned

The following clients are planned for future releases of Whiteboard:

* Standalone Whiteboard application for Windows 10 or later versions
* Standalone Whiteboard application for Surface Hub (currently can be used in anonymous mode)
* Whiteboard in the Office.com app launcher
* Whiteboard in Teams meetings on Surface Hub and Teams meeting rooms
* Whiteboard in 1:1 calls in Teams

____
[!NOTE] While users can install the Windows client, they won't be able to sign in until the client is updated.
____

=== See also

xref:manage-whiteboard-access-gcc-high.adoc[Manage access to Whiteboard - GCC High]

xref:manage-data-gcc-high.adoc[Manage data for Whiteboard - GCC High]

xref:manage-sharing-gcc-high.adoc[Manage sharing for Whiteboard - GCC High]
