= Manage sharing for Microsoft Whiteboard in GCC High environments
:audience: admin
:author: johnddeweese
:description: Learn how to manage sharing for Microsoft Whiteboard in GCC High environments.
:manager: alexfaulkner
:ms.author: v-jdeweese
:ms.collection:
:ms.custom:
:ms.localizationpriority: medium
:ms.reviewer:
:ms.service: microsoft-365-enterprise
:ms.topic: article
:search.appverid: MET150

== Manage sharing for Microsoft Whiteboard in GCC High environments

____
[!NOTE] This guidance applies to US Government Community Cloud (GCC) High environments.
The sharing experience differs based on the device and client being used.
____

=== Share in Teams meetings

When you share a whiteboard in a Teams meeting, Whiteboard creates a sharing link.
This link is accessible by anyone within the organization.
The whiteboard is also shared with any in-tenant users in the meeting.
Whiteboards are shared using company-shareable links, regardless of the default setting.
Support for the default sharing link type is planned.

There's more capability for temporary collaboration by most external and shared device accounts during a meeting.
Users can temporarily view and collaborate on whiteboards when they're shared in a Teams meeting, similar to PowerPoint Live sharing.

In this case, Whiteboard provides temporary viewing and collaboration on the whiteboard during the Teams meeting only.
A share link isn't created and Whiteboard doesn't grant access to the file.

If you have external sharing enabled for OneDrive for Business, no further action is required.

If you restrict external sharing for OneDrive for Business, you can keep it restricted, and just enable a new setting in order for external and shared device accounts to work.
To do so, follow these steps:

. Ensure that Whiteboard is enabled for your organization.
For more information, see xref:manage-whiteboard-access-gcc-high.adoc[Manage access to Whiteboard].
. Using PowerShell, connect to your tenant and ensure the SharePoint Online module is updated by running the following command:
+
[,powershell]
----
Update-Module -Name Microsoft.Online.SharePoint.PowerShell
----

. Then run the following *Set-SPOTenant* command:
+
[,powershell]
----
Set-SPOTenant -AllowAnonymousMeetingParticipantsToAccessWhiteboards On
----

This setting applies only to whiteboards and replaces the previously shared settings: *OneDriveLoopSharingCapability* and *CoreLoopSharingCapability*.
Those settings are no longer applicable and can be disregarded.

____
[!NOTE] This applies only to guests and federated users.
It does not apply to anonymous meeting users at this time.
____

These changes should take approximately 60 minutes to apply across your tenancy.

|===
| Scenario | Storage and ownership | Sharing settings | Sharing experience

| Start the whiteboard from a desktop or mobile device
| Storage: OneDrive for Business +  + Owner: User who creates the whiteboard
| Enabled
| In-tenant users: Can create, view, and collaborate +  + External users: Can view and collaborate during the meeting only (the button to share a whiteboard won't appear for external users) +  + Shared device accounts: Can view and collaborate during the meeting only

| Start the whiteboard from a Surface Hub or Microsoft Teams Rooms
| Not yet available
|
|
|===

=== Add as a tab in Teams channels and chats

When you add a whiteboard as a tab in a Teams channel or chat, Whiteboard will create a sharing link that's accessible by anyone in the organization.

|===
| Scenario | Storage and ownership | Sharing settings | Sharing experience

| Add the whiteboard to a channel or chat from a desktop or mobile device
| Storage: OneDrive for Business +  + Owner: User who creates the whiteboard
| Not applicable
| In-tenant users: Can initiate, view, and collaborate +  + External users: Not supported
|===

=== Create and share in Whiteboard native clients

When you share a whiteboard from the web, desktop, or mobile clients, you can choose specific people.
You can also create a sharing link that's accessible by anyone in the organization.

____
[!NOTE] External sharing during a Teams meeting is not yet available, but will be added in a future release.
____

|===
| Scenario | Storage and ownership | Sharing settings | Sharing experience

| Create the whiteboard from a desktop or mobile device
| Storage: OneDrive for Business +  + Owner: User who creates the whiteboard
| Not applicable
| In-tenant users: Can share within their organization +  + External users: Sharing with external users isn't supported at this time

| Create the whiteboard from a Surface Hub
| Storage: Local +  + Owner: None
| Not applicable
| In-tenant users (coming soon): User will be able to sign in to save and share the board +  + External users: Sharing with external users isn't supported at this time

| Create the whiteboard from Microsoft Teams Rooms
| Not yet available
|
|
|===

=== See also

xref:manage-whiteboard-access-gcc-high.adoc[Manage access to Whiteboard - GCC High]

xref:manage-data-gcc-high.adoc[Manage data for Whiteboard - GCC High]

xref:manage-clients-gcc-high.adoc[Manage clients for Whiteboard - GCC High]
