= 
schmurky
:keywords: advanced hunting, threat hunting, cyber threat hunting,
Microsoft 365 Defender, microsoft 365, m365, search, query, telemetry,
schema reference, kusto, table, column, data type, description, threat &
vulnerability management, TVM, device management, software, inventory,
vulnerabilities, CVE ID, OS DeviceTvmSoftwareInventoryVulnerabilities

== DeviceTvmSoftwareVulnerabilities

{empty}[!INCLUDE link:../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* - Microsoft 365 Defender

____
[!IMPORTANT] Some information relates to pre-released product which may
be substantially modified before it’s commercially released. Microsoft
makes no warranties, express or implied, with respect to the information
provided here.
____

The `DeviceTvmSoftwareVulnerabilities` table in the advanced hunting
schema contains the
link:/windows/security/threat-protection/microsoft-defender-atp/next-gen-threat-and-vuln-mgt[Microsoft
Defender Vulnerability Management] list of vulnerabilities in installed
software products. This table also includes operating system
information, CVE IDs, and vulnerability severity information. You can
use this table, for example, to hunt for events involving devices that
have severe vulnerabilities in their software. Use this reference to
construct queries that return information from the table.

____
[!NOTE] The `DeviceTvmSoftwareInventory` and
`DeviceTvmSoftwareVulnerabilities` tables have replaced the
`DeviceTvmSoftwareInventoryVulnerabilities` table. Together, the first
two tables include more columns you can use to help inform your
vulnerability management activities or hunt for vulnerable devices.
____

For information on other tables in the advanced hunting schema, see
link:advanced-hunting-schema-tables.md[the advanced hunting reference].

[width="100%",cols="36%,29%,35%",options="header",]
|===
|Column name |Data type |Description
|`DeviceId` |`string` |Unique identifier for the machine in the service

|`DeviceName` |`string` |Fully qualified domain name (FQDN) of the
machine

|`OSPlatform` |`string` |Platform of the operating system running on the
machine. Indicates specific operating systems, including variations
within the same family, such as Windows 11, Windows 10, and Windows 7.

|`OSVersion` |`string` |Version of the operating system running on the
machine

|`OSArchitecture` |`string` |Architecture of the operating system
running on the machine

|`SoftwareVendor` |`string` |Name of the software publisher

|`SoftwareName` |`string` |Name of the software product

|`SoftwareVersion` |`string` |Version number of the software product

|`CveId` |`string` |Unique identifier assigned to the security
vulnerability under the Common Vulnerabilities and Exposures (CVE)
system

|`VulnerabilitySeverityLevel` |`string` |Severity level assigned to the
security vulnerability based on the CVSS score and dynamic factors
influenced by the threat landscape

|`RecommendedSecurityUpdate` |`string` |Name or description of the
security update provided by the software publisher to address the
vulnerability

|`RecommendedSecurityUpdateId` |`string` |Identifier of the applicable
security updates or identifier for the corresponding guidance or
knowledge base (KB) articles
|===

=== Related topics

* link:advanced-hunting-overview.md[Proactively hunt for threats]
* link:advanced-hunting-query-language.md[Learn the query language]
* link:advanced-hunting-shared-queries.md[Use shared queries]
* link:advanced-hunting-query-emails-devices.md[Hunt across devices&#44;
emails&#44; apps&#44; and identities]
* link:advanced-hunting-schema-tables.md[Understand the schema]
* link:advanced-hunting-best-practices.md[Apply query best practices]
* link:/windows/security/threat-protection/microsoft-defender-atp/next-gen-threat-and-vuln-mgt[Overview
of Microsoft Defender Vulnerability Management]
