= 
schmurky
:keywords: advanced hunting, threat hunting, cyber threat hunting,
Microsoft 365 Defender, microsoft 365, m365, search, query, telemetry,
schema reference, kusto, table, column, data type, description, threat &
vulnerability management, evidence, software evidence, TVM, device
management, software, inventory, vulnerabilities, CVE ID, OS
DeviceTvmSoftwareEvidenceBeta

== DeviceTvmSoftwareEvidenceBeta

{empty}[!INCLUDE link:../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* - Microsoft 365 Defender - Microsoft Defender for Endpoint

____
[!IMPORTANT] The `DeviceTvmSoftwareEvidenceBeta` table is currently in
beta. Once it leaves beta, the final table name will change and column
names may also change. The modifications will then likely break queries
that are still using previous names. Users are advised to review and
adjust their queries when this table is finalized.
____

The `DeviceTvmSoftwareEvidenceBeta` table in the advanced hunting schema
contains data from
link:/windows/security/threat-protection/microsoft-defender-atp/next-gen-threat-and-vuln-mgt[Microsoft
Defender Vulnerability Management] related to the
link:/microsoft-365/security/defender-endpoint/tvm-software-inventory#software-evidence[software
evidence section]. This table allows you to view evidence of where a
specific software was detected on a device. You can use this table, for
example, to identify the file paths of specific software. Use this
reference to construct queries that return information from the table.

For information on other tables in the advanced hunting schema, see
link:advanced-hunting-schema-tables.md[the advanced hunting reference].

[width="100%",cols="36%,29%,35%",options="header",]
|===
|Column name |Data type |Description
|`DeviceId` |`string` |Unique identifier for the device in the service

|`SoftwareVendor` |`string` |Name of the software publisher

|`SoftwareName` |`string` |Name of the software product

|`SoftwareVersion` |`string` |Version number of the software product

|`RegistryPaths` |`dynamic` |Registry paths where evidence indicating
the existence of the software on a device was detected

|`DiskPaths` |`dynamic` |Disk paths where file-level evidence indicating
the existence of the software on a device was detected

|`LastSeenTime` |`string` |Date and time when the device last seen by
this service
|===

=== Related topics

* link:/windows/security/threat-protection/microsoft-defender-atp/next-gen-threat-and-vuln-mgt[Overview
of Microsoft Defender Vulnerability Management]
* link:advanced-hunting-overview.md[Proactively hunt for threats]
* link:advanced-hunting-query-language.md[Learn the query language]
* link:advanced-hunting-shared-queries.md[Use shared queries]
* link:advanced-hunting-query-emails-devices.md[Hunt across devices&#44;
emails&#44; apps&#44; and identities]
* link:advanced-hunting-schema-tables.md[Understand the schema]
* link:advanced-hunting-best-practices.md[Apply query best practices]
