= 
schmurky
:keywords: advanced hunting, threat hunting, cyber threat hunting,
Microsoft 365 Defender, microsoft 365, m365, search, query, telemetry,
schema reference, kusto, table, column, data type, description, threat &
vulnerability management, TVM, device management, security
configuration, DeviceTvmHardwareFirmware

== DeviceTvmHardwareFirmware

{empty}[!INCLUDE link:../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* - Microsoft 365 Defender

____
[!IMPORTANT] Some information relates to prereleased product which may
be substantially modified before it’s commercially released. Microsoft
makes no warranties, express or implied, with respect to the information
provided here.
____

The `DeviceTvmHardwareFirmware` table in the advanced hunting schema
contains hardware and firmware information of devices as checked by
link:/windows/security/threat-protection/microsoft-defender-atp/next-gen-threat-and-vuln-mgt[Microsoft
Defender Vulnerability Management]. The information includes the system
model, processor, and BIOS, among others.

For information on other tables in the advanced hunting schema, see
link:advanced-hunting-schema-tables.md[the advanced hunting reference].

[width="100%",cols="36%,29%,35%",options="header",]
|===
|Column name |Data type |Description
|`DeviceId` |`string` |Unique identifier for the device in the service

|`DeviceName` |`string` |Fully qualified domain name (FQDN) of the
device

|`ComponentType` |`string` |Type of hardware or firmware component

|`Manufacturer` |`string` |Manufacturer of hardware or firmware
component

|`ComponentName` |`string` |Name of hardware or firmware component

|`ComponentFamily` |`string` |Component family or class, a grouping of
components that have similar features or characteristics as determined
by the manufacturer

|`ComponentVersion` |`string` |Component version (for example, BIOS
version)

|`AdditionalFields` |`string` |Additional information about the
components in JSON array format
|===

You can try the following sample queries to use the information
available in the `DeviceTvmHardwareFirmware` table:

[source,kusto]
----
// Count the number of Lenovo devices
DeviceTvmHardwareFirmware
| where ComponentType == "Hardware" and Manufacturer == "lenovo"
| summarize count()
----

[source,kusto]
----
// Find all devices with a specific BIOS version, replace ComponentVersion with what you are looking for
DeviceTvmHardwareFirmware
| where ComponentType == "Bios" and ComponentVersion contains "N2VET29W"
|project DeviceId, DeviceName
----

=== Related topics

* link:advanced-hunting-overview.md[Proactively hunt for threats]
* link:advanced-hunting-query-language.md[Learn the query language]
* link:advanced-hunting-schema-tables.md[Understand the schema]
* link:advanced-hunting-best-practices.md[Apply query best practices]
* link:/windows/security/threat-protection/microsoft-defender-atp/next-gen-threat-and-vuln-mgt[Overview
of Microsoft Defender Vulnerability Management]
