= 
schmurky
:keywords: advanced hunting, threat hunting, cyber threat hunting,
Microsoft 365 Defender, microsoft 365, m365, search, query, telemetry,
schema reference, kusto, device, devicefromIP, function, enrichment

== DeviceFromIP()

{empty}[!INCLUDE link:../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* - Microsoft 365 Defender

{empty}[!INCLUDE link:../includes/prerelease.md[Prerelease information]]

Use the `DeviceFromIP()` function in your
link:advanced-hunting-overview.md[advanced hunting] queries to quickly
obtain the list of devices that have been assigned to a certain IP
address at a given point in time.

This function returns a table with the following columns:

[width="100%",cols="32%,34%,34%",options="header",]
|===
|Column |Data type |Description
|`IP` |`string` |IP address
|`DeviceId` |`string` |Unique identifier for the device in the service
|===

=== Syntax

[source,kusto]
----
invoke DeviceFromIP()
----

=== Arguments

This function is invoked as part of a query.

* *x*—The first parameter is typically already a column in the query. In
this case, it is the column named `IP`, the IP address for which you
want to see a list of devices that have been assigned to it. It should
be a local IP address. External IP addresses are not supported.
* *y*—A second optional parameter is the `Timestamp`, which instructs
the function to obtain the most recent assigned devices from a specific
time. If not specified, the function returns the latest available
records.

=== Example

==== Get the latest devices that have been assigned specific IP addresses

[source,kusto]
----
DeviceNetworkEvents 
| limit 100 
| project IP = LocalIP 
| invoke DeviceFromIP()
----

=== Related topics

* link:advanced-hunting-overview.md[Advanced hunting overview]
* link:advanced-hunting-query-language.md[Learn the query language]
* link:advanced-hunting-schema-tables.md[Understand the schema]
