= Alert grading playbooks
:audience: ITPro
:author: dansimp
:description: Review the alerts for well-known attacks and take recommended actions to remediate the attack and protect your network.
:f1.keywords: ["NOCSH"]
:keywords: incidents, alerts, investigate, analyze, response, correlation, attack, machines, devices, users, identities, identity, mailbox, email, 365, microsoft, m365
:manager: dansimp
:ms.author: dansimp
:ms.collection: ["M365-security-compliance", "m365initiative-m365-defender"]
:ms.custom: ["autoir", "admindeeplinkDEFENDER"]
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.reviewer: evaldm, isco
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: m365d
:ms.topic: how-to
:search.appverid: met150

== Alert grading playbooks

[!INCLUDE xref:../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* Microsoft 365 Defender

Alert grading playbooks allow you to methodically review and quickly classify the alerts for well-known attacks and take recommended actions to remediate the attack and protect your network.
Alert grading will also help in properly classifying the overall incident.

As a security researcher or security operations center (SOC) analyst, you must have access to the Microsoft 365 Defender portal so that you can:

* Assess and review the generated alerts and associated incidents.
See xref:investigate-alerts.adoc[investigate alerts].
* Search your tenant's security signal data and check for potential threats and suspicious activities.
See xref:advanced-hunting-overview.adoc[advanced hunting].

____
[!Note] You can provide feedback to Microsoft about true positive and false positives alerts, not only at the end of the investigation, but also during the investigation process.
This can help Microsoft with future analysis and classification of security events.
____

=== Microsoft Defender for Office 365

link:/microsoft-365/security/office-365-security/defender-for-office-365[Microsoft Defender for Office 365] safeguards your organization against malicious threats posed by email messages, links (URLs), and collaboration tools.
Defender for Office 365 includes:

* Threat protection policies
+
Define threat-protection policies to set the appropriate level of protection for your organization.

* Reports
+
View real-time reports to monitor Defender for Office 365 performance in your organization.

* Threat investigation and response capabilities
+
Use leading-edge tools to investigate, understand, simulate, and prevent threats.

* Automated investigation and response capabilities
+
Save time and effort investigating and mitigating threats.

Defender for Office 365 alerts can be classified as:

* True positive (TP) for confirmed malicious activity.
* False positive (FP) for confirmed non-malicious activity.

____
[!Note] Microsoft 365 Defender portal https://security.microsoft.com brings together functionality from existing Microsoft security portals.
The Microsoft 365 Defender portal emphasizes quick access to information, simpler layouts, and bringing related information together for easier use.
____

=== Microsoft Defender for Cloud Apps

link:/defender-cloud-apps[Microsoft Defender for Cloud Apps] is a Cloud Access Security Broker (CASB) that supports various deployment modes including log collection, API connectors, and reverse proxy.
It provides rich visibility, control over data travel, and sophisticated analytics to identify and combat cyberthreats across all your Microsoft and third-party cloud services.

Defender for Cloud Apps natively integrates with leading Microsoft solutions and is designed with security professionals in mind.
It provides simple deployment, centralized management, and innovative automation capabilities.

The Defender for Cloud Apps framework includes the capability to protect your network against cyberthreats and anomalies, detects unusual behavior across cloud apps to identify ransomware, compromised users or rogue applications.
It enables the analysis of high-risk usage and can remediate automatically to limit the risk to your organization.

Defender for Cloud Apps alerts can be classified as:

* TP for confirmed malicious activity.
* Benign true positive (B-TP) for suspicious but not malicious activity, such as a penetration test or other authorized suspicious action.
* FP for confirmed non-malicious activity.

=== Alert grading playbooks

See these playbooks for steps to more quickly grade alerts for the following threats:

* xref:alert-grading-playbook-email-forwarding.adoc[Suspicious email forwarding activity]
* xref:alert-grading-playbook-inbox-manipulation-rules.adoc[Suspicious inbox manipulation rules]
* xref:alert-grading-playbook-inbox-forwarding-rules.adoc[Suspicious inbox forwarding rules]

See xref:investigate-alerts.adoc[Investigate alerts] for information on how to examine alerts with the Microsoft 365 Defender portal.
