= 
mjcaparas
:keywords: access, apis, application context, user context, aad
application, access token

== Access the Microsoft 365 Defender APIs

{empty}[!INCLUDE link:../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:*

* Microsoft 365 Defender

____
[!NOTE] *Try our new APIs using MS Graph security API*. Find out more
at: link:/graph/api/resources/security-api-overview[Use the Microsoft
Graph security API - Microsoft Graph beta | Microsoft Learn].
____

____
[!IMPORTANT] Some information relates to prereleased product which may
be substantially modified before it’s commercially released. Microsoft
makes no warranties, express or implied, with respect to the information
provided here.
____

Microsoft 365 Defender exposes much of its data and actions through a
set of programmatic APIs. These APIs help you automate workflows and
make full use of Microsoft 365 Defender’s capabilities.

In general, you’ll need to take the following steps to use the APIs:

* Create an Azure Active Directory application
* Get an access token using this application
* Use the token to access the Microsoft 365 Defender API

____
[!NOTE] API access requires OAuth2.0 authentication. For more
information, see
link:/azure/active-directory/develop/active-directory-v2-protocols-oauth-code[OAuth
2.0 Authorization Code Flow].
____

Once you’ve accomplished these steps, you’re ready to access the
Microsoft 365 Defender API using a particular context.

=== Application context (Recommended)

Use this context for apps that run without a signed-in user present,
such as background services or daemons.

[arabic]
. Create an Azure Active Directory web application.
. Assign the desired permissions to the application.
. Create a key for the application.
. Get a security token using the application and its key.
. Use the token to access the Microsoft 365 Defender API.

For more information, see *link:api-create-app-web.md[Create an app to
access Microsoft 365 Defender without a user]*.

=== User context

Use this context to perform actions on behalf of a single user.

[arabic]
. Create an Azure Active Directory native application.
. Assign the desired permission to the application.
. Get a security token using the user credentials for the application.
. Use the token to access the Microsoft 365 Defender API.

For more information, see *link:api-create-app-user-context.md[Create an
app to access Microsoft 365 Defender APIs on behalf of a user]*.

=== Partner context

Use this context when you need to provide an app to many users across
link:/azure/active-directory/develop/single-and-multi-tenant-apps[multiple
tenants].

[arabic]
. Create an Azure Active Directory multi-tenant application.
. Assign the desired permission to the application.
. Get
link:/azure/active-directory/develop/v2-permissions-and-consent#requesting-consent-for-an-entire-tenant[admin
consent] for the app from each tenant.
. Get a security token using user credentials based on a customer’s
tenant ID.
. Use the token to access the Microsoft 365 Defender API.

For more information, see *link:api-partner-access.md[Create an app with
partner access to Microsoft 365 Defender APIs]*.

=== Related articles

* link:/graph/api/resources/security-api-overview[Use the Microsoft
Graph security API - Microsoft Graph beta | Microsoft Learn]
* link:api-overview.md[Microsoft 365 Defender APIs overview]
* link:/azure/active-directory/develop/active-directory-v2-protocols-oauth-code[OAuth
2.0 authorization for user sign in and API access]
* link:/training/modules/manage-secrets-with-azure-key-vault/[Manage
secrets in your server apps with Azure Key Vault]
* link:api-hello-world.md[Create a `Hello world' application that
accesses the Microsoft 365 APIs]
