= 
mjcaparas
:keywords: incident, incidents, api

== Microsoft 365 Defender incidents API and the incidents resource type

{empty}[!INCLUDE link:../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365
Defender]

____
[!NOTE] *Try our new APIs using MS Graph security API*. Find out more
at: link:/graph/api/resources/security-api-overview[Use the Microsoft
Graph security API - Microsoft Graph beta | Microsoft Learn].
____

____
[!IMPORTANT] Some information relates to prereleased product which may
be substantially modified before it’s commercially released. Microsoft
makes no warranties, express or implied, with respect to the information
provided here.
____

An link:incidents-overview.md[incident] is a collection of related
alerts that help describe an attack. Events from different entities in
your organization are automatically aggregated by Microsoft 365
Defender. You can use the incidents API to programatically access your
organization’s incidents and related alerts.

=== Quotas and resource allocation

You can request up to 50 calls per minute or 1500 calls per hour. Each
method also has its own quotas. For more information on method-specific
quotas, see the respective article for the method you want to use.

A `429` HTTP response code indicates that you’ve reached a quota, either
by number of requests sent, or by allotted running time. The response
body will include the time until the quota you reached will be reset.

=== Permissions

The incidents API requires different kinds of permissions for each of
its methods. For more information about required permissions, see the
respective method’s article.

=== Methods

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Method |Return Type |Description
|link:api-list-incidents.md[List incidents]
|link:api-incident.md[Incident] list |Get a list of incidents.

|link:api-update-incidents.md[Update incident]
|link:api-incident.md[Incident] |Update a specific incident.

|link:api-get-incident.md[Get incident] |link:api-incident.md[Incident]
|Get a single incident.
|===

=== Request body, response, and examples

Refer to the respective method articles for more details on how to
construct a request or parse a response, and for practical examples.

=== Common properties

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Property |Type |Description
|incidentId |long |Incident unique ID.

|redirectIncidentId |nullable long |The Incident ID the current Incident
was merged to.

|incidentName |string |The name of the Incident.

|createdTime |DateTimeOffset |The date and time (in UTC) the Incident
was created.

|lastUpdateTime |DateTimeOffset |The date and time (in UTC) the Incident
was last updated.

|assignedTo |string |Owner of the Incident.

|severity |Enum |Severity of the Incident. Possible values are:
`UnSpecified`, `Informational`, `Low`, `Medium`, and `High`.

|status |Enum |Specifies the current status of the incident. Possible
values are: `Active`, `InProgress`, `Resolved`, and `Redirected`.

|classification |Enum |Specification of the incident. Possible values
are: `TruePositive`, `Informational, expected activity`, and
`FalsePositive`.

|determination |Enum |Specifies the determination of the incident.

|tags |string list |List of Incident tags.

|comments |List of incident comments |Incident Comment object contains:
comment string, createdBy string, and createTime date time.

|alerts |alert list |List of related alerts. See examples at
link:api-list-incidents.md[List incidents] API documentation.
|===

____
[!NOTE] Around August 29, 2022, previously supported alert determination
values (`Apt' and `SecurityPersonnel') will be deprecated and no longer
available via the API.
____

=== Related articles

* link:/graph/api/resources/security-api-overview[Use the Microsoft
Graph security API - Microsoft Graph beta | Microsoft Learn]
* link:api-overview.md[Microsoft 365 Defender APIs overview]
* link:incidents-overview.md[Incidents overview]
* link:api-list-incidents.md[List incidents API]
* link:api-update-incidents.md[Update incident API]
