= Create an app to access Microsoft 365 Defender APIs on behalf of a user
:audience: ITPro
:author: mjcaparas
:description: Learn how to access Microsoft 365 Defender APIs on behalf of a user.
:f1.keywords: ["NOCSH"]
:keywords: access, on behalf of user, api, application, user, access token, token,
:manager: dansimp
:ms.author: macapara
:ms.collection: M365-security-compliance
:ms.custom: api
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: m365d
:ms.topic: conceptual
:search.appverid: ["MOE150", "MET150"]
:search.product: eADQiWindows 10XVcnh

== Create an app to access Microsoft 365 Defender APIs on behalf of a user

[!INCLUDE xref:../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* Microsoft 365 Defender

____
[!IMPORTANT] Some information relates to prereleased product which may be substantially modified before it's commercially released.
Microsoft makes no warranties, express or implied, with respect to the information provided here.
____

This page describes how to create an application to get programmatic access to Microsoft 365 Defender on behalf of a single user.

If you need programmatic access to Microsoft 365 Defender without a defined user (for example, if you're writing a background app or daemon), see xref:api-create-app-web.adoc[Create an app to access Microsoft 365 Defender without a user].
If you need to provide access for multiple tenants--for example, if you're serving a large organization or a group of customers--see xref:api-partner-access.adoc[Create an app with partner access to Microsoft 365 Defender APIs].If you're not sure which kind of access you need, see xref:api-access.adoc[Get started].

Microsoft 365 Defender exposes much of its data and actions through a set of programmatic APIs.
Those APIs help you automate workflows and make use of Microsoft 365 Defender's capabilities.
This API access requires OAuth2.0 authentication.
For more information, see link:/azure/active-directory/develop/active-directory-v2-protocols-oauth-code[OAuth 2.0 Authorization Code Flow].

In general, you'll need to take the following steps to use these APIs:

* Create an Azure Active Directory (Azure AD) application.
* Get an access token using this application.
* Use the token to access Microsoft 365 Defender API.

This article explains how to:

* Create an Azure AD application
* Get an access token to Microsoft 365 Defender
* Validate the token

____
[!NOTE] When accessing Microsoft 365 Defender API on behalf of a user, you will need the correct application permissions and user permissions.
____

____
[!TIP] If you have the permission to perform an action in the portal, you have the permission to perform the action in the API.
____

=== Create an app

. Sign in to https://portal.azure.com[Azure] as a user with the *Global Administrator* role.
. Navigate to *Azure Active Directory* > *App registrations* > *New registration*.
+
:::image type="content" source="../../media/atp-azure-new-app2.png" alt-text="The New registration option in the Manage pane in the Azure portal" lightbox="../../media/atp-azure-new-app2.png":::

. In the form, choose a name for your application and enter the following information for the redirect URI, then select *Register*.
+
:::image type="content" source="../../media/nativeapp-create2.PNG" alt-text="The application registration pane in the Azure portal" lightbox="../../media/nativeapp-create2.PNG":::

 ** *Application type:* Public client
 ** *Redirect URI:* https://portal.azure.com

. On your application page, select *API Permissions* > *Add permission* > *APIs my organization uses* >, type *Microsoft Threat Protection*, and select *Microsoft Threat Protection*.
Your app can now access Microsoft 365 Defender.
+
____
[!TIP] _Microsoft Threat Protection_ is a former name for Microsoft 365 Defender, and will not appear in the original list.
You need to start writing its name in the text box to see it appear.
____
+
:::image type="content" source="../../media/apis-in-my-org-tab.PNG" alt-text="Your organization's APIs pane in the Microsoft 365 Defender portal" lightbox="../../media/apis-in-my-org-tab.PNG":::

 ** Choose *Delegated permissions*.
Choose the relevant permissions for your scenario (for example *Incident.Read*), and then select *Add permissions*.
+
:::image type="content" source="../../media/request-api-permissions-delegated.PNG" alt-text="The Delegated permissions pane in the Microsoft 365 Defender portal" lightbox="../../media/request-api-permissions-delegated.PNG":::

+
____
[!NOTE] You need to select the relevant permissions for your scenario.
_Read all incidents_ is just an example.
To determine which permission you need, please look at the *Permissions* section in the API you want to call.

For instance, to xref:api-advanced-hunting.adoc[run advanced queries], select the 'Run advanced queries' permission;
to link:/windows/security/threat-protection/microsoft-defender-atp/isolate-machine[isolate a device], select the 'Isolate machine' permission.
____

. Select *Grant admin consent*.
Every time you add a permission, you must select *Grant admin consent* for it to take effect.
+
:::image type="content" source="../../media/grant-consent-delegated.PNG" alt-text="The admin consent-granting pane in the Microsoft 365 Defender portal" lightbox="../../media/grant-consent-delegated.PNG":::

. Record your application ID and your tenant ID somewhere safe.
They're listed under *Overview* on your application page.
+
:::image type="content" source="../../media/app-and-tenant-ids.png" alt-text="The Overview pane in the Microsoft 365 Defender portal" lightbox="../../media/app-and-tenant-ids.png":::

=== Get an access token

For more information on Azure Active Directory tokens, see the link:/azure/active-directory/develop/active-directory-v2-protocols-oauth-client-creds[Azure AD tutorial].

==== Get an access token on behalf of a user using PowerShell

Use the MSAL.PS library to acquire access tokens with Delegated permissions.
Run the following commands to get access token on behalf of a user:

[,powershell]
----
Install-Module -Name MSAL.PS # Install the MSAL.PS module from PowerShell Gallery

$TenantId = " " # Paste your directory (tenant) ID here.
$AppClientId="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" # Paste your application (client) ID here.

$MsalParams = @{
   ClientId = $AppClientId
   TenantId = $TenantId
   Scopes   = 'https://graph.microsoft.com/User.Read.All','https://graph.microsoft.com/Files.ReadWrite'
}

$MsalResponse = Get-MsalToken @MsalParams
$AccessToken  = $MsalResponse.AccessToken

$AccessToken # Display the token in PS console
----

=== Validate the token

. Copy and paste the token into https://jwt.ms[JWT] to decode it.
. Make sure that the _roles_ claim within the decoded token contains the desired permissions.

In the following image, you can see a decoded token acquired from an app, with `Incidents.Read.All`, `Incidents.ReadWrite.All`, and `AdvancedHunting.Read.All` permissions:

:::image type="content" source="../../media/defender-endpoint/webapp-decoded-token.png" alt-text="The permissions section in the Decoded Token pane in the Microsoft 365 Defender portal" lightbox="../../media/defender-endpoint/webapp-decoded-token.png":::

=== Use the token to access the Microsoft 365 Defender API

. Choose the API you want to use (incidents, or advanced hunting).
For more information, see xref:api-supported.adoc[Supported Microsoft 365 Defender APIs].
. In the http request you're about to send, set the authorization header to `"Bearer" <token>`, _Bearer_ being the authorization scheme, and _token_ being your validated token.
. The token will expire within one hour.
You can send more than one request during this time  with the same token.

The following example shows how to send a request to get a list of incidents *using C#*.

[,c#]
----
    var httpClient = new HttpClient();
    var request = new HttpRequestMessage(HttpMethod.Get, "https://api.security.microsoft.com/api/incidents");

    request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);

    var response = httpClient.SendAsync(request).GetAwaiter().GetResult();
----

=== Related articles

* xref:api-overview.adoc[Microsoft 365 Defender APIs overview]
* xref:api-access.adoc[Access the Microsoft 365 Defender APIs]
* xref:api-hello-world.adoc[Create a 'Hello world' app]
* xref:api-create-app-web.adoc[Create an app to access Microsoft 365 Defender without a user]
* xref:api-partner-access.adoc[Create an app with multi-tenant partner access to Microsoft 365 Defender APIs]
* xref:api-terms.adoc[Learn about API limits and licensing]
* xref:api-error-codes.adoc[Understand error codes]
* link:/azure/active-directory/develop/active-directory-v2-protocols-oauth-code[OAuth 2.0 authorization for user sign in and API access]
