= Integrate your SIEM tools with Microsoft 365 Defender
:audience: ITPro
:author: mjcaparas
:description: Learn how to use REST API and configure supported security information and events management tools to receive and pull detections.
:keywords: configure siem, security information and events management tools, splunk, arcsight, custom indicators, rest api, alert definitions, indicators of compromise
:manager: dansimp
:ms.author: macapara
:ms.collection: M365-security-compliance
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: m365d
:ms.topic: article
:search.appverid: met150
:search.product: eADQiWindows 10XVcnh

== Integrate your SIEM tools with Microsoft 365 Defender

[!INCLUDE xref:../../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/p/?linkid=2154037[Microsoft Defender for Endpoint]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

=== Pull Microsoft 365 Defender incidents and streaming event data using security information and events management (SIEM) tools

____
[!NOTE]

* xref:incident-queue.adoc[Microsoft 365 Defender Incidents] consists of collections of correlated alerts and their evidence.
* xref:streaming-api.adoc[Microsoft 365 Defender Streaming API] streams event data from Microsoft 365 Defender to event hubs or Azure storage accounts.
____

Microsoft 365 Defender supports security information and event management (SIEM) tools ingesting information from your enterprise tenant in Azure Active Directory (AAD) using the OAuth 2.0 authentication protocol for a registered AAD application representing the specific SIEM solution or connector installed in your environment.

For more information, see:

* xref:api-terms.adoc[Microsoft 365 Defender APIs license and terms of use]
* xref:api-access.adoc[Access the Microsoft 365 Defender APIs]
* xref:api-hello-world.adoc[Hello World example]
* xref:api-create-app-web.adoc[Get access with application context]

There are two primary models to ingest security information:

. Ingesting Microsoft 365 Defender incidents and their contained alerts from a REST API in Azure.
. Ingesting streaming event data either through Azure Event Hubs or Azure Storage Accounts.

Microsoft 365 Defender currently supports the following SIEM solution integrations:

* <<ingesting-incidents-from-the-incidents-rest-api,Ingesting incidents from the incidents REST API>>
* <<ingesting-streaming-event-data-via-event-hubs,Ingesting streaming event data via Event Hub>>

=== Ingesting incidents from the incidents REST API

==== Incident schema

For more information on Microsoft 365 Defender incident properties including contained alert and evidence entities metadata, see link:../defender/api-list-incidents.md#schema-mapping[Schema mapping].

==== Splunk

Using the new, fully-supported Splunk Add-on for Microsoft Security that supports:

* Ingesting incidents that contain alerts from the following products, which are mapped onto Splunk's Common Information Model (CIM):
 ** Microsoft 365 Defender
 ** Microsoft Defender for Endpoint
 ** Microsoft Defender for Identity and Azure Active Directory Identity Protection
 ** Microsoft Defender for Cloud Apps
* Ingesting Defender for Endpoint alerts (from the Defender for Endpoint's Azure endpoint) and updating these alerts
* Support for updating Microsoft 365 Defender Incidents and/or Microsoft Defender for Endpoint Alerts and the respective dashboards has been moved to the Microsoft 365 App for Splunk.

For more information on:

* The Splunk Add-on for Microsoft Security, see the https://splunkbase.splunk.com/app/6207/#/overview[Microsoft Security Add-on on Splunkbase]
* The Microsoft 365 App for Splunk, see the https://splunkbase.splunk.com/app/3786/[Microsoft 365 App on Splunkbase]

==== Micro Focus ArcSight

The new SmartConnector for Microsoft 365 Defender ingests incidents into ArcSight and maps these onto its Common Event Framework (CEF).

For more information on the new ArcSight SmartConnector for Microsoft 365 Defender, see https://community.microfocus.com/cyberres/productdocs/w/connector-documentation/39246/smartconnector-for-microsoft-365-defender[ArcSight Product Documentation].

The SmartConnector replaces the previous FlexConnector for Microsoft Defender for Endpoint that has been deprecated.

=== Ingesting streaming event data via Event Hubs

First you need to stream events from your AAD tenant to your Event Hubs or Azure Storage Account.
For more information, see xref:../defender/streaming-api.adoc[Streaming API].

For more information on the event types supported by the Streaming API, see xref:../defender/supported-event-types.adoc[Supported streaming event types].

==== Splunk

Use the Splunk Add-on for Microsoft Cloud Services to ingest events from Azure Event Hubs.

For more information on the Splunk Add-on for Microsoft Cloud Services, see the https://splunkbase.splunk.com/app/3110/[Microsoft Cloud Services Add-on on Splunkbase].

==== IBM QRadar

____
Use the new IBM QRadar Microsoft 365 Defender Device Support Module (DSM) that calls the xref:streaming-api.adoc[Microsoft 365 Defender Streaming API] that allows ingesting streaming event data from Microsoft 365 Defender products via Event Hubs or Azure Storage Account.
For more information on supported event types, see xref:supported-event-types.adoc[Supported event types].
____
