= 
siosulli

== Edit or delete roles in Microsoft 365 Defender role-based access control (RBAC)

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365
Defender]
* https://go.microsoft.com/fwlink/?LinkID=2198108[Microsoft Defender for
Identity]
* https://go.microsoft.com/fwlink/?LinkID=2158212[Microsoft Defender for
Office 365 P2]

{empty}[!includelink:../../includes/prerelease.md[Prerelease
information]]

In Microsoft 365 Defender role-based access control (RBAC), you can edit
and delete custom roles or roles that were imported from Defender for
Endpoint, Defender for Identity, or Defender for Office 365.

=== Edit roles

The following steps guide you on how to edit roles in Microsoft 365
Defender RBAC:

____
[!Important] You must be a Global Administrator or Security
Administrator in Azure Active Directory, or have all the *Authorization*
permissions assigned in Microsoft 365 Defender RBAC to perform this
task. For more information on permissions, see
link:../defender/manage-rbac.md#permissions-pre-requisites[Permission
pre-requisites].
____

[arabic]
. Sign in to the https://security.microsoft.com[Microsoft 365 Defender
portal] as global administrator or security administrator.
. In the navigation pane, select *Permissions*.
. Select *Roles* under Microsoft 365 Defender to get to the Permissions
and roles page.
. Select the role you want to edit. You can only edit one role at a
time.
. Select the *Edit* button or select *Edit* from the action menu next to
the role name. This opens a flyout pane where you can edit the role:
+
:::image type=``content''
source=``../../media/defender/m365-defender-rbac-edit-roles.png''
alt-text=``Screenshot of the activate workloads page''
lightbox=``../../media/defender/m365-defender-rbac-edit-roles.png'':::

____
[!Note] After editing an imported role, the changes made in Microsoft
365 Defender RBAC will not be reflected back in the individual product
RBAC model.
____

=== Delete Roles

To delete roles in Microsoft 365 Defender RBAC, select the role or roles
you want to delete and select *Delete roles*.

If the workload is active, by removing the role all assigned user
permission will be deleted.

____
[!Note] After deleting an imported role, the role won’t be deleted from
the individual product RBAC model. If needed, you can re-import it to
the Microsoft 365 Defender RBAC list of roles.
____

=== Next steps

* link:custom-permissions-details.md[Learn about RBAC permissions]
* link:compare-rbac-roles.md[Map existing RBAC roles to Microsoft 365
Defender RBAC roles]
