= 
dansimp

== Enable the evaluation environment for Microsoft Defender for Identity

*Applies to:* - Microsoft 365 Defender

This article is link:eval-defender-identity-overview.md[Step 2 of 2] in
the process of setting up the evaluation environment for Microsoft
Defender for Identity. For more information about this process, see the
link:eval-defender-identity-overview.md[overview article].

Use the following steps to set up your Microsoft Defender for Identity
environment.

:::image type=``content''
source=``../../media/defender/m365-defender-identity-eval-enable-steps.png''
alt-text=``The steps to enable Microsoft Defender for Identity in the
Microsoft Defender evaluation environment''
lightbox=``../../media/defender/m365-defender-identity-eval-enable-steps.png'':::

* link:#step-1-set-up-the-defender-for-identity-instance[Step 1. Set up
the Defender for Identity Instance]
* link:#step-2-install-and-configure-the-sensor[Step 2. Install and
configure the sensor]
* link:#step-3-configure-event-log-and-proxy-settings-on-machines-with-the-sensor[Step
3. Configure event log and proxy settings on machines with the sensor]
* link:#step-4-allow-defender-for-identity-to-identify-local-admins-on-other-computers[Step
4. Allow Defender for Identity to identify local admins on other
computers]

=== Step 1. Set up the Defender for Identity Instance

Sign in to the Defender for Identity portal to create your instance and
then connect this instance to your Active Directory environment.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Step |Description |More information
|1 |Create the Defender for Identity instance
|link:/defender-for-identity/install-step1[Quickstart: Create your
Microsoft Defender for Identity instance]

|2 |Connect the Defender for Identity instance to your Active Directory
forest |link:/defender-for-identity/install-step2[Quickstart: Connect to
your Active Directory Forest]
|===

=== Step 2. Install and configure the sensor

Next, download, install, and configure the Defender for Identity sensor
on the domain controllers and AD FS servers in your on-premises
environment.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Step |Description |More information
|1 |Determine how many Microsoft Defender for Identity sensors you need.
|link:/defender-for-identity/capacity-planning[Plan capacity for
Microsoft Defender for Identity]

|2 |Download the sensor setup package
|link:/defender-for-identity/install-step3[Quickstart: Download the
Microsoft Defender for Identity sensor setup package]

|3 |Install the Defender for Identity sensor
|link:/defender-for-identity/install-step4[Quickstart: Install the
Microsoft Defender for Identity sensor]

|4 |Configure the sensor
|link:/defender-for-identity/install-step5[Configure Microsoft Defender
for Identity sensor settings]
|===

=== Step 3. Configure event log and proxy settings on machines with the sensor

On the machines that you installed the sensor on, configure Windows
event log collection and Internet proxy settings to enable and enhance
detection capabilities.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Step |Description |More information
|1 |Configure Windows event log collection
|link:/defender-for-identity/configure-windows-event-collection[Configure
Windows Event collection]

|2 |Configure Internet proxy settings
|link:/defender-for-identity/configure-proxy[Configure endpoint proxy
and Internet connectivity settings for your Microsoft Defender for
Identity Sensor]
|===

=== Step 4. Allow Defender for Identity to identify local admins on other computers

Microsoft Defender for Identity lateral movement path detection relies
on queries that identify local admins on specific machines. These
queries are performed with the SAM-R protocol, using the Defender for
Identity Service account.

To ensure Windows clients and servers allow your Defender for Identity
account to perform SAM-R, a modification to Group Policy must be made to
add the Defender for Identity service account in addition to the
configured accounts listed in the Network access policy. Make sure to
apply group policies to all computers *except domain controllers*.

For instructions on how to do this, see
link:/defender-for-identity/install-step8-samr[Configure Microsoft
Defender for Identity to make remote calls to SAM].

=== Next steps

Step 3 of 3: link:eval-defender-identity-pilot.md[Pilot Microsoft
Defender for Identity]

Return to the overview for
link:eval-defender-identity-overview.md[Evaluate Microsoft Defender for
Identity]

Return to the overview for link:eval-overview.md[Evaluate and pilot
Microsoft 365 Defender]
