= 
dansimp

== Pilot Microsoft Defender for Identity

*Applies to:* - Microsoft 365 Defender

This article is link:eval-defender-identity-overview.md[Step 3 of 3] in
the process of setting up the evaluation environment for Microsoft
Defender for Identity. For more information about this process, see the
link:eval-defender-identity-overview.md[overview article].

Use the following steps to setup and configure the pilot for Microsoft
Defender for identity. Note that the recommendations don’t include
setting up a pilot group. The best practice is to go ahead and install
the sensor on all of your servers running Active Directory Domain
Services (AD DS) and Active Directory Federated Services (AD FS).

:::image type=``content''
source=``../../media/defender/m365-defender-identity-pilot-steps.png''
alt-text=``The steps for piloting Microsoft Defender for Identity in the
Microsoft Defender evaluation environment''
lightbox=``../../media/defender/m365-defender-identity-pilot-steps.png'':::

The following table describes the steps in the illustration.

* link:#step-1-configure-benchmark-recommendations-for-your-identity-environment[Step
1: Configure benchmark recommendations for your identity environment]
* link:++#step-2-try-out-capabilities--walk-through-tutorials-for-identifying-and-remediating-different-attack-types++[Step
2: Try out capabilities — Walk through tutorials for identifying and
remediating different attack types]

=== Step 1. Configure benchmark recommendations for your identity environment

Microsoft provides security benchmark recommendations for customers
using Microsoft Cloud services. The
link:/security/benchmark/azure/overview[Azure Security Benchmark] (ASB)
provides prescriptive best practices and recommendations to help improve
the security of workloads, data, and services on Azure.

These benchmark recommendations include
link:/security/benchmark/azure/baselines/defender-for-identity-security-baseline[Azure
security baseline for Microsoft Defender for Identity]. Implementing
these recommendations can take some time to plan and implement. While
these will greatly increase the security of your identity environment,
they shouldn’t prevent you from continuing to evaluate and implement
Microsoft Defender for Identity. These are provided here for your
awareness.

=== Step 2. Try out capabilities — Walk through tutorials for identifying and remediating different attack types

The Microsoft Defender for Identity documentation includes a series of
tutorials that walk through the process of identifying and remediating
various attack types.

Try out Defender for Identity tutorials: -
link:/defender-for-identity/reconnaissance-alerts[Reconnaissance alerts]
- link:/defender-for-identity/compromised-credentials-alerts[Compromised
credential alerts] -
link:/defender-for-identity/lateral-movement-alerts[Lateral movement
alerts] - link:/defender-for-identity/domain-dominance-alerts[Domain
dominance alerts] -
link:/defender-for-identity/exfiltration-alerts[Exfiltration alerts] -
link:/defender-for-identity/investigate-a-user[Investigate a user] -
link:/defender-for-identity/investigate-a-computer[Investigate a
computer] -
link:/defender-for-identity/investigate-lateral-movement-path[Investigate
lateral movement paths] -
link:/defender-for-identity/investigate-entity[Investigate entities]

=== Next steps

link:eval-defender-office-365-overview.md[Evaluate Microsoft Defender
for Office 365]

Return to the overview for
link:eval-defender-office-365-overview.md[Evaluate Microsoft Defender
for Office 365]

Return to the overview for link:eval-overview.md[Evaluate and pilot
Microsoft 365 Defender]
