= 
MSFTTracyP

== Step 1. Create the Microsoft 365 Defender Evaluation Environment for greater cyber security

You can learn about and build out this Microsoft Defender XDR solution
in steps that are distributed through the rest of this series:

* link:eval-create-eval-environment.md[How to create the environment]
* Set up or learn about each technology of this Microsoft XDR
** link:eval-defender-identity-overview.md[Microsoft Defender for
Identity]
** link:eval-defender-office-365-overview.md[Microsoft Defender for
Office]
** link:eval-defender-endpoint-overview.md[Microsoft Defender for
Endpoint]
** link:eval-defender-mcas-overview.md[Microsoft Defender for Cloud
Apps]
* link:eval-defender-investigate-respond.md[How to investigate and
respond using this XDR]
* link:eval-defender-promote-to-production.md[Promote the trial
environment to production]
* link:eval-overview.md[Back to the Overview]

The steps in this series run end-to-end, from learning the concepts
behind the Microsoft 365 Defender XDR to building it, and into taking
the evaluation environment live to production.

There are two common ways to do this next step in evaluation. This
series assumes you already have a production Microsoft 365 tenant and
will activate E5 trial licenses to evaluate Microsoft 365 Defender in
_the current environment_. An in-place evaluation will let you keep any
security methods with the purchase of licenses after the evaluation
period.

The second is to link:setup-m365deval.md[Set up your Microsoft 365
Defender trial lab environment] for the purpose of evaluation. Note that
it may not have many real signals from the business while in testing.

=== You will need to activate E5 trial licenses to evaluate Microsoft 365 Defender

[arabic]
. Log on to your existing Microsoft 365 tenant administration portal.
. Select *Purchase Services* from the navigation menu.
. Scroll down to the Office 365 section and select *Details* button
under Office 365 E5 license.
+
:::image type=``content''
source=``../../media/mdo-eval/2_mdo-eval-license-details.png''
alt-text=``The Details button in the Microsoft 365 Defender portal''
lightbox=``../../media/mdo-eval/2_mdo-eval-license-details.png'':::
. Select *Start free trial* link.
+
:::image type=``content''
source=``../../media/mdo-eval/3-m365-purchase-button.png''
alt-text=``The Start free trial button in the Microsoft 365 Defender
portal'' lightbox=``../../media/mdo-eval/3-m365-purchase-button.png'':::
. Confirm your request and click *Try now* button.
+
:::image type=``content''
source=``../../media/mdo-eval/4_mdo-trial-order.png'' alt-text=``The Try
Now button in the Microsoft 365 Defender portal''
lightbox=``../../media/mdo-eval/4_mdo-trial-order.png'':::

=== Go to the next step

link:eval-defender-identity-overview.md[Learn how to enable Microsoft
365 for Identity]

Or return to the Overview for link:eval-overview.md[Evaluate and pilot
Microsoft 365 Defender]
