= 
brendacarter

== Pilot Microsoft Defender for Cloud Apps with Microsoft 365 Defender

*Applies to:* - Microsoft 365 Defender

This article is link:eval-defender-mcas-overview.md[Step 3 of 3] in the
process of setting up the evaluation environment for Microsoft Defender
for Cloud Apps. For more information about this process, see the
link:eval-defender-mcas-overview.md[overview article].

Use the following steps to set up and configure the pilot for Microsoft
Defender for Cloud Apps.

:::image type=``content''
source=``../../media/defender/m365-defender-mcas-pilot-steps.png''
alt-text=``The steps for piloting the Microsoft Defender for Cloud
Apps''
lightbox=``../../media/defender/m365-defender-mcas-pilot-steps.png'':::
-
link:#step-1-create-the-pilot-groupscope-your-pilot-deployment-to-certain-user-groups[Step
1. Create the pilot group—Scope your pilot deployment to certain user
groups] -
link:#step-2-configure-protectionconditional-access-app-control[Step 2.
Configure protection—Conditional Access App Control] -
link:#step-3-try-out-capabilitieswalk-through-tutorials-for-protecting-your-environment[Step
3. Try out capabilities—Walk through tutorials for protecting your
environment]

=== Step 1. Create the pilot group—Scope your pilot deployment to certain user groups

Microsoft Defender for Cloud Apps enables you to scope your deployment.
Scoping allows you to select certain user groups to be monitored for
apps or excluded from monitoring. You can include or exclude user
groups. To scope your pilot deployment, see
link:/cloud-app-security/scoped-deployment[Scoped Deployment].

=== Step 2. Configure protection—Conditional Access App Control

One of the most powerful protections you can configure is Conditional
Access App Control. This protection requires integration with Azure
Active Directory (Azure AD). It allows you to apply Conditional Access
policies, including related policies (like requiring healthy devices),
to cloud apps you’ve sanctioned.

The first step in using Microsoft Defender for Cloud Apps to manage SaaS
apps is to discover these apps and then add them to your Azure AD
tenant. If you need help with discovery, see
link:/cloud-app-security/tutorial-shadow-it[Discover and manage SaaS
apps in your network]. After you’ve discovered apps,
link:/azure/active-directory/manage-apps/add-application-portal[add
these apps to your Azure AD tenant].

You can begin to manage these apps by executing the following tasks:

* First, in Azure AD, create a new conditional access policy and
configure it to ``Use Conditional Access App Control.'' This
configuration helps to redirect the request to Defender for Cloud Apps.
You can create one policy and add all SaaS apps to this policy.
* Next, in Defender for Cloud Apps, create session policies. Create one
policy for each control you want to apply.

For more information, including supported apps and clients, see
link:/cloud-app-security/proxy-intro-aad[Protect apps with Microsoft
Defender for Cloud Apps Conditional Access App Control].

For example policies, see
link:../office-365-security/mcas-saas-access-policies.md[Recommended
Microsoft Defender for Cloud Apps policies for SaaS apps]. These
policies build on a set of
link:../office-365-security/microsoft-365-policies-configurations.md[common
identity and device access policies] that are recommended as a starting
point for all customers.

=== Step 3. Try out capabilities—Walk through tutorials for protecting your environment

The Microsoft Defender for Cloud Apps documentation includes a series of
tutorials to help you discover risk and protect your environment.

Try out Defender for Cloud Apps tutorials:

* link:/cloud-app-security/tutorial-suspicious-activity[Detect
suspicious user activity]
* link:/cloud-app-security/tutorial-ueba[Investigate risky users]
* link:/cloud-app-security/investigate-risky-oauth[Investigate risky
OAuth apps]
* link:/cloud-app-security/tutorial-dlp[Discover and protect sensitive
information]
* link:/cloud-app-security/tutorial-proxy[Protect any app in your
organization in real time]
* link:/cloud-app-security/use-case-proxy-block-session-aad[Block
downloads of sensitive information]
* link:/cloud-app-security/use-case-admin-quarantine[Protect your files
with admin quarantine]
* link:/cloud-app-security/tutorial-step-up-authentication[Require
step-up authentication upon risky action]

For more information on advanced hunting in Microsoft Defender for Cloud
Apps data, see the
https://www.microsoft.com/en-us/videoplayer/embed/RWFISa[video].

=== Next steps

link:eval-defender-investigate-respond.md[Investigate and respond using
Microsoft 365 Defender in a pilot environment]

Return to the overview for link:eval-defender-mcas-overview.md[Evaluate
Microsoft Defender for Cloud Apps]

Return to the overview for link:eval-overview.md[Evaluate and pilot
Microsoft 365 Defender]
