= Enable the evaluation environment for Microsoft Defender for Office 365 in your production environment
:audience: ITPro
:author: MSFTTracyP
:description: Steps to activate Microsoft Defender for Office 365 evaluation, with trial licenses, MX record handling, & auditing of accepted domains and inbound connections.
:f1.keywords: ["NOCSH"]
:manager: dansimp
:ms.author: tracyp
:ms.collection: ["M365-security-compliance", "m365solution-scenario", "m365solution-evalutatemtp", "zerotrust-solution", "highpri"]
:ms.date: 09/01/2021
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: m365d
:ms.topic: how-to
:search.appverid: met150
:search.product: eADQiWindows 10XVcnh

== Enable the evaluation environment

*Applies to:*

* Microsoft 365 Defender

This article is xref:eval-defender-office-365-overview.adoc[Step 2 of 3] in the process of setting up the evaluation environment for Microsoft Defender for Office 365.
For more information about this process, see the xref:eval-defender-office-365-overview.adoc[overview article].

Use the following steps to enable the evaluation for Microsoft Defender for Office 365.

:::image type="content" source="../../media/defender/m365-defender-office-eval-enable-steps.png" alt-text="The steps to enable Microsoft Defender for Office 365 in the Microsoft Defender evaluation environment." lightbox="../../media/defender/m365-defender-office-eval-enable-steps.png":::

* <<step-1-audit-and-verify-the-public-mx-record,Step 1: Audit and verify the public MX record>>
* <<step-2-audit-accepted-domains,Step 2: Audit accepted domains>>
* <<step-3-audit-inbound-connectors,Step 3: Audit inbound connectors>>
* <<step-4-activate-the-evaluation,Step 4: Activate the evaluation>>

=== Step 1: Audit and verify the public MX record

To effectively evaluate Microsoft Defender for Office 365, it's important that inbound external email is relayed through the Exchange Online Protection (EOP) instance associated with your tenant.

. In the M365 Admin Portal at https://admin.microsoft.com, expand _...Show all_ if necessary, expand _Settings_, and then select *Domains*.
Or, to go directly to the _Domains_ page, use https://admin.microsoft.com/Adminportal/Home#/Domains.
. On the _Domains_ page, select your verified email domain by clicking anywhere on the entry other than the check box.
. In the domain details flyout that opens, select the *DNS records* tab.
Make note of the MX record that's generated and assigned to your EOP tenant.
. Access your external (public) DNS zone and check the primary MX record associated with your email domain:
 ** _If your public MX record currently matches the assigned EOP address (for example, contoso-com.mail.protection.outlook.com) then no further routing changes should be required_.
 ** If your public MX record currently resolves to a third-party or on-premises SMTP gateway then additional routing configurations may be required.
 ** If your public MX record currently resolves to on-premises Exchange then you may still be in a hybrid model where some recipient mailbox have not yet been migrated to EXO.

=== Step 2: Audit accepted domains

. In the Exchange admin center (EAC) at https://admin.exchange.microsoft.com, expand _Mail flow_, and then click *Accepted domains*.Or, to go directly to the _Accepted domains_ page, use https://admin.exchange.microsoft.com/#/accepteddomains.
. On the _Accepted domains_ page, make note of the *Domain type* value for your primary email domain.
 ** If the domain type is set to *Authoritative* then it is assumed all recipient mailboxes for your organization currently reside in Exchange Online.
 ** If the domain type is set to *InternalRelay* then you may still be in a hybrid model where some recipient mailboxes still reside on-premises.

=== Step 3: Audit inbound connectors

. In the Exchange admin center (EAC) at https://admin.exchange.microsoft.com, expand _Mail flow_, and then click *Connectors*.
Or, to go directly to the _Connectors_ page, use https://admin.exchange.microsoft.com/#/connectors.
. On the _Connectors_ page, make note of any connectors with the following settings:
 ** The *From* value is *Partner org* that might correlate to a third-party SMTP gateway.
 ** The *From* value is *Your org* that might indicate you're still in a hybrid scenario.

=== Step 4: Activate the evaluation

Use the instructions here to activate your Microsoft Defender for Office 365 evaluation from the Microsoft 365 Defender portal.

For detailed information, see xref:../office-365-security/try-microsoft-defender-for-office-365.adoc[Try Microsoft Defender for Office 365].

. In the Microsoft 365 Defender portal at https://security.microsoft.com expand _Email & collaboration_ > select *Policies & rules* > select *Threat policies* > scroll down to the _Others_ section, and then select *Evaluation mode*.
Or, to go directly to the _Evaluation mode_ page, use https://security.microsoft.com/atpEvaluation.
. On the _Evaluation mode_ page, click *Start evaluation*.
+
:::image type="content" source="../../media/mdo-eval/mdo-eval-activate-eval_05.png" alt-text="The Evaluation mode page and the Start evaluation button to click." lightbox="../../media/mdo-eval/mdo-eval-activate-eval_05.png":::

. In the _Turn on protection_ dialog, select *No, I only want reporting*, and then click *Continue*.
+
:::image type="content" source="../../media/mdo-eval/mdo-eval-activate-eval_06.png" alt-text="The Turn on protection dialog and the No, I only want reporting option to select." lightbox="../../media/mdo-eval/mdo-eval-activate-eval_06.png":::

. In the _Select the users you want to include_ dialog, select *All users*, and then click *Continue*.
+
:::image type="content" source="../../media/mdo-eval/mdo-eval-activate-eval_07.png" alt-text="The Select the users you want to include dialog and the All users option to select." lightbox="../../media/mdo-eval/mdo-eval-activate-eval_07.png":::

. In the _Help us understand your mail flow_ dialog, one of the following options is automatically selected based on our detection of the MX record for your domain:
 ** *I'm only using Microsoft Exchange Online*: The MX records for your domain point to Microsoft 365.
There's nothing left to configure, so click *Finish*.
+
:::image type="content" source="../../media/mdo-eval/mdo-eval-activate-eval_08a.png" alt-text="The Help us understand your mail flow dialog with the I'm only using Microsoft Exchange Online option selected." lightbox="../../media/mdo-eval/mdo-eval-activate-eval_08a.png":::

 ** *I'm using a third-party and/or on-premises service provider*: In the upcoming screens, select the vendor name along with the inbound connector that accepts mail from that solution.
You also decide if you need an Exchange Online mail flow rule (also known as a transport rule) that skips spam filtering for incoming messages from the third-party protection service or device.
When you're finished, click *Finish*.

=== Next steps

Step 3 of 3: Set up the pilot for Microsoft Defender for Office 365

Return to the overview for xref:eval-defender-office-365-overview.adoc[Evaluate Microsoft Defender for Office 365]

Return to the overview for xref:eval-overview.adoc[Evaluate and pilot Microsoft 365 Defender]
