= 
jweston-1

== Step 4. Evaluate Microsoft Defender for Endpoint overview

*Applies to:*

* Microsoft 365 Defender

This article outlines the process to enable and pilot Microsoft Defender
for Endpoint. Before starting this process, be sure you’ve reviewed the
overall process for link:eval-overview.md[evaluating Microsoft 365
Defender], and you’ve link:eval-create-eval-environment.md[created the
Microsoft 365 Defender evaluation environment].

Use the following steps to enable and pilot Microsoft Defender for
Endpoint.

:::image type=``content''
source=``../../media/defender/m365-defender-endpoint-eval-steps.png''
alt-text=``The steps for adding Microsoft Defender for Endpoint to the
Microsoft Defender evaluation environment''
lightbox=``../../media/defender/m365-defender-endpoint-eval-steps.png'':::

The following table describes the steps in the illustration.

[width="100%",cols="50%,50%",options="header",]
|===
|Step |Description
|link:eval-defender-endpoint-architecture.md[Step 1. Review architecture
requirements and key concepts] |Understand the Defender for Endpoint
architecture and the capabilities available to you.

|link:eval-defender-endpoint-enable-eval.md[Step 2. Enable the
evaluation environment] |Follow the steps to set up the evaluation
environment.

|link:eval-defender-endpoint-pilot.md[Step 3. Set up the pilot] |Verify
your pilot group, run simulations, and become familiar with key features
and dashboards.
|===
