= 
dansimp

== Step 6. Investigate and respond using Microsoft 365 Defender in a pilot environment

*Applies to:* - Microsoft 365 Defender

This article outlines the process to create incidents with attack
simulations and tutorials and use Microsoft 365 Defender to investigate
and respond. Before starting this process, be sure you’ve reviewed the
overall process for link:eval-overview.md[evaluating Microsoft 365
Defender] and you have link:eval-create-eval-environment.md[created the
Microsoft 365 Defender evaluation environment].

Use the following steps.

:::image type=``content''
source=``../../media/eval-defender-investigate-respond/eval-defender-eval-investigate-respond-steps.png''
alt-text=``The steps for performing simulated incident response in the
Microsoft 365 Defender evaluation environment''
lightbox=``../../media/eval-defender-investigate-respond/eval-defender-eval-investigate-respond-steps.png'':::

The following table describes the steps in the illustration.

[width="100%",cols="50%,50%",options="header",]
|===
|Step |Description
|1. link:eval-defender-investigate-respond-simulate-attack.md[Simulate
attacks] |Simulate attacks on your evaluation environment and use the
Microsoft 365 Defender portal to perform incident response.

|2. link:eval-defender-investigate-respond-additional.md[Try incident
response capabilities] |Try additional incident response features and
capabilities in Microsoft 365 Defender.

| |
|===

=== Navigation you may need

link:eval-create-eval-environment.md[Create the Microsoft 365 Defender
Evaluation Environment]
