= 
lovina-saldanha

== Step 3. Enable and pilot Microsoft Defender for Office 365

*Applies to:* - Microsoft 365 Defender

This article outlines the process to enable and pilot Microsoft Defender
for Office 365. Before starting this process, be sure you’ve reviewed
the overall process for link:eval-overview.md[evaluating Microsoft 365
Defender], and you’ve link:eval-create-eval-environment.md[created the
Microsoft 365 Defender evaluation environment].

Use the following steps to enable and pilot Microsoft Defender for
Office 365.

:::image type=``content''
source=``../../media/defender/m365-defender-office-eval-steps.png''
alt-text=``The steps for adding Microsoft Defender for Office to the
Microsoft Defender evaluation environment.''
lightbox=``../../media/defender/m365-defender-office-eval-steps.png'':::

The following table describes the steps in the illustration.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Step number |Link |Description
|1 |link:eval-defender-office-365-architecture.md[Review architecture
requirements and key concepts] |Understand the Defender for Office
architecture and be sure your Exchange Online environment meets the
architecture prerequisites.

|2 |link:eval-defender-office-365-enable-eval.md[Enable the evaluation
environment] |Follow the steps to set up the evaluation environment.

|3 |link:eval-defender-office-365-pilot.md[Set up the pilot] |Create
pilot groups, configure protection, and become familiar with key
features and dashboards.
|===
