= 
dansimp
:keywords: incidents, alerts, investigate, correlation, attack,
machines, devices, users, identities, identity, mailbox, email, 365,
microsoft, m365

== Step 3. Perform a post-incident review of your first incident

{empty}[!INCLUDE link:../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* - Microsoft 365 Defender

National Institute of Standards and Technology (NIST) recommends that
once all steps have been taken to recover from the attack, organizations
must review the incident to learn from it and improve security posture
or processes. Assessing the different aspects of incident-handling
becomes important in preparing for the next incident.

Microsoft 365 Defender can help in performing post-incident activities
by providing an organization with alerts that align with
https://attack.mitre.org/[MITRE ATT&CK Framework]. All Microsoft
Defender solutions label attacks in accordance with an ATT&CK tactic or
technique.

By mapping alerts to this industry framework, you can:

* Conduct an analysis of gaps in security coverage.
* Determine adversary and campaign attribution.
* Perform trend analysis.
* Identify skill gaps in attack method awareness.
* Create a Power Automate Playbook for faster remediation.

Post-incident review activity can also result in fine-tuning your
security configuration and security team’s processes to streamline your
organization’s response capabilities.

=== Next step

See these additional investigation paths:

* link:first-incident-path-phishing.md[Phishing email]
* link:first-incident-path-identity.md[Identity-based attack]

=== See also

* link:incidents-overview.md[Incidents overview]
* link:investigate-incidents.md[Investigate incidents]
* link:manage-incidents.md[Manage incidents]
