= 
siosulli

== Import roles to Microsoft 365 Defender RBAC

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:*

* https://go.microsoft.com/fwlink/?linkid=2154037[Microsoft Defender for
Endpoint Plan 2]
* https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365
Defender]
* https://go.microsoft.com/fwlink/?LinkID=2198108[Microsoft Defender for
Identity]
* https://go.microsoft.com/fwlink/?LinkID=2158212[Microsoft Defender for
Office 365 P2]

{empty}[!includelink:../../includes/prerelease.md[Prerelease
information]]

=== Import roles to Microsoft 365 Defender RBAC from individual RBAC models

You can import existing roles that are maintained as part of individual
supported products in Microsoft 365 Defender (for example, Microsoft
Defender for Endpoint) to the Microsoft 365 Defender RBAC model.

Importing roles will migrate and maintain the roles with full parity in
relation to their permissions and user assignments in the Microsoft 365
Defender RBAC model.

____
[!NOTE] Once roles are migrated, you can modify the imported roles and
change the level of permissions as needed.
____

The following steps guide you on how to import roles into Microsoft 365
Defender RBAC:

____
[!IMPORTANT] You must be a Global Administrator or Security
Administrator in Azure Active Directory, or have all the *Authorization*
permissions assigned in Microsoft 365 Defender RBAC to perform this
task. For more information on permissions, see
link:../defender/manage-rbac.md#permissions-pre-requisites[Permission
pre-requisites].
____

[arabic]
. Sign in to the https://security.microsoft.com[Microsoft 365 Defender
portal].
. In the navigation pane, select *Permissions*.
. Select *Roles* under Microsoft 365 Defender to get to the Permissions
and roles page.
. Select *Import role*.
. Select the products you want to import roles from.
+
:::image type=``content''
source=``../../media/defender/m365-defender-import-workloads.png''
alt-text=``Screenshot of the import workloads page''
lightbox=``../../media/defender/m365-defender-import-workloads.png'':::
. Select *Next* to choose the roles to import. You can choose all roles
or select specific roles from the list. You can always repeat the import
action and import other roles at a later date.
. Review the roles you want to import and select *Submit*.
. A confirmation message appears and at this point you select *Done*.

Now that you have imported your roles you will be able to
link:edit-delete-rbac-roles.md[View and edit roles] and activate the
workloads.

For the Microsoft 365 Defender security portal to start enforcing the
permissions and assignments configured in your new or imported roles,
you’ll need to activate the new Microsoft 365 Defender RBAC model. For
more information, see link:activate-defender-rbac.md[Activate the
workloads].

Imported roles appear in the *Permissions and roles* list together with
any custom roles you might have created. All imported roles will be
marked as *Imported* in the description. Once you edit an imported role
it will no longer be marked as *Imported*.

____
[!NOTE] You can import roles as frequently as required. After you edit
an imported role, the changes will not affect the original role where it
was imported from. This means you have the option to delete an imported
role and re-import the original role, if required. If you import the
same role twice you will create a duplicate role.
____

=== Next steps

* link:activate-defender-rbac.md[Activate Microsoft 365 Defender RBAC]
* link:edit-delete-rbac-roles.md[Edit or delete roles]
