= 
dansimp
:keywords: incidents, alerts, investigate, correlation, attack, devices,
users, identities, identity, mailbox, email, 365, microsoft, Microsoft
365, incident response, cyber-attack, secops, security operations, soc

== Step 4. Define Microsoft 365 Defender roles, responsibilities, and oversight

{empty}[!INCLUDE link:../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* - Microsoft 365 Defender

Your organization must establish ownership and accountability of the
Microsoft 365 Defender licenses, configurations, and administration as
initial tasks before any operational roles can be defined. Typically,
the ownership of the licenses, subscription costs, and administration of
Microsoft 365 and Enterprise Security + Mobility (EMS) services (which
may include Microsoft 365 Defender) fall outside the Security Operations
Center (SOC) teams. SOC teams should work with those individuals to
ensure proper oversight of Microsoft 365 Defender.

Many modern SOCs assign its team members to categories based on their
skillsets and functions. For example:

* A threat intelligence team assigned to tasks related to lifecycle
management of threat and analytics functions.
* A monitoring team comprised of SOC analysts responsible for
maintaining logs, alerts, events, and monitoring functions.
* An engineering & operations team assigned to engineer and optimize
security devices.

SOC team roles and responsibilities for Microsoft 365 Defender would
naturally integrate into these teams.

The following table breaks out each SOC team’s roles and
responsibilities and how their roles integrate with Microsoft 365
Defender.

[width="100%",cols="<37%,<27%,<36%",options="header",]
|===
|SOC team |Roles and responsibilities |Microsoft 365 Defender tasks
|SOC Oversight | |

|Threat Intelligence & Analytics | |

|Monitoring | |Uses:

|Engineering & SecOps | |

|Computer Security Incident Response Team (CSIRT) | |Collaborate and
maintain Microsoft 365 Defender incident response playbooks

| | |
|===

=== Next step

link:integrate-microsoft-365-defender-secops-use-cases.md[Step 5.
Develop and test use cases]
