= 
dansimp
:keywords: incidents, alerts, investigate, correlation, attack, devices,
users, identities, identity, mailbox, email, 365, microsoft, m365,
incident response, cyber-attack, secops, security operations, soc

== Integrating Microsoft 365 Defender into your security operations

{empty}[!INCLUDE link:../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* - Microsoft 365 Defender

A modern Security Operations Center (SOC) is an intelligence-driven,
adaptive organization that embraces threat defense strategy of moving
security processes earlier in the deployment process so that security is
built in. This means that the traditional assignment of isolated
technologies and processes to single security analysts no longer
supports the vast increase in data coming in from multiple sources.
Security analysts and engineers are being asked to take a more holistic
approach and to use shared insights across different platforms and
disciplines to take effective action.

For this reason, the deployment and implementation of the Microsoft 365
Defender platform will need careful planning with the SOC team to
optimize the day-to-day operations and lifecycle management of the
Microsoft 365 Defender service itself. This content explores several
concepts on how to operationalize and integrate Microsoft 365 Defender
with either new or existing people, processes, and technologies that
form the basis for modern security operations.

If you are not already familiar with Microsoft 365 Defender, see these
articles:

* link:get-started.md[Get started with Microsoft 365 Defender]
* link:m365d-enable.md[Turn on Microsoft 365 Defender]

If your organization has already implemented some aspects of Microsoft
365 Defender, these articles can either affirm or help improve your
existing architecture and processes.

____
[!Note] As a Microsoft partner, Protiviti contributed to and provided
material feedback to this article.
____

=== Target audience

This content is designed for the following:

* DevOps and Security Operations (SecOps) teams
* Security engineering teams
* IT teams
* CISOs and CTOs
* Red, Blue, and Purple Teams
* CSIRT & forensic teams
* Microsoft 365 administrators

=== Next steps

Use these steps to integrate Microsoft 365 Defender into your SOC.

* link:integrate-microsoft-365-defender-secops-plan.md[Step 1. Plan for
Microsoft 365 Defender operations readiness]
* link:integrate-microsoft-365-defender-secops-readiness.md[Step 2.
Perform a SOC integration readiness assessment using the Zero Trust
Framework]
* link:integrate-microsoft-365-defender-secops-services.md[Step 3. Plan
for Microsoft 365 Defender integration with your SOC catalog of
services]
* link:integrate-microsoft-365-defender-secops-roles.md[Step 4. Define
Microsoft 365 Defender roles&#44; responsibilities&#44; and oversight]
* link:integrate-microsoft-365-defender-secops-use-cases.md[Step 5.
Develop and test use cases]
* link:integrate-microsoft-365-defender-secops-tasks.md[Step 6. Identify
SOC maintenance tasks]
