= 
dansimp
:keywords: automated, investigation, alert, trigger, action,
remediation, self-healing

== Automated investigation and response in Microsoft 365 Defender

{empty}[!INCLUDE link:../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* - Microsoft 365 Defender

If your organization is using link:microsoft-365-defender.md[Microsoft
365 Defender], your security operations team receives an alert within
the Microsoft 365 Defender portal whenever a malicious or suspicious
activity or artifact is detected. Given the seemingly never-ending flow
of threats that can come in, security teams often face the challenge of
addressing the high volume of alerts. Fortunately, Microsoft 365
Defender includes automated investigation and response (AIR)
capabilities that can help your security operations team address threats
more efficiently and effectively.

This article provides an overview of AIR and includes links to next
steps and additional resources.

=== How automated investigation and self-healing works

As security alerts are triggered, it’s up to your security operations
team to look into those alerts and take steps to protect your
organization. Prioritizing and investigating alerts can be very time
consuming, especially when new alerts keep coming in while an
investigation is going on. Security operations teams can feel
overwhelmed by the sheer volume of threats they must monitor and protect
against. Automated investigation and response capabilities, with
self-healing, in Microsoft 365 Defender can help.

Watch the following video to see how self-healing works:

____
{empty}[!VIDEO https://www.microsoft.com/videoplayer/embed/RE4BzwB]
____

In Microsoft 365 Defender, automated investigation and response with
self-healing capabilities works across your devices, email & content,
and identities.

____
[!TIP] This article describes how automated investigation and response
works. To configure these capabilities, see
link:m365d-configure-auto-investigation-response.md[Configure automated
investigation and response capabilities in Microsoft 365 Defender].
____

=== Your own virtual analyst

Imagine having a virtual analyst in your Tier 1 or Tier 2 security
operations team. The virtual analyst mimics the ideal steps that
security operations would take to investigate and remediate threats. The
virtual analyst could work 24x7, with unlimited capacity, and take on a
significant load of investigations and threat remediation. Such a
virtual analyst could significantly reduce the time to respond, freeing
up your security operations team for other important threats or
strategic projects. If this scenario sounds like science fiction, it’s
not! Such a virtual analyst is part of your Microsoft 365 Defender
suite, and its name is _automated investigation and response_.

Automated investigation and response capabilities enable your security
operations team to dramatically increase your organization’s capacity to
deal with security alerts and incidents. With automated investigation
and response, you can reduce the cost of dealing with investigation and
response activities and get the most out of your threat protection
suite. Automated investigation and response capabilities help your
security operations team by:

[arabic]
. Determining whether a threat requires action.
. Taking (or recommending) any necessary remediation actions.
. Determining whether and what other investigations should occur.
. Repeating the process as necessary for other alerts.

=== The automated investigation process

An alert creates an incident, which can start an automated
investigation. The automated investigation results in a verdict for each
piece of evidence. Verdicts can be: - _Malicious_ - _Suspicious_ - _No
threats found_

Remediation actions for malicious or suspicious entities are identified.
Examples of remediation actions include:

* Sending a file to quarantine
* Stopping a process
* Isolating a device
* Blocking a URL
* Other actions

For more information, see See
link:m365d-remediation-actions.md[Remediation actions in Microsoft 365
Defender].

Depending on link:m365d-configure-auto-investigation-response.md[how
automated investigation and response capabilities are configured] for
your organization, remediation actions are taken automatically or only
upon approval by your security operations team. All actions, whether
pending or completed, are listed in the
link:m365d-action-center.md[Action center].

While an investigation is running, any other related alerts that arise
are added to the investigation until it completes. If an affected entity
is seen elsewhere, the automated investigation expands its scope to
include that entity, and the investigation process repeats.

In Microsoft 365 Defender, each automated investigation correlates
signals across Microsoft Defender for Identity, Microsoft Defender for
Endpoint, and Microsoft Defender for Office 365, as summarized in the
following table:

[width="100%",cols="<50%,<50%",options="header",]
|===
|Entities |Threat protection services
|Devices (also referred to as endpoints or machines)
|link:../defender-endpoint/automated-investigations.md[Defender for
Endpoint]

|On-premises Active Directory users, entity behavior, and activities
|link:/azure-advanced-threat-protection/what-is-atp[Defender for
Identity]

|Email content (email messages that can contain files and URLs)
|link:../office-365-security/defender-for-office-365.md[Defender for
Office 365]
|===

____
[!NOTE] Not every alert triggers an automated investigation, and not
every investigation results in automated remediation actions. It depends
on how automated investigation and response is configured for your
organization. See
link:m365d-configure-auto-investigation-response.md[Configure automated
investigation and response capabilities].
____

=== Viewing a list of investigations

To view investigations, go to the *Incidents* page. Select an incident,
and then select the *Investigations* tab. To learn more, see
link:m365d-autoir-results.md[Details and results of an automated
investigation].

=== Automated investigation & response card

The new Automated investigation & response card is available in the
Microsoft 365 Defender portal (https://security.microsoft.com). This new
card visibility to the total number of available remediation actions.
The card also gives an overview of all the alerts and required approval
time for each alert.

:::image type=``content''
source=``../../media/automated-investigation-response-card.png''
alt-text=``Screenshot that shows the automated investigation & response
card.'':::

Using the Automated investigation & response card, your security
operations team can quickly navigate to the Action center by selecting
the *Approve in Action Center* link, and then taking appropriate
actions. The card enables your security operations team to more
effectively manage actions that are pending approval.

=== Training for security analysts

Use this learning module from Microsoft Learn to understand how
Microsoft 365 Defender uses automated self-healing for incident
investigation and response.

[width="100%",cols="50%,50%",options="header",]
|===
|Training: |Automate self-healing with Microsoft 365 Defender
|image:../../media/m365d-autoir/m365-defender-auto-self-healing.svg[Automate
self-healing with Microsoft 365 Defender training icon.] |Microsoft 365
Defender uses AI to automate remediation for incidents, helping your
security operations team address threats more efficiently and
effectively.
|===

____
{empty}[!div class=``nextstepaction'']
link:/training/modules/defender-self-healing/[Start >]
____

=== Next steps

* link:m365d-configure-auto-investigation-response.md#prerequisites-for-automated-investigation-and-response-in-microsoft-365-defender[See
the prerequisites for automated investigation and response]
* link:m365d-configure-auto-investigation-response.md[Configure
automated investigation and response for your organization]
* link:m365d-action-center.md[Learn more about the Action center]
