= Configure automated investigation and response capabilities in Microsoft 365 Defender
:audience: ITPro
:author: dansimp
:description: Configure automated investigation and response with self-healing in Microsoft 365 Defender
:f1.keywords: CSH
:manager: dansimp
:ms.author: dansimp
:ms.collection: ["M365-security-compliance", "m365initiative-m365-defender"]
:ms.custom: ["autoir", "admindeeplinkDEFENDER"]
:ms.localizationpriority: medium
:ms.reviewer: evaldm, isco
:ms.service: microsoft-365-security
:ms.subservice: m365d
:ms.topic: how-to
:search.appverid: MET150

== Configure automated investigation and response capabilities in Microsoft 365 Defender

[!INCLUDE xref:../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

Microsoft 365 Defender includes powerful xref:m365d-autoir.adoc[automated investigation and response capabilities] that can save your security operations team much time and effort.
With link:m365d-autoir.md#how-automated-investigation-and-self-healing-works[self-healing], these capabilities mimic the steps a security analyst would take to investigate and respond to threats, only faster, and with more ability to scale.

This article describes how to configure automated investigation and response in https://go.microsoft.com/fwlink/p/?linkid=2077139[Microsoft 365 Defender] with these steps:

. <<prerequisites-for-automated-investigation-and-response-in-microsoft-365-defender,Review the prerequisites>>.
. <<review-or-change-the-automation-level-for-device-groups,Review or change the automation level for device groups>>.
. <<review-your-security-and-alert-policies-in-office-365,Review your security and alert policies in Office 365>>.
. <<make-sure-microsoft-365-defender-is-turned-on,Make sure Microsoft 365 Defender is turned on>>.

Then, after you're all set up, you can xref:m365d-autoir-actions.adoc[view and manage remediation actions in the Action center].

=== Prerequisites for automated investigation and response in Microsoft 365 Defender

{blank} +

'''

|===
| Requirement | Details

| Subscription requirements
| One of these subscriptions: <ul><li>Microsoft 365 E5</li><li>Microsoft 365 A5</li><li>Microsoft 365 E3 with the Microsoft 365 E5 Security add-on</li><li>Microsoft 365 A3 with the Microsoft 365 A5 Security add-on</li><li>Office 365 E5 plus Enterprise Mobility + Security E5 plus Windows E5</li></ul> <p> See link:./prerequisites.md#licensing-requirements[Microsoft 365 Defender licensing requirements].

| Network requirements
| <ul><li>link:/azure-advanced-threat-protection/what-is-atp[Microsoft Defender for Identity] enabled</li><li>link:/cloud-app-security/what-is-cloud-app-security[Microsoft Defender for Cloud Apps] configured</li><li>link:/cloud-app-security/mdi-integration[Microsoft Defender for Identity integration]</li></ul>

| Windows device requirements
| <ul><li>Windows 11</li><li>Windows 10, version 1709 or later installed (See link:/windows/release-information/[Windows release information])</li><li>The following threat protection services configured:<ul><li>xref:../defender-endpoint/configure-endpoints.adoc[Microsoft Defender for Endpoint]</li><li>link:/windows/security/threat-protection/windows-defender-antivirus/configure-windows-defender-antivirus-features[Microsoft Defender Antivirus]</li></ul></li></ul>

| Protection for email content and Office files
| link:/microsoft-365/security/office-365-security/defender-for-office-365#configure-atp-policies[Microsoft Defender for Office 365] configured

| Permissions
| To configure automated investigation and response capabilities, you must have the Global Administrator or Security Administrator role assigned in either Azure Active Directory (https://portal.azure.com) or in the Microsoft 365 admin center (https://admin.microsoft.com).
<p> To get the permissions needed to work with automated investigation and response capabilities, such as reviewing, approving, or rejecting pending actions, see link:m365d-action-center.md#required-permissions-for-action-center-tasks[Required permissions for Action center tasks].

|
|
|===

=== Review or change the automation level for device groups

Whether automated investigations run, and whether remediation actions are taken automatically or only upon approval for your devices depend on certain settings, such as your organization's device group policies.
Review the configured automation level for your device group policies.

. Go to the Microsoft 365 Defender portal (https://security.microsoft.com) and sign in.
. Go to *Settings* > *Endpoints* > *Device groups* under *Permissions*.
. Review your device group policies.
In particular, look at the *Automation level* column.
We recommend using *Full - remediate threats automatically*.
You might need to create or edit your device groups to get the level of automation you want.
To get help with this task, see the following articles:
 ** link:/windows/security/threat-protection/microsoft-defender-atp/automated-investigations#how-threats-are-remediated[How threats are remediated]
 ** link:/windows/security/threat-protection/microsoft-defender-atp/machine-groups[Create and manage device groups]

=== Review your security and alert policies in Office 365

Microsoft provides built-in xref:../../compliance/alert-policies.adoc[alert policies] that help identify certain risks.
These risks include Exchange admin permissions abuse, malware activity, potential external and internal threats, and information governance risks.
Some alerts can trigger xref:../office-365-security/office-365-air.adoc[automated investigation and response in Office 365].
Make sure your xref:../office-365-security/defender-for-office-365.adoc[Defender for Office 365] features are configured correctly.

Although certain alerts and security policies can trigger automated investigations, _no remediation actions are taken automatically for email and content_.
Instead, all remediation actions for email and email content await approval by your security operations team in the xref:m365d-action-center.adoc[Action center].

Security settings in Office 365 help protect email and content.
To view or change these settings, follow the guidance in xref:../office-365-security/protect-against-threats.adoc[Protect against threats].

. In the https://go.microsoft.com/fwlink/p/?linkid=2077139[Microsoft 365 Defender portal], go to *Policies & Rules* > *Threat policies*.
. Make sure all of the following policies are configured.
To get help and recommendations, see link:/microsoft-365/security/office-365-security/protect-against-threats[Protect against threats].
 ** link:../office-365-security/protect-against-threats.md#part-1---anti-malware-protection-in-eop[Anti-malware]
 ** link:../office-365-security/protect-against-threats.md#part-2---anti-phishing-protection-in-eop-and-defender-for-office-365[Anti-phishing]
 ** link:../office-365-security/protect-against-threats.md#safe-attachments-policies-in-microsoft-defender-for-office-365[Safe Attachments]
 ** link:../office-365-security/protect-against-threats.md#safe-links-policies-in-microsoft-defender-for-office-365[Safe Links]
 ** link:../office-365-security/protect-against-threats.md#part-3---anti-spam-protection-in-eop[Anti-spam]
. Make sure xref:../office-365-security/mdo-for-spo-odb-and-teams.adoc[Safe Attachments for SharePoint, OneDrive, and Microsoft Teams] is turned on.
. Make sure xref:../office-365-security/zero-hour-auto-purge.adoc[Zero-hour auto purge (ZAP) in Exchange Online] is in effect.
. (This step is optional.) Review your xref:../../compliance/alert-policies.adoc[Office 365 alert policies] in the Microsoft Purview compliance portal (https://compliance.microsoft.com/compliancepolicies).
Several default alert policies are in the Threat management category.
Some of these alerts can trigger automated investigation and response.
To learn more, see link:../../compliance/alert-policies.md#default-alert-policies[Default alert policies].

=== Make sure Microsoft 365 Defender is turned on

:::image type="content" source="../../media/mtp-enable/mtp-on.png" alt-text="The left navigation pane in the Microsoft 365 Defender portal when Microsoft 365 Defender is turned on" lightbox="../../media/mtp-enable/mtp-on.png":::

. Sign in to the https://go.microsoft.com/fwlink/p/?linkid=2077139[Microsoft 365 Defender portal]
. In the navigation pane, look for *Incidents & Alerts*, *Hunting*, and *Action center* as shown in the preceding image.
 ** If you see *Incidents & Alerts*, *Hunting*, and *Action center*, Microsoft 365 Defender is turned on.
See the <<review-or-change-the-automation-level-for-device-groups,Review or change the automation level for device groups>> section of this article.
 ** If you do _not_ see *Incidents*, *Action center*, or *Hunting*, Microsoft 365 Defender might not be turned on.
In this case, xref:m365d-action-center.adoc[visit the Action center].

____
[!TIP] Need help?
See xref:m365d-enable.adoc[Turn on Microsoft 365 Defender].
____

=== Next steps

* xref:m365d-remediation-actions.adoc[Remediation actions in Microsoft 365 Defender]
* xref:m365d-action-center.adoc[Visit the Action center]
