= Frequently asked questions when turning on Microsoft 365 Defender
:audience: ITPro
:author: dansimp
:description: Get answers to the most commonly asked questions about licensing, permissions, initial settings, and other products and services related to enabling Microsoft 365 Defender
:experimental:
:f1.keywords: ["NOCSH"]
:keywords: frequently asked questions, FAQ, GCC, get started, enable Microsoft 365 Defender, Microsoft 365 Defender, M365, security, data location, required permissions, license eligibility, settings page
:manager: dansimp
:ms.author: dansimp
:ms.collection: M365-security-compliance
:ms.custom: admindeeplinkDEFENDER
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: m365d
:ms.topic: conceptual
:search.appverid: ["MOE150", "MET150"]
:search.product: eADQiWindows 10XVcnh

== Frequently asked questions when turning on Microsoft 365 Defender

[!INCLUDE xref:../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* Microsoft 365 Defender

Read responses to the most commonly asked questions about turning on xref:microsoft-365-defender.adoc[Microsoft 365 Defender], including required licenses and permissions, deploying support services, and initial settings.

For instructions on how to turn on the service, xref:m365d-enable.adoc[read Turn on Microsoft 365 Defender].

=== I don't have a Microsoft 365 E5 license. Can I still use Microsoft 365 Defender?

Customers with the following non-E5 licenses can use Microsoft 365 Defender:

* Microsoft Defender for Endpoint
* Microsoft Defender for Identity
* Microsoft Defender for Cloud Apps
* Defender for Office 365 (Plan 2)

For a full list of supported licenses, link:prerequisites.md#licensing-requirements[read the licensing requirements].

=== Do I need to install or deploy anything to start using Microsoft 365 Defender?

No, Microsoft 365 Defender consolidates data from Microsoft 365 security services that you have already deployed.
Once you turn it on, incident, automation, and hunting experiences will start working within the scope of the deployed products.
If none of these products are properly deployed, Microsoft 365 Defender will not display any data and is unable to take any action.

To optimize your Microsoft 365 Defender experiences, we recommend deploying _all_ supported xref:deploy-supported-services.adoc[Microsoft 365 security products and services].

=== Where does Microsoft 365 Defender process and store my data?

Microsoft 365 Defender automatically selects an optimal location for the data center where consolidated data is processed and stored.
If you have Microsoft Defender for Endpoint, it selects the same location used by Defender for Endpoint.

____
[!NOTE] Microsoft Defender for Endpoint automatically provisions in European Union (EU) data centers when turned on through Microsoft Defender for Cloud.
Microsoft 365 Defender will automatically provision in the same EU data center for customers who have provisioned Microsoft Defender for Endpoint in this manner.
____

The data center location is shown before and after the service is provisioned in the settings page for Microsoft 365 Defender (menu:Settings[Microsoft 365 Defender]).
If you prefer to use another data center location, select *Need help?* in the Microsoft 365 Defender portal to contact Microsoft support.

=== Where can I access Microsoft 365 Defender?

Microsoft 365 Defender is available at: https://go.microsoft.com/fwlink/p/?linkid=2077139[https://security.microsoft.com].

=== What permissions do I need to access Microsoft 365 Defender?

Accounts assigned the following Azure Active Directory (Azure AD) roles can access Microsoft 365 Defender functionality and data:

* Global administrator
* Security administrator
* Security Operator
* Global Reader
* Security Reader
* Compliance Administrator
* Compliance Data Administrator
* Application Administrator
* Cloud Application Administrator

____
[!NOTE] Role-based access control settings in Microsoft Defender for Endpoint influence access to data.
For more information, read about xref:m365d-permissions.adoc[managing access to Microsoft 365 Defender].
____

=== What time zone does Microsoft 365 Defender default to?

By default, Microsoft 365 Defender displays time information in the UTC time zone.
You can change this setting to use your local time zone.
xref:m365d-time-zone.adoc[Learn about setting the time zone]

=== How can I learn about new Microsoft 365 Defender feature and UI updates?

Microsoft regularly provides information through the various channels, including:

* The xref:../../admin/manage/message-center.adoc[message center] in Microsoft 365 admin center
* Blogposts in the https://techcommunity.microsoft.com/t5/security-privacy-and-compliance/bg-p/securityprivacycompliance[Microsoft 365 security & compliance tech community]

Get the latest publicly available experiences by turning on xref:preview.adoc[preview features].

=== Related topics

* xref:microsoft-365-defender.adoc[Microsoft 365 Defender overview]
* xref:m365d-enable.adoc[Turn on Microsoft 365 Defender].
* xref:prerequisites.adoc[Licensing requirements and other prerequisites]
* xref:deploy-supported-services.adoc[Deploy supported services]
* xref:preview.adoc[Turn on preview features]
