= Microsoft 365 Defender portal
:adobe-target: true
:audience: ITPro
:author: mjcaparas
:description: The Microsoft 365 Defender portal combines protection, detection, investigation, and response to email, collaboration, identity, device, and app threats, in a central place.
:f1.keywords: ["NOCSH"]
:keywords: introduction to MMicrosoft 365 Defender, cyber security, advanced persistent threat, enterprise security, devices, device, identity, users, data, applications, incidents, automated investigation and remediation, advanced hunting
:manager: dansimp
:ms.author: macapara
:ms.collection: ["M365-security-compliance", "m365initiative-m365-defender"]
:ms.custom: ["admindeeplinkDEFENDER", "intro-overview"]
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: m365d
:ms.topic: conceptual
:search.appverid: met150
:search.product: eADQiWindows 10XVcnh

== Microsoft 365 Defender portal

The https://sip.security.microsoft.com/homepage[Microsoft 365 Defender portal] combines protection, detection, investigation, and response to email, collaboration, identity, device, and cloud app threats, in a central place.
The Microsoft 365 Defender portal emphasizes quick access to information, simpler layouts, and bringing related information together for easier use.
It includes:

* *link:/microsoft-365/security/office-365-security/defender-for-office-365[Microsoft Defender for Office 365]* Microsoft Defender for Office 365 helps organizations secure their enterprise with a set of prevention, detection, investigation and hunting features to protect email, and Office 365 resources.
* *link:/microsoft-365/security/defender-endpoint/microsoft-defender-advanced-threat-protection[Microsoft Defender for Endpoint]* delivers preventative protection, post-breach detection, automated investigation, and response for devices in your organization.
* *link:/defender-for-identity/what-is[Microsoft Defender for Identity]* is a cloud-based security solution that leverages your on-premises Active Directory signals to identify, detect, and investigate advanced threats, compromised identities, and malicious insider actions directed at your organization.
* *link:/cloud-app-security/[Microsoft Defender for Cloud Apps]* is a comprehensive cross-SaaS and PaaS solution bringing deep visibility, strong data controls, and enhanced threat protection to your cloud apps.

Watch this short video to learn about the Microsoft 365 Defender portal.

____
[!VIDEO https://www.microsoft.com/en-us/videoplayer/embed/RWBKau]
____

=== What to expect

The Microsoft 365 Defender portal helps security teams investigate and respond to attacks by bringing in signals from different workloads into a set of unified experiences for:

* Incidents & alerts
* Hunting
* Actions & submissions
* Threat analytics
* Secure score
* Learning hub
* Trials

Microsoft 365 Defender emphasizes _unity, clarity, and common goals_.

____
[!NOTE] The Microsoft 365 Defender portal is accessible without any need for customers to take migration steps or purchase a new license.
For example, this new portal is accessible to administrators with an E3 subscription, just as it is to those with Microsoft Defender for Office 365 Plan 1 and Plan 2;
however, Exchange Online Protection, or Defender for Office 365 Plan 1 customers see only the security features their subscription license supports.
The goal of the portal is to centralize security.
____

=== Incident and alert investigations

Centralizing security information creates a single place for investigating security incidents across Microsoft 365.
A primary example is *Incidents* under *Incidents & alerts*.

:::image type="content" source="../../media/converged-incidents-2.png" alt-text="The Incidents page in the Microsoft 365 Defender portal" lightbox="../../media/converged-incidents-2.png":::

Selecting an incident name displays a page that demonstrates the value of centralizing security information as you'll have better insights into the full extend of a threat, from email, to identity, to endpoints.

:::image type="content" source="../../media/converged-incident-info-3.png" alt-text="The Summary page for an incident in the Microsoft 365 Defender portal" lightbox="../../media/converged-incident-info-3.png":::

Take the time to review the incidents in your environment, drill down into each alert, and practice building an understanding of how to access the information and determine next steps in your analysis.

For more information, see xref:incidents-overview.adoc[incidents in Microsoft 365 Defender].

=== Hunting

You can build custom detection rules and hunt for specific threats in your environment.
*Hunting* uses a query-based threat hunting tool that lets you proactively inspect events in your organization to locate threat indicators and entities.
These rules run automatically to check for, and then respond to, suspected breach activity, misconfigured machines, and other findings.

For more information, see xref:advanced-hunting-overview.adoc[Proactively hunt for threats with advanced hunting in Microsoft 365 Defender].

=== Improved processes

Common controls and content either appear in the same place, or are condensed into one feed of data making it easier to find.
For example, unified settings.

==== Unified settings

:::image type="content" source="../../media/converged-add-role-9.png" alt-text="The Settings page in the Microsoft 365 Defender portal" lightbox="../../media/converged-add-role-9.png":::

==== Permissions & roles

:::image type="content" source="../../media/converged-roles-5.png" alt-text="The Endpoints roles & groups displayed on the Permissions & roles page" lightbox="../../media/converged-roles-5.png":::

Access to Microsoft 365 Defender is configured with Azure AD global roles or by using custom roles.

* Learn more about how to xref:m365d-permissions.adoc[manage access to Microsoft 365 Defender]
* Learn more about how to xref:custom-roles.adoc[create custom roles] in Microsoft 365 Defender

==== Integrated reports

Reports are also unified in Microsoft 365 Defender.
Admins can start with a general security report, and branch into specific reports about endpoints, email & collaboration.
The links here are dynamically generated based upon workload configuration.

==== Quickly view your Microsoft 365 environment

The *Home* page shows many of the common cards that security teams need.
The composition of cards and data is dependent on the user role.
Because Microsoft 365 Defender portal uses role-based access control, different roles will see cards that are more meaningful to their day to day jobs.

This at-a-glance information helps you keep up with the latest activities in your organization.
Microsoft 365 Defender brings together signals from different sources to present a holistic view of your Microsoft 365 environment.

You can add and remove different cards depending on your needs.

==== Search across entities (Preview)

____
[!IMPORTANT] Some information relates to prereleased product which may be substantially modified before it's commercially released.
Microsoft makes no warranties, express or implied, with respect to the information provided here.
The search bar is located at the top of the page.
As you type, suggestions are provided so that it's easier to find entities.
The enhanced search results page centralizes the results from all entities.
____

You can search across the following entities in Defender for Endpoint and Defender for Identity:

* *Devices* - supported for both Defender for Endpoint and Defender for Identity.
Supports use of search operators.
* *Users* - supported for Defender for Endpoint, Defender for Identity, and Defender for Cloud Apps.
* *Files, IPs, and URLs* - same capabilities as in Defender for Endpoint.
+
____
[!NOTE] IP and URL searches are exact match and don't appear in the search results page -- they lead directly to the entity page.
____

* *MDVM* -  same capabilities as in Defender for Endpoint (vulnerabilities, software, and recommendations).

=== Threat analytics

Track and respond to emerging threats with the following Microsoft 365 Defender threat analytics: Threat analytics is the Microsoft 365 Defender threat intelligence solution from expert Microsoft security researchers.
It's designed to assist security teams to be as efficient as possible while facing emerging threats, such as:

* Active threat actors and their campaigns
* Popular and new attack techniques
* Critical vulnerabilities
* Common attack surfaces
* Prevalent malware

=== Learning Hub

https://go.microsoft.com/fwlink/p/?linkid=2077139[Microsoft 365 Defender portal] includes a learning hub that provides guidance from resources such as the Microsoft security blog, the Microsoft security community on YouTube, and the official documentation.

____
[!NOTE] There are helpful *filters* along the top of Microsoft 365 Defender learning hub that will let you choose between products (currently Microsoft 365 Defender, Microsoft Defender for Endpoint, and Microsoft Defender for Office 365).
Notice that the number of learning resources for each section is listed, which can help learners keep track of how many resources they have at hand for training and learning.

Along with the Product filter, current topics, types of resources (from videos to webinars), levels of familiarity or experience with security areas, security roles, and product features are listed.
____

____
[!TIP] There are lots of other learning opportunities in link:/training/[Microsoft Learn].
You'll find certification training such as link:/training/certifications/courses/ms-500t02[Course MS-500T02-A: Implementing Microsoft 365 Threat Protection].
____

=== Send us your feedback

We need your feedback.
We're always looking to improve, so if there's something you'd like to see, https://www.microsoft.com/videoplayer/embed/RE4K5Ci[watch this video to find out how you can trust us to read your feedback].

=== Explore what the Microsoft 365 Defender portal has to offer

Keep exploring the features and capabilities in Microsoft 365 Defender:

* xref:manage-incidents.adoc[Manage incidents and alerts]
* xref:threat-analytics.adoc[Track and respond to emerging threats with threat analytics]
* xref:m365d-action-center.adoc[The Action center]
* xref:./advanced-hunting-query-emails-devices.adoc[Hunt for threats across devices, emails, apps, and identities]
* xref:./custom-detection-rules.adoc[Custom detection rules]
* link:../../compliance/alert-policies.md#default-alert-policies[Email & collaboration alerts]
* xref:../office-365-security/attack-simulation-training.adoc[Create a phishing attack simulation] and link:/microsoft-365/security/office-365-security/attack-simulation-training-payloads[create a payload for training your teams]

=== Training for security analysts

With this learning path from Microsoft Learn, you can understand Microsoft 365 Defender and how it can help identify, control, and remediate security threats.

|===
| Training: | Detect and respond to cyber attacks with Microsoft 365 Defender

| image:../../media/microsoft-365-defender/m365-defender-secure-organization.svg[Microsoft 365 Defender training icon.]
| Microsoft 365 Defender unifies threat signals across endpoints, identities, email, and applications to provide integrated protection against sophisticated cyber attacks.
Microsoft 365 Defender is the central experience to investigate and respond to incidents and proactively search for ongoing malicious cyber security activities.<p> 1 hr 38 min - Learning Path - 5 Modules
|===

____
[!div class="nextstepaction"] link:/training/paths/defender-detect-respond/[Start >]
____

=== See also

* xref:whats-new.adoc[What's new in Microsoft 365 Defender]
* xref:microsoft-365-security-center-mdo.adoc[Microsoft Defender for Office 365 in Microsoft 365 Defender]
* xref:microsoft-365-security-center-mde.adoc[Microsoft Defender for Endpoint in Microsoft 365 Defender]
