= Redirecting accounts from Microsoft Defender for Endpoint to Microsoft 365 Defender
:audience: ITPro
:author: dansimp
:description: How to redirect accounts and sessions from the Defender for Endpoint to Microsoft 365 Defender.
:f1.keywords: ["NOCSH"]
:keywords: Microsoft 365 Defender, Getting started with Microsoft 365 Defender, security center redirection
:manager: dansimp
:ms.author: dansimp
:ms.collection: ["M365-security-compliance"]
:ms.custom: admindeeplinkDEFENDER
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: m365d
:ms.topic: article
:search.appverid: met150
:search.product: eADQiWindows 10XVcnh

== Redirecting accounts from Microsoft Defender for Endpoint to Microsoft 365 Defender

[!INCLUDE xref:../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* Microsoft 365 Defender
* Defender for Endpoint

In alignment with Microsoft's cross-domain approach to threat protection with SIEM and Extended detection and response (XDR), we've rebranded Microsoft Defender Advanced Threat Protection as Microsoft Defender for Endpoint and unified it into a single integrated portal: Microsoft 365 Defender.

This guide explains how to route accounts to Microsoft 365 Defender by enabling automatic redirection from the former Microsoft Defender for Endpoint portal (securitycenter.windows.com or securitycenter.microsoft.com), to https://go.microsoft.com/fwlink/p/?linkid=2077139[Microsoft 365 Defender].

____
[!NOTE] Microsoft Defender for Endpoint in Microsoft 365 Defender supports link:/windows/security/threat-protection/microsoft-defender-atp/grant-mssp-access[granting access to managed security service providers (MSSPs)] in the same that way access is xref:./mssp-access.adoc[granted in the Microsoft Defender Security Center].
____

=== What to expect

Once automatic redirection is enabled, accounts accessing the former Microsoft Defender for Endpoint portal at securitycenter.windows.com or securitycenter.microsoft.com, will be automatically routed to Microsoft 365 Defender portal at https://go.microsoft.com/fwlink/p/?linkid=2077139[+++<security.microsoft.com>+++</a>.+++</security.microsoft.com>+++]

Learn more about what's changed: xref:microsoft-365-security-center-mde.adoc[Microsoft Defender for Endpoint in Microsoft 365 Defender].

This includes redirection for direct access to the former portal via browser, including links pointing towards the former securitycenter.windows.com portal - such as links in email notifications, and links returned by SIEM API calls.

External links from email notifications or SIEM APIs currently contain links to both portals.
Once redirection is enabled, both links will point to Microsoft 365 Defender until the old link is eventually removed.
We encourage you to adopt the new link pointing to Microsoft 365 Defender.

Refer to the table below for more on links and routing.

=== SIEM API routing

|===
| Property | Destination when redirection is OFF | Destination when redirection is ON

| LinkToWDATP
| Alert page in securitycenter.windows.com
| Alert page in security.microsoft.com

| IncidentLinkToWDATP
| Incident page in securitycenter.windows.com
| Incident page in security.microsoft.com

| LinkToMTP
| Alert page in security.microsoft.com
| Alert page in security.microsoft.com

| IncidentLinkToMTP
| Incident page in security.microsoft.com
| Incident page in security.microsoft.com
|===

=== Email alert notifications

|===
| Property | Destination when redirection is OFF** | Destination when redirection is ON

| Alert page
| Alert page in securitycenter.windows.com
| Alert page in security.microsoft.com

| Incident page
| Incident page in securitycenter.windows.com
| Incident page in security.microsoft.com

| Alert page in Defender for Cloud portal
| Alert page in security.microsoft.com
| Alert page in security.microsoft.com

| Incident page in Defender for Cloud portal
| Incident page in security.microsoft.com
| Incident page in security.microsoft.com
|===

=== When does this take effect?

Once enabled, this update might take effect almost immediately for some accounts.
But the redirection might take longer to propagate to every account in your organization.
Accounts in active sessions while this setting is applied will not be ejected from their session and will only be routed to Microsoft 365 Defender after ending their current session and signing back in again.

==== Set up portal redirection

To start routing accounts to Microsoft 365 Defender:

. Make sure you're a global administrator or have security administrator permissions in Azure Active Directory.
. Sign in to https://go.microsoft.com/fwlink/p/?linkid=2077139[Microsoft 365 Defender].
. Navigate to *Settings* > *Endpoints* > *General* > *Portal redirection* or https://security.microsoft.com/preferences2/portal_redirection[click here].
. Toggle the Automatic redirection setting to *On*.
. Click *Enable* to apply automatic redirection to Microsoft 365 Defender.

____
[!IMPORTANT] Enabling this setting will not terminate active user sessions.
Accounts who are in an active session while this setting is applied will only be directed to Microsoft 365 Defender after ending their current session and signing in again.
____

____
[!NOTE] You must be a global administrator or have security administrator permissions in Azure Active Directory to enable or disable this setting.
____

=== Can I go back to using the former portal?

If something isn't working for you or if there's anything you're unable to complete through Microsoft 365 Defender, we want to hear about it.
If you've encountered any issues with redirection, we encourage you to let us know by using the Give feedback submission form.

To revert to the former Microsoft Defender for Endpoint portal:

. Sign in to https://go.microsoft.com/fwlink/p/?linkid=2077139[Microsoft 365 Defender] as a global administrator or using and account with security administrator permissions in Azure Active directory.
. Navigate to *Settings* > *Endpoints* > *General* > *Portal redirection* or https://security.microsoft.com/preferences2/portal_redirection[open the page here].
. Toggle the Automatic redirection setting to *Off*.
. Click *Disable* & share feedback when prompted.

This setting can be enabled again at any time.

Once disabled, accounts will no longer be routed to security.microsoft.com, and you will once again have access to the former portal - securitycenter.windows.com or securitycenter.microsoft.com.

=== Related information

* xref:microsoft-365-defender.adoc[Microsoft 365 Defender overview]
* xref:microsoft-365-security-center-mde.adoc[Microsoft Defender for Endpoint in Microsoft 365 Defender]
* https://www.microsoft.com/security/blog/?p=91813[Microsoft delivers unified SIEM and XDR to modernize security operations]
* https://afrait.com/blog/xdr-versus-siem/[XDR versus SIEM infographic]
* https://afrait.com/blog/the-new-defender/[`The New Defender`]
* https://www.microsoft.com/microsoft-365/security/microsoft-365-defender[About Microsoft 365 Defender]
* xref:portals.adoc[Microsoft security portals and admin centers]
