= Microsoft 365 Defender prerequisites
:audience: ITPro
:author: mjcaparas
:description: Learn about the licensing, hardware and software requirements, and other configuration settings for Microsoft 365 Defender
:f1.keywords: ["NOCSH"]
:keywords: requirements, prerequisites, hardware, software, browser, Microsoft 365 Defender, M365, license, E5, A5, EMS, purchase
:manager: dansimp
:ms.author: macapara
:ms.collection: M365-security-compliance
:ms.localizationpriority: medium
:ms.mktglfcycl: deploy
:ms.pagetype: security
:ms.service: microsoft-365-security
:ms.sitesec: library
:ms.subservice: m365d
:ms.topic: conceptual
:search.appverid: ["MOE150", "MET150"]
:search.product: eADQiWindows 10XVcnh

== Microsoft 365 Defender prerequisites

[!INCLUDE xref:../includes/microsoft-defender.adoc[Microsoft 365 Defender rebranding]]

*Applies to:*

* Microsoft 365 Defender

Learn about licensing and other requirements for provisioning and using xref:microsoft-365-defender.adoc[Microsoft 365 Defender].

=== Licensing requirements

Any of these licenses gives you access to Microsoft 365 Defender features via the Microsoft 365 Defender portal without additional cost:

* Microsoft 365 E5 or A5
* Microsoft 365 E3 with the Microsoft 365 E5 Security add-on
* Microsoft 365 E3 with the Enterprise Mobility + Security E5 add-on
* Microsoft 365 A3 with the Microsoft 365 A5 Security add-on
* Windows 10 Enterprise E5 or A5
* Windows 11 Enterprise E5 or A5
* Enterprise Mobility + Security (EMS) E5 or A5
* Office 365 E5 or A5
* Microsoft Defender for Endpoint
* Microsoft Defender for Identity
* Microsoft Defender for Cloud Apps
* Defender for Office 365 (Plan 2)

For more information, https://www.microsoft.com/licensing/product-licensing/microsoft-365-enterprise[view the Microsoft 365 Enterprise service plans].

____
Don't have license yet?
xref:../../commerce/try-or-buy-microsoft-365.adoc[Try or buy a Microsoft 365 subscription]
____

==== Check your existing  licenses

Go to Microsoft 365 admin center (https://admin.microsoft.com/[admin.microsoft.com]) to view your existing licenses.
In the admin center, go to *Billing* > *Licenses*.

____
[!NOTE] You need to be assigned either the *Billing admin* or *Global reader* link:/azure/active-directory/roles/permissions-reference[role in Azure AD] to be able to see license information.
If you encounter access problems, contact a global admin.
____

=== Required permissions

You must be a *global administrator* or a *security administrator* in Azure Active Directory to turn on Microsoft 365 Defender.
For the list of roles required to use Microsoft 365 Defender and information on how access to data is regulated, read about xref:m365d-permissions.adoc[managing access to Microsoft 365 Defender].

=== Browser requirements

Access Microsoft 365 Defender in the Microsoft 365 Defender portal using Microsoft Edge, Internet Explorer 11, or any HTML 5 compliant web browser.

=== Availability to US GCC, GCC High, and other US government institutions

For information related to US Government customers, see xref:usgov.adoc[Microsoft 365 Defender for US Government customers].

Currently, the Microsoft Defender for Office 365 integration into the unified Microsoft 365 Defender features are not available to customers in the following Office 365 datacenter locations:

* Norway
* South Africa
* United Arab Emirates
* Sweden
* Singapore

=== Related topics

* xref:microsoft-365-defender.adoc[Microsoft 365 Defender overview]
* xref:m365d-enable.adoc[Turn on Microsoft 365 Defender]
* xref:m365d-permissions.adoc[Manage access and permissions]
