= 
siosulli
:keywords: microsoft secure score, secure score, Microsoft 365 Defender
portal, Secure score, data storage and privacy, storage, privacy,
licensing, geolocation, data retention, data

== Microsoft Secure Score data storage and privacy

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

This section covers frequently asked questions regarding privacy and
data handling for Secure Score.

=== Data storage location

Secure score operates in the Microsoft Azure datacenters in the European
Union, the United Kingdom, or in the United States. Customer data
collected by the service may be stored in: (a) the geo-location of the
tenant as identified during provisioning or, (b) if Secure Score uses
another Microsoft online service to process such data, the geolocation
as defined by the data storage rules of that other online service.

Customer data in pseudonymized form may also be stored in the central
storage and processing systems in the United States.

Once configured, you cannot change the location where your data is
stored. This provides a convenient way to minimize compliance risk by
actively selecting the geographic locations where your data will reside.

=== How long will Microsoft store my data? What is Microsoft’s data retention policy?

==== At service onboarding

By default, data is retained for 90 days based on your active licenses.

==== At contract termination or expiration

Your data will be kept and will be available to you while the license is
under grace period or suspended mode. At the end of this period, data
which is associated to expired or terminated license will be erased from
Microsoft’s systems to make it unrecoverable, no later than 90 days from
the associated contract termination or expiration.
