= 
mjcaparas
:keywords: raw data export, streaming API, API, Event hubs, Azure
storage, storage account, Advanced Hunting, raw data sharing

== Streaming API

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
[!NOTE] *Try our new APIs using MS Graph security API*. Find out more
at: link:/graph/api/resources/security-api-overview[Use the Microsoft
Graph security API - Microsoft Graph beta | Microsoft Learn].
____

{empty}[!includelink:../../includes/prerelease.md[Prerelease
information]]

=== Stream Advanced Hunting events to Event Hubs and/or Azure storage account.

Microsoft 365 Defender supports streaming events through
link:../defender/advanced-hunting-overview.md[Advanced Hunting] to an
link:/azure/event-hubs/[Event Hubs] and/or link:/azure/event-hubs/[Azure
storage account].

For more information on Microsoft 365 Defender streaming API, see the
https://www.microsoft.com/en-us/videoplayer/embed/RE4r4ga[video].

=== In this section

[width="100%",cols="<50%,<50%",options="header",]
|===
|Topic |Description
|link:streaming-api-event-hub.md[Stream events to Azure Event Hubs]
|Learn about enabling the streaming API in your tenant and configure
Microsoft 365 Defender to stream
link:../defender/advanced-hunting-overview.md[Advanced Hunting] to Event
Hubs.

|link:streaming-api-storage.md[Stream events to your Azure storage
account] |Learn about enabling the streaming API in your tenant and
configure Microsoft 365 Defender to stream
link:advanced-hunting-overview.md[Advanced Hunting] to your Azure
storage account.

|link:supported-event-types.md[Supported event types] |Learn which
Advanced Hunting event types the Streaming API supports.
|===

Watch this short video to learn how to set up the streaming API to ship
event information directly to Azure Event hubs for consumption by
visualization services, data processing engines, or Azure storage for
long-term data retention. +
> [!VIDEO https://www.microsoft.com/en-us/videoplayer/embed/RE4r4ga]

=== Related topics

* link:/graph/api/resources/security-api-overview[Use the Microsoft
Graph security API - Microsoft Graph beta | Microsoft Learn]
* link:../defender/advanced-hunting-overview.md[Overview of Advanced
Hunting]
* link:/azure/event-hubs/[Azure Event Hubs documentation]
* link:/azure/storage/common/storage-account-overview[Azure Storage
Account documentation]
