= 
mjcaparas
:keywords: raw data export, streaming API, API, Azure Event Hubs, Azure
storage, storage account, Advanced Hunting, raw data sharing

== Configure Microsoft 365 Defender to stream Advanced Hunting events to your Azure Event Hub

{empty}[!INCLUDE link:../../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

*Applies to:* -
https://go.microsoft.com/fwlink/?linkid=2118804[Microsoft 365 Defender]

____
[!NOTE] *Try our new APIs using MS Graph security API*. Find out more
at: link:/graph/api/resources/security-api-overview[Use the Microsoft
Graph security API - Microsoft Graph beta | Microsoft Learn].
____

{empty}[!includelink:../../includes/prerelease.md[Prerelease
information]]

=== Prerequisites

Prior to configuring Microsoft 365 Defender to stream data to Event
Hubs, ensure the following prerequisites are fulfilled:

[arabic]
. Create an Event Hubs (for information, see
link:configure-event-hub.md#set-up-event-hubs[Set up Event Hubs]).
. Creating an Event Hubs Namespace (for information, see
link:configure-event-hub.md#set-up-event-hubs-namespace[Set up Event
Hubs namespace]).
. Add permissions to the entity who has the privileges of a
*Contributor* so that this entity can export data to the Event Hubs. For
more information on adding permissions, see
link:configure-event-hub.md#add-permissions[Add permissions]

____
[!NOTE] The Streaming API can be integrated either via Event Hubs or
Azure Storage Account.
____

=== Enable raw data streaming

[arabic]
. Log on to Microsoft 365 Defender portal as a *_Global Administrator_*
or *_Security Administrator_*.
. Go to the
https://sip.security.microsoft.com/settings/mtp_settings/raw_data_export[Streaming
API settings page].
. Click on *Add*.
. Choose a name for your new settings.
. Choose *Forward events to Azure Event Hub*.
. You can select if you want to export the event data to a single Event
Hub, or to export each event table to a different Event Hubs in your
Event Hubs namespace.
. To export the event data to a single Event Hub, enter your *Event Hub
name* and your *Event Hub resource ID*.
+
To get your *Event Hub resource ID*, go to your Azure Event Hubs
namespace page on https://ms.portal.azure.com/[Azure] > *Properties* tab
> copy the text under *Resource ID*:
+
:::image type=``content''
source=``../defender-endpoint/images/event-hub-resource-id.png''
alt-text=``An Event Hub resource ID''
lightbox=``../defender-endpoint/images/event-hub-resource-id.png'':::
. Go to the link:supported-event-types.md[Supported Microsoft 365
Defender event types in event streaming API] to review the support
status of event types in the Microsoft 365 Streaming API.
. Choose the events you want to stream and click *Save*.

=== The schema of the events in Azure Event Hub

[source,json]
----
{
   "records": [
               {
                  "time": "<The time Microsoft 365 Defender received the event>"
                  "tenantId": "<The Id of the tenant that the event belongs to>"
                  "category": "<The Advanced Hunting table name with 'AdvancedHunting-' prefix>"
                  "properties": { <Microsoft 365 Defender Advanced Hunting event as Json> }
               }
               ...
            ]
}
----

* Each Event Hubs message in Azure Event Hubs contains list of records.
* Each record contains the event name, the time Microsoft 365 Defender
received the event, the tenant it belongs (you’ll only get events from
your tenant), and the event in JSON format in a property called
``**properties**''.
* For more information about the schema of Microsoft 365 Defender
events, see link:advanced-hunting-overview.md[Advanced Hunting
overview].
* In Advanced Hunting, the *DeviceInfo* table has a column named
*MachineGroup* which contains the group of the device. Here every event
will be decorated with this column as well.

=== Data types mapping

To get the data types for event properties, do the following steps:

[arabic]
. Log on to Microsoft 365 Defender and go to
https://security.microsoft.com/hunting-package[Advanced Hunting page].
. Run the following query to get the data types mapping for each event:
+
[source,kusto]
----
{EventType}
| getschema
| project ColumnName, ColumnType
----

* Here’s an example for Device Info event:
+
:::image type=``content''
source=``../defender-endpoint/images/machine-info-datatype-example.png''
alt-text=``An example query for device info''
lightbox=``../defender-endpoint/images/machine-info-datatype-example.png'':::

=== Estimating initial Event Hub capacity

The following Advanced Hunting query can help provide a rough estimate
of data volume throughput and initial event hub capacity based on
events/sec and estimated MB/sec. We recommend running the query during
regular business hours so as to capture `real' throughput.

[source,kusto]
----
let bytes_ = 500;
union withsource=MDTables*
| where Timestamp > startofday(ago(6h))
| summarize count() by bin(Timestamp, 1m), MDTables
| extend EPS = count_ /60
| summarize avg(EPS), estimatedMBPerSec = (avg(EPS) * bytes_ ) / (1024*1024) by MDTables
| sort by toint(estimatedMBPerSec) desc
----

=== Monitoring created resources

You can monitor the resources created by the streaming API using *Azure
Monitor*. For more information, see
link:/azure/azure-monitor/logs/logs-data-export[Log Analytics workspace
data export in Azure Monitor].

=== Related topics

* link:/graph/api/resources/security-api-overview[Use the Microsoft
Graph security API - Microsoft Graph beta | Microsoft Learn]
* link:advanced-hunting-overview.md[Overview of Advanced Hunting]
* link:streaming-api.md[Microsoft 365 Defender streaming API]
* link:supported-event-types.md[Supported Microsoft 365 Defender event
types in event streaming API]
* link:streaming-api-storage.md[Stream Microsoft 365 Defender events to
your Azure storage account]
* link:/azure/event-hubs/[Azure Event Hubs documentation]
* link:/azure/event-hubs/troubleshooting-guide[Troubleshoot connectivity
issues - Azure Event Hubs]
