= 
dansimp
:keywords: Microsoft Defender Antivirus, Windows Defender Antivirus, av
reviews, antivirus test, av testing, latest av scores, detection scores,
security product testing, security industry tests, industry antivirus
tests, best antivirus, av-test, av-comparatives, SE labs, MITRE ATT&CK,
endpoint protection platform, EPP, endpoint detection and response, EDR,
Windows 10, Windows 11 Microsoft Defender Antivirus, WDAV, Microsoft
Defender for Endpoint, Microsoft 365 Defender, security, malware, av,
antivirus, scores, scoring, next generation protection, ranking, success

== Top scoring in industry tests

{empty}[!INCLUDE link:../includes/microsoft-defender.md[Microsoft 365
Defender rebranding]]

https://www.microsoft.com/security/business/threat-protection/integrated-threat-protection[Microsoft
365 Defender] technologies consistently achieve high scores in
independent tests, demonstrating the strength of its enterprise threat
protection capabilities. Microsoft aims to be transparent about these
test scores. This page summarizes the results and provides analysis.

=== Microsoft 365 Defender

link:microsoft-365-defender.md[Microsoft 365 Defender] is a unified pre-
and post-breach enterprise defense suite. It natively coordinates
detection, prevention, investigation, and response across endpoints,
identities, email, and applications to provide integrated protection
against sophisticated attacks.

Microsoft 365 Defender combines the capabilities of
https://www.microsoft.com/microsoft-365/windows/microsoft-defender-atp[Microsoft
Defender for Endpoint],
https://www.microsoft.com/microsoft-365/exchange/advance-threat-protection[Microsoft
Defender for Office 365],
https://azure.microsoft.com/features/azure-advanced-threat-protection/[Microsoft
Defender for Identity],
link:/azure/active-directory/identity-protection/overview-identity-protection[Azure
Active Directory Identity Protection], and
https://www.microsoft.com/microsoft-365/enterprise-mobility-security/cloud-app-security[Microsoft
Defender for Cloud Apps] into a single solution.

==== MITRE: Demonstrated real-world detection, response, and protection from advanced attacks

Core to MITRE’s testing approach is emulating real-world attacks to
understand whether solutions can adequately detect and respond to them.
While the test focused on endpoint detection and response, MITRE’s
simulated APT29 attack spans multiple attack domains, creating
opportunities to empower defenders beyond just endpoint protection.
Microsoft expanded visibility beyond the endpoint with Microsoft 365
Defender.

* ATT&CK-based evaluation of Microsoft 365 Defender - April 2022:
%5BMicrosoft%20Security%20Blog:%20Microsoft%20365%20Defender%20demonstrates%20industry-leading%20protection%20in%20the%202022%20MITRE%20Engenuity%20ATT&CK®%20Evaluations%5D(https://www.microsoft.com/en-us/security/blog/2022/04/05/microsoft-365-defender-demonstrates-industry-leading-protection-in-the-2022-mitre-engenuity-attck-evaluations/)[Microsoft
365 Defender demonstrates industry-leading protection in the 2022 MITRE
Engenuity ATT&CK® Evaluations]
* ATT&CK-based evaluation of Microsoft 365 Defender - April 2021:
https://www.microsoft.com/security/blog/2021/04/21/[Evaluation proves
Microsoft Defender for Endpoint stops advanced attacks across platforms]

Microsoft 365 Defender provided nearly 100 percent coverage across the
attack chain stages. It delivered leading out-of-box visibility into
attacker activities. The visibility dramatically reduces manual work for
the security operations center and vendor solutions that relied on
specific configuration changes. Microsoft 365 Defender also had the
fewest gaps in visibility, diminishing attacker ability to operate
undetected.

=== Next generation protection

link:/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-in-windows-10[Microsoft
Defender Antivirus] consistently performs highly in independent tests,
displaying how it’s a top choice in the antivirus market. Keep in mind,
these tests only provide results for antivirus and don’t test for
additional security protections.

Microsoft Defender Antivirus is the
https://www.youtube.com/watch?v=Xy3MOxkX_o4[next generation protection]
capability in the
link:/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection[Microsoft
Defender for Endpoint Windows security stack] that addresses the latest
and most sophisticated threats today. In some cases, customers might not
even know they were protected because a cyberattack is stopped
https://cloudblogs.microsoft.com/microsoftsecure/2018/03/07/behavior-monitoring-combined-with-machine-learning-spoils-a-massive-dofoil-coin-mining-campaign[milliseconds
after a campaign starts]. That’s because Microsoft Defender Antivirus
and other
https://www.microsoft.com/security/blog/2019/08/23/gartner-names-microsoft-a-leader-in-2019-endpoint-protection-platforms-magic-quadrant/[endpoint
protection platform (EPP)] capabilities in Defender for Endpoint detect
and stop malware at first sight. They use
https://cloudblogs.microsoft.com/microsoftsecure/2018/06/07/machine-learning-vs-social-engineering[machine
learning],
https://cloudblogs.microsoft.com/microsoftsecure/2018/02/14/how-artificial-intelligence-stopped-an-emotet-outbreak[artificial
intelligence], behavioral analysis, and other advanced technologies.

==== AV-TEST: Protection score of 6.0/6.0 in the latest test

The AV-TEST Product Review and Certification Report tests on three
categories: protection, performance, and usability. The following scores
are for the Protection category that has two scores: Real-World Testing
and the AV-TEST reference set (known as ``Prevalent Malware'').

* November - December 2021 AV-TEST Business User test:
https://www.av-test.org/en/antivirus/business-windows-client/windows-10/december-2021/microsoft-defender-antivirus-4.18-212622/[Protection
score 6.0/6.0] *Latest*
+
Microsoft Defender Antivirus achieved a perfect Protection score of
6.0/6.0, with 100% in November and December. 18,870 malware samples were
used.
* September - October 2021 AV-TEST Business User test:
https://www.av-test.org/en/antivirus/business-windows-client/windows-10/october-2021/microsoft-defender-antivirus-4.18-212518/[Protection
score 6.0/6.0]
* July - August 2021 AV-TEST Business User test:
https://www.av-test.org/en/antivirus/business-windows-client/windows-10/august-2021/microsoft-defender-antivirus-4.18-212419/[Protection
score 6.0/6.0]
* May - June 2021 AV-TEST Business User test:
https://www.av-test.org/en/antivirus/business-windows-client/windows-10/june-2021/microsoft-defender-antivirus-4.18-212318/[Protection
score 6.0/6.0]
* March - April 2021 AV-TEST Business User test:
https://www.av-test.org/en/antivirus/business-windows-client/windows-10/april-2021/microsoft-defender-antivirus-4.18-212216/[Protection
score 6.0/6.0]
* January - February 2021 AV-TEST Business User test:
https://www.av-test.org/en/antivirus/business-windows-client/windows-10/february-2021/microsoft-defender-antivirus-4.18-212117/[Protection
score 6.0/6.0] |
https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE4CflZ[Analysis]

==== AV-Comparatives: Protection rating of 99.8% in the latest test

Business Security Test consists of three main parts: the Real-World
Protection Test that mimics online malware attacks, the Malware
Protection Test where the malware enters the system from outside the
internet (for example by USB), and the Performance Test that looks at
the impact on the system’s performance.

* Business Security Test 2021 (August - November):
https://www.av-comparatives.org/tests/business-security-test-2021-august-november/[Real-World
Protection Rate 99.8%] *Latest*
+
Microsoft Defender Antivirus has scored consistently high in Real-World
Protection Rates over the past year, with 99.8% in the latest test.
* Business Security Test 2021 (March - June):
https://www.av-comparatives.org/tests/business-security-test-2021-march-june/[Real-World
Protection Rate 99.7%]
* Business Security Test 2020 (August - November):
https://www.av-comparatives.org/tests/business-security-test-2020-august-november/[Real-World
Protection Rate 99.8%]
* Business Security Test 2020 (March - June):
https://www.av-comparatives.org/tests/business-security-test-2020-march-june/[Real-World
Protection Rate 99.7%] |
https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE3Esbl[Analysis]

==== SE Labs: AAA award in the latest test

SE Labs test a range of solutions used by products and services to
detect and/or protect against attacks. It includes endpoint software,
network appliances, and cloud services.

* Annual Report 2020 - 2021:
https://selabs.uk/wp-content/uploads/2021/11/annual-report-2021.pdf[AAA
award] *Latest*
* Enterprise Endpoint Protection: October - December 2021:
https://selabs.uk/wp-content/uploads/2021/12/oct-dec-2021-enterprise.pdf[AAA
award]
* Enterprise Advanced Security (EDR): Kaspersky: August to September
2021:
https://selabs.uk/wp-content/uploads/2021/12/AS-EDR-Kaspersky-EDR-2021-1.pdf[AAA
award]
* Enterprise Advanced Security (EDR): Crowdstrike: August to September
2021:
https://selabs.uk/wp-content/uploads/2021/12/AS-EDR-Crowdstrike-Falcon-2021-1.pdf[AAA
award]
* Breach Response (NDR Detection): VMware NSX Network Detection and
Response: August 2021:
https://selabs.uk/wp-content/uploads/2021/10/NDR-VMware-NSX-detection-2021-1.pdf[AAA
award]
* Enterprise Endpoint Protection: July - September 2021:
https://selabs.uk/wp-content/uploads/2021/11/july-sept-2021-enterprise.pdf[AAA
award]
* Breach Response (Protection): BlackBerry Protect and Optics: July
2021:
https://selabs.uk/wp-content/uploads/2021/07/BRT-BlackBerry-Protect-protection-2021-1.pdf[AAA
award]
* Enterprise Endpoint Protection: April - June 2021:
https://selabs.uk/wp-content/uploads/2021/07/apr-jun-2021-enterprise-1.pdf[AAA
award]
* Enterprise Endpoint Protection: January - March 2021:
https://selabs.uk/wp-content/uploads/2021/04/jan-mar-2021-enterprise.pdf[AAA
award] *pdf*

=== Endpoint detection & response

Microsoft Defender for Endpoint
link:/windows/security/threat-protection/microsoft-defender-atp/overview-endpoint-detection-response[endpoint
detection and response] capabilities provide advanced attack detections
that are near real-time and actionable. Security analysts can prioritize
alerts effectively, gain visibility into the full scope of a breach, and
take response actions to remediate threats.

Microsoft Defender for Endpoint’s EDR and endpoint protection
capabilities have received positive results from industry tests and
publications.
https://www.scmagazine.com/home/reviews/sc-product-reviews-endpoint-security/[SC
Labs assessed endpoint security tools] in June 2020, and gave Microsoft
Defender for Endpoint
https://www.scmagazine.com/review/microsoft-defender-advanced-threat-protection/[5/5
stars]. They called out Microsoft Defender for Endpoint’s ability to
protect organizations against the modern threat landscape using a full
set of security capabilities. SC Labs also identified the endpoint
security solution as holistic and unified. They also acknowledged the
convergence of endpoint protection with endpoint detection and response
functionality, because the attack chain now gets fully covered by
solutions.

=== To what extent are tests representative of protection in the real world?

Independent security industry tests aim to evaluate the best antivirus
and security products in an unbiased manner. However, Microsoft sees a
wider and broader set of threats beyond what’s tested in the evaluations
highlighted in this article. In an average month, Microsoft’s security
products identify over 100 million new threats. Even if an independent
tester can acquire and test 1% of those threats, that is a million tests
across 20 or 30 products. In other words, the vastness of the malware
landscape makes it difficult to evaluate the quality of protection
against real world threats.

The capabilities within Microsoft Defender for Endpoint provide
https://cloudblogs.microsoft.com/microsoftsecure/2017/12/11/detonating-a-bad-rabbit-windows-defender-antivirus-and-layered-machine-learning-defenses[additional
layers of protection] that aren’t factored into industry antivirus
tests, and address some of the latest and most sophisticated threats.
Isolating AV from the rest of Defender for Endpoint creates a partial
picture of how Microsoft’s security stack operates in the real world.
For example, attack surface reduction and endpoint detection & response
capabilities can help prevent malware from getting onto devices in the
first place. We’ve proven that
https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2ouJA[Microsoft
Defender for Endpoint components catch samples] that Microsoft Defender
Antivirus missed in these industry tests. It’s more representative of
how effectively Microsoft’s security suite protects customers in the
real world.

link:/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection[Learn
more about Microsoft Defender for Endpoint] and evaluate it in your own
network by signing up for a
https://www.microsoft.com/microsoft-365/windows/microsoft-defender-atp[90-day
trial], or
link:/windows/security/threat-protection/microsoft-defender-atp/preview[enabling
Preview features on existing tenants].

https://www.microsoft.com/security/business/threat-protection/integrated-threat-protection[Learn
more about Microsoft 365 Defender] or link:m365d-enable.md[start using
the service].
