= 
mjcaparas
:keywords: what’s new in Microsoft 365 Defender, ga, generally
available, capabilities, available, new

== What’s new in Microsoft 365 Defender

Lists the new features and functionality in Microsoft 365 Defender.

RSS feed: Get notified when this page is updated by copying and pasting
the following URL into your feed reader:

[source,http]
----
https://learn.microsoft.com/api/search/rss?search=%22Lists+the+new+features+and+functionality+in+Microsoft+365+defender%22&locale=en-us
----

For more information on what’s new with other Microsoft Defender
security products, see:

* link:../office-365-security/defender-for-office-365-whats-new.md[What’s
new in Microsoft Defender for Office 365]
* link:../defender-endpoint/whats-new-in-microsoft-defender-endpoint.md[What’s
new in Microsoft Defender for Endpoint]
* link:/defender-for-identity/whats-new[What’s new in Microsoft Defender
for Identity]
* link:/cloud-app-security/release-notes[What’s new in Microsoft
Defender for Cloud Apps]

You can also get product updates and important notifications through the
https://admin.microsoft.com/Adminportal/Home#/MessageCenter[message
center].

=== December 2022

* (Preview) The new Microsoft 365 Defender role-based access control
(RBAC) model is now available for preview. The new RBAC model enables
security admins to centrally manage privileges across multiple security
solutions within a single system with a greater efficiency, currently
supporting Microsoft Defender for Endpoint, Microsoft Defender for
Office 365, and Microsoft Defender for Identity. The new model is fully
compatible with the existing individual RBAC models currently supported
in Microsoft 365 Defender. For more information, see
link:./manage-rbac.md[Microsoft 365 Defender role-based access control
(RBAC)].

=== November 2022

* (Preview) Microsoft Defender Experts for XDR (Defender Experts for
XDR) is now available for preview. Defender Experts for XDR is a managed
detection and response service that helps your security operations
centers (SOCs) focus and accurately respond to incidents that matter. It
provides extended detection and response for customers who use Microsoft
365 Defender workloads: Microsoft Defender for Endpoint, Microsoft
Defender for Office 365, Microsoft Defender for Identity, Microsoft
Defender for Cloud Apps, and Azure Active Directory (Azure AD). For
details, refer to link:dex-xdr-overview.md[Expanded Microsoft Defender
Experts for XDR preview].
* (Preview) The query resource report is now available in advanced
hunting. The report shows your organization’s consumption of CPU
resources for hunting based on queries that ran in the last 30 days
using any of the hunting interfaces. See
link:advanced-hunting-limits.md#view-query-resources-report-to-find-inefficient-queries[View
query resources report] to find inefficient queries.

=== August 2022

* (GA) link:defender-experts-for-hunting.md[Microsoft Defender Experts
for Hunting] is now generally available. If you’re a Microsoft 365
Defender customer with a robust security operations center but want
Microsoft to help you proactively hunt for threats across endpoints,
Office 365, cloud applications, and identity using Microsoft Defender
data, then learn more about applying, setting up, and using the service.
Defender Experts for Hunting is sold separately from other Microsoft 365
Defender products.
* (Preview)
link:advanced-hunting-modes.md#get-started-with-guided-hunting-mode[Guided
mode] is now available for public preview in advanced hunting. Analysts
can now start querying their database for endpoint, identities, email &
collaboration, and cloud apps data _without knowing Kusto Query Language
(KQL)_. Guided mode features a friendly, easy-to-use, building-block
style of constructing queries through dropdown menus containing
available filters and conditions. See
link:advanced-hunting-query-builder.md[Get started with query builder].

=== July 2022

* (Preview) Microsoft Defender Experts for Hunting public preview
participants can now look forward to receiving monthly reports to help
them understand the threats the hunting service surfaced in their
environment, along with the alerts generated by their Microsoft 365
Defender products. For details, refer to
link:defender-experts-report.md[Understand the Defender Experts for
Hunting report in Microsoft 365 Defender].

=== June 2022

* (Preview) The
link:advanced-hunting-devicetvminfogathering-table.md[DeviceTvmInfoGathering]
and
link:advanced-hunting-devicetvminfogatheringkb-table.md[DeviceTvmInfoGatheringKB]
tables are now available in the advanced hunting schema. Use these
tables to hunt through assessment events in Defender Vulnerability
Management including the status of various configurations and attack
surface area states of devices.
* The newly introduced Automated investigation & response card in the
Microsoft 365 Defender portal provides an overview on pending
remediation actions. The security operations team can view all actions
pending approval, and the stipulated time to approve those actions in
the card itself. The security team can quickly navigate to the Action
center and take appropriate remediation actions. The Automated
investigation & response card also has a link to the Full Automation
page. This enables the security operations team to effectively manage
alerts and complete remediation actions in a timely manner.

=== May 2022

* (Preview) In line with the recently announced expansion into a new
service category called
https://aka.ms/MicrosoftSecurityExperts[Microsoft Security Experts],
we’re introducing the availability of
link:defenderexpertsforhuntingprev.md[Microsoft Defender Experts for
Hunting] (Defender Experts for Hunting) for public preview. Defender
Experts for Hunting is for customers who have a robust security
operations center but want Microsoft to help them proactively hunt for
threats across Microsoft Defender data, including endpoints, Office 365,
cloud applications, and identity.

=== April 2022

* (Preview) link:advanced-hunting-take-action.md[Actions] can now be
taken on email messages straight from hunting query results. Emails can
be moved to other folders or deleted permanently.
* (Preview) The new
link:advanced-hunting-urlclickevents-table.md[`UrlClickEvents` table] in
advanced hunting can be used to hunt for threats like phishing campaigns
and suspicious links based on information coming from Safe Links clicks
in email messages, Microsoft Teams, and Office 365 apps.

=== March 2022

* (Preview) The incident queue has been enhanced with several features
designed to help your investigations. Enhancements include capabilities
such as ability to search for incidents by ID or name, specify a custom
time range, and others.

=== December 2021

* (GA) The `DeviceTvmSoftwareEvidenceBeta` table was added on a
short-term basis in advanced hunting to allow you to view evidence of
where a specific software was detected on a device.

=== November 2021

* (Preview) The application governance add-on feature to Defender for
Cloud Apps is now available in Microsoft 365 Defender. App governance
provides a security and policy management capability designed for
OAuth-enabled apps that access Microsoft 365 data through Microsoft
Graph APIs. App governance delivers full visibility, remediation, and
governance into how these apps and their users access, use, and share
your sensitive data stored in Microsoft 365 through actionable insights
and automated policy alerts and actions.
link:/cloud-app-security/app-governance-manage-app-governance[Learn more
about application governance].
* (Preview) The link:advanced-hunting-overview.md[advanced hunting] page
now has multitab support, smart scrolling, streamlined schema tabs,
quick edit options for queries, a query resource usage indicator, and
other improvements to make querying smoother and easier to fine-tune.
* (Preview) You can now use the
link:advanced-hunting-link-to-incident.md[link to incident] feature to
include events or records from the advanced hunting query results right
into a new or existing incident that you are investigating.

=== October 2021

* (GA) In advanced hunting, more columns were added in the
link:advanced-hunting-cloudappevents-table.md[CloudAppEvents] table. You
can now include `AccountType`, `IsExternalUser`, `IsImpersonated`,
`IPTags`, `IPCategory`, and `UserAgentTags` to your queries.

=== September 2021

* (GA) Microsoft Defender for Office 365 event data is available in the
Microsoft 365 Defender event streaming API. You can see the availability
and status of event types in the link:supported-event-types.md[Supported
Microsoft 365 Defender event types in streaming API].
* (GA) Microsoft Defender for Office 365 data available in advanced
hunting is now generally available.
* (GA) Assign incidents and alerts to user accounts
+
You can assign an incident, and all the alerts associated with it, to a
user account from *Assign to:* on the *Manage incident* pane of an
incident or the *Manage alert* pane of an alert.

=== August 2021

* (Preview) Microsoft Defender for Office 365 data available in advanced
hunting
+
New columns in email tables can provide more insight into email-based
threats for more thorough investigations using advanced hunting. You can
now include the `AuthenticationDetails` column in
link:./advanced-hunting-emailevents-table.md[EmailEvents], `FileSize` in
link:./advanced-hunting-emailattachmentinfo-table.md[EmailAttachmentInfo],
and `ThreatTypes` and `DetectionMethods` in
link:./advanced-hunting-emailpostdeliveryevents-table.md[EmailPostDeliveryEvents]
tables.
* (Preview) Incident graph
+
A new *Graph* tab on the *Summary* tab of an incident shows the full
scope of the attack, how the attack spread through your network over
time, where it started, and how far the attacker went.

=== July 2021

* https://sip.security.microsoft.com/interoperability/professional_services[Professional
services catalog]
+
Enhance the detection, investigation, and threat intelligence
capabilities of the platform with supported partner connections.

=== June 2021

* (Preview) link:threat-analytics.md#view-reports-per-threat-tags[View
reports per threat tags]
+
Threat tags help you focus on specific threat categories and review the
most relevant reports.
* (Preview) link:../defender-endpoint/raw-data-export.md[Streaming API]
+
Microsoft 365 Defender supports streaming all the events available
through Advanced Hunting to an Event Hubs and/or Azure storage account.
* (Preview) link:advanced-hunting-take-action.md[Take action in advanced
hunting]
+
Quickly contain threats or address compromised assets that you find in
link:advanced-hunting-overview.md[advanced hunting].
* (Preview)
link:advanced-hunting-schema-tables.md#get-schema-information-in-the-security-center[In-portal
schema reference]
+
Get information about advanced hunting schema tables directly in the
security center. In addition to table and column descriptions, this
reference includes supported event types (`ActionType` values) and
sample queries.
* (Preview)
link:advanced-hunting-devicefromip-function.md[DeviceFromIP() function]
+
Get information about which devices have been assigned a specific IP
address or addresses at a given time range.

=== May 2021

* https://techcommunity.microsoft.com/t5/microsoft-365-defender/easily-find-anomalies-in-incidents-and-alerts/ba-p/2339243[New
alert page in the Microsoft 365 Defender portal]
+
Provides enhanced information for the context into an attack. You can
see which other triggered alert caused the current alert and all the
affected entities and activities involved in the attack, including
files, users and mailboxes. See
link:/microsoft-365/security/defender/investigate-alerts[Investigate
alerts] for more information.
* https://techcommunity.microsoft.com/t5/microsoft-365-defender/new-alert-page-for-microsoft-365-defender-incident-detections/ba-p/2350425[Trend
graph for incidents and alerts in the Microsoft 365 Defender portal]
+
Determine if there are several alerts for a single incident or that your
organization is under attack with several different incidents. See
link:/microsoft-365/security/defender/incident-queue[Prioritize
incidents] for more information.

=== April 2021

* Microsoft 365 Defender
+
The improved https://security.microsoft.com[Microsoft 365 Defender]
portal is now available. This new experience brings together Defender
for Endpoint, Defender for Office 365, Defender for Identity, and more
into a single portal. This is the new home to manage your security
controls. link:microsoft-365-defender-portal.md[Learn what’s new].
* link:threat-analytics.md[Microsoft 365 Defender threat analytics
report]
+
Threat analytics helps you respond to and minimize the impact of active
attacks. You can also learn about attack attempts blocked by Microsoft
365 Defender solutions and take preventive actions that mitigate the
risk of further exposure and increase resiliency. As part of the unified
security experience, threat analytics is now available for Microsoft
Defender for Endpoint and Microsoft Defender for Office E5 license
holders.

=== March 2021

* link:advanced-hunting-cloudappevents-table.md[CloudAppEvents table]
+
Find information about events in various cloud apps and services covered
by Microsoft Defender for Cloud Apps. This table also includes
information previously available in the `AppFileEvents` table.
