= Microsoft Purview Compliance Manager quickstart guide
:audience: Admin
:author: chvukosw
:description: Use the Compliance Manager quickstart guide to help you along your journey of understanding, getting set up, and using Compliance Manager.
:f1.keywords: ["NOCSH"]
:manager: laurawi
:ms.author: chvukosw
:ms.collection: ["M365-security-compliance", "m365solution-compliancemanager", "m365initiative-compliance"]
:ms.custom: admindeeplinkCOMPLIANCE
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: article
:search.appverid: ["MOE150", "MET150"]

== Compliance Manager quickstart

*In this article:* Use this quickstart guide to help you along your journey of using Microsoft Purview Compliance Manager to manage your organization's compliance with regulations, policies, and standards.

Compliance Manager provides intelligent and actionable data upon your first visit.
Compliance Manager also has advanced capabilities for scaling your compliance when you're ready.
Available assessments depend on your licensing agreement;
link:/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance[learn more].

Whether you're coming to Compliance Manager for the first time, or are ready to use some of the advanced features, this guide can support you along your journey.

=== First visit: get to know Compliance Manager

Compliance Manager is located in the https://go.microsoft.com/fwlink/p/?linkid=2077149[Microsoft Purview compliance portal].
Your organization's global administrator will need to link:compliance-manager-setup.md#set-user-permissions-and-assign-roles[set up user permissions and assign roles] before you start using Compliance Manager.

The first time you visit Compliance Manager, you'll see a compliance score for your organization.
Compliance Manager is already assessing your current Microsoft 365 environment against the data protection baseline.
The best way to start getting familiar with Compliance Manager is to understand what it's showing you, its key elements, and how to customize your dashboard.

Our xref:compliance-manager.adoc[Compliance Manager overview page] is the best first stop for a comprehensive review of what Compliance Manager is and how it works.
You may also want to jump right to key sections of our documentation using the links below:

* link:compliance-manager.md#understanding-your-compliance-score[Understand your compliance score]
* link:compliance-manager.md#key-elements-controls-assessments-templates-improvement-actions[Overview of key elements: controls, assessments, templates, and improvement actions]
* link:compliance-manager-setup.md#understand-the-compliance-manager-dashboard[Understand the Compliance Manager dashboard]
* link:compliance-manager-setup.md#filtering-your-dashboard-view[Filter your dashboard view]
* link:compliance-manager-setup.md#improvement-actions-page[Learn about improvement actions]
* link:compliance-manager.md#assessments[Understand assessments]
* xref:compliance-manager-mcca.adoc[Do a quick scan of your environment using the Configuration Analyzer for Microsoft Purview]

=== Ramping up: configure Compliance Manager to manage your compliance activities

Once you're familiar with the basics, it's time to set up things to meet your organization's needs.
You can start working with assessments and taking improvement actions to implement controls and improve your compliance score.
Knowing how to perform all the activities at this stage can help your organization comply and demonstrate compliance with regulations across your industry and region.
Visit the links below to dive in:

* xref:compliance-manager-assessments.adoc[Choose a pre-built assessment to create and manage your first assessment]
* xref:compliance-manager-templates.adoc[Understand how to use templates for building assessments]
* xref:compliance-manager-improvement-actions.adoc[Perform implementation and testing work on improvement actions to complete controls in your assessments]
* xref:compliance-score-calculation.adoc[Better understand how different actions impact your compliance score]

=== Scaling up: use advanced functionality to meet your custom needs

When you're comfortable managing assessments in Compliance Manager, you can work with templates to modify a Compliance Manager assessment with your own actions and controls.
You can also create your own custom assessment.
Custom assessments are helpful for:

* Managing compliance for non-Microsoft 365 products such as third-party apps and services, on-premises applications, and other assets.
* Managing your own custom or business-specific compliance controls.

You can also set up automated testing of all or a subset of improvement actions.
Visit the links below to understand more advanced functionality in Compliance Manager:

* xref:compliance-manager-templates-extend.adoc[Extend a Compliance Manager template by adding your own controls and improvement actions]
* xref:compliance-manager-templates-create.adoc[Create your own custom template]
* xref:compliance-manager-templates-modify.adoc[Modify an existing template to add or remove controls and actions]
* link:compliance-manager-setup.md#set-up-automated-testing[Set up automated testing of improvement actions]
* link:compliance-manager-setup.md#reassign-improvement-actions-to-another-user[Reassign improvement actions to another user]
