= About the Microsoft Purview Compliance Manager premium assessment trial
:audience: Admin
:author: chvukosw
:description: About the Microsoft Purview Compliance Manager premium assessment trials.
:experimental:
:f1.keywords: ["NOCSH"]
:manager: laurawi
:ms.author: chvukosw
:ms.collection: m365-security-compliance
:ms.localizationpriority: high
:ms.service: O365-seccomp
:ms.topic: article
:search.appverid: ["MOE150", "MET150"]

== About the free trial for Microsoft Purview Compliance Manager premium assessments

Compliance Manager helps you manage your organization's compliance requirements and assess and improve your compliance score.
The assessments you build are based on templates that correspond to governmental regulations and industry standards around the world.

Your licensing agreement to use Compliance Manager may include one or more built-in templates for building assessments.
An extensive library of premium assessment templates is also available for building assessments specific to your organization's needs.
To try out these templates before purchasing licenses, sign up for the free Compliance Manager premium assessments trial.

=== Terms and conditions

See the link:/legal/microsoft-365/microsoft-365-trial[terms and conditions] for Microsoft 365 trials.

=== Set up a premium assessment trial

You can sign up for a trial in the Microsoft Purview compliance portal using the *Trials* link in the left navigation pane.
Select the *Compliance Manager premium assessment trial* to start a trial for premium assessment templates.

This premium assessment trial is available to organizations using Compliance Manager under a commercial license.
For GCC and DOD information and trial options, see xref:compliance-manager-templates.adoc[Working with Compliance Manager templates].

Full access to Compliance Manager features may depend on your licensing agreement for Compliance Manager.
To learn more about the free compliance trial that includes Compliance Manager, see xref:compliance-easy-trials.adoc[About the free trial for Microsoft Purview].

____
[!NOTE] Check your Microsoft 365 admin center settings to facilitate enrollment in the trial.
In the Microsoft 365 admin center, go to the menu:Settings[Org settings > Services] page, and select *User owned apps and services*.
Then check the box to let users start trials on behalf of your organization.
When setup finishes in about two minutes, you can go back and uncheck the box to disable this setting.
You can also start the trial without adjusting your org settings by going to the menu:Billing[Purchase services] page and searching for the Compliance Manager premium assessment trial.
____

=== Template licensing

Starting your one-time trial for premium assessments gives you the right to use 25 premium templates of your choice for free for 90 days.
You can create as many assessments from the 25 templates as you wish.

After you start your trial, go to your *Assessments* tab in Compliance Manager and view the *Activated/Licensed templates* counter to see how many templates are available and are in use.
This counter will show your 25 licensed templates.
As you create assessments using these templates, your activated number will update.
Template use is counted based on the underlying certification, meaning that multiple assessments based on the same template, or different versions of the same template that support different products, will count as one template use.

For more information about how to use and manage Compliance Manager templates, see xref:compliance-manager-templates.adoc[Working with assessment templates].

=== Required roles for starting the trial

Users must hold one of the following admin roles in order to sign up for or end a trial:

* Billing Administrator
* Compliance Administrator
* Global Administrator
* Compliance Data Administrator

Get more details about xref:compliance-easy-trials-roles.adoc[roles for starting Microsoft 365 trials].

=== During your trial

Throughout your trial, you can review the *Trial summary* section of the *Overview* page in Compliance Manager to see how many assessments you've created, how many improvement actions you've taken, how that has contributed to your compliance score, and how much time remains in your trial.
From here, you can also review the list of available templates and learn more about purchasing them for ongoing use.

=== After the trial

After your trial ends, the templates you used won't receive automatic updates and may fall out of date with any regulatory changes.
We recommend that you delete assessments built from templates that you don't intend to purchase.

=== Learn more about compliance

To learn more about the features of Compliance Manager and how it can help your organization meet compliance and regulatory requirements, see xref:compliance-manager.adoc[Microsoft Purview Compliance Manager].

You can also learn about other Microsoft compliance solutions and how to start trials at xref:compliance-easy-trials.adoc[About the free trial for Microsoft Purview].
