= Microsoft Purview solutions trial playbook
:ROBOTS: NOINDEX, NOFOLLOW
:audience: Admin
:author: chvukosw
:description: Microsoft Purview solutions trial playbook.
:f1.keywords: ["NOCSH"]
:manager: laurawi
:ms.author: chvukosw
:ms.collection: m365-security-compliance
:ms.custom: trial-playbook
:ms.localizationpriority: high
:ms.service: O365-seccomp
:ms.topic: landing-page
:search.appverid: ["MOE150", "MET150"]

== Trial playbook: Microsoft Purview solutions

Welcome to the Microsoft Purview solutions trial playbook.
This playbook will help you make the most of your free trial by helping you discover robust and comprehensive capabilities of Microsoft Purview and security products.

=== Compliance actions with Microsoft Purview

Easily and quickly start trying Microsoft's compliance solutions without changing your organization's metadata.

Depending on your priorities, you can start with any of these solution areas to see immediate value.
Here are four top organizational concerns as communicated by our customers and recommended solutions to start with.

:::image type="content" source="../media/compliance-trial/workflow.png" alt-text="Top organizational concerns":::

*Let's get started!*

=== Microsoft Purview Compliance Manager

We recommend that you become familiar with Compliance Manager and improve your organization's compliance posture.
What can Compliance Manager do for your organization?

* It can help you  get compliant -- with easy onboarding and step-by-step guidance
* It can help you stay compliant -- with customizable and multi-cloud assessments
* It can help you scale compliance -- with built-in collaboration and workflow capabilities

==== Step 1: Get to know Compliance Manager

Our Compliance Manager overview page is the best first stop for a comprehensive review of what Compliance Manager is and how it works.

* Start with the https://go.microsoft.com/fwlink/?linkid=2197452[Microsoft Purview Compliance Manager Setup Guide].

You may also want to jump right to key sections of our documentation using the links below:

* link:compliance-manager.md#understanding-your-compliance-score[Understand your compliance score]
* link:compliance-manager.md#key-elements-controls-assessments-templates-improvement-actions[Overview of key elements]: controls, assessments, templates, and improvement actions
* link:compliance-manager-setup.md#understand-the-compliance-manager-dashboard[Understand the Compliance Manager dashboard]
* link:compliance-manager-setup.md#filtering-your-dashboard-view[Filter your dashboard view]
* link:compliance-manager-setup.md#improvement-actions-page[Learn about improvement actions]
* link:compliance-manager.md#assessments[Understand assessments]
* xref:compliance-manager-mcca.adoc[Do a quick scan of your environment using the Microsoft Compliance Configuration Analyzer for Compliance Manager (preview)]

:::image type="content" source="../media/compliance-trial/compliance-portal.png" alt-text="Compliance Manager - dashboard":::

==== Step 2: Configure Compliance Manager to manage your compliance activities

Start working with assessments and taking improvement actions to implement controls and improve your compliance score.

. xref:compliance-manager-assessments.adoc[Choose a pre-built template to create and manage your first assessment].
. xref:compliance-manager-templates.adoc[Understand how to use templates for building assessments].
. xref:compliance-manager-improvement-actions.adoc[Perform implementation and testing work on improvement actions to complete controls in your assessments].
. xref:compliance-score-calculation.adoc[Better understand how different actions impact your compliance score].

____
[!NOTE] Microsoft 365 or Office 365 E1/E3 subscription includes Microsoft Data Protection Baseline template.
Microsoft 365 or Office 365 E5, E5 Compliance includes templates for:

* Microsoft Data Protection Baseline
* European Union GDPR
* ISO/IEC 27001,
* NIST 800-53
____

Compliance Manager includes 300+ regulatory or premium templates that can be purchased as an add-on with xref:compliance-easy-trials-compliance-manager-assessments.adoc[Compliance Manager premium assessments add-on].
With any xref:compliance-manager-templates-list.adoc[premium templates] (included with your subscription or purchased as add-on) you will receive the universal version of those templates, allowing you to manage your compliance with any product or service

==== Step 3: Scaling up: use advanced functionality to meet your custom needs

Custom assessments are helpful for:

* Managing compliance for non-Microsoft 365 products such as third-party apps and services, on-premises applications, and other assets
* Managing your own custom or business-specific compliance controls:
 .. xref:compliance-manager-templates-extend.adoc[Extend a Compliance Manager template by adding your own controls and improvement actions]
 .. xref:compliance-manager-templates-create.adoc[Create your own custom template]
 .. xref:compliance-manager-templates-modify.adoc[Modify an existing template to add or remove controls and actions]
 .. link:compliance-manager-setup.md#set-up-automated-testing[Set up automated testing of improvement actions]
 .. link:compliance-manager-setup.md#reassign-improvement-actions-to-another-user[Reassign improvement actions to another user]

*Organizational Concerns*

=== Information protection

The first organizational concern raised by customers is understanding what, where and how sensitive, business-critical data is being used and how to protect sensitive and confidential data from unauthorized access or leakage.

Get data visibility and protection starting with Information Protection and Data Loss Prevention.

* Detect -- discover sensitive data across your entire digital estate and understand how it's being used.
* Protect -- classify information and apply sensitivity labels with a unified approach.
* Prevent -- prevent accidental, malicious, and unauthorized oversharing of sensitive data.

=== Information Protection and Data Loss Prevention

*Discover, classify and protect your sensitive data*

One of the main concerns for most organizations, regarding compliance regulations, is how to classify their sensitive data, how to protect it, and prevent data loss.
Purview Information Protection and Data Loss Prevention solutions allow customers to discover and classify their sensitive data, to protect their sensitive data using sensitivity labels, and finally to setup data loss prevention policies to prevent unauthorized sharing, use, or transfer of sensitive data through multiple egress points.
The classification, labeling, and DLP capabilities are natively built-in Microsoft 365 workloads such as SharePoint Online, Exchange Online, OneDrive for Business, and Teams.
You can extend these to non-Microsoft workloads.

==== Set up your information protection and data loss prevention trial

Eligible customers can activate default labels and default DLP policies for Information Protection and Data Loss Prevention.
When you enable the default configuration in the trial, it will take about 2 minutes to configure all policies for your tenant and up to 24 hours to see the results of these default policies.

Choosing the default configuration, with 1-click, the following is automatically configured:

* Sensitivity labels and a sensitivity label policy
* Client-side auto-labeling
* Service-side auto-labeling
* Data loss prevention (DLP) policies for Teams and devices

link:mip-easy-trials.md#activate-the-default-labels-and-policies[Activate the default labels and policies].
If necessary, you can edit it manually after the configuration is complete.
If necessary, you can edit it manually after the configuration is complete.

You can follow the actions below or alternatively, use the https://go.microsoft.com/fwlink/?linkid=2197428[Microsoft Purview Information Protection Setup Guide] to set up your Information Protection and Data Loss Protection.

*Actions to try:*

=== Microsoft Purview Information Protection

==== Step 1: Automatically apply sensitivity labels to documents

When you create a sensitivity label, you can automatically assign that label to files and emails when it matches conditions that you specify.

. link:create-sensitivity-labels.md#create-and-configure-sensitivity-labels[Create and configure sensitivity labels]
. link:create-sensitivity-labels.md#publish-sensitivity-labels-by-creating-a-label-policy[Publish sensitivity label policy to all users]
. Create an xref:apply-sensitivity-label-automatically.adoc[auto-labeling policy]
 ** Choose info you want label applied to
 ** Define locations to apply label
 ** Select label to apply
 ** Run policy in simulation mode

:::image type="content" source="../media/compliance-trial/new-policy.png" alt-text="New policy configuration for auto-labeling":::

==== Step 2: Review and turn on auto-labeling policy

Now on the Information protection > Auto-labeling page, you see your auto-labeling policy in the Simulation section.

. Select your policy to see the details of the configuration and status.
When the simulation is complete, select the Items to review tab to see which emails or documents matched the rules that are specified.
. When you're ready to run the policy without simulation, select the Turn on policy option.

=== Microsoft Purview Data Loss Prevention

==== Step 1: Prevent data loss on Microsoft Teams locations

If your organization has data loss prevention (DLP), you can define policies that prevent people from sharing sensitive information in a Microsoft Teams channel or chat session.

. link:dlp-microsoft-teams.md#dlp-licensing-for-microsoft-teams[Learn about DLP Licensing for Microsoft Teams and the scope of DLP protection]
. link:dlp-microsoft-teams.md#add-microsoft-teams-as-a-location-to-existing-dlp-policies[Add Microsoft Teams as a location to existing DLP policies]
. xref:mip-easy-trials.adoc[Configure our default DLP policy for Teams or define a new DLP policy for Microsoft Teams]

==== Step 2: Prevent data loss on devices

Microsoft Purview DLP for endpoints allows you to detect and prevent when sensitive items are used or shared on Windows 10, Windows 11 and macOS devices.

. Prepare your endpoints - make sure that the Windows 10 and macOS devices that you plan on deploying Endpoint DLP link:endpoint-dlp-getting-started.md#skusubscriptions-licensing[meet these requirements].
. link:endpoint-dlp-getting-started.md#windows-10-and-windows-11-onboarding-procedures[Onboard devices into device management] - You must onboard your endpoints before you can detect and protect sensitive items on a device.
Both of these actions are done in the Microsoft Purview compliance portal.
 ** Scenario 1 -- Onboarding devices that have not been onboarded yet.
 ** Scenario 2 - Microsoft Defender for Endpoint is already deployed and there are endpoints reporting in.
All these endpoints will appear in the managed devices list.
. link:mip-easy-trials.md#dlp-for-devices[Configure our default DLP policy for devices or define a new DLP policy for devices].
. xref:dlp-configure-view-alerts-policies.adoc[View Endpoint DLP alerts] in DLP Alerts Management dashboard.
. xref:data-classification-activity-explorer.adoc[View Endpoint DLP data] in activity explorer.

==== Step 3: Expand policies in scope or protection

You have flexibility in how you configure your DLP policies.
You can start with our default DLP policy for Teams and devices and expand those policies to protect additional locations, sensitive information types, or labels.
Note customers can run a DLP policy in test mode to understand or fine tune how the policy is working before it is turned on.
In addition, you can expand upon the policy actions and customize alerting.

. Add locations
. Add sensitive information types or labels to protect
. Add actions
 ** Teams:  i.
link:dlp-microsoft-teams.md#prevent-external-access-to-sensitive-documents[Prevent external access to sensitive documents]  i.
link:dlp-microsoft-teams.md#policy-tips-help-educate-users[Get policy tips to help educate users and instructions for customizing policy tips]
 ** Devices: switch from audit only to block
. xref:dlp-configure-view-alerts-policies.adoc[Configure and view alerts for data loss prevention policies]

=== Microsoft Purview data governance

The second organizational concern customers convey is how to reduce risk and meet regulations by classifying data to keep what they need and delete what they don't need.
Customers want compliant lifecycle management of sensitive data, to meet record keeping obligations, and to reduce the risk from over-retained data.

Microsoft Purview Data Lifecycle Management and Records Management help you to:

* Apply retention and deletion policies to data where users collaborate to manage risk and prevent productivity loss.
* Ensure the correct policies are enforced by auto-classifying content.
* Comply with record keeping obligations with immutability options, defensible disposal, and advanced policy targeting.

=== Microsoft Purview Data Lifecycle Management

==== Govern at scale with automation

Start with the https://go.microsoft.com/fwlink/?linkid=2197335[Data Lifecycle Management Setup Guide].
Additionally, you may want to consider implementing these common scenarios:

. Auto-apply retention or deletion settings to sensitive data
. Auto-apply retention or deletion settings to everything in a SharePoint document library
. Target a retention or deletion policy to only specific users or mailboxes

==== Step 1: Auto-apply retention or deletion settings to sensitive data

Start by managing the lifecycle of sensitive data by managing it automatically using retention and deletion settings.
First, decide on the type of sensitive data that you want to protect.
You may want to use one of our pre-built xref:sensitive-information-type-learn-about.adoc[sensitive information types].
Next, link:retention.md#retention-labels[create a retention label] with your desired retention or deletion settings.
Finally, link:apply-retention-labels-automatically.md#auto-apply-labels-to-content-with-specific-types-of-sensitive-information[automatically apply the retention label] that contains the sensitive information type you selected.

==== Step 2: Auto-apply retention or deletion settings to everything in a SharePoint document library, folder, or document set

You can set a default retention label in SharePoint to automatically apply it to all items within a specific document library, folder, or document set in SharePoint.
This option is useful when users store a specific type of document in one of these locations.

First, identify the content you would like to manage and the location of the content in SharePoint.
Next, link:retention.md#retention-labels[create a retention label] with your desired retention or deletion settings.
Finally, link:create-apply-retention-labels.md#applying-a-default-retention-label-to-all-content-in-a-sharepoint-library-folder-or-document-set[publish the retention to the document library, folder, or document set].

==== Step 3: Dynamically target retention policies with Adaptive Policy Scopes

Many customers want to target a retention policy to specific users or mailboxes.
For example, they may want to apply a longer retention period to the mailboxes of people in leadership roles or apply shorter retention to shared mailboxes.
Adaptive policy scopes allow you to do this by using their AD attributes to target the policy.
If one of the attribute values changes then the retention policy will automatically update its membership.

First, link:retention-settings.md#configuration-information-for-adaptive-scopes[decide what attributes you will use to target] the users or mailboxes that you want to include or exclude from your policy.
Next, link:retention.md#adaptive-or-static-policy-scopes-for-retention[Create an Adaptive Policy Scope and use it with a retention policy].

=== Microsoft Purview Records Management

*Manage high-value items for business, legal, or regulatory record-keeping requirements*

Records Management helps you to comply with more granular retention and deletion requirements.
As an example, you can track your retention schedule or use flexible automation options.
Additionally, you can make content immutable, trigger retention using an event, or require approval before items are disposed.

Here are our most popular records management scenarios:

. Automatically apply a retention label based on SharePoint file metadata
. Conduct a disposition review at the end of a retention period
. Make content immutable to prevent users from editing it

==== Step 1: Automatically apply a retention label based on SharePoint file metadata

Auto-applying labels removes the need for your users to manually perform the labeling activities.
As an example, you can auto-apply retention labels to content that has specific metadata properties in SharePoint.
First, decide the metadata properties you would like to use, the locations where you want to look for matches, and the retention or deletion settings you want to apply.
Next, link:retention.md#retention-labels[create a retention label].
Then, xref:auto-apply-retention-labels-scenario.adoc[follow the steps] to auto-apply the label based on SharePoint metadata.

==== Step 2: Review content to approve before it's permanently deleted

Some organizations have a requirement to review content at the end of its retention period before it is permanently deleted.
Using Records Management, users you specify ("reviewers") can be notified to review the content and approve the permanent disposal action.
Reviewers can also choose to assign a different retention period to the content or postpone deletion.
Learn more here:   Disposition of content.

==== Step 3: Make content immutable to prevent users from editing it

Some content has a lifecycle phase where both the file and the metadata should not be available for editing, often called declaring the content as an immutable record.
Learn how to configure this option in Records Management: xref:declare-records.adoc[Create a retention label that declares content as a record or a regulatory record].

=== Manage insider risks

The third organizational concern we hear is how to protect your data and respond to potential insider data security incident risks, which may include data theft and inappropriate sharing of confidential information across all platforms like email and IM (e.g.
Microsoft Teams).

Using Insider Risk Management and Communication Compliance you can quickly identify and act on insider data security incidents and regulatory requirement risks, empowering you to collaborate with your Security, HR, Legal and other teams, depending on your organization.

* Get rich insights -- identifying hidden risks with customizable ML templates requiring no endpoint agents.
* Investigate -- integrated investigation workflows enable end-to-end collaboration across Security, HR and Legal.
* Know privacy is built-in -- protect user privacy and prevent bias by removing identifiable user details, like name or email, while mitigating organizational risk.

=== Microsoft Purview Insider Risk Management

*Detect and remediate insider risks*

Leverage end-to-end workflows to help you quickly identify, triage, and remediate.
Using logs from Microsoft 365    and Azure services, you can define policies to identify potential data security incidents and take remediation actions such as promoting user education or initiating an investigation.

==== Step 1 (required): Enable permissions for Insider Risk Management

There are four role groups used to configure permissions to manage Insider Risk Management features, which have different roles and level of access.
Setting up permissions to Insider Risk Management is key before proceeding.

link:insider-risk-management-configure.md#add-users-to-an-insider-risk-management-role-group[Add users to an insider risk management role group]

If you are not able to see permissions, please talk to your tenant admin to assign the correct roles.

==== Step 2 (required): Enable the Microsoft 365 audit log

Auditing is enabled for Microsoft 365 organizations by default.
Some organizations may have disabled auditing for specific reasons.
If auditing is disabled for your organization, it might be because another administrator has turned it off.
We recommend confirming that it's OK to turn auditing back on when completing this step.

For step-by-step instructions to turn on auditing, see xref:turn-audit-log-search-on-or-off.adoc[Turn audit log search on or off].
After you turn on auditing, a message is displayed that says the audit log is being prepared and that you can run a search in a couple of hours after the preparation is complete.
You only have to do this action once.
For more information about  using the Microsoft 365 audit log, see xref:search-the-audit-log-in-security-and-compliance.adoc[Search the audit log].

==== Step 3 (recommended): Enable and view Insider Risk Management analytics insights

Analytics within Insider Risk Management enables you to conduct an evaluation of potential insider risks that may lead to a data security incident in your organization without configuring any insider risk policies.
Analytics scan results may take up to 48 hours before insights are available as reports for review.
These assessment results are aggregated and anonymized, and offer organization-wide insights, like the percentage of users performing potential sensitive data exfiltration activities.

To learn more about analytics insights, see link:insider-risk-management-settings.md#analytics[Insider risk management settings: Analytics] and check out the https://www.youtube.com/watch?v=5c0P5MCXNXk[Insider risk management analytics video] to help you understand your insider risk posture and help you take action by setting up appropriate policies to identify risky users.

____
[!NOTE] To enable insider risk analytics, you must be a member of the Insider Risk Management or Insider Risk Management Admin.
____

==== Step 4: Start with Recommended actions

Quickly get started and get the most out of Insider Risk Management capabilities with Recommended actions.
Included on the Overview page, recommended actions will help guide you through the steps to configure and deploy policies and to take investigation actions for user actions that generate alerts from policy matches.

link:insider-risk-management-configure.md#recommended-actions-preview[Select a recommendation from the list] to get started with configuring insider risk management.

:::image type="content" source="../media/compliance-trial/irm-recommended-actions.png" alt-text="Insider Risk Management recommended actions":::

Each recommended action guides you through the required activities for the recommendation, including any requirements, what to expect, and the impact of configuring the feature in your organization.

Note that the recommended steps in the playbook (above) may also be included in the Recommended actions shown in the portal.

Set up recommendations are also available on the Microsoft docs page, via the https://go.microsoft.com/fwlink/?linkid=2197153[Microsoft Purview Insider Risk Management Setup Guide].

To fully leverage the functionality of Insider Risk Management, we recommend setting up policies for your organization to better identify potential risky actions that may lead to a security incident, leveraging templates for Data leaks or Data theft.

=== Microsoft Purview Communication Compliance

*Identify regulatory compliance policy violations*

Microsoft Purview Communication Compliance provides the tools to help organizations detect regulatory compliance violations (e.g.
SEC or FINRA), such as  sensitive or confidential information, harassing or threatening language, and sharing of adult content.
Built with privacy by design, usernames are pseudonymized by default, role-based access controls are built in, investigators are opted in by an admin, and audit logs are in place to ensure user-level privacy.

==== Step 1: Enable permissions for communication compliance

Assign users communication compliance roles to be able to use the product.
The "Communication Compliance" role group gives you all the permissions to use the product.
Learn about other communication compliance role groups here: link:communication-compliance-configure.md#step-1-required-enable-permissions-for-communication-compliance[Get started with communication compliance].

==== Step 2: Enable the audit log

To use this feature, turn on auditing.
When you turn this on actions will be available in the audit log and view in a report.
To learn more, see xref:turn-audit-log-search-on-or-off.adoc[Turn audit log search on or off].

==== Step 3: Review recommended actions insights

Included on the Policies page, recommended actions helps you discover risks you may not be aware of, like inappropriate sharing of sensitive or confidential information that are already occurring in your organization.
This view includes only the aggregate number of matches per classification type, with none of the insights containing any personally identifiable information, and helps you determine the type and scope of communication compliance policies to configure.

==== Step 4: Create a communication compliance policy

Create a communication compliance policy using the existing templates: 1- Sensitive information;
2- Regulatory compliance;
3- Conflict of interest.
Learn more about our out of the box policy templates and how to create a custom policy here: xref:communication-compliance-policies.adoc[Communication compliance policies].

==== Step 5: Investigate and remediate alerts

xref:communication-compliance-investigate-remediate.adoc[Investigate and remediate communication compliance alerts].

==== Step 6: Review reports for insights

xref:communication-compliance-reports-audits.adoc[Review reports for insights on your overall communication compliance posture].

=== Discover & respond

The fourth organizational concern from customers is how to find relevant data when needed for investigations, regulatory requests, or litigations and for meeting regulatory requirements.

With eDiscovery and Audit, you can discover data efficiently.

* Discover and collect data in-place -- collect, filter, and gain data insights faster, with greater visibility.
* Manage workflows -- reduce the friction of identifying and collecting potential sources of relevant information by automatically mapping unique and shared data sources.
* Accelerate the discovery process -- manage the increase of data volume by searching and processing highly relevant content in-place.

=== Microsoft Purview eDiscovery (Premium)

Discover more efficiently with an end-to-end workflow Take advantage of an end-to-end workflow for preserving, collecting, analyzing, and exporting content that's responsive to your organization's internal and external investigations.
Legal teams can also manage the entire legal hold notification process by communicating with custodians involved in a case.

==== Step 1 (required): Permissions

To access eDiscovery (Premium) or be added as a member of an eDiscovery (Premium) case, a user must be assigned the appropriate permissions.

. link:get-started-with-advanced-ediscovery.md#step-2-assign-ediscovery-permissions[Set up eDiscovery (Premium) -- Assign eDiscovery permissions]
. xref:add-or-remove-members-from-a-case-in-advanced-ediscovery.adoc[Add or remove members from a case]

==== Step 2 (required): Create a Case

More organizations use the eDiscovery (Premium) solution in Microsoft 365 for critical eDiscovery processes.
This includes responding to regulatory requests, investigations, and litigation.

. Manage eDiscovery (Premium) -- link:/training/modules/manage-advanced-ediscovery[learn how to configure eDiscovery (Premium), manage cases by using the Security & Compliance Center, manage a workflow in Advanced eDiscovery, and analyze Advanced eDiscovery search results].
. xref:advanced-ediscovery-new-case-format.adoc[Create an eDiscovery case] using eDiscovery Premium's new case format
. xref:close-or-delete-case.adoc[Close or delete a case] - When the legal case or investigation is completed, you can close or delete.
You can also reopen a closed case.

==== Step 3 (optional): Settings

To allow people in your organization start to create and use cases, you must configure global settings that apply to all cases in your organization.
You can manage settings such as attorney-client privilege detection, historical versions and many more.

. link:get-started-with-advanced-ediscovery.md#step-3-configure-global-settings-for-ediscovery-premium[Configure global settings for eDiscovery (Premium)]
. xref:configure-search-and-analytics-settings-in-advanced-ediscovery.adoc[Configure search and analytics settings]
. xref:managing-jobs-ediscovery20.adoc[Manage jobs in eDiscovery (Premium)]

==== Step 4 (optional): Compliance Boundaries

Compliance boundaries create logical boundaries within an organization that control the user content locations (such as mailboxes, OneDrive accounts, and SharePoint sites) that eDiscovery managers can search.
They also control who can access eDiscovery cases used to manage the legal, human resources, or other investigations within your organization.

:::image type="content" source="../media/compliance-trial/compliance-boundaries.png" alt-text="Compliance boundaries consist of search permissions filters that control access to agencies and admin role groups that control access to eDiscovery cases":::

Set up compliance boundaries for eDiscovery investigations:

. link:set-up-compliance-boundaries.md#step-1-identify-a-user-attribute-to-define-your-agencies[Identify a user attribute to define your agencies]
. link:set-up-compliance-boundaries.md#step-2-create-a-role-group-for-each-agency[Create a role group for each agency]
. link:set-up-compliance-boundaries.md#step-3-create-a-search-permissions-filter-to-enforce-the-compliance-boundary[Create a search permissions filter to enforce the compliance boundary]
. link:set-up-compliance-boundaries.md#step-4-create-an-ediscovery-case-for-intra-agency-investigations[Create an eDiscovery case for an intra-agency investigations]

==== Step 5 (optional): eDiscovery Premium's collection tool

Use the link:create-draft-collection.md#create-a-draft-collection[eDiscovery (Premium) collection workflow] to quickly find email in Exchange mailboxes, documents in SharePoint sites and OneDrive locations, and instant messaging conversations in Teams.
Collections in eDiscovery (Premium) help eDiscovery managers quickly scope a search for content across email, documents, Teams reactions, and other content in Microsoft 365.
Collections provide managers with an estimate of the content that may be relevant to the case.

xref:building-search-queries.adoc[Learn more about collection queries and estimates.]

=== Microsoft Purview Audit (Premium)

*Conduct investigations*

Advanced Audit helps organizations to conduct forensic and compliance investigations by increasing audit log retention required to conduct an investigation, providing access to crucial events that help determine scope of compromise, and providing faster access to the Office 365 Management Activity API.

==== Step 1: Apply the E5 license to each user for which you'd like to generate E5 events

Audit (Premium) features such as the ability to log crucial events such as MailItemsAccessed and Send require an appropriate E5 license assigned to users.
Additionally, the Advanced Auditing app/service plan must be enabled for those users.

Set up Audit (Premium) for users - to verify that the Advanced Auditing app is assigned to users, link:set-up-advanced-audit.md#step-1-set-up-audit-premium-for-users[perform the following steps for each user].

. Enable Audit (Premium) events - link:set-up-advanced-audit.md#step-2-enable-audit-premium-events[enable SearchQueryInitiatedExchange and SearchQueryInitiatedSharePoint] to be audited for each user in link:/powershell/exchange/connect-to-exchange-online-powershell[Exchange Online PowerShell].
. Set up audit retention policies - link:set-up-advanced-audit.md#step-3-set-up-audit-retention-policies[create additional audit log retention policies] to meet the requirements of your organization's security operations, IT, and compliance teams.
. Search for Audit (Premium) events - link:set-up-advanced-audit.md#step-4-search-for-audit-premium-events[search for crucial Audit (Premium) events] and other activities when conducting forensic investigations.

==== Step 2: Create new Audit Log policies to specify how long to retain audit logs in your org for activities performed by users and define priority levels for your policies

Audit log retention policies are part of the new Advanced Audit capabilities in Microsoft 365.
An audit log retention policy lets you specify how long to retain audit logs in your organization.

. Before you create an audit log retention policy -- link:audit-log-retention-policies.md#before-you-create-an-audit-log-retention-policy[key things to know] before creating your policy.
. link:audit-log-retention-policies.md#create-an-audit-log-retention-policy[Create an audit log retention policy].
. link:audit-log-retention-policies.md#manage-audit-log-retention-policies-in-the-compliance-portal[Manage audit log retention policies in the Microsoft Purview compliance portal] - Audit log retention policies are listed on the Audit retention policies tab (also called the dashboard).
You can use the dashboard to view, edit, and delete audit retention policies.
. link:audit-log-retention-policies.md#create-and-manage-audit-log-retention-policies-in-powershell[Create and manage audit log retention policies on PowerShell] - You can also use Security & Compliance Center PowerShell to create and manage audit log retention policies.
One reason to use PowerShell is to create a policy for a record type or activity that isn't available in the UI.

=== Additional trials and add-ons

==== Compliance Manager premium assessments

*Assess risks and efficiently respond*:

Help your organization assess risks and efficiently respond to nations, regional and industry requirements governing the collection and use of data.

xref:compliance-easy-trials-compliance-manager-assessments.adoc[More information on the Compliance Manager premium assessments trial].

xref:compliance-easy-trials-compliance-manager-assessment-playbook.adoc[Trial playbook: Microsoft Purview Compliance Manager premium assessments]

==== Microsoft Priva Privacy Risk Management and Microsoft Priva Subject Rights Requests

*Identify & prevent privacy risks*:

Proactively identify and protect against privacy risks such as data hoarding, data transfers, and data oversharing and help your organization automate and manage subject requests at scale.

link:/privacy/solutions/privacymanagement/privacy-management[Learn more about Microsoft Priva].

link:/privacy/solutions/privacymanagement/privacy-management-trial-playbook[Trial playbook: Microsoft Priva]

=== Additional resources

*What's included*: For a full list of Microsoft Purview solutions and features listed by product tier, view the https://go.microsoft.com/fwlink/?linkid=2139145[Feature Matrix].

*Microsoft Security Technical Content Library*: Explore this library to find interactive guides and other learning content relevant to your needs.
link:/security[Visit Library].

*Microsoft Security Resources*: From antimalware to Zero Trust, get all the relevant resources for your organization's security needs.
