= Create assessment templates in Microsoft Purview Compliance Manager
:audience: Admin
:author: chvukosw
:description: Understand how to create templates for assessments in Microsoft Purview Compliance Manager. Create and modify templates using a formatted Excel file.
:f1.keywords: ["NOCSH"]
:manager: laurawi
:ms.author: chvukosw
:ms.collection: ["M365-security-compliance", "m365solution-compliancemanager", "m365initiative-compliance"]
:ms.custom: admindeeplinkMAC
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: article
:search.appverid: ["MOE150", "MET150"]

== Create an assessment template in Microsoft Purview Compliance Manager

To create your own new template for custom assessments in Compliance Manager, you'll use a specially formatted Excel spreadsheet to assemble the necessary control data.
After completing the spreadsheet, you will import it into Compliance Manager.

To learn about formatting your spreadsheet, see xref:compliance-manager-templates-format-excel.adoc[Format assessment template data with Excel].

=== Required roles

Only users who hold a Global Administrator or Compliance Manager Administration role can create and modify templates.
Learn more about link:compliance-manager-setup.md#set-user-permissions-and-assign-roles[roles and permissions].

=== Create new template in Compliance Manager

. Go to your *assessment templates* page in Compliance Manager.
. Select *Create new template*.
A template creation wizard will open.
. Choose the type of template you want to create.
In this case, select *Create a custom template*, then select *Next*.
. At the *Upload file* screen, select *Browse* to find and upload your formatted Excel file containing all the required template data.
. If there are no problems with your file, the name of the file uploaded will be displayed.
Select *Next* to continue.
(If you need to change the file, select *Upload a different file*).
 ** If there's an error with your file, an error message at the top explains what's wrong.
You'll need to fix your file and upload it again.
Errors will result if your spreadsheet is formatted improperly, or if there's invalid information in certain fields.
. The *Review and finish* screen shows the number of improvement actions and controls and the maximum score for the template.
When ready to approve, select *Create template.* (If you need to make changes, select *Back*.)
. The last screen confirms a new template has been created.
Select *Done* to exit the wizard.
. You'll arrive at your new template's details page, where you can link:compliance-manager-assessments.md#create-assessments[create your assessment].
