= Onboard and offboard macOS devices into Microsoft Purview solutions using Microsoft Intune
:audience: ITPro
:author: chrfox
:description: Learn how to onboard and offboard macOS devices into Microsoft Purview solutions using Microsoft Intune
:f1.keywords: NOCSH
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: article
:search.appverid: ["MET150"]

== Onboard and offboard macOS devices into Microsoft Purview solutions using Intune

You can use Intune to onboard macOS devices into Microsoft Purview solutions.

____
[!IMPORTANT] Use this procedure if you *_do not_* have Microsoft Defender for Endpoint (MDE) deployed to your macOS devices
____

*Applies to:*

* xref:./endpoint-dlp-learn-about.adoc[Endpoint data loss prevention (DLP)]
* xref:insider-risk-management.adoc[Insider risk management]

=== Before you begin

* Make sure your link:/mem/intune/fundamentals/deployment-guide-platform-macos[macOS devices are onboarded into Intune] and are enrolled in the link:/mem/intune/user-help/enroll-your-device-in-intune-macos-cp[Company Portal app].
* Make sure you have access to the https://endpoint.microsoft.com/#home[Microsoft Endpoint Manager center].
* This supports three most recent major releases of macOS.
* Create the user groups that you are going to assign the configuration updates to.
* Install the v95+ Edge browser on your macOS devices

=== Onboard macOS devices into Microsoft Purview solutions using Microsoft Intune

Onboarding a macOS device into Compliance solutions is a multi-phase process.

. <<create-system-configuration-profiles,Create system configuration profiles>>
. <<get-the-device-onboarding-package,Get the device onboarding package>>
. <<deploy-the-mobileconfig-and-onboarding-packages,Deploy the mobileconfig and onboarding packages>>
. <<publish-application,Publish application>>
// 1. [Enable system extension](#enable-system-extension)

==== Create system configuration profiles

. You'll need these files for this procedure.

|===
| file needed for | source

| System mobile config file
| https://github.com/microsoft/mdatp-xplat/blob/master/macos/mobileconfig/combined/mdatp-nokext.mobileconfig[mdatp-nokext.mobileconfig] Copy and paste the contents into a text file.
Save the file with the *mobileconfig* extension only, it will not be recognized if it has the .txt extension.

| MDE preferences
| https://github.com/microsoft/mdatp-xplat/blob/master/macos/settings/data_loss_prevention/com.microsoft.wdav.mobileconfig[com.microsoft.wdav.mobileconfig].
Copy and paste the contents into a text file.
Save the file with the *mobileconfig* extension only, it will not be recognized if it has the .txt extension.
|===

==== Get the device onboarding package

. In *Microsoft Purview Compliance center* open *Settings* > *Device Onboarding* and choose *Onboarding*.
. For *Select operating system to start onboarding process* choose *macOS*.
. For *Deployment method* choose *Mobile Device Management/Microsoft Intune*.
. Choose *Download onboarding package*.
. Extract the zip file and open the _Intune_ folder.
This contains the onboarding code in the _DeviceComplianceOnboarding.xml_ file.

////
|accessibility |[accessibility.mobileconfig](https://github.com/microsoft/mdatp-xplat/blob/master/macos/mobileconfig/profiles/accessibility.mobileconfig)|
full disk access     |[fulldisk.mobileconfig](https://github.com/microsoft/mdatp-xplat/blob/master/macos/mobileconfig/profiles/fulldisk.mobileconfig)|
|Network filer| [netfilter.mobileconfig](https://github.com/microsoft/mdatp-xplat/blob/master/macos/mobileconfig/profiles/netfilter.mobileconfig)]
|System extensions |[sysext.mobileconfig](https://github.com/microsoft/mdatp-xplat/blob/master/macos/mobileconfig/profiles/sysext.mobileconfig)
|MDE preference     |[com.microsoft.wdav.mobileconfig](https://github.com/microsoft/mdatp-xplat/blob/master/macos/settings/data_loss_prevention/com.microsoft.wdav.mobileconfig)|
|MAU preference|[com.microsoft.autoupdate2.mobileconfig](https://github.com/microsoft/mdatp-xplat/blob/master/macos/settings/microsoft_auto_update/com.microsoft.autoupdate2.mobileconfig)|
|Installation package     |downloaded from the compliance portal **Installation package**, file name *\*wdav.pkg*\* |

> [!TIP]
> You can download the *.mobileconfig* files individually or in [single combined file](https://github.com/microsoft/mdatp-xplat/blob/master/macos/mobileconfig/combined/mdatp-nokext.mobileconfig) that contains:
> - accessibility.mobileconfig
> - fulldisk.mobileconfig
> - netfilter.mobileconfig
> - system extensions
>
>If any of these individual files is updated, you'd need to download the either the combined file again or the single updated file individually.
////

==== Deploy the mobileconfig and onboarding packages

. Open the *Microsoft Endpoint Manager center* > *Devices* > *Configuration profiles*.
. Choose: *Create profile*
. Choose:
 .. *Platform = macOS*
 .. *Profile type = Templates*
 .. *Template name = Custom*
. Choose *Create*
. Choose a name for the profile, like _SystemMobileConfig_ in this example.
Choose *Next*.
. Choose the *mdatp-nokext.mobileconfig* file that you copied and saved in step 1 as the configuration profile file.
. Choose *Next*
. On the *Assignments* tab add the group you want to deploy these configurations to and choose *Next*.
. Review your settings and choose *Create* to deploy the configuration.
. Repeat steps 2-9 to create profiles for the:
 .. *DeviceComplianceOnboarding.xml* file.
Name it _Purview Device Onboarding Package_
 .. *com.microsoft.wdav.mobileconfig* file.
Name it _Endpoint Device Preferences_
. Open *Devices* > *Configuration profiles*, you should see your created profiles there.
. In the *Configuration profiles* page, choose the profile that you just created, for example _SystemMobileConfig_ and choose *Device status* to see a list of devices and the deployment status of the configuration profile.

==== Publish application

Microsoft Endpoint DLP is installed as a component of Microsoft Defender for Endpoint (MDE) on macOS.
This procedure applies to onboarding devices into Microsoft Purview solutions

. In the https://endpoint.microsoft.com/[Microsoft Endpoint Manager admin center], open *Apps*.
. Select By platform > macOS > Add.
. Choose *App type*=*macOS*, click *Select*.
. Keep default values, click *Next*.
. Add assignments, click *Next*.
. Review and *Create*.
. You can visit *Apps* > *By platform* > *macOS* to see it on the list of all applications.

////
## Offboard macOS devices using Intune PINGING PG FOR THIS PROCEDURE

> [!NOTE]
> Offboarding causes the device to stop sending sensor data to the portal but data from the device, including reference to any alerts it has had will be retained for up to six months.

1. In **Microsoft Endpoint Manager center**, open **Devices** > **Configuration profiles**, you should see your created profiles there.

1. In the **Configuration profiles** page, choose the *wdav.pkg.intunemac* profile.

1. Choose **Device status** to see a list of devices and the deployment status of the configuration profile

1. Open **Properties** and **Assignments**

1. Remove the group from the assignment. This will uninstall the *wdav.pkg.intunemac* package and offboard the macOS device from Compliance solutions.
////
