= Onboard and offboard macOS devices into Compliance solutions using Microsoft Intune for Microsoft Defender for Endpoint customers
:audience: ITPro
:author: chrfox
:description: Learn how to onboard and offboard macOS devices into Microsoft Purview solutions using Microsoft Intune for MDE customers
:f1.keywords: NOCSH
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: article
:search.appverid: ["MET150"]

== Onboard and offboard macOS devices into Compliance solutions using Intune for Microsoft Defender for Endpoint customers

____
[!IMPORTANT] Use this procedure *_if you have_* deployed Microsoft Defender for Endpoint (MDE) to your macOS devices
____

*Applies to:*

* Customers who have MDE deployed to their macOS devices.
* xref:./endpoint-dlp-learn-about.adoc[Endpoint data loss prevention (DLP)]
* xref:insider-risk-management.adoc[Insider risk management]

=== Before you begin

* Make sure your link:/mem/intune/fundamentals/deployment-guide-platform-macos[macOS devices are onboarded into Intune] and enrolled in the link:/mem/intune/user-help/enroll-your-device-in-intune-macos-cp[Company Portal app].
* Make sure you have access to the https://endpoint.microsoft.com/#home[Microsoft Endpoint Manager center]
* This supports macOS version Catalina 10.15 and higher
* Install the v95+ Edge browser on your macOS devices

=== Onboard macOS devices into Microsoft Purview solutions using Microsoft Intune

Use these steps to onboard a macOS device into Compliance solutions if it already has MDE deployed to it.

. You'll need these files for this procedure.

|===
| file needed for | source

| accessibility
| https://github.com/microsoft/mdatp-xplat/blob/master/macos/mobileconfig/profiles/accessibility.mobileconfig[accessibility.mobileconfig]

| full disk access
| https://github.com/microsoft/mdatp-xplat/blob/master/macos/mobileconfig/profiles/fulldisk.mobileconfig[fulldisk.mobileconfig]
|===

____
[!TIP] You can download the _.mobileconfig_ files individually or in https://github.com/microsoft/mdatp-xplat/blob/master/macos/mobileconfig/combined/mdatp-nokext.mobileconfig[single combined file] that contains:

* accessibility.mobileconfig
* fulldisk.mobileconfig

If any of these individual files is updated, you'd need to download the either the combined file again or the single updated file individually.
____

==== Create system configuration profiles

. Open the *Microsoft Endpoint Manager center* > *Devices* > *Configuration profiles*.
. Choose: *Create profile*.
. Choose:
 .. *Platform = macOS*
 .. *Profile type = Templates*
 .. *Template name = Custom*
. Choose *Create*
. Choose a name for the profile, like _AccessibilityformacOS_ in this example.
Choose *Next*.
. Choose the *accessibility.mobileconfig* file that you downloaded in step 1 as the configuration profile file.
. Choose *Next*
. On the *Assignments* tab add the group you want to deploy these configurations to and choose *Next*.
. Review your settings and choose *Create* to deploy the configuration.
. Open *Devices* > *Configuration profiles*, you should see your created profiles there.
. In the *Configuration profiles* page, choose the profile that you just created, in this example _AccessibilityformacOS_ and choose *Device status* to see a list of devices and the deployment status of the configuration profile.

==== Update existing system configuration profiles

. A Full Disk Access configuration profile should have been previously created and deployed for MDE.
See, link:/microsoft-365/security/defender-endpoint/mac-install-with-intune#full-disk-access[Intune-based deployment for Microsoft Defender for Endpoint on Mac].
Endpoint DLP requires an additional Full Disk Access permission for a new application: `com.microsoft.dlp.daemon`.
 .. Update the existing Fullfull Disk Access configuration profile with the fulldisk.mobileconfig file.
. Find the existing MDE Preferences configuration profile.
See, link:/microsoft-365/security/defender-endpoint/mac-preferences#intune-full-profile[Set preferences for Microsoft Defender for Endpoint on macOS]
 .. Add a new key to the profile using these values:

[,xml]
----
<key>features</key>
<dict>
    <key>systemExtensions</key>
    <string>enabled</string>
    <key>dataLossPrevention</key>
    <string>enabled</string>
</dict>
----

Here's an https://github.com/microsoft/mdatp-xplat/blob/master/macos/settings/data_loss_prevention/com.microsoft.wdav.mobileconfig[example mobileconfig]

=== Offboard macOS devices using Intune

____
[!IMPORTANT] Offboarding causes the device to stop sending sensor data to the portal but data from the device, including reference to any alerts it has had will be retained for up to 6 months.
____

. In *Microsoft Endpoint Manager center*, open *Devices* > *Configuration profiles*, you should see your created profiles there.
. In the *Configuration profiles* page, choose the MDE preferences profile.
. Remove these settings:

[,xml]
----
<key>features</key>
<dict>
    <key>systemExtensions</key>
    <string>enabled</string>
    <key>dataLossPrevention</key>
    <string>enabled</string>
</dict>
----

. *Save*.
