= Get started with data loss prevention on-premises scanner
:audience: ITPro
:author: chrfox
:description: Set up data loss prevention on-premises scanner
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.DLPLandingPage"]
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance", "m365solution-mip", "m365initiative-compliance"]
:ms.custom: admindeeplinkCOMPLIANCE
:ms.date:
:ms.localizationpriority: high
:ms.service: O365-seccomp
:ms.topic: how-to
:search.appverid: ["MET150"]

== Get started with the data loss prevention on-premises scanner

This article walks you through the prerequisites and configuration for the Microsoft Purview data loss prevention on-premises scanner.

=== Before you begin

==== SKU/subscriptions licensing

Before you get started with DLP on-premises scanner, you should confirm your https://www.microsoft.com/microsoft-365/compare-microsoft-365-enterprise-plans?rtc=1[Microsoft 365 subscription] and any add-ons.
The admin account that sets up the DLP rules must be assigned one of the following licenses:

* Microsoft 365 E5
* Microsoft 365 E5 Compliance
* Microsoft 365 E5 Information Protection & Governance

For full licensing details see: link:/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance[Microsoft 365 licensing guidance for security & compliance]

____
[!IMPORTANT] All users who contribute to the scanned location either by adding files or consuming files need to have a license, not just the scanner user.
____

==== Permissions

Data from DLP on-premises scanner can be viewed in xref:data-classification-activity-explorer.adoc[Activity explorer].
There are four roles that grant permission to activity explorer, the account you use for accessing the data must be a member of any one of them.

* Global administrator
* Compliance administrator
* Security administrator
* Compliance data administrator

===== Roles and Role Groups in preview

There are roles and role groups in preview that you can test out to fine tune your access controls.

Here's a list of applicable roles that are in preview.
To learn more about them, see link:../security/office-365-security/permissions-in-the-security-and-compliance-center.md#roles-in-the-security--compliance-center[Roles in the Security & Compliance Center]

* Information Protection Admin
* Information Protection Analyst
* Information Protection Investigator
* Information Protection Reader

Here's a list of applicable role groups that are in preview.
To learn more about the, see link:../security/office-365-security/permissions-in-the-security-and-compliance-center.md#role-groups-in-the-security--compliance-center[Role groups in the Security & Compliance Center]

* Information Protection
* Information Protection Admins
* Information Protection Analysts
* Information Protection Investigators
* Information Protection Readers

==== DLP on-premises scanner prerequisites

* The Azure Information Protection (AIP) scanner implements DLP policy matching and policy enforcement.
The scanner is installed as part of the AIP client so your installation must meet all the prerequisites  for AIP, the AIP client, and the AIP unified labeling scanner.
* Deploy the AIP  client and scanner.
For more information link:/azure/information-protection/rms-client/install-unifiedlabelingclient-app[Install the AIP unified labeling client] and [], see link:/azure/information-protection/deploy-aip-scanner-configure-install[Configuring and installing the Azure Information Protection unified labeling scanner].
* There must be at least one label and policy published in the tenant, even if all your detection rules are based on sensitive information types only.

=== Deploy the DLP on-premises scanner

. Follow the procedures in link:/azure/information-protection/rms-client/install-unifiedlabelingclient-app[Install the AIP unified labeling client].
. Follow the procedures in link:/azure/information-protection/deploy-aip-scanner-configure-install[Configuring and installing the Azure Information Protection unified labeling scanner] to complete the scanner installation.
 .. Network discovery jobs configuration is an optional step.
You can skip it and define specific repositories to be scanned in your content scan job.
 .. You must create content scan job and specify the repositories that host files that need to be evaluated by the DLP engine.
 .. Enable DLP rules in the created Content scan job, and set the *Enforce* option to *Off*, unless you want to proceed directly to the DLP enforcement stage.
. Verify that you content scan job is assigned to the right cluster.
If you still did not create a content scan job create a new one and assign it to the cluster that contains the scanner nodes.
. Connect to the https://portal.azure.com/#blade/Microsoft_Azure_InformationProtection/DataClassGroupEditBlade/scannerProfilesBlade[Azure Information Protection extension in Azure portal] and add your repositories to the content scan job that will perform the scan.
. Do one of the following to run your scan:
 .. set the scanner schedule
 .. use the manual *Scan Now* option in the portal
 .. or run *Start-AIPScan* PowerShell cmdlet

+
____
[!IMPORTANT] Remember that the scanner runs a delta scan of the repository by default and the files that were already scanned in the previous scan cycle will be skipped unless the file was changed or you initiated a full rescan.
Full rescan can be initiated by using *Rescan all files* option in the UI or by running *Start-AIPScan-Reset*.
____
. Open the https://compliance.microsoft.com/datalossprevention?viewid=policies[Data loss prevention page] in the Microsoft Purview compliance portal.
. Choose *Create policy* and create a test DLP policy.
See xref:create-a-dlp-policy-from-a-template.adoc[Create a DLP policy from a template] if you need help creating a policy.
Be sure to run it in test until you are comfortable with this feature.
Use these parameters for your policy:
 .. Scope the DLP on-premises scanner rule to specific locations if needed.
If you scope *locations* to *All*, all files scanned by the scanner will be subject to the DLP rule matching and enforcement.
 .. When specifying the locations, you can use either exclusion or inclusion list.
You can either define that the rule is relevant only to paths matching one of the patterns listed in inclusion list or, all files, except the files matching the pattern listed in inclusion list.
No local paths are supported.
Here are some examples of valid paths:
  *** \\server\share
  *** \\server\share\folder1\subfolderabc
  *** *\folder1
  *** *secret*.docx
  *** *secret*.*
  *** https:// sp2010.local/sites/HR
  *** https://*/HR
 .. Here are some examples of unacceptable values use:
  *** *
  *** *\a
  *** Aaa
  *** c:\
  *** C:\test

____
[!IMPORTANT] The exclusion list takes precedence over the inclusions list.
____

==== Viewing DLP on-premises scanner alerts in DLP Alerts Management dashboard

. Open the https://compliance.microsoft.com/datalossprevention?viewid=policies[Data loss prevention page] in the Microsoft Purview compliance portal and select *Alerts*.
. Refer to the procedures in xref:dlp-configure-view-alerts-policies.adoc[How to configure and view alerts for your DLP policies] to view alerts for your on-premises DLP policies.

==== Viewing DLP on-premises scanner in activity explorer and audit log

____
[!NOTE] The on-premises scanner requires that auditing be enabled.
In Microsoft 365 auditing is enabled by default.
____

. Open the https://compliance.microsoft.com/dataclassification?viewid=overview[Data classification page] for your domain in the Microsoft Purview compliance portal and select Activity explorer.
. Refer to the procedures in xref:data-classification-activity-explorer.adoc[Get started with Activity explorer] to access and filter all the data for your on-premises scanner locations.
. Open the https://security.microsoft.com/auditlogsearch[Audit log in the Compliance center].
The DLP rule matches are available in Audit log UI or accessible by link:/powershell/module/exchange/search-unifiedauditlog[Search-UnifiedAuditLog] PowerShell

=== Next steps

Now that you have deployed a test policy for DLP on-premises locations and can view the activity data in Activity explorer, you are ready to move on to your next step where you create DLP policies that protect your sensitive items.

* xref:dlp-on-premises-scanner-use.adoc[Using DLP on-premises]

=== See also

* xref:dlp-on-premises-scanner-learn.adoc[Learn about DLP on-premises scanner]
* xref:dlp-on-premises-scanner-use.adoc[Use DLP on-premises scanner]
* xref:dlp-learn-about-dlp.adoc[Learn about data loss prevention]
* xref:create-test-tune-dlp-policy.adoc[Create, test, and tune a DLP policy]
* xref:data-classification-activity-explorer.adoc[Get started with Activity explorer]
* https://www.microsoft.com/microsoft-365/compare-microsoft-365-enterprise-plans?rtc=1[Microsoft 365 subscription]
