= Export case data in eDiscovery (Premium)
:audience: Admin
:author: robmazz
:description: Learn how to export or download content from a review set for presentations or external reviews in an eDiscovery (Premium) case.
:f1.keywords: ["NOCSH"]
:manager: laurawi
:ms.author: robmazz
:ms.collection: ["tier1", "M365-security-compliance", "ediscovery"]
:ms.custom: seo-marvel-mar2020
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: article
:search.appverid: ["MOE150", "MET150"]

== Export case data in eDiscovery (Premium)

There are three ways to export data from a review set:

*Download:* Download (by using a browser) a small set of native files.
This is the quickest way to export a small set of data.
This method preserves the native file names.
For more information, see xref:download-documents-from-review-set.adoc[Download documents from a review set].

*Export:* Customize what data is exported.
This includes exporting file metadata, native files, text files, and redacted documents that have been saved to a PDF file.
Once the exported data is prepared, you can download the data from the *Export* tab to a local computer.
For more information, see xref:export-documents-from-review-set.adoc[Export documents from a review set]

*Add to another review set:* Copy data from one review set to a different review set.
For more information, see xref:add-data-to-review-set-from-another-review-set.adoc[Add data from one review set to another review set].

____
[!NOTE] In Microsoft 365, data is hashed and those hashes are provided in the output file for verification purposes.
This is supplemented by audit logs and reporting functionality, such as collection statistics, load set reports, and export reports (including the export load file).
____
