= Manage hold notifications
:audience: Admin
:author: robmazz
:description: Use the communications workflow in eDiscovery (Premium) to track the status of your legal hold notifications and if necessary update and resend them.
:experimental:
:f1.keywords: ["NOCSH"]
:manager: laurawi
:ms.author: robmazz
:ms.collection: ["tier1", "M365-security-compliance", "ediscovery"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: article
:search.appverid: ["MOE150", "MET150"]

== Manage hold notifications

After you have initiated your legal hold notification workflow, you can use the communications workflow in Microsoft Purview eDiscovery (Premium) to track the status of your communications.
The Communications tab contains a list of all notifications within your eDiscovery (Premium) case.
You can see details such as the number of custodians that have been assigned or have acknowledged the notice.

=== Monitor acknowledgments

After you select a communication from the *Communications* tab, you can view a list of custodians that have acknowledged a hold notice.

. In the compliance center, go to menu:eDiscovery[eDiscovery (Premium)].
. Select a case and then click the *Communications* tab.
. Select a communication to display the *Custodian communication* flyout page.

A list of custodians associated with the selected communication is displayed on the communication flyout page.
This page also displays insights and about how many acknowledgments were received and how many are outstanding.
The page also shows which custodians have sent an acknowledgment that they received the hold notification.

=== Re-send a hold notice

Occasionally, custodians lose track of email messages in their day-to-day work.
Or for a long-running litigation case, a custodian may contact you or others and request that you re-send a notice.
As you manage the communications workflow for legal hold notices, you may need to re-send a notice to bring it back to the "top of a user's mailbox".

To re-send a hold notice to a custodian:

. In eDiscovery (Premium), select a case and then click the *Communications* tab.
. Select a communication to display the *Custodian communication* flyout page.
. Click menu:More[Re-send hold notice].
. On the *Re-send hold notice* flyout page, select the custodians that you what to re-send the notice and type an optional reason.
. Click *Re-send* to send the notice to the selected custodians.

If a custodian hasn't acknowledged the hold notification, the reminder and escalation workflow is restarted.
If a custodian has acknowledged the hold notice, the custodian will receive a copy of the original hold notice.

____
[!NOTE] You can only resend a legal hold notification to custodians that are assigned to the communication.
____

=== Update preservation requirements

As the case progresses, custodians may be required to preserve additional or less data than was previously instructed.
In eDiscovery terms, you need to re-issue the hold notice with updated content.

To update the contents of the initial hold notice:

. In eDiscovery (Premium), select a case and then click the *Communications* tab.
. Select the hold notice that you want to update and click *Edit* on the *Custodian communication* flyout page.
. In the *Edit Communication* wizard, click *Define Portal Content* in the left pane of the wizard, and update the contents of the notice.
. Click *Save*.

The re-issuance notice will be sent to all the custodians assigned to the legal hold notification.
In addition, if the Reminder or Escalation notice is enabled, then the workflows for those types of notices will restart.

=== Update legal hold notifications and settings

When you update the content or settings of the Issuance, Release, Reissue, Reminder, or Escalation notice, these changes will apply to all future communications generated by the workflow.

=== More information

* xref:add-custodians-to-case.adoc[Add custodians to a case]
* xref:create-hold-notification.adoc[Create a legal hold notice]
* xref:acknowledge-hold-notification.adoc[Acknowledge a hold notification]
