= Encryption in Azure
:audience: ITPro
:author: kccross
:description: Learn about encryption available in Azure, such as Azure Disk Encryption
:f1.keywords: ["NOCSH"]
:manager: laurawi
:ms.author: krowley
:ms.collection: ["Strat_O365_Enterprise", "M365-security-compliance", "Strat_O365_Enterprise"]
:ms.custom: seo-marvel-apr2020
:ms.localizationpriority:
:ms.service: O365-seccomp
:ms.topic: article
:search.appverid: ["MET150"]

== Encryption in Azure

Technological safeguards in Azure, such as encrypted communications and operational processes, help keep your data secure.
You also have the flexibility to implement additional encryption features and manage your own cryptographic keys.
Regardless of customer configuration, Microsoft applies encryption to protect customer data in Azure.
Microsoft also enables you to control your data hosted in Azure through a range of advanced technologies to encrypt, control, and manage cryptographic keys, and control and audit access to data.
In addition, Azure Storage provides a comprehensive set of security capabilities which together enable developers to build secure applications.

Azure offers many mechanisms for protecting data as it moves from one location to another.
Microsoft uses TLS to protect data when it's traveling between the cloud services and customers.
Microsoft's data centers negotiate a TLS connection with client systems that connect to Azure services.
Perfect Forward Secrecy (PFS) protects connections between customers' client systems and Microsoft's cloud services by unique keys.
Connections also use RSA-based 2,048-bit encryption key lengths.
This combination makes it difficult for someone to intercept and access data that is in-transit.

Data can be secured in transit between an application and Azure by using link:/azure/storage/storage-client-side-encryption[client-side encryption], HTTPS, or SMB 3.0.
You can enable encryption for traffic between your own virtual machines (VMs) and your users.
With https://azure.microsoft.com/services/virtual-network/[Azure Virtual Networks], you can use the industry-standard IPsec protocol to encrypt traffic between your corporate VPN gateway and Azure as well as between the VMs located on your Virtual Network.

For data at rest, Azure offers many encryption options, such as support for AES-256, giving you the flexibility to choose the data storage scenario that best meets your needs.
Data can be automatically encrypted when written to Azure Storage using link:/azure/storage/storage-service-encryption[Storage Service Encryption], and operating system and data disks used by VMs can be encrypted.
For more information, see link:/azure/virtual-machines/security-recommendations[Security recommendations for Windows virtual machines in Azure].
In addition, delegated access to data objects in Azure Storage can be granted using link:/azure/storage/storage-dotnet-shared-access-signature-part-1[Shared Access Signatures].
Azure also provides encryption for data at rest using link:/sql/relational-databases/security/encryption/transparent-data-encryption-azure-sql[Transparent Data Encryption for Azure SQL Database and Data Warehouse].

For more information about encryption in Azure, see link:/azure/security/security-azure-encryption-overview[Azure encryption overview] and link:/azure/security/azure-security-encryption-atrest[Azure Data Encryption-at-Rest].

=== Azure Disk Encryption

Azure Disk Encryption enables you to encrypt your Windows and Linux Infrastructure as a Service (IaaS) VM disks.
Azure Disk Encryption leverages the BitLocker feature of Windows and the DM-Crypt feature of Linux to provide volume-level encryption for the operating system and the data disks.
It also ensures that all data on the VM disks are encrypted at rest in your Azure storage.
Azure Disk Encryption is integrated with Azure Key Vault to help you control, manage, and audit the use of the encryption keys and secrets.

For more information, see link:/azure/virtual-machines/windows/security-recommendations[Security recommendations for Windows virtual machines in Azure].

=== Azure Storage Service Encryption

With link:/azure/storage/storage-service-encryption[Azure Storage Service Encryption], Azure Storage automatically encrypts data prior to persisting it to storage and decrypts data prior to retrieval.
The encryption, decryption, and key management processes are totally transparent to users.
Azure Storage Service Encryption can be used for https://azure.microsoft.com/services/storage/blobs/[Azure Blob Storage] and https://azure.microsoft.com/services/storage/files/[Azure Files].
You can also use Microsoft-managed encryption keys with Azure Storage Service Encryption, or you can use your own encryption keys.
(For information on using your own keys, see link:/azure/storage/common/storage-service-encryption-customer-managed-keys[Storage Service Encryption using customer managed keys in Azure Key Vault].
For information about using Microsoft-managed keys, see link:/azure/storage/storage-service-encryption[Storage Service Encryption for Data at Rest].) In addition, you can automate the use of encryption.
For example, you can programmatically enable or disable Storage Service Encryption on a storage account using the link:/rest/api/storagerp/[Azure Storage Resource Provider REST API], the link:/dotnet/api/overview/azure/storage[Storage Resource Provider Client Library for .NET], link:/powershell/azureps-cmdlets-docs[Azure PowerShell], or the link:/azure/storage/storage-azure-cli[Azure CLI].

Some Microsoft 365 services use Azure for storing data.
For example, SharePoint Online and OneDrive for Business store data in Azure Blob storage, and Microsoft Teams stores data for its chat service in tables, blobs, and queues.
In addition, the Compliance Manager feature in the Microsoft Purview compliance portal stores customer-entered data which is stored in encrypted form in link:/azure/cosmos-db/database-encryption-at-rest[Azure Cosmos DB], a Platform as a Service (PaaS), globally-distributed, multi-model database.
Azure Storage Service Encryption encrypts data stored in Azure Blob storage and in tables, and Azure Disk Encryption encrypts data in queues, as well as Windows and IaaS virtual machine disks to provide volume encryption for the operating system and the data disk.
The solution ensures that all data on the virtual machine disks are encrypted at rest in your Azure storage.
link:/azure/cosmos-db/database-encryption-at-rest[Encryption at rest in Azure Cosmos DB] is implemented by using several security technologies, including secure key storage systems, encrypted networks, and cryptographic APIs.

=== Azure Key Vault

Secure key management is not just core to encryption best practices;
it's also essential for protecting data in the cloud.
link:/azure/key-vault/key-vault-whatis[Azure Key Vault] enables you to encrypt keys and small secrets like passwords that use keys stored in hardware security modules (HSMs).
Azure Key Vault is Microsoft's recommended solution for managing and controlling access to encryption keys used by cloud services.
Permissions to access keys can be assigned to services or to users with Azure Active Directory accounts.
Azure Key Vault relieves organizations of the need to configure, patch, and maintain HSMs and key management software.
With Azure Key Vault, Microsoft never sees your keys and applications don't have direct access to them;
you maintain control.
You can also import or generate keys in HSMs.
Organizations that have a subscription that includes Azure Information Protection can configure their Azure Information Protection tenant to use a customer-managed key link:/information-protection/plan-design/byok-price-restrictions[Bring Your Own Key] (BYOK)) and link:/information-protection/deploy-use/log-analyze-usage[log its usage].
