= Set an expiration date for email encrypted by Microsoft Purview Advanced Message Encryption
:audience: Admin
:author: kccross
:description: Use Microsoft Purview Advanced Message Encryption to extend your email security by setting an expiration date on emails through a custom branded template.
:f1.keywords: ["NOCSH"]
:manager: laurawi
:ms.author: krowley
:ms.collection: ["Strat_O365_IP", "M365-security-compliance"]
:ms.custom: seo-marvel-apr2020
:ms.date: 10/8/2019
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: conceptual
:search.appverid: ["MET150"]

== Set an expiration date for email encrypted by Microsoft Purview Advanced Message Encryption

Microsoft Purview Advanced Message Encryption is included in https://www.microsoft.com/microsoft-365/enterprise/home[Microsoft 365 Enterprise E5], Office 365 E5, Microsoft 365 E5 (Nonprofit Staff Pricing), Office 365 Enterprise E5 (Nonprofit Staff Pricing), and Office 365 Education A5.
Microsoft 365 E5 Compliance SKU add-on for Microsoft 365 E3, Microsoft 365 E3 (Nonprofit Staff Pricing), or the Office 365 Advanced Compliance SKU add-on for Microsoft 365 E3, Microsoft 365 E3 (Nonprofit Staff Pricing), or Office 365 SKUs.

If your organization has a subscription that does not include Microsoft Purview Advanced Message Encryption, you can purchase it with the Microsoft 365 E5 Compliance SKU add-on for Microsoft 365 E3, Microsoft 365 E3 (Nonprofit Staff Pricing), or the Office 365 Advanced Compliance SKU add-on for Microsoft 365 E3, Microsoft 365 E3 (Nonprofit Staff Pricing), or Office 365 SKUs.

You can use message expiration on emails that your users send to external recipients who use the OME Portal to access encrypted emails.
You force recipients to use the OME portal to view and reply to encrypted emails sent by your organization by using a custom branded template that specifies an expiration date in PowerShell.

As an Office 365 global administrator, when you apply your company brand to customize the look of your organization's email messages, you can also specify an expiration for these email messages.
With Microsoft Purview Advanced Message Encryption, you can create multiple templates for encrypted emails that originate from your organization.
Using a template, you can control how long recipients have access to mail sent by your users.

When an end user receives mail that has an expiration date set, the user sees the expiration date in the wrapper email.
If a user tries to open an expired mail, an error appears in the OME portal.

You can only set expiration dates for emails to external recipients.

With Microsoft Purview Advanced Message Encryption, anytime you apply custom branding, the Office 365 applies the wrapper to email that fits the mail flow rule to which you apply the template.
In addition, you can only use expiration if you use custom branding.

=== Create a custom branding template to force mail expiration by using PowerShell

. link:/powershell/exchange/connect-to-exchange-online-powershell[Connect to Exchange Online PowerShell] with an account that has global administrator permissions in your organization.
. Run the New-OMEConfiguration cmdlet.
+
[,powershell]
----
 New-OMEConfiguration -Identity "Expire in 7 days" -ExternalMailExpiryInDays 7
----

Where:

* `Identity` is the name of the custom template.
* `ExternalMailExpiryInDays` identifies the number of days that recipients can keep mail before it expires.
You can use any value between 1--730 days.

=== More information about Microsoft Purview Advanced Message Encryption

* xref:ome-advanced-message-encryption.adoc[Advanced Message Encryption]
* xref:revoke-ome-encrypted-mail.adoc[Revoke email encrypted by Microsoft Purview Advanced Message Encryption]
* link:/office365/servicedescriptions/exchange-online-service-description/message-policy-and-compliance[Message policy and compliance service description]
