= Work with processing errors in eDiscovery (Premium)
:audience: Admin
:author: robmazz
:description: Overview about processing various forms of data in eDiscovery (Premium).
:f1.keywords: ["NOCSH"]
:manager: laurawi
:ms.author: robmazz
:ms.collection: ["tier1", "M365-security-compliance", "ediscovery"]
:ms.custom: ["seo-marvel-apr2020"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: overview
:search.appverid: ["MOE150", "MET150"]

== Work with processing errors in eDiscovery (Premium)

_Processing_ is the process of file identification, expansion of embedded documents and attachments, text extraction, and Optical Character Recognition (OCR) of image files and the subsequent indexing of that content.

When you add custodians and non-custodian data sources to a case on the *Sources* tab, all partially indexed items from Microsoft 365 are processed to make them fully searchable.
Likewise, when content is added to a review set from both Microsoft 365 and non-Microsoft 365 data sources, this content is also processed.

The *Processing* tab in eDiscovery (Premium) provides insight into the status of advanced indexing for different processing scenarios.

For more information, see the following articles:

* xref:indexing-custodian-data.adoc[Advanced indexing of custodian data]
* xref:error-remediation-when-processing-data-in-advanced-ediscovery.adoc[Error remediation when processing data]
* xref:single-item-error-remediation.adoc[Single item error remediation]
