= Protect user and device access
:audience: Admin
:author: brendacarter
:description: Learn how to protect user and device access to Microsoft 365 data and services and defend against data loss.
:f1.keywords: ["NOCSH"]
:manager: laurawi
:ms.assetid: a6ef28a4-2447-4b43-aae2-f5af6d53c68e
:ms.author: bcarter
:ms.custom: seo-marvel-apr2020
:ms.date: 4/17/2018
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: landing-page
:search.appverid: ["MOE150", "MET150"]

== Protect user and device access

Protecting access to your Microsoft 365 data and services is crucial to defending against cyberattacks and guarding against data loss.
The same protections can be applied to other SaaS applications in your environment and even to on-premises applications published with Azure Active Directory Application Proxy.

=== Step 1: Review recommendations

Recommended capabilities for protecting identities and devices that access Office 365, other SaaS services, and on-premises applications published with Azure AD Application Proxy.

[cols=3*]
|===
| https://go.microsoft.com/fwlink/p/?linkid=841656[PDF]
| https://go.microsoft.com/fwlink/p/?linkid=841657[Visio]
| https://www.microsoft.com/download/details.aspx?id=55032[More languages]
|===

=== Step 2: Protect administrator accounts and access

The administrative accounts you use to administer your Microsoft 365 environment include elevated privileges.
These are valuable targets for hackers and cyberattackers.

Begin by using administrator accounts only for administration.
Admins should have a separate user account for regular, non-administrative use and only use their administrative account when necessary to complete a task associated with their job function.

Protect your administrator accounts with multi-factor authentication and conditional access.
For more information, see link:../security/office-365-security/identity-access-prerequisites.md#protecting-administrator-accounts[Protecting administrator accounts].

Next, configure Microsoft Purview Privileged Access Management.
Privileged access management allows granular access control over privileged admin tasks in Office 365.
It can help protect your organization from breaches that may use existing privileged admin accounts with standing access to sensitive data or access to critical configuration settings.

* xref:privileged-access-management.adoc[Overview of privileged access management]
* xref:privileged-access-management-configuration.adoc[Configure privileged access management]

Another top recommendation is to use workstations especially configured for administrative work.
These are dedicated devices that are only used for administrative tasks.
See link:/windows-server/identity/securing-privileged-access/securing-privileged-access[Securing privileged access].

Finally, you can mitigate the impact of inadvertent lack of administrative access by creating two or more emergency access accounts in your tenant.
See link:/azure/active-directory/users-groups-roles/directory-emergency-access[Manage emergency access accounts in Azure AD].

=== Step 3: Configure recommended identity and device access policies

Multi-factor authentication (MFA) and conditional access policies are powerful tools for mitigating against compromised accounts and unauthorized access.
We recommend implementing a set of policies that have been tested together.
For more information, including deployment steps, see xref:../security/office-365-security/microsoft-365-policies-configurations.adoc[Identity and device access configurations].

These policies implement the following capabilities:

* Multi-factor authentication
* Conditional access
* Intune app protection (app and data protection for devices)
* Intune device compliance
* Azure AD Identity Protection

Implementing Intune device compliance requires device enrollment.
Managing devices allows you to ensure that they are healthy and compliant before allowing them access to resources in your environment.
See link:/mem/intune/user-help/enroll-windows-10-device[Enroll devices for management in Intune]

=== Step 4: Configure SharePoint device access policies

Microsoft recommends you protect content in SharePoint sites with sensitive and highly regulated content with device access controls.
For more information, see xref:../security/office-365-security/sharepoint-file-access-policies.adoc[Policy recommendations for securing SharePoint sites and files].
