= Records management for documents and emails in Microsoft 365
:audience: Admin
:author: cabailey
:description: Learn how Microsoft Purview Records Management supports high-value items for business, legal, or regulatory record-keeping requirements.
:f1.keywords: ["NOCSH"]
:manager: laurawi
:ms.author: cabailey
:ms.collection: ["M365-security-compliance", "tier1", "highpri"]
:ms.custom: ["admindeeplinkCOMPLIANCE", "seo-marvel-apr2020", "seo-marvel-jun2020"]
:ms.date:
:ms.localizationpriority: high
:ms.service: O365-seccomp
:ms.topic: conceptual
:search.appverid: ["MOE150", "MET150"]

== Learn about records management

____
_link:/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance[Microsoft 365 licensing guidance for security & compliance]_
____

A records management system, also known as records and information management, is a solution for organizations to manage regulatory, legal, and business-critical records.
Records management for Microsoft Purview helps you achieve your organization's legal obligations, provides the ability to demonstrate compliance with regulations, and increases efficiency with regular disposition of items that are no longer required to be retained, no longer of value, or no longer required for business purposes.

____
[!TIP] _Did you know you can try the premium versions of all nine Microsoft Purview solutions for free?_ Use the 90-day Purview solutions trial to explore how robust Purview capabilities can help your organization meet its compliance needs.
Microsoft 365 E3 and Office 365 E3 customers can start now at the https://compliance.microsoft.com/trialHorizontalHub?sku=ComplianceE5&ref=DocsRef[Microsoft Purview compliance portal trials hub].
Learn details about xref:compliance-easy-trials.adoc[who can sign up and trial terms].
____

Use the following capabilities to support your records management solution for Microsoft 365 data:

* *Label content as a record*.
Create and configure retention labels to mark content as a <<records,record>> that can then be applied by users or automatically applied by identifying sensitive information, keywords, or content types.
* *Migrate and manage your retention requirements with file plan*.
By using a xref:file-plan-manager.adoc[file plan], you can bring in an existing retention plan to Microsoft 365, or build a new one for enhanced management capabilities.
* *Configure retention and deletion settings with retention labels*.
Configure link:retention.md#retention-labels[retention labels] with the retention periods and actions based on various factors that include the date last modified or created.
* *Start different retention periods when an event occurs* with xref:event-driven-retention.adoc[event-based retention].
* *Review and validate disposition* with link:disposition.md#disposition-reviews[disposition reviews] and proof of link:disposition.md#disposition-of-records[records deletion].
* *Export information about all disposed items* with the link:disposition.md#filter-and-export-the-views[export option].
* *Set specific permissions* for records manager functions in your organization to xref:../security/office-365-security/permissions-in-the-security-and-compliance-center.adoc[have the right access].

Using these capabilities, you can incorporate your organization's retention schedules and requirements into a records management solution that manages retention, records declaration, and disposition, to support the full lifecycle of your content.

In addition to the online documentation, you might find it useful to download a https://aka.ms/MIPC/Blog-RecordsManagementWebinar[deck with FAQs] from a records management webinar.
The recording of the actual webinar is no longer available.

=== Records

When content is declared a record:

* Restrictions are placed on the items in terms of what <<compare-restrictions-for-what-actions-are-allowed-or-blocked,actions are allowed or blocked>>.
* Additional activities about the item are logged.
* You have proof of disposition when the items are deleted at the end of their retention period.

You use link:retention.md#retention-labels[retention labels] to mark content as a *record*, or a *regulatory record*.
The difference between these two are explained in the next section.
You can either publish those labels so that users and administrators can manually apply them to content, or auto-apply those labels to content that you want to mark as a record or a regulatory record.

By using retention labels to declare records, you can implement a single and consistent strategy for managing records across your Microsoft 365 environment.

==== Compare restrictions for what actions are allowed or blocked

Use the following table to identify what restrictions are placed on content as a result of applying a standard retention label, and retention labels that mark content as a record or regulatory record.

A standard retention label has retention settings and actions but doesn't mark content as a record or a regulatory record.

____
[!NOTE] For completeness, the table includes columns for a locked and unlocked record, which is applicable to SharePoint and OneDrive, but not Exchange.
The ability to lock and unlock a record uses xref:record-versioning.adoc[record versioning] that isn't supported for Exchange items.
So for all Exchange items that are marked as a record, the behavior maps to the *Record - locked* column, and the *Record - unlocked column* is not relevant.
____

|===
| Action | Retention label | Record - locked | Record - unlocked | Regulatory record

| Edit contents
| Allowed
| *Blocked*
| Allowed
| *Blocked*

| Edit properties, including rename
| Allowed
| Allowed ^1^
| Allowed
| *Blocked*

| Delete
| Allowed ^2^
| *Blocked*
| *Blocked*
| *Blocked*

| Copy
| Allowed
| Allowed
| Allowed
| Allowed

| Move within container ^3^
| Allowed
| Allowed
| Allowed
| Allowed

| Move across containers ^3^
| Allowed
| Allowed if never unlocked
| *Blocked*
| *Blocked*

| Open/Read
| Allowed
| Allowed
| Allowed
| Allowed

| Change label
| Allowed
| Allowed - container admin only
| *Blocked*
| *Blocked*

| Remove label
| Allowed
| Allowed - container admin only
| *Blocked*
| *Blocked*
|===

Footnotes:

^1^ Editing properties for a locked record is allowed by default but can be blocked by a tenant setting in the https://compliance.microsoft.com/[Microsoft Purview compliance portal] > *Records management* > *Records management settings* > *Retention labels* > *Allow editing of record properties*.

^2^ Deleting labeled items in SharePoint and OneDrive can be blocked as a tenant setting in the https://compliance.microsoft.com/[Microsoft Purview compliance portal] > *Records management* > *Records management settings* > *Retention labels* > *Deletion of items*.

When you apply a retention label to a list item that has a document attachment, that document doesn't inherit the retention settings and can be deleted from the list item.
In comparison, if that list item was declared a record with a retention label, the document attachment would inherit the retention settings and couldn't be deleted.

^3^ Containers include SharePoint document libraries, OneDrive accounts, and Exchange mailboxes.

____
[!IMPORTANT] The most important difference for a regulatory record is that after it is applied to content, nobody, not even a global administrator, can remove the label.

Retention labels configured for regulatory records also have the following admin restrictions:

* The retention period can't be made shorter after the label is saved, only extended.
* These labels aren't supported by auto-labeling policies, and must be applied by using xref:create-apply-retention-labels.adoc[retention label policies].

In addition, a regulatory label can't be applied to a document that's checked out in SharePoint.

Because of the restrictions and irreversible actions, make sure you really do need to use regulatory records before you select this option for your retention labels.
To help prevent accidental configuration, this option is not available by default but must first be enabled by using PowerShell.
Instructions are included in xref:declare-records.adoc[Declare records by using retention labels].
____

=== Validating migrated records

If you're migrating records to SharePoint or OneDrive, you might need to validate these records haven't been altered and retain their immutability status.
For example, you're using a migration solution and need to meet the chain of custody requirements for your records.
Typical file properties and methods often used for this type of validation, such as file size or file hash, might not be sufficient because SharePoint automatically updates the metadata for a file when it's uploaded.

Instead, to validate your migrated records, you can use the value of the `vti_writevalidationtoken` property, which is a base64-encoded XOR hash of the file before it is modified by SharePoint.
Use the following steps:

. Generate the XOR hash of the original file by using the QuickXorHash algorithm.
For more information, see the link:/onedrive/developer/code-snippets/quickxorhash[QuickXorHash Algorithm code snippet].
. Base64-encode the XOR hash.
For more information, see the link:/windows/win32/seccrypto/utilities-base64encode[Base64Encode method documentation].
. After the file is migrated, retrieve the value of the `vti_writevalidationtoken` property from the uploaded file.
. Compare the value generated in step 2 with the value retrieved in step 3.
These two values should match.
If they do, you've validated that the record hasn't changed.

=== Configuration guidance

See xref:get-started-with-records-management.adoc[Get started with records management].
This article has information about subscriptions, permissions, and links to end-to-end configuration guidance for records management scenarios.
