= Set up Microsoft Purview Message Encryption
:audience: ITPro
:author: kccross
:description: Learn about Microsoft Purview Message Encryption that enables protected email communication with people inside and outside your organization.
:experimental:
:f1.keywords: ["NOCSH"]
:manager: laurawi
:ms.assetid: 7ff0c040-b25c-4378-9904-b1b50210d00e
:ms.author: krowley
:ms.collection: ["Strat_O365_IP", "M365-security-compliance"]
:ms.custom: ["seo-marvel-apr2020", "admindeeplinkMAC", "admindeeplinkEXCHANGE"]
:ms.date: 4/16/2022
:ms.localizationpriority: high
:ms.service: O365-seccomp
:ms.topic: article
:search.appverid: ["MET150"]

== Set up Message Encryption

Microsoft Purview Message Encryption allows organizations to share protected email with anyone on any device.
Users can exchange protected messages with other Microsoft 365 organizations, as well as third-parties using Outlook.com, Gmail, and other email services.

Follow the steps below to ensure that Microsoft Purview Message Encryption is available in your organization.

=== Verify that Azure Rights Management is active

Microsoft Purview Message Encryption leverages the protection features in link:/azure/information-protection/what-is-information-protection[Azure Rights Management Services (Azure RMS)], the technology used by link:/azure/information-protection/what-is-azure-rms[Azure Information Protection] to protect emails and documents via encryption and access controls.

The only prerequisite for using Microsoft Purview Message Encryption is that link:/azure/information-protection/what-is-azure-rms[Azure Rights Management] must be activated in your organization's tenant.
If it is, Microsoft 365 activates message encryption automatically and you don't need to do anything.

Azure RMS is also activated automatically for most eligible plans, so you probably don't have to do anything in this regard either.
See link:/azure/information-protection/activate-service[Activating Azure Rights Management] for more information.

____
[!IMPORTANT] If you use Active Directory Rights Management service (AD RMS) with Exchange Online, you need to link:/azure/information-protection/migrate-from-ad-rms-to-azure-rms[migrate to Azure Information Protection] before you can use message encryption.
Microsoft Purview Message Encryption is not compatible with AD RMS.
____

For more information, see:

* link:ome-faq.yml[Message Encryption FAQ] to check whether your subscription plan includes Azure Information Protection (which includes Azure RMS functionality).
* https://azure.microsoft.com/services/information-protection/[Azure Information Protection] for information about purchasing an eligible subscription.

==== Manually activating Azure Rights Management

If you disabled Azure RMS, or if it was not automatically activated for any reason, you can activate it manually.

For instructions, see link:/azure/information-protection/activate-service#how-to-activate-or-confirm-the-status-of-the-protection-service[How to activate or confirm the status of the protection service].

=== Configure management of your Azure Information Protection tenant key

This is an optional step.
Allowing Microsoft to manage the root key for Azure Information Protection is the default setting and recommended best practice for most organizations.
If this is the case, you don't need to do anything.

There are many reasons, for example compliance requirements, that may necessitate you generating and managing your own root key, also known as "bring your own key" (BYOK).
If this is the case, we recommend that you complete the required steps before setting up Microsoft Purview Message Encryption.
See link:/information-protection/plan-design/plan-implement-tenant-key[Planning and implementing your Azure Information Protection tenant key] for more.

=== Verify Microsoft Purview Message Encryption configuration in Exchange Online PowerShell

You can verify that your Microsoft 365 tenant is properly configured to use Microsoft Purview Message Encryption in link:/powershell/exchange/exchange-online-powershell[Exchange Online PowerShell].

. link:/powershell/exchange/connect-to-exchange-online-powershell[Connect to Exchange Online PowerShell] using an account with global administrator permissions in your Microsoft 365 tenant.
. Run the Get-IRMConfiguration cmdlet.
+
You should see a value of `$True` for the AzureRMSLicensingEnabled parameter, which indicates that Microsoft Purview Message Encryption is configured in your tenant.
If it is not, use Set-IRMConfiguration to set the value of AzureRMSLicensingEnabled to `$True` to enable Microsoft Purview Message Encryption.

. Run the Test-IRMConfiguration cmdlet using the following syntax:
+
[,powershell]
----
Test-IRMConfiguration [-Sender <email address> -Recipient <email address>]
----
+
*Example*:
+
[,powershell]
----
Test-IRMConfiguration -Sender securityadmin@contoso.com -Recipient securityadmin@contoso.com
----

 ** For sender and recipient, use the email address of any user in your Microsoft 365 tenant.
+
Your results should be similar to:
+
[,console]
----
Results : Acquiring RMS Templates ...
           - PASS: RMS Templates acquired.  Templates available: Contoso  - Confidential View Only, Contoso  - Confidential, Do Not
       Forward.
       Verifying encryption ...
           - PASS: Encryption verified successfully.
       Verifying decryption ...
           - PASS: Decryption verified successfully.
       Verifying IRM is enabled ...
           - PASS: IRM verified successfully.

       OVERALL RESULT: PASS
----

 ** Your organization name will replace _Contoso_.
 ** The default template names may be different from those displayed above.
See link:/azure/information-protection/configure-policy-templates[Configuring and managing templates for Azure Information Protection] for more.

. If the test fails with an error message *Failed to acquire RMS templates*, execute the following commands and run the Test-IRMConfiguration cmdlet to verify that it passes.
Connect to the link:/powershell/module/aipservice/?view=azureipps[AIPService module] to run the cmdlet.
+
[,powershell]
----
$RMSConfig = Get-AipServiceConfiguration
$LicenseUri = $RMSConfig.LicensingIntranetDistributionPointUrl
Set-IRMConfiguration -LicensingLocation $LicenseUri
Set-IRMConfiguration -InternalLicensingEnabled $true
----

. Run the Remove-PSSession cmdlet to disconnect from the Rights Management service.
+
[,powershell]
----
  Remove-PSSession $session
----

=== Next steps: Define mail flow rules to use Microsoft Purview Message Encryption

If there are previously configured mail flow rules to encrypt email in your organization, you need to update the existing rules to use Microsoft Purview Message Encryption.
For new deployments, you need to create new mail flow rules.

____
[!IMPORTANT] If you do not update existing mail flow rules, your users will continue to receive encrypted mail that uses the previous HTML attachment format, instead of the new seamless experience.
____

Mail flow rules determine under what conditions email messages should be encrypted, as well as conditions for removing that encryption.
When you set an action for a rule, any messages that match the rule conditions are encrypted when they're sent.

For steps on creating mail flow rules message encryption, see xref:define-mail-flow-rules-to-encrypt-email.adoc[Define mail flow rules to encrypt email messages in Office 365].

To update existing rules to use Microsoft Purview Message Encryption:

. In the Microsoft 365 admin center, go to *Admin centers* > https://go.microsoft.com/fwlink/p/?linkid=2059104[*Exchange*].
. In the Exchange admin center, go to menu:Mail flow[Rules].
. For each rule, in *Do the following*:
 ** Select *Modify the message security*.
 ** Select *Apply Office 365 Message Encryption and rights protection*.
 ** Select *Encrypt* from the RMS template list.
 ** Select *Save*.
 ** Select *OK*.
