= Germany value added tax number entity definition
:audience: Admin
:author: chrfox
:description: Germany value added tax number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Germany value added tax number

=== Format

11 character alphanumeric pattern

=== Pattern

11-character alphanumeric pattern:

* a letter D or d
* a letter E or e
* an optional space
* three digits
* an optional space or comma
* three digits
* an optional space or comma
* three digits

=== Checksum

Yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_germany_value_added_tax_number` finds content that matches the pattern.
* A keyword from `Keywords_germany_value_added_tax_number` is found.

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_germany_value_added_tax_number` finds content that matches the pattern.

[,xml]
----
      <!-- Germany Value Added Tax Number -->
      <Entity id="db177eb2-8811-4842-bffc-128c14aa219f" patternsProximity="300" recommendedConfidence="85">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_germany_value_added_tax_number" />
          <Match idRef="Keywords_germany_value_added_tax_number" />
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Func_germany_value_added_tax_number" />
        </Pattern>
      </Entity>
----

=== Keywords

==== Keyword_germany_value_added_tax_number

* vat number
* vat no
* vat#
* vat#  mehrwertsteuer
* mwst
* mehrwertsteuer identifikationsnummer
* mehrwertsteuer nummer
