= Crednetial in URL
:audience: Admin
:author: chrfox
:description: Credentials in URL sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Credentials in URL

=== Format

Paired username and password used in URL

or

Plain-text password used in script

=== Pattern

Various URL username and password formats, for example:

`+https://username:********@contoso.com/...+` `+ftp://username:********@contoso.com:20/...+`

for example: `+https://myuser:mypassword@localhost+`

or

Various password formats in script, for example:

`+password = ********...+`

for example:

`password=ZYXWVU_1`

=== Checksum

No

=== Description

This SIT is designed to match the security information that's used as a token in URL to do client validation or identification link:/azure/key-vault/quick-create-portal[user login process].
It uses several primary resources:

* Patterns of User Login Credentials in URL.
* Patterns of Password context in script.
* Patterns of CredentialName, CredentialFeatures, AccountIdentityName, AccountIdentityValue, ResourceType, ResourceName.
* Patterns of mockup values, redactions, and placeholders.

The patterns are designed to match actual credentials with reasonable confidence.
The patterns don't match credentials formatted as examples.
Mockup values, redacted values, and placeholders, like credential type or usage descriptions, in the position where an actual secret value should present won't be matched.

=== Keywords

==== Keyword_LoginCredentialsInUrl

* ://

==== Keyword_PasswordContextInScript

* secret
* password
* pw
