= Malta tax identification number entity definition
:audience: Admin
:author: chrfox
:description: Malta tax identification number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Malta tax identification number

=== Format

For Maltese nationals:

* seven digits and one letter in the specified pattern

Non-Maltese nationals and Maltese entities:

* nine digits

=== Pattern

Maltese nationals: seven digits and one letter

* seven digits
* one letter (not case-sensitive)

Non-Maltese nationals and Maltese entities: nine digits

* nine digits

=== Checksum

Not applicable

=== Definition

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The regex `Regex_malta_eu_tax_file_number`  or `Regex_malta_eu_tax_file_number_non_maltese_national` finds content that matches the pattern.
* A keyword from `Keywords_malta_eu_tax_file_number` is found.

A DLP policy has low confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The regex `Regex_malta_eu_tax_file_number` or `Regex_malta_eu_tax_file_number_non_maltese_national` finds content that matches the pattern.

[,xml]
----
      <!-- Malta Tax ID Number -->
      <Entity id="ec830c63-65f4-45d0-9d8c-910dc8334b20" patternsProximity="300" recommendedConfidence="75">
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Regex_malta_eu_tax_file_number" />
          <Match idRef="Keywords_malta_eu_tax_file_number" />
        </Pattern>
        <Pattern confidenceLevel="65">
          <IdMatch idRef="Regex_malta_eu_tax_file_number" />
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Regex_malta_eu_tax_file_number_non_maltese_national" />
          <Match idRef="Keywords_malta_eu_tax_file_number" />
        </Pattern>
        <Pattern confidenceLevel="65">
          <IdMatch idRef="Regex_malta_eu_tax_file_number_non_maltese_national" />
        </Pattern>
      </Entity>
----

=== Keywords

==== Keywords_malta_eu_tax_file_number

* citizen service number
* id tat-taxxa
* identifika numru tal-biljett
* kodiċi numerali personali
* numru ta 'identifikazzjoni personali
* numru ta 'identifikazzjoni tat-taxxa
* numru ta 'identifikazzjoni uniku
* numru ta' identità uniku
* numru tas-servizz taċ-ċittadin
* numru tat-taxxa
* personal numeric code
* tax id
* tax identification no
* tax identification number
* tax no#
* tax no
* tax number
* tax registration number
* taxid#
* taxidno#
* taxidnumber#
* taxno#
* taxnumber#
* taxnumber
* tin id
* tin no
* tin#
* unique identification number
* unique identity number
* uniqueidentityno#
