= All medical terms and conditions entity definition
:audience: Admin
:author: chrfox
:description: All medical terms and conditions sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== All medical terms and conditions

All medical terms and conditions is a bundled named entity that detects medical terms and medical conditions.
It detects English terms only.
Use this SIT to detect all possible matches of medical terms and conditions.

=== Format

Dictionary

=== Pattern

Dictionary

=== Checksum

No

=== Description

This bundled named entity matches text that mentions medical conditions that are present in curated dictionaries.
There's one curated dictionary per supported language.
The dictionaries are from many international medical resources.
The dictionaries include as many medical conditions as possible without risking a large number of false positives.
Each entry contains the different forms that a single condition is commonly written in to ensure coverage, for example:

* _TB_
* _tuberculosis_
* _phthisis pulmonalis_

=== Contains

This bundled named entity SIT contains these individual SITs.

* Blood test terms
* Types of medication
* Diseases
* Generic medication names
* Impairments listed in the U.S.
Disability Evaluation Under Social Security
* Lab test terms
* Lifestyles that relate to medical conditions
* Medical specialties
* Surgical procedures
* Brand medication names
