= Japan My Number - Corporate entity definition
:audience: Admin
:author: chrfox
:description: Japan My Number - Corporate sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Japan My Number - Corporate

=== Format

13-digit number

=== Pattern

13-digit number:

* one digit from one to nine
* 12 digits

=== Checksum

Yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_japanese_my_number_corporate` finds content that matches the pattern.
* A keyword from `Keywords_japanese_my_number_corporate` is found.

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_japanese_my_number_corporate` finds content that matches the pattern.

[,xml]
----
      <!-- Japanese My Number – Corporate -->
      <Entity id="9e0eaf79-ff20-4ffb-b3e4-e7368d5db6ff" patternsProximity="300" recommendedConfidence="85">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_japanese_my_number_corporate" />
          <Match idRef="Keywords_japanese_my_number_corporate" />
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Func_japanese_my_number_corporate" />
        </Pattern>
      </Entity>
----

=== Keywords

==== Keyword_japan_my_number_corporate

* corporate number
* マイナンバー
* 共通番号
* マイナンバーカード
* マイナンバーカード番号
* 個人番号カード
* 個人識別番号
* 個人識別ナンバー
* 法人番号
* 指定通知書
