= Hungary social security number (TAJ) entity definition
:audience: Admin
:author: chrfox
:description: Hungary social security number (TAJ) sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Hungary social security number (TAJ)

=== Format

Nine digits without spaces and delimiters

=== Pattern

Nine digits

=== Checksum

Yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_hungary_eu_ssn_or_equivalent` finds content that matches the pattern.
* A keyword from `Keywords_hungary_eu_ssn_or_equivalent` is found.

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_hungary_eu_ssn_or_equivalent` finds content that matches the pattern.

[,xml]
----
      <!-- Hungarian Social Security Number (TAJ) -->
      <Entity id="0de78315-9537-47f5-95ab-b3e77eba3993" patternsProximity="300" recommendedConfidence="85">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_hungary_eu_ssn_or_equivalent" />
          <Match idRef="Keywords_hungary_eu_ssn_or_equivalent" />
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Func_hungary_eu_ssn_or_equivalent" />
        </Pattern>
      </Entity>
----

=== Keywords

==== Keywords_hungary_eu_ssn_or_equivalent

* hungarian social security number
* social security number
* socialsecuritynumber#
* hssn#
* socialsecuritynno
* hssn
* taj
* taj#
* ssn
* ssn#
* social security no
* áfa
* közösségi adószám
* általános forgalmi adó szám
* hozzáadottérték adó
* áfa szám
* magyar áfa szám
