= Luxemburg national identification number (natural persons) entity definition
:audience: Admin
:author: chrfox
:description: Luxemburg national identification number (natural persons) sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Luxemburg national identification number (natural persons)

=== Format

13 digits with no spaces or delimiters

=== Pattern

13 digits:

* 11 digits
* two check digits

=== Checksum

yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_luxemburg_eu_tax_file_number` finds content that matches the pattern.
* A keyword from `Keywords_luxemburg_eu_national_id_card` is found.

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_luxemburg_eu_tax_file_number` finds content that matches the pattern.

[,xml]
----
      <!-- Luxemburg National Identification Number (Natural persons) -->
      <Entity id="aaf661ed-29ec-426d-8bf9-880cad298ebb" patternsProximity="300" recommendedConfidence="85">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_luxemburg_eu_tax_file_number" />
          <Match idRef="Keywords_luxemburg_eu_national_id_card" />
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Func_luxemburg_eu_tax_file_number" />
          <Any minMatches="0" maxMatches="0">
            <Match idRef="Keywords_luxemburg_eu_telephone_number" />
            <Match idRef="Keywords_luxemburg_eu_mobile_number" />
          </Any>
        </Pattern>
      </Entity>
----

=== Keywords

==== Keywords_luxemburg_eu_national_id_card

* eindeutige id
* eindeutige id-nummer
* eindeutigeid#
* id personnelle
* idpersonnelle#
* idpersonnelle
* individual code
* individual id
* individual identification
* individual identity
* numéro d'identification personnel
* personal id
* personal identification
* personal identity
* personalidno#
* personalidnumber#
* persönliche identifikationsnummer
* unique id
* unique identity
* uniqueidkey#
