= Http authorization header entity definition (preview)
:audience: Admin
:author: chrfox
:description: Http authorization header sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Http authorization header (preview)

=== Format

An authorization header used in HTTP request.

=== Pattern

Various authentication header formats for example:

`+authorization: basic ********+` + `+authorization: bearer ********+` + `+authorization: digest ********+` + `+authorization: negotiate ********+` +

=== Checksum

No

=== Definition

This SIT is designed to match the security information that's used in the header of an link:/dotnet/api/system.net.http.headers.httprequestheaders.authorization?view=netframework-4.8[HTTP request for authentication and authorization.]

It uses several primary resources:

* Patterns of Http authorization header.
* Patterns of CredentialName, CredentialFeatures, ResourceType.
* Patterns of mockup values, redactions, and placeholders.

The patterns are designed to match actual credentials with reasonable confidence.
The patterns don't match credentials formatted as examples.
Mockup values, redacted values, and placeholders, like credential type or usage descriptions, in the position where an actual secret value should present won't be matched.

=== Keywords

==== Keyword_HttpAuthorizationHeader:

* authorization
