= Canada passport number entity definition
:audience: Admin
:author: chrfox
:description: Canada passport number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Canada passport number

=== Format

two uppercase letters followed by six digits

=== Pattern

two uppercase letters followed by six digits

=== Checksum

No

=== Definition

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The regular expression `Regex_canada_passport_number` finds content that matches the pattern.
* A keyword from `Keyword_canada_passport_number` or `Keyword_passport` is found.

[,xml]
----
<!-- Canada Passport Number -->
<Entity id="14d0db8b-498a-43ed-9fca-f6097ae687eb" patternsProximity="300" recommendedConfidence="75">
  <Pattern confidenceLevel="75">
        <IdMatch idRef="Regex_canada_passport_number" />
        <Any minMatches="1">
          <Match idRef="Keyword_canada_passport_number" />
          <Match idRef="Keyword_passport" />
        </Any>
  </Pattern>
</Entity>
----

=== Keywords

==== Keyword_canada_passport_number

* canadian citizenship
* canadian passport
* passport application
* passport photos
* certified translator
* canadian citizens
* processing times
* renewal application

==== Keyword_passport

* Passport Number
* Passport No
* Passport #
* Passport#
* PassportID
* Passportno
* passportnumber
* パスポート
* パスポート番号
* パスポートのNum
* パスポート＃
* Numéro de passeport
* Passeport n °
* Passeport Non
* Passeport #
* Passeport#
* PasseportNon
* Passeportn °
