= Germany tax identification number entity definition
:audience: Admin
:author: chrfox
:description: Germany tax identification number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Germany tax identification number

=== Format

11 digits without spaces and delimiters

=== Pattern

11 digits

* Two digits
* An optional space
* Three digits
* An optional space
* Three digits
* An optional space
* Two digits
* one check digit

=== Checksum

Yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_germany_eu_tax_file_number` finds content that matches the pattern.
* A keyword from `Keywords_germany_eu_tax_file_number` is found.

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_germany_eu_tax_file_number` finds content that matches the pattern.

[,xml]
----
      <!-- Germany Tax Identification Number -->
      <Entity id="43316a89-9880-40cf-b980-04bc7eefcec5" patternsProximity="300" recommendedConfidence="85">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_germany_eu_tax_file_number" />
          <Match idRef="Keywords_germany_eu_tax_file_number" />
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Func_germany_eu_tax_file_number" />
        </Pattern>
      </Entity>
----

=== Keywords

==== Keywords_germany_eu_tax_file_number

* identifikationsnummer
* steuer id
* steueridentifikationsnummer
* steuernummer
* tax id
* tax identification no
* tax identification number
* tax no#
* tax no
* tax number
* tax registration number
* taxid#
* taxidno#
* taxidnumber#
* taxno#
* taxnumber#
* taxnumber
* tin id
* tin no
* tin#
* zinn#
* zinn
* zinnnummer
