= Sweden national ID entity definition
:audience: Admin
:author: chrfox
:description: Sweden national ID sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Sweden national ID

=== Format

10 or 12 digits and an optional delimiter

=== Pattern

10 or 12 digits and an optional delimiter:

* two digits (optional)
* Six digits in date format YYMMDD
* delimiter of "-" or "+" (optional)
* four digits

=== Checksum

Yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_swedish_national_identifier` finds content that matches the pattern.
* A keyword from `Keywords_swedish_national_identifier` is found
* The checksum passes.

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_swedish_national_identifier` finds content that matches the pattern.
* The checksum passes.

[,xml]
----
    <!-- Sweden National ID -->
    <Entity id="f69aaf40-79be-4fac-8f05-fd1910d272c8" patternsProximity="300" recommendedConfidence="85">
      <Pattern confidenceLevel="85">
        <IdMatch idRef="Func_swedish_national_identifier" />
        <Match idRef="Keywords_swedish_national_identifier" />
      </Pattern>
      <Pattern confidenceLevel="75">
        <IdMatch idRef="Func_swedish_national_identifier" />
      </Pattern>
    </Entity>
----

=== Keywords

==== Keywords_swedish_national_identifier

* id no
* id number
* id#
* identification no
* identification number
* identifikationsnumret#
* identifikationsnumret
* identitetshandling
* identity document
* identity no
* identity number
* id-nummer
* personal id
* personnummer#
* personnummer
* skatteidentifikationsnummer
