= Malta identity card number entity definition
:audience: Admin
:author: chrfox
:description: Malta identity card number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Malta identity card number

=== Format

seven digits followed by one letter

=== Pattern

seven digits followed by one letter:

* seven digits
* one letter in "M, G, A, P, L, H, B, Z" (case insensitive)

=== Checksum

Not applicable

=== Definition

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The regular expression `Regex_malta_eu_national_id_card` finds content that matches the pattern.
* A keyword from `Keywords_malta_eu_national_id_card` is found.

A DLP policy has low confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The regular expression `Regex_malta_eu_national_id_card` finds content that matches the pattern.

[,xml]
----
      <!-- Malta Identity Card Number -->
      <Entity id="854b36b3-a388-4ac8-a4ec-677c2b5e4356" patternsProximity="300" recommendedConfidence="75">
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Regex_malta_eu_national_id_card" />
          <Match idRef="Keywords_malta_eu_national_id_card" />
        </Pattern>
        <Pattern confidenceLevel="65">
          <IdMatch idRef="Regex_malta_eu_national_id_card" />
        </Pattern>
      </Entity>
----

=== Keywords

==== Keywords_malta_eu_national_id_card

* citizen service number
* id tat-taxxa
* identifika numru tal-biljett
* kodiċi numerali personali
* numru ta 'identifikazzjoni personali
* numru ta 'identifikazzjoni tat-taxxa
* numru ta 'identifikazzjoni uniku
* numru ta' identità uniku
* numru tas-servizz taċ-ċittadin
* numru tat-taxxa
* personal numeric code
* unique identification number
* unique identity number
* uniqueidentityno#
