= Czech passport number entity definition
:audience: Admin
:author: chrfox
:description: Czech passport number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Czech passport number

=== Format

eight digits without spaces or delimiters

=== Pattern

eight digits without spaces or delimiters

=== Checksum

No

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The regular expression `Regex_czech_republic_eu_passport_number` finds content that matches the pattern.
* A keyword from `Keywords_eu_passport_number` or `Keywords_czech_republic_eu_passport_number` is found.
* The regular expression `Regex_eu_passport_date1` finds date in the format DD.MM.YYYY or a keyword from `Keywords_eu_passport_date` is found

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The regular expression `Regex_czech_republic_eu_passport_number` finds content that matches the pattern.
* A keyword from `Keywords_eu_passport_number` or `Keywords_czech_republic_eu_passport_number` is found.

[,xml]
----
      <!-- Czech Republic Passport Number -->
      <Entity id="7bcd8ce8-5e92-4bbe-bc92-fa669f0369fa" patternsProximity="300" recommendedConfidence="75">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Regex_czech_republic_eu_passport_number" />
          <Any minMatches="1">
            <Match idRef="Keywords_eu_passport_number" />
            <Match idRef="Keywords_czech_republic_eu_passport_number" />
          </Any>
          <Any minMatches="1">
            <Match idRef="Regex_eu_passport_date1" />
            <Match idRef="Keywords_eu_passport_date" />
          </Any>
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Regex_czech_republic_eu_passport_number" />
          <Any minMatches="1">
            <Match idRef="Keywords_eu_passport_number" />
            <Match idRef="Keywords_czech_republic_eu_passport_number" />
          </Any>
        </Pattern>
      </Entity>
----

=== Keywords

==== Keywords_eu_passport_number_common

* passport#
* passport #
* passportid
* passports
* passportno
* passport no
* passportnumber
* passport number
* passportnumbers
* passport numbers

==== Keywords_czech_republic_eu_passport_number

* cestovní pas
* číslo pasu
* cestovní pasu
* passeport no
* čísla pasu

==== Keywords_eu_passport_date

* date of issue
* date of expiry
