= Hungary tax identification number entity definition
:audience: Admin
:author: chrfox
:description: Hungary tax identification number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Hungary tax identification number

=== Format

10 digits with no spaces or delimiters

=== Pattern

10 digits:

* One digit that must be "8"
* Eight digits
* One check digit

=== Checksum

Yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_hungary_eu_tax_file_number` finds content that matches the pattern.
* A keyword from `Keywords_hungary_eu_tax_file_number` is found.

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_hungary_eu_tax_file_number` finds content that matches the pattern.

[,xml]
----
      <!-- Hungary Tax Identification Number -->
      <Entity id="ede42eb4-59d9-49eb-9603-d7853fbda91d" patternsProximity="300" recommendedConfidence="85">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_hungary_eu_tax_file_number" />
          <Match idRef="Keywords_hungary_eu_tax_file_number" />
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Func_hungary_eu_tax_file_number" />
          <Any minMatches="0" maxMatches="0">
            <Match idRef="Keywords_hungary_eu_telephone_number" />
            <Match idRef="Keywords_hungary_eu_mobile_number" />
          </Any>
        </Pattern>
      </Entity>
----

=== Keywords

==== Keywords_hungary_eu_tax_file_number

* adóazonosító szám
* adóhatóság szám
* adószám
* hungarian tin
* hungatiantin#
* tax authority no
* tax id
* tax identification no
* tax identification number
* tax no#
* tax no
* tax number
* tax registration number
* taxid#
* taxidno#
* taxidnumber#
* taxno#
* taxnumber#
* taxnumber
* tin id
* tin no
* tin#
* vat number
