= Switzerland SSN AHV number entity definition
:audience: Admin
:author: chrfox
:description: Switzerland SSN AHV number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Switzerland SSN AHV number

=== Format

13-digit number

=== Pattern

13-digit number:

* three digits - 756
* an optional dot
* four digits
* an optional dot
* four digits
* an optional dot
* two digits

=== Checksum

Yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_swiss_social_security_number_ahv` finds content that matches the pattern.
* A keyword from `Keywords_swiss_social_security_number_ahv` is found.

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_swiss_social_security_number_ahv` finds content that matches the pattern.

[,xml]
----
      <!-- Swiss SSN AHV Number -->
      <Entity id="277cfa4b-6eaa-4a1b-9492-099dec849971" patternsProximity="300" recommendedConfidence="85">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_swiss_social_security_number_ahv" />
          <Match idRef="Keywords_swiss_social_security_number_ahv" />
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Func_swiss_social_security_number_ahv" />
        </Pattern>
      </Entity>
----

=== Keywords

==== Keyword_swiss_ssn_AHV_number

* ahv
* ssn
* pid
* insurance number
* personalidno#
* social security number
* personal id number
* personal identification no.
* insuranceno#
* uniqueidno#
* unique identification no.
* avs number
* personal identity no versicherungsnummer
* identifikationsnummer
* einzigartige identität nicht
* sozialversicherungsnummer
* identification personnelle id
* numéro de sécurité sociale
