= Australia tax file number entity definition
:audience: Admin
:author: chrfox
:description: Australia tax file number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Australia tax file number

=== Format

eight to nine digits

=== Pattern

eight to nine digits typically presented with spaces as follows:

* three digits
* an optional space
* three digits
* an optional space
* two to three digits where the last digit is a check digit

=== Checksum

Yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function Func_australian_tax_file_number finds content that matches the pattern.
* No keyword from Keyword_Australia_Tax_File_Number or Keyword_number_exclusions is found.
* The checksum passes.

[,xml]
----
   <!-- Australia Tax File Number -->
    <Entity id="e29bc95f-ff70-4a37-aa01-04d17360a4c5" patternsProximity="300" recommendedConfidence="85">
      <Pattern confidenceLevel="85">
        <IdMatch idRef="Func_australian_tax_file_number" />
        <Match idRef="Keyword_Australia_Tax_File_Number" />
      </Pattern>
    </Entity>
----

=== Keywords

==== Keyword_australia_tax_file_number

* australian business number
* marginal tax rate
* medicare levy
* portfolio number
* service veterans
* withholding tax
* individual tax return
* tax file number
* tfn
