= Poland REGON number entity definition
:audience: Admin
:author: chrfox
:description: Poland REGON number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Poland REGON number

=== Format

9-digit or 14-digit number

=== Pattern

nine digit or 14-digit number:

* nine digits or
* nine digits
* hyphen
* five digits

=== Checksum

Yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_polish_regon_number` finds content that matches the pattern.
* A keyword from `Keywords_polish_regon_number` is found.

A DLP policy has low confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_polish_regon_number` finds content that matches the pattern.

[,xml]
----
      <!-- Polish REGON Number  -->
      <Entity id="fc87b421-f437-4f8b-b739-29a735ead0d9" patternsProximity="300" recommendedConfidence="85">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_polish_regon_number" />
          <Match idRef="Keywords_polish_regon_number" />
        </Pattern>
        <Pattern confidenceLevel="65">
          <IdMatch idRef="Func_polish_regon_number" />
        </Pattern>
      </Entity>
----

=== Keywords

==== Keywords_poland_regon_number

* regon id
* statistical number
* statistical id
* statistical no
* regon number
* regonid#
* regonno#
* company id
* companyid#
* companyidno#
* numer statystyczny
* numeru regon
* numerstatystyczny#
* numeruregon#
