= Azure Shared Access key / Web Hook token signature entity definition (preview)
:audience: Admin
:author: chrfox
:description: Azure Shared Access key / Web Hook token sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Azure Shared Access key / Web Hook token (preview)

=== Format

A combination of 44 characters consisting of letters, digits, and special characters.

or

A combination of up to 76 characters consisting of letters, digits, and special characters.

=== Pattern

Any combination of 43 characters consisting of:

* a-z (not case-sensitive)
* 0-9
* forward slashes (/)
* or plus signs (+)
* ends with an equal sign (=)

for example:

`abcdefghijklmnopqrstuvwxyz0123456789/+ABCDE=`

or

A combination of 43 to 73 characters consisting of:

* a-z (case insensitive )
* 0-9
* percent signs (%)
* ends with a suffix '%3d' (case insensitive)

for example:

`abcdefghijklmnopqrstuvwxyz0123456789%2F%2BABCDE%3D`

=== Checksum

No

=== Definition

This SIT is designed to match the security information that's used to access general link:/azure/notification-hubs/notification-hubs-push-notification-security[Azure resources with restricted permission].

It uses several primary resources:

* Patterns of Base64 encoded 256 bits symmetric key.
* Patterns of URL Encoded 256 bits symmetric key.
* Patterns of CredentialName, CredentialFeatures, AccountIdentityName, AccountIdentityValue, ResourceType, ResourceName, Id.
* Patterns of mockup values, redactions, and placeholders.
* A dictionary of vocabulary

The patterns are designed to match actual credentials with reasonable confidence.
The patterns do not match credentials formatted as examples.
Mockup values, redacted values, and placeholders, like credential type or usage descriptions, in the position where an actual secret value should present will not be matched.

=== Keywords

==== Keyword_SymmetricKey256:

* SharedAccessKey
* AccountKey

==== Keyword_SymmetricKey256UrlEncoded:

* sig=
* key
* token
* secret
* password
