= Cyprus tax identification number entity definition
:audience: Admin
:author: chrfox
:description: Cyprus tax identification number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Cyprus tax identification number

=== Format

eight digits and one letter in the specified pattern

=== Pattern

eight digits and one letter:

* a "0" or "9"
* seven digits
* one letter (not case-sensitive)

=== Checksum

not applicable

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_cyprus_eu_tax_file_number` finds content that matches the pattern.
* A keyword from `Keywords_cyprus_eu_tax_file_number` is found.

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_cyprus_eu_tax_file_number` finds content that matches the pattern.

[,xml]
----
      <!-- Cyprus Tax Identification Number -->
      <Entity id="40e64bd9-55f3-4a09-9bd6-1db18dced9dd" patternsProximity="300" recommendedConfidence="85">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_cyprus_eu_tax_file_number" />
          <Match idRef="Keywords_cyprus_eu_tax_file_number" />
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Func_cyprus_eu_tax_file_number" />
        </Pattern>
      </Entity>
----

=== Keywords

==== Keywords_cyprus_eu_tax_file_number

* tax id
* tax identification code
* tax identification no
* tax identification number
* tax no#
* tax no
* tax number
* tax registration number
* taxid#
* taxidno#
* taxidnumber#
* taxno#
* taxnumber#
* taxnumber
* tic#
* tic
* tin id
* tin no
* tin#
* vergi kimlik kodu
* vergi kimlik numarası
* αριθμός φορολογικού μητρώου
* κωδικός φορολογικού μητρώου
* φορολογική ταυτότητα
* φορολογικού κωδικού
