= Azure IoT shared access key entity definition
:audience: Admin
:author: chrfox
:description: Azure IoT shared access key sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Azure IoT shared access key

=== Format

A combination of 44-characters consisting of letters, digits, and special characters ending with and equals sign that is not part of the pattern.

=== Pattern

Any combination of 43 characters consisting of:

* a-z (not case-sensitive)
* 0-9
* forward slashes (/)
* or plus signs (+)
* ends with an equal sign (=) that is not part of the pattern.

For example:

`abcdefghijklmnopqrstuvwxyz0123456789/+ABCDE=`

=== Checksum

No

=== Definition

This SIT is designed to match the security information that's used to authenticate link:/azure/iot-fundamentals/iot-security-deployment[Azure IoT devices and services].

It uses several primary resources:

* Patterns of Base64 encoded 256 bits symmetric key.
* Patterns of CredentialName, CredentialFeatures, AccountIdentityName, AccountIdentityValue, ResourceType, ResourceName, Id.
* Patterns of mockup values, redactions, and placeholders.
* A dictionary of vocabulary.

The patterns are designed to match actual credentials with reasonable confidence.
The patterns do not match credentials formatted as examples.
Mockup values, redacted values, and placeholders, like credential type or usage descriptions, in the position where an actual secret value should present will not be matched.

=== Keywords

==== Keyword_SymmetricKey256:

* SharedAccessKey
* AccountKey
