= Modify a custom sensitive information type using PowerShell
:audience: Admin
:author: chrfox
:description: Learn how to modify a custom sensitive information using PowerShell.
:f1.keywords: ["NOCSH"]
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: article
:search.appverid: ["MOE150", "MET150"]

== Modify a custom sensitive information type using PowerShell

In Security & Compliance PowerShell, modifying a custom sensitive information type requires you to:

. Export the existing rule package that contains the custom sensitive information type to an XML file (or use the existing XML file if you have it).
. Modify the custom sensitive information type in the exported XML file.
. Import the updated XML file back into the existing rule package.

To connect to Security & Compliance PowerShell, see link:/powershell/exchange/exchange-online-powershell[Security & Compliance PowerShell].

=== Step 1: Export the existing rule package to an XML file

____
[!NOTE] If you have a copy of the XML file (for example, you just created and imported it), you can skip to the next step to modify the XML file.
____

. If you don't already know it, run the link:/powershell/module/exchange/get-dlpsensitiveinformationtype[Get-DlpSensitiveInformationTypeRulePackage] cmdlet to find the name of the custom rule package:
+
[,powershell]
----
Get-DlpSensitiveInformationTypeRulePackage
----
+
____
[!NOTE] The built-in rule package that contains the built-in sensitive information types is named Microsoft Rule Package.
The rule package that contains the custom sensitive information types that you created in the Compliance center UI is named Microsoft.SCCManaged.CustomRulePack.
____

. Use the link:/powershell/module/exchange/get-dlpsensitiveinformationtyperulepackage[Get-DlpSensitiveInformationTypeRulePackage] cmdlet to store the custom rule package to a variable:
+
[,powershell]
----
$rulepak = Get-DlpSensitiveInformationTypeRulePackage -Identity "RulePackageName"
----
+
For example, if the name of the rule package is "Employee ID Custom Rule Pack", run the following cmdlet:
+
[,powershell]
----
$rulepak = Get-DlpSensitiveInformationTypeRulePackage -Identity "Employee ID Custom Rule Pack"
----

. Use the following syntax to export the custom rule package to an XML file:
+
[,powershell]
----
[System.IO.File]::WriteAllBytes('XMLFileAndPath', $rulepak.SerializedClassificationRuleCollection)
----
+
This example exports the rule package to the file named ExportedRulePackage.xml in the C:\My Documents folder.
+
[,powershell]
----
[System.IO.File]::WriteAllBytes('C:\My Documents\ExportedRulePackage.xml', $rulepak.SerializedClassificationRuleCollection)
----

=== Step 2: Modify the sensitive information type in the exported XML file

Sensitive information types in the XML file and other elements in the file are described earlier in this topic.

=== Step 3: Import the updated XML file back into the existing rule package

To import the updated XML back into the existing rule package, use the link:/powershell/module/exchange/set-dlpsensitiveinformationtyperulepackage[Set-DlpSensitiveInformationTypeRulePackage] cmdlet:

[,powershell]
----
Set-DlpSensitiveInformationTypeRulePackage -FileData ([System.IO.File]::ReadAllBytes('C:\My Documents\External Sensitive Info Type Rule Collection.xml'))
----

For detailed syntax and parameter information, see link:/powershell/module/exchange/set-dlpsensitiveinformationtyperulepackage[Set-DlpSensitiveInformationTypeRulePackage].

=== More information

* xref:dlp-learn-about-dlp.adoc[Learn about Microsoft Purview Data Loss Prevention]
* xref:sensitive-information-type-entity-definitions.adoc[Sensitive information type entity definitions]
* xref:sit-functions.adoc[Sensitive information type functions]
