= Poland national ID (PESEL) entity definition
:audience: Admin
:author: chrfox
:description: Poland national ID (PESEL) sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Poland national ID (PESEL)

=== Format

11 digits

=== Pattern

* six digits representing date of birth in the format YYMMDD
* four digits
* one check digit

=== Checksum

Yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_pesel_identification_number` finds content that matches the pattern.
* A keyword from `Keyword_pesel_identification_number` is found.
* The checksum passes.

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_pesel_identification_number` finds content that matches the pattern.
* The checksum passes.

[,xml]
----
      <!-- Poland National ID (PESEL) -->
      <Entity id="E3AAF206-4297-412F-9E06-BA8487E22456" patternsProximity="300" recommendedConfidence="85">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_pesel_identification_number" />
          <Match idRef="Keyword_pesel_identification_number" />
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Func_pesel_identification_number" />
        </Pattern>
      </Entity>
----

=== Keywords

==== Keyword_pesel_identification_number

* dowód osobisty
* dowódosobisty
* niepowtarzalny numer
* niepowtarzalnynumer
* nr.-pesel
* nr-pesel
* numer identyfikacyjny
* pesel
* tożsamości narodowej
