= Bulgaria passport number entity definition
:audience: Admin
:author: chrfox
:description: Bulgaria passport number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Bulgaria passport number

=== Format

nine digits without spaces and delimiters

=== Pattern

nine digits

=== Checksum

No

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The regular expression `Regex_bulgaria_eu_passport_number` finds content that matches the pattern.
* A keyword from `Keywords_eu_passport_number` or `Keywords_bulgaria_eu_passport_number` is found.
* The regular expression `Regex_eu_passport_date1` finds date in the format DD.MM.YYYY or a keyword from `Keywords_eu_passport_date` is found

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The regular expression `Regex_bulgaria_eu_passport_number` finds content that matches the pattern.
* A keyword from `Keywords_eu_passport_number` or `Keywords_bulgaria_eu_passport_number` is found.

[,xml]
----
      <!-- Bulgaria Passport Number -->
      <Entity id="f7172b82-c588-4216-845e-4e54e397f29a" patternsProximity="300" recommendedConfidence="75">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Regex_bulgaria_eu_passport_number" />
          <Any minMatches="1">
            <Match idRef="Keywords_eu_passport_number" />
            <Match idRef="Keywords_bulgaria_eu_passport_number" />
          </Any>
          <Any minMatches="1">
            <Match idRef="Regex_eu_passport_date1" />
            <Match idRef="Keywords_eu_passport_date" />
          </Any>
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Regex_bulgaria_eu_passport_number" />
          <Any minMatches="1">
            <Match idRef="Keywords_eu_passport_number" />
            <Match idRef="Keywords_bulgaria_eu_passport_number" />
          </Any>
        </Pattern>
      </Entity>
----

=== Keywords

==== Keywords_eu_passport_number

* passport#
* passport #
* passportid
* passports
* passportno
* passport no
* passportnumber
* passport number
* passportnumbers
* passport numbers

==== Keywords_bulgaria_eu_passport_number

* номер на паспорта
* номер на паспорт
* паспорт №

==== Keywords_eu_passport_date

* date of issue
* date of expiry
