= Azure DevOps personal access token entity definition (preview)
:audience: Admin
:author: chrfox
:description: Azure DevOps personal access token sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Azure DevOps personal access token (preview)

=== Format

A combination of 52 characters consisting of letters, digits, and special characters.

=== Pattern

Any combination of 52 characters consisting of:

* a-z or A-Z (case-sensitive)
* or 2-7

for example:

`ntpi2ch67ci2vjzcohglogyygwo5fuyl365n2zdowwxhsys6jnoa`

=== Checksum

Yes

=== Definition

This SIT is designed to match the security information that's used as an alternate password to authenticate into link:/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops[Azure DevOps.]

It uses several primary resources:

* Patterns of Base32 encoded 256 bits symmetric key.
* Patterns of CredentialName, CredentialFeatures, AccountIdentityName, AccountIdentityValue, ResourceType, ResourceName.
* Patterns of mockup values, redactions, and placeholders.
* A dictionary of vocabulary

The patterns are designed to match actual credentials with reasonable confidence.
The patterns do not match credentials formatted as examples.
Mockup values, redacted values, and placeholders, like credential type or usage descriptions, in the position where an actual secret value should present will not be matched.

=== Keywords

==== Keyword_SymmetricKey256B32:

* pat
* token
* ado
* vsts
* azuredevops
* visualstudio.com
* dev.azure.com
