= Azure Redis cache connection string password entity definition (preview)
:audience: Admin
:author: chrfox
:description: Azure Redis cache connection string password sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Azure Redis cache connection string password (preview)

=== Format

A combination of up to 20,000-characters consisting of letters, digits, and special characters.

or

A combination of 44-characters consisting of letters, digits, and special characters.

=== Pattern

Any combination of up to 20,000 characters consisting of:

* a-z (not case-sensitive)
* 0-9
* forward slashes (/)
* or plus signs (+)
* Up to 2
* equal signs (=)

for example:

`MIIKcQIBAzCCCi0GCSqGSIb3DQEHAaCCCh4EggoaMIIKFjCCBg8GCSqGSIb3DQEHAaCCBgAEggX8MIIF+DCCBfQGCyqGSIb3DQEM`

or

Any combination of 43 characters consisting of:

* a-z (not case-sensitive)
* 0-9
* forward slashes (/)
* or plus signs (+)
* ends with an equal sign (=)

for example:

`abcdefghijklmnopqrstuvwxyz0123456789/+ABCDE=`

=== Checksum

Yes

=== Definition

This SIT is designed to match the security information that's used to connect to link:/azure/azure-cache-for-redis/[Azure Cache for Redis servers].

It uses several primary resources:

* Patterns of Base64 encoded string literal.
* Patterns of Base64 encoded 256 bits symmetric key.
* Patterns of CredentialName, CredentialFeatures, AccountIdentityName, AccountIdentityValue, ResourceType, ResourceName, Id.
* Patterns of mockup values, redactions, and placeholders.
* A dictionary of vocabulary.

The patterns are designed to match actual credentials with reasonable confidence.
The patterns do not match credentials formatted as examples.
Mockup values, redacted values, and placeholders, like credential type or usage descriptions, in the position where an actual secret value should present will not be matched.

=== Keywords

==== Keyword_Base64EncodedStringLiteral:

* MII

==== Keyword_SymmetricKey256:

* SharedAccessKey
* AccountKey
