= Azure App Service Deployment Password entity definition (preview)
:audience: Admin
:author: chrfox
:description: Azure App Service Deployment Password sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Azure App Service deployment password (preview)

=== Format

A combination of 60 characters consisting of letters, digits, and special characters.

=== Pattern

Any combination of 60 characters consisting of:

* a-z (not case-sensitive)
* 0-9
* forward slashes (/)
* or plus signs (+)

for example:

`abcdefghijklmnopqrstuvwxyz0123456789/+ABCDEFGHIJKLMNOPQRSTUV`

=== Checksum

No

=== Definition

This SIT is designed to match the security information that's used to secure link:/azure/app-service/deploy-configure-credentials[Azure App Service deployment] from a local computer.

It uses several primary resources:

* Patterns of Base64 encoded 360 bits symmetric key.
* Patterns of CredentialName, CredentialFeatures, AccountIdentityName, AccountIdentityValue, ResourceType, ResourceName.
* Patterns of mockup values, redactions, and placeholders.
* A dictionary of vocabulary.

The patterns are designed to match actual credentials with reasonable confidence.
The patterns do not match credentials formatted as examples.
Mockup values, redacted values, and placeholders, like credential type or usage descriptions, in the position where an actual secret value should present will not be matched.

=== Keywords

==== Keyword_SymmetricKey360:

* password
* pw
