= Japan My Number - Personal entity definition
:audience: Admin
:author: chrfox
:description: Japan My Number - Personal sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Japan My Number - Personal

=== Format

12-digit number

=== Pattern

12-digit number:

* four digits
* an optional space, dot, or hyphen
* four digits
* an optional space, dot, or hyphen
* four digits

=== Checksum

Yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_japanese_my_number_personal` finds content that matches the pattern.
* A keyword from `Keywords_japanese_my_number_personal` is found.

A DLP policy has low confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_japanese_my_number_personal` finds content that matches the pattern.

[,xml]
----
      <!-- Japanese My Number – Personal -->
      <Entity id="98da8e66-7299-4ebd-9f82-c871ab37d3ef" patternsProximity="300" recommendedConfidence="85">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_japanese_my_number_personal" />
          <Match idRef="Keywords_japanese_my_number_personal" />
        </Pattern>
        <Pattern confidenceLevel="65">
          <IdMatch idRef="Func_japanese_my_number_personal" />
        </Pattern>
      </Entity>
----

=== Keywords

==== Keyword_japan_my_number_personal

* my number
* マイナンバー
* 個人番号
* 共通番号
* マイナンバーカード
* マイナンバーカード番号
* 個人番号カード
* 個人識別番号
* 個人識別ナンバー
* 通知カード
