= GitHub personal access token entity definition (preview)
:audience: Admin
:author: chrfox
:description: GitHub personal access token sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== GitHub personal access token (preview)

=== Format

A combination of 40 characters consisting of letters, digits, and special characters.

or

Paired username and password used in URL.

or

A combination of 40 characters consisting of letters and digits.

=== Pattern

* A token prefix (case-sensitive) 'ghp_', 'gho_', 'ghu_', 'ghs_', or 'ghr_'
* Any combination of 36
* a-z (not case-sensitive) or 0-9

for example:

`ghp_abcdefghijklmnopqrstuvwxyzABCD012345`

or

Various URL username and password formats for example:

`+https://username:********@contoso.com/+` +

`+ftp://username:********@contoso.com:20/+` +

or

A combination of 40 characters:

* a-f or A-F (case-sensitive) or 0-9

for example:

`abcdef0123456789abcdef0123456789abcdef01`

=== Checksum

Yes

=== Definition

This SIT is designed to match the security information that's used as an alternate password for authentication to GitHub when using https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token[GitHub API or the command line].

It uses several primary resources:

* Patterns of Identifiable GitHub PAT.
* Patterns of User Login Credentials in URL.
* Patterns of Hex encoded 160 bits Symmetric Key.
* Patterns of CredentialName, CredentialFeatures, AccountIdentityName, AccountIdentityValue, ResourceType, ResourceName.
* Patterns of mockup values, redactions, and placeholders.

The patterns are designed to match actual credentials with reasonable confidence.
The patterns don't match credentials formatted as examples.
Mockup values, redacted values, and placeholders, like credential type or usage descriptions, in the position where an actual secret value should present won't be matched.

=== Keywords

==== Keyword_GitHubPatIdentifiableSecret:

* gh_

==== Keyword_LoginCredentialsInUrl:

* ://

==== Keyword_SymmetricKey160Hex:

* token
