= Modify Exact Data Match schema to use configurable match
:audience: Admin
:author: chrfox
:description: Learn how to modify an edm schema to use configurable match.
:f1.keywords: ["NOCSH"]
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.custom: seo-marvel-apr2020
:ms.date:
:ms.localizationpriority: high
:ms.service: O365-seccomp
:ms.topic: article
:search.appverid: ["MOE150", "MET150"]

== Modify Exact Data Match schema to use configurable match

=== Applies to

* Exact data match (EDM) sensitive information type (SIT) creation using PowerShell.

Exact Data Match (EDM) based classification enables you to create custom sensitive information types that refer to exact values in a database of sensitive information.
When you need to allow for variants of an exact string, you can use _configurable match_ to tell Microsoft Purview to ignore case and some delimiters.

____
[!IMPORTANT] Use this procedure to modify an existing EDM schema and data file.
____

. Uninstall the *EdmUploadAgent.exe* from the computer that you use to connect to Microsoft 365 for EDM schema and data file upload purposes.
. Download the appropriate *EdmUploadAgent.exe* file for your subscription using the links below:
 ** https://go.microsoft.com/fwlink/?linkid=2088639[Commercial + GCC] - most commercial customers should use this
 ** https://go.microsoft.com/fwlink/?linkid=2137521[GCC-High] - This is specifically for high security government cloud subscribers
 ** https://go.microsoft.com/fwlink/?linkid=2137807[DoD] - this is specifically for United States Department of Defense cloud customers
. Authorize the EDM Upload Agent, open a Command Prompt window (as an administrator) and run the following command:
+
[,dos]
----
EdmUploadAgent.exe /Authorize
----

. If you don't have a current copy of the existing schema, you'll need to download a copy of the existing schema, run this command:
+
[,dos]
----
EdmUploadAgent.exe /SaveSchema /DataStoreName <dataStoreName> [/OutputDir [Output dir location]]
----

. Customize the schema so each column utilizes "`caseInsensitive`" and / or "`ignoredDelimiters`".
The default value for "`caseInsensitive`" is "`false`" and for "`ignoredDelimiters`", it is an empty string.
+
____
[!NOTE] The underlying custom sensitive information type or built in sensitive information type used to detect the general regex pattern must support detection of the variations inputs listed with ignoredDelimiters.
For example, the built in U.S.
social security number (SSN) sensitive information type can detect variations in the data that include dashes, spaces, or lack of spaces between the grouped numbers that make up the SSN.
As a result, the only delimiters that are relevant to include in EDM's ignoredDelimiters for SSN data are: dash and space.
____
+
Here is a sample schema that simulates case insensitive match by creating the extra columns needed to recognize case variations in the sensitive data.
+
[,xml]
----
 <EdmSchema xmlns="http://schemas.microsoft.com/office/2018/edm">
   <DataStore name="PatientRecords" description="Schema for patient records policy" version="1">
            <Field name="PolicyNumber" searchable="true" />
            <Field name="PolicyNumberLowerCase" searchable="true" />
            <Field name="PolicyNumberUpperCase" searchable="true" />
            <Field name="PolicyNumberCapitalLetters" searchable="true" />
   </DataStore>
 </EdmSchema>
----
+
In the above example, the variations of the original `PolicyNumber` column will no longer be needed if both `caseInsensitive` and `ignoredDelimiters` are added.
+
To update this schema so that EDM uses configurable match use the `caseInsensitive` and `ignoredDelimiters` flags.
Here's how that looks:
+
[,xml]
----
 <EdmSchema xmlns="http://schemas.microsoft.com/office/2018/edm">
   <DataStore name="PatientRecords" description="Schema for patient records policy" version="1">
          <Field name="PolicyNumber" searchable="true" caseInsensitive="true" ignoredDelimiters="-,/,*,#,^" />
   </DataStore>
 </EdmSchema>
----
+
The `ignoredDelimiters` flag supports any non-alphanumeric character, here are some examples:

 ** .
 ** -
 ** \/
 ** _
 ** *
 ** \{caret}
 ** #
 ** !
 ** \?
 ** [
 ** ]
 ** {
 ** }
 ** \
 ** ~
 ** \;

+
The `ignoredDelimiters` flag doesn't support:

 ** characters 0-9
 ** A-Z
 ** a-z
 ** "
 ** \,

. link:/powershell/exchange/connect-to-scc-powershell[Connect to Security & Compliance PowerShell].
+
____
[!NOTE] If your organization has set up link:customer-key-tenant-level.md#overview-of-customer-key-for-microsoft-365-at-the-tenant-level-public-preview[Customer Key for Microsoft 365 at the tenant level (public preview)], Exact data match will make use of its encryption functionality automatically.
This is available only to E5 licensed tenants in the Commercial cloud.
____

. Update your schema by running the following command:
+
[,powershell]
----
Set-DlpEdmSchema -FileData ([System.IO.File]::ReadAllBytes('.\\edm.xml')) -Confirm:$true
----

. If necessary, update the data file to match the new schema version.
+
____
[!TIP] Optionally, you can run a validation against your csv file before uploading by running:

`EdmUploadAgent.exe /ValidateData /DataFile [data file] /Schema [schema file]`

For example: `EdmUploadAgent.exe /ValidateData /DataFile  C:\data\testdelimiters.csv /Schema C:\EDM\patientrecords.xml`

For more information on all the EdmUploadAgent.exe supported parameters, run

`EdmUploadAgent.exe /?`
____

. Open Command Prompt window (as an administrator) and run the following command to hash and upload your sensitive data:
+
[,dos]
----
EdmUploadAgent.exe /UploadData /DataStoreName [DS Name] /DataFile [data file] /HashLocation [hash file location] /Salt [custom salt] /Schema [Schema file]
----

=== Related articles

* link:sit-learn-about-exact-data-match-based-sits.md#learn-about-exact-data-match-based-sensitive-information-types[Learn about exact data match based sensitive information types]
* xref:sensitive-information-type-entity-definitions.adoc[Sensitive information type-entity definitions]
* xref:./sensitive-information-type-learn-about.adoc[Custom sensitive information types]
* xref:dlp-learn-about-dlp.adoc[Learn about Microsoft Purview Data Loss Prevention]
* link:/cloud-app-security[Microsoft Defender for Cloud Apps]
* link:/powershell/module/exchange/new-dlpedmschema[New-DlpEdmSchema]
