= Taiwan national identification number entity definition
:audience: Admin
:author: chrfox
:description: Taiwan national identification number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Taiwan national identification number

=== Format

one letter (in English) followed by nine digits

=== Pattern

one letter (in English) followed by nine digits:

* one letter (in English, not case-sensitive)
* the digit "1" or "2"
* eight digits

=== Checksum

Yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_taiwanese_national_id` finds content that matches the pattern.
* A keyword from `Keyword_taiwanese_national_id` is found.
* The checksum passes.

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_taiwanese_national_id` finds content that matches the pattern.
* The checksum passes.

[,xml]
----
<!-- Taiwanese National ID -->
<Entity id="4C7BFC34-8DD1-421D-8FB7-6C6182C2AF03" patternsProximity="300" recommendedConfidence="85">
      <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_taiwanese_national_id" />
          <Match idRef="Keyword_taiwanese_national_id" />
      </Pattern>
       <Pattern confidenceLevel="75">
         <IdMatch idRef="Func_taiwanese_national_id" />
       </Pattern>
</Entity>
----

=== Keywords

==== Keyword_taiwan_national_id

* 身份證字號
* 身份證
* 身份證號碼
* 身份證號
* 身分證字號
* 身分證
* 身分證號碼
* 身份證號
* 身分證統一編號
* 國民身分證統一編號
* 簽名
* 蓋章
* 簽名或蓋章
* 簽章
