= Canada drivers license number entity definition
:audience: Admin
:author: chrfox
:description: Canada driver's license number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Canada drivers license number

=== Format

Varies by province

=== Pattern

Various patterns covering:

* Alberta
* British Columbia
* Manitoba
* New Brunswick
* Newfoundland/Labrador
* Nova Scotia
* Ontario
* Prince Edward Island
* Quebec
* Saskatchewan

=== Checksum

No

=== Definition

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_[province_name]_drivers_license_number` finds content that matches the pattern.
* A keyword from `Keyword_[province_name]_drivers_license_name` is found.
* A keyword from `Keyword_canada_drivers_license` is found.

[,xml]
----
<!-- Canada Driver's License Number -->
    <Entity id="37186abb-8e48-4800-ad3c-e3d1610b3db0" patternsProximity="300" recommendedConfidence="75">
      <Pattern confidenceLevel="75">
        <IdMatch idRef="Func_alberta_drivers_license_number" />
        <Match idRef="Keyword_alberta_drivers_license_name" />
        <Match idRef="Keyword_canada_drivers_license" />
      </Pattern>
      <Pattern confidenceLevel="75">
        <IdMatch idRef="Func_british_columbia_drivers_license_number" />
        <Match idRef="Keyword_british_columbia_drivers_license_name" />
        <Match idRef="Keyword_canada_drivers_license" />
      </Pattern>
      <Pattern confidenceLevel="75">
        <IdMatch idRef="Func_manitoba_drivers_license_number" />
        <Match idRef="Keyword_manitoba_drivers_license_name" />
        <Match idRef="Keyword_canada_drivers_license" />
      </Pattern>
      <Pattern confidenceLevel="75">
        <IdMatch idRef="Func_new_brunswick_drivers_license_number" />
        <Match idRef="Keyword_new_brunswick_drivers_license_name" />
        <Match idRef="Keyword_canada_drivers_license" />
      </Pattern>
      <Pattern confidenceLevel="75">
        <IdMatch idRef="Func_newfoundland_labrador_drivers_license_number" />
        <Match idRef="Keyword_newfoundland_labrador_drivers_license_name" />
        <Match idRef="Keyword_canada_drivers_license" />
      </Pattern>
      <Pattern confidenceLevel="75">
        <IdMatch idRef="Func_nova_scotia_drivers_license_number" />
        <Match idRef="Keyword_nova_scotia_drivers_license_name" />
        <Match idRef="Keyword_canada_drivers_license" />
      </Pattern>
      <Pattern confidenceLevel="75">
        <IdMatch idRef="Func_ontario_drivers_license_number" />
        <Match idRef="Keyword_ontario_drivers_license_name" />
        <Match idRef="Keyword_canada_drivers_license" />
      </Pattern>
      <Pattern confidenceLevel="75">
        <IdMatch idRef="Func_prince_edward_island_drivers_license_number" />
        <Match idRef="Keyword_prince_edward_island_drivers_license_name" />
        <Match idRef="Keyword_canada_drivers_license" />
      </Pattern>
      <Pattern confidenceLevel="75">
        <IdMatch idRef="Func_quebec_drivers_license_number" />
        <Match idRef="Keyword_quebec_drivers_license_name" />
        <Match idRef="Keyword_canada_drivers_license" />
      </Pattern>
      <Pattern confidenceLevel="75">
        <IdMatch idRef="Func_saskatchewan_drivers_license_number" />
        <Match idRef="Keyword_saskatchewan_drivers_license_name" />
        <Match idRef="Keyword_canada_drivers_license" />
      </Pattern>
    </Entity>
----

=== Keywords

==== Keyword_[province_name]_drivers_license_name

* The province abbreviation, for example AB
* The province name, for example Alberta

==== Keyword_canada_drivers_license

* DL
* DLS
* CDL
* CDLS
* DriverLic
* DriverLics
* DriverLicense
* DriverLicenses
* DriverLicence
* DriverLicences
* Driver Lic
* Driver Lics
* Driver License
* Driver Licenses
* Driver Licence
* Driver Licences
* DriversLic
* DriversLics
* DriversLicence
* DriversLicences
* DriversLicense
* DriversLicenses
* Drivers Lic
* Drivers Lics
* Drivers License
* Drivers Licenses
* Drivers Licence
* Drivers Licences
* Driver'Lic
* Driver'Lics
* Driver'License
* Driver'Licenses
* Driver'Licence
* Driver'Licences
* Driver' Lic
* Driver' Lics
* Driver' License
* Driver' Licenses
* Driver' Licence
* Driver' Licences
* Driver'sLic
* Driver'sLics
* Driver'sLicense
* Driver'sLicenses
* Driver'sLicence
* Driver'sLicences
* Driver's Lic
* Driver's Lics
* Driver's License
* Driver's Licenses
* Driver's Licence
* Driver's Licences
* Permis de Conduire
* id
* ids
* idcard number
* idcard numbers
* idcard #
* idcard #s
* idcard card
* idcard cards
* idcard
* identification number
* identification numbers
* identification #
* identification #s
* identification card
* identification cards
* identification
* DL#
* DLS#
* CDL#
* CDLS#
* DriverLic#
* DriverLics#
* DriverLicense#
* DriverLicenses#
* DriverLicence#
* DriverLicences#
* Driver Lic#
* Driver Lics#
* Driver License#
* Driver Licenses#
* Driver License#
* Driver Licences#
* DriversLic#
* DriversLics#
* DriversLicense#
* DriversLicenses#
* DriversLicence#
* DriversLicences#
* Drivers Lic#
* Drivers Lics#
* Drivers License#
* Drivers Licenses#
* Drivers Licence#
* Drivers Licences#
* Driver'Lic#
* Driver'Lics#
* Driver'License#
* Driver'Licenses#
* Driver'Licence#
* Driver'Licences#
* Driver' Lic#
* Driver' Lics#
* Driver' License#
* Driver' Licenses#
* Driver' Licence#
* Driver' Licences#
* Driver'sLic#
* Driver'sLics#
* Driver'sLicense#
* Driver'sLicenses#
* Driver'sLicence#
* Driver'sLicences#
* Driver's Lic#
* Driver's Lics#
* Driver's License#
* Driver's Licenses#
* Driver's Licence#
* Driver's Licences#
* Permis de Conduire#
* id#
* ids#
* idcard card#
* idcard cards#
* idcard#
* identification card#
* identification cards#
* identification#
