= Finland passport number entity definition
:audience: Admin
:author: chrfox
:description: Finland passport number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Finland passport number

This entity is available in the EU Passport Number sensitive information type and is available as a stand-alone sensitive information type entity.

=== Format

combination of nine letters and digits

=== Pattern

combination of nine letters and digits:

* two letters (not case-sensitive)
* seven digits

=== Checksum

No

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The regular expression `Regex_finland_passport_number` finds content that matches the pattern.
* A keyword from `Keywords_eu_passport_number` or `Keyword_finland_passport_number` is found.
* The regular expression `Regex_eu_passport_date1` finds date in the format DD.MM.YYYY or a keyword from `Keywords_eu_passport_date` is found

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The regular expression `Regex_finland_passport_number` finds content that matches the pattern.
* A keyword from `Keywords_eu_passport_number` or `Keyword_finland_passport_number` is found.

[,xml]
----
      <!-- Finland Passport Number -->
      <Entity id="d1685ac3-1d3a-40f8-8198-32ef5669c7a5" patternsProximity="300" recommendedConfidence="75">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Regex_finland_passport_number" />
          <Any minMatches="1">
            <Match idRef="Keywords_eu_passport_number" />
            <Match idRef="Keyword_finland_passport_number" />
          </Any>
          <Any minMatches="1">
            <Match idRef="Regex_eu_passport_date1" />
            <Match idRef="Keywords_eu_passport_date" />
          </Any>
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Regex_finland_passport_number" />
          <Any minMatches="1">
            <Match idRef="Keywords_eu_passport_number" />
            <Match idRef="Keyword_finland_passport_number" />
          </Any>
        </Pattern>
      </Entity>
----

=== Keywords

==== Keywords_eu_passport_number

* passport#
* passport #
* passportid
* passports
* passportno
* passport no
* passportnumber
* passport number
* passportnumbers
* passport numbers

==== Keyword_finland_passport_number

* suomalainen passi
* passin numero
* passin numero.#
* passin numero#
* passin numero.
* passi#
* passi number

==== Keywords_eu_passport_date

* date of issue
* date of expiry
