= New Zealand inland revenue number entity definition
:audience: Admin
:author: chrfox
:description: New Zealand inland revenue number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== New Zealand inland revenue number

=== Format

eight or nine digits with optional delimiters

=== Pattern

eight or nine digits with optional delimiters

* two or three digits
* an optional space or hyphen
* three digits
* an optional space or hyphen
* three digits

=== Checksum

Yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_new_zealand_inland_revenue_number` finds content that matches the pattern.
* A keyword from `Keywords_new_zealand_inland_revenue_number` is found.

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_new_zealand_inland_revenue_number` finds content that matches the pattern.

[,xml]
----
      <!-- New Zealand Inland Revenue Number -->
      <Entity id="dd0fe2bc-7bcf-455f-bac1-83b1e3eb25fd" patternsProximity="300" recommendedConfidence="85">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_new_zealand_inland_revenue_number" />
          <Match idRef="Keywords_new_zealand_inland_revenue_number" />
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Func_new_zealand_inland_revenue_number" />
        </Pattern>
      </Entity>
----

=== Keywords

==== Keyword_new_zealand_inland_revenue_number

* ird no.
* ird no#
* nz ird
* new zealand ird
* ird number
* inland revenue number
