= General Symmetric key entity definition (preview)
:audience: Admin
:author: chrfox
:description: General Symmetric key sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== General Symmetric key (preview)

=== Format

A combination of 44 characters consisting of letters, digits, and special characters.

or

A combination of 88 characters consisting of letters, digits, and special characters.

=== Pattern

A combination of 43 characters:

* a-z (not case-sensitive)
* 0-9
* forward slashes (/) or plus signs (+)
* ends with an equal sign (=)

for example:

`abcdefghijklmnopqrstuvwxyz0123456789/+ABCDE=`

or

A combination of 86 characters:

* a-z (not case-sensitive)
* 0-9
* forward slashes (/) or plus signs (+)
* ends with two equal signs (=)

for example:

`abcdefghijklmnopqrstuvwxyz0123456789/+ABCDEabcdefghijklmnopqrstuvwxyz0123456789/+ABCDE==`

=== Checksum

No

=== Definition

This SIT is designed to match the security information that's used in link:/dotnet/api/system.security.cryptography.aes?view=net-5.0[general authentication process.]

It uses several primary resources:

* Patterns of Base64 encoded 256 bits symmetric key.
* Patterns of Base64 encoded 512 bits symmetric key.
* Patterns of CredentialName, CredentialFeatures, AccountIdentityName, AccountIdentityValue, ResourceType, ResourceName, Id, AccountName.
* Patterns of mockup values, redactions, and placeholders.
* A dictionary of vocabulary.

The patterns are designed to match actual credentials with reasonable confidence.
The patterns don't match credentials formatted as examples.
Mockup values, redacted values, and placeholders, like credential type or usage descriptions, in the position where an actual secret value should present won't be matched.

=== Keywords

==== Keyword_SymmetricKey256:

* SharedAccessKey
* AccountKey

==== Keyword_SymmetricKey512:

* SharedAccessKey
* AccountKey
