= Austria tax identification number entity definition
:audience: Admin
:author: chrfox
:description: Austria tax identification number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Austria tax identification number

=== Format

nine digits with optional hyphen and forward slash

=== Pattern

nine digits with optional hyphen and forward slash:

* two digits
* a hyphen (optional)
* three digits
* a forward slash (optional)
* four digits

=== Checksum

Yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_austria_eu_tax_file_number` finds content that matches the pattern.
* A keyword from `Keywords_austria_eu_tax_file_number` is found.

A DLP policy has low confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_austria_eu_tax_file_number` finds content that matches the pattern.

[,xml]
----
      <!-- Austria Tax Identification Number -->
      <Entity id="4fd58d22-af28-4451-b18a-6f722430a56d" patternsProximity="300" recommendedConfidence="85">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_austria_eu_tax_file_number" />
          <Match idRef="Keywords_austria_eu_tax_file_number" />
        </Pattern>
        <Pattern confidenceLevel="65">
          <IdMatch idRef="Func_austria_eu_tax_file_number" />
        </Pattern>
      </Entity>
----

=== Keywords

==== Keywords_austria_eu_tax_file_number

* österreich
* st.nr.
* steuernummer
* tax ID
* tax identification no
* tax identification number
* tax no#
* tax no
* tax number
* tax registration number
* taxid#
* taxidno#
* taxidnumber#
* taxno#
* taxnumber#
* taxnumber
* tin ID
* tin no
* tin#
* tax number
