= Austria value added tax entity definition
:audience: Admin
:author: chrfox
:description: Austria value added tax sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Austria value added tax

=== Format

11-character alphanumeric pattern

=== Pattern

11-character alphanumeric pattern:

* A or a
* T or t
* Optional space
* U or u
* optional space
* two or three digits
* optional space
* four digits
* optional space
* one or two digits

=== Checksum

Yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function Func_Austria_Value_Added_Tax finds content that matches the pattern.
* A keyword from Keyword_Austria_Value_Added_Tax is found.

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function Func_Austria_Value_Added_Tax finds content that matches the pattern.

[,xml]
----
      <!-- Austria Value Added Tax -->
      <Entity id="b6a3eda2-c56c-4b69-a5f7-dca34db00f48" patternsProximity="300" recommendedConfidence="85">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_Austria_Value_Added_Tax" />
          <Match idRef="Keyword_Austria_Value_Added_Tax" />
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Func_Austria_Value_Added_Tax" />
        </Pattern>
      </Entity>
----

=== Keywords

==== Keyword_austria_value_added_tax

* vat number
* vat#
* austrian vat number
* vat no.
* vatno#
* value added tax number
* austrian vat
* mwst
* umsatzsteuernummer
* mwstnummer
* ust.-identifikationsnummer
* umsatzsteuer-identifikationsnummer
* vat identification number
* atu number
* uid number
