= Azure Bot Framework secret key entity definition (preview)
:audience: Admin
:author: chrfox
:description: Azure Bot Framework secret key sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Azure Bot Framework secret key (preview)

=== Format

A combination of 55 characters consisting of letters, digits, and special characters.

or

A combination of 63 characters consisting of letters, digits, and special characters.

=== Pattern

A combination of 55 characters:

* a-z (not case-sensitive)
* 0-9
* underlines (_)
* or dots (.)

`abcdefghijklmnopqrstuvwxyz.0123456789_ABCDEabcdefghijkl`

or for the 63 characters

A combination of 11 characters:

* a-z (not case-sensitive)
* 0-9
* dashes (-)
* or underlines (_)
* a dot

A combination of 3 characters:

* a-z (not case-sensitive)
* 0-9
* dashes (-)
* or underlines (_)
* a dot

A combination of 3 characters:

* a-z (not case-sensitive)
* 0-9
* dashes (-)
* or underlines (_)
* a dot

A combination of 43 characters

* a-z (not case-sensitive)
* 0-9
* dashes (-)
* or underlines (_)

for example:

`abcdefghijk.lmn.opq.rstuvwxyz0123456789-_ABCDEFGHIJKLMNOPQRSTUV`

=== Checksum

No

=== Definition

This SIT is designed to match the security information that's used to connect to link:/azure/bot-service/bot-service-channel-connect-webchat?view=azure-bot-service-4.0[WebChat channels from Azure Bot services.]

It uses several primary resources:

* Patterns of Base64 URL encoded 328 bits symmetric key.
* Patterns of Base64 URL encoded 360 bits symmetric key.
* Patterns of CredentialName, CredentialFeatures, AccountIdentityName, AccountIdentityValue, ResourceType, ResourceName.
* Patterns of mockup values, redactions, and placeholders.
* A dictionary of vocabulary.

The patterns are designed to match actual credentials with reasonable confidence.
The patterns do not match credentials formatted as examples.
Mockup values, redacted values, and placeholders, like credential type or usage descriptions, in the position where an actual secret value should present will not be matched.

=== Keywords

==== Keyword_SymmetricKey328Url:

* botframework
* key

==== Keyword_SymmetricKey360Url:

* botframework
* key
