= Malta passport number entity definition
:audience: Admin
:author: chrfox
:description: Malta passport number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Malta passport number

=== Format

seven digits without spaces or delimiters

=== Pattern

seven digits

=== Checksum

No

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The regular expression `Regex_malta_eu_passport_number` finds content that matches the pattern.
* A keyword from `Keywords_eu_passport_number` or `Keywords_malta_eu_passport_number` is found.
* A keyword from `Keywords_eu_passport_date` is found

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The regular expression `Regex_malta_eu_passport_number` finds content that matches the pattern.
* A keyword from `Keywords_eu_passport_number` or `Keywords_malta_eu_passport_number` is found.

[,xml]
----
      <!-- Malta Passport Number -->
      <Entity id="b2b21198-48f9-4d13-b2a5-03969bff0fb8" patternsProximity="300" recommendedConfidence="75">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Regex_malta_eu_passport_number" />
          <Any minMatches="1">
            <Match idRef="Keywords_eu_passport_number" />
            <Match idRef="Keywords_malta_eu_passport_number" />
          </Any>
          <Match idRef="Keywords_eu_passport_date" />
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Regex_malta_eu_passport_number" />
          <Any minMatches="1">
            <Match idRef="Keywords_eu_passport_number" />
            <Match idRef="Keywords_malta_eu_passport_number" />
          </Any>
        </Pattern>
      </Entity>
----

=== Keywords

==== Keywords_eu_passport_number

* passport#
* passport #
* passportid
* passports
* passportno
* passport no
* passportnumber
* passport number
* passportnumbers
* passport numbers

==== Keywords_malta_eu_passport_number

* numru tal-passaport
* numri tal-passaport
* Nru tal-passaport

==== Keywords_eu_passport_date

* date of issue
* date of expiry
