= Hungary value added tax number entity definition
:audience: Admin
:author: chrfox
:description: Hungary value added tax number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Hungary value added tax number

=== Format

10 character alphanumeric pattern

=== Pattern

10 character alphanumeric pattern:

* two letters - HU or hu
* optional space
* eight digits

=== Checksum

Yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_hungarian_value_added_tax_number` finds content that matches the pattern.
* A keyword from `Keywords_hungarian_value_added_tax_number` is found.

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_hungarian_value_added_tax_number` finds content that matches the pattern.

[,xml]
----
      <!-- Hungarian Value Added Tax Number -->
      <Entity id="976349a0-683b-477a-90f8-ff0a220d5592" patternsProximity="300" recommendedConfidence="85">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_hungarian_value_added_tax_number" />
          <Match idRef="Keywords_hungarian_value_added_tax_number" />
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Func_hungarian_value_added_tax_number" />
        </Pattern>
      </Entity>
----

=== Keywords

==== Keyword_Hungary_value_added_tax_number

* vat
* value added tax number
* vat#
* vatno#
* hungarianvatno#
* tax no.
* value added tax áfa
* közösségi adószám
* általános forgalmi adó szám
* hozzáadottérték adó
* áfa szám
