= Australia passport number entity definition
:audience: Admin
:author: chrfox
:description: Australia passport number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Australia passport number

=== Format

eight or nine alphanumeric characters

=== Pattern

* one letter (N, E, D, F, A, C, U, X) followed by seven digits or
* Two letters (PA, PB, PC, PD, PE, PF, PU, PW, PX, PZ) followed by seven digits.

=== Checksum

No

=== Definition

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The regular expression `Regex_australia_passport_number` finds content that matches the pattern.
* A keyword from `Keyword_australia_passport_number` is found.

A DLP policy has low confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The regular expression `Regex_australia_passport_number` finds content that matches the pattern.

[,xml]
----
    <!-- Australia Passport Number -->
    <Entity id="29869db6-602d-4853-ab93-3484f905df50" patternsProximity="300" recommendedConfidence="75" relaxProximity="true">
      <Pattern confidenceLevel="75">
        <IdMatch idRef="Regex_australia_passport_number" />
        <Match idRef="Keyword_australia_passport_number" />
      </Pattern>
      <Pattern confidenceLevel="65">
        <IdMatch idRef="Regex_australia_passport_number" />
      </Pattern>
    </Entity>
----

=== Keywords

==== Keyword_australia_passport_number

* passport#
* passport #
* passportid
* passports
* passportno
* passport no
* passportnumber
* passport number
* passportnumbers
* passport numbers
* passport details
* immigration and citizenship
* commonwealth of australia
* department of immigration
* national identity card
* travel document
* issuing authority
