= France value added tax number entity definition
:audience: Admin
:author: chrfox
:description: France value added tax number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== France value added tax number

=== Format

13 character alphanumeric pattern

=== Pattern

13 character alphanumeric pattern:

* two letters  - FR (case insensitive)
* an optional space or hyphen
* two letters or digits
* an optional space, dot, hyphen, or comma
* three digits
* an optional space, dot, hyphen, or comma
* three digits
* an optional space, dot, hyphen, or comma
* three digits

=== Checksum

Yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_france_value_added_tax_number` finds content that matches the pattern.
* A keyword from `Keywords_france_value_added_tax_number` is found.

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_france_value_added_tax_number` finds content that matches the pattern.

[,xml]
----
      <!-- France Value Added Tax Number -->
      <Entity id="949121e6-ad9f-4379-8731-710342baea78" patternsProximity="300" recommendedConfidence="85">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_france_value_added_tax_number" />
          <Match idRef="Keywords_france_value_added_tax_number" />
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Func_france_value_added_tax_number" />
        </Pattern>
      </Entity>
----

=== Keywords

==== Keyword_France_value_added_tax_number

* vat number
* vat no
* vat#
* value added tax
* siren identification no numéro d'identification taxe sur valeur ajoutée
* taxe valeur ajoutée
* taxe sur la valeur ajoutée
* n° tva
* numéro de tva
* numéro d'identification siren
