= France passport number entity definition
:audience: Admin
:author: chrfox
:description: France passport number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== France passport number

This entity is available in the EU Passport Number sensitive information type.
It's also available as a stand-alone sensitive information type entity.

=== Format

nine digits and letters

=== Pattern

nine digits and letters:

* two digits
* two letters (not case-sensitive)
* five digits

=== Checksum

No

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_fr_passport` finds content that matches the pattern.
* A keyword from `Keywords_eu_passport_number` or `Keywords_france_eu_passport_number` is found.
* The regular expression `Regex_eu_passport_date3` finds date in the format DD MM YYYY or a keyword from `Keywords_eu_passport_date` is found

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_fr_passport` finds content that matches the pattern.
* A keyword from `Keywords_eu_passport_number` or `Keywords_france_eu_passport_number` is found.

[,xml]
----
    <!-- France Passport Number -->
    <Entity id="3008b884-8c8c-4cd8-a289-99f34fc7ff5d" patternsProximity="300" recommendedConfidence="75">
      <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_fr_passport" />
          <Any minMatches="1">
            <Match idRef="Keywords_eu_passport_number" />
            <Match idRef="Keywords_france_eu_passport_number" />
          </Any>
          <Any minMatches="1">
            <Match idRef="Regex_eu_passport_date3" />
            <Match idRef="Keywords_eu_passport_date" />
          </Any>
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Func_fr_passport" />
          <Any minMatches="1">
            <Match idRef="Keywords_eu_passport_number" />
            <Match idRef="Keywords_france_eu_passport_number" />
          </Any>
        </Pattern>
    </Entity>
----

=== Keywords

==== Keywords_eu_passport_number

* passport#
* passport #
* passportid
* passports
* passportno
* passport no
* passportnumber
* passport number
* passportnumbers
* passport numbers

==== Keywords_france_eu_passport_number

* numéro de passeport
* passeport n °
* passeport non
* passeport #
* passeport#
* passeportnon
* passeportn °
* passeport français
* passeport livre
* passeport carte
* numéro passeport
* passeport n°
* n° du passeport
* n° passeport

==== Keywords_eu_passport_date

* date of issue
* date of expiry
