= Austria social security number entity definition
:audience: Admin
:author: chrfox
:description: Austria social security number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Austria social security number

=== Format

10 digits in the specified format

=== Pattern

10 digits:

* three digits that correspond to a serial number
* one check digit
* six digits that correspond to the birth date (DDMMYY)

=== Checksum

Yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_austria_eu_ssn_or_equivalent` finds content that matches the pattern.
* a keyword from `Keywords_austria_eu_ssn_or_equivalent` is found.

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_austria_eu_ssn_or_equivalent` finds content that matches the pattern.

[,xml]
----
      <!-- Austria Social Security Number -->
      <Entity id="6896a906-86c9-4d19-a2da-6e43ccd19b7b" patternsProximity="300" recommendedConfidence="85">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_austria_eu_ssn_or_equivalent" />
          <Match idRef="Keywords_austria_eu_ssn_or_equivalent" />
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Func_austria_eu_ssn_or_equivalent" />
          <Any minMatches="0" maxMatches="0">
            <Match idRef="Keywords_austria_eu_telephone_number" />
            <Match idRef="Keywords_austria_eu_mobile_number" />
          </Any>
        </Pattern>
      </Entity>
----

=== Keywords

==== Keywords_austria_eu_ssn_or_equivalent

* austrian ssn
* ehic number
* ehic no
* insurance code
* insurancecode#
* insurance number
* insurance no
* krankenkassennummer
* krankenversicherung
* socialsecurityno
* socialsecurityno#
* social security no
* social security number
* social security code
* sozialversicherungsnummer
* sozialversicherungsnummer#
* soziale sicherheit kein
* sozialesicherheitkein#
* ssn#
* ssn
* versicherungscode
* versicherungsnummer
* zdravstveno zavarovanje
