= Greece Social Security Number (AMKA) entity definition
:audience: Admin
:author: chrfox
:description: Greece Social Security Number (AMKA) sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Greece Social Security Number (AMKA)

=== Format

11 digits without spaces and delimiters

=== Pattern

* Six digits as date of birth YYMMDD
* Four digits
* a check digit

=== Checksum

Yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_greece_eu_ssn` finds content that matches the pattern.
* A keyword from `Keywords_greece_eu_ssn_or_equivalent` is found.

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_greece_eu_ssn` finds content that matches the pattern.

[,xml]
----
      <!-- Greece Social Security Number (AMKA) -->
      <Entity id="e39b03f4-50ea-41ae-af7a-a4b9539596ad" patternsProximity="300" recommendedConfidence="85">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_greece_eu_ssn" />
          <Match idRef="Keywords_greece_eu_ssn_or_equivalent" />
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Func_greece_eu_ssn" />
        </Pattern>
      </Entity>
----

=== Keywords

==== Keywords_greece_eu_ssn_or_equivalent

* ssn
* ssn#
* social security no
* socialsecurityno#
* social security number
* amka
* a.m.k.a.
* Αριθμού Μητρώου Κοινωνικής Ασφάλισης
