= International classification of diseases (ICD-9-CM) entity definition
:audience: Admin
:author: chrfox
:description: International classification of diseases (ICD-9-CM) sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== International classification of diseases (ICD-9-CM)

=== Format

Dictionary

=== Pattern

Keyword

=== Checksum

No

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* A keyword from `Dictionary_icd_9_updated` is found.
* A keyword from `Dictionary_icd_9_codes` is found.

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* A keyword from `Dictionary_icd_9_updated` is found.

[,xml]
----
    <Entity id="fa3f9c74-ee07-4c52-b5f2-085d6b2c0ec4" patternsProximity="300" recommendedConfidence="85">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Dictionary_icd_9_updated" />
          <Match idRef="Dictionary_icd_9_codes" />
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Dictionary_icd_9_updated" />
        </Pattern>
      </Entity>
----

=== Keywords

Any term from the `Dictionary_icd_9_updated` keyword dictionary, which is based on the https://go.microsoft.com/fwlink/?linkid=852605[International Classification of Diseases,Ninth Revision, Clinical Modification (ICD-9-CM)].
This type looks only for the term, not the insurance codes.

Any term from the `Dictionary_icd_9_codes` keyword dictionary, which is based on the https://go.microsoft.com/fwlink/?linkid=852605[International Classification of Diseases,Ninth Revision, Clinical Modification (ICD-9-CM)].
This type looks only for insurance codes, not the description.
