= Belgium value added tax number entity definition
:audience: Admin
:author: chrfox
:description: Belgium value added tax number sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Belgium value added tax number

=== Format

12-character alphanumeric pattern

=== Pattern

12-character alphanumeric pattern:

* a letter B or b
* a letter E or e
* a digit 0
* a digit from 1 to 9
* an optional dot or Hyphen or space
* four digits
* an optional dot or Hyphen or space
* four digits

=== Checksum

Yes

=== Definition

A DLP policy has high confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_belgium_value_added_tax_number` finds content that matches the pattern.
* A keyword from `Keywords_belgium_value_added_tax_number` is found.

A DLP policy has medium confidence that it's detected this type of sensitive information if, within a proximity of 300 characters:

* The function `Func_belgium_value_added_tax_number` finds content that matches the pattern.

[,xml]
----
      <!-- Belgium Value Added Tax Number -->
      <Entity id="85b5b3c3-f2de-4ae8-ac46-fd3cb38bf9ed" patternsProximity="300" recommendedConfidence="85">
        <Pattern confidenceLevel="85">
          <IdMatch idRef="Func_belgium_value_added_tax_number" />
          <Match idRef="Keywords_belgium_value_added_tax_number" />
        </Pattern>
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Func_belgium_value_added_tax_number" />
        </Pattern>
      </Entity>
    </Version>
----

=== Keywords

==== Keyword_belgium_value_added_tax_number

* nº tva
* vat number
* vat no
* numéro t.v.a
* umsatzsteuer-identifikationsnummer
* umsatzsteuernummer
* btw
* btw#
* vat#
