= Azure subscription management certificate entity definition (preview)
:audience: Admin
:author: chrfox
:description: Azure subscription management certificate sensitive information type entity definition.
:f1.keywords: ["CSH"]
:f1_keywords: ["ms.o365.cc.UnifiedDLPRuleContainsSensitiveInformation"]
:feedback_system: None
:hideEdit: true
:manager: laurawi
:ms.author: chrfox
:ms.collection: ["M365-security-compliance"]
:ms.date:
:ms.localizationpriority: medium
:ms.service: O365-seccomp
:ms.topic: reference
:recommendations: false
:search.appverid: MET150

== Azure subscription management certificate (preview)

=== Format

A combination of up to 20,000 characters consisting of letters, digits, and special characters.

=== Pattern

A combination of up to 20,000 characters:

* a-z (not case-sensitive)
* 0-9
* forward slash (/) or plus sign (+)
* Up to two equals signs (==)

for example:

`MIIKcQIBAzCCCi0GCSqGSIb3DQEHAaCCCh4EggoaMIIKFjCCBg8GCSqGSIb3DQEHAaCCBgAEggX8MIIF+DCCBfQGCyqGSIb3DQEM`

=== Checksum

Yes

=== Definition

This SIT is designed to match the security information that's used to authenticate with the link:/azure/azure-resource-manager/management/deployment-models[classic deployment model] provided by Azure.
Many programs and tools, like Visual Studio or the Azure SDK, use these certificates to automate configuration and deployment of various link:/azure/azure-api-management-certs[Azure services].

It uses several primary resources:

* Patterns of Base64 encoded string literal.
* Patterns of CredentialName, CredentialFeatures, AccountIdentityName, AccountIdentityValue, ResourceType, ResourceName.

The patterns are designed to match actual credentials with reasonable confidence.
The patterns don't match credentials formatted as examples.
Mockup values, redacted values, and placeholders, like credential type or usage descriptions, in the position where an actual secret value should present won't be matched.

=== Keywords

==== Keyword_Base64EncodedStringLiteral:

* MII
