= Manage device access settings in Basic Mobility and Security
:audience: Admin
:author: kwekua
:description: For devices you can't manage with Basic Mobility and Security, block Exchange ActiveSync app access to email and use Azure AD PowerShell to get details about org devices.
:f1.keywords: ["NOCSH"]
:manager: scotv
:ms.author: kwekua
:ms.collection: ["M365-subscription-management", "Adm_O365", "Adm_TOC"]
:ms.custom: ["AdminSurgePortfolio"]
:ms.localizationpriority: medium
:ms.service: o365-administration
:ms.topic: article
:search.appverid: ["MET150"]

== Manage device access settings in Basic Mobility and Security

If you're using Basic Mobility and Security, there might be devices that you can't manage with Basic Mobility and Security.
If so, you should block Exchange ActiveSync app access to Microsoft 365 email for mobile devices that aren't supported by Basic Mobility and Security.
This helps secure your organization information across more devices.

Use these steps:

. Sign in to Microsoft 365 with your global admin account.
. In your browser, type: https://protection.office.com/.
+
____
[!IMPORTANT] If this is the first time you're using Basic Mobility and Security for Microsoft 365 Business Standard, activate it here: https://admin.microsoft.com/EAdmin/Device/IntuneInventory.aspx[Activate Basic Security and Mobility].
After you've activated it, manage your devices with https://protection.office.com/[Office 365 Security & Compliance].
____

. Go to *Data loss prevention* > *Device management* > *Device policies*, and select *Manage organization-wide device access settings*.
. Select *Access*.
+
:::image type="content" source="../../media/basic-mobility-security/basic-mobility-access.png" alt-text="Basic Mobility and Security block access checkbox.":::

. Select *Save*.

To learn what devices Basic Mobility and Security supports, see xref:capabilities.adoc[Capabilities of Basic Mobility and Security].

=== Get details about Basic Mobility and Security managed devices

Additionally, you can use Azure AD PowerShell to get details about the devices in your organization that you set up for Basic Mobility and Security.

Here's a breakdown for the device details available to you.

|===
| Detail | What to look for in PowerShell

| Device is enrolled in Basic Mobility and Security.
For more info, see xref:enroll-your-mobile-device.adoc[Enroll your mobile device using Basic Mobility and Security]
| The value of the _isManaged_ parameter is: + *True*= device is enrolled.
+ *False*= device is not enrolled.

| Device is compliant with your device security policies.
For more info, see xref:create-device-security-policies.adoc[Create device security policies]
| The value of the _isCompliant_ parameter is: + *True* = device is compliant with policies.
+ *False* = device is not compliant with policies.
|===

:::image type="content" source="../../media/basic-mobility-security/bms-7-powershell-parameters.png" alt-text="Basic Mobility and Security PowerShell parameters.":::

____
[!NOTE] The commands and scripts that follow also return details about any devices managed by https://www.microsoft.com/cloud-platform/microsoft-intune[Microsoft Intune].
____

Here are a few things you need to set up to run the commands and scripts that follow:

==== Step 1: Download and install the Azure Active Directory Module for Windows PowerShell

For more info on these steps, see link:/office365/enterprise/powershell/connect-to-office-365-powershell[Connect to Microsoft 365 with PowerShell].

. Go to https://download.microsoft.com/download/7/1/E/71EF1D05-A42C-4A1F-8162-96494B5E615C/msoidcli_32bit.msi[Microsoft Online Services Sign-In Assistant for IT Professionals RTWl] and select *Download for Microsoft Online Services Sign-in Assistant*.
. Install the Microsoft Azure Active Directory Module for Windows PowerShell with these steps:
 .. Open an administrator-level PowerShell command prompt.
 .. Run the `Install-Module MSOnline` command.
 .. If prompted to install the NuGet provider, type Y and press ENTER.
 .. If prompted to install the module from PSGallery, type Y and press ENTER.
 .. After installation, close the PowerShell command window.

==== Step 2: Connect to your Microsoft 365 subscription

. In the Windows Azure Active Directory Module for Windows PowerShell, run the following command.
+
[,powershell]
----
$UserCredential = Get-Credential
----

. In the Windows PowerShell Credential Request dialog box, type the user name and password for your Microsoft 365 global admin account, and then select *OK*.
. Run the following command.
+
[,powershell]
----
Connect-MsolService -Credential $UserCredential
----

==== Step 3: Make sure you're able to run PowerShell scripts

____
[!NOTE] You can skip this step if you're already set up to run PowerShell scripts.
____

To run the Get-MsolUserDeviceComplianceStatus.ps1 script, you need to enable the running of PowerShell scripts.

. From your Windows Desktop, select *Start*, and then type Windows PowerShell.
Right-click Windows PowerShell, and then select *Run as administrator*.
. Run the following command.
+
[,powershell]
----
Set-ExecutionPolicy RemoteSigned
----

. When prompted, type Y and then press Enter.

===== Run the Get-MsolDevice cmdlet to display details for all devices in your organization

. Open the Microsoft Azure Active Directory Module for Windows PowerShell.
. Run the following command.
+
[,powershell]
----
Get-MsolDevice -All -ReturnRegisteredOwners | Where-Object {$_.RegisteredOwners.Count -gt 0}
----

For more examples, see https://go.microsoft.com/fwlink/?linkid=2157939[Get-MsolDevice].

==== Run a script to get device details

First, save the script to your computer.

. Copy and paste the following text into Notepad.
+
[,powershell]
----
param (
[PSObject[]]$users = @(),
[Switch]$export,
[String]$exportFileName = "UserDeviceComplianceStatus_" + (Get-Date -Format "yyMMdd_HHMMss") + ".csv",
[String]$exportPath = [Environment]::GetFolderPath("Desktop")
)
[System.Collections.IDictionary]$script:schema = @{
DeviceId = ''
DeviceOSType = ''
DeviceOSVersion = ''
DeviceTrustLevel = ''
DisplayName = ''
IsCompliant = ''
IsManaged = ''
ApproximateLastLogonTimestamp = ''
DeviceObjectId = ''
RegisteredOwnerUpn = ''
RegisteredOwnerObjectId = ''
RegisteredOwnerDisplayName = ''
}
function createResultObject
{
[PSObject]$resultObject = New-Object -TypeName PSObject -Property $script:schema
return $resultObject
}
If ($users.Count -eq 0)
{
$users = Get-MsolUser
}
[PSObject[]]$result = foreach ($u in $users)
{
[PSObject]$devices = get-msoldevice -RegisteredOwnerUpn $u.UserPrincipalName
foreach ($d in $devices)
{
[PSObject]$deviceResult = createResultObject
$deviceResult.DeviceId = $d.DeviceId
$deviceResult.DeviceOSType = $d.DeviceOSType
$deviceResult.DeviceOSVersion = $d.DeviceOSVersion
$deviceResult.DeviceTrustLevel = $d.DeviceTrustLevel
$deviceResult.DisplayName = $d.DisplayName
$deviceResult.IsCompliant = $d.GraphDeviceObject.IsCompliant
$deviceResult.IsManaged = $d.GraphDeviceObject.IsManaged
$deviceResult.DeviceObjectId = $d.ObjectId
$deviceResult.RegisteredOwnerUpn = $u.UserPrincipalName
$deviceResult.RegisteredOwnerObjectId = $u.ObjectId
$deviceResult.RegisteredOwnerDisplayName = $u.DisplayName
$deviceResult.ApproximateLastLogonTimestamp = $d.ApproximateLastLogonTimestamp
$deviceResult
}
}
If ($export)
{
$result | Export-Csv -path ($exportPath + "\" + $exportFileName) -NoTypeInformation
}
Else
{
$result
}
----

. Save it as a Windows PowerShell script file by using the file extension .ps1;
for example, Get-MsolUserDeviceComplianceStatus.ps1.

==== Run the script to get device information for a single user account

. Open the Microsoft Azure Active Directory Module for Windows PowerShell.
. Go to the folder where you saved the script.
For example, if you saved it to C:\PS-Scripts, run the following command.
+
[,powershell]
----
cd C:\PS-Scripts
----

. Run the following command to identify the user you want to get device details for.
This example gets details for bar@example.com.
+
[,powershell]
----
$u = Get-MsolUser -UserPrincipalName bar@example.com
----

. Run the following command to initiate the script.
+
[,powershell]
----
.\Get-MsolUserDeviceComplianceStatus.ps1 -User $u -Export
----

The information is exported to your Windows Desktop as a CSV file.
You can use additional parameters to specify the file name and path of the CSV.

==== Run the script to get device information for a group of users

. Open the Microsoft Azure Active Directory Module for Windows PowerShell.
. Go to the folder where you saved the script.
For example, if you saved it to C:\PS-Scripts, run the following command.
+
[,powershell]
----
cd C:\PS-Scripts
----

. Run the following command to identify the group you want to get device details for.
This example gets details for users in the FinanceStaff group.
+
[,powershell]
----
$u = Get-MsolGroupMember -SearchString "FinanceStaff" | % { Get-MsolUser -ObjectId $_.ObjectId }
----

. Run the following command to initiate the script.
+
[,powershell]
----
.\Get-MsolUserDeviceComplianceStatus.ps1 -User $u -Export
----

The information is exported to your Windows Desktop as a CSV file.
You can use additional parameters to specify the file name and path of the CSV.

=== Related content

link:/collaborate/connect-redirect[Microsoft Connect Has Been Retired]

xref:overview.adoc[Overview of Basic Mobility and Security]

https://go.microsoft.com/fwlink/?linkid=2157939[Get-MsolDevice]
